### ISSUE TITLE
Interface: Query execution fails for Array of ObjectTypes unless other query defined for single same ObjectType

### ISSUE THREAD

**Issue by Yoshiji** [rmosolgo/graphql-ruby#1001]
Hello,

For some reason, a query is not working for an expected list from an Interface, unless you define another field on the Query with the type using this Interface... It probably does not make sense, see the example below:

I can reproduce this error with the [`graphql-ruby-demo`](https://github.com/rmosolgo/graphql-ruby-demo) app. Just replace the content of [`query_type.rb`](https://github.com/rmosolgo/graphql-ruby-demo/blob/master/app/graph/types/query_type.rb) with the following:

```
module Types
  QueryType = GraphQL::ObjectType.define do
    name "Query"
    description "The query root for this schema"

    field :heros do
      type types[CharacterInterface]
      resolve -> (obj, args, ctx) { Human.limit(5) }
    end

    # un-comment the following and the query { heros { id } } will magically works
    # field :human_hero do
    #   type HumanType
    #   resolve -> { Human.first }
    # end
  end
end
```

Start your server, try the `{ heros { id } }` query and you will end up with the following server error:

```
GraphQL::UnresolvedTypeError - The value from "heros" on "Query" could not be resolved to "[Character]". (Received: Human, Expected: []):
  graphql (1.4.1) lib/graphql/schema/default_type_error.rb:10:in 'call'
  graphql (1.4.1) lib/graphql/schema.rb:311:in 'type_error'
  graphql (1.4.1) lib/graphql/execution/execute.rb:183:in 'resolve_value'
  graphql (1.4.1) lib/graphql/execution/execute.rb:148:in 'block in resolve_value'
  activerecord (5.0.1) lib/active_record/relation/delegation.rb:38:in 'each'
  graphql (1.4.1) lib/graphql/execution/execute.rb:140:in 'resolve_value'
  graphql (1.4.1) lib/graphql/execution/execute.rb:105:in 'continue_resolve_field'
  graphql (1.4.1) lib/graphql/execution/execute.rb:76:in 'resolve_field'
  graphql (1.4.1) lib/graphql/execution/execute.rb:31:in 'block in resolve_selection'
  graphql (1.4.1) lib/graphql/internal_representation/selection.rb:41:in 'block in each_selection'
  graphql (1.4.1) lib/graphql/internal_representation/selection.rb:38:in 'each_selection'
  graphql (1.4.1) lib/graphql/execution/execute.rb:29:in 'resolve_selection'
  graphql (1.4.1) lib/graphql/execution/execute.rb:9:in 'execute'
  graphql (1.4.1) lib/graphql/query/executor.rb:37:in 'execute'
  graphql (1.4.1) lib/graphql/query/executor.rb:18:in 'result'
  graphql (1.4.1) lib/graphql/query.rb:115:in 'result'
  graphql (1.4.1) lib/graphql/schema.rb:184:in 'execute'
  app/controllers/queries_controller.rb:8:in 'create'
# [...]
```

Un-comment the `field :human_hero` lines and it will magically work in `/graphiql` for query `{ heros { id } }`!

I think the culprit is related to how the ObjectType are "registered" (when traversed):
- **Without** the `QueryType` field using `type HumanType` :
`StarWarsSchema.types.values` does not include the `Human` ObjectType.
- **With** the `QueryType` field using `type HumanType`:
`StarWarsSchema.types.values` does include the `Human` ObjectType...

A call `StarWarsSchema.types.values` is made here: https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/possible_types.rb#L16

IRB dump:
```
2.3.1 :005 > StarWarsSchema.types.values.map(&:to_s).sort
 => ["Boolean", "Character", "CharacterConnection", "CharacterEdge", "Episode", "Human", "ID", "Int", "Node", "PageInfo", "Query", "String", "__Directive", "__DirectiveLocation", "__EnumValue", "__Field", "__InputValue", "__Schema", "__Type", "__TypeKind"]
# [commenting the field :human_hero, Human line and restarting the console
2.3.1 :001 > StarWarsSchema.types.values.map(&:to_s).sort
 => ["Boolean", "Character", "CharacterConnection", "CharacterEdge", "Episode", "ID", "Int", "PageInfo", "Query", "String", "__Directive", "__DirectiveLocation", "__EnumValue", "__Field", "__InputValue", "__Schema", "__Type", "__TypeKind"]
```

It feels like the type Human is not "registered" if it is only used via an Interface and not used explicitly in a field's `type`. A workaround would be to define "dummy endpoints" for each Type using the CharacterInterface:

```
    field :making_interface_work_for_human do
      type HumanType
      resolve ->(obj, args, ctx) { nil }
    end
```

But it feels so wrong...

**Comment by rmosolgo** [comment]
Hi, I think `orphan_types` is what you're looking for, can you give it a try? 

http://graphql-ruby.org/types/abstract_types.html#orphan-types

How does it work for you?

**Comment by Yoshiji** [comment]
I does works, thank you very much. I have to pay more attention to the documentation... Thanks for your time!
