### ISSUE TITLE
Use ObjectType to encode object to json

### ISSUE THREAD

**Issue by MSchmidt** [rmosolgo/graphql-ruby#1012]
Is it possible to use a defined ObjectType just for JSON encoding? I'd like to return JSON in other places than GraphQL (e.g. Sockets, REST endpoints) but would like to go through the same ObjectType, so the output is equal to the GraphQL-API output.

**Comment by tb** [comment]
@MSchmidt I think you mean

```
Types::JSONType = GraphQL::ScalarType.define do
  name "JSON"
end
```

I use it for `field :errors, Types::JSONType`

**Comment by rmosolgo** [comment]
Alternatively, if you're talking about about re-using the GraphQL layer to serve JSON in other places, I recommend https://github.com/github/graphql-client for that. It's what we use for GraphQL-backed REST endpoints at GitHub, and I know a few others use it the same way. 

You can write a static GraphQL query, then execute it and, if necessary, reformat the result a bit, then send the JSON somewhere else.

**Comment by MSchmidt** [comment]
Instead of adding a client, I've just used ``execute`` directly in REST-based controllers.

```ruby
result = GraphSchema.execute(query)
render json: result
```

But what I was actually looking for was some representation of a single type. E.g. I have a ``UserType`` and a ``User`` model. Now I was hoping for something like this:

```ruby
user = User.new(name: 'Foo', email: 'bar@example.com')
graphql_representation_of_user = UserType.generate_from_model(user)
```

**Comment by rmosolgo** [comment]
Using `execute` directly sounds good too! There's not a built-in way to get a "representation" of a type with GraphQL. It's part of what makes GraphQL special: clients all have different needs, so the concept of a "canonical representation" is not really useful for productive client development. With that in mind, the solution is just like what you're already doing: create a certain "representation" by writing a GraphQL query, then serve that result to clients.

**Comment by kaito0228** [comment]
Hi, is there still no support for any more methods?
