### ISSUE TITLE
Middleware declaration in schema raises undefined method error

### ISSUE THREAD

**Issue by hedselu** [rmosolgo/graphql-ruby#1023]
Hi. I am playing with GraphQL in current work. I faced an issue while trying to apply custom middleware. Let's say we've got schema:
```
ApiSchema = GraphQL::Schema.define do
  query(Types::QueryType)
  mutation(Mutations::MutationRoot)
  max_depth 5
  middleware NiceMiddleware
end
```
This middleware declaration raises error while trying to execute query:
```
undefined method `call' for class `#<Class:NiceMiddleware>'
```
So I've dig into code a little bit and there is no initialization of such middleware. Addition to `MiddlewareChain` instance occurs here as class object:

https://github.com/rmosolgo/graphql-ruby/blob/924b92bc86a6da1b90a0528ac4f623af1a5b35bd/lib/graphql/schema.rb#L73

```
ApiSchema.middleware << NiceMiddleware
=>
NameError: undefined method `call' for class `#<Class:NiceMiddleware>'
ApiSchema.middleware << NiceMiddleware.new
ApiSchema.middleware
 => #<GraphQL::Schema::MiddlewareChain:0x007f924f8544c0 @steps=[#<NiceMiddleware:0x007f924f951058>], @final_step=GraphQL::Execution::Execute::FieldResolveStep>
```
Can anyone confirm this or am I missing something?
PS1. There are no specs for adding custom middleware as I saw.
PS2. Can fix this if needed.

**Comment by rmosolgo** [comment]
A middleware should respond to `.call`, does `NiceMiddleware` above respond to that method? 

Can you share the definition of `NiceMiddleware`?

**Comment by hedselu** [comment]
Sure, the middleware class is pretty simple.

```
class NiceMiddleware
  def call(*_args)
    begin
      yield
    rescue StandardError => err
      ...
    end
  end
end
```

**Comment by hedselu** [comment]
Ok, now I see where's the problem, this should be defined as class method ;)

**Comment by rmosolgo** [comment]
Yep, or, initialize the middleware, for example:

```
middleware NiceMiddleware.new 
```

**Comment by hedselu** [comment]
I was following my earlier implementations of middleware & creating instances of MiddlewareChain & RescueMiddleware, that's why I was hitting this error.
Yay, I've initialized it as you written, but was wondering why it isn't working basing on docs :)

Thanks for your help :+1:

**Comment by hedselu** [comment]
Due to finding solution for this I am closing this "issue".
