### ISSUE TITLE
[Question] How to add fields to ObjectType dynamiclly?

### ISSUE THREAD

**Issue by cpunion** [rmosolgo/graphql-ruby#1027]
I need to add some field to a type defined by ObjectType, these types generated by CMS, and then add some fields in plugins. In `v1.6.4`, I can call `.redefine` likes below:

```ruby
all_types = {}
all_types['User'] = GraphQL::ObjectType.define do
  name 'User'
  # ... some fields
end

# ... add fields in some plugins
all_types['User'] = all_types['User'].redefine do      # <-- REDEFINE
  field 'new_field', types.String
end

# Build Query type and Schema type
# ...
```

It works fine. But after I upgraded to 1.7.4, I got an error:

```console
RuntimeError (Duplicate type definition found for name 'User'):
```

If I change
```
all_types['User'] = all_types['User'].redefine
```
to:
```
all_types['User'].redefine
```

No errors but the field doesn't add.

Is there a way to do this?

**Comment by cpunion** [comment]
Downgrade to `v1.6.4`, it works again.

**Comment by cpunion** [comment]
Solved by change all field type to **lazy** that reference to other object type. 😀😀

@rmosolgo Please let me know this is the right way, or you will change something to compatible that usage.

**Comment by rmosolgo** [comment]
:+1: I think that's a good solution, because otherwise some fields have references to _old versions_ of the type, while other fields refer to new versions of it!

**Comment by cpunion** [comment]
Thanks!

**Comment by volkanunsal** [comment]
@cpunion Can you post a snippet of your solution? I think I have the same problem. It would be really useful.

**Comment by rmosolgo** [comment]
I would guess it's like this 

```diff 
- type(all_types["User"])
+ type( -> { all_types["User"] })
```

Using a proc literal for deferred type lookup

**Comment by volkanunsal** [comment]
👍

**Comment by cpunion** [comment]
Yes. See @rmosolgo 's example.
