### ISSUE TITLE
Improve returned validation error 

### ISSUE THREAD

**Issue by dblock** [rmosolgo/graphql-ruby#1028]
```
Mutations::CreateRsvpMutation = GraphQL::Relay::Mutation.define do
  name "createRsvp"

  input_field :name, !types.String
  input_field :email, !types.String

  return_type Types::RsvpType

  resolve -> (object, inputs, ctx) {
  }
end
```

Post this:

```ruby
          post '/api/graphql', params: { query: %{
            mutation {
              createRsvp(input: {
                email: "matt@example.org",
                event_id: "420",
              }) { id, total_count } }
            }
          }
```

The error returned is `Argument 'input' on Field 'createRsvp' has an invalid value. Expected type 'createRsvpInput!'`, not very useful.

With the following:

```ruby
post '/api/graphql', params: {
            variables: { input: { email: 'matt@example.org' } },
            query: %{
              mutation($input: createRsvpInput!) {
                createRsvp(input: $input) {
                  id
                  total_count
                }
              }
            },
          }
```

It's better

```
{"errors"=>[{"message"=>"Variable input of type createRsvpInput! was provided invalid value", "locations"=>[{"line"=>2, "column"=>24}], "value"=>{"email"=>"matt@example.org"}, "problems"=>[{"path"=>["name"], "explanation"=>"Expected value to not be null"}, {"path"=>["event_id"], "explanation"=>"Expected value to not be null"}]}]}
```

We want at least the latter in the former example.

This is because the `LiteralValidator` just returns a boolean indicating whether the literal input is valid or not, see https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/static_validation/literal_validator.rb. Change the `LiteralValidator` so that it’s `validate` method returned some more information describing the specific problem. This is invoked inside of `GraphQL::StaticValidation::ValidationContext` and called in two places, it looks like, including the specific culprit `ArgumentLiteralsAreCompatible`.

**Comment by dblock** [comment]
Failing spec in https://github.com/dblock/graphql-ruby/tree/issue-1028.

**Comment by rmosolgo** [comment]
Yeah, I agree this would be a great place to improve, maybe we could take inspiration from graphql-js!

**Comment by broskoski** [comment]
+1 😃

**Comment by dblock** [comment]
Btw, I wasn't able to wrap this up in a working PR, maybe someone smarter than me like @broskoski above will take a stab :)

**Comment by joallard** [comment]
Is #1701 related to this? The error message dumbfounds me

**Comment by rmosolgo** [comment]
GraphQL-Ruby now returns the full error message, even when values are given as literals in the query strings: 

![image](https://user-images.githubusercontent.com/2231765/75782749-69e8d700-5d2d-11ea-9405-3a320d7cc86b.png)


If you find another issue with this error message, please open a new issue!

**Comment by joallard** [comment]
@rmosolgo Looking good!
