### ISSUE TITLE
ActionCable subscription backend for Relay returns nil on first subscription fetch?

### ISSUE THREAD

**Issue by Ruin0x11** [rmosolgo/graphql-ruby#1038]
Hello. I'm trying to create a Relay subscription using the built-in ActionCable backend, but on the initial subscription confirmation there isn't any data sent and the channel is unsubscribed prematurely. My understanding is that the server is supposed to send a different response the first time a subscription is requested, but instead I get an error when first fetching the subscription.

This is my subscription and payload type:

```ruby
Types::SubscriptionType = GraphQL::ObjectType.define do
  name "Subscription"
  field :receivedMessage, !Types::MessageType
end

Types::MessageType = GraphQL::ObjectType.define do
  name "Message"
  implements GraphQL::Relay::Node.interface
  global_id_field :id
  field :body, types.String
end

```

The ActionCable channel for the GraphQL subscriptions is the same as the one in the API documentation, seen [here](http://www.rubydoc.info/gems/graphql/1.7.4/GraphQL/Subscriptions/ActionCableSubscriptions).

My environment has these lines for setting up ActionCable:

```js
const ActionCable = require("actioncable");
var cable = ActionCable.createConsumer();
window.cable = cable;

const createHandler = require("graphql-ruby-client/subscriptions/createHandler");

// ...

var subscriptionHandler = createHandler({
  cable: cable
});

const network = Network.create(fetchQuery, subscriptionHandler);
```

I tried to use the subscription client-side like this:

```js
import { graphql, requestSubscription } from "react-relay";
import environment from "../Environment";

const receivedMessage = graphql`
  subscription ReceivedMessageSubscription {
    receivedMessage {
      body
    }
  }
`;

export default (onNext, onError, onCompleted, updater) => {
  const subscriptionConfig = {
    subscription: receivedMessage,
    variables: {},
    onError,
    onNext,
    onCompleted,
    updater
  };

  requestSubscription(environment, subscriptionConfig);
};
```

Inside a React component I requested a subscription like this:

```js
componentDidMount() {
  ReceivedTextMessageSubscription(
    response => console.log(`Received data: `, response),
    error => console.log(`An error occurred:`, error, error.source),
    () => console.log(`Completed`)
  );
}

```

On page load this is logged:

```
An error occurred: Error: No data returned for operation `ReceivedMessageSubscription`, got error(s):
(No errors)

See the error `source` property for more information.
    at createError (RelayError.js?6e26:44)
    at Object.create (RelayError.js?6e26:29)
    at normalizePayload (normalizePayload.js?a0e3:32)
    at eval (RelayModernEnvironment.js?f1c2:171)
    at eval (RelayObservable.js?8f68:297)
    at Object.next (RelayObservable.js?8f68:331)
    at Object.next [as onNext] (RelayObservable.js?8f68:517)
    at Subscription.received (createActionCableHandler.js?24f0:42)
    at Subscriptions.ActionCable.Subscriptions.Subscriptions.notify (action_cable.js?aa7c:493)
    at Connection.message (action_cable.js?aa7c:347) 
```

When I inspected the message sent by the server, it looked like this:

```json
{
    "identifier":"{\"channel\":\"GraphqlChannel\",\"channelId\":\"15f2c05c21d\"}",
    "message":{"result":{"data":null},"more":true}
}
```
Is `data` supposed to be `null` here? I'm not sure what else it could be since nothing was triggered yet, so there isn't a Message to fetch. But triggering the subscription in the console causes no changes on the frontend since the channel was unsubscribed after the error.

Also, something that might be unrelated is that when I tried to test the query using GraphiQL, I got an error relating to ActionCable. It might have to do with the GraphiQL environment not being connected to ActionCable.

```json
{
  "error": "undefined method `stream_from' for nil:NilClass"
}
```

This is the query I ran:

```graphql
subscription { 
  receivedTextMessage {
    body
  }
}
```

Any help would be greatly appreciated.

**Comment by rmosolgo** [comment]
Hi! First of all, thanks for opening this great issue. Let's see what we can find! 

> ` "error": "undefined method `stream_from' for nil:NilClass"`

That's because GraphiQL doesn't use ActionCable, so it couldn't stream 😖 

Here's where the code expects to get a `Channel` instance, but it was `nil`: 

https://github.com/rmosolgo/graphql-ruby/blob/17a497d0ed4514b7af90ee1abf5e1ce18e9b12a1/lib/graphql/subscriptions/action_cable_subscriptions.rb#L95

Maybe we can raise a more descriptive error there! 

I haven't seen anyone test `subscription`s with GraphiQL yet :/ 

> An error occurred: Error: No data returned for operation `ReceivedMessageSubscription`, got error(s):
> (No errors)


Oh! I tried on my own app and I see that my initial response is different: 

![image](https://user-images.githubusercontent.com/2231765/31696133-441cbe58-b37d-11e7-9fa0-a0c42cbca3de.png)

Maybe there's a bug in the docs, let me compare my `GraphqlChannel`... 

Yeah! How about trying this change:

```diff 
    payload = {
-     result: result.to_h,
+     result: result.subscription? ? nil : result.to_h,
      more: result.subscription?,
    }
```

Does that work better for you? Maybe those docs are out-of-date 😖

**Comment by cpunion** [comment]
I'm trying to run subscriptions in GraphiQL, just finished a demo to call subscriptions in GraphiQL, didn't test complete.

```js
import { parse } from 'graphql'
import { gql, ApolloClient, createNetworkInterface } from 'react-apollo'

const hasSubscriptionOperation = (queryDoc) => {
  for (let definition of queryDoc.definitions) {
    if (definition.kind === 'OperationDefinition') {
      const operation = definition.operation
      if (operation === 'subscription') {
        return true
      }
    }
  }

  return false
}

function buildFetcher(cable) {
  // Load ApolloClient and create a network interface
  var networkInterface = createNetworkInterface({
   uri: '/graphql',
   opts: {
     credentials: 'include',
   }
  })

  // Add subscriptions to the network interface
  var addGraphQLSubscriptions = require("graphql-ruby-client/subscriptions/addGraphQLSubscriptions")
  addGraphQLSubscriptions(networkInterface, { cable })

  // Optionally, add persisted query support:
  // var OperationStoreClient = require("./OperationStoreClient")
  // networkInterface.use([OperationStoreClient.apolloMiddleware])

  const client = new ApolloClient({ networkInterface })

  return function graphQLFetcher(graphQLParams) {
    const clientParams = {
      ...graphQLParams,
      variables: graphQLParams.variables || {},
      query: gql(graphQLParams.query)
    }
    const queryDoc = parse(graphQLParams.query)

    if (hasSubscriptionOperation(queryDoc)) {
      return {
        subscribe: ({next, error, complete}) => {
          const id = networkInterface.subscribe(clientParams, (errors, result) => {
            if (errors) {
              return error(errors)
            }

            if (result) {
              next(result)
            }
          })

          return {
            unsubscribe() {
              networkInterface.unsubscribe(id)
            }
          }
        }
      }
    }

    return client.query(clientParams)
  }
}
```

Then build a fetcher to GraphiQL:
```js
const fetcher = buildFetcher(cable)
return (
  <GraphiQL fetcher={fetcher} {...other props} />
)
```

I need some time to read GraphiQL's code to understand its `next/error/complete` callbacks.

@rmosolgo After subscription, the callback argument of `subscribe` be called with`(null, null)`, what's that means?

**Comment by Ruin0x11** [comment]
@rmosolgo Yes, it works! Thanks for your hard work as always.

The GraphiQL version I'm using is embedded as a Rails engine using the `graphiql-rails` gem, which just places it at an endpoint. It would be nice to have subscriptions working, since I was working through a GraphQL tutorial and got a different output from the tutorial which uses a different backend (visible [here](https://www.howtographql.com/graphql-js/9-subscriptions/)). They receive a string on the first request and the data on subsequent requests.

If GraphiQL is meant to work then I could create another issue for it.

**Comment by rmosolgo** [comment]
Glad it's working a bit better! I just opened another issue about migrating GraphiQL: https://github.com/rmosolgo/graphql-ruby/issues/1051

**Comment by rmosolgo** [comment]
It's been a while, but in case anyone still finds it helpful, `graphql-ruby-client` now includes a GraphiQL "fetcher" for using ActionCableSubscriptions: https://graphql-ruby.org/javascript_client/graphiql_subscriptions.html
