### ISSUE TITLE
accepts_definition default?

### ISSUE THREAD

**Issue by xuorig** [rmosolgo/graphql-ruby#1044]
It would be awesome to be able to provide a default for a certain metadata attribute / attribute on schema members.

For example:

```ruby
ObjectType.accepts_definitions([{
  definition: :someMeta,
  default: "test"
}])
```

Then:

```ruby
Car = ObjectType.define do
  name "Car"
end

Boat = ObjectType.define do
  name "Boat"
  someMeta "test2"
end

Car.someMeta == "test"
# true

Boat.someMeta == "test2"
# true
```

Of course, this particular example breaks the current accepts_definition signature. We could probably find a way to keep the old behaviour.

WDYT @rmosolgo ?

**Comment by rmosolgo** [comment]
:+1: as long as there's a way to not-break existing code 😎

**Comment by rmosolgo** [comment]
This API is on the way out, I'm not planning further improvements for it :'(
