### ISSUE TITLE
How to scope subscriptions?

### ISSUE THREAD

**Issue by steobrien** [rmosolgo/graphql-ruby#1057]
I'm having difficulty figuring out how to restrict subscription broadcasts to specific users. I'm using version 1.7.4 of the gem.

Here's a miniature version of my implementation (using ActionCable):
```ruby
module ApplicationCable
  class Connection < ActionCable::Connection::Base
    identified_by :current_user

    def connect
      self.current_user = find_verified_user
    end

    #…
  end
end
```

```ruby
class GraphqlChannel < ApplicationCable::Channel
  # …

  def execute(data)
    #…
    MainSchema.execute(
      data["query"],
      variables: ensure_hash(data["variables"]),
      context: { user: current_user, channel: self },
      operation_name: data["operationName"]
    )
    #…
  end

  #…
end
```

```ruby
# in application code somewhere…

MainSchema.subscriptions.trigger("newMessage", {}, message)
```
As is, this functions, but would broadcast _all_ new messages – belonging to any user – to any user with a subscription.

From the [subscriptions/triggers docs](http://graphql-ruby.org/subscriptions/triggers.html) I see a reference to scope, which sounds exactly like what I want.  And I've seen some [test cases](https://github.com/rmosolgo/graphql-ruby/blob/master/spec/graphql/subscriptions_spec.rb#L327) that seem to be doing what I need.

But, I can't seem to figure out how to make it work!

I've tried:
- `MainSchema.subscriptions.trigger("newMessage", {}, message, scope: user)`
- Adding `subscription_scope :user` to `field`s on subscription types
- Both of those things in combination

Any pointers?

**Comment by cpunion** [comment]
Try `arguments`. In your subscription, you can provide `user_id` argument, and keep it consistent with the 2nd argument of `trigger` (See the triggers docs).

**Comment by steobrien** [comment]
Thanks @cpunion! I think that's insecure though, because couldn't a malicious client guess/pass the `user_id` of a different user?

**Comment by cpunion** [comment]
@steobrien Oh sorry, I misunderstood.

**Comment by steobrien** [comment]
Turns out I was putting `subscription_scope` in the wrong place.

I got this working eventually with:

```ruby
Types::SubscriptionType = GraphQL::ObjectType.define do
  name "Subscription"

  field : newMessage, Subscriptions::NewMessageType do
    subscription_scope :user
  end
end
```

```ruby
# in application code somewhere…

MainSchema.subscriptions.trigger("newMessage", {}, message, scope: user)
```

**Comment by steobrien** [comment]
Hey @Mexxerio, my understanding is that the value in `subscription_scope` must correspond to a variable set in the execution `context`: https://github.com/rmosolgo/graphql-ruby/blob/719b5eda918d71ce7e6695939653f2371f95e607/lib/graphql/subscriptions/event.rb#L28

If so, a unique identifier for the user will then be used as a prefix:
https://github.com/rmosolgo/graphql-ruby/blob/719b5eda918d71ce7e6695939653f2371f95e607/lib/graphql/subscriptions/event.rb#L49 https://github.com/rmosolgo/graphql-ruby/blob/719b5eda918d71ce7e6695939653f2371f95e607/lib/graphql/subscriptions/serialize.rb#L38-L43

This is borne out by the logs I see in my Rails console:
```
[ActionCable] Broadcasting to graphql-event:Z2lkOi8vbEApbi9Vc2VyLzI:newMessage::
```

Therefore, in my case as long as I set `context[:user]` securely, and include the `scope` argument with the correct user in the appropriate `.trigger`s, I believe that the transmission is safely restricted to the intended user.

***However…*** I'm currently relying on this behavior only in an isolated, low-risk, prototype; so I haven't taken the time to carefully check all of this. I'd be keen to verify this understanding! @rmosolgo, perhaps you could let us know if what I've outlined in this and my previous comment is broadly correct?

**Comment by Mexxerio** [comment]
@steobrien Yeah I think you are right. It works for me now as well.

**Comment by rmosolgo** [comment]
Yes, you've described it correctly! Sorry it's not well-documented, I'll be solidifying the subscription docs before the next release (and removing the "experimental" flag)!

**Comment by steobrien** [comment]
Great, thanks!

**Comment by cantino** [comment]
How does one scope to an entry in a set? E.g., imagine I have Workspaces with many Users in each one. I want to be able to trigger an update when a Workspace changes and have it go only to the Users who are both members and are subscribed. Using `subscription_scope :workspace_id` doesn't seem sufficient, as then I'd have to put a single `workspace_id` in the `MySchema.execute` context which is called only on subscription in my `ApplicationCable::Channel`. I somehow need an array of allowed workspace_ids in the context.

**Comment by rmosolgo** [comment]
What if you had a field called `viewerWorkspaceWasUpdated { workspace { ... } }` which updated whenever one of a user's workspaces was updated? 

Then you could set it up like `subscription_scope :current_user_id`, and trigger it with

```ruby 
# in a background job
workspace.members.each do |member| 
  MySchema.trigger("viewerWorkspaceWasUpdated", workspace, {}, scope: member.id)
end 
```

How does that sound?

**Comment by cantino** [comment]
@rmosolgo Thanks for replying. Yes, that would work. I was hoping to be able to scope to workspace_id and have the context contain an array of valid workspace IDs, or to define a custom scope method that tests to see if a message is valid for a subscriber.
