### ISSUE TITLE
Argument prepare changing type

### ISSUE THREAD

**Issue by axos88** [rmosolgo/graphql-ruby#1059]
Hello,

I'm not sure if this is desired, or perhaps there is a better way to do it, however when the prepare function returns a different type of data, graphql crashes. Obviously the example below is not the actual code we are running and is a bit awkward, but describes what we are trying to achieve:

Internally I believe we should be able to map to anything...

#Setup
```
EnumType = GraphQL::EnumType.define do
    value('V1', 'V1', value: 'v1')
    value('V2', 'V2', value: 'v2')
  (...)
end

GraphQL::Relay::Mutation.define do
(...)
input_field :foo, !types[EnumType], 'Description', prepare: ->(value, ctx) do
  case value.sort
  when [] then 'none'
  when ['v1'] then 'v1'
  when ['v1','v2'] then 'v1_v2'
  else nil
end
(...)
  resolve ->(obj,arg, ctx) do
    puts args[:foo]
  end
```
#Expectation

Calling the mutation with foo: ["V1", "V2"] should output "v1_v2"

#Actual
```
E, [2017-10-26T13:53:05.903344 #16768] ERROR -- : undefined method `map' for "v1_v2":String
Did you mean?  tap
graphql-1.7.4/lib/graphql/query/arguments.rb:113:in `wrap_value'
graphql-1.7.4/lib/graphql/query/arguments.rb:43:in `block in initialize'
graphql-1.7.4/lib/graphql/query/arguments.rb:40:in `each'
graphql-1.7.4/lib/graphql/query/arguments.rb:40:in `inject'
graphql-1.7.4/lib/graphql/query/arguments.rb:40:in `initialize'
graphql-1.7.4/lib/graphql/query/arguments.rb:16:in `initialize'
graphql-1.7.4/lib/graphql/input_object_type.rb:99:in `new'
graphql-1.7.4/lib/graphql/input_object_type.rb:99:in `coerce_non_null_input'
(...)
```

**Comment by rmosolgo** [comment]
GraphQL-Ruby assumes that all GraphQL `List` types will have underlying Ruby `Array`s. In this example, a `List`-typed input (`[Enum]!`) is being converted to a Ruby String [`"v1_v2"`], which is not supported. 

I'm not convinced that graphql-ruby _should_ support this. Can you reimplement your `case` statement to return an array (eg, `["v1", "v2"]`), then convert the array to a string inside your resolve function?

**Comment by axos88** [comment]
Even if this should not be supported within the prepare function, which unsure wether would be a good idea either, there should be another functionality, call it resolve or map, or whatever that can map the incoming argument to the inner domain model, which values type may or may not coincide with the graphql defined outer type. And this mapped value should be available within args[:xxx]

**Comment by rmosolgo** [comment]
>  map the incoming argument to the inner domain model

:+1:, yes, I think this is the responsibility of resolve functions. They should take GraphQL-defined inputs and map them to your application logic.
