### ISSUE TITLE
Unexpected "NoMethodError: undefined method 'id'"

### ISSUE THREAD

**Issue by jdsjr** [rmosolgo/graphql-ruby#1063]
I'm using graphql-ruby fronting a postgresql database.  I'm attaching graphiql screenshots that show me querying for all the displays (Display.all) and getting the expected results.  A second screenshot shows an attempt to get a single display with a specific "retailDisplayId".  This second query fails with a "NoMethodError: undefined method 'id'".  As you can see in the screenshots the display schema has an "id" defined and also you can see I do get back ids when I get all objects.

I'm also attaching a screenshot of my single resolver method.

Since I am relatively new to the graphql world I suspect I have something set up incorrectly and I'm hoping you can help me figure out just where I've gone wrong.

Thanks in advance.
![screen shot 2017-10-28 at 6 00 03 pm](https://user-images.githubusercontent.com/16107620/32139372-ebe8ac78-bc0b-11e7-9a0a-f92dea775368.png)
<img width="1815" alt="screen shot 2017-10-28 at 5 55 02 pm" src="https://user-images.githubusercontent.com/16107620/32139373-ec088db8-bc0b-11e7-8ae5-a93553847442.png">
![Uploading Screen Shot 2017-10-28 at 5.53.47 PM.png…]()

**Comment by pengwynn** [comment]
Missing a `.first` in your `display` resolver?

```ruby
Display.where("retail_display_id = ?", args["retailDisplayId"]).first
```

**Comment by jdsjr** [comment]
Thanks pengwynn, that was the problem.
