### ISSUE TITLE
Allow GraphQL::InterfaceType to define 'implements'

### ISSUE THREAD

**Issue by eugenk** [rmosolgo/graphql-ruby#1067]
I'm facing a situation of hierarchical inheritance like:
```ruby
class A
  def fooA
    'a'
  end
end

class B < A
  def fooB
    'b'
  end
end

class C < B
  def fooC
    'c'
  end
end

class D < B
  def fooD
    'd'
  end
end

class E < A
  def fooE
    'e'
  end
end
```
and want to mirror this in the GraphQL API (with graphql-ruby 1.7.4). You can think of classes A and B as "abstract classes" that are never actually instantiated, but only the leafs of the inheritance tree (C, D, E). I would like to write my types like this:
```ruby
Types::AType = GraphQL::InterfaceType.define do
  field :fooA, !types.String
end

Types::BType = GraphQL::InterfaceType.define do
  implements [Types::AType]
  field :fooB, !types.String
end

Types::CType = GraphQL::ObjectType.define do
  implements [Types::BType]
  field :fooC, !types.String
end

Types::DType = GraphQL::ObjectType.define do
  implements [Types::BType]
  field :fooD, !types.String
end

Types::EType = GraphQL::ObjectType.define do
  implements [Types::AType]
  field :fooE, !types.String
end
```
However, this is not possible. `GraphQL::Schema::Printer.print_schema(MySchema)` fails with:
```
GraphQL::Define::NoDefinitionError: GraphQL::InterfaceType can't define 'implements'
```

Is there a solution without duplicating the code or introducing and including modules to keep the code DRY?

**Comment by eapache** [comment]
It's interesting you bring this up. I don't think the current interface system has a solution for this but it shouldn't be too difficult to do in the class-based system @rmosolgo has been working on.

Robert: our internal class-based interface supports this already, the code looks kind of like this:
```ruby
      def implements(*interfaces)
        self.interfaces += interfaces
      end

      def on_implements(&block)
        @on_implements = block
      end

      def implemented_by(klass)
        sub_interfaces = self.interfaces
        klass.instance_exec do
          sub_interfaces.each { |interface| implements interface }
        end

        klass.instance_exec(&@on_implements) if @on_implements
      end

      def graphql_fields
        fields = {}
        interfaces.each do |interface|
          fields.merge!(interface.graphql_fields)
        end
        fields.merge(super)
      end
```

Worth noting this also lets interfaces define `on_implements { |type| ... }` blocks to let interfaces run additional work (e.g. setting permissions, visibility, complexity, etc) on their types. This has also proved quite useful.

**Comment by eugenk** [comment]
Interesting. So, you suggest to wait for the class-based system? Is it targeted for graphql-ruby 2.0?

**Comment by thefliik** [comment]
Previously, see #897, `@rmosolgo` has indicated he's personally not interested in building in the ability for interfaces to have interfaces.

**Comment by rmosolgo** [comment]
In class-based graphql, interfaces can include other interfaces, see 1.8+
