### ISSUE TITLE
Add graphql subscriptions with Apollo 2.0 support

### ISSUE THREAD

**Issue by Mexxerio** [rmosolgo/graphql-ruby#1068]
Apollo 1.x support was added recently https://github.com/rmosolgo/graphql-ruby/blob/master/javascript_client/subscriptions/addGraphQLSubscriptions.js

But unfortunately the newly released Apollo 2.0 has a lot of breaking changes. The network interface was ditched in favor of links: https://dev-blog.apollodata.com/apollo-link-the-modular-graphql-network-stack-3b6d5fcf9244

It would be great if Apollo 2.0 support could be added as well. Or maybe someone digged into this deeper and could help me build a custom Link for graphql-ruby?

**Comment by rmosolgo** [comment]
I haven't taken a look at this yet, but thanks for opening the issue! If anyone makes progress, please let us know here. I'll be sure to do the same when I update the JS client included here.

**Comment by Mati365** [comment]
@Mexxerio :+1:

**Comment by staugaard** [comment]
here is an implementation: #1120

**Comment by rmosolgo** [comment]
The docs now include Apollo Link for ActionCable and Pusher :tada:
