### ISSUE TITLE
invalid query args pass validation

### ISSUE THREAD

**Issue by minasmart** [rmosolgo/graphql-ruby#1069]
hey there!

While working on a thing that auto-generates pagination queries, I accidentally generated some bad queries.

One of them had query args like this:

```graphql
query($first: Int!, $first: Int = $first){
  hello
}
```

Clearly logically incorrect (and syntactically questionable). However, with the graphql-ruby gem, this seems to pass parsing validation, whereas, using the js graphql parser it gets caught as a syntax error [ref](https://launchpad.graphql.com/kjz4p1ll7).

**Comment by rmosolgo** [comment]
Eek! Thanks for the bug report. Just to clarify, I duplicated the issue on two platforms, SWAPI (which uses graphql-js): 

![image](https://user-images.githubusercontent.com/2231765/32255332-72795940-be7d-11e7-8807-99b9ab8b8d81.png)

And GitHub (which uses graphql-ruby): 

![image](https://user-images.githubusercontent.com/2231765/32255352-9339fce8-be7d-11e7-91ec-c86fd6b8a5e0.png)

Interestingly, if I reverse the order of variables, I get a different error: 

![image](https://user-images.githubusercontent.com/2231765/32255366-b16191cc-be7d-11e7-8560-af48f4b9eb70.png)

So, graphql-js (properly) returned an error to the client, but graphql-ruby is using the _last_ definition for a given name! 

I guess we need another validation rule in `static_validation/rules` to cover this case. I'm happy to take a look soon, or if anyone wants to take a try, I'm happy to help out in that process too :)

**Comment by minasmart** [comment]
also, in my original issue, the default value was the var name itself so like `$first: Int = $first`, which is weird but also seems to cause a different error.

**Comment by rmosolgo** [comment]
Derp, thanks for the correction, I tried again with: 

```graphql
query($login: String, $login: String = $login) {
  user(login: $login) {
		login
  }
}
```

And got: 

```
lib/ruby/2.4.0/forwardable.rb:227:in `[]'
gems/graphql-1.7.3/lib/graphql/query/literal_input.rb:13:in `coerce'
gems/graphql-1.7.3/lib/graphql/query/variables.rb:41:in `block in initialize'
gems/graphql-1.7.3/lib/graphql/query/variables.rb:18:in `each'
gems/graphql-1.7.3/lib/graphql/query/variables.rb:18:in `each_with_object'
gems/graphql-1.7.3/lib/graphql/query/variables.rb:18:in `initialize'
gems/graphql-1.7.3/lib/graphql/query.rb:170:in `new'
gems/graphql-1.7.3/lib/graphql/query.rb:170:in `block in variables'
gems/graphql-1.7.3/lib/graphql/query.rb:332:in `with_prepared_ast'
gems/graphql-1.7.3/lib/graphql/query.rb:169:in `variables'
gems/graphql-1.7.3/lib/graphql/query/validation_pipeline.rb:85:in `ensure_has_validated'
gems/graphql-1.7.3/lib/graphql/query/validation_pipeline.rb:34:in `valid?'
gems/graphql-1.7.3/lib/graphql/query.rb:206:in `valid?'
gems/graphql-1.7.3/lib/graphql/analysis/analyze_query.rb:11:in `block (2 levels) in analyze_multiplex'
gems/graphql-1.7.3/lib/graphql/analysis/analyze_query.rb:10:in `map'
gems/graphql-1.7.3/lib/graphql/analysis/analyze_query.rb:10:in `block in analyze_multiplex'
gems/graphql-1.7.3/lib/graphql/tracing.rb:40:in `block in trace'
gems/graphql-1.7.3/lib/graphql/tracing.rb:71:in `call_tracers'
gems/graphql-1.7.3/lib/graphql/tracing.rb:40:in `trace'
gems/graphql-1.7.3/lib/graphql/analysis/analyze_query.rb:8:in `analyze_multiplex'
gems/graphql-1.7.3/lib/graphql/execution/multiplex.rb:169:in `with_instrumentation'
gems/graphql-1.7.3/lib/graphql/execution/multiplex.rb:60:in `block in run_queries'
gems/graphql-1.7.3/lib/graphql/tracing.rb:40:in `block in trace'
gems/graphql-1.7.3/lib/graphql/tracing.rb:71:in `call_tracers'
gems/graphql-1.7.3/lib/graphql/tracing.rb:40:in `trace'
gems/graphql-1.7.3/lib/graphql/execution/multiplex.rb:50:in `run_queries'
gems/graphql-1.7.3/lib/graphql/query.rb:144:in `block in result'
gems/graphql-1.7.3/lib/graphql/query.rb:332:in `with_prepared_ast'
gems/graphql-1.7.3/lib/graphql/query.rb:143:in `result'
```

**Comment by minasmart** [comment]
Yep, that's the business 😉
