### ISSUE TITLE
Infinite resolution when instrumenter inspects query result

### ISSUE THREAD

**Issue by haydentherapper** [rmosolgo/graphql-ruby#1072]
Given the following conditions, I've run into an infinite loop when resolving a query. This is used to build tracing data, similar to https://github.com/uniiverse/apollo-tracing-ruby/blob/0ac17ca17f328ca13cee2ad29308874726f44f90/lib/apollo_tracing.rb#L62

* The query instrumenter inspects the query with `query.result` in `after_query`.
* The result throws an exception not inheriting a `GraphQL::ExecutionError`

This will prevent the multiplexer from executing [`finish_query`](https://github.com/rmosolgo/graphql-ruby/blob/4eef45fee9cdda0b139fea5d96cec06b0a8448ae/lib/graphql/execution/multiplex.rb#L90)as the [resolver](https://github.com/rmosolgo/graphql-ruby/blob/4eef45fee9cdda0b139fea5d96cec06b0a8448ae/lib/graphql/execution/multiplex.rb#L85) will raise an exception.

With an instrumenter, the [`ensure` block](https://github.com/rmosolgo/graphql-ruby/blob/4eef45fee9cdda0b139fea5d96cec06b0a8448ae/lib/graphql/execution/multiplex.rb#L182) will still execute. Note that `finish_query` has not set the query to [`executed`](https://github.com/rmosolgo/graphql-ruby/blob/72cf8d6fe637c2273730b1a6a16cd6431e4b08b7/lib/graphql/query.rb#L135). This will cause `after_query` to execute in a loop, since the multiplexer will never have the opportunity to set the query to `executed`.

I've attached a repro. This is on version 1.7.4.

```ruby
require 'graphql'

class QueryInstrumentation
  def before_query(query)
  end

  def after_query(query)
    puts query.result.to_json
  end
end

QueryType = GraphQL::ObjectType.define do
  name "Query"

  field :raiseExecutionError, types.String do
    resolve ->(object, args, ctx) {
      raise GraphQL::ExecutionError, "Whoops"
    }
  end

  field :raiseError, types.String do
    resolve ->(object, args, ctx) {
      raise GraphQL::Error, "Whoops"
    }
  end
end

MySchema = GraphQL::Schema.define do
  query QueryType
  instrument(:query, QueryInstrumentation.new)
end

MySchema.execute("{ raiseExecutionError }")
# {"data":{"raiseExecutionError":null},"errors":[{"message":"Whoops","locations":[{"line":1,"column":3}],"path":["raiseExecutionError"]}]}

MySchema.execute("{ raiseError }")
# `after_query': stack level too deep (SystemStackError)
```

**Comment by rmosolgo** [comment]
😖  I thought there was a _test_ for exactly this. Thanks for reporting it, I'll take a look!

**Comment by tylerhou** [comment]
@rmosolgo I noticed that the fix for this bug rescues `StandardError`, but I think it should rescue `Exception` instead. If I raise an non-StandardError exception inside a mutation, the mutation will still infinitely loop. I am on an old version of `ruby-graphql` (1.7.9) but looking at the current version I don't see any code which would mitigate this.
