### ISSUE TITLE
Circular Dependency when creating union type

### ISSUE THREAD

**Issue by kormie** [rmosolgo/graphql-ruby#1091]
graphql-ruby version: `1.5.10` (also reproduced on `1.7.6`)

Code:
```ruby
Schema = GraphQL::Schema.define do
  mutation Mutations::MutationType
end

Mutations::MutationType = GraphQL::ObjectType.define do
  name "Mutation"

  field :CreateCard, field Mutations::CreateCard.field
end

Mutations::CreateCard = GraphQL::Relay::Mutation.define do
  name 'CreateCard'
  description 'Creates a card'

  input_field :owner, !Types::CardOwnerInput, 'Details about the owner'

  return_field :errors, Types::Error, 'An optionally returned client error'
end

Types::Error = GraphQL::UnionType.define do
  name 'Error'
  description 'Client friendly errors'
  possible_types [GraphQL::ObjectType.define {
    name 'Foo'
    field :message, types.String
  }]
end
```
The inlining of the `ObjectType` was done simply to eliminate one level of possible confusion. I have also tried inlining the entire `Error` `UnionType` into the `return_field` call inside the mutation. This results in the same Circular dependency issue.

With that setup I'm getting the following error:
```sh
Circular dependency detected while autoloading constant Mutations::MutationType
```
with a stack trace:
```sh
/Users/kormie/.rvm/gems/ruby-2.3.5@letote/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:478:in `load_missing_constant'
/Users/kormie/.rvm/gems/ruby-2.3.5@letote/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:180:in `const_missing'   
/Users/kormie/letote/letote/app/graph/schema.rb:4:in `block in <top (required)>'                                                       
/Users/kormie/.rvm/gems/ruby-2.3.5@letote/gems/graphql-1.7.6/lib/graphql/define/instance_definable.rb:161:in `instance_eval'   
/Users/kormie/.rvm/gems/ruby-2.3.5@letote/gems/graphql-1.7.6/lib/graphql/define/instance_definable.rb:161:in `ensure_defined'
/Users/kormie/.rvm/gems/ruby-2.3.5@letote/gems/graphql-1.7.6/lib/graphql/schema.rb:196:in `define'           
/Users/kormie/.rvm/gems/ruby-2.3.5@letote/gems/graphql-1.7.6/lib/graphql/define/instance_definable.rb:226:in `define'           
/Users/kormie/letote/letote/app/graph/schema.rb:1:in `<top (required)>'
```

**Comment by rmosolgo** [comment]
Thanks for opening an issue on this one! I'd like to track it down and fix it. 

I've tried to reproduce the issue here: 

https://github.com/rmosolgo/graphql-cyclical-dep-repo

And you can see my setup here: 

https://github.com/rmosolgo/graphql-cyclical-dep-repo/commit/c3ce36618e5479a5f77b51554d51227aba9ec92d

But for me, the tests pass ok. 

Can you see any important details that might be missing from that setup? 

Just to be clear, I see this line in the backtrace: 

```
app/graph/schema.rb:4:in `block in <top (required)>'         
```

Does that correspond to 

```ruby 
  mutation Mutations::MutationType
```

?

**Comment by kormie** [comment]
@rmosolgo That looks almost identical to my setup, though I'm wondering if that `resolve_type` proc is what's causing some issues. I set up breakpoints inside `active_support/dependencies.rb` and when stepping through I saw this error for the first time:

schema contains Interfaces or Unions, so you must define a
```ruby
resolve_type  -> (obj, ctx) { ... } function
```

**Comment by kormie** [comment]
That was the issue. So tl;dr, I guess lack of `resolve_type` can cause circular dependencies which obfuscate the underlying issue.

**Comment by rmosolgo** [comment]
I'm not sure we actually got to the bottom of this, but `.define` is officially deprecated, and the new class-based schema definition API loads code pretty differently. I don't have plans to work on this further, so I'm closing it. If someone runs into a new occurrence of this, please open a new issue!
