### ISSUE TITLE
Guide: Error Handling

### ISSUE THREAD

**Issue by KevinColemanInc** [rmosolgo/graphql-ruby#1093]
# error-handling-with-wrappers

defines a class `RescueFrom` and then below, a class `Rescuable.new` is used.

Are these two supposed to be the same class? If not, can the documentation explain how these two classes are related?

**Comment by dblock** [comment]
Maybe https://code.dblock.org/2017/10/30/generating-and-handling-errors-in-graphql-in-ruby.html is helpful.

**Comment by rmosolgo** [comment]
A while ago, I rewrote the errors docs, including the new errors plugin for the interpreter 💁‍♂ https://graphql-ruby.org/guides#errors-guides 

If anyone runs into trouble with that, please open a new issue!
