### ISSUE TITLE
Support machine readable error handling

### ISSUE THREAD

**Issue by KevinColemanInc** [rmosolgo/graphql-ruby#1094]
The current recommended [error handling story](http://graphql-ruby.org/queries/error_handling.html) needs improvement.

Consider the following:

POST /graphql
```  
mutation
{
  updateProfile(input: {name: "", age: 12}) {
    clientMutationId
    errors
  }
}
```

updateProfile mutation
```
    resolve ->(obj, inputs, ctx) {
      profile_params = { name: inputs['name'],
                         age: inputs['age']}.compact
      ctx[:current_profile].update(profile_params)
      if ctx[:current_profile].save
        {
          profile: ctx[:current_profile]
        }
      else
        raise GraphQL::ExecutionError.new(ctx[:current_profile].errors.full_messages.to_sentence)
      end
    }
```
results in an error message that looks like:
```
{
  "data": {
    "updateProfile": null
  },
  "errors": [
    {
      "message": "Name can't be blank and Age must be greater than or equal to 18",
      "locations": [
        {
          "line": 3,
          "column": 3
        }
      ],
      "path": [
        "updateProfile"
      ]
    }
  ]
}
```

Clients are not able to see programmatically see exactly which fields are failing, so the best they can do is render a toast with the human readable string.

Proposal:
`GraphQL::ExecutionError.new(...)` should be able to accept a `hash` we can highlight exactly which fields have errors and what those errors are.

**Comment by rmosolgo** [comment]
ExecutionError now accepts `extensions:` for this 🍻 https://graphql-ruby.org/errors/execution_errors.html#customizing-error-json
