### ISSUE TITLE
Support composite primary_key in graphql-pro cursors 

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#1108]
Sometimes primary_key returns an array; this isn't supported yet!

**Comment by phaedryx** [comment]
Specifically, it would be great if it worked with this gem: https://github.com/composite-primary-keys/composite_primary_keys

**Comment by rmosolgo** [comment]
This should be properly supported in version 1.6.1, please follow up here if you have any trouble with it!
