### ISSUE TITLE
Per-query backtrace wrapping doesn't work

### ISSUE THREAD

**Issue by eapache** [rmosolgo/graphql-ruby#1121]
From http://graphql-ruby.org/queries/backtrace_annotations.html.

Adding the backtrace module with `use GraphQL::Backtrace` at the schema level works correctly. Adding it by passing `backtrace: true` in the query's context does not.

The reason is that the backtrace module gets added as a tracer to the query object itself https://github.com/rmosolgo/graphql-ruby/blob/21fb53ced3ada7e088c22f7442bcfcedb05bdabb/lib/graphql/query.rb#L89
but the multiplex tracing event occurs on the generated multiplex object
https://github.com/rmosolgo/graphql-ruby/blob/21fb53ced3ada7e088c22f7442bcfcedb05bdabb/lib/graphql/execution/multiplex.rb#L57-L58
which does not have the backtrace tracing installed.

The backtracing module relies on the `execute_multiplex` event in order to install its rescue hook https://github.com/rmosolgo/graphql-ruby/blob/21fb53ced3ada7e088c22f7442bcfcedb05bdabb/lib/graphql/backtrace/tracer.rb#L26-L31

So 99% of the backtrace module is present and working (the context is fully populated etc.) but because the rescue is never hooked, exceptions don't actually get wrapped.

@rmosolgo @swalkinshaw

**Comment by eapache** [comment]
I suppose this is a broader design question; if only certain queries in a multiplex set use backtracing, we can't install a single global rescue can we?

**Comment by rmosolgo** [comment]
😖 

The way it's _supposed_ to work is that `backtrace: true` is pulled out from `Schema.execute`: 

https://github.com/rmosolgo/graphql-ruby/blob/f249953938128be63c8fa43f4a52a72dc3dd35be/lib/graphql/schema.rb#L268

Then passed along to the `Multiplex`, which uses that flag to add the backtrace tracer: 

https://github.com/rmosolgo/graphql-ruby/blob/f249953938128be63c8fa43f4a52a72dc3dd35be/lib/graphql/execution/multiplex.rb#L40

Here's where it's meant to be tested:

https://github.com/rmosolgo/graphql-ruby/blob/d43b949d663fb290019655cb7ccec71aa6540519/spec/graphql/backtrace_spec.rb#L129-L133

But it sounds like that's not working in your case? Or maybe, pulling it out from `Schema#execute` is too early? (For example, if it's added during `before_query`, it won't get noticed!)

**Comment by eapache** [comment]
The problem is that the `Multiplex` method is not being passed the context:
https://github.com/rmosolgo/graphql-ruby/blob/f249953938128be63c8fa43f4a52a72dc3dd35be/lib/graphql/query.rb#L160 so it's just the default empty hash: https://github.com/rmosolgo/graphql-ruby/blob/f249953938128be63c8fa43f4a52a72dc3dd35be/lib/graphql/execution/multiplex.rb#L56-L57

**Comment by rmosolgo** [comment]
Oh, sorry I forgot to respond here 😖  I saw you're using `Query#result`, not `Schema#execute`. I guess we should select a few keys from `@context` to pass along here, just like we do for `Schema#execute`!

**Comment by eapache** [comment]
Passing along the context would solve our immediate problem. I'm still a bit curious about the broader design question I raised in https://github.com/rmosolgo/graphql-ruby/issues/1121#issuecomment-346044023? Although maybe that's incoherent if multiplexed queries have to share a context?

**Comment by rmosolgo** [comment]
> certain queries in a multiplex set use backtracing

I don't _expect_ that to work, instead, you can pass one `backtrace:` kwarg per call (either `.execute` or `.multiplex`). That unit of work (a single query or a multiplex) will get that setting. That's the _goal_ !
