### ISSUE TITLE
Class-based API: field name casing

### ISSUE THREAD

**Issue by swalkinshaw** [rmosolgo/graphql-ruby#1124]
The class-based API provides a bunch of automatic `underscore` transformations, but field names are still passed through directly preserving original case.

There's a lot of subjective arguments on both sides. Should the gem even provide a solution to this?

Simplest solution could be a few pre-defined options on the schema:

* preserve/nothing
* camelcase
* underscore

Or if there's a need it could even take a transformation proc.

However, with the class-based API, another solution is just overriding `field` in your own base `Object` and `InputObject` class and the gem doesn't have to do anything.

**Comment by swalkinshaw** [comment]
cc @eapache

**Comment by eapache** [comment]
For a bit of context, this came up because internally we still define `field :foo_bar` which defaults to calling `def foo_bar`, but gets exposed in the actual API as `fooBar`. AFAICT this is slightly different from the behaviour the gem currently provides.

**Comment by rmosolgo** [comment]
:+1: I _want_ the behavior that @eapache described above, but I don't think I've done it properly yet. Feel free to take a crack at it if you get a chance!

**Comment by rmosolgo** [comment]
fixed by #1126, right?

**Comment by MiguelSavignano** [comment]
@rmosolgo How I can't disable/enable fields camelcase?

**Comment by rmosolgo** [comment]
Adding `camelize: false` option here: https://github.com/rmosolgo/graphql-ruby/pull/1300
