### ISSUE TITLE
Simple ObjectType DateTime type field?

### ISSUE THREAD

**Issue by johnunclesam** [rmosolgo/graphql-ruby#1128]
I have this simple Type:

```ruby
Types::PlayerType = GraphQL::ObjectType.define do
  name 'Player'

  field :id, !types.ID
  field :name, !types.String
  field :created_at, !types.DateTime

end
```

**Why `DateTime` is in error? There isn't this Type?**

**Comment by rmosolgo** [comment]
That's correct; it's not built-in because it's not part of the spec. You can implement it in a way that works for you, for example: 

https://github.com/howtographql/graphql-ruby/blob/master/app/graphql/types/date_time_type.rb

**Comment by johnunclesam** [comment]
> That's correct; it's not built-in because it's not part of the spec.

Why here I see: https://github.com/howtographql/react-apollo/blob/master/server/types.graphql ???

```graphql
type Link @model {
  id: ID! @isUnique
  createdAt: DateTime!
  updatedAt: DateTime!
  description: String!
  url: String!
  postedBy: User @relation(name: "UsersLinks")
  votes: [Vote!]! @relation(name: "VotesOnLink")

}

type User @model {
  id: ID! @isUnique
  createdAt: DateTime!
  updatedAt: DateTime!
  name: String!
  email: String @isUnique
  password: String
  links: [Link!]! @relation(name: "UsersLinks")
  votes: [Vote!]! @relation(name: "UsersVotes")

}

type Vote @model {
  id: ID! @isUnique
  user: User! @relation(name: "UsersVotes")
  link: Link! @relation(name: "VotesOnLink")
}
```

**Comment by rmosolgo** [comment]
DateTime is a user-defined type, like the link I posted above. 

That snippet has some other code which isn't part of the spec (or supported by graphql-ruby): `@model`, `@isUnique`, `@relation`. So I hope it's explained in the tutorial!

**Comment by johnunclesam** [comment]
Yes. The tutorial is not with Ruby backend. Ok. So today graphql-ruby doesn't support DateTime out of the box. Ok. This I wanted to know. Thanks.

**Comment by johnunclesam** [comment]
Hi @rmosolgo can we write a recipe for DateTime types for newbies like me?

I don't understand what `coerce_input` and `coerce_result` are here: https://github.com/howtographql/graphql-ruby/blob/master/app/graphql/types/date_time_type.rb

I can PR, but where?

What do you suggest?

**Comment by Willianvdv** [comment]
@johnunclesam have a look at this gem -> https://github.com/bitjourney/graphql_types-ruby. They implemented the DateType, maybe you can use this one?
