### ISSUE TITLE
why graphql returns "200 OK" response code for exceptions?

### ISSUE THREAD

**Issue by dkumar431** [rmosolgo/graphql-ruby#1130]
When i pass some unknown fields in a query(field that does not exist) or invalid variables (I mean server expecting an int value but i am passing a string value), why does it returns "200OK" as its status code in reponse?

**Comment by rmosolgo** [comment]
It's common practice to use `200` for all GraphQL requests. When errors happen, they're put in the `"errors"` key. Non-`200` response codes indicate that some issue occurred at the HTTP transport layer, not the GraphQL layer. 

See [Graph.cool docs](https://www.graph.cool/docs/faq/api-eep0ugh1wa/#how-does-error-handling-work-with-graphcool) for a bit more background.

**Comment by johnunclesam** [comment]
Is there a way to force other status code? Maybe for unauthorized?

**Comment by rmosolgo** [comment]
graphql-ruby doesn't have any code relating to HTTP status codes. If you want to use a different error code, maybe you could inspect the returned hash's `"errors"` key.

**Comment by maRci002** [comment]
Basicly your PC has to use extra resources to determine if there was an error in your response or not (it needs to parse/decode the whole body beacuse of it)

Moreover in Browsers dev tools -> Network tab, you see always 200 status :)

**Comment by Alexandr-Pletnev** [comment]
> It's common practice to use `200` for all GraphQL requests. When errors happen, they're put in the `"errors"` key. Non-`200` response codes indicate that some issue occurred at the HTTP transport layer, not the GraphQL layer.
> 
> See [Graph.cool docs](https://www.graph.cool/docs/faq/api-eep0ugh1wa/#how-does-error-handling-work-with-graphcool) for a bit more background.

My opinion is it is a bad practice. Because there are a lot of third-party tools which is expecting bad statuses to do something.  for example, process 401 status code in some way. and now i have to do extra efforts to process 401 error.

**Comment by martinbonnin** [comment]
Came here to say that in 2025, you may use `application/graphql-response+json` Content-Type and the HTTP status code of your liking if your server supports it.

See the GraphQL over HTTP draft: https://graphql.github.io/graphql-over-http/draft/#sec-application-graphql-response-json
