### ISSUE TITLE
GraphQL Pro Dashboard: Rails Route Inspector

### ISSUE THREAD

**Issue by sj26** [rmosolgo/graphql-ruby#1137]
Loving the new dashboard. But I noticed once I've mounted it in my rails routes doing a `rake routes` prints the whole graphql schema and all it's nested objects which takes a _very long time_ for us. Rails seems to handle a `Rails::Engine` with some finesse, but does an `#inspect` on regular Rack apps, which includes `#inspect`-ing the instance variables and their instance variabels, etc which, for the dashboard, includes the schema and all its children several times.

I found adding a `GraphQL::Pro::Dashboard#inspect` method which just returns a simplified `"#< GraphQL::Pro::Dashboard[#{@schema}]>"` makes it bearable and looks reasonably idiomatic.

For reference we have a couple of engines like this mounted:

```
$ rake routes | egrep "graphql|pghero|sidekiq"
        admin_graphql GET   /admin/graphql(.:format) admin/graphql#show
admin_graphql_mounted       /admin/graphql/mounted   #<GraphQL::Pro::Dashboard[#<GraphQL::Schema:0x00007fb74c0fb738>]>
         admin_pghero GET   /admin/pghero(.:format)  admin/pghero#show
 admin_pghero_mounted       /admin/pghero/mounted    PgHero::Engine
        admin_sidekiq GET   /admin/sidekiq(.:format) admin/sidekiq#show
admin_sidekiq_mounted       /admin/sidekiq/mounted   Sidekiq::Web
```

Hotfix:

```ruby
GraphQL::Pro::Dashboard.class_eval do
  def inspect
    "#<GraphQL::Pro::Dashboard[#@schema]>"
  end
end
```

**Comment by rmosolgo** [comment]
> prints the whole graphql schema 

😆  ... :sob:
