### ISSUE TITLE
GraphQL Pro Dashboard: Missing Content-Type

### ISSUE THREAD

**Issue by sj26** [rmosolgo/graphql-ruby#1139]
After deploying the dashboard to our production environment which is reverse-proxied through nginx, when viewing in Safari the page does a download as application/octet-stream because there is no Content-Type header. This was masked in development by reverse proxying through puma-dev which seems to add a text/html header by default.

It looks like `GraphQL::Pro::Dashboard::Dispatcher#render_view` needs to add `"Content-Type" => "text/html"` to the headers in the response.

Hotfix:

```ruby
GraphQL::Pro::Dashboard::Dispatcher.class_eval do
  prepend(Module.new do
    def render_view(*args)
      super(*args).tap do |(_, headers, _)|
        unless headers.keys.any? { |key| key.casecmp("Content-Type").zero? }
          headers["Content-Type"] = "text/html"
        end
      end
    end
  end)
end
```

**Comment by rmosolgo** [comment]
Derp, I guess that's the downside of the minimal-dependencies route! You miss some stuff that you're used to getting from your dependencies. Thanks for opening the issue, I'll release a patch soon!

**Comment by sj26** [comment]
Loving the minimal deps approach! But yeah, so easy to forget what we get for free. :-)

And speaking of things easily forgotten that I forget all the time, It might be good to add a content-length header while you’re in there based on the rendered string length.

**Comment by rmosolgo** [comment]
Fixed in 1.6.2!

**Comment by rmosolgo** [comment]
@sj26 btw, were you able to remove your hot-fix on a more recent graphql-pro version? I ask because I just got another report of this via email, and I wonder if I missed the mark 😖

**Comment by sj26** [comment]
@rmosolgo yeah, we removed out patch, and our currently deployed version seems to respond with a Content-Type correctly. 👌 Odd if somebody else is seeing this, maybe an old version? 😟

**Comment by rmosolgo** [comment]
that was my guess too, I guess we'll see 😬  Thanks for confirming!!
