### ISSUE TITLE
Query variables not getting replaced

### ISSUE THREAD

**Issue by hunterc** [rmosolgo/graphql-ruby#114]
Just getting started with graphql and started with your library ( thanks for building it by the way :) ).

I am attempting to use query variables to resolve a field. I am passing the variables in to my execute call but when I access the argument in my field resolve proc it is still the variable name string.

What am I missing to get the argument value to be set to the variable value?

Thanks for any and all help.

**Comment by rmosolgo** [comment]
Could you share some code? For example: 

- your field definition, including the argument definition and resolve proc 
- an example query string + Ruby code which demonstrates the bug 

That will make it a little easier to understand what's going wrong!

**Comment by hunterc** [comment]
I just figured out what I was doing wrong.

I wasn't parsing the JSON from `params[:variables]` so when I sent `variables` to the executor it was still a string. This caused the variable to not get replaced.

Sorry for the issue spam. :frowning:

**Comment by rmosolgo** [comment]
No problem, glad you found it! Hmm, I'm torn -- I could add some type assertion, but I also like thinking that you could inject _any_ key-value enumerable as `variables:` ... hmmm....

**Comment by daqo** [comment]
After upgrading to the latest version of GraphQL the problem happened to me as well. Parsing the string before passing it to executor fixed it for me.
