### ISSUE TITLE
Rubocop and reek on graphql_controller.rb.

### ISSUE THREAD

**Issue by johnunclesam** [rmosolgo/graphql-ruby#1146]
I have the default one file:

```ruby
class GraphqlController < ApplicationController
  def execute
    variables = ensure_hash(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      current_user: current_user
    }
    result = MyAPISchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  end

  private

  def ensure_hash(ambiguous_param)
    case ambiguous_param
    when String
      if ambiguous_param.present?
        ensure_hash(JSON.parse(ambiguous_param))
      else
        {}
      end
    when Hash, ActionController::Parameters
      ambiguous_param
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{ambiguous_param}"
    end
  end
end
```

Rubocop default on this file says:

`app/controllers/graphql_controller.rb:15:3 = Method has too many lines. [14/10]`

Reek says:

`[reek:TooManyStatements] GraphqlController#execute: has approx 6 statements`

and

`[reek:NilCheck] GraphqlController#ensure_hash: performs a nil-check` (on `when nil` line).

What we can do?

**Comment by Willianvdv** [comment]
Hey @johnunclesam, thanks for using GraphQL-Ruby! The lint errors you receive are from your project using your linter configuration; it's pretty hard for us to fix issues in your setup. Anyway, I can give you a couple of hints to fix the lint violations. To fix the `reek:TooManyStatements` you have to reduce the number of cases, start by trying to remove the nested `if` statement. You could do something like:
```ruby
# Old
 def ensure_hash(ambiguous_param)
    case ambiguous_param
    when String
      if ambiguous_param.present?
        ensure_hash(JSON.parse(ambiguous_param))
      else
        {}
      end
    when Hash, ActionController::Parameters
      ambiguous_param
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{ambiguous_param}"
    end
  end

# New
 def ensure_hash(ambiguous_param)
    case ambiguous_param
    when String
      ambiguous_param_as_hash
    when Hash, ActionController::Parameters
      ambiguous_param
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{ambiguous_param}"
    end
  end

  def ambiguous_param_as_hash
    if ambiguous_param.present?
      ensure_hash(JSON.parse(ambiguous_param))
    else
      {}
    end
  end
```

To reduce the number of lines, you could do:
```ruby
  def execute
    query = params[:query]
    context = { current_user: current_user }
    render json: MyAPISchema.execute(query, variables: variables, context: context, operation_name: operation_name)
  end

  def variables
    ensure_hash(params[:variables])
  end

  def operation_name
     params[:operationName]
  end
```

As said, this is something you have to fix yourself, but I hope these hints enable you to write linter violation free graphql-ruby code!

Hack on!

**Comment by johnunclesam** [comment]
Thanks @Willianvdv.

My question was to scan possible fixes for everyone in this library just because these linting rules are pretty basic and community-shared. Do they seem wrong to you? Too extreme? Not valid?

**Comment by Willianvdv** [comment]
Since basically everyone has their own linter preferences, it's hard for a library like this to make everyone's linter happy. Looking at your example you've posted, I find the rules a bit too strict. But that's just my opinion! 

Do you have suggestions how we can improve the gem regarding linting?

**Comment by johnunclesam** [comment]
Maybe your same suggestions for this file. :D No?

**Comment by rmosolgo** [comment]
Personally I don't think it needs to be changed, breaking a single operation into several functions creates indirection, forces _naming things_ (🙀), and encourages people to structure code implicit dependencies (especially in rails controllers), I can't recommend those practices to anyone! 

I hope the suggestions here satisfied your linter, though 😬

**Comment by rmosolgo** [comment]
So much this: https://medium.com/@copyconstruct/small-functions-considered-harmful-91035d316c29
