### ISSUE TITLE
Hide password (or other fields) from Rails log.

### ISSUE THREAD

**Issue by johnunclesam** [rmosolgo/graphql-ruby#1147]
In a signInUser scenario like this: https://github.com/howtographql/graphql-ruby/blob/master/app/graphql/resolvers/sign_in_user.rb **how can I hide password (or other delicate data) from Rails log**?

Is there a way?

**Comment by Willianvdv** [comment]
@johnunclesam in most setups the query variables are sent through a POST request. By default, Rails doesn't store POST params in logs. Do you think this will be a problem or do the passwords actually show up? If the latter, I'm curious what your setup looks like and (especially) how you sent data to the GraphQL queries.

**Comment by Willianvdv** [comment]
Interesting use case, but Rails' filter_parameters should work if you sent the password using the query variables field. When I query something with password as the key, Rails will remove it. Check:
```
Parameters: {"query"=>"{}", "variables"=>{"password"=>"[FILTERED]"}, "operationName"=>nil, "graphql"=>{"query"=>"{}", "variables"=>{"password"=>"[FILTERED]"}, "operationName"=>nil}}
```

**Comment by johnunclesam** [comment]
So? How can I do?

**Comment by rmosolgo** [comment]
@Willianvdv is right, you should use variables to get fine-grained filtering.  Otherwise, perhaps you could filter the _whole_ query parameter with 

```ruby
config.filter_parameters += [:query]
```

In the meantime, we're building a better printer in #1118 which can be used for fine-grained re-printing. Hope that helps!
