### ISSUE TITLE
Add support for block string

### ISSUE THREAD

**Issue by cjoudrey** [rmosolgo/graphql-ruby#1150]
Block string support [just landed in `graphql-js`](https://github.com/graphql/graphql-js/pull/926). Adding this issue so we keep track of progress on adding it to `graphql-ruby`.

Reference implementation: https://github.com/graphql/graphql-js/pull/926
Spec: https://github.com/facebook/graphql/pull/327

**Comment by rmosolgo** [comment]
Woah, it got merged! 🎉

**Comment by rmosolgo** [comment]
Taking a try in #1219
