### ISSUE TITLE
1.8 upgrade doc notes

### ISSUE THREAD

**Issue by eapache** [rmosolgo/graphql-ruby#1153]
Sorry for the brain-dumpy format, I just helped somebody through an experimental migration to the 1.8 format using https://github.com/rmosolgo/graphql-ruby/blob/c39c352e7e2e68887b02e9e0619d7c7846153b33/guides/schema/class_based_api.md and came out with a list of notes:

- If you were using the field block syntax before most of those will now throw `NoMethodError` (e.g. `description` or `resolve`) and there's no hint anywhere that they need to be converted to kwargs on the `field` call.
- docs still say arguments take `null`, but it's now `required` just like inputs
- "Resolution with methods" section seems to be missing part of the explanation? At the least, it's in dire need of an example.

**Comment by rmosolgo** [comment]
👌  Thanks for sharing! I'll take a crack at making the right updates to that page.

**Comment by rmosolgo** [comment]
> field block syntax

Curious about your opinion on this one, should we keep the flexibility to put these in the block? Open for discussion at #1158

**Comment by rmosolgo** [comment]
Took a stab at the method docs and arg docs in #1160 , thanks gain for pointing those out!

**Comment by eapache** [comment]
Thank you!
