### ISSUE TITLE
Cache the documents right after we’ve parsed the query, and then tell our Schema to take a parsed document instead of a string. Caching strategy.

### ISSUE THREAD

**Issue by johnunclesam** [rmosolgo/graphql-ruby#1162]
Is this still needed today or maybe `graphql-ruby` can do it itself?

http://mgiroux.me/2016/graphql-query-caching-with-rails/

> When a GraphQL query hits the server, what exactly happens first ? To start the execution, a GraphQL executor must first have a Query Document. Think of it as a query object containing all you need to exectute a query (Operation, Fields, Arguments, etc.).
> 
> Of course when we send a query to a GraphQL server, it’s a simple string, not a Document object. The first thing the server has to do is to lex and parse it.
> 
> With GraphQL-ruby at least, that step is the slowest one in the chain. Parsing, especially huge queries can be quite slow, and re-parsing the same query twice or more sounds like a huge waste!
> 
> What if we could cache the documents right after we’ve parsed the query, and then tell our Schema to take a parsed document instead of a string?

**Comment by xuorig** [comment]
👋 @johnunclesam 

Here's a few thoughts on this topic. It'd be really useful especially for persisted queries. One thing I'm not totally convinced (even though I wrote that post 😨 ) is how safe marshaling documents into a cache is 🤔

The example is the post is quite simple and works well but I wonder how that would behave with a more complex caching infrastructure / different back ends.

**Comment by rmosolgo** [comment]
I don't have a short-term plan to investigate in-memory caching with this library. Sometime in the next few months I will revisit execution code and keep that in mind though!
