### ISSUE TITLE
Make it possible to store custom variables in traces

### ISSUE THREAD

**Issue by esjee** [rmosolgo/graphql-ruby#1176]
For our application, we use the datadog tracing system. Datadog has the notion of "tags", which is really just metadata for a certain trace. In our case, we would like to add request-specific information about the user doing the request to the trace. The current user id, for example.

Does anybody have any thoughts about if this were a useful feature? If so, how should it be used/what would it look like?

**Comment by rmosolgo** [comment]
:+1: I think that's a great idea. How about making the datadog tracer check for `context[:datadog_tags]`, and use them if present? Would that be fine-grained enough, or, should we support different tags for tracing different events?

**Comment by rmosolgo** [comment]
As mentioned above, query `context` might be a good place for this. Good luck!
