### ISSUE TITLE
[1.8-dev] Some cases Upgrader doesn't convert correctly

### ISSUE THREAD

**Issue by cpunion** [rmosolgo/graphql-ruby#1177]
I tested upgrade latest commit of `1.8-dev`(https://github.com/rmosolgo/graphql-ruby/commit/90afbe58438bbcaa689036ea4cc0e3802ec64fc5) with `rake graphql:upgrade[app/graphql/**/*]`, input types aren't being converted.

Case:
```ruby
Types::Backend::FieldInputType = GraphQL::InputObjectType.define do
  name "FieldInput"
  input_field :name, !types.String
end
```

Expecteds:
```diff
- Types::Backend::FieldInputType = GraphQL::InputObjectType.define do
-   name "FieldInput"
-   input_field :name, !types.String
+ class Types::Backend::FieldInputType < GraphQL::Schema::InputObject
+   graphql_name "FieldInput"
+   argument :name, String, required: true
 end
```

Currently:
```diff
 Types::Backend::FieldInputType = GraphQL::InputObjectType.define do
   name "FieldInput"
-  input_field :name, !types.String
+  input_field :name, String, null: false
 end
```

**Comment by cpunion** [comment]
Oh, `name "FieldInput"` need convert to `graphql_name "FieldInput"` in other types.

See https://github.com/rmosolgo/graphql-ruby/blob/1.8-dev/guides/schema/class_based_api.md#common-type-configurations

**Comment by cpunion** [comment]
Namespace problem. I have a type named `Types::Backend::TableType`, it be convered to:

```ruby
class Types::Backend::TableType < BaseObject
  # ...
end
```
It raise error `NameError (uninitialized constant BaseObject)`, should be `Types::BaseObject`.

**Comment by cpunion** [comment]
ScalarType didn't convert. Is Upgrader done? If not, I will test later.

**Comment by rmosolgo** [comment]
Thanks for sharing these issues!

**Comment by rmosolgo** [comment]
Oh, I don't think the Scalar upgrader is done yet. Maybe we won't do one, because usually there are only a few custom scalars. Do you want to try adding one?

**Comment by cpunion** [comment]
I have a complex project to test, so I can try to fix some cases. Because Upgrader is implemented by RegExp, I feel is't hard to make it works "perfectly". E.g. currently, many matching just allow one space delimiter, and ignore wrap line.

**Comment by cpunion** [comment]
Field's resolve property doesn't converted:

> undefined method `resolve' for #<GraphQL::Schema::Field::FieldProxy:0x007f9a6efc6998>

@rmosolgo How to convert a field with `argument`? I'm not found in docs.

```ruby
field :project, Types::ProjectType, null: true do
    description 'Query my project by ID'
    argument :id, ID, null: false
    resolve Resolvers::Project.new
  end
```

**Comment by cpunion** [comment]
Found. But doesn't pretty.

```ruby
field :project, Types::ProjectType, 'Query my project by ID',
  null: true,
  resolve: ->(obj, args, ctx) {
    ctx[:current_user].project.find(args[:id])
  } do
    argument :id, ID, required: true
  end
```

**Comment by rmosolgo** [comment]
I think these cases are covered in 1.8-dev now: 

- Arguments are upgrade automatically 
- Resolve procs are moved to methods 
- You can replace the `< BaseObject` with whatever class name you need, for example: 

  ```ruby 
      # Replace the default one with a custom one:
      type_transforms = GraphQL::Upgrader::Member::DEFAULT_TYPE_TRANSFORMS.map { |t|
        if t == GraphQL::Upgrader::TypeDefineToClassTransform
          GraphQL::Upgrader::TypeDefineToClassTransform.new(base_class_pattern: "Platform::\\2s::Base")
        else
          t
        end
      }
      upgrader = GraphQL::Upgrader::Member.new(original_text, type_transforms: type_transforms, field_transforms: field_transforms)
      upgrader.upgrade
  ```

If you give it another try and find any problems, please open a new issue!
