### ISSUE TITLE
hasNextPage reports true when using last: qualifier

### ISSUE THREAD

**Issue by geneeblack** [rmosolgo/graphql-ruby#1180]
When retrieving last:1...n from a RelationConnection I am receiving a hasNextPage:true on PagingInfo. I've got bidirectional-paging set to true and can't think of a case where

https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/relay/relation_connection.rb#L30

would return anything other than false. I've done some preliminary testing but may not be correctly thinking about all cases. It appears to work when using a before/after cursor qualifier in conjunction with :last. Is there some other case that I'm not thinking of when this would not return false when using a last: qualifier?

#1181

**Comment by daemonsy** [comment]
Hi, I'm helping to close out issues. It seems like the PR is closed and there's been no further discussion for a while. 

I'm closing it, let me know if you'd like to reopen it.
