### ISSUE TITLE
How to create a custom input field in relay mutations?

### ISSUE THREAD

**Issue by syedanees15** [rmosolgo/graphql-ruby#1182]
I want to use a custom argument(input field) for Relay mutations which will convert an externalID from the client to an object. 

Added following declaration to the schema file:
```ruby
GraphQL::Relay::Mutation.accepts_definitions(workspace_id_argument: AssignWorkspaceIdArgument)
```

Prepare function is part a module:
```ruby
module AssignWorkspaceIdArgument
  def self.call(target, *args, **kwargs, &block)
    argument = GraphQL::Define::AssignArgument.call(target, *args, **kwargs, &block)
    argument.type = !GraphQL::ID_TYPE
    argument.as = :workspace
    argument.prepare = -> (workspace_external_id, ctx) {
      workspace = Workspace.where(external_id: workspace_external_id).first
      return workspace if workspace.present
      ::GraphQL::ExecutionError.new("Invalid workspace ID")
    }
  end
end
```

usage:
```ruby
module Mutations
  ArchiveTransaction = GraphQL::Relay::Mutation.define do
    name "ArchiveTransaction"
    workspace_id_argument :workspace_id
    return_field :archived_transaction_count, types.Int
    resolve -> (obj, inputs, ctx) {
      # resolver code
    }
  end
end
```

I implemented above by looking at https://github.com/rmosolgo/graphql-ruby/issues/685 where we do this for queries.  

This seems to work, but I am not sure if this is the right approach.  Am I doing this right?

Using graphql(V1.7.4) & graphiql-rails(v1.4.7) on Rails 5

Thanks,
Anees

**Comment by rmosolgo** [comment]
Looks good to me! Are you having any trouble with it?

**Comment by syedanees15** [comment]
@rmosolgo  It works but wasn't sure if this was the right approach. Closing this issue.

Thank You
