### ISSUE TITLE
Caching GraphQL Documents inadvertently swallows parse errors

### ISSUE THREAD

**Issue by clader** [rmosolgo/graphql-ruby#1184]
Hi, I recently implemented graphql-ruby Document Caching as outlined here by @xuorig 
[http://mgiroux.me/2016/graphql-query-caching-with-rails/](http://mgiroux.me/2016/graphql-query-caching-with-rails/)

It works great (thx Marc-Andre!!), but has one unforeseen side-effect (not really sure if this is a bug, or just an inconvenience).

The Caching Code from Marc-Andre as written: 
```Ruby
class DirGraphqlController < ApplicationController
	def query
		query_string = params[:query]
		query_variables = params[:variables] || {}
		document = get_document(query_string)

		result = DirSchema.execute(
			document: document,
			variables: query_variables
		)

		render json:result
	end

 def get_document(query_string)
    cache_key = Base64.encode64(query_string)
	Rails.cache.fetch(cache_key) do
	GraphQL.parse(query_string)
	end
  end

end
```

... has the side effect of swallowing query parsing (and possibly other) errors that are normally exposed as handled exceptions when simply using Schema.execute.

For instance, when caching Documents this way if you are missing a closing bracket in your query, instead of getting a nicely formatted Graphql::ExectionError, we get:
`SyntaxError: Unexpected token < in JSON at position 0`

I wrote the following (admittedly clunky) work around to catch parse errors, but I think there are other error situations that might get swallowed by using parse separate from execute:
```Ruby
class DirGraphqlController < ApplicationController
	def query
		query_string = params[:query]
		query_variables = params[:variables] || {}
		document, errMsg = get_document(query_string)

		if document
			result = DirSchema.execute(
			document: document,
			variables: query_variables
			)
			render json:result
		else
			errHash = { "errors" => ["message" => errMsg]}
			render json:errHash
		end
	end

	def get_document(query_string)
		cache_key = Base64.encode64(query_string)
		Rails.cache.fetch(cache_key) do
			begin
				return GraphQL.parse(query_string), true
			rescue Exception => e  
				errMsg = "Graphql Document Parse Exception: #{e.message}"
				Rails.logger.error errMsg 
				return false, errMsg 
			end 		
		end
	end
end
```

I'm guessing there is for sure a more graceful way to handle this without altering the graphql-ruby code base, but also perhaps there is a way to allow GraphQL.parse, to gracefully raise an error to Schema.execute?  

Thanks
~Calder

**Comment by 34code** [comment]
@clader why not change the `get_document` to take in more variables?

and then passing this in the non-cached case..
```Schema.execute(query, variables: variables, context: context, operation_name: operation_name)```

after which you would ONLY add to cache if the schema.execute did not return an error..
and queries which error out would report to your error tracking system.

another option would be to do a catch-all where ALL errors point to same "error_key" in cache and just returning the default "error document" in case of an error in production. Instead of a catch-all it might also be possible to pre-define common "error-docs" based on the type of error encountered by the rescue block.

**Comment by rmosolgo** [comment]
Closed as third-party issue
