### ISSUE TITLE
Transform field name on fly

### ISSUE THREAD

**Issue by quolpr** [rmosolgo/graphql-ruby#1190]
Is it possible to add middleware, that will be transforming on fly field name from `field :engine_name` to `engineName`?

**Comment by rmosolgo** [comment]
Sorry, not in 1.7, but it will be possible in 1.8 which is currently available on rubygems as a `pre`: 

https://github.com/rmosolgo/graphql-ruby/blob/1.8-dev/guides/schema/class_based_api.md#customizing-fields

In fact, with class-based type definitions in 1.8, the naming transformation you're describing is the default behavior :)

**Comment by quolpr** [comment]
Wow, thank you!
