### ISSUE TITLE
Rails engine and type merge

### ISSUE THREAD

**Issue by jasonbuehler** [rmosolgo/graphql-ruby#1194]
Hi, this isn't really an issue but I am not sure what to do so I thought I would post here and see if there were any suggestions or ideas. I have an engine with a basic set of resources that I want to make available to my api. These resource definitions are all managed in the engine. I use this engine to integrate this basic resource set into multiple apps. I have query and mutation types defined in the engine, as well as the controller/route for graphql. I want to be able to define query and mutation types on the implementing apps for their unique api needs while bringing in the shared type definitions as well. I saw in another issue that there was class/module based DSL in the works so if that were to happen I think I could accomplish what I am trying to do pretty easily. 

Is there a clean way to merge or combine multiple query or mutation types? 

Thanks, sorry in advance if this isn't the place to post this question.

**Comment by rmosolgo** [comment]
In 1.8+, type definitions will be "plain ol'" Ruby classes, so you could put the shared code inside an `ActiveSupport::Concern`, for example: 

```ruby 
module QueryFieldsInEngine 
  included do 
    field ... 
    field ... 
  end 
end 

# ... 

class Query < GraphQL::Schema::Object 
  include QueryFieldsInEngine
end 
```

1.8 is on rubygems as a prerelease and documented here: https://github.com/rmosolgo/graphql-ruby/blob/1.8-dev/guides/schema/class_based_api.md

Feel free to give it a try and open an issue if you find any bugs or other hangups!

**Comment by jasonbuehler** [comment]
Thanks Robert, I will give it a shot. 1.8 definitely looks like it should be able to achieve what I am looking to do.
