### ISSUE TITLE
Handling Errors documentation issue

### ISSUE THREAD

**Issue by samirph** [rmosolgo/graphql-ruby#1197]
About these docs: https://github.com/rmosolgo/graphql-ruby/blob/master/guides/queries/error_handling.md
At "Error Handling with Wrappers" in that following line:
`messages = e.record.errors.full_messages.join("\n")`
Should be 
`messages = err.record.errors.full_messages.join("\n")`
My application kept raising errors and I didn't know why.
I tried to create a new branch, fix it and make a pull request, but I don't have permissions to push any branch. :)

**Comment by Willianvdv** [comment]
Hey @samirph, thanks for letting us know there's an error in the docs! Do you know GitHub allows you to make edits on their website?

![graphql-ruby_error_handling_md_at_master_ _rmosolgo_graphql-ruby](https://user-images.githubusercontent.com/102915/34212051-50f5fc7a-e59b-11e7-993c-71febed3c10f.png)

Please let me know if it doesn't work for you and I'll create the PR for you!

**Comment by samirph** [comment]
It worked and I created a pull request :)

**Comment by Willianvdv** [comment]
#1198
