### ISSUE TITLE
Boolean type not working properly

### ISSUE THREAD

**Issue by dkumar431** [rmosolgo/graphql-ruby#1199]
In my postgresql, I have set column datatype to boolean and same for graphql type also.

```ReleaseType = GraphQL::ObjectType.define do
    name "release"
  description "A release"

  global_id_field :id

  field :id, !types.ID
  field :name, types.String
  field :description, types.String
  field :starts_at, DateType
  field :status, types.Boolean
end
```

Mutations seems to be working fine , but query always return "true" even if the status is false.

```query{
  releases{
    edges{
      node{
        id
        description
        status
      }
    }
  }
}
```

**Comment by Willianvdv** [comment]
That's strange, are you sure your parent resolver does return an object with status set to false and is not dealing with some stale object?

**Comment by dkumar431** [comment]
Yes it does return correctly. After hours of frustration , I am finally able to resolve the issue by renaming status column to `is_active`. Not sure what was the issue. May be some special meaning for `status`

**Comment by Willianvdv** [comment]
Weid, AFAIK status isn't some special field in this gem. My best guess it's related to the ORM you're using. I'll close this issue for now, but please let us know if you're running into this issue again/
