### ISSUE TITLE
Library does not follow ruby naming conventions

### ISSUE THREAD

**Issue by felixbuenemann** [rmosolgo/graphql-ruby#12]
The library is split up across several directories, but does not follow the naming conventions associated with that.

Example:
`GraphQL::ObjectType` should be at `lib/graph_ql/object_type.rb`, but it is at `lib/graph_ql/types/object_type.rb`, which would suggest `GraphQL::Types::ObjectType`.

Not following conventions makes it harder for developers and tooling to understand the code structure.

**Comment by rmosolgo** [comment]
Yeah, sorry, I totally hear that. It's basically the result of shifting off of activesupport but not finishing the reordering. I'll try'n clean it up this week, moving everything to the right place according to its name!

It's pretty annoying that a lot of the folders are just arbitrary :(

**Comment by rmosolgo** [comment]
how about this? 5951b7a671a7660437636df166fcf8f491c02595

**Comment by felixbuenemann** [comment]
That looks much more straightforward. If you would like to keep the types grouped together in their own directory you could probably do something like GraphQL::Types::Scalar and have it inside  lib/graph_ql/types/scalar.rb.

**Comment by rmosolgo** [comment]
Yeah, that's something to think about!
