### ISSUE TITLE
GraphQL subscriptions example available?

### ISSUE THREAD

**Issue by cebartling** [rmosolgo/graphql-ruby#1203]
The development group I am working with has been using `graphql-ruby` for a couple of months now to build out a GraphQL API. The gem has proven very valuable for this query-only API. We're now investigating how to do asynchronous API invocations. We have a webhook system working, but for many clients, the webhook system won't work. So we're looking at GraphQL subscriptions to stream results back to these clients via a WebSocket connection. We tried to build a spike solution using `graphql-ruby` version 1.7.7 and followed all the documentation that is available around setting up an ActionCable-implementation of GraphQL subscriptions. Our spike solution client is a React SPA using Apollo Client 2.0.4. 

I have verified that the ActionCable connectivity is working between the web application and the Rails server in this spike solution. That was fairly straightforward. The part that isn't working is the GraphQL subscription piece sitting on top of ActionCable. 

I was wondering if there's any public examples of GraphQL subscriptions that utilize `graphql-ruby` gem for this functionality.

**Comment by rmosolgo** [comment]
I don't know of any full-blown public examples, but you could see who else has given it a try by looking at the contributors to the subscription implementation: https://github.com/rmosolgo/graphql-ruby/commits/master/lib/graphql/subscriptions/action_cable_subscriptions.rb

Also, you could ask around on Slack! https://graphql-slack.herokuapp.com/

**Comment by cebartling** [comment]
@rmosolgo We did end up building a small demo of GraphQL subscriptions. The web client is React and Apollo Client 2.x and there are two servers: one is Express and Apollo Server and the other is Ruby on Rails 5.1, ActionCable and graphql-ruby. Instructions in the GitHub repositories. The repository is open to the public. Feel free to comment. 

https://github.com/SenteraLLC/graphql-subscriptions-spike

**Comment by rafaelsales** [comment]
@cebartling thanks for sharing that? Just curious: Did you guys go for it?

**Comment by cebartling** [comment]
@rafaelsales Indeed we did go for subscriptions using the `graphql-ruby` gem! We have one GraphQL subscription currently going to production, but we're looking to migrate away from Firebase Real-time Database and it's WebSocket-based access and towards GraphQL with subscriptions. Much more flexibility afforded to you by using GraphQL on Rails. We used Apollo Client 2.0 and `react-apollo` on the client. Overall a great user experience, once everything is wired up correctly.

**Comment by rafaelsales** [comment]
@cebartling that's great to hear. I was doing spike on this as well, your repo is certainly very helpful! Thanks!

**Comment by Conturbo** [comment]
@cebartling did `actioncable`  give you issues with **server-side rendering**? If so, how did you solve it? I'm getting:
(i'm also using React Apollo + GraphQL + Rails )
```
WebSocket: window.WebSocket,
           ^
...
ReferenceError: window is not defined
```

In general, I'm not sure how to **best** handle `window`/`document` *reference errors*. To solve it, I kind of just put bandaids everywhere.

Currently, I just wrap them in **conditionals**, but this *doesn't work* for **third-party code**. How can I get around these errors caused by *third-party code* like `actioncable`?

I tried adding `global.window = {};` in my **server.js**, but it never works =[.

In general, is there a better (or **best**) way? Can I just add 1-5 magic lines to my `webpack.config` and never get `window`/`document` errors again?

*And of course...* Thanks for your demo, it helped out a lot.

**Comment by tambakoo** [comment]
> @rmosolgo We did end up building a small demo of GraphQL subscriptions. The web client is React and Apollo Client 2.x and there are two servers: one is Express and Apollo Server and the other is Ruby on Rails 5.1, ActionCable and graphql-ruby. Instructions in the GitHub repositories. The repository is open to the public. Feel free to comment.
> 
> https://github.com/SenteraLLC/graphql-subscriptions-spike

Late to the party. Have you moved this somewhere or taken this off altogether ?

**Comment by cebartling** [comment]
@tambakoo I don't work with Sentera anymore, so they may have taken the spike solution down. I don't have access to the referenced repository anymore.

**Comment by guyzmo** [comment]
FYI, the repository is still there on github, as someone forked it, and it was a very good base to get started: https://github.com/mlwilkerson/graphql-subscriptions-spike/

thank you @tambakoo for the original share and thank you @mlwilkerson for keeping it around 😉
