### ISSUE TITLE
1.8.0.pre2 input arguments not being converted to snake_case

### ISSUE THREAD

**Issue by bmcdaniel11** [rmosolgo/graphql-ruby#1204]
@rmosolgo , first off, thank you so much for this conversion! I have spent the last few days getting our project converted over to the class-based api and have had no issues up until this point. I saw several issues close to this, and it may have been resolved, but I haven't seen it yet so I thought I'd mention it.

I have a mutation set up in the form of a function
```ruby
class BaseMutation < GraphQL::Schema::Object
      field :create_contact, Types::Contact, function: Mutations::Contact::Create.new, null: false
end

module Mutations
    module Contact
      class Create < GraphQL::Function
        argument :first_name, !types.String
        argument :last_name, !types.String
        argument :affiliation, AffiliationInput

        def call(obj, args, ctx)
          ...
        end
      end
    end
  end
```

And have an InputObject like so
```ruby
 class AffiliationInput < GraphQL::Schema::InputObject
      argument :id, Integer, required: false
      argument :title, String, required: false
      argument :org_name, String, required: false
end
```

Upon submitting the following:
```
mutation ContactMutations {
            createContact(
              first_name: "Billy",
              last_name: "Kid",
              affiliation: 
                {
                  org_name: "The Wild West"
                }
            )
              {
                firstName,
                lastName,
                affiliation {
                  id,
                  orgName
                }
              }
          }
```
I am getting an error telling me `org_name` does not exist on AffiliationInput. Upon introspection of the schema, I see this
```
{
          "kind": "INPUT_OBJECT",
          "name": "AffiliationInput",
          "description": null,
          "fields": null,
          "inputFields": [
            {
              "name": "id",
              "description": null,
              "type": {
                "kind": "SCALAR",
                "name": "Int",
                "ofType": null
              },
              "defaultValue": null
            },
            {
              "name": "title",
              "description": null,
              "type": {
                "kind": "SCALAR",
                "name": "String",
                "ofType": null
              },
              "defaultValue": null
            },
            {
              "name": "orgName",
              "description": null,
              "type": {
                "kind": "SCALAR",
                "name": "String",
                "ofType": null
              },
              "defaultValue": null
            },
          ],
          "interfaces": null,
          "enumValues": null,
          "possibleTypes": null
        },
```

So it appears it is converting my snake_case input argument `org_name` into camelCase `orgName`, something not seen on a regular argument. I'm assuming this isn't expected behavior based on `first_name` and `last_name` not being converted this way. Is this an issue?

**Comment by eapache** [comment]
IIRC the intent was to convert snake_case to camelCase everywhere, so the issue is that `first_name` and `last_name` are getting missed somehow.

**Comment by swalkinshaw** [comment]
Have a hunch it's due to the usage of `GraphQL::Function` which isn't really part of the newer class-based API so it's missing those case conversions.

**Comment by bmcdaniel11** [comment]
I can understand converting snake case to camelCase on a query, but it seems odd to convert them for input arguments. That would mean you would be working with camelCase arguments in your ruby code, which isn't right.

**Comment by swalkinshaw** [comment]
The intention is to only convert to camelCase in the schema itself. Everything in Ruby land is automatically called (and converted) as snake_case.

So you define everything as snake_case, access keys like that, call methods etc. But in the GraphQL schema itself, they are camelCase.

**Comment by bmcdaniel11** [comment]
So ideally, `first_name` and `last_name` should be sent as `firstName` and `lastName` for the mutation, is that correct? And that `org_name` is actually working as intended?

**Comment by swalkinshaw** [comment]
Here's how the schema and query *should* look (assuming it all works correctly):

```ruby
class BaseMutation < GraphQL::Schema::Object
  field :create_contact, Types::Contact, null: false do
    argument :first_name, !types.String
    argument :last_name, !types.String
    argument :affiliation, AffiliationInput
  end

  def create_contact(first_name:, last_name:, affiliation: nil)
    # resolve etc
  end
end

class AffiliationInput < GraphQL::Schema::InputObject
  argument :id, Integer, required: false
  argument :title, String, required: false
  argument :org_name, String, required: false
end
```

```graphql
mutation ContactMutations {
  createContact(
    firstName: "Billy",
    lastName: "Kid",
    affiliation: { orgName: "The Wild West" }
  ) {
    firstName
    lastName
    affiliation {
      id
      orgName
    }
  }
}
```

I got rid of the function usage just to demonstrate this inline.

**Comment by bmcdaniel11** [comment]
Okay, gotcha. I tried it with `firstName` and `lastName` and got errors because it doesn't convert it to snake_case. I agree, I think it's the `GraphQL::Function`. I didn't realize that wasn't part of the class-based api changes. Let me see if it works how you described and get back to you.

**Comment by swalkinshaw** [comment]
If you want a hybrid solution, you could do:

```ruby
class BaseMutation < GraphQL::Schema::Object
  field :create_contact, Types::Contact, null: false, resolve: Mutations::Contact::Create.new do
    argument :first_name, !types.String
    argument :last_name, !types.String
    argument :affiliation, AffiliationInput
end

module Mutations
  module Contact
    class Create
      def call(obj, args, ctx)
        ...
      end
    end
  end
end
```

**Comment by bmcdaniel11** [comment]
@swalkinshaw Thanks for the hybrid solution, that may be what I go with. I tried the way it is intended with the new class-based style (the first one you posted, as it _should_ be) and it didn't work. It's not converting my camelCase arguments into snake_case.

**Comment by bmcdaniel11** [comment]
Now that I know the intended scenario, I'll keep digging and see what I can find

**Comment by bmcdaniel11** [comment]
Ok so I stripped my project down to nothing but a mutation and I did see that using
```ruby
class BaseMutation < GraphQL::Schema::Object
  field :create_contact, Types::Contact, null: false do
    argument :first_name, !types.String
  end

  def create_contact(first_name:)
    # resolve etc
  end
end
```
works. I got rid of that and added back in your suggested hybrid approach
```ruby
class BaseMutation < GraphQL::Schema::Object
  field :create_contact, Types::Contact, null: false, resolve: Mutations::Contact::Create.new do
    argument :first_name, !types.String
  end
end

module Mutations
  module Contact
    class Create
      def call(obj, args, ctx)
        ...
      end
    end
  end
end
```
and the `args` I was getting was a class containing my argument values...as `firstName`. So I am getting my arguments, but they aren't being transformed.

 I looked at the differences in defining a resolve function vs using the public send on the field name and I found the dynamic resolve uses the `public_method_send` within `GraphQL::Schema::Field::DynamicResolve` and using a custom resolve, or function, uses `call` within `GraphQL::Schema::Field::UnwrappedResolve`. The reason my args aren't being converted to snake case is because `public_send_method` in `DynamicResolve` uses 
```ruby
...
graphql_args.keys.each do |key|
  ruby_kwargs[Schema::Member::BuildType.underscore(key).to_sym] = graphql_args[key]
end
...
```
and the `call` method in `UnwrappedResolve` does not do this. 

So my question is this: should `call` in `UnwrappedResolve` transform our arguments, or is the lack of transforming them done on purpose?

**Comment by bmcdaniel11** [comment]
Also, I just confirmed `InputType` arguments do not get converted to snake_case, even when using the `DynamicResolver`

**Comment by swalkinshaw** [comment]
🤔  that's tough to say. Ideally they'd be the same for consistency, but those two kinds of resolvers could have very different use cases right now.

If someone was migrating from the DSL to the class-based APIs, they might keep their `resolve` procs which would use the camelCase args. Any auto transformation would break that.

If the pattern of separating mutations into individual resolvers is an important/popular one, maybe there should be a new class-based way of doing that.

There would be two options:

1. make `Function` work with the new transforms (or a new alternative)
2. allow a field to set a `class` option? 

```ruby
class BaseMutation < GraphQL::Schema::Object
  field :create_contact, Types::Contact, null: false, class: Mutations::Contact::Create do
    argument :first_name, !types.String
  end
end

module Mutations
  module Contact
    class Create
      def create_contact(first_name:)
        # resolve
      end
    end
  end
end
```
But then we'd have a ton of ways to set the resolver on a field: `field`, `resolve`, `function`, `class`, and finally class-based methods.

**Comment by bmcdaniel11** [comment]
Okay, that makes sense. Perhaps this is something to be revisited once the update decides to break support for existing structure (IMO should be 2.0 release) and maybe not even necessary when that happens. I kept this open in case it was something that needed discussing. I'll close it for the mean time and if it still is a problem in the (roadmapped as 1.10 release) 2.0 release, we can reopen to discuss futher. Thanks for your help on this @swalkinshaw!
