### ISSUE TITLE
Errors raised in field instrumentation should stop execution; data and errors should be mutually exclusive

### ISSUE THREAD

**Issue by phaedryx** [rmosolgo/graphql-ruby#1209]
As noted [here](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/query/executor.rb#L17) the expectation is that a response will be either data *or* errors. This is violated when you raise errors in field instrumentation, as seen in [this gist](https://gist.github.com/rmosolgo/86e6104067f88d109f12e2802722f34c). It still returns data, but the data is nulled and the errors are repeated.

The errors are [rescued here](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/execution/execute.rb#L109) and [passed along](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/execution/execute.rb#L130) where it is [handled here](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/execution/execute.rb#L141) and [here](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/execution/execute.rb#L175).

Rather than logging the errors, returning `nil`s, and continuing, the behavior I would expect is that when it an error is encountered it would stop completely and return the error.

**Comment by phaedryx** [comment]
<img width="342" alt="screen shot 2017-12-28 at 4 30 28 pm" src="https://user-images.githubusercontent.com/288994/34447340-1165fb8a-eca0-11e7-8d46-f1ab250d0caa.png">

**Comment by phaedryx** [comment]
<img width="392" alt="screen shot 2017-12-28 at 4 30 48 pm" src="https://user-images.githubusercontent.com/288994/34447347-1b9a660e-eca0-11e7-9cb4-51c1aa15374f.png">

**Comment by phaedryx** [comment]
The above images are screenshots from a graphiql session, demonstrating what I'm referring to.

**Comment by thefliik** [comment]
Hmm, well that comment you point out in the source does confuse things, but from the [graphql spec](http://facebook.github.io/graphql/October2016/#sec-Response), the current behavior seems both desirable and allowed:

> A response may contain both a partial response as well as encountered errors in the case that an error occurred on a field which was replaced with null.

Continuing execution after errors, where possible, makes it easier for a dev to fix everything. If there are multiple errors with a request, but you only return the first, then the dev would fix one error, send the request again, get another error, fix it, send the request again, etc. 

In your case, it happens to be that you have the same error on multiple fields making it seem less helpful.

**Comment by phaedryx** [comment]
@thefliik what I'm trying to accomplish is halting execution to limit the number of results. That is, if the number of results looks like it will be too high, return a single "result count exceeded" error.

You're right, though. The current behavior follows the spec.

**Comment by thefliik** [comment]
@phaedryx, I believe you could accomplish that with a [graphql query analyzer](http://graphql-ruby.org/queries/analysis.html)
