### ISSUE TITLE
can't generate in Rails_API only

### ISSUE THREAD

**Issue by Antoine007** [rmosolgo/graphql-ruby#1210]
Hi,

From what I see, you can't `generate graphql:install` if your rails app is `--api` only. 
Works nicely if you add the files manually. Why is it the case?

Thanks!

ruby 2.5.0
rails 5.1.4
graphql 1.7.7

**Comment by rmosolgo** [comment]
I'm not sure about this. Please give it a try, and if you encounter an error, please post the full message and stack trace here, then we can look into it!
