### ISSUE TITLE
connection_type and nulls

### ISSUE THREAD

**Issue by sporto** [rmosolgo/graphql-ruby#1217]
When I use `connection_type` it creates `edges` and `node` as nullable fields. 

```
          {
            "name": "edges",
            "description": "A list of edges.",
            "args": [

            ],
            "type": {
              "kind": "LIST",
              "name": null,
              "ofType": {
                "kind": "OBJECT",
                "name": "AwsAccountOrOnboardingEdge",
                "ofType": null
              }
            },
            ...
          },
```

Does this make sense? I don't see why these should be null. Maybe the edges does, not sure.
At least shouldn't `node` be `NOT_NULLABLE`?

**Comment by rmosolgo** [comment]
It looks like `edges` is nullable according to the spec: https://facebook.github.io/relay/graphql/connections.htm#sec-Edges

But `node` may be a non-null type: https://facebook.github.io/relay/graphql/connections.htm#sec-Node

I'm open to supporting non-null `node` fields, but I don't think we should change the default behavior.

**Comment by eapache** [comment]
FWIW the vast majority of our connections use non-null nodes. In fact any field we create that is a list defaults to the inner wrapped element being non-null unless otherwise specified.

**Comment by thefliik** [comment]
While it certainly makes sense that a connection object, in general, could have nullable edges/nodes, for the `connection_type` helper method, specifically, does it make sense? My understanding of the `connection_type` method, is that you provide it with a list of nodes and then it creates the edges (and connection object) around those nodes. In this case, an edge will always have a node and the `edges` field itself will always return a list (which may be empty).

**Comment by sporto** [comment]
For a bit more context. We are using Elm for our front end. We started using a library that generates types from our graphql schema. So at the moment for a connection we get something like:

```
List (Maybe { node = Maybe Thing} )
        ^ edge                 ^ node
```
Having to deal with these nullables in the FE is harder than it should be. We would like to be able to specify a `connect_type` where nothing is null. So we can end up with:

```
List { node = Thing }
```

Thanks

**Comment by petrbela** [comment]
This is not an issue just with Elm but also TypeScript/Flow or any other type system.

There's a similar discussion for [graphql-relay-js](https://github.com/graphql/graphql-relay-js/issues/185). Specifically, it reiterates that [edges are always nullable while nodes can be non-null](https://github.com/graphql/graphql-relay-js/issues/185#issuecomment-387923487), and that [nullability is required in case of an error](https://github.com/graphql/graphql-relay-js/issues/185#issuecomment-387925025).

I originally came here to +1 for making the edges non-null but now I'm not so sure. As for nodes, I think those should still be non-nullable.

**Comment by petrbela** [comment]
For those looking to make everything non-null in their app:

```rb
class Types::BaseConnection < GraphQL::Types::Relay::BaseConnection
  def self.edge_type(edge_type_class, edge_class: GraphQL::Relay::Edge, node_type: edge_type_class.node_type, nodes_field: true)
    # Set this connection's graphql name
    node_type_name = node_type.graphql_name

    @node_type = node_type
    @edge_type = edge_type_class

    field :edges, [edge_type_class],
      null: false,
      description: "A list of edges.",
      method: :edge_nodes,
      edge_class: edge_class

    field :nodes, [node_type],
      null: false,
      description: "A list of nodes." if nodes_field

    description("The connection type for #{node_type_name}.")
  end
end

class Types::BaseEdge < GraphQL::Types::Relay::BaseEdge
  description "An edge in a connection."

  class << self
    # Get or set the Object type that this edge wraps.
    #
    # @param node_type [Class] A `Schema::Object` subclass
    def node_type(node_type = nil)
      if node_type
        @node_type = node_type
        field :node, node_type, null: false, description: "The item at the end of the edge."
      end
      @node_type
    end
  end

  field :cursor, String,
    null: false,
    description: "A cursor for use in pagination."
end
```

And finally hook them up in your `BaseObject`:

```rb
class Types::BaseObject < GraphQL::Types::Relay::BaseObject
  connection_type_class Types::BaseConnection
  edge_type_class Types::BaseEdge
end
```

**Comment by audiolion** [comment]
While I think @petrbela 's solution works, I would rather have official support for this before using it. That being said, there probably needs to be liberal warnings about the tradeoffs that you are making when using non-null types [[1]](https://medium.com/@calebmer/when-to-use-graphql-non-null-fields-4059337f6fc8), namely:

- Impacts ability to evolve schema (removing fields is now a breaking change as clients expect it to be non-null)
- Errors propagate higher, e.g. if a node is missing the whole edge fails

**Comment by rmosolgo** [comment]
I don't have plans to add more support in this area. The built-in classes provide inspiration for your own connection types, which aren't too hard to build, and you could even extend those built-ins. Please let me know if you try it and run into trouble!

**Comment by acoffman** [comment]
For anyone that stumbles upon this issue in 2021 like I just did, there are now configuration options that control this behavior in the `ConnectionBehaviors` module so you no longer have to override the node and edges fields manually.

If you mix it into your custom or base connection you can simply call `edge_nullable(false)` (or edges, or nodes) when defining your connection. Some documentation here: https://graphql-ruby.org/api-doc/1.12.8/GraphQL/Types/Relay/ConnectionBehaviors/ClassMethods.html

```
module Types
  class BaseConnection < Types::BaseObject
    include GraphQL::Types::Relay::ConnectionBehaviors

    edges_nullable(false)
    edge_nullable(false)
    node_nullable(false)
  end
end
```

**Comment by danielwaltz** [comment]
@acoffman Thank you for sharing this! Also a note for people like me who tried this and weren't sure why it wasn't working, make sure you check the version of `graphql` you are using is at least `1.12.6` (ideally later). It is a fairly recently feature.

https://github.com/rmosolgo/graphql-ruby/blob/master/CHANGELOG.md#1126-11-march-2021

**Comment by pfilipow** [comment]
Hi @tagrudev 

Make sure you are calling `node_nullable` in the base Edge type, not just the base Connection, e.g.:
```ruby
module Types
  class BaseEdge < Types::BaseObject
    # add `node` and `cursor` fields, as well as `node_type(...)` override
    include GraphQL::Types::Relay::EdgeBehaviors
    node_nullable(false)
  end
end
```
