### ISSUE TITLE
Code style: `hash_key` vs `as`

### ISSUE THREAD

**Issue by KevinColemanInc** [rmosolgo/graphql-ruby#1221]
Why are there two different things that basically mean the same thing?  Could we just pick one and use it everywhere instead?

**Comment by Willianvdv** [comment]
You can use `as` like:
```ruby
# `as` on a field's argument 
field :post, PostType do
  argument :postId, types.Id, as: :id
end
```

and `hash_key` like:
```ruby
# `hash_key` as the field's resolver
field :firstName, types.String, hash_key: :first_name
```

Your proposal is to remove `hash_key:` or `as:`?

**Comment by KevinColemanInc** [comment]
I am thinking they both basically have the same functionality: map a GraphQL value to a ruby style, so why not call them the same name?

**Comment by xuorig** [comment]
There's a slight difference here @KevinColemanInc 

`hash_key` automatically calls `obj[hash_key]` for the resolver. https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/field/resolve.rb#L14

`as` only transforms the name of the argument. So you can get it using `args[as]` in the resolver.

**Comment by KevinColemanInc** [comment]
`fields` and `arguments` are just names for the output and input attributes of graqhql, right?

`obj` and `args` are the output and input hashes you manipulate in the business logic of mutations and queries.

`hash_key` seems to serve the same purpose for both input and output of graphql, though?  They both transform the `argument` or `field_name` to a different key.

**Comment by rmosolgo** [comment]
It suits me to keep the two separate options, as mentioned above, `as:` renames an incoming value; `hash_key:` is a short-cut for defining resolve behavior. I'm willing to be outvoted if anyone else supports a rename!
