### ISSUE TITLE
Cursors breaking connection in upgrade from 1.6.7 to 1.7.7

### ISSUE THREAD

**Issue by kleinjm** [rmosolgo/graphql-ruby#1237]
Using `connection` the following query gets generated

    SELECT  users.*, 
    users.FIELD(users.id AS cursor_0, users.7106261) AS cursor_1, 
    users.id AS cursor_2 
    FROM `users` 
    WHERE `users`.`id` = 7106261 
    ORDER BY FIELD(users.id, 7106261), `users`.`id` ASC LIMIT 11

I'm seeing `Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax...`
I saw the changelog https://github.com/rmosolgo/graphql-ruby/blob/caeb995da53fb71cecaef22ca5c96cfbdbb35247/CHANGELOG-pro.md#bug-fix-5
and the discussion here https://github.com/rmosolgo/graphql-ruby/issues/1076 but it's not even hitting my `total_count` implementation. FWIW my implementation is using `.size` but that doesn't seem to be the issue anyway.

      connection :pymk_recommendations, connection_type_with_count(
        Gql::Types::Colleague, :pymk_recommendations
      ) do
        resolve ->(profile, args, ctx) {
          # some service that returns an array (not AR relation) of users
        }
      end

      def connection_type_with_count(type, relation_name)
        type.define_connection do
          name "Profile#{relation_name.to_s.camelize}ConnectionWithCount"
          field :total_count do
            type types.Int
            resolve ->(obj, _, _) {
              obj.nodes.size
            }
          end
        end
      end

Outside GQL the service generates this query

    SELECT `users`.* FROM `users` WHERE `users`.`id` = 7106261 ORDER BY FIELD(users.id, 7106261)

**Comment by rmosolgo** [comment]
I just released `graphql-pro` version `1.6.3` which should fix this issue, could you give that version a try?

**Comment by kleinjm** [comment]
@rmosolgo thanks for the help. Our company is currently on a retreat and code freeze but I will try it and verify when we get back.

**Comment by kleinjm** [comment]
@rmosolgo looks like that did it. Thanks a ton for the fix and fast reply
