### ISSUE TITLE
Example of rails to rails graphql implementation

### ISSUE THREAD

**Issue by mmahalwy** [rmosolgo/graphql-ruby#1238]
All the examples are mostly for client to api (rails). Is it possible to generate a query from a rails service using this gem to another rails/other service? Can this gem create those queries and mutations?

Thanks!

**Comment by rmosolgo** [comment]
This library has tools for building a GraphQL server, but nothing for building GraphQL clients! Maybe you could take a look at: https://github.com/github/graphql-client

**Comment by mmahalwy** [comment]
Fantastic! Thanks @rmosolgo !
