### ISSUE TITLE
Trying to use a union, getting "Unable to autoload constant Types::MutationType"

### ISSUE THREAD

**Issue by bbugh** [rmosolgo/graphql-ruby#1245]
I'm getting a confusing error while trying to use a UnionType for a polymorphic model association:

`LoadError - Unable to autoload constant Types::MutationType, expected .../app/graphql/types/mutation_type.rb to define it:`

I have just run the rails `graphql:install` and have made a small number of changes to try to test out our use case. (`Group` has a polymorphic column that can be a number of different things) .

```ruby
# app/graphql/types/query_type.rb
Types::QueryType = GraphQL::ObjectType.define do
  name "Query"
  # Add root-level fields here.
  # They will be entry points for queries on your schema.

  field :groups, types[Types::GroupType] do
    resolve ->(_obj, _args, _ctx) { Group.all }
  end
end
```

```ruby
# app/graphql/types/group_type.rb
Types::GroupType = GraphQL::ObjectType.define do
  name 'Group'

  field :polymorphic_object_reference, ProductUnion
end
```

```ruby
# app/graphql/product_union.rb
ProductUnion = GraphQL::UnionType.define do
  name 'ProductUnion'
  description 'Does something'
  possible_types [Types::ThingType]
end
```

```ruby
# app/graphql/types/thing_type.rb
Types::ThingType = GraphQL::ObjectType.define do
  name 'Thing'

  field :name, types.String
end
```

I can reproduce the above described issue with this code. However, if I change `Types::GroupType` to directly reference the other type, it works fine:

```ruby
# app/graphql/types/group_type.rb
Types::GroupType = GraphQL::ObjectType.define do
  name 'Group'

  field :polymorphic_object_reference, Types::ThingType
end
```

No errors for that.

*(Some names were sanitized for NDA)*

My guess is that I'm doing something wrong and the DSL loader is choking on it, but without a useful error message I don't have any idea what to do next. Maybe I'm putting the union in the wrong spot?No idea, and I can't find a working example in either the docs or a web search.

I dug around in the Rails autoloading code to try to emit a more valuable error message, but I couldn't get any useful results.

**Comment by rmosolgo** [comment]
Hi! 

The message you posted references `MutationType`:

```
LoadError - Unable to autoload constant Types::MutationType, expected .../app/graphql/types/mutation_type.rb to define it:
```

But none of your samples have any references to `MutationType`. Do you think `MutationType` is related at all?

**Comment by cyb-ahmadh** [comment]
I faced the same problem and it is kind of related to auto loading. Temporary fix is to do `require 'types/mutation_type'` in the schema file.

**Comment by bbugh** [comment]
To reiterate, the issue with `MutationType` is misdirection that doesn't have anything to do with my problem, except perhaps showing a load issue. I am changing the `group_type.rb` file. In one rendition it works, in another it breaks (seemingly unrelated) in `MutationType`.

```ruby
# app/graphql/types/group_type.rb
Types::GroupType = GraphQL::ObjectType.define do
  name 'Group'

  # 1. breaks in MutationType
  field :polymorphic_object_reference, ProductUnion
  # 2. works fine, just isn't a union
  field :polymorphic_object_reference, Types::ThingType
end
```

`MutationType` doesn't seem to be relevant to me.

**Comment by rmosolgo** [comment]
Ok, I don't know what it could be! It's not any behavior I've seen before.

If you want to debug further, please reopen this issue with the full stack trace, and if the stack trace has any references to your application code, please share those lines of code.

**Comment by bbugh** [comment]
I've spent quite a bit of time debugging this, and the stack trace wasn't helpful, because it's failing in a place that isn't related to the actual error. That's why I'm being verbose in explaining the misdirection. 

This is definitely a bug, though. If there's something wrong in `group_type` the error should be there, not another random file that works fine without that one Union type.

This project *very* basic - just `rails generate graphql:install`, plus the files listed in the original issue post. This looks to me like there's a parsing error of union types in `group_type` that isn't being handled properly by the DSL loader.

Do you see anything wrong with the original code, particularly the union setup? I think that can help us track it down. I'm happy to spend more time on fixing the bug with a PR.

**Comment by rmosolgo** [comment]
No, I don't see anything wrong with the original code

**Comment by yoonwaiyan** [comment]
I've seen this very same error in my project even though I have one syntax problem(extra comma somewhere) which is really hard to trace. Would be glad if this gem provides a better error message other than MutationType problem as OP said, silly errors has nothing to do with MutationType and we can't get any useful information from the error message in the server log.

**Comment by yoonwaiyan** [comment]
@bbugh did you try put union type inside `graphql/types` folder? Not sure if classes are being auto loaded outside of `types` folder.

**Comment by postmodem** [comment]
I had a similar experience to @yoonwaiyan. I had a simple syntax issue—a missing `end`, heh—but the error displayed was `LoadError - Unable to autoload constant Types::MutationType`. If anyone else runs into this, check the syntax on all of your Types.

**Comment by brunoreis** [comment]
I'm also getting this error whenever something is wrong in any of the schema files. Very hard to trace indeed.

**Comment by StanBoyet** [comment]
I encountered the same issue with the bootstrapping of a project, so no particular context.
@cyb-ahmadh worked. Thanks.

**Comment by pradyumna2905** [comment]
I've been facing this issue as well - Looking at my autoload paths, here is what I found (in a vanilla graphql installation)

```ruby
[
    [ 0] "/app/assets",
    [ 1] "/app/channels",
    [ 2] "/app/controllers",
    [ 3] "/app/controllers/concerns",
    [ 4] "/app/graphql",
    [ 5] "/app/helpers",
    [ 6] "/app/javascript",
    [ 7] "/app/jobs",
    [ 8] "/app/mailers",
    [ 9] "/app/models",
    [10] "/app/models/concerns"
]
```

We are **not** autoloading `app/graphql/types` directory in here. My fix was to autoload `types` directory explicitly by adding the following line

```ruby
# config/application.rb

config.autoload_paths.push(*%W[#{config.root}/app/graphql/types/])
```

Please note that any additional directories inside `app/graphql/types/` will need to be called out in the autoload path.

In non-dev (where we might need to eager load), I will tend to do something on these lines

```ruby
# config/application.rb

config.eager_load_paths.push(*%W[#{config.root}/app/graphql/types/])
config.autoload_paths = config.eager_load_paths.dup
```

That said, I'm not 100% sure if this is the right way to do it - maybe @rmosolgo can advice more?

**Comment by bbugh** [comment]
Yeah, this error still happens all the time even in 1.8. 😐 Most of the time the issue claims to be in  `MutationType`, but sometimes it's our `BaseObject`. 100% of the time, the problem is elsewhere (like an incorrect field parameter), and the parser is just reporting it incorrectly. Occasionally there will be an earlier error where the parser actually failed, try checking the logs. 

I'm curious why you decided not to autoload, as it works fine in development. Additionally, there's an issue https://github.com/rmosolgo/graphql-ruby/issues/1505 with not preloading all of the structure ahead of time in production, so I'd recommend not doing it how you're doing it and looking at that thread instead.

**Comment by ntgussoni** [comment]
Is there any sollution for this? It's really hard to trace back errors, being new to grapqhl is making it worse.

**Comment by bbugh** [comment]
Not that I've found. I usually just deal with it by making the smallest incremental changes possible to the graphql-ruby-related code, and then test it. Once it works it's very stable, but actually building it is quite fragile and frustrating. 

I have noticed that, many times, there's another error further up in the logs. That's usually the actual source of the problem, but you have to dig for it. If you see the reported error, try scrolling back through the logs until your last error, and you might get lucky and have a useful stack trace.

**Comment by ntgussoni** [comment]
@rmosolgo  is there any way we can help with this?

**Comment by rmosolgo** [comment]
The most helpful thing for me would be to share _full_ error messages and stack traces, including preceding errors, as bbugh described in https://github.com/rmosolgo/graphql-ruby/issues/1245#issuecomment-462328547. 

I think these errors mostly happen because a GraphQL schema is "booted" in two phases: first it creates the class, then, before the first query, the class creates a bunch of caches. Errors during that cache-building phase are really hard to debug in my experience. So, I'm hoping to _remove_ that phase and build the caches _while_ creating the class. (This structure is basically a compatibility hack between class-based and `.define`-based schemas.)

But, if you can share any full logs of this error, that would help me understand more precisely what's happening. If my suspicion above is _correct_, then it will help me prioritize the solution I've described. If my guess is _wrong_, then sharing full logs will help me understand what's _actually_ happening!

**Comment by saiidalhalawi** [comment]
I faced the same error message. _`Unable to autoload constant Types::MutationType`_

My fault is also just about ruby-sytax, not about graphql structure.

```ruby
result = []
result.push {   # here, unexpected token tCOLON
  user_id: user.id,
  name: user.name
}
```

and error resolved with weird message afte I fix it like below. 

```ruby
result.push(
  user_id: user.id,
  name: user.name
)
```

thanks for https://github.com/rmosolgo/graphql-ruby/issues/1245#issuecomment-422665927 

`config.paths.add` takes me the cause of real error.

**Comment by bbugh** [comment]
Hey @rmosolgo! Thanks for looking at this again (any chance to reopen?)

I'm happy to post stack traces, though I suspect it won't be very helpful due to the nature of the issue. Attached is one from the recent development server logs (some file names were modified for NDA but they are otherwise identical).

Generally what I see is that the problem is either 1) ruby syntax isn't correct, 2) a file isn't in the right path and can't autoload, 3) the graphql setup is wrong (like a misnamed method, e.g. `feild` vs `field`). Any time one of these is true, the `Unable to autoload constant Types::MutationType` has a high chance to occur. At random, it also won't report the real error.

In certain circumstances (like subscriptions) you'll never see the "real" error, only the "Unable to...MutationType"

It seems to me like somewhere in the graphql code is missing either a correct exception catch and shutdown, which allows the exception to end up causing an autoload error.

In this log, a comma got dropped while pasting, and I got lucky that it showed the real error along with the dreaded MutationType error.

```
SyntaxError - syntax error, unexpected tLABEL, expecting '('
...:NotificationPayloadUnion null: false
...                          ^~~~~:
  app/graphql/types/notification_type.rb:8:in `'
  app/graphql/types/user_type.rb:22:in `<class:UserType>'
  app/graphql/types/user_type.rb:9:in `<main>'
  app/graphql/types/another_interface.rb:13:in `<module:AnotherInterface>'
  app/graphql/types/another_interface.rb:1:in `<main>'
  app/graphql/types/base_custom_object.rb:5:in `<class:BaseCustomObject>'
  app/graphql/types/base_custom_object.rb:4:in `<main>'
  app/graphql/types/thing_type.rb:3:in `<main>'
  app/graphql/types/selected_thing_type.rb:6:in `<class:SelectedThingType>'
  app/graphql/types/selected_thing_type.rb:3:in `<main>'
  app/graphql/types/special_row_type.rb:7:in `<class:SpecialRowType>'
  app/graphql/types/special_row_type.rb:3:in `<main>'
  app/graphql/types/project_type.rb:36:in `<class:ProjectType>'
  app/graphql/types/project_type.rb:3:in `<main>'
  app/graphql/types/expense_type.rb:5:in `<class:ExpenseType>'
  app/graphql/types/expense_type.rb:1:in `<main>'
  app/graphql/mutations/expense_mutations.rb:5:in `<class:ExpensePayload>'
  app/graphql/mutations/expense_mutations.rb:4:in `<module:ExpenseMutations>'
  app/graphql/mutations/expense_mutations.rb:3:in `<main>'
  app/graphql/types/mutation_type.rb:5:in `<class:MutationType>'
  app/graphql/types/mutation_type.rb:1:in `<main>'
  app/graphql/site_schema.rb:12:in `<class:SiteSchema>'
  app/graphql/site_schema.rb:5:in `<main>'
  app/controllers/graphql_controller.rb:17:in `execute'

LoadError - Unable to autoload constant Types::MutationType, expected /Users/bbugh/projects/develop/app/graphql/types/mutation_type.rb to define it]:
/Users/bbugh/.rvm/gems/ruby-2.6.2/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:511:in `load_missing_constant'
| /Users/bbugh/.rvm/gems/ruby-2.6.2/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:43:in `load_missing_constant'
| /Users/bbugh/.rvm/gems/ruby-2.6.2/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:195:in `const_missing'
| /Users/bbugh/projects/develop/app/graphql/site_schema.rb:12:in `<class:SiteSchema>'
| /Users/bbugh/projects/develop/app/graphql/site_schema.rb:5:in `<main>'
```

**Comment by leom806** [comment]
I've seen this error message sometimes and I thought that it would be great if we could reopen this issue because I myself and I'm sure that many others has spent hours trying to find simple errors that were just showing this mistaken `Unable to autoload constant Types::MutationType` trace.

Is there any chance to reopen this issue @rmosolgo?

**Comment by ro31337** [comment]
@rmosolgo this needs to be reopened

**Comment by benjaminbarbe** [comment]
@bbugh Do you have some update to make the union example works? I have got the exact same issue. Thanks

**Comment by benjaminbarbe** [comment]
@bbugh Finally, I found the cause of the error: you need to implement ```resolve_type``` method.
For information about ```resolve_type```, see the [Interfaces guide](https://graphql-ruby.org/type_definitions/interfaces#resolve-type).

```ruby
Schema = GraphQL::Schema.define do
    # ...
    resolve_type lambda { |type, obj, ctx|
        # ...
    }
end
```

**Comment by mmahalwy** [comment]
Reopen? Same problem here

**Comment by dkniffin** [comment]
Yep, just hit the same problem

**Comment by KevinAdu** [comment]
Yeah I think this should be reopened. I'm seeing the same issue too

**Comment by rmosolgo** [comment]
Sorry about the bad error messages. If one of the above solutions works for you, please share it. My hope is to fix the "hidden" exception by simplifying the way that schemas "boot", #2363

**Comment by Hajar1** [comment]
Had the same problem. It was caused by forgetting one comma in one of my mutation. 
Checking your pay load might be helpful

**Comment by bluciam** [comment]
I had the same problem. Mine was caused by redefining a field. I was working with some legacy code and at first (and second and ...) sight,  was not findable.

**Comment by jakemumu** [comment]
hitting this today -- makes debugging very difficult.

I'm on: graphql (1.12.19)
Rails 6.1.4.1
