### ISSUE TITLE
Cannot authorise connections / scopes when using Mongoid (MongoDB)

### ISSUE THREAD

**Issue by rubenfonseca** [rmosolgo/graphql-ruby#1249]
We're trying to use graphql-pro to add authorization and cursors to our app. While graphql-pro easily allows to extend the cursors funcionality to new classes, we can't do the same on the authorization side.

Specifically, MergedGate doesn't support Mongoid and there's no point for extension. This makes us impossible to authorize scopes on our graphql connections. Is there an easy workaround for this?

**Comment by rmosolgo** [comment]
Sadly, no, GraphQL-Pro's support is pretty closely tied to ActiveRecord :'( 

Thanks for opening this issue, I'll report back here if the situation changes in the future!
