### ISSUE TITLE
args.key? unexpected behaviour with default values

### ISSUE THREAD

**Issue by axos88** [rmosolgo/graphql-ruby#1258]
If an argument has a default value: 
`argument :page_size, types.Int, default_value: 5`

The `args.key?(:page_size)` within the `resolve` function will ALWAYS return `true`.

I would expect:
  - `args[:page_size]` to return `5` (or nil and have something like `args.fetch(:page_size)` that would return 5)
  - `args.key?(:page_size)` to return `false`
  - `args.to_h` to NOT contain `:page_size => 5`

**Comment by axos88** [comment]
This would be helpful for pagintion: If either the page num or page size is defined, the data is paginated. If the page size is not set, then the default page size is used, if neither are given, the data is return unpaginated.

**Comment by rmosolgo** [comment]
I'm sorry that was unexpected! I hope you can use `#default_used?` in the meantime: http://www.rubydoc.info/gems/graphql/1.7.8/GraphQL/Query/Arguments#default_used%3F-instance_method
