### ISSUE TITLE
How to do a delete mutation ?

### ISSUE THREAD

**Issue by c0ze** [rmosolgo/graphql-ruby#1263]
Hello there,

sorry this is not really an issue. I am in the process of converting a REST API (Grape) to GraphQL.

I've done almost all without much trouble, but I can't find any examples on how to do delete mutations ?

If possible I want to avoid having a create a dedicated delete mutation for all my models, I want a single mutation to take a Type, id, delete the found record and return the deleted records id.

How can I go about with something like this ?

Thanks in advance !

**Comment by Willianvdv** [comment]
Hello @c0ze,

You can create a `DeleteNode` mutation that accepts a [global node identifier](http://graphql-ruby.org/relay/object_identification.html) to get the object you want to delete.

Would that work for you?

**Comment by c0ze** [comment]
@Willianvdv thank you ! This looks good ! One thing though, it seems this is written for Relay, and I am using Apollo on the frontend (Vue). Are there any nuances I should care about ?
