### ISSUE TITLE
resolve_type vs is_type_of

### ISSUE THREAD

**Issue by axos88** [rmosolgo/graphql-ruby#1267]
Possibly related: https://github.com/rmosolgo/graphql-ruby/issues/1193

Is there a way to define the typeresolve within the concrete types? Apollo uses isTypeOf for this: https://launchpad.graphql.com/zrz504kp37

This would enable better separation of concerns between the interface and the implementations, as the interface need not to know about every concrete type, and how do differentiate them.

**Comment by rmosolgo** [comment]
Thanks for the suggestion, but I don't have any plans to change this right now. The advantage isn't clear to me (at least, not in a way that is worth the complexity of a refactor). Unfortunately Launchpad seems to have stopped its service :'(
