### ISSUE TITLE
GraphQL::Define::NoDefinitionError

### ISSUE THREAD

**Issue by maheshbablu17** [rmosolgo/graphql-ruby#1271]
When I'm trying to fetch the records in [graphiql](http://localhost:3000/graphiql), I'm getting 
 
  "message": "The server responded with invalid JSON, this is probably a server-side error",
  "response":......

This is my logs:
Started POST "/graphql" for 127.0.0.1 at 2018-02-10 16:37:53 +0530
Processing by GraphqlController#execute as */*
  Parameters: {"query"=>"{\n  allMovies {\n    id\n    title\n  }\n}\n", "variables"=>nil, "operationName"=>nil, "graphql"=>{"query"=>"{\n  allMovies {\n    id\n    title\n  }\n}\n", "variables"=>nil, "operationName"=>nil}}
Completed 500 Internal Server Error in 0ms (ActiveRecord: 0.0ms)

  
GraphQL::Define::NoDefinitionError (GraphQL::Field can't define 'movies”'):
  
app/graphql/types/query_type.rb:16:in `block (2 levels) in <top (required)>'
app/graphql/learning_graphql_schema.rb:1:in `<top (required)>'
app/controllers/graphql_controller.rb:10:in `execute'

**Comment by Willianvdv** [comment]
Can you show us the contents of the query and other relevant types?

**Comment by maheshbablu17** [comment]
yeaa..... I had followed this [link](https://medium.com/@UnicornAgency/you-should-be-using-graphql-a-ruby-introduction-9b1de3b001dd) steps as it is to create a simple app. I'm getting error while executing this `{
  allMovies {
    id
    title
    description
  }
}`
in [local](http://localhost:3000/graphiql)

**Comment by Willianvdv** [comment]
It looks like a small typo, but it's tough to tell if we don't have code! Can you add the source of `app/graphql/learning_graphql_schema.rb` to this issue or push your project to a public repo here on Github?

Thanks!

**Comment by maheshbablu17** [comment]
Thanks for the reply. Please check this repo [graphql](https://github.com/maheshbablu17/graphql.git)

**Comment by rmosolgo** [comment]
Here's the line with the error: 

https://github.com/maheshbablu17/graphql/blob/master/app/graphql/types/query_type.rb#L16

It looks like your code is using smart quotes: 

> `“A list of all the movies”`

When it should use simple quotes: 

> `"A list of all the movies"


I don't think Ruby supports smart quotes, use simple quotes instead, I think that will fix it!
