### ISSUE TITLE
Subscribe doesn't return subscription id

### ISSUE THREAD

**Issue by cptaffe** [rmosolgo/graphql-ruby#1272]
I think this may be a usage question rather than a bug. I'd like to return information like the subscription id to clients when they submit a subscribe query.

The example in the PR that adds the `subscribe` functionality uses the `X-Channel-Id` header for this, but that requires communicating back to the controller from the `Subscriptions` subclass.

#### 1. Generate a new Rails 5 app

```sh
rails new graphql-subscription-test
cd graphql-subscription-test
cat << EOF >> Gemfile
gem 'graphql'
EOF
bundle install
bin/rails generate graphql:install
bundle install
```

#### 2. Add a subscription

`/app/graphql/types/post_type.rb`
```ruby
Types::PostType = GraphQL::ObjectType.define do
  name "Post"
  field :title, !types.String
end
```

`app/graphql/types/subscription_type.rb`:
```ruby
Types::SubscriptionType = GraphQL::ObjectType.define do
  name "Subscription"
  field :postWasPublished do
    type !Types::PostType
    description "A Post was published!"
  end
end
```

`/app/graphql/graphql_subscription_test_schema.rb`:
```ruby
class Subscriptions < GraphQL::Subscriptions
  def initialize(**args)
    @subs = Concurrent::Map.new
    @subs_by_topic = Concurrent::Map.new
    super
  end

  def each_subscription_id(event)
    @subs_by_topic[event.topic].each do |id|
      yield id
    end
  end

  def deliver(subscription_id, result)
    # TODO: deliver message
    Rails.logger.info("Sending #{subscription_id}: #{result.to_json}")
  end

  def read_subscription(subscription_id)
    @subs[subscription_id]
  end

  def write_subscription(query, events)
    subscription_id = query.context[:subscription_id] ||= build_id
    @subs[subscription_id] = {
      query_string: query.query_string,
      variables: query.provided_variables,
      context: query.context.to_h,
      operation_name: query.operation_name,
    }
    events.each do |event|
      (@subs_by_topic[event.topic] ||= []) << subscription_id
    end
  end
end

GraphqlSubscriptionTestSchema = GraphQL::Schema.define do
  use Subscriptions

  subscription Types::SubscriptionType
end
```

#### 3. Run the server

```sh
bin/rails server
```

#### 4. Try to subscribe

Navigate to:
* http://localhost:3000 to get a cookie
* http://localhost:3000/graphiql

Try this query:
```graphql
subscription TestSubscription {
  postWasPublished {
    title
  }
}
```

Observe that the response is:
```json
{
  "data": null
}
```

**Comment by rmosolgo** [comment]
Hi, thanks for opening a detailed issue! 

Did you modify your controller to add any data to the response? See for example `result.context[:subscription_id]` in the ActionCable docs: 

http://www.rubydoc.info/gems/graphql/1.7.9/GraphQL/Subscriptions/ActionCableSubscriptions

Or the header in the Pusher subscription docs: 

http://graphql-ruby.org/subscriptions/pusher_implementation.html#execution-configuration

Did you make a similar change in your controller to return more data in the response?

**Comment by cptaffe** [comment]
Thanks! I went with adding the `X-Subscription-Id` to the response
