### ISSUE TITLE
Non-null arguments

### ISSUE THREAD

**Issue by axos88** [rmosolgo/graphql-ruby#1273]
In case of mutation complex input types (but I guess the same applies to arguments as well), how can I specify, that the particular field, can either be left out / not supplied, or must be non-null.

A bit of an abstract example in case of an update mutation:
```
  Update = GraphQL::Relay::Mutation.define do
          name 'updateBook'

          input_field :id, !GraphQL::Common::ObjectId
          input_field :cover, GraphQL::Cover::InputType

          resolve ->(obj, args, ctx) do
                 (...)
                 book.cover = Cover.find(args[:cover][:id]).tap { |c| c.update_attributes(args[:cover]) }                  if args.key?(:cover)
                 (...)
          end
   end
```

I want to make sure the cover either not specified (it is left unmodified), or it is supplied, and is defined (not null).

I'm not even sure the GraphQL standard allows this, does it?

**Comment by axos88** [comment]
So I would like to disallow `cover: null`

**Comment by rmosolgo** [comment]
No, this isn't covered by GraphQL right now. Using `!` means it must be _present_ and it must not be `nil`. So there's no built-in way to express "it may be absent _or_ it may be present-and-non-`nil`"!
