### ISSUE TITLE
[BUG] RelationConnection won't behave correctly if the relation query contains 'distinct'

### ISSUE THREAD

**Issue by cuijiemmx** [rmosolgo/graphql-ruby#1279]
As the codes from RelationConnection.rb shown below
![screen shot 2018-02-14 at 4 07 41 pm](https://user-images.githubusercontent.com/3148003/36193532-3cc7a7a8-11a1-11e8-9207-fbdd65781a48.png)

Consider If the relation query contains 'DISTINCT' keyword, the relation_count method returns a wrong result, because relation.count(:all) will be translated to a sql statement without 'DISTINCT', as shown below
<img width="640" alt="screen shot 2018-02-14 at 4 11 15 pm" src="https://user-images.githubusercontent.com/3148003/36193773-1eabcb18-11a2-11e8-82da-a5bf9b8abb2c.png">

So, can we fix this bug by using relation.count instead of relation.count(:all)?

**Comment by rmosolgo** [comment]
Hey @cuijiemmx sorry about the bug! Thanks for sharing all that information about it. 

We need `.count(:all)` for some _other_ special cases, like joins or functions like `LENGTH`. But I can see it breaks `DISTINCT`. 

🤔 I'm not sure how to support both. Can we detect `DISTINCT` somehow? (Or detect the conditions when we should use `:all`?)

**Comment by cuijiemmx** [comment]
@rmosolgo You can use relation.select_values OR relation.distinct_value to detect DISTINCT, because DISTINCT may appears in two forms
1. distinct method on relation
2. DISTINCT keyword in select statement
I paste a screenshot to show both situations
<img width="524" alt="screen shot 2018-02-14 at 10 56 53 pm" src="https://user-images.githubusercontent.com/3148003/36211352-fb3fb3b2-11db-11e8-8a46-41a293f2897b.png">
Hope it helps!

**Comment by rmosolgo** [comment]
Sorry I haven't had a chance to work on this. I don't plan to, but if anyone wants to improve support along the lines suggested here, I'd welcome a PR!
