### ISSUE TITLE
Add multiple errors - with correct nesting to a query

### ISSUE THREAD

**Issue by axos88** [rmosolgo/graphql-ruby#1282]
Related to #629:

Thanks for giving that tip on `ctx.add_error` in the referenced issue. I'm wondering if it's possible to add an error for a subfield/argument?

For example in case of multiple validation errors, in the field's resolve function I would like to add an error that that the argument `item_no` was out of bounds, and the argument `commission` cannot be set if the `commission_type` is not set.

`ctx.add_error` would return the query in the `fields` field of the error, whereas it would be much more self-explanatory (and easier for the frontend), if it were the erroneous argument, so it would not need a complex decision logic to show it to the user.

I'm thinking something like `ctx.get_context_for(:item_no).add_error(...)`

**Comment by axos88** [comment]
Ok, I found a way, although it is a bit cumbersome:

```
e = GraphQL::ExecutionError.new('message')
e.path = ctx.path + ["item_no"]
ctx.add_error(e)
```

**Comment by rmosolgo** [comment]
Glad you found a solution! I think a new mutation API could provide better support for this, I'll keep it in mind at #1275
