### ISSUE TITLE
Undefined method for nil:NilClass

### ISSUE THREAD

**Issue by egilburg** [rmosolgo/graphql-ruby#1284]
Hi, I need to write a GraphQL consumer and want to model a matching schema of what our server returns for validation purposes. But I'm blocked at this simple example:

```ruby
module Types
  TitleType = GraphQL::ScalarType.define do
    name "Title"
  end

  TableType = GraphQL::ObjectType.define do
    name "Table"

    field :title, Types::TitleType
  end

  QueryType = GraphQL::ObjectType.define do
    name "Query"

    field :table, Types::TableType do
      argument :id, !types.Int
    end
  end
end

Schema = GraphQL::Schema.define do
  query Types::QueryType
end

query_string = <<~EOS
  query {
    table(id: 1) {
      title
    }
  }
EOS

puts Schema.execute(query_string).to_h
```

And I'm getting:
```
NoMethodError:
  undefined method `table' for nil:NilClass
```

I even tried simplifying the title field in `TableType` to just be `field :title, types.String` (rather than a custom `TitleType` scalar, and it still gives the same error.

Can anyone please help me understand what I'm doing wrong? Thanks!

**Comment by joshjcarrier** [comment]
Your table field needs a better resolve method. The default is trying to call obj.table, where obj is the parent resolved value which is nil for Query

**Comment by rmosolgo** [comment]
@joshjcarrier is right, it's trying to call the `#table` method to resolve that field, but you haven't given it any objects to resolve from. You should define a `resolve: ` function for that field if you want it to return data, for example: 

```ruby 
    field :table, Types::TableType do
      argument :id, !types.Int
      resolve: ->(obj, args, ctx) { OpenStruct.new(title: "Cool Table") }
    end
```
