### ISSUE TITLE
Validating enum and input names

### ISSUE THREAD

**Issue by KieranP** [rmosolgo/graphql-ruby#1292]
Made some changes today, changed some enum and input name to "Enums::User::Gender" and "Inputs::User::Profile". ruby graphql parsed it fine. Then deployed, and apollo started breaking. Turned out "::" is not valid in names. ruby-graphql already validates for unique names, it should validate on name format too, so that issues can be caught early.

**Comment by rmosolgo** [comment]
That would be nice! A PR would be welcome, EnumValue already has a check like this, so maybe the same code could be reapplied.

**Comment by KarlHarnois** [comment]
So we're talking about making a test like pass for both `enum_type` and `input_object_type`?

```ruby
describe "invalid names" do
  # ...

  it "rejects names with colons" do
    assert_raises(GraphQL::InvalidNameError) do
      InvalidEnumTest = GraphQL::EnumType.define do
        name "Some::Invalid::Name"
      end
    end

    InvalidEnumTest.name
  end
end
```

**Comment by KarlHarnois** [comment]
Aka passing the type's name through the `GraphQL::NameValidator`?

**Comment by KarlHarnois** [comment]
Sorry for polluting this issue with my rebases 😮

**Comment by KieranP** [comment]
@KarlHarnois Awesome, thank you :-)
