### ISSUE TITLE
Massive warning noise under ruby 2.5.0

### ISSUE THREAD

**Issue by andriytyurnikov** [rmosolgo/graphql-ruby#1296]
Using library in test suites creates enormous warning noise in ruby 2.5.0

```
Library creates enourmous warning noise in when used it test suites in ruby 2.5.0
```
/Users/andriytyurnikov/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/bundler/gems/graphql-ruby-32a637c28aee/lib/graphql/define/instance_definable.rb:183: warning: method redefined; discarding old edges?
/Users/andriytyurnikov/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/bundler/gems/graphql-ruby-32a637c28aee/lib/graphql/define/instance_definable.rb:206: warning: previous definition of edges? was here
/Users/andriytyurnikov/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/bundler/gems/graphql-ruby-32a637c28aee/lib/graphql/define/instance_definable.rb:183: warning: method redefined; discarding old edge_class
/Users/andriytyurnikov/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/bundler/gems/graphql-ruby-32a637c28aee/lib/graphql/define/instance_definable.rb:206: warning: previous definition of edge_class was here
/Users/andriytyurnikov/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/bundler/gems/graphql-ruby-32a637c28aee/lib/graphql/define/instance_definable.rb:183: warning: method redefined; discarding old subscription_scope
/Users/andriytyurnikov/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/bundler/gems/graphql-ruby-32a637c28aee/lib/graphql/define/instance_definable.rb:206: warning: previous definition of subscription_scope was here
/Users/andriytyurnikov/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/bundler/gems/graphql-ruby-32a637c28aee/lib/graphql/define/instance_definable.rb:183: warning: method redefined; discarding old introspection?
/Users/andriytyurnikov/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/bundler/gems/graphql-ruby-32a637c28aee/lib/graphql/define/instance_definable.rb:206: warning: previous definition of introspection? was here
```

**Comment by rmosolgo** [comment]
Hi, thanks for this issue! It's inevitable with the `.define`-based API. But soon, the class-based API won't do this kind of method overriding. I don't know of a short-term fix for this, and I want to focus on releasing & supporting the new API, so I'm going to close the issue, but if you know a fix, or want to explore some other possibility, feel free to open a PR or continue discussing here.

**Comment by andriytyurnikov** [comment]
Another *popular* warning is about usage of non-initialized instance variables:
```
/Users/andriytyurnikov/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.7.12/lib/graphql/query/context.rb:31: warning: instance variable @invalid_null not initialized
```

**Comment by andriytyurnikov** [comment]
@rmosolgo , just out of curiosity - have you seen [lacinia](https://github.com/walmartlabs/lacinia) ?
Their use of hashes and arrays to describe type structure is impressive. 

Weird, I thought that issue is not in external layer of `.define`-based API, but in the aggressive method rewriting inside, which, again is an even deeper dependency. 

I am just incapable of wrapping my mind around  AST's built with class hierarchies with dynamic method definitions.

Will ping if I'll figure out how to use hashes, arrays, and lambdas to build something distantly as powerful as the current implementation.

Thank you so much for sharing a library.

**Comment by rmosolgo** [comment]
😬  that one might be an easier fix!

**Comment by RBIII** [comment]
Any update on this? I'm getting it with ruby `2.3.3` `~/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/graphql-1.7.13/lib/graphql/enum_type.rb:142: warning: method redefined; discarding old name=`
