### ISSUE TITLE
Doesn't execute introspection query

### ISSUE THREAD

**Issue by devknoll** [rmosolgo/graphql-ruby#13]
See: https://github.com/graphql/graphql-js/blob/master/src/utilities/introspectionQuery.js

This might be covered by one of the TODOs, not sure :smile:

**Comment by rmosolgo** [comment]
Wow, thanks for pointing that out! No I hadn't seen that query. That's a great way to make sure everything's working right. 

This commit makes it _run_: 402eae095523cffe95b93b71c662d4fb45d624d0

I guess the next thing to do is a fine-grained test that the output is right!
