### ISSUE TITLE
[1.8] Schema::Printer raises error if called before @schema.types

### ISSUE THREAD

**Issue by benkimball** [rmosolgo/graphql-ruby#1311]
I've just converted our 1.7-style schema to use the new 1.8 class-based schema, and my test that asserts that the schema has been dumped is failing. The reason is that `GraphQL::Schema::Printer` is raising a `NoMethodError` when, during the execution of `#print_schema`, it retrieves the schema definitions and gets `nil`, then calls `each_value` on `nil`. (The actual line that raises the exception is in `Warden#directives`).

By experimenting in the console, I found that if I manually call the Warden's `types` method, I can subsequently print the schema without error. It appears to me that what's happening is that the schema's `@directives` attribute is `nil` until its `#rebuild_artifacts` method is called.

We're using `graphql` version 1.8pre6 on Rails 4.2.7.1. Here's an excerpt from my console that demonstrates the problem:

    $ bundle exec rails console
    Loading development environment (Rails 4.2.7.1)
    [1] pry(main)> ApiSchema
    => ApiSchema
    [2] pry(main)> GraphQL::Schema::Printer.print_schema(ApiSchema)
    NoMethodError: undefined method `each_value' for nil:NilClass
    from /Users/zubin/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/graphql-1.8.0.pre6/lib/graphql/schema/warden.rb:115:in `directives'
    [3] pry(main)> filter = GraphQL::Filter.new(only: nil, except: nil)
    => #<GraphQL::Filter:0x00007fcced521108 @except=nil, @only=nil>
    [4] pry(main)> GraphQL::Schema::Warden.new(filter, context: nil, schema: ApiSchema).types
    => [Boolean,
    String,
    Query,
    Award,
    ID,
    AwardStatus,
    Time,
    Int,
    Nomination,
    User,
    Company,
    Mutation,
    AwardInput,
    NominationInput,
    __Schema,
    __Type,
    __Field,
    __Directive,
    __EnumValue,
    __InputValue,
    __TypeKind,
    __DirectiveLocation]
    [5] pry(main)> GraphQL::Schema::Printer.print_schema(ApiSchema)
    => "# TODO: write description of Award type\ntype Award {\n  # The moment the Award closes for nominations\n  closesAt: Time!\n\n  # The wording of the question asking for a core value\n  coreValueQuestion: String!\n\n  # A description of the Award\n  description: String\n\n  # A count of the number of people who are eligible to submit nominations, based\n  # on nominator_eligibility_groups. Before the Award has ended, this is expensive\n  # to compute. After the award has ended, this number is stored and no longer\n  # computationally expensive.\n  eligibleNominatorCount: Int!\n\n  # A count of the number of people who are eligible to be nominated, based on\n  # nominee_eligibility_groups. Before the Award has ended, this is expensive to\n  # compute. After the award has ended, this number is stored and no longer\n  # computationally expensive.\n  eligibleNomineeCount: Int!\n\n  # Whether the Award includes a question asking for a core value\n  hasCoreValueQuestion: Boolean!\n\n  # Whether a nominator has a limited number of nominations per Award\n  hasNominationLimit: Boolean!\n\n  # Whether the Award includes a question asking for skills\n  hasSkillsQuestion: Boolean!\n\n  # The ID of the Award\n  id: ID!\n\n  # If has_nomination_limit is true, the number of nominations a nominator may submit per Award. Otherwise undefined.\n  nominationLimit: Int\n\n  # A list of nominations submitted for this Award\n  nominations: [Nomination!]!\n\n  # The IDs of groups to which nominators should be restricted. If empty, no restrictions are applied.\n  nominatorEligibilityGroups: [String!]!\n\n  # The IDs of groups to which nominees should be restricted. If empty, no restrictions are applied.\n  nomineeEligibilityGroups: [String!]!\n\n  # The wording of the question asking who to nominate\n  nomineeQuestion: String!\n\n  # The moment the Award opens for nominations\n  opensAt: Time!\n\n  # The wording of the question asking for a nomination rationale\n  rationaleQuestion: String!\n\n  # Whether email invitations will be sent to eligible nominators when the Award opens for nominations\n  sendInvitationsOnOpen: Boolean!\n\n  # Whether email reminders will be sent to eligible nominators 3 days before the Award closes for nominations\n  sendRemindersBeforeClose: Boolean!\n\n  # The wording of the question asking for skills\n  skillsQuestion: String!\n\n  # The status of the Award\n  status: AwardStatus!\n\n  # The title of the Award\n  title: String!\n}\n\n# The input type for mutating an award.\ninput AwardInput {\n  closesAt: Time!\n  coreValueQuestion: String = \"Which core value does this person most demonstrate?\"\n  description: String\n  hasCoreValueQuestion: Boolean = false\n  hasNominationLimit: Boolean = false\n  hasSkillsQuestion: Boolean = false\n  nominationLimit: Int\n  nominatorEligibilityGroups: [ID!] = []\n  nomineeEligibilityGroups: [ID!] = []\n  nomineeQuestion: String = \"Who would you like to nominate?\"\n  opensAt: Time!\n  rationaleQuestion: String = \"Why are you nominating this person?\"\n  sendInvitationsOnOpen: Boolean = false\n  sendRemindersBeforeClose: Boolean = false\n  skillsQuestion: String = \"What skills make this person deserving of the nomination?\"\n  title: String = \"Untitled Award\"\n}\n\n# An award can be in one of four states, depending on its open and close dates\n# and whether a winner has been selected.\nenum AwardStatus {\n  # Not accepting nominations; a winner has been selected\n  awarded\n\n  # No longer accepting nominations; a winner has not been selected\n  ended\n\n  # Accepting nominations\n  live\n\n  # Not yet accepting nominations\n  scheduled\n}\n\n# A company represents a customer and has their own youearnedit.com subdomain.\ntype Company {\n  # The ID of the company\n  id: ID!\n\n  # The name of the company\n  name: String!\n\n  # The company subdomain (*.youearnedit.com)\n  subdomain: String!\n}\n\n# The base type from which all Object types should inherit. Override this description in the subclass.\ntype Mutation {\n  # Create a new award\n  createAward(awardInput: AwardInput!): Award!\n\n  # Create a new nomination\n  createNomination(nominationInput: NominationInput!): Nomination!\n}\n\n# A nomination is effectively a \"vote\" for a person (the nominee) to win an award, created\n# by a user (the nominator). It collects the answers to the award questions: who (nominee),\n# why (rationale), and optionally a core value and up to 3 demonstrated skills.\ntype Nomination {\n  # The Award for which this nomination was submitted\n  award: Award!\n\n  # The core value associated with this nomination, if present\n  coreValue: String\n\n  # The ID of the Nomination\n  id: ID!\n\n  # The person who made the nomination\n  nominator: User!\n\n  # The person who is being nominated for the Award\n  nominee: User!\n\n  # Why this person deserves to win the Award\n  rationale: String!\n\n  # An array of the skill names identified for this nomination, if any\n  skills: [String!]\n}\n\ninput NominationInput {\n  awardId: ID!\n  coreValueId: ID\n  nominatorId: ID!\n  nomineeId: ID!\n  rationale: String!\n  skills: [String!] = []\n}\n\n# The base type from which all Object types should inherit. Override this description in the subclass.\ntype Query {\n  # Find an Award by ID\n  award(id: String!): Award\n\n  # Find a Company\n  company(id: ID, subdomain: String): Company\n\n  # Find a Nomination\n  nomination(id: ID!): Nomination\n\n  # Find a User\n  user(email: String, id: ID): User\n\n  # Retrieve the current user\n  viewer: User\n}\n\n# A type for holding a Time value with a time zone. Must conform to ISO8601.\nscalar Time\n\n# An individual user account, used for authentication and authorization. Belongs to a single company.\ntype User {\n  # The email address of the user\n  email: String!\n\n  # First name\n  firstName: String\n\n  # The ID of the user\n  id: ID!\n\n  # Last name\n  lastName: String\n}"
    [6] pry(main)>

**Comment by rmosolgo** [comment]
Thanks for the detailed issue! Someone else just mentioned it and posted a fix at #1308 . So, it's fixed on `1.8-dev`, and I'll try to get another pre-release on Rubygems soon 😬
