### ISSUE TITLE
exception LoadError: Unable to autoload constant

### ISSUE THREAD

**Issue by cyb-ahmadh** [rmosolgo/graphql-ruby#1312]
Hi, 

I'm using graphql(1.7.9), rails-api (5.1.4) and ruby(2.5.0p0).
For the `queries` in `query_type.rb` file, i have used `functions` to cleaner approach. So i have created one folder inside the graphql folder for functions and put all the functions there. As expected i am using those functions in query_type.rb file like this:

```
field :user, function: Functions::FindRecord.new(model_class: User, type: Types::UserType)
field :activeUsers, function: Functions::ActiveUsers.new(type: types[Types::UserType])
field :nonActiveUsers, function: Functions::NonActiveUsers.new(type: types[Types::UserType])
```
- Function definitions
```
#app/graphql/functions/find_record.rb
module Functions
  class FindRecord < GraphQL::Function
    attr_reader :type

    def initialize(model_class:, type:)
      @model_class = model_class
      @type = type
    end

    argument :id, !types.Int

    def call(obj, args, ctx)
      @model_class.find(args[:id])
    end
  end
end

#app/graphql/functions/all_users.rb
module Functions
  class AllUsers < GraphQL::Function
    attr_reader :type

    def initialize(type:)
      @type = type
    end

    def call(_, args, _)
      User.all
    end
  end

  class ActiveUsers < AllUsers
    def call(_, args, _)
      super.active
    end
  end

  class CompletedUsers < AllUsers
    def call(_, args, _)
      super.non_active
    end
  end
end
```

Now when i'm hitting `graphiql`, it says this:
```
{
  "status": 500,
  "error": "Internal Server Error",
  "exception": "#<LoadError: Unable to autoload constant Functions::FindRecord, expected /usr/src/app/app/graphql/functions/find_record.rb to define it>",
  "traces": {
    "Application Trace": [
      {
        "id": 2,
        "trace": "app/graphql/types/query_type.rb:5:in `block in <top (required)>'"
      },
      {
        "id": 19,
        "trace": "app/graphql/user_service_schema.rb:3:in `<top (required)>'"
      },
      {
        "id": 35,
        "trace": "app/controllers/graphql_controller.rb:10:in `execute'"
      }
    ],
    "Framework Trace": [
      {
        "id": 0,
        "trace": "activesupport (5.1.4) lib/active_support/dependencies.rb:511:in `load_missing_constant'"
      },
      {
        "id": 1,
        "trace": "activesupport (5.1.4) lib/active_support/dependencies.rb:202:in `const_missing'"
      },
      {
        "id": 3,
        "trace": "graphql (1.7.9) lib/graphql/define/instance_definable.rb:161:in `instance_eval'"
      },
...
```

I have to then manually require the files in schema file like this:

```
require 'types/mutation_type'
require 'functions/all_users'
```
The same thing happened for mutation_type file as well. Please suggest what am i missing or doing wrong here.

**Comment by rmosolgo** [comment]
Sorry to hear it! Did you add `app/graphql` to your `autoload_paths`?

**Comment by cyb-ahmadh** [comment]
I think there is no need of it because of this result:
```
bin/rails r 'puts ActiveSupport::Dependencies.autoload_paths'
Running via Spring preloader in process 26
/usr/src/app/app/controllers
/usr/src/app/app/graphql
/usr/src/app/app/models
/usr/local/bundle/gems/graphiql-rails-1.4.8/app/assets
/usr/local/bundle/gems/graphiql-rails-1.4.8/app/controllers

```

**Comment by benkimball** [comment]
You might try running a Rails console, and referencing your schema object in it. I had a similar problem, and by loading the schema in a console I was able to see that the problem was a syntax error in one of my resolvers.

**Comment by wtigert** [comment]
I'm running into a similar error and it's clear that rails is autoloading it as I'm able to access various Types in the rails console.

I did notice this in the logs:
```LoadError (Unable to autoload constant Types::QueryType, expected /app/app/graphql/types/query_type.rb to define it)```

specifically `expected /app/app...` which I think may be part of the issue. I'm on v1.7.13

**Comment by cyb-ahmadh** [comment]
@benkimball I tried your approach but it is not complaining any thing.

**Comment by jturkel** [comment]
I hit a similar problem in 1.8.0.pre7. Looking back further in my logs I found there were errors loading my query class which left my schema in a partially loaded state that later manifested in LoadErrors. Not sure if you're hitting the same problem.

**Comment by cyb-ahmadh** [comment]
I'm pretty sure that my queries are error free because i have tried to run them all one by one in rails console using these commands:

```
query = <<-GRAPHQL
   activeUsers(projectId: #{project_id}){
        id
        name
        endDate
        active
        usersCount
      }
GRAPHQL

Schema.execute(query)
```

**Comment by Glitched-Manual** [comment]
I solved my issue.

I opened the .rb file in the model folder (posts.rb for me)

```
class Post < ApplicationRecord
end
```
Opened the controller and used the name of the child class from above

``
# was
 @posts = **Posts**.find(params[:id])
#now 
 @posts = **Post**.find(params[:id])
``

**Comment by lucaong** [comment]
Just ran into a similar issue today, where I had a small mistake in one of my types:

```ruby
field :is_member_of_group, Boolean, null: false do
  # Mistakenly use `null: false` instead of `required: true`:
  argument :key, String, null: false
end
```

This resulted in a confusing autoloading error in a completely different file:

```
LoadError (Unable to autoload constant Types::Mutation, expected /usr/src/app/app/graphql/types/mutation.rb to define it)
```

Also note the `app/app` in the path like the example reported by @wtigert.

The issue is 100% my mistake of course, but the resulting error is misleading, and raising a better one might help users in the same situation a lot.

**Comment by rmosolgo** [comment]
If anyone runs into a problem like this, please open another issue!

In 1.10, when using the interpreter runtime, schema loading is much simpler (there's no deferred cache building),  so it should be much easier to debug autoloading problems.

**Comment by justin808** [comment]
I have no idea how to fix this one:

```
bin/rake graphql:dump_schema                                                                                                                                        
LoadError: Unable to autoload constant GraphType::QueryType, expected /Users/justin/clients/popmenu/popmenu/app/graphql/graph_type/query_type.rb to define it
/Users/justin/.rvm/gems/ruby-2.7.3@popmenu/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:550:in `load_missing_constant'
/Users/justin/.rvm/gems/ruby-2.7.3@popmenu/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:214:in `const_missing'
```
