### ISSUE TITLE
Paging back to "first" page does not allow forward paging afterwards

### ISSUE THREAD

**Issue by winterchord** [rmosolgo/graphql-ruby#1318]
On master @ ee4c065, with bidirectional pagination turned on (#955).

When querying a connection with `first`, then to the next "page" with `first+after`, and then back to the previous "page" with `last+before` (which is the first page), the `hasNextPage` field is set to  `false`.

For example, if there are 10 empire bases (SW example).

Actual: 

1. bases(first: 1) => hasPreviousPage: false, hasNextPage: true, endCursor: X
1. bases(first: 1, after: X) => hasPreviousPage: true, hasNextPage: true, endCursor: Y
1. bases(last: 1, before: Y) => hasPreviousPage: false, hasNextPage: **false**

Expected: 

1. bases(first: 1) => hasPreviousPage: false, hasNextPage: true, endCursor: X
1. bases(first: 1, after: X) => hasPreviousPage: true, hasNextPage: true, endCursor: Y
1. bases(last: 1, before: Y) => hasPreviousPage: false, hasNextPage: **true**

**Comment by rmosolgo** [comment]
Hi, thanks for the great write-up and this nice patch! It looks good to merge, let me take a closer look tomorrow.
