### ISSUE TITLE
[1.8] How to specify metadata in class-based API?

### ISSUE THREAD

**Issue by benkimball** [rmosolgo/graphql-ruby#1324]
Our 1.7 schema has some fields like this:

    Types::UserType = GraphQL::ObjectType.define do
      field :birth_day, types.Int do
        guard ->(user, _args, ctx) { UserPolicy.new(ctx[:current_user], user).show_birth_date? }
        not_authorized ->(_type, _field) { nil }
        resolve ->(user, _args, _ctx) { user.birth_date&.day }
      end
    end

To implement `guard` and `not_authorized`, we have a `Guard` class which calls:

    GraphQL::ObjectType.accepts_definitions(guard: GraphQL::Define.assign_metadata_key(:guard))
    GraphQL::Field.accepts_definitions(guard: GraphQL::Define.assign_metadata_key(:guard))

    GraphQL::ObjectType.accepts_definitions(not_authorized: GraphQL::Define.assign_metadata_key(:not_authorized))
    GraphQL::Field.accepts_definitions(not_authorized: GraphQL::Define.assign_metadata_key(:not_authorized))

When converting this `UserType` class to the new 1.8 class-based API, I tried doing this:

    Types::UserType = GraphQL::ObjectType.define do
      field :birth_day, 'The day of the month this user was born on', Int, null: true,
        guard: ->(user, _args, ctx) { UserPolicy.new(ctx[:current_user], user).show_birth_date? },
        not_authorized: ->(_type, _field) { nil },
        resolve: ->(user, _args, _ctx) { user.birth_date&.day }
    end

I expected that was all I'd need to do, but instead when the types load I'm getting 

    ArgumentError: unknown keywords: not_authorized, guard
      /Users/zubin/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-19c3dcb073ec/lib/graphql/schema/field.rb:42:in `initialize'
      /Users/zubin/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-19c3dcb073ec/lib/graphql/schema/member/has_fields.rb:12:in `new'
      /Users/zubin/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-19c3dcb073ec/lib/graphql/schema/member/has_fields.rb:12:in `field'
      /Users/zubin/code/yei/rails/app/graphql/types/user_type.rb:21:in `<class:UserType>'

That leads me to believe I didn't convert the file to the new API correctly. Is that the case? If so, how can I repair it to correctly specify the metadata?

(mea culpa: I do not know if `metadata` is really the right word for this) :)

**Comment by benkimball** [comment]
Just a quick followup: I've since discovered that I can declare a `birth_day` method in the `UserType` class, inside of which I have access to `context` and `object` objects. From there it was simple enough to convert the resolver and the call to `UserPolicy`. But I still think I'm missing something important about middlewares and whether `Field.accepts_definitions` is still a thing in 1.8.

**Comment by rmosolgo** [comment]
Hey,  it's still a bit in flux, but I've documented my _goals_ for this, as well as techniques I've used while migrating GitHub's schema here: 

https://github.com/rmosolgo/graphql-ruby/blob/1.8-dev/guides/type_definitions/extensions.md

I've used all the techniques in ["Customization Compatibility"](https://github.com/rmosolgo/graphql-ruby/blob/1.8-dev/guides/type_definitions/extensions.md#customization-compatibility)  too, to gradually port "accepts_definitions" code into the class-based API.

Does that help at all??

**Comment by benkimball** [comment]
Absolutely. I'm going to close this issue, since I was able to figure out how to do the things I needed for my schema. Thanks!
