### ISSUE TITLE
[Pro] COMM-LICENSE references Contributed Systems refund policy

### ISSUE THREAD

**Issue by benkimball** [rmosolgo/graphql-ruby#1328]
Is the GraphQL Pro commercial license's reference to Contributed Systems' refund policy (§10(b)) intentional?

**Comment by rmosolgo** [comment]
No, an error in my (permitted) adaptation from Sidekiq's license, thanks for pointing it out!

**Comment by rmosolgo** [comment]
thanks again for sharing this, finally updated 😊
