### ISSUE TITLE
Slack link in README not working

### ISSUE THREAD

**Issue by jturkel** [rmosolgo/graphql-ruby#1331]
Clicking the "#ruby channel on Slack" link in the README results in the following:

![application error](https://user-images.githubusercontent.com/2598096/37168684-bb5324f6-22d3-11e8-9786-dec7496490d1.png)

**Comment by jturkel** [comment]
Looks like it's back up now. Closing the issue.

**Comment by rubendinho** [comment]
Link is broken again.
