### ISSUE TITLE
GraphQL.config?

### ISSUE THREAD

**Issue by golmansax** [rmosolgo/graphql-ruby#134]
Thoughts about a global config?  The specific use case I am thinking of is to default `debug = true` in `Schema.execute` for my tests.

I can scrape up a pull request if you're into this idea.  Thanks!

**Comment by rmosolgo** [comment]
How about a schema-level default for that instead? I think that would be a better fit.  (One design goal I have is to avoid global state, but rather keep things at the "smallest" scope possible.)

**Comment by rmosolgo** [comment]
of course, another solution would be a test helper: 

```ruby
def graphql_query(query_string, variables = {})
  MySchema.execute(query_string, variables: variables, debug: true) 
end
```

something like that might be more maintainable in the long run anyways

**Comment by golmansax** [comment]
cool, ill go with the test helper and see how it turns out
