### ISSUE TITLE
Namespace in Host App

### ISSUE THREAD

**Issue by jonasheinrich-akelius** [rmosolgo/graphql-ruby#1344]
Hi @rmosolgo, 

first of all thanks for this gem. I'm starting to use it for my company and so far I really like it. :)

At the moment (`graphql-1.7.12`), I see one little drawback: There seems to be no possibility to easily namespace classes/modules. Types for example live in the namespace `Types`.  I think this could clash with some other concept of types in a host app. Or if you write dedicated resolver class, you would most likely put them in `app/graphql/resolvers/...` and thus, they would live in the namespace `Resolvers`. 

It would be nice to be able to namespace things with something like `GraphQL`. That would help to really separate objects created for the `graphql` implementation from the rest of the application. 

I am aware that this probably is a problem of Rails and its autoloading behaviour itself. All folders in `app` get autoloaded automatically and therefore, files in `app/graphql/...` cannot have the namespace `GraphQL` (please correct me if I'm wrong). 

So, what are your thoughts on this? 
Thanks in advance!

Jonas

**Comment by rmosolgo** [comment]
Hi, a couple of thoughts on this: 

- graphql-ruby has no requirements about what Ruby constants you use for your types. You can put them in any namespaces that you want. 
- I really recommend _against_ using `GraphQL::` as your namespace. You'd be setting yourself up for naming conflicts! 
- If you want to use another namespace, for example `MyExampleNamespace`, use that as the folder name inside `app/graphql`, for example, `app/graphql/my_example_namespace/`. (The choice of `Types` => `app/graphql/types` is arbitrary, you can use any namespace you want.) 

I hope that helps! Feel free to reopen or leave another comment if those don't work for you or if they aren't clear.

**Comment by jonasheinrich-akelius** [comment]
Thanks for the fast response!

And yes, that helped a lot. I didn't realise that I am the one setting the `Types` namespace just by using `app/types/...`. 

I also thought about using the extra folder to achieve the namespace. To be honest, I think this feels a bit hacky. You would have a more or less blank folder `graphql` just to make Rails' autoloading jump through hoops. But this of course is Rails' fault if anyones. Sometimes I wonder if it would make sense to namespace models with `Models::`. But maybe I'm going to far here. :)

Again: Thanks. 👍
