### ISSUE TITLE
[PRO] uninitialized constant GraphQL::Pro::Subscriptions

### ISSUE THREAD

**Issue by rubenfonseca** [rmosolgo/graphql-ruby#1355]
I have graphql-pro version 1.5.9 and I was following this instructions to get Pusher + Redis working: http://graphql-ruby.org/subscriptions/pusher_implementation.html.

However after I set up everything I always get a "uninitialized constant GraphQL::Pro::Subscriptions" on my schema. Digging through the source code, I noticed that the class doesn't even exist. Was it removed by mistake from the gem?

**Comment by rmosolgo** [comment]
`GraphQL::Pro::Subscriptions` was added in version 1.6.0: 

https://github.com/rmosolgo/graphql-ruby/blob/master/CHANGELOG-pro.md#160-13-nov-2017

Can you update the gem version and try again?

**Comment by rubenfonseca** [comment]
Oops that was a rookie mistake. It all works fine now, thank you!
