### ISSUE TITLE
Missing errors on invalid types in development

### ISSUE THREAD

**Issue by dphaener** [rmosolgo/graphql-ruby#136]
If a type is not defined correctly, i.e.: `field :name, "This is missing a type argument"` the app will run fine in development with no errors as long as the type is not queried. In production however, all queries will fail (rightly so). 

FWIW I am using Puma in production and pre-loading the app. Here is a small Rails app that reproduces the problem: https://github.com/dphaener/graphql-test

**Comment by rmosolgo** [comment]
Ohhh I see ... this is tough. 

Firstly, a String _is_ a valid entry for field type. It gets looked up in the global namespace to find the type object. 

Secondly, type resolution starts with QueryType  & MutationType and follows the tree, going from field to field, finding all the types included in the schema. So any types which aren't connected to those roots (like `BreweryType` in the example) aren't found during that search :cry: 

Options? Hm...

- Provide a "Types" argument like they recently added to the JavaScript version: https://github.com/graphql/graphql-js/pull/327
- Provide some help for loading an entire `graph/` directory ? (`graphql-rails`?)

A `types:` argument would also with not mutating InterfaceTypes.

**Comment by dphaener** [comment]
I think providing some help loading the graph directory is a great idea. I've had issues surrounding loading all the type definitions in the right order, it can get a bit hairy with a larger application. If they're all preloaded, something like this would definitely cause an error I think.

As far as the `types` argument goes. Does this end up enforcing a strict set of types that can be used in the schema?

**Comment by rmosolgo** [comment]
> strict set of types?
No, it's just a way to add _additional_ types which can't be discovered by crawling fields from the schema roots. (Specifically, that's types who are only connected to the schema because they're members of an interface.)

**Comment by rmosolgo** [comment]
I think I've done all I can here: "floating" types can (must) be added with `types:` and types are validated as soon as you use `Schema.define`, so these errors will appear in development, too!
