### ISSUE TITLE
Cannot find record of id=<activerecord_id>

### ISSUE THREAD

**Issue by sAnti09** [rmosolgo/graphql-ruby#1363]
Hello. I am implementing the subscribe feature for graphql and I am hitting this wall wherein I can't seem to figure out why there is some inconsistency in the behavior of `subscriptions.trigger`. I am passing an model object in the third parameter and there are certain cases wherein it throws 'Cannot find record of id' error.

I have made sure that the record is persisted first before calling the trigger. Does it have something to do with threading and concurrency issues with the database connection?

**Comment by sAnti09** [comment]
I fixed it by by calling `Model.connection.commit_db_transaction` after persisting the model. It appears that the model is persisted on memory but the transaction is not committed yet to the database which produces a not found error when calling `subscriptions.trigger`.

**Comment by rmosolgo** [comment]
yep, this can happen with background jobs too. For example, Sidekiq can run so fast that the job will start before the transaction is finished 😆 

https://github.com/mperham/sidekiq/issues/322#issuecomment-7381319
