### ISSUE TITLE
Is it possible to define and use generic SuccessType which can be return from different mutations

### ISSUE THREAD

**Issue by trupti-crealytics** [rmosolgo/graphql-ruby#1365]
I want to define generic 'SuccessType' object which can have following fields
```
SuccessType = GraphQL::ObjectType.define do
  name "SuccessType"
  field :success, !types.Boolean
  field :message, types.String
end
```
And use this as a return field for the mutations.

I have two mutations for selecting and deleting users, and have used resolver functions for cleaner approach.

```
Types::MutationType = GraphQL::ObjectType.define do
 name "Mutation"

 field :selectUsers, function: Resolvers::SelectUsers.new
 field :deselectUsers, function: Resolvers::DeselectUsers.new
end
``` 
Code for one of the resolver function

```
class Resolvers::DeselectProducts < GraphQL::Function

  argument :user_id, !types.Int
  argument :project_ids, !types[types.String]

  # return type from the mutation
  type types.String

  def call(_obj, args, _ctx)
    user = User.find(args[:user_id])
    # some logic on to delete the user

    "product/products deleted successfully"
  end
end
```

Is it possible to create generic success type, so that instead of
```
# return type from the mutation
  type types.String
```
I can have 
```
# return type from the mutation
  type Types::SuccessType
```

Also how can I return `SuccessType` object instead of returning string `product/products deleted successfully`

**Comment by rmosolgo** [comment]
Hi, sorry I missed this issue before! I'm considering something similar for error types. 

In 1.8, you can extend the base `Mutation` or `RelayClassicMutation` classes to change what kind of GraphQL structure they generate. 

If you look at `RelayClassicMutation`, you can see how the generated field is extended to take an `input` argument: 

https://github.com/rmosolgo/graphql-ruby/blob/bb7627c5e43fd17236da8b09478af0c4c3278ac8/lib/graphql/schema/relay_classic_mutation.rb#L53-L59

You can also see `Mutation.generate_payload_type` which is how the return type of a mutation is created: 

https://github.com/rmosolgo/graphql-ruby/blob/bb7627c5e43fd17236da8b09478af0c4c3278ac8/lib/graphql/schema/mutation.rb#L161-L176

Perhaps you could override one of those methods to change the generated return type!
