### ISSUE TITLE
[1.8] Automatic camel casing of argument names leads to inconsistent behavior

### ISSUE THREAD

**Issue by jturkel** [rmosolgo/graphql-ruby#1373]
Argument names are automatically converted from snakecase to camelcase which is awesome for Ruby developers. Unfortunately this isn't well encapsulated on the input side:

```ruby
module Types
  class QueryType < Types::BaseObject

    class MyInput < Types::BaseInputObject
      argument :property_id, String, required: true
    end

    class MyOutput < Types::BaseObject
      field :message, String
    end

    field :do_something, MyOutput do
      argument :input, MyInput, required: true
    end

    def do_something(input:)
      # I would expect this to return true but it returns false
      puts "input.key?(:property_id): #{input.key?(:property_id)}"

      # I would expect this to return "my_property" but it returns nil
      puts "input[:property_id]: #{input[:property_id]}"
  
      # I would expect this to us the argument names that I specified e.g.
      # {property_id: 'my property'}  rather than {"propertyId"=>"foo"}
      puts "input.arguments.to_h: #{input.arguments.to_h}"

      nil
    end
  end
end
```
The current behavior makes it hard to do things like automatically pass an attributes hash to an ActiveRecord model from a mutation.

**Comment by rmosolgo** [comment]
Thanks for opening this issue! I agree with your points about `key?` and `[]`.

`input.arguments` is a reference to the underlying `Query::Arguments` instance, this is nifty for compatibility. Maybe we could change `input.to_h` to return the kind of hash you describe. (I started adding this behavior as `to_kwargs` in #1360)

**Comment by jturkel** [comment]
That sounds great to me since it gives developers the option of getting the raw input values from the `Query::Arguments` instance. For completeness I assume the following methods on `GraphQL::Schema::InputObject` would use the transformed keys:

* `[]`
* `key?`
* `to_h`
* `keys`
* `each`
* `any?`

**Comment by rmosolgo** [comment]
Took a crack at it in ae01e97e, will merge to 1.8-dev soon!
