### ISSUE TITLE
Pusher: "Received web hook with unknown key"

### ISSUE THREAD

**Issue by dpaola2** [rmosolgo/graphql-ruby#1381]
Received webhook with unknown key: a06472cd8653481db421

I have my web hook configured inside Pusher for "Channel Existence". I see this error in the logs:

`Received webhook with unknown key: a06472cd8653481db421`

and, the subscriptions list is not updated when viewing through the dashboard (mounted in rails routes).

I am not sure where to begin to debug this.

**Comment by dpaola2** [comment]
Lesson learned: always read the source. I assumed "key" meant the channel key. This looks like it was the issue, thank you for your debugging suggestion.

**Comment by rmosolgo** [comment]
Glad you got to the bottom of it! 🎉
