### ISSUE TITLE
Registering custom connections question

### ISSUE THREAD

**Issue by CodyBrouwers** [rmosolgo/graphql-ruby#1383]
Hey,

First off, thanks so much for all of the fantastic work on this gem. I've been digging into it over the past week and it is just really nicely put together!

I have a small question about registering a custom connection via the `register_connection_implementation` method. I've created a custom connection made specifically for a certain model's ActiveRecord::Relation, but when I register it using that method, the const `CONNECTION_IMPLEMENTATIONS` in the BaseConnection class goes from:

```ruby
{
  "Array" => GraphQL::Relay::ArrayConnection,
  "ActiveRecord::Relation" => GraphQL::Relay::RelationConnection
}
```

 to

```ruby
{
  "Array" => GraphQL::Relay::ArrayConnection,
  "ActiveRecord::Relation" => Connections::MyCustomConnection
}
```

Which then breaks every other connection implementation for a `ActiveRecord::Relation` collection that I want to use the original `GraphQL::Relay::RelationConnection`.

I looked at the source-code and it looks like when passing a class to `register_connection_implementation`, `.name` is called on it, which for every AR collection is going to be equal to `ActiveRecord::Relation` so it overwrites the default connection.

A solution I came up with was to call `.to_s` on the class instead which then preserves the namespace `MyModel::ActiveRecord_Relation`, so I've monkey-patched the two methods saving a connection and retrieving it like so:

```ruby
GraphQL::Relay::BaseConnection.class_eval do
  def self.connection_for_nodes(nodes)
    nodes.class.ancestors.each do |ancestor|
      conn_impl = GraphQL::Relay::BaseConnection::CONNECTION_IMPLEMENTATIONS[ancestor.to_s]
      return conn_impl if conn_impl
      conn_impl = GraphQL::Relay::BaseConnection::CONNECTION_IMPLEMENTATIONS[ancestor.name]
      return conn_impl if conn_impl
    end
    # Should have found a connection during the loop:
    raise("No connection implementation to wrap #{nodes.class} (#{nodes})")
  end

  def self.register_connection_implementation(nodes_class, connection_class)
    GraphQL::Relay::BaseConnection::CONNECTION_IMPLEMENTATIONS[nodes_class.to_s] = connection_class
  end
end
```

Throwing that into an initializer now gives me the proper constant:

```ruby
{
  "Array" => GraphQL::Relay::ArrayConnection,
  "ActiveRecord::Relation" => GraphQL::Relay::RelationConnection,
  "MyModel::ActiveRecord_Relation" => Connections::MyCustomConnection
}
```

With that said, my question is, is this the best approach or is there maybe a better alternative?

Versions:

graphql - `1.7.13`
rails   - `4.2.10`
ruby    - `2.4.1`

**Comment by rmosolgo** [comment]
Hi! This is a pretty common request. Honestly, your workaround is probably the best I've seen. The other thing I've seen is using named proxy classes to get special behavior for certain objects. I think the pagination system needs work, I want to rethink it soon (#1359) but for now I think this is a good workaround! Thankns for sharing the details.

**Comment by CodyBrouwers** [comment]
Ah cool, I considered a named proxy class but this seemed a little easier despite having to monkey-patch. Thanks for the comment and I'll keep an eye out for updates to pagination!
