### ISSUE TITLE
[1.8] Better handling of boolean attributes with "?" suffix

### ISSUE THREAD

**Issue by jturkel** [rmosolgo/graphql-ruby#1385]
Readers for boolean attributes in Ruby usually end with the `?` suffix. Ideally the new 1.8 class based API would handle this without an explicit configuration of the `method` e.g.

```ruby
module Types
   class MyResultType < Types::BaseObject
     # Ideally we wouldn't have to specify the method here
      field :valid, Boolean, method: :valid?
    end

  class QueryType < Types::BaseObject
    field :my_result, MyResultType

    def my_result
      OpenStruct.new(valid?: true)
    end 
end
```
Currently this results in the following error:
```
RuntimeError (Failed to implement MyResult.valid, tried:

- `Types::QueryType::MyResultType#valid`, which did not exist
- `OpenStruct#valid`, which did not exist
- Looking up hash key `"valid"` on `#<Types::QueryType::MyResultType:0x00007f9ba55537a8>`, but it wasn't a Hash
)
```
I can think of two potential ways to solve this:

1) First try to resolve `<field name>?` for booleans and then fallback to `<field name>`
2) Borrowing from [active_model_serializers](https://github.com/rails-api/active_model_serializers) allow the field name to be specified with the `?` suffix (e.g. `field :valid?, Boolean`) but strip of the suffix for the JSON member name.

**Comment by rmosolgo** [comment]
That's interesting, I noticed a lot of similar duplication in GitHub, but we have a slightly different convention: our Boolean fields (usually!) have a third-person verb, like `isValid` or `viewerCanUpdate`. I wonder if we should pick one way and provide first-class support for it 🤔

**Comment by jturkel** [comment]
We got our conventions from this [Ruby Style Guide](https://github.com/bbatsov/ruby-style-guide#bool-methods-qmark) which seems to be pretty widely used and has good enforcement via [Rubocop](https://github.com/bbatsov/rubocop). That said I haven't seen consistent naming conventions for boolean fields in GraphQL so it's possible that just dropping the `?` will prove to be insufficient for lots of scenarios.

**Comment by rmosolgo** [comment]
I'm going to close this because I'm fine with the current behavior and don't have plans to change it. However, I'm open to it -- if someone wants to submit a PR which offers this behavior in a way that doesn't introduce a breaking a change (for example, opt-in), I'd be happy to take a look!

**Comment by klyonrad** [comment]
I find this lack of functionality a bit of unintuitive. Ruby-graphQL *seems* to do a bit of effort in catering ruby idioms, especially by converting snake_case written fields to camelCase and then suddenly with Booleans you gotta figure.

There does not seem to a convention to have the third-person verb so something like `field :valid, Boolean` seems something that people might enjoy to write.
