### ISSUE TITLE
Can we can make the arguments mandatory inside the call method?

### ISSUE THREAD

**Issue by cyb-ahmadh** [rmosolgo/graphql-ruby#1387]
I am using `resolvers` for updating different attributes like this:

```
Types::UserInputType = GraphQL::InputObjectType.define do
  name 'User'

  argument :id, !types.Int
  argument :name, types.String
  argument :active, types.Boolean
  argument :startDate, Types::DateType, as: :start_date
  argument :endDate, Types::DateType, as: :end_date
end
```

```
module Resolvers
  class MutateUser < GraphQL::Function
    argument :user, UserInputType

    type !Types::UserType

    def call(_, args, _)
      User.find(args[:id])
    end
  end

  class DeleteUser < MutateUser
    def call(_, args, _)
      super.destroy
    end
  end

  class ActivateDeactivateUser < MutateUser
    def call(_, args, _)
      raise MandatoryFieldMissing, "Field active is missing" if args[:user][:active].nil?
      user = super
      user.update(active: args[:active])
      user
    end
  end
end
```

Is there any other way to not use `raise` and make the `:active` field mandatory inside the `def call` method ?

**Comment by cyb-ahmadh** [comment]
I missed to mention one thing that i want `active` field mandatory only for `ActivateDeactivateUser`.

**Comment by rmosolgo** [comment]
Ah, to do that, you could either: 

- Use a _different_ input type for that mutation, and add `!` to that different input type 
- Or, do a runtime check, as shown in your snippet above. 

At the GraphQL language level, there's no way to enforce non-null on a case-by-case basis!
