### ISSUE TITLE
Error handling in custom scalars

### ISSUE THREAD

**Issue by eapache** [rmosolgo/graphql-ruby#139]
@rmosolgo it's not clear to me from poking through the code what the expected pattern is for handling errors in custom scalar formats (e.g. when I define a `Date` scalar and the input doesn't conform to the required format). Since `coerce_result` is called in `get_finished_value` there doesn't seem to be any mechanism for rescuing an error that is raised or returned. What did you have in mind?

cc @dylanahsmith

**Comment by dylanahsmith** [comment]
It looks like the coerce procs expect nil to be returned for invalid values

**Comment by eapache** [comment]
Except there's no code I could find to distinguish between "nil because the raw input was nil" and "nil because of an error".

**Comment by dylanahsmith** [comment]
Oh, I guess there is only something for input coercion: https://github.com/rmosolgo/graphql-ruby/blob/061d0577a79976ecbb838599f7fe1464fb6ee0ee/lib/graphql/scalar_type.rb#L24

For result coercion, the error isn't really a client error anyways, so should get treated as an internal error.  I think right now that causes that causes the entire query to fail, but we could rescue it to give a partial result that just has `nil` for that field selection.

**Comment by rmosolgo** [comment]
Yes, if the coerce proc returns nil, it's handled as invalid. 

I think the distinguishing code you're looking for is here: https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/base_type.rb#L86

If the incoming value is `nil`, it's never passed to coerce procs, it's just left alone.

Down the road, a non-nil value is passed to the coerce proc:  https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/scalar_type.rb#L23

(Unfortunately, the values are coerced twice. It's a bit inefficent, but it's worth it for the feature (#113) and I think it will be a straightforward refactor to coerce & validate in one pass..!)

I've just pushed a commit with a spec to describe that behavior: https://github.com/rmosolgo/graphql-ruby/commit/061d0577a79976ecbb838599f7fe1464fb6ee0ee

How does that look for your case?
