### ISSUE TITLE
Arguments can't be accessed with symbols

### ISSUE THREAD

**Issue by devknoll** [rmosolgo/graphql-ruby#14]
Not a bug, just a little annoying.

Arguments in `resolve` have to be accessed using a string (despite being defined as symbols). It might be nice to use something like `HashWithIndifferentAccess` from Rails, and automatically stringify symbols, just for the developers sake.

**Comment by rmosolgo** [comment]
Yeah, I guess that's confusing to define with symbols but access with strings! 

I'm torn on `HashWithIndifferentAccess`, it's convenient but it also introduces some ambiguity ("What kind of hash is this?"). Besides that we just yanked out ActiveSupport in #8 

Hmmm

**Comment by rmosolgo** [comment]
I was also thinking back to an old API  where you declare things like 

```ruby
Field.new do |f, types| 
  f.arg("argument_name", types.String)
end
``` 

Instead of a hash

**Comment by rmosolgo** [comment]
:tada:  https://github.com/rmosolgo/graphql-ruby/commit/98cea2f0e66ccf2d03273675aa72db1fa3f7e93e

It's a bit weird because the `args` value isn't a hash (it's a `GraphQL::Query::Arguments`) but I think it's enough, and we could delegate more stuff to the underlying hash if need be.

**Comment by devknoll** [comment]
@rmosolgo Anything preventing symbols from being used on InputObjectTypes as well?

**Comment by rmosolgo** [comment]
Oh, I expect it to "just work", does it not??

**Comment by rmosolgo** [comment]
(They should all be using `GraphQL::Query::Arguments` objects)

**Comment by devknoll** [comment]
Ahhh, maybe you're right. Disregard, I'll follow up if necessary. Thanks :smile:

**Comment by rmosolgo** [comment]
I expect it to work because `Query::Arguments` gets used for: 

- field arguments https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graph_ql/query/field_resolution_strategy.rb#L7
- input object types https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graph_ql/query/arguments.rb#L29-L30

so it should be `Query::Arguments` objects all the way down...

**Comment by devknoll** [comment]
@rmosolgo You're right, this seems to work. I think the actual problem is that an input type in $variables isn't making it down to resolve correctly.
