### ISSUE TITLE
[1.8] Accessing a GraphQL::Schema::Field's type

### ISSUE THREAD

**Issue by rylanc** [rmosolgo/graphql-ruby#1410]
I've started migrating my code over to the new class-based API (which is great!) and I've noticed there's no easy way to examine a `GraphQL::Schema::Field`'s type. Are there any plans on adding an accessor? It would be very helpful for testing and extending my `GraphQL::Schema::Object` subclasses.

For example:
```ruby
expect(SomeObject.fields['some_field'].type).to eq(AnotherObject)
```

**Comment by rmosolgo** [comment]
yes, I've added something like that to #1407 ! Feel free to try out that branch or copy the method into your project as monkey patch and let me know how it works out for you.

**Comment by rylanc** [comment]
That's good to hear! Are there plans on adding it to `GraphQL::Schema::Argument` as well?

**Comment by rmosolgo** [comment]
No, but there can be ... Just  added to #1407 also :)
