### ISSUE TITLE
[1.8] Inheriting arguments from input object

### ISSUE THREAD

**Issue by joshforbes** [rmosolgo/graphql-ruby#1412]
If I inherit from another input object the arguments are not passed down.

If I include GraphQL::Schema::Member::HasArguments on the input object I am inheriting from - then everything works as expected.

Pretty sure it has something to do with this in the HasArguments module:

![image](https://user-images.githubusercontent.com/3682518/38636459-3baef418-3d96-11e8-9420-c2191c47dab5.png)

which is returning an empty hash

**Comment by rmosolgo** [comment]
aww bummer, thanks for opening the issue! I bet that check could be changed to `if superclass.respond_to?(:arguments)`, I updated a bunch of the other ones but must have missed one :S
