### ISSUE TITLE
function definition works via kwarg but not via the function method in a block

### ISSUE THREAD

**Issue by Mori** [rmosolgo/graphql-ruby#1414]
Where

    class FindRecord < GraphQL::Function
      ...
      argument :id, !types.ID
      ...
    end

this variation of a field definition within a `GraphQL::ObjectType.define` block works without error:

     field 'd1', DirectoryType, function: FindRecord.new(:directory) 

But for the same query this fails with the error message "Field 'd2' doesn't accept argument 'id'":
                                                                
    field 'd2', DirectoryType do                                                                                
      function FindRecord.new(:directory)                                                               
    end      

After those fields are defined, for both `d1` and `d2` the value of `target.fields['d?'].function` is the same (with different object ids). But it looks like in the block version the function doesn't get applied to the field.

It also doesn't work when I skip the `field` helper and define the field like this:

    target.fields[name] = GraphQL::Field.define {
      ...
      function FindRecord.new(:directory)
      ...
    }

Am I calling the function method wrong? Any suggestions appreciated.

Thanks ...

**Comment by Mori** [comment]
No. This is in version 1.7.14. I can't upgrade for a while, but if you can't replicate in 1.8 it may not be worth tracking down. I've stumbled around it. Thanks for looking.

**Comment by rmosolgo** [comment]
Sorry, I'm not sure what was wrong! 1.8+ has a class-based replacement for Functions called [Resolver](http://graphql-ruby.org/type_definitions/resolvers.html), it has a much nicer API, feel free to give it a try if you have more trouble.
