### ISSUE TITLE
possible_types on Union classes raising InvalidNameError

### ISSUE THREAD

**Issue by mohamadbitar** [rmosolgo/graphql-ruby#1428]
While trying to migrate to the new version of GraphQL, converting union files to the below format: 
```
class Types::Unions::Test < Types::BaseUnion
  graphql_name 'TestType'
  possible_types Types::TypeForUnion,
                 Types::Type2,
                 Types::Type3
end
```

results in an error:
`GraphQL::InvalidNameError: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but 'TYPES/TYPEFORUNION' does not`

Any ideas on how to resolve this?

**Comment by rmosolgo** [comment]
Weird! I think it should be validating the result of `Types::TypeForUnion.graphql_name`, can you puts that out for debugging, for example, add to the top of your file: 

```ruby 
puts Types::TypeForUnion.graphql_name 
class Types::Unions::Test < Types::BaseUnion 
  # ... 
end 
```

Does the output match the name in the error message? If so, is there a chance that `TypeForUnion` is getting a custom name from something?

**Comment by mohamadbitar** [comment]
It outputs `TypeForUnion`

**Comment by rmosolgo** [comment]
Ok, hmm, could you share the stack trace of the error?

**Comment by mohamadbitar** [comment]
```
GraphQL::InvalidNameError: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but 'TYPES/TYPEFORUNION' does not
from /home/mohamad/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.8.0.pre10/lib/graphql/name_validator.rb:7:in `validate!'
```

this is the full stacktrace I'm getting from the console

**Comment by rmosolgo** [comment]
Ick! That's not much of a stack trace 😖 

That's so odd that it's all caps, with a slash. It's like some Rails methods are being called on the string: 

```ruby
irb(main):007:0> "Types::TestForUnion".upcase
# => "TYPES::TESTFORUNION"
irb(main):009:0> "Types::TestForUnion".upcase.underscore
# => "types/testforunion"
irb(main):008:0> "Types::TestForUnion".upcase.underscore.upcase
# => "TYPES/TESTFORUNION"
```

But it doesn't make sense _why_ that would be called 😖

**Comment by mohamadbitar** [comment]
Found the problem out, looks like we were accessing the `.name` on a union instead of `.graphql_name` . Thanks for the support :)
