### ISSUE TITLE
[1.8] Instrumentation compatibility

### ISSUE THREAD

**Issue by exAspArk** [rmosolgo/graphql-ruby#1429]
Hey!

I have 2 issues when I'm trying to instrument fields by using the `1.8-dev` branch:

1. Type class mismatch

For example, I have the following code in my app:

```ruby
class User < ApplicationRecord
  ...
end

class Types::User < GraphQL::Schema::Object
  ...
end
```

When I'm trying to [introspect](https://github.com/exAspArk/graphql-guard/blob/4536febbae729c21f20f6952a534e5971fa0ca30/lib/graphql/guard.rb#L27) a field, I'm getting the following:

```ruby
def instrument(type, field)
  binding.pry
end

pry> type == Types::User
# => false
# ^ it returns "true" with v1.7 

pry> type
# => User

pry> type.class
# => GraphQL::ObjectType
```

2. Type instance instead of the passed object as the first argument

When I'm trying to [redefine](https://github.com/exAspArk/graphql-guard/blob/4536febbae729c21f20f6952a534e5971fa0ca30/lib/graphql/guard.rb#L32) the `resolve_proc`, it passes the following:

```ruby
->(obj, args, ctx) { binding.pry }

pry> obj.class
# => Types::User
# ^ it returns "User" with v1.7 

pry> obj.object
# => #<User:0x007fb9fa86abd0>
```

Are you planning to keep the instrumentation compatible with the previous gem versions? :)

**Comment by exAspArk** [comment]
Thank you for your reply! `type.metadata[:type_class]` works fine 👍 

> Sometime, execution will use the classes instead of ObjectType instances ... but not yet!

Are you still planning to do that? :)

**Comment by rmosolgo** [comment]
Yes, 1.9-dev branch has a new runtime that uses class-based types only, although in a few cases it's still supported by the compatibility layer. Hoping to remove that too, but not quite there yet!

**Comment by rmosolgo** [comment]
Removing the compat layer is WIP in #2363 , closing this issue as it doesn't have any specific work to do.
