### ISSUE TITLE
Allow `super` inside of resolver methods

### ISSUE THREAD

**Issue by theorygeek** [rmosolgo/graphql-ruby#1433]
Right now, when you define a field like:
```ruby
class MyClass < GraphQL::Schema::Type
  field :some_field, SomeType
end
```

The code for resolving this field lives in `GraphQL::Schema::Field#resolve_field_dynamic`, and it goes hunting for a method, hash key, etc.

What if _instead_, the behavior was something more like:
- Inject a dynamic module into `MyClass` when it is inherited (eg, `MyClass::DefaultFieldResolvers`)
- When you call `field :some_field`, it dynamically defines a method like `MyClass::DefaultFieldResolvers#some_field`, and all of that hunting logic lives there.

The advantage is that you get a natural way to define your method, but you can fall back to the built-in behavior:

```ruby
field :some_field, SomeType

def some_field
  preload(:something).then { super }
end
```

The key is that now you can call `super` to fall back to the original hunt-and-search behavior. Now, you probably wouldn't really need this in the trivial scenario that I just shared, but imagine if instead, you were using a _macro_ to generate your field helpers:

```ruby
field :some_field, SomeType
field :some_other_field, SomeType

preload :another_model, fields: [:some_field, :some_other_field]
```

Now it would be easy to create that `preload` macro, since it could just dynamically define those methods, something like:
```ruby
definition_methods do
  def preload(association, fields:)
    fields.each do |name|
      define_method(name) { MagicPreloader.preload(object, association).then { super() } }
    end
  end
end
```

I'd be happy to take a stab at putting together a PR for this. I think the changes would involve:
- Give `HasFields` some `extended`/`included` methods so that it generates those modules, and injects them into your classes. Interfaces might be a little tricky, and might have to do some book-keeping around inheritance.
- Change `HasFields::add_field` so that it adds the field, and also defines the default resolver method.
- Modify `GraphQL::Schema::Field` so that `resolve_field_dynamic` just does a dumb dispatch to your type class.

Thoughts?

**Comment by rmosolgo** [comment]
Thanks for opening this method. I wondered, "will we want `super`?" and it didn't take long to find out 😆  I totally agree that it will come in handy. I've seen it used in AR models too, so it seemed analogous.

I have a design preference to keep resolution inside `GraphQL::Schema::Field` _too_, so that you can mess with that class to affect resolution of the object fields that use it. I took a stab at this with #1411 , although it's far from done. 

In that case, instead of: 

> `resolve_field_dynamic` just does a dumb dispatch to your type class

It might be the opposite, the something like, the auto-created method would do something like 

```ruby 
def some_field(**args)
  self.class.fields[:some_field].resolve(@object, args, @context) 
end 
```

That way, a definition in the class could still use `super`, but the bulk of the logic would still be in the field class itself. What do you think of that, would it also work?

**Comment by theorygeek** [comment]
Ah yeah, that is good. I had started to take a stab at it too, and felt bad for spreading resolution logic around the codebase.

>  "will we want `super`?" and it didn't take long to find out 😆
Haha, yeah, I think it would be really nice to have. It is a clean way to get back to the "default" behavior.

**Comment by rmosolgo** [comment]
I started taking a stab at it here, what do you think? 

https://github.com/rmosolgo/graphql-ruby/tree/field-methods-super

Still to-do is interface fields 😬  but that will have to be after lunch! Feel free to take a crack at it yourself if you have the time.

**Comment by theorygeek** [comment]
Yeah, that looks really nice! That is almost exactly the same path that I was going down, except that I had tried to put the `def inherited` stuff into the `HasFields` module.

**Comment by rmosolgo** [comment]
Ah yeah, that's nice to put it all there, here's what I was able to cook up so far: 

https://github.com/rmosolgo/graphql-ruby/pull/1437

**Comment by rmosolgo** [comment]
donezo 🎉
