### ISSUE TITLE
Double execution of GraphQL queries?

### ISSUE THREAD

**Issue by tap349** [rmosolgo/graphql-ruby#1435]
Good day!

I've accidentally found that GraphQL query string is duplicated in Rails log:

```
{"query"=>"
    query AllUsers {
      users {
        name
      }
    }
  ", "graphql"=>{"query"=>"
    query AllUsers {
      users {
        name
      }
    }
  "}}
```

Even though request payload sent from client doesn't contain `graphql` parameter (with nested `query` parameter).

Also we use AppSignal for bugtracking and there's such a line in its event timeline for all GraphQL requests:

```
process_action.action_controller
    ...
    execute.graphql × 2
```

So it looks like each GraphQL query is executed twice.

So my question: does duplication of query in params cause its double execution? Or it has no impact on execution at all and this is how `graphql-ruby` is supposed to work?

**Comment by rmosolgo** [comment]
How strange! In fact, GraphQL doesn't know anything about controller params. It only knows about the arguments you give to `MySchema.execute`. Can you share the code where you take controller params and pass them to `execute`? 

Also, another way to figure out what's happening is to find your `Query.users` field and put some debugging there, like a `puts` or `binding.pry`, to see if it's really being called twice, and you could use `caller` to look back and see where it's being called from. 

In fact, if you find it's being called twice, if you can share the two responses from the `caller` method, I'm happy to help you debug where the two calls are coming from!

**Comment by tap349** [comment]
Thanks for quick for response.

I've examined the arguments supplied to `MySchema.execute` - I pass query as described in your `Getting Started` guide:

```ruby
result = MySchema.execute(
  params[:query],
  variables: ensure_hash(params[:variables]),
  context: { current_user: current_user },
  operation_name: params[:operationName]
)
```

So it turns out the second query from `params` (`params[:graphql][:query]`) is not used at all.

Resolver for `users` field (from example above) is also called once.

I still don't know where the second query comes from - it's not sent from client but appears to be equal to original query:

```
> params[:query] == params[:graphql][:query]
true
```

But anyway `graphql-ruby` gem must be working correctly.

So the issue can be closed - thanks for your help!
