### ISSUE TITLE
[1.8] GraphQL::Relay::Node.field incompatible

### ISSUE THREAD

**Issue by bessey** [rmosolgo/graphql-ruby#1436]
(Wow I'm a real bee in your bonnet this week, sorry! This is totally unrelated to my auth work)

We're in the process of switching to 1.8 and I've hit my first road block in my Query type! Post upgrade script, the whole thing runs fine except for:

```ruby
    field :node, GraphQL::Relay::Node.field, null: true do
      argument :id, ID, required: true
    end

    def node(id:)
      GlobalID::Locator.locate_signed id
    end
```

Which when present causes schema compile failure:

```
RuntimeError (Unhandled to_type_name input: <Field name:not-named desc:Fetches an object given its ID. resolve:GraphQL::Relay::Node::FindNode> (GraphQL::Field)):
```

**Comment by rmosolgo** [comment]
Not at all, glad to see someone else try the upgrade!

Huh, sorry, it assumes that the second positional argument is the `type`, even though as your example shows, it may also be a GraphQL::Field instance in the old API. 

I think you could add the `field:` keyword, like this: 

```ruby
    #             V
    field :node, field: GraphQL::Relay::Node.field, null: true do
      argument :id, ID, required: true
    end

    def node(id:)
      GlobalID::Locator.locate_signed id
    end
```

However, I think in that case it will ignore the other options, it assumes that the given field is finished. Could you remove the extra settings there? (eg `null:`, and the block with `argument` ?)

**Comment by bessey** [comment]
That did it, thanks. Although not sure wether to close because the error could be more helpful.
