### ISSUE TITLE
[1.8] [pro] Authorization: Schema#unauthorized_object not ported to class based system

### ISSUE THREAD

**Issue by bessey** [rmosolgo/graphql-ruby#1441]
A note for others perhaps, as far as I can tell if you use `Schema#unauthorized_object` and want to convert your Schema to the class based API, this is necessary

```ruby
class MySchema < GraphQL::Schema
  # ...
end
MySchema.metadata[GraphQL::Pro::Access::UNAUTHORIZED_OBJECT_KEY] = -> (obj, ctx) {
    err = GraphQL::ExecutionError.new("You don't have permission to see #{obj}")
    ctx.add_error(err)
  }
```

**Comment by rmosolgo** [comment]
Sorry about this trouble, that hook was reused in the class-based API for a slightly different purpose 😖  I'm glad you found a solution!
