### ISSUE TITLE
[1.8] [pro] Authorization: Schema using class based API fails to redefine authorize

### ISSUE THREAD

**Issue by bessey** [rmosolgo/graphql-ruby#1442]
I'm still using that AllowScalarFields instrumenter that you recommended a while back for my unusual auth needs. It has stopped working with 1.8, even though I can see it _is_ redefining on the relevant fields, so I'm guessing despite having this in my Schema:

```ruby
  instrument(:field, Instrumenters::AllowScalarFields.new)
  authorization(:cancan, fallback: {authorize: :read_api}, ability_class: AbilityDelegator)
```

```ruby
module Instrumenters
  class AllowScalarFields
    def instrument(type, field)
      field_return_type = field.type.unwrap
      # If a parent object has passed authorization, then its scalars may be accessed:
      if field_return_type.is_a?(GraphQL::ScalarType)
        field = field.redefine(authorize: :always)
      end
      field
    end
  end
end

```

In 1.7, this overrode `authorize: :read_api` with `authorize: :always` on all scalars, but on 1.8 at runtime I am still seeing `can? :read_api` calls to scalars. I'd like to give a more detailed explanation but I'm struggling to find where the fallback proc is in `graphql-pro`, so I can't instrument with puts / prys.

Smells like the order in which these are applied has changed between 1.7 and 1.8, perhaps due to what you mentioned here? https://github.com/rmosolgo/graphql-ruby/issues/1429#issuecomment-382755016

**Comment by bessey** [comment]
PS I tried rewriting to handle the new `GraphQL::Schema::Scalar` in case that was the problem, to no avail:
```ruby
module Instrumenters
  class AllowScalarFields
    def instrument(type, field)
      field_return_type = field.type.unwrap
      # If a parent object has passed authorization, then its scalars may be accessed:
      case field_return_type
      when GraphQL::ScalarType, GraphQL::Schema::Scalar
        field.redefine do
          authorize :always
        end
      else
        field
      end
    end
  end
end
```

**Comment by rmosolgo** [comment]
Sorry for the trouble with using the old authorization plugin with a class-based schema. The best of that system (including a lot of your feedback about authz context! 🙇 ) was rolled into a class-based framework which is part of GraphQL-Ruby: https://graphql-ruby.org/authorization/overview.html

I hope that works better for you!
