### ISSUE TITLE
[1.8] using connection in class-based API

### ISSUE THREAD

**Issue by SeanRoberts** [rmosolgo/graphql-ruby#1449]
```
# base_object.rb
class Types::BaseObject < GraphQL::Schema::Object
end

# query.rb
class Types::Query < Types::BaseObject
  connection :posts, Types::Post.connection_type

  def posts
    ::Post.all
  end
end
```

This raises `undefined method 'connection' for Types::Query:Class`

Is it possible to use `connection` with the class-based API, or not yet?

**Comment by rmosolgo** [comment]
There is no `connection` method in 1.8, here are some details: http://graphql-ruby.org/schema/class_based_api.html#connection-fields--types

Instead, connection wrappers are applied if: 

- The return type's name ends in `Connection` (like `PostConnection` in your example above)
- Or you explicitly pass `connection: true` 

You can use `connection: false` to opt out. Feel free to reopen this if you have any other questions or trouble!

**Comment by mull** [comment]
How does one go about implementing custom edges? I have a projectFeed connection which returns a projectFeedEdge whose _node_ in turn is a ProjectFeedUnion. For whatever reason using the .define syntax is causing me circular dependency errors so I'm trying to just get rid of it entirely.

So I _had_ something like this:

```
Connections::ProjectFeed = Types::Unions::ProjectFeed.define_connection(
  edge_type: Types::Edges::ProjectFeed
)

Types::Edges::ProjectFeed = ::Types::Unions::ProjectFeed.define_edge do
  field :node, ::Types::Unions::ProjectFeed do
    resolve ->(edge, _args, _ctx) {
      # edge.node here is a ProjectFeedFeedItem model
      # which has foreign keys to a bunch of other tables
      node = edge.node
      if node.note_id
        Loaders::RecordLoader.for(Note).load(node.note_id)
      elsif node.file_id
        Loaders::RecordLoader.for(FileResource).load(node.file_id)
      elsif node.task_id
        Loaders::RecordLoader.for(Task).load(node.task_id)
      end
    }
  end
end

Types::Project = Graphql::ObjectType.define do
  connection :feed, Connections::ProjectFeed do

    resolve ->(project, args, _ctx) {
      feed_items = project.feed_items.order('created_at DESC')
    }
  end
```

I can't quite figure out how to translate this into the new syntax. Any help appreciated! ❤️

**Comment by yskkin** [comment]
```ruby
ParentConnection = GraphQL::UnionType.define do
 name 'ParentConnection'
 possible_types [Child1Connection, Child2Connection]
end
```

Once this union is upgraded to class-based one, listing API for `ParentConnection.connection_type` (its graphql_name is ParentConnectionConnection) stop working.

>  `No connection implementation to wrap Child1Connection (#<Child1Connection:0x000000010c9faa30>)`

Is there way to enable connection but prevent recursively handle that even if name of return type end with `Connection`?
