### ISSUE TITLE
1.8 How do I declare arguments on a field in the class-based API?

### ISSUE THREAD

**Issue by blevine** [rmosolgo/graphql-ruby#1450]
Not sure where to put the argument declarations without using blocks when declaring a field.

**Comment by fameoflight** [comment]
I think you have to use blocks to put arguments, here is what I have in my schema file 

  field :benefits, [BenefitType], null: true do
    argument :status, String, required: false, default_value: 'active'
  end

**Comment by blevine** [comment]
Yep.  That's it.  I guess a thought were was a non-block way of doing everything in the class-based API.  I'll close this issue.
