### ISSUE TITLE
1.8: support for 'property' keyword in field definitions?

### ISSUE THREAD

**Issue by blevine** [rmosolgo/graphql-ruby#1456]
Is the 'property' keyword no longer supported in the class-based API.  E.g.:

`field :viewableRoleNames, [String], property: :viewable_roles, null: false`

results in a 'unknown keyword: property' error

**Comment by rmosolgo** [comment]
Use `method:` instead! The auto-upgrader should make that transform for you, please share the source code if it didn't work. Docs: 

http://graphql-ruby.org/type_definitions/objects.html#field-resolution

**Comment by DouglasBlumeyerOmadaHealth** [comment]
I don't see that the docs have been updated appropriately: https://www.rubydoc.info/gems/graphql/GraphQL/Field#property-instance_method

**Comment by rmosolgo** [comment]
Sorry about the hangup! That page describes `GraphQL::Field`, a legacy object still used under the hood in some cases. When you build a class-based schema, it makes `GraphQL::Schema::Field`s instead, see: https://www.rubydoc.info/gems/graphql/GraphQL/Schema/Field

Sorry for the confusion. With such a big migration, I don't really expect to remove `GraphQL::Field` until a 2.0 version ... maybe the end of this year??
