### ISSUE TITLE
Relay support in 1.8?

### ISSUE THREAD

**Issue by blevine** [rmosolgo/graphql-ruby#1466]
I'm wondering whether there will be support for Relay conventions in 1.8.  For example, prior to 1.8 we'd define a mutation using `input_field`s. The mutation would be created with a single `input` argument comprised of the input_fields.  Will something like this be supported in 1.8 or are we responsible for creating the input argument and constructing our own `InputType` subclasses that conform to Relay conventions?

**Comment by fameoflight** [comment]
You can use GraphQL::Schema::RelayClassicMutation

I have class defined in my code base  which make all mutations relay ones 

```
class BaseMutation < GraphQL::Schema::RelayClassicMutation
end
```

We have been using it successfully at [www.goodlyapp.com](www.goodlyapp.com)

**Comment by blevine** [comment]
Great.  Thanks @fameoflight
