### ISSUE TITLE
Auto use graphql batch for associations [Class based API]

### ISSUE THREAD

**Issue by fameoflight** [rmosolgo/graphql-ruby#1467]
Just wondering what is the best way to go about implementing graphql batch automatically if the field name is for an association. 

I can certainly do this if I auto write resolve method on field, just wondering if it possible to do this with new method level fields?

Is there any common method get for each field like resolve in mutation?

**Comment by Willianvdv** [comment]
The gem doesn't provide an automatic batching system. You could implement it yourself using instrumentations or maybe a gem like https://github.com/ConsultingMD/graphql-preload is the thing you're looking for.

Hopefully, this answers your questions!

**Comment by jturkel** [comment]
[goldiloader](https://github.com/salsify/goldiloader) can also help for association eager loading (assuming the owning models have been loaded via a single query).

**Comment by Willianvdv** [comment]
@jturkel thanks! Nice gem btw!

**Comment by fameoflight** [comment]
What is the difference between preloader and graphql batch?
