### ISSUE TITLE
Negative offset breaks/crashes PostgreSQL

### ISSUE THREAD

**Issue by karki011** [rmosolgo/graphql-ruby#1468]
I keep running to this error, is there a solution for this.

 I tried to look at past solution but the link is not found.

ActiveRecord::StatementInvalid · PG::InvalidRowCountInResultOffsetClause: ERROR: OFFSET must not be negative : SELECT DISTINCT "positions".* FROM "positions" WHERE "positions"."deleted_at" IS NULL ORDER BY "positions"."id" DESC LIMIT 10 OFFSET -10

Any help would be helpful.

THnaks

**Comment by Willianvdv** [comment]
Hey @karki011, I've seen this error before but unfortunately I wasn't able to reproduce. It would be really helpful if you could submit a PR with a failing spec!

**Comment by rmosolgo** [comment]
Closed as stale
