### ISSUE TITLE
Log graphql executor errors in production

### ISSUE THREAD

**Issue by zjlovezj** [rmosolgo/graphql-ruby#147]
Hi,

https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/query/executor.rb#L22
As I understand, in production env, if the graphql execution failed, the error won't be logged.

```ruby
def result
        execute
rescue GraphQL::ExecutionError => err
        query.context.errors << err
        {"errors" => [err.to_h]}
rescue StandardError => err
        query.context.errors << err
        query.debug && raise(err)
        message = "Internal error" # : #{err} \n#{err.backtrace.join("\n  ")}"
        {"errors" => [{"message" => message}]}
end
```

Should the error be logged?

Thanks

**Comment by rmosolgo** [comment]
Yes, I think you're basically right! The current error handling situation was roughly inspired by the JS implementation, but it's not doing us any favors. 

Ironically, the best solution at the moment is to use the `debug: true` option when you execute your query, then handle the error _outside_ graphql. 

I'm hoping to revamp error handling for the next release!

**Comment by rmosolgo** [comment]
0.15 doesn't gobble errors by default :tada: :) Feel free to rescue, log and `Bugsnag.notify` as you see fit!
