### ISSUE TITLE
Transformed arguments on functions bug

### ISSUE THREAD

**Issue by mohamadbitar** [rmosolgo/graphql-ruby#1473]
So after I ran the upgrader on my functions files, the arguments transformed from camelCase to snake_case (expected behavior). Although, now from my GraphiQL I can only use the snake_case arguments.

In my opinion, it should be translated to the FE into camelCase again (like what's happening with fields on types for example) or at least those arguments should not have been transformed.

**Comment by mohamadbitar** [comment]
P.S.: arguments on mutations still get translated *correctly* to the FE 
i.e. BE's `person_id` ==> FE's `personId`

**Comment by rmosolgo** [comment]
Sorry, but you should revert the transformation on the GraphQL::Function files. They don't change at all with 1.8, so you should keep them as they were.
