### ISSUE TITLE
1.8: Is GraphQL::Schema::Member::HasArguments using the '<=

### ISSUE THREAD

**Issue by blevine** [rmosolgo/graphql-ruby#1475]
In prototyping solutions for #1474. I created a subclass of `GraphQL::Schema::Mutation` called `DeleteByIdMutation` which will be subclassed by the actual mutation class. `DeleteByIdMutation` declares a single argument called 'id'.  However, subclasses of `DeleteByIdMutation` were not including that argument. I noticed the following code in `GraphQL::Schema::Member::HasArguments#arguments`:

`inherited_arguments = ((self.is_a?(Class) && superclass <= GraphQL::Schema::Member::HasArguments) ? superclass.arguments : {})`

I don't think the class comparison operator can be used to determine whether the class extends the given module.  In the Rails console, I tried:

`GraphQL::Schema::Mutation <= GraphQL::Schema::Member::HasArguments`

which returned nil.  So if one creates a subclass of `GraphQL::Schema::Mutation` that declares arguments, subclasses of that subclass will not inherit those arguments.

**Comment by rmosolgo** [comment]
I think this is fixed by https://github.com/rmosolgo/graphql-ruby/pull/1432, try upgrading to the latest version and please reopen this if you have any trouble!
