### ISSUE TITLE
1.8 (class-based API): Declaration errors in schema result in LoadError errors during query execution

### ISSUE THREAD

**Issue by blevine** [rmosolgo/graphql-ruby#1476]
If there's an error somewhere in the schema declaration, the result during execution of a query is a LoadError which does not describe the actual source of the problem.

For example, I insert a typo in my schema file (e.g. I type 'mtation' instead of 'mutation'). When I execute the query, the exception is something like:

`LoadError (Unable to autoload constant Types::Query, expected /path/to/file/types/query.rb to define it):`

The actual constant that is reported in this error seems to vary depending on where the real problem is. I can also reproduce this when there's an error in one of my GraphQL type classes.  The LoadError is reported on some constant that is not related to the class that contains the error. This makes it very difficult to determine where the problem actually is.

**Comment by rmosolgo** [comment]
What's your Rails version? 

If it's less than latest `5.1.x`, have you already tried the patch in https://github.com/rmosolgo/graphql-ruby/issues/651#issuecomment-357339249?

**Comment by blevine** [comment]
Rails version is 5.2.0

**Comment by blevine** [comment]
Just upgraded to pre11 where there are some breaking changes according to the release notes.  I think I've made the appropriate changes in my code (e.g., interface is not a module), but I must have missed something.  So now I'm getting the LoadError (on my BaseObject class this time) and I have no idea where the real error is.

**Comment by rmosolgo** [comment]
So brutal, I think I need to update a demo app to understand it better, since GitHub is on an older Rails version,  I don't usually run into this :S

**Comment by blevine** [comment]
Would it be of any use for me to run the constant-loading-issue project you created or do you believe that would be a waste of time?

**Comment by rmosolgo** [comment]
Yeah, that was for a _different_ constant loading issue which I fixed on Rails :'(

**Comment by cdhagmann** [comment]
I'm having the same issue that @blevine described though I am not as good as finding typos. Any updates or workarounds for this issue?

**Comment by rmosolgo** [comment]
The long play fix here is finally released: in 1.10, when you use the Interpreter runtime, _all_ the GraphQL "booting" is done at load time. This means that any typos will result in errors at load time, not during the the first query. 

If you get a chance to try that new version, and you still have trouble with this, please open a new issue!
