### ISSUE TITLE
type must return GraphQL::BaseType, not Array

### ISSUE THREAD

**Issue by gastonmorixe** [rmosolgo/graphql-ruby#1479]
```
Field Query.channel's return type is invalid: field "typingParticipants" type must return GraphQL::BaseType, not Array ([Person])
```

I solved it by using `types[Types::PersonType]` but the documentation states otherwise:

```
# A field returning a list type:
# Equivalent to `aliases: [String!]` above
field :aliases, [String], null: true

```
http://graphql-ruby.org/type_definitions/lists.html

**Comment by Willianvdv** [comment]
Hey @gastonmorixe, this depends on the implementation, right? In your case, the `typingParticipants` is returning `Person` objects rather than `String` objects. Maybe I'm missing something, can you help me understand what we need to change? Is there an error in the docs? Or is some reference implementation broken?

**Comment by rmosolgo** [comment]
I think that doc (and the non-null one) need the `class_based: true` frontmatter, then they will have the appropriate banner: 

![image](https://user-images.githubusercontent.com/2231765/40125024-d80b968c-58f7-11e8-8d27-a17ed6f32a13.png)

**Comment by guyzmo** [comment]
I'm also getting that issue when I try to use an Array. I'm using v1.8.0, and if I read the documentation correctly I should be doing:

```ruby
Types::MyThingType = GraphQL::ObjectType.define do
  # […]
  field :options, [Types::OptionType, null: false]
end
```

And I'm getting the following error:

```
GraphQL::Schema::InvalidTypeError at /graphql
=============================================

> Field Query.my_thing's return type is invalid: field "options" type must return GraphQL::BaseType, not Array ([Option, {:null=>false}])

```

But instead, the following works:

```ruby
Types::MyThingType = GraphQL::ObjectType.define do
  # […]
  field :options, types[Types::OptionType]
end
```

I might have missed something reading the documentation…

**Comment by thefliik** [comment]
I think the `field :options, [Types::OptionType, null: false]` format is only suppose to be used with the new, class based API. Here you are using it with the old `.define` API.
