### ISSUE TITLE
Ruby version

### ISSUE THREAD

**Issue by wy16119** [rmosolgo/graphql-ruby#148]
Got the following error because our rails app uses ruby 1.9.3. It's really hard for us to migrate to a higher ruby version. I wonder if we can get around this or maybe using a previous release of `graphql-ruby`?
`graphql requires Ruby version >= 2.1.0.`

**Comment by rmosolgo** [comment]
Sorry, this gem makes heavy use of required keyword arguments, which were introduced in Ruby 2.1! 

As far as I know, that's the only hard requirement for that recent Ruby version. (Hmm, maybe `Hash#key?` must be switched for `Hash#has_key?`, something like that?) 

I'm not interested in supporting Ruby versions which have been EOLed, but if you fork the projects and revert the syntax, I'm willing to pitch on any other issues! For example, if you got a branch that ran the tests on 1.9.3 on Travis, maybe I could review the failures to see how other issues should be resolved.

**Comment by wy16119** [comment]
👍  Makes sense. Ima fork it and revert the syntax. Do you know if someone else tried to do this?

**Comment by brandonblack** [comment]
@wy16119 Ruby 2.0.0 actually supports keyword arguments and is fully backward compatible with Ruby 1.9.3 (which was [end-of-lifed over a year ago](https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/)). 

You should consider making the jump to at least 2.0.0 which should still be compatible with all your 1.9.3 code and won't involve re-writing literally every method and interface in this gem to get it working.

**Comment by astorije** [comment]
Hi @wy16119,

I will be trying to add support for GraphQL in a massive project that still requires Ruby 1.9.3 tomorrow, as part of a 24h-hackathon (but secretly my first step as convincing the company to switch to GraphQL 😋).

Have you had any luck porting this to Ruby 1.9.3 or finding an alternative? I'm obviously not looking for anything production-ready per the nature of the exercise, so any input is appreciated :-)

**Comment by rmosolgo** [comment]
If it's true that keyword args are the main problem, you could try rewriting the code a la [transpec](https://github.com/yujinakayama/transpec) (which uses [astrolabe](https://github.com/yujinakayama/astrolabe)), I also saw this one, [synvert](https://github.com/xinminlabs/synvert), but ... I've never tried either one 😬

**Comment by astorije** [comment]
Unfortunately, the keyword args are not the only issue: 

```
Gem::InstallError: json requires Ruby version ~> 2.0.
Gem::InstallError: public_suffix requires Ruby version >= 2.0.
```

I guess I'm going to track down gem versions that work with 1.9.3 but that's not a too great start 😅.
