### ISSUE TITLE
Subscriptions GlobalID::Locator.locate Mongoid::Errors::DocumentNotFound 

### ISSUE THREAD

**Issue by gastonmorixe** [rmosolgo/graphql-ruby#1482]
When using subscriptions with mongo (mongoid) having a `embeds_many`/ `embedded_in` association, the embedded model can't be located by using `Model.find(id)`

Is there any way we can pass the object (serialized ?) somehow and prevent locating it?

Example: `msg` object is `embedded_in` a `channel`  and does not work. 
```
      Schema.subscriptions.trigger 'on_new_message', {
        channelID: msg.channel.token
      }, msg, scope: participant
```

Workaround: move to `has_many` `belongs_to`

**Comment by rmosolgo** [comment]
ActionCableSubscription accepts a `serializer:` option which allows you to customize this behavior: 

https://www.rubydoc.info/gems/graphql/1.7.14/GraphQL%2FSubscriptions%2FActionCableSubscriptions:initialize

You can have a look at the built-in `Subscriptions::Serialize` module, and perhaps use that in your custom serializer! Please reopen this if you give it a try and it doesn't work out or you run into an issue.
