### ISSUE TITLE
1.8 Cannot declare not null on fields in root_query

### ISSUE THREAD

**Issue by mohamadbitar** [rmosolgo/graphql-ruby#1483]
example in `root_query.rb`
```ruby
 field :person, null: false, function: Functions::Generic::FindRecord.new(
    model_class: ::Person, type: Types::Person
  )
```

GraphiQL, when I check the documentation of `person`, does not reflect the not-null option

**Comment by mohamadbitar** [comment]
Also inside the `Fuctions` scope, defined types (i.e. Types::Enums::Gender) cannot be declared as non-nullable. Using either `required` or `!` would throw an error

```bash
Failure/Error: type = GraphqlSchema.resolve_type(nil, object, {})
      
GraphQL::Schema::InvalidTypeError:
Query is invalid: field "PersonSearch" argument "gender" type must be a valid input type (Scalar or InputObject), not FalseClass (false)
```

**Comment by rmosolgo** [comment]
Sorry, the new API ignores other options when `field:`, `function:` or `mutation:` is provided. There's a [little bit of warning](https://github.com/rmosolgo/graphql-ruby/blob/c88c79fa3a6b55c39b58a944e15915f89dda8a88/lib/graphql/schema/field.rb#L56-L58) about this, but obviously not enough! 

Let's keep this issue open until more warning is added. 

In the meantime, you can work around it by passing a non-null type to your `type:` option, for example: 

```ruby 
 field :person, null: false, function: Functions::Generic::FindRecord.new(
    model_class: ::Person, type: Types::Person.to_non_null_type 
                                               # ^^^^
  )
```
```

**Comment by andreamazz** [comment]
@rmosolgo thanks, the `to_non_null_type` workaround works. I wanted to add that the same issue happens in the `argument` call inside a function, for example:

```ruby
class Resolvers::Users::Create < GraphQL::Function
  description 'Creates a new user'

  argument :email, !types.String
  argument :password, !types.String
  argument :role, Types::RoleEnum.to_non_null_type

   # ...

end
```

Using `!Types::RoleEnum` would throw this:
`type must be a valid input type (Scalar or InputObject), not FalseClass (false)`

**Comment by rmosolgo** [comment]
See `Schema::Resolver` as a replacement for `Function` that supports the new API: http://graphql-ruby.org/type_definitions/resolvers.html
