### ISSUE TITLE
Get Query/Mutation Name from GraphQL::Query instance

### ISSUE THREAD

**Issue by drewmbrien** [rmosolgo/graphql-ruby#1486]
Hello! First off, I'd just like to say great work on this gem - I've really enjoyed working with it.

I'm attempting to write a custom tracer for Datadog by extending `GraphQL::Tracing::PlatformTracing` and I have a question: is it possible to get the name of the query/mutation from the `data` hash that's passed into `platform_trace`? I'm looking to get the name of the query/mutation itself - not the consumer-defined `operation_name`.

`data[:query]` has an instance of `GraphQL::Query` which contains a bunch of great info about the request coming in.  However, I can't seem to find a way to pull the name of the query/mutation out of it.

I'm trying to get this name and set it as the `resource` on the datadog span.  The provided Datadog tracer is great, but it really only sets the resource as `graphql.execute`, and so all the queries/mutations get aggregated together in Datadog. We'd like each of our queries/mutations to show up independently, and using the query/mutation name seems to be the easiest way to accomplish this.

Any thoughts on the matter would be super helpful! Thanks!

**Comment by rmosolgo** [comment]
Hi! Great question. Yes, it's possible, see for example how the built-in datadog instrumentation does it: 

https://github.com/rmosolgo/graphql-ruby/blob/9ace3bf661a090f320b18fa367a0205a61292522/lib/graphql/tracing/data_dog_tracing.rb#L27


Using `Query#selected_operation_name`. Like you said, it's not the _client-supplied_ value, but rather, the name of the operation which will be executed, because of _either_ a client-supplied name or the default (running the only present operation). 

Feel free to reopen this if it doesn't work out for you!

**Comment by drewmbrien** [comment]
Thanks for such a quick response!

When I POST the query string:
```
query {
  countries {
    countryCode
    name
  }
}
```

`data[:query].selected_operation_name` returns `nil`

However, if I provide this query string:

```
query foobar {
  countries {
    countryCode
    name
  }
}
```

`data[:query].selected_operation_name` returns `foobar`

It seems `selected_operation_name` returns the consumer-provided name (as opposed to `countries`).  Is this expected?

**Comment by drewmbrien** [comment]
We're currently running `graphql (1.7.14)` if thats helpful at all.

**Comment by drewmbrien** [comment]
Perfect! Thats exactly what I'm looking for.  Those are important caveats to note - this gets me one step closer though. Thanks again! This issue can remain closed :)

**Comment by kaka-ruto** [comment]
@rmosolgo how can I get the same from within the GraphQL controller? I'd like to run a before_action check to require authentication, but if the ast_node is one we do not require login, it will skip. Trying something like this

```
  before_action :require_authentication!

  def require_authentication!
    return if current_user || unauthenticated_operations

    render json: {
      errors: [
        message: 'Hi, please login to continue :)'
      ]
    }
  end

  def unauthenticated_operations
    params['operationName'].in? %w[signupUser signinUser]
  end
```

**Comment by rmosolgo** [comment]
You _could_ do it in a controller by using `GraphQL::Query.new(...)` and checking `query.document` (the AST) to get the root field names. However, I recommend using an AST analyzer to inspect incoming queries: https://graphql-ruby.org/queries/ast_analysis.html

That gives you a uniform interface to incoming queries and you can reject invalid ones from there. If you give it a try and run into issues, please open an issue describing what you hope to accomplish, what code you tried, and what happened when you tried it.
