### ISSUE TITLE
Guide: Action Cable Implementation - Broken API docs link

### ISSUE THREAD

**Issue by abhaynikam** [rmosolgo/graphql-ruby#1487]
![screen recording 2018-05-09 at 10 58 am](https://user-images.githubusercontent.com/7736232/39797139-244161ce-5378-11e8-9b4c-429e76f82b03.gif)

https://www.rubydoc.info/gems/graphql/GraphQL/Subscriptions/ActionCableSubscriptions is the correct documentation link? 

I can raise a PR for fix.

**Comment by bgentry** [comment]
I think this is a dupe of #1477. All the doc links are broken because they're attempting to point at a prerelease gem version, and rubydoc.info doesn't seem to support those.

**Comment by abhaynikam** [comment]
@bgentry sorry my bad. I didn't check if there is an existing issue for this. 

Closing this issue.
