### ISSUE TITLE
How to run a single test case in file?

### ISSUE THREAD

**Issue by flyfy1** [rmosolgo/graphql-ruby#1490]
Context: I'm trying to write some test case to make Graphql#Subscription call executing resolvers to actually do the authorization check.

I know how to run tests from a single file: `rake test TEST=spec/graphql/execution/execute_spec.rb`; but I cannot figure out how to run test for, say, line number 139.

Any idea on how to run such kind of test on a particular line number? Thanks.

(Sorry if this question is very simple.. but I've been searching around for an hour but cannot find the answer. If anyone could point to me the related source for me to read, that would be very helpful)

**Comment by Willianvdv** [comment]
The gem is shipped with minitest-focus (https://github.com/seattlerb/minitest-focus), you can use `focus` to run one spec.

**Comment by flyfy1** [comment]
Update: just in case someone else bump into this question.. it's actually documented here: http://graphql-ruby.org/development.html#unit-tests
