### ISSUE TITLE
Guide: Introduction

### ISSUE THREAD

**Issue by kartik-gr** [rmosolgo/graphql-ruby#1493]
I keep getting linked to pages that come up "Oops, we couldn't find that page." For example: https://www.rubydoc.info/gems/graphql/1.8.0.pre11/GraphQL/InterfaceType. Is something wrong with the documentation?

**Comment by Willianvdv** [comment]
Sorry about that! rubydoc.info doesn't like the 1.8 pre-releases too much, I'm not sure why. Anyway, here's the correct URL to the page you're looking forhttps://www.rubydoc.info/gems/graphql/GraphQL/InterfaceType
