### ISSUE TITLE
[1.8] Filters broken by class-based schema upgrade

### ISSUE THREAD

**Issue by bgentry** [rmosolgo/graphql-ruby#1497]
I have the following filter:

```rb
class NoMutationMask
  def call(schema_member, _ctx)
    schema_member == ::Types::MutationType
  end
end
```

In the controller where I handle GraphQL requests, I use it to enforce that mutations are not run on non-`POST` requests:

```rb
def execute
  ::ActApiSchema.execute(params.fetch(:query), { except: filters })
end

def filters
  filters = []
  filters.unshift(NoMutationMask.new) unless request.method == "POST"
  filters
end
```

Using v1.7, that filter gets called with my actual mutation type, so it effectively blocks those requests:

```
From: /Users/bgentry/Code/api/app/controllers/v1/graph_controller.rb @ line 53 V1::GraphController::NoMutationMask#call:

    52: def call(schema_member, _ctx)
 => 53:   binding.pry
    54:   schema_member == ::Types::MutationType
    55: end

[1] pry(#<V1::GraphController::NoMutationMask>)> schema_member.class
=> GraphQL::ObjectType
[2] pry(#<V1::GraphController::NoMutationMask>)> schema_member
=> Mutation
[3] pry(#<V1::GraphController::NoMutationMask>)> schema_member == ::Types::MutationType
=> true
[4] pry(#<V1::GraphController::NoMutationMask>)> 
```

However, using v1.8.pre11 with a schema, query, and mutation converted to the class-based definitions, this filter no longer works. The schema member passed into the filter is still `GraphQL::ObjectType` rather than being the mutation class itself (which has kept the same name, `Types::MutationType`):

```
From: /Users/bgentry/Code/api/app/controllers/v1/graph_controller.rb @ line 53 V1::GraphController::NoMutationMask#call:

    52: def call(schema_member, _ctx)
 => 53:   schema_member == ::Types::MutationType
    54: end

[22] pry(#<V1::GraphController::NoMutationMask>)> schema_member
=> Mutation
[23] pry(#<V1::GraphController::NoMutationMask>)> schema_member.class
=> GraphQL::ObjectType
```

From what I've read about this transitional period (moving to class-based definitions), this is expected behavior. I wanted to post it here in case others have the same issue, and also in case you thought there might be similar cases broken by this transition or thought it needed better calling out in the migration docs.

Cheers :v:

**Comment by bgentry** [comment]
FWIW I was able to resolve my own issue using the `type_class` metadata field:

```rb
[1] pry(#<V1::GraphController::NoMutationMask>)> schema_member.metadata
=> {:type_class=>Types::MutationType, :access=>nil, :admin_only=>nil, :mutation=>true}
```

```rb
class NoMutationMask
  def call(schema_member, _ctx)
    type_class = schema_member.metadata[:type_class]
    type_class && type_class == ::Types::MutationType
  end
end
```

**Comment by rmosolgo** [comment]
:+1: Thanks for sharing your solution. Yes, that's the right approach, since legacy objects are used at runtime. Hoping to remove the legacy "shadow" objects in #2363
