### ISSUE TITLE
How about bumping to 2.0.0?

### ISSUE THREAD

**Issue by david50407** [rmosolgo/graphql-ruby#1501]
In Ruby gems' world, [Semantic Versioning 2.0.0](https://semver.org) is commonly used to declaring how much changes between versions.

Since we have many public API changes from 1.7.x to 1.8 (like class-based definition), IMO, how about bumping version to 2.0.0 instead of just 1.8?

**Comment by thefliik** [comment]
Adding a link to the versioning scheme to the top of the changelog would probably be helpful.

**Comment by david50407** [comment]
@bessey @thefliik thanks, I'm going to close this issue now

**Comment by mortik** [comment]
This is to bad... semantic versioning is there for a reason and i'm a little bit annoyed every time i see a patch release with breaking changes like 1.9.4 just now...

**Comment by david50407** [comment]
@mortik I think this is not the reason to "not using semver is bad", they give a good rule on versioning policy, but they still put the breaking changes inside the patch.

According to the answer of @thefllik, I thought there won't be any breaking changes between the patch versions, and the small breaking changes can be between the minor versions, am I wrong?

**Comment by mortik** [comment]
I dont really now if i understand you correctly - but currently i have no indication how easy it is to integrate a new release. I need to assume that every single version can introduce a breaking change which currently they do quite often... I actually don't care if you use semver or whatever but currently you could also create a new major version with every single release the only thing changing for everyone using graphql-ruby would be the version number nothing else...

**Comment by thefliik** [comment]
Well 
1. Personally, in general, I agree with @mortik, I would prefer it if projects used semver. This being said, [90% of the work is done by `@rmosolgo`](https://github.com/rmosolgo/graphql-ruby/graphs/contributors). If he wants to use something else, I'm totally fine with that.
2. > currently i have no indication how easy it is to integrate a new release.
    - Did you not read this thread? This repo doesn't follow semver, but it does have a clear version policy and also explains the reasoning behind the version policy.

**Comment by swalkinshaw** [comment]
> but currently i have no indication how easy it is to integrate a new release

Yes you do since there's a "Breaking changes" section in the changelog for every version.

> I need to assume that every single version can introduce a breaking change which currently they do quite often

In my opinion, this is probably a good thing. Doing some due diligence before blindly updating a gem is healthy. Simply trusting a package update since it's a minor/patch update is a bad habit in general and we see examples of this all the time.

Even if this (or any) package claimed to follow semver, there's still no guarantee they wouldn't accidentally introduce breaking changes. Detecting them is largely a manual process (especially in Ruby) and deciding what type of version bump to do is subjective.

**Comment by mortik** [comment]
Its a good thing to introduce breaking changes in a patch level release?  :) seriously? Can you give me one good reason why its not possible to create a major release when you introduce breaking changes?

**Comment by swalkinshaw** [comment]
I didn't exactly say that 😄I said it's a good practice to assume that any release *could* contain a breaking change regardless of what kind of versioning the package uses.

**Comment by mortik** [comment]
No its not :)

**Comment by etherbob** [comment]
I'd like to respectfully ask @rmosolgo: Please reconsider your stance on SemVer. Even "minor" breaking changes can have nock on effects that introduce real costs to a downstream project.

I had my GraphQL dep set to 'graphql', '~> 1.8' and was bitten by the change in 1.9 that removed implicitly defined field methods. It's a long story, but I ended up in a scenario where I was running bundle install without a lock file and this added on hours to an already complex refactor.

Please don't take this as angry. I'm grateful for this project and the time and effort it has saved me. I have also appreciated its gradual move towards adopting interfaces and norms that feel more familiar the avg ruby dev  and I think SemVer would be another great move in that direction.
