### ISSUE TITLE
[1.8] Connections with non-nullable edges and nodes in function

### ISSUE THREAD

**Issue by mull** [rmosolgo/graphql-ruby#1503]
To return a list of `[SomeType!]!` (i.e. both inner and outer non-null) in a function we can use this workaround:

```
class Functions::AttributeList < GraphQL::Function
  type Types::Attribute.to_non_null_type.to_list_type.to_non_null_type
end
```

But how could one achieve the same for connections? We can't say `Type.to_non_null_type.connection_type` as that yields `undefined method `connection_type' for #<GraphQL::Schema::NonNull:0x00007fb635a18f40>`

We also can't say `Type.connection_type.to_non_null_type` as it simply marks the connection itself as non-nullable but not the edge and its node.

**Comment by rmosolgo** [comment]
The best way to do this is to use class-based Relay types, so you can customize the nullability as you see fit: http://graphql-ruby.org/api-doc/1.8.6/GraphQL/Types/Relay
