### ISSUE TITLE
GraphQL Pro's authorization doesn't have a way to hide input arguments

### ISSUE THREAD

**Issue by phaedryx** [rmosolgo/graphql-ruby#1506]
suppose there is a UserType with two fields, name and email, and an input of `emailContains`. The purpose being to give admins the ability to do something like this: `{Users(emailContains: "gmail"){name email}}`. However, you don't want to give regular users access to email information.

As long as the `emailContains` isn't hidden, hiding the `email` field doesn't matter:
`{Users(emailContains: "gmail"){name}` (Doesn't contain "bob johnson)
`{Users(emailContains: "yahoo"){name}` (Does return "Bob Johnson")
`{Users(emailContains: "johnson"){name}` (Does return "Bob Johnson") (edited)
`{Users(emailContains: "bob"){name}` (Doesn't return "Bob Johnson")
etc.

Eventually you could figure out that the user's email address is "robert.johnson1980@yahoo.com" even though the `email` field of `UserType` is `view: :read` and restricted to only admins because there isn't a corresponding restriction for input arguments.

This is necessary to "Add comprehensive, granular authorization to your schema."

**Comment by rmosolgo** [comment]
Thanks for opening this issue! 

Since starting at GitHub, I've learned that the auth system here has the feature you described -- even arguments may be hidden on a query-by-query basis. 

Rather than extend the graphql-pro auth system, I'm going to rework it a bit and include it in graphql-ruby, with this feature. You can follow the work at: #1494

**Comment by rmosolgo** [comment]
The new CanCan integration has support for hiding arguments, and it's built on the new authorization system linked above: http://graphql-ruby.org/authorization/can_can_integration#authorizing-arguments

So, I recommend migrating to that one. I'm happy to help out on any bumps along the way!
