### ISSUE TITLE
Inheriting arguments in fields

### ISSUE THREAD

**Issue by Croge32** [rmosolgo/graphql-ruby#1513]
I'm working on some very simple pagination in a project that just utilizes `page` and `limit` arguments passed in through the client, like so:

```
query {
  index_officers(page:1, limit:2) {
    name
  }
}
```

And I have implemented it like so:

In `OfficerType` ObjectType:
```
...
field :index_officers do
    type types[Types::OfficerType]
    argument :page, types.Int, default_value: 1
    argument :limit, types.Int, default_value: Resolvers::BaseResolver.pagination_limit
    description "Index Officers in db"
    
    resolve Resolvers::OfficerResolvers::IndexOfficers.new
  end
...
```

In `IndexOfficers` Resolver:
```
class IndexOfficers < BaseResolver
      def call(_, args, ctx)
        super
        
        offset = (args["page"] - 1) * args["limit"]
        ::Officer.offset(offset).limit(args["limit"])
      end
    end
```

And in my `BaseResolver`:
```
module Resolvers
  class BaseResolver
    def call(_, args, context)
      if context[:current_officer].blank?
        raise GraphQL::ExecutionError.new("Authentication required")
      end
    end

    def self.pagination_limit
      25
    end
  end
end
```

Similarly to how I have IndexOfficers set up to inherit from BaseResolver in order to authenticate all of the queries in the app, is there a way I can generalize some sort of `Field` type in order to generalize pagination for any fields I'd want to paginate? Can this be achieved with a `Function` in some way? Or maybe is there a way I can implement this entirely differently in a more generalized way? We aren't currently looking to utilize Relay, instead opting for Apollo, but maybe this is something we'd need to use Relay for to utilize `connections`? Thanks for any information!

**Comment by rmosolgo** [comment]
In 1.8+, [Schema::Resolver](http://graphql-ruby.org/type_definitions/resolvers.html) supports inheritance this way, perhaps it would work. Also, I want to support pagination this way through #1411 , but I haven't quite finished it up yet. 

Regarding connections, yes, i'd recommend using them even if you aren't using Relay. The structure they provide (with connection/edges/nodes) gives  you lots of room to grow as you need to add fields!
