### ISSUE TITLE
Could not found auto-upgrader rake task after upgrade to 1.8.0

### ISSUE THREAD

**Issue by zw963** [rmosolgo/graphql-ruby#1517]
After upgrade graphql-ruby to 1.8.0, and add `parser` into Gemfile.

But, not found any rake task.

Following is my application.rb

```rb
# require "active_model/railtie"
require "active_job/railtie"
require "action_controller/railtie"
# require "action_mailer/railtie"
# require "action_view/railtie"
require "action_cable/engine"
require "rails/test_unit/railtie"
require "sequel"
```

**Comment by zw963** [comment]
add `require "graphql/railtie"` into application.rb, not worked

**Comment by zw963** [comment]
Hi, i think rake task is exist ... but not `desc '.....'` is declare, so i could not found it ...

**Comment by rmosolgo** [comment]
Oops, I guess we should add `desc '...'` to the task!
