### ISSUE TITLE
Separate MongoDB support from the core

### ISSUE THREAD

**Issue by gfx** [rmosolgo/graphql-ruby#1522]
From #1452 on, graphql-ruby requires mongodb to run tests, but I'm not interested in MongoDB.

Can you consider to separate MongoDB support from the core? I think [kaminari](https://github.com/kaminari) is a good example.

**Comment by rmosolgo** [comment]
I would like to keep Mongoid support in this project, but what about making the tests conditional on discovery of MongoDB? Then, we could test it on CI, but not require it for local development.

**Comment by gfx** [comment]
Sounds good if MongoDB tests become optional 👍
