### ISSUE TITLE
Subscription type in 1.8

### ISSUE THREAD

**Issue by joshforbes** [rmosolgo/graphql-ruby#1523]
When I try to define a subscription type in 1.8 I get an error. Here is my type:

![image](https://user-images.githubusercontent.com/3682518/40316425-52397dd2-5cec-11e8-9d2e-fe532f007184.png)

Here is the error:

![image](https://user-images.githubusercontent.com/3682518/40316432-5a1f1ac0-5cec-11e8-88b3-d5013bd0063e.png)

It does seem likes its defined in the Schema::Field class though.. so maybe I am just doing something wrong?

**Comment by rmosolgo** [comment]
Pass it as a keyword instead, `subscription_scope: :current_user_id`. If that works ok, we can add a method for it. (not all keywords are available as configuration methods ... yet ...?)

**Comment by joshforbes** [comment]
Ah, thanks! That seems to work.  It was bit confusing because of:

![image](https://user-images.githubusercontent.com/3682518/40338736-d9bd2d96-5d44-11e8-830f-b579c93863d0.png)

But I realize now that probably hasn't been updated.

**Comment by rmosolgo** [comment]
That doc was updated in #1559 so at least it's accurate now!
