### ISSUE TITLE
[1.8] TypeType declarations necessary due to autoloading class behavior

### ISSUE THREAD

**Issue by frank-west-iii** [rmosolgo/graphql-ruby#1524]
Having a type declared with the suffix type strips off the last `Type` suffix from the class definition.

For example:

```
module Types
  class SupplierItem < GraphQL::Schema::Object
  end
end

module Types
  class SupplierItemType < GraphQL::Schema::Object
  end
end
```

This results in an error:

```
 "error": "Duplicate type definition found for name 'SupplierItem' (Types::SupplierItem, Types::SupplierItemType})"
```

In order to get around this we have to declare our `SupplierItemType` as `SupplierItemTypeType` which just doesn't feel right.

Is there a way to turn this off or somehow solve this in another fashion.

It was mentioned here in Slack, but not much conversation around it.

https://graphql.slack.com/archives/C07MVL1AB/p1524155628000310

**Comment by rmosolgo** [comment]
This happens in the `self.graphql_name` method: 

https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/member/base_dsl_methods.rb#L26

You can either: 

- override that method in your base class without that logic; or 
- explicitly set `graphql_type "SupplierItemType"` in your type definition, to override that behavior 

I'm happy to change the default behavior too if more people run into this issue, just leave a comment here. Please reopen if those don't work for you!

**Comment by frank-west-iii** [comment]
Other than changing `graphql_type "SupplierItemType"` to `graphql_name "SupplierItemType"` worked like a charm.

**Comment by rmosolgo** [comment]
oops, typo, fixed above!

**Comment by kammerer** [comment]
I just ran into the same issue. It was surprising because this behavior is not documented (or I just couldn't find). The solution with using `graphql_name` works just fine, perhaps it could be added to the docs?
