### ISSUE TITLE
Guide: Connections

### ISSUE THREAD

**Issue by carlos-gomez-tx** [rmosolgo/graphql-ruby#1536]
Hello guys, 
the example for custom connections does not work.

This part specifically:
http://graphql-ruby.org/relay/connections.html
Section: Creating connection fields by hand

The code 
```
connection_field = GraphQL::Relay::ConnectionField.create(field)
```
The error says that GraphQL::Relay::ConnectionFlied does not exist.

Seems that the docs is not accurate on this, and we ca not create a connection field that way. 
Is there an alternative for doing that? do we need to update the docs?

regards, 
Carlos

**Comment by rmosolgo** [comment]
Hi, sorry, it seems like something old was left over in the docs!

**Comment by rmosolgo** [comment]
Thanks for pointing it out, removed in 6682dc814!
