### ISSUE TITLE
Can't dynamically build interfaces

### ISSUE THREAD

**Issue by gleopoldo** [rmosolgo/graphql-ruby#1537]
Hello! I'm having a problem defining a interface inside my schema. I'm trying to build a dynamic response over a email message recipients (that includes already mapped active record objects and their respective graphql types). My implementation is as follows:

```
Types::MessageType = GraphQL::ObjectType.define do
  name 'Message'
  # some other fields

  field :recipients, -> { types[Interfaces::Recipient] } do
    resolve -> (obj, args, ctx) do
      if obj.contacts?
        []
      elsif obj.lists?
        obj.lists
      elsif obj.segmentations?
        obj.segmentations
      elsif obj.msg_filter?
        #[]
        obj.msg_filter.split('').map { |filter| { name: filter } }
      else
        []
      end
    end
  end
```

```
Interfaces::Recipient = GraphQL::InterfaceType.define do
  name 'Recipient'
  description 'Represents an abstraction of the messages contacts'

  field :name, !types.String

  possible_types [ -> { Types::List }]

  resolve_type -> (obj, _ctx) {
    if (obj.is_a? List)
      Types::ListType
    elsif (obj.is_a? Segmentation)
      Types::SegmentationType
    else
      Types::MsgFilterType
    end
  }
end
```

Each of the listed types has a similar format to this one:
```
Types::ListType = GraphQL::ObjectType.define do
  name 'List'
  description 'An instance of a List'
  interfaces [Interfaces::Recipient]

  field :name, !types.String
end
```

However, when running the following query:

```
{
  allMessages {
    messages {
      recipients {
        name
        __typename
      }
    }
  }
}
```

I get this error:

```
GraphQL::UnresolvedTypeError (The value from "recipients" on "Message" could not be resolved to "[Recipient]". (Received: `List`, Expected: []) Make sure you have defined a `resolve_type` proc on your schema and that value `#<List id: 1, name: "Planet of the Bloody Thief", description: nil, approved_contacts_count: 0, contact_imports_count: 0, deleted_at: nil, account_id: 31, created_at: "2018-05-24 13:48:13", updated_at: "2018-05-24 13:48:13", reputation: "waiting">` gets resolved to a valid type. You may need to add your type to `orphan_types` if it implements an interface but isn't a return type of any other field.):
  app/controllers/graphql_controller.rb:14:in `execute'
```

I was searching inside the gem's source code, and I think that it might be related to [this line of code](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/query/serial_execution/value_resolution.rb#L65), since it is treating an interface type the same as an union type. I've also tried to declare a `possible_types` into my interface type, but I get a not defined error. I've also searched in the docs and there's no reference to `possible_types` usage inside interfaces. Can you guys help? 

Thanks in advance!

**Comment by rmosolgo** [comment]
Hi, sorry for the late reply. Did you try this suggestion from the error message?

> add your type to `orphan_types`

You can read more about orphan types here: http://graphql-ruby.org/search?query=orphan%20types

I think if you add `List` to orphan_types, it will work. Feel free to reopen this if it doesn't!

(By the way, you might consider renaming it from `List` to something more specific, since GraphQL has a native concept of "list types"!)

**Comment by gleopoldo** [comment]
Nice!!! I'll try this one. Any updates I'll reopen this issue. Tks!
