### ISSUE TITLE
How to describe complex types which are not active records object?

### ISSUE THREAD

**Issue by shir** [rmosolgo/graphql-ruby#1539]
I have a pretty complex type which represents money value:
```
      {
        fractional: amount.fractional.to_s,
        currency:   {
          isoCode:       amount.currency.iso_code,
          name:          amount.currency.name,
          symbol:        amount.currency.symbol,
          subunitToUnit: amount.currency.subunit_to_unit,
          htmlEntity:    amount.currency.html_entity,
        }
      }
```

But it's not model object. It's just some type. I've tried to describe it like using `GraphQL::Schema::Object` but I got error `Objects must have selections (field 'amount' returns Money but has no selections)`. I guess it's because this object doesn't have any `id` field (error is not clear here). Now I use `GraphQL::Schema::Scalar` and just return hash with values. It works, but there is no info structure of field in schema and I can't query only required fields.

**Comment by Willianvdv** [comment]
Hey @shir, this looks like an error in your query! I guess you do something like:
```
product {
   amount
}
```

But it expects selections on that amount, something like:
```
product {
   amount {
      currency { name } 
   }
}
```

Does that work?

**Comment by shir** [comment]
@Willianvdv damn, you are right! From this perspective error was pretty clear, but my mind went wrong way. Thanks!
