### ISSUE TITLE
Making clientMutationId optional

### ISSUE THREAD

**Issue by keithpitt** [rmosolgo/graphql-ruby#154]
Howdy! This is probably a silly question, but is there a way to mark the `clientMutationId` field for mutations optional? Most other frameworks / implementations seem to have it optional by default. I tried looking in the `graphql-ruby` source for a mention of it, but I couldn't find anything!

**Comment by keithpitt** [comment]
Oh! I just found it in `graphql-relay`. Should I close this issue here and move it over there perhaps?

**Comment by rmosolgo** [comment]
yes, that's the place for it, sorry for the run-around!

**Comment by keithpitt** [comment]
No problems at all!
