### ISSUE TITLE
1.8 field definition not compatible with Hashr.

### ISSUE THREAD

**Issue by zw963** [rmosolgo/graphql-ruby#1545]
Following is a example:

```rb
# Following code now work, role return nil.
class GuardianType < Types::BaseObject
  field :role, String, null: true
end
```

```rb
# Following code is worked!
class GuardianType < Types::BaseObject
  field :role, String, null: true

  def role
    @object.role
  end
end
```
Following is field definition:

```rb
GuardiansField = GraphQL::Field.define do
    resolve ->(o, args, c) 
    guardians = [
      {role: '爸爸'},
      {role: '妈妈'},
      {role: '爷爷'},
      {role: '奶奶'},
      {role: '外公'},
      {role: '外婆'}
    ]
   # Hashr.new convert hash to a invokable form.
   guardians.map {|guardian| Hashr.new(guardian) }
end

### expect behavior

 eliminate role method definition, it should work out of box.

**Comment by rmosolgo** [comment]
I'm surprised it doesn't _just work_ ! 

My first suggestion is to try removing `Hashr`. In 1.8+, GraphQL will lookup hash keys by default, so you might not need Hashr. 

Second, we can try to figure out what's wrong in this bit of code, which chooses what method to call: 

https://github.com/rmosolgo/graphql-ruby/blob/e3d429a8f2fe28737078d015659ae1350c45b71c/lib/graphql/schema/field.rb#L304-L329

In particular, I expect _this_ condition to be `true` for your case above:

**Comment by zw963** [comment]
> My first suggestion is to try removing Hashr. In 1.8+, GraphQL will lookup hash keys by default, so you might not need Hashr.

This `GuardianType` backed by three model, one model have `role` method, and another exist `role` column, and third is a hash, in this case, should i just keep  `field :role, String, null: true`, it will work?

**Comment by rmosolgo** [comment]
I _think_ it will work, the best way to be sure is to try :)

**Comment by zw963** [comment]
Hi,  first solution is worked, if only leave a hash, it will work as expect.

And, after debug,  second solution still not work, following is breaking point in line 314:

```rb
(pry):0>
(pry):0> p obj.object
<Hashr {:role=>"爸爸", :role1=>"爸爸"}>

(pry):0> obj.object.role1
"爸爸"
(pry):0> @method_sym
:role1
(pry):0> obj.object.send(@method_sym)
nil
(pry):0>
```

**Comment by zw963** [comment]
```sh
 ╰─ $ bundle list |grep 'hashr\|graph'
  * graphql (1.8.0)
  * graphql-batch (0.3.9)
  * graphql-client (0.12.3)
  * hashr (2.0.1)
```

**Comment by zw963** [comment]
Following two form is work:

```rb
 eval "obj.object.#{@method_sym}"
```
Or

```rb
obj.object.__send__(@method_sym)
```

Because Hashr object is a subclass of BasicObject, no `send` or `public_send` method 
is defined.

**Comment by rmosolgo** [comment]
It sounds like this works by _removing_ Hashr, which is no longer necessary in 1.8. If you have specific improvements to suggest in graphql-ruby, feel free to open another issue or PR!
