### ISSUE TITLE
Graphql extensions

### ISSUE THREAD

**Issue by sebglazebrook** [rmosolgo/graphql-ruby#1546]
Hi,

Wanted to ask if there is a supported way for returning graphql extension data using this library.

Basically the use case I have is that each resolver potentially wanted to append something to the extension data returned to the client.

I've had a look through the code and checked for other issues but haven't found anything on this topic.

Thanks,

Seb

**Comment by rmosolgo** [comment]
There's no special handling of `"extensions"`, but here's a suggesetion for implementing it yourself: 

1. While your query runs, put data in the `context` object, for example: 

  ```ruby 
  context[:my_extension] || = {} 
  context[:my_extension][:something] = 1234 
  ```

2. Then, after getting the query result, read the value from context, and put it back in the result hash: 

  ```ruby 
  result = MySchema.execute(...) 
  ext_value = result.context[:my_extension]
  hash_result = result.to_h 
  hash_result["extensions"] = { "my_extension" => ext_value } 
  render json: hash_result 
  ```

Then the JSON response will have your extra data in it! Thanks for asking and I hope that helps, feel free to reopen if not.

**Comment by sebglazebrook** [comment]
Awesome thanks!
