### ISSUE TITLE
Special namespace fields

### ISSUE THREAD

**Issue by christophweegen** [rmosolgo/graphql-ruby#1556]
Hey there! 

I have the following problem:

I want to order fields under special namespaces, so that i can write queries/mutation like this ( ignore for now that queries and mutations are present under one query) :
```
{
  categories {
    show
    create
    update
    destroy
  }
}
```
instead of 
```
{ 
  show_category
  create_category
  update_category
  destroy_category
}
```
The idea behind this is to have a namespaced schema and avoid duplication on field names ( in this case four times repeating "category").

This makes it easier for finding the right queries for example in GraphiQL, if you just have the resources as entry objects ( similar to standard RESTful routes in rails like /users, user/:id etc. ) and can dig your way from there deeper into the schema, instead of having all actions under the global namespace.

Right now i solved it like this: 

Besides making a Types::CategoryType i made a Types::CategoriesType to provide a field in my QueryType under that i can sort all of the different CategoryType actions.

```ruby
class Types::QueryType < Types::BaseObject
  field :categories, Types::CategoriesType, null: false
end
```

Now comes the problem:

In order to make the `:categories` field work, i have to provide an object other than `nil` as a resolver for this field, though this object isn't needed at all for resolving all the fields that come under it. ( In case you define custom methods on the type instead relying on methods defined on the underlying object )

```ruby
class Types::QueryType < Types::BaseObject
  field :categories, Types::CategoriesType, null: false
  
  def categories
    # arbitrary object that can respond to needed methods or empty object if methods get overridden later
  end
end
```

In this case there's actually no intermediate `Categories` object needed. The whole purpose of `:categories` is to provide a namespace in your schema for all fields that fall under it. But in order to make it work it needs an object in Types::QueryType, even if that object possibly doesn't fulfill any purpose regarding resolving. This feels a bit odd and hacky.

So if there's no other way i propose something similar to `field` but called something like `namespace` which acts as some kind of field but with the sole purpose to define other fields on it and doesn't need an object to make it work properly.  

What do you think of that approach?

Thanks for your replies. :-)

**Comment by Willianvdv** [comment]
@christophweegen we return such namespaced objects to create namespaces in our schema, we call them virtual objects and initialize them with the current user so they can behave just like any other object. 

Unfortunately, this doesn't work for mutations as the spec doesn't allow you to nest them. 

Does this help?

**Comment by Willianvdv** [comment]
Yeah, so if we have:
```
query {
   me {
      collections {
         books { title }
         cats { brands }
      }
   }
}
```

The collections' object returned by the UserType (me) is something like:
```lang=ruby
class Collections
  def initialize(user):
     @user = user
  end

   def cats
      @user.cats_i_like
    end

   def books
      @user.books_i_have
   end
end
```

**Comment by christophweegen** [comment]
Ah thanks.. that leaves it crystal clear :-)
