### ISSUE TITLE
Upgrading to 1.8.2 breaks subscriptions

### ISSUE THREAD

**Issue by joshforbes** [rmosolgo/graphql-ruby#1567]
I just updated from 1.8.0 to 1.8.2 and now my subscriptions are not working

```
GraphqlChannel#execute({"query"=>"subscription MessageReceived($conversationId: ID) {\n  messageReceived(conversationId: $conversationId) {\n    id\n    body\n    status\n    createdAt\n    conversation {\n      id\n      contact {\n        id\n        firstName\n        lastName\n        phoneNumber\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n", "variables"=>{"conversationId"=>62}, "operationName"=>"MessageReceived"})
E, [2018-06-08T17:35:23.428878 #11261] ERROR -- : Could not execute command from ({"command"=>"message", "identifier"=>"{\"channel\":\"GraphqlChannel\",\"channelId\":\"163e077df69\"}", "data"=>"{\"query\":\"subscription MessageReceived($conversationId: ID) {\\n  messageReceived(conversationId: $conversationId) {\\n    id\\n    body\\n    status\\n    createdAt\\n    conversation {\\n      id\\n      contact {\\n        id\\n        firstName\\n        lastName\\n        phoneNumber\\n        __typename\\n      }\\n      __typename\\n    }\\n    __typename\\n  }\\n}\\n\",\"variables\":{\"conversationId\":62},\"operationName\":\"MessageReceived\",\"action\":\"execute\"}"}) [RuntimeError -         Failed to implement Subscription.messageReceived, tried:

        - `SubscriptionType#message_received`, which did not exist
        - `NilClass#message_received`, which did not exist
        - Looking up hash key `:message_received` or `"message_received"` on ``, but it wasn't a Hash

        To implement this field, define one of the methods above (and check for typos)
```

My subscription type looked like this:

![screen shot 2018-06-08 at 2 00 17 pm](https://user-images.githubusercontent.com/3682518/41173314-6d2929c6-6b24-11e8-9941-c87ca3c3f214.png)

Turns out that if I define empty methods for `message_received` and `message_status_changed` it will work again.

**Comment by rmosolgo** [comment]
Thanks for reporting the bug and sharing the work-around! I guess the next step is to reproduce in the tests and figure out _why_ 🤔

**Comment by ferland182** [comment]
@joshforbes this may help you https://graphql-ruby.org/subscriptions/subscription_type#authorizing-subscriptions

**Comment by rmosolgo** [comment]
Yes, a lot of new work has gone into subscriptions (https://graphql-ruby.org/guides#subscriptions-guides), especially with the interpreter runtime. I don't think that empty method is required anymore.

> Did you find a solution 

The solution was shared in the initial post: 

> Turns out that if I define empty methods for `message_received` and `message_status_changed` it will work again.
