### ISSUE TITLE
[1.8] TypeError (superclass must be a Class (Module given))

### ISSUE THREAD

**Issue by everdrone** [rmosolgo/graphql-ruby#1576]
> user_type.rb
```ruby
class Types::UserType < Types::BaseObject
  implements GraphQL::Relay::Node.interface, Types::OwnerType
  # ...
end
```

> owner_type.rb
```ruby
class Types::OwnerType < Types::BaseInterface
  field :login, String, null: false
  # ...
end
```

I suppose the error is referring to the generated `base_interface.rb` ?
```ruby
module Types::BaseInterface
  include GraphQL::Schema::Interface
end
```

`TypeError (superclass must be a Class (Module given))`

**Comment by rmosolgo** [comment]
Check out the stack trace on the error message, which line of code is it pointing to? 

Then compare your `Types::OwnerType` to the interface examples here: 

http://graphql-ruby.org/type_definitions/interfaces.html#defining-interface-types

Your interfaces should be Ruby `module`s, for example: 

```ruby 
module Types::OwnerType 
  include Types::BaseInterface 
  # ... 
end 
```

Feel free to reopen if that doesn't help sort out the issue!
