### ISSUE TITLE
Broken link on graphql-ruby.org

### ISSUE THREAD

**Issue by reentim** [rmosolgo/graphql-ruby#1578]
Sorry for posting this in the wrong place, but http://graphql-ruby.org/types/introduction is currently a 404.

**Comment by gjtorikian** [comment]
@rmosolgo You should be using https://github.com/gjtorikian/html-proofer 🤓

**Comment by rmosolgo** [comment]
It used to be configured, but I didn't know how to make it handle relative links. So in development, when I added a new page, but it hadn't been published yet, it would 💥 !

**Comment by daemonsy** [comment]
Hi, I'm helping to close old issues. I can't find any link that leads to `types/introduction`, guessing it's resolved. Feel free to reopen otherwise :) 

`html-proofer` looks like something I need on internal doc sites :smile:
