### ISSUE TITLE
Dynamically define a subset of the schema

### ISSUE THREAD

**Issue by nuclearspike** [rmosolgo/graphql-ruby#158]
Problem:
One of my fields of my rails model is a serialized hash that comes in and goes out as JSON. Currently, with a REST interface, this is pretty easy to do. But, I'd like to move this to graphql and _not_ just have the field pass through GraphQL as a string.

Idea for Solution:
I have a json-schema that I use for this field and I would use that schema to dynamically generate the graphql definition. That json schema is then used by field validators as well as passed to the client to generate forms from and it is the "source" that everything else derives from so it makes sense to dynamically generate the graphql definition from it.

Question:
I don't know what that code would look like. Maybe someone reading this has a better solution than what direction I'm heading or can help. Is there a way to do this without code generation?

**Comment by rmosolgo** [comment]
Hi, sorry I missed this issue before! 

If you're talking about defining some types at "load time", then using them in the schema, then yes, this is possible! For example, graphql-relay defines types programmatically. For example, this method defines a connection type: https://github.com/rmosolgo/graphql-relay-ruby/blob/master/lib/graphql/relay/base_connection.rb#L22

If you mean that the definition would _change_ at runtime, then that probably won't work. GraphQL is built on an assumption that getting the schema _once_ is sufficient for (nearly) all-time.

**Comment by rmosolgo** [comment]
Some of the recent Rails-oriented graphql gems also have examples of generating types based on other objects (eg https://github.com/goco-inc/graphql-activerecord) I hope those help!

**Comment by nuclearspike** [comment]
Thanks!
