### ISSUE TITLE
Can the arguments hash be preset?

### ISSUE THREAD

**Issue by gjtorikian** [rmosolgo/graphql-ruby#1586]
Suppose you have a field like this:

``` ruby
field :check_suites, Connections.define(CheckSuite), visibility: :under_development, description: "The check suites associated with a commit.", null: true, connection: true, numeric_pagination_enabled: true do
  argument :filterBy, Inputs::CheckSuiteFilter, "Filters the check suites by this type.", required: false
end
```

Now, in my resolver method, I have to use this

```ruby
def check_suites(**arguments)
  arguments[:filter_by] ||= {}
  
  if id = arguments[:filter_by][:app_id].presence
    check_suites = check_suites.for_app_id(id)
  end
end
```

Because the argument is not required, if I try to directly use `arguments[:filter_by][:app_id]` without setting it to `{}`, I'll get a `undefined method `[]' for nil:NilClass`.

Would you accept a PR that just sets this argument to `||= {}` for us if args are not provided?

**Comment by rmosolgo** [comment]
How about using Ruby's built-in default values for keyword arguments, for example: 

```ruby
def check_suites(filter_by: {})
  # ... 
end 
```

Then, if the value isn't passed, you get `{}` as the value. Would that work?

**Comment by rmosolgo** [comment]
(Alternatively, you could consider the `default_value:` option for GraphQL arguments, but it would also affect the documentation)

**Comment by gjtorikian** [comment]
That would totally work. I didn't realize you could do that, but after unpacking `**` (which always trips me up) makes sense!
