### ISSUE TITLE
Mutation cannot return Array of GraphQL::ExecutionErrors

### ISSUE THREAD

**Issue by ndac-todoroki** [rmosolgo/graphql-ruby#1587]
Thanks to #1230 & #1231, Arrays of `GraphQL::ExecutionError`s are valid returns.
Although this could be done in `GraphQL::Schema::Object`s, it doesn't work on `GraphQL::Schema::RelayClassicMutation`s.

#### examples
https://github.com/ndac-todoroki/graphql-ruby-test
do `rails server` and post queries to /graphql

- Query example
```graphql
query testField {
  testField
}
```

- Mutation example
```graphql
mutation testMutation {
  addFoo(input: {}) {
    foo
  }
}
```

#### what is expected
Both returns errors like

```js
{
  "data": null,
  "errors": [
    {
      "message": "one",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "testField",
        0
      ]
    },
    ...
  ]
}
```

#### what happens

The query example returns the error above as expected.
The mutation example, in contrast returns an error like this:

```json
{
  "error": "Unexpected token T in JSON at position 0"
}
```

Rails console log:
```
Started POST "/graphql" for 127.0.0.1 at 2018-06-15 12:06:47 +0900
Processing by GraphqlController#execute as */*
  Parameters: {"operationName"=>"testMutation", "variables"=>{}, "query"=>"mutation testMutation {\n  addFoo(input:{}) {\n    foo\n  }\n}\n", "graphql"=>{"operationName"=>"testMutation", "variables"=>{"input"=>{"lessonId"=>4000}}, "query"=>"mutation testMutation {\n  addFoo(input: {}) {\n    foo\n  }\n}\n"}}
Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.0ms)



TypeError (no implicit conversion of Symbol into Integer):

app/controllers/graphql_controller.rb:10:in `execute'
```

#### environment
    graphiql-rails (1.4.10)
      railties
      sprockets-rails
    graphql (1.8.3)

**Comment by rmosolgo** [comment]
Thanks for the bug report! Sounds like an inconsistency in `Schema::RelayClassicMutation` 😖

**Comment by rmosolgo** [comment]
I don't have plans to work more on this. If you need to add multiple execution errors, you can use `extras [:execution_errors]` in your mutation, then

```ruby 
def resolve(execution_errors:, ...) 
  execution_errors.add(GraphQL::ExecutionError.new(...))
  execution_errors.add(GraphQL::ExecutionError.new(...))
end 
```

Let me know if that doesn't work! You can find the API docs for that object here: https://graphql-ruby.org/api-doc/1.9.11/GraphQL/Query/Context/ExecutionErrors
