### ISSUE TITLE
Left Outer Join in wrong order

### ISSUE THREAD

**Issue by coreycondardo** [rmosolgo/graphql-ruby#1588]
```
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "bars"
```
When I am fetching a nested resource the AR query appears to  have Left Outer Joins in the wrong order, trying to join tables before they have been joined. Is this related to the graphql gem, or is this somewhere in my actual relationships?

**Comment by rmosolgo** [comment]
AFAIK GraphQL doesn't know anything about ActiveRecord or SQL, so I wouldn't expect to find the cause of this bug in the gem. 

However, if you want to keep debugging here, please reopen the issue with all the relevant debugging info: 

- Full error message 
- Full stack trace 
- Source code of relevant GraphQL types/fields 

Good luck!
