### ISSUE TITLE
Reusing types in root

### ISSUE THREAD

**Issue by mlh758** [rmosolgo/graphql-ruby#1591]
I'm fairly new to GraphQL so this could very well be me messing something basic up here.

I used the Rails generator to install the GraphQL gem and get the basic types set up.

Here's an example of a type set up under `graphql/types`:
```
class Types::PageType < Types::BaseObject
  field :name, String, null: false
  field :category, String, null: false
end
```

Then in `query_type.rb`
```
field :page, PageType, null: true do
  description 'A page!'
  argument :name, String, required: true
end

field :pages [PageType], null: true do
  description 'A list of configured pages'
  argument :category, String, required: true
end

...methods to retrieve those
```

However, if I try to query the API with this setup I get an error like:
`NameError (uninitialized constant Types::QueryType::PageType):`

This error goes away if I remove either of the fields above. I can also add queries for other types in the file.

Am I missing something obvious here? If I declare a `PagesType` and give it one field with an array of Pages and use that `PagesType` that also fixes the issue but that feels cludgy and articles like [this](https://hackernoon.com/advanced-querying-with-graphql-and-express-8cf2fd05f5ea) make me think I should be able to have a singular and a plural version of the query exposed.

**Comment by rmosolgo** [comment]
Hi! sorry about the bug! 

> This error goes away if I remove either of the fields above. 

How interesting. So, if _both_ fields are present, you see that bug, but if one of the fields is commented out, then it works ok? 

Could you please share the full error message and backtrace? Readers can help you debug if you share the context that you have 😉

**Comment by mlh758** [comment]
Unfortunately, that's where it gets weird for me:
```
LoadError (Unable to autoload constant Types::MutationType, expected<app_path>/app/graphql/types/mutation_type.rb to define it):
```

**Comment by rmosolgo** [comment]
Is that the entire stack trace?

**Comment by mlh758** [comment]
I updated my comment with more of the trace, our logging goes to a remote server and traces get truncated after a few lines. I'll switch my logging around and try to get a more thorough one.

**Comment by mlh758** [comment]
Line 12 is where the second declaration using that type starts. `field :pages [PageType], null: true do` in my example above.

**Comment by hidde-jan** [comment]
I’ve noticed error messages are rather iffy sometimes. Open a rails console (`bin/rails c`) and type `<YourAppName>Schema`. The real error should present itself. It’s got something to do with the rails development server and auto loading.

**Comment by jabawack81** [comment]
I had the same exact problem and using the old way for the types fixed it for me:

```
 field :posts, [Types::PostType], null: false do
    description "All the post"
  end
  def posts
    Post.all
  end

  field :post, Types::PostType, null: true do
    description "Find a post by ID"
    argument :id, ID, required: true
  end
  def post(id:)
    Post.find(id)
  end
```

**Comment by mlh758** [comment]
That looks the same as my declaration above, except you have scoped the types with `Types::`. Is that what fixed it for you?

**Comment by jabawack81** [comment]
@mlh758 yes

**Comment by mlh758** [comment]
I finally got back around to this. Adding the prefix didn't fix it for me. Same errors all around.

**Comment by jabawack81** [comment]
yes I get a lot of error like those in my experiences there is an error in one of your mutation or query and is reported like that a suggestion i can give you is to comment out all of them and add one at the time untile you find the culprit

**Comment by mlh758** [comment]
Unfortunately that brings me around to the beginning of this issue.

I have no mutations, and if I comment out either of the two queries for this type it works. I can't have both queries using the type, but I can have either of them.

**Comment by bary822** [comment]
@mlh758 
It looks to me that reported errors both resulted by failure on autoload, which how typical rails application looks up constant.

For this case, looking up `PageType` fails because you are referring it from inside `Types::QueryType` class. The app simply assumes `PageType` defined under `Types::QueryType` namespace, hence `Types::QueryType::PageType`. As @jabawack81 stated, adding `Types::` should fix this issue.

Same goes to the issue `Unable to autoload constant Types::MutationType`.
Assuming your schema looks like:
```
# app/graphql/your_schema.rb

class YourSchema < GraphQL::Schema
  mutation(Types::MutationType)
  query(Types::QueryType)
end
```
then this expects `Types::MutationType` defined in `app/graphql/types/mutation_type.rb`.

If you don't want your app accepts any mutation queries, the line `mutation(Types::MutationType)` should be removed from schema.

**Comment by mlh758** [comment]
@bary822 as I pointed out at the beginning, this error only happens if I have both of the query fields defined. If I comment out either of them it works fine. It doesn't matter which of the two fields I comment out. 

I also already responded that adding `Types::` simply brought about a different error which appears to be misleading since the mutations portion doesn't raise any exceptions and I can use the schema normally as long as I only have one field per type.

**Comment by bary822** [comment]
>  this error only happens if I have both of the query fields defined

This is due to the mechanism how Rails look up constant.
Suppose you have:
```
# app/graphql/types/page_type.rb
class Types::PageType < Types::BaseObject
...
end
 
# app/graphql/types/query_type.rb
class Types::QueryType < Types::BaseObject
...
  field :page, PageType, null: true do
    description 'A page!'
    argument :name, String, required: true
  end

  field :pages [PageType], null: true do
    description 'A list of configured pages'
    argument :category, String, required: true
  end
...
```
In the first time `PageType` is called, Rails starts auto-loading process because at this moment, Rails doesn't know how to resolve what `PageType` is.
The order Rails looks for the constant `PageType` follows:
1. `Types::QueryType::PageType` => NameError
2.` Types::PageType` => Bingo!!
Then `PageType` will be identified as `Types::PageType`.

In the second time, however, Rails does not perform this lookup. It simply assumes `PageType` is `Types::QueryType::PageType` then it raises `NameError` in this case.

I don't honestly know why Rails takes this approach, but that's how it's implemented as of Rails 5.2.
https://github.com/rails/rails/blob/v5.2.0/activesupport/lib/active_support/dependencies.rb#L509-L513

[This](https://nopecode.com/2013/11/13/rails-autoloading.html) explains even better. If you are interested, you can check it out.

**Comment by bary822** [comment]
To workaround this, you can explicitly specify nested module name, for example:
```
# app/graphql/types/page_type.rb
module Types
  class PageType < Types::BaseObject
    ...
  end
end
 
# app/graphql/types/query_type.rb
module Types
  class QueryType < Types::BaseObject
    ...
    field :page, PageType, null: true do
      description 'A page!'
      argument :name, String, required: true
    end

    field :pages [PageType], null: true do
      description 'A list of configured pages'
      argument :category, String, required: true
    end
    ...
  end
end
```

**Comment by mlh758** [comment]
Okay. Trying out the suggestions:

1. Just to make sure I wasn't skipping anything, I commented out the mutation portion of my schema with both queries defined. Error: `uninitialized constant Types::QueryType::PageType`
2. Added `Types::` on the prefix in my declarations in the query schema again, with mutations commented out. This time it worked.
3. Uncommented the mutations and it still worked.

I must have messed something up before when I added the `Types::` prefix in the early troubleshooting. Thank you for helping out.

**Comment by Magic-Jay** [comment]
> I’ve noticed error messages are rather iffy sometimes. Open a rails console (`bin/rails c`) and type `<YourAppName>Schema`. The real error should present itself. It’s got something to do with the rails development server and auto loading.

Thanks for this helpful answer! Can't believe it's 2023 and all these ruby rails-related libraries and packages still operate like it's in the 1970s. It cannot catch a compiling formatting error and what's the point of throwing error logs and code traces if they are just wrong?
