### ISSUE TITLE
Datadog tracing does not work with the new class based interface

### ISSUE THREAD

**Issue by staugaard** [rmosolgo/graphql-ruby#1592]
I recently migrated my schema and a few types to the new class based system. When deploying that, I lost datadog traces.

**Comment by michal-samluk** [comment]
That's weird. We have migrated most of our code to class based API and DataDog works perfectly. Are you using any custom instrumentation? Have you been using datadog tracing from graphql-pro?

**Comment by staugaard** [comment]
Turns out the bug is in the datadog gem

https://github.com/DataDog/dd-trace-rb/blob/master/lib/ddtrace/contrib/graphql/patcher.rb#L28-L39
