### ISSUE TITLE
More flexibility in error management

### ISSUE THREAD

**Issue by everdrone** [rmosolgo/graphql-ruby#1594]
Is there a way to provide more *strict* errors?

Currently when we `raise GraphQL::ExecutionError, "message"`, the error is appended to the `errors` array in the response, while the *successful* queries get through and appear inside the `data` key.

What if when the first `ExecutionError` is thrown, it appears inside the `errors` array **and** clears out the `data` object by enforcing the API consumer to fix the query?

Of course this is scenario may not be the correct way for every API that uses `graphql-ruby`, so why not adding some configuration options to the graphql initializers?

**Comment by everdrone** [comment]
In my case, the perfect scenario - whenever an `ExecutionError` is thrown - would be:
- leave the `data` in the response blank
- display **only** the latest error from the `errors` stack

```diff
 {
-  "data": {
-    "fruits": [ ... ]
-  },
   "errors": [
     {
       "message": "...",
       "locations": [ ... ],
       "fields": [ ... ]
-    },
-    {
-      "message": "more errors",
-      "locations": [ ... ],
-      "fields": [ ... ]
     }
   ]
 }
```

**Comment by hidde-jan** [comment]
This is precisely contrary to the GraphQL philosophy of nullability and the fact that in a networked context things might fail. If a query is according to the Schema, then the query is not wrong, the backend just isn’t able to respond to the query in a ‘proper’ way. There’s two approaches, at least, such as bubbling up a null or have a response type that gives back errors. If I ask for multiple unrelated fields, why should an ‘error’ in the backend on one field affect a completely different field?

**Comment by rmosolgo** [comment]
Hi, I'm glad you found a work-around that works for you! 

`GraphQL::ExecutionError` is basically an implementation of "field errors" from [the GraphQL spec](http://facebook.github.io/graphql/June2018). As described there, both errors and data may be present in a response (like @hidde-jan  pointed out). 

So, if you want some behavior different from the spec, maybe `GraphQL::ExecutionError` is not a good fit for you! Instead, why not use a plain old Ruby exception to halt the query, for example: 

```ruby 
class MySchema < GraphQL::Schema 
  class HaltError < StandardError
    # ... 
  end 

  def self.execute(*args)
    super 
  rescue HaltError => err 
    { "errors" => [err.to_json] } 
  end 
end 
```

Then, raise that error during execution if you want to return _just_ an error, with no data. 

Thanks for the question and I hope that helps!

**Comment by everdrone** [comment]
Thanks @rmosolgo, i'll try that out!
seems far more flexible than my current approach
