### ISSUE TITLE
Field for Type with interface is not accessible

### ISSUE THREAD

**Issue by leoc** [rmosolgo/graphql-ruby#1597]
Hi there, thanks for building `graphql-ruby` I hope to enjoy it much more in the future! Cheers.

I have a schema like this:

```ruby
class Types::Query < GraphQL::Schema::Object
  description "Query"

  field :repository, Types::Repository, null: false do
    argument :repositoryId, ID, as: :id, required: true
  end
  def repository(id:)
    ::Repository.find(id)
  end

  field :project, Types::Project, null: false do
    argument :projectId, ID, as: :id, required: true
  end
  def project(id:)
    Project.find(id)
  end
end

class Types::Project < GraphQL::Schema::Object
  description 'Project'

  field :id, ID, null: false
  field :name, String, null: false
end

module Types::BaseInterface
  include GraphQL::Schema::Interface
end

module Types::Node
  include Types::BaseInterface

  orphan_types Types::Repository, Types::Folder

  field :id, ID, null: false
  field :name, String, null: false
end

module Types::Repository
  include Types::Node
end

module Types::Folder
  include Types::Node
end
```

I took the structure from the `jazz.rb` example from the specs.

Unfortunately for the query:

```
{
  repository(repositoryId: 309) {
    name
  }
}
```

I only get:

```json
{
  "errors": [
    {
      "message": "Field 'repository' doesn't exist on type 'Query'",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "fields": [
        "query",
        "repository"
      ]
    }
  ]
}
```

This query works though:

```
{
  project(projectId: 2) {
    name
  }
}
```

Does anyone have an idea what might be wrong with my example?

Also I am confused about the use of `module` instead of `class`. The Docs are a little confusing. In the part about `orphaned_types` it's suddenly a `class` but that does not work either. Since ruby complains about the inherited superclass not being a `class` but a `module`

Edit: If I add `orphan_types` to my schema:

```ruby
class MySchema < GraphQL::Schema
  orphan_types(Types::Repository)
  query(Types::Query)
end
```

I see the following exception:

```
GraphQL::Schema::InvalidTypeError (Unexpected schema traversal member: Types::Node (Module))
```

**Comment by rmosolgo** [comment]
Hi, sorry about the bug and thanks for opening such a detailed issue!

I'm not _exactly_ sure but I think GraphQL-Ruby has a rule that says "interfaces without any objects are hidden from the schema", so that might be why `Types::Repository` is being hidden. 

Did you mean for `Types::Repository` to be an interface or an object? (If you meant for it to be an object, you could change the definition to use `class ... < GraphQL::Schema::Object`, like `Types::Project`)

**Comment by leoc** [comment]
Hi, thanks for your quick reply. Maybe it's not a bug, because of a misunderstanding.

I copied the example from the `jazz.rb` in the specs :smile_cat: 

`Types::Repository` and `Types::Folder` should be types with shared fields from `Types::Node` interface.  I don't know if they need to be Objects or Interfaces ... :sweat_smile: 

I imagined something like:

```
interface Node {
  name: String!
  path: [String!]
}

type Repository implements Node {
  specialArg: String!
}

type Folder implements Node {
  contents: [String!]
}
```

**Comment by rmosolgo** [comment]
Oh, I see! For a structure like that, try this Ruby code: 

```
class Types::BaseObject < GraphQL::Schema::Object 
end 

class Types::Repository < Types::BaseObject
  implements Types::Node
end

class Types::Folder < Types::BaseObject
  implements Types::Node
end
```

Specifically: 

- Use `class ... < ` to make object types 
- Use `implements ...` to add interfaces to objects

I think that will make it work a bit better!  Feel free to reopen this if not.
