### ISSUE TITLE
Case of GraphQL::Schema.rescue_from doesn't work

### ISSUE THREAD

**Issue by michiomochi** [rmosolgo/graphql-ruby#1598]
graphql-ruby version is v1.8.3.
`rescue_from` doesn't work when there is a `query` or `mutation` definition before `rescue_from`.

## Implement

NG

```
class TestSchema < GraphQL::Schema
  〜
  query Types::Query
  mutation Types::Mutation

  rescue_from(Exception) do |error|
    # doesn't call
  end
〜
```

OK

```
class TestSchema < GraphQL::Schema
  〜
  rescue_from(Exception) do |error|
    # call
  end

  query Types::Query
  mutation Types::Mutation
〜
```

# Reason

`rescue_from` is following code.
```
def rescue_from(err_class, &handler_block)
  @rescues ||= {}
  @rescues[err_class] = handler_block
end
```

And, `query` and `mutation` are affected by `@rescues`. (maybe)

Please check 🙏

**Comment by rmosolgo** [comment]
How strange! Thanks for opening this issue and sharing your work-around.

**Comment by mcdave029** [comment]
Any Updates here? both implementations are not working with me too. 😅

**Comment by modosc** [comment]
i noticed the same thing and (at least for us) it was related to [graphql-preload](https://github.com/ConsultingMD/graphql-preload). having `enable_preloading` inside of our schema class definition broke `rescue_from` behavior (both the built-in and from [graphql-errors](https://github.com/exAspArk/graphql-errors). making a call to `enable_preloading` outside of the class (ie, `MySchema.enable_preloading`) seems to resolve it but i'm not sure why.

**Comment by jonathanheron** [comment]
@modosc I see the same problematic behaviour when using graphql-preload and including `enable_preloading` inside the schema class definition.

However, when I move `MySchema.enable_preloading` to anywhere else in my code, I see the same issue. Where are you calling `MySchema.enable_preloading` in a way that resolves the problem?

**Comment by nekogami** [comment]
@jonathanheron Since it's been 4 months, I don't know if you solved your issue but I ended finding a solution that worked on my project here https://github.com/ConsultingMD/graphql-preload/issues/17#issuecomment-456337822

**Comment by rmosolgo** [comment]
I just added new error handling for the interpreter runtime here: https://github.com/rmosolgo/graphql-ruby/pull/2458 I think it should work with any order of schema configuration, since it doesn't touch the `.graphql_definition` compatibility layer.

If you give it a try and run into trouble, please open a new issue!
