### ISSUE TITLE
Needs a cool logo.

### ISSUE THREAD

**Issue by sgwilym** [rmosolgo/graphql-ruby#16]
This project’s great, and the beginnings of documentation you have (and advice you've been dispensing on Slack) has been super helpful. I'd like to help out in my own small way and suggest a logo for this project, riffing off of Facebook's own GraphQL logo:

![graph-ql-01](https://cloud.githubusercontent.com/assets/579491/9082548/23b4c6ca-3b65-11e5-98a9-b3c5ddd3515c.png)

I've tried to use a more Ruby-like colour here, but I'd be happy with the original magenta, too.

**Comment by rmosolgo** [comment]
Oh I like it! I might play a bit with colors, give me a minute....

**Comment by rmosolgo** [comment]
I tried a couple of other reds: 

![untitled drawing](https://cloud.githubusercontent.com/assets/2231765/9092184/5d2467e6-3b59-11e5-9826-63d076e30aa0.png)

I like yours best :D Wanna make a PR to put it in the readme & add an SVG?

**Comment by sgwilym** [comment]
Cool! Done and done.
