### ISSUE TITLE
Store query complexity and depth in a query object

### ISSUE THREAD

**Issue by y310** [rmosolgo/graphql-ruby#1604]
For logging purpose, I want to get a query complexity and depth value.
Although those values are available in analyzer, I think there's no way to export those values outside of the analyzer other than using some global state (class variable, Thread.current, etc) since analyzer is schema-level object and query object is the only available query-level object in the analyzer.

So, I think it's convenient if it's available from query object like below.

```ruby
result = Schema.execute(query: query)
MyLogger.post(
  operation_name: result.query.operation_name,
  complexity: result.query.complexity,
  depth: result.query.depth
)
```

**Comment by rmosolgo** [comment]
Sorry for the late reply, but I think this could be done using `query.context`: 

```ruby 
class MySchema < GraphQL::Schema
  # Make a custom instance of the analyzer 
  log_query_depth = GraphQL::Analysis::QueryDepth.new { |query, depth| 
    query.context[:query_depth] = depth
  }
  # Hook it up to your schema
  query_analyzer(log_query_depth)
end
```

The complexity analyzer can be extended in the same way, see http://graphql-ruby.org/queries/complexity_and_depth

Feel free to give it a try and reopen this issue if it doesn't work!

**Comment by y310** [comment]
Thanks, it works for me 👍
