### ISSUE TITLE
Guide: Extending the GraphQL-Ruby Type Definition System

### ISSUE THREAD

**Issue by blevine** [rmosolgo/graphql-ruby#1605]
Guide talks about customizing fields and adding the `field_class` declaration to the BaseInterface using the following example:

```
class BaseInterface < GraphQL::Schema::Interface
  field_class AuthorizedField
end
```

However, BaseInterface is actually a module that includes `GraphQL::Schema::Interface` in 1.8 correct?

**Comment by rmosolgo** [comment]
I checked the current docs and didn't find this bad example, so I guess it was taken care of.
