### ISSUE TITLE
New 1.8 add hash_key: :some_key not find that key.

### ISSUE THREAD

**Issue by zw963** [rmosolgo/graphql-ruby#1607]
Previous working code:

```rb
field :content, String, null: true
def content
    @object[:content]
end
```

After change to Following, it not work:

```rb
field :content, String, null: true, hash_key: :content
```

`@object` is not a hash object, what, what i expect is, if add `hash_key` options,
it always first try to invoke `@object[:content]`, but behavior seem like not work 
like this.

**Comment by rmosolgo** [comment]
That's right, it only uses `#[]` if the object is a Hash. Here's the check in question: 

https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/field.rb#L305

I'd happily accept a PR that improves that check (maybe to see if `@hash_key` is set?) and adds a test for non-Hash objects. I think that would be a nice improvement! I'm happy to help out if you want to open a PR.
