### ISSUE TITLE
Guide: Extending the GraphQL-Ruby Type Definition System (for mutations?)

### ISSUE THREAD

**Issue by blevine** [rmosolgo/graphql-ruby#1608]
Can a mutation also be extended as is described in this section for types, fields, arguments? For example:

Can I use the field_class and argument_class declarations in my BaseMutation class (which is a subclass of RelayClassicMutation)?

Can the mutation itself be assigned metadata that can be considered in a schema filter to limit visibility of that mutation?

**Comment by rmosolgo** [comment]
It's similar but a bit different: 

- `field_class` will be used for the generated `*Payload` type's fields 
- `argument_class` will be used for the generated field's arguments 
- `input_object_class` will be used for the generated input object (and in the case of `RelayClassicMutation`, the arguments are actually applied to this input object, not the generated field) 

To filter based on the mutation you can do: 

```ruby
# Go from old-style `GraphQL::Field` to the new-style `GraphQL::Schema::Field` that generated it: 
field_instance = field_defn.metadata[:type_class]
# Get the mutation attached to this field: 
field_instance.mutation
```

How does that sound?

**Comment by blevine** [comment]
Is this code in the to_graphql method of the mutation base class?  Or is it in the filter.  Need some more context.

**Comment by blevine** [comment]
Never mind.  Figured it out.

**Comment by blevine** [comment]
Ok sorry.  I think I see what you're doing. The filter would encounter the field associated with the mutation (the field on the Mutation object). So getting the mutation from the field would determine that it represented  a mutation in the first place and then returning true or false would include or exclude the field for that mutation.
