### ISSUE TITLE
Query execution strategy option missing from new object-based schema definition?

### ISSUE THREAD

**Issue by eiwi1101** [rmosolgo/graphql-ruby#1614]
Perhaps I'm missing something, but when converting to the new Object-based schema definition (a required rabbit hole to start using Mutation classes), I can't seem to define the `{query|mutation}_execution_strategies`.

Old:
```ruby
MySchema = GraphQL::Schema.define do
  query QueryType
  query_execution_strategy MyCustomStrategy
end
```

New:
```ruby
class MySchema < GraphQL::Schema
  query QueryType
  query_execution_strategy MyCustomStrategy # <- No longer a setter
end
```

Error:
`ArgumentError: wrong number of arguments (given 1, expected 0)`

It'd seem that, when inheriting from `GraphQL::Schema`, `*_execution_strategy` is no longer a setter, however, I can't find any notes about this in the changelog. How can we still use our custom execution strategies?

**Comment by rmosolgo** [comment]
Hi! Sorry about the bug, this is an oversight. Lots of configuration methods had to be ported from the instance-defined API to the new class-based API. If you look in `GraphQL::Schema.to_graphql` you'll see how class configurations are transferred to a Schema instance; I'd welcome a PR to add these methods to that code if you're interested in making a try!

**Comment by mhuggins** [comment]
Looks like this can be closed out!
