### ISSUE TITLE
CoercionError does not allow for extra options

### ISSUE THREAD

**Issue by aschepis** [rmosolgo/graphql-ruby#1621]
I have been using the `options` accessor on `GraphQL::ExecutionError` to add additional information to errors so that they are consumable by humans and machines. I was also hoping to do this in the case of `GraphQL::CoercionError`s that occur during validation but the `CoercionError` does not allow for this. Is there a specific reason why? If not I would be happy to put together a PR.

**Comment by rmosolgo** [comment]
No, I think it's an oversight! That would be nice improvement, feel free to ping me in the PR if I can help out while it's in progress.

**Comment by aschepis** [comment]
@rmosolgo -- do you prefer having a common class that `ExecutionError` and `CoercionError` derive from that has the `options` accessor or just adding an `options` accessor to `CoercionError`?

**Comment by rmosolgo** [comment]
Either way is fine with me!

**Comment by rmosolgo** [comment]
Fixed by #2431
