### ISSUE TITLE
Question: Is a Enum type (but allowing random string) possible for mutation argument type?

### ISSUE THREAD

**Issue by crokobit** [rmosolgo/graphql-ruby#1622]
As title, I found that the type for argument seems like only allow one of below type,  GraphQL::ScalarType, GraphQL::InputObjectType, and GraphQL::EnumType. (see reference [1])  

I want to have a Enum like type that has several default options but also allow random string for mutation saving data. Like an Union type of String and Enum. Is that possible? I think this will be helpful for client side. Client side (which has attributes accepting some default values but also allowing random string) just need to check schema for rendering the select options.

reference [1] https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/validation.rb#L126

**Comment by rmosolgo** [comment]
What you're describing is not possible. Enum types only allow enum values; unions are only allowed to contain object types. 

However, here are a couple of thoughts to implementing with compliant graphql: 

- Use an enum to list default values in the UI, but accept a string in the mutation 
- Make it so the mutation accepts two inputs, one enum and one string, and the UI can send a value in one _or_ the other

Hope that helps!

**Comment by crokobit** [comment]
Thanks @rmosolgo  :)
