### ISSUE TITLE
Schema class inheritance support

### ISSUE THREAD

**Issue by swalkinshaw** [rmosolgo/graphql-ruby#1627]
Right now most of the new 1.8 classes support inheritance (and it's recommended), but `Schema` does not. This has come up once or twice on Slack and we also have a use case for it.

We have two different schemas which share some base functionality. These are mostly plugins and query analyzers.

One solution is just ensuring we've define them manually on both schemas, but we also end up creating schemas in unit tests where it would be nice to always have that guarantee of consistency.

This is on our radar but nothing immediate so wanted to open an issue.

**Comment by rmosolgo** [comment]
:+1: definitely an oversight on my part, it'd be great to implement the necessary ancestor merging to make that work (joining arrays, merging hashes, etc)

**Comment by rmosolgo** [comment]
Thanks for chiming in! I'm working hard to wrap up the 1.9.0 stable release, and I'll circle back to this in the next version.

**Comment by jturkel** [comment]
@rmosolgo - We're increasingly needing this one too. I'd be happy to take a crack at it if you haven't had a chance to take a look yet.

**Comment by rmosolgo** [comment]
👌 !

**Comment by rmosolgo** [comment]
We may have _missed_ some spots, but the expected behavior is that inheriting schema classes Just Works :tm: starting in 1.9.8
