### ISSUE TITLE
mutation generator bug

### ISSUE THREAD

**Issue by ZeroSoulEater** [rmosolgo/graphql-ruby#1629]
If I generate a a new mutation `rails g graphql:mutation UserDelete`.

It will add 
```
class Types::MutationType  field :userDelete, Mutations::UserDelete.field
 < Types::BaseObject
```
to my mutation_type.rb. This leads to an error, because its placed in the wrong place it should be somewhere within the class.

could be intended to add it like this
```
class Types::MutationType < Types::BaseObject
  field :userDelete, Mutations::UserDelete.field
end
```

**Comment by ZeroSoulEater** [comment]
aaaand it should look like this

`field :userDelete,  mutation: Mutations::UserDelete`

not like this  `field :userDelete, Mutations::UserDelete.field`

it is wrong in my issue sorry

**Comment by rmosolgo** [comment]
Thanks for reporting this bug! Sounds like it needs a fix.
