### ISSUE TITLE
How to get proper type of field?

### ISSUE THREAD

**Issue by gjtorikian** [rmosolgo/graphql-ruby#163]
I'm trying to do some metaprogramming with fields. Given the following code:

```
field = Project::Schema.types[type].fields["number"]
```

I expect `field.type` to be `Int`. Instead, it's `Non-Null`. This is the case with all the fields in my schema. Is there a way to get the proper type name back?

**Comment by rmosolgo** [comment]
Maybe [`#unwrap`](http://www.rubydoc.info/github/rmosolgo/graphql-ruby/GraphQL/BaseType#unwrap-instance_method), which will return the "inner type" if there is one, otherwise it returns `self`. So:

```ruby 
types.Int.unwrap           # => Int 
(!types.Int).unwrap        #=> Int 
types[types.Int].unwrap # => Int 
```

How does that sound?

**Comment by gjtorikian** [comment]
Sadly, none of those seemed to work. To be clear `field` is `GraphQL::Field` object so I'm not sure why simply asking for [`type`](https://github.com/rmosolgo/graphql-ruby/blob/f3488487afce1dc96a5f1a952fc67dd92532c4b8/lib/graphql/field.rb#L75) wouldn't work.

**Comment by xuorig** [comment]
@gjtorikian I think what @rmosolgo means here is:

```
field = Project::Schema.types[type].fields["number"]
type = field.type.unwrap
```

<img width="436" alt="screenshot 2016-06-07 23 42 28" src="https://cloud.githubusercontent.com/assets/1919498/15882068/8577dc44-2d09-11e6-8738-438761362004.png">

**Comment by rmosolgo** [comment]
^^ Yep, thanks for a clearer example! 

> I'm not sure why simply asking for type wouldn't work

In a sense, it _does_ work. If the field's type is "simple", like `Int`, you get `GraphQL::INT_TYPE`. But some types are modified, for example `!Int` or `[Int]`. In this case, the "simple" type is wrapped by modifiers `NonNullType` or `ListType`. In these cases, you're getting instances of NonNullType or ListType which wrap the underlying type. 

You can use `#of_type` to step down _one_ layer of nesting, or `#unwrap` to "jump" to the inner-most type:

```ruby 
# Let's say you have a field that always returns a list of integers:
non_null_list_of_ints = field.type      # => ![Int]
non_null_list_of_ints.class             # => NonNullType 

# Step "in" by one level with `of_type`: 
non_null_list_of_ints.of_type           # => [Int]
non_null_list_of_ints.of_type.of_type   # => Int

# Or, go all the way to the inner type with `unwrap`: 
non_null_list_of_ints.unwrap            # => Int 

# If there is no nesting, `unwrap` returns `self`
int_type = non_null_list_of_ints.unwrap # => Int
int_type.unwrap                         # => Int 
```

In a case like this, if you don't know how many layers of "wrapping" there will be (from ListType or NonNullType), you can always use `unwrap` to get the inner-most type.

**Comment by gjtorikian** [comment]
> In a case like this, if you don't know how many layers of "wrapping" there will be (from ListType or NonNullType), you can always use unwrap to get the inner-most type.

That makes total sense. Thank you and @xuorig !
