### ISSUE TITLE
Expose query complexity in response

### ISSUE THREAD

**Issue by drewmbrien** [rmosolgo/graphql-ruby#1631]
Hi! I'm implementing a complexity-based rate limiting strategy.  Part of my work entails exposing the calculated complexity of a given request in the response.

I'd like to make `complexity` a field of `Types::QueryType` like so:

```
field :complexity do
    type types.Int
    description 'The complexity of the current query'
    resolve -> (obj, args, ctx) do
      # this is where im getting stuck
    end
  end
```

I can easily get a handle on the complexity value in an Analyzer, but I can't quite figure out how to get this value in the resolver.

My first instinct was to figure out a way to calculate it in my `GraphqlController` and pass it in the context to `AppSchema.execute(...)`However, I'm not sure how to quite accomplish this.

Am I on the right track here? Or am I going about this all wrong?

Thanks!

**Comment by drewmbrien** [comment]
Update: this seems to be working, but I'm not quite sure its the best approach. Do you think there is a cleaner way of accomplishing this?
```
class GraphqlController < Api::V2::ApiController
      def execute
        variables = ensure_hash(params[:variables])
        query = params[:query]
        operation_name = params[:operationName]
        complexity_score = get_complexity_score(query, variables)
        context = {
          current_api_key: @api_key,
          super_admin: @api_key.company.employees.not_terminated.admin.first!,
          rate_limit: env.dig('rack.attack.throttle_data', 'throttle.api.v1'),
          complexity_score: complexity_score
        }
        result = AppSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
        ...
      end
      
      ...

     def get_complexity_score(query_string, variables)
        query = GraphQL::Query.new(AppSchema, query_string=query_string)
        query_analyzer = GraphQL::Analysis::QueryComplexity.new { |_query, complexity| complexity }
        GraphQL::Analysis.analyze_query(query, [query_analyzer]).first
     end
     
     ... 
end
```

and then query_type.rb is as simple as:
```
Types::QueryType = GraphQL::ObjectType.define do

  ...

  field :complexity do
      type types.Int
      complexity 0
      description 'The complexity of the current query'
      resolve -> (_obj, _args, ctx) do
        ctx[:complexity_score]
      end
    end

  ...

end
```

**Comment by rmosolgo** [comment]
👋  Hey, great question! We do it similarly in GitHub, writing the complexity into `context`, then using that to return the value to client (for our `rateLimit` field). 

I think there's one downside the solution you posted, performance. The incoming query will be parsed, validated, and analyzed _twice_, once in `get_complexity_score`, then again to execute the query. Depending on your situation, that might really add up! 

I think another option is to use the built-in analyzer and add it to your schema: 

```ruby 
class MySchema < GraphQL::Schema 
  # ... 
  # Make an analyzer that will write the complexity to context: 
  COMPLEXITY_LOGGER = GraphQL::Analysis::QueryComplexity.new do |query, complexity|
    query.context[:complexity_score] = complexity 
  end 
  # Then hook it up to the schema: 
  query_analyzer(COMPLEXITY_LOGGER) 
end 
```

That should work too! Feel free to post back here if you give it a try and it doesn't work.

**Comment by drewmbrien** [comment]
ah thats way better! I didn't realize `query` had a reference to `context`. I'll give it a whirl - thanks!
