### ISSUE TITLE
Unexpected behavior from `GraphQL::Relay::Node` id field

### ISSUE THREAD

**Issue by cmatheson** [rmosolgo/graphql-ruby#1634]
I would like to provide a default `id` implementation for types in my schema (they all implement `GraphQL::Relay::Node.interface`).  Here is a small script that demonstrates the issue I run into:

```ruby
class ApplicationObjectType < GraphQL::Schema::Object
  def id
    "I AM A GLOBAL ID"
  end
end

class FooType < ApplicationObjectType
  graphql_name "Foo"
  implements GraphQL::Relay::Node.interface
  # GraphQL::Relay::Node.interface defines the id field below, so I wouldn't expect to have to repeat it here
  # (if i do repeat it here though, everything works)
  #field :id, ID, null: false
end

class QueryType < GraphQL::Schema::Object
  graphql_name "Query"
  field :node, field: GraphQL::Relay::Node.field
end

class Schema < GraphQL::Schema
  query QueryType
  orphan_types FooType

  def self.id_from_object(obj, type_def, _)
    GraphQL::Schema::UniqueWithinType.encode(type_def.name, obj.id)
  end

  def self.object_from_id(id, query_ctx)
    {id: "OOPS"}
  end

  def self.resolve_type(_, _, _)
    FooType
  end
end

puts Schema.execute(<<~QUERY).to_json
  {
    node(id: "1234") {
      id
    }
  }
QUERY
```
When running this script, I would expect to see:

```
{"data":{"node":{"id":"I AM A GLOBAL ID"}}}
```

But what I really get is:

```
graphql-ruby-0090cf632736/lib/graphql/schema/field.rb:309:in `block in resolve_field': undefined method `object' for {:id=>"OOPS"}:Hash (NoMethodError)
```

In 1.8.0, I wouldn't get an error, but I would get "OOPS" for the id instead of "I AM A GLOBAL ID", which is not what I would expect.  The current version of graphql returns an error instead.

The interesting thing is that if I uncomment the `field :id, ID, null:  false` line from `FooType`, everything works as expected.  Since `GraphQL::Relay::Node.interface` defines that field though, I would think it's unnecessary to re-define that field?

I know there is the `global_id_field` helper, but it _seems_ like I shouldn't need that with the new class API.

**Comment by rmosolgo** [comment]
Thanks for opening this issue and for giving all the relevant details! I suspect this has something to with the fact that `Node.interface` returns a _legacy-style_ interface. 

I wonder, do you mind giving it a try with `GraphQL::Types::Relay::Node` instead? That one is a class-based interface, it might Just Work :tm: .

**Comment by cmatheson** [comment]
Hey @rmosolgo,

Switching to `GraphQL::Types::Relay::Node` does indeed get rid of the run-time error, so that is great.  It is still calling the id method on the object instead of the inherited id method on the type though. (That is, I'm getting "OOPS" for the id, instead of "I AM A GLOBAL ID".  I think this is a bug, but maybe my sense of how this should work is just wrong.

Thanks!

**Comment by mskubenich** [comment]
Hi ! 

Legacy-style `GraphQL::Relay::Node.field` is being added to a class-based type. See `GraphQL::Types::Relay::NodeField` for a replacement.
Legacy-style `GraphQL::Relay::Node.plural_field` is being added to a class-based type. See `GraphQL::Types::Relay::NodesField` for a replacement.

how to use it ?

**Comment by dmill** [comment]
Big bump on this! This gave me the runaround for several hours. I kept getting `undefined method `object' for #<Hash:0x00007f990b8795a0>` when resolving my mutation. Turned out it was because I was using `GraphQL::Relay::Node.interface`. `implements GraphQL::Types::Relay::Node` fixed it. I don't see this documented anywhere - can we get this in the docs to save future poor souls?

P.S great work @rmosolgo and team, your attention to these issues is admirable and appreciated.

**Comment by rmosolgo** [comment]
>  can we get this in the docs

Each docs page has an `Edit` link at the bottom. Please feel free to use it if you'd like to improve the documentation! 

The `global_id_field` method actually defines a new method. It sounds like you don't want the behavior from that helper, so how about _not_ using it? Here's the source by the way: 

https://github.com/rmosolgo/graphql-ruby/blob/a22d04f28ce4ee4b83c90f01aec46ac2873d1ec6/lib/graphql/schema/member/has_fields.rb#L86-L92

If you have your own ID setup, I recommend not using that helper.

**Comment by kakas** [comment]
@mskubenich 
```diff
 module Types
   class QueryType < BaseObject
-    field :node, field: GraphQL::Relay::Node.field
-    field :nodes, field: GraphQL::Relay::Node.plural_field
+    add_field(GraphQL::Types::Relay::NodeField)
+    add_field(GraphQL::Types::Relay::NodesField)
    ...
```
