### ISSUE TITLE
Mutation should check that the return value is a hash

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#1638]
It happily tries to set `result[:client_mutation_id] = ...`, but doesn't actually make sure it's a hash, so might get `ActiveModel::MissingAttributeError: can't write unknown attribute `client_mutation_id` if you return an ActiveRecord object.

**Comment by clader** [comment]
I too have this problem.  In previous versions I've never had to set or use the ClientMutationID input field on Mutations, and so I'm really unsure why it's there or what I'm supposed to do with it.

Am in the process of upgrading my mutations to 1.8 and hit this error.

**Comment by atomaka** [comment]
@clader ClientMutationId is a field your client may opt to send.  Your only job is to send it back to them.  You can fix the issue by returning a hash from your mutation resolver.

@rmosolgo Will the final implementation throw an exception if a hash is not passed or will it deal with AR objects?

**Comment by blevine** [comment]
Did a recent change cause this? My resolver returns an ActiveRecord object and I'm getting the MissingAttributeError even though my mutation didn't request the client_mutation_id field.

**Comment by rmosolgo** [comment]
Fixed with the new interpreter: 

https://github.com/rmosolgo/graphql-ruby/blob/8403452f2d2e3a3ab2aa0f03cd31b945671b589c/lib/graphql/schema/relay_classic_mutation.rb#L64-L67
