### ISSUE TITLE
Retrieving field name new API context (formerly ctx)?

### ISSUE THREAD

**Issue by clader** [rmosolgo/graphql-ruby#1639]
With 1.7x, I used to be able to reference the current contexts field names in my resolvers by using:

`ctx.field.name
`
But with 1.8 using the new context it throws an undefined method error:
```
F, [2018-06-29T16:14:06.065369 #8114] FATAL -- :
F, [2018-06-29T16:14:06.065413 #8114] FATAL -- : NoMethodError (undefined method `field' for #<Query::Context ...>):
F, [2018-06-29T16:14:06.065435 #8114] FATAL -- :
```

With 1.8 API how can I properly resolve the "relative) field name using context?

Thanks
~Calder

**Comment by clader** [comment]
I think I've "sort of" solved this by adding the path to extras:

`field :created_users, resolver: RBAC::Resolvers::UsersResolver, extras: [:path]`

and then in my resolver I can use:
`path.last`

To the the fieldname as the last value in the path.  But I'm not totally sure this is the recommended method. 
Can someone confirm if there's a more preferred way or not?

**Comment by cabello** [comment]
I am looking into this issue myself, looking at the codebase I see that extras is also available inside the resolver definition:

```ruby
module Resolvers
  class SensitiveValue < Resolvers::Base
    type [Types::SensitiveValue], null: true

    argument :obfuscate, GraphQL::Types::Boolean, required: false, default_value: true

    extras [:path]

    def resolve(obfuscate:, path:)
       # ...
    end
  end
end
```

I am just curious on how the implementation works because I would like to support something similar as the regular field definition with optional `method: :foo`.

**Comment by rmosolgo** [comment]
:+1: for `extras [...]`, that's the best way to get field-level info in resolve methods. I think `extras [:graphql_name]` would also work to give you the field name.
