### ISSUE TITLE
Setting field to an InputObject subclass produces invalid schema information

### ISSUE THREAD

**Issue by hidde-jan** [rmosolgo/graphql-ruby#1642]
GraphQLi started throwing invariant related errors when I accidentally set a field to a InputObject descendent class. I didn't get any errors on the graphql-ruby side of things. It seems it produces a schema that isn't according to spec.

graphql (1.8.3)
graphql-batch (0.3.9)
graphiql-rails (1.4.10)

**Comment by rmosolgo** [comment]
Hi! If you want to debug this together, please reopen this issue with the relevant code and the entire stack trace.
