### ISSUE TITLE
Class Based API: Implementing interfaces on Connections with .define_connection?

### ISSUE THREAD

**Issue by clader** [rmosolgo/graphql-ruby#1644]
Hi there,

With the 1.8 upgrade it seems I still have to define my connections using the old method as Relay has not yet been ported to the new class based API.  So I'm still defining my connections with custom fields as follows:
Connection:
```ruby
# Define Graphql Connection for Users
RBAC::Connections::UsersConnection = RBAC::Types::UserType.define_connection do
  name 'UsersConnection'
  field :totalCount, Shared::Fields::TotalCountField
  field :totalPageCount, Shared::Fields::TotalPageCountField
end
```
Custom Field:
```ruby
# define total count custom field to be re-used
# on all custom connections
Shared::Fields::TotalCountField = GraphQL::Field.define do
  name 'TotalCountField'
  type !types.Int
  description 'Get total count of objects (nodes) on a connection, after filtering'

  # - `obj` is the Connection
  # - `obj.nodes` is the collection of objects
  resolve ->(obj, _args, _ctx) { obj.nodes&.count }
end
```

I was hoping that I could instead use an interface for these fields on each connection, but trying the following did not work:
Connection:
```ruby
# Define Graphql Connection for Users
RBAC::Connections::UsersConnection = RBAC::Types::UserType.define_connection do
  name 'UsersConnection'
  implements ::Shared::Interfaces::ConnectionCountsInterface
end
```
Interface:
```ruby
module Shared
  module Interfaces
    # interface that defines fields for total_count and total_page_count
    # on any connections that implement it
    module ConnectionCountsInterface
      include ::Types::BaseInterface

      description 'Interface to calculate total_count and total_page_count on connections'
      field :totalCount, Integer, 'Total # of items in return list', null: false

      def totalCount
        object.nodes&.count
      end
    end
  end
end
```
... with the error: 
`F, [2018-07-03T11:04:51.448973 #55609] FATAL -- : GraphQL::Schema::InvalidTypeError (Field User.created_users's return type is invalid: UsersConnection failed to implement some interfaces: "totalCount" is required by ConnectionCountsInterface but not implemented by UsersConnection, "totalPageCount" is required by ConnectionCountsInterface but not implemented by UsersConnection):`

Is there any v1.8 way to implement an interface on a custom defined connection?
(also perhaps I'm not correct in thinking that using define_connection is still the only way of creating custom connections in 1.8??  It would be great if there were a class based way of defining connections and edges).

**Comment by rmosolgo** [comment]
How about trying (or taking inspiration from) the new `Types::Relay` classes, for example: 

https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/types/relay/base_connection.rb

Personally I'd recommend using that one as a base class for your app (and `base_edge.rb`) and working from there. 

The specific bug you found is that fields implemented with methods can't be inherited by `.define`-based types, I couldn't figure out a way to solve that!

**Comment by clader** [comment]
This is perfect! Apologies, I didn’t realize that you added the relay classes in 1.8.4. I will definitely  go that route. 

One last related question before closing this out:  if I implemented connections based on these relay classes, do you see any way to allow for dynamic edge types to be “passed in “ when declaring the connection field?  

To be more specific, if I have connectiontype A and for some fields I want to implement it as a plain connection with a standard edge, but sometimes I want to implement it for a field, but with a custom edgetype (say edgetype “X”).

Right now I have to create two versions of the connection (“A” and “B”).  One that uses the standard edge and another that uses the custom edgetype. 

It would be really helpful to just have the one connection implementation that would use the standard edge if none were supplied, but then use a custome edge type  passed in the field declaration somehow. 

Thanks!

**Comment by rmosolgo** [comment]
Sorry, just saw the follow up question here. 

> two versions of the connection 

That's the correct solution. The same connection type can't have two different edge types, there have to be two types one way or another, since the edge type is a field return type! Although it's wordier to prepare those types ahead of time, it might make the code easier to understand. And if you prefer a metaprogramming approach, I bet you could _build_ one 😎
