### ISSUE TITLE
Missing example on how to **use** interface

### ISSUE THREAD

**Issue by rafaelsales** [rmosolgo/graphql-ruby#1645]
This is found in the [Objects](http://graphql-ruby.org/type_definitions/objects.html#implementing-interfaces) section, but it just makes harder having to reach another section to see how to use interfaces. I'd add an example on how to use the interface in both links below:

https://github.com/rmosolgo/graphql-ruby/blob/master/guides/type_definitions/interfaces.md
http://graphql-ruby.org/type_definitions/interfaces.html

If you agree with that, I can add submit a PR. Thanks!

**Comment by rmosolgo** [comment]
Yes, that sounds like a nice improvement, a PR would be great!

**Comment by rmosolgo** [comment]
Clarified in 90474a965, thanks for reporting the issue!
