### ISSUE TITLE
[ Feature Request ] - Warn users if field is a reserved Ruby or Rails keyword

### ISSUE THREAD

**Issue by jacobsmith** [rmosolgo/graphql-ruby#1648]
Hello,

I write this issue with one part pride for finally figuring out what was causing my mutation to fail in its return type, one part shame at how long it took to figure it out :smile:

Part of the domain of my app relies on displaying (or not displaying) something in the UI. I added a `display` column to the database and everything seemed to work okay testing via the console, but I kept getting a `cannot return null` error because the `display` property was marked as non-null, even though I was returning `{ display: true }` from the mutation to try and get the simplest test case possible.

Eventually, I looked up a list of reserved words in Rails and, lo and behold, `display` is one of those keywords. I'm not sure what it does or how it works, but somehow it was causing a conflict - as soon as I changed the property to `display_two` as a sanity check, everything worked just fine.

My proposal is that for any `field` name, we offer a warning if the field name is a reserved word in Ruby or Rails. We could use an opt-in mechanism for Rails because I know the library can be used outside of the Rails ecosystem (though I imagine a large portion of the user base is Rails-based). We wouldn't stop the user (as there may be legitimate use cases) but a warning along the lines of `Please be aware that field "display" is a reserved word in Rails. It may cause issues with field resolution. Please rename the field or whitelist this field name in the graphql initializers file.`

Feedback welcome, just trying to save someone else from a 3 hour debugging session for what comes down to poor naming choices :smile:

**Comment by rmosolgo** [comment]
A similar issue is with conflicts with GraphQL-Ruby itself, for example #1320

**Comment by jacobsmith** [comment]
@rmosolgo do you think the project is at a point where a PR for something like this would be welcome? I know there were a few different approaches addressed in #1320 but it went quiet a few months ago. I'll gladly work on a PR if you think something like this could bring value.
