### ISSUE TITLE
Guide: Testing

### ISSUE THREAD

**Issue by penkz** [rmosolgo/graphql-ruby#1651]
Hello, I'm following the guide on testing, but it seems that RSpec is not finding the Schema to execute it.
I get an NameError `uninitialized constant MySchema`

Is there any configuration that needs to be done before running GraphQL on RSpec?

Thanks!

**Comment by penkz** [comment]
Well I'm not sure what happened but it is working now... I think maybe it's because Guard was somehow not loading the schema file, but it seems that everything is working fine now after a reboot.

**Comment by chrise86** [comment]
@penkz can you shed any more light on this please? Also facing this issue and restarting spring does not fix.

**Comment by penkz** [comment]
Hi, @chrise86, are you using guard? I'm not sure if I can be of much help here, but if I remember correctly I tried restarting spring, and then after that I did reboot the system, and somehow the error went I way... I suspect Guard was keeping a cache but I'm not entirely sure...
