### ISSUE TITLE
(1.8) Pass initialization parameters to resolver that implements GraphQL::Schema::Resolver?

### ISSUE THREAD

**Issue by clader** [rmosolgo/graphql-ruby#1655]
With a GraphQL::Function I am able to pass parameters to it via it's initialization method:

An Object...
```ruby
class UserType < ::Types::BaseObject
  graphql_name 'UserType'
  description 'A User'
  field foo:, function: Functions::FooFunction.new('alpha', 'beta')
end
```
The Function...
```ruby
class Functions::FooFunction < GraphQL::Function
  type types.String
  description  'Foo-ing'
  def initialize (arg1, arg2)
    @my_arg1 = arg1
    @my_arg2 = arg2
  end
  def call(obj, args, ctx)
    #  (... do stuff with @my_arg1 and @myarg2)
  end
end
```

... But I'm hoping to migrate all my functions to Resolvers using my base resolver (which is based on GraphQL::Schema::Resolver) and am quickly finding there doesn't seem to be any way to pass custom parameters to the resolver class.  Ex:
BaseResolver:
```ruby
module Types
  class BaseResolver < GraphQL::Schema::Resolver
  end
end
```
An Object...
```ruby
class UserType < ::Types::BaseObject
  graphql_name 'UserType'
  description 'A User'
  field foo:, resolver: Resolvers::FooResolver # <--How to pass non-argument parameters here?
end
```
The Resolver:
```ruby
class Resolvers::FooResolvers < ::Types::BaseResolver
  type String, null: true
  description  'Foo-ing'
  def resolve
    # how can I get passed parameters here?
  end
end
```

I understand that I can declare arguments in the resolver and reference those in the resolve function, but those are for arguments passed from the API, and in this situation I want to "hard code" these parameters in the field declaration and not make them inputs to the field.

I was hoping that extras: could be used to add just any old custom parameters to reference in the resolve method, but that doesn't seem to be the case.

The initialization parameters on GraphQL::Function are really helpful to have "configurable" resolve methods that do different things when you pass them different parameters, and it would be great to have something similar with Resolver classes.

Apologies if this is just me being a ruby n00b and the answer is obvious.
Thanks!

**Comment by rmosolgo** [comment]
Yep, that's one of the differences between `Schema::Resolver` and `Function`. I can think of two options: 

- Instead of providing configurations on-the-fly, create subclasses of the base resolver in their own files, and put the configurations there. Then, in the `field(...)` definition, reference that subclass. 
- Create a wrapper around `Class.new` which accepts some configurations, then applies them to a subclass of the base resolver. For example: 

  ```ruby
  class ConfigurableResolver < GraphQL::Schema::Resolver 
    # Create a subclass of this resolver, applying configurations based on `options` 
    def self.with_configuration(options) 
      Class.new(self) do # create a subclass 
        options.each do |key, value| 
          public_send(key, value) # turn the given options into class method calls 
        end 
      end 
    end 
  end 
  ```
  
  Then it could be used as: 

  ```ruby 
  field(..., resolver: ConfigurableResolver.with_configurations(extras: [...])
  ```

   For real usage, you might: 
  
   - Add `.with_configuration` to some _real_ resolver that actually does something (the one above doesn't have `#resolve` method)
  - Implement more class methods on the base class to accept those configurations

In GitHub, we chose to put resolver classes in their own files. It makes it easier to find the code, anyway. 

Hope that helps!

**Comment by clader** [comment]
Thanks for the response.  The 2nd option you gave (wrap Class.new) seems like the best option, but I'm still not clear on how I can reference those option fields in the resolver exactly.

Could you provide some more details?

Given: 
```ruby
class ConfigurableResolver < GraphQL::Schema::Resolver 
  # Create a subclass of this resolver, applying configurations based on `options` 
  def self.with_configuration(options) 
    Class.new(self) do # create a subclass 
      options.each do |key, value| 
        public_send(key, value) # turn the given options into class method calls 
      end 
    end 
  end

  def resolve()
    # how to access the 'options' here?  
  end
end
```

Also when implementing a field to use the ConfigurableResovler what do I put in the "extras: [...]" parameter exactly?  Just an array of values or should it be a hash of some sort?

In my example of wanting to pass two strings 'alpha' 'beta' would it look like the below:
```ruby
field(..., resolver: ConfigurableResolver.with_configurations(extras: ['alpha', 'beta'])
```
... or is that way off?

**Comment by rmosolgo** [comment]
First, sorry for the confusion, but `extras` has special meaning for fields, see: http://graphql-ruby.org/type_definitions/objects.html#extra-field-metadata . Let's use `options` instead for example. 

What you could do in your resolver class is: 

- define a class method which will receive the given `options` 
- inside `#resolve`, access the values via `self.class.options` 

For example: 

```ruby 
class ConfigurableResolver < GraphQL::Schema::Resolver 
  def self.with_configurations(configurations) 
    # as shown above 
  end 

  # This method will be called with the value of `options: ...` 
  def self.options(new_options = nil) 
    if new_options 
      @options = new_options 
    else 
      @options 
    end 
  end 

  def resolve()
    self.class.options 
    # => returns what was passed as `options: ...`, or `nil` if nothing was passed 
  end
end
```

It gets a little trickier if you want to _inherit_ options, I recommend looking at `GraphQL::Schema::HasArguments#arguments` in this library if you want an example of merging hashes along an inheritance chain. 

Does that help?

**Comment by clader** [comment]
Yes! This was exactly what I was looking for and works perfectly.

Thanks so much for the quick response.

**Comment by vfonic** [comment]
@rmosolgo that's a neat trick!

Here's how I achieved similar (each class has _class_ instance variable):

```rb
class ConfigurableResolver < GraphQL::Schema::Resolver 
  def self.with_configurations(options) 
    Class.new(self) do # create a subclass
      class << self
        attr_accessor :list
        attr_accessor :of
        attr_accessor :available
        attr_accessor :configuration
        attr_accessor :variables
      end
      options.each do |key, value|
        public_send("#{key}=", value) # setter has to be key=
      end
    end
  end

  # no longer needed
  # def self.options(new_options = nil)
    # if new_options
    #   @options = new_options
    # else
    #   @options
    # end
  # end

  def resolve()
    self.class.list
    self.class.of
    self.class.available
    self.class.configuration
    self.class.variables
  end
end
```
