### ISSUE TITLE
Subscriptions(ActionCable): Does the initial query require a channel in the context?

### ISSUE THREAD

**Issue by blevine** [rmosolgo/graphql-ruby#1668]
When executing a subscription, I'm getting:

`undefined method `stream_from' for nil:NilClass`

from `ActionCableSubscriptions#write_subscription ` on the call to `channel.stream_from` because a channel was not added to the query context.  Do I need to instantiate a channel and add it to the query context for the initial subscription query?

**Comment by rmosolgo** [comment]
It expected that the initial subscription request will come via ActionCable, and the context will include `channel: self`, see the example here: 

http://graphql-ruby.org/api-doc/1.8.5/GraphQL/Subscriptions/ActionCableSubscriptions

In fact, the JavaScript client in this repo _should_ send the initial request that way, does it work for you?

**Comment by blevine** [comment]
Ah, I see.  I had just implemented subscriptions on the server side and I wanted to do a quick test of the initial request using Graphiql. It didn't occur to me that the initial request would be via websockets (ActionCable) rather than HTTP. I'll work up a test using your client library which I should have looked at for hints about this in the first place.  Thanks for the response!
