### ISSUE TITLE
Request: Change the license of graphql-ruby-client, LGPL 3.0, to others

### ISSUE THREAD

**Issue by gfx** [rmosolgo/graphql-ruby#1670]
Hi, thanks to the great framework that is inevitable for our business.

I am investigation subscriptions with graphql-ruby, and have found that the `graphql-ruby-client` is licensed under LGPL 3.0: https://github.com/rmosolgo/graphql-ruby/blob/master/javascript_client/package.json

Is it intentionally? If not, I'd like for you to take other licenses that do not require publish application source codes, like ISC or MIT. LGPL 3.0 is  difficult to use in frontend / mobile applications.

**Comment by thefliik** [comment]
Considering you can [purchase a commercial license](https://github.com/rmosolgo/graphql-ruby/blob/master/javascript_client/LICENSE.md), I'm confident in saying this is intentional.

**Comment by rmosolgo** [comment]
Yes, @thefliik is right: when I decided to try graphql-pro, I started following in the footsteps of Sidekiq, which was licensed with LGPL v3, except for sidekiq-pro customers. It was too late to relicense the Ruby gem. (Maybe it's possible, but I assume it would require coordinating acceptance from contributors. Instead, I added `CONTRIBUTING.md`.) But, I started later work under that license. So, if you'd like to customize graphql-ruby-client under a more permissive license, please consider signing your company up for graphql-pro! If that's not appropriate for some reason, please let me know.
