### ISSUE TITLE
[1.8] Interfaces and module inheritance

### ISSUE THREAD

**Issue by swalkinshaw** [rmosolgo/graphql-ruby#1674]
We have a bunch of modules that were included in our versions of `Interface` and `Object`. All of these modules are "concerns" (`extend ActiveSupport::Concern`). It seems that it's not possible to include (in any way) a module that's a concern and actually have the methods included.

Note: while this (potential) issue was discovered from our unusual use case of moving from a class-based Interface to the new Module-based one, this might apply to anyone in the future.

Here's a branch with some new tests to see examples: https://github.com/rmosolgo/graphql-ruby/compare/master...swalkinshaw:interface-module-includes?expand=1

Is this expected? Is it a bug? Or should this limitation be documented at least? My solution is to make the modules "plain" again (no need for the concern/`ClassMethods` since that's all that's in them).

Here's what *does* work:

```ruby
module DefaultFieldDescription
  def field(*args, **kwargs)
    kwargs[:description] += ' plus DefaultFieldDescription'
    super
  end
end

module BaseInterface
  include GraphQL::Schema::Interface

  definition_methods do
    include DefaultFieldDescription

    def field(*args, **kwargs)
      kwargs[:description] = 'from interface'
      super
    end
  end
end
```

Is including a module within the `definition_methods` block the best/intended solution?

**Comment by rmosolgo** [comment]
> a module within the `definition_methods`

If you want to add class methods that are passed to all descendants of that module (interfaces or objects), then that's the place to do it. 

If you want to add instance methods for resolving fields (or helper methods to be called while resolving fields), then adding instance methods to the interface module is the way to go.

As for class methods in the interface, I can't remember the details exactly, but I had a hard time making those methods inherited from interface to interface, something about how module class methods are inherited by default in Ruby didn't work for that. That's why `definition_methods do` was added, so that they're put in a _different_ module that can be added down the line. 

If you want to explore some improvements there, I'd be happy to see the API simplified! But I'm still too tired from the initial battle with module inheritance to take it up myself right now 😆

**Comment by swalkinshaw** [comment]
I'm already tired from my brief exploration into this 😰 

I'll likely just convert our modules away from being concerns for now (probably better anyway). It is pretty common in Rails apps for people to default to concerns for their modules which won't work right now. So it might be worthwhile to explore that at some point, or document the limitation. I'll add it to my list!

**Comment by swalkinshaw** [comment]
I ran into another issue related to this:

```ruby
module DefaultFieldDescription
  def field(*args, **kwargs)
    kwargs[:description] += ' plus DefaultFieldDescription'
    super
  end
end

module AnotherDefaultFieldDescription
  def field(*args, **kwargs)
      kwargs[:description] += ' plus AnotherDefaultFieldDescription'
    super
  end
end

module BaseInterface
  include GraphQL::Schema::Interface

  definition_methods do
    include DefaultFieldDescription
  end
end

module SuperBaseInterface
  include BaseInterface

  definition_methods do
    include AnotherDefaultFieldDescription
  end
end

module NodeInterface
  include SuperBaseInterface

  field :id, ID, null: false, description: 'node'
end
```

```ruby
NodeInterface.fields['id'].description
=> "node plus DefaultFieldDescription plus AnotherDefaultFieldDescription"
```

I would have expected `AnotherDefaultFieldDescription` to come first. What's also interesting is the inheritance chain:

```ruby
constants: DefinitionMethods
GraphQL::Schema::Member::CachedGraphQLDefinition#methods: graphql_definition
GraphQL::Relay::TypeExtensions#methods: connection_type  define_connection  define_edge  edge_type
GraphQL::Schema::Member::BaseDSLMethods#methods: authorized?  description  graphql_name  introspection  mutation  name  overridden_graphql_name  unwrap
GraphQL::Schema::Member::TypeSystemHelpers#methods: list?  non_null?  to_list_type  to_non_null_type  to_type_signature
GraphQL::Schema::Member::HasFields#methods: add_field  field_class  fields  global_id_field  inherited  own_fields
GraphQL::Schema::Member::AcceptsDefinition::AcceptsDefinitionDefinitionMethods#methods: accepts_definition  accepts_definition_methods  own_accepts_definition_methods
GraphQL::Schema::Interface::DefinitionMethods#methods: accessible?  definition_methods  included  kind  orphan_types  visible?
GraphQL::Schema::Member::AcceptsDefinition::ToGraphQLExtension#methods: to_graphql
DefaultFieldDescription#methods: field
instance variables: @_default_resolve  @_definition_methods  @own_fields  @own_interfaces
```

`DefaultFieldDescription` shows up while `AnotherDefaultFieldDescription` does not.

**Comment by swalkinshaw** [comment]
https://github.com/rmosolgo/graphql-ruby/pull/1686 is a PR to fix the core issue I was running into it as described above.
