### ISSUE TITLE
[1.8] Default value not provided for omitted optional input object with arguments with defaults

### ISSUE THREAD

**Issue by Envek** [rmosolgo/graphql-ruby#1678]
#### Summary
If query argument is _optional_ complex input object with arguments with default values then these default values are not provided in this input object is omitted from the query arguments

#### Example
Given the following query definition:
```rb
class Types::QueryType < GraphQL::Schema::Object
  field :products, Types::Product.connection_type, null: false do
    argument :filters, Types::Product::Filter, required: false, default_value: {}
  end
  def products(filters:)
    # apply filters
  end
end
class Types::Product::Filter < GraphQL::Schema::InputObject
  graphql_name "ProductFilter"
  argument :archived,            Boolean, required: false, default_value: false
  argument :status,              String,  required: false
end
```

Generated docs says that `filters` have default values:

```graphql
products(
  first: Int
  after: String
  last: Int
  before: String
  filters: ProductFilter = {archived: false}
): ProductConnection!
```

If executing a query without `filters` parameter then in method empty hash is passed (**not** as expected):
```graphql
{
  products(first: 2) {
    edges { node { id } }
  }
}
```
```rb
def products(filter:) # filter: {} - plain hash as provided in default_value
```

If executing a query with empty `filters` parameter then in method passed a hash with default parameter set (as expected):
```graphql
{
  products(first: 2, filters: {}) {
    edges { node { id } }
  }
}
```

```rb
def products(filter:) # filter: {:archived=>false} - instance of Types::Product::Filter
```

#### Environment 

gem graphql 1.8.5
gem graphql-batch 0.3.9
ruby 2.5.1
rails 5.2.0

#### Notes

I'm naturally don't want to duplicate default values from `Types::Product::Filter` in the `default_value` option in `filters` argument definition.

**Comment by rmosolgo** [comment]
🤔  Hmm, thanks for the detailed report. How misleading that the generated schema suggests _one thing_ while the runtime behavior shows _something else_! 

I wonder what the spec has to say on this, which one is right...

**Comment by N0xFF** [comment]
It actual problem? I can't reproduce in 1.9.9 with Interpreter and AST.

Executing without `filter` argument returns a filter object as expected.

**Comment by Envek** [comment]
Yes, with [Interpreter](https://graphql-ruby.org/queries/interpreter.html) enabled it works like it should. :heavy_check_mark: @N0xFF, thank you for pointing it out!
With disabled interpreter this issue is still there, though.

The only weird case left is that you still should specify any default value for `filters` argument (like empty hash) or Ruby will throw exception about not provided keyword argument.

**Comment by cantino-automated-sys-account** [comment]
We just ran into this as well in our app that doesn't yet use Interpreter. Defaults are not applied for the sub-object when the field using it has a `default_value` of `{}` (or when it has no `default_value` at all). Is there some way we could set the parent field's `default_value` to something like `Types::Product::Filter.defaults`? I.e.g, is there some method to generate the default output of an object?

**Comment by cantino** [comment]
We just ran into this as well in our app that doesn't yet use Interpreter. Defaults are not applied for the sub-object when the field using it has a default_value of {} (or when it has no default_value at all). Is there some way we could set the parent field's default_value to something like Types::Product::Filter.defaults? I.e.g, is there some method to generate the default output of an object?

**Comment by rmosolgo** [comment]
I'm sorry, I don't really have the bandwidth to support the old runtime these days. If you're a GraphQL-Pro customer, shoot me an email and I'll keep digging, or if anyone wants to submit a PR, I'd be happy to review and help as I can.
