### ISSUE TITLE
Non-Empty Sec-WebSocket-Protocol error

### ISSUE THREAD

**Issue by jacobsmith** [rmosolgo/graphql-ruby#1689]
Hello,

I'm trying to connect React Apollo Subscriptions with graphql-ruby. I've followed along with the examples provided in the documentation, but I continue to get the following error message:

```
WebSocket connection to 'ws://localhost:3001/websocket' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received
```

`Sec-WebSocket-Protocol` is `graphql-ws` - Rails responds with a 101 properly, but then chrome throws an error about the protocol not being the same. I'm not sure if this is a bug, if there is a config option, or if it's just something wrong I'm doing in trying to get these things to work together. Any advice would be appreciated (:

**Comment by rmosolgo** [comment]
Hi! I can't really say much about graphql-ws. I  think it's supposed to play nice with a certain JavaScript server library, right? 

For GraphQL-Ruby, I can help with: 

- ActionCable: http://graphql-ruby.org/subscriptions/action_cable_implementation.html
- Pusher: http://graphql-ruby.org/subscriptions/pusher_implementation.html

But I'm afraid I don't know much about `graphql-ws`! Sorry I can't help more.

**Comment by rmosolgo** [comment]
(It seems like you need a Ruby server equivalent of the JS server that's meant to be used with `graphql-ws`, but I haven't seen that implemented before and I'm not sure how to go about implementing it.)

**Comment by zaguiini** [comment]
I'm getting the same error, but I'm using Apollo client v2. Do you have some suggestion @rmosolgo?
