### ISSUE TITLE
Use ActiveSupport's camelize when available?

### ISSUE THREAD

**Issue by phyllisstein** [rmosolgo/graphql-ruby#1692]
👋 Hi there! I was wondering if you'd be amenable to a pull request that checked to see if strings to be camelized `respond_to?(:camelize)` before falling back on the custom logic at <https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/member/build_type.rb#L118-L126>. The reason for proposing this is that I use `ActiveSupport::Inflector` acronyms to keep my frontend and backend in stylistic sync (e.g., I prefer `authorID` to `authorId`, so I've set up `ID` as an acronym), but the current auto-camelization logic doesn't take that into account. Establishing a tacit dependency on ActiveSupport feels a little oogie, but not as oogie as grepping all my JS apps for `ID` and `SRC` and `URL`. 😬

Let me know if you have any thoughts! Thanks a bunch for considering it.

**Comment by rmosolgo** [comment]
I think hooking into people's AS::Inflector is a great idea! Totally agree with your rationalle. 

How about this for an implementation?

- Add a method, `GraphQL::Schema.camelize(string)` whose implementation calls out to `BuiltType`, the method that you linked 
- Create a new module, something like `GraphQL::Schema::CamelizeWithActiveSupport`, which, when mixed in, overrides that method to use `String#camelize` from active support 
- Document the new mixin, so that people can opt into it 

I think that will make it easy to find and will avoid any compatibility issues when changing the default behavior. What do you think?

**Comment by phyllisstein** [comment]
Thanks for suggesting a more sophisticated implementation! I very much like the approach from a cleanliness standpoint, but it seems a little difficult to work as a consumer of the package. Would the developer not have to open up `GraphQL::Schema` again in order to include the new module? Or am I thinking about it all wrong?

I took a crack at it here, if it's more useful to read code: <https://github.com/phyllisstein/graphql-ruby/commit/ae449164a3fb7e51349d4afcb6100617430e0901>.

**Comment by rmosolgo** [comment]
Instead of opening up the base `GraphQL::Schema` class, folks could customize their subclass of `GraphQL::Schema`. (Since 1.8, the recommended way to make a schema is by extending the base class, see for example http://graphql-ruby.org/schema/definition.html.) 

So, you could have: 

```ruby 
class MySchema < GraphQL::Schema
  include ActiveSupportStrings
end 
```

That code looks good! I guess it just needs some tests. One way to test would be to override those methods on a certain string, for example: 

```ruby
example_str = "abcd" 
def example_str.camelize(arg)
  # return something to show it was called 
  "called with #{arg.inspect}"
end 

camelized_str = schema_with_active_support.camelize(example_str)
assert_equal "called with :lower", camelized_str
```

That would show that `.camelize(str)` is calling `str.camelize(:lower)` under the hood. I suppose something similar could work for `.underscore`.

**Comment by phyllisstein** [comment]
Thanks for taking a look! I'll work on adding tests.

Maybe I'm misunderstanding something about Ruby mixins and inheritance, but wouldn't including `ActiveSupportStrings` there just affect `MySchema`, rather than `GraphQL::Schema`?

**Comment by thefliik** [comment]
Correct, but in this scenario, the entire schema includes `MySchema` in the ancestor chain. Hence the entire schema includes `ActiveSupportStrings` (if someone wants it to)

**Comment by phyllisstein** [comment]
Thanks, I think I follow. Unfortunately it seems like making the overridden methods available in the subclassed schema doesn't affect how fields are defined. With the new module mixed in, calling `Schema.camelize` from within (for example) a `GraphQL::Schema::Object` subclass invokes the ActiveSupport method, but the GraphQL schema still doesn't include the inflected fields:

```
[1] pry(main)> 'provider_id'.camelize(:lower)
=> "providerID"
[2] pry(main)> GraphQL::Schema::Member::BuildType.camelize('provider_id')
=> "providerId"
[3] pry(main)> cd Types::Profile
[4] pry(Types::Profile):1> Schema.camelize('provider_id')
=> "providerID"
[5] pry(Types::Profile):1> fields['providerID']
=> nil
[6] pry(Types::Profile):1> fields['providerId']
=> #<GraphQL::Schema::Field:0x00000001128748b8
 @complexity=1,
 @connection=nil,
 @deprecation_reason=nil,
 @description=nil,
 @extras=[],
 @field=nil,
 @function=nil,
 @introspection=false,
 @max_page_size=nil,
 @method_str="provider_id",
 @method_sym=:provider_id,
 @name="providerId",
 @own_arguments={},
 @owner=Types::Profile,
 @resolve=nil,
 @resolver_class=nil,
 @return_type_expr=String,
 @return_type_null=true,
 @subscription_scope=nil>
```

On the other hand, if I open `GraphQL::Schema` and `include` the AS module there, it works as expected.

Forgive me for needing so much hand-holding on such a simple feature! My Ruby's clearly gone to pot, been spending too much time with JavaScript.

**Comment by rmosolgo** [comment]
Oh, I see what you mean, 

> hand-holding

Not at all, _I'm_ the one who got it wrong :P 

🤔 Hmm, I wonder what's a better way to support opting into this feature but with a nice API 🤔

**Comment by phyllisstein** [comment]
I mean, without pretending for a second this isn't a super ugly hack, the mixed-in module could always call `base.superclass`: <https://github.com/phyllisstein/graphql-ruby/commit/e13078f17e9377a4a75f5c77ae167a5c28b83bed>.

**Comment by phyllisstein** [comment]
Sad trombone, calling `base.superclass` worked in development but not in production.

**Comment by zhangyonguu** [comment]
How about this:

```
GraphQL::Schema::Member::BuildType.class_eval do
  module_function

  def camelize(string)
    return string unless string.include?("_")
    splited = string.split('_')
    camelized = ActiveSupport::Inflector.inflections(:en) do |inflect|
      inflect.acronym('URL')
      splited.map {|w| ActiveSupport::Inflector.camelize(w)}
    end
    camelized = camelized.join
    camelized[0] = camelized[0].downcase
    if (match_data = string.match(/\A(_+)/))
      camelized = "#{match_data[0]}#{camelized}"
    end
    camelized
  end
end
```

I override the private module function `camelize` of `GraphQL::Schema::Member::BuildType`, and put it in my initializer, and it works.

**Comment by rmosolgo** [comment]
I'm totally open to an improvement here, but I don't have plans to work on it myself. Feel free to open a PR if you want to move it forward!

**Comment by prikha** [comment]
To solve the problem above we can do the following

```rb
module GraphQLStringUtils
    def camelize(string)
        ::ActiveSupport::Inflector.camelize(string, false)
    end

    def underscore(string)
        ::ActiveSupport::Inflector.underscore(string)
    end

    def constantize(string)
        ::ActiveSupport::Inflector.constantize(string)
    end
end

GraphQL::Schema::Member::BuildType.singleton_class.prepend(GraphQLStringUtils)
```

It changes the private API though. So it'd be nice to make the private API use some publicly configurable behavior.

What if we wrap the code above into some configurable module?

The interface may look something like this:

```rb
GraphQL::Schema::StringUtils.config do
    def camelize(string)
        ::ActiveSupport::Inflector.camelize(string, false)
    end

    def underscore(string)
        ::ActiveSupport::Inflector.underscore(string)
    end

    def constantize(string)
        ::ActiveSupport::Inflector.constantize(string)
    end
end
```

```rb
module GraphQL::Schema::StringUtils
    def self.setup(module=nil, &block)
        singleton_class.prepend(module || Module.new(&block)
    end

    module_function

    def camelize(_); ... end
    def constantize(_); ... end
    def underscore(_); ... end
end
```

And we can call string functions from this module inside `GraphQL::Schema::Member::BuildType`


@rmosolgo WDYT? I have drafted a PR for that: https://github.com/rmosolgo/graphql-ruby/pull/3380
