### ISSUE TITLE
Async event trigger

### ISSUE THREAD

**Issue by jacob-s-son** [rmosolgo/graphql-ruby#1695]
We are working on realtime portion of our app and so far we were able to wire everything together just fine (we are using pro version together with pusher). The only problem I have is `trigger` being synchronous, which is not great, because it's an HTTP call to Pusher API with varied latency.

What would be the suggested way to make it async? So far my naive attempt was to simply push it to Sidekiq, but I am not sure what is the best way to carry over the query context. I can see that the `Event` object itself receives it as an argument in the initializer, but it's implicitly fetched from the query in the `trigger` method itself.

Suggestions?

**Comment by rmosolgo** [comment]
Hi, great question! I think using Sidekiq is a great idea. I think you could make a job for each kind of trigger, for example: 

```ruby 
class PublishCommentWasAddedWorker 
  include Sidekiq::Worker
  def perform(comment_id)
    comment = Comment.find(comment_id) 
    post_id = comment.post_id
    # update any GraphQL clients who are subscribed 
    MySchema.subscriptions.trigger("commentWasAdded", { post_id: post_id }, comment) 
  end
end
```

Then whenever an event happens, you can enqueue a job like that, for example: 

```ruby 
class Comment < ActiveRecord::Base 
  # Use after_commit so that the database transaction will be finished 
  # (otherwise, the Sidekiq worker might not be able to find the newly-created comment)
  after_commit :publish_comment_was_added, on: :create 

  def publish_comment_was_added 
    # enqueue the job to update GraphQL subscribers 
    PublishCommentWasAddedWorker.perform_async(self.id) 
  end 
end 
```

What do you think of that? 

> carry over the query context 

I think this is a bit different story, you can see how the Pusher implementation persists `context` here: 

http://graphql-ruby.org/subscriptions/pusher_implementation.html#serializing-context

You can see that it uses the `Subscriptions::Serialize` module by default, the source for that is here: https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/subscriptions/serialize.rb

Does that help?

**Comment by jacob-s-son** [comment]
Thanks for the quick reply.

I am very well acquainted with **`Subscriptions::Serialize`**, because we had a PORO object in our context and I had to make it work with `globalid`.

I am currently aiming to introduce something more general - basically I have extended my `TypeObject` with a method that has the same signature as the original `trigger` and I am simply forwarding all the arguments to the Sidekiq job.

The part I would love to see some advice for - how do you suggest restoring `context` object inside the Sidekiq job? As I understand it, when `trigger`is called, a subscription gets written to redis storage and then read, when execute is called (BTW, this part seems a bit weird, what's the point writing it to redis, if the event is executed as soon as stored in redis? seems like wasted CPU cycles). Thus, when this call is moved to Sidekiq job, `trigger` is called with context being non-existent, right? So, how do you fix that?

**Comment by rmosolgo** [comment]
I'm not sure why we need `context` inside the Sidekiq job. Can you share an example call to `.trigger`? Maybe that will give some clarity about how to background it.

**Comment by jacob-s-son** [comment]
Thanks for the reply. Yes, I think this will do the job. Feel free top close it.

**Comment by rmosolgo** [comment]
Great, let me know if you get any trouble!

**Comment by github0013** [comment]
related to my topic https://github.com/rmosolgo/graphql-ruby/issues/1799
I also thought it was a good place to call a background job (ex: sidekiq) in SubscriptionType methods, but I get queues on initial and trigger calls, instead of just on initial (which makes sense).

I created a repo branch for this
https://github.com/github0013/graphql_subscription_actioncable/tree/622cbd4df472e4ebc9086e66c65575727a6a3faf

This job queue gets twice.
https://github.com/github0013/graphql_subscription_actioncable/blob/622cbd4df472e4ebc9086e66c65575727a6a3faf/app/graphql/types/subscription_type.rb#L8

```rb
git clone ..
cd ..
bundle
rails s
```

```bash
$ open http://localhost:3000/sidekiq # monitor queues.  you will see 2 queues stack up after the trigger call
```

```bash
$ open http://localhost:3000 # this access creates a TestWorker queue
```


```rb
rails c
> GraphqlSubscriptionActioncableSchema.subscriptions.trigger('testSub', {}, Time.now.to_i)
# this trigger will also creates a TestWorker queue
```

Am I doing it wrong or any thoughts?

**Comment by github0013** [comment]
In my case, there is no mutations related to my subscription.  It's more like status update pushes (no database C/U/D).

1. client calls the subscription
1. subscription kicks the job
1. job checks updates and triggers subscriptions until an event ends

So it's kinda important that the SubscriptionType method gets called only once at initial call (as document says so).

`This will be called on the initial request`
![graphql_-_subscription_type-2](https://user-images.githubusercontent.com/809378/44440219-22df3900-a602-11e8-9425-2381c0076870.png)
