### ISSUE TITLE
Cannot create more than one subscription on same channel at a time using pusher

### ISSUE THREAD

**Issue by mikefaraponov** [rmosolgo/graphql-ruby#1703]
https://github.com/rmosolgo/graphql-ruby/blob/32c3d1b683d547c30786b6808104ea7a4802d878/javascript_client/subscriptions/PusherSubscriber.js#L35

**Comment by rmosolgo** [comment]
Hi! I'm happy to help out on this issue but I need a little more information. It sounds like you found a limitation of the Pusher subscription implementation, is that right? Could you add some information to describe:

- What behavior do you consider to be a limitation? 
- Why do you think it's a limitation? What are the downsides of this behavior? 
- How would you _like_ the feature to work? Is there an implementation _without_ these downsides?

If you get a chance to add that descriptive info, please reopen this issue!
