### ISSUE TITLE
Don't camelize field names by default

### ISSUE THREAD

**Issue by sdemjanenko** [rmosolgo/graphql-ruby#1707]
When migrating from v1.7 syntax to v1.8 class syntax I discovered that the `name` attribute on an instance of `Field` was being camelized. This is incredibly unpredictable and will probably bite many developers. It certainly bit me. This library should not modify the name of the field that a developer passes in.

An example of the issue:
```
field :current_user, Type::User

def current_user
  ...
end
```
The auto-camelizing behavior this would mean that a developer now has to change the method name to be `currentUser`. Ideally they would update the `field` definition as well, but it would be a valid config for the configuration to have a mismatch.

**Comment by thefliik** [comment]
[The Graphql convention](http://facebook.github.io/graphql/June2018/#sec-Language.Fields) is for field names to be in camelCase. So I, for one, am very much in favor of keeping the default as auto-camelizing field names -> to allow ruby conventions to co-exist with graphql conventions. This being said, in general, I would not expect
```
field :current_user, Type::User

def current_user
  ...
end
```
to throw an error.

**Comment by rmosolgo** [comment]
Sorry it came as a surprise! You can disable this new behavior by using default `camelize: false` in your field base class, see: 

http://graphql-ruby.org/type_definitions/objects.html#field-parameter-default-values

**Comment by rmosolgo** [comment]
Yes, feel free to improve the migration docs as you see fit! Here's the source: 

https://github.com/rmosolgo/graphql-ruby/blob/master/guides/schema/class_based_api.md

**Comment by sdemjanenko** [comment]
I've also found that a camelCase `argument` gets turned into an underscored keyword argument to the `resolve` function in a mutation which also seems unexpected. Is there a  good way to override this behavior?

**Comment by rmosolgo** [comment]
No, there's not a good way to override underscored arguments as method arguments. Happy to help brainstorm a solution if you'd like to share your usecase!
