### ISSUE TITLE
GraphQL::Schema::NonNull#to_type_signature -> #graphql_name ? 

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#1711]
Most types respond to `#graphql_name`, but not the new list and non-null wrappers. Maybe their `#to_type_signature` methods should be aliased, just to give us fewer names to remember.

**Comment by RobertWSaunders** [comment]
Are you saying to make `alias_method :graphql_name, :to_type_signature`? or rename `to_type_signature` to 'graphql_name` and `alias_method :to_type_signature, :graphql_name`? 

IMO I think the wrapping types should both implement `graphql_name` and `description` but return nil for both of them. By specification wrapping types have a name and description but they are nullable fields.

What are your thoughts on this? 

I have a PR that I'm working on that could easily add this change.

**Comment by rmosolgo** [comment]
:+1: to rename and implement `description` like you said, I think I wrote some code using `:to_type_signature` ,but it's probably better to do a breaking change now rather than leave it around.

**Comment by rmosolgo** [comment]
I'm working through a lot of this over in #2363 , if anyone finds a particular problem, please open an issue!
