### ISSUE TITLE
"Field is missing required arguments: input" in mutation

### ISSUE THREAD

**Issue by kaiomagalhaes** [rmosolgo/graphql-ruby#1719]
Hey everyone, I'm facing an issue while trying to add a mutation route.  I tried to find solutions in all the places available and couldn't see anyone facing it or a way to solve it.

Graphql-ruby version: raphql (1.8.5)

the response:

```
{
  "errors": [
    {
      "message": "Field 'addLesson' is missing required arguments: input",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "fields": [
        "mutation",
        "addLesson"
      ]
    },
    {
      "message": "Field 'addLesson' doesn't accept argument 'description'",
      "locations": [
        {
          "line": 3,
          "column": 3
        }
      ],
      "fields": [
        "mutation",
        "addLesson",
        "description"
      ]
    },
    {
      "message": "Field 'description' doesn't exist on type 'AddLessonPayload'",
      "locations": [
        {
          "line": 5,
          "column": 3
        }
      ],
      "fields": [
        "mutation",
        "addLesson",
        "description"
      ]
    }
  ]
}
```

Lesson Type:

```
# app/graphql/types/lesson_type.rb
class Types::LessonType < Types::BaseObject
  field :id, ID, null: false
  field :description, String, null: false
end
```

Mutation Type:
```
# app/graphql/types/mutation_type.rb
class Types::MutationType < Types::BaseObject
  field :add_lesson, mutation: Mutations::AddLesson
end
```

Mutation Add Lesson
```
# app/graphql/mutations/add_lesson.rb
class Mutations::AddLesson < Mutations::BaseMutation
  argument :description, String, required: true

  field :lesson, Types::LessonType, null: false

  def resolve(description:)
    Lesson.create!(description: description)
  end
end
```

**Comment by rmosolgo** [comment]
Does your `BaseMutation` extend `RelayClassicMutation`? If so, then all its arguments belong to a nested `input:` object. For example, try this: 

```graphql
mutation AddLesson {
  addLesson(description: "My new lesson") {
    lesson {
      description 
    }
  }
}
```

That's a convention from the first version of Relay (although I can't find the old server specs for it anymore). 

If you don't want to use that convention, use `GraphQL::Schema::Mutation` instead. 

Hope that helps! Please reopen this if it doesn't.

**Comment by kaiomagalhaes** [comment]
Yes, my BaseMutation extend RelayClassicMutation. I tried
```
mutation AddLesson {
  addLesson(description: "My new lesson") {
    lesson {
      description 
    }
  }
}
```

And it is giving the same error. Could you point me what is the newest way to create a mutation and which Class should I extend in my BaseMutation in order to achieve it?

**Comment by rmosolgo** [comment]
🤦‍♂️  I'm sorry, there was a typo in my previous comment. I edited it: 

![image](https://user-images.githubusercontent.com/2231765/43401716-e4648cf0-93de-11e8-85e0-434793454917.png)

Could you try again with `input: { ... }`?

**Comment by rmosolgo** [comment]
> newest way to create a mutation and which Class

I think you're doing it!

**Comment by kaiomagalhaes** [comment]
It works, thanks!
