### ISSUE TITLE
Calling `to_graphql` on a wrapping type does not return a legacy types

### ISSUE THREAD

**Issue by RobertWSaunders** [rmosolgo/graphql-ruby#1745]
## Problem

Calling `to_graphql` on a wrapping type (ex.`GraphQL::Schema::List` or `GraphQL::Schema::NonNull`) returns the new class based type instead of the legacy types. I see an issue in this because `to_graphql` is all other cases (maybe...?) returns the legacy types. For anyone relying on `to_graphql` to return the legacy types this would cause issues. 

The the root of this issue is found here:
https://github.com/rmosolgo/graphql-ruby/blob/be5439d76b4ee2176253eaab9fd329ebd09f5a7a/lib/graphql/schema/member/type_system_helpers.rb#L8-L15

## Proposed Solution

Return the legacy types when calling `to_graphql` on a wrapping type and if required make a new method that will provide the class based types?

## Action Item

Wanted to discuss the issue here before making a PR as the issue might have been intentional.

Thoughts?

cc @swalkinshaw

**Comment by rmosolgo** [comment]
:+1: I think it was an oversight on my part, just something I didn't need myself so forgot to add.

**Comment by RobertWSaunders** [comment]
Sounds good, I'll make a PR for it and we can discuss the change there!

**Comment by rmosolgo** [comment]
Closing as stale, if someone else runs into trouble here, please feel free to open a new issue!
