### ISSUE TITLE
actioncablesubscriptions documentation update

### ISSUE THREAD

**Issue by modosc** [rmosolgo/graphql-ruby#1746]
http://graphql-ruby.org/api-doc/1.8.6/GraphQL/Subscriptions/ActionCableSubscriptions suggests creating a payload like:
```
    payload = {
      result: result.subscription? ? {data: nil} : result.to_h,
      more: result.subscription?,
    }
```

but that results in an error. the correct payload is mentioned [here](https://github.com/rmosolgo/graphql-ruby/issues/1038#issuecomment-337427215):
```
    payload = {
      result: result.subscription? ? nil : result.to_h,
      more: result.subscription?,
    }

```

**Comment by rmosolgo** [comment]
Thanks for sharing the correction, would you mind open a PR to fix it? You can find the source for that documentation here: 

https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/subscriptions/action_cable_subscriptions.rb#L42

And if you don't want to clone the repo, you could probably use the Web UI's edit button: 

![image](https://user-images.githubusercontent.com/2231765/43909833-43b915bc-9bc9-11e8-9251-68ad3cbf6bbb.png)

**Comment by modosc** [comment]
hah, didn't realize. pr created, thanks!
