### ISSUE TITLE
Question: how to output input objects back to client?

### ISSUE THREAD

**Issue by Envek** [rmosolgo/graphql-ruby#1749]
**Rationale**: I've some query which accepts a complex `filters` object as an argument and returns a filtered collection. The problem is that filters are complex and have some defaults. Because of this, I want to return currently applied filters to the client to let it know what is going on.

For example, when client issues following query:
```graphql
query {
  products(first:1, filters: {managed: false}) {
    nodes { id title archived managed }
    filters { archived managed }
  }
}
```

It may get following result:

```json
{
  "data": {
    "products": {
      "nodes": [{ "id": "1", "title": "…",  "archived": false, "managed": false }],
      "filters": { "archived": false, "managed": false }
    }
  }
}
```

But for now I need to duplicate filters' fields in InputObject and type to achieve that:

```ruby
class Types::QueryType < Types::BaseObject
  field :products, Types::Product::Connection, null: false do
    # TODO: https://github.com/rmosolgo/graphql-ruby/issues/1678
    argument :filters, Types::Product::FilterInput, required: false, default_value: { archived: false }
  end
  def products(filters:)
    ::Product.filter(filters.to_h).tap do |result|
      result.instance_variable_set(:@filters, filters.to_h) # This is dirty hack, don't pay attention
    end
  end
end

class Types::Product::Connection < GraphQL::Types::Relay::BaseConnection
  graphql_name "ProductConnection"
  field :filters, Types::Product::Filter, null: false

  def filters
    object.nodes.instance_variable_get(:@filters) # This is dirty hack, don't pay attention
  end
end

class Types::Product::FilterInput < Types::BaseInputObject
  graphql_name "ProductFilterInput"

  argument :archived,            Boolean, required: false, default_value: false
  argument :status,              String,  required: false
  argument :managed,             Boolean, required: false
  # and more…
end

# FIXME: Somehow DRY it as it is just duplicates
class Types::Product::Filter < Types::BaseObject
  graphql_name "ProductFilter"

  field :archived,            Boolean, null: true
  field :status,              String,  null: true
  field :managed,             Boolean, null: true
  # and more…
end
```

**Question**: does it makes sense to make `argument` to always create `field` under the hood so `InputObjects` can be output back to the client? Is there a better way to achieve this without declaring dozens of duplicating attribute-field pairs?

**Comment by rmosolgo** [comment]
How about adding a method to your `BaseInputObject` which generates an object type? For example: 

```ruby 
class Types::BaseInputObject < GraphQL::Schema::InputObject 
  def self.to_object_type 
    input_object_class = self # work around `instance_eval` in Class.new 
    Class.new(Types::BaseObject) do 
      # derive a name:
      graphql_name(input_object_class.sub("Input", "")
      # derive the fields:
      input_object_class.arguments.each do |name, arg_defn| 
        field(name, arg_defn.type, null: arg_defn.null)
      end 
    end 
  end 
end 
```

Then you could create types like: 

```ruby 
Types::Product::Filter = Types::ProductFilterInput.to_object_type 
```

What do you think of that approach? 


The only problem is that `GraphQL::Schema::Argument`'s API is not very complete yet, it probably needs some `attr_reader`s added, you can see the source here: 

https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/argument.rb

So, if you give it a try, you can monkey-patch some attr_readers to the base class ... then feel free to upstream them if you want to open a PR 😊

**Comment by Envek** [comment]
Thank you very much! Will give it a try and think how it can be enhanced and contributed back!

**Comment by rmosolgo** [comment]
Good luck , look forward to hearing back!
