### ISSUE TITLE
Relay Connection authorization integration

### ISSUE THREAD

**Issue by swalkinshaw** [rmosolgo/graphql-ruby#1752]
Visibility and accessibility both have integration with Relay connections here:

https://github.com/rmosolgo/graphql-ruby/blob/be5439d76b4ee2176253eaab9fd329ebd09f5a7a/lib/graphql/schema.rb#L971-L973

However this doesn't apply to authorization since `authorized?` is called from field instrumentation and not via `call_on_type_class` on the schema.

Is this something that should be taken care of automatically? I'd also assume `relay_node_type` should be the source of `authorized?` for the connection and edge.

**Comment by rmosolgo** [comment]
I wasn't really sure how to make it work. For example, let's say you have a connection which wraps a AR::Relation of `Item`s. Should it go to `Item.authorized?` ? That means that `.authorized?` should be prepared for _both_ an `Item` and an AR::Relation. 

A related feature was added for something _like_ this: #1723

**Comment by swalkinshaw** [comment]
We've always delegated to node type with implementations like this:

```ruby
# Edge
def authorized?(edge, ctx)
  node_type.authorized?(edge.node, ctx)
end

# Connection
def authorized?(connection, ctx)
  edge_authorizations = connection.edges.map { |edge| edge_type.authorized?(edge, ctx) }
  Promise.all(edge_authorizations).then(&:all?)
end
```

**Comment by rmosolgo** [comment]
This is _kinda_ done here: 

https://github.com/rmosolgo/graphql-ruby/blob/90474a965062820673c0c596ec0e55236b83dfd2/lib/graphql/types/relay/base_connection.rb#L79-L89

https://github.com/rmosolgo/graphql-ruby/blob/90474a965062820673c0c596ec0e55236b83dfd2/lib/graphql/types/relay/base_edge.rb#L41-L51

It might be improved by ahead-of-time filtering of nodes, as shown above, but right now that filtering is delayed until the node itself is queried.
