### ISSUE TITLE
Improve documentation of GraphQL arguments to Ruby keyword arguments

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#1761]
Because Ruby kwargs are relatively new, people aren't too familiar with it. We should have some documentation to clarify: 

- GraphQL args are camelized before calling methods 
- `**inputs` and `**arguments` can always be specified as specific, individual keyword arguments
- Ruby argument default values are required when GraphQL arguments are optional 
- If a GraphQL default value is present and a query is sent without a value for that argument, the default value will be passed as the Ruby keyword argument.

**Comment by davidrf** [comment]
Hi @rmosolgo I'd love to contribute to the project and put up a PR for this. Would it just be updating the [Fields > Arguments](http://graphql-ruby.org/fields/arguments.html) page? Or are there other pages which also mention kwargs?

**Comment by rmosolgo** [comment]
Hey, cool!

Hmm, interesting, those "Fields" guides actually use the old API, they should be replaced altogether. 

I think a good place to start would be to add a _new_ `arguments.md` guide in the `type_definitions/` folder. It could include: 

- How to add arguments to a field 
- How arguments are injected to field methods 
- Working with keyword arguments (the bullets mentioned above)

That would give us a place to add more argument documentation for the new API if we ever need it, and we could remove that old guide. 

Are you interested in adding that new page? I'd be happy to help out along the way if you want to give it a shot.

**Comment by davidrf** [comment]
Yes definitely interested in adding that new page. I'll go ahead and give it a try and we can go from there

**Comment by rmosolgo** [comment]
Fixed by #1864 🎉
