### ISSUE TITLE
Authorize operations by name at one point

### ISSUE THREAD

**Issue by nleo** [rmosolgo/graphql-ruby#1780]
I want to authorize operations by their names at one point and do it like this: 

```ruby
class Types::BaseObject < GraphQL::Schema::Object

  def initialize *options
    operation_name = options[1].query.selected_operation.selections.first.name
    @current_user = options[1][:current_user]
    @current_permission = Permission.new(@current_user)
    unless @current_permission.allow? operation_name
      raise GraphQL::ExecutionError.new('Not authorized ', options: { type: :not_authorized })
    end
    super *options
  end

end


class Permission
  def initialize(user)
    # unauthorized users can get auth token
    allow :getAuthToken
    if user
      # authorized users can create records
      allow :createLegalPhysicalEntity
      allow_all if user.admin?
    end
  end

  def allow?(action, resource = nil)
    allowed = @allow_all || @allowed_actions[action.to_s]
    allowed && (allowed == true || allowed.call(resource))
  end

  def allow_all
    @allow_all = true
  end

  def allow(actions, &block)
    @allowed_actions ||= {}
    Array(actions).each do |action|
      @allowed_actions[action.to_s] = block || true
    end
  end

end
```

Is there a better way or better place to check `current_permission.allow?` and `raise GraphQL::ExecutionError.new('Not authorized ')` if check was unsuccessfull?

Also I have an issue. Then I call `raise GraphQL::ExecutionError` in `Types::BaseObject#initialize` it don't handled by GraphQL-ruby like if it called in field resolver, just like regular 500 error with backtrace.

**Comment by rmosolgo** [comment]
Hi, I think another way you could run this check is with Query instrumentation: 

http://graphql-ruby.org/queries/instrumentation.html

Inside `before_query`, you could initialize `current_permission` (or get it from `context[:current_permission]` and check it. 

Regarding the other issue, please open another issue with the relevant Ruby code and full stack trace if you'd like to debug it!
