### ISSUE TITLE
Parser allows omitted argument value

### ISSUE THREAD

**Issue by cjoudrey** [rmosolgo/graphql-ruby#1782]
While investigating #1772, I noticed the parser currently allows argument values to be omitted.

```
{
  something(id:)
}
```

```
<GraphQL::Language::Nodes::Field @line=2, @col=3,
  @name="something",
  @arguments=[
    #<GraphQL::Language::Nodes::Argument:0x00007feed777b820 @line=2, @col=13
      @name="id",
      @value=nil>
  ]
]>
```

In the reference implementation, this results in a parse error:

```javascript
require("graphql").parse("{ something(id:) }"));

# GraphQLError: Syntax Error: Unexpected )
```

I've tried digging into this issue, but cannot figure out why this is happening. As far as I can tell the [`argument:` parser rule](https://github.com/rmosolgo/graphql-ruby/blob/34c0bdbf14ed7bd6dafc321c9acd06abb7e79098/lib/graphql/language/parser.y#L175-L176) shouldn't allow this.

**Comment by daemonsy** [comment]
Resolved by https://github.com/rmosolgo/graphql-ruby/pull/2344
