### ISSUE TITLE
Infinite resolution with instrumenters inspecting results when an exception not inheriting from StandardError 

### ISSUE THREAD

**Issue by tylerhou** [rmosolgo/graphql-ruby#1803]
https://github.com/rmosolgo/graphql-ruby/issues/1072 was a previous version of this bug.

If an exception not inheriting from `StandardError` is thrown in a GraphQL mutation, then the [rescue block added to fix #1072](https://github.com/rmosolgo/graphql-ruby/blob/0b40b5b5766508180611aa14ad1f504e1fc3e00d/lib/graphql/execution/multiplex.rb#L94) will not catch that exception. If such an exception is always thrown, the query will never be marked as resolved, and the schema resolver will never terminate. This could happen in development if you make a syntax error inside a mutation, for example.

I've been able to reproduce this bug on 1.7.9. I haven't attempted to reproduce on later releases (1.8.x/master), but I'm pretty certain that this bug exists.

Proposed fix is to change [line 94](https://github.com/rmosolgo/graphql-ruby/blob/0b40b5b5766508180611aa14ad1f504e1fc3e00d/lib/graphql/execution/multiplex.rb#L94) to rescue from `Exception` instead. Although it is generally frowned upon to rescue from `Exception`, in this case I think it is okay since we reraise.

**Comment by rmosolgo** [comment]
:+1: to your proposed fix!

**Comment by tylerhou** [comment]
https://github.com/rmosolgo/graphql-ruby/pull/1804

**Comment by tylerhou** [comment]
Closed by #1804.
