### ISSUE TITLE
Access query arguments from `authorized?` on a Query field [1.8.5]

### ISSUE THREAD

**Issue by Batou99** [rmosolgo/graphql-ruby#1805]
I'm trying to access query arguments from a field `authorized?` method but I just can't figure out how to access the query arguments.

This is what I currently have:

```
class Query < Types::BaseObject
  field :some_field do
    argument :some_arg, String, required: false
    
    def authorized?(object, context)
      # How can I access here the query arg values?
    end
  end
  def some_field
    # Only reach here if field is authorized?
  end
end
```

I want to authorize the field here before it reaches the instance method (resolver).
Any hints?

Apologies in advance if this is not the right place to ask for this.

**Comment by rmosolgo** [comment]
You can't :'( But it's a reasonable request, maybe we can add it.

**Comment by clader** [comment]
Would love this as I've been trying to do the same thing and trying to get to the query arguments surreptitiously through context.irep_node, but no such luck.

**Comment by clader** [comment]
Even more useful for my use case would be to allow access to ‘irep_node’ and ‘path’ in  ‘authorized?’ and ‘self.scope_items’ they same way that you can make them accessible in resolvers. 

I had built my own authorization framework within my resolvers, but it would be much cleaner to use this framework. I would just need have access to all the same query fields that I have in the resolver.

**Comment by rmosolgo** [comment]
Thanks for sharing that request, it makes a lot of sense. I'll try to find a way if I get the chance.

**Comment by rmosolgo** [comment]
Hi, I'm not planning to add arguments to `.authorized?`. In my experience, this kind of context-specific info ends up being a foot-gun, because in unexpected contexts, authorization doesn't behave properly. 

Instead, if incoming arguments are relevant to application behavior, perhaps they could be embedded _inside_ the application objects, so that the objects themselves become aware of that context.
