### ISSUE TITLE
Acesssing parent objects to show/hide fields

### ISSUE THREAD

**Issue by jacob-s-son** [rmosolgo/graphql-ruby#1809]
The docs suggest using `#visible?` method to define, if the field is visible to client, but the context passed to that method is not enough to deduce the access. 

Concrete example: a competition is organized and every submission has a rank that consists of several fields. The organizer, when setting up the competition, can decide which rank fields are allowed to be seen by participants. Browser queries our backend this way:
```
query {
  submission(id: $id) {
    #..other fields
    competition {
      #....
    }
    rank {
      place_in_rank,
      is_tied,
    }
  }
}
```

Our goal is to make sure that if `competition` object `is_allowed_to_see_ranks` and/or `is_allowed_to_see_ties` is set to false, the query that is listed above takes out `place_in_rank` and `is_tied` accordingly.

Currently, as rank object is calculated value object not an entity, we simply remove the fields that are not allowed when calculating, but we would prefer to do this on authorization, not data calculation layer.
We iterated over several options, trying to understand how this can be solved:
1) when query is being executed additional information is injected into queries context
2) accessing parent through context (does not work with current versions AFAIK: https://github.com/rmosolgo/graphql-ruby/issues/881#issuecomment-383117637)
3) use method definitions, where `parent` is still accessible in a context. There are several issues with this approach:
  - parent tree is different, because rank is accessible two ways - through submission, and through subscription
  - at that point it's not possible cleanly remove the fields from the response, but they would be nullified

Another problem that might plague the mentioned options - N+1, how to keep the instance of the auction for every field authorization without re-fetching it ? One of the options I thought about is to define some sort of implicitly passed arguments that are mandatory for rank object.

Any thoughts?

**Comment by rmosolgo** [comment]
I have a few thoughts. First, on this: 

> if `competition` object `is_allowed_to_see_ranks`

Do you mean checking the value of a Ruby method, eg `competition.is_allowed_to_see_ranks?` ? If so, then `#visible?` won't work for you. `#visible?` is called before any data is fetched (before the query is evaluated at all), so you don't have access to any runtime values.

Instead, you could use `#authorized?(parent, ctx)`, which will be called with the parent of the `rank` (which looks like the `submission`). So for example you could have: 

```ruby 
class Types::RankField < Types::BaseField
  def authorized?(submission, ctx)
    if name == "place_in_rank"
      # Hide this field unless this check returns true:
      submission.competition.is_allowed_to_see_ranks?
    elsif name == "is_tied" 
      # similar check here 
    else 
      # OTher fields are always visible: 
      true 
    end 
  end 
end 
```

Then use that custom field for the Rank type: 

```ruby 
class Types::Rank 
  # implements permission checks for these fields: 
  field_class Types::RankField 
end 
```

Then, some fields will be rejected when those Ruby checks return false. 

Is that what you're hoping to do here?

**Comment by jacob-s-son** [comment]
This sounds as a viable approach, will reiterate with responsible dev team and see how it works. Thank you for your response.

**Comment by rmosolgo** [comment]
I hope you found something that works here!
