### ISSUE TITLE
Schema Stitching

### ISSUE THREAD

**Issue by audiolion** [rmosolgo/graphql-ruby#1812]
Hey 👋 

Does the graphql-ruby gem provide support for schema stitching?

**Comment by rmosolgo** [comment]
No, but I recommend: https://github.com/d12/graphql-remote_loader

It's a nice approach to consuming one GraphQL API from within another.

**Comment by gmac** [comment]
There’s now a Ruby implementation of schema stitching at https://github.com/gmac/graphql-stitching-ruby.
