### ISSUE TITLE
Support for inline enum definitions for an argument

### ISSUE THREAD

**Issue by megalithic** [rmosolgo/graphql-ruby#1814]
There doesn't seem to be a way to define inline enums for an argument (especially when the enum is only of a specific concern) - something like:

```rb
argument :only, enum [:active, :completed], required: false
```

If this is possible, is there something specific that I'm missing, to invoke this?

**Comment by rmosolgo** [comment]
It's not supported by the gem but if you want it, you can build it with a class method for example: 

```ruby 
def self.enum(ruby_values) 
  Class.new(Types::BaseEnum) do 
    graphql_name "TODO: somehow provide a name here" 
    ruby_values.each do |v| 
      value(v.to_s.upcase, value: v)
    end 
  end 
end 
```

The only catch is that you also have to provide a name, probably: 

```ruby
def self.enum(type_name, ruby_values)
```

And use `type_name` for the `graphql_name` configuration. 

Feel free to give that a try and report back if you have any trouble!

**Comment by fameoflight** [comment]
Here is nice little shortcut if anyone is look at this in future 

```ruby 

# frozen_string_literal: true

module Types
  module Concerns
    module EnumHelpers
      extend ActiveSupport::Concern

      class_methods do
        def enum_field(name, null: false, values: nil)
          gql_name = "#{graphql_name}#{name.to_s.classify}Enum"

          ruby_values = values || model.send(name).values

          enum_class = Class.new(Types::Base::BaseEnum) do
            graphql_name gql_name

            ruby_values.each do |v|
              value(v.to_s.upcase, value: v)
            end
          end

          field name, enum_class, null: null
        end
      end
    end
  end
end
```

Now include this in your base object, and you have enum_field 

```ruby 
include Types::Concerns::EnumHelpers
```

**Comment by Deekor** [comment]
> Here is nice little shortcut if anyone is look at this in future
> 
> ```ruby
> # frozen_string_literal: true
> 
> module Types
>   module Concerns
>     module EnumHelpers
>       extend ActiveSupport::Concern
> 
>       class_methods do
>         def enum_field(name, null: false, values: nil)
>           gql_name = "#{graphql_name}#{name.to_s.classify}Enum"
> 
>           ruby_values = values || model.send(name).values
> 
>           enum_class = Class.new(Types::Base::BaseEnum) do
>             graphql_name gql_name
> 
>             ruby_values.each do |v|
>               value(v.to_s.upcase, value: v)
>             end
>           end
> 
>           field name, enum_class, null: null
>         end
>       end
>     end
>   end
> end
> ```
> 
> Now include this in your base object, and you have enum_field
> 
> ```ruby
> include Types::Concerns::EnumHelpers
> ```

Thank you!
