### ISSUE TITLE
Eager loading and `ast_node` / `irep_node`

### ISSUE THREAD

**Issue by cheerfulstoic** [rmosolgo/graphql-ruby#1818]
`graphql` gem version 1.8.8
Rails 5.1.6
Ruby 2.5.1

I'm trying to allow for eager loading in queries as discussed in various places (such as #58) and the solution proposed is to use `ast_node` and/or `irep_node` to reflect on the children.  When I try to do this, however, I'm given nodes which reflect the top-level of the schema (`query` / `Query`) and not the place where my field is defined.  Is this a bug, or maybe I'm misunderstanding something?  I don't think I should have to parse down the try to try to figure out where I am currently...

My query:

```graphql
query { equipment { brands { id name products { id name } } } }
```

```ruby
module Types
  class EquipmentType < Types::BaseObject
    # Namespace for equipment types

    field :brands, [Types::Equipment::BrandType], null: false, description: 'Brands which sell products in our gear section' do·
      argument :per_page, Integer, default_value: 20, required: false, prepare: -> (per_page, ctx) { [per_page, 30].min }
    end

    def brands(per_page:)
      ::Equipment::Brand.all.limit(per_page).to_a
    end
  end
end
```

One other thing to note is that the `EquipmentType` there to provide a namespace.  Since we have many different types of modules we have different namespaces to group by functionality (such as "Equipment").  Inside of the `QueryType` the `equipment` field has a method defined which simply returns `{}` which, as an object, is ignored.  I don't think that's affecting things as the `ast_node` / `irep_node` that I'm getting is still giving me the "query" level, but I wanted to mention it in case you know of a better approach.

**Comment by cheerfulstoic** [comment]
Also, it's inside the `brands` method in `EquipmentType` that I'm trying to call `context.ast_node` and `context.irep_node`

**Comment by rmosolgo** [comment]
In the class-based API, `context` is the _query-level_ context, not the field-level context. This was changed to support better performance in future version.  In the class-based API, use `extras: [...]` to request metadata in your resolver, see: http://graphql-ruby.org/type_definitions/objects.html#extra-field-metadata

**Comment by cheerfulstoic** [comment]
Perfect, thanks!  I'm glad it was an easy answer!
