### ISSUE TITLE
Splatting Query::Arguments and Query::Context

### ISSUE THREAD

**Issue by arempe93** [rmosolgo/graphql-ruby#1821]
I recently discovered you cannot simply `**args` in resolvers, because `args` is a duck-typed hash, but is really an instance of `GraphQL::Query::Arguments`

Splatting it breaks the "duck-typing" because Ruby looks for `to_hash`, which is unimplemented

I thought "all this class needs is an alias `to_hash` to `to_h` and it will be a perfectly transparent hash duck". Then I remembered that double-splat needs symbol keys to work and `to_h` returns a string-keyed Hash...

Do the maintainers have an opinion on how to have double-splat work with `Arguments`?

The options could be:
1. Don't
2. Change `to_h` to return a symbol-keyed Hash
3. Add a custom `to_hash` instead of an alias that returns a symbol-keyed Hash

**Comment by rmosolgo** [comment]
Can you share an example resolver where you experience this issue? 

Are you using the new class-based API? If not, I recommend that you try to adopt it. In the new API, arguments are passed around using plain ol' symbol-keyed hashes, so you can splat them as you please :)

**Comment by ojab** [comment]
I've also encoutered this issue [here](https://github.com/can-i-has-a-job-plz/graphql-remote_fields/blob/master/lib/graphql/remote_fields.rb#L43) (overriding field initialize to add custom arguments). What's the concensus on how it should be solved? I'd like to make a PR to fix it.
