### ISSUE TITLE
Input Objects respond to `fields` but not `fields?` is false

### ISSUE THREAD

**Issue by eapache** [rmosolgo/graphql-ruby#1823]
This is probably just a weird quirk, but I noticed the following when `type` is an input object:

```
(byebug) type.kind.fields?
false
(byebug) type.fields
{ ... all the input fields on the input type ... }
```

@rmosolgo should the INPUT_OBJECT kind have `fields?` as true? Or is that intentional since input arguments aren't technically fields? In which case maybe the type itself shouldn't respond to fields and should only respond to `arguments`?

**Comment by rmosolgo** [comment]
Weird, I would not expect `type.fields` to return anything! I wonder why that's there. 

> only respond to `arguments`

yeah, that seems right to me!

**Comment by eapache** [comment]
🤦‍♂️ our fault, we had a `alias_method :fields, :arguments` left over from the migration to 1.8 in our input object base class.

**Comment by eapache** [comment]
However (after digging a little more), input objects should probably have `composite?` true when they currently have it false, no?

**Comment by rmosolgo** [comment]
I don't really remember what `composite?` is about, feel free to update this issue or open another one if you want to look into it
