### ISSUE TITLE
Uninitialized Constant ID

### ISSUE THREAD

**Issue by NicholasLYang** [rmosolgo/graphql-ruby#1828]
I'm attempting to write a small helper that adds fields to QueryType for a given model:

```
def queryable_on(model, query_field, query_type)
  QueryType.class_eval do
    field model, Module.const_get("#{model}Type"), null: true do
      description "Query #{model} by ID"
      argument :id, query_type, required: true
      resolve -> (obj, args, ctx) { PostsResolver.show(id) }
    end
  end
end
```

Usage:
```
class Post < Sequel::Model
  queryable_on Post, :id, ID
end
```

However, I'm getting an error that Post::ID doesn't exist. I've required GraphQL so that's pretty confusing. Do you have any suggestions on how to fix this?

Thanks,
Nicholas

**Comment by rmosolgo** [comment]
Hey! If you want to bring those constants into scope, you can include [this module](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/member/graphql_type_names.rb#L14): 

```ruby 
include GraphQL::Schema::Member::GraphQLTypeNames 
```

Alternatively, you can just use strings to name those types, for example: 

```ruby 
queryable_on Post, :id, "ID"
```

Let me know if those don't work!

**Comment by NicholasLYang** [comment]
Thanks!
