### ISSUE TITLE
"NoMethodError: undefined method `instrumenter' for Skylight:Module"

### ISSUE THREAD

**Issue by AndrewRayCode** [rmosolgo/graphql-ruby#1833]
We're starting to see this error in our logs for GraphQL queries:

```
File "/usr/local/rvm/gems/ruby-2.5.1@bundler/gems/graphql-pro-4dedb4349ae2/lib/graphql/pro/monitoring/skylight_platform.rb" line 32 in before_query
...
File "./app/controllers/graphql_controller.rb", line 43 in execute_query
```

We see this stack trace when performing normal GraphQL queries.

The line it's coming from in the graphql-pro gem is:
```ruby
inst = Skylight.instrumenter
```

To get around a critical bug in the Skylight gem (long story), we started running our Rails application with this configuration flag set:
```
SKYLIGHT_LAZY_START=false
```
This flag is as internal API setting for Skylight, but we worked with their support team to identify Skylight's critical bug, and they signed off that this flag setting should address our issue.

The docs (https://www.rubydoc.info/gems/skylight/0.8.1/Skylight/Instrumenter) for the Skylight::Instrumenter class say it's a private API, so it's unclear to me if this is a problem with _our_ use of the internal API, or _your_ use of the internal API (or both, or neither).

Are you able to reproduce this, setting the above env var, with the below versions?

Skylight gem version 2.0.2
Graphql pro version 1.7.8

**Comment by rmosolgo** [comment]
🤔  Interesting! In the [2.0.2 docs](https://www.rubydoc.info/gems/skylight/2.0.2/Skylight/Instrumenter), Skylight::Instrumenter is no longer marked as private. 

About a year ago, I replaced graphql-pro's monitoring with an open-source "tracing" system that covers more parts of the GraphQL query lifecycle, it has support for Skylight: http://graphql-ruby.org/queries/tracing.html#skylight

It only calls `Skylight.instrumenter` if a certain configuration is set: 

https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/tracing/skylight_tracing.rb#L30-L33

Do you want to give that new tracer a try?

**Comment by AndrewRayCode** [comment]
Nevermind, this was a red herring, we had an engineer yoloing our test env and downgrading the skylight gem. I assumed this error was from the most recent version of the gem (it's not)

**Comment by rmosolgo** [comment]
😅  Glad you got to the bottom of it!
