### ISSUE TITLE
Input objects value for `composite?`

### ISSUE THREAD

**Issue by eapache** [rmosolgo/graphql-ruby#1834]
https://github.com/rmosolgo/graphql-ruby/issues/1823#issuecomment-418383043

It's not super-clear to me what `composite?` was intended to be either, but:
- the comment in the code is: https://github.com/rmosolgo/graphql-ruby/blob/07abd0f616c2403db51a90cbacc0e5be109e0ff1/lib/graphql/type_kinds.rb#L30
- intuitively I would expect it to be true for any type that has sub-things

Right now it's inferred from either `fields? || abstract?` which covers objects, interfaces, and unions. However, input objects are also arguably composite (they compose multiple other inputs/args) and currently result in `composite?` being false.

I would propose adding input objects to return `composite?` as true, though I'm not sure how; `|| input?` would be over-broad since it also includes scalars and enums.

**Comment by rmosolgo** [comment]
It looks like that typekind check comes from the spec: https://graphql.github.io/graphql-spec/June2018/#sec-Fragments-On-Composite-Types

> Fragments On Composite Types
> ... 
> The target type of fragment must have kind UNION, INTERFACE, or OBJECT.

I supposed I grabbed the term from there. I'd rather keep the method as-is, but feel free to improve the docstring if you like!
