### ISSUE TITLE
Some best practices, code organization advices

### ISSUE THREAD

**Issue by nleo** [rmosolgo/graphql-ruby#1836]
I'm looking for something like http://docs.ansible.com/ansible/latest/playbooks_best_practices.html but for graphql-ruby

For example I have a lot standard CRUD actions

![CRUD](https://i.imgur.com/17ZS3uW.png)
![CRUD](https://i.imgur.com/GI7XTd4.png)

Now I'm putting them mostly into two files `Types::Mutation` & `Types::Query` and `mutation.rb` now have almost 200 lines.

Ideally I want organization like standard rails controller. Put in one file actions (create update delete show index) for one resource.

**Comment by bidluo** [comment]
If you’re still looking for a solution, I’ve taken inspiration from howtographql and organised my folder structure first by type (ie mutation/query/base) and then by feature (user/some domain model/etc).

Inside the feature packages are each of my CRUD methods, you can of course organise this like a normal rails controller in one file but I opted to keep it seperate so it’s more solid. These classes are also namespaced.
![IMG_0012](https://user-images.githubusercontent.com/1412440/59362575-0837a580-8d77-11e9-9e02-f56a140b5aeb.jpeg)

Then your schema kinda acts like routes.rb 

![IMG_0013](https://user-images.githubusercontent.com/1412440/59362909-a88dca00-8d77-11e9-80db-5c0d4611b8cf.jpeg)

![IMG_0014](https://user-images.githubusercontent.com/1412440/59362918-ab88ba80-8d77-11e9-81ed-5cb7d764e834.jpeg)

I’m trying to find a way to clean this last part up and only need one file, but it works for now even though it’s a bit more verbose.

Personally this approach is preferable and more maintainable than a massive file as it also makes testing more clear. Open to any improvements though

**Comment by daemonsy** [comment]
Hi, I'm closing this issue because it seems like there isn't any more activity. 

A big `query_type.rb` file is a problem I have too, but there are some teammates who appreciate everything in one place too. 

Anyhow, feel free to reopen this issue or discuss this more in https://graphql.slack.com #ruby.

**Comment by daemonsy** [comment]
Refer to https://github.com/rmosolgo/graphql-ruby/issues/1825
