### ISSUE TITLE
Unknown loads in input object

### ISSUE THREAD

**Issue by mcdave029** [rmosolgo/graphql-ruby#1838]
Hi!, is `loads:` in argument are only available from [mutation classes](http://graphql-ruby.org/mutations/mutation_classes.html)?. because right now I'm using it in [input objects](http://graphql-ruby.org/type_definitions/input_objects.html) and I'm getting an error of `unknown keyword: loads`. Thanks for the help. 😄

**Comment by lemuelbarango** [comment]
Hey, @rmosolgo any work/progress on this? I don't mind working on a PR for this. I have just encountered a similar situation at work, trying to use the `loads` argument in the input object type.

I assume that the work involved here would be to reimplement the `loads` logic in the resolvers class for input objects - 

https://github.com/rmosolgo/graphql-ruby/blob/3642ee92b722bccf49562fef9608eaab4e339711/lib/graphql/schema/resolver.rb#L329-L370

Let me know if you had better ideas. 😄 

### Thanks for the efforts put into building this gem!! 🙌

**Comment by lemuelbarango** [comment]
Sweet! I create a PR https://github.com/rmosolgo/graphql-ruby/pull/2080

I welcome any early feedback on the initial refactor... Thanks

**Comment by duderamos** [comment]
Hey @lemuelbarango, what happened to close the PR?

**Comment by lemuelbarango** [comment]
@duderamos I've reopened the PR. was a mistake

**Comment by duderamos** [comment]
No worries @lemuelbarango. I don't know if it helps, but I tested a scenario on my end and using `prepare` param seems enough:

https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/argument.rb#L31

In my case, I have something like this:

```ruby
module Foo
    class UpdateBarAttributes < Types::BaseInputObject
      argument :my_object_id, ID, required: true, prepare: :load_object
  end
end
```

```ruby
module Types
  class BaseInputObject < GraphQL::Schema::InputObject
    def load_object(encoded_id)
      MySchema.object_from_id(encoded_id)
    end
  end
end
```

So I just need to append `prepare: :load_object` to my `ID` arguments.

**Comment by lemuelbarango** [comment]
@duderamos Yeah, I didn't know there was a `prepare` param on the `InputObject`. That's good to know.

**Comment by swalkinshaw** [comment]
Fixed by https://github.com/rmosolgo/graphql-ruby/pull/2080
