### ISSUE TITLE
Requiring graphql in tests for an engine

### ISSUE THREAD

**Issue by ecbrodie** [rmosolgo/graphql-ruby#1846]
I would like to know what the correct method is for requiring this gem in a Rails Engine. I am following gem/engine development best-practices by listing the gem as a dependency in the `.gemspec` file instead of the `Gemfile`. Then, of course, I run `bundle install` to get the `Gemfile.lock` file updates.

When I use the library in the RSpec tests for the engine, I run into this issue:

```
NameError:
  uninitialized constant Types::GraphQL
```

My current workaround is to explicitly require the gem in my `unit_helper.rb`:

```
require "graphql"
```

What's weird is that I do not need to do this for any other 3rd party gem in this Engine. Is there a better way to do this? Is this a legit bug in graphql?

**Comment by Willianvdv** [comment]
For Rails engines you have to explicitly require libs, does your engine requires graphql? Typically you find these in `lib/your_engine.rb` or `lib/your_engine/engine.rb`.
