### ISSUE TITLE
Cannot use Boolean types with ActionController::Parameters

### ISSUE THREAD

**Issue by trevorrjohn** [rmosolgo/graphql-ruby#1848]
When receiving http requests all params are parsed as strings, thus making Boolean types fail validation like:

```
Could not coerce "true" to Boolean
```

I have solved it by adding overriding `.validate_input` and `.coerce_input`, (see https://gist.github.com/trevorrjohn/9520f7d59bd2c7318b10e71c15849ebf) however I don't think that this is ideal.

Is there a better way to do this? I was looking at `#prepare` on the field but that seems to happen after the validation thus making it useless for this case.

**Comment by paweljw** [comment]
In my experience the builtin [`GraphQL::Types::Boolean`](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/types/boolean.rb), have you ran into issues with it?

**Comment by trevorrjohn** [comment]
Yes. It doesn't work with http requests where all parameters are strings

**Comment by rmosolgo** [comment]
What client is sending this data to your server? Can they send JSON instead?

**Comment by rmosolgo** [comment]
So, if the client sends a POST with the body `'{"someVariable": true}'`, and you parse it with ruby, wouldn't you get 

```ruby 
data["someVariable"] # => true 
```

With a proper boolean value? 

Where does the string `"true"` come in?

**Comment by trevorrjohn** [comment]
Ok sorry I see what you mean, I was not setting the correct content-type. Thanks for the help.
