### ISSUE TITLE
How to return custom GraphQL::ExecutionError by rescue_from

### ISSUE THREAD

**Issue by michiomochi** [rmosolgo/graphql-ruby#1850]
I want to return custom GraphQL::ExecutionError by rescue_from.
But it seems that it can not, now.

```ruby
# Not work
class TestSchema < GraphQL::Schema
  rescue_from(ActiveRecord::RecordInvalid) do |error|
    GraphQL::ExecutionError.new(message: error.message, extensions: { "code" => "INVALID_RECORD" })
  end
end

# Work
class TestSchema < GraphQL::Schema
  rescue_from(ActiveRecord::RecordInvalid) do |error|
    error.message
  end
end
```

How do you think?

**Comment by michiomochi** [comment]
I found `GraphQL::Schema#rescue_middleware`.
https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema.rb#L1026

So, override `GraphQL::Schema#rescue_middleware` and define custom rescue middleware.

```ruby
class MySchema < GraphQL::Schema
  protected def rescue_middleware
     @rescue_middleware ||= MyRescueMiddleware.new.tap { |m| middleware.insert(0, m) }
  end

  rescue_from(ActiveRecord::RecordInvalid) do |error|
    GraphQL::ExecutionError.new(message: error.message, extensions: { "code" => "INVALID_RECORD" })
  end
end

class MyRescueMiddleware < ::GraphQL::Schema::RescueMiddleware
  private def attempt_rescue(err)
    rescue_table.each { |klass, handler|
      if klass.is_a?(Class) && err.is_a?(klass) && handler
        return handler.call(err)
      end
    }
     raise(err)
  end
end
```

**Comment by michiomochi** [comment]
Please tell me if there is a better way. 🙏

**Comment by dhruv-shipmnts** [comment]
> Please tell me if there is a better way.

Have you found any other way to do this, i am facing the same issue too.

**Comment by DamirSvrtan** [comment]
I've used the [graphql-errors](https://github.com/exAspArk/graphql-errors) gem for cases like this which allows for passing extensions:

```ruby
GraphQL::Errors.configure(Schema) do
  rescue_from ActiveRecord::RecordInvalid do |error, _object, _args, ctx|
    ctx.add_error(GraphQL::ExecutionError.new(message: error.message, extensions: { "code" => "INVALID_RECORD" }))
  end
end
```

**Comment by rmosolgo** [comment]
Hi, I just merged some new error handling for the interpreter runtime which supports returning/raising custom errors: https://github.com/rmosolgo/graphql-ruby/pull/2458

Please give it a try and let me know if you run into any other trouble by opening a new issue!
