### ISSUE TITLE
Webpack build crashes after install `1.4.1` graphql-ruby-client

### ISSUE THREAD

**Issue by Mati365** [rmosolgo/graphql-ruby#1858]
When Im trying to import `graphql-ruby-client` as es6 module webpack generates code that crashes on client.

It shows me:
`Cannot assign to read only property 'exports' of object`

And module is exported using `module.exports` instead of `UMD`

**Comment by rmosolgo** [comment]
Oh no! Does it print any more backtrace than that? Does it work with 1.4.0?

**Comment by Mati365** [comment]
@rmosolgo It shows me that file from where webpack want to import package contains `module.exports`. It happened only after upgrade `1.4.1` but diff in file `https://github.com/rmosolgo/graphql-ruby/blob/master/javascript_client/subscriptions/ActionCableLink.js` shows me that there wasnt any changes. Maybe something wrong has been happened during publishing package(no build package or something)?

**Comment by hootlex** [comment]
@Mati365 were you able to resolve this issue?

**Comment by Mati365** [comment]
@hootlex Sadly not. I just locked version to `1.4.0`
