### ISSUE TITLE
Best Examples?

### ISSUE THREAD

**Issue by andyl** [rmosolgo/graphql-ruby#1862]
Where is the best place to read example code that shows the new (class-based) syntax introduced in 1.8??

**Comment by hjJunior** [comment]
I'm looking for this too, I'm new on ruby, so please could anyone provide an example of query in separated file, I even got it to do using Mutations, but I don't know what class I should extend in case of queries

@andyl maybe

**Comment by hjJunior** [comment]
```ruby
# app/graphql/mutations/report_survivor.rb
module Mutations
  class ReportSurvivor < GraphQL::Schema::Mutation
    graphql_name 'report_survivor'
    null true
    description "Report an infected survivor"

    argument :reporter_id, ID, required: true
    argument :reported_id, ID, required: true

    field :errors, [String], null: false, description: "Array of errors"
    field :report, Types::ReportType, null: true, description: "The instance in database"

    def resolve(reporter_id:, reported_id:)
         # my function here
    end
  end
end
```
and I added this line to query_type file

```ruby
# app/graphql/types/query_type.rb
field :report_survivor, mutation: Mutations::ReportSurvivor
```

**Comment by thefliik** [comment]
@andyl http://graphql-ruby.org/

**Comment by hjJunior** [comment]
@thefliik could u help me, with an example using queries in separated files like I have done with Mutations?

**Comment by thefliik** [comment]
@hjJunior https://github.com/rmosolgo/graphql-ruby/issues/1825#issuecomment-422660921

**Comment by daemonsy** [comment]
Hi, it looks like there's no more activity on this, I'm closing the issue. 

If there are any more queries, feel free to reopen it.
