### ISSUE TITLE
Slack channel

### ISSUE THREAD

**Issue by kennyadsl** [rmosolgo/graphql-ruby#1866]
Hello! 

In the README there is a link to Slack that does not work. Is there some Slack workspace or the README is just not up to date?

Thanks in advance!

**Comment by rmosolgo** [comment]
Sorry, seems like it's just flaky. It's up again (https://graphql-slack.herokuapp.com/)

**Comment by cirdes** [comment]
It's not working again. =/

**Comment by rmosolgo** [comment]
🤷‍♂ 

<img width="664" alt="image" src="https://user-images.githubusercontent.com/2231765/59040864-8eb72900-8845-11e9-9564-496547c2e91f.png">

**Comment by cirdes** [comment]
<img width="1680" alt="Screen Shot 2019-06-06 at 11 28 02" src="https://user-images.githubusercontent.com/727781/59041032-39cbe080-884e-11e9-95ea-8bef088dfa22.png">

**Comment by rmosolgo** [comment]
😖

**Comment by krider2010** [comment]
It's up again just now in the UK if that helps anyone!

**Comment by cirdes** [comment]
Got it!!!
