### ISSUE TITLE
camelCase -> snake_case arguments?

### ISSUE THREAD

**Issue by joefiorini** [rmosolgo/graphql-ruby#187]
Thanks to #80 I was pretty easily able to implement a `camelized_field` method to allow requesting fields in camel case. Now I'm defining my first mutation to update the same record I'm retrieving with camel case fields. Here is an example similar to my setup:

```ruby
UserType = GraphQL::ObjectType.define do
  camelized_field :id, !types.ID
  camelized_field :email, types.String
  camelized_field :first_name, types.String
  camelized_field :last_name, types.String
  # ... my actual type has 50 fields on it
end

UserInputType = GraphQL::InputObjectType.define do
  # I need to accept these fields in camelCase, but would prefer to
  # define them in snake_case so I can eventually combine these definitions
  # somehow...
  input_field :email, types.String
  input_field :first_name, types.String
  input_field :last_name, types.String
  # ... this would have the same 50 fields as the object type
end

MutationType = GraphQL::ObjectType.define do
  field :updateCurrentUser, !UserInputType do
    argument :data, !UserInputType
    resolve -> (o, args, ctx) do
      # args[:data] should have all keys in snake_case here
      UserService.upadate(ctx[:current_user], args[:data])
    end
  end
end
```

I'm a little confused about how to make it work:

1. If I specify the arguments in camel case (not my preference since the fields are defined in snake case on my other object type), there is no resolve on arguments (afaict) to convert them to underscore; how would I make it so the `args` hash that my mutation type gets in the resolver has snake case keys?
2. If I specify the arguments in snake case (as I do in the `ObjectType` definition), how do I tell the validator that it should accept their camel case equivalents?
3. Is there a simpler way to define parallel types for input/non-input rather than having to define all 50 fields twice?

**Comment by rmosolgo** [comment]
>  parallel types for input/non-input rather than having to define all 50 fields twice
/me shakes head 
😞 

Sorry! It would be nice to have something like that, like a recursive input type generator ... 

One option might be plain Ruby: 

```ruby
USER_TYPE_FIELDS = {
  email: GraphQL::STRING_TYPE, 
  first_name: GraphQL::STRING_TYPE, 
  last_name: GraphQL::STRING_TYPE, 
  # ... 
}

UserType = GraphQL::ObjectType.define do 
  USER_TYPE_FIELDS.each do |name, type|
    camelized_field name, type
  end 
end 

UserInputType = GraphQL::ObjectType.define do 
  USER_TYPE_FIELDS.each do |name, type|
    input_field name, type
  end 
end 
```

Yes, it's a bit harder to make the camelization transform with inputs. 

Here is a camelization helper for arguments (and input fields):

```ruby
module CamelizedArgument
  def self.call(target, argument_name, *args, &block)
    # modify the incoming name:
    camelized_field_name  = camelize(argument_name)
    GraphQL::Define::AssignArgument.call(target, camelized_argument_name, *args, &block)
  end 
end

GraphQL::Field.accepts_definitions(camelized_argument: CamelizedArgument)
GraphQL::InputType.accepts_definitions(camelized_input_field: CamelizedArgument, camelized_argument: CamelizedArgument)
```

You could define a method to read camelized arguments: 

```ruby
def fetch_argument(args, key) 
  camelized_key = key.to_s.camelize 
  args[camelized_key]
end 
```

The use it in resolve: 

```ruby 
-> (obj, args, ctx) {
  # find args["firstName"]
  first_name = fetch_argument(args, :first_name) 
}
```

I'll try to think of some logical place where that transform could be added, but I'm not sure of a place right now!

**Comment by colepatrickturner** [comment]
Maybe this could be accomplished via Middleware or a function on Schema similar to `object_from_id` where variables can be transformed?

**Comment by rmosolgo** [comment]
This can now be done in a middleware.  Personally I'm not convinced that adding a transformation step is right for the library, but I'm happy to provide some support for it as an add-on.

**Comment by cberkom** [comment]
Any examples how to do this with a middleware?

**Comment by colepatrickturner** [comment]
https://gist.github.com/colepatrickturner/cdb99df21c7e07b287e13ed2bf7972ab

Last tested v1.0.0

**Comment by rmosolgo** [comment]
`1.` ... `1` (?) introduced the instrumentation API and I recommend checking it out if you get the chance. The advantage is that you can avoid overhead on fields _without_ arguments!

**Comment by colepatrickturner** [comment]
It does look wonderful although I'm locked down to v1.0.0 until the introspection issue (#383) with Babel Relay Plugin is resolvable.
