### ISSUE TITLE
Same named fields can't distinguish each other

### ISSUE THREAD

**Issue by Croge32** [rmosolgo/graphql-ruby#1872]
I have an API where objects can be queried for a SHOW by their name, and some objects also have relationships and can query for those by the same name. An example:

in PersonType:

```
field :person do
    type Types::PersonType
    argument :id, !types.ID
    description "Find a Person by ID"

    resolve Resolvers::PersonResolvers::ShowPerson.new
  end
```

in TaskType:

```
field :person, Types::PersonType
```

I'd expect that based on the context, the API should be able to distinguish them, but when running in graphiql, I see errors.

For the following query:

```
query {
  person(id:1) {
    id
  }
}
```

I get this error:

```
{
  "errors": [
    {
      "message": "Field 'person' doesn't accept argument 'id'",
      "locations": [
        {
          "line": 2,
          "column": 10
        }
      ],
      "fields": [
        "query",
        "person",
        "id"
      ]
    }
  ]
}
```

However when running this query:

```
query {
  tasks {
    person {
      id
    }
  }
}
```

It resolves fine:

```
{
  "data": {
    "tasks": []
  }
}
```

I have confirmed this is a name clashing situation because if I change either the PersonType's `person` field OR the TaskType's `person` field to be named something different, the issue resolves.

I was unsure if this would be considered a bug or oversight of the library, or if this is something I'm doing that's against convention. Any ideas about this? Thanks in advance.

**Comment by rmosolgo** [comment]
Wow! sounds like a weird bug. I have a couple of questions: 

- You mentioned a field on `PersonType` and one on `TaskType`. Do you have a `field :person` on your `QueryType`? (That's what I'd expecte `{ person }` to call.) 

- What do you mean by "the issue resolves"? Does the behavior of the API change in some way?

**Comment by Croge32** [comment]
The QueryType undoubtedly contributes to the weirdness. I needed to find a way to separate all the fields into their own subclasses basically, so this is the strategy I found to do so. My entire QueryType:

```
Types::QueryType = GraphQL::ObjectType.new.tap do |root_type|
  root_type.name = "Query"
  root_type.interfaces = []
  root_type.fields = Util::FieldCombiner.combine([
    Types::PersonType,
    Types::TaskType,
    ... many other types
  ])
end
```

I didn't know if there was some other way to set up the QueryType so I could have each object type in its own file and have it read into the QueryType?

Also when I meant "the issue resolves", I mean that whenever the `person` field on either of those types is named differently, both endpoints work properly. So that means it is indeed an issue that they are the same name.

Does that information help?

**Comment by rmosolgo** [comment]
Can you tell me more about this? 

```ruby 
Util::FieldCombiner.combine([
    Types::PersonType,
    Types::TaskType,
```

It looks like it's taking fields _from_ those objects type and applying them _to_ the QueryType?  So, if two of the types have a field with the same name (say, `PersonType.person` and `TaskType.person`), wouldn't they conflict? How does `FieldCombiner.combine` handle naming conflicts?

**Comment by Croge32** [comment]
I think you're right about that. This is the [article](https://m.alphasights.com/graphql-ruby-clean-up-your-query-type-d7ab05a47084) I read that lead me to this solution. Here's the code snippet from that class:

```
module Util
  class FieldCombiner
    def self.combine(query_types)
      Array(query_types).inject({}) do |acc, query_type|
        acc.merge!(query_type.fields)
      end
    end
  end
end
```

This is definitely why this is happening. Would you be able to suggest an alternative way to divide up the code in a similar way (where all the fields/object_types in the API are segmented into their own files) without having any name clashing happen?

**Comment by rmosolgo** [comment]
I recommend not doing it. If you have a large application object, you might as well put it in one large file. Otherwise, you introduce subjective, blurry boundaries behind components and any new developer is going to have to hunt around to find where various configurations have been scattered. You might as well leave them all together, so that the source code and the application reflect one another in a simple way. 

That said, other people have suggested other approaches to something similar, for example #1825
