### ISSUE TITLE
RSS feed of newletter

### ISSUE THREAD

**Issue by ianks** [rmosolgo/graphql-ruby#1873]
Hey @rmosolgo, hope all is well! I was curious if it's possible to get an RSS feed of the newsletter? I would love to keep my team up to date on things and RSS integrates nicely with services we use (Slack, etc). Is there a way to get an RSS feed of the updates?

**Comment by rmosolgo** [comment]
Sadly, it looks like Tinyletter [doesn't support RSS out of the box](https://twitter.com/tinyletter/status/717054937113300992?lang=en), but someone made a project to create an RSS feed, so you could try that: https://github.com/hawx/tl-feed
