### ISSUE TITLE
GraphQL::Query ambiguous result when passed the graphql_definition vs schema class

### ISSUE THREAD

**Issue by xuorig** [rmosolgo/graphql-ruby#1875]
Was debugging a problem where `max_depth` set on the schema would not be respected at the query level.

It appears `Query.new` can receive both, but the behavior is a bit ambiguous.

On schema, doing this:

```
Schema.max_depth = 100
```

Ends up being delegated to `graphql_definition`. If we then use `Query.new(schema: Schema, "query { ... }")`

In the initializer, this logic then fails, because we passed the Schema class and not the `graphql_definition`

```ruby
      @max_depth = max_depth || schema.max_depth
      # max_depth is nil, even though we would expect 100 here
```

I'm not sure if query should expect only graphql definitions, or accept both, but it would be great to shape the API / implementation in a way to avoid these mistakes.

**Comment by rmosolgo** [comment]
Wow, weird, so ... `Schema.max_depth` returned nil, even though we set `Schema.max_depth = 100`? 

It would be nice to support _both_ `Schema` (class) and `Schema.graphql_definition` (instance). In the future, the instance will be gone and only the class will be used, so it would be nice to move that direction.

**Comment by xuorig** [comment]
Yep thats because `max_depth=` is delegated to `graphql_definition` 😅 

```
Schema.max_depth = 100
Schema.max_depth => nil
Schema.graphql_definition.max_depth => 100
```

**Comment by rmosolgo** [comment]
Oh, I guess those should be unified (either both delegated, or both stored at class-level and passed down at .to_graphql)

**Comment by xuorig** [comment]
Yep :D! If that sounds good I'll make the fix right away.

**Comment by rmosolgo** [comment]
:+1:

**Comment by rmosolgo** [comment]
I've done a lot of work on the schema class in the last ... year 😆  And nobody else has reported this issue, so I'll close it.
