### ISSUE TITLE
Specify versioning model

### ISSUE THREAD

**Issue by ivan-kolmychek** [rmosolgo/graphql-ruby#188]
Is there any mention about which version model (i.e. [semver](semver.org)) does `graphql-ruby` follow?

From a quick glance at [changelog](https://github.com/rmosolgo/graphql-ruby/blob/master/CHANGELOG.md) it seems that it's something like "release breaking changes only on 0.X increment", but I'm not sure.

Also, the [0.14.1](https://github.com/rmosolgo/graphql-ruby/blob/master/CHANGELOG.md#breaking-changes--deprecations-3) seems to have deprecations, which can be mistaken for the breaking change, as they are in the same section.

So, there may be a confusion about that, which can be resolved by:

* specifying the versioning model
* separating the deprecations from breaking changes in changelog

What do you think about it?

**Comment by rmosolgo** [comment]
Thanks for raising this issue!

> release breaking changes only on 0.X increment

Yes, this has been my approach so far. 

> separating the deprecations from breaking changes in changelog

:+1: Happy to do this from now on!

> specifying the versioning model

Hmm, what can I say for this one? I have the same concerns with SemVer as expressed here: https://gist.github.com/jashkenas/cbd2b088e20279ae2c8e

- It's not a good expression of how a library changes over time 
- It's not a replacement for reading the changelog (or maintaining a good changelog)

So, to quote the conclusion of that post: 

>  keep version numbers that reflect the real state and progress of a project, use descriptive changelogs to mark and annotate changes in behavior as they occur, avoid creating breaking changes in the first place whenever possible, and responsibly update your dependencies instead of blindly doing so

That's definitely my goal, and I appreciate your suggestion to separate deprecations from breaking changes in the changelog. I will do that for future deprecations!

**Comment by ivan-kolmychek** [comment]
@rmosolgo sure, whatever is working for the project in the first place - the versioning is there for the project, not vice-versa. :)

The semver was just an example of well-documented versioning scheme.  I think it would be enough to just have your own schema documented at least a little bit somewhere - let's say, put something like this to `VERSIONING.md`:
> Versioning is done by scheme MAJOR.MINOR.PATCH, where:
> * MAJOR is not used right now and should be 0.
> * MINOR is for the new features and breaking changes
>  * PATCH is for fixes and non-breaking changes

This way what you're striving to signal with versions is clear. Also, the `VERSIONING.md` may be a nice place to specify "Disclaimer: these are the guidelines, please, always read the changelogs before updating". 

P. S. I really appreciate that `graphql-ruby` has detailed changelog; there are still projects without one. :)

**Comment by rmosolgo** [comment]
Sorry, I'm not interested in a versioning document because I don't see the value in it. If people don't see a versioning document, they'll just check the changelog, which is the right thing to do :)
