### ISSUE TITLE
When to use field with resolve, field, function, resolver

### ISSUE THREAD

**Issue by mmahalwy** [rmosolgo/graphql-ruby#1880]
There is reference to new field API in the docs:
```
# Using a Proc literal or #call-able
field :something, ... resolve: ->(obj, args, ctx) { ... }
# Using a predefined field
field :do_something, field: Mutations::DoSomething.field
# Using a GraphQL::Function
field :something, function: Functions::Something.new
```

When would one use either or? 

Lastly, these seem like solutions to keep an object then or better testing – how can one keep their query object thin and abstract the different fields out?

Thanks

**Comment by rmosolgo** [comment]
Hmm, great question! I think the best way to understand it is from a historical perspective. 

In the earliest version of GraphQL-Ruby, I wanted to make the system as conceptually _simple_  as possible, so I implemented field resolution as a plain function call. That's the origin of `resolve: ->(obj, args, ctx) { ... }`. 

People expected more structure from the gem, so I added `function:` as a way to link resolution logic with the input and return types. 

However, this was still not an API that made developers productive. So I rewrote GraphQL-Ruby's schema definition to use classes, where plain old Ruby methods were used for resolving fields _instead_ of resolve functions. 

However, there were a few things that _were_ possible with `->(obj, args, ctx) { ... }` which were _not_ possible with plain old Ruby methods. So for compatibility purposes, `resolve:` was continued to be supported. The same is true for `field:` and `function:`, they are not recommended now but they are supported for historical compatibility. 

At present, the _best_ way to resolve fields is with plain old Ruby methods or with `resolver:`, if need be. (The docs for `Resolver` suggest _not_ using it :P. It's easy to put too much business logic in the GraphQL layer with a resolver.)

Does that answer some of your questions?

**Comment by mmahalwy** [comment]
@rmosolgo any chance to see comment above?

**Comment by rmosolgo** [comment]
> Wanted to get your thoughts on this.

Personally, I'm in favor of making the source code match the application's logical structure as closely as possible, so I don't arbitrarily split up code that belongs together. It makes giant files, but if I'm hunting a bug, I don't want to spend my time hunting through files to find what I'm looking for. 

So, there's sometimes a code smell of "giant files", and people fix the _symptom_ by arbitrarily splitting the one file into several files, but they don't fix the actual _problem_, for example, that there's a god class or a failure to Do One Thing, or whatever. With GraphQL's Query type, it's gonna be a god class, and I don't think there's any way around that. It's possible to scatter the god class across a bunch of different files, but that just introduces indirection without actually improving the application structure. 

> plain ol’ Ruby class

Sometimes I see resolvers like this: 

```ruby 
def posts(order_by:, author_id:, categories:) 
  posts = Post.all 
  if order_by 
    posts = posts.order(order_by[:field] => order_by[:dir])
  end 
  # Only allow authors to see themselves, or allow admins to filter 
  if author_id && (context[:viewer].admin? || context[:viewer].id == authori_id)
    posts = posts.where(author_id: author_id) 
  end 

  if categories 
    posts = posts.joins(:categories).where("categories.name" => categories)  
  end 
  
  # Hide unmoderated posts unless the viewer is admin 
  if !context[:viewer].admin?
    posts = posts.moderated 
  end 
 
   posts 
end 
```

The problem here is that lots of business logic is implemented in the GraphQL layer, so the only way to test it is to run GraphQL queries, and if you need this kind of behavior somewhere else, you'll have to duplicate the code. 

It's better to make some object which encapsulates the business logic then call that: 

```ruby 
# app/models/posts/listing.rb
class Post::Listing 
  def initialize(viewer:, order_by:, categories:, author_id:) 
    # ... 
   end 

   def posts 
      # apply filtering like above 
   end 
end 
```

Then in the resolver, call the underlying business object:

```ruby 
def posts(kwargs) 
  Post::Listing.new(viewer: context[:viewer], **kwargs) 
end 
```

That way, you can give good tests to `Post::Listing` in isolation and have more confidence about how your GraphQL layer interacts with the application, since the boundaries are very clear. Besides that, if you have some post listing behavior elsewhere in the app, you can use this underlying business object to DRY up that logic and provide consistent behavior.

**Comment by mmahalwy** [comment]
I think your suggestion of isolation the business logic makes a lot of sense. This won't solve the problem of the QueryType file becoming extreme large, no? Especially if you are defining arguments and such. I have been using the included pattern pretty heavily so far – it works but I am not sure it's perfect. It also works well for query but not as much for mutation. Can share files if needed

**Comment by yagudaev** [comment]
@rmosolgo I think you are both right, I think of `query_type.rb` and `mutation_type.rb` as routers and they should specify all the actions allowed (this is btw also how the documentation in graphql works).

However, they should not specify the implementation.

Right now it is possible to do something like this:

```ruby
module Types
  class MutationType < Types::ObjectType
    field :update_order, mutation: Mutations::UpdateOrder
    field :create_order, mutation: Mutations::CreateOrder
  end
end

module Types
  class QueryType < Types::ObjectType
    include Queries::Orders

    field :orders
    field :order, Models::OrderType, null: false do
      argument :id, ID, required: true
    end
  end
end
```

To be more consistent between `mutation_type` and `query_type` it would be nice to be able to do something like this:

```ruby
module Types
  class MutationType < Types::ObjectType
    field :update_order, mutation: Mutations::UpdateOrder
    field :create_order, mutation: Mutations::CreateOrder
  end
end

module Types
  class QueryType < Types::ObjectType
    field :orders, resolver: Queries::Orders
    field :order, Models::OrderType, null: false, resolver: Queries::Orders do
      argument :id, ID, required: true
    end
  end
end
```
Would that make sense?

**Comment by rmosolgo** [comment]
I think the example you posted should work just fine, assuming that `class Queries::Orders < GraphQL::Schema::Resolver`, and that `def resolve(**kwargs)` is ready to accept an `id:` argument. Is that what you mean?

**Comment by macfanatic** [comment]
The resolver path worked well, but still left a decoupling between the field definition and the resolve of the collection itself, which I didn't care for as much.

In our app, I introduced a new "resolver" class that allows you to define the field alongside the resolution, and include this back into the main query type.  To add a little more DSL to to the query type to stay DRY, I introduced a "router" that just includes each resolver for us following a rails-like naming convention.

```ruby
# app/graphql/queries/resolver.rb
class Queries::Resolver < GraphQL::Schema::Resolver
  class_attribute :field_args, default: []
  class_attribute :field_definition, default: ->{}

  class << self
    def field(*args, &definition)
      args.last.merge!(resolver: self)

      self.field_args = args
      self.field_definition = definition
    end

    # Used in the QueryType to include the functionality
    def define
      Types::QueryType.field(*field_args, &field_definition)
    end
  end
end

# app/graphql/queries/organizations/show.rb
class Queries::Organizations::Show < Queries::Resolver
  field :organization, Types::Models::OrganizationType, null: false do
    argument :id, ID, required: true
  end

  def resolve(id:)
    Organization.find(id)
  end
end

# app/graphql/queries/router.rb
class Queries::Router < Types::ObjectType
  class << self
    def namespace(name, &definition)
      begin
        @namespace = name
        definition.call
      ensure
        @namespace = nil
      end
    end

    def resources(name, actions: [])
      actions.map! do |action|
        [:queries, @namespace, name, action].compact.join('/').classify.constantize
      end

      actions.each(&:define)
    end

    alias_method :resource, :resources
  end
end

# app/graphql/types/query_type.rb
class Types::QueryType < Queries::Router
  resources :organizations, actions: [:show]

  namespace :organizations do
    resources :sub_resource, actions: [:show]
  end
end
```

In this example, we have a query for fetching an organization by ID.  The logic is defined in the resolver, included via the class `define` method automatically via the router.

We support all the options to the normal `field` definition, but we do inject ourself as the `resolver` option before passing on.

**Comment by rmosolgo** [comment]
Thanks for the conversation here! I'll close this since I think we're done here.
