### ISSUE TITLE
Subscription trigger field resolution is fixed to "Subscription" class name

### ISSUE THREAD

**Issue by wealth** [rmosolgo/graphql-ruby#1882]
Hi. When subscription type classname is different from Subscription (ex. AuctionsSubscription), field resolution is returning "No subscription matching trigger" error. I see that this is mostly depends on a project code organization preference, but probably, there should be a way to get_field only from supscription types, without a subscription classname.

https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/subscriptions.rb

```
      field = @schema.get_field("Subscription", event_name)

      if field.nil?
        # And if it wasn't found, normalize it:
        normalized_event_name = normalize_name(event_name)
        field = @schema.get_field("Subscription", normalized_event_name)
```

**Comment by rmosolgo** [comment]
Oops! You're right, it shouldn't be hardcoded that way, it should probably be: 

```
field = @schema.get_field(@schema.subscription, normalized_event_name)
```
