### ISSUE TITLE
Sequel eager loaded datasets are not eager executed

### ISSUE THREAD

**Issue by sarahhenkens** [rmosolgo/graphql-ruby#1887]
Using version `1.8.10` (with Sequel `5.3.0`).

Example code:
```ruby
module Types
  class Query < GraphQL::Schema::Object
    description "The query root of this schema"

    field :popular_shows, [Types::Show], null: false do
      description "List of popular shows"
      argument :filter, String, required: false
    end

    def popular_shows(filter: false, first: false)
      attrs = {
        "filter" => filter || :all
      }

      ::Show
        .eager(:show_rating_view)
        .with_filters(attrs)
        .order(Sequel.desc(:shows__followers_count))
        .where{Sequel[:shows][:followers_count] > 0}
    end
  end
end
```

The return value of `Types::Query#popular_shows` is a Sequel::DataSet instance.

One of the caveats in Sequel is that you need to use `.all` for any eager loaded dataset: (https://sequel.jeremyevans.net/rdoc/classes/Sequel/Model/Associations/DatasetMethods.html#method-i-eager). Because GraphQL considers  the result set to be an Enumerable, it would just call `each`, `map` etc. As a result, no eager loading occurs.

What is the best practice to make eager loading work here? Should I manually call `.all` inside the `popular_shows` method or is there a cleaner way through the API to modify the enumeration of result sets?

With the built-in connectors, a similar problem occurs, if I would return a resolved Sequel DataSet (`.all` method), the connector would never apply the Sequel::DataSet specific pagination. It would consider it just as an array.

**Comment by rmosolgo** [comment]
Hmm, I don't use Sequel so I'm not _really_ sure on the details here, but this reminds me of another open PR. Could you take a look at #1779  ? That also has to do with Sequel eager loading. If you can give it a try and it solves this problem, I'll try to merge it!

**Comment by sarahhenkens** [comment]
@rmosolgo, yups. Instead of overriding the internals I ended up making my own Sequel-only Connection class that improves Sequel integration with eager loading support and also stable seek pagination.

Since I solved the original reported ask, closing this ticket :)

**Comment by rmosolgo** [comment]
Awesome, glad you found something that works, and thanks for sharing your solution!

**Comment by Aryk** [comment]
Hi @rmosolgo 

Is there any chance we can get @sarahhenkens changes into this gem?

The fact that the gem does not call "all" and forgoes eager loading can become an issue down the road.

**Comment by sarahhenkens** [comment]
hey @Aryk, I ended up open-sourcing this change as part of https://github.com/sarahhenkens/sequel-keyset_pagination which enabled stable keyset pagination for the Sequel gem.

**Comment by Aryk** [comment]
@sarahhenkens Thanks! I've added the gem and added the updated gist.
