### ISSUE TITLE
dynamic type definition

### ISSUE THREAD

**Issue by benbonnet** [rmosolgo/graphql-ruby#1890]
Hi; sorry if not asking at right place, I was interested in the example shown [here](https://github.com/rmosolgo/graphql-ruby/blob/master/guides/schema/dynamic_schema.md) :

```
class DynamicTypeDefinition
  attr_reader :model
  def initialize(model)
    @model = model
  end
  def to_graphql_type
    model_name = model.name
    GraphQL::ObjectType.define do
      name(model_name)
    end
  end
end
```

So far, not understanding fully yet how to use correctly the class based utilities; 

From what I understand in that example, it provides a way to define a type dynamically. Thing is, I don't get yet how to reuse such example. Could you expose a use case of such class ? Thx a lot in advance for any tips about this

Best

**Comment by rmosolgo** [comment]
Hi, sorry for the late reply here! A general use case is when the GraphQL API is generated _based on_ some other code. 

For example, you might generate GraphQL types from  your ActiveRecord models. Or, if you already have a REST API layer, you might generate your GraphQL schema from your previous API layer.

**Comment by chrisharrison** [comment]
The link in the original issue is dead. Here is the documentation being referred to:
https://github.com/rmosolgo/graphql-ruby/blob/v1.7.14/guides/schema/dynamic_schema.md
