### ISSUE TITLE
Customized partial error for queries.

### ISSUE THREAD

**Issue by RealSilo** [rmosolgo/graphql-ruby#1896]
Is a customized partial query error like below supported?

I was trying to add something like

`context.add_error(GraphQL::ExecutionError.new("MSG to show to user", ast_node: context.ast_node, options: { path: context.path }))`

on field resolver level, but did not work out with the path. Is this the right approach you think? If so what's the preferred way to make it happen?

<img width="618" alt="screen shot 2018-10-10 at 11 43 35" src="https://user-images.githubusercontent.com/10554687/46763514-e5586d00-cc8e-11e8-987d-03c3ee932ce1.png">

**Comment by rmosolgo** [comment]
Try this instead (using `raise`): 

```ruby 
raise GraphQL::ExecutionError.new("MSG to show to user")
```

The path will be added for you by graphql-ruby. Please reopen and let me know what you find if that doesn't work out!

**Comment by RealSilo** [comment]
Ahh, for some reason I thought this would return the error but the data would be an empty object.
Is there a preferred way to quickly configure this, so all the resolvers add these errors by default. E.g. if a parent resource is nil (belong_to) or a child resource is nil (has_one) then the errors are added by default without raising them?

**Comment by rmosolgo** [comment]
No, there's not a way to configure that. Generally you'd just return `nil` in that case, errors are for when things go wrong
