### ISSUE TITLE
Relay Helpers

### ISSUE THREAD

**Issue by devknoll** [rmosolgo/graphql-ruby#19]
It would be great to get some helpers for generating Relay types. Not sure if these should go here, or if we should break out another lib though.

I've got a simple `Connection` field helper for enumerables. We could probably generate an entire connection given an `ActiveRecord::Relation` (maybe for graphql-rails?)

Another one would be a `Mutation` field helper that automatically generates input/payload types. I've got something like this at the moment:

```ruby
:change_profile_picture => MutationType.create do |m|
  m.accepts({
    :uri => !types.String
  })

  m.returns({
    :viewer => !ViewerType
  })

  m.resolve -> (object, args, ctx) { ... }
end
```

**Comment by rmosolgo** [comment]
Agreed that helpers would be great, but I think they belong "somewhere else."

Facebook split things up into `graphql-js`, `graphql-express` and `graphql-relay`. I think that split would fit Ruby quite well too:

- one part is an implementation of GraphQL schema definition & query execution 
- one part connects a GraphQL schema to HTTP 
- another part provides helpers for Relay-specific GraphQL use 

 One advantage to keeping these parts decoupled is that users could swap them out or pick-and-choose as they see fit (eg, swap GraphQL implementations)

I'm definitely excited to see the options for ActiveRecord-to-GraphQL mappings, but I feel too busy with this project to spend _too_ much time on it!

**Comment by devknoll** [comment]
Sounds great to me!

**Comment by sgwilym** [comment]
I've been truly befuddled by Relay's special requirements of a GraphQL server, and would love to see how some of you have made it work with this gem. So echoing everyone else that helpers sound _great_.

Just out of curiosity, would a library of relay helpers have to be specific to `graphql-ruby`'s particular idioms and ways of defining a schema?

**Comment by rmosolgo** [comment]
Yes, it's definitely weird stuff. I had some tinkerings based on the items under this header:

https://github.com/graphql/graphql-relay-js#using-relay-library-for-graphqljs

And I pushed them up here: 

https://github.com/rmosolgo/graphql-relay-ruby

(Interesting parts: [Star Wars Schema defn](https://github.com/rmosolgo/graphql-relay-ruby/blob/master/spec/support/star_wars_schema.rb), [Relay helpers](https://github.com/rmosolgo/graphql-relay-ruby/tree/master/lib/graphql/relay))

Still a lot to do there :)

I think the way it would work (eh, the way _I_ did it anyways) is to have a handful of objects that implement the requirements of Relay, then _also_ have some helpers for creating `graphql-ruby` types & fields. 

If you can keep the Relay helpers decoupled from the actual graphql types, that leaves you some freedom to support other GraphQL implementations in the future :grimacing:

**Comment by rmosolgo** [comment]
Also pushed to rubygems: https://rubygems.org/gems/graphql-relay
