### ISSUE TITLE
Question: How to deal with Mutations on abstract classes

### ISSUE THREAD

**Issue by Fleick** [rmosolgo/graphql-ruby#1900]
Hey,
I have the following question dealing with Mutations on Abstract classes:
(Of course this is an example explaining the problem not the real Problem)
I have an MTI in Rails (using active_record-acts_as) like this:
Pet
Dog < Pet
Cat < Pet
Now for queries using interface and Mutations on Cats or Dogs everything is working great. But than there are Mutations for all Pets - like set_owner which assigns a Pet to a Person. In Reals this is an Association(person_id, pet_id). How would the Pet be given to the Backend:
I have 3 Ideas on this:
1. Put pet_id through the loading of Pets and send this
set_owner(pet_id: x, person_id: x)
2. Put a touple with id and type  (Than load the specific Object in the Backend)
set_owner(pet{id: x, type: Cat/Dog}, person_id: )
3. Use everywhere the abstract id (pet_id):
Cat(id: 5, pet_id: 6) => Cat(id: 6)
Dog(id: 5, pet_id:7) => Dog(id: 7) 
So you can handle inheritance migrations easily with one ID
set_owner(pet_id: x, person_id: x)

Unfortunately I can find any real examples to this case and especially no best solution discussions...

**Comment by rmosolgo** [comment]
Hi! A lot of GraphQL APIs use unique IDs, inspired by Relay JS. GraphQL-Ruby includes some tools for global IDs like this. The ids are encoded with _both_ the GraphQL object type name _and_ the Rails table primary key. Then you can use the ID to figure out what type to treat the object as. I guess that's similar to your third option. 

Are you using global IDs? What do you think about adding them?

**Comment by Fleick** [comment]
Hey,
thanks for your Answer rmosolgo. Yes after a deep discussion we decided to use globas IDs and as the global ID we use the ID of the basic (the abstract) type as we don't need any additional tables to decode them. With this Version we can just use Pet.find(pet_id).specific and get the Cat or Dog object - (pet_id) is the global ID.
Thanks for your help
