### ISSUE TITLE
support for react-relay-network-modern's batching?

### ISSUE THREAD

**Issue by modosc** [rmosolgo/graphql-ruby#1904]
https://github.com/relay-tools/react-relay-network-modern#how-batching-works-internally

right now we're doing something like:
```
    queries = params[:_json].to_a.map do |param|
      {
        query: param[:query],
        variables: ensure_hash(param[:variables]),
        context: context,
        operation_name: param[:operationName] || param[:id], 
      }
    end

    result = MySchema.multiplex(queries).map.with_index do |query, i|
      query['id'] = params[:_json][i][:id]
      query.to_h
    end
```

but i'm unsure if multiplexed queries will always return in the same order? would it be possible to accept an optional `id:` parameter for multiplexed queries which would be used to identify them in the resulting response? happy to put a pr together for this.

**Comment by rmosolgo** [comment]
Yes, they return in the same order. I think accepting an `id:` parameter would be fine, please open a PR!

**Comment by modosc** [comment]
`react-relay-network-modern` changed how batching worked. no more id so this isn't relevant now.
