### ISSUE TITLE
Is there a way to keep GraphQL:InputObjectType input_fields DRY?

### ISSUE THREAD

**Issue by ChrisKaun** [rmosolgo/graphql-ruby#1908]
Hey,

lets assume I have two GraphQL::InputObjectTypes:
```
CreateCompany = GraphQL::InputObjectType.define do
  name 'CreateCompany'
  input_field :street, !types.String
  input_field :city,   !types.String
end
```
```
CreatePerson = GraphQL::InputObjectType.define do
  name 'CreatePerson'
  input_field :street, !types.String
  input_field :city,   !types.String
end
```

Is there a way to put those two input_fields in a module/mixin and load it inside my `createPerson`/`createCompany` InputObjectType without using a nested input field?

**Comment by rmosolgo** [comment]
Using `InputObject.define`, you could add a custom plugin with `accepts_definitions` (eg http://graphql-ruby.org/api-doc/1.8.10/GraphQL/Define/InstanceDefinable). 

But better would be to use the new class-based API, then you could add a helper class method on your base class which would call the shared code in its method body. (http://graphql-ruby.org/type_definitions/input_objects.html)

Hope that helps!
