### ISSUE TITLE
multiplex instrumentation called on non-multiplexed queries

### ISSUE THREAD

**Issue by modosc** [rmosolgo/graphql-ruby#1909]
we have a logger:
```
  instrument :multiplex, ::Instrumentation::MultiplexLogger
```
```
module Instrumentation
  module MultiplexLogger

    module_function

    def before_multiplex(multiplex)
      @start = DateTime.current
    end

    def after_multiplex(multiplex)
      elapsed_ms = ((DateTime.current - @start) * 1.days).in_milliseconds.to_f.round(1)
      # do something here
    end

  end
end
```
it appears that our `:multiplex` instrumentation is called for non-multiplexed queries (ie, `Schema.execute`). is there some way to tell that this is a multiplexed call from `multiplex`? i tried checking `multiplex.queries.length` but i couldn't figure out how to tell the difference between `Schema.execute(query)` and `Schema.multiplex([ query ])` (both of which have length of 1).

**Comment by swalkinshaw** [comment]
What about tracing? http://graphql-ruby.org/queries/tracing

`execute_multiplex` exists as a trace key.

I think the issue you're running into is that every query gets executed as multiplex. It's just that there's only one by default.

**Comment by modosc** [comment]
sure - i'll look into tracing. if every query is executed as multiplex then maybe the docs should be updated to reflect this? specifically http://graphql-ruby.org/queries/multiplex.html which makes it seem as though all the analysis / instrumentation is specific only to `#multiplex`

**Comment by rmosolgo** [comment]
I've added a note to the docs in 7124873a4
