### ISSUE TITLE
Question: Executing and Returning Initial Query with Subscription

### ISSUE THREAD

**Issue by ksylvest** [rmosolgo/graphql-ruby#1910]
For a GraphQL subscription is it possible to execute the initial query (to support pseudo live-queries)?

```ruby
module Types
  class SampleType < GraphQL::Schema::Object
    field :greeting, String, null: false

    def greeting
     Time.current < Time.current.noon ? 'Morning!' : 'Evening'
    end
  end
end

class SampleSchema < GraphQL::Schema
  use GraphQL::Subscriptions::ActionCableSubscriptions
  subscription Types::SampleType
end

SampleSchema.execute('subscription greeting { greeting }')['data'] # nil -- can this be configured to be { greeting: '...' } ?
```

Per [FB RFC on subscriptions](https://github.com/facebook/graphql/blob/master/rfcs/Subscriptions.md) - I'm a bit unclear if this type of thing is meant to be supported:

> The server may send an initial publish from executing the subscription operation.

Realize this can likely be done via a `Query` + `Subscription`.

Also - is the logic on controlling execution wrapped up here?: 

https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/subscriptions/instrumentation.rb#L59

**Comment by ksylvest** [comment]
Thanks for the response Robert! Appreciate the work you put into graphql-ruby (super useful library). Closing.

**Comment by rmosolgo** [comment]
Btw I was looking back on the spec and didn't see any mention one way or another about initial responses, do you? 

https://facebook.github.io/graphql/June2018/#sec-Subscription

I see your link above is to the RFC, but I wonder if/how that made it to the spec. I'm going to add support for initial responses one way or another but I'll include a bit from the spec if I can find it!

**Comment by ksylvest** [comment]
Hmm, I can not find anything within the spec linked. It seems like it'd be challenging to avoid race conditions without (via the query / subscribe combo.

**Comment by rmosolgo** [comment]
yeah, i [agree](https://github.com/facebook/graphql/issues/283#issuecomment-284553218) 😉

**Comment by rmosolgo** [comment]
Trying to add proper support for this in #1930
