### ISSUE TITLE
Complex Filtering and Searching

### ISSUE THREAD

**Issue by RealSilo** [rmosolgo/graphql-ruby#1913]
Is it worth using the `gem 'search_object` and `gem 'search_object_graphql'` gems for filtering and searching? [Reference](https://www.howtographql.com/graphql-ruby/7-filtering/)

At the moment for top level queries I simply add the where queries/scopes in the field resolver.

For child objects (nested queries) I use `gem 'graphql-batch'` with HasManyLoader like below.
Is this the right approach?

As this seems to be a basic feature, some recommended implementation description could be also added to the docs.

```
class HasManyLoader < GraphQL::Batch::Loader
  def initialize(model, foreign_key, options = {})
    @model = model
    @foreign_key = foreign_key
    @options = options
  end

  def perform(foreign_value_sets)
    foreign_values = foreign_value_sets.flatten.uniq

    where_hash = { @foreign_key => foreign_values }

    @options[:where_options]&.each { |key, value| where_hash[key] = value }

    records = @model.where(where_hash).to_a

    foreign_value_sets.each do |foreign_value_set|
      matching_records = records.select do |r|
        foreign_value_set.include?(r.send(@foreign_key))
      end
      fulfill(foreign_value_set, matching_records)
    end
  end
end
```

```
class VehicleType
  ....
  def vehicle_alerts(state: 'created')
    HasManyLoader.for(
      VehicleAlert, :vehicle_id, where_options: { state: state }
    ).load(object.id)
  end
end
```

**Comment by rmosolgo** [comment]
Adding application-specific searching and filtering to resolvers is a good approach here, thanks for sharing your solution!
