### ISSUE TITLE
Will GraphQL::ExecutionError removed with .define methode

### ISSUE THREAD

**Issue by Fleick** [rmosolgo/graphql-ruby#1926]
Hello, everybody,
I decided to use the class method in my new application. However, I don't like the error method in the new guide to use an errors-field in every mutation. Especially because I have to explicitly retrieve this field in the query and don't get an error automatically like with the top-level error. In the documentation there is unfortunately no information about whether GraphQL::ExecutionError is still available after 2.0 or if it is thrown out with .define.
Can anyone answer this question for me?

**Comment by rmosolgo** [comment]
I have no plans to ever remove `raise GraphQL::ExecutionError, "..."` (or subclasses of that error). Use it as much as you like!

**Comment by Fleick** [comment]
Thank you very much for your answer. Sorry for the question, but it would take a lot of work to refactor this afterwards so I wanted to be sure.
