### ISSUE TITLE
Refactoring errors .define method to class-method

### ISSUE THREAD

**Issue by Fleick** [rmosolgo/graphql-ruby#1927]
Hello, everybody,
we are currently considering refactoring an existing application to the new class method to guarantee compatibility from version 2.0. At first sight we found 2 illogical errors:
1) The general naming has been changed to camelCase. This is how it becomes: team_create => teamCreate or team_members => teamMembers
2) Mutations don't return the type directly anymore but nest a field type (at least following the new guide). So the retrieval becomes: team_create(data){id, team_name} => teamCreate(data){team{id, teamName}}}}. 

Is it possible to bypass these changes? Because with this the complete frontend would have to be refactored as well and not only the backend. Also the compatibility to old frontend versions would be lost.

**Comment by rmosolgo** [comment]
Hi, thanks for sharing your question! 

> 1. camelCase 

By default, graphql-ruby camelizes field names. You can customize this by adding `camelize: false` to your base field class, see: http://graphql-ruby.org/fields/introduction.html#field-parameter-default-values

> 2. Mutations

By default, mutations generate a payload type. You can override this by providing a `payload_type` configuration, for example: 

```
payload_type Types::TeamType 
```

See http://graphql-ruby.org/api-doc/1.8.11/GraphQL/Schema/Mutation#payload_type-class_method

Let me know if you have any other trouble! I definitely want to help you update the server without requiring front-end changes :)

**Comment by Fleick** [comment]
Thank you very much for your answer. 
I will test the config changes. The pure backend refactoring of course saves a lot of effort and ensures compatibility with old frontend versions. Which probably also makes refactoring easier for others, so thank you for your commitment.
If you are planning a guide for porting from the define to class method, these would be two good notes ;)
