### ISSUE TITLE
Control the camelCase behaviour

### ISSUE THREAD

**Issue by cabello** [rmosolgo/graphql-ruby#1935]
From http://graphql-ruby.org/type_definitions/objects.html#object-classes
> Field and argument names should be underscored as a convention. They will be converted to camelCase in the underlying GraphQL type and be camelCase in the schema itself

That has been biting us from time to time, things like: the developer is unaware of the convention, or temporarily forgets it; or the autocompletion, instropection query is not working, or when they are writing an integration spec. 

Some time is wasted until they realize `is_completed` is being transformed into `isCompleted` by the gem. Any chance we can control this behaviour? At this moment we are replacing `is_completed` by `isCompleted` in the codebase. We would rather hurt Ruby's naming conventions than deal with developer frustration.

[The spec](https://facebook.github.io/graphql/June2018/) does provide all examples using camelCase but does not mention casing, camelCase, snake_case and the token for Name an argument includes underscores (`/[_A-Za-z][_0-9A-Za-z]*/`).

Thoughts?

**Comment by rmosolgo** [comment]
Yes, you can configure the schema to use `camelize: false`, so that no transformation is performed: http://graphql-ruby.org/fields/introduction.html#field-parameter-default-values
