### ISSUE TITLE
UglifyJs: SyntaxError: Unexpected token punc «(», expected punc «:» [./~/graphql-ruby-client/subscriptions/registry.js

### ISSUE THREAD

**Issue by gastongouron** [rmosolgo/graphql-ruby#1936]
Hello, 

Thanks you so much for your work and making this incredibly cool gem. I use Rails 5 API to serve a ReactJS client using `"apollo-client": "1.9.3"` , ` "react-apollo": "^2.2.3"` on a project bootstraped with `create-react-app`. Everything works flawelessy in development and I recently introduced subscriptions. When deploying to production (or running yarn build) **yarn raises this error**: 

```
Failed to compile.

static/js/main.6dec48f7.js from UglifyJs
SyntaxError: Unexpected token punc «(», expected punc «:» [./~/graphql-ruby-client/subscriptions/registry.js:11,0]
```

I'm setting up the client app subscriptions that way:
```
//setup.js
...
import addGraphQLSubscriptions from 'graphql-ruby-client/subscriptions/addGraphQLSubscriptions'


const cable = ActionCable.createConsumer()
window.cable = cable

const RailsNetworkInterface = createNetworkInterface({
 uri: '/graphql',
 opts: {
   credentials: 'include',
 },
 headers: {
   'X-CSRF-Token': $("meta[name=csrf-token]").attr("content"),
 }
});

const networkInterfaceWithSubscriptions = addGraphQLSubscriptions(RailsNetworkInterface, {cable: cable})

const apolloClient = new ApolloClient({
  ssrMode: false,
  link: new HttpLink({ uri: '/graphql', fetch }),
  cache: new InMemoryCache(),
  networkInterface: networkInterfaceWithSubscriptions
}); 
```

(Everything works like a charm locally, what am I doing wrong for deployment?)

Thanks for your time, any input appreciated

**Comment by gastongouron** [comment]
Quickfix:  requiring it manually w/o node modules to avoid non supported UglifyJS from react-script...

**Comment by rmosolgo** [comment]
Oops, I wonder if this line: 

https://github.com/rmosolgo/graphql-ruby/blob/5e08b52afee660e848df7408078e5155a0df2711/javascript_client/subscriptions/addGraphQLSubscriptions.js#L68

Should be re-written in plain old javascript: 

```js
unsubscribe: function(id) { 
```
