### ISSUE TITLE
Schema self.id_from_object(object, type, ctx) seems to return a base class?

### ISSUE THREAD

**Issue by emilebosch** [rmosolgo/graphql-ruby#1938]
Id from object's `type` seems to return type that lives above `GraphQL::Schema::Object`. 
Given this id from object the `type` returns a base class that lives above the `GraphQL::Schema::Object`.

I.e given this tree it returns Base

```
Types::User < Types::Base <  GraphQL::Schema::Object
```

Given this:

```
Types::User <  GraphQL::Schema::Object
```

It returns `Types::User`

Occurss in 1.9rc till 1.8.

```
   26:
   27:   def self.id_from_object(object, type, ctx)
   28:     byebug
=> 29:     GraphQL::Schema::UniqueWithinType.encode(object.class.name, object.id)
   30:   end
   31: end
   32:
```

If type directly inherits from schema object its fine

```
class Types::User < GraphQL::Schema::Object
  implements GraphQL::Relay::Node.interface
  global_id_field :id
 end
```

type = "User"

```
class Types::Base < GraphQL::Schema::Object
  implements GraphQL::Relay::Node.interface
  global_id_field :id
end

class Types::User < Types::Base
end
```

type = "Base"

Any ideas? Ill check it with a complete clean setup as well.

**Comment by freestyl3r** [comment]
Hello, use `type.name` without going through the class first.

**Comment by emilebosch** [comment]
@freestyl3r Can you explain what you mean? Afaik. The type in: 

```
 def self.id_from_object(object, type, ctx)
```

Should just be the graphql type it is called on. The issue is it returns the base class instead of the type really. There is some code in graphql  gemthat traverses the ancestors and and it seems to get confused there somewhere.

**Comment by freestyl3r** [comment]
The `type` is actually the correct one (`User` in your case).
You can verify it yourself by calling methods on it like `graphql_definition, all_fields, name` etc.
It's just that the `class` method returns something different.
I don't know the exact internals, but I found the following:

- [Class based API](http://graphql-ruby.org/schema/class_based_api.html#type-instances) suggests using `.graphql_definition` to get the underlying type object. 
- [Extensions](http://graphql-ruby.org/type_definitions/extensions.html#customization-overview) says that the “legacy” object may be accessed using .graphql_definition.
- [Schema generator template](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/generators/graphql/templates/schema.erb) uses `type_definition.name`.
- `global_id_field` uses the following class which in turn calls `id_from_object` [using `.graphql_definition`](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/relay/global_id_resolve.rb#L13) (if present).
- [Object identification](http://graphql-ruby.org/relay/object_identification.html#defining-uuids) guide uses `type_definition.name` in the 2nd example.

All the above reasons lead me to believe that the encrypt example that you saw in the [Object identification](http://graphql-ruby.org/relay/object_identification.html#defining-uuids) guide and uses `object.class.name`, is wrong and needs fixing.

**Comment by daemonsy** [comment]
Hi, there's an improvement to the documentation. I bumped into the same issue. 

https://github.com/rmosolgo/graphql-ruby/pull/2339/files#diff-d63623bd9c5e306e20efcbff6e21713bR42

I think in the type identification, you probably want to use `graphql_name`, that's consistent and also doesn't expose your internal naming structure. I think that is inline with what @freestyl3r said. 

Closing this because it's been a while, but feel free to reopen it if you're still facing issues with the identification interface.
