### ISSUE TITLE
Rescuing errors on lazy objects

### ISSUE THREAD

**Issue by DamirSvrtan** [rmosolgo/graphql-ruby#1939]
Hi! 👋 Thank you for your work on this gem!

I want to return partial data when an error occurs. Often time the error occurs in a lazy resoluted field.

I see that that is invoked in `lib/graphql/field`: (in the `obj.public_send`).

```
    module DefaultLazyResolve
      def self.call(obj, args, ctx)
        method_name = ctx.schema.lazy_method_name(obj)
        next_obj = obj.public_send(method_name)
        if ctx.schema.lazy?(next_obj)
          call(next_obj, args, ctx)
        else
          next_obj
        end
      end
    end
```

What would be a best way to catch an error like that? Would it be to override this class, and if so, in which manner?

Thanks!

**Comment by rmosolgo** [comment]
Hi, I don't know of a great built-in solution right now, but you can rescue the error in application code. Can you share an example of errors that might propagate up? Does your deferred object system have any kind of error handling?

**Comment by DamirSvrtan** [comment]
I am using the https://github.com/exAspArk/batch-loader gem, and as much as I see it does not have a way to handle errors. Basically I can get various different kinds of errors, Faraday Errors being one of the most popular ones. 

I could rescue the errors in application code, but from there, there isn't a clean way to add errors to the graphql execution.

A simple example of a lazy loaded resolution:

```ruby
field :project, Types::ProjectType, null: true, resolve: ->(object, _, _) do
  BatchLoader.for(object.project_id).batch do |ids, loader|
    ProjectRepo.filter_by_id(ids).each do |project|
      loader.call(project.id, project)
    end
  end
end
```

Would inserting a different class instead of the `DefaultLazyResolve` module be a good solve for this? How stable is that module?

**Comment by DamirSvrtan** [comment]
Hey @rmosolgo - sorry for closing this issue late, but the answer for this one is to create an instrumentation over fields that are supposed to be resolved in a lazy fashion.

Basically doing this:

```ruby
field.redefine do
  resolve(new_resolve_proc)
  lazy_resolve(new_lazy_resolve_proc)
end
```

For reference, I've used it here: https://github.com/exAspArk/graphql-errors/pull/14
