### ISSUE TITLE
undefined method `name=' for #<Class:0x00007fab7c0887c8> Did you mean? name

### ISSUE THREAD

**Issue by simonbowen** [rmosolgo/graphql-ruby#1942]
I'm trying to implement a simple GraphQL API using Sinatra, but I am hitting issues with defining a mutation.

This is my mutation
```ruby
class StartSpiderMutation < GraphQL::Schema::Mutation
  graphql_name 'start_spider'
  null true

  description "Kick off a spider crawling instance"

  argument :name, String, required: true

  field :name, String, null: false

  def resolve(name:)
    return {
      name: "Foo"
    }
  end
end
```

This is my schema

```ruby
require 'query'
require 'start_spider_mutation'

class MutationType < GraphQL::Schema::Object
  field :start_spider, field: StartSpiderMutation
end

class Schema < GraphQL::Schema
  query Query
  mutation MutationType
end
```

This is the error I get.

```
undefined method `name=' for #<Class:0x00007fab7c0887c8> Did you mean? name
```

I've looked at the documentation and I am a little confused since as far as I can tell, specifying the `graphql_name` should define the name for the schema to use for that particular mutation. I'm at a loss and not sure whether it's a bug or something I doing incorrectly.

**Comment by rmosolgo** [comment]
Hi, sorry about the hangup, but I can't debug without a stack trace. Feel free to add a stack trace and reopen this issue!

**Comment by simonbowen** [comment]
Hi,

Thanks for responding. I refactored a lot of the code and it started to work, sorry for not providing a stack trace in my original issue.

Many thanks.

**Comment by gauravtiwari** [comment]
@simonbowen Do you remember what was the issue in your code?

**Comment by cvandermeer** [comment]
@simonbowen Im curious as well, do you remember what was the issue in your code?

**Comment by simonbowen** [comment]
@gauravtiwari @cvandermeer 

So sorry. I no longer work on that project and can't remember what I did to get it working.

**Comment by cvandermeer** [comment]
@simonbowen it was a long shot :P,  thankyou
