### ISSUE TITLE
infinite resolve with union

### ISSUE THREAD

**Issue by jchatel** [rmosolgo/graphql-ruby#1945]
I added GraphQL::Schema::Union in my type description but when I do a graphql call (**not even involving this part**), puma doesn't return the call (high CPU) and I have to kill the process (CTRL+C doesn't work)

```ruby
class Types::CampaignStepType < GraphQL::Schema::Object
    graphql_name 'CampaignStep'
    field :id, ID, null: false
    field :variations, [Types::CampaignStepVariationType], null: false
end
  
class Types::BaseUnion < GraphQL::Schema::Union
end


class Types::CampaignStepVariationType < Types::BaseUnion
    graphql_name 'CampaignStepVariation'

    possible_types Types::EmailVariationType, Types::WaitVariationType

    # also tried this syntax with no luck
    #def self.possible_types
    #    [Types::EmailVariationType, Types::WaitVariationType]
    #end

    # I tried with and without this function, both leads to infinite loop
    def self.resolve_type(object, context)
        if object.is_a?(EmailVariation)
          Types::EmailVariationType
        else
          Types::WaitVariationType
        end
    end

end

class Types::EmailVariationType < GraphQL::Schema::Object
    graphql_name 'EmailVariation'

    field :id, ID, null: false
    field :something, String, null: true
end

class Types::WaitVariationType < GraphQL::Schema::Object
    graphql_name 'WaitVariation'

    field :id, ID, null: false

    field :value, Integer, null: true
end
```

I tried on 1.8.11 & 1.9.pre1, no luck

Also tried to have Types::CampaignStepVariationType directly deriving from Types::BaseUnion. No chance there either.

What am I doing wrong?

**Comment by jchatel** [comment]
I created a gist from the sample of the thread that seems to work in an infinite loop with puma (done with activity monitor): https://gist.github.com/jchatel/a53bdfdf571ae531c54ac587597d0feb
Probably won't tell us much, but just in case.

**Comment by jchatel** [comment]
For my graphql call:

```
query accountProfile {
  account(account_id: 1) {
    id
    campaign(campaignId: 1) {
      id
      steps {
        id
        variations {
          id
          ... on EmailVariation {
            id
            subject
            body
            __typename
          }
          ... on WaitVariation {
            id
            unit
            value
            __typename
          }
          __typename
        }
        __typename
      }
      __typename
    }
    __typename
  }
}
```

**Comment by jchatel** [comment]
cmd+C doesn't do anything, I'm assuming this is control+C you mean? It doesn't do anything either.

Because Puma runs 2 threads on my local machine, I launched a graphql request (moves one thread in infinite loop) and launched another page that display the dump of all threads.

I thought that was smart, but the result is puzzling. I don't see a thread that seems locked... (they are all sleeping except the one running the dump threads)

https://gist.github.com/jchatel/11a82d343d2af333b045514a09858474

If I call a second time a graphql request, then the 2 threads are dead and I can't call my dump threads function...

That's how I quickly printed the threads in my controller.

```ruby
  def dump_backtrace(thread)
    io = ""

    status = thread.status
    if status == nil
      status = "finished"
    elsif status == false
      status = "error"
    end

    io = io + "<br/>  Thread #{thread} status=#{status} priority=#{thread.priority} (current: #{Thread.current == thread})<br/>"
    if thread.backtrace
      thread.backtrace.each {|bt|
        io = io + "      #{bt}<br/>"
      }
    end

    return io
  end

  def thread_dump
    result = ""
    
    Thread.list.select {|thread| result = result + dump_backtrace(thread)}.count

    render text: result.to_s
    return
  end
```

Any ideas?

**Comment by jchatel** [comment]
ok, the problem is on the other process, not sure how I can access threads from the other process. I'm not sure how to get the ruby stack with gdb either

**Comment by jchatel** [comment]
Ok, I installed the awesome rbtrace.

Thread dumps is no luck (sendto(17): No buffer space available), apparently there are too much to display.

So I tried another approach, I used rbtrace to display all function that were slower than 1 millisec (basically printing the entire function path).

I'm not sure how useful that is. I had to stop it at some point, it seemed to be locked in a loop in ActiveSupport.

https://gist.github.com/jchatel/5ce455ba2b384d746e043ecd66266d93

Any idea? :/

**Comment by rmosolgo** [comment]
Interesting, all the way at the bottom I see: 

```
                                                                          ActiveSupport::Dependencies#remove_constant <0.001064>
                                                                          ActiveSupport::Dependencies#remove_constant <0.001089>
                                                                          ActiveSupport::Dependencies#remove_constant <0.001215>
                                                                                ActiveSupport::Dependencies#load_missing_constant <0.001073>
                                                                              ActiveSupport::Dependencies::ModuleConstMissing#const_missing <0.001211>
                                                                            Module#const_get <0.001256>
                                                                          ActiveSupport::Dependencies#remove_constant <0.001753>
                                                                          ActiveSupport::Dependencies#remove_constant <0.001035>
                                                                          ActiveSupport::Dependencies#remove_constant <0.001220>
```

I've seen that happen before where Rails's autoloading can get stuck in [infinite loops](https://github.com/rails/rails/pull/31803) in some cases. 

You could try adding this initializer which will print out load/remove constant messages: 

https://gist.github.com/rmosolgo/4eba313cb21189d952152ce3f1a6135a

That will give a clue _which_ constants Rails is getting stuck on, then we can look at those files to try to figure out why they're causing a loop.

**Comment by jchatel** [comment]
Bingo. It keeps doing this in loop:

```
     (done) load_missing_constant(Object, Mutations)
        (done) remove_constant(Mutations)
        remove_constant(Mutations)
          load_missing_constant(Object, Mutations)
          (done) load_missing_constant(Object, Mutations)
        (done) remove_constant(Mutations)
        remove_constant(Mutations)
          load_missing_constant(Object, Mutations)
          (done) load_missing_constant(Object, Mutations)
        (done) remove_constant(Mutations)
        remove_constant(Mutations)
          load_missing_constant(Object, Mutations)
          (done) load_missing_constant(Object, Mutations)
        (done) remove_constant(Mutations)
        remove_constant(Mutations)
          load_missing_constant(Object, Mutations)
          (done) load_missing_constant(Object, Mutations)
        (done) remove_constant(Mutations)
        remove_constant(Mutations)
          load_missing_constant(Object, Mutations)
          (done) load_missing_constant(Object, Mutations)
        (done) remove_constant(Mutations)
        remove_constant(Mutations)
          load_missing_constant(Object, Mutations)
          (done) load_missing_constant(Object, Mutations)
        (done) remove_constant(Mutations)
        remove_constant(Mutations)
          load_missing_constant(Object, Mutations)
          (done) load_missing_constant(Object, Mutations)
        (done) remove_constant(Mutations)
        remove_constant(Mutations)
          load_missing_constant(Object, Mutations)
          (done) load_missing_constant(Object, Mutations)
        (done) remove_constant(Mutations)
        remove_constant(Mutations)
          load_missing_constant(Object, Mutations)
          (done) load_missing_constant(Object, Mutations)
        (done) remove_constant(Mutations)
        remove_constant(Mutations)
          load_missing_constant(Object, Mutations)
          (done) load_missing_constant(Object, Mutations)
        (done) remove_constant(Mutations)
        remove_constant(Mutations)
          load_missing_constant(Object, Mutations)
          (done) load_missing_constant(Object, Mutations)
        (done) remove_constant(Mutations)
        remove_constant(Mutations)
          load_missing_constant(Object, Mutations)
          (done) load_missing_constant(Object, Mutations)
        (done) remove_constant(Mutations)
        remove_constant(Mutations)
          load_missing_constant(Object, Mutations)
          (done) load_missing_constant(Object, Mutations)
        (done) remove_constant(Mutations)
        remove_constant(Mutations)
          load_missing_constant(Object, Mutations)
```

**Comment by rmosolgo** [comment]
Ok, cool! I'm guessing that you're using mutations as a namespace, like `app/graphql/mutations`, is that right? (This actually might be the _same_ error in the PR I linked above. What Rails version are you on? The patch I linked above is on 5.2+.)

I _think_ the problem is that some _other_ error causes this infinite loading. So the catch is, what's the _other_ error. There's probably something in one of the files that defines `class Mutations::Something ...`. 

One way to test it is to comment out your `mutation(Types::Mutation)` configuration in the schema, and see if it will run queries. By commenting that out, it will prevent Rails from loading the constant. 

If it works _without_ that configuration, I recommend basically binary-searching the code: re-enable `mutation(Types::Mutation)`, then comment out half of the fields in your `Types::Mutation`, so that the corresponding mutation classes aren't loaded, and see if the error appears. If it does, comment out half of the remaining mutations. If it doesn't, uncomment the ones you commented and comment out the ones that were previously active. And so on, until you can isolate the one that's raising an error. 

Then modify the file so at the top and bottom it has 

```ruby
begin 
# ... 
rescue 
  puts $! 
  puts $!.backtrace 
  raise 
end 
```

(Or however you like to debug errors)

**Comment by jchatel** [comment]
You are a star. I did have a directory under graphql called mutations... for mutations. So yeah, that was a lot of :  field :setInactivityDeletion, Mutations::SetInactivityDeletionMutation.field

I renamed the folder to Mutation (without s) and this worked. Kind of scary.

I'm still on good old 4.2.10 :) Great report you did on Rails.

I now have another error with unions and resolve_type not defined. I'll open another issue :)

Thanks!

**Comment by jchatel** [comment]
Solved my problem by adding this:
```ruby
resolve_type ->(record, ctx) do end
```

in my 
```ruby
QuickMailSchema = GraphQL::Schema.define do
```
function.

Would be useful to add it in the help: http://graphql-ruby.org/type_definitions/unions because I would never have guessed why my resolve function was not working without reading github issues. Or I get it all wrong :)
