### ISSUE TITLE
Subscriptions trigger in Sidekiq is not working

### ISSUE THREAD

**Issue by mcdave029** [rmosolgo/graphql-ruby#1950]
Rails: 5.2.1
Ruby: 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin17]
Sidekiq: 5.2.3
GraphQL: 1.8.11
Redis server v=5.0.0 sha=00000000:0 malloc=libc bits=64 build=2693b64502c71820
Actioncable: 5.2.1

Hello, can i ask if its possible to use subscriptions trigger in sidekiq worker?
`MySchema.subscriptions.trigger("myField", {}, active_record_object)`
this seems fine in `after_commit` model callbacks but when moved in Sidekiq worker it doesn't trigger or even sending a broadcast to my client js app. any ideas how to work on this? thanks 😊😅. Btw already tried it in model callbacks as i said and its working. Just in sidekiq worker.

**Comment by rmosolgo** [comment]
I expect it to work! What have you done to debug? For example, if you inspect `active_record_object`, does it look like what you expect? Is there an error raised in the background job? How is the job enqueued?

**Comment by mcdave029** [comment]
I created a repo for checking https://github.com/mcdave029/test-subscriptions. there is no error raised in Job logs. also creating task object in model is also not sending subscriptions but creating it in mutation did send the broadcast. My guess is subscription broadcast only works in rails server thread? Thanks for the help. 😇

**Comment by mcdave029** [comment]
Ooops! my bad i missed some documentation of cable. anyways this fixed my problem https://stackoverflow.com/a/35304453/10386293 😅
