### ISSUE TITLE
Improve undefined method `unwrap' for nil:NilClass error message

### ISSUE THREAD

**Issue by stubailo** [rmosolgo/graphql-ruby#1952]
Right now, if you pass a class that doesn't exist, or somehow ends up being `nil` into a `field` declaration, you get a pretty cryptic error message from inside the library. We're running into this a lot at Stripe and it would reduce confusion if the exception was something like `nil passed to the type: argument of MyType.field_name, but expected a class`.

**Comment by rmosolgo** [comment]
😖  How frustrating! Could you share an example stack trace of that error, or some code that might produce it? That would help make sure we handle it in the right spot.

**Comment by stubailo** [comment]
Next time we see this pop up I'll make sure to get the stack trace!

**Comment by rmosolgo** [comment]
I'm going to close this because I guess it hasn't happened for quite a while. But if you run into it again, please do share the details!
