### ISSUE TITLE
Improve error message for snake case vs camel case in queries

### ISSUE THREAD

**Issue by holic** [rmosolgo/graphql-ruby#1953]
For a Ruby GraphQL schema defined like
```rb
class Person < GraphQL::Schema::Object
  field :username, String, null: false
  field :first_name, String, null: false
end
```
And a query like:
```graphql
query {
  people {
    username
    first_name
  }
}
```
I get an error like this:
```
Field 'first_name' doesn't exist on type 'Person'
```

Since we know that we have a field defined with `first_name`, but expect it to be queried like `firstName`, is it possible to improve the error message to point to/suggest the correct field name? As someone new to GraphQL and graphql-ruby, this had me stuck for a non-trivial amount of time wondering what I did wrong!

An improvement might look like:
```
Field 'first_name' doesn't exist on type 'Person'. Did you mean `firstName`?
```

**Comment by rmosolgo** [comment]
I wish I had time to work on this improvement, but I don't :'( I'm going to close this because I don't plan to work on it, but if someone wants to submit an improvement, I'd be glad to review it!
