### ISSUE TITLE
Camel and Snake Case with a Single Schema

### ISSUE THREAD

**Issue by jdalt** [rmosolgo/graphql-ruby#1963]
Currently we are converting our GraphQL API from the DSL definition to the class based API. Given that the class based API makes it easy to work with Ruby/Rails conventions and the GraphQL conventions favor camel case, we'd like to convert our API to camel case from it's current state in snake case.

In my opinion, the ideal version of this process would include the following properties:
  1. incremental conversion of each file to the class based api
  2. retain a single schema (types should not be duplicated across the class based definition and the DSL)
  3. serve the API in both camel and snake case (either with two endpoints or multiplexed on a single endpoint based on a header)

To implement this strategy, I've tried to create two top level 2 Schema objects and use field instrumentation plus some (maybe evil?) code to transform arguments in the hope that I can retain a single schema (in the sense of 2 -- that all logic and types are defined once). 

Example trying to convert schema to Camel Case:
```
module FieldInstrumentation

  class CamelCaser

    def instrument(type, field)
      args = field.arguments.values
      field.arguments = {}
      args.each do |arg|
        if !arg.metadata[:type_class] # these are types from the DSL
          arg.as = arg.name.to_sym
          arg.name = arg.name.camelize(:lower)
        end
        field.arguments[arg.name] = arg
      end
      field.redefine(name: field.name.camelize(:lower))
    end

  end
end
```
However this fails to account for Input objects whose arguments I'm not able to redefine with the field instrumentation strategy above.

What I would appreciate (enormously, thank you so much for building this incredibly powerful gem!!) is some advice on whether this approach makes sense and whether there's a way to transform the Input types.

I've tried iterating `Schema.types`, picking out the Input types, and transforming their arguments. This successfully changes them in the documentation (on the introspection query) but not when a normal query is executed. It seems like the Input arguments are rebuilt when the query executes.

Do I have other options for using a single schema to do both camel and snake case? Is it possible to create two schema objects with different Input arguments? Any insight greatly appreciated. Thank you!

**Comment by rmosolgo** [comment]
Hi! You should be able to migrate type-by-type. The new API is meant to be backwards-compatible, and for my own work, I migrated the schema first, then types according to their kind (objects, then unions, then inputs, etc). 

If you don't want the auto-camelization, you can use `camelize: false`. (You can [make it the default, too](http://graphql-ruby.org/fields/introduction#field-parameter-default-values).)

How about trying to do it with only _one_ schema class? I really can't guess what would happen trying to merge two schemas 😆

**Comment by jdalt** [comment]
@rmosolgo 
I have the `camelize: false` default solution working (although it might misbehave with automatically generated payload types), but the problem is I'm greedy and I want a camel and snake version so that I can ultimately have a camel case version of the API in the future while still serving my existing mobile clients using the snake case version of the API.

**Comment by rmosolgo** [comment]
How about implementing `def self.field` to create _two_ fields then? For example: 

```ruby 
def self.field(*args, camelize: false, **kwargs, &block) 
  if camelize == false 
    # Also make a camelized field: 
    field(*args, camelize: true, **kwargs, &block) 
  end 
  super 
end 
```

?

**Comment by jdalt** [comment]
I'm already able to make two copies of the schema with *fields* in camel and snake. I'm able to do this with the *arguments* as well. I'm not able to make 2 copies of the *inputs*.

Do you have a suggestion for making Input arguments in both camel and snake?

For your double definition solution, it seems like there might be major complexity around making required arguments since duplicate arguments in camel and snake would both be required.

**Comment by rmosolgo** [comment]
> 2 copies of the _inputs_.

What do you mean by that? Could you share an example of what you're trying to duplicate? 

> complexity around making required arguments

Yeah, that's a bummer. One alternative is is to do an AST transformation _before_ running the query, for example, on 1.9-dev, you can create an AST visitor that creates a copy of the document with changes applied: https://github.com/rmosolgo/graphql-ruby/blob/1.9-dev/guides/language_tools/visitor.md

**Comment by jdalt** [comment]
I don't have a strategy to put the `Input` objects (http://graphql-ruby.org/type_definitions/input_objects.html) into two different cases. The field instrumentation in my first comment can handle fields and the arguments on fields (in a kind of gross dark magic way), but not `Input` objects on fields.

For example say I had a had a query like the following:
`import_cars(car_id: "id_str", pagination: { page_size: 10, selected_page: 1 }) { ... }`

My `CamelCaser` that uses field instrumentation would get me:
`importCars(carId: "id_str", pagination: { page_size: 10, selected_page: 1 }) { ... }`

I got everything camelized but the arguments to the `pagination` Input object. It appears that arguments on a field are held in memory and accessed differently than those on `Input` objects. This makes sense since the Input objects are shared across multiple fields unlike field arguments.

I'm looking for a way to redefine Input objects on my Schema.

The AST visitor strategy might work although it doesn't have quite the same benefits as having two fully accurate and functional schemas -- the API documentation and validation will be accurate for both when I have two Schema objects whereas AST transformation will cause drift and inconsistencies between the two.

**Comment by anujbiyani** [comment]
@jdalt The approach I've come up with is to modify my `BaseMutation` class like so:

1. define both fields (snake_case and camelCase) in a module
    - if it's required, only make the camelCase version required
1. include that module in both `BaseMutation` and `BaseInputObject`
1. add a description that denotes the field as deprecated. (once inputs support deprecation (https://github.com/graphql/graphql-spec/pull/525) and graphql-ruby has implemented the feature, this can change to a proper deprecation warning)
1. monkey patch the `GraphQL::StaticValidation::RequiredInputObjectAttributesArePresent` validation so that it matches a snake_case field against the camelCase version

Drawbacks:
1. Sucks that the monkey-patch is needed, but until GraphQL itself supports deprecation this gem shouldn't have to support deprecated inputs, which in turn means the validator shouldn't have to care about snake_case AND camelCase fields.
1. The schema doesn't reflect that if you provide the snake_case field, the camelCase version isn't required.

```ruby
# Load the validation monkey-patch necessary for this module to work
require_relative "../monkey_patches/required_input_object_attributes_are_present"

module Mutations
  module BackwardsCompatibleArguments
    extend ActiveSupport::Concern

    class_methods do
      # all snake_case arguments created before upgrade to graphql 1.8 should be camelize false.
      # prior to 1.8, all client requests were snake_case and expected snake_case in response
      # this class method will also create a camelize: true version so clients
      # can update to camelCased queries
      #
      # in the case of a required field, only the camelCase version gets the required: true flag.
      # the below monkey-patch tweaks GraphQL's validation so that if the snake_case field
      # is passed, it passes the required validation for the camelCase version
      def argument(*args, camelize: true, required: false, **kwargs, &block)
        if camelize
          super
        else
          argument(*args, camelize: true, required: true, **kwargs, &block)
          super(
            *args,
            camelize: false,
            description: "deprecated, please use the camelCase version",
            required: false,
            **kwargs,
            &block
          )
        end
      end
    end
  end
end
```

```ruby
class Mutations::BaseMutation < GraphQL::Schema::RelayClassicMutation
  include Mutations::BackwardsCompatibleArguments

  # taken from https://graphql-ruby.org/mutations/mutation_classes.html
  object_class Types::BaseObject
  field_class Types::BaseField
  input_object_class Types::BaseInputObject
end
```

```ruby
class Types::BaseInputObject < GraphQL::Schema::InputObject
  include Mutations::BackwardsCompatibleArguments
end
```

```ruby
# copied from https://github.com/rmosolgo/graphql-ruby/blob/e9f4c664cd7a0be4887fe3ea8aecadee92894c6a/lib/graphql/static_validation/rules/required_input_object_attributes_are_present.rb#L34-L57
module GraphQL
  module StaticValidation
    class RequiredInputObjectAttributesArePresent
      private

      def validate_input_object(ast_node, context, parent)
        parent_type = get_parent_type(context, parent)
        return unless parent_type && parent_type.kind.input_object?

        required_fields = parent_type.arguments
          .select{|k,v| v.type.kind.non_null?}
          .keys

        present_fields = ast_node.arguments.map(&:name)

        # Change to make snake_case fields validate against camelCase fields for required-ness
        # e.g. if argument argument_with_underscores is required, and the argument is backwards-compatible (has camelize: false),
        # then passing argument_with_underscores and omitting argumentWithUnderscores will still work
        present_fields += present_fields.map { |name| ::GraphQL::Schema::Member::BuildType.camelize(name) }

        missing_fields = required_fields - present_fields

        missing_fields.each do |missing_field|
          path = [*context.path, missing_field]
          missing_field_type = parent_type.arguments[missing_field].type
          add_error(RequiredInputObjectAttributesArePresentError.new(
            "Argument '#{missing_field}' on InputObject '#{parent_type}' is required. Expected type #{missing_field_type}",
            argument_name: missing_field,
            argument_type: missing_field_type.to_s,
            input_object_type: parent_type.to_s,
            path: path,
            nodes: ast_node,
          ))
        end
      end
    end
  end
end
```

**Comment by daemonsy** [comment]
Hi, closing this because there hasn't been activity on the question for a while. 

Feel free to reopen it if there are any more queries.
