### ISSUE TITLE
Hook for unauthorized field

### ISSUE THREAD

**Issue by noaelad** [rmosolgo/graphql-ruby#1964]
The `unauthorized_object` hook does not get triggered when field-level authorization fails. It would be great if we had a hook for those cases and could raise an exception there as well.

**Comment by rmosolgo** [comment]
Hi! Thanks for the suggestion, I agree it's a bit odd that the field-level check is handled differently. I think adding a hook like you suggest would be great. 

I wonder if we could give it a default implementation to call through to `.unauthorized_object`. It would be nice to keep it simple at first, but allow customization for people who _want_ to treat those cases differently. 

Want to take a crack at implementing it??

**Comment by noaelad** [comment]
Yeah I like the idea of having the default implementation call through to `.unauthorized_object`, this is at least how I'd want this hook to work.
Absolutely I'll take a crack at it!

**Comment by rmosolgo** [comment]
Fixed by #1994 🎉
