### ISSUE TITLE
argument :as option for inputs

### ISSUE THREAD

**Issue by ngouy** [rmosolgo/graphql-ruby#1965]
ruby : 2.4.3
graphql-ruby : 1.8.x

Is there a way to have the "inverse" of `property`, or `hash_key` used by `GraphQL::ObjectType` -> `field` method
I thought it was through the `:as`  option but it doesn't works (for me)

my implementation:

```rb
#types/my_type.rb

Types::MyType = GraphQL::ObjectType.define do
  name "MyType"

  field :api_exposed_attr, type: types.String, property: :model_real_attr
end
```

```rb
#inputs/my_input.rb

Inputs::MyInput = GraphQL::InputObjectType.define do
  name "MyInput"

  argument :what_the_api_receive, types.String, as: :what_my_ruby_model_is_waiting_for
end
```

```rb
#mutations/update_object.rb
Mutations::UpdateObject = GraphQL::Field.define do
  name "UpdateObject"
  description "Updates Object"

  argument :id, !types.Int
  argument :object, !Inputs::MyInput

  type Types::MyType

  resolve ->(_, args, context) do
    object = MyModel.find(args.id)
    attributes = args.object.to_h
    # sadly I have
    # { what_the_api_receive: "my_value" }
    # I wish I could have
    # {what_my_ruby_model_is_waiting_for: "my_value" }
   attributes[:what_my_ruby_model_is_waiting_for] = attributes.delete(:what_the_api_receive)
   object.update!(attributes)
   object
end
```

Sorry if double post or if it's documentation, but I can't find the info after some researches.

**Comment by rmosolgo** [comment]
🤔  Yes, I would have expected `as:` to work! 

I'm not developing the `.define` API anymore, but if you want to add a failing test case to the gem, I'd be happy to help hunt for the solution. Or, if you migrate to the class-based API and `as:` still doesn't work, I can troubleshoot further.

**Comment by ngouy** [comment]
👍 
Class based api on the road, I'll keep you update

**Comment by rmosolgo** [comment]
I hope you found something that worked here. Feel free to open another issue if you have trouble with the class-based API!

**Comment by ngouy** [comment]
Sorry I didn't keep you updated at all.

All is working fine ! Thank you and sorry for the inconvenience
