### ISSUE TITLE
Web socket link re-authentication

### ISSUE THREAD

**Issue by casiodk** [rmosolgo/graphql-ruby#1966]
I can't find any documentation on how to re-authenticate my websocket connection, when for example signing in & out. 

Also I cant get connectionParams to work. Some documentation would be awesome :)

Thanks for awesome work driving this gem!

**Comment by rmosolgo** [comment]
Hi! 

Sorry, I'm not sure about that. Are you asking about how to use ActionCable? If so, you could probably find something in the ActionCable docs about signing in or out. Sorry I don't have more to offer!
