### ISSUE TITLE
New format (post 1.8) for mutation

### ISSUE THREAD

**Issue by jchatel** [rmosolgo/graphql-ruby#1968]
I've been battling for a couple of hours now trying to create mutation in the new new format (I like the clarity that new interface gives us, good move), but I keep bouncing my head around this error and I'm not sure where the problem is exactly (I'm suspecting a case or maybe the array, but I can't figure it out):

`
{"errors":[{"message":"AddProspectToCampaignInput isn't a defined input type (on $input)","locations":[{"line":1,"column":11}],"fields":["mutation"]},{"message":"Field 'addProspectToCampaign' doesn't exist on type 'Mutation'","locations":[{"line":2,"column":3}],"fields":["mutation","addProspectToCampaign"]},{"message":"Variable $input is declared by  but not used","locations":[{"line":1,"column":1}],"fields":["mutation"]}]}
`

I can't transform all my mutation in one go, so my mutation lives in an old root structure for mutations:

```ruby
Types::MutationType = GraphQL::ObjectType.define do
  name 'Mutation'

  #... many old syntax field : ... .field ...

  #new structure:

  mutation Types::AddProspectToCampaign
end

```

My class:

```ruby
class AddProspectToCampaign < GraphQL::Schema::RelayClassicMutation

  argument :campaign_id, ID, required: true
  argument :prospects, [Int], required: true

  field :total, Int, null: true 
  field :error, String, null: true 

  def resolve(campaign_id, prospects)
      # implementation specifics ...
  end

end
```

And my graph ql call:

  ```typescript
    let prospect_ids = prospects.map(a => a.id);

    const input = {
      campaignId: campaign_id,
      prospects: prospect_ids,
    };
  this.apollo
      .mutate({
        mutation: gql`
          mutation($input: AddProspectToCampaignInput!) {
            addProspectToCampaign(input: $input) {
              total
            }
          }
        `,
        variables: { input: input },
      })
```

Any help with decrypting the error message will be highly appreciated

edit: version 1.8.11

**Comment by rmosolgo** [comment]
Hmm, judging by this part: 

```
Field 'addProspectToCampaign' doesn't exist on type 'Mutation'
```

It seems like the mutation field is not being correctly applied to the root `Mutation` type. What if you print the schema definition, for example: 

```ruby
puts MySchema.to_definition
```

And look for your `type Mutation { ... }` definition. What fields do you see there? Is `addProspectToCampaign` on the list?

**Comment by jchatel** [comment]
Oh, I must have missed this notification.

I figured the same, and I managed to make it work by removing all the old code I had and starting from scratch.

Now I have my mutations working with the new format :)

Thanks for the puts tip. I'll definitely use it if I run into similar issues.
