### ISSUE TITLE
graphql-ruby@0.17.2 validation has broken mutations?

### ISSUE THREAD

**Issue by gjtorikian** [rmosolgo/graphql-ruby#197]
Hello! Since upgrading to `0.17.2`, we can't seem to get any of our mutations loaded. The error is:

```
ruby/2.1.0/gems/graphql-0.17.2/lib/graphql/schema/type_map.rb:23:in `[]=': Duplicate type definition found for name 'Payload' (RuntimeError)
```

It _looks_ like types are simply marked as `Payload`. Presumably, before, they were called `AddReactionPayload`, `RemoveReactionPayload`, etc. Some digging and debugging confirms this a bit:

```
[32, 41] in ruby/2.1.0/gems/graphql-0.17.2/lib/graphql/schema/reduce_types.rb
   32:       end
   33: 
   34:       def self.crawl_type(type, type_hash, context_description)
   35:         if type.kind.fields?
   36:           type.all_fields.each do |field|
=> 37:             reduce_type(field.type, type_hash, "Field #{type.name}.#{field.name}")
   38:             field.arguments.each do |name, argument|
   39:               reduce_type(argument.type, type_hash, "Argument #{name} on #{type.name}.#{field.name}")
   40:             end
   41:           end
(byebug) field.type
Payload
(byebug) type
Mutation
(byebug) type.all_fields.first
#<GraphQL::Field:0x007fba54ed3b98 @complexity=1, @arguments={"input"=>#<GraphQL::Argument:0x007fba54ed3800 @name="input", @type=Non-Null>}, @resolve_proc=#<Proc:0x007fba54ed3c38@ruby/2.1.0/gems/graphql-relay-0.11.2/lib/graphql/relay/mutation.rb:77 (lambda)>, @definition_proc=nil, @clean_type=Payload, @dirty_type=Payload, @name="addReaction">
```

Please let me know if I can provide more info for you!

**Comment by rmosolgo** [comment]
Hmm, I bet it some bug with lazy definitions, like some way of accessing the name doesn't run the definition properly ....

**Comment by rmosolgo** [comment]
Is your graphql-relay version 0.12.0 ?

**Comment by rmosolgo** [comment]
I pushed a test for this behavior here: 

https://github.com/rmosolgo/graphql-relay-ruby/commit/b4e491fad652dd1aa429709fc5db92fd0816a01a

You can see here where it must be coming blank: 

https://github.com/rmosolgo/graphql-relay-ruby/blob/0.12.x/lib/graphql/relay/mutation.rb#L95

Can you share a mutation definition with this issue?

**Comment by gjtorikian** [comment]
My mistake! Upgrading `graphql-ruby-relay` to 0.12.0 fixed the problem. Sorry for the false alarm.

**Comment by rmosolgo** [comment]
😌 hopefully this kind of compat issue will be a thing of the past after the next release!
