### ISSUE TITLE
[pro] Ordering causes error about ambiguous column

### ISSUE THREAD

**Issue by cheerfulstoic** [rmosolgo/graphql-ruby#1971]
We're getting an error on an ActiveRecord scope which is returned from a field.  The scope is matching other tables via a `joins` (though we've gotten this on `includes` too, I think) and gives as a "Mysql2::Error: Column 'ID' in order clause is ambiguous"

Looking into the `graphql-pro` gem, I think the problem lies in `lib/graphql/pro/relation_connections/order.rb` on line 90:

```ruby
ordered_relation = ordered_relation.order("#{pkey} asc")
``` 

I think that if you specify it with this syntax it will specify the table name automatically:

```ruby
ordered_relation = ordered_relation.order(pkey => :asc)
```

It seems to be making our test pass, at least

**Comment by rmosolgo** [comment]
Sorry about the bug and thanks for sharing your workaround! I'll get a fix like this into graphql-pro soon and follow up here. IIRC, I have to use a string to support some very old ActiveRecord versions 😬 ! But I'll give it a try. Thanks again.

**Comment by cheerfulstoic** [comment]
Thanks!  And right, I didn't think about old versions of `ActiveRecord`.  I actually started with a solution like this:

```ruby
ordered_relation = ordered_relation.order("`#{ordered_relation.table_name}`.`#{pkey}` asc")
```

That definitely worked, but I switched to the other because of the brevity.  I think `table_name` is available in older versions of Rails, though, so hopefully that should work.

**Comment by rmosolgo** [comment]
🚢  in graphql-pro 1.9.3! Please do let me know if it give you any more trouble.

**Comment by cheerfulstoic** [comment]
Awesome, thanks!
