### ISSUE TITLE
[Pro] relay client integration with ably?

### ISSUE THREAD

**Issue by modosc** [rmosolgo/graphql-ruby#1975]
i noticed there's an apollo integration but no relay integration. we really want to try out ably but we use relay, was this intentionally left out?

**Comment by rmosolgo** [comment]
No, it was not intentionally left out! It just wasn't requested yet. Ably is so similar to Pusher, I think the easiest approach is to port one to the other. Want to give it a try? Otherwise I can take a look soon.

**Comment by modosc** [comment]
https://github.com/rmosolgo/graphql-ruby/pull/1977
