### ISSUE TITLE
[pro] Subscriptions::RedisStorage#write_subscription doesn't handle parsed queries correctly

### ISSUE THREAD

**Issue by modosc** [rmosolgo/graphql-ruby#1980]
using `AblySubscriptions` if i try to run  `MySchema.execute(document: GraphQL.parse(query_string))` and `query_string` has a subscription in it then i get a [No query string was present](https://github.com/rmosolgo/graphql-ruby/blob/368e68a3979c8a7453f6a7466ff80d401fbede68/lib/graphql/query.rb#L316) error whenever i try to trigger that subscription.

i traced it down to `GraphQL::Pro::Subscriptions::RedisStorage#write_subscription` and worked around it with a monkeypatch that does something like:
```
    query_string = query.document ? query.document.to_query_string : query.query_string

    query_data = JSON.dump({
      query_string: query_string,
```
but it would be cool to get an actual fix in.

**Comment by rmosolgo** [comment]
Derp! Thanks for sharing this report and your work-around. I'll get a fix into graphql-pro and follow up here.

**Comment by rmosolgo** [comment]
🚢  in graphql-pro 1.9.3! I ended up doing the reverse logic: 

```ruby
    query_string = query.query_string ? query.query_string : query.document.to_query_string 
```

Because I think that will avoid _re_-stringifying an already-parsed document, if the document was previously parsed. Anyways, let me know if you have any more trouble with it!
