### ISSUE TITLE
Relay connection paging with Searchkick results?

### ISSUE THREAD

**Issue by usamah82** [rmosolgo/graphql-ruby#1985]
In our app, we're doing the searching and sorting in Searchkick instead of ActiveRecord, since it's simpler to query intentionally denormalized / flattened, reindexed data on Searchkick than having to fight with complex joins across normalized data structure in the actual DB.

Searchkick returns the results, but there's a cost to it. In our implementation we still have GraphQL resolving the types assuming the underlying data as ActiveRecord entities, so we have to enumerate the Searchkick results and return them back as ActiveRecord entities in an array (not `ActiveRecord::Relation`). This means we no longer lazy load.

The short story behind it is that if we attempt to lazy load by returning the relation

```ruby
EntityClass.where(id: searchkick_result_ids)
````

there's a possibility that we lose the ordering / sort done in Searchkick - e.g PostgreSQL doesn't guarantee ordering when using WHERE IN(..) - [here](https://dba.stackexchange.com/questions/59394/order-of-returned-record-with-in-statement-postgres).

One way for us to minimize the cost is to only load the ActiveRecord entities that we need early on. This means we need to paginate in Searchkick instead of paginating within the Relay Connection.

Questions:

- Should we come up with a custom Relay Connection implementation, OR, 
- Should we just totally do away with Relay Connection instead, and just custom resolve it? Seems like the current Relay Connection implementations (`ArrayConnection`, `RelationConnection`) are mostly about pagination concerns anyway.

Any tips would be much appreciated!

**Comment by usamah82** [comment]
Ooops closing this. Apparently I didn't eager load properly. My bad.

**Comment by apuntovanini** [comment]
Hey @usamah82, what did you end up using?
We tried wrapping a custom connection as well, because passing results to AR actually looses ordering, but we have some issues with calculating offset and limit
Would you mind sharing your solution?
Thanks!

(I know it's long time ago, but I couldn't find many solutions about it)

**Comment by usamah82** [comment]
@apuntovanini I don't really remember, but I would guess you just need to do your own pagination.

- basically index whatever details you need in Searchkick / Elasticsearch so that you don't need to fallback to DB. Usually searches are done on `#index` action, and you don't need to return all model attributes - you just need to return the important ones to show in the listing. Basically index and show only attributes you need.
- for efficiency, pass along the pagination params and implement paginated search query on Searchkick itself. Basically filter what you need, early on at the source
- resolve using whatever Searchkick returns back to you

**Comment by apuntovanini** [comment]
Thanks @usamah82

Eventually we did something similar, except that we passed query parameters directly to the custom connection, so we could manage pagination with `search_after` (we needed to wrap an infinite scroll) and not with offset and limit
Thanks a lot!
