### ISSUE TITLE
Revert "Remove needless nil check"

### ISSUE THREAD

**Issue by maletor** [rmosolgo/graphql-ruby#1990]
Sorry for posting this in issues but if you're anything like me, GitHub notifications get lost. Much easier to find in "Issues".

https://github.com/rmosolgo/graphql-ruby/commit/843a7bc3ad62b92e37a729222473b50ab423c0b3#commitcomment-31559479

**Comment by rmosolgo** [comment]
Hey, yes, thanks for opening it here :) I'm definitely happy to revert this check, but, do you know _why_ there happens to be `nil` here? I'd live to get an example in the test suite so I don't remove this again 😬

**Comment by maletor** [comment]
I'm a bit hazy on why it's `nil` but it would appear that because the field is setup like this (again, for legacy reasons):

```ruby
GraphQL::Schema::Field.from_options(
  name: "",
  mutation: self
).graphql_definition
```

**Comment by maletor** [comment]
#2000
