### ISSUE TITLE
Get all enums as array (GraphQL::Schema::Enum)

### ISSUE THREAD

**Issue by hahmed** [rmosolgo/graphql-ruby#1992]
When passing in a default argument to my `field` I want to be able to pull out the enums into an array. (By default I want to list all project statuses), I have the values already defined in my enum type, is there an easier way to pull out this info?

I have declared in my `QueryType` a field, which has an argument:

```
argument :status, [Types::ProjectStatusEnum],
               required: false,
               default_value: Types::ProjectStatusEnum.enum_values
```

`ProjectStatusEnum` inherits from the BaseEnum below:

```
module Types
  class BaseEnum < GraphQL::Schema::Enum
    def self.enum_values
      values.values.map(&:value)
    end
  end
end
```

My project statuses are declared like so;

```
class ProjectStatusEnum < Types::BaseEnum
    value 'DRAFT', value: 'draft', description: 'Project in draft mode.'
    value 'PROGRESS', value: 'progress', description: 'Project has begun ✨.'
end
```

Wondering how common this is, and if you would like me to open a PR?

**Comment by rmosolgo** [comment]
Hi! I'm glad you found something that worked for you. Here's another way to think of it: 

In your application, there's probably a concept of a _Project_, whose status is in one of _ProjectStatus_'s values. Probably, the Project class (maybe `app/models/project.rb`?) should have the "master list" of statuses. 

Your application has a GraphQL API as a layer _on top_ of the core logic. The GraphQL layer should be derived from the application logic. So, if you have a master list of project statuses in the business logic layer, I recommend using _that_ to populate the GraphQL layer. For example: 

```ruby 
class ProjectStatusEnum < Types::BaseEnum
  # Use the master list of statuses to generate the API 
  Project::STATUSES.each do |project_status| 
    value(project_status.name.upcase, value: project_status.name, description: project_status.description)
  end 
end 
```

And in the same way for arguments: 

```ruby 
argument :status, Enums::ProjectStatus, required: false, 
  default_value: Project::STATUSES.map(&:name) 
```

That way, your application has a _single_ source of truth, and the source of truth is located in the _application layer_, not the API layer. 

Anyhow, glad you found a solution, just thought I'd share!
