### ISSUE TITLE
Interface Type - undefined method for Object methods

### ISSUE THREAD

**Issue by Fleick** [rmosolgo/graphql-ruby#1993]
Hey there,
by refactoring from .define to class Method I run into another issue. In the project there are some interfaces, with these it seems as if there is an error with the inheritance of GraphQL::Schema::Object. For all types that implement an interface I get the error: ```#<NoMethodError: undefined method `metadata' for Types::SeminarsInheritance::FreeSeminarType:Class>``` (of course with the respective type). The error occurs in: ```lib/graphql/schema/member/instrumentation.rb:103:in `block in proxy_to_depth'```, since I don't overwrite metadata anywhere the default implementation of GraphQL::Schema::Object should actually apply here?
Implementation:

```ruby
module Types::BaseInterface
  include GraphQL::Schema::Interface
end
```
```ruby
module Types
  class RootObject < GraphQL::Schema::Object
    field_class Types::CustomField

    field :updated_at, Types::DateTimeType, null: false
    field :created_at, Types::DateTimeType, null: false
  end
end
```
```ruby
module Types::SeminarsInheritance::SeminarInterface
  include Types::BaseInterface
  description 'Interface for Seminar Types'
  field_class Types::CustomField

  orphan_types Types::SeminarsInheritance::FreeSeminarType,
               Types::SeminarsInheritance::InhouseSeminarType,
               Types::SeminarsInheritance::WebinarType,
               Types::SeminarsInheritance::TelecourseType
# some field definitions
end
```
```ruby
module Types::SeminarsInheritance
  class FreeSeminarType < Types::RootObject
    implements Types::SeminarsInheritance::SeminarInterface
    description 'Free Seminar'

  end
end
```

I have although tried:
```ruby
module Types::SeminarsInheritance
  class FreeSeminarType < GraphQL::Schema::Object
    implements Types::SeminarsInheritance::SeminarInterface
    description 'Free Seminar'

  end
end
```
=> Same result

Where is my fault?

**Comment by Fleick** [comment]
After long searching with a coworker I found the issue - my fault.
For all future people running through this issue:
In the new class Methode the resolve_type method of interfaces must return anl graphql object and not the class. So the new type return is (for the case above) ```Types::Seminars::FreeSeminarType.to_graphql``` instead of only ```Types::Seminars::FreeSeminarType``` in old define method

**Comment by rmosolgo** [comment]
Glad you found it! By the way, I recommend using `.graphql_definition` instead of `.to_graphql`, otherwise, you may end up with duplicate copies of the same GraphQL type. (`.to_graphql` creates a new backwards-compatible type; `.graphql_definition` returns a previously-cached object.)

**Comment by mattcowles** [comment]
Greetings,

I am having the issue reported above and was not clear on what the change was to make this work. You mention that the new return type must include the .to_graphql or .to_graphql_definition but how exactly is this specified?

Thanks!
