### ISSUE TITLE
Guide: Mutation authorization

### ISSUE THREAD

**Issue by ch-tactica** [rmosolgo/graphql-ruby#1997]
# Versions

    graphiql-rails (1.5.0)
    graphql (1.8.2)
    rails (5.2.2)

It doesn't appear that the `authorized?` functionality is used in mutations, take the following example for instance:

Mutation:
```
module Mutations
  class UpdateGoalSelection < BaseMutation
    argument :id, ID, required: true
    argument :reason, String, required: true

    field :goal_selection, GoalSelectionType, null: true
    field :errors, [String], null: false

    def authorized?
      raise
    end

    def resolve(id:, reason:)
     ...
    end
  end
end
```

I'm testing the mutation above with the following mutation query, I'm expecting it to always raise an error when the authorization is performed (just to verify if it's indeed being called).
```
mutation {
  updateGoalSelection(input: {reason: "adsasdasd", id: "f539e9d9-0512-41b3-822b-daa79cc8ee88"}) {
    errors
    goalSelection {
      reason
      id     
    }
  }
}
```

Instead, the mutation is performed without a hitch, and I get the following output:

```
{
  "data": {
    "updateGoalSelection": {
      "errors": [],
      "goalSelection": {
        "reason": "adsasdasd",
        "id": "f539e9d9-0512-41b3-822b-daa79cc8ee88"
      }
    }
  }
}
```

As trite as the example above might be, I also tried something like the following meeting similar results:

```
def authorized?
  return false, { errors: ["Can't do it"] }
end
```

**Comment by rmosolgo** [comment]
Hi, that feature was added in 1.8.7, could you please update your graphql-ruby version and give it another try? (https://github.com/rmosolgo/graphql-ruby/blob/master/CHANGELOG.md#new-features-5) Please reopen if you still have this issue!

**Comment by mhuggins** [comment]
I'm on 1.8.11 and this doesn't work.  I opened #2025 with a similar question.
