### ISSUE TITLE
Consider separating out GraphQL parsing

### ISSUE THREAD

**Issue by devknoll** [rmosolgo/graphql-ruby#2]
Facebook's implementation actually compiles GraphQL to an AST on the client side. This seems to be a prerequisite for Relay to work (maybe @leebyron or @schrockn can comment on this).

I propose that graphql-ruby starts moving in that direction. Instead of parsing GraphQL, the interface would accept and process a JSON AST. On the client side, you could use something like https://github.com/ooflorent/graphql-parser (or the Facebook reference implementation when it's released).

This would free graphql-ruby from worrying about parsing the query and handling variables. Everything would just come in the JSON AST. You could also fall back to processing a full query (for non-JS clients) using something like therubyracer.

I'm happy to work on this, but I'd like to hear your thoughts.

**Comment by devknoll** [comment]
Closing because @josephsavona [proved me wrong](https://twitter.com/en_JS/status/591050229073321985) :smile:

**Comment by rmosolgo** [comment]
Cool, thanks for checking it out anyways. Seems like its hard to do too much more til we get a proper spec etc!

**Comment by devknoll** [comment]
Have you done anything about schema descriptions yet? Facebook's definitions look like https://twitter.com/schrockn/status/567902849272659968/photo/1

**Comment by rmosolgo** [comment]
Support here is pretty half-hearted (and not documented) but I plan to "get on their level" and require descriptions at build time!

**Comment by rmosolgo** [comment]
@devknoll I made node descriptions required here https://github.com/rmosolgo/graphql-ruby/commit/dbf49884a9a79218913adc93dff7093e9a6bedd6 and I'm thinking a bit about the field description API here https://github.com/rmosolgo/graphql-ruby/pull/3

I'm not feeling great about that field description API though, it feels long-winded!
