### ISSUE TITLE
Print descriptions as strings when printing schema

### ISSUE THREAD

**Issue by rylanc** [rmosolgo/graphql-ruby#2002]
The GraphQL SDL spec [specifies strings or block strings](https://facebook.github.io/graphql/June2018/#sec-Descriptions) as the format for field/type/argument descriptions. In the current version of graphql-ruby, strings are printed using comments (although, it looks like block string descriptions are parsed correctly). It should be easy enough to change, but before I put in too much work, I wanted to get some thoughts:
1. Should the printer still support comment descriptions?
2. If so, should the default be block strings or comments?

**Comment by rmosolgo** [comment]
Hey, thanks for raising this issue! I think it would be great to update the printer to use block strings. For compatibility, it's nice to _parse_ both comments and block strings, but I think defaulting to block strings would be a great update. 

I don't think it's important to support comment descriptions. The only use I know for the schema printer is internal tooling, and it should be alright to make the switch to block strings.
