### ISSUE TITLE
[pro] Pundit integration fails with plain Array field

### ISSUE THREAD

**Issue by cainlevy** [rmosolgo/graphql-ruby#2008]
## Context

Every mutation in my GraphQL API may optionally return a list of validation errors (as data). This is typed as:

```ruby
field :errors, [ServiceError], null: true
```

Now I'm adding Pundit integration, and my tests fail with:

```
GraphQL::Pro::PunditIntegration::PolicyNotFoundError: No policy found for:

- Type: ServiceError
- Runtime value: `[#<struct ServiceError field="description", code=:blank>, #<struct ServiceError field="name", code=:too_long>]`

Pundit error: Pundit::NotDefinedError, unable to find scope `ServiceError::ServiceErrorPolicy::Scope` for `[#<struct ServiceError field="description", code=:blank>, #<struct ServiceError field="name", code=:too_long>]`
```

## Bug

The problem is that `Pundit::PolicyFinder` expects an Array to be a [list of constant names](https://github.com/varvet/pundit/blob/master/lib/pundit/policy_finder.rb#L72-L76), not a list of values. Thus, any attempt to return more than one ServiceError will fail the policy lookup.

This logic is not problematic for Relations, because a Relation is not an Array.

## Example

```
irb(main):001:0> Pundit::PolicyFinder.new(nil).send(:find, [ServiceError.new])
=> "::ServiceErrorPolicy"
irb(main):002:0> Pundit::PolicyFinder.new(nil).send(:find, [ServiceError.new, ServiceError.new])
=> "ServiceError::ServiceErrorPolicy"
irb(main):003:0> Pundit::PolicyFinder.new(nil).send(:find, [ServiceError.new, ServiceError.new, ServiceError.new])
=> "ServiceError::ServiceError::ServiceErrorPolicy"
```

## Suggestion

Disable scoping logic for plain arrays. It's a conceptual mismatch.

## Workarounds

* `scope: false` on everything
* monkey patch or override `ScopeByPolicy` logic

**Comment by rmosolgo** [comment]
> Disable scoping logic for plain arrays.

👌 Thanks for the bug report, I'll take a look and follow up here.

**Comment by aarons22** [comment]
Any progress/update on this? We're currently blocked on a few fronts because of this bug. Thanks 😄

**Comment by rmosolgo** [comment]
Thanks for the bump here, this slipped off my radar over the holidays 😊  I just pushed graphql-pro 1.9.5 which includes the same kind of solution that @cainlevy posted. Thanks for sharing your workaround and let me know if you run into any trouble with that new version!
