### ISSUE TITLE
Guide: Introduction

### ISSUE THREAD

**Issue by CumbersomeFugly** [rmosolgo/graphql-ruby#2014]
I'm not sure if this is a bug, but I'm getting an error when I try to require arguments.

I'm using Ruby 2.5.3 with graphql 1.9.0pre1 (I've also tried with 1.8.11) and graphiql-rails 1.4.4.

Here's my code:

field :searchCalls, !types[Types::CallType] do
  argument :phone_number, !types.String, required: true
  resolve -> (obj, args, ctx) { Call.where(phone_number: args[:phone_number]) }
end

I keep getting this error: "GraphQL::Argument can't define 'required'"

The field works fine without the "required: true" part.

**Comment by rmosolgo** [comment]
If youre using the the old `.define` API, use `!...` (as in `!types.String`) _instead of_ `required: true`, so you can remove `required: true` from your example.
