### ISSUE TITLE
Subscription class GraphqlChannel Path

### ISSUE THREAD

**Issue by ZeroSoulEater** [rmosolgo/graphql-ruby#2019]
I'm using Rails and I implement subscription right now.

I don't get why the Class needs to be in the graphql folder and not in `channels/application_cable`?

If the class is not in in the graphql folder, I get the error subscription class GraphqlChannel not found.

Maybe this is a rails thing, I'm not sure

**Comment by nekogami** [comment]
It works here, is your file path /channels/graphql_channel.rb ?

**Comment by ZeroSoulEater** [comment]
ah, I see I put it in `channels/application_cable/graphql_channel.rb`

works now thanks 😄
