### ISSUE TITLE
Scalar-type fields on Mutation generated types only resolve to nil

### ISSUE THREAD

**Issue by mlwilkerson** [rmosolgo/graphql-ruby#2027]
While (manually, incrementally) migrating from the old `.define` based API to the newer class-based API, I stumbled onto a problem where a String type (any scalar type?) is returning `nil` from a field on a  Mutation when I expect it to return a string, even a literal string.

I've prepared a repo to reproduce the scenario [here](https://github.com/mlwilkerson/graphql-ruby-nil-mutation-field).

The failing Rspec in that repo shows what I expect and what actually happens instead.

Here's the Rspec output with some additional debugging logging:

```
DEBUG: DooFoo.resolve wants to return this: {:processId=>"foo done", :errors=>[]}
DEBUG: spec gets: #<GraphQL::Query::Result @query=... @to_h={"data"=>{"doFoo"=>{"processId"=>nil}}}>
F

Failures:

  1) Mutations doFoo works
     Failure/Error: expect(result['data']['doFoo']['processId']).to eq "foo done"
     
       expected: "foo done"
            got: nil
     
       (compared using ==)
     # ./spec/do_foo_spec.rb:33:in `block (3 levels) in <top (required)>'

Finished in 0.11958 seconds (files took 2.57 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/do_foo_spec.rb:30 # Mutations doFoo works
```

The first `DEBUG` line in the rspec output above inspects the payload object as `#resolve` returns it. It has the expected string `"foo done"` as the value of `processId`.

The second `DEBUG` line in the rspec output above inspects the payload object as received by the query in the spec. It shows a `nil` value for `processId`.

To summarize the code in the repo, the Mutation looks like this ( [link to source](https://github.com/mlwilkerson/graphql-ruby-nil-mutation-field/blob/ead5576b9e966a4d3861aec78b794b4ef189177f/app/graphql/mutations/do_foo.rb#L1) ):

```ruby
class Mutations::DoFoo < GraphQL::Schema::Mutation
  field :processId, String, null: true
  field :errors, [String], null: false

  def resolve
    result = {
      processId: "foo done",
      errors: []
    }

    puts "DEBUG: DooFoo.resolve wants to return this: #{result.inspect}"
    result
  end
end
```

Out of curiosity—trying to answer then question _where along the way does the literal String value get replaced with `nil`_—I did some debugging.

I don't yet know the full significance of this, but I can see that [at this point](https://github.com/rmosolgo/graphql-ruby/blob/5527179a7b2f100ce9ee093764c924e87d155f1b/lib/graphql/execution/flatten.rb#L26) in `#flatten`, when inspecting `obj.object.object[:processId]` I can see the value I expect to be returned in the query (expecting `"foo done"`). And it seems to be just at this point that `nil` is returned as the value that will be assigned to the `processId` key in the resulting query. When this method returns `nil` here, it is assigned to the `flattened` key [here](https://github.com/rmosolgo/graphql-ruby/blob/5527179a7b2f100ce9ee093764c924e87d155f1b/lib/graphql/execution/flatten.rb#L20), and returned on up the stack [here](https://github.com/rmosolgo/graphql-ruby/blob/5527179a7b2f100ce9ee093764c924e87d155f1b/lib/graphql/execution/flatten.rb#L22).

If I knew what the comment on [`#invalid_null?`](https://github.com/rmosolgo/graphql-ruby/blob/5527179a7b2f100ce9ee093764c924e87d155f1b/lib/graphql/query/context.rb#L30) meant, maybe that would shed some light on the matter:
```ruby
# @return [Boolean] True if this selection has been nullified by a null child
```

As a comparison, there's also a `doBar` mutation in this example repo that is very similar, but instead of the mutation having a `String` (scalar) type field, its field type is one that I've made (`Types::ItemType`), and _that_ type has the `String` field on it. So, as far as I can tell, that's just adding one layer of indirection. But that works (see the passing `do_bar_spec` in the repo).

**Comment by mlwilkerson** [comment]
In my further development, looking for a workaround, I stumbled onto a combination that works closer to my expectations, allowing the mutation to return a `String` type field that doesn't get coerced to `nil`. I've added a [`doAlpha`](https://github.com/mlwilkerson/graphql-ruby-nil-mutation-field/blob/a7008c7248195aeda578fad72e64c106e0f463b1/app/graphql/types/mutation_type.rb#L5) mutation to my example repo that is declared with a return type, where that return type declares a `String` field. So if I've understood correctly how the mutation payload type generation works, this technique _circumvents_ that `generated_type` logic.

```ruby
# app/graphql/types/mutation_type.rb
# ...
field :doAlpha, Types::DoAlphaResult, mutation: Mutations::DoAlpha
# ...
```

```ruby
# app/graphql/types/do_alpha_result.rb
class Types::DoAlphaResult < Types::BaseObject
  field :alpha, String, null: false
end
```

```ruby
# app/graphql/mutations/do_alpha.rb
class Mutations::DoAlpha < GraphQL::Schema::Mutation

  def resolve
    return { alpha: "alpha done" }
  end
end
```

Now when running `bundle exec rspec` in the example, there's a passing `do_alpha_spec.rb`.

I've also [updated the failing "foo" scenario](https://github.com/mlwilkerson/graphql-ruby-nil-mutation-field/blob/bf2ba13da223ebe0e00e7b7e5a02eaa1fe28591e/app/graphql/mutations/do_foo.rb#L3) to add additional scalar-type fields to the mutation: `ID` and `Int`. You can see that these unexpectedly get resolved to `nil`, like the original `String` type field did (as [`do_foo_spec.rb` demonstrates](https://github.com/mlwilkerson/graphql-ruby-nil-mutation-field/blob/bf2ba13da223ebe0e00e7b7e5a02eaa1fe28591e/spec/do_foo_spec.rb#L38)). 

This seems to make it more clear that there's a problem with resolving a scalar fields on mutation generated types.

**Comment by mlwilkerson** [comment]
OK, I've got it working. Thank you.

So my feedback, then, is that this seems awfully error prone. Or maybe I just have a tendency to get shot by every foot gun.

Even when trying to apply your suggestion, I went round and round with various combinations of where camelCase should be used and where underscore_case should be used, trying to find a combination that worked.

Initially, I thought you were suggesting that I change this (all camelCase):
```ruby
  # field declaration
  field :processId, String, null: true
 
  # mutation return hash
  {
    processId: "foo done"
  }

  # query
      let(:query_string) {%|
        mutation {
          doFoo {
            processId
          }
        }
      |}
```

to this (i.e. use underscores everywhere, instead of camelCase):

```ruby
  # field declaration
  field :process_id, String, null: true
 
  # mutation return hash
  {
    process_id: "foo done"
  }

  # query
      let(:query_string) {%|
        mutation {
          doFoo {
            process_id
          }
        }
      |}
```

But when I did that, I got the error:
```
Field 'process_id' doesn't exist on type 'DoFooPayload'
```

In the process of editing and revising to post an update with my (still failing) results, I _accidentally_ stumbled onto this working combination:

```ruby
  # field declaration
  field :processId, String, null: true
 
  # mutation return hash
  {
    process_id: "foo done"
  }

  # query
      let(:query_string) {%|
        mutation {
          doFoo {
            processId
          }
        }
      |}
```

Playing around further, I now understand the rule to be:
_Always used underscore_cased in the return hash on the mutation AND always use camelCased on the graphQL query to select that field._

This rule holds true whether `field` declaration on the mutation is in camelCase or underscore_case (i.e. my spec passes either way, as long as I keep the above rule).

After re-re-reading your suggestion, I see that your rule holds too: _always use underscores in ruby code_. But given that the camelCase was _required_ in the _GraphQL code_ I'm still not sure I would have avoided this accident if I'd had that rule in mind. My intuition would have been to write the field in the GraphQL query the same way it appears in the ruby code. It's really a surprise to me to see that the casing of the field is being _changed_ in the process of moving from ruby to GraphQL.

If I'm the only person who stumbles on this, no big deal. But it seems like a pretty easy mistake to make.

In any case, this is a pretty minor nit. My appreciation for `graphql-ruby` has only grown in the process of debugging it :smile:

**Comment by rmosolgo** [comment]
Sorry about the trouble here! Thanks for sharing your debugging process. Yes, perhaps the addendum to my previous rule is, _Always use camel-case for GraphQL_!
