### ISSUE TITLE
Missing class forces a restart of the server

### ISSUE THREAD

**Issue by jchatel** [rmosolgo/graphql-ruby#2029]
I've been working a lot with GraphQL that last month and one thing that is very time-consuming is syntax errors or simple mistakes blocking a thread in my puma server forcing me to restart the server.

Of course, when this happens, I don't have any information as to where the problem might be and I have to revert my changes one by one to try to figure out what caused the problem.

I'm using 1.9.pre1 with the new syntax.

Here is the latest example of things that made my server spin: 

I declare a mutation

```ruby
module Types
  class MutationType < Types::BaseObject
  
    field :create_or_update_task_step, mutation: Mutations::CreateOrUpdateTaskStep

  end
end

```

and the corresponding file: create_or_update_task_step.rb

```ruby
module Mutations
  class CreateOrUpdateEmailStep < GraphQL::Schema::RelayClassicMutation
    null true

```

But due to a bad copy paste of another mutation (I forgot to change the class name from Email to Task). It's easy to mistype names (especially while refactoring) and having to restart your server without knowing why for these simple mistakes feels like an harsh punishment.

**To reproduce:**

Simply add a migration and the corresponding file but don't declare the class in the file.

```ruby
module Types
  class MutationType < Types::BaseObject
  
    field :problem, mutation: Mutations::Problem

  end
end

```

Fixing this should also fix the syntax errors (since the class is probably not declared).

**Comment by rmosolgo** [comment]
What version of Rails are you using? I was able to identify [one particular bug](https://github.com/rails/rails/pull/31803) and address it in Rails, but I think it only made it into 5.1+ .

**Comment by jchatel** [comment]
Oh, that's freaking awesome, I spent the entire night migrating from 4.2 to 5.2.

I just tried to reproduce the bug and I can't anymore! So happy, I should have done it early.

I was using Rails 4.2.11 with ruby 2.5.3
(I also moved to ruby 2.6.0)
