### ISSUE TITLE
Schema initialization happens on execution after migration to class-based API

### ISSUE THREAD

**Issue by philipkocanda** [rmosolgo/graphql-ruby#2034]
After converting our Schema to the class-based API, the initialization (loading of instrumentation, etc.) happens on the first call to `Schema.execute`, whereas it used to happen on application initialization. Since HackerOne has a big schema with a lot of instrumentation, this can take some time; and it caused whichever spec happened to be the first to run to be be slowed down by ~15 seconds, causing build failures in the process.

To work around this we're currently calling `Schema.instrumenters` manually while loading the app, which shaves ~7 seconds off of the first call to `Schema.execute`.

We're open to any suggestions on how to improve the situation!

**Comment by rmosolgo** [comment]
Hey! You've basically found the best way to address it, by forcing the schema loading some way. Another way is calling `MySchema.graphql_definition` at the bottom of the file, which will build out all the caches, etc. 

I'm hoping to eliminate the all-at-once initialization in a future release (1.10?) by building those caches incrementally, but I still have some things to finish up for 1.9 😅

**Comment by philipkocanda** [comment]
Thanks Robert! That's super helpful, looking forward to >1.9 😄

**Comment by fgrehm** [comment]
@rmosolgo I've brought our site down because of this 😅The initial requests were timing out because of this so I'm wondering if there should be a big note about this somewhere for others in case there isn't one already
