### ISSUE TITLE
[PRO] uninitialized constant GraphQL::StaticValidation::Message

### ISSUE THREAD

**Issue by djgable** [rmosolgo/graphql-ruby#2043]
graphQL-ruby: 1.9.0.pre1 master@cf41256
graphql-pro: 1.9.3
graphQL-batch: 0.3.10

Updated graphql-ruby to the latest rev from master, attempting to start / restart the rails server (or other services, i.e. Sidekiq) throws an error from graphql-pro:

`uninitialized constant GraphQL::StaticValidation::Message (NameError)`

coming from `graphql-pro-1.9.3/lib/graphql/pro/operation_store/operation_names_are_present_and_unique.rb:6:in <class:OperationNamesArePresentAndUnique>`

I'm pulling in graphql-pro in my Gemfile using:

```
source 'https://gems.graphql.pro/' do
  gem 'graphql-pro'
end
```
and properly authorizing using our pro credentials.

Is there a "pre-release" version of pro that addresses this issue and I'm not pulling it in correctly or is this unexpected behavior with the current pro version?

**Comment by rmosolgo** [comment]
I just released graphql-pro 1.9.4 which should support 1.9 as well as previous versions. Please give it a try and reopen this issue if you encounter any more trouble!
