### ISSUE TITLE
[Pro] ably client broken

### ISSUE THREAD

**Issue by modosc** [rmosolgo/graphql-ruby#2044]
the ably client is 100% broken for us with the release of [ably-js@1.0.21](https://github.com/ably/ably-js/releases/tag/1.0.21) .

<img width="495" alt="screen shot 2019-01-11 at 12 57 21 pm" src="https://user-images.githubusercontent.com/2231664/51058474-b9a29700-159d-11e9-889f-f1660f95693f.png">

 it has something to do with #2003 - i can either roll back to `ably-js@1.0.20` or roll back to `1.6.1` and everything works. @jscheid any ideas?

**Comment by rmosolgo** [comment]
Thanks for the heads up, I'll take a look too and see if I can find a clue!

**Comment by rmosolgo** [comment]
(It's got to be something about the change in https://github.com/ably/ably-js/pull/547/files)

**Comment by modosc** [comment]
agreed - i just don't know anything about this option, was hoping someone who did could chime in

**Comment by rmosolgo** [comment]
Could you share anything about your auth setup? Are you using clientIds?

**Comment by modosc** [comment]
i don't think so? we're currently just doing:

```
const realtime = new Ably.Realtime({ key: Config.ABLY_CLIENT_API_KEY })
```

**Comment by jscheid** [comment]
It still works for me with latest ably-js (using client IDs). I'm not sure what's going on, I'm afraid won't get a chance to check before later this week or next week.

**Comment by modosc** [comment]
@jscheid how are you doing auth?

**Comment by jscheid** [comment]
We're doing server-side token generation via `authCallback`.

**Comment by modosc** [comment]
i got things working with `authUrl` locally so this isn't blocking us anymore.

unfortunately i didn't document `authUrl` in the examples , only token auth (and that's still broken with the current version). @rmosolgo maybe it makes sense to provide an example for this? we're using something like this:
```
class AblyController < ActionController::Base

  before_action :handle_authentication

  def auth
    render status: 201, json: ably_rest_client.auth.create_token_request(
      capability: { '*' => ['presence', 'subscribe'] },
      client_id: 'graphql-subscriber',
    )
  end

```
not sure how you could make it generic since everyone's going to have their own auth setup but maybe at least having some code up would be useful. 

i'm going to leave this open since it is still broken.

**Comment by rmosolgo** [comment]
🤦‍♂️  @modosc are you using the AblyLink or createAblyHander? (The changes from jscheid were just to createAblyHandler, so I'm porting them to AblyLink)

**Comment by modosc** [comment]
`createAblyHander`

**Comment by rmosolgo** [comment]
oh, well, nevermind then, thanks.

**Comment by rmosolgo** [comment]
(finally updated the docs 🍻 )
