### ISSUE TITLE
1.8 Migration - .to_graphql NotImplementedError

### ISSUE THREAD

**Issue by zberkom** [rmosolgo/graphql-ruby#2047]
![screen shot 2019-01-14 at 3 46 34 pm](https://user-images.githubusercontent.com/7085617/51148601-bca6bd00-1813-11e9-99e0-f4f665aaf733.png)

Version: 1.8.11

```
NotImplementedError: NotImplementedError
web_1    | /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/schema/member/base_dsl_methods.rb:69:in `to_graphql'
```

I'm trying to upgrade piecemeal and I'm running into the issue above ^. If I don't call `.to_graphql`, I get 
```
GraphQL::Schema::InvalidTypeError: Mutation is invalid: field "inviteUser" type must return GraphQL::BaseType, not NilClass (nil)
```

Mutation
```ruby
  class InviteUser < GraphQL::Schema::Mutation
      argument :name, String, required: true
      argument :email, String, required: true
      argument :deal_type_ids, [ID], required: false

      field :user, UserType, null: true
      field :errors, [Types::Error], null: true
      
     def resolve(name:, email:, deal_type_ids:)
        result =
          Core::Users::InviteService.call(
            ...
          )

        if result.success?
          return { user: result.user }
        else
          return { errors: result.errors }
        end
      end
  end
```

**Comment by rmosolgo** [comment]
Oh! How annoying. It _should_ work to update piecemeal, without calling `.to_graphql` (ex: http://graphql-ruby.org/mutations/mutation_classes.html#hooking-up-mutations). 

Is your `Mutation` root type a class yet? If not, could you try updating it to be a `class Mutation ...`?

**Comment by zberkom** [comment]
@rmosolgo We ended up just redoing all the mutations, types, & inputs in one go.

**Comment by nepalez** [comment]
I have the same issue with migration from `1.9.21` to class-based syntax
