### ISSUE TITLE
Lookahead for connections

### ISSUE THREAD

**Issue by JanStevens** [rmosolgo/graphql-ruby#2049]
Hello,

Trying to use lookahead on a field which is a `GraphQL::Types::Relay::BaseConnection` but it doesn't seem to be supported, I guess that the lookahead needs to dig a bit deeper to figure out if the fields of the resulting edge type / node type are selected or not, example query

```graphql
query team {
  team(id: 2) {
    members {
      edges {
        node {
          id
          info {
            firstName
            lastName
          }
        }
      }
    }
  }
}
```

I want to know if `info` is selected so I can properly load in the association, else I can use a smaller / simpler query. Right now I added the `extras: [:lookahead]` to the `members` field on the `team`. This results in the resolver getting called with `lookahead` but I then receive the following error
`RuntimeError (Invariant: no field for Connections::MembersConnection.info)`

**Comment by rmosolgo** [comment]
Right now, you have to address this "manually", digging into either `edges { node }`, or `nodes`, like this: 

```ruby 
def members(lookahead:) 
  nodes_lookaheads = [
    # Selections made through `edges { node { ... } }`
    lookahead.selection(:edges).selection(:node),
    # Selections made through `nodes { ... }`
    lookahead.selection(:node) 
  ]

  if nodes_lookaheads.any? { |l| l.selects?(:info) } 
    # do something here because `members { ... { info } }` was selected 
  end 
end 
```

Let me know if you give that a try!
