### ISSUE TITLE
JavaScript library is not compatible with older browsers (<ES6)

### ISSUE THREAD

**Issue by hootlex** [rmosolgo/graphql-ruby#2057]
The library is using the `Class` keyword to define [PusherLink](https://github.com/rmosolgo/graphql-ruby/blob/master/javascript_client/subscriptions/PusherLink.js#L40). Since there is no transpilation (ie babel) the library is not compatible with older browsers that do not support ES6 and beyond, like Internet Explorer.

This is a dealbreaker for big companies and websites that need to support all major browsers.

Are the maintainers interested in supporting older browsers or is the library intended for modern browsers only?

**Comment by hootlex** [comment]
Another issue is that the modules do not use the `export` statement so when trying to transpile the library the following error is thrown: 

`"export 'default' (imported as 'PusherLink') was not found in 'graphql-ruby-client/subscriptions/PusherLink'`

**Comment by rmosolgo** [comment]
Hey! Sorry about that. I haven't really done front-end stuff for a couple of years so I forget exactly what's required to run code in different spots. 

I'm definitely interested in supporting older browsers! I imagine PusherLink could be refactored to be a constructor like [ActionCableLink](https://github.com/rmosolgo/graphql-ruby/blob/master/javascript_client/subscriptions/ActionCableLink.js), do you think that would do the trick?

**Comment by hootlex** [comment]
That could work but the best approach would be to transpile the library to ensure it remains compatible and take a step forward. IMO using modern JavaScript will encourage new contributions and will make the library _safer_ when it comes in making changes without being afraid of breaking stuff for non-modern browsers. ES6 and beyond is more pleasant for the developers and requires less code to achieve same results.

I think today many developers are unsure if a piece of code, like `const`, or `Class`, is modern JavaScript or not and the worst part is that the code might work locally and break for others when shipped due to the different environments. I highly recommend using a module bundler like `webpack` and transpile the library with babel.

Is that something you'd like to do? If so, I can help you out 🙂

**Comment by rmosolgo** [comment]
> unsure if a piece of code is modern JavaScript or not

Yes, I think you've described me exactly 😅 ! 

Someone recently recommended the same change to the JS library here: #2052  and IMO, safer browser support is one of the best arguments for adding that build tooling.

Let's do it, but we should get on the same page at #2052.

**Comment by hootlex** [comment]
Happy to hear! I will start working on a PR and we can get it from there. I don't see any technical suggestions in #2052 so I think we kill two birds with one stone - ensure browser compatibility and get modern goodies.
