### ISSUE TITLE
Following Connection Types document gives duplicate type definition error

### ISSUE THREAD

**Issue by yskkin** [rmosolgo/graphql-ruby#2059]
Following http://graphql-ruby.org/relay/connections.html#connection-types gives 

```
RuntimeError (Duplicate type definition found for name 'EventEdge' at 'Field EventConnectionWithTotalCount.edges's return type' (#<Class:0x0000557c559a56b0>, Types::EventEdgeType)):
```

event_type.rb
```ruby
module Types
  class EventType < Types::BaseObject
    implements GraphQL::Relay::Node.interface
    field :id, ID, null: false
    global_id_field :id
  
    # snip
  end
end
```

event_connection_with_total_count_type.rb
```ruby
module Types
  class EventEdgeType < GraphQL::Types::Relay::BaseEdge
    node_type(EventType)
  end

  class EventConnectionWithTotalCountType < GraphQL::Types::Relay::BaseConnection
    edge_type(EventEdgeType)

    field :total_count, Integer, null: false

    def total_count
      object.count
    end
  end
end
```

query_type.rb
```ruby
module Types
  class QueryType < Types::BaseObject

    field :events, EventConnectionWithTotalCountType, null: false, max_page_size: 20, connection: true do
      # snip
    end

    def events(**params)
      Event.resolve(params)
    end
  end
end
```

<details>
<summary>Changeing to following make it work but I'm not sure this is proper approach</summary>

add this to event_type.rb
```ruby
    class << self
      def connection_type_class
        @connection_type_class ||= Types::EventConnectionWithTotalCountType
      end
    end
```

event_connection_with_total_count_type.rb
```ruby
module Types
  class EventConnectionWithTotalCountType < GraphQL::Types::Relay::BaseConnection

    field :total_count, Integer, null: false

    def total_count
      @object.send(:relation_count, @object.nodes)
    end
  end
end
```

query_type.rb
```ruby
module Types
  class QueryType < Types::BaseObject
    field :events, Event.connection_type, null: false, max_page_size: 20 do
      # snip
    end
    # snip
  end
end
```
</details>

Can document be improved somehow?

**Comment by rmosolgo** [comment]
It seems like `class EventEdgeType` is conflicting with the automatically generated edge type of `EventType.connection_type`. 

Perhaps the documentation could point out this issue, and suggest: 

> If you use classes for an object's connection or edge types, then _all_ of that object's connection and edge types should be classes. Otherwise, the auto-generated types from the `.edge_type` or `.connection_type` helpers will conflict with the class-based types.

What do you think of that?

**Comment by yskkin** [comment]
I was mixing `EventConnectionWithTotalCountType` and `EvntType.connection_type`, and unaware that this is the source of issue.
Your suggestion definitely helps.

If we can detect such situation and show this message in warning, that is even better.

**Comment by rmosolgo** [comment]
Added a note in 7984d8749
