### ISSUE TITLE
[pro] ably missing unsubscribes?

### ISSUE THREAD

**Issue by modosc** [rmosolgo/graphql-ruby#2061]
we've noticed a ton of lingering subscriptions in the dashboard.in digging around i found this on [ably's site](https://www.ably.io/documentation/general/webhooks)

```
Channel lifecycle events – get notified when a channel is created (following the first client attaching to this channel) or discarded (when there are no more clients attached to the channel)
Presence events – get notified when clients enter, update their data, or leave channels
```

but in the [graphql instructions](http://graphql-ruby.org/subscriptions/ably_implementation.html#ably)
```
Under “Source” select “Channel Lifecycle”
```
i'm wondering if we also need webhooks for `Presence events` as well?

beyond that i'll try some more debubgging, but it's hard to track down exactly how/when this is occurring. it's possible this has something to do with development/hot-reloading in react-native as well, since right now we don't have any production builds pointing at this api (yet).

**Comment by rmosolgo** [comment]
🤔 Do you use [ngrok](http://graphql-ruby.org/subscriptions/ably_implementation.html#developing-with-webhooks) in development? Without ngrok, the local server won't be able to receive webhooks from Ably, so it won't know when channels are vacated. 

(The subscription transport uses one-channel-per-subscription, so creating a subscription causes the channel to be created, then unsubscribing causes the channel to be vacated and destroyed. So, I don't expect to need presence events.)

**Comment by modosc** [comment]
wanted to chime in a year later on this.

in digging in the docs we found that ably doesn't _guarantee_ webhook events for channel lifecycle events. some math with our logs + redis server found that we end up not receiving these notifications ~1% of the time. not a huge deal but after a year this filled up our redis server :/

we also end up getting errors from the pro subscriptions when a subscription that should exist according to a topic's records doesn't actually exist. we wrote a cleanup script to deal with this but it would be cool if the attempts at JSON serialization in the subscription code would actually cleanup if they fail to deserialize data from redis. 

also maybe consider allowing timeouts to be set on the subscription keys themselves? again, this still leaves dangling issues to be resolved (topics pointing to dead subscriptions and/or all_topics pointing to topics that don't exist anymore) but maybe a combination of this + error handling described above would help.

then again maybe we're the only people doing subscriptions this way with high enough traffic to notice this, 🤷‍♂

**Comment by rmosolgo** [comment]
Thanks for sharing your experiences here! 

> actually cleanup if they fail to deserialize data

I agree! Could you share the backtrace of one of those errors? It looks like the Ably implementation _tries_ to check if the channel still has subscribers. But maybe the issue at hand is something slightly different. I'd love to look into it more. 

> timeouts

This is a great point. Like you said, it will require a little care to make sure that the data is cleaned up properly, but I think it'll work one way or another. I'll take a look and follow up here!

**Comment by modosc** [comment]
so here's the stack trace (mixed in unfortunately with some of our code):
```
TypeError: Nil is not a valid JSON source.
1 File "/app/vendor/bundle/ruby/2.6.0/gems/graphql-pro-1.11.0/lib/graphql/pro/subscriptions/redis_storage.rb" line 44 in parse
2 File "/app/vendor/bundle/ruby/2.6.0/gems/graphql-pro-1.11.0/lib/graphql/pro/subscriptions/redis_storage.rb" line 44 in read_subscription
3 File "/app/vendor/ruby-2.6.5/lib/ruby/2.6.0/forwardable.rb" line 230 in read_subscription
4 File "/app/app/graphql/subscriptions/swoop_subscription_execute.rb", line 16 in execute
5 File "/app/app/graphql/subscriptions/swoop_ably_subscriptions.rb", line 14 in block in execute_all
6 File "/app/vendor/bundle/ruby/2.6.0/gems/graphql-pro-1.11.0/lib/graphql/pro/subscriptions/redis_storage.rb" line 65 in block in each_subscription_id
7 File "/app/vendor/bundle/ruby/2.6.0/gems/graphql-pro-1.11.0/lib/graphql/pro/subscriptions/redis_storage.rb" line 60 in each
8 File "/app/vendor/bundle/ruby/2.6.0/gems/graphql-pro-1.11.0/lib/graphql/pro/subscriptions/redis_storage.rb" line 60 in each_subscription_id
9 File "/app/app/graphql/subscriptions/swoop_ably_subscriptions.rb", line 11 in execute_all
10 File "/app/vendor/bundle/ruby/2.6.0/gems/graphql-1.9.17/lib/graphql/subscriptions.rb" line 69 in trigger
11 File "/app/app/graphql/subscriptions/swoop_multi_subscriptions.rb", line 46 in trigger
12 File "/app/app/workers/graphql/job_updated_worker.rb", line 61 in block (2 levels) in perform
```

i think the basic gist would be to handle that exception by clearing out the related set elements as i mentioned above, however iirc that's hard because this deep down the stack we don't necessarily have access to the redis key that we were trying to read? maybe i'm wrong, it was ~1 year ago that i dug into this.

**Comment by rmosolgo** [comment]
I just released graphql-pro 1.13.0 that _partly_ addresses this issue: 

- It cleans up dangling subscriptions when something is missing during `each_subscription_id`. 
- It returns `nil` when it finds missing subscription data during `read_subscription`. 

The thing is, I think there's a funny state where a subscription is _identified_ during `each_subscription_id`, but deleted between that time and `read_subscription`. (I see that the codebase contains some cleanup code, but I was trying to think why it wouldn't always work!)

I still need an upstream fix in graphql-ruby to _handle_ the returned `nil` during `def execute`.  I'll take a look at that along with the `prepare:` issue soon.

**Comment by rmosolgo** [comment]
Ok, GraphQL-Ruby 1.10.3 (not released yet) + GraphQL-Pro 1.13.0 should do better here: 

- The redis backend will return `nil` and clean itself up when subscriptions aren't found 
- GraphQL-Ruby handles that returned `nil` by not delivering anything and telling the DB to clean up

**Comment by modosc** [comment]
thanks! i'm still in the upgrade process but will ping back when this is finally live on our end.

**Comment by rmosolgo** [comment]
Sure, I'm still hoping to work on the `prepare:` issue as well https://github.com/rmosolgo/graphql-ruby/issues/2721

**Comment by rmosolgo** [comment]
@modosc  just checking in on this -- are you still seeing stale data in Redis?

**Comment by modosc** [comment]
honestly i'm unsure because we're running our cleanup job. i'll turn it off and check back in a few days.
