### ISSUE TITLE
[pro] better formatting in the subscription screen?

### ISSUE THREAD

**Issue by modosc** [rmosolgo/graphql-ruby#2062]
(sorry, i'd do a pr for this if it was in the public repo)

![image](https://user-images.githubusercontent.com/2231664/51352315-169cc200-1a62-11e9-9352-dc9dfca5d0cc.png)

adding `white-space: pre-wrap;` to that `<pre>` would help:

![image](https://user-images.githubusercontent.com/2231664/51352553-c7a35c80-1a62-11e9-88d7-b96462953745.png)

would be nice to get rid of hash rockets, correctly show ActiveRecord instances instead of `#`, etc but just adding this wrapping would be greatly appreciated.

**Comment by rmosolgo** [comment]
shipped in 1.9.6!
