### ISSUE TITLE
default_value: nil produces different schema introspection than nil argument

### ISSUE THREAD

**Issue by aarons22** [rmosolgo/graphql-ruby#2063]
`graphql`: 1.8.13
`graphql-batch`: 0.3.10
`graphql-errors`: 0.2.0
`graphql-pro`: 1.9.5

When specifying `default_value` as `nil`:
```
field :comments, Types::CommentType.connection_type, null: false do
    argument :orderBy, InputTypes::CommentOrderInputType, default_value: nil, required: false
end

def comments(order_by:)

end
```

it produces this in the schema introspection:
```
"defaultValue": "null"
```

When specifying the argument as `nil`:

```
field :comments, Types::CommentType.connection_type, null: false do
    argument :orderBy, InputTypes::CommentOrderInputType, required: false
end

def comments(order_by: nil)

end
```

it produces this in the schema introspection
```
"defaultValue": null
```

I would expect those to be the same.

**Comment by jordanthomas** [comment]
Peeking into this just a little bit – should [this line](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/introspection/input_value_type.rb#L18) be returning `nil`, similar to [line 28](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/introspection/input_value_type.rb#L28)?

**Comment by rmosolgo** [comment]
I _think_ the current behavior is in compliance with the spec: 

> `defaultValue` may return a String encoding (using the GraphQL language) of the default value used by this input value in the condition a value is not provided at runtime. If this input value has no default value, returns __null__.

(https://facebook.github.io/graphql/June2018/#sec-The-__InputValue-Type)

So, in the first case (`default_value: nil`), the argument _does_ have a default value, and so we return a "String encoding" of the default value (`"null"`). In the second case (no `default_value:` option), the field has no default value, so we return `null`. 

Does that behavior match the spec by your reading too?

**Comment by aarons22** [comment]
I can certainly see how the spec could be read that way. I'll ultimately defer to your judgement since you have much more familiarity with the spec than I do, but the it does say _may_ instead of _must_ (like the other field descriptors in that link), so it _seems_ that it's up to you. If you agree that there is flexibility with the spec, I would only question whether or not there is value in returning a string encoded `"null"` instead of always returning `null`. If there is a compelling use case, I would concede that it is acceptable as is.

**Comment by rmosolgo** [comment]
I'll keep it as is then, thanks. I think it's good to keep it as a string (`"null"`) so that it can be distinguished from arguments which _don't have_ a default value (`null`).
