### ISSUE TITLE
Unable to reload Graphiql, warning: already initialized constant Types::QueryType

### ISSUE THREAD

**Issue by FusionStreak** [rmosolgo/graphql-ruby#2065]
Every time I make a change to the code and restart the Rails app, the Graphiql does not reload correctly and gives me the following errors.

```
D:/Code/Shopity/app/graphql/types/query_type.rb:7: warning: already initialized constant Types::QueryType
D:/Code/Shopity/app/graphql/types/query_type.rb:4: warning: previous definition of QueryType was here
D:/Code/Shopity/app/graphql/types/product_type.rb:5: warning: already initialized constant Types::ProductType
D:/Code/Shopity/app/graphql/types/product_type.rb:4: warning: previous definition of ProductType was here
```

The only way to fix I found is to run `$ rails generate graphql:install -f` then rewrite all the methods with the changes I want. Is there a way to unload the previous definitions?

Repo of my code: [Shopity](https://github.com/FusionStreak/Shopity)

Thanks

**Comment by rmosolgo** [comment]
I see that you're defining QueryType twice, once as a class: 

```ruby 
 class QueryType < Types::BaseObject
```

And then again using `.define`: 

```ruby 
 Types::QueryType = GraphQL::ObjectType.define do
```

In fact, those approaches are _alternatives_ (either `class` _or_ `.define`, but not both). `.define` is being phased out, and being replaced by `class`, but currently both are supported for backwards-compatibility reasons. 

How did you end up with both of those in your code? Was that the generator output, or were you following documentation somewhere?

**Comment by FusionStreak** [comment]
Was following [HowToGraphql](https://www.howtographql.com/graphql-ruby/0-introduction/) . 
 Is this the same for my ProductType file?
Thanks

**Comment by FusionStreak** [comment]
Updated project with the fixes, it removed the old error. But produces this error when loading `localhost:3000/graphiql `:

```
TypeError: Cannot read property 'types' of undefined
    at buildClientSchema (http://localhost:3000/assets/graphiql/rails/graphiql-0.12.0.self-84a2376c545f0620e86ec9d8681863a2f1b56b5eb3fe74c45003ff1fb982c1a3.js?body=1:33481:72)
    at http://localhost:3000/assets/graphiql/rails/graphiql-0.12.0.self-84a2376c545f0620e86ec9d8681863a2f1b56b5eb3fe74c45003ff1fb982c1a3.js?body=1:2174:55
```

**Comment by FusionStreak** [comment]
I switched to only use `.define` method. It gives me no errors.
Thanks
