### ISSUE TITLE
NewRelic Integration: track by operation name _and_ controller action

### ISSUE THREAD

**Issue by rtymchyk** [rmosolgo/graphql-ruby#2073]
I've recently enabled `set_transaction_name` with the NR integration, which allows us to track each query/mutation as a separate transaction. However, in addition to that, I would like to continue tracking overall performance of the the GraphQL controller method. Is it possible to have both running side-by-side?

I see that NR provides the ability to add method tracing as well, but I figured I'd ask here first instead of trying to guess the right way to go about this.

**Comment by rmosolgo** [comment]
Hi! Good question. I'm not sure a way to do that, since `set_transaction_name` overrides the controller/action. However, if you find an approach that works for you, please share it here or consider opening a PR!

**Comment by rtymchyk** [comment]
@rmosolgo Thanks for your response. I've decided to stick with the granular setup but have a follow-up question if you don't mind.

I dug up in some documentation that ` This is not advised if you run more than one query per HTTP request, for example, with graphql-client or multiplexing.`. We make use of multiplexing/batching. Any workarounds there or is this still unsolved? I believe it may be skewing some data I'm seeing in NR.

**Comment by rmosolgo** [comment]
For clarity's sake, multiplexing is different from batching: http://graphql-ruby.org/queries/multiplex.html

I don't really have any great ideas for batching 😖 . Usually the first field that depends on a batch loader causes it to resolve, and gets "credited" for the time spent. It would be nice to divide it somehow, but I'm really not sure how to implement that!

**Comment by rtymchyk** [comment]
@rmosolgo Does it make sense to open a new issue on this? Would be nice to hear if anyone has other work-arounds. It's very difficult to analyze performance correctly of GraphQL if it shows as a single transaction on New Relic.

**Comment by rmosolgo** [comment]
Yes,  a new issue would be great! The more info you can share, the better, for example, what your current charts look like, what you _think_ they should look like, and how the underlying Ruby code is structured would all be helpful.
