### ISSUE TITLE
Running graphql-ruby-client sync gives syntax error

### ISSUE THREAD

**Issue by cella** [rmosolgo/graphql-ruby#2074]
I am trying to implement persisted queries using GraphQL::Pro::OperationStore and am getting a syntax error when syncing with the client using `graphql-ruby-client sync`, as noted in the backtrace below.  To the best of my knowledge, everything has been set up correctly with `OperationStore` and the client `ios` was registered successfully via the dashboard.  Seems like the syntax error is coming from one of the `graphql` or `graphql-ruby-client` package files.

```
$ yarn run graphql-ruby-client sync --url=http://localhost:3000/graphql/sync --client=ios
yarn run v1.3.2
$ /app/node_modules/.bin/graphql-ruby-client sync --url=http://localhost:3000/graphql/sync --client=ios

/app/node_modules/graphql/language/lexer.js:247
  throw (0, _error.syntaxError)(source, position, unexpectedCharacterMessage(code));
  ^
GraphQLError: Syntax Error GraphQL request (1:1) Cannot parse the unexpected character "/".

1: /**
   ^
2:  * @flow

    at syntaxError (/app/node_modules/graphql/error/syntaxError.js:31:15)
    at readToken (/app/node_modules/graphql/language/lexer.js:247:32)
    at Object.advanceLexer [as advance] (/app/node_modules/graphql/language/lexer.js:46:28)
    at expect (/app/node_modules/graphql/language/parser.js:970:11)
    at parseDocument (/app/node_modules/graphql/language/parser.js:106:3)
    at Object.parse (/app/node_modules/graphql/language/parser.js:46:10)
    at prepareProject (/app/node_modules/graphql-ruby-client/sync/prepareProject.js:22:21)
    at gatherOperations (/app/node_modules/graphql-ruby-client/sync/generateClient.js:66:28)
    at sync (/app/node_modules/graphql-ruby-client/sync/index.js:49:17)
    at Object.<anonymous> (/app/node_modules/graphql-ruby-client/cli.js:39:18)
error Command failed with exit code 1.
```

**Comment by rmosolgo** [comment]
Hi! Sorry about the hangup :S 

It looks like it's trying to parse some plain JavaScript _as if it were GraphQL_. How about using the [--path option](http://graphql-ruby.org/javascript_client/sync#sync-utility) to specify a directory of `.graphql` files to persist? That might help it do the right thing! 

(This isn't the first time this has happened to someone, maybe I should require a `--path`, or at least output to the terminal what path it's working on!)

**Comment by cella** [comment]
Thanks for the prompt response!  I tried assigning path to `app/javascript/graphql` and verified that the folder exists at that location and still getting a similar but different syntax error of `Unexpected <EOF>`

```
$ yarn run graphql-ruby-client sync --url=http://localhost:3000/graphql/sync --client=ios --path=app/javascript/graphql
yarn run v1.3.2
$ /app/node_modules/.bin/graphql-ruby-client sync --url=http://localhost:3000/graphql/sync --client=ios --path=app/javascript/graphql

/app/node_modules/graphql/language/parser.js:155
  throw unexpected(lexer);
  ^
GraphQLError: Syntax Error GraphQL request (1:1) Unexpected <EOF>

1:
   ^

    at syntaxError (/app/node_modules/graphql/error/syntaxError.js:31:15)
    at unexpected (/app/node_modules/graphql/language/parser.js:996:33)
    at parseDefinition (/app/node_modules/graphql/language/parser.js:155:9)
    at parseDocument (/app/node_modules/graphql/language/parser.js:109:22)
    at Object.parse (/app/node_modules/graphql/language/parser.js:46:10)
    at prepareProject (/app/node_modules/graphql-ruby-client/sync/prepareProject.js:22:21)
    at gatherOperations (/app/node_modules/graphql-ruby-client/sync/generateClient.js:66:28)
    at sync (/app/node_modules/graphql-ruby-client/sync/index.js:49:17)
    at Object.<anonymous> (/app/node_modules/graphql-ruby-client/cli.js:39:18)
    at Module._compile (module.js:635:30)
error Command failed with exit code 1.

```

**Comment by rmosolgo** [comment]
Weird 🤔  are there any blank files in that directory?

**Comment by rmosolgo** [comment]
Oh, or maybe it's not finding anything in that directory, and that's why it's blank!

**Comment by cella** [comment]
The directory is currently empty @rmosolgo.  Should it be populated with something?  Let me know if you need any additional context or screenshots that might be helpful!  The `--verbose` option should be helpful too once it gets added :)

**Comment by rmosolgo** [comment]
Oh! Yes, it should have `.graphql` files in it (for example: https://github.com/rmosolgo/graphql-ruby-chatroom-example/tree/master/app/javascript/packs/graphql). Those files will be sent to the server and exchanged for Query IDs. Then in production, only Query IDs will be sent to the server.

**Comment by cella** [comment]
Doh, thanks thanks for that! That makes total sense. Ok, I added a .graphql file `ProductsQuery.graphql` inside the `app/javascript/graphql` folder that looks like this:

```
query ProductsQuery {
  products {
    id
    name
    description
    accountId
    createdAt
    deletedAt
    updatedAt
    properties
  }
}
```
then I reran `yarn run graphql-ruby-client sync` and got a new error:

```
$ yarn run graphql-ruby-client sync --url=http://localhost:3000/graphql/sync --client=ios --path=app/javascript/graphql
yarn run v1.3.2
$ /app/node_modules/.bin/graphql-ruby-client sync --url=http://localhost:3000/graphql/sync --client=ios --path=app/javascript/graphql
Syncing 1 operations to http://localhost:3000/graphql/sync...
Sync failed:
{ Error: connect ECONNREFUSED 127.0.0.1:3000
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3000 }
```

this is what my `routes.rb` looks like 

```
using GraphQL::Pro::Routes

Rails.application.routes.draw do

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  mount V3Schema.dashboard, at: "/graphql/dashboard"
  mount V3Schema.operation_store_sync, at: "/graphql/sync"
```

And my GraphQl schema
```
class V3Schema < GraphQL::Schema
  mutation(Types::MutationType)
  query(Types::QueryType)
  use GraphQL::Pro::OperationStore
end
```

Thanks for your help so far with this @rmosolgo!

**Comment by cella** [comment]
FYI I'm also running all of this within a docker container that may have something to do with it!

**Comment by rmosolgo** [comment]
`sync` will try to send the data to your development server (identified by `--url`). Was it running? Was that the correct URL to access it?

**Comment by cella** [comment]
Confirming that the development server is running at `localhost:3000` but still running into that issue, will try to do more digging and report back

**Comment by cella** [comment]
Hey! Just wanted to follow up that I got the `sync` to run correctly by replacing `localhost` with the app's client ip instead of the server ip.  Thanks for your help again!! Closing this issue.

**Comment by rmosolgo** [comment]
Ohhhh that makes sense! Thanks for sharing your solution, I'll keep that in mind in case i hear this problem again 💡 !
