### ISSUE TITLE
loads: options in argument (in mutation) throws error about missing object (1.8.13)

### ISSUE THREAD

**Issue by michal-samluk** [rmosolgo/graphql-ruby#2081]
Code snippet 
```
module Mutations
  class MyMutation < BaseMutation
    argument :invoice_id, ID, required: true, loads: Types::InvoiceType
    # ... 
  end
end 
```
[edit] BaseMutation inherits from: `GraphQL::Schema::RelayClassicMutation`

`context.schema.possible_types(lookup_as_type)` returns `[Invoice]`, where Invoice is a subclass of `GraphQL::ObjectType`
`context.schema.resolve_type(lookup_as_type, application_object, context)` returns `Types::InvoiceType`

Type defined like this:
```
module Types
  class InvoiceType < BaseObject
    implements NodeType
  end 
end
```

```
module Types
  class BaseObject < GraphQL::Schema::Object
  end
end 
```

will match this condition `#possible_types` method. 
https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/possible_types.rb#L26
[edit]
Worth to mention - I am forced to set `resolve_type` with message: 
`GraphqlSchema.resolve_type(type, obj, ctx) must be implemented to use Union types or Interface types (tried to resolve: Invoice)`, where my `Types::InvoiceType` is not a Union or Interface. `NodeType` is but it already defines `resolve_type`.

**Comment by michal-samluk** [comment]
@rmosolgo Hey, any news about this one? Have you been able to reproduce it? Do you need any help from to dig further here (e.g. failing spec)?

**Comment by michal-samluk** [comment]
I cannot reproduce it anymore while using: 1.9.2

**Comment by rmosolgo** [comment]
Glad to hear it 😅  Thanks for following up!
