### ISSUE TITLE
Guide: Enable HTTPS for graphql-ruby.org

### ISSUE THREAD

**Issue by reedloden** [rmosolgo/graphql-ruby#2083]
http://graphql-ruby.org is hosted via GitHub Pages. GitHub Pages supports HTTPS (https://help.github.com/articles/securing-your-github-pages-site-with-https/). Could HTTPS be enabled for graphql-ruby.org and made the default?

**Comment by rmosolgo** [comment]
Hey, thanks for the suggestion here! I just made the required DNS updates, and it looks like it's underway. The settings page says: 

> Not yet available for your site because the certificate has not finished being issued.
>
> Please allow 24 hours for this process to complete.

So, I'll keep an eye on it and follow up here when it's done!

**Comment by rmosolgo** [comment]
Annd we're up! 

![image](https://user-images.githubusercontent.com/2231765/52218352-7e2b7d80-2868-11e9-9719-4c2a3bc80c50.png)


Thanks again.
