### ISSUE TITLE
Connections breaks includes

### ISSUE THREAD

**Issue by mbajur** [rmosolgo/graphql-ruby#2084]
I have a following setup:

    class Product < ApplicationRecord
      has_many :variants
    end
    
    class Variant < ApplicationRecord
      belongs_to :product
    end
    
    Types::QueryType = GraphQL::ObjectType.define do
      connection :products, Types::ProductType.connection_type do
        resolve -> (obj, _, _) do
          Product.all.includes(:variants)
        end
      end
    end
    
    Types::ProductType = GraphQL::ObjectType.define do
      connection :variants, Types::VariantType.connection_type do
        resolve -> (obj, _, _) { obj.variants }
      end
    end

And running a following query:

    {
      products {
        edges {
          nodes {
            variants {
              edges {
                node {
                  id
                }
              }
            }
          }
        }
      }
    }

produces following SQL queries:

      Product Load (2.7ms)  SELECT  "products".* FROM "products" LIMIT $1  [["LIMIT", 25]]
      Variant Load (8.6ms)  SELECT "variants".* FROM "variants" WHERE "variants"."product_id" IN (1, 2, 3)
      Variant Load (19.0ms)  SELECT  "variants".* FROM "variants" WHERE "variants"."product_id" = $1 LIMIT $2  [["product_id", 1], ["LIMIT", 25]]
      Variant Load (13.6ms)  SELECT  "variants".* FROM "variants" WHERE "variants"."product_id" = $1 LIMIT $2  [["product_id", 2], ["LIMIT", 25]]
      Variant Load (2.4ms)  SELECT  "variants".* FROM "variants" WHERE "variants"."product_id" = $1 LIMIT $2  [["product_id", 3], ["LIMIT", 25]]

As we can see in the sql output, `includes` works but graphql don't care and makes a n+1 anyway. Is that normal behaviour and i'm forced to use solutions like graphql-batch to fix that or something is not right with my setup? As far as i have seen all over the internet, using `includes` should be enough for such simple scenario and graphql should use the eager loaded data instead of producing the n+1. Have i done anything wrong in here?

I'm on graphql-ruby 1.7.9

Thanks in advance for any clues!

**Comment by mbajur** [comment]
Yes, that was it! Thank you so much :)

**Comment by rmosolgo** [comment]
Keep in mind, if you were relying on `max_page_size,` you'll want to implement that another way where ever you were depending on it!

**Comment by mbajur** [comment]
sure thing and thanks for the heads up! btw - if you care about stack-overflow, i encourage you to post your reply here: https://stackoverflow.com/questions/54506509/connections-breaks-includes so i can accept it
