### ISSUE TITLE
input is not coerced into a list of one if there is a type error in the InputObject

### ISSUE THREAD

**Issue by jtgrenz** [rmosolgo/graphql-ruby#2085]
**Gem Version:** v1.8.13

**Issue:** When an InputObject expects a List, but only one item is provided, it is unneccecasry to wrap the object in square brackets because it is coerced into a List of one. If there is an error in that single list item, the coercion of the object to a List of one never happens which raises an error.

**Example**

```graphql
mutation {
  productCreate(
      input: {
          id:  "gid://shopify/Product/id",
          title: "A Title", 
          variants: {
              price: 17, 
              weight: 1, 
              weightUnit: "POUNDS"
            }
        }
    ) {
    product {
      id
    }
  }
}
```

The `variants` field expects a List, but given we only have a single variant here, it should be coerced into a List of one automatically. The `weightUnit` expects an Enum value, not a String. `weightUnit: "POUNDS"` is invalid and the line should read `weightUnit: POUNDS` instead.  

The invalid input correctly raises `GraphQL::LiteralValidationError` and is rescued, but fails in the rescue block here in [lib/graphql/static_validation/rules/argument_literals_are_compatible.rb#L25](
https://github.com/rmosolgo/graphql-ruby/blob/v1.8.13/lib/graphql/static_validation/rules/argument_literals_are_compatible.rb#L25) with `undefined method 'include?' for <GraphQL::Language::Nodes::InputObject:0x00005567ad947f40>`

Because `"POUNDS"` is not a valid enum, something goes wrong and `variants` is never coerced into a List, even though `arg_defn.type.kind.list?` evaluates to true (arg_defn.type is `[ProductVariantInput!]` at the type of the error)

CC: @rmosolgo @eapache @swalkinshaw

**Comment by rmosolgo** [comment]
Thanks for reporting this bug!
