### ISSUE TITLE
Subscriptions Trigger with class based api?

### ISSUE THREAD

**Issue by kidcosmic** [rmosolgo/graphql-ruby#2091]
Following docs, trigger doesn't seem to work on our Schema:

```
class RelevntApiSchema < GraphQL::Schema

  mutation(Types::MutationType)
  query(Types::QueryType)
  subscription(Types::SubscriptionType)
end
```
```
RelevntApiSchema.subscriptions.trigger("communityChat", {community_id: community.id}, message)
```
We get:
```
undefined method `trigger' for nil:NilClass
```

Tried the following variations:
```
RelevntApiSchema.subscription.trigger("communityChat", {community_id: community.id}, message)
context.schema.subscriptions.trigger("communityChat", {community_id: community.id}, message)
```

**Comment by rmosolgo** [comment]
Hi, you also need a `use ...` line in your schema to add a Subscription implementation -- something that will take messages and transport them to clients. 

For example: 
- ActionCable: https://graphql-ruby.org/api-doc/1.8.13/GraphQL/Subscriptions/ActionCableSubscriptions
- Pusher: https://graphql-ruby.org/subscriptions/pusher_implementation#schema-configuration

Please reopen if you still have trouble after hooking one of those up!

**Comment by kidcosmic** [comment]
@rmosolgo didn't see use in the docs anywhere. have a connection now 
```
GraphqlChannel is streaming from graphql-event::communityChat:communityId:Q29tbXVuaXR5LTE=
```
but it's misbehaving, any chance i could get some help getting this stream online? running it with react relay client side, and not getting any events. Relay complains it receives no data on subscription
