### ISSUE TITLE
field API documentation is outdated

### ISSUE THREAD

**Issue by cerdiogenes** [rmosolgo/graphql-ruby#2105]
The [field API](https://graphql-ruby.org/api-doc/1.8.13/GraphQL/Field.html) documentation talks about `property` to provide a custom method to define the field value. This [issue](https://github.com/rmosolgo/graphql-ruby/issues/1456) already tracks that this changed to `method`.

Is there any other place that this can be wrong and is generated by the code in the repo?

**Comment by rmosolgo** [comment]
Hi there, GraphQL-Ruby is in a bit of transition from an old approach to schema definition to a new approach. 

The file you linked is for the legacy definition object. You can find the new object here: https://graphql-ruby.org/api-doc/1.8.13/GraphQL/Schema/Field. 

I've added a todo to the [next version](https://github.com/rmosolgo/graphql-ruby/issues/2100) to mark those as deprecated, hopefully that will help!
