### ISSUE TITLE
Error installing documentation when packaging gem as rpm

### ISSUE THREAD

**Issue by xprazak2** [rmosolgo/graphql-ruby#2111]
We ran into an issue where darkfish/RDoc documentation fails to install when trying to package the gem as rpm:

[graphql-build.log](https://github.com/rmosolgo/graphql-ruby/files/2863731/graphql-build.log)

[koji task](http://koji.katello.org/koji/taskinfo?taskID=171280)

The workaround I used is not to allow docs to install by using `gem install` with options rather that `%gem_install`, as can be seen in the [packaging PR](https://github.com/theforeman/foreman-packaging/pull/3452)

**Comment by rmosolgo** [comment]
Looking at the attached log, the error is: 

```
Installing ri documentation for graphql-1.8.14
Installing darkfish documentation for graphql-1.8.14
BUILDSTDERR: ERROR:  While executing gem ... (RDoc::Error)
BUILDSTDERR:     error generating GraphQL/Schema/Member/BuildType.html: no implicit conversion of nil into String (TypeError)
BUILDSTDERR: error: Bad exit status from /var/tmp/rpm-tmp.GbFope (%build)
BUILDSTDERR:     Bad exit status from /var/tmp/rpm-tmp.GbFope (%build)
RPM build errors:
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 96, in trace
    result = func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/mockbuild/util.py", line 634, in do
    raise exception.Error("Command failed: \n # %s\n%s" % (command, output), child.returncode)
Error: Command failed: 
 # bash --login -c /usr/bin/rpmbuild -bb --target noarch --nodeps /builddir/build/SPECS/rubygem-graphql.spec
```

I don't encounter this error, and I don't understand what's causing it, so I have no plans to work on it :sweat_smile:
