### ISSUE TITLE
Wrong link "GraphQL type system" on website homepage

### ISSUE THREAD

**Issue by southwolf** [rmosolgo/graphql-ruby#2118]
![image](https://user-images.githubusercontent.com/150648/52914996-b374a880-3309-11e9-926b-c90587dd9298.png)
The link "GraphQL type system" on the homepage goes to https://graphql-ruby.org/schema/definition

![image](https://user-images.githubusercontent.com/150648/52915002-cc7d5980-3309-11e9-8137-2a0ed9c0f945.png)

while the same link on "https://graphql-ruby.org/getting_started" goes to https://graphql.org/learn/schema/#type-system (the correct one)

Or the problem is actually wrong description of "Define your schema" - which should be using a different demo code snippet?

**Comment by rmosolgo** [comment]
Thanks for pointing this out! I updated the link text in 86cdfd148 to make it a bit clearer where it's going.
