### ISSUE TITLE
Can't override `GraphQL::Schema.id_from_object`

### ISSUE THREAD

**Issue by michiomochi** [rmosolgo/graphql-ruby#2120]
graphql-ruby version is v1.9.2.
`id_from_object` can't override (there is workaround), so `MyAppSchema.id_from_object must be implemented` error occurs when GraphQL query executed.

## NG Implement

```
class MyAppSchema < GraphQL::Schema
  ~
  query Types::MyAppQuery
  mutation Types::MyAppMutation

  self.id_from_object
    # Not executed
  end
  ~
end
```

## Work Around

I discovered that if define `self.id_from_object` before `query` or `mutation`, it will be fine.

```
class MyAppSchema < GraphQL::Schema
  ~
  self.id_from_object
    # Not executed
  end
  ~
  query Types::MyAppQuery
  mutation Types::MyAppMutation
  ~
end
```

**Comment by ZeroSoulEater** [comment]
the workaround is not working for me

**Comment by ZeroSoulEater** [comment]
the  loading feature is not working without this method
argument :building_id, ID, required: true, loads: Types::BuildingType

**Comment by rmosolgo** [comment]
Could you please share the full error message and stack trace? I don't quite understand how this is happening, and it's very hard to debug without the relevant details!

**Comment by daemonsy** [comment]
Hi @michiomochi I'm closing this because it's been a while. If you're still having any issues, feel free to reopen it :)
