### ISSUE TITLE
Sort or order by a nested field and/or virtual attribute?

### ISSUE THREAD

**Issue by terencechow** [rmosolgo/graphql-ruby#2124]
I'm trying to sort / order by a nested field. I've done some searching but could not find any result. I think the issue also applies to virtual attributes. Am I missing something? Or is this functionality non-existent in `graphql-ruby`

Example:

```
ExampleType = GraphQL::ObjectType.define do
   name 'Example'
   description '...'
   field :nested_field, NestedType, 'some nested field' do
       // some result that is virtually calculated and returns
       OpenStruct.new(a: 123//some random number, b: 'some string')
   end
end

QueryType = GraphQL::ObjectType.define do
    name 'query'
    field: examples, types[ExampleType] do
        resolve -> (_obj, args,_ctx) {
            // NOTE: How to order by nested field here? Keep in mind the nested attribute is not in active record
            Example.where(args['id'])
            // Note: if this resolved the nested field I could order it here, but since it does not resolve 
            // nested fields here, I can't order it here. Is there somwhere else I can order it?
        }
    end
end
```
And if I am trying to get a list of examples ordered by nested_field.a:

```
query getExamples {
    examples(ids: ["1","2"], order: 'nested_field.a desc') {
        nested_field {
             a
        }
    }
}
```

**Comment by rmosolgo** [comment]
Hi there, GraphQL-Ruby doesn't provide anything special for this. You should use whatever makes sense for your application and data model: 

- If you're using active record, you'd want to `.join` the other table and order by a column by it 
- If you're not using AR, then you'd want to `.sort_by` the array to get a sorted array 


> // Note: if this resolved the nested field I could order it here, but since it does not resolve 
> // nested fields here, I can't order it here. Is there somwhere else I can order it?

No, there's nowhere else to apply an order!
