### ISSUE TITLE
1.8.10 Arguments not passed to underlying object

### ISSUE THREAD

**Issue by terencechow** [rmosolgo/graphql-ruby#2128]
I have an active record model, let's call it `Example`. It has a method let's call `some_field`. I pass an argument to my query and I expect it to call my method with the argument. Instead it does not

Example.rb (active record model)
```
def some_field(some_arg: "DEFAULT")
       puts some_arg // expect this to be 'ABC' not 'DEFAULT'
end
```

Graphql query
```
query getExamples {
                examples(ids: ["example-1", "example-2"]) {
                  id,
                  some_field(some_arg: "ABC") {
                    a,
                    b
                  }
                }
              }
```

where examples resolves with an active record result: 
```
    resolve -> (_obj, args, _ctx) do 
         Example.where(ids: args['ids')
    end
```

And the Example type is defined as:
```
ExampleType = GraphQL::ObjectType.define do
  name 'Example'
  description 'An example'
  field: id, types.Int, 'Id'
  field :some_field, SomeNestedType, 'Some nested field' do
    argument :some_arg, types.String, default_value: 'DEFAULT VALUE'
  end
end
```

**Comment by terencechow** [comment]
Note: passing a resolve function to `some_field` worked but its kind of awkward since I'm just calling the underlying object with the argument available...

```
field :some_field, SomeNestedType, 'some nested field' do
    argument :some_arg, types.String, default_value: 'DEFAULT VALUE'
    resolve -> (obj, args, ctx) {
      obj.some_field(some_arg: args[:some_arg])
    }
  end
```

**Comment by rmosolgo** [comment]
Hi! I think the behavior you're expecting _is_ supported by class-based fields (https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/field.rb#L534). But, you can see that for legacy-style fields, the default behavior is to ignore the arguments: https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/field/resolve.rb#L54

I'm not updating legacy-style schema objects anymore, so I recommend updating to class-based! I hope you can give it a try, and please open an issue if you run into any trouble.
