### ISSUE TITLE
nil value Pundit policy lookup failure

### ISSUE THREAD

**Issue by jordanthomas** [rmosolgo/graphql-ruby#2129]
An error is thrown trying to lookup the policy on a field when a query on that field returns `null`.

### user_type.rb

```
 class UserType < BaseType
    graphql_name 'User'
    pundit_role :staff
    field :permissions, [Types::PermissionType], null: true
  end
```

### Stack trace

```
No policy found for:

- Type: Permission
- Runtime value: `nil`

Pundit error: Pundit::NotDefinedError, unable to find policy scope of nil
```

<details>
<pre>
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-pro-1.9.9/lib/graphql/pro/pundit_integration.rb:131:in `rescue in scope_by_pundit_policy'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-pro-1.9.9/lib/graphql/pro/pundit_integration.rb:125:in `scope_by_pundit_policy'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-pro-1.9.9/lib/graphql/pro/pundit_integration.rb:114:in `scope_items'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/schema/field.rb:408:in `block in apply_scope'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/schema.rb:1056:in `after_lazy'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/schema/field.rb:407:in `apply_scope'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/schema/field.rb:359:in `block in resolve_field'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/schema.rb:1056:in `after_lazy'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/schema/field.rb:342:in `resolve_field'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-errors-0.2.0/lib/graphql/errors.rb:28:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-errors-0.2.0/lib/graphql/errors.rb:28:in `block in instrument'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/schema/member/instrumentation.rb:74:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/field.rb:248:in `resolve'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/execution/execute.rb:295:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/schema/middleware_chain.rb:49:in `invoke_core'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/schema/middleware_chain.rb:38:in `invoke'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/execution/execute.rb:108:in `block in resolve_field'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/tracing.rb:57:in `block in trace'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/tracing.rb:73:in `block (2 levels) in call_tracers'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/tracing.rb:71:in `call_tracers'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/tracing.rb:73:in `block in call_tracers'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/backtrace/tracer.rb:45:in `trace'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/tracing.rb:73:in `call_tracers'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/tracing.rb:57:in `trace'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/execution/execute.rb:107:in `resolve_field'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/execution/execute.rb:71:in `block in resolve_selection'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/execution/execute.rb:64:in `each'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/execution/execute.rb:64:in `resolve_selection'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/execution/execute.rb:260:in `resolve_value'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/execution/execute.rb:189:in `continue_resolve_field'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/execution/execute.rb:160:in `continue_or_wait'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/execution/execute.rb:133:in `resolve_field'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/execution/execute.rb:71:in `block in resolve_selection'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/execution/execute.rb:64:in `each'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/execution/execute.rb:64:in `resolve_selection'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/execution/execute.rb:36:in `block in resolve_root_selection'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/tracing.rb:57:in `block in trace'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/tracing.rb:73:in `block (2 levels) in call_tracers'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/tracing.rb:71:in `call_tracers'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/tracing.rb:73:in `block in call_tracers'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/backtrace/tracer.rb:45:in `trace'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/tracing.rb:73:in `call_tracers'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/tracing.rb:57:in `trace'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/execution/execute.rb:32:in `resolve_root_selection'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/execution/multiplex.rb:108:in `begin_query'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/execution/multiplex.rb:81:in `block in run_as_multiplex'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/execution/multiplex.rb:80:in `map'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/execution/multiplex.rb:80:in `run_as_multiplex'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/execution/multiplex.rb:69:in `block (2 levels) in run_queries'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/execution/multiplex.rb:175:in `block in instrument_and_analyze'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/execution/multiplex.rb:167:in `instrument_and_analyze'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/execution/multiplex.rb:68:in `block in run_queries'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/tracing.rb:57:in `block in trace'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/tracing.rb:73:in `block (2 levels) in call_tracers'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/tracing.rb:71:in `call_tracers'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/tracing.rb:73:in `block in call_tracers'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/backtrace/tracer.rb:30:in `trace'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/tracing.rb:73:in `call_tracers'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/tracing.rb:57:in `trace'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/execution/multiplex.rb:58:in `run_queries'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/execution/multiplex.rb:48:in `run_all'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/schema.rb:347:in `block in multiplex'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/schema.rb:1122:in `with_definition_error_check'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/schema.rb:346:in `multiplex'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.8.14/lib/graphql/schema.rb:323:in `execute'
/Users/jordanthomas/Projects/ebth-com/app/controllers/graphql_controller.rb:24:in `execute'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6.1/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6.1/lib/abstract_controller/base.rb:186:in `process_action'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/react-rails-2.4.4/lib/react/rails/controller_lifecycle.rb:31:in `use_react_component_helper'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/callbacks.rb:135:in `run_callbacks'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6.1/lib/action_controller/metal/rescue.rb:20:in `process_action'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/notifications.rb:166:in `block in instrument'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/notifications.rb:166:in `instrument'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6.1/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.1.6.1/lib/active_record/railties/controller_runtime.rb:22:in `process_action'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6.1/lib/abstract_controller/base.rb:124:in `process'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionview-5.1.6.1/lib/action_view/rendering.rb:30:in `process'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6.1/lib/action_controller/metal.rb:189:in `dispatch'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6.1/lib/action_controller/metal.rb:253:in `dispatch'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6.1/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6.1/lib/action_dispatch/routing/route_set.rb:31:in `serve'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6.1/lib/action_dispatch/journey/router.rb:50:in `block in serve'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6.1/lib/action_dispatch/journey/router.rb:33:in `each'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6.1/lib/action_dispatch/journey/router.rb:33:in `serve'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6.1/lib/action_dispatch/routing/route_set.rb:844:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/omniauth-1.8.1/lib/omniauth/strategy.rb:190:in `call!'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/omniauth-1.8.1/lib/omniauth/strategy.rb:168:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/scout_statsd_rack-0.1.7/lib/scout_statsd_rack.rb:33:in `call_with_timing'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/scout_statsd_rack-0.1.7/lib/scout_statsd_rack.rb:21:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jquery-fileupload-rails-0.4.7/lib/jquery/fileupload/rails/middleware.rb:14:in `_call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jquery-fileupload-rails-0.4.7/lib/jquery/fileupload/rails/middleware.rb:10:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/flipper-0.13.0/lib/flipper/middleware/memoizer.rb:64:in `memoized_call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/flipper-0.13.0/lib/flipper/middleware/memoizer.rb:42:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/flipper-0.13.0/lib/flipper/middleware/setup_env.rb:35:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/etag.rb:25:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/conditional_get.rb:38:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/head.rb:12:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:232:in `context'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:226:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6.1/lib/action_dispatch/middleware/cookies.rb:613:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.1.6.1/lib/active_record/migration.rb:556:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6.1/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/callbacks.rb:97:in `run_callbacks'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6.1/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6.1/lib/action_dispatch/middleware/executor.rb:12:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rollbar-2.17.0/lib/rollbar/middleware/rails/rollbar.rb:24:in `block in call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rollbar-2.17.0/lib/rollbar.rb:146:in `scoped'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rollbar-2.17.0/lib/rollbar/middleware/rails/rollbar.rb:22:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/better_errors-2.4.0/lib/better_errors/middleware.rb:84:in `protected_app_call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/better_errors-2.4.0/lib/better_errors/middleware.rb:79:in `better_errors_call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/better_errors-2.4.0/lib/better_errors/middleware.rb:57:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6.1/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rollbar-2.17.0/lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6.1/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.1.6.1/lib/rails/rack/logger.rb:36:in `call_app'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.1.6.1/lib/rails/rack/logger.rb:24:in `block in call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/tagged_logging.rb:26:in `tagged'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/tagged_logging.rb:69:in `tagged'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.1.6.1/lib/rails/rack/logger.rb:24:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:13:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6.1/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/request_store-1.4.1/lib/request_store/middleware.rb:19:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6.1/lib/action_dispatch/middleware/request_id.rb:25:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/method_override.rb:22:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/runtime.rb:22:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/dragonfly-1.2.0/lib/dragonfly/cookie_monster.rb:9:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6.1/lib/action_dispatch/middleware/executor.rb:12:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.1.6.1/lib/action_dispatch/middleware/static.rb:125:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/sendfile.rb:111:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/webpacker-3.5.5/lib/webpacker/dev_server_proxy.rb:22:in `perform_request'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.1.6.1/lib/rails/engine.rb:522:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/configuration.rb:225:in `call'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/server.rb:632:in `handle_request'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/server.rb:446:in `process_client'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/server.rb:306:in `block in run'
/Users/jordanthomas/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
</pre>
</details>

**Comment by rmosolgo** [comment]
Thanks for the detailed report! I fixed the underlying issue in `graphql` version `1.9.3`, please give that one a go and let me know if you have any more trouble.
