### ISSUE TITLE
ArgumentError (missing keyword: field):

### ISSUE THREAD

**Issue by gauravtiwari** [rmosolgo/graphql-ruby#213]
Hey @rmosolgo 

Getting follow error when creating a new relation connection object - `ArgumentError (missing keyword: field):`

I see addition of new field argument. Does this require passing a field option?

**Comment by rmosolgo** [comment]
Oops, we forgot about the range add use case! This was added in #206, I guess it should be optional

Definitely need a range add test to avoid this in the future, sorry!

**Comment by gauravtiwari** [comment]
Yeah, I think not needed in all use cases. No worries! 😄

**Comment by gauravtiwari** [comment]
All works! Fixed by #215

**Comment by panbanda** [comment]
When I upgraded from 1.9.14 to 1.9.16 this may have been introduced.  In my rspec I initialize the mutation like this:

```ruby
Mutations::Auth::Login.new(object: nil, context: {}).resolve(args)
```

And all my mutations fail when `field:` is missing.  The following passes:

```ruby
Mutations::Auth::Login.new(object: nil, field: nil, context: {}).resolve(args)
```

**Comment by rmosolgo** [comment]
Thanks for sharing your solution! It's also listed here https://github.com/rmosolgo/graphql-ruby/blob/master/CHANGELOG.md#breaking-changes-1

**Comment by firedev** [comment]
Sorry I don't get it, I did interit from my own `Base` class but I didn't override `initialize`. Why do I have to add `field: nil` everywhere?

**Comment by rmosolgo** [comment]
The method has a new required argument. It's meant to be called by GraphQL-Ruby internals, which I already updated. If you're using it in some other way, you'll have to update it.

**Comment by firedev** [comment]
I am updating all tests. I thought it meant to be an optional argument. Guess it wasn't.
