### ISSUE TITLE
Subscriptions don't work with new interpreter

### ISSUE THREAD

**Issue by mengledowl** [rmosolgo/graphql-ruby#2131]
With the latest version of the gem, opting into the new interpreter (`use GraphQL::Execution::Interpreter`), subscriptions are not working correctly.

First, versions and relevant details:

* ruby 2.6.1
* rails 5.2.2
* graphql-ruby 1.9.2
* using ActionCable
* class-based everything

We are trying to pull in subscriptions and just updated to the latest version of the gem prior to starting on it. With the new interpreter turned on, we are able to establish the websocket connection, and can see from the logs that the subscription confirmation is being transmitted, along with the initial transmission: `GraphqlChannel transmitting {:result=>nil, :more=>true}`. When triggering the subscription, everything goes smoothly including the expected log message from ActionCable about broadcasting the message - and of course the fact that no message ever makes it to the client.

The only thing I would expect to see in the logs that I'm _not_ seeing is the message about streaming to the client which lead me on a hunt to see if the subscription was really being created successfully in the gem.

Commenting out `use GraphQL::Execution::Interpreter` in our schema and restarting the server results in the subscriptions executing successfully.

I've been able to narrow down the issue to `write_subscription` not being called in this method:

https://github.com/rmosolgo/graphql-ruby/blob/25be1b945ccab3c3515309e6d4148d09d4ba5b2e/lib/graphql/subscriptions/instrumentation.rb#L31-L36

When hitting this method with the new interpreter turned on, `query.context.namespace(:subscriptions)[:events]` is empty. When it's turned off, it's not, so `write_subscription` gets called and begins streaming.

This is as far as I've been able to get, as I'm not really sure where that gets set (other than it being set to an empty array in the `before_query` callback), so I figured it was time to open up an issue rather than continue to bang my head against it.

**Comment by martintomas** [comment]
Have you extended your Subscription root type with `GraphQL::Subscriptions::SubscriptionRoot`? It should look for example as:
```
class Types::Subscription < Types::BaseObject
  # Extend this module to support subscription root fields with Interpreter
  extend GraphQL::Subscriptions::SubscriptionRoot
end
```
When You check `SubscriptionRoot` module, there is `after_resolve` method that adds event that you are probably missing.

I also discovered that this will unfortunately not work in case that your subscription fields are in interface and you are `implementing` it in your base type. Just to be clear, this is working for me:
```
class Types::SubscriptionType < Types::BaseObject
  extend GraphQL::Subscriptions::SubscriptionRoot
  field :updated_orders_count, subscription: Resolvers::Subscriptions::OrderCount
end
```
But this is not working:
```
class Types::SubscriptionType < Types::BaseObject
  extend GraphQL::Subscriptions::SubscriptionRoot
  implements Subscriptions::OrderSubscriptionType # contains :updated_orders_count field
end
```

**Comment by mengledowl** [comment]
@martintomas The `extend ...` line did the trick - we missed that in the docs since it was under the section about the new interpreter rather than under the subscriptions. Thanks!

**Comment by rmosolgo** [comment]
Glad you got to the bottom of it, I've beent hinking that `use GraphQL::Execution::Interpreter` should go `schema.subscription.include(SubscriptionRoot)` "for you", but I'm not sure if it's too magical ✨ .
