### ISSUE TITLE
New interpreter breaks NewRelic tracing

### ISSUE THREAD

**Issue by tmtrademarked** [rmosolgo/graphql-ruby#2133]
Hey, all. It looks like using the new Interpreter breaks New Relic tracing on our introspection queries - but seemingly *only* on Introspection. If I use the following schema:
```
class MySchema < GraphQL::Schema
  use GraphQL::Execution::Interpreter
  use GraphQL::Tracing::NewRelicTracing, set_transaction_name: true
end
```

I get the following error on an introspection query: 
```
[adbc4f71-95fa-4d69-9fb5-b9a73feaf32d] Completed 500 Internal Server Error in 62ms (ActiveRecord: 4.4ms)
[adbc4f71-95fa-4d69-9fb5-b9a73feaf32d] 
NoMethodError (undefined method `kind' for #<LateBoundType @name=__Schema>):
  app/controllers/graphql_controller.rb:18:in `execute'
  lib/middleware/version_endpoint.rb:16:in `call'
  lib/middleware/force_admin.rb:15:in `call'
  lib/middleware/force_www.rb:13:in `call'
```

As soon as I comment out `use GraphQL::Execution::Interpreter`, though, the query goes back to working. I suspect there's something really simple wrong in the plugin somewhere, but it's not obvious to me how to track this down. Any thoughts on work-arounds or fixes? For now, I'm just disabling the interpreter, but figured I'd point this out.

**Comment by rmosolgo** [comment]
Hi! Thanks for reporting this. Could you please try graphql 1.9.3 from Rubygems and reopen this if you encounter the issue again? I think it's fixed by #2137 (It was also reported in #2125).

**Comment by tmtrademarked** [comment]
Ah - 1.9.3 did in fact fix this! I was previously being dumb and testing with 1.9.2 instead. Thanks!

**Comment by rmosolgo** [comment]
No, not dumb at all! I pushed the fix after you opened this issue :)
