### ISSUE TITLE
How to test file uploads

### ISSUE THREAD

**Issue by guyzmo** [rmosolgo/graphql-ruby#2146]
Hello :wave:,

I'm writing tests for my graphql-ruby implementation using rspec, using the template provided in the documentation. And I'd like to test a mutation where I'm uploading a file, using jetruby/apollo_upload_server-ruby to do so:

```
RSpec.describe(MySchema) do
  let(:result) { MySchema.execute(query, context, variables) }
  let(:query) { "mutation foo($file:Upload!) { uploadFile($file) { url } }" }
  let(:variables) { { file: nil } } # XXX How can I push a test file?
end
```

Would you know what type shall I use to prepare the file for upload and validate the test?

**Comment by rmosolgo** [comment]
Hi, sorry, I'm not familiar with that project and I don't know how to write a test for it! I hope the maintainers of that project can help.
