### ISSUE TITLE
No error when executing mutation not in schema

### ISSUE THREAD

**Issue by shelmire** [rmosolgo/graphql-ruby#2147]
graphql-ruby Version: 1.8.11

Steps to reproduce:

1) Create mutation type.
2) DON'T add mutation type to list of fields in mutation_type.rb.
3) Attempt to execute mutation.

Result: You will not get an error or any sort of indication that the mutation wasn't added to MutationType, and the mutation will not happen.

This has happened to me twice a few months apart, and it's a tough one to track down (although of course, now it's going to be the first thing I check). `MySchema.execute()` should error, shouldn't it? Unless I'm missing something - let me know!

**Comment by shelmire** [comment]
I noticed from the guide after some more searching, "The validation rules are part of the GraphQL specification and built into GraphQL-Ruby, so there’s not really a way to customize this behavior, except to pass validate: false when executing a query, which skips validation altogether." I assume this means this is intended behavior, and that the errors must be viewed and handled on the client side. Closing issue.

**Comment by rmosolgo** [comment]
Hey @shelmire , sorry about the hangup. I don't quite understand what you mean. Could you share an example query string (which you _expect_ to error) and the resulting graphql response? Given the situation you describe, I would _also_ expect an error in the response!
