### ISSUE TITLE
AST Visitor should return nil for all on_<type> hooks

### ISSUE THREAD

**Issue by chrisseto** [rmosolgo/graphql-ruby#2148]
This error only appears while traversing queries that contain a list of something while attempting to inspect the [`parent` parameter](https://github.com/rmosolgo/graphql-ruby/blob/44d0548330cf1c030d81f9be90540110ba0d57ab/lib/graphql/analysis/ast/visitor.rb#L167).

As the `AST::Visitor` doesn't explicitly return nil, it ends up returning a the list of analyzers being run.
https://github.com/rmosolgo/graphql-ruby/blob/44d0548330cf1c030d81f9be90540110ba0d57ab/lib/graphql/analysis/ast/visitor.rb#L236

This causes the `parent` argument to become whatever the second analyzer is, or `nil` in the case of one analyzer, as returning anything besides `nil` is seen as an attempt to rewrite the AST.
https://github.com/rmosolgo/graphql-ruby/blob/df0e6b37bbd9510b73d11ff7fcbe7c3b6a1f7107/lib/graphql/language/visitor.rb#L104

I'll put up a PR in the next few days if no one beats me to it!

**Comment by rmosolgo** [comment]
Oh my! Could you share some example analyzer code that causes this bug? I don't quite get it!

**Comment by chrisseto** [comment]
The analyzer only breaks if it attempts to touch `parent`. For my specific example I'm adding in slightly more granular argument validation, `x > 10 but < 20`.

```ruby
class Analyzers::Validation < GraphQL::Analysis::AST::Analyzer

  def initialize(query)
    super
    @errors = []
  end

  def result
    @errors || nil
  end

  def on_enter_abstract_node(node, parent, visitor)
    # Only interested in input objects
    return unless node.visit_method == :on_input_object

    # Pulled from the static analysis on input_object arguments
    arg_defn = visitor.argument_definition
    defn = if arg_defn && arg_defn.type.unwrap.kind.input_object?
             arg_defn.type.unwrap
           else
             visitor.field_definition
           end

    # Breaks as parent here is nil :(
    defn.arguments.values.find { |argument| argument.name == parent.name }

    # Additional logic ...
  end
```




https://github.com/rmosolgo/graphql-ruby/blob/44d0548330cf1c030d81f9be90540110ba0d57ab/lib/graphql/analysis/ast/visitor.rb#L166-L170

The input object looks roughly like so:
```ruby
class Types::Cheese
   argument :years_old, Integer, required: true
end

class Types::DairyInput 
   argument :cheeses, [Types::Cheese], required: true
end
```

Once visitor gets to the input object for `DairyInput` we end up here:
https://github.com/rmosolgo/graphql-ruby/blob/df0e6b37bbd9510b73d11ff7fcbe7c3b6a1f7107/lib/graphql/language/visitor.rb#L98-L108
where `new_node` and `node` are the `Types::DairyInput` node, the first iteration runs just fine, but the return value of `on_node_with_modifications` is the return value of  `on_abstract_node`:
https://github.com/rmosolgo/graphql-ruby/blob/44d0548330cf1c030d81f9be90540110ba0d57ab/lib/graphql/analysis/ast/visitor.rb#L166-L170
Which happens to be the list of analyzers
https://github.com/rmosolgo/graphql-ruby/blob/44d0548330cf1c030d81f9be90540110ba0d57ab/lib/graphql/analysis/ast/visitor.rb#L236

Lines 104-105 replace the parent node (`new_node`) with the second analyzer or `nil` if there is only one analyzer. The analyzer then breaks if there's a second element to `cheeses` as `parent` is no longer part of the AST.
https://github.com/rmosolgo/graphql-ruby/blob/df0e6b37bbd9510b73d11ff7fcbe7c3b6a1f7107/lib/graphql/language/visitor.rb#L98-L108




Actually, after following this all the way though I think the actual error is right here:
https://github.com/rmosolgo/graphql-ruby/blob/df0e6b37bbd9510b73d11ff7fcbe7c3b6a1f7107/lib/graphql/language/visitor.rb#L188-L191
The comment says to return the original input values but it returns the result of `visit_node` instead of `[node, parent]`
