### ISSUE TITLE
[pro] Changelog link in `graphql-pro.gemspec`

### ISSUE THREAD

**Issue by cheerfulstoic** [rmosolgo/graphql-ruby#2155]
I can't see the `gemspec` in the released version of the `graphql-pro` gem, but I was wondering if it would be helpful to have the [`CHANGELOG-pro.md`](https://github.com/rmosolgo/graphql-ruby/blob/master/CHANGELOG-pro.md) file be linked to inside of it.  We use dependabot to keep our gems up-to-date and I think (hope?) that if the changelog link is in the `gemspec` that dependabot would be able to show the changes for us automagically in it's PRs.  [Here's a post](https://olivierlacan.com/posts/changelogs-on-rubygems-org/) on how to put a reference to a changelog in a gemspec.

**Comment by cheerfulstoic** [comment]
Thanks!  I just tried re-creating and it didn't work, but it just force-pushed new changes to the same PR rather that create a new PR, so I don't know if it was also supposed to update the PR description.  🤷‍♂️  We'll see going forward!

**Comment by cheerfulstoic** [comment]
Ah, I see that it updated from .11 to .12, but .12 was out and so I gather than probably .13 will have the `gemspec` change.  I'll keep an eye out ;)

**Comment by cheerfulstoic** [comment]
`1.10.0` just came through from `dependabot` and the changes for the differences in versions showed up.  Thanks again!

**Comment by rmosolgo** [comment]
🎉  Glad to hear it worked!
