### ISSUE TITLE
ActionCableLink.js and Subscription example does not handle errors well

### ISSUE THREAD

**Issue by julianalucena** [rmosolgo/graphql-ruby#2159]
Subscriptions  API doc has an example code to implement `GraphqlChannel < ApplicationCable::Channel`, the relevant part is detailed below:

```ruby
    payload = {
      result: result.subscription? ? { data: nil } : result.to_h,
      more: result.subscription?,
    }
```

In an error scenario, such as an top-level error like `raise GraphQL::ExecutionError`, the response contains `errors` key, but do not necessarily contains `data` key. For example:

```json
{
   "result":{
      "data":null,
      "errors":[
         {
            "message":"An object was hidden due to permissions",
            "locations":[ { "line":2,  "column":3 }],
            "path":["messageSent"],
            "extensions":{ "code":"FORBIDDEN" }
         }
      ]
   },
   "more":true
}
```

The absence of `data` or filled with `nil` value leads to an error because of the JS code below:

https://github.com/rmosolgo/graphql-ruby/blob/05ce45a65bde465524406a96769cd40912e8d693/javascript_client/subscriptions/ActionCableLink.js#L34-L37

Since `data` is falsy, `observer.next(payload.result)` will not be called and our `<Subscription/>` component will not react as expected. 

The same problem applies to always returning `{ data: nil }`, if `result.subscription?` evals to `true`, because `errors` key will not be passed as payload to be trasmitted by Action Cable. 

Does that make sense to you too? 🤔

**Comment by rmosolgo** [comment]
Thanks for the detailed writeup of this issue! I agree it seems to overlook errors completely 🙈 . 

It seems like the two spots you mentioned could use updates to check for errors, do you want to try a PR for that? I'm happy to help out along the way if you're interested.

**Comment by julianalucena** [comment]
Okay, @rmosolgo! I'll submit a PR in a few days.

By the way, thanks for the project! 🤘

**Comment by rmosolgo** [comment]
These days, the link passes along data _and_ errors 🎉 

https://github.com/rmosolgo/graphql-ruby/blob/120ec5e5fd6c9d485f57479cb3861ca1c4bb4a84/javascript_client/src/subscriptions/ActionCableLink.ts#L45-L47
