### ISSUE TITLE
Array index excluded in error path

### ISSUE THREAD

**Issue by chrisseto** [rmosolgo/graphql-ruby#2160]
I noticed that when validation fails on arrays, the index of the offending object is not included in the error's `path` key. 
I got halfway through adding it in, realized that it would more or less be a breaking change, and wanted to check if this was intentional or not.

If this would be a desirable feature to add in, should the index be a string or an integer?

Examples pulled from `spec/graphql/static_validation/rules/required_input_object_attributes_are_present_spec.rb`
```rb
offending_query = "missingNestedRequiredInputObjectAttribute: searchDairy(product: [{fatContent: 1.2, order_by: {}}]) { __typename }"

missing_order_by_direction_error = {
  "message"=>"Argument 'direction' on InputObject 'ResourceOrderType' is required. Expected type String!",
  "locations"=>[{"line"=>8, "column"=>100}],
  # I would expect path to actually be:
  # "path"=>["query getCheese", "missingNestedRequiredInputObjectAttribute", "product", "0", "order_by", "direction"],
  # Rather than:
  "path"=>["query getCheese", "missingNestedRequiredInputObjectAttribute", "product", "order_by", "direction"],
  "extensions"=>{
    "code"=>"missingRequiredInputObjectAttribute",
    "argumentName"=>"direction",
    "argumentType"=>"String!",
    "inputObjectType"=>"ResourceOrderType"
  }
}
```

**Comment by rmosolgo** [comment]
:+1: from me for adding it! I think we can call it a breaking _fix_ 😅
