### ISSUE TITLE
[PRO] Authorization issue: owner's pundit role ignored

### ISSUE THREAD

**Issue by ingemar** [rmosolgo/graphql-ruby#2164]
Hi Robert, 

I might be wrong but I suspect this to be a bug.

`GraphQL::Pro::PunditIntegration::HasPunditRole#pundit_policy_class` looks up the `@owner`'s `.pundit_policy_class`, but `HasPunditRole#pundit_role` does **not** consider its `@owner`'s `.pundit_role`, thus leading to wrong role being called on the pundit policy class, and a undefined method being thrown.

We're on gem version `1.9.12`.

**Comment by rmosolgo** [comment]
Hey, thanks for reporting this! Could you share an example snippet where the wrong role is used? I don't quite understand when `@owner.pundit_role` _should_ be used!

**Comment by rmosolgo** [comment]
For clarity's sake, the _purpose_ of that code is to support this feature: 

> [Y]ou can add pundit_role: options to your fields ... It will call the named role (eg, #staff?) on the parent object’s policy (eg JobPostingPolicy).

(https://graphql-ruby.org/authorization/pundit_integration.html#authorizing-fields)

It uses the _object's_ policy, but you can specify the role to use for a certain field. So the field uses `@owner.pundit_policy_class` (the object's policy) but its own `pundit_role`. 

However, it sounds like maybe some particular case is not supported. Please feel free to share some example code there!

**Comment by ingemar** [comment]
Thanks for the help!
