### ISSUE TITLE
Interpreter Support for Execution Timeouts

### ISSUE THREAD

**Issue by jturkel** [rmosolgo/graphql-ruby#2167]
The 1.9 `GraphQL::Execution::Interpreter` runtime doesn't support middleware which means the `GraphQL::Schema::TimeoutMiddleware` won't work. Is there a recommendation migration path? The best I could come up with was using a field extension resolve hook but that's a bit painful to use throughout my schema.

**Comment by jturkel** [comment]
I was able to get this working with the following [tracer](https://graphql-ruby.org/queries/tracing.html) (word of warning - I haven't yet tested this with multiplexing and lazy field execution so that might not be implemented properly):

```ruby
class TimeoutTracer
  TIMEOUT_STATE_KEY = :graphql_execution_timeout_state

  attr_reader :timeout, :timeout_callback

  def self.use(schema, **options, &block)
    tracer = new(**options, &block)
    schema.tracer(tracer)
  end

  def initialize(timeout:, &timeout_callback)
    @timeout = timeout
    @timeout_callback = timeout_callback || Proc.new {}
  end

  def trace(key, data)
    case key
    when 'execute_query'
      with_timeout_context([data.fetch(:query)]) { yield }
    when 'execute_multiplex'
      with_timeout_context(data.fetch(:multiplex).queries) { yield }
    when 'execute_field', 'execute_field_lazy'
      if Process.clock_gettime(Process::CLOCK_MONOTONIC, :millisecond) > Thread.current[TIMEOUT_STATE_KEY][:at]
        timeout_callback.call(queries: Thread.current[TIMEOUT_STATE_KEY][:queries])
        GraphQL::ExecutionError.new('Query timeout')
      else
        yield
      end
    else
      yield
    end
  end

  def with_timeout_context(queries)
    # The query context isn't available in execute_field callbacks when using the interpreter so we have to
    # store the timeout in a thread local
    if Thread.current[TIMEOUT_STATE_KEY].nil?
      Thread.current[TIMEOUT_STATE_KEY] = {
        at: Process.clock_gettime(Process::CLOCK_MONOTONIC, :millisecond) + timeout * 1000,
        queries: queries
      }
      begin
        yield
      ensure
        Thread.current[TIMEOUT_STATE_KEY] = nil
      end
    else
      yield
    end
  end
end
```
It's relatively straightforward and easy to package up in a plugin. The biggest downside (other than it not being supported OOTB anymore :stuck_out_tongue_winking_eye:) is the use of thread locals. Perhaps this could be mitigated by making the `GraphQL::Query` (and thus the `GraphQL::Query::Context` for stashing timeout context) available in the `data` hash for `'execute_field'` and `'execute_field_lazy'` trace events? I'd be happy to put up a PR for any of this if you're interested.

**Comment by rmosolgo** [comment]
Hey, thanks for sharing your solution here! I would _like_ to support timeout with the interpreter, but I haven't gotten to it. The improvement you mentioned sounds good!

**Comment by jturkel** [comment]
I created PR #2205 with the enhancement to include the `GraphQL::Query` in `execute_field` and `execute_field_lazy` trace events. I'd be happy to clean up my implementation of a timeout tracer and put a PR for it unless you're planning on implementing interpreter timeouts through some other mechanism.
