### ISSUE TITLE
entire array field resolves null when any element fails authorization

### ISSUE THREAD

**Issue by mlwilkerson** [rmosolgo/graphql-ruby#2169]
Using graphql-ruby `1.9.3` and authorization checking. I'm seeing unexpected behavior where, when a field's type is `[Bar], null: false`, a `null` is being returned (and throwing a "Cannot return null for non-nullable field" error) when _any_ elements of that array fail authorization.

Here's a reproduction ([gist](https://gist.github.com/mlwilkerson/590bd83b2b14993ae8a66fa56fe75494))

```ruby
require 'graphql'

class Bar < GraphQL::Schema::Object
  field :color, String, null: false

  def self.authorized?(object, _context)
    object[:color] === 'red'
  end
end

class Query < GraphQL::Schema::Object
  field :bars, [Bar], null: false
  field :bills, [Bar], null: false

  def bars
    [{color: 'red'}, {color: 'blue'}]
  end

  def bills
    [{color: 'green'}]
  end
end

class MySchema < GraphQL::Schema
  query(Query)
end

result = MySchema.execute("query{ bars { color } bills { color } }").to_h

expected = {"data"=>{"bars"=>[{"color"=>"red"}], "bills"=>[]}}

if result == expected
  puts "ok"
else
  puts "EXPECTED: #{ expected }"
  puts "GOT:      #{ result }"
end
```
**Expected**

I'd expect that:
1. for any element that fails authorization, that element would simply be absent from the resulting array
2. if no elements pass authorization, it would result in an empty array

**Actual**

The array field resolves to `null`, which also causes the non-nullable field error to be thrown so that the entire result (`result['data']`) is `nil`.

**Output**
```
$ ruby array_type_null.rb 
EXPECTED: {"data"=>{"bars"=>[{"color"=>"red"}], "bills"=>[]}}
GOT:      {"data"=>nil, "errors"=>[{"message"=>"Cannot return null for non-nullable field Query.bars"}]}
```

**Comment by rmosolgo** [comment]
Hi, thanks for the very detailed report! 

In GraphQL-Ruby 1.9+, the default nullability for list types switched from _nullable_ to _non-null_. So, if the type is `[Bar], null: false`,  then the equivalent GraphQL type is `[Bar!]!`. That means that the list _can't_ contain `nil`. If it _does_ contain `nil`, then the error propagates as you've observed here. 

If you want to support `nil`s in your list, Add `null: true` to the list: `[Bar, null: true], null: false` (https://graphql-ruby.org/type_definitions/lists.html#non-null-lists-with-nullable-items).

Another option is to implement [list scoping](https://graphql-ruby.org/authorization/scoping.html) to remove unauthorized items from the list _before_ they get checked by `.authorized?`. 

Does one of those help? Feel free to reopen this if I've misunderstood the situation, but it sounds like it's working as designed 😅

**Comment by mlwilkerson** [comment]
Yes, I can definitely use one of the other approaches. Either looks good. And in my real-world case, the list scoping is actually more like what I should probably be doing anyway.

I didn't realize we could do this (specify nullability _inside_ the square brackets): [https://graphql-ruby.org/type_definitions/lists.html#non-null-lists-with-nullable-items](https://graphql-ruby.org/type_definitions/lists.html#non-null-lists-with-nullable-items). Somehow, I overlooked that page in the docs. Very nice.

Thank you.
