### ISSUE TITLE
Lazilly define Enum values in class based API

### ISSUE THREAD

**Issue by bessey** [rmosolgo/graphql-ruby#2172]
I am upgrading a pre 1.8 `#define` based API to class based, and have found a case where there is no class based equivalent.

Take the following example, of an Enum type who's values are pulled from the database.

```ruby
Types::BlogNameType = GraphQL::EnumType.define do
  name "BlogName"

  Blog.pluck(:key :name).each do |(name, description)|
    value(name.upcase, description)
  end
end
```
Now obviously there is a mostly functionally equivalent class based implementation:
```ruby
class Types::BlogNameType < Types::BaseEnum
  Blog.pluck(:key :name).each do |(name, description)|
    value(name.upcase, description)
  end
end
``` 
However, unlike the `#define` approach, this class will call `Blog.pluck` the second the file is `require`'d, and thus hit the database the second the Rails application is preloaded. This is problematic, because it means for example on a CI machine or just a new developer's machine, commands like `bin/rails db:setup` fail, because the application tries to hit a non existent database when loading the Rails environment.

Rails takes great care to support lazy evaluation of any code that could hit the DB, mostly using optional lambda / proc syntax in place of real values (haha, that sound familiar?). 

Note that this idea isn't really specific to Enums, one could imagine a case where your _fields_ are dynamically defined based on DB contents, but I personally only have the Enum use case.

### API Ideas

```ruby
# Rails like lambda based lazy evaluation, requires a `values` (plural) API 
class Types::BlogNameType < Types::BaseEnum
  values -> { Blog.pluck(:key :name) }
end

# Explicit API
class Types::BlogNameType < Types::BaseEnum
  boot do # alternatives: before_to_graphql  / before_parse
    Blog.pluck(:key :name).each do |(name, description)|
      value(name.upcase, description)
    end
  end
end
```

**Comment by rmosolgo** [comment]
Thanks for opening this! For history's sake, linking the similar-but-different https://github.com/rmosolgo/graphql-ruby/issues/862

**Comment by rmosolgo** [comment]
I think this should work a little better in 1.10, using the new interpreter runtime. In this setup, there's a lot less caching going on, so I think you could call `Types::MyEnumType.value(...)` at _any time_ to add values to an enum type, just like you would in the class definition at load time. 

(In previous versions, the class itself _wasn't_ used at runtime; instead, a singleton instance was generated and cached at boot, and that singleton was used at runtime. In 1.10 + interpreter, the actual classes are actually used at runtime, so dynamic changes to those classes should be reflected at runtime.)

Of course, the question remains, _where_ in a Rails app can you dynamically add this info in a threadsafe way, but I'll let you figure that one out 😅 

Let me know if you give it a try on the latest version and run into any trouble!

**Comment by duffyjp** [comment]
I'm running into this exact situation.  I'm on `1.12.3` and like the OP newly added DB records do not translate into new ENUM options without an app restart.

If anyone has a trick to allow these enums to be lazy loaded or a way to just refresh the entire schema hot please drop me a line.

**Comment by duffyjp** [comment]
@rmosolgo Could we reopen this for further discussion?  

I have an application where users define saved queries we call "definitions" which they then pull from GraphQL.  I was able to add a newly created definition to my DefinitionType enum easily enough (though it feels not very Railsy), but I don't see a way to remove a value.  I'm looking in [schema/enum.rb](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/enum.rb) for such a method.   


Definition Model
```ruby
after_create { Types::DefinitionType.value(graphql_slug, graphql_description) }
```

What could I do for an `after_destroy` callback to remove the enum value?

**Comment by rmosolgo** [comment]
I'd be game to: 

- Expand the `.values` method to accept `(context = GraphQL::Query::NullContext)` : 

  https://github.com/rmosolgo/graphql-ruby/blob/1f2f2a474f1ba143cb5f415723612d88e6de56a8/lib/graphql/schema/enum.rb#L47-L52
 
 - Update the warden to pass `@context` when caching the enum values for the current query: 
 
   https://github.com/rmosolgo/graphql-ruby/blob/1f2f2a474f1ba143cb5f415723612d88e6de56a8/lib/graphql/schema/warden.rb#L136-L140
   
- Add some tests, audit the codebase, etc, to make sure all runtime uses of enum values go through `warden.enum_values(enum_type)` 


Then, enum classes could override `def self.enum_values(ctx)` to dynamically return different values for every query. It's a pretty intense feature, but I agree it'd be useful! 

I plan to investigate that sometime this calendar year, but not anytime particularly soon, so if someone wants to give it a shot, I'd be happy to review a PR!

**Comment by rmosolgo** [comment]
> What could I do for an after_destroy callback to remove the enum value?

Sorry, to answer your question, I can't guarantee this will keep working forever, but you could probably do this: 

```ruby 
after_destroy {
  # this will probably work to delete enum values dynamically, but it depends on calling a private method from graphql-ruby
  private_hash_of_enum_values = Types::DefinitionType.send(:own_values)
  private_hash_of_enum_values.delete(graphql_slug)
}
```

😅
