### ISSUE TITLE
Unexpected behavior if an argument is named "keys"

### ISSUE THREAD

**Issue by lucaong** [rmosolgo/graphql-ruby#2173]
First of all, before reporting the issue, thanks to the maintainers for the outstanding library 👏 

Now, to the issue. If I define an argument for a field called `keys`:

```ruby
field :content_pages, [Types::ContentPage], null: false do
  argument :keys, [String], required: true
end

def content_pages(keys:, unpublished: false)
  ContentPage.where(key: keys)
end
```

I get an error upon querying: `missing keyword: keys`. Curious why the keyword argument `keys` is not set, I printed the arguments of `content_pages`:

```ruby
def content_pages(**args)
  puts(args)
  ContentPage.where(key: args[:keys])
end
```

If I query this field passing `keys: ["foo", "bar"]`, it turns out that `args` is `{ :foo => nil, :bar => nil }` (instead of the expected `{ keys: ["foo", "bar"] }`).

All works perfectly fine if I rename the argument, for example to `page_keys`. I suspect therefore that there is some sort of naming conflict going on.

**Comment by rmosolgo** [comment]
Wow, crazy! Definitely a bug. Could you please share the full error message and stack trace from the error you mentioned above?

**Comment by rmosolgo** [comment]
(Probably related: #2171)

**Comment by lucaong** [comment]
Here is a minimal app reproducing the issue: https://github.com/lucaong/graphql-ruby-issue-2173

I hope this helps

**Comment by lucaong** [comment]
Yeah, #2171 will definitely help people who stumble upon this issue.

Ideally, though, it would be great to be able to use such reserved argument names like `keys` or `values`, as the fact that these names are already defined as methods on `GraphQL::Query::Arguments` is an implementation detail that should probably not affect the user. I need to dig into the codebase a bit before I am able to contribute a PR, but I could look into this soon.

**Comment by lucaong** [comment]
Digging a bit into the code, it seems indeed that #2171 would fix this, and allow using these reserved names as arguments, so my previous comment is redundant.

I think what was happening is that the `keys` method of `GraphQL::Query::Arguments` was mistakenly overridden, and therefore the `GraphQL::Query::Arguments#to_kwargs` method was returning wrong results, in turn calling the resolver method with wrong keyword arguments.

Now, after the fix, the `keys` method won't be overridden, and `to_kwargs` will work as expected, but the definition of the argument helper method will be skipped, and a warning will be logged to inform the user. The lack of a helper method, as I understand, should not be a big issue for those defining resolver methods (that receive arguments as method keyword args) or, alternatively, always accessing arguments as keys (like `args[:arg_name]` instead of `args.arg_name`).

So, thanks a lot for the extra fast response and to @gabrielmdeal for the fix! Looking forward for the next release.

**Comment by lucaong** [comment]
And, I can confirm that the bug is fixed in the demo app https://github.com/lucaong/graphql-ruby-issue-2173 when using the GitHub version of the `graphql` gem. 🎉

**Comment by rmosolgo** [comment]
🎉  Thanks for trying it out. I'll close this since it's fixed on master! Thanks @gabrielmdeal 😊
