### ISSUE TITLE
fields `method` arg doesn't lookup locally first (regression 1.9.? )

### ISSUE THREAD

**Issue by ngouy** [rmosolgo/graphql-ruby#2183]
working (graphql 1.8.x) :
```rb
class MyType < GraphQL::Schema::Object
   field :is_selected, Boolean, "whatever desc", null: true, method: :selected?

    def selected?
        object.has_many_stuffs.any?
    end
end
```

not working in `1.9.3`. It works if I remove the `method: :selected?` from the field options and rename my "local" method `is_selected`

**Comment by swalkinshaw** [comment]
This was highlighted in the Changelog as a breaking change. You should use `resolver_method` now instead of the `method` option.

**Comment by ngouy** [comment]
sorry for this ticket then, my bad, hasn't look close enough apparently
