### ISSUE TITLE
[pro] Stable cursor generation with RangeAdd

### ISSUE THREAD

**Issue by wakeless** [rmosolgo/graphql-ruby#2184]
I've encountered an error when querying an edge that has been added. The error is:

```
Failed to build GraphQL cursor, no attribute `cursor_0`
```

graphql code: 
```GRAPHQL
  mutation() {
    newMessageEdge {
      __typename
      cursor
      node {
        reference
      }
    }
  }
```

Mutation code: 
```RUBY
      range_add = GraphQL::Relay::RangeAdd.new(
        parent: chat,
        collection: chat.messages
        item: message,
        context: context
      )

      respond_with(
        chat: chat,
        new_message_edge: range_add.edge
      )
```

The solution to this has been to grab the correct node out of the selected nodes:

```RUBY
module GraphQL
  module Pro
    # @api private
    class OrderedRelation
      alias_method :original_build_cursor, :build_cursor

      def build_cursor(proposed_node)
        node = nodes.find {|i| i == proposed_node }
        original_build_cursor(node)
      end
    end
  end
end
```

**Comment by rmosolgo** [comment]
Thanks for sharing that work-around! I'll take a look at improving the built-in code.

**Comment by wakeless** [comment]
How is this going? I'm running into some subtle issues around the monkey patch.

**Comment by rmosolgo** [comment]
Hey, sorry for the delay here! We had a new baby last week but I'm hoping to catch up on this soon 😅

**Comment by wakeless** [comment]
No worries! Congratulations on the new family member.

**Comment by wakeless** [comment]
Hi @rmosolgo Any news on this issue? We've just realised that this workaround is causing us to load the whole set and this can be really bad (we've got some big tables).

Any advice would be appreciated :)

**Comment by rmosolgo** [comment]
Hey @wakeless , thanks for your patience here and sorry for the slow help 😩 . 

I took a look to find a better performing work-around, at least to get started. How about trying this instead of `GraphQL::Relay::RangeAdd`? 

```diff 
-       range_add = GraphQL::Relay::RangeAdd.new(
-         parent: chat,
-         collection: chat.messages
-         item: message,
-         context: context
-       )
+      # Make a new relation so that the proper SELECTs can be applied to it
+      new_message_relation = chat.messages.where(id: message.id)
+      # Wrap it in a connection which will apply the cursor generation SELECTs 
+      example_connection = GraphQL::Pro::RelationConnection.new(new_message_relation, {}, parent: chat, context: context)
+      # Then make a new edge, using a refetched node
+      new_card_edge = GraphQL::Relay::Edge.new(example_connection.nodes.first, example_connection)
```

The downside here is that it will run _one more_ SQL query: it will refetch the node with `SELECT ... as cursor_0, ... WHERE id={new-id}` (with the new `SELECT` clauses added). Do you think that'll work for you for now? I'll plan to make a better API as part of the new pagination system if so.

**Comment by rmosolgo** [comment]
The approach described above will need work, because `GraphQL::Relay` will be deprecated in 1.12.0.

**Comment by rmosolgo** [comment]
(I'm going to leave Relay::RangeAdd in place, but other parts of GraphQL::Relay were deprecated -- the ones that had _replacements_!)

**Comment by rmosolgo** [comment]
With GraphQL-Ruby 1.12.5 and GraphQL-Pro 1.17.6, `RangeAdd` will work properly out-of-the-box with stable relation connections 🎉  See #3341 for implementation.
