### ISSUE TITLE
Pls explain: Duplicate type definition

### ISSUE THREAD

**Issue by LemonAndroid** [rmosolgo/graphql-ruby#2187]
Hey,

This error was raised in our app, I don't understand it.

Could you explain, what issues this is supposed to be solving?

**Comment by rmosolgo** [comment]
It's possible to make two types with the same name, for example: 

```ruby
class Thing < GraphQL::Schema::Object 
  # ... 
end 

class Thing < GraphQL::Schema::Union 
  # ... 
end 
```

And that would be a naming conflict! So, we make sure that types with the _same name_ are also the _same ruby object_. However, sometimes this doesn't play nice with Rails autoloading, see #935

**Comment by adaam2** [comment]
I've noticed that this also happens if you have an input type named similarly to a mutation (e.g. mutation is called `CreateBlah` and the input type is called `CreateBlahInputType`). Thought it may be useful mentioning here for future travellers.
