### ISSUE TITLE
How can I use an alternate LazyResolve implementation in a field

### ISSUE THREAD

**Issue by blevine** [rmosolgo/graphql-ruby#2188]
Fields default to using DefaultLazyResolve. How can I use an alternate lazy resolve proc for a specific field.  It looks like this is overridable (`accepts_definitions ... :lazy_resolve`), but I'm not sure how to use that.

**Comment by rmosolgo** [comment]
It's ... not really made to be customizeable. Could you share more about what you're trying to accomplish?

**Comment by blevine** [comment]
Without going into too much detail, I wanted the value method of the lazy resolver to have access to the context.  If you look at DefaultLazyResolve#call:

```
def self.call(obj, args, ctx)
        method_name = ctx.schema.lazy_method_name(obj)
        next_obj = obj.public_send(method_name)
        ...
```
I wanted to pass ctx like so:_`next_obj = obj = obj.public_send(method_name, ctx)`

So I was just going to create my own FooLazyResolve module to do that.

**Comment by rmosolgo** [comment]
I hope you found something that worked! I don't plan to support this API so I'm going to close the issue.
