### ISSUE TITLE
Relay subscriptions require an initial result

### ISSUE THREAD

**Issue by wakeless** [rmosolgo/graphql-ruby#2191]
I'm using Relay v3 and I'm having some issues with the initial setup of an actioncable subscription. It seems that relay is expecting a result.

On setup I get:
```
chatWasUpdated.js:36 RelayNetwork: No data returned for operation `chatWasUpdatedSubscription`, got error(s):
(No errors)
```

This leaves the subscription unsubscribed.

In my channel I'm implementing it as such:

```
GraphQL::Execution::Interpreter
    result = Admin::Graph::Schema.execute({
      query: query,
      context: context,
      variables: variables,
      operation_name: operation_name
    })

    pp result #always data is nil
    payload = {
      result: result.subscription? ? { data: nil } : result.to_h,
      more: result.subscription?
    }
```

However, if I override the payload like below, the subscription successfully starts and receives my notifications to the subscription no problems.

```
    #this works
    payload = {
      result: result.subscription? ? { data: {chatWasUpdated: { chat: { id: "ASdFAS", subject: "Awerert"}}}} : result.to_h,
      more: result.subscription?
    }
```

Is this intended behaviour, a bug or am I simply missing something in the setup of this functionality?

**Comment by wakeless** [comment]
I resolved this by moving to the new interpreter: https://github.com/rmosolgo/graphql-ruby/blob/master/guides/queries/interpreter.md

I'm not too sure if it is supposed to be possible without that, but this appears to have resolved my issues.

**Comment by rmosolgo** [comment]
:+1: Glad you found something that works! I think I shold update the docs to stop recommending `data: nil`.
