### ISSUE TITLE
Custom directives have no effect

### ISSUE THREAD

**Issue by tall-dan** [rmosolgo/graphql-ruby#2194]
**Problem**
Adding a custom directive makes it available on the SDL, but the directive has no effect on output

**Versions**
* graphql version: `1.9.3`
* graphql-batch version: `0.4.0`
* ruby version: `2.3.6`
* rails version: `4.2.10`

**Schema**
```ruby
class MySchema < GraphQL::Schema
  use GraphQL::Batch
  query Types::QueryType
  mutation Types::MutationType

  directive(GraphQL::Schema::Directive::Transform)
end

module Types
   class QueryType < GraphQL::Schema::Object
     graphql_name 'Query'
     field :events, Types::EventType.connection_type, null: false, description: 'The events for a client',
                                                      resolver: Resolvers::EventsResolver
   end
end

module Types
  class EventType < GraphQL::Schema::Object
    field :id, GraphQL::Types::UUID, null: false
    field :slug, String, null: true, description: 'An external identifier for the event'
    field :location, String, null: true, description: 'Location of the event'
  end
end
```

The directive, `GraphQL::Schema::Directive::Transform` is what comes included in the gem, seen [here](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/directive/transform.rb).  However, the `resolve` function implemented by that class doesn't seem to be getting called - I've put a `binding.pry` within, and it never gets hit. When using the `transform` directive, my data is not transformed: 

![image](https://user-images.githubusercontent.com/1512489/54554530-a2f43400-4982-11e9-9702-224c938a7ec1.png)

I've been digging through source code, and I've only been able to find one place that implements directives: [`GraphQL::Execution::DirectiveChecks`](https://github.com/rmosolgo/graphql-ruby/blob/v1.9.3/lib/graphql/execution/directive_checks.rb). This only deals with inclusion / exclusion. 

Am I missing something here, or should the case statement in that module be doing more?

**Comment by swalkinshaw** [comment]
Are you using the new interpreter? I think that's a requirement.

ie: `use GraphQL::Execution::Interpreter` on your schema

**Comment by tall-dan** [comment]
Oh good catch, thank you!
