### ISSUE TITLE
How to limit fields queried in the database table?

### ISSUE THREAD

**Issue by evgenyfadeev** [rmosolgo/graphql-ruby#2196]
Hi, we have a postgres table with ~130 columns and noticed in the query stats that  graphql always requests `select * from sometable ...` regardless of what fields are needed.

It seems that this is impacting the performance of the queries significantly - is there a way to make the graphql do something like `select field1, field2, .. from sometable ..` instead? Or perhaps this is something that might be implemented in `graphql-query` in the future if it is not yet done?

Thank you!

**Comment by rmosolgo** [comment]
Hi, you can either use [`Lookahead`](https://graphql-ruby.org/queries/lookahead.html) to do this ahead-of-time, based on the query AST, or you could use [graphql-batch](https://github.com/Shopify/graphql-batch) to do it at runtime (by accumulating a "query object" based on the fields that are actually called, then running that query object). 



Hope that helps! Feel free to share what you find.

**Comment by fameoflight** [comment]
@evgenyfadeev did you ever ended up finding a good soln?

**Comment by schmurfy** [comment]
@rmosolgo Hi, could you give more pointers as to how we could do this ?

I looked at lookahead but this is a fairly obscure feature to work with, I also tried with `graphql-batch` but failed to understand how I could do that :/
