### ISSUE TITLE
Field not properly resolved when using restricted keyword

### ISSUE THREAD

**Issue by awinograd** [rmosolgo/graphql-ruby#2199]
Hi,

I have a mutation with a "class" field that looks something like the following:

```rb
class MyMutation < GraphQL::Schema::Mutation
    graphql_name("SaveClass")

    arguments: attributes, Types::ClassAttributes, required: true

    field "class", Types::ClassType, null: false
    field "errors", [Types::UserError], null :false

    def resolve(args)
        @class = Class.where(args).first
        {
             "class" => @class,
             "errors" => [],
        }
    end
end
```

However, when I try to perform the mutation and request the "class" field in the response, my resolver doesn't get the passed `@class` object as expected. Instead it gets passed SaveClassPayload's class. I believe the culprit is the following line:

https://github.com/rmosolgo/graphql-ruby/blob/d31d378c56d3c4a652ef42a2b0ae0d2d4736622d/lib/graphql/schema/field.rb#L599

Are we not supposed to be able to use reserved keywords like this as field names? Please let me know if there's a suggested workaround or if there is in face a bug. Happy to provide more information if helpful.

**Comment by awinograd** [comment]
This may be a duplicate of https://github.com/rmosolgo/graphql-ruby/issues/1648

**Comment by rmosolgo** [comment]
Hi, yes I'd like to fix this so I'll keep it open to track work on it!
