### ISSUE TITLE
Support non-null input objects

### ISSUE THREAD

**Issue by devknoll** [rmosolgo/graphql-ruby#22]
Relay mutations require a mutation take a single argument named `input` with a non-null INPUT_OBJECT (https://facebook.github.io/relay/graphql/mutations.htm#sec-Mutation-inputs)

graphql-ruby currently raises an exception on non-null input objects, complaining that it can't find `input_fields` on the type, presumably because it hasn't unboxed it first :smile:

**Comment by rmosolgo** [comment]
Oh snap! Thanks 

Added a test and fixed here: https://github.com/rmosolgo/graphql-ruby/commit/808164ae6a1e4918d92f80d76d25da04c4cce7cc

Just pushed `0.6.0`, wanna give it a try?

**Comment by devknoll** [comment]
Seems great, thanks!
