### ISSUE TITLE
Reusing query response data in a nested query

### ISSUE THREAD

**Issue by nelobaba** [rmosolgo/graphql-ruby#2200]
@rmosolgo Just curious, how can I re use a result of a query to make another query within graphql e.g

mutation M {
   createUser(firstName: 'bob') { id }
   createPreferences(user_id: #createUser.id, preferences: "doesn't appreciate purple") {
       success
    }
}

how can I reuse the id from createUser in createPreferences

**Comment by rmosolgo** [comment]
Hi, there's no built-in way to do it, but there's been talk of a directive called `@export` which would support that. Sangria has experimental support for it: https://sangria-graphql.org/learn/#batch-executor

So, you could implement a custom directive (https://graphql-ruby.org/type_definitions/directives.html) to support `@export`. Without `@export`, you could: 

- Send two separate requests to accomplish it 
- Accomplish both changes with a single mutation (eg, adding a `createUserWithPreferences` mutation, or accepting `preferences:` in the `createUser` mutation).
