### ISSUE TITLE
Expected behavior when raising GraphQL::Execution error

### ISSUE THREAD

**Issue by blevine** [rmosolgo/graphql-ruby#2202]
Running GraphQL version 1.8.5.

I'm implementing a "federated search" API in which multiple back-end search services can be searched from a single GraphQL query something like:

```
query {
  multiSearch(query: "brian") {
    service1 {
      results
    }
    service2 {
        results
    }
  }
}
```

The queries against the back-end search services are run concurrently and so I have the following in my schema:

`lazy_resolve(Concurrent::Future, :value!)`

and the resolver method for each service returns a `Concurrent::Future`. The resolver method for each service raises GraphQL::ExecutionError if there's an error while executing the search against the corresponding search service.

If some of the search services fail and some succeed, I see:
1. the appropriate error in the errors array based on the raised ExecutionError
2. `multiSearch` field is null

However, I was hoping to see:
1. the appropriate error in the errors array based on the raised ExecutionError
2. null in the `result` field for the service(s) that failed
3. data in the `result` field for service(s) that succeed

Just to make this a bit more confusing, the call to each search service is made in the resolver for the `searchn` field, not the resolver for the `result` field. The resolver for each `searchn` field returns a CanonicalSearchResultsType (within the Future)that contains the `result` field.  So I guess I should really expect the `searchn` fields to be null for any failed search.  

That code looks something like this:

```
Future::execute do
  begin
    native_results = service.search(query_string: query_string, from: args[:from], limit: args[:limit], opts: opts)
    canonical_results = service.to_canonical_form(native_results, opts) unless args[:native_form]
    CanonicalSearchResults.new(canonical_results, native_results, args[:limit], args[:from])
  rescue StandardError => e
    Rails.logger.error(e)
    Rails.logger.error(e.backtrace.join("\n"))
    raise ::GraphQL::ExecutionError.new("Search execution error (#{service_name}): #{e.message}", extensions: {original_error: e})
  end
end
```

Regardless, the important point here is that I'd like to see the results for any searches that succeeded.

Is there a way to achieve this error behavior?

**Comment by blevine** [comment]
So what I finally did was add the `ExecutionError` to the errors array using `context.add_error()` rather than raising the `ExecutionError`.  The resolver then returns an empty `CanonicalSearchResults` like so:

```
context.add_error(::GraphQL::ExecutionError.new("Search execution error (#{service_name}): #{e.message}", extensions: {original_error: e}))
Suede::GraphQL::Helper::CanonicalSearchResults.new({}, {}, args[:limit], args[:from])
```

I suspect that I shouldn't have had to do this and that there's something obvious I'm missing in how I've defined my schema and/or how I've coded the resolver.

**Comment by rmosolgo** [comment]
Hi, could you share the configuration of the `service1` and `service2` fields? If they have `null: false`, then GraphQL will "propagate" the null to the next-_highest_ field with `null: true`. This is so that the response complies with the published type system. 

If it's not a null propagation error, then it's probably a missing `rescue` somewhere in GraphQL-Ruby's source code. You could help debug this by providing the `caller` right before your `raise ::GraphQL::ExecutionError`. That would show where in GraphQL-Ruby we aren't catching the error. Let me know what you find!

**Comment by blevine** [comment]
I just _knew_ it had to be something obvious! ;-). Yes, the `service` fields were not nullable and the `multiSearch` field _was_ nullable.  This is exactly the opposite of what I intended.  Making the service<n> fields nullable did the trick.  Thanks!
