### ISSUE TITLE
relay documentation

### ISSUE THREAD

**Issue by fdutey** [rmosolgo/graphql-ruby#2204]
Hi, would it be possible to have documentation for relay implementation please? Up to date documentation.

The one in the guides is completely out of date, it doesn't match the code in the gem at all. Reading the code is helping a bit but not that much.

Thanks

**Comment by rmosolgo** [comment]
Hi! I'm happy to investigate how the docs can be improved. Could you share some snippets or screenshots about what's not working for you? Also, if you think they could be improved feel free to use the "edit" links on the pages to suggest changes.

**Comment by fdutey** [comment]
Well actually I figured out most of the problems. Mostly coming from old documentation about input field in mutations that got me extremely confused. The new version is terrific about that.

Yet, I'm struggling with errors.
The doccumentation suggests to use errors as data (https://graphql-ruby.org/mutations/mutation_errors) which is, to me, the best way to go. 
Therefore, the "full_error_message" is a real problem if you go with translations.

I think using the details api is much better

```json
{
  "errors": {
    "username": [{
      "error": "already_taken"
    }]
  }
}
```

But some validations (like length, numericality ...) come with "random" values (min, max ...) and I don't think it's very important to go strong typing here.

Is there a way to "bypass" the strong typing and just return an arbitrary set of data?

**Comment by robbie-mcfarlane** [comment]
Hey guys, is there any way to create Relay Modern Mutations using the standard ruby class syntax without using define, blocks and the old method names? It seems like everything else has been updated except mutations for relay modern, is that correct or am I missing something? Cheers

**Comment by rmosolgo** [comment]
@robbie-mcfarlane  try https://graphql-ruby.org/api-doc/1.9.7/GraphQL/Schema/RelayClassicMutation

**Comment by rmosolgo** [comment]
> Is there a way to "bypass" the strong typing and just return an arbitrary set of data?

No, except for using JSON https://graphql-ruby.org/api-doc/1.9.7/GraphQL/Types/JSON.html

**Comment by fdutey** [comment]
Ok, I used String with serialized JSON inside but I was not satisfied with the result. I will try JSON instead. Thanks :)
