### ISSUE TITLE
Best Practice for implementing a search/filtering API

### ISSUE THREAD

**Issue by udl** [rmosolgo/graphql-ruby#2206]
Hi there,

thank you for the good work in bringing GraphQL to the ruby world!
I was wondering how you would approach a `query` like this:

```graphql
  {
    blogPostQuery(where: {
      _AND: {
        title: {_contains: "interesting term"},
        description: {_contains: "awesome"}
      }
    }) {
      blogposts {
        id
        title
        description
      }
    }
  }
```

Do I have to create `field`s for all possible values? Or do you know an easier solution?

**Comment by udl** [comment]
Also: `argument :_AND, String, required: false` generates `_and` in the schema. Is there a way to keep it upper cased?

**Comment by dreampulse** [comment]
> Do I have to create fields for all possible values? Or do you know an easier solution?

Yes, I think you need to do that.. The Graphql-Schema has to contain all available field-names.
I think this is a good practice in order to have a clear interface between the graphql-server and its consumer

**Comment by duyleekun** [comment]
Our app used JSON scalar type for the `where` clause. Inspired by ransack

**Comment by rmosolgo** [comment]
Sorry for the slow response here! 

GraphQL-Ruby doesn't prescribe any kind of filtering, you should implement the system you want. 

Use `camelize: false` to keep your original argument names intact. I bet the camelizer is out of control on that! 

Please let me know if you have any trouble with that.
