### ISSUE TITLE
Wrong coercion on String literal argument

### ISSUE THREAD

**Issue by Batou99** [rmosolgo/graphql-ruby#2207]
I have a query like this:

```
query ticketTransaction($id: TicketTransactionID!) {
  ticketTransaction(id: $id) {
    tickets(first: 20, after: nil) {
      totalCount
    }
  }
}
```
It raises an error on `invalid cursor` after resolving the call.
I've been tracing the GraphQL code for this and the issue is that the `after` cursor (a String)
gets coerced as `"nil"` instead of `nil` because it's a string literal.

This is not really an issue with cursors but with String coercion.
Is there any reason for `nil` string to be coerced as `"nil"` instead of just `nil`?

**Comment by vitorbortolotti** [comment]
Null values in GraphQL are represented as the keyword `null`, not `nil`. 

However, if you already knew that and your question is *why* it doesn't work with `nil`, my guess would be to keep the syntax consistent with [GraphQL's specification](https://graphql.github.io/graphql-spec/June2018/#sec-Null-Value)

**Comment by Batou99** [comment]
@vitorbortolotti I foolishly thought that nil would be valid to pass as a `null` literal, but I see now why that would be not consistent with GraphQL spec.
Thanks for the explanation!
