### ISSUE TITLE
Deprecation of GraphQL::Function

### ISSUE THREAD

**Issue by atainton** [rmosolgo/graphql-ruby#2213]
I am interested to know why GraphQL::Function was deprecated. I have found the structure of the GraphQL::Function a lot better than the resolver classes. If I need to use resolvers I am keen to understand why it is preferred

**Comment by rmosolgo** [comment]
Hi, here are a few problems: 

- Function was easy to misuse: https://github.com/rmosolgo/graphql-ruby/pull/1472#issue-185814297

- Function's API was different than other APIs: https://github.com/rmosolgo/graphql-ruby/issues/980

So, `Schema::Resolver` has an API that matches `Mutation` (and now `Subscription`) and has a shorter, less-error prone lifecycle. Hope that helps!
