### ISSUE TITLE
proxying a Connection to upstream API

### ISSUE THREAD

**Issue by cainlevy** [rmosolgo/graphql-ruby#2218]
I have an upstream API that paginates with cursors. I'm hiding it behind GraphQL so that clients can request additional information to decorate the result set.

The built-in `ArrayConnection` handler didn't fit my needs: my resolver needs access to the connection arguments, and my result object is technically an Array but really only a slice.

Eventually I worked out a custom connection handler that is a small modification of the `ArrayConnection` and works for anything call-able returned from the resolver. Would this be a useful contribution to graphql-ruby?

```ruby
class ProxyConnection < GraphQL::Relay::ArrayConnection
  def cursor_from_node(item)
    encode item.id.to_s
  end

  def sliced_nodes
    @sliced_nodes ||= nodes.call(
      first: first,
      last: last,
      after: after ? index_from_cursor(after) : nil,
      before: before ? index_from_cursor(before) : nil,
    )
  end
end

GraphQL::Relay::BaseConnection.register_connection_implementation(Method, ProxyConnection)
GraphQL::Relay::BaseConnection.register_connection_implementation(Proc, ProxyConnection)
```

I'd be happy to work it into a pull request.

**Comment by rmosolgo** [comment]
Hey, thanks for sharing your solution here! Custom connections can be awfully tricky. 

It looks like this implementation assumes that the remote list is ordered by `id`, is that right? (I see that `id` is used as the cursor.)

My hunch is to keep this issue in mind and direct folks to it if they need similar functionality. (We have something like this in GitHub, but it _also_ proxies the remote cursors into the local schema.) If more folks come looking for it, I'm open to adding to GraphQL-Ruby. I'm in the works of redoing pagination (#2143), so we could build it on top of that. (The redo is supposed to make the system simpler, although your solution here is 👌 .)

**Comment by cainlevy** [comment]
Oh, good spot! I did wrap my results in a struct with an `id` property. That's not quite as generic as I thought.

> My hunch is to keep this issue in mind and direct folks to it if they need similar functionality.

Whatever you think is best!

> I'm in the works of redoing pagination (#2143), so we could build it on top of that.

Sounds nice. 😅

**Comment by rmosolgo** [comment]
I don't think there's anything else do to here for now, so I'll close this out.
