### ISSUE TITLE
`graphql_name` on `...Relay::BaseEdge` causes duplicates

### ISSUE THREAD

**Issue by cheerfulstoic** [rmosolgo/graphql-ruby#2221]
I was creating a custom edge with `GraphQL::Types::Relay::BaseEdge` and I specified `node_type(UserType)` and got the error `Duplicate type definition found for name 'UserEdge'`

I think maybe this line isn't doing the right thing: https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/types/relay/base_edge.rb#L36

Maybe the `node_type`'s `graphql_name` could be used sometimes, but I would think that the class name of the edge class would be better.  Would that just be `self.name` in this case?

**Comment by cheerfulstoic** [comment]
For not in order to fix it I call `graphql_name('UserRecommendationEdge')` (*after* the call to `node_type` because that will just overwrite the `graphql_name`).  Kinda hacky ;(

**Comment by rmosolgo** [comment]
Ah, yes, i remember running into this issue too, and it looks like i worked around it in my own base edge class: 

```ruby 
           graphql_name("#{wrapped_type_class.graphql_name}Edge") if self.name.nil?
```

If you want to take a crack at improving that, feel free! Or I can keep this issue open to track the bug.
