### ISSUE TITLE
argument prepare only reference by symbol get

### ISSUE THREAD

**Issue by tjbarker** [rmosolgo/graphql-ruby#2222]
_Preface_
I don't know if this is the desired behaviour and I missed the doc on it, if I've done some incorrect implementation, or if this behaviour is undesired.

The actual use case in my app is quite complex but I checked out a branch and updated a spec in the gem to fail to show an example of what I'm seeing.
I've attached a copy of the changed spec below, and the failure message it throws.

_The Issue_
The discrepancy is when an input object has a prepare function that changes the value, the new value is only applied to the corresponding method when referenced by the symbol, but the new value is not available when referenced by the string.

_Why do I think this is an issue_
This is confusing as I would expect the result of the prepare function to be accessible when referenced by any method that returns a result. If string referencing is not desired, I would expect it to not return any result.

_Ideas_
Some possible outcomes that might be considered:
- referencing by string returns prepare function result
- referencing by string logs a warning (that can be turned off if desired)
- referencing by string returns `nil`

example pseudo code
```
class InputObj < GraphQL::Schema::InputObject
  argument :a, Integer, required: true, prepare: :prep
  
  def prep(val)
    val * 2
  end
end

class Query < GraphQL::Schema::Object
  field :inputs, String, null: false do
    argument :input, InputObj, required: true
  end

  def inputs(input:)
    # here input[:a]  => val * 2
    # and  input['a'] => val
    input
  end
end
```

here is the test I've changed to fail, my assumption is that a test like this would pass if this functionality is desired. (spec/graphql/schema/input_object_spec.rb:108)
```
   58   describe "prepare: / as:" do
   59     module InputObjectPrepareTest
   60       class InputObj < GraphQL::Schema::InputObject
   61         argument :a, Integer, required: true
   62         argument :b, Integer, required: true, as: :b2
   63         argument :c, Integer, required: true, prepare: :prep
   64         argument :d, Integer, required: true, prepare: :prep, as: :d2
   65         argument :e, Integer, required: true, prepare: ->(val, ctx) { val * ctx[:multiply_by] * 2 }, as: :e2
   66         argument :danger, Integer, required: false, prepare: ->(val, ctx) { raise GraphQL::ExecutionError.new('boom!') }
   67
   68         def prep(val)
   69           val * context[:multiply_by]
   70         end
   71       end
   72
   73       class Query < GraphQL::Schema::Object
   74         field :inputs, String, null: false do
   75           argument :input, InputObj, required: true
   76         end
   77
   78         def inputs(input:)
~  79           string_input = %w[a b2 c d2 e2].each_with_object({}) { |s, i| i[s] = input[s]  }
+  80           sym_input = %i[a b2 c d2 e2].each_with_object({}) { |s, i| i[s] = input[s]  }
+  81           { string_input: string_input, sym_input: sym_input }
   82         end
   83       end
   84
   85       class Schema < GraphQL::Schema
   86         query(Query)
   87         if TESTING_INTERPRETER
   88           use GraphQL::Execution::Interpreter
   89         end
   90       end
   91     end
   92
~  93     it "calls prepare on the input object" do
   94       query_str = <<-GRAPHQL
~  95         query Base_Query($input: InputObj!) {
+  96           inputs(input: $input)
+  97         }
   98       GRAPHQL
   99
~ 100       inputs = { a: 1, b: 2, c: 3, d: 4, e: 5 }
~ 101       variables = { input: inputs }
~ 102       res = InputObjectPrepareTest::Schema.execute(query_str, variables: variables, context: { multiply_by: 3 })['data']['inputs']
+ 103       expected_inspected_hash = {
+ 104         string_input: {"a"=>1, "b2"=>2, "c"=>9, "d2"=>12, "e2"=>30},
+ 105         sym_input: {:a=>1, :b2=>2, :c=>9, :d2=>12, :e2=>30}
+ 106       }.inspect
+ 107
+ 108       assert_equal res, expected_inspected_hash
  109     end
```

this fails with the following error
```
Failure:
GraphQL::Schema::InputObject::prepare: / as:#test_0001_calls prepare on the input object [###/graphql-ruby/spec/graphql/schema/input_object_spec.rb:108]
Minitest::Assertion: --- expected
+++ actual
@@ -1 +1 @@
-"{:string_input=>{\"a\"=>1, \"b2\"=>2, \"c\"=>3, \"d2\"=>4, \"e2\"=>5}, :sym_input=>{:a=>1, :b2=>2, :c=>9, :d2=>12, :e2=>30}}"
+"{:string_input=>{\"a\"=>1, \"b2\"=>2, \"c\"=>9, \"d2\"=>12, \"e2\"=>30}, :sym_input=>{:a=>1, :b2=>2, :c=>9, :d2=>12, :e2=>30}}"
```
As you can see, the test is expecting the prepare function to run on both hashes, but the `c`,`d2` and `e2` values have not been multiplied in the `string_hash`

FYI
merge information at the top of my git log:
```
Merge: 6690245bd 2bd26fb97
Author: Robert Mosolgo <rmosolgo@github.com>
Date:   Thu Apr 4 11:40:09 2019 -0400
```

**Comment by rmosolgo** [comment]
Hi, thanks for the detailed report here! Sorry about the confusion. It's definitely a bug. 

In the long run, I'd like to deprecate access-by-string (just to simplify the library), but not yet. If you're interested in patching this, though, I'd be happy to review a PR!

**Comment by rmosolgo** [comment]
Sorry, I don't really have the bandwidth to pursue a fix here 😖  In the long run, I'm moving towards symbols-only-everywhere, so using symbols will be future-compatible anyways!
