### ISSUE TITLE
Incorrect authorization documentation for mutations

### ISSUE THREAD

**Issue by ro31337** [rmosolgo/graphql-ruby#2231]
Documentation is incorrect. Moreover, documentation about **authorization** is incorrect.

Here is the [link](https://github.com/rmosolgo/graphql-ruby/blob/master/guides/authorization/authorization.md) that says:

> Type and mutation classes have .authorized?(value, context) class methods

"mutation classes have... class methods"?

Here is example from the [website](https://graphql-ruby.org/mutations/mutation_authorization.html#can-this-user-perform-this-action) about mutations, and there is no class methods:

```ruby
def authorized?(employee:)
  context[:current_user].manager_of?(employee)
end
```

It's confusing. What if I follow the first link and define `authorized?` class method? (`self.authorized?`) for mutation. Will this gets ever called for mutation or it will be skipped?

I don't know if it introduces a security flaw, but it should be fixed.

**Comment by ro31337** [comment]
@rmosolgo please take a look if you have time, because it's security-related.

**Comment by rmosolgo** [comment]
Oops, yes, I think that part of the docs is wrong, but the examples are right!

**Comment by ro31337** [comment]
@rmosolgo which part is wrong? Or it would be nice if you could just update docs if it doesn't take too long. Thanks!

**Comment by daemonsy** [comment]
- mutation calls the `#ready?(**args)` method **Note:** But the example doesn't use it, a little confusing). Second `#ready?` call doesn't have args? **Solution:** Improve ready example.  
- ObjectType does have a  `self.authorized?(object, context)` method. 
- MutationType does NOT have a class method `self.authorized?` 
- MutationType has an instance `authorized?` method that passes in args. 

If everything looks correct, the documentation that requires change is 
> mutation classes have .authorized?(value, context) class methods

That is not true. All the examples are correct. But I'll suggest clarifying the `#ready?` example. Also, after reading the docs, I'm still not so sure what exactly it is that it does

**Comment by daemonsy** [comment]
I piggybacked the change on my PR
