### ISSUE TITLE
[1.9] Using GraphQL::Execution::Interpreter is there a replacement for the extras: :parent functionality?

### ISSUE THREAD

**Issue by blevine** [rmosolgo/graphql-ruby#2232]
I've been using `extras[:parent] `to get the parent field for a field.  It appears that this is no longer supported when using `GraphQL::Execution::Interpreter.`  Is there a way to get the parent node when using `GraphQL::Execution::Interpreter`?

**Comment by swalkinshaw** [comment]
Maybe `extras[:owner]`? Every field has its owner type set at definition time.

**Comment by blevine** [comment]
I don't think so @swalkinshaw. `:owner `appears to be the parent type as opposed the parent AST node

**Comment by swalkinshaw** [comment]
Yeah that's correct. It's not a direct replacement but depending on what you used from `parent` it's an alternative.

**Comment by blevine** [comment]
Right.  So maybe I should describe what I'm trying to accomplish in a bit more detail.  I want to get the arguments that were passed to the parent field of a certain field.

**Comment by rmosolgo** [comment]
No, there's not a way to do that. IIRC `:parent` returned the previous `context` object, right? There are no field-level context objects anymore, so there's nothing to return. 

I can't really think of a way to reference _previous_ arguments with the interpreter. I can't think of a data structure which retains that info at all 😬 . Is it the kind of think you could add to the parent's return value, so that the child field could get it from `@object`?

**Comment by blevine** [comment]
I think this "sort of" works assuming I know something about the structure of the query:

`parent = args[:irep_node].ast_node.children.select {|n| n.name == 'multiSearch'}[0]`

The goal is for me to find the parent node (which should be the `multiSearch` field, not the context) from one of the immediate child fields of the `multiSearch` field

**Comment by etherbob** [comment]
BTW, docs still strongly suggest that extras[:parent] is available. I'd submit a pull request, but I'm still lost on how this all works myself.

**Comment by etherbob** [comment]
And it is still there if I set everything up right sheesh... my bad.

**Comment by rmosolgo** [comment]
Sorry again for the confusion, I've updated the list of extras in f7a1388bf
