### ISSUE TITLE
Description of mutation

### ISSUE THREAD

**Issue by b8in** [rmosolgo/graphql-ruby#224]
Hello guys!

I would be grateful if you could share your thoughts and help on the following thing considering GraphQL and GraphiQL Editor.

I use GraphQL in my application. I provide descriptions for my queries/mutations and use GraphiQL Editor for reading the outcoming documentation.
Currently, mutation description is not displayed in the editor:
http://joxi.ru/nAyqdDWcXJ648A

Here's my code:

```ruby
#mutation_type.rb
MutationType = GraphQL::ObjectType.define do
  name "Mutation"
  description "The mutation root for this schema"
  
  field :createBlogPost, field: Widgets::Blog::CreateBlogPostMutation.field
end

#widgets\blog\create_blog_post_mutation.rb
Widgets::Blog::CreateBlogPostMutation = GraphQL::Relay::Mutation.define do

  # Used to name derived types:
  name "createBlogPost"
  description I18n.t('graphql.mutations.createBlogPost.description')

  # ...
end
```

Here are the results from rails console:

```ruby
>> Widgets::Blog::CreateBlogPostMutation.field.description 
nil

>> Widgets::Blog::CreateBlogPostMutation.description 
"*Create new post in blog widget*"
```

Maybe, description should be set somehow differently. 
If yes, then please, advise on how could I do it correctly.

At this point, I found a way, but it requires changes in gem source, particularly adding parameter `(description: self.description)` into method call `GraphQL::Field.define do` in here:

```ruby
#lib/graphql/relay/mutation.rb

  def field
    @field ||= begin
      # ...
      GraphQL::Field.define(description: self.description) do
      # ...
      end
    end
  end
```

Here's the result after editing the gem: http://joxi.ru/BA0pKJBFBOkRBA

If you like the way I suggested, I can leave a PR.

Thanks and looking forward to your thoughts on this!
Alex

**Comment by rmosolgo** [comment]
Huh, it looks like that description is not used at all, oops! Your fix sounds good to me!

**Comment by b8in** [comment]
Glad to hear that! I'm happy to be of help :)
Then, I'll leave a PR today or tomorrow already.

**Comment by b8in** [comment]
Thanks, updated the gem (v 0.18.7) on my side, everything's ok.
