### ISSUE TITLE
[1.9] with GraphQL::Execution::Interpreter.  Any way to customize PageInfo?

### ISSUE THREAD

**Issue by blevine** [rmosolgo/graphql-ruby#2241]
Previously, I had added a count field to PageInfo like so:

```
count_field = ::GraphQL::Field.define do
  name 'count'
  type !types.Int
  description 'Total count of edges in this connection.'
  resolve ->(obj, args, ctx) {
    obj.object.nodes.count
  }
end

# Add a 'count' field to PageInfo for connections.  This is the total number of
# edges in the connection (nodes in the collection)
::GraphQL::Relay::PageInfo.fields['count'] = count_field
```
Obviously, this is no longer possible.  Any way to achieve the same thing in 1.9 with the new interpreter?

**Comment by blevine** [comment]
Ok.  I may have figured this out.  Tell me if there's a better way:

Define my own PageInfo:
```
class MyPageInfo < GraphQL::Types::Relay::PageInfo
  field :count, Int, null: false
end
```

Define my own BaseConnection:
```
class MyBaseConnection < GraphQL::Types::Relay::BaseConnection
  field :page_info, MyPageInfo, null: false, description: "My Page Info!!!."
end
```

Use my BaseConnection class for all interfaces and objects.  In my BaseObject and BaseInterface classes add:
`connection_type_class(MyBaseConnection)
`

**Comment by rmosolgo** [comment]
Yes, that's the way to do it! Thanks for sharing your solution.
