### ISSUE TITLE
Using `authorized?` on a union?

### ISSUE THREAD

**Issue by cheerfulstoic** [rmosolgo/graphql-ruby#2245]
I'm wanting to implement a `def self.authorized?(object, context)` definition (as [seen here](https://graphql-ruby.org/authorization/authorization.html)) in a union but it doesn't seem to be called.  Is there something different about unions that doesn't support this?  Since my union is combining together different scopes I need to be able to make a list, so I can't use the scope-based authorization in the pundit integration.

My base union class is inheriting from `GraphQL::Schema::Union`

**Comment by cheerfulstoic** [comment]
I came in after a weekend's rest and I'm realizing that the `def self.authorized?` belongs on the classes which are part of the union, not on the union itself 🤦‍♂️   That makes much more sense.  Nevermind, and thanks!

**Comment by rmosolgo** [comment]
Glad you found something that works! If you find a use case for implementing `.authorized?` on a union (or interface) please do share the details. I think it could be implemented by calling _before_ resolving the runtime object to an object type: 

https://github.com/rmosolgo/graphql-ruby/blob/4223bde1da68132ad8d259d191d4658b9cdbbe83/lib/graphql/execution/interpreter/runtime.rb#L284
