### ISSUE TITLE
ExecutionError returns a Hash that can have string and symbols keys

### ISSUE THREAD

**Issue by blevine** [rmosolgo/graphql-ruby#2246]
A `GraphQL::ExecutionError` can be created with options and/or extensions which may contain a `Hash` that uses symbolized keys. Calling `to_h` will then return a `Hash` in which some keys are strings and some are symbols. Granted, the choice of using symbols vs strings is up to the caller.  However, I don't believe that the caller should have to know that the implementation of `ExecutionError.to_h` happens to prefer strings.  So either:

`ExecutionError.to_h` should stringify or symbolize all keys and document which one was used. OR
`ExecutionError.to_h` should return a `HashWithIndifferentAccess `

Some additional thoughts:

- I realize this issue is a bit of a nit.
- This is not an issue when the GraphQL query is executed remotely and the result is serialized/deserialized during transmission over the wire.  However, it is an issue when the query is executed locally.
- The string-vs-symbol-keys-in-hashes issue is almost as old as Ruby
- There are probably other graphql-ruby classes that can be converted to Hashes that suffer from the same problem.  I just happened to run into the `ExecutionError` issue while writing a few specs that tested the errors result.

**Comment by rmosolgo** [comment]
:+1: From me to stringify the output keys. The intention is to return a response-ready (JSON-ready) hash, which would be string-keyed. It's not a design choice to return the user's symbols, just an oversight. (Alternatively, I guess we could _check_ the extension keys and raise if any of them are non-String.)
