### ISSUE TITLE
GraphQL::Define::TypeDefiner should probably define a BigInt symbol

### ISSUE THREAD

**Issue by fdr** [rmosolgo/graphql-ruby#2247]
I think this is an omission, given 2b36d8bd44138f99fd0fe04d050ccffa74851312:

https://github.com/rmosolgo/graphql-ruby/blob/523808293a05b25e7a510132a62a4da81e90624a/lib/graphql/define/type_definer.rb#L10-L14

**Comment by rmosolgo** [comment]
That's right, Types::BigInt is only supported for class-based schemas right now. Feel free to open a PR to backport it ... but personally, I recommend making the update to class-based 😉
