### ISSUE TITLE
Directive support for argument definition

### ISSUE THREAD

**Issue by g-gaston** [rmosolgo/graphql-ruby#2250]
It looks like this not supported yet, or at least I can't find how to do it. 

I would like to set constraints without declaring custom scalars (like max for page size) and this looks like a pretty good solution.

Happy to put together a PR, but looking for opinions first and maybe a bit of guidance 😄

**Comment by rmosolgo** [comment]
Hi, that's right that _definition_ directives don't have any support yet. If you're parsing a schema from SDL, you can access the `.ast_node` of each type, field and argument, and get `.ast_node.directives` from there. Here's a small example: 

https://gist.github.com/rmosolgo/c0f77ec8bde255daab4cc8122a8226dc

I think that's the starting point for definition directives, hope that helps!
