### ISSUE TITLE
Query validation with schema visibility rules

### ISSUE THREAD

**Issue by daemonsy** [rmosolgo/graphql-ruby#2251]
Hello, I'm having an issue with using `GraphQL::Schema.validate` filtering out fields by visibility, hence marking queries with errors like "Field x doesn't exist on type User".  

## Background

We have some stored queries. I made a test to make sure that some of these queries are valid as a sanity spec. Roughly

```ruby
queries.each do |graphql_query_as_string|
  MySchema.validate(graphql_query_as_string)
end
```

This is invoking the visibility method in my field class. 

```
class QueryField 
  def visible?(context)
    super && allowed_to_view?(context[:current_user]) # no user, #allowed_to_view? is returning false
  end
end
```

## What I expected 
- The ability to pass in the context to validation if schema visibility hooks are running. In this case, I might solve the visibility issue in specs by introducing some form of test user policy that grants full visibility. 

OR 

- Schema visibility hooks not to run for validation. In that case, I'll consider mentally that this validation is "static", doesn't take account of the visibility limitation feature. 

## What seems to be happening

When `MySchema.valdidate` is called, field `#visible?` hooks are invoked, but there is no way to pass an option to prevent that OR pass in a user context to satisfy visibility. 

Thanks for the help in advance!

**Comment by rmosolgo** [comment]
Ohhh oops! 

I think what we need is a new `context:` keyword in the method here: 

https://github.com/rmosolgo/graphql-ruby/blob/8273c20edc696d5a8e77f6c35d97284ab4c51e85/lib/graphql/schema.rb#L249

Which passes that value along as `Query.new(... context: context)` here: 

https://github.com/rmosolgo/graphql-ruby/blob/8273c20edc696d5a8e77f6c35d97284ab4c51e85/lib/graphql/schema.rb#L255

That would give you the flexibility to run `Schema.validate(...)` with any context you choose. Want to give it a try?

**Comment by daemonsy** [comment]
Yes! I’ll give it a go :)
