### ISSUE TITLE
Specific Timeout for Mutations

### ISSUE THREAD

**Issue by zberkom** [rmosolgo/graphql-ruby#2252]
I'm using the schema middleware with `TimeoutMiddleware.new(max_seconds: 2)`, which works great for all query resolvers, but several mutations take longer than two seconds to resolve their single return field. Is there a way to set a timeout on a specific mutation or all mutations in general?

**Comment by swalkinshaw** [comment]
`TimeoutMiddleware` describes its behaviour and the limitations apply in your case here:

```
# This middleware will stop resolving new fields after `max_seconds` have elapsed.
# Note that this will stop a query _in between_ field resolutions, but
# it doesn't interrupt long-running `resolve` functions.
```

You could do what you want wrapping mutation resolvers in Ruby's native `Timeout`, but it has issues which are detailed here: http://www.mikeperham.com/2015/05/08/timeout-rubys-most-dangerous-api/ and http://blog.headius.com/2008/02/rubys-threadraise-threadkill-timeoutrb.html

**Comment by rmosolgo** [comment]
Thanks for the obligatory link to `Timeout`'s brokenness :P Feel free to use it in your own code but it doesn't sound like something I want to add in GraphQL-Ruby!
