### ISSUE TITLE
Type coercion truncates Float to Int instead of raising an error

### ISSUE THREAD

**Issue by rymwoo** [rmosolgo/graphql-ruby#2259]
Hi guys; I'm pretty new to graphQL; I noticed it automatically coerces my type-float mutation arguments into type-int by truncation without raising any error. That seems to contradict what it says in the specs:

From https://graphql.github.io/graphql-spec/June2018/#sec-Int
> Input Coercion
> When expected as an input type, only integer input values are accepted. All other input values, including strings with numeric content, must raise a query error indicating an incorrect type.

in https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/types/int.rb#L13
>      def self.coerce_input(value, _ctx)
>        value.is_a?(Numeric) ? value.to_i : nil
>      end

should it not be
> value.is_a?(Integer) ? value.to_i : nil

instead?

**Comment by rmosolgo** [comment]
Hi! I think you're right about that. I bet it was just an oversight.

 If you're interested in trying to make a fix, I'd be happy to review a PR!

**Comment by rmosolgo** [comment]
Fixed by #2404
