### ISSUE TITLE
Name of ActionCable channel for graphql subscriptions

### ISSUE THREAD

**Issue by speakingcode** [rmosolgo/graphql-ruby#2260]
One must create an ActionCable Channel when using ActionCable as the provider for graphql subscriptions. In the example in documentation (https://graphql-ruby.org/api-doc/1.9.3/GraphQL/Subscriptions/ActionCableSubscriptions.html), the name used for the actioncable Channel is 'GraphqlChannel`. 

1. Can a channel name other than 'GraphqlChannel' be used?
Via ActionCableLink's options param, one may specify the `channelName` option to define the channel to use, which defaults to `GraphqlChannel`:  
https://github.com/rmosolgo/graphql-ruby/blob/f9e3e7f7b028374f7c4a19ad8f447d0feb45d68e/javascript_client/subscriptions/ActionCableLink.js#L7.  
However `GraphqlChannel` appears to be hardcoded in `ActionCableSubcriber.js` and other files:  
https://github.com/rmosolgo/graphql-ruby/blob/73ac09cb95a0b03b3f00c09921b65534f66d0ae6/javascript_client/subscriptions/ActionCableSubscriber.js#L28  
https://github.com/rmosolgo/graphql-ruby/blob/73ac09cb95a0b03b3f00c09921b65534f66d0ae6/javascript_client/subscriptions/createActionCableHandler.js#L15

2. Either way, should the documentation be updated?  
To clarify if the class name `GraphqlChannel` is required for the graphql subscription channel, or if it is only default convention and how to override it. It may be obvious to others, but not so for me. I'd be happy to submit a PR with a documentation change if someone can answer the questions.

Thanks!

**Comment by rmosolgo** [comment]
Hi! That's a great question. The two files with `channel: "GraphqlChannel"` are the _older_ ones, while the newer one was created with the option to use a different channel name. 

In my opinion, either solution you mentioned is appropriate: either, document that `GraphqlChannel` is a required name, or improve those other files to include a `channelName` option!

**Comment by speakingcode** [comment]
Ok great. I'll do an initial PR documenting the current behavior, and attempt a 2nd that adds the `channelName` option and updates the documentation accordingly. Thanks again
