### ISSUE TITLE
Requiring one of 2 Arguments to be required 

### ISSUE THREAD

**Issue by RobsonKing** [rmosolgo/graphql-ruby#2267]
I have a field that I want to filter in one of two ways.

```
    field :car, Types::CarType, null: false do
      argument :id, ID, required: true
      argument :external_id, ID, required: false
    end
```
Is there anyway to indicate that one of the two values must be required, but not both?

I tried overriding GraphQL::Schema::Argument, but it doesn't seem like 'context' is available where 'required' is used.

**Comment by jturkel** [comment]
This sounds like a good use case input unions in GraphQL to support schema level enforcement of this contract. See https://github.com/graphql/graphql-spec/pull/395 for more on that.

In the meantime the best you can do is a runtime validation check:
```ruby
field :car, Types::CarType, null: false do
  argument :id, ID, required: false
  argument :external_id, ID, required: false
end

def car(id: :unspecified, external_id: :unspecified)
  if (id == :unspecified && external_id == :unspecified) || (id != :unspecified && external_id != :unspecified)
    raise GraphQL::ExecutionError.new('Must specify exactly one of id or externalId')
  end

  # ...
end
```

**Comment by RobsonKing** [comment]
ok, that is what I fell back to as well.

**Comment by rmosolgo** [comment]
Yep, best bet now is runtime, as shown above.

**Comment by blairio** [comment]
@RobsonKing  oneOf is now a thing: https://github.com/rmosolgo/graphql-ruby/pull/4184
