### ISSUE TITLE
How to 'decorate' result of a connection field

### ISSUE THREAD

**Issue by blevine** [rmosolgo/graphql-ruby#2275]
Use case:
Define a 'filter' in the schema that programmatically generates arguments that can be used to form additional scopes (where clauses). The additional scope is then applied to the result of the resolve method. Example:

```
field :all_pages, PageType.connection_type, null: true do
  argument :filter, required: false, filter_fields: [:foo, :bar]
end

def all_pages(**args)
  Page.all
end
```
which would generate arguments like: 'fooEquals', 'fooLike', 'barEquals', 'barLike' which can be used to define a where predicate.

I have the argument generation/where clause generation working fine.  The challenge is how to add the additional scope(s) to the result returned from the resolve method. 

Consider the above example. The resolve method will return an `ActiveRecord::Relation`. I had thought that a good way to achieve what I want would be to define a `GraphQL::Schema::FieldExtension` to apply the additional scopes in the extension's `after_resolve()` method.  However, by the time my extension is called, the ConnectionExtension has already been called so my extension receives a RelationConnection rather than the underlying Relation. And the underlying Relation is not visible from the RelationConnection. 

Summary:  I'm looking for a way to decorate the result set returned from the resolve method

**Comment by rmosolgo** [comment]
Thanks for the detailed writeup, sorry I didn't respond sooner. 

Honestly, the best solution I can think of is to manually prepend your extension, for example:

```ruby 
class Types::BaseField < GraphQL::Schema::Field 
 def initialize(*args, &block)
    super 
    if arguments["filter"]
      ext = FilterArgumentExtension.new(any_options_needed)
      extensions.unshift(ext)
    end 
end 
```

Maybe it'd be nice to improve the `extension(...)` API to accept an `index:` option, or `prepend: true`, or something to cover that use case. 

Anyways, I hope that helps! Feel free to open a PR for a formal API, or let me know if it doesn't work. If more folks come looking for this, maybe I'll add an API myself.
