### ISSUE TITLE
Guide: Authorization

### ISSUE THREAD

**Issue by mpoisot** [rmosolgo/graphql-ruby#2277]
Please show an example of using .authorization() on a field.

**Comment by wecanooo** [comment]
In my case,

https://www.howtographql.com/graphql-ruby/0-introduction/

this document was really helpful for me to start graphql with ruby

**Comment by smk1992** [comment]
[Authorization Guide](https://graphql-ruby.org/authorization/authorization.html#adding-authorization-checks) ?

**Comment by mpoisot** [comment]
Honestly I can't remember what I was looking at when I asked this. https://graphql-ruby.org/authorization/authorization.html seems to cover what I want.
