### ISSUE TITLE
Guide: Lookahead

### ISSUE THREAD

**Issue by mpoisot** [rmosolgo/graphql-ruby#2278]
Please show an example of avoiding N+1 DB loads.

**Comment by wecanooo** [comment]
http://blog.rstankov.com/dealing-with-n-1-with-graphql-part-1/
I hope this url can help you :D

**Comment by Tengoot** [comment]
[graphql-batch gem](https://github.com/Shopify/graphql-batch) is an pretty neat solution in terms of batch loading.

**Comment by mpoisot** [comment]
@Tengoot that's what I ended up using. But I'm still not sure the lazy loading approach is best way for all scenarios. It seems like you can't make full use of ActiveRecord associations with that approach. So when I first looked at the Lookahead docs I thought it would be for knowing when to do an ActiveRecord preload (include). Something like: "We're currently loading a Post, lookahead to see if we will need post.user deeper down, and if so add `.includes(:user)` to the lookup. And maybe it could be used for that, I haven't heard anyone say otherwise. Or maybe it's hard to detect all scenarios where you need to lookahead so it's not worth the trouble. Any insight would be appreciated.

**Comment by rmosolgo** [comment]
Hi, I don't use lookahead for avoiding n+1s, I also use graphql-batch. Feel free to update the docs if you find something that works!
