### ISSUE TITLE
.id_from_object receives object as string, when using Schema.subscriptions.trigger

### ISSUE THREAD

**Issue by mathiasjakobsen** [rmosolgo/graphql-ruby#2279]
Migrating our app to Ruby 2.6.3, Rails 5.2.3 and Ruby GraphQL 1.9.4, I'm having an issue with Subscription triggering. I'm finding, that triggering a subscription, will raise an exception in the `self.id_from_object(object, type_definition, context)` method, because `object` is a JSON string of the originally passed ActiveRecord instance.
 
```ruby
  comment = Comment.create!(body: 'Hi') # ActiveRecord instance
  Schema.subscriptions.trigger(:comment_added, { comment_id: comment.id }, comment)
```

```console
NoMethodError (undefined method 'id' for #<String:0x00007f8a2adaec40>):
  app/graphql/schema.rb:23:in `id_from_object'
```

```ruby
class Schema < GraphQL::Schema
  use GraphQL::Execution::Interpreter
  use GraphQL::Subscriptions::ActionCableSubscriptions
  
  mutation(Types::Mutation)
  query(Types::Query)
  subscription(Types::Subscription)

  def self.object_from_id(id, context)
    type_name, item_id = UrlSafeUniqueWithinType.decode(id)
    type_name.constantize.find(item_id)
  end

  def self.id_from_object(object, type_definition, context)
      UrlSafeUniqueWithinType.encode(type_definition.name, object.id) # Line 23, where it seems 'object' is a String
  end
...
```

The problems continues, even if I "fix" the `self.id_from_object` method, returning a valid hardcoded UUID. Then, the next exception is raised because `ruby-graphql` can't call the defined type fields on a `String`.

```console
14:18:29 web.1     | RuntimeError (        Failed to implement Comment.body, tried:
14:18:29 web.1     |         - `Types::Comment#body`, which did not exist
14:18:29 web.1     |         - `String#body`, which did not exist
14:18:29 web.1     |         - Looking up hash key `:body` or `"body"` on `{"id":"2b3613b7-1b41-45a5-aa4c-517b0bd41d59","body":"Hi"}` , but it wasn't a Hash
14:18:29 web.1     |
14:18:29 web.1     |         To implement this field, define one of the methods above (and check for typos)
14:18:29 web.1     | ):
```

The rest of the API works fine, otherwise. It's only the `.trigger` call, that will fail in the `id_from_object` method and afterwards as above. Any chance you have an idea why this is happening?

**Comment by rmosolgo** [comment]
@gagalogo, the snippet you pasted with `def resolve(*)` is the expected configuration for a subscription like this. The `field ...`s that you add to a subscription class will be resolved against the return value of `resolve`, so you've done the right thing by returning a hash with a key for each of those fields.
