### ISSUE TITLE
Mutation input that is equal to ObjectType fields

### ISSUE THREAD

**Issue by zamith** [rmosolgo/graphql-ruby#228]
Hey,

I not sure if what I'm doing makes sense with GraphQL or if there is a better way. I am trying to create a mutation that takes as input all the fields of a type. Let's say I have an `ArticleType`:

```ruby
ArticleType = GraphQL::ObjectType.define do
  name "Article"

  field :title, !types.String
  field :body, !types.String
  field :author_name, types.String
end
```

And the mutation using the relay helpers:

```ruby
CreateArticleMutation = GraphQL::Relay::Mutation.define do
  name "CreateArticle"

  input_field :article_attributes, ArticleType

  return_field :article, ArticleType

  resolve -> (inputs, _context) do
    ...
  end
end
```

The `input_field` line won't work, as I have to create an `ArticleInput` that defines all the fields I was to take as arguments.

Is that the only way to this? Is this "repetition" desirable so that I have complete control of what goes each way?

**Comment by rmosolgo** [comment]
> Is that the only way to this?

Yes 😬 

> Is this "repetition" desirable so that I have complete control

Yes, that's the idea. Inputs are typed, just like return values. Additionally, you can require (or ignore) certain fields in certain contexts.
