### ISSUE TITLE
Wrong error trace showing up

### ISSUE THREAD

**Issue by Loschcode** [rmosolgo/graphql-ruby#2281]
**Context**

Rails 5.2.2.1
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18]

**My problem**

It's been a while I work with this gem and I noticed when I was having errors - usually about syntax or anything which's eager loaded such as class names, etc. - the correct error was showing up once or less, and when I would re-run the exact same query this shows up

```
{
  "error": "Unable to autoload constant Types::MutationType, expected /my-project/api/app/graphql/types/mutation_type.rb to define it"
}
```

When testing it out through GraphiQL, my current workaround is to slightly change a file and save it, then re-run to see the real error. The thing is, I believe there should be a better error output than that, something stable.

I'm unsure the gem itself is causing this and not some shady Rails thing, caching up or whatever, so here I ask.

**Comment by rmosolgo** [comment]
Sorry about this. It's an issue with how the schema is lazy-loaded. I'm hoping to fix it in 1.10 (https://github.com/rmosolgo/graphql-ruby/issues/2100), see also #1505 for similar error issues.
