### ISSUE TITLE
Web site broken links

### ISSUE THREAD

**Issue by davidw** [rmosolgo/graphql-ruby#2288]
Not sure if there's an update in progress, but I'm getting a bunch of 404's trying to look at the docs:

- https://graphql-ruby.org/guides/
- https://graphql-ruby.org/getting_started/
- https://graphql-ruby.org/api-doc/1.9.4/

**Comment by davidw** [comment]
Seems to be better right now - API link is still broken though.

**Comment by croaker** [comment]
You're right, it seems as if the update has gone wrong. However, I accidentally found out that the api docs for 1.9.3. are still available at https://graphql-ruby.org/api-doc/1.9.3 Maybe this helps in the meantime.

**Comment by davidw** [comment]
I was able to get everything running locally with `rake site:serve`, but thought I'd point out there was a problem in any case.  Thank you

**Comment by ralphhaygood** [comment]
The API link is still broken today.

**Comment by rmosolgo** [comment]
Hey, thanks for reporting this. I'm not sure about the guides pages, but the API docs were broken because it requires a separate task to generate those. I just ran it and republished, so they're up now. I wish I could streamline this better but ... not enough hours in the day 🍻
