### ISSUE TITLE
Default Object pundit_role overrides field level pundit_role

### ISSUE THREAD

**Issue by goalaleo** [rmosolgo/graphql-ruby#2291]
Hi!

I'm having some trouble understanding how the authorization should work if both object level and field level authorization is used. I'm not sure if this is a bug, but - at least for me - it's  a bit confusing.

Here's my situation:

I've set the default `pundit_role` to `:show` for `BaseObject`
```
module Types
  class BaseObject < GraphQL::Schema::Object
    field_class Types::BaseField

    include GraphQL::Pro::PunditIntegration::ObjectIntegration
    pundit_role :show
  end
end
```
I've set the default `pundit_role` to `nil` for `BaseField`
```
class Types::BaseField < GraphQL::Schema::Field
  # Add the Pundit integration:
  include GraphQL::Pro::PunditIntegration::FieldIntegration
  # By default, don't require a role at field-level:
  pundit_role nil

  argument_class Types::BaseArgument
end
```
Then I have these two types:
```
module Types
  class MessageType < Types::BaseObject
    # ...
    field :author, AuthorType, "Author of the message", null: false
  end
end
```
```
module Types
  module AuthorType
    include Types::BaseInterface

    # ...
  end
end
```
---
**Expected behaviour**:
Since the `pundit_role` for fields is set to `nil`, I'm expecting a user to be able to access the author of the message if they pass the (object level) `MessagePolicy#show?` check.

**Actual behaviour**:
The object level check `MessagePolicy#show?` is ran first, and *if* that passes, an object level check `WorkerPolicy#show?` is ran (`WorkerType` implements `AuthorType` interface).

I tried to explicitly set the `pundit_role` to nil for the `:author` field, which did not help.
```
field :author, AuthorType, "Author of the message", null: false,
  pundit_role: nil
```
I also tried to set it to `:something_else` hoping that it would replace the `MessagePolicy#show?` call, but it just ran `MessagePolicy#something_else?` and then ran `WorkerPolicy#show?`
```
field :author, AuthorType, "Author of the message", null: false,
  pundit_role: :something_else
```
---
Have I misunderstood something?

**Comment by rmosolgo** [comment]
Hi, sorry about the confusion! It sounds like it's working as _intended_, so maybe we can find a way to accomplish what you're looking for.

- _Object types_ check their inner objects before resolving any fields on that object. So, `BaseObject.pundit_role(:show)` will cause the `#{classname}#show?` policy to be checked for _every_ object in the system (every Message and every Worker). 
- _Fields_ check their return value before returning it. This is for cases where the _relationship_
 between parent object and field is special. For example, "Only administrators can see a user's birthday": in this case, the `Date` type is not private in general, only _this_ Date field is private.


So, the two approaches are _additive_ but never override one another. To implement "Anyone who can see a message can also see the message's author," you should include that logic in the `WorkerPolicy#show?` check. 

For example, let's say I accessed an author ID like this: 

```graphql 
{
  viewer {
    messages(first: 1) {
      nodes { 
        author {
          authorId: id 
        }
      }
  }
}
```

Then refetched the object like this: 

```graphql 
query($authorId: ID!) {
  node(id: $authorId) {
    name 
  }
}
```

Shouldn't I be able to see the `Author` in both cases (regardless of whether or not I'm also seeing the message)?

**Comment by daemonsy** [comment]
Hi @goalaleo I'm going to close the issue. If you still need help, please feel free to reopen this.
