### ISSUE TITLE
Field `authorized?` doesn't get schema object

### ISSUE THREAD

**Issue by eapache** [rmosolgo/graphql-ruby#2293]
Currently `Field#authorized?` takes the application object and the context.
https://github.com/rmosolgo/graphql-ruby/blob/8f25306ce643c26c87ad592a8b67b0159528f72d/lib/graphql/schema/field.rb#L478

We have a use case where we'd like to look something up off of the schema object instead. It's not the `owner` (because that's an interface, and we want to look up on the concrete type). We can use the interface and the application object to reverse-engineer the schema object again, but ideally it just gets passed in (at the call site above it's already in scope).

Only issue is that it's potentially a breaking change to the `authorized?` method?

**Comment by eapache** [comment]
This is actually more important when we have some inheritance, like
```ruby
class SomeBaseClass < GraphQL::Schema::Object
  field :foo
end

class SomeRealClass < SomeBaseClass
end
```

Because in `authorize?` for `foo`, `owner` is `SomeBaseClass`, but we really want `SomeRealClass`. Since it's not an interface with a `resolve_type` method AFAICT the only way to get that type is to have it passed down.

**Comment by eapache** [comment]
As a workaround we've found we can put the following in our local subclass of `GraphQL::Schema::Field`:

```ruby
    def resolve(obj, args, ctx)
      @current_type = obj
      super
    ensure
      @current_type = nil
    end
```

Tangentially, the more we're digging into this the more I'm realizing that long-term we may want more parts of an interface's fields to differ across the concrete types that implement them, which calls into question the interface-as-module approach. But anyway.

**Comment by rmosolgo** [comment]
Personally, I consider it a _feature_ to hide that position-related context from the authorization layer. I say that because we used to have some position-based authorization in GitHub's code (eg, different auth rules for the same object, depending on the field it was returned from), but it was very buggy and prone to errors. For example, there might be a field whitelisted by name, assuming that no same-named field would ever be created. But if we _did_ create a field with the same name, it would have gotten lax authorization by accident. So, I migrated our code to use the signature `authorize(application_obj, graphql_ctx)` like you noted here, so that we would avoid the temptation to use (incomplete) position-based context for authorization. 

I'd love to hear more about the specific use case in case I've overlooked something or there's another way to get it done!

**Comment by eapache** [comment]
Ah, ya I can see why it would generate that concern. What we're actually doing is wanting the ability to specify on an object a list of fields with a particular extra protected state, e.g.

```ruby
class GraphApi::Object < GraphQL::Schema::Object
  def self.some_extra_protection(*args)
  end
end

class SomeType < GraphApi::Object
  some_extra_protection(:field1, :field2, :field3)
end
```

We don't want to just make it part of the arguments to `field` directly because the same logical field (coming from the same interface) may have extra protection on one type but not on another. And then we run into load-order issues (does `some_extra_protection` end up being run before or after the interface that defines `field1` was included?) so we wanted to do it dynamically at runtime, but this requires access to the schema object.

A simpler way to do this may just be to have a way to redefine parts of a field (e.g. coming from inheritance or an interface) on a concrete type in a way that doesn't break the schema contract?

**Comment by rmosolgo** [comment]
I'm finally coming back to this, sorry for the delay. I see your point about needing the runtime object -- and I really can't think of a better way to pass in that information. 

I'd love to implement it in a way that doesn't break existing authorized? implementations, at least not yet. Something like adding a new method, `authorized_with_schema_object?(schema_obj, args, ctx)` which calls `authorized?`. Maybe in a later version, we could change the default behavior of `authorized?`.

Did you end up finding anything else that worked well for you here?

**Comment by eapache** [comment]
We're still running with the workaround in https://github.com/rmosolgo/graphql-ruby/issues/2293#issuecomment-493592295 and I've mostly forgotten how all of this works again. I think `authorized_with_schema_object` would let us get rid of the workaround still, and seems to be in line with what past me was after.

**Comment by rmosolgo** [comment]
After so much time, and no other requests for this behavior, I don't have plans to work on this. If anyone wants to investigate the situation above, or if anyone wants to discuss this change again, please open a PR or a new issue and I'd be happy to help out!
