### ISSUE TITLE
Allow mutation to return an existing type

### ISSUE THREAD

**Issue by schmurfy** [rmosolgo/graphql-ruby#2298]
Hello, I have been looking thought the code and it seems possible with a relay mutation but I can't find a way to do it with a normal mutation:

```ruby
class PriceListType < GraphQL::Schema::Object
  field :id, Integer
  field :label, String
  
end

class CreatePriceListMutation < GraphQL::Schema::Mutation
  
  return_type PriceListType
  
  def resolve(...)
    PriceList.create()
  end
end
```

It would be nice to allow this ti return an object directly without having to copy all the fields in the mutation definition.

PS: I am not clear on what relay mutations are but I decied to not use relay objects since it seems way more xomplicated than what I need.

**Comment by rmosolgo** [comment]
Hi, I think you can use `type(...)` to configure this (instead of `return_type` in your example above). Give it a try and let me know what you find!

Source: 

https://github.com/rmosolgo/graphql-ruby/blob/e78521d8011d39d628f1282845ff32e850803b0b/lib/graphql/schema/resolver.rb#L202-L209

**Comment by schmurfy** [comment]
@rmosolgo  thanks it worked perfectly :)

**Comment by benbonnet** [comment]
@rmosolgo if I may ask about it; using `input_type` removes the `Autogenerated input type of ...`

Is there a way to blocks the autogenerated `Autogenerated return type of...` ? I thought that using `type` would let it be handled completely, but it is still there. I might miss something, thx if you have such info
