### ISSUE TITLE
Handle empty strings strings in args/input objects

### ISSUE THREAD

**Issue by devknoll** [rmosolgo/graphql-ruby#23]
Empty strings aren't being parsed. It looks we `repeat(1)`'d when we should have `repeat`'d :wink:

**Comment by rmosolgo** [comment]
errp, sure enough:  https://github.com/rmosolgo/graphql-ruby/commit/19ed3fb8c605c0b84ebe8207908d48533db724c9

TODO: handle escaped character & unicode :grin:

**Comment by rmosolgo** [comment]
Added support for escaped characters and unicode here: https://github.com/rmosolgo/graphql-ruby/commit/abbdd3430cf0e39f8240ffb7ed45445da8ad46c5 

Let me know if you run into more string bugs!
