### ISSUE TITLE
RuntimeError: Unexpected parent_type:

### ISSUE THREAD

**Issue by Nghi93** [rmosolgo/graphql-ruby#2303]
We just upgraded from 1.8.11 to 1.9.4 and now we have problems with debugging errors during our rspec tests.
e.g. we have an exception occuring during the first test:
NameError:
       uninitialized constant Types::ApplicationType

In 1.8.11 this error would occur repeatedly during the whole test suite run.
Since 1.9.4 only the first spec fails with the error above. All following specs are failing with
RuntimeError:
       Unexpected parent_type:

Does this behavior has something to do with schema caching?
How can we get better errors in this case?

**Comment by Nghi93** [comment]
We narrowed down the issue.

When defining a type:
class Customer < GraphQL::Schema::Object
  field :someField, GraphQL::Types::String, null: false, resolve: UnknownClass
end 

This results in a NameError the first time, but Customer is still defined.
For the following specs the schema seems valid for the validator.

When GraphqlSchema.execute is called  the error `RuntimeError: Unexpected parent_type:` occurs.

**Comment by drop-george** [comment]
Seeing the same issue on (1.9.6)

**Comment by jean-francois-labbe** [comment]
Hi I had the same issue with:
```ruby
class UserType < Types::BaseObject
  field :id,  null: false
end
```
I fixed it by adding the field ID type.
```ruby
class UserType < Types::BaseObject
  field :id, ID, null: false
end
```

Hope this helps

**Comment by Nghi93** [comment]
> Hi I had the same issue with:
> 
> ```ruby
> class UserType < Types::BaseObject
>   field :id,  null: false
> end
> ```
> 
> I fixed it by adding the field ID type.
> 
> ```ruby
> class UserType < Types::BaseObject
>   field :id, ID, null: false
> end
> ```
> 
> Hope this helps

As long as your definition is valid, everything is fine.
But if you have an error, you will get the error message mentioned above.

**Comment by rmosolgo** [comment]
Hi! Please reopen with the full backtrace along and full error messages if you want to debug further. Hard to debug without seeing that.

**Comment by jessecurry** [comment]
I ran into this one and realized I was using `null: false` instead of `required: true`.

**Comment by etherbob** [comment]
Had a similar issue when I accidentally inherited from `BaseType` instead of `BaseObject`, but I had no hint that was what was wrong. Just `RuntimeError:
       Unexpected parent_type:`

**Comment by etherbob** [comment]
I was looking at the backtrace, but I always get a little tangled in the visitor pattern (my failing there) and I'm having trouble seeing where to hook in and raise that might call this out more clearly.

**Comment by jclemans** [comment]
I ran into this issue when I accidentally removed a type file that was referenced by a parent object type. Bringing the missing type file back fixed the issue for me.

**Comment by iDuuck** [comment]
I had the same issue and it got fixed for me, because I accidently had the wrong file name (Autoloading issue).

Previously, my file was named `trackable_union.rb` and the class was `Trackable`. After renaming the `trackable_union.rb` to `trackable.rb` it worked for me.

**Comment by sveredyuk** [comment]
+1

Found a new case. This exception raise for clear schema without any queries or mutations. Pretty confused. Expect to see something different.
