### ISSUE TITLE
Strings inside of list arguments are being frozen in v1.9.0

### ISSUE THREAD

**Issue by stanishev** [rmosolgo/graphql-ruby#2304]
It appears that as of version 1.9.0.pre1 strings **inside** of list arguments are being frozen (new behavior compared to pre 1.9).
Individual string arguments are **not** frozen (same behavior as pre 1.9)

For example: 
```ruby
# each (email) address inside of the addresses list comes into your resolver as a frozen string
argument :addresses, !types[!types.String]

# this individual string argument is not frozen
argument :subject, !types.String
```

This is a breaking change for any apps that depend on services downstream from graphql to be able to sanitize (modify) the arguments.

Raising this issue to politely suggest that we do one of the following instead: 

1. do not freeze strings in lists. This would mean removing the freeze [here](https://github.com/rmosolgo/graphql-ruby/commit/f2d8f6b524bfd69841d8f4baaf3a2c8e58f4d91d#diff-e93b48ad28511014b5c2ba266dcc3db0R227) (or [here](https://github.com/rmosolgo/graphql-ruby/commit/f2d8f6b524bfd69841d8f4baaf3a2c8e58f4d91d#diff-e93b48ad28511014b5c2ba266dcc3db0R227), I am not sure which of these two is causing the argument freeze in the lists).

2. if we opt to keep freezing string arguments in lists, then lets freeze individual string arguments as well. This would be even more of a breaking change but at least the behavior would be consistent for all string arguments.

If freezing strings in arguments is kept, the API docs for arguments should be updated to reflect that. 

**and PS**: argument sanitizing should probably be performed in `prepare` methods instead of passing them to and relying on downstream services to do it.

**Comment by rmosolgo** [comment]
Hmm, thanks for reporting this! I don't quite understand what went wrong. Could you share some example code that's broken? (I see the field configurations above, but could you share some resolvers that demonstrate this issue?)

**Comment by stanishev** [comment]
@rmosolgo 
apologies, I was mistaken with my original analysis so I am closing this issue.

strings are indeed frozen in v1.9.0 and later. but the behavior is consistent (individual string arguments are frozen, as are string arguments inside lists).

The problem this caused for us is that the following started failing: 

```ruby
    field :send_email, !types.Boolean do
      argument :addresses, !types[!types.String]
      resolve lambda { |_, args, _|
        #the call to strip! in the next line causes a: RuntimeError: can't modify frozen String
        args[:addresses].map {|email| email.strip!}
        send_email(args[:addresses]) 
        .... 
      }
    end
```
This is an oversimplification, the error was coming from a method further down the call stack, but the result is the same.

I assume this could still cause someone a problem, but considering that all string arguments behave consistently it's much less of an issue than I thought at first. Might still be worth mentioning it in one of the **breaking changes** sections of the CHANGELOG file (we upgraded from v1.7.4 to v1.9.4, I am not sure exactly which version in between introduced this).
