### ISSUE TITLE
Installing plugins on schemas built from a definition string is hard

### ISSUE THREAD

**Issue by myronmarston** [rmosolgo/graphql-ruby#2307]
I'm trying to use [graphql-batch](https://github.com/Shopify/graphql-batch) on a project.  In my project, I'm not defining a `GraphQL::Schema` as shown in the `graphql-batch` README (and most graphql-ruby examples in general).  Instead, I read the schema at boot time of my app from a `.graphql` file:

``` ruby
schema  = GraphQL::Schema.from_definition(graphql_schema_string, default_resolve: ->(*args) { MyResolver.resolve(*args) })
```

It's not clear how I can install `graphql-batch` when I don't have a schema class.  I did some digging through the source of this gem, and found `GraphQL::Define::DefinedObjectProxy`, which lets me install `graphql-batch`:

``` ruby
GraphQL::Define::DefinedObjectProxy.new(schema).use(GraphQL::Batch)
```

However, this isn't a documented, supported way to install plugins as far as I can tell.  More generally, `GraphQL::Define::DefinedObjectProxy` doesn't feel like it's intended to be part of the public API and used in this manner.

Is there a simpler/better way to install a plugin on my `GraphQL::Schema` instance?  If not, can one be added?

**Comment by rmosolgo** [comment]
Hi, thanks for opening this issue. I think I can implement `Schema.use(...)` to cover this case in 1.10.

**Comment by rmosolgo** [comment]
In 1.10-dev, `from_definition` accepts a `using:` Hash of `plugin => options`  which is passed to the defined schema: 

https://github.com/rmosolgo/graphql-ruby/blob/96072b42caecb5021db3b3cc1e1006f239c7753f/lib/graphql/schema/build_from_definition.rb#L8

https://github.com/rmosolgo/graphql-ruby/blob/96072b42caecb5021db3b3cc1e1006f239c7753f/lib/graphql/schema/build_from_definition.rb#L131-L133

You can see an example here, for subscriptions: 

https://github.com/rmosolgo/graphql-ruby/blob/6874a943779423a349c1495b3398d358eb4a3211/spec/graphql/subscriptions_spec.rb#L201
