### ISSUE TITLE
Schema::Loader does not fail gracefully

### ISSUE THREAD

**Issue by belt** [rmosolgo/graphql-ruby#2308]
https://github.com/rmosolgo/graphql-ruby/blob/571e05ab82eed2d405c74febc93b45fd90e2fbcc/lib/graphql/schema/loader.rb#L16

What happens when there is no `data` object returned e.g. there is an error with the query formatting, or a field doesn't exist, or the service is offline? `.fetch("data")` fails, so `nil.fetch(...)` method not found

**Comment by rmosolgo** [comment]
Hi! I agree that error handling could be better here. Feel free to improve it as you see fit! I don't have a use case for it or the bandwidth to do it myself right now.
