### ISSUE TITLE
How to override argument class on InputObject

### ISSUE THREAD

**Issue by FX-HAO** [rmosolgo/graphql-ruby#2310]
I want to disable camel-style in default, so i updated `base_argument.rb` as following:
```ruby
class DisableCamelCaseArgument < GraphQL::Schema::Argument
  def initialize(*args, **kwargs, &block)
    kwargs.reverse_merge! camelize: false

    super(*args, **kwargs, &block)
  end
end
```

and my input files:

```ruby
class Types::BaseInputObject < GraphQL::Schema::InputObject
  self.arguments_class = DisableCamelCaseArgument
end

class TimeRangeInput < Types::BaseInputObject
  graphql_name 'TimeRangeInput'

  argument :pickup_from, Types::DateTimeType, required: true
  argument :pickup_to, Types::DateTimeType, required: true
end
```

But it didn't work, I still got camel-style fields.
![image](https://user-images.githubusercontent.com/6838487/58628549-8eca9c80-830c-11e9-8880-ca6c26086e2a.png)

**Comment by rmosolgo** [comment]
Hi! Try this instead: 

```ruby 
class Types::BaseInputObject < GraphQL::Schema::InputObject
  argument_class(DisableCamelCaseArgument)
end
```

I've updated the docs in https://github.com/rmosolgo/graphql-ruby/commit/bcf0eb1c7a51dad6957460c80b5d32291ef1b9b7, sorry for the confusion there!
