### ISSUE TITLE
Apollo Federation Spec Support

### ISSUE THREAD

**Issue by audiolion** [rmosolgo/graphql-ruby#2311]
Hi @rmosolgo 👋 

Apollo announced their [federation service](https://blog.apollographql.com/apollo-federation-f260cf525d21) today which enables the creation of a graphql gateway that merges multiple graphql schemas together under one graphql endpoint. Would `graphql-ruby` consider adding support for the [Federation spec](https://www.apollographql.com/docs/apollo-server/federation/federation-spec/)? It would enable people using `graphql-ruby` to easily compose multiple graphql apis into a single graphql gateway.

**Comment by rtymchyk** [comment]
Based on this SO answer (https://stackoverflow.com/a/56432125/3271124) there is some hope in building this out ourselves before it is merged into graphql-ruby. Creating few types, custom directives, and implementation details for them.

Has anyone had a chance to start? I will be exploring this pretty soon and will share any progress I got.

**Comment by rmosolgo** [comment]
Hey, thanks for sharing that news! I'd be happy to include support along with GraphQL-Ruby, but personally I don't expect to have bandwidth for it until 1.10 (#2100) is done. If someone wants to implement it separately, please upstream any improvements to graphql-ruby that would make it easier to support!

**Comment by jbaxleyiii** [comment]
👋 Anything I can do to help (from the Apollo Federation team)

**Comment by diogobeda** [comment]
I'm also starting to take a look at this in my own fork. Will use this issue to post future questions and progress 👋

**Comment by rylanc** [comment]
I just published the first version of a Ruby implementation of Apollo Federation: https://github.com/Gusto/apollo-federation-ruby. It works alongside `graphql-ruby`. Please try it out and let me know what you think!

**Comment by audiolion** [comment]
@rylanc that is awesome! Going to try this out next week

**Comment by sam-enough** [comment]
@rylanc Also going to give this a try this week, first glance it looks like a great start.

**Comment by rmosolgo** [comment]
Thanks for your work on this @rylanc! Please do open an issue if there's anything we could do in GraphQL-Ruby to help you support it.
