### ISSUE TITLE
[pro] failed pundit checks leave null in non-nullable array

### ISSUE THREAD

**Issue by cainlevy** [rmosolgo/graphql-ruby#2312]
How can I prevent a failed Pundit check from leaving a null inside my non-nullable array?

Suppose an author with many books:

```ruby
class AuthorType < GraphQL::Schema::Object
  include GraphQL::Pro::PunditIntegration::ObjectIntegration
  pundit_role :view

  field :books, [BookType], null: false
end
```

If my `BookPolicy#view?` returns false for one of the books then the field will contain `[null]` and throw a type error (e.g. null for non-nullable AuthorType.books).

Should I expect this to work, or should I focus on scoping the collection so that policy checks always pass?

**Comment by cainlevy** [comment]
> should I focus on scoping the collection so that policy checks always pass

If this ends up being the recommendation, then it becomes a developer experience issue. The "null for non-nullable" error doesn't provide any clues about why the field has a null and developers must rely solely on intuition to figure out that policies are to blame.

**Comment by rmosolgo** [comment]
Yes, scoping the collection is the right solution here. Thanks for pointing out that developer experience issue. I wonder how it could notify the developer that it was `nil` because of authorization without leaking data to the API client 🤔  Perhaps another use case for #2286
