### ISSUE TITLE
ArgumentError: missing keyword: required

### ISSUE THREAD

**Issue by LilyMGoh** [rmosolgo/graphql-ruby#2314]
Hi. I just freshly installed graphql to a new rails codebase (v 5.2.3). When I put this

```ruby
    field :foo, ID, null: false do
    end
```
in `query_type.rb`, it seems to be working fine. However, when I include argument to the field, like this,

```ruby
    field :foo, ID, null: false do
      argument :aaaa, ID
    end
```
I got `LoadError - Unable to autoload constant Types::BaseObject, expected ...../app/graphql/types/base_object.rb to define it:`

In the rails console, when I invoke the schema, I'm also getting this error,

```
ArgumentError: missing keyword: required
from /Users/lily/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.9.6/lib/graphql/schema/argument.rb:33:in `initialize'
```
Did I miss anything? Thank you.

---------------
rails: 5.2.3
ruby: 2.5.0p0
graphql: 1.9.6
graphiql-rails: 1.7.0

**Comment by nekogami** [comment]
Are you sure that
app/graphql/types/base_object.rb  (that exact path) define Types::BaseObject ? 

Also, when you define an argument, you have to add a required: true/false value to it (which is missing in your example)

**Comment by LilyMGoh** [comment]
@nekogami 

> Are you sure that
app/graphql/types/base_object.rb (that exact path) define Types::BaseObject ?

Yes, that was generated. It also doesn't make sense why `BaseObject` would be undefined when I added argument to field, it works otherwise.

 > Also, when you define an argument, you have to add a required: true/false value to it (which is missing in your example)

I have tried that as well, didn't work.

**Comment by hugoh59** [comment]
Error messages are usually very unhelpful it's a shame.
