### ISSUE TITLE
Argument is defined in snake_case but field resolves into camelCase

### ISSUE THREAD

**Issue by anhang** [rmosolgo/graphql-ruby#2315]
graphql version: 1.9.6

See Example below:

Ruby Definition
```ruby
class Types::UserType < Types::BaseObject
  field :car, Types::CarType, null: false, resolve: ->(obj, args, ctx) {
    args[:car_color] # Does not exist but should, since we implemented in snake case.
    args[:carColor] # Exists
    args["carColor"] # Also exists
  }
end

class Types::CarType < Types::BaseObject
  argument :car_color, String, required: true
end
```

GraphQL callsite
```graphql
{
  users($username: "my-username") {
    car($carColor: "blue"){
      ...
    }
  }
}
```

**Comment by daemonsy** [comment]
Hi @anhang I believe the default behavior of GraphQL Ruby is to generate the schema in camelcase. 

https://graphql-ruby.org/fields/arguments.html (search for "To disable auto-camelization"), read upwards and downwards a little. Sorry no anchors around that area to give you a direct link. 

if you'd like to disable camelization altogether, I believe you can do it by setting the default value in the args. 

https://graphql-ruby.org/fields/introduction.html#field-parameter-default-values

Let me know if this solves your issue.

**Comment by rmosolgo** [comment]
Thanks for addressing this, @daemonsy. This is a "feature" :P 

In old graphql-ruby, it wasn't camelized, and many people requested automatic camelization. Please see the links shared above for disabling camelization and reopen if you have any trouble.

**Comment by anhang** [comment]
I think there's a misunderstanding here. This has nothing to do with the GraphQL schema, but rather how arguments are resolved on the ruby side.

In this example from the link provided:
```ruby
field :posts, [PostType], null: false do
  argument :start_date, String, required: true, prepare: ->(startDate, ctx) {
    # return the prepared argument.
    # raise a GraphQL::ExecutionError to halt the execution of the field and
    # add the exception's message to the `errors` key.
  }
end

def posts(start_date:)
  # use prepared start_date
end
```

the argument `start_date` is both defined in snake_case and resolved into snake_case in

However, in my initial example, I cannot use `args[:start_date]` (or `args[:car_color]`). Instead, I have to use `args[:startDate]`. Shouldn't this be consistent?

**Comment by rmosolgo** [comment]
Oh 🤦‍♂  I see what you mean, I'm sorry I didn't read closely! 

I see now that your example is using `resolve: ->(obj, args, ctx) { ... }`. Resolve procs are supported for backwards compatibility. They use camel-cased arguments just like old graphql-ruby versions did. This was to make it easier for people to migrate gradually. 

I recommend using a method instead!

**Comment by anhang** [comment]
Got it. I didn't know resolve is deprecated. Thanks!
