### ISSUE TITLE
Rails 6 upgrade -  uninitialized constant GraphQL::Types

### ISSUE THREAD

**Issue by Rob117** [rmosolgo/graphql-ruby#2316]
One line in a file works perfectly in rails 5, but not in rails 6:

config/time_initializer.rb:

`GraphQL::Types::ISO8601DateTime.time_precision = 6`
gives
` uninitialized constant Types::ISO8601DateTime (NameError)`

**Comment by Rob117** [comment]
Actually, it seems like ` uninitialized constant GraphQL::Schema::Object` is popping up everywhere post upgrade.

**Comment by daemonsy** [comment]
Hey @Rob117, there could a lot of reasons to your issue. Do you have a code sample or a way to reliably reproduce this? 

Hypothetical example for reproduction instructions. 
- For a default Rails 6.0 installation generated using `rails new <app>`
- Add latest version of GraphQL gem in Gemfile. 
- Referencing this constant `GraphQL::Schema::Object` causes an error.

**Comment by rmosolgo** [comment]
Hi, sorry for the trouble. Please share the full error message and full backtrace if you want to debug further! I can't debug what I can't see 😉
