### ISSUE TITLE
How can I define String ScalarType with limited length?

### ISSUE THREAD

**Issue by harhogefoo** [rmosolgo/graphql-ruby#2317]
I'm trying to define Custom String ScalarType. But I have no idea how to define it.

In the document, Url type is mentioned.

https://graphql-ruby.org/type_definitions/scalars.html#custom-scalars
```
# app/graphql/types/url.rb
class Types::Url < Types::BaseScalar
  description "A valid URL, transported as a string"

  def self.coerce_input(input_value, context)
    # Parse the incoming object into a `URI`
    url = URI.parse(input_value)
    if url.is_a?(URI::HTTP) || url.is_a?(URI::HTTPS)
      # It's valid, return the URI object
      url
    else
      raise GraphQL::CoercionError, "#{input_value.inspect} is not a valid URL"
    end
  end

  def self.coerce_result(ruby_value, context)
    # It's transported as a string, so stringify it
    ruby_value.to_s
  end
end
```

I'd like to define like this
```
module ScalarTypes
  class LimitedString < BaseScalar
    def self.coerce_input(input_value, _context)
      if (limit < input_value.length) {
        raise GraphQL::CoercionError, "#{input_value.inspect} is too long"
      }
      return input_value
    end

    def self.coerce_result(ruby_value, _context)
      ruby_value
    end
  end
end
```

How can I give `limit` to ScalarType?

Thank you for reading.

**Comment by rmosolgo** [comment]
Hi, good question! 

Do you want your `LimitedString`s  to have the _same_ limit, or do you want them to have different limits? 

To apply the _same_ limit to all limited strings, you could hardcode the value or make a `LIMIT` constant in the type class. 

For varying limits, graphql-ruby doesn't have anything to support this yet. You'd have to make the check in the field, for example:

```ruby 
field :update_name, String, null: false, description: "update your username, limit 100 characters" do 
  argument :new_name, String, required: true 
end 

def update_name(new_name:) 
  if new_name.size > 100 
    raise GraphQL::ExecutionError, "new_name is too long, must be less than 100 but it was #{new_name.size}" 
  else 
    context[:viewer].update(name: new_name) 
    new_name # return the new name 
  end 
end 
```

GraphQL-Ruby doesn't have any rails-style validations for inputs yet! 

Does that answer your question?

**Comment by harhogefoo** [comment]
@rmosolgo 

Thank you for answering and writing example!

> Do you want your LimitedStrings to have the same limit, or do you want them to have different limits?

I'd like to them to have different limits.
OK, I'll make ScalarType by hardcord.

I'm using GraphQL-Ruby in serverless-ruby without Rails. so I wanted validation function（If I use Rails, I wouldn't care about validation in ScalarType).

Thank you!
