### ISSUE TITLE
AnalysisError format

### ISSUE THREAD

**Issue by bejczib** [rmosolgo/graphql-ruby#2324]
Hi, 

this is related to #1962. 

In case of a static analyzer error is there a solution where I can extend `extensions` in the response? 

Thank you in advance! 

Best,
Balint

**Comment by rmosolgo** [comment]
Yes, it accepts an `extensions:` key, just like execution errors:

https://graphql-ruby.org/errors/execution_errors.html#customizing-error-json

(AnalysisError is a subclass of ExecutionError: https://github.com/rmosolgo/graphql-ruby/blob/73ac09cb95a0b03b3f00c09921b65534f66d0ae6/lib/graphql/analysis_error.rb#L3)

Please let me know if you have any trouble with that!
