### ISSUE TITLE
Add a Printer to redact inlined argument values in GraphQL queries for logging

### ISSUE THREAD

**Issue by daemonsy** [rmosolgo/graphql-ruby#2333]
## Background 

Typically GraphQL uses `HTTP POST` for execution over the wire and POST bodies are not usually written to logs. Hence if we searched the logs, it must just consist of: 

```sh
method=POST path=/graphql format=json controller=GraphQLController  action=execute status=200

method=POST path=/graphql format=json controller=GraphQLController  action=execute status=200

method=POST path=/graphql format=json controller=GraphQLController  action=execute status=200
```

`<s>` This is super useful for debugging :)  `</s>`

### Logs are our friend 
Logging the `query` parameter can be really useful for a variety of reasons: 
- when GraphQL execution is not successful 
- Capturing field selections for deprecation of a field 
- Traces for NewRelic for slow queries

### Logging queries safely 
In web frameworks such as Rails, there are helpers to filter out sensitive parameters such as `password`, `token`. `Authorization`. 

In a GraphQL raw query , if the author did not used **inline variables**, we can already deem the query as safe as it does not contain any data. `variables` is usually a separate parameter is a `Hash`, so it's straightforward for Devs/DevOps to do filtering there. 

### The Problem and Solution
Inline variables are used frequently, especially when someone is prototyping a query. 

Hence I propose to add a `FilteredArgumentsPrinter` class that allows filtering all arguments and filtering by name matching. 

### A prototype

```graphql
query($string_variable: String!, $input: MyInput!) {
  queryEntry(stringVar: $string_variable, input_object: $input) {
    objectType(moreInlineVar: "my_var", string_var: $string_variable) {
      name 
      booleanDirectiveArgument @skip(if: true)
      customDirectiveArgument @customdirective(inline: "arg", stringVar: $string_variable)
    }
  }
}

```

```ruby
puts GraphQL::Language::FilteredPrinter.new.print(GraphQL.parse(query))
```

```graphql
query($string_variable: String!, $input: MyInput!) {
  queryEntry(stringVar: $string_variable, input_object: $input) {
    objectType(moreInlineVar: "<FILTERED>", string_var: $string_variable) {
      name
      booleanDirectiveArgument @skip(if: "<FILTERED>")
      customDirectiveArgument @customdirective(inline: "<FILTERED>", stringVar: $string_variable)
    }
  }
}
```

### The Draft PR 
Prototype PR at #2334 

### Other concerns / Todos
- A filtered query is no longer typed correctly, for example when we replace boolean values with `<FILTERED>`
- Should consider allowing the inlining of declared variables such as `$id`

**Comment by jturkel** [comment]
Would it make sense to drive this off metadata on the argument i.e. somehow tag certain arguments as being sensitive so they're excluded from the query logs?

**Comment by daemonsy** [comment]
A draft PR with the most naive code to do this. 
https://github.com/rmosolgo/graphql-ruby/pull/2334

**Comment by daemonsy** [comment]
@jturkel do you mean matching? For example the `filter_list`

```ruby
GraphQL::Language::FilteredArgumentsPrinter.new(filter_list: [:password, :token]).print(query)
```

**Comment by jturkel** [comment]
I was imagining something like this:

```ruby
class Mutations::SetCredentials < Mutations::BaseMutation
  argument :username, String, required: true
  # Marking the argument as sensitive prevents it from showing up in query logs
  argument :password, String, required: true, sensitive: true

  field :errors, [String], null: false

  def resolve(username:, password:)
    # ...
  end
end
```
One of the great things about GraphQL is the type system so it would be awesome if it could be leveraged for stuff like this :)

We could always create a generic sanitization framework with hooks to check if a given argument value should be redacted or not. That could easily support multiple strategies but it might be overkill.

**Comment by daemonsy** [comment]
I like this idea, it makes a lot of sense! I had a similar idea originally before writing the code. 

I was hoping though to make the filtering simple by not depending on the Schema, hence the initial prototype did it at the with a generic query. 

Let me research what it would take to bring in the schema.

**Comment by daemonsy** [comment]
I guess as the you're walking down the `print_field` level, you can use that to check against the `sensitive` flag, like the [gist](https://gist.github.com/rmosolgo/3452d2bf98837381df25949498e78e79#file-query_printer-rb-L85) @rmosolgo provided.

This is a bigger feature though, if we went down this approach, ideally it should be part of the `GraphQL::Schema::Argument` class.

**Comment by daemonsy** [comment]
After toying with it a little more, @jturkel, it feels much more involved to do it at the field definition level, where now the schema is involved. For that, I'd like to submit a RFC for that with more thought around data filtering. 

I'm inclined to just do a simple printer for now that redacts all scalars, hence it solves the simpler use case of stringifying a valid graphql query without values first.

**Comment by jturkel** [comment]
Makes sense. I didn't realize that the `GraphQL::Language::Printer` didn't have access to the schema which makes my suggestion much more involved.
