### ISSUE TITLE
Dependent connection types

### ISSUE THREAD

**Issue by v-kolesnikov** [rmosolgo/graphql-ruby#2336]
How to specify "connection" type in that case?

```ruby
# types/book.rb
module Types
  class Book < GraphQL::Schema::Object
    field :genres, Types::Genre.connection_type, null: false
  end
end

# types/genre.rb
module Types
  class Genre <  GraphQL::Schema::Object
    field :books, Types::Book.connection_type, null: false
  end
end
```

It will raise an error, because of circular dependency.

If I use type names (as mentioned here #1929), it will break "connection" feature.

```ruby
# types/book.rb
module Types
  class Book < GraphQL::Schema::Object
    field :genres, "Types::Genre", connection: true, null: false
  end
end
```

So, how I can have two related connection types that includes each other?

**Comment by rmosolgo** [comment]
How about making a manual connection type, for exapmle 

```ruby 
# app/graphql/types/genre_connection.rb 
# TODO: make your own base class 
class Types::GenreConnection < GraphQL::Types::Relay::BaseConnection 
  node_type(Types::Genre) 
end 
```

Then 

```ruby 
field :genres, Types::GenreConnection, null: false 
```

Does that still raise an error? If so could you please share the full message and backtrace?

**Comment by v-kolesnikov** [comment]
`GraphQL::Types::Relay::BaseConnection.node_type` does not accept any argument.

I think you mean it: https://graphql-ruby.org/relay/connections.html#connection-types. No so elegant, but at least it works.

**Comment by v-kolesnikov** [comment]
@rmosolgo Thank you for help!
