### ISSUE TITLE
Should startCursor and endCursor be ID instead of String?

### ISSUE THREAD

**Issue by cabello** [rmosolgo/graphql-ruby#2338]
Hi 👋 

I am wondering if `startCursor` and `endCursor` should be type of ID instead of String, from Relay docs and other cursor based pagination suggestions I see that value as being opaque and not human readable.

https://github.com/rmosolgo/graphql-ruby/blob/73ac09cb95a0b03b3f00c09921b65534f66d0ae6/lib/graphql/types/relay/page_info.rb#L15-L19

The description for String is:
> The String scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.

While the description for ID is:
> The ID scalar type represents a unique identifier, often used to refetch an object or as key for a cache. The ID type appears in a JSON response as a String; however, it is not intended to be human-readable. When expected as an input type, any string (such as "4") or integer (such as 4) input value will be accepted as an ID.

Am I being pedantic?

Thanks for this awesome gem 💜

**Comment by rmosolgo** [comment]
Hi, good question. The Relay specification gives some flexibility: 

> An “Edge Type” must contain a field called cursor. This field must return a type that serializes as a String; this may be a String, a Non‐Null wrapper around a String, a custom scalar that serializes as a String, or a Non‐Null wrapper around a custom scalar that serializes as a String.

(https://facebook.github.io/relay/graphql/connections.htm#sec-Cursor)

So, I think `String` is definitely appropriate, but `ID` would also be appropriate. 

If you want to customize it, you can override the `page_info` field in your own Connection base class. Here's the default implementation: 

https://github.com/rmosolgo/graphql-ruby/blob/2bf7dcd2e206a5602909fd2e6ae17436bff78ae6/lib/graphql/types/relay/base_connection.rb#L100

If you make a custom subclass of `Types::Relay::BaseConnection` for your app's connections, then you could override this field to use a custom PageInfo type, for example: 

```ruby 
field :page_info, MyCustomPageInfo, null: false, ... 
```

Please do open an issue if that doesn't work properly; I certainly expect it to. In 4 years, this is the first mention I've heard of using non-Strings for cursors, so I'm not inclined to change the default without more popular support and trial in production by those who are in favor. If you're reading this and would like to see the default changed, please try the customization above and leave a comment!
