### ISSUE TITLE
Weird `AssignConnection` leakage

### ISSUE THREAD

**Issue by gjtorikian** [rmosolgo/graphql-ruby#234]
Suppose you have a `connection` defined on your root query. If you list the fields off of this root query, you get an interesting extra object:

```
$ Schema.types["RootQuery"].fields.keys
> ["node", "viewer", "connection", "GraphQL::Define::AssignConnection"]
```

I'm not sure what `GraphQL::Define::AssignConnection` is. It doesn't _seem_ to be exposed when trying to make requests to the GraphQL server, so is it harmless?

**Comment by gjtorikian** [comment]
Just realized this becomes a minor public annoyance if you try to list the schema:

``` graphql
{
  __schema {
    queryType {
      fields {
        name
        description
      }
    }
  }
}
```

Let's say you have a connection defined with `connection :foo`. `foo` appears twice in that list—presumably, taking over `GraphQL::Define::AssignConnection`.

**Comment by rmosolgo** [comment]
🙀 whatna world ...
