### ISSUE TITLE
snake case arguments coming through as nil or set defaults 

### ISSUE THREAD

**Issue by ChrisLusted** [rmosolgo/graphql-ruby#2348]
**Versions**
Graphql 1.9.6 (latest)
Ruby 2.5.0p0
Rails 5.2.1

**Issue**
i’m having an issue with using snake cased arguments, similar to this issue - https://github.com/rmosolgo/graphql-ruby/issues/2315 although I am using a method and not the older style resolve proc. It doesn’t seem to pull through snake cased arguments properly, unless i’m doing something wrong. I can access arguments like `page` but something like `sort_column` doesn’t get passed into the args hash. I've followed the docs and can't see that i've set this up incorrectly.

```
module Types
  class QueryType < Types::BaseObject
    # Add root-level fields here.
    # They will be entry points for queries on your schema.

    # TODO: remove me
    field :viewer, UserType, null: true, description: "The signed in user"
    def viewer
      context[:current_user]
    end

    field :orders, [OrderType], null: true, description: "Orders list" do
      argument :page, Int, default_value: 1, required: false
      argument :limit, Int, default_value: 25, required: false
      argument :sort_column, String, required: false, default_value: 'created_at'
      argument :sort_direction, String, required: false, default_value: 'asc'
    end

    def orders(**args)
      Rails.logger.debug "args -- #{args}"
      Order
        .ordered(args[:sort_column], args[:sort_direction])
        .page(args[:page])
        .per(args[:limit])
    end
  end
end
```

output of the args log just shows the defaults for sort arguments `args -- {:page=>1, :limit=>1, :sort_column=>"created_at", :sort_direction=>"asc"}`

```
query orders($page: Int, $limit: Int, $sortColumn: String, $sortDirection: String) {
  orders(page: $page, limit: $limit, sortColumn: $sortColumn, sortDirection: $sortDirection) {
    id
    orderNumber
  }
}

# variables
{
  "page": 1,
  "limit": 1,
  "sortColumn": "updated_at",
  "sortDirection": "desc"
}
```

I can get this working by setting the camelize option on the argument to false and calling the GraphQL query like so, but I wonder if this is a bug or if i'm doing something obviously wrong?

```
##args
argument :sort_column, String, required: false, camelize: false
argument :sort_direction, String, required: false, camelize: false

##query
query orders($page: Int, $limit: Int, $sort_column: String!, $sort_direction: String!) {
  orders(page: $page, limit: $limit, sort_column: $sort_column, sort_direction: $sort_direction) {
    id
    orderNumber
  }
}

##variables
{
  "page": 1,
  "limit": 1,
  "sort_column": "updated_at",
  "sort_direction": "desc"
}
```

**Comment by rmosolgo** [comment]
Hi! Sorry about the hangup. I tried to replicate the issue but couldn't. Here's the script I wrote: 

```ruby 
# __camelize_test.rb
require "graphql"
puts "GraphQL-Ruby " + GraphQL::VERSION

class QueryType < GraphQL::Schema::Object
  field :orders, String, null: true, description: "Orders list" do
    argument :page, Int, default_value: 1, required: false
    argument :limit, Int, default_value: 25, required: false
    argument :sort_column, String, required: false, default_value: 'created_at'
    argument :sort_direction, String, required: false, default_value: 'asc'
  end

  def orders(**args)
    args.inspect
  end
end

class Schema < GraphQL::Schema
  query(QueryType)
end

query_string = "
query($page: Int, $limit: Int, $sortColumn: String, $sortDirection: String) {
  orders(page: $page, limit: $limit, sortColumn: $sortColumn, sortDirection: $sortDirection)
}"

variables = {
  "page" => 1,
  "limit" => 1,
  "sortColumn" => "updated_at",
  "sortDirection" => "desc",
}

result = Schema.execute(query_string, variables: variables)
pp result.to_h
```

And when I ran it, I got the _expected_ variable values in arguments: 

```
~/code/graphql-ruby $ ruby __camelize_test.rb
GraphQL-Ruby 1.9.6
{"data"=>
  {"orders"=>
    "{:page=>1, :limit=>1, :sort_column=>\"updated_at\", :sort_direction=>\"desc\"}"}}
```

If you run that script locally, do you get the same result? I mean, does the script I posted work for you? 

Here's some other information that might help debug: 

- How are you executing this code? Is it in a controller, or in a unit test? Could you share the code? If you `p variables` before running the query, what comes out in Ruby's log? 
- Also, we can debug the variables from _inside_ `def orders`. Could you add a `pp context.query.variables.to_h` to the resolve method, to see what _it thinks_ the variables are? 

Those will help  show where it's getting confused!

**Comment by ChrisLusted** [comment]
Thanks for the quick reply @rmosolgo. Your example does work for me and i've created a new dummy app to test it out quickly and it seems to work there also. 

Happy to close this as it's not a libray issue, it's something in this app that is stopping it working.

Thanks for the help.
