### ISSUE TITLE
Generic mutations for Interfaces

### ISSUE THREAD

**Issue by Fleick** [rmosolgo/graphql-ruby#2357]
Hey together, 
I am currently working on the following Problem:
I have a Person STI with the specific Types Customer, Employee and Lecturer. They mostly have the same fields, but additionally some specific assigns. For the Queries I used an Interface, no Problem so far. But what about the Mutations, is it really necessary to write an own CRUD-Mutations for every Type? Especially as I have the same Issue for an MTI with many and over 90% the same fields. Therefore it would be much copy and paste to write own Mutations and attributes for every Type. Especially it would be much refactoring if fields in the abstract Models would change - with many room for failures.
In discussion with a colleague we have had the idea to use a generic Mutation with an attributes for the common fields an specific attributes for the specific fields like this:

argument :people_fields, ...
argument :customer_fields, ...
argument :employee_fields, ...
argument :lecturer_fields, ...

and then look in the mutation with specific fields are set or add an additional enum argument to set the type. With this, we would only need one instead of 3 Mutations and a change in the common fields would be possible with less work and error-potencial.
But in my research i could not find any example using a pattern like this, but using own mutations for every type. So my question, is there anything we have forgotten, which would speak against this solution? The only thing we could think about is that in common to Rails Controllers every Mutation should only refer to one Model, but we would say, in this case the extra work an error potential would justify such an infringement. What do you guys think? And are there any future plans to make it possible to use something like the interfaces for fields although for arguments?

**Comment by rmosolgo** [comment]
Hi, thanks for the great question! 

It sounds like you have a "template" mutation with several "concrete" implementations. Mutation classes play nicely with inheritance, so how about making one abstract, parent class, then three (or four?) concrete child classes. You could use class methods for setting up those type-specific arguments. 

For example, you might have:

```ruby 
class Mutations::AbstractUpdatePerson 
  # This method generates the field input 
  def self.fields_argument(name) 
    self.argument(name, UpdatePersonInput, required: true) 
  end 
end 

# Then, a concrete subclass: 

class Mutations::UpdateLecturer 
  # This adds `argument :lecturer_fields` with the configuration from that method above. 
  fields_argument(:lecturer_fields) 
end 
```

Then, you could use the parent class for any shared behavior, and put the context-specific code in each concrete class. 

I hope that helps! Please let me know how it goes if you give it a try.

**Comment by meddMeddinski** [comment]
Hello @rrmosolgo,
I'm the coworker @fleick mentioned. Thank you very much for your answer, it really helps mitigating redundant arguments. I hope I understand correctly, but am I wrong that I would still need a concrete implementation for every subtype mutation? In that case, it would mean that we would still have to implement UpdateLecturer, UpdateCustomer, UpdateEmployee, CreateLecturer..., and so on, while a lot of information and processes would be duplicated inside of the concrete queries, and also would upscale the amount of mutations to be implemented in both BE and FE significantly.
We played around with the idea of having one entrypoint for the parent entity (in this case person) and from there mapping to the correct implementation, inspired by the way a query would interface attributes and the respective orphan type attributes, only that in the mutation probably the help of service workers would be required. Would that be something worth investigating further, or are we totally wrong with that idea? 
Thanks a lot for your help, really appreciated

**Comment by rmosolgo** [comment]
> having one entrypoint for the parent entity

Yes, I bet that approach is worth exploring further as well! 


Another approach to creating concrete  classes is to make them on the fly. For example, adding a class method to _make subclasses_: 

```ruby 
# Returns a mutation for the given class 
def self.mutation_for(person_class)
  Class.new(self) do 
    fields_argument("#{person_class.name.underscore}_fields")
  end 
end 
```

Then hooking it up as-needed:

```ruby 
field :update_lecturer, mutation: Mutations::AbstractUpdatePerson.mutation_for(Lecturer)
field :update_customer, mutation: Mutations::AbstractUpdatePerson.mutation_for(Customer)
```

Just another thought!

**Comment by meddMeddinski** [comment]
i think that might be exactly what we need, thanks a lot! we will definitely discuss this
