### ISSUE TITLE
Document "slicing" API idea

### ISSUE THREAD

**Issue by josh** [rmosolgo/graphql-ruby#236]
Hey @rmosolgo!

I have another API *we're* using and I wanted to ask you think it's worth upstreaming to graphql-ruby core.

When working with a single monolith document with all the operations and fragment definitions, its useful to extract slices of the document given a root operation and pulling in all its fragment definitions.

For an example:

``` ruby
document = GraphQL.parse <<-'GRAPHQL' 
query FooQuery { ...FooFragment }
query BarQuery { ...BarFragment }
query BazQuery { ...BarFragment }
mutation FooMutation { ... }
fragment FooFragment on Foo { ... }
fragment BarFragment on Bar { ... }
GRAPHQL

sliced_document = slice(document, operation_name: "FooQuery")
sliced_document == <<-'GRAPHQL'
query FooQuery { ...FooFragment }
fragment FooFragment on Foo { ... }
GRAPHQL
```

Where `sliced_document` is the minimal set of definitions to fulfill the `FooQuery` operation.

With Relay 2 and an attempt to standardize persisted queries, executing operations on large documents will become more common than always posting small queries in production environments.

I have two use cases for this sort of algorithm:

1. If client maintains a concatenated document of all its queries, it may prefer sending a minimal slice of the operation definition to minimal the size of the request body. Rather than sending the entire document every time and specify an operation name parameter.

``` ruby
http_request("POST", "https://example.com/graphql?operation=FooQuery", body: large_document)

# post small document slice instead
small_document = slice(large_document, operation_name: "FooQuery")
http_request("POST", "https://example.com/graphql", body: small_document)
```

2. If the server supports persisted queries, it will likely be storing large GraphQL documents. To aid server error debugging and reporting, the server may want to dump a smaller query in its logs that is sufficient to reproduce the error.

``` ruby
operation_name = request.params["operation_name"]
document = load_document_from_database(request.params["document_id"])

# add simplified document to our exception reporter so we know what original
# query caused the exception.
AppErrorContext.push query: slice(document, operation_name).to_query_string

query = GraphQL::Query.new(MySchema, document: document, operation_name: operation_name)
query.result
```

The gist of the algorithm recursively walks from the operation to any fragment spreads, then each fragment dependency, all of its fragment dependencies.

I was also wondering if this process was already encoded somewhere in the query executor (I assume it does a similar thing) and could be exposed as a public API.

Ha, well, even if it doesn't belong in this lib, hopefully you find this use case interesting.

**Comment by rmosolgo** [comment]
Yes, very interesting! I'm not using persisted queries yet but I think it's one of the best possibilities with GraphQL. 

The analogous part of the current code is `InternalRepresentation::Rewrite`. It takes a document as input (actually, it visits the document while static validation is happening) and builds up a tree of `InternalRepresentation::Node`s. This rewrite does a few things: 

- It "inlines" fragment spreads: fields inside a spread are merged with fields outside the spread, but they get a type condition from their spread (and maybe directives from the spread)
- When a field would be selected on two types, it creates a _single_ `Node` with type condition of "type 1 or type 2" (`Node#definitions` contains `{ Type => field_defn }` pairs which serve as type conditions: only a type which is a key in that hash may resolve this field.)
- Returns a hash of `{ operation_name => tree_of_nodes }` -- where each value is _roughly_ the result of `slice` above. 

However, there's no mechanism for serializing this structure, so storing it in the database is iffy. (Ok, I'm not experienced with `Marshal`, can it be applied here?)

In any case, I this supporting this use case (pile all the GraphQL together, then sort out independent operations) one way or another is great, and I'm happy to support it in the gem.

**Comment by josh** [comment]
> However, there's no mechanism for serializing this structure, so storing it in the database is iffy. (Ok, I'm not experienced with Marshal, can it be applied here?)

We have got that far either, but I would imagine the original raw query string would be stored in a database, then we could cache an IR for each document/operation_name pair in memcache.

So maybe making the IR `InternalRepresentation::Node` class more "public" so you could grab it and pass it back in to an execute function. `Marshal` is legit, but we probably need to test and ensure the default serialization works as expected. Otherwise its something we could improve here.

> In any case, I this supporting this use case (pile all the GraphQL together, then sort out independent operations) one way or another is great, and I'm happy to support it in the gem.

Awesome! Alright, I've already got something written internally already. Maybe I'll just post that up as a PR and figure out how it would best fit into this gem.

I'll close out this discussion for now. Thanks!
