### ISSUE TITLE
GraphQL cannot parse some characters

### ISSUE THREAD

**Issue by borenho** [rmosolgo/graphql-ruby#2360]
I am setting up end to end tests, but GraphQL throws a Parse Error when it encounters a dot (.) in any of the attributes, eg on `gmail.com` - `{"errors"=>[{"message"=>"Parse error on \".\" (error) at [5, 21]", "locations"=>[{"line"=>5, "column"=>21}]}]}`.

This is my query string:

```
    59 def query(attributes:)
    60     <<~GRAPHQL
    61       mutation {
    62         register(
    63           firstName: #{attributes[:first_name]}
    64           lastName: #{attributes[:last_name]}
    65           email: #{attributes[:email]}
    66           password: #{attributes[:password]}
    67         )
    68       }
    69     GRAPHQL
    70   end
```
`

**Comment by daemonsy** [comment]
Hi @borenho  I believe you using the `register()` with a list of args. The syntax doesn't look correct for the arguments list. Here's an example. 

```ruby
mutate = <<~GQL
  mutation {
    register(firstName: "Damon", email: "me@example.com") {
      id
    }
  }
GQL
```

Notice `me@example.com` is quoted like `"me@example.com"`. 

Also a suggestion, using variables make string interpolation much easier. 

```ruby
mutate = <<~GQL
  mutation($first_name: String!) {
    register(firstName: $first_name, email: "me@example.com") {
      id
    }
  }
GQL
```
Then you can pass in `first_name` in the variables hash.

**Comment by rmosolgo** [comment]
Yes, @daemonsy is right, either add quotes: 

```diff 
- firstName: #{attributes[:first_name]}
+ firstName: "#{attributes[:first_name]}"
```

Or use variables like `$firstName`, etc. Hope that helps!

**Comment by borenho** [comment]
Thanks @daemonsy and @rmosolgo! You both are right. Took me a while to figure that out. I did end up using `MySchema.execute(query_string, variables: variables)` though (for I wanted to write integration tests).

I now have 
```
def query_string
  <<~GQL
    mutation register($attributes: Registration!) {
      register(params: $attributes) {
        user {
          firstName
          lastName
          email
       }
         errors
      }
     }
   GQL
end
```

and I'm passing the query variables like so
```
variables = {
       "attributes" => {
         "firstName" => "Ava",
         "lastName" => "Mcclure",
         "email" => "ava.mcclure@gmail.com",
         "password" => "[Omitted]"
       }
     }
```

Resources:
1. https://graphql-ruby.org/testing/integration_tests
2. https://graphql-ruby.org/queries/executing_queries.html
