### ISSUE TITLE
Enum values should not be accepted as IDs

### ISSUE THREAD

**Issue by dani-sc** [rmosolgo/graphql-ruby#2371]
Hi!

Using the [example types of the documentation](https://graphql-ruby.org/getting_started):
```ruby
class QueryType < GraphQL::Schema::Object
  field :post, PostType, null: true do
    argument :id, ID, required: true
  end

  def post(id:)
    "Received request with id: #{id}"
  end
end
```
When using an argument of type ID, a query needs no quotation marks around the ID-value:
```ruby
{ post(id: 1) }

=> Received request with id: 1
```
This also holds true when characters are used as the ID:
```ruby
{ post(id: abc) }

=> Received request with id: abc
```
However, if the ID starts with a number followed by characters, we get an error:
```ruby
{ post(id: 1abc) }

=> #<GraphQL::Query::Result @query=... @to_h={"errors"=>[{"message"=>"Parse error on \"'\" (error) at [1, 15]", "locations"=>[{"line"=>1, "column"=>15}]}]}>
```
We can fix this, if we wrap quotation marks around the value:
```ruby
{ post(id: "1abc") }

=> Received request with id: 1abc
```

Is this behavior expected? If yes, is this documented somewhere?

**Comment by rmosolgo** [comment]
Hi! Thanks for the detailed report. 

Here's the relevant part of the spec: 

> __Input Coercion__
>
> When expected as an input type, any string (such as "4") or integer (such as 4) input value should be coerced to ID as appropriate for the ID formats a given GraphQL server expects. Any other input value, including float input values (such as 4.0), must raise a query error indicating an incorrect type.

(from https://graphql.github.io/graphql-spec/June2018/#sec-ID)

So, I think the case of `abc` as you posted above _should_ be rejected. (It's parsed as an enum value, but ID type requires a string (that is, with quotes) or integer.)

**Comment by dani-sc** [comment]
Good point - thanks for the fast response. In our case, we used string IDs which _sometimes_ start with a number, thus we had some brittle tests. That is why I would be in favor, as you have suggested, of this being handled more restrictively :+1:

**Comment by daemonsy** [comment]
Hi I took a stab at this with https://github.com/rmosolgo/graphql-ruby/pull/2505
