### ISSUE TITLE
Anonymous class should declare a `graphql_name`

### ISSUE THREAD

**Issue by kayn1** [rmosolgo/graphql-ruby#2385]
Got this error being with latest version. 
I have never declared graphql_name and default_graphql_name.
The error raises in controller when my ApiSchema.execute is called
``
     Failure/Error:
        result = ApiSchema.execute(query, variables: variables,
                                          context: context,
                                          operation_name: operation_name)

      NotImplementedError:
        Anonymous class should declare a `graphql_name`
``

**Comment by rmosolgo** [comment]
Hi! Sorry about the hangup. Please reopen with the full stack trace if you want to debug further. 

Check the lines in your stack trace to see if any of them point to `Class.new(...) do ... end` definitions. Inside the definition block, you should add `graphql_name "MyGraphQLType"`, using a String to name the GraphQL type.
