### ISSUE TITLE
Interface/Union PossibleTypes visibility

### ISSUE THREAD

**Issue by grcooper** [rmosolgo/graphql-ruby#2390]
# Problem

I would like a way to change the visibility on types that Unions and Interfaces can be. 

```GraphQL
interface A {
 VALUE
}

type B implements A {
  VALUE
  FOO_VALUE
}

type C implements A {
  VALUE
  BAR_VALUE
}
```

There may be cases where we want to hide that type C implements A in some contexts of an API call, but still allow B to implement A for a different context. Under my current understanding, we can only control visibility of A, so either it is visible through the entire schema or not at all.

# Investigation 
This brought me to investigate how Warden handles Union and Interface visibilities. The common ground seemed to be https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/warden.rb#L173 Which goes into the PossibleTypes class.

Following along with how visibility is currently implemented and to have the correct knowledge of which types to show, we need context injected somewhere here. We have it in the initializer to get the visible interfaces and could store it on `PossibleTypes` to return the correct types.

## Questions
1. How do we know which types to allow in (where do we expose this)
2. Are there other places that possible types might be used
3. Does Union's definition of possible types need to change?

## Possible Solutions
1. This can follow along with how visibility is currently implemented by providing a method like `visible_types(context)` which returns a list of the available types based on the context passed in. By default as to not mess with the current implementation of interfaces, it would return all possible types, but could be overridden on other interfaces.

2. This I am not 100% sure of, but it seems that possible types are used in a few different places. The main place that I believe it will cause issues is in `get_possible_types` methods on interfaces and unions which checks the possible types. For those of you with more knowledge of the codebase know if there are cases where we do not have the context? Or if we need all of the known possible types and not just the visible ones?

3. Question 2 leads into this solution, I believe that the Union's possible_types need to change, and we can then filter out visible types there, which is surfaced in `PossibleTypes`: https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/possible_types.rb#L28. We already seem to have the context when using `get_possible_type` so this might be a better location for this visibility check?

# Summary
I believe we can provide an interface similar to `visible?` but instead provide `visible_types` which only returns the types visible in the current context. This would likely live right on the InterfaceType and UnionType to be used by the `PossibleTypes` class.

Does this seem like a reasonable approach to this problem? Does this conflict with any current thoughts on how to change up how Warden works?

**Comment by rmosolgo** [comment]
Hey @grcooper , thanks for the detailed writeup. We've encountered this issue too and worked around it with hacks. (We shadowed interface `A` with a `SecretA`, and exposed `SecretA` in some cases.) 

I agree that it should support what you're describing ... and I agree it will be a lot of work 🙈 . I don't have a better suggestion than what you wrote, I think those methods will need to be context-aware.

**Comment by grcooper** [comment]
@rmosolgo Ah yah that is a reasonable hack, but is unsustainable for our visibility requirements. If you are ok with this approach then I'll start picking at a solution and get some more feedback once I have some code written.

**Comment by rmosolgo** [comment]
Please give it a go! Feel free to open a PR if you want any :eyes: along the way.

**Comment by rmosolgo** [comment]
I think this is done! Thanks @grcooper  for making this happen.
