### ISSUE TITLE
Handling of max_complexity is not pluggable

### ISSUE THREAD

**Issue by jturkel** [rmosolgo/graphql-ruby#2402]
The runtime is hardcoded to use `GraphQL::Analysis::AST::MaxQueryComplexity` (or `GraphQL::Analysis::MaxQueryComplexity` for the legacy runtime) when either `GraphQL::Schema.max_complexity` is set or the `max_complexity` argument is passed to `GraphQL::Schema#execute`. This forces us to monkey patch `GraphQL::Analysis::AST::MaxQueryComplexity` for a two reasons:

1) We want to return an error that matches our error conventions when the complexity threshold is exceeded
2) We customize the complexity calculation to provide more accurate results for our pagination schema. Unfortunately this can't be done via the `GraphQL::Schema::Field#complexity` callbacks because the paginated field's complexity callback doesn't have access to its individual child fields' complexities.

It would be nice if longer term issue 2 was supported directly by the gem (maybe as part of the pagination rethink if it only comes up there?) but that still leaves issue 1. Would you be open to making this behavior pluggable via a `GraphQL::Schema.max_complexity_query_analyzer` setting that defaults to `GraphQL::Analysis::AST::MaxQueryComplexity` (or `GraphQL::Analysis::MaxQueryComplexity` when using the legacy runtime class)?

**Comment by rmosolgo** [comment]
🤔 

> paginated field's complexity callback doesn't have access to its individual child fields' complexities.

That's not good! It's definitely supposed to be able to apply multipliers to its child values. That's a failure in backwards compatibility if so. 

Thinking bigger: `MaxQueryComplexity` is "just" an AST analyzer. If you're trying to perform a different calculation, how about using a _different_ analyzer? (In fact, GitHub's own "query coster" is not using MaxQueryComplexity, but it's very similar.) Would a custom analyzer be a good fit here, if you want to customize the limit _and_ behavior?

**Comment by jturkel** [comment]
Using our own analyzer sounds like the perfect solution! We're creating multiple GraphQL APIs all of which extend a common base schema so we'd really like something that works with the `GraphQL::Schema.max_complexity` setting and the `max_complexity` argument to `GraphQL::Schema.execute` to avoid developer confusion. Turns out that's pretty easy to do with something like the following:

```ruby
class BaseSchema < ::GraphQL::Schema
  def self.execute(query, max_complexity: self.max_complexity, context: {}, **options)
    # Tuck the requested max_complexity in the context so it can be used by our analyzer 
    context[:max_complexity] = max_complexity
    # Pass a nil max_complexity to prevent graphql-ruby from using that native max complexity analyzer
    super(query, max_complexity: nil, context: context, **options)
  end
end

class Complexity < GraphQL::Analysis::AST::Analyzer
  # Insert fancy complexity calculations here

  def result
    # Stick the complexity in the context so it can be returned in the result
    query.context[:complexity] = complexity

    max_allowed_complexity = query.context[:max_complexity]
    if max_allowed_complexity && complexity > max_allowed_complexity
      # Return an analysis error
    end
  end
end
```
That also avoids computing complexity twice (once for figuring out what to return in the result and once for use in enforcing max complexity with the built-in analyzer) which is a nice side benefit 🎉 

re: Only having access to the total complexity for all child fields - That's what made the optimizations in #2389 possible :) This seems to be the behavior since at least 1.8.7 but it's a non-issue for me since I can use my own analyzer. Perhaps others would benefit from the built-in complexity handling having better handling for the built-in pagination schemes (i.e. it takes into account the `first`/`last` arguments and the fields `max_page_size`)? I'd be happy to file an issue for that if you'd like.

**Comment by jturkel** [comment]
I believe #2409 will simplify my solution a bit by not requiring an override of `GraphQL::Schema.to_graphql` (which will be necessary once #2363 lands) i.e.

```ruby
class BaseSchema < ::GraphQL::Schema
  def self.execute(query, max_complexity: self.max_complexity, context: {}, **options)
    # Tuck the requested max_complexity in the context so it can be used by our analyzer 
    context[:max_complexity] = max_complexity
    # Pass a nil max_complexity so we can use our own max complexity analyzer
    super(query, max_complexity: nil, context: context, **options)
  end
end
```

**Comment by rmosolgo** [comment]
>  the built-in complexity handling having better handling for the built-in pagination schemes 

I agree that would be great! Glad that a custom analyzer worked OK.
