### ISSUE TITLE
Enum may not support `nil` value

### ISSUE THREAD

**Issue by cabello** [rmosolgo/graphql-ruby#2405]
Hello 👋 This is a question / bug report as I couldn't find similar open issues or documentation on this behaviour. 

I was writing a mutation that had an optional field that in the backend that can be set to null, i.e. database column allow for null values.

So my challenge is to differentiate not receiving the input parameter vs receiving it as `nil`.

I "cheated" a bit by creating a symbol default parameter value that can never be set by a GraphQL query and that seems to have worked:

```ruby
module Mutations
  class UpdateBar < BaseMutation
    null true

    argument :name, String, required: true
    argument :foobar, Types::FoobarEnum, required: false

    def resolve(name:, foobar: :not_provided)
      bar = Bar.find_by!(name: name)

      bar.foobar = foobar if foobar != :not_provided
      # ...
```

Unhappy with this solution. I still wanted to explore alternatives as it felt "dirty" to me.

So I introduced the empty Ruby value to the Enum type:

```ruby
module Types
  class FoobarEnum < BaseEnum
    value('FOO', "foo desc", value: 'foo')
    value('BAR', "bar desc", value: 'bar')
    value('UNKNOWN', "unknown desc", value: nil)
  end
end
```

But after adding a debugger breakpoint inside the resolver I got the following behaviour:

```
(byebug) Types::FoobarEnum.coerce_isolated_input('UNKNOWN')
"UNKNOWN"
(byebug) Types::FoobarEnum.coerce_isolated_input('FOO')
"foo"
```

Which may be a surprise? I am not sure what would be the correct behaviour here but by marking the Ruby value explicitly as `nil` I was expecting `UNKNOWN` to be translated into `nil`.

The current behaviour is documented in the tests: https://github.com/rmosolgo/graphql-ruby/blob/5098895eac570db4d76562a859c0f9da02b9770e/spec/graphql/enum_type_spec.rb#L7-L14

So the question remains: how differentiate not receiving a input parameter vs receiving it as `nil`?

Thanks for taking the time to read and answer this question 🙏

**Comment by rmosolgo** [comment]
Hi! Great question. 

I think the two approaches you described are both good. Personally, I'd use the first one with a default value that means "nothing was passed here".  (Gasp, you'll find the same thing in the [graphql-ruby source](https://github.com/rmosolgo/graphql-ruby/blob/1c95c917837491e8350e94a18c3f9c4d3f22bc9b/lib/graphql/schema/argument.rb#L9) 😆 !) 

In the second approach, I think it would work, but you'd have to use a truthy Ruby value for `value:`, like `value: :unknown`. Maybe the code could be improved to distinguish between `value: nil` and no-value-given, but apparently it doesn't support that now, and I'm not sure it's really worth supporting. 

Would one of those other options work in your case?

**Comment by daemonsy** [comment]
Hi, I see a :+1: on Robert's comment from @cabello , going to close this.
