### ISSUE TITLE
How do we check if an argument was supplied instead of checking nil?

### ISSUE THREAD

**Issue by jchatel** [rmosolgo/graphql-ruby#2408]
I'd like to implement a "put-like" mutation. That is: to update some fields only if present in the call. However, nil is a valid value to set a field to, so I can't rely on an argument being nil or not.

Like here:
https://medium.com/workflowgen/graphql-mutations-partial-updates-implementation-bff586bda989

At the moment, my fields are all like

`argument :something, String, required false, null: true`

But then if it's not provided at all I need to still give it a default value in resolve function or it won't execute.

`def resolve(seomthing: nil)`

What can I do to check if it was provided in the mutation call or not, instead of set to nil?

**Comment by jturkel** [comment]
We've used two patterns to handle this:

```ruby
# Capture args with a double splat
def resolve(**options)
  if options.include?(:something)
    # do something
  end
end

# Use a method level default that won't overlap with user specified values
def resolve(something: :unspecified)
  unless something == :unspecified
    # do something
  end
end
```

**Comment by jchatel** [comment]
I was thinking about the :unspecific, for number types, this could be problematic

We are thinking about array of key/value pair and some cool ninja trick

```
def foo(arg1, arg2 = (arg2_not_passed = true; "bar"))
  puts arg1
  puts arg2
  puts 'arg2 was passed' unless arg2_not_passed
end
```

But was hoping to have something natively supported here

**Comment by rmosolgo** [comment]
Personally I use the plain-Ruby techniques that @jturkel shared above. Let me know if one of those doesn't work for you!
