### ISSUE TITLE
Persisted queries with Relay and sync

### ISSUE THREAD

**Issue by sgwilym** [rmosolgo/graphql-ruby#2412]
It seems that the implementation for deriving persisted queries from Relay graphql.js files may now be broken, as Relay queries no longer embed a relayHash in their artefacts.

The default export of *.graphql.js files does have a `node` property on it which I think is analogous to relayHash, but there's one wrinkle: `relay-compiler` supports language plugins which can change its output (the most commonly used one is Typescript artefacts with https://github.com/relay-tools/relay-compiler-language-typescript). But theoretically, they could be any format, so graphql-ruby shouldn't be able to make any kind of assumption about what they are at all.

Fortunately there does seem to be a more direct way: when relay-compiler is passed the `--persist-output` flag, it also generates a JSON file mapping IDs to queries. I think it would be much better to make `sync` use this JSON, though this may require changing the names of some argument to make it make sense!

For convenience, here's the link to Relay's current documentation regarding persisted queries: https://relay.dev/docs/en/persisted-queries

**Comment by rmosolgo** [comment]
Hi, thanks for opening this issue! I didn't this change before, it looks like it came in 2.0.0 back in January: https://github.com/facebook/relay/pull/2354

I agree `--persist-output` looks like a perfect fit! I think we could add a new option that reads from that file instead of gathering up `.graphql` files.

**Comment by sgwilym** [comment]
Great! Another thought: as Relay also alters it's own static artefacts when using `--persist-output` to omit the query text, I wonder if it's necessary to use the generated OperationStoreClient at all, as all you need to do is [change your network layer to send operation IDs now stored on those artefacts](https://relay.dev/docs/en/persisted-queries#network-layer-changes).

**Comment by rmosolgo** [comment]
👌 That's a great point! We just need to push queries to the server.
