### ISSUE TITLE
Guide: Definition

### ISSUE THREAD

**Issue by jdpaterson** [rmosolgo/graphql-ruby#2413]
Typo in this line: 

> It receives a unique ID and must return the object for that ID, or nil if the object isn’t found (_**or if the should be**_ hidden from the current user).

[https://graphql-ruby.org/schema/definition#object-identification-hooks]()

**Comment by rmosolgo** [comment]
Thanks for reporting this. Fixed in https://github.com/rmosolgo/graphql-ruby/commit/67417f44d8aa3a955477fddc34882620c2847967!
