### ISSUE TITLE
Elasticsearch search_after

### ISSUE THREAD

**Issue by enthusiasmus** [rmosolgo/graphql-ruby#2417]
### Questions
How could one implement navigation with graphql combined with elasticsearch? We are already using the search_after feature of elasticsearch (https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html#request-body-search-search-after) in our project, but now we want to allow also the graphql users to navigate via `after` through our products. So my questions are: 
1. How can I receive the cursor value of the `after` argument from the query below?
2. Where can I place a hook to transform the cursor to the matching `search_after` for elasticsearch values?

### Code
```
module Graphql
  class Queries < ::GraphQL::Schema::Object
    field :product_search, ::Graphql::Products::ProductSearchType, null: false do
      argument :keywords, String, "The search string for finding products", required: false
    end

    def product_search(**args)
      { products: Searcher::Elasticsearch.new(args).retrieve_products }
    end
  end
end
```
```
module Graphql
  module Products
    class ProductSearchType < ::GraphQL::Schema::Object
      field :products, ::Graphql::Products::ProductType.connection_type, null: false
    end
  end
end
```
### Query
```
{
  productSearch(keywords: "shirt") {
    products(after: id) {
      nodes {
        id
      }
    }
  }
}
```
### Further Infos
Gem-Version: 1.9.9
Ruby-Version: 2.6

Thanks in advance for any answer!
Best regards,
Lukas

**Comment by rmosolgo** [comment]
In short, you want to make a custom connection (https://graphql-ruby.org/relay/connections.html#custom-connections) for your Search object. It would be very similar to the built-in `RelationConnection`, and it would automatically wrap instances of `Searcher::Elasticsearch`, for example. 

Just like when your application returns an AR::Relation, you could return a search object from a resolver or method. The search object would be initialized with some of the parameters, like `keywords`, `query`, etc. 

Then, GraphQL-Ruby matches the application object (a search object, in this case), with a connection wrapper (you'd write a custom one in this case). It wraps the application object with the connection, and the connection object is initialized with first/after/last/before. The connection object manipulates those inputs (eg, converting an `after` cursor into a useful value) and adds those parameters to the underlying search object. Finally, the connection wrapper uses the search object to make an external service call and return some results. Those results are the `nodes` (or `def edge_nodes`, IIRC) for the connection. 

The connection wrapper also implements `def page_info` for the `pageInfo` field, which may be based on the return from the external service call.

Finally, if you don't want a re-usable connection wrapper, another option is to pass `connection: false`, and implement the connection arguments by hand, then perform pagination etc inside `def product_search`.

I hope this helps! Let me know if you have trouble with one of those approaches.
