### ISSUE TITLE
GET /graphql

### ISSUE THREAD

**Issue by lifeiscontent** [rmosolgo/graphql-ruby#2423]
does graphql ruby support this?

https://www.apollographql.com/docs/apollo-server/v1/requests/#get-requests

allow `queries` but not `mutations` on a GET request.

**Comment by rmosolgo** [comment]
Hi! You could implement this with two steps. First, include the HTTP method in your GraphQL context (in the controller, for example): 

```ruby 
context = {
  # ... 
  http_method: request.method, 
}
result = MySchema.execute(query, context: context, ...)
```

Then, add a [query instrumenter](https://graphql-ruby.org/queries/instrumentation) that checks for a valid combination of http_method and operation type:

```ruby
class AllowGetQueries 
  def before_query(query) 
    case query.context[:http_method].downcase
    when "post" 
      # Allow any query 
    when "get" 
      if !query.query? 
        raise GraphQL::ExecutionError, "Only queries are allowed in GET requests" 
      end 
    else 
      raise "Unexpected context[:http_method]: #{query.context[:http_method].inspect}" 
    end 
  end

  def after_query(_q); end  
end 
```

And add it to your schema: 

```ruby 
class MySchema < GraphQL::Schema
  instrument(:query, AllowGetQueries.new) 
end 
```

I hope that works for you! Feel free to reopen this if not.
