### ISSUE TITLE
Directives and argument conflict behavioural difference in v1.8.x vs v1.9.x

### ISSUE THREAD

**Issue by dteoh** [rmosolgo/graphql-ruby#2426]
Consider the following query:

```gql
query Q($yes: Boolean!) {
  users(first: 1) @include(if: $yes) {
    nodes {
      id
      name
    }
  }
  users(first: 2) @skip(if: $yes) {
    nodes {
      id
      name
    }
  }
}
```

Variables:

```json
{ "yes": true }
```

In version 1.8.11, this query generates no issues. When `yes` is `true` you get back one user, when `yes` is `false` you get back two users. However in version 1.9.9, we now get this error:

```json
{
  "errors": [
    {
      "message": "Field 'users' has an argument conflict: {first:\"1\"} or {first:\"2\"}?",
      "locations": [
        {
          "line": 562,
          "column": 3
        },
        {
          "line": 568,
          "column": 3
        }
      ],
      "path": [],
      "extensions": {
        "code": "fieldConflict",
        "fieldName": "users",
        "conflicts": "{first:\"1\"} or {first:\"2\"}"
      }
    }
  ]
}
```

I've tried this query both with the new interpreter (`use GraphQL::Execution::Interpreter` + `use GraphQL::Analysis::AST`) and the original interpreter. I don't see anything in the 1.9.x changelog which suggests that this is an intended breaking change, so I think this is a bug?

**Comment by dteoh** [comment]
I lean towards v1.9.x behaviour being wrong or at least incomplete or over-eager in the case that I've presented. The query and variables are submitted to the runtime in a single package. On encountering the directives, it can already determine if the associated field or fragment should form part of the query to execute. Fields or fragments that are not part of the final query should be ignored.

Personally I don't think these sort of conditionals should have been added to the GraphQL spec in the first place (with the resulting behaviour left as implementation defined), but now that we have clients built on top of v1.8.x's behaviour (and who can blame the devs, the runtime accepted it and produced the desired results), upgrading the gem is difficult because we cannot revoke clients.

It would be really great to see v1.8.x's behaviour restored, so that we can get access to v1.9.x's performance improvements.

**Comment by rmosolgo** [comment]
The updated spec still makes no mention of directives in this scenario: https://spec.graphql.org/October2021/#sec-Field-Selection-Merging

> -  Let set be any selection set defined in the GraphQL document.
> - FieldsInSetCanMerge(set) must be true.
>
> - __FieldsInSetCanMerge(set)__
>     - Let fieldsForName be the set of selections with a given response name in set including visiting fragments and inline fragments.
>     - Given each pair of members fieldA and fieldB in fieldsForName:
>        - SameResponseShape(fieldA, fieldB) must be true.
>        - If the parent types of fieldA and fieldB are equal or if either is not an Object Type:
>            - fieldA and fieldB must have identical field names.
>            -  fieldA and fieldB must have identical sets of arguments.
>            - Let mergedSet be the result of adding the selection set of fieldA and the selection set of fieldB.
>            - FieldsInSetCanMerge(mergedSet) must be true.


Given how much time has passed without further difficulty with the current behavior, I plan to leave it as is. Thanks for reporting this issue and sorry it came as a surprise 😖
