### ISSUE TITLE
Arguments dropped when query includes fragments

### ISSUE THREAD

**Issue by fredefox** [rmosolgo/graphql-ruby#2427]
I have run into an issue where the arguments passed into `::GraphQL::Schema.execute` seem to be dropped when the query contains GraphQL fragments.

Unfortunately I can't provide a link to the program exhibiting the problem, but I've tried to boil the problem down.  This should be a minimal setup that exhibits the issue.

Assume we have the following:

```rb
query = <<~GRAPHQL
  fragment T on U {
    y
  }


  query f($x: Int) {
    g(x: $x) {
      ...T
    }
  }
GRAPHQL

variables = {
  x: 1337
}

GraphQL::Schema.execute(query, variables: variables)
```

Now assume that the query type has this field and corresponding resolver:

```rb
field :g, R.connection_type, null: false do
  argument :x, Int, required: false
end

def f(x:)
  puts(x)
  { y: x }
end
```

Where `R` is a type with a single integral field `y`. Note the usage of `.connection_type`. Now, I'd expect the following to print `1337` when executed.  Yet it seems that the arguments do not get passed in when using a fragment. If you, however, change `query` to the equivalent query:

```gql
query f($x: Int) {
  g(x: $x) {
    y
  }
}
```

The arguments are printed correctly.

I *don't* believe that #29 should be related.

I might be able to help fix this. It would be great if you could provide me with pointers on where to look.

**Comment by fredefox** [comment]
I should say as well that I'm using version 1.9.9 of this gem.

**Comment by fredefox** [comment]
It would appear that I will need to do some more digging into the code that I'm working on. I tried to add a test-case exhibiting this issue to the test-suite - but that test-case does not reproduce it...

**Comment by fredefox** [comment]
Maybe I should close this and re-open when I can provide more context. What do you think @rmosolgo?

**Comment by vecerek** [comment]
I'm not sure how the non-fragment query could work in your example. Assuming a type `R` with a single field `y` and the defined query field `g` in the above example, the following query would behave according to your expectations:

```gql
fragment T on R {
  y
}

query f($x: Int) {
  g(x: $x) {
    edges {
      node { ...T }
    }
  }
}
```

Note that using `R.connection_type` will also create 2 extra types as per the Relay specification: `RConnectionType` and `REdgeType`. The `RConnectionType` will have the following arguments added besides the argument `x` declared in the example above: `before`, `after`, `first`,  and `last`. However, these arguments will not be passed down to the resolver of field `g` as named params (unlike `x`). The resolver of the generated `RConnectionType` will take care of the pagination "automagically".

**Comment by fredefox** [comment]
The actual output of the query is `nil`.

Feel free to close the ticket if you think this may be invalid. @vecerek found a fix for what we're working on.
