### ISSUE TITLE
Suggestion: resolve field with method with question mark

### ISSUE THREAD

**Issue by jazzdragon** [rmosolgo/graphql-ruby#2438]
Little sugar suggestion, I'd expect this:
`field :enabled, Boolean, null: false`
to look for the method `enabled?` on the model, especially if it resolves to a boolean.

Thanks!

**Comment by rmosolgo** [comment]
Hi, I'm open to it, but I'm not sure how to roll out that change in a way that doesn't upset existing schemas. 

For the time being, you can implement it in your own base field class: 

```ruby 
def initialize(**kwargs, &block) 
  if kwargs[:type].unwrap.graphql_name == "Boolean" && kwargs[:method].nil? 
    kwrags[:method] = :"#{kwargs[:name]}?" 
  end 
  super 
end 
```

I think something like that would work! 

If you want to add something like this to the gem, please open a PR for it. 

One option to roll this out as default _without_ breaking existing schemas would be to implement the behavior in a Ruby module. Then, we could update the Rails generator to put that module in base field classes by default. That way, new graphql-ruby installations would benefit from the behavior, but existing users could adopt it if/when they see fit. 

Thanks for the suggestion! If you try it out, let me know how it goes.

**Comment by jazzdragon** [comment]
Thanks! will do!

**Comment by jazzdragon** [comment]
I guess that brings me to another question, something I couldn't figure out from the docs:
In `https://graphql-ruby.org/fields/introduction.html#field-parameter-default-values` you show how to create a custom field, but how do you use it? also, how would I override my base field behavior?

Thanks!

**Comment by rmosolgo** [comment]
Use the `field_class MyBaseField` method configuration as shown at the bottom here: https://graphql-ruby.org/type_definitions/extensions.html#customizing-fields

**Comment by aizotov** [comment]
For anyone coming across this in the future, you can resolve it like this
`field :enabled, Boolean, null: false, method: :enabled?`
