### ISSUE TITLE
Custom field class that uses `extras`, incompatible with `GraphQL::Relay::Node.field` as specified by `field:`?

### ISSUE THREAD

**Issue by chrisbutcher** [rmosolgo/graphql-ruby#2440]
Is there a way to customize all fields with custom `extras` for use with an extension? The [recommended way in the guide](https://graphql-ruby.org/relay/object_identification.html#node-field-find-by-uuid) conflicts with anyone using the `field` class option such as `field :node, field: GraphQL::Relay::Node.field`.

It also seems that even if someone is using [`add_field(NodeField)`](https://github.com/rmosolgo/graphql-ruby/blob/1671b91f5d6995c65cad4242c9a932cfaab7b4a7/lib/graphql/schema/member/has_fields.rb#L55) theres no way to set its extras.

```ruby
class FieldWithExtensionAndExtras < GraphQL::Schema::Field
  def initialize(*args, **kwargs, &block)
    kwargs = kwargs.merge(extensions: [MyExtension])

    kwargs[:extras] ||= kwargs[:mutation]&.extras || []
    kwargs[:extras] << :ast_node # 💣

    super(*args, **kwargs, &block)
  end
end

class BaseObject < GraphQL::Schema::Object
  field_class FieldWithExtensionAndExtras
end

class Comment < BaseObject
  implements GraphQL::Relay::Node.interface
  description "A blog comment"

  field :id, ID, null: false
  field :body, String, null: false
end

class QueryRoot < BaseObject
  # NOTE: The following field definition, using `field:` errors out with:
  #   `ArgumentError: keyword `extras:` may only be used with method-based resolve and class-based field such as
  #   mutation class, please remove `field:`, `function:` or `resolve:``
  field :node, field: GraphQL::Relay::Node.field # 💥

  field :comments, [Comment], null: false
end

class Schema < GraphQL::Schema
  query QueryRoot
  use GraphQL::Analysis::AST
end
```

**Comment by rmosolgo** [comment]
Interesting! How about skipping the `extras` addition if `kwargs[:field]` is present? For example: 

```ruby 
class FieldWithExtensionAndExtras < GraphQL::Schema::Field
  def initialize(*args, **kwargs, &block)
    kwargs = kwargs.merge(extensions: [MyExtension])
    if !kwargs[:field]
      kwargs[:extras] ||= kwargs[:mutation]&.extras || []
      kwargs[:extras] << :ast_node # 💣
    end 

    super(*args, **kwargs, &block)
  end
end
```

That would at least side-step it in this case! For a more fine-grained approach, you could add another initialization option to skip the extras, and pass the option when adding `Node.field`. What do you think?

**Comment by swalkinshaw** [comment]
Ideally we should be able to customize *every* field without skipping any like the above case. Skipping the legacy `Node.field` case seems fine, but I don't think there's any way to customize a field added by `add_field` either unless we're missing something.

We can't override `add_field` on object types and set `extras` because `GraphQL::Schema::Field` doesn't expose it like it does with `extensions`. So I think one solution is to forget about the `Node.field` case and add an `#extras` method to set extras after the field is instantiated.

**Comment by rmosolgo** [comment]
Is this more than an edge case? Why use `add_field`?

**Comment by swalkinshaw** [comment]
Isn't that the recommended solution to add the Node field now? It's used throughout the codebase when the new interpreter is used.
