### ISSUE TITLE
ActionCable subscriptions no longer work with new interpreter

### ISSUE THREAD

**Issue by kidcosmic** [rmosolgo/graphql-ruby#2446]
Adding only the line:

```ruby
 use GraphQL::Execution::Interpreter
```
to the schema breaks subscriptions. Clients can connect and everything looks like it works, but logging subscription_ids in `GraphqlChannel` shows no subscriptions.

```ruby
class GraphqlChannel < ApplicationCable::Channel
  def subscribed
    @subscription_ids = []
  end

  def execute(data)
    query = data["query"]
    variables = ensure_hash(data["variables"])
    operation_name = data["operationName"]
    context = {
        current_user: current_user,
        # Make sure the channel is in the context
        channel: self,
    }

    result = RelevntApiSchema.execute({
                                  query: query,
                                  context: context,
                                  variables: variables,
                                  operation_name: operation_name
                              })

    payload = {
        result: result.subscription? ? { data: nil } : result.to_h,
        more: result.subscription?,
    }


    # Track the subscription here so we can remove it
    # on unsubscribe.
    if result.context[:subscription_id]
      @subscription_ids << context[:subscription_id]
    end

    puts "Subscription #{@subscription_ids}"

    transmit(payload)
  end
```
`result.subscription?` is true here, but using the debugger to inspect the ConcurrentHash of subscriptions shows that the hash is empty.
The triggers look like they work fine, but since there are no subscriptions retained, no messages are delivered aside from the first one of `{result: {data: nil}, more: true}`

**Comment by rmosolgo** [comment]
Sorry to hear that! In the gem, we run a Rails system test to test ActionCable: 

https://github.com/rmosolgo/graphql-ruby/blob/master/spec/dummy/test/system/action_cable_subscription_test.rb

We run the test with the interpreter (https://github.com/rmosolgo/graphql-ruby/blob/fce0e54813c4468bb9fa8f0734b9164b20adcdbf/spec/dummy/app/channels/graphql_channel.rb#L54, https://github.com/rmosolgo/graphql-ruby/blob/fce0e54813c4468bb9fa8f0734b9164b20adcdbf/.travis.yml#L23), and it's currently passing. 

I'm not sure how to debug this further, but if you want to look into it, you could create a failing case, like a small Rails app that demonstrates the issue or a failing test in this repository. 

Also, did you add the SubscriptionRoot plugin which is currently required for hte interpreter? You can see it here: 

https://graphql-ruby.org/queries/interpreter.html#installation

Hope that helps!

**Comment by rahilsondhi** [comment]
See https://github.com/rmosolgo/graphql-ruby/issues/2727#issuecomment-584870542 and onward
