### ISSUE TITLE
typename wrong in test env

### ISSUE THREAD

**Issue by jazzdragon** [rmosolgo/graphql-ruby#2449]
Hi,
When running a local rails server with `RAILS_ENV=test` all the `__typename` keys returned are "User", which I assume is just the type of the entry point to the query ("viewer").

Also, if I set `graphql_name` on my type it doesn't affect it at all.

All of this is not happening in my development or production environments. This is breaking our feature tests though.

Thanks!

**Comment by rmosolgo** [comment]
Hi, sorry to hear it! This is not enough information to debug. If you'd like to look into it further, please share some specifics, for example: 

- An example query with the actual response and expected response 
- If the query runs differently in another context, share the response in that other context 
- The test setup for the query and its `.execute` call 

Please reopen this issue if you're able to share any of those details!
