### ISSUE TITLE
[Request] Utility to create aliases with deprecation_reason (when renaming fields)

### ISSUE THREAD

**Issue by gfx** [rmosolgo/graphql-ruby#2460]
I have been maintaining a GraphQL schema for years, and I have renamed some fields with `deprecating_reason` by copy and paste the field definition.

I'm thinking a new feature to define alias with `deprecation_reason` like this:

```ruby
field :foo, ...

deprecated_alias :bar, to: :foo, reason: "This has been renamed to foo. Use foo instead."
```

What do you think of it?

**Comment by rmosolgo** [comment]
Personally, my experience with deprecation is that there is often more to change than just the name, for example, we also need to make one of the arguments required, or we need to change the return type. So, I don't have a use for it. 

But, I think it should be straightforward to implement as a class method, for example:

```ruby 
def self.deprecated_alias(field_name, to:, reason:) 
  other_field = self.fields[to.to_s.camelize(false)]
  # Schema::Field#type contains any nullability constraints, so we can use `null: false` here 
  field(field_name, other_field.type, null: false, deprecation_reason: reason, resolve_method: to) 
end 
```

(It will get harder and harder, the more use cases you have to cover 😬 )

Anyway, let me know if you have trouble implementing it in your app, or if more folks would like to see this in the gem, I'm open to including it!

**Comment by gfx** [comment]
Okay, I'll do it with a custom class method. Thanks for looking at this issue!
