### ISSUE TITLE
PunditIntegration - undefined method `BaseArgument#authorized_by_policy?`

### ISSUE THREAD

**Issue by thornomad** [rmosolgo/graphql-ruby#2464]
Just started working with `graphql-ruby` and the `PunditIntegration` today and ran into an error as I went along with the docs:

```undefined method `authorized_by_policy?' for #<Types::BaseArgument:0x00007fab1252a818>\nDid you mean?  authorized?```

I was able to remedy this by updating my `BaseArgument` to:

```# app/graphql/types/base_argument.rb
class Types::BaseArgument < GraphQL::Schema::Argument

  def authorized_by_policy?(*args, **opts)
    self.authorized?(*args, **opts)
  end

end
```

Not sure if this indicates I set up something incorrectly or indeed the method name changed.  But I thought I would reach out and see.  Thanks!

**Comment by rmosolgo** [comment]
Hi, sorry about the hangup! Did you add the ArgumentIntegration to your base class as described here? https://graphql-ruby.org/authorization/pundit_integration.html#authorizing-arguments

That might add the missing methods. If it doesn't help, could you please share the full error message and back trace?

**Comment by thornomad** [comment]
@rmosolgo - thanks for the quick response.  That was definitely it!

II had been slogging through that page but obviously missed that step.  Appreciate it.
