### ISSUE TITLE
Upgrader fails on splat args in resolvers

### ISSUE THREAD

**Issue by jstrater** [rmosolgo/graphql-ruby#2466]
First of all, thanks for the upgrader utility! It's a great idea for large codebases.

The issue I've encountered is that `rake graphql:upgrade:member` raises an error when it hits a resolver with a splat in the arguments. For example, if I wrote a resolver that only depended on the first argument, and used a splat to ignore the rest, like this:
```
resolve ->(obj, *_) { do_something_with(obj) }
```
then I'd get the following error:
```
TypeError: no implicit conversion from nil to integer
.../gems/graphql-1.9.11/lib/graphql/upgrader/member.rb:538:in `[]'
.../gems/graphql-1.9.11/lib/graphql/upgrader/member.rb:538:in `block in apply'
.../gems/graphql-1.9.11/lib/graphql/upgrader/member.rb:537:in `each'
.../gems/graphql-1.9.11/lib/graphql/upgrader/member.rb:537:in `apply'
.../gems/graphql-1.9.11/lib/graphql/upgrader/member.rb:854:in `apply_transforms'
.../gems/graphql-1.9.11/lib/graphql/upgrader/member.rb:855:in `apply_transforms'
.../gems/graphql-1.9.11/lib/graphql/upgrader/member.rb:855:in `apply_transforms'
.../gems/graphql-1.9.11/lib/graphql/upgrader/member.rb:859:in `apply_transforms'
.../gems/graphql-1.9.11/lib/graphql/upgrader/member.rb:859:in `apply_transforms'
.../gems/graphql-1.9.11/lib/graphql/upgrader/member.rb:859:in `apply_transforms'
.../gems/graphql-1.9.11/lib/graphql/upgrader/member.rb:859:in `apply_transforms'
.../gems/graphql-1.9.11/lib/graphql/upgrader/member.rb:855:in `apply_transforms'
.../gems/graphql-1.9.11/lib/graphql/upgrader/member.rb:855:in `apply_transforms'
.../gems/graphql-1.9.11/lib/graphql/upgrader/member.rb:855:in `apply_transforms'
.../gems/graphql-1.9.11/lib/graphql/upgrader/member.rb:827:in `block in upgrade'
.../gems/graphql-1.9.11/lib/graphql/upgrader/member.rb:826:in `each'
.../gems/graphql-1.9.11/lib/graphql/upgrader/member.rb:826:in `upgrade'
.../gems/graphql-1.9.11/lib/graphql/railtie.rb:103:in `block (5 levels) in <class:Railtie>'
.../gems/graphql-1.9.11/lib/graphql/railtie.rb:103:in `open'
.../gems/graphql-1.9.11/lib/graphql/railtie.rb:103:in `block (4 levels) in <class:Railtie>'
.../gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
.../bin/bundle:23:in `load'
.../bin/bundle:23:in `<main>'
```
From the upgrader source, it appears that `ResolveProcProcessor` is [looking for](https://github.com/rmosolgo/graphql-ruby/blob/3f519a08607944b903e3753d1587e0fbdd5a7ac6/lib/graphql/upgrader/member.rb#L625) exactly three arguments in the AST, which of course it won't find in cases like the one above.

**Comment by rmosolgo** [comment]
Hi, thanks for the detailed report! Are you interested in hunting a fix here? It would look like this: 

- Add a `.original.rb` file to https://github.com/rmosolgo/graphql-ruby/tree/master/spec/fixtures/upgrader which reproduces the bug (with `bundle exec rake test TEST=spec/graphql/upgrader/member_spec.rb`)
- Add a `.transformed.rb` which reflects the _expected_ output 
_ ... monkey with the upgrader until the test passes 😬 

Even if you could share a failing case, I could probably help with the upgrader code. What do you think?

**Comment by rmosolgo** [comment]
Feel free to open a PR with a failing test if you'd like to look into this further!
