### ISSUE TITLE
GraphhQL::Types::JSON returns plain string

### ISSUE THREAD

**Issue by povilasjurcys** [rmosolgo/graphql-ruby#2468]
Maybe I'm missing something, but at the moment JSON type implementation does not make sense for me.

GraphQL JSON type is written as:

```ruby
class JSON < GraphQL::Schema::Scalar
  description "Represents untyped JSON"

  def self.coerce_input(value, _context)
    value
  end

  def self.coerce_result(value, _context)
    value
  end
end
```

so it does not parse value in any form. No validation, no conversion from string to json. What I expect to find is this:

```ruby
  def self.coerce_input(json_str, _context)
    JSON.parse(json_str)
  end
  
  def self.coerce_result(hash, _context)
    JSON.generate(hash)
  end
```

So at the moment I have to call `JSON.parse` in all resolvers where I expect JSON argument. 
My question: is this no-json-parse is intentional or it's a bug after all?

**Comment by rmosolgo** [comment]
@povilasjurcys How did it work when you tried it?

As far as I know, it works as intended. The tests are here: https://github.com/rmosolgo/graphql-ruby/blob/master/spec/graphql/schema/scalar_spec.rb#L46-L99

If you try to use it and find a shortcoming or a bug, please open an issue describing it.

**Comment by semirart** [comment]
@rmosolgo I have the same issue, there is no parsing of json string.

**Comment by rmosolgo** [comment]
> no parsing 

That's right, this scalar doesn't parse strings. Instead, it accepts _any_ GraphQL input data and returns values in _any_ structure. If it receives a string, it passes that string along to the application. If you want a different data structure, either: 


- Provide the input as a non-stringified JSON value (eg, parse JSON in your controller, or get a complext data structure from params); 
- Or, implement a custom scalar that performs the parsing you're looking for 

Hope that helps!
