### ISSUE TITLE
Allow Marshal.dump/load of GraphQL::Schema

### ISSUE THREAD

**Issue by singpolyma-shopify** [rmosolgo/graphql-ruby#2472]
This would be very useful for many default Rails caches, etc.  Just need something like:

```
def _dump(*)
    to_definition
end

def self._load(s)
    from_definition(s)
end
```

**Comment by rmosolgo** [comment]
Ah, yes, I think it's better for your case. If you like, you could also add that to your own schema class, eg 

```ruby 
class DumpableSchema < GraphQL::Schema 
  def _dump ... 
  def self._load ... 
end 

DumpableSchema.from_definition(...)
```

Thanks for sharing!
