### ISSUE TITLE
Best GraphQL client for rails

### ISSUE THREAD

**Issue by simonhutchings** [rmosolgo/graphql-ruby#2475]
Not strictly a issue, but…

I have 2 rails apps i want to do manual syncs on certain parts of data.

Does GraphQL-ruby have a client? What other graphql rails clients are the cleanest and easiest to pull data from the server?

**Comment by daemonsy** [comment]
Hi @simonhutchings assuming you're talking about a Ruby based client. `graphql-ruby` doesn't include a Ruby based client, there are some as https://github.com/github/graphql-client and https://github.com/yuki24/artemis. 

I personally had good success with Artemis on a Rails app. 

If you find any interesting client approaches / issues etc, happy to hear about them (or even a PR to the docs)
