### ISSUE TITLE
Guide: Mutation Classes

### ISSUE THREAD

**Issue by carltonsmith** [rmosolgo/graphql-ruby#2480]
This all looks great, but it should say where the code should go

**Comment by daemonsy** [comment]
Using https://graphql-ruby.org/mutations/mutation_root.html as an example, do you mean having something like a comment for the file? `# In graphql/types/mutation.rb`

```ruby
# In graphql/types/mutation.rb
class Types::Mutation < Types::BaseObject
  # ...
end
```
