### ISSUE TITLE
Guide: Triggers

### ISSUE THREAD

**Issue by genxhero** [rmosolgo/graphql-ruby#2492]
But what about deletion?  What are we supposed to do for a comment DELETION subscription?

**Comment by rmosolgo** [comment]
Hi! I think it would work pretty much the same. Set up a subscription with GraphQL, then while deleting the comment, capture its ID (or whatever you need to call `trigger`), delete the comment, and if the delete succeeds, call `trigger` with the information captured beforehand. 

Please let me know if you give it a try and run into any issues!

**Comment by genxhero** [comment]
Nope that's not the case it immediately tries to find the active record
after it's deleted for some stupid reason

**Comment by rmosolgo** [comment]
Sorry to hear it 😖  If you want to debug further, please share the definition of your subscription, the source for your `.trigger` call, and if your code reaches a Ruby error, please share the full error message and stack trace.

**Comment by genxhero** [comment]
Regarding the trigger I literally tried everything: passing the comment
data prior to destruction, passing an ID, even changing the return format
to GraphQL::Types::JSON (which didnt work).

 field :comment_deleted, Types::CommentType, null: false

def comment_deleted

end

```

JSON version:

module Mutations

class DeleteComment < BaseMutation

include Concurrent::Async

argument :id, Int, required: true

type Types::CommentType

def resolve(id: nil)

comment = Comment.find(id)

post = comment.post

commentor = comment.user

phony = {

id: comment.id,

body: comment.body,

createdAt: comment.created_at,

commentor: {

username: commentor.username,

id: commentor.id

}

}

SwyleSchema.subscriptions.trigger("commentDeleted", {}, phony)

SwyleSchema.subscriptions.trigger("articleUpdated", {}, post)

comment.destroy

post

end

end

end

```


COmment Type version


module Mutations

class DeleteComment < BaseMutation

include Concurrent::Async

argument :id, Int, required: true

type Types::CommentType

def resolve(id: nil)

comment = Comment.find(id)

post = comment.post

comment_copy = comment

SwyleSchema.subscriptions.trigger("commentDeleted", {}, comment_copy)

SwyleSchema.subscriptions.trigger("articleUpdated", {}, post)

comment.destroy

post

end

end

  end

**Comment by genxhero** [comment]
And on the frontend all of the subscriptions are expecting the same type of
data as the index query.

import gql from 'graphql-tag';
import mutation from '../mutations/delete_comment';

const CommentSubscription = gql`
subscription CommentSubscription {
   commentAdded {
    commentor {
      username
      id
    }
    body
    id
    createdAt
   },

    commentUpdated {
      commentor {
      username
      id
    }
    body
    id
    createdAt
   },

   commentDeleted {
      commentor {
      username
      id
    }
    body
    id
    createdAt
   }
}`

export default CommentSubscription;
