### ISSUE TITLE
Actioncable subscriptions trigger payload is stringified

### ISSUE THREAD

**Issue by whereyoubinns** [rmosolgo/graphql-ruby#2499]
Hey! I’m having issues with the graphql subscriptions implementation using actioncable/anycable. 

We’ve successfully added the subscription to the schema and the initial subscription is created. But triggering is causing issues. 

I'm triggering my subscription update using this command: 
![image](https://user-images.githubusercontent.com/49168885/65799371-362bd480-e131-11e9-8d07-129695aeec16.png)

BUT subscription.trigger is stringifying the payload and giving an 
```Uncaught TypeError: Cannot read property 'data' of undefined``` 

ActionCableLink.js expects a hash in a particular form of
```{:result => {:data => “stuff”}, {:more => true} } ```

![image](https://user-images.githubusercontent.com/49168885/65799379-3af08880-e131-11e9-914f-45c1f3a1f46e.png)

From here parsing the payload into JSON totally fixes this issue and the data is broadcasted successfully. 

All other implementations I’ve been looking at seem to just broadcast objects as the payload. So I’m curious if this is a bug or maybe just an error in my implementation.

Any insight is greatly appreciated! 🙌

**Comment by rmosolgo** [comment]
Hi, sorry about the trouble! 

It looks like you're passing a response-like Hash (containing `:data` and `:more`)  into `.trigger`, but instead, you should pass an object from your application into `trigger`. For example, if someone subscribed to new comments on a post:

```graphql
subscription {
  newCommentOnPost(postId: 1) {
     body
  }
}
```

Then, in the Ruby code, we'd call `.trigger` with the newly created comment: 

```ruby 
MySchema.subscriptions.trigger(:new_comment_on_post, {post_id: 1}, comment) 
```

After that, GraphQL-Ruby would take the provided `comment` and begin updating any subscribers who are waiting for `newCommentOnPost(postId: 1)`

Does that help? 

If not, please share an example subscription query from your client, the source code for that subscription in your schema, and the code from your application where `.trigger` is called, then re-open this issue so we can continue debugging.

**Comment by whereyoubinns** [comment]
Thanks for the response! 

I found the problem to lie between `anycable-go` and `ruby-graphql` after finding this issue https://github.com/anycable/anycable-rails/issues/40. 

Using the `graphql-anycable` gem (https://github.com/Envek/graphql-anycable) solved this problem. Needed to use AnyCableSubscriptions instead of the ActionCableSubscriptions 👍
