### ISSUE TITLE
Whitespace parsing issues

### ISSUE THREAD

**Issue by devknoll** [rmosolgo/graphql-ruby#25]
I noticed some minor parsing issues with whitespace… not important now since so far Relay is generating accepted queries, but will become a bigger problem when GraphiQL lands.

Parses fine:
```test(input: {variable: test})```

Fails:
```test(input: { variable: test })```

(This is coming from memory so this might not be exact :smile:)

**Comment by rmosolgo** [comment]
Thanks, found it and fixed it here! https://github.com/rmosolgo/graphql-ruby/commit/e1d89ed921d5b557fd84da6fb3fe9926e096d65f

Please let me know if you come across any others!

**Comment by rmosolgo** [comment]
Also pushed 0.6.2 with this fix
