### ISSUE TITLE
Query Arguments can't differentiate between omitted and null keys

### ISSUE THREAD

**Issue by josh** [rmosolgo/graphql-ruby#250]
``` graphql
query {
  foo
  foo(bar: null)
}
```

It should be possible to differentiate between unset argument keys vs arguments that have an explicit `null` value. But `GraphQL::Query::Arguments` stores both as `nil`.

```
#<GraphQL::Query::Arguments:0x007fd8fb45a340 @original_values={"foo"=>nil}, @argument_values={"foo"=>nil}>
```

I don't think this behavior is clear from the spec, but FB devs say this should be the case.

Its useful to distinguish these keys for mutations when an explicit field can mean "set the value to null" where omitting the key can mean "don't update field".

``` graphql
mutation {
  # project.name = "GraphQL"
  # project.description = nil
  updateProject(input: { name: "GraphQL", description: null })
}

mutation {
  # project.name = "GraphQL"
  # and leave description alone
  updateProject(input: { name: "GraphQL" })
}
```

**Comment by rmosolgo** [comment]
How about mimicking `Hash#key?` #251

**Comment by josh** [comment]
I guess this whole idea is actually invalid

``` graphql
query {
  foo
  foo(bar: null)
}
```

Is a parse error, `Parse error on \"null\" (error) at [3, 12]`
