### ISSUE TITLE
Pagination returns wrong cursors after second page

### ISSUE THREAD

**Issue by volkanunsal** [rmosolgo/graphql-ruby#2502]
I'm getting the wrong cursor from `pageInfo` after paginating a few times. You can see more clearly in the output below:

```
page 1
>>>>>>>> startCursor: MQ
>>>>>>>> endCursor: MTA
> click next!

page 2
>>>>>>>> startCursor: MTE
>>>>>>>> endCursor: MjA
> click next!

page 3
>>>>>>>> startCursor: MjE
>>>>>>>> endCursor: MzA
> click prev!

page 2
>>>>>>>> startCursor: MQ
>>>>>>>> endCursor: MTA
(Same cursors as page 1)
```

My query is using `before`, `after` and `first`. And the value of `first` is always 10.

```graphql
query getListPanelProjects(
    $filters: FiltersInput!
    $first: Int!
    $before: String
    $after: String
  ) {
    projectList(
      filters: $filters
      first: $first
      before: $before
      after: $after
    ) {
      totalCount
      pageInfo {
        hasNextPage
        hasPreviousPage
        startCursor
        endCursor
      }
      nodes {
        id
        resourceId
        type
        name
        latlon
        category
        status
        fillColor
      }
    }
  }
```

**Comment by rmosolgo** [comment]
Sorry to hear it! Could you please tell me more about the underlying data? Is it an ActiveRecord relation? If the data is backed by a database, could you share the queries that run while executing each GraphQL query? 

Also, could you share the request logs that show which cursors are being passed _into_ the GraphQL query after each page click?

**Comment by volkanunsal** [comment]
Thanks, I captured all the log output on the server and [pasted it here](https://gist.github.com/volkanunsal/ae6799029b6d7dd120b3b12531256827).

**Comment by rmosolgo** [comment]
Thanks for sharing those logs, that's really helpful. 

I noticed that in `click4`, it's asking for: 

> `"first"=>10, "after"=>nil, "before"=>"MjE"` 

The _first_ 10 before `MjE` will be the first 10 _of the whole set_. Usually, you want to use `last` and `before` together, for example: 

> `"last" => 10, "before" => "MjE"`

That will give you 10 items _immediately_ preceding `MjE`.  Could you update the client logic to use `last` instead of `first` in that case? 

If that doesn't clear it up for you, please reopen this and let me know!

**Comment by volkanunsal** [comment]
Oh wow, thank you so much. What a relief!
