### ISSUE TITLE
Parse error when non-last argument ends with two backslashes (\\)

### ISSUE THREAD

**Issue by povilasjurcys** [rmosolgo/graphql-ruby#2506]
graphql generates parse error response when:
* field has multiple arguments
* non-last string argument has double backslashes in the end (example: "abc\\\\")

Everything works fine if backslashes are  in last argument or backslashes are not at the end of string (this will not generate parse error: "ab\\\\c"). Also it works fine if I pass values via variables

## The proof

I have a new project and I have QueryType which looks like this:

```ruby
module Types
  class Item < Types::BaseObject
    description "A list of items which may be completed"

    field :text, String, null: true
    field :other_text, String, null: true
  end

  class QueryType < Types::BaseObject
    field :item, Item, "test item", null: false do
      argument :text, String, "Restrict items to this status", required: false
      argument :other_text, String, "Restrict items to this statuss", required: false
    end

    def item(**kwargs)
      kwargs
    end
  end
end
```

if I make query like this:
```graphql
query {
  item(text: "a", otherText: "b\\") {
    text
    otherText
  }
}
```

I will get response:
```json
{
  "data": {
    "item": {
      "text": "a",
      "otherText": "b\\"
    }
  }
}
```
So far everything works just fine.

But if I change the order or arguments and do query like this:
```graphql
query {
  item(otherText: "b\\", text: "a") {
    text
    otherText
  }
}
```

I will get:
```json
{
  "errors": [
    {
      "message": "Parse error on \"\\\"\" (error) at [31, 34]",
      "locations": [
        {
          "line": 31,
          "column": 34
        }
      ]
    }
  ]
}
```

Reproduced with graphql v1.9.12 and also with master code.
Example project where you can check this behavior: https://github.com/povilasjurcys/graphql_failure_proof

**Comment by daemonsy** [comment]
Thanks for submitting a reproduction example, that is really awesome :heart: 

I'm trying to see if this can be reproduced

**Comment by daemonsy** [comment]
Can reproduce the anomaly using the two strings below. 

```ruby
passes = "query {\n  item(text: \"a\", otherText: \"b\\\\\") {\n    text\n    otherText\n  }\n}"
GraphQL.parse(passes) # argument value is "b\\"

fails = "query {\n  item(otherText: \"b\\\\\", text: \"a\") {\n    text\n    otherText\n  }\n}"
GraphQL.parse(fails) # GraphQL::ParseError (Parse error on "\"" (error) at [2, 34])
```

Since it errors at the `GraphQL.parse` call, it's probably something at the lexer/parser level. 

@povilasjurcys are you interested in taking a stab at this?

**Comment by povilasjurcys** [comment]
ah, @andrewdotn was smarter and faster then me. Thanks!
