### ISSUE TITLE
Is there a way to define camelize: false by default in all fields?

### ISSUE THREAD

**Issue by igorlemosvicente** [rmosolgo/graphql-ruby#2507]
If not, where could it be so I can create a pull request?

**Comment by daemonsy** [comment]
Hi @igorlemosvicente you can pass `camelize: false` in your base field as a default arg option. 

https://graphql-ruby.org/fields/introduction.html#field-parameter-default-values

If this doesn't solve the problem, feel free to reopen the issue.
