### ISSUE TITLE
Guide: Integration Tests

### ISSUE THREAD

**Issue by mpoisot** [rmosolgo/graphql-ruby#2515]
In the section the [last section](https://graphql-ruby.org/testing/integration_tests.html#testing-transport-level-behaviors) the header name is wrong.

"Authentication" should be "Authorization"

**Comment by rmosolgo** [comment]
Hi! Thanks for reporting an issue. I took another look at the page but I didn't spot the mistake. How about using the "Edit this page" link to submit a correction?
