### ISSUE TITLE
How to check a fields meta data in resolve?

### ISSUE THREAD

**Issue by lifeiscontent** [rmosolgo/graphql-ruby#2516]
e.g. if I create some meta data on a field such as 

`field :createReference, mutation: Mutations::CreateReference, allow_anonymous: true`

and then in the mutations resolve

how would I know that the `allow_anonymous: true` has been set?

```
def resolve(**args)
  # how to check here?
  if field.allow_anonymous
  end
end

**Comment by lifeiscontent** [comment]
@rmosolgo

**Comment by rmosolgo** [comment]
Hi, good question! First, two easy answers to different questions: 

- For fields which _don't_ use `mutation:` (or `resolver:`), you can use `self.` inside resolve. For example, if you have a base `GraphQL::Schema::Field` subclass, you can use `self.` inside [`resolve`](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/field.rb#L495) (for the interpreter) or [`resolve_field`](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/field.rb#L464) for the legacy runtime. 
- For mutations (or resolvers), you can use `self.` to access the instance of the resolver. 

However, the case you posted is neither here nor there: `allow_anonymous` is attached to the field, but resolution is delegated to a mutation instance. I can think of two options, plus a bonus third option: 

- You could use the applicable `def resolve...` method in your base field class (described above) to check for the presence of that option. 
- You could move the configuration to your mutation classes, then check for that configuration in `def resolve` in your mutations 

And the bonus third option would be to modify GraphQL-Ruby to pass the field instance _into_ the resolver when delegating resolve behavior, for example, here: 

https://github.com/rmosolgo/graphql-ruby/blob/3c0dfc046f73905c71525243957881e8b4e6b954/lib/graphql/schema/field.rb#L511

Oh, I thought of another option. If you add a reader method to your base field class, you could use `extras: [:allow_anonymous]` to inject the field into resolution (see [custom extras](https://graphql-ruby.org/fields/introduction.html#extra-field-metadata))

I hope that helps! If you run into trouble, please let me know what approach(es) you tried, what happened when you tried them, and the code for the implementation, then reopen this issue!
