### ISSUE TITLE
Latest version on RubyGems not up to date

### ISSUE THREAD

**Issue by iDuuck** [rmosolgo/graphql-ruby#2518]
Hey guys, I want to use the `context.parent` feature to only show specific things to a specific user on a specific nested model. Now I just digged into the source code, and I found out, that my installed source is way older than the one on the GitHub. When I try to install the source from GitHub, I am keep getting the message: 

```
Could not find gem 'graphql' in https://github.com/rmosolgo/graphql (at master@af50a0a).
The source does not contain any versions of 'graphql'
```

Please, could you tell me how to install the latest version of GraphQL?

**Comment by rmosolgo** [comment]
> in https://github.com/rmosolgo/graphql

The repository is called `graphql-ruby`, so you need to configure it like: 

```ruby
gem "graphql", github: "rmosolgo/graphql-ruby"
```

Hope that helps!
