### ISSUE TITLE
GraphQL Client extraction possibilities

### ISSUE THREAD

**Issue by josh** [rmosolgo/graphql-ruby#252]
Hey @rmosolgo,

I just wanted to write down some thoughts ahead of time for things that could be pulled in here from https://github.com/github/graphql-client.

All just ideas, but I figured writing it down would give you some time to think about them.

## Rack server

Well, this isn't even in graphql-client, but now that [GraphQL has a published set of HTTP conventions](http://graphql.org/learn/serving-over-http/#uris-routes), it'd be great to encourage people to use them by including a bare bones rack app. Here's a micro example.

``` ruby

class Server
  def initialize(schema); @schema = schema; end

  def call(env)
    req = Rack::Request.new(env)
    @schema.execute(req.params["query"], operation_name: req.params["operationName"], variables: JSON.parse(req.params["variables"]))
  end
end

map "/graphql" do
  run GraphQL::Server.new(MyCoolSchema)
end

# or embedded in Rails router
# routes.rb
match "/graphql", to: GraphQL::Server.new(MyCoolSchema)
```

Kinda works similar to what graphql-express provides with

``` js
app.use('/graphql', graphqlHTTP({
  schema: MyCoolSchema
}));
```

## Network adapters

I was on the fence about even including this in graphql-client itself, but since the HTTP conventions are out there, it'd be great to encourage HTTP clients to follow best practices using the same parameter naming conventions. The basic `Net::HTTP` wrapper I wrote for graphql-client isn't too many lines https://github.com/github/graphql-client/blob/master/lib/graphql/client/http.rb.

## Execution interface

But more important than including an HTTP adapter out of the box, which I can understand not wanting to maintain, I think we should standardize a calling interface for "execution adapters". Basically a *thing* that you can pass a query or document to and it will execute it.

I thought I had a clever insight with the `GraphQL::Client::HTTP` adapter and simply copied the method signature of `GraphQL::Schema.execute`. This way, `GraphQL::Schema` instances already work as "execution adapters".

``` ruby
MyLocalSchema.execute(document: document, operation_name: "FooQuery", variables: { :bar => 1 }, context: {})
HTTP.new("https://api.github.com/graphql").execute(document: document, operation_name: "FooQuery", variables: { :bar => 1 }, context: {})
SomeRPCThing.new.execute(document: document, operation_name: "FooQuery", variables: { :bar => 1 }, context: {})
```

Though, I'm wishing the method name was generically `call(document, operation_name, variables, context)` so you could use a simple proc `-> (document, operation_name, variables, context) {}` as a valid adapter wrapper.

Once theres a standardized interface, we can build tooling that works against local server schema and remote ones.

``` ruby
GraphQL::Schema.dump(MyLocalSchema)
GraphQL::Schema.dump(HTTP.new("https://api.github.com/graphql"))
```

## Response and error wrapper structs

Basically something like:

``` ruby
response_hash = LocalOrRemoteSchema.execute("query { ... }")
response = GraphQL::Response.new(response_hash)
response.data
response.errors.first.location
```

Could see this being useful server side, writing tests and for clients.

https://facebook.github.io/graphql/#sec-Response-Format

## Response Data wrappers

Sweet piece of graphql-client's magic IMO. Data wrappers allow more Ruby-ish method access to the nested data tree. All this is figured out statically without having to rely on `method_missing` at runtime.

``` ruby
data["node"]["user"]["login"]
# vs
data.node.user.login
```

graphql-client's implementation is kinda a mess now. I think the approach needs some time to bake before we should consider standardizing it.

I'm also trying to figure out how types can fit in more naturally. This doesn't work yet,

``` ruby
# maybe checking __typename internally or something
data.node.is_a?(Types::User)

case data.node
when Types::User
when Types::Repository
end
```

**Comment by rmosolgo** [comment]
😻 I love the idea of an execution interface. I wonder, could we get two birds with one stone? 

- Execution interface uses the `#call(...)` method 
- It returns a `Response` struct instead of a hash 

This gives us an easy upgrade path and no breaking changes! 

> Response Data wrappers ... without having to rely on method_missing at runtime

Oh la, I want to see that! Do you derive response classes from the types? 

> Rack 

Is this for the "real world" or as an example only? In my own case, I need Rails `before_action`s, so I don't have a use for a pure Rack app. I also don't mind making people copy-and-paste the Rails setup because I think it's important to see upfront how the incoming params are used. 

However, if you (or someone else) has use for a server like that one, we could include it in the library, but not require it automatically (so we don't have to add a Rack dependency).

**Comment by josh** [comment]
Awesome, thanks for the feedback @rmosolgo. I'll try to open individual PRs or more actionable issues for these specific ideas. Thanks!
