### ISSUE TITLE
Union Field Can't Add Resolver to Another Class

### ISSUE THREAD

**Issue by panbanda** [rmosolgo/graphql-ruby#2526]
I had a hard time naming this behavior.  Sorry for the weird title I can change it if I can figure out a better way to phrase it. :P

I have two classes that are joined to a polymorphic source.  

```ruby
module Types
  class Log < BaseObject
    field :id, ID, null: false

    # TODO: this next line raises an error if I uncomment it
    #field :records, function: Resolvers::RecordsSearch
    field :record, Record, null: true do
      argument :id, ID, required: true
    end

    def record id:
      object.records.find(id)
    end
  end
end

module Types
  class Sensor < BaseObject
    field :records, function: Resolvers::RecordsSearch
    field :record, Record, null: true do
      argument :id, ID, required: true
    end

    def record id:
      object.records.find(id)
    end
  end
end

```

These two classes both have a `RecordsSearch` resolver which is pretty basic:

```ruby
module Resolvers
  class RecordsSearch < BaseResolver
    type types[Types::Record]
    scope { object.respond_to?(:records) ? object.records : ::Record.all }
  end
end
```

Here is the actual `Records` type with the BaseUnion object:

```ruby
module Types
  class Record < BaseObject
    class Source < Types::BaseUnion
      description "The writer source of a single record."
      possible_types Types::Sensor, Types::Log
    end

    field :id, ID, null: false
    field :source, Source, null: true
  end
end
```

The issue is if I uncomment that line (commented above) then I get a runtime error:

```sh
RuntimeError: Unhandled to_type_name input:  (NilClass)
```

With the stack trace:

```sh
RuntimeError: Unhandled to_type_name input:  (NilClass)
/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/graphql-1.9.12/lib/graphql/schema/member/build_type.rb:114:in `to_type_name'
/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/graphql-1.9.12/lib/graphql/schema/field.rb:115:in `connection?'
/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/graphql-1.9.12/lib/graphql/schema/field.rb:248:in `initialize'
/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/graphql-1.9.12/lib/graphql/schema/member/accepts_definition.rb:142:in `initialize'
/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/graphql-1.9.12/lib/graphql/schema/field.rb:106:in `new'
/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/graphql-1.9.12/lib/graphql/schema/field.rb:106:in `from_options'
/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/graphql-1.9.12/lib/graphql/schema/member/has_fields.rb:11:in `field'
/app/graphql/types/log.rb:15:in `<class:Log>'
/app/graphql/types/log.rb:2:in `<module:Types>'
/app/graphql/types/log.rb:1:in `<top (required)>'
/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/zeitwerk-2.1.10/lib/zeitwerk/kernel.rb:16:in `require'
/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/zeitwerk-2.1.10/lib/zeitwerk/kernel.rb:16:in `require'
/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/jets-2.3.0/lib/jets/core_ext/kernel.rb:11:in `require'
/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `block in require'
/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:291:in `load_dependency'
/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
/app/graphql/types/record.rb:7:in `<class:Source>'
/app/graphql/types/record.rb:5:in `<class:Record>'
/app/graphql/types/record.rb:2:in `<module:Types>'
/app/graphql/types/record.rb:1:in `<top (required)>'
...
```

What is weird is that I actually can add this resolver to another class.  It is just these two classes, only one of them can have the resolver function.  If I switch the commented line to the other class, it works just the same.  Any thoughts or special considerations I am missing or maybe a bug with the union type initialization?

**Comment by rmosolgo** [comment]
Hi, sorry about that! It has all the tell-tale signs of a circular reference bug. I see lines in the stack trace point at the place where constants are referenced, then ActiveSupport::Dependencies gets involved 😅 

In many places in GraphQL-Ruby, you can replace Ruby constants with strings that contain the constant name. Then GraphQL-Ruby will try to defer the reference to that constant as long as it can. It's meant to help in tough spots like this. 

I'm sorry, I don't have a better recommendation than randomly substituting constant references with strings. Here are a few examples to try one-at-a-time, until it magically works: 

(This one is actually a bit different -- I see it's a function. It might work with a `proc`) 

```diff 
+ type -> { Types::Record }
- type types[Types::Record]
```

```diff 
+    field :record, "Types::Record", null: true do
-    field :record, Record, null: true do
       argument :id, ID, required: true
     end
```

```diff 
+      possible_types "Types::Sensor", "Types::Log"
-      possible_types Types::Sensor, Types::Log
```

Do any of those work for you?

**Comment by panbanda** [comment]
Well that is quite a tricky thing haha.  Yeah the last one in the `union` seems to work.  Thanks for the lifesaving tip ;)

**Comment by panbanda** [comment]
@rmosolgo quick question on this thread, did you have any tips for avoiding this behavior while returning an Array?  ["Types::Sensor"] for example...  Or functions `field .... function: "Type::REesolver"`

**Comment by rmosolgo** [comment]
For an array, you can put the whole thing as a string: `"[Types::Sensor]"`. For resolvers, you have to use a Ruby class reference, not a string.
