### ISSUE TITLE
Accessing Connection's Pagination Arguments in Resolver

### ISSUE THREAD

**Issue by marcpoulin** [rmosolgo/graphql-ruby#2532]
This isn't really a bug - it's more of a question. I'm on `1.9`.

I'm testing out this gem and I'm curious if there's a way to access the `first`, `last`, `before` and `after` methods in my connection type's resolver. I noticed they're being deleted automatically by the `ConnectionExtension` here: https://github.com/rmosolgo/graphql-ruby/blob/7239c771f52b77341a795a45766619d4230eaa94/lib/graphql/schema/field/connection_extension.rb#L17

Is there a way for me to skip or override this extension with my own extension to get access to the pagination parameters? Or is there a better way? I looked into creating my own connection base types (as specified [here](https://graphql-ruby.org/relay/connections.html#customizing-base-classes), but I don't think that's going to accomplish what I want.

Apologies if I'm missing something really obvious.

**Comment by rmosolgo** [comment]
No, I don't think it's obvious at all! Good question. That extension is applied to fields when they have `connection: true`. The catch is, it _defaults_ to true when the field's return type ends in `Connection`. Source:

https://github.com/rmosolgo/graphql-ruby/blob/2c6b7a8f7e5b107ca22350f41a255531c15a2329/lib/graphql/schema/field.rb#L109-L126

To skip "automatic" arg handling, pass `connection: false` to your field definition. However, if you skip argument handling, it will _also_ skip automatic wrapping in connection objects. You'll have to do something like that in your resolver. Here's the implementation from the gem: 

https://github.com/rmosolgo/graphql-ruby/blob/7239c771f52b77341a795a45766619d4230eaa94/lib/graphql/schema/field/connection_extension.rb#L35-L43

That should do the trick! We do it a few places in GitHub because ... reasons? Please reopen this if you give it a try and it doesn't work, and share the code you tried and what happened when you tried it.

**Comment by benbonnet** [comment]
Hello; I've landed here as while trying out to move on relay based schema, and wondering how things were to be used using connection and resolvers. I feel like it has to do with the original question, pardon me if I was wrong

Trying things out with the following snippet :

```
require 'graphql'

class BookType < ::GraphQL::Schema::Object
  field :id, ID, null: false
  field :title, String, null: false
end

class BookEdgeType < GraphQL::Types::Relay::BaseEdge
  node_type(BookType)
end

class BookConnection < GraphQL::Types::Relay::BaseConnection
  edge_type(BookEdgeType)
end

class BookResolver < ::GraphQL::Schema::Resolver
  # feels like using `type BookConnection...` is not the way to go,
  # but this is out first try into such implementation
  type BookConnection, null: false

  def resolve
    10.times.map { |i| OpenStruct.new(id: i+1, title: 'some title') }
  end
end

class QueryType < GraphQL::Schema::Object
  field :get_books, resolver: BookResolver
end

module Api
  class Schema < ::GraphQL::Schema
    query QueryType
  end
end

Api::Schema.execute <<-GRAPHQL
query {
  getBooks {
    id
    title
  }
}
GRAPHQL
```

At this point it works well. But, while trying to implement the following :

```
query($search: String) {
  getBooks(search: $search) {
    id
    title
  }
}
```

how do you get you hand on the search value in the resolver ?

We're scratched our head hard on the documentation provided, we were unsuccessful... the resolver's resolve method won't get anything back from variables. It feels like we're missing the point, hope to get some tips to get a better understanding

**Comment by marcpoulin** [comment]
Thank you for your response! I ended up subclassing `GraphQL::Schema::Field::ConnectionExtension` and overriding the `resolve` method to achieve what I wanted.

**Comment by benbonnet** [comment]
@marcpoulin without asking a full exposure of your code; would you mind sharing the entrypoint you've found out ? Am having a similar need and quite struggling

**Comment by marcpoulin** [comment]
Hi @benbonnet,

Basically this is what I did:

```
class RelayConnectionExtension < GraphQL::Schema::Field::ConnectionExtension
  def resolve(object:, arguments:, context:)
    next_args = arguments.dup
    yield(object, next_args)
  end
end

########

...
field :x,
      Types::Y.connection_type,
      connection: false,
      extensions: [RelayConnectionExtension],
      null: false

...

def x(**params)
  params[:first]
  ...
end
```

Probably not the cleanest approach, but it's good enough for testing.

**Comment by bolandrm** [comment]
implemented this recently with the following code, if it's helpful to anyone:

```
field = self.class.fields["latestTextMessages"]
# https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/field/connection_extension.rb#L55
context.namespace(:connections)[:all_wrappers] ||= context.schema.connections.all_wrappers
context.schema.connections.wrap(field, object, value, arguments, context)
```

**Comment by Artheanos** [comment]
Anyone knows how to do the same thing but for `argument` instead of `field`?
