### ISSUE TITLE
Uninitialized constant GraphQL::Types::ISO8601Date

### ISSUE THREAD

**Issue by pyrabbit** [rmosolgo/graphql-ruby#2533]
When attempting to use GraphQL::Types::ISO8601Date as a scalar type inside one of my obects, I receive an **Uninitialized constant GraphQL::Types::ISO8601Date** error. 

The only way to resolve this is to add `require 'graphql/types/iso_8601_date'` at the top of my model.

I am using the standard folder structure generated by the `rails g graphql:install` and `rails g graphql:object` commands. Is this the intended design or is there a known issue for these types not autoloading appropriately?

This issue does not occur with the similar `GraphQL::Types::ISO8601DateTime` type

**Comment by javiercr** [comment]
Is this a duplicated of #2527? If so, it got fixed on #2528 and published as `v1.9.13`

**Comment by pyrabbit** [comment]
@javiercr Ah, yeah this probably a duplicate. I will point to master in the meantime. Thanks for the quick response!
