### ISSUE TITLE
Union Type Implementation

### ISSUE THREAD

**Issue by K-Sato1995** [rmosolgo/graphql-ruby#2540]
I'm trying to implement a union type and followed the [official documentation](https://graphql-ruby.org/type_definitions/unions) but got the error listed below.

Here is my current code.

```ruby
module Types
  class AudioClipType < Types::BaseObject
    field :id, Int, null: false
    field :duration, Int, null: false
  end
end

module Types
  class MovieClipType < Types::BaseObject
    field :id, Int, null: false
    field :previewURL, String, null: false
    field :resolution, Int, null: false
  end
end

module Types
  class MediaItemType < Types::BaseUnion
    possible_types Types::AudioClipType, Types::MovieClipType

    def self.resolve_type(object, context)
      if object.is_a?(AudioClip)
        Types::AudioClipType
      else
        Types::MovieClipType
      end
    end
  end
end

module Types
  class PostType < Types::BaseObject
    description 'Post'
    field :id, Int, null: false
    field :media_item, Types::MediaItemType, null: true
  end
end

```

And here is the graphql query.

```
{
  posts {
    id
    mediaItem {
      __typename
      ... on AudioClip {
        id
      	duration
      }
      ... on MovieClip {
        id
        previewURL
        resolution
      }
    }
  }
}
```

When I send the query I get the following error.

```
Failed to implement Post.mediaItem, tried:
 - `Types::PostType#media_item`, which did not exist
 - `Post#media_item`, which did not exist
 - Looking up hash key `:media_item` or `"media_item"` on `#<Post:0x007fb385769428>`, but it wasn't a Hash

To implement this field, define one of the methods above (and check for typos
```

Am I missing something??

**Comment by rmosolgo** [comment]
How do you expect `field :media_item` to be resolved by GraphQL? Does your `Post` model have a `media_item` method? If not, you should define an implementation in your type class, for example: 

```ruby
field :media_item, # ... 

def media_item 
   object # => #<Post ... >
   # Somehow return the media item for this post
end 
```

If you don't provide a method on the underlying object (eg `Post#media_item`) or a manual implementation, GraphQL doesn't know what to _do_ with that field! 

Please give one of those approaches a try and reopen if that doesn't work for you, along with the code you tried and what happened when you tried it.

**Comment by K-Sato1995** [comment]
@rmosolgo 
Figured out how to implement it thanks to your advice. Thanks for taking the time to respond to such a fundamental question.
Appreciate it.
