### ISSUE TITLE
Pagination docs feedback

### ISSUE THREAD

**Issue by connorshea** [rmosolgo/graphql-ruby#2542]
I've been trying out `1.10.0.pre1` and adding pagination to my GraphQL API today, and I wanted to give some feedback on the documentation:

- There's a link to a non-existent page at the top of [`custom_connections.md`](https://github.com/rmosolgo/graphql-ruby/blob/1.10-dev/guides/pagination/custom_connections.md): `{% internal_link "Using Connections", "/pagination/using_connections" %}`.
- There's a broken link in [`connection_concepts`](https://github.com/rmosolgo/graphql-ruby/blob/97b2dff3dfa866cf101f3626b248ec1e65ebbaef/guides/pagination/connection_concepts.md#connection-metadata): `{% internal_link "add a total count field", "xyz" %}`

- In [the Connection Type section of `custom_connections.md`](https://github.com/rmosolgo/graphql-ruby/blob/1.10-dev/guides/pagination/custom_connections.md#connection-type), there's this bit of code:

```ruby
class Types::BaseConnectionObject < Types::BaseObject
  # implement based on `GraphQL::Types::Relay::BaseConnection`, etc
end
```

I wasn't able to get this working as-is, I _think_ it's supposed to be a subclass of `GraphQL::Types::Relay::BaseConnection`? At least, that's how I got it to work.

- There's no mention of limiting the number of nodes per-page (other than the user doing it themselves with something like `first: 10`) in the pagination docs, you have to go to [the Connections documentation for that](https://github.com/rmosolgo/graphql-ruby/blob/1.10-dev/guides/relay/connections.md#maximum-page-size), and I'm not 100% sure that's how it'd be recommended to handle it.

- The pagination docs could probably do a better job of showing how the pagination functionality fits in with other code, e.g. I'm not sure how to [fit this in](https://github.com/rmosolgo/graphql-ruby/blob/1.10-dev/guides/pagination/custom_connections.md#using-a-custom-connection) with my existing code since I don't know what `MyApp::SearchResults` is supposed to look like. Is it a GraphQL type or a Rails model?

I hope this feedback is useful :) Thanks for adding this pagination functionality as a core part of graphql-ruby, it seems like it will make my implementation much easier :D

**Comment by rmosolgo** [comment]
Thanks again for your thoughts on this! I've been working through them bit by bit and pushing improvements to 1.10-dev. 

> a subclass of `GraphQL::Types::Relay::BaseConnection`

You _could_ do it that way, but the downside is, you don't get the benefit of any customizations to `Types::BaseObject`, since it doesn't inherit from that class. I imagined it wouldn't be too much trouble to take the built-in `Relay::BaseConnection` and port it to one's own application, but I may have been mistaken about that. 

One way I can think to make it _easier_ would be to wrap up connection-related stuff in a _module_ so that people could do: 

```ruby 
class Types::BaseConnection < Types::BaseObject
  # get edges, nodes, page_info, etc: 
  include GraphQL::Types::Relay::ConnectionMixin
end 
```

Do you think that would be an improvement?

**Comment by connorshea** [comment]
The mixin seems like it should work, this is what my base connection object looks like right now: https://github.com/connorshea/VideoGameList/blob/master/app/graphql/types/base_connection_object.rb

**Comment by rmosolgo** [comment]
Thanks for sharing. The downside about that approach is that features from `BaseObject` (like `def self.authorized?`) _aren't_ inherited by the connection object class, since BaseObject isn't a superclass of it. Seems like a footgun 😅

**Comment by connorshea** [comment]
It's no fun to code without a bit of risk of shooting yourself in the foot :^)

**Comment by rmosolgo** [comment]
v1.12.0 includes mixins for connection and edge behaviors: 

https://graphql-ruby.org/api-doc/1.12.0/GraphQL/Types/Relay/EdgeBehaviors
https://graphql-ruby.org/api-doc/1.12.0/GraphQL/Types/Relay/ConnectionBehaviors

Please open a new issue if you give them a try and run into any trouble!
