### ISSUE TITLE
Disable only one introspection entry point

### ISSUE THREAD

**Issue by TomasBarry** [rmosolgo/graphql-ruby#2546]
Following the work done [here](https://github.com/rmosolgo/graphql-ruby/pull/2327), is it possible to only disable the `__schema` introspection entry point?

If not, would a PR similar to [this](https://github.com/rmosolgo/graphql-ruby/pull/2327) (which introduced the `disable_introspection_entry_points` method) be accepted?

The PR would introduce two more methods:

1) `enable_schema_introspection_entry_point`
2) `enable_type_introspection_entry_point`

A case has arisen where we would like to disable only the `__schema` entry point, or in other words, only expose the `__type` entry point (should any more entry points be added in future).

The usage would look something like:

```ruby
class MySchema < GraphQL::Schema
  # disable all introspection entry points by default
  disable_introspection_entry_points

  # enable the __type introspection entry point
  enable_type_introspection_entry_point

  mutation(Types::MutationType)
  query(Types::QueryType)
end
```

Alternatively, we could just introduce `disable_X_introspection_entry_point` methods for the two existing introspection entry point methods:

1) `disable_schema_introspection_entry_point`
2) `disable_type_introspection_entry_point`

Therefore, the usage would be like:

```ruby
class MySchema < GraphQL::Schema
  # disable the __schema introspection entry point while leaving others (__type) available
  disable_schema_introspection_entry_point

  mutation(Types::MutationType)
  query(Types::QueryType)
end
```

**Comment by ryanfreddy** [comment]
I think this would be a very useful feature.

**Comment by rmosolgo** [comment]
You could implement this dynamically by customizing the introspection system: 

https://graphql-ruby.org/schema/introspection.html#customizing-introspection

For example, you could raise an error if someone accesses an entry point you don't want to support. Alternatively, you could try defining an `EntryPoints` class that _doesn't_ have that field. (You'd riff off the built-in `EntryPoints` class, but I don't think you could use it as a base class, since it already includes `__schema`.) 

Finally, yes, if you want to make the change, I'd accept it! 

Hope that helps and please let me know if you try the custom introspection approach and run into trouble.

**Comment by TomasBarry** [comment]
Which would be preferable:

1) Add methods to disable specific entry points (`disable_schema_introspection_entry_point`, `disable_type_introspection_entry_point`, etc)
2) Update the [`disable_introspection_entry_points`](https://github.com/rmosolgo/graphql-ruby/blob/35dc19b57329294baf20f93d8f1265c563d733d9/lib/graphql/schema.rb#L100) method to accept an optional `except` parameter that will take a list of entry points to disable. The API would be:

```ruby
class MySchema < GraphQL::Schema
  disable_introspection_entry_points(except: ['__type'])

  mutation(Types::MutationType)
  query(Types::QueryType)
end
```

Option 2 would introduce some breaking changes ([this](https://github.com/rmosolgo/graphql-ruby/blob/35dc19b57329294baf20f93d8f1265c563d733d9/lib/graphql/schema.rb#L913) method would no longer make sense unless it was interpreted as returning `true` if and only if _all_ introspection methods are disabled (but this could hide the fact that only one of them is disabled).

Any thoughts on this @rmosolgo?

**Comment by rmosolgo** [comment]
I prefer Option 1
