### ISSUE TITLE
Action not found: "The action 'execute' could not be found for GraphqlController" for Rails API only application

### ISSUE THREAD

**Issue by aarona** [rmosolgo/graphql-ruby#2548]
**Steps to produce:**

```
rails new execute-test --api
cd execute-test
vim Gemfile # or open an editor and add "gem 'graphql'"
bundle
rake db:create
rails g graphql:install
rake routes # to test that the route exists
rails s
```

Now go to an app like GraphiQL that can test the end point and hit the url http://localhost:3000/graphql .

Server side error:

```
Started POST "/graphql" for 127.0.0.1 at 2019-10-15 16:23:29 -0700
   (0.3ms)  SELECT sqlite_version(*)
  
AbstractController::ActionNotFound (The action 'execute' could not be found for GraphqlController):
  
actionpack (6.0.0) lib/abstract_controller/base.rb:131:in `process'
..... stack trace continues on...
```

**Comment by aarona** [comment]
Ok it looks like the following line in the `execute` method was causing the problem:

`protect_from_forgery with: :null_session`.

**Comment by rmosolgo** [comment]
Could you elaborate on what you found here? I can't tell if there's something wrong with GraphQL-Ruby's install generator, or if there was something out of place in your application. What did you do to fix this problem?

**Comment by chrislambe** [comment]
Just as another data point: I also just ran into this with a new api-only Rails project and fixed it with @aarona's suggested line removal. Looks like I'm on `rails` `6.0.0` and `graphql` `1.9.14`.

**Comment by aarona** [comment]
@rmosolgo I think this isn't a graphql issue actually. I think if you create an API only rails app and you use the `protect_from_forgery` method in any controller as you do with the vanilla `GraphqlController` class that gets installed, it causes an error that at face value made it seem like `graphql` was causing this.

I dont think you need to do anything to fix this but possibly add something in the documentation or a simple comment above the line stating that you should remove that line if running an API only application. I'll put it to you another way: If I were to add the cookies/session middleware back into the application and kept that line in the controller code, I wouldn't get this error (didn't test this but this is what I'm assuming).

**Comment by daemonsy** [comment]
```ruby
ActionController::Base.protect_from_forgery
=> [:verify_same_origin_request]

ActionController::API.protect_from_forgery
NoMethodError: undefined method `protect_from_forgery' for ActionController::API:Class
```

So for any apps that are using API mode, I assume `ApplicationController` probably inherits `ActionController::API`  @chrislambe @aarona if you have the code handy, is that right?

**Comment by rmosolgo** [comment]
Personally I think a good fix would be to comment out that call in the generated code. 

That way, it's there for people who need it, but doesn't break stuff out of the box. (I'm trying to save people the step of, "Oh, I need to bypass CSRF, let me google the Rails-fu for that".)

**Comment by daemonsy** [comment]
@rmosolgo :+1: makes sense, follow up PR
https://github.com/rmosolgo/graphql-ruby/pull/2557

**Comment by aarona** [comment]
@rmosolgo great idea. Closing ticket.
