### ISSUE TITLE
PR for #2461 breaks the spec

### ISSUE THREAD

**Issue by dteoh** [rmosolgo/graphql-ruby#2549]
According to both the current and draft specs:

* https://graphql.github.io/graphql-spec/June2018/#sec-Objects
* https://graphql.github.io/graphql-spec/draft/#sec-Objects

... a type definition like ~~`type Query { }`~~ `type Query` _is_ a valid definition, ~~because the production of `FieldsDefinition` is optional~~.

People might wonder why this could possibly be useful. Well in conjunction with union, it can be used to implement variant types like in OCaml, where some variants might have parameters, and others might not. For example:

```
type RGB {
  red: Int
  green: Int
  blue: Int
}

type SystemDefault

union Color = RGB | SystemDefault
```

Edit: Apologies, `type Query { }` is invalid, because it requires one or more `FieldDefinition` productions. However, `type Query` is valid, which is now not possible to model in graphql-ruby.

**Comment by swalkinshaw** [comment]
In both of the spec links:

> An Object type must define one or more fields.

https://graphql.github.io/graphql-spec/draft/#sel-HAHZhCFBABABuBq9O

Also see https://github.com/graphql/graphql-js/issues/937 and here's where graphql-js enforces it: https://github.com/graphql/graphql-js/blob/0eaa5e60bd34d3303fde14ecf328bc7b1cbfa1e9/src/type/validate.js#L267-L273

**Comment by dteoh** [comment]
Ok, sorry about this. I guess I will just have to add a dummy field to model variants with no params.

I don't quite understand why `FieldsDefinition` would be marked as optional though.
