### ISSUE TITLE
Subscriptions not work with snake_cased arguments

### ISSUE THREAD

**Issue by durcak** [rmosolgo/graphql-ruby#2553]
First of all, thank you for all your work on this library!

I have tried `subscriptions` with `ActionCable` and new `interpreter` in my project and found out, that its not working correctly with not camelized arguments. Its because events IDs generated in a initial subscription process are always camelized, apart from arguments class is initialized with `camelize: false`. 

To provide a failing case I've forked the [evilmartians/chronicles-gql-martian-library](https://github.com/evilmartians/chronicles-gql-martian-library/tree/part-3) project (that's part of the [blog post](https://evilmartians.com/chronicles/graphql-on-rails-3-on-the-way-to-perfection)), and added the set of changes to make it fail: update the graphql gem, add the new interpreter and add simple arguments to `ItemUpdated` and `ItemAdded` subscriptions. In first case argument with name: `id` and in second `test_id` to provide failing case.

Here are the instructions to reproduce the bug

```
git clone -b graphql-ruby-subscriptions-bug https://github.com/durcak/chronicles-gql-martian-library.git
cd chronicles-gql-martian-library
bundle install
rake db:create
rake db:seed
bin/rails s

```

Now you can log in with john.doe@example.com. You'll see this in the console:
```
GraphqlChannel is streaming from graphql-event::itemUpdated:id:10
GraphqlChannel is streaming from graphql-event::itemAdded:testId:10
```
After updating an item:
`[ActionCable] Broadcasting to graphql-event::itemUpdated:id:10`

After adding new item:
`[ActionCable] Broadcasting to graphql-event::itemAdded:test_id:10`

Subscription for update is working, event ids are the same, but subscription for adding new item is not working, because ids are diferent. `testId` should not be camelized. 

I think, its because of this line https://github.com/rmosolgo/graphql-ruby/blob/74f736beafdcc9fab9967475bbfd0f5d9f958336/lib/graphql/subscriptions/event.rb#L63

I have created [PR ](https://github.com/rmosolgo/graphql-ruby/pull/2552) with possible solution, can someone check it, tests are failing.

**Comment by rmosolgo** [comment]
Fixed by #2552 , thanks @durcak 🎉 !
