### ISSUE TITLE
Circular references in fragments, but shouldn't!

### ISSUE THREAD

**Issue by gjtorikian** [rmosolgo/graphql-ruby#257]
From https://platform.github.community/t/circular-references-in-fragments/314:

> It seems that requests with circular references in fragments fail abruptly, instead of returning a validation error. See the "No fragment cycles4" validation rule.

True story! The query provided does refer onto itself, and shouldn't, because it results in a `stack level too deep`.

@rmosolgo Think you'll have time to look into this? If not I can pick it up, no worries. 👌

**Comment by rmosolgo** [comment]
Derp, it fails because it's nested, just a bit ...

**Comment by rmosolgo** [comment]
I can't rewrite this module fast enough 😢
