### ISSUE TITLE
Infinite loop with duplicate fragments

### ISSUE THREAD

**Issue by grcooper** [rmosolgo/graphql-ruby#2571]
I was running into a validation issue:
`Resolution loops exceeded the number of definitions; infinite loop detected.`

I ran something that looked like this:
```
fragment myFooFragment on Foo {
  id
}

fragment myBarFragment on Bar {
  ... myFooFragment
}

fragment myBarFragment on Bar {
 ...myFooFragment
}

{
   myObject {
    ...myBarFragment
  }
}
```

This is coming from: https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/static_validation/definition_dependencies.rb#L131

It might be that we need duplicate fragment checks before dependancy checking to prevent multiple items being added to the dependancy graph you are creating above.

**Comment by rmosolgo** [comment]
Thanks for the detailed report. It was a headache, but I got something working over at https://github.com/rmosolgo/graphql-ruby/pull/2577

It changes the validation error in one case, but it's not too bad.

**Comment by grcooper** [comment]
Thanks for fixing this so quickly 🙏 Looks great!
