### ISSUE TITLE
AST Analyzer: Arguments supplied by input objects are visited or not visited depending on whether they are supplied inline or via variables

### ISSUE THREAD

**Issue by chrisbutcher** [rmosolgo/graphql-ruby#2573]
Arguments supplied by nested input objects via variables are not visited by the AST Analyzer visitor. They are visited when the same nested input objects are supplied inline, directly in the query document.

See the attached PR for more details, with tests the confirm this issue.

**Comment by rmosolgo** [comment]
Thanks so much for your research into this. 

AST analyzers were meant to replace IRep analyzers. In the IRep, there were only nodes for fields. Arguments were never visited. Instead, `irep_node.arguments` would provide the arguments to the analyzer. 

Do you think it might work to take an approach like that with the AST analyzer? For example, we might be able to add the arguments hash (using `query.arguments_for(node)`) into the API. 

I can't remember exactly how the analyzer is set up, but if we provided access to the arguments _that_ way (that is, normalizing to a Hash instead of normalizing to an AST), would it suit your needs?

**Comment by chrisbutcher** [comment]
I think https://github.com/rmosolgo/graphql-ruby/pull/2574 is really pointing out two issues.

The first is what we're discussing here so far:

## Ease of obtaining argument values for input object fields

> query.arguments_for(node)

Interesting! I also started to go down that kind of path (`query.arguments_for(node)`), but hit a snag where ArgumentsCache is expecting to be called with a field definition as well as an `irep_or_ast_node`:

```ruby
@arguments_cache[irep_or_ast_node][definition]
```
https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/query.rb#L244

> I can't remember exactly how the analyzer is set up, but if we provided access to the arguments that way (that is, normalizing to a Hash instead of normalizing to an AST), would it suit your needs?

I'm not sure I 100% follow what you mean by "normalizing to a Hash instead of normalizing to an AST". Do you mean:

```ruby
def on_leave_argument(node, parent, visitor)
   # where `node` is an instance of GraphQL::Language::Nodes::Argument

  # returns an instance of GraphQL::Query::Arguments
  arguments = query.arguments_for(node)

  # returns an instance of GraphQL::Query::Arguments::ArgumentValue
  value = arguments.argument_values[node.name]

  static_metrics = {
    argument_name: node.name,
    argument_type_name: visitor.argument_definition.type.unwrap.to_s,
    default_used: value.default_used?,
    parent_field_name: visitor.field_definition.name,
    parent_field_type_name: visitor.parent_type_definition.name,
    value_is_null: value.value.nil?,
  }
  
  # do something with static_metrics
end
```

## on_enter/leave_argument hook is not called on input object fields supplied by variables

This is demonstrated with a failing test here:
https://github.com/rmosolgo/graphql-ruby/pull/2574/files#diff-c845a0b55ef57645aa53df4e3836bc96R281

I've also pushed up a WIP branch in which I'm rewriting basically all of our graphql-metrics gem to combine AST analysis with instrumentation and tracing to easily get a full set of static and runtime metrics for queries, fields and arguments: https://github.com/Shopify/graphql-metrics/pull/10, with a failing test and some FIXME values left in to highlight the places I'm blocked at the moment.

**Comment by eapache** [comment]
We have several analyzers which need to recursively visit all the input objects in a query. This would be much simpler if the analyzer simply iterated them as part of the AST, though it's still entirely possible if the analyzer only visits the field and we have to recurse on the input args manually. I think we're all in agreement there should be consistency though - either it should visit all of them (including nested ones and variables) or it should visit none of them and require manual handling.
