### ISSUE TITLE
Upgrader doesn't work with zsh

### ISSUE THREAD

**Issue by heatherbooker** [rmosolgo/graphql-ruby#2581]
Hi, I just wanted to let other people know that if your shell is zsh, you might have problems with the upgrader for 1.8+ to class based syntax.

Namely,
```
rake graphql:upgrade[app/graphql/**/*] 
```
does not work, but
```
rake 'graphql:upgrade[app/graphql/**/*]'
```
(with single quotes around the task) does!

I could also run the original task in bash with no problems. 

The error message I got in zsh was `zsh: no matches found:`; other search terms might be "rake upgrade task doesn't work / exist, can't find upgrade task". 

(I don't think this is a bug report, but just in case others are confused/stuck. Also #1517 is a bug report that the task is not listed in `rake --tasks`, which may contribute to your confusion, dear reader. Good luck.)

**Comment by rmosolgo** [comment]
Hi, thanks for sharing your solution here! If you'd like to help future readers, you could use the "Edit" button on the bottom of the docs page to suggest an improvement to that page. For example, it might fit well in this section: https://graphql-ruby.org/schema/class_based_api.html#using-the-default-upgrade-task
