### ISSUE TITLE
Unhandled GraphQL subscription error ReferenceError: document is not defined

### ISSUE THREAD

**Issue by hugoh59** [rmosolgo/graphql-ruby#2584]
I'm trying to setup a subscription with my React Native app and Rails Graphql server but I get the following error message.

> Unhandled GraphQL subscription error ReferenceError: document is not defined

I followed this guide: https://haughtcodeworks.com/blog/software-development/graphql-rails-react-standalone/

Any idea how to solve that?

**Comment by rmosolgo** [comment]
Hi! Sorry I'm slow to respond here. I don't know about that error. Could you please share some more information about it? 

- Did you encounter this error in JavaScript or Ruby?
- Could you share the full error and backtrace? 
- Could you share the code that you wrote which gave this error?

**Comment by hugoh59** [comment]
I've encoutered this error trying to implement subscriptions on my React Native App Following this tutorial https://haughtcodeworks.com/blog/software-development/graphql-rails-react-standalone/

**Comment by pshettigar26** [comment]
@hugoh59 Hi that link is not working for me. Why?  i also need  to implement  graphql subscription using ruby on rails . can you please help me to get proper example project. i am not getting proper document to implement it. #GraphqlSubscription #Ruby #Rails #actioncable #Graphql
