### ISSUE TITLE
Possibility of Regex in argument type

### ISSUE THREAD

**Issue by TomasBarry** [rmosolgo/graphql-ruby#2587]
Is it possible to apply a regex to an argument type? Something like:

```ruby
module Inputs
  class MyInput < Types::BaseInputObject
    argument(
      :phone_number, 
      String,
      required: true,
      matches: /^(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}$/
    )
  end
end
```

Or would a custom resolver be required here?

**Comment by rmosolgo** [comment]
Hi, this is not supported. You could perform the validation inside `#initialize`, for example: 

```ruby 
def initialize(*)
  super 
  if self[:phone_number] !~ PHONE_NUMBER_PATTERN 
    raise GraphQL::ExecutionError, "Validation error: ..."
  end 
end 
```

Alternatively, you could implement a PhoneNumber scalar that performs this validation in `coerce_input`. Hope that helps!

**Comment by TomasBarry** [comment]
I like the `PhoneNumber` scalar solution. Thanks for the suggestion.
