### ISSUE TITLE
AST analyzers and merged fields

### ISSUE THREAD

**Issue by swalkinshaw** [rmosolgo/graphql-ruby#2589]
In the process of porting irep based analyzers to AST analyzers I've noticed at least one difference: merged fields.

Example query:

```graphql
{
  shop {
    name
  }
  shop {
    url
  }
}
```
Assuming scalars are free these are the calculated complexity for each kind of analyzer

Irep: 1
AST: 2

This makes complete sense considering how each one represents a query document but it's not "correct" when you want to calculate complexity. The only solution that comes to mind is more complicated state tracking per AST node but even that I'm unsure of. It might be easier to handle that in the complexity itself instead of trying to account for merged fields in the visitor?

**Comment by rmosolgo** [comment]
I added an analyzer-based approach at  #2595

**Comment by rmosolgo** [comment]
I ended up fixing the complexity analyzer. But any other analyzer with a similar goal will have to solve the same problem, so maybe we'll want to generalize later. 

Is there anything else to do on this now?

**Comment by swalkinshaw** [comment]
We ran the updated analyzer from #2595 in parallel with the legacy irep based one and there's been **no** differences logged 🎉 

I'll close this, thanks 😄
