### ISSUE TITLE
Empty array in query variable is nil

### ISSUE THREAD

**Issue by shawnwonolo** [rmosolgo/graphql-ruby#2592]
If I pass in an empty array explicitly as an attribute, graphql-ruby interprets as an empty array, but if I pass it as a query variable, graphql-ruby thinks I'm passing in nil.

As an example, here I'm passing in an empty array for an attribute that expects an array of IDs, and this works as expected.
```
mutation EmptyBadges($scoutId: ID!) {
  updateScout(
    id: $scoutId,
    attributes: {
      badges: []
    }
  )
  {
  	scout {
      id
      badges {
        id
      }
    }  
  }
}
```
This is what the argument looks like for that attribute, and I get an empty array as expected.
```
argument :badges, [ID], required: false
```

But, when I pass it as a query variable, it thinks its nil. Here's the graphql query:
```
mutation RevengeOfEmptyBadges($scoutId: ID!, $badges: [ID!]) {
  updateScout(
    id: $jobRequestId,
    attributes: {
      badges: $badges
    }
  )
  {
    scout {
      id
      badges {
        id
      }
    }  
  }
}
```
Here are the query variables:
```
{ 
  "scoutId": 1,
  "badges": []
}
```

I can make the code behave as I expect, if I change the argument like this:
```
argument :badges, [ID], required: false, prepare: -> (badges, context) { badges || [] }
```

I'm really confused as to why badges is nil if the empty array is passed as a query variable. Is this potentially a bug with graphql-ruby or is there something I'm fundamentally misunderstanding about graphql?

I'm on graphql version 1.9.14 and Rails 4.2.

**Comment by michal-samluk** [comment]
Check this rails issue: https://github.com/rails/rails/issues/13766

**Comment by rmosolgo** [comment]
Thanks @michal-samluk , I agree it looks like that Rails issue. You could confirm it (or refute it) by sharing your Rails logs, with the raw incoming request and the parsed Rails params. Does the raw incoming request include `[]`? Does Rails turn it into `nil`? If _not_, I'll reopen this issue!

 It looks like there's _supposed_ to be a way to disable this behavior by Rails: 

https://github.com/rmosolgo/graphql-ruby/issues/986#issuecomment-335496101

If that doesn't work, the other avenue I'd consider is parsing the response body "by hand", something like `raw_params = JSON.parse(request.body.read); raw_params["variables"]`. Maybe that would give you access to the "real" incoming values with Rails's replacements. 

Let me know if you determine it's _not_ a Rails behavior and I'll keep digging!

**Comment by shawnwonolo** [comment]
Thanks, I confirmed that this was Rails behavior.
