### ISSUE TITLE
Overriding inspect

### ISSUE THREAD

**Issue by destructobeam** [rmosolgo/graphql-ruby#2593]
Hi, is there any reason the inspect method is overridden in so many classes to provide no useful output? It's quite frustrating when debugging having it unusable.

**Comment by rmosolgo** [comment]
Hi! I implemented `inspect` _so that_ they'd be helpful 😆  It sounds like that didn't work. If you'd like to recommend new implementations, please open a PR!

**Comment by destructobeam** [comment]
Sorry, that initial message came off as overly harsh rereading it. Did not intend it that way!

I was trying to use inspect on a `GraphQL::Query` instance and only getting back the string `"query ..."`.

I was thinking maybe as a stop gap using the superclass's implementation might be worthwhile, until potentially making something more specific as needed on a class by class basis? If that works for you would be happy to work on that later this week.

**Comment by destructobeam** [comment]
Looking through the rest of the classes a lot of the overrides look like they do make sense, I think I may have just hit the unimplemented one?

**Comment by rmosolgo** [comment]
Oh, yes, I think that one was implemented out of desperation 😬  The default implementation spewed tons of text (besides the query string, it displayed the `@schema` reference, which was also huge). 

I bet it could be done much better, for example, including the operation name, the variables, the context hash perhaps, maybe some other things. If you find something that works better for you, please do consider sharing it!

**Comment by destructobeam** [comment]
Hah, no worries, will have a look at it next week or so, and submit a pull request if I come up with anything decent.
