### ISSUE TITLE
GraphQL Install doesn't generate expectedly

### ISSUE THREAD

**Issue by lifeiscontent** [rmosolgo/graphql-ruby#2609]
when I run `rails g graphql:install`

it generates

**app/graphql/types/base_input_object.rb**
``` rb
module Types
  class BaseInputObject < GraphQL::Schema::InputObject
    argument_class Types::BaseArgument
  end
end
```

this seems odd, why would you put it in types and not its own `inputs` folder? since the schema itself doesn't classify it as a type, this seems counter intuitive. I guess now that I think more about it, it would also make sense to do this with enums, scalars, unions, etc.

it also seems that a generator is missing for `rails g graphql:input` or what is the expected way to create inputs via a generator?

**Comment by rmosolgo** [comment]
Yes, the generator puts _all_ types in `types/` folder and `Types::` namespace: Objects, Unions, Interfaces, Inputs and Scalars.

Oops, it looks like there's no input generator! There's no reason for that, I guess it just hasn't been implemented yet.
