### ISSUE TITLE
Plugins cannot attach tracers, query analyzers

### ISSUE THREAD

**Issue by chrisbutcher** [rmosolgo/graphql-ruby#2615]
This bug/inconsistency was uncovered in https://github.com/Shopify/graphql-metrics/pull/10#discussion_r336174539

Attaching instrumentation via a plugin with `def self.use(schema_defn_proxy)` works just fine, but attaching a tracer or query analyzer this way doesn't work.

```ruby
def self.use(schema_defn_proxy)
  schema_defn = schema_defn_proxy.target
  schema_defn.instrument :query, NoOpInstrumentation # ✅works fine
  schema_defn.tracer NoOpTracer # 💥NoMethodError: undefined method `tracer' for #< ...>
  schema_defn.query_analyzer NoOpAnalyzer # 💥NoMethodError: undefined method `query_analyzer' for #< ...>
end
```

It seems like attaching these things to either a schema class definition or schema instance _ought_ to be supported as is the case with instrumentation, but this doesn't appear to be so yet.

**Repro PR: https://github.com/rmosolgo/graphql-ruby/pull/2614**

**Comment by chrisbutcher** [comment]
cc: @swalkinshaw

**Comment by rmosolgo** [comment]
This works as expected in 1.10, where schema classes work a lot better. See #2614
