### ISSUE TITLE
Feature: option to add a module prefix when using string type_expr

### ISSUE THREAD

**Issue by TSMMark** [rmosolgo/graphql-ruby#2616]
If your types are in a deep module namespace, it can be overly verbose to write the module namespace each time. 

Contrived example:

```ruby
field :user, "Application::API::GraphQL::V1::Objects::User"
field :feature, "Application::API::GraphQL::V1::Enums::Features"
```

I'm not overly intimate with this library or its conventions but my first draft of a proposal would be to set a config value something like this

```ruby
# Set some global config in an initializer
config.type_module_namespace = "Application::API::GraphQL::V1"

# Use field string which will use module prefix when constantized
field :user, "Objects::User"
field :feature, "Enums::Features"
```

I think it might be useful to circumvent the prefix as needed, so prefix with root namespace `::` to use root:

```ruby
field :user, "Objects::User"
field :feature, "Enums::Features"
field :some_root_type, "::Some::Root::Type"
```

Relevant method `constantize` here:

https://github.com/rmosolgo/graphql-ruby/blob/9d2bac94cc2c4494b2201d4356306ae26029e8f8/lib/graphql/schema/member/build_type.rb#L129-L158

If this is approved and we agree on an API I can submit a PR.

**Comment by rmosolgo** [comment]
I don't think we need this in GraphQL-Ruby, at least not yet. How about implementing it in your base field class? For example: 

```ruby 
class Types::BaseField 
  TYPE_PREFIX = "Application::API::GraphQL::V1::"

  def initialize(type:, **rest, &block)
    # If the type is given as a string, add TYPE_PREFIX _unless_ it's: 
    # - a global constant, scoped with a leading `::`
    # - a constant _already_ prefixed with TYPE_PREFIX
    if type.is_a?(String) && !type.start_with?("::") && !type.start_with?(TYPE_PREFIX)
      type = "#{TYPE_PREFIX}#{type}"
    end 

    # Forward all args, including the maybe-modified `type`
    super(type: type, **rest, &block)
  end 
end 
```

Does that work for you?

**Comment by TSMMark** [comment]
This is great, I had not discovered the `field_class` method until seeing this.

There is an issue with the snippet you posted when it tries to parse a list-type string e.g. "[MyType]". I'll try updating it to handle this case

**Comment by TSMMark** [comment]
@rmosolgo Thanks so much, your snippet was a great start and here is the code that was finally required for everything to fit together nicely. Posted here in case it helps anyone else accomplish this:

```ruby
module Vydia
  module GraphQL
    module V1
      module Types
        module Arguments
          class Base < ::GraphQL::Schema::Argument

            TYPE_PREFIX = "Vydia::GraphQL::V1::Types::".freeze

            def initialize(arg_name = nil, type_expr = nil, desc = nil, camelize: false, **rest, &block)
              # If the type is given as a string, add TYPE_PREFIX _unless_ it's:
              # - a global constant, scoped with a leading `::`
              # - a constant _already_ prefixed with TYPE_PREFIX
              # - a constant that references one of GraphQL's default types in GraphQL::Types
              case type_expr
              when Array
                type_expr[0] = maybe_prepend_module_prefix(type_expr[0])
              else
                type_expr = maybe_prepend_module_prefix(type_expr)
              end

              # Forward all args, including the maybe-modified `type`
              super(arg_name, type_expr, desc, :camelize => camelize, **rest, &block)
            end

            private

            def maybe_prepend_module_prefix(type)
              type = "#{TYPE_PREFIX}#{type}" if type.is_a?(String) && !type.start_with?("::") && !type.start_with?(TYPE_PREFIX) && !protected_type?(type)

              type
            end

            def protected_type?(type)
              type == "Integer" || ::GraphQL::Types.constants.include?(type.to_sym)
            end

          end
        end
      end
    end
  end
end
```

and then placing `argument_class` on our base classes for all of `Field`, `InputObject`, `Mutation`

```ruby
argument_class Arguments::Base
```

```ruby
require_relative "../arguments/base"

module Vydia
  module GraphQL
    module V1
      module Types
        module Fields
          class Base < ::GraphQL::Schema::Field

            argument_class Arguments::Base

            TYPE_PREFIX = "Vydia::GraphQL::V1::Types::".freeze

            # - Override type with a prefix in some cases
            # - Override camlize to false
            def initialize(type:, camelize: false, **rest, &block)
              # If the type is given as a string, add TYPE_PREFIX _unless_ it's:
              # - a global constant, scoped with a leading `::`
              # - a constant _already_ prefixed with TYPE_PREFIX
              # - a constant that references one of GraphQL's default types in GraphQL::Types
              case type
              when Array
                type[0] = maybe_prepend_module_prefix(type[0])
              else
                type = maybe_prepend_module_prefix(type)
              end

              # Forward all args, including the maybe-modified `type`
              super(:type => type, :camelize => camelize, **rest, &block)
            end

            private

            def maybe_prepend_module_prefix(type)
              type = "#{TYPE_PREFIX}#{type}" if type.is_a?(String) && !type.start_with?("::") && !type.start_with?(TYPE_PREFIX) && !protected_type?(type)

              type
            end

            def protected_type?(type)
              type == "Integer" || ::GraphQL::Types.constants.include?(type.to_sym)
            end

          end
        end
      end
    end
  end
end
```

and then placing `field_class` on our base classes for all of `Interfaces`, `Mutations`, `Objects`, `Roots`

```ruby
field_class Fields::Base
```

I understand not wanting to add unnecessary bloat to the base graphql-ruby library, but in my opinion this was much more complex and fiddly to implement than I think it should have to be ideally, and I think even this code has some cases that are not handled well. If you have any ideas at all how to implement this, maybe as a separate plugin gem, it might help others.

Thanks again!

**Comment by rmosolgo** [comment]
Glad it worked ok! Here's the method where any ol' type input is resolved to a proper GraphQL type definition: 

https://github.com/rmosolgo/graphql-ruby/blob/ecadc49c1c369769d7db8f23592d8703f0b7f8a0/lib/graphql/schema/member/build_type.rb#L10-L95

It's quite a mess -- but you can see how it calls itself when it gets a string like `[...]` (a list type). Finally, when it has a string and we thing the string is the name of a Ruby class, we call `.constantize`: 

https://github.com/rmosolgo/graphql-ruby/blob/ecadc49c1c369769d7db8f23592d8703f0b7f8a0/lib/graphql/schema/member/build_type.rb#L128-L158

If you wanted a more robust addition of a prefix, you might be able to hook in there, although I can't promise that it's a very stable API! For example, you could use the old `alias` chain trick: 

```ruby 
module GraphQL::Schema::Member::BuildType 
  class << self 
    alias old_constantize constantize
    def constantize(str)
      old_constantize(PREFIX + str) 
    end 
  end 
end 
```

Like I said, I can't promise it wouldn't break, so you'd just have to keep an eye on that behavior when you update graphql-ruby versions!

**Comment by TSMMark** [comment]
I agree, it seems like overriding constantize as you recommended and as I mentioned in OP is more straightforward. Able to remove overrides in Base Field and Base Argument and just override the `Member::BuildType.constantize`. Here's what we're using now, for posterity:

```ruby
module ::GraphQL::Schema::Member::BuildType

  TYPE_PREFIX = "Whatever::Module::Namespace::Types::".freeze

  class << self

    alias_method :old_constantize, :constantize

    # If the type is given as a string, add TYPE_PREFIX _unless_ it's:
    # - a global constant, scoped with a leading `::`
    # - a constant _already_ prefixed with TYPE_PREFIX
    # - a constant that references one of GraphQL's default types in GraphQL::Types
    def constantize(str)
      old_constantize(maybe_prepend_module_prefix(str))
    end

    private

    def maybe_prepend_module_prefix(type)
      type = "#{TYPE_PREFIX}#{type}" if type.is_a?(String) && !type.start_with?("::") && !type.start_with?(TYPE_PREFIX) && !protected_type?(type)

      type
    end

    def protected_type?(type)
      type == "Integer" || ::GraphQL::Types.constants.include?(type.to_sym)
    end

  end

end
```
