### ISSUE TITLE
Relay connection edge can be null?

### ISSUE THREAD

**Issue by djchen** [rmosolgo/graphql-ruby#2631]
Version 1.9.16

The edges field in a Relay connection is defined as being nullable. I'm trying to understand why it would be null? If there are no edges, shouldn't it return an empty array?

In base_connection.rb:
```
          def edge_type(edge_type_class, edge_class: GraphQL::Relay::Edge, node_type: edge_type_class.node_type, nodes_field: true)
            # Set this connection's graphql name
            node_type_name = node_type.graphql_name

            @node_type = node_type
            @edge_type = edge_type_class
            @edge_class = edge_class

            field :edges, [edge_type_class, null: true],
              null: true, # Right here
              description: "A list of edges.",
              edge_class: edge_class

            define_nodes_field if nodes_field

            description("The connection type for #{node_type_name}.")
          end
```

For example, I would expect to get this:
```
{
  "data": {
    "someQuery": {
      "edges": []
    }
  }
}
```
(which is the current behavior I'm seeing)

Thank you!

**Comment by rmosolgo** [comment]
It depends on the backend. How is the connection _implemented_? Since I don't know how different applications are implemented, I interpreted the spec that way. To build connection types with non-null fields, see the solution suggested here: https://github.com/rmosolgo/graphql-ruby/issues/1217#issuecomment-422884621

Hope that helps! Please let me know if it doesn't address your issue.

**Comment by djchen** [comment]
Just wanted to circle back and say thanks. I was able to copy the shortcut for [`connection_type` and `edge_type`](https://github.com/rmosolgo/graphql-ruby/blob/6a6ee63f57476f3a4ddee8b25ed09d89494c1104/lib/graphql/schema/member/relay_shortcuts.rb#L23-L43) into my own `base_object` and change `node_type(node_type_class)` to `node_type node_type_class, null: false`.

**Comment by anark** [comment]
I was able to make the array items non-null by overriding the following in my BaseConnection

```
      def self.define_nodes_field
        field :nodes, [@node_type],
          null: true,
          description: "A list of nodes."
      end
```

Not sure if this is the best approach but it seems to be the smallest change possible that gives back an array that doesn't contain null items.
