### ISSUE TITLE
How to set an argument description?

### ISSUE THREAD

**Issue by duffyjp** [rmosolgo/graphql-ruby#2635]
I looks like I should be able to set an argument description in GraphQL:

https://www.rubydoc.info/github/rmosolgo/graphql-ruby/GraphQL/Argument
```ruby
GraphQL::Field.define do
  # ...
  argument :favoriteFood, types.String, "Favorite thing to eat", default_value: "pizza"
end
```

I'm using what I understand to be the ~2018+ syntax that looks different.  I tried this:

```ruby
argument :favorite_food, String, description: "Favorite thing to eat", required: false
```

and this:

```ruby
argument :favorite_food, String, required: false do
  description: "Favorite thing to eat"
end
```

But nothing comes across in the GraphiQL screen.  It does work for fields, just not arguments.

Is this possible?  I have some arguments I'd like to explain how to use in the GraphiQL interface and don't want to put everything in the root-level field's description if possible.

**Comment by rmosolgo** [comment]
Hi! Sorry about the hangup. It should work just like you showed in the first example, `argument ..., description: "Favorite thing to eat"` 

When GraphiQL loads, it sends an "introspection query" to fetch the schema structure. I'm curious to see that query (to make sure it includes argument descriptions) and the result (to see if the argument description is present). Can you spot that request in your browser's network tab? For example, the `POST` here: 

![image](https://user-images.githubusercontent.com/2231765/70355011-1b679180-183f-11ea-8895-a2c15915747a.png)


Can you spot that request in your browser? If you can, could you share the response to it? I'm curious to see if the configured description is present in the response.

**Comment by duffyjp** [comment]
GraphQL is correctly returning the description in the POST response: 

```
     {
                  "name": "definition",
                  "description": "This should appear",
                  "type": {
                    "kind": "SCALAR",
                    "name": "String",
                    "ofType": null
                  },
                  "defaultValue": null
                },
```

Turns out to be a [pebcak](https://en.wiktionary.org/wiki/PEBCAK) error.  


---------------


![argument_description 2019-12-09 10_51_46](https://user-images.githubusercontent.com/382216/70455513-0f174a80-1a72-11ea-925b-31510676338d.gif)

**Comment by rmosolgo** [comment]
Glad you got to the bottom of it! Thanks for following up.
