### ISSUE TITLE
How can I get mutation/query name?

### ISSUE THREAD

**Issue by wis-ekubesh** [rmosolgo/graphql-ruby#2638]
Hi. For some actions I need to know in GraphqlController what is the name or some another identifier of current mutation/query. `operation_name` it's is a thing what can be random.

I need to know requested field name, like `field :refresh_token` (refresh_token). 

How can I get this?

**Comment by rmosolgo** [comment]
It sounds like you want to get the names of the _root fields_ in any incoming query or mutation, is that right? 

If so, you can get this from [`Query#lookahead`](https://graphql-ruby.org/api-doc/1.9.11/GraphQL/Query.html#lookahead-instance_method), which returns an [`Execution::Lookahead`](https://graphql-ruby.org/api-doc/1.9.11/GraphQL/Execution/Lookahead.html) instance: 

```ruby 
query.lookahead.selections.map(&:name) 
# [:refresh_token, ...] 
```

Some places you might use this are: 

- AST Analyzer (runs before the query is executed) https://graphql-ruby.org/queries/ast_analysis.html
- Query instrumenter (also runs before the query is executed) https://graphql-ruby.org/queries/instrumentation.html

I hope that helps! If you give it a try and run into problems, please share the code that you tried and what happened when you tried it.
