### ISSUE TITLE
uninitialized constant GraphQL::Subscriptions::ActionCableSubscriptions):

### ISSUE THREAD

**Issue by Sibgha228** [rmosolgo/graphql-ruby#2641]
**Graphql version: 1.9.16**

Hi I was trying to add subscriptions to the project but adding this line to graphql scehma is leading to the above error.

```
class AppSchema < GraphQL::Schema
  use GraphQL::Subscriptions::ActionCableSubscriptions
  mutation(Types::MutationType)
  query(Types::QueryType)
  subscription(Types::SubscriptionType)
end
```

**Comment by rmosolgo** [comment]
Sorry about that! 

ActionCableSubscriptions is only loaded by graphql-ruby if it detects ActionCable at load time: 

https://github.com/rmosolgo/graphql-ruby/blob/734ad4bee373ec1c213f40fc65bab533da420f49/lib/graphql/subscriptions.rb#L6-L8

Maybe that didn't work in your case :S 

How about adding an explicit 

```ruby
require "graphql/subscriptions/action_cable_subscriptions"
```

To your `app_schema.rb` file? That way, you can be sure it was loaded. 

If that doesn't fix the problem, could you please share the _full_ error message and backtrace?

**Comment by rmosolgo** [comment]
I hope that helped!
