### ISSUE TITLE
Cannot use `GraphQL::Types::Relay::Node`

### ISSUE THREAD

**Issue by dteoh** [rmosolgo/graphql-ruby#2642]
I started a new Rails 6 project and am using 1.9.16 of the gem. I haven't been able to get the Relay setup working. Eventually I decided to write the bare minimum implementation, but it still does not work. My query class:

```ruby
module Types
  class QueryType < Types::BaseObject

    # this does not seem to work
    # add_field GraphQL::Types::Relay::NodeField

    # works, can query this field OK!
    field :foo, String, null: false
    def foo
       'bar'
    end

    # does not work?
    field :bar, GraphQL::Types::Relay::Node, null: true
    def bar
      nil
    end
  end
end
```

My query:

```
query Q {
  bar {
    id
  }
}
```

I always get `Field 'bar' doesn't exist on type 'Query'`. Querying for `foo` field works, so I'm a bit puzzled.

My app schema:

```ruby
class ApplicationSchema < GraphQL::Schema
  query Types::QueryType
  mutation Types::MutationType

  use GraphQL::Execution::Interpreter
  use GraphQL::Analysis::AST

  def self.id_from_object(obj, type_def, ctx)
    obj.relay_global_id
  end

  def self.object_from_id(id, ctx)
    ApplicationRecord.global_find id
  end

  def self.resolve_type(type, obj, ctx)
    case obj
    when User then Types::User
    else
      raise "Unhandled object type: #{obj.class}"
    end
  end
end
```

I have tried with and without `use GraphQL::Execution::Interpreter; use GraphQL::Analysis::AST` and got the same results. Is there some other magic I need to switch on to make Relay integration work?

**Comment by swalkinshaw** [comment]
I can't see your entire schema but you need two things:

1. `Types::User` has to implement the Node interface: `implements GraphQL::Types::Relay::Node`
2. since no field directly returns the `Types::User` type, you need to define it as an orphan type on the schema:

```ruby
class ApplicationSchema < GraphQL::Schema
  query Types::QueryType
  mutation Types::MutationType
  orphan_types(Types::User)

  # etc
end
```

**Comment by dteoh** [comment]
> I can't see your entire schema but you need two things:

That is all there is to it.

> since no field directly returns the Types::User type, you need to define it as an orphan type on the schema:

Thank you! This was the magic I needed.

Is there a reason why I would get `Field 'bar' doesn't exist on type 'Query'` as an error message? I don't quite understand why a type not yet connected to the schema would make the field disappear, since there is no reference in my query for a user object.

**Comment by swalkinshaw** [comment]
Not sure if this gem has a good explanation, but graphql-js does: https://github.com/graphql/graphql-js/blob/538aa696c66c756af490462310ec31db9d82c319/src/type/schema.js#L60-L109
