### ISSUE TITLE
Cursor pagination problems with date fields

### ISSUE THREAD

**Issue by szanella** [rmosolgo/graphql-ruby#2649]
I've been experiencing pagination issues using cursor based pagination when I sort my model by the `created_at` column.
What happens is the following:

- when I query for the first n items, say 2, I get the correct ones (1st and 2nd);
- when I query for the next 2, using the `after` and `first` arguments together, I again get the correct ones (3d and 4th);
- when I ask again for the first page, but this time navigating back from the second (using the `before` and `last` arguments) what I get are not the 1st and 2nd item, but the 2nd and 3rd.

Here are the aforementioned examples, with their responses underneath:
Page 1
```
{
  p1: testConn(first: 2) {
    edges {
      node {
        id
      }
      cursor
    }
    pageInfo {
      startCursor
      endCursor
    }
  }
}

{
  "data": {
    "p1": {
      "edges": [
        {
          "node": {
            "id": "47",
            "sequenceNumber": 32
          },
          "cursor": "WyIyMDE5LTEyLTAyIDE0OjQzOjQ0IFVUQyIsNDdd"
        },
        {
          "node": {
            "id": "46",
            "sequenceNumber": 31
          },
          "cursor": "WyIyMDE5LTEyLTAyIDE0OjQwOjQ2IFVUQyIsNDZd"
        }
      ],
      "pageInfo": {
        "startCursor": "WyIyMDE5LTEyLTAyIDE0OjQzOjQ0IFVUQyIsNDdd",
        "endCursor": "WyIyMDE5LTEyLTAyIDE0OjQwOjQ2IFVUQyIsNDZd"
      }
    }
  }
}
```
Page 2
```
{
  p2: testConn(first: 2, after: "WyIyMDE5LTEyLTAyIDE0OjQwOjQ2IFVUQyIsNDZd") {
    edges {
      node {
        id
        sequenceNumber
      }
      cursor
    }
    pageInfo {
      startCursor
      endCursor
    }
  }

  {
  "data": {
    "p2": {
      "edges": [
        {
          "node": {
            "id": "45",
            "sequenceNumber": 30
          },
          "cursor": "WyIyMDE5LTEyLTAyIDE0OjQwOjI3IFVUQyIsNDVd"
        },
        {
          "node": {
            "id": "44",
            "sequenceNumber": 29
          },
          "cursor": "WyIyMDE5LTEyLTAyIDE0OjM5OjA2IFVUQyIsNDRd"
        }
      ],
      "pageInfo": {
        "startCursor": "WyIyMDE5LTEyLTAyIDE0OjQwOjI3IFVUQyIsNDVd",
        "endCursor": "WyIyMDE5LTEyLTAyIDE0OjM5OjA2IFVUQyIsNDRd"
      }
    }
  }
}
```
Back to page 1
```
{
  bp1: testConn(last: 2, before: "WyIyMDE5LTEyLTAyIDE0OjQwOjI3IFVUQyIsNDVd") {
    edges {
      node {
        id
        sequenceNumber
      }
      cursor
    }
    pageInfo {
      startCursor
      endCursor
    }
  }
}

{
  "data": {
    "bp1": {
      "edges": [
        {
          "node": {
            "id": "46",
            "sequenceNumber": 31
          },
          "cursor": "WyIyMDE5LTEyLTAyIDE0OjQwOjQ2IFVUQyIsNDZd"
        },
        {
          "node": {
            "id": "45",
            "sequenceNumber": 30
          },
          "cursor": "WyIyMDE5LTEyLTAyIDE0OjQwOjI3IFVUQyIsNDVd"
        }
      ],
      "pageInfo": {
        "startCursor": "WyIyMDE5LTEyLTAyIDE0OjQwOjQ2IFVUQyIsNDZd",
        "endCursor": "WyIyMDE5LTEyLTAyIDE0OjQwOjI3IFVUQyIsNDVd"
      }
    }
  }
}
```

Note that this does not happen unless I order my records by a date column in the resolver.

I analysed what's done underneath, and from what I've seen the pagination is handled by encoding the columns involved in the query ordering into a cursor, which is then used to produce a query that uses these items to perform comparisons. 
The problem with date columns is that the encoded value looks like this: `["2019-12-02 14:43:44 UTC",47]` (along with the date column, I saw that the library also involves the `id` column, which I understand why)
The actual value inside the database, though, will not exactly be `2019-12-02 14:43:44` down to the milliseconds, but most times it will be slightly bigger, say `2019-12-02 14:43:44.102`. 

When we're paginating forwards (mind that my ordering by date is descending), the query looks like this:
`SELECT quotation_requests.*, quotation_requests.created_at AS cursor_0, quotation_requests.id AS cursor_1 FROM "quotation_requests" WHERE (((quotation_requests.created_at < '2019-12-02 14:40:46 UTC') OR (quotation_requests.created_at = '2019-12-02 14:40:46 UTC' AND quotation_requests.id > 46))) ORDER BY "quotation_requests"."created_at" DESC, quotation_requests.id asc LIMIT 3 `
which works great, but when paginating backwards, the query looks like this:
`SELECT quotation_requests.*, quotation_requests.created_at AS cursor_0, quotation_requests.id AS cursor_1 FROM "quotation_requests" WHERE (((quotation_requests.created_at > '2019-12-02 14:40:27 UTC') OR (quotation_requests.created_at = '2019-12-02 14:40:27 UTC' AND quotation_requests.id < 45))) ORDER BY "quotation_requests"."created_at" ASC, quotation_requests.id DESC LIMIT 3`
which gives problems, because the value we're using as pivot has it's `created_at` value which will be slightly bigger than the one we're using for our comparison, and will therefore be included in the result.

A solution that might work would be to encode a precise value down to the milliseconds to obtain accurate comparisons.

**Comment by szanella** [comment]
Sorry I've accidentally posted this before finishing writing it, I'll edit it to complete it and submit it again

**Comment by rmosolgo** [comment]
Thanks for the detailed report! Which version of graphql-pro are you using? 1.10.8 [added more precise cursors for DateTimes](https://github.com/rmosolgo/graphql-ruby/blob/master/CHANGELOG-pro.md#1108-8-oct-2019), but honestly, I was working entirely from similar bug reports -- I couldn't reproduce the issue properly locally! It seemed like something in my environment was causing datetimes to be stringified with milliseconds by default. 

Are you using 1.10.8+? If not, could you try that version, at least?

**Comment by szanella** [comment]
Works like a charm, thank you!
Sorry about not realising sooner that the issue had already been taken care of.

**Comment by rmosolgo** [comment]
🤘 Glad to hear it. Let me know if I can help with anything else!
