### ISSUE TITLE
Schema loader and default value types

### ISSUE THREAD

**Issue by swalkinshaw** [rmosolgo/graphql-ruby#265]
Loading a schema from an introspection result errors for any arguments which have a `defaultValue` of a non-String type.

> Query is invalid: field "post" argument "integer" default value "1" is not valid for type Int (GraphQL::Schema::InvalidTypeError)

Here's a reduced test case:

```ruby
PostType = GraphQL::ObjectType.define do
  name 'Post'
  description 'A blog post'

  field :id, !types.ID, resolve: ->(*) {
    'id'
  }
end

QueryType = GraphQL::ObjectType.define do
  name 'Query'
  description 'The query root of this schema'

  field :post do
    type PostType
    argument :id, !types.ID
    argument :integer, GraphQL::INT_TYPE, default_value: 1
    resolve -> (obj, args, ctx) do
    end
  end
end

Schema = GraphQL::Schema.define do
  query QueryType
end

introspection_result = Schema.execute(GraphQL::Introspection::INTROSPECTION_QUERY)

schema = GraphQL::Schema::Loader.load(introspection_result)
puts schema.types
```

Executing `schema.types` results in the error since it fails `GraphQL::Schema::Validation`.

/cc @theorygeek

**Comment by rmosolgo** [comment]
I think this was fixed by #267, please reopen if you're still seeing it!
