### ISSUE TITLE
Combining List and Non-Null does not behave properly with [T!]!

### ISSUE THREAD

**Issue by mcrampon** [rmosolgo/graphql-ruby#2661]
According to [the graphQL specification](https://github.com/graphql/graphql-spec/blob/master/spec/Section%203%20--%20Type%20System.md#combining-list-and-non-null), a `[T!]!` type should error out in case one of the elements in the list is `null`.

It apparently is not the case with graphql-ruby.

Here is an example query, ran with graphql-ruby 1.9.17:

```ruby
class Foo < GraphQL::Schema::Resolver
  type [Int], null: false

  def resolve
    [1, 2, nil, 3, 4]
  end
end
```

### What is currently happening:

The result I get is this:
```json
{
  "data": null
}
```

No error is returned, no exception is raised.

### What I expect

```json
{
  "data": null,
  "errors": [
    {
      "message": "Cannot return null for non-nullable element of list field Query.foo"
    }
  ]
}
```

### Question

Is that only happening within my application / my setup, or is it a general bug of graphql-ruby? Could anyone confirm or refute my findings?

### Note
I think it happens also with mutation fields. To be tested.

**Comment by rmosolgo** [comment]
Thanks for the detailed report! I agree it should work the way you described here. 

Regarding your question, I think the next step is to add a test to the gem's test suite and see if the bug appears there. For example, you can see here a test which builds a small schema then runs queries with it: 

https://github.com/rmosolgo/graphql-ruby/blob/352768809c1448e599bed0a05fc9c7d59c063f44/spec/graphql/schema/list_spec.rb#L47-L73

I think you could copy and modify that test to demonstrate the issue you've described here. Then, if you open a PR with a failing test, I'd be happy to help you hunt down the source of the misbehavior!

**Comment by mcrampon** [comment]
Alright, will do that during the weekend probably 🙂

**Comment by mcrampon** [comment]
Alright, managed to write a quick test: can't reproduce. I do get a proper error in the test, saying `Cannot return null for non-nullable field Query....`

Closing the issue, as this is most likely a problem in my own application / setup.

Thanks for the help anyway!
