### ISSUE TITLE
max_page_size does not substitute first/last for hasNextPage check

### ISSUE THREAD

**Issue by rbviz** [rmosolgo/graphql-ruby#2662]
Supposedly previously fixed with #2608 now seems to be broken again/still.

Easy to reproduce by setting `default_max_page_size` or `max_page_size` less than actual record count and not passing first/last arguments to connection_type field query.

hasNextPage always return false regardless of actual page count

tested with 1.9.16/1.9.17, ActiveRecord relation

**Comment by rmosolgo** [comment]
Hi, sorry for the trouble! #2608 is a patch for the 1.10 branch. You'll find it on 1.10.0.pre2 on RubyGems. (I have a few loose ends to tie up before I call it 1.10.0, but I've been running 1.10-dev in production for many months.) 

Please give that version a try and let me know if you run into trouble with it!
