### ISSUE TITLE
Need a way to inspect _sibling_ fields' lookaheads

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#2663]
We need some way to handle a situation like this: 

```graphql
... on Something {
  items {
    id 
  }
  things {
    # ... stuff 
  }
}
```

Where `things` can be optimized if `items` has exactly one selection, `id`. 

This can kind of be hacked, by injecting a `lookahead` into every field that returns `Something`, and passing it down with scoped_context, but that's error-prone.

**Comment by bmorton** [comment]
We're currently working around this by injecting the lookahead at the root Query/Mutation level and keeping that in the context object.  From there, we can use the current path to traverse the lookahead to find the siblings.

**Comment by rmosolgo** [comment]
I'm glad you found a good solution. I haven't found the time to work on this, and since nobody else is asking for it now, I'm going to close it. Happy to dig in again later if need be.
