### ISSUE TITLE
GraphQL Pro installation failure

### ISSUE THREAD

**Issue by yjaspar** [rmosolgo/graphql-ruby#2681]
Hello!

Since yesterday we are experiencing some issues when running `rake graphql:pro:validate`.

```
➜  atrium-web git:(authorization-cancan) rake graphql:pro:validate
Validating graphql-pro v
  - Checking for graphql-pro credentials...
    ✓ found
  - Fetching the gem...
ERROR:  While executing gem ... (Gem::Requirement::BadRequirementError)
    Illformed requirement ["--source"]
    ✘ failed to fetch v
```

I believe that it was working the day before yesterday, and I was wondering if you could help me debug / resolve this issue?

Thank you for your work!

**Comment by rmosolgo** [comment]
Oops, sorry about the hangup! That rake task requires a specific version number, for example: 

```
$ bundle exec rake graphql:pro:validate[1.12.2]
# ... 
```

However, it didn't have a check to _make sure_ that input was provided 🤦‍♂ . I've added a check in 552658624. Now, it fails with a helpful error: 

```
$ be rake graphql:pro:validate
rake aborted!
ArgumentError: A specific version is required, eg `rake graphql:pro:validate[1.12.0]`
/Users/rmosolgo/code/graphql-ruby/lib/graphql/rake_task/validate.rb:11:in `block in <class:RakeTask>'
/Users/rmosolgo/.rbenv/versions/2.6.3/bin/bundle:23:in `load'
/Users/rmosolgo/.rbenv/versions/2.6.3/bin/bundle:23:in `<main>'
Tasks: TOP => graphql:pro:validate
```

That requirement is also documented here: https://graphql-ruby.org/pro/installation#verifying-integrity

Does it work properly when you include a version?

**Comment by yjaspar** [comment]
Thank you very much!
