### ISSUE TITLE
Guide: Authorization

### ISSUE THREAD

**Issue by sincospi** [rmosolgo/graphql-ruby#2685]
It isn’t clear where/how to implement `#authorized?(value, context)` instance methods for Fields.

**Comment by stevecrozz** [comment]
You can implement this method on your own custom field class. See https://graphql-ruby.org/type_definitions/extensions.html#customizing-fields

**Comment by sincospi** [comment]
Thanks for pointing that out @stevecrozz .

However, if this is the case, the `#authorized?(value, context)` method is not very useful at all - since all fields are subject to the same validation logic. Am I missing something here?
