### ISSUE TITLE
Custom type definition for list manipulations (filtering scope, pagination, sorting)

### ISSUE THREAD

**Issue by amkisko** [rmosolgo/graphql-ruby#2693]
I was looking for custom implementation of pagination that will suit my requirements that are listed below.

Any ideas on improvement or downsides of such implementation? I am afraid of dynamic type definition, but couldn't find any other way to avoid creation of "files" with new types.

Use case requirements:
* return ordered and paginated `rows` and `totalCount` for current search and filter scope (common structure for lists)
* allow more operations on current field (arguments, extensions, etc?)
* use custom resolver
* reusable method(s)
* less code for each list field
* “dynamic” graph changes (?)

[Code](https://gist.github.com/amkisko/f77e72066b7a2d200a2aad4210c3a1eb):
```ruby
module Types
  class BaseObject < GraphQL::Schema::Object
    field_class Types::BaseField

    def self.listable(name, object_type, name_suffix: "", override_options: {})
      list_type = GraphQL::ObjectType.define do
        name "#{name}#{name_suffix}"
        field :rows, object_type.to_list_type do
          resolve -> (object, args, _ctx) { object }
        end
        field :totalCount, types.Int do
          resolve -> (object, args, _ctx) { object.unscope(:limit, :offset, :order).size }
        end
      end
      default_field_options = { type: list_type, null: false }
      field_options = default_field_options.merge(override_options)
      field(name, **field_options) do
        argument :offset, Integer, required: false
        argument :limit, Integer, required: false
        argument :efilter, GraphQL::Types::JSON, required: false
        argument :order, GraphQL::Types::JSON, required: false
        argument :search, String, required: false
        yield self if block_given?
      end
    end

    def query_efilter(query, filter)
      # NOTE: https://gitlab.com/snippets/1788967
      if filter.present?
        query.efilter(filter)
      else
        query
      end
    end
  
    def query_order(query, order)
      if order.present?
        order.reduce(query) { |q, o| q.safe_order(o.first, o.last) }
      else
        query
      end
    end
  
    def query_paginate(query, offset, limit)
      query.offset(offset || 0).limit(limit || 25)
    end
  
    def reduce_query(query, offset: nil, limit: nil, order: nil, efilter: nil, search: nil)
      query = query_efilter(query, efilter)
      query = query_order(query, order)
      query_paginate(query, offset, limit)
    end
    
    listable :abuses, Types::AbuseType, name_suffix: "_root" do |field|
      field.argument :author_id, ID, required: false
      field.argument :author_type, String, required: false
    end
    def abuses(author_id: nil, author_type: nil, **options)
      cursor = Abuse.for_user(context[:current_user])
      reduce_query(cursor, **options)
    end
  end
end
```

**Comment by rmosolgo** [comment]
Personally, I think you're on the right track. An approach like that is how this library builds connection types, too: 

https://github.com/rmosolgo/graphql-ruby/blob/55265862420b545cbdac89c99383bf91261b4846/lib/graphql/schema/member/relay_shortcuts.rb#L23-L43

In this case, they get their `field...` definitions from their base classes, for example: 

https://github.com/rmosolgo/graphql-ruby/blob/55265862420b545cbdac89c99383bf91261b4846/lib/graphql/types/relay/base_connection.rb

Anyway, I think you're on the right track! The only thing I'd change is to swap `ObjectType.define` for `Class.new(Types::BaseObject) { ... }` , so that the generated types properly inherit from your base class. 

Let me know if you run into any specific trouble with it!

**Comment by konsilito** [comment]
@rmosolgo thanks for review and advice!

**Comment by amkisko** [comment]
@rmosolgo thanks for review and advice!

**Comment by amkisko** [comment]
```ruby
      list_type = GraphQL::ObjectType.define do
        name "#{name}#{name_suffix}"
```
@rmosolgo any thoughts how do I find already defined GraphQL Type by name for further usage?

**Comment by rmosolgo** [comment]
There's nothing _particular_ to find it. I'd recommend something like a _cache_ on the underlying object type. For example: 

```
class Types::BaseObject < GraphQL::ObjectType
  def self.listable_type(name, suffix: "")
    full_type_name = name + suffix
    @listable_types ||= {} 
    @listable_types[full_type_name] ||= begin 
      # generate class here
    end 
  end
end 
```

It's not thread-safe as written, which can be a problem with multithreaded servers that load code gradually. I haven't run into that problem personally, but I think some folks running Puma have, so I share it in case you run into it!

**Comment by amkisko** [comment]
Possibly avoid multithreading issues by using `request_store`?
