### ISSUE TITLE
hasNextPage check causes extremely slow queries to be run

### ISSUE THREAD

**Issue by raysuelzer** [rmosolgo/graphql-ruby#2695]
After updating to the latest verison, there were some breaking changes to pagination.  One being that the `nodes` property now was limited, and in order to get a `totalCount` the `items` property had to be used. 

https://github.com/rmosolgo/graphql-ruby/issues/2662

More of a problem is that I noticed queries like the following being executed, even when I am not requesting hasNextPage or hasPreviousPage.  

```
(4125.0ms)  SELECT COUNT(*) FROM (SELECT 1 AS one FROM "people" INNER JOIN "campaigns_people" ON "campaigns_people"."person_id" = "people"."id" WHERE "campaigns_people"."campaign_id" = $1 OFFSET $2) subquery_for_count
```
Is there a way to NOT fire this query unless we are asking for hasNextPage?  On large tables or complicated queries it is extremely slow.

**Comment by raysuelzer** [comment]
I tracked down the issue to `relation_count`  I am not entirely sure what it is being used for but doing the following seemed to have no impact on cursors, pagination, or results.  I wrote my own Connections wrapper and modified it to limit the relations count to 10, as an arbitrary number to limit. 

Like I said, it seems to have had no impact on the pageInfo results or the edges / nodes being returned.  

```
class Connections::OptimizedActiveRecordConnection < GraphQL::Pagination::ActiveRecordRelationConnection
  # Overrides default usage and sets a limit when determining the relation
  # count.  This is a bit hacky, but works for now and avoids very long queries from running.
  def relation_count(relation)
    if relation.respond_to?(:unscope)
      relation.unscope(:order).limit(10).count(:all)
    else
      # Rails 3
      relation.limit(10).count
    end
  end
end
```

**Comment by rmosolgo** [comment]
Thanks for the detailed report! I've opened #2697 to address it, let me know what you think.
