### ISSUE TITLE
Post processing nodes for connection_type

### ISSUE THREAD

**Issue by vgunawan** [rmosolgo/graphql-ruby#2696]
Hi!

I am looking into how to apply `connections` type into our existing graphql endpoints. It works pretty seamlessly for any type of relational object such as ActiveRecord::Relation. However this is not what we have unfortunately. 

I have considered to implement custom connection, however I can't figure out how to use that to solve the atm. So to give brief example, here what a typical field resolve looks like in the codebase

```
field :active_users, UserObject.connection_type, ...
... 
def active_users
   # returns a [] of Users
   UseCases::Users::Active.call()
end
```

Now inside the `UseCase` itself I will be making ActiveRecord call, no magic there. In this case it will be doing something like `User.where.not(activate_at: nil)`.  From there, our `UseCase` will often do other bits and pieces,  such as authorization and other business logic processing.

You may have identified my problem now, I am  not working with `ActiveRecord::Relation` object as the output of the UseCase.

Is there some sort of a work around this or a good way to solve this? What I can think of at the moment is to do some sort of `afterSlicedNodes()` call back method / proc / lambda, where then I can apply post processing after the nodes has been sliced for the connection. This nodes then can be passed in to the  `UseCase` object to be further processed. 

My apologies if this has been discussed in the past but I have not been able to find any discussion related to it.

**Comment by rmosolgo** [comment]
Hi, sounds tricky! It sounds like you need to _integrate_ GraphQL's connection logic with `UseCase`'s logic, is that right? 

If so, I have two suggestions: 

- Creating a custom connection might work. It's a lot easier on 1.10.0 and you can find the new docs here: https://graphql-ruby.org/pagination/overview.html
- Alternatively, you could pass `field(..., connection: false)` to disable GraphQL-Ruby's automatic connection handling. Then, you could add `argument :first, Int, required: false` and so on -- adding the connection arguments -- and they would appear in your resolver like normal arguments, as `def active_users(first: nil, after: nil, last: nil, before: nil)`. When those values are passed into the method, you could them pass them to the `UseCase` code and implement pagination yourself. 

Does either of those sound good? If you give it a try, please share what you find!

**Comment by vgunawan** [comment]
Thanks for the reply! I did not realise that this has changed in `1.10` I am still using `1.9.2`.

It seems that the `Connection` class has been improved so it has more sensible interface in my opinion, which is great 👍 .

I have not yet give it a try yet, however it seems the `Connection` wrapper still have the same issue I faced in `1.9.2`. The issue here is that `Connection` wrapper, executes *after* the resolve function finished, which in this case my `UseCase` yields a static `List` and not some sort of `ActiveRecord:Relation`. So in the custom `Connection` class, I don't have enough information to create `cursor_for` or `has_next_page`. I guess I can make the result that came out of the `UseCase` to include this information, however I don't fancy that because now my `UseCase` classes will now need to worry about pagination. A concern that `Connection` class is perfect for!

In fact, I can totally use the provided `GraphQL::Pagination::ActiveRecordRelationConnection`, if somehow we can make the `Connection` class execute *before* the `UseCase` and pass the paginated nodes to `UseCase` or any type of business logic that anyone wish. This is where I think the `afterSlicedNodes`, or, in the new interface it would be just `afterNodes` or some better naming, is really powerful. 

So perhaps something like this in `resolve` method would be nice

```
def active_users
   GraphQL::Pagination::ConnectionResult.new(
      nodes: UseCases::Users::Active.base_query <this is ActiveRecord::Relation>,
      post_process: -> (paginated_nodes) { UseCases::Users::Active.call(paginated_nodes) }
   )
end
```

wdyt? maybe i can create a PR for this, may need some pointers from you where best to call `post_process` block however from `GraphQL::Pagination::Connection`, assuming this is the new `BaseConnection` class.

In my opinion, `Connection` wrapper is a really nice design because of its tight responsibility in providing pagination.

**Comment by rmosolgo** [comment]
Hmm, if you want to customize the paginated nodes, how about doing it in a custom wrapper? 


```ruby 
class ActiveUsersConnection < GraphQL::Pagination::ActiveRecordRelationConnection 
  def nodes 
    unprocessed_paginated_nodes = super 
    processed_nodes = UseCases::Users::Active.call(unprocessed_paginated_nodes)
    @nodes = processed_nodes 
  end 
end 
```

Then, hook it up in the field:

```ruby 
def active_users 
  ActiveUsersConnection.new(UseCases::Users::Active.base_query)
end 
```

(This should work in 1.10+ with `use GraphQL::Pagination::Connections` in your schema definition)

That way, you can pass in the relation to the connection, allow it to run pagination, then modify the nodes before continuing to execute the query. 

I hope that helps!
