### ISSUE TITLE
1.10.0, GraphQL::Schema::InputObject argument and instance prepare

### ISSUE THREAD

**Issue by dteoh** [rmosolgo/graphql-ruby#2698]
Just a couple of questions...

In 1.9.x, I have some custom `GraphQL::Schema::InputObject` subclasses with arguments like:

```
argument :pairs, [KeyValue], required: true, prepare: ->(kv_array, ctx) {
  # assume that each KeyValue object prepares into an array [k, v]
  # so kv_array is an array [[k1, v1], [k2, v2], ...]
  Hash[kv_array]
}
```

This works and my resolver will get `{k1: v1, k2: v2}` as the value for the `pairs` argument.

However after installing 1.10.0, I am now getting these warnings:

```
warning: wrong element type Hash at0 (expected array)
warning: ignoring wrong elements is deprecated, remove them explicitly
warning: this causes ArgumentError in the next release
```

Can I get some advice on how I am supposed to accomplish the same result as 1.9.x?

Same subclass, overriding prepare:

```
def prepare
  self.to_h
end
```

This used to work, eg. I would then get `{ pairs: { k1: v2, k2: v2 } }` in the mutation that uses my custom input object. Now in 1.10.0, it seems like this functionality is gone. I get the InputObject instance instead. How can I accomplish the same result as 1.9.x?

**Comment by dteoh** [comment]
I tried v1.10.4 today, it seems like this issue was fixed 🎉

**Comment by rmosolgo** [comment]
Thanks for following up. I'm glad to hear it, though I don't have a clue why it was fixed 😆
