### ISSUE TITLE
Deprecation of arguments

### ISSUE THREAD

**Issue by zyixc** [rmosolgo/graphql-ruby#270]
It would be nice to have the ability to deprecate arguments,
like you can do with fields and enum values

Reference [Deprecation of input fields](https://github.com/facebook/graphql/issues/197),
This was proposed as part of the GraphQL specification, discussion is still ongoing

```
PostInputType = GraphQL::InputObjectType.define do
  name 'PostInputType'
  argument :title, !types.String
  argument :body, !types.String
  argument :content, ContentInputType, deprecation_reason: 'Simplified'
end
```

**Comment by rmosolgo** [comment]
I won't support this until it's in the spec. At that time, we can revisit it! 

If you have a specific use case, you could share it on facebook/graphql to help inform their decision.

**Comment by gottfrois** [comment]
I think this has been roadmap by the graphql community https://github.com/facebook/graphql/issues/197

**Comment by willisplummer** [comment]
It looks like this lives here now: https://github.com/graphql/graphql-spec/pull/525

**Comment by quinn-freshly** [comment]
this would be very useful for us (pro customer)

**Comment by jturkel** [comment]
#3015 adds support for this.
