### ISSUE TITLE
Is it possible to keep arguments values as original, don't snake-case always?

### ISSUE THREAD

**Issue by semoal** [rmosolgo/graphql-ruby#2706]
Hi, 

is it possible to keep the style of the graphql arguments when they're passed to the resolver?

Thanks.

**Comment by mjrode** [comment]
Yes, you can set the extra field metadata property `graphql_name` This should allow you to specify the style. 

https://graphql-ruby.org/fields/introduction.html#extra-field-metadata

**Comment by rmosolgo** [comment]
https://github.com/rmosolgo/graphql-ruby/pull/2792 will change the behavior to use the symbol _as configured_ with `argument(...)` when building keyword arguments for a method -- is that what you're requesting here?
