### ISSUE TITLE
max_page_size pagination still not working on 1.10.1 and no first/last passed

### ISSUE THREAD

**Issue by rbviz** [rmosolgo/graphql-ruby#2707]
Issue from #1109 #2662 still persist 

```
query {
  someConnectionField(first: 50) {
    pageInfo {
      hasNextPage
      endCursor
    }
  }  
}
```

produces:
```
{
  "data": {
    "someConnectionField": {
      "pageInfo": {
        "hasNextPage": true,
        "endCursor": "NTA",
      }
    }
  }
}
```

while:
```
query {
  someConnectionField {
    pageInfo {
      hasNextPage
      startCursor
    }
  }  
}
```

endup with:
```
{
  "data": {
    "someConnectionField": {
      "pageInfo": {
        "hasNextPage": false,
        "endCursor": "NTA",
      }
    }
  }
}
```

**Comment by rbviz** [comment]
my bad `use GraphQL::Pagination::Connections` was required.

**Comment by joelvh** [comment]
@rbviz I've specified `use GraphQL::Pagination::Connections`, but when I execute a query, the `connections` object that registers the custom collections is `nil` -- have you experienced this? So, it's not finding my mappings and falling back to the Relay connection registrations.

**Comment by rmosolgo** [comment]
No, I haven't! Could you please open an issue with the configuration you tried and the error (or misbehavior) that you encountered? Please include the full error message and backtrace if there is one.

**Comment by joelvh** [comment]
@rmosolgo thanks for taking note. I've opened issue #2743
