### ISSUE TITLE
What is the best place for helper methods available both to Queries and Mutations?

### ISSUE THREAD

**Issue by gueorgui** [rmosolgo/graphql-ruby#2708]
Hello and thank you for all the work on graphql-ruby!

I'm trying to use a helper method to trigger an error in case a field is being accessed without the proper authentication.

Until now, I have only used these on Mutations, so I had this code in `app/graphql/mutations/base_mutation.rb`:

```ruby
module Mutations
  class BaseMutation < GraphQL::Schema::Mutation
    # ...
    def check_authentication!
      return if context[:current_user]
      raise GraphQL::ExecutionError, 'Unauthorized'
    end
  end
end
```

Now, I would like to reuse the same code in Queries.

Since we want to keep things DRY, where is the recommended place to put this kind of helpers that would make them available both to Mutations and Queries?

Thank you in advance!

**Comment by rmosolgo** [comment]
How about a Ruby module?

```ruby 
# app/graphql/check_authentication.rb
module CheckAuthentication 
  def check_authentication!
    # ...
  end 
end 
```

Then, you can include the module anyplace you want the method: 

```ruby 
class Types::QueryType < Types::BaseObject 
  include CheckAuthentication
end 
```

```ruby 
class Mutations::BaseMutation < GraphQL::Schema::RelayClassicMutation
  include CheckAuthentication
end 
```

I hope that helps!
