### ISSUE TITLE
Mutation generator creates camelCased field names contrary to the convention

### ISSUE THREAD

**Issue by hidde-jan** [rmosolgo/graphql-ruby#2709]
According to the guide:

> ## Object classes
> (...)
> Field and argument names should be underscored as a convention. They will be converted to camelCase in the underlying GraphQL type and be camelCase in the schema itself.

https://graphql-ruby.org/type_definitions/objects.html#object-classes

However, when using a generator to create a new mutation (and probably also other generators, I haven't checked) the field names get converted to camelCase:

https://github.com/rmosolgo/graphql-ruby/blob/master/lib/generators/graphql/mutation_generator.rb#L48

**Comment by rmosolgo** [comment]
Hmm, I expect that line to return an underscored name: 
https://github.com/rmosolgo/graphql-ruby/blob/3ce661d61cbce84655b968acf0a95d9fbf7b773c/lib/generators/graphql/mutation_generator.rb#L48

And the spec indicates that the generator uses underscored names: 

https://github.com/rmosolgo/graphql-ruby/blob/3ce661d61cbce84655b968acf0a95d9fbf7b773c/spec/integration/rails/generators/graphql/mutation_generator_spec.rb#L42

Did you get something different when you ran the generator? Could you please share the command you ran and the output you got? Maybe there's something that still needs an update!

**Comment by Luit** [comment]
Strange, the `/usr/local/bundle/gems/graphql-1.9.12/lib/generators/graphql/mutation_generator.rb` on my machine contains the following `assign_names!`:

    def assign_names!(name)
        @field_name = name.camelize(:lower)
        @mutation_name = name.camelize(:upper)
        @file_name = name.camelize.underscore
    end

**Comment by Luit** [comment]
Seems to check out for 1.9.12, let's upgrade shall we?

**Comment by hidde-jan** [comment]
Sorry, we were still on a previous version of the gem.
