### ISSUE TITLE
Argument complexity and pre-processing

### ISSUE THREAD

**Issue by zyixc** [rmosolgo/graphql-ruby#271]
A very similair functionality as compared to fields on InputObjects. Adding complexity to arguments and being able to add a custom resolver to arguments. This also requires to have similair kind of constraints like 'max_depth' for queries

Example:
```ruby 
PostInputType = GraphQL::InputObjectType.define do
  name 'PostInputType'
  argument :title, !types.String
  argument :description, !types.String
  argument :content, ContentInputType, complexity: 10 do
    resolve -> (obj, _args, _ctx) { obj }
  end
end

ContentInputType = GraphQL::InputObjectType.define do
  name 'ContentInputType'
  argument :body, !types.String
end
```

Before processing the input would look something like this
```json
{
  "input": {
    "title": "PostTitle",
    "description": "PostDescription",
    "content": {
      "body": "PostBody"
    }
  }
}
```

After processing the input would look something like this
```json
{
  "input": {
    "title": "PostTitle",
    "description": "PostDescription",
    "body": "PostBody"
  }
}
```

Nice to have would be ability to set types in the input argument, altough this exposes some security constraint
```json
{
  "input": {
    "article": {
      "type": "PostInputType",
      "title": "PostTitle",
      "description": "PostDescription",
      "body": "PostBody"
    }
  }
}
```

**Comment by rmosolgo** [comment]
It looks like the resolve function returns the same object which is passed to it: 

```ruby
 resolve -> (obj, _args, _ctx) { obj }
```

Can you help me understand how that's different from the current behavior? 

Alternatively, could you illustrate the behavior by including a "before processing the input..." example, to go along with your "after processing the input" example?

**Comment by zyixc** [comment]
Not sure how the what the resolve function should look like, 

What i would expect:
* **obj**: The current GraphQL::InputObjectType in scope
* **args**: This contains all the given arguments in a mutation
* **ctx**: Just the normal schema context

**Comment by rmosolgo** [comment]
I think these are both easily handled by existing features, here's what I have in mind: 

- __Argument complexity__: Field complexity may be specified as a proc, and in the proc, you can check for the presence of a certain argument. For example: 

  ```ruby 
  field :createPost, !PostInputType do 
    complexity -> (ctx, args, child_complexity) {
      complexity = 1 + child_complexity
      # Add an "extra charge" if a certain argument is present 
      if args[:content]
        complexity += 10 
      end 
      complexity 
    }
    # ...
  end 
  ```

- __"Resolving" input objects__ can be done with plain Ruby. Why not define a method to reduce the object, then call it in your resolve proc, for example: 
  
  ```ruby 
  field :createPost, !PostInputType do 
    resolve -> (obj, args, ctx) {
      # Call a method from your application: 
      content = CreatePost.prepare_content(args[:content])
      # Then do your thing ... 
      Post.create(content: content) 
    }
  end 
  ```

  This has one significant downside: you have to _manually_ match the custom method to each usage of the input type. 

  I would accept a patch to move that behavior into the gem, but personally, I have other priorities and the workaround is straightforward, so I'm not likely to work on it myself for a while. 

Please feel free to reopen this if I haven't addressed these questions well!
