### ISSUE TITLE
Tracing mutations

### ISSUE THREAD

**Issue by bilby91** [rmosolgo/graphql-ruby#2712]
Hello,

I've been looking into implementing a custom tracer based on the `PlatformTracer`. I'm wondering if it's possible to trace a mutation call. 

I couldn't find a way to get `platform_trace` called in this context.

**Comment by rmosolgo** [comment]
A mutation is "just" a field, so it's usually covered that way, using `execute_field` and `execute_field_lazy`. 

For example, you can detect a mutation field by: 

```ruby
data[:field].owner.graphql_name == "Mutation"
```

Alternatively, you could override `def resolve` in your mutation base class and add custom instrumentation. 

Would one of those work for you?

**Comment by rmosolgo** [comment]
I hope that will help!

**Comment by bilby91** [comment]
@rmosolgo Sorry I forgot to reply, for some reason the mutations were not propagated at some point, probably my fault. It's working as expected. 

Thanks!
