### ISSUE TITLE
Recommend pattern when using active record to delay all commits until after the mutation response shape has been validated ...?

### ISSUE THREAD

**Issue by breathe** [rmosolgo/graphql-ruby#2715]
I'd like to organize my code so that I can use the graphql-ruby response validation logic to help maintain invariants in my database (most particularly for postgres jsonb fields).

I'm using active record -- so what I'd like to do is organize my code so that I don't commit any changes to the database (via ActiveRecord `.save`) until after graphql-ruby has validated the shape of the mutation response.  For the code I'm wanting to do this with -- I can assemble the objects needed to compute the mutation response in full prior to committing any database changes.  

So what I'd like to do is somehow trigger a function call _after_ the mutation response has been validate by graphql-ruby ...

Is there a good pattern for how to achieve this?  I'm pretty new to ruby ... I was thinking there might be a way by overriding the BaseMutation -- but I'm not entirely sure how to trigger an application action _after_ graphql-ruby validates the shape of the response ...

**Comment by breathe** [comment]
Maybe overriding BaseField is what I want ... ?

```
def resolve_field(obj, args, ctx)
      begin
        resolve(obj, args, ctx)
        # insert logic to decide if this is the 'last' time resolve_field is going to be called for this mutation ...  
        # then pick some value off of ctx and call it if it exists  maybe ...
      rescue => e
        # convenience debugger spot
        raise e
      end
    end

**Comment by rmosolgo** [comment]
It sounds like you're trying to use your application's _interface layer_ to satisfy _persistence constraints_. Personally, I don't recommend it -- the _persistence layer_ should enforce _persistence constraints_. Otherwise, the only way to make sure that those constraints are in place is to run end-to-end API calls. And besides, if the application becomes accessible in another way (another API, or background jobs, or a UI), how will you enforce those constraints? 

I don't think GraphQL-Ruby will support this very well ... and I'm not sure it _should!_

A better option would be to move these validations to the persistence operation (eg, checking the structure before saving data) or to the business logic (eg, building a "service object" that includes checking the output). I hope one of those directions works for you!

**Comment by breathe** [comment]
I don't think I agree with where you are coming from with above response.  Nothing about my question implies that persistence layer validation _can't also be used_ to maintain _some_ invariants -- but my storage layer can be as constrained as it wants to be and still completely fail to produce a valid response according to the application data model after some change has been made.

What I want to do is be able to use the graphql type-checking layer to validate a data-model which the underlying persistence layer _can't validate_.  There is no such thing as a persistence layer that can validate my application's data model.  I do not want (some of) my graphql mutations to succeed at modifying persistent state and then fail to produce a valid application response.  

There are a lot of reasons such a failure could occur -- buggy code, unrealized consequences of persistence layer round-trips, etc, etc, rails-controllers injecting bugs due to the horribleness of 'death by a hundred thousands conventions'.  

What I want to do with above validation accomplishes a totally separate goal from what any logic which might exist at the persistence layer might enforce.  My aim here is not only to maintain the validity of data in the persistence layer -- but also to maintain the validity of the linkage of mutable persistent data types to the application layer.

Given that 'valid application data' is best defined by 'the data returnable by my graphql server' I think this is a reasonable way to think about things.

Doing this validation as a consequence of constructing the api response isn't necessarily the most complete form of safety here as the fields requested to construct the api response are not controlled by the server -- but it seems like a quick way to get a lot of benefit ...

Let's suppose instead I rephrase the question:

Given a ruby object `root_value` and a type `gql_type` from the schema -- determine whether all or some of the fields (recursive) publishable by `gql_type` can be resolved successfully from the given `root_value` ...

Is that possible to do?

If that's possible maybe I'll do that -- but it now becomes the mutation handler's responsibility to decide on the set of fields for which performing this validation is 'worth it.'  But I already have the 'user' of the data requesting the application's notion of 'the data which may have been changed by this mutation which the application cares about' and I'm going to be computing at least that much of the data anyway post mutation ...  This is the data I _most want_ to validate can still be computed successfully...

I guess I could try to use a `.execute(...)` call with an appropriate value for root_value to accomplish this ... but I don't really want to have to maintain a bunch of graphql query strings on my server -- especially when I already have a pretty good approximation for the set of fields I want to apply this application-level validation logic to -- and this validation logic is _going_ to be computed anyway no matter what during the computation of the mutation response ...

**Comment by breathe** [comment]
I think this does what I want ...

```
  def execute
    variables = ensure_hash(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      current_user: current_user,
      post_validation_commits: Hash.new { |hash, key| hash[key] = [] },
    }

    result = ItsACheckmateSchema.execute(query, variables: variables, context: context, operation_name: operation_name)

    context[:post_validation_commits].each do |transaction_group, commits|
      ActiveRecord::Base.transaction do
        commits.each do |commit|
          commit.call
        end
      end
    end

    render json: result
  rescue => e
    ...
  end
```
