### ISSUE TITLE
Missing plugin in `rails generate graphql:install`

### ISSUE THREAD

**Issue by prograhamer** [rmosolgo/graphql-ruby#2718]
Running `rails generate graphql:install` creates a schema that uses `GraphQL::Execution::Interpreter` without `GraphQL::Analysis::AST`.

Running a query against the newly installed schema gives the following error message:

```
Can't use `GraphQL::Execution::Interpreter` without `GraphQL::Analysis::AST`, please add this plugin to your schema:

use GraphQL::Analysis::AST

For information about the new analysis engine: https://graphql-ruby.org/queries/ast_analysis.html
```

This seems like a simple fix to add a line `use GraphQL::Analysis::AST` to the template used for the schema by the generator? This is running graphql-ruby 1.10.2, and it looks like the generator in master has this issue too.

**Comment by rmosolgo** [comment]
Derp, yes, I think you're right about the fix there!
