### ISSUE TITLE
change in subscription behavior from old-style to class-based when using prepare:

### ISSUE THREAD

**Issue by modosc** [rmosolgo/graphql-ruby#2721]
not sure if this is a bug or not, but maybe it should be documented somewhere:

we're using opaque ids (ie, `object_from_id` / `id_from_object`). we had a subscription that looked like:
```
field :thingUpdated, Types::ThingType do 
  argument :id, ID, required: true, prepare: Resolvers::GlobalId.new
```
(`Resolvers::GlobalId` maps the opaque id to an integer)

when we upgraded to the class based subscriptions, things stopped working. it took me a while to track this down but it turns out there's a subtle change. previously, our graphql topic would look like:
```
someOpaqueId:thingUpdated:id:anotherOpaqueId
```

but now it looks like:
```
someOpaqueId:thingUpdated:id:integerId
```

removing the `prepare:` argument fixes this but also removes the validity check of the incoming id (which is what we had it for in the first place). 

i think the old behavior was probably incorrect (i'd expect the prepared version to be used instead) but here we are.

**Comment by rmosolgo** [comment]
Ick, so it looks like prepare was _previously_ ignored for making a topic, but now it's used. `prepare:` is such a footgun. Thanks for opening the issue. I agree it's not _clear_ what the right solution is here.

**Comment by modosc** [comment]
maybe a backwards compatible option to run the `prepare` hook but still use the original value?

most people probably won't notice this if they don't have long-running subscriptions, but we have a webhook subscription setup which expected these to stay the same.

**Comment by rmosolgo** [comment]
Yeah, and I really didn't _mean_ to break it -- that topic ID is meant to stay stable. But I always forget about `prepare:`, because I don't use it, and I so there's no test for it 😖

**Comment by modosc** [comment]
> Yeah, and I really didn't mean to ~break~ fix it

ftfy

**Comment by rmosolgo** [comment]
😆 I meant, from a _compatibility_ standpoint, there was a service disruption. Whether `prepare:` was applied or not, the _proper_ behavior is that GraphQL subscriptions _don't_ break between version updates!

**Comment by rmosolgo** [comment]
I looked into the behavior a bit in #2749 and now I agree that the previous behavior was ... wrongish. I think for compatibility though, you'll have to remove the `prepare:` function.

Prepare has all kinds of issues, I want to reconsider it: #2749 But, if there's a compelling reason to keep it (including, "we're already using it a lot"), then I won't mess with it.
