### ISSUE TITLE
"field :module conflicts with a built-in method" in a mutation result

### ISSUE THREAD

**Issue by vimalloc** [rmosolgo/graphql-ruby#2723]
If I have a field like `field :module, Types::ModuleType, null: true` as a mutation result, I get the following warning when generating the graphql schema:

```
CreateMutation's `field :module` conflicts with a built-in method, use `resolver_method:` to pick a different resolver method for this field (for example, `resolver_method: :resolve_module` and `def resolve_module`)
CreateMutationPayload's `field :module` conflicts with a built-in method, use `resolver_method:` to pick a different resolver method for this field (for example, `resolver_method: :resolve_module` and `def resolve_module`)
```

If I use the `resolver_method` to try and get around that the error does go away. However the resolver method is not actually called, which could be confusing:

```ruby
  field :module, Types::ModuleType, null: true, resolver_method: :foo_test
  def foo_test
    raise 'this is never hit'
  end
```

It would be awesome if we could suppress that warning in a better way if we know we are working with a hash instead of an object.

Thoughts?

**Comment by rmosolgo** [comment]
Thanks for reporting the issue! I agree it's not a helpful error message 🤦‍♂
