### ISSUE TITLE
Upload file

### ISSUE THREAD

**Issue by tchukuchuk** [rmosolgo/graphql-ruby#2725]
Hi,

I'm wondering which solution you recommend to upload files.
It's not possible for me to use direct upload with ActiveStorage or Shrine :(

Thanks for your excellent job !

Regards.

**Comment by rmosolgo** [comment]
Sorry, I don't have a recommendation! I can share these links, although I haven't vetted them: 

- https://github.com/jetruby/apollo_upload_server-ruby
- https://graphqlme.com/2017/09/16/upload-images-to-s3-in-graphql-using-rails-and-paperclip/
- http://mgiroux.me/2015/uploading-files-using-relay-with-rails/

I hope one of those is helpful! Feel free to share an update here if you find something that works, I'd love to hear about it.

**Comment by lhguerra** [comment]
How upload should be done nowadays? These solotions are all outdated
