### ISSUE TITLE
Custom resolve block with fallback to default behaviour

### ISSUE THREAD

**Issue by 23tux** [rmosolgo/graphql-ruby#2728]
I have a custom field with a default resolve block that should optimize batch loading using a lazy resolver

```
module Graphql
  module Types
    class OptimizedField < GraphQL::Schema::Field
      def initialize(*args, **kwargs, &block)
        kwargs[:resolve] = ->(object, resolve_args, ctx) {
          if object.class.reflect_on_association(ctx.field.name)
            # custom logic for lazy resolvers
          else
            resolve(object, resolve_args, ctx)
          end
        }
        super(*args, **kwargs, &block)
      end
    end
  end
end
```

The idea behind this is, when we deal with an association, we can try batch loading. If not, I'd like to fall back on the default resolver of the gem. But using this results in an error, when it tries to call `#resolve` within the block:

```
Can't run resolve proc for BaseObject.id when using GraphQL::Execution::Interpreter
```

I tried to overwriting `#resolve` inside my `OptimizedField` class, but it isn't called. Can someone tell me how I would fall back to the default behaviour of graphql?

**Comment by rmosolgo** [comment]
If you want to wrap resolve behavior, I recommend Field Extensions: https://graphql-ruby.org/type_definitions/field_extensions.html

Please give that a try and let me know if you run into any trouble!
