### ISSUE TITLE
[PRO] Trying to allow some QueryType fields to be public results in NilClassPolicy lookup failure

### ISSUE THREAD

**Issue by martinemde** [rmosolgo/graphql-ruby#2730]
I'm still seeing issues related to #2129.

Here's what I want:
1. Most of the fields in QueryType should be private
2. A couple of them are allowed to be seen publicly
3. I'd like to prevent the query from running rather than validating that the objects returned are authorized (which I am also doing)
4. I'd rather not define a custom role and policy class for every query if there's a better way.

I'm not sure what mix of the solutions I wrote/commented below gets me what I want, but right now I keep getting this NilClassPolicy.

Gem versions:
```
    graphql (1.10.2)
    graphql-pro (1.11.0)
    rails (5.2.4.1)
```

```
No policy found for:
       - Types::BaseField: Query.user
       - Runtime value: `nil`
       Pundit error: Pundit::NotDefinedError, unable to find policy `NilClassPolicy` for `nil`
```

Relevant snippets:

```ruby
class Types::BaseObject < GraphQL::Schema::Object
  include GraphQL::Pro::PunditIntegration::ObjectIntegration
  field_class Types::BaseField
  pundit_role :authenticated # checks if there is a user
end
```

```ruby
class Types::QueryType < Types::BaseObject
  pundit_role nil # allow seeing query root
  # If I change above to what is below then I successfully make all
  # queries authenticated but then I can't see any way to allow access
  # to certain fields on QueryType that bypass this policy
  #pundit_policy_class QueryPolicy
  #pundit_role :authenticated

  field :user, Types::UserType, null: true do
    argument :id, ID, required: true
    pundit_role :authenticated # I'd prefer not having to add this to every query
    # individually since most of them just need :authenticated.
    #pundit_policy_class UserPolicy # If I uncomment this, it works,
    # but it means I need to do this for every query
  end

  field :public_thing, Types::PublicThing do
    # What do I do here to allow this one to be public
    # without adding a pundit_policy_class and pundit_role to
    # every field on the QueryType?
    #pundit_policy nil # This is what I'd expect to be able to do to allow this to not be denied.
    # Adding the above does not allow public access to this field
    # since it's already been blocked by QueryPolicy.authenticated?
  end
```

**Comment by martinemde** [comment]
I just played around with the code above and arrived at this, which I'm not sure is perfect but it does what I want:

Do you have any better recommendation?

```ruby
class Types::QueryType < Types::BaseObject
  pundit_policy_class QueryPolicy
  pundit_role nil

  field :user, Types::UserType, null: true do
    argument :id, ID, required: true
    pundit_role :authenticated
  end

  field :public_thing, Types::PublicThing do
    pundit_policy nil
  end
```

**Comment by rmosolgo** [comment]
It looks like the code you posted is _right_ to me! 

- By default, each GraphQL object uses its underlying `object` to determine which Pundit policy class to use. Often, the root object of a GraphQL query is `nil`. (You can pass `root_value:` to `Schema.execute` to set it to something else.) 
- You were getting `NilClassPolicy` errors because it was trying to find a policy for `nil`.
- By explicitly requesting `pundit_policy_class QueryPolicy` in the type definition, you overrode the default lookup and provided a policy class -- so it's not using `nil` anymore 

Sorry about the confusion along the way!
