### ISSUE TITLE
GraphQL::Pro::Encoder ArgumentError (key must be 16 bytes)

### ISSUE THREAD

**Issue by tadman** [rmosolgo/graphql-ruby#2732]
When using the [example code for defining an encoder](https://graphql-ruby.org/pro/encoders.html) the encoder refuses to run on anything but 16-byte keys. The example given looks like this when applying the recommendation for defining a key using SecureRandom:

```ruby
MyEncoder = GraphQL::Pro::Encoder.define do
  key(SecureRandom.random_bytes(64))
  # optional:
  tag("81ce51c307")
end
```

When calling this you get:

```ruby
MyEncoder.encode('test')
# => ArgumentError (key must be 16 bytes)
```

Which is not the expected behaviour. The documentation implies that you can use longer keys, yet only 16-byte keys are supported. This is presumably due to the choice of `aes-128-gcm` which needs a 128-bit key, or 16 bytes. The `define` method doesn't seem to allow changing of the encryption type used, or if it somehow does the example should at least show how to do that.

Is the intention to have 16 random bytes, or to actually permit 64?

This is with GraphQL Pro 1.13.0, but also occurred on 1.12.2.

**Comment by rmosolgo** [comment]
Sorry, that's a bad recommendation 🤦‍♂ The thing is, Ruby silently ignored the unused tail of the key until Ruby 2.4. In Ruby 2.4, it started raising that error, and I forgot to update the docs.

A better recommendation is: 

```ruby
SecureRandom.bytes(16)
```

I'll update the docs! Let me know if you have any more trouble after that.
