### ISSUE TITLE
Overriding auto generated mutation return types

### ISSUE THREAD

**Issue by christophweegen** [rmosolgo/graphql-ruby#2737]
Is it possible to override the auto generated payload types of mutations? 

Right now mutations have their class name appended by "Payload" as their return type like:

```
createArticle(name: String!): CreateArticlePayload!
```

My intention behind that is as follows: I want to have something like a `Result` monad union type with possible types of `Success | Failure` as return type of a mutation.

for example 
```
createArticle(name: String!): Result!
```
where `Result` will be either `Success` or `Failure`.

Thanks!

**Comment by swalkinshaw** [comment]
Yes you can override the `generate_payload_type` method on your `Mutation` base class:

 https://github.com/rmosolgo/graphql-ruby/blob/0fccda6efe5a4eef3b4009ce5f024656f2171a51/lib/graphql/schema/resolver/has_payload_type.rb#L49-L62

**Comment by rmosolgo** [comment]
You can also provide a type with `type(...)` in the mutation: 

```ruby 
class Mutations::CreateArticle < Mutations::BaseMutation 
  type(Unions::Result) 
  # ... 
end 
```

Let me know if you have any trouble with it!

**Comment by christophweegen** [comment]
@swalkinshaw @rmosolgo thanks for that lightning fast reply! :zap: 

Will try that out!

As far as I've seen the `type` class method isn't documented in the guides. Maybe it would be a nice addition?

**Comment by rmosolgo** [comment]
yes, feel free to submit a patch using the "edit" buttons on the bottom of the guides!

**Comment by xiaoduwuer** [comment]
I have upgraded the version of GraphQL to the latest version, and in `Mutations::Distributor::Create`, I have set the `graphql_name` to 'DistributorCreate'. I expect the name of the return type to be 'DistributorCreatePayload'. However, in the generated `schema.graphql` file, the return type is 'CreatePayload'. 
```ruby
module Mutations
    module Distributor
          class Create < Mutations::BaseMutation
                 graphql_name 'DistributorCreate'
                 ...
          end
     end
end 
         
```
Gemfile.lock ref gems info:

    graphql (2.3.9)
      base64
    graphql-batch (0.6.0)
      graphql (>= 1.12.18, < 3)
      promise.rb (~> 0.7.2)

**Comment by rmosolgo** [comment]
Hey, sorry to hear it! I wrote up a quick script and found that the type was properly named `DistributorCreatePayload`: 

<details>
<summary>Test Mutation Custom GraphQL name</summary>

<p>

```ruby
require "bundler/inline"

gemfile do
  gem "graphql", "2.3.9"
end

module Mutations
  module Distributor
    class Create < GraphQL::Schema::RelayClassicMutation
      graphql_name "DistributorCreate"
    end
  end
end


class MySchema < GraphQL::Schema
  class Mutation < GraphQL::Schema::Object
    field :distributor_create, mutation: Mutations::Distributor::Create
  end
  mutation Mutation
end

puts MySchema.to_definition


```

```graphql 
"""
Autogenerated input type of DistributorCreate
"""
input DistributorCreateInput {
  """
  A unique identifier for the client performing the mutation.
  """
  clientMutationId: String
}

"""
Autogenerated return type of DistributorCreate.
"""
type DistributorCreatePayload {
  """
  A unique identifier for the client performing the mutation.
  """
  clientMutationId: String
}

type Mutation {
  distributorCreate(
    """
    Parameters for DistributorCreate
    """
    input: DistributorCreateInput!
  ): DistributorCreatePayload
}
```
</p>
</details>

If you're still having trouble, please open a new issue to investigate this problem, including: 

- The full definition of your mutation 
- A snippet of SDL or GraphQL introspection which shows the wrong GraphQL name (or some other way of demonstrating that the payload type doesn't have the right name) 

That should give us enough information to find the cause!
