### ISSUE TITLE
@fake directive

### ISSUE THREAD

**Issue by kfitzvineti** [rmosolgo/graphql-ruby#2740]
I would like to try to write a custom directive which conforms to the https://github.com/APIs-guru/graphql-faker style:
`name: String @fake(type: firstName)` 

All it really needs to do is output the `@fake` clause when dumping the schema. graphql-faker takes care of the rest. I was unsure from the [docs](https://graphql-ruby.org/type_definitions/directives.html) on where to start with that. Any advice is welcome.

I'm not sure how to tag this issue "we're a pro customer."

**Comment by rmosolgo** [comment]
Hi, great question! There's not a great built-in way to do this now, but if you want to experiment, I can give you a little direction. 

The bulk of printing is actually done by `GraphQL::Language::DocumentFromSchemaDefinition`. For example, see how it adds `@deprecated`: 

https://github.com/rmosolgo/graphql-ruby/blob/4e367c71d93c4ce5235ca4a357c8f585c319866b/lib/graphql/language/document_from_schema_definition.rb#L65-L81

You could do something similar in a custom subclass to add `@fake`: 

```ruby 
class DocumentFromSchemaDefinitionWithFake < GraphQL::Language::DocumentFromSchemaDefinition
  def print_field(field_defn)
    field_node = super 
    # Check to see if the field has a configured `fake_type`, and if it does, then add the directive
    if field_defn.fake_type 
      field_node = field_node.merge_directive(
        name: "fake",
        arguments: [GraphQL::Language::Nodes::Argument.new(name: "type", value: field.fake_type)]
      )
    end 
    field_node 
end 
```

In order to support `field_defn.fake_type`, you have to add it to your base field class, for example:

```ruby 
class Types::BaseField < GraphQL::Schema::Field 
  def initialize(*args, fake_type: nil, **kwargs, &block) 
    @fake_type = fake_type 
    super(*args, **kwargs, &block)
  end 
  attr_reader :fake_type 
end 
```

After that, you can use `fake_type:` in your field definitions: 

```ruby 
field :name, String, null: false, fake_type: "firstName" 
```

(That's how you'd implement `BaseField#fake_type` to return an explicitly-configured value. Of course, you could implement `def fake_type` to infer a value based on the field's name and return type, too.) 

Finally, you could create a schema dump with `@fake` by using your custom document builder: 

```ruby 
builder = DocumentFromSchemaDefinitionWithFake.new(MySchema)
schema_str = builder.document.to_query_string 
File.write("schema.graphql", schema_str)
```

Want to give it a try? Let me know how it goes!

**Comment by kfitzvineti** [comment]
Thanks! Will do.

**Comment by kfitzvineti** [comment]
@rmosolgo In your example subclass, you write a `#print_field` method. I don't see that on the superclass GraphQL::Language::DocumentFromSchemaDefinition. Did you mean a different class or a different method?

```
class DocumentFromSchemaDefinitionWithFake < GraphQL::Language::DocumentFromSchemaDefinition
  def print_field(field_defn)
```

**Comment by kfitzvineti** [comment]
For the moment I'm assuming you meant that to go into `#build_field_node`

**Comment by rmosolgo** [comment]
Derp, yes, I meant `build_field_node`. I was getting confused with `SchemaPrinter`.

**Comment by kfitzvineti** [comment]
@rmosolgo I think I’ve come up with a solution, but it’s been pretty hacky to implement from the outside. Would you be open to a PR to implement this in the gem? If not, maybe we can work to make the integration easier.

**Comment by rmosolgo** [comment]
I'd be happy to consider either of those options, could you share what you got working so far? That would inform how much could be improved by cleaning up the extension points, and what would be involved in upstreaming it to graphql-ruby.

**Comment by kfitzvineti** [comment]
Sure thing, I'll put something together this week.

**Comment by rmosolgo** [comment]
I'm going to close this since I don't expect to do more work here, but please do let me know if you have any snippets to share! I'm sure plenty of other folks would be interested in mocking their schemas.

**Comment by kfitzvineti** [comment]
@rmosolgo Check out this PR. It's lacking tests at the moment, but I'd like to see if it's a direction you're interested in going. If not, any tips on implementing it from outside the gem?

**Comment by kfitzvineti** [comment]
https://github.com/vinetiworks/graphql-ruby/pull/1

**Comment by kfitzvineti** [comment]
For what it's worth I didn't use custom directives because I couldn't figure out how to get it to output correctly in the SDL output.

**Comment by kfitzvineti** [comment]
I notice [here](https://github.com/rmosolgo/graphql-ruby/blob/feature/graphql-faker/lib/graphql/language/printer.rb#L41-L49) in GraphQL::Language::Printer we have
```ruby
      def print_directive(directive)
        out = "@#{directive.name}".dup

        if directive.arguments.any?
          out << "(#{directive.arguments.map { |a| print_argument(a) }.join(", ")})"
        end
        out
      end
```
But in [GraphQL::Schema::Printer](https://github.com/vinetiworks/graphql-ruby/blob/feature/graphql-faker/lib/graphql/schema/printer.rb#L97-L10) we have
```ruby
      def print_directive(directive)
        if directive.name == "deprecated"
          reason = directive.arguments.find { |arg| arg.name == "reason" }

          if reason.value == GraphQL::Schema::Directive::DEFAULT_DEPRECATION_REASON
            "@deprecated"
          else
            "@deprecated(reason: #{reason.value.to_s.inspect})"
          end
          ...
```
Is there a reason it is hardcoded, @rmosolgo ?
