### ISSUE TITLE
loads: not working on a field's argument

### ISSUE THREAD

**Issue by sayduck-daniel** [rmosolgo/graphql-ruby#2744]
I'm implementing loads everywhere as I just updated the gem's version and it seems to be working quite well except for arguments in a field.

See the query and response. We can see that my `id` was renamed as `node` but it was not passed to `object_from_id `. If I run my `node` trough `object_from_id ` I get the the value I'm expecting.

query_type.rb
```ruby
# frozen_string_literal: true

module Types
  class QueryType < BaseObject
    field :all_materials_from_library,
          Types::MaterialType.connection_type,
          null: true do
      argument :id,
               ID,
               loads: Types::CustomerType,
               as: :node,
               required: true
    end

    def all_materials_from_library(node:)
      pp node
      pp node.class
      pp SayduckSchema.object_from_id(node, context)
    end
end
```

query
```graphql
  query {
    all_materials_from_library(id: "Q3VzdG9tZXItYzQwOThlOTAtMzIxOS0wMTM4LTUyNTEtMGM4NTkwOWQ4YmYw") {
      totalCount
    }
  }
```

response
```
"Q3VzdG9tZXItOTIxM2UwMjAtMzIxYS0wMTM4LTYwNzAtMGM4NTkwOWQ4YmYw"
String
#<Customer:0x00007fe84a7cd9b0
 id: 6403,
 uuid: "9213e020-321a-0138-6070-0c85909d8bf0",
 name: "Sherill Volkman",
 created_at: Sat, 15 Feb 2020 12:13:59 UTC +00:00,
 updated_at: Sat, 15 Feb 2020 12:13:59 UTC +00:00,
 business: true,
 billing_email: nil,
 stripe_identifier: "cust_91263910-321a-0138-d2f2-0c85909d8bf0",
 testing: "a",
 shopify_shop_id: nil,
 phone: nil,
 tax_exempt: "none_",
 vat_number: nil,
 address_line1: nil,
 address_line2: nil,
 city: nil,
 country: nil,
 postal_code: nil>
```

I hope this example makes sense to you.

**Comment by rmosolgo** [comment]
Hi! This feature was added/fixed in #2720 , which is on the master branch but hasn't been released to RubyGems yet. Are you using `gem "graphql", github: "rmosolgo/graphql-ruby", ref: "master"`? 

You can use that to get the new feature, or wait for 1.10.3 to be released on Rubygems, which should be sometime this week.

**Comment by sayduck-daniel** [comment]
Ok, awesome, I'm gonna switch to `graphql", github: "rmosolgo/graphql-ruby", ref: "master"? ` for my development and staging environment. 

Any ETA for the release?

**Comment by rmosolgo** [comment]
> ETA

Monday 😊 

💁‍♂ https://rubygems.org/gems/graphql/versions/1.10.3

**Comment by sayduck-daniel** [comment]
Awesome! Thanks, great work as always 👍
