### ISSUE TITLE
GraphQL::InvalidNullError during subscription query

### ISSUE THREAD

**Issue by Envek** [rmosolgo/graphql-ruby#2754]
**Environment**

Ruby 2.6.5
rails 6.0.2.1
graphql (1.10.2)

**Description**

Given a non-nullable subscription field with a stub method just to allow any client to subscribe:
```ruby
class Types::SubscriptionType < Types::BaseObject
  field :product_updated, [Types::Product], null: false, subscription_scope: :user_id

  def product_updated; end
end
```
And type error handler set up to report non-nullable violations as per [our blog post](https://evilmartians.com/chronicles/reporting-non-nullable-violations-in-graphql-ruby-properly):

```ruby
class ApplicationSchema < GraphQL::Schema
  def self.type_error(exception, query_context)
    # report exception to error tracker
    super
  end
end
```

We started to get a lot of `GraphQL::InvalidNullError` in our tracker after upgrading from graphql-ruby 1.8.17 to 1.10.2.

It turns out that now graphql-ruby started to execute queries at subscription type (not sure why as there is no information available at this time) and fails because of that.

However, we're just ignoring any results of subscription query in our graphql channel:

```ruby
class GraphqlChannel < ApplicationCable::Channel
  def subscribed; end

  def execute(data)
    result = execute_query(data)
    transmit(
      result: result.subscription? ? { data: nil } : result.to_h,
      more: result.subscription?,
    )
  end
end
```

**Workaround**

Detect if query is a subscription and swallow errors about non-nullable violations:
```ruby
class ApplicationSchema < GraphQL::Schema
  def self.type_error(exception, query_context)
    return if context.query.subscription? && exception.is_a?(GraphQL::InvalidNullError)

    # report exception to error tracker
    super
  end
end
```

---

Possibly related issues: https://github.com/rmosolgo/graphql-ruby/issues/1799, https://github.com/rmosolgo/graphql-ruby/issues/1910

**Comment by rmosolgo** [comment]
Sorry for the hangup! It's the sixth breaking change in 1.10: https://github.com/rmosolgo/graphql-ruby/blob/master/CHANGELOG.md#breaking-changes-1

I think the solution here is to remove your empty method. It was previously required, but the return value was ignored (weird). In 1.10, we started _not_ requiring the method, but using the return value if the method was defined. (See #2536)

Alternatively, you can keep the method, but instead of returning `nil`,  return `context.skip`:

```ruby 
def product_updated 
  context.skip
end 
```

That tells the runtime to skip this field altogether in the response, which is the default behavior for initial subscriptions. 

Please let me know if one of those doesn't work for you!

**Comment by Envek** [comment]
Well, actually if I try to remove these methods, I will get an error:
```
RuntimeError:         Failed to implement Subscription.productUpdated, tried:

        - `Types::SubscriptionType#product_updated`, which did not exist
        - `NilClass#product_updated`, which did not exist
        - Looking up hash key `:product_updated` or `"product_updated"` on ``, but it wasn't a Hash

        To implement this field, define one of the methods above (and check for typos)
 (while resolving Subscription.productUpdated)
```

These methods wasn't needed in 1.8, but in 1.10 I was forced to add them.

---

In case of returning `context.skip` from these methods, subscription query won't be performed on trigger:

```ruby
ApplicationSchema.subscriptions.trigger(:product_updated, {}, [Product.first], scope: 1)
```
and empty response will be sent to clients:

```json
{"result":{"data":null},"more":true}
```

Instead of correct:

```json
{"result":{"data":{"productUpdated":[{"__typename":"Product", …}]}},"more":true}}
```

---

I assume that I should migrate to using subscription classes, maybe?

**Comment by rmosolgo** [comment]
> subscription classes, maybe?

That's definitely the _happy path_, but it should work one way or another to migrate what you have. 

Here's the previous default behavior: 

https://github.com/rmosolgo/graphql-ruby/blob/ad7bc23c3b3a5880433cd20299a41da175087b33/lib/graphql/subscriptions/instrumentation.rb#L46-L75

What I missed was the check for `subscription_topic ==`, which is determining whether it's a call to `trigger`. 

The new default behavior is here: 

https://github.com/rmosolgo/graphql-ruby/blob/ad7bc23c3b3a5880433cd20299a41da175087b33/lib/graphql/subscriptions/subscription_root.rb#L16-L20

I suppose you could try that logic, something like: 

``ruby 
def product_updated 
  if context.query.subscription_update?
    object 
  else 
    context.skip
  end 
end 
```

(Of course, you might extract or alias that method, or use `resolve_method: ...` to keep things DRY)

Does that work properly? It should pass through the object from `.trigger`, but properly skip the initial subscription.

**Comment by Envek** [comment]
This _spell_ works!
```ruby
def product_updated 
  if context.query.subscription_update?
    object 
  else 
    context.skip
  end 
end 
```
Thank you very much!
