### ISSUE TITLE
Allow empty array values for GraphQL::Define.assign_metadata_key 

### ISSUE THREAD

**Issue by RStankov** [rmosolgo/graphql-ruby#2755]
Hey, 👋

Passing an empty array to a custom metadata definition results returns true instead of an empty array.

## Steps to reproduce

```ruby
require 'graphql'

GraphQL::Field.accepts_definitions(
  fallback: GraphQL::Define.assign_metadata_key(:fallback),
)

GraphQL::Schema::Field.accepts_definition(:fallback)

module TestInstrument
  extend self

  def instrument(_type, field)
    return field unless field.metadata.key?(:fallback)

    field.metadata[:fallback]
  end
end

class QueryType < GraphQL::Schema::Object
  field :foo, [String], null: true, fallback: []

  def foo
    ['no fallback']
  end
end

class TestSchema < GraphQL::Schema
  query QueryType

  instrument :field, TestInstrument
end

p TestSchema.execute('query { foo }')
```

## Longer explanation

I have a gem with adds authorization to GraphQL - [kitty-policy](https://github.com/producthunt/kitty-policy). It allows the following:

```ruby
field :secret, String, required: false authorize: :access, fallback: '-hidden-'
```

But when I try to have this with an empty array. I was getting `[true]` as value. 🤔

```ruby
field :secret, [String], required: false authorize: :access, fallback: []
```

When I start digging into the code, I found the cause.

This is what I was using to add meta keys:

```ruby
  ::GraphQL::Field.accepts_definitions(
    fallback: GraphQL::Define.assign_metadata_key(:fallback),
    authorize: GraphQL::Define.assign_metadata_key(:authorize),
  )
```

In [GraphQL::Schema::Member::AcceptsDefinition::ToGraphQLExtension#initialize](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/member/accepts_definition.rb#L124):

```ruby
if !value.nil?
  defn = defn.redefine { public_send(method_name, *value) }
end
```

If we have value be empty array this becomes `public_send(method_name)`. Then [GraphQL::Define](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/define.rb#L15) have its value to default to [true](https://github.com/rmosolgo/graphql-ruby/blob/09996529842132f69bee86aa8a1547aa3b69a814/lib/graphql/define/instance_definable.rb#L183-L191).

[This is how I fixed this in my gem](https://github.com/producthunt/kitty-policy/commit/085e33d59ee3f292546fc165207b1d7f81918e74).

I think the following will fix it in the library. However, I'm not very familiar with internals to know if this won't break things:

```diff
-- defn = defn.redefine { public_send(method_name, *value) }
++  defn = defn.redefine { value == [] ? public_send(method_name, value) : public_send(method_name, *value) } 
```

This results in:

>  undefined method `connection?' for true:TrueClass (NoMethodError)

**Comment by rmosolgo** [comment]
Thanks for the detailed report. I agree, something like the fix you suggested would be appropriate. I'll take a look and try to hack through the failures!

**Comment by rmosolgo** [comment]
Taking another look over this issue, it looks like you found a good workaround for your case, right? 

I'd rather not go back and work on it if I can help it, because this legacy compat code is not an area of active development for me. 

In GraphQL-Ruby 1.10, class-based schemas using the Interpreter _don't_ ever call the underlying `.define` APIs (the classes are used directly at runtime; no legacy instances are ever made). This is a much simpler paradigm, and I'd rather keep focusing on _that_ if I can! 

Did you find something that works well enough for your gem?

**Comment by RStankov** [comment]
Yeah sure. I suspect a fix might have unintended consequences, because of this didn't open a PR 😅
