### ISSUE TITLE
GraphQL::ExecutionError response status code

### ISSUE THREAD

**Issue by gouvermxt** [rmosolgo/graphql-ruby#2758]
Every time I raise a GraphQL::ExecutionError the response status code is set to 500. Shouldn't it be 200?

With status code 500 my client library can't understand that it is a Graphql error and that it should extract the error data from the errors key. Maybe there's a way to choose the status code.

**Comment by rmosolgo** [comment]
Hi, as far as I know, GraphQL-Ruby never sets any status codes! I don't know of any HTTP-related code in GraphQL-Ruby, actually. 

Could you please share some details about your issue? For example: 

- The code that raises an error 
- The controller that calls graphql and returns a response 
- An example response 

That would give some insight into where the response code is coming from.

**Comment by gouvermxt** [comment]
It turns out that a bridge that I was using was misinterpreting the response and putting a 500 status code. Thank you for appreciating it.
