### ISSUE TITLE
loads: and required: false behaviour

### ISSUE THREAD

**Issue by sayduck-daniel** [rmosolgo/graphql-ruby#2760]
I'm still migrating all our code base to use `loads:`and I think we found a bug.

This code:
https://github.com/rmosolgo/graphql-ruby/blob/4e367c71d93c4ce5235ca4a357c8f585c319866b/lib/graphql/schema/member/has_arguments.rb#L143-L146

Should become:

```ruby
 if application_object.nil?  && id.nil?
  # id.nil? -> for the case when we actually have send objectId that would return a nil object (= object sent is not existing)
  return nil
 end 
```

At the moment, `loads:` is overlapping on `required`. This does not allow us to (for example) having a mutation that would update a model attributes with a `load:` on a relation. At the moment we can set the relation from `nil` to `object` but we can not go back to nil.

We should have this behaviour:

```ruby
argument :object_id, loads: Object, required: false

# object_id: Object.first.id           => Object.first
# object_id: OtherObject.first.id      => error from loads:
# object_id: nil'                      => nil

argument :object_id, loads: Object, required: true

# object_id: Object.first.id           => Object.first
# object_id: OtherObject.first.id      => error from loads:
# object_id: nil'                      => error from required:
```

**Comment by sayduck-daniel** [comment]
@rmosolgo any opinion on this one?

**Comment by rmosolgo** [comment]
Thanks for the bump on this. I read it last week, and thought about it, but I think I misunderstood. 

I think the behavior you described in "We should have this behaviour:" is correct. (Well, it _should_ work that way, anyhow.) But, it sounds like it's ignoring `required: false` right now?

**Comment by sayduck-daniel** [comment]
Yes. 

We should check the `loads` type against the return of `object_from_id() ` only when the argument value was not nil.

Those are the case scenario:

```
argument :object_id, loads: Object, required: false

class

**Comment by sayduck-daniel** [comment]
Any idea for this problem @rmosolgo ?
