### ISSUE TITLE
`Schema.to_definition` results in undefined method `visible?` error

### ISSUE THREAD

**Issue by mikong** [rmosolgo/graphql-ruby#2764]
The error started happening after upgrading the `graphql` gem from `1.9.17` to `1.10.3`.

Versions:
- `graphql 1.10.3`
- `rails 6.0.2.1`

The test code being executed:

```ruby
  test 'GraphQL Schema dump is up-to-date' do
    schema_definition = RailsGraphqlTutorialSchema.to_definition
    schema_dump = File.read(Rails.root.join('app/graphql/schema.graphql'))
    assert_equal schema_definition, schema_dump
  end
```

Backtrace:

```
Error:
SchemaTest#test_GraphQL_Schema_dump_is_up-to-date:
DRb::DRbRemoteError: undefined method `visible?' for nil:NilClass (NoMethodError)
    /Users/mikong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/schema.rb:1362:in `visible?'
    /Users/mikong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/filter.rb:32:in `call'
    /Users/mikong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/filter.rb:32:in `call'
    /Users/mikong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/filter.rb:12:in `call'
    /Users/mikong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/schema/warden.rb:51:in `block in initialize'
    /Users/mikong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/schema/warden.rb:219:in `block in read_through'
    /Users/mikong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/schema/warden.rb:215:in `visible?'
    /Users/mikong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/schema/warden.rb:164:in `visible_field?'
    /Users/mikong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/schema/warden.rb:127:in `block (2 levels) in arguments'
    /Users/mikong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/schema/warden.rb:127:in `each_value'
    /Users/mikong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/schema/warden.rb:127:in `each'
    /Users/mikong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/schema/warden.rb:127:in `select'
    /Users/mikong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/schema/warden.rb:127:in `block in arguments'
    /Users/mikong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/schema/warden.rb:219:in `block in read_through'
    /Users/mikong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/schema/warden.rb:128:in `arguments'
    /Users/mikong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/schema/warden.rb:281:in `block in reachable_type_set'
    /Users/mikong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/schema/warden.rb:277:in `each'
    /Users/mikong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/schema/warden.rb:277:in `reachable_type_set'
    /Users/mikong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/schema/warden.rb:83:in `reachable_types'
    /Users/mikong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/language/document_from_schema_definition.rb:259:in `build_definition_nodes'
    /Users/mikong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/language/document_from_schema_definition.rb:41:in `document'
    /Users/mikong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/schema/printer.rb:56:in `initialize'
    /Users/mikong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/schema/printer.rb:83:in `new'
    /Users/mikong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/schema/printer.rb:83:in `print_schema'
    /Users/mikong/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/schema.rb:822:in `to_definition'
    /Users/mikong/Projects/rails/rails-graphql-tutorial/test/graphql/schema_test.rb:7:in `block in <class:SchemaTest>'
```

In the method `reachable_type_set` of `lib/graphql/schema/warden.rb`, while looping through the `unvisited_types`, the error seemed to have happened at type `Query`. Here's the relevant part of the GraphQL IDL:

```
type Query {
  allLinks(filter: LinkFilter): [Link]
}
```

And here's `app/graphql/types/query_type.rb`:

```ruby
module Types
  class QueryType < Types::BaseObject
    field :all_links, function: Resolvers::LinksSearch
  end
end
```

Please let me know if you need more information.

**Comment by rmosolgo** [comment]
D'oh! I suspect it's because `function:` isn't supported anymore. It's been replaced by `GraphQL::Schema::Resolver` https://graphql-ruby.org/fields/resolvers.html 

I bet it's failing to find a return type for that field. 

Does the schema still run queries?! I can't imagine it does 🙈  

I'll take a look and try to improve the error message in this case. If you run into any trouble migrating to resolvers, please let me know!

**Comment by mikong** [comment]
The query still works. I've verified that the test for `allLinks` query still works, and the frontend app is still able to fetch data for the same query before changing `function:` to `resolver:`.

Also confirmed that after changing `function:` to `resolver:`, there's no error anymore. Thanks.

Btw, was `function:` support dropped at version 1.10.0? Should we update the `CHANGELOG` to mention this under the **Breaking changes** section?

**Comment by rmosolgo** [comment]
Ohhhh are you using `GraphQL::Execution::Interpreter` in your schema definition? _That_ module doesn't support `function`s.

I'd like to understand how this happened and update the changelog, like you said.

**Comment by mikong** [comment]
I didn't explicitly use `GraphQL::Execution::Interpreter`. You can find my repo here: https://github.com/mikong/rails-graphql-tutorial

I haven't pushed the change where I upgraded the gem so the repo is still at 1.9.17. Locally, I'm trying to make Subscription work which is why I tried upgrading the gem. I reverted all my changes locally and the only change left is the gem upgrade and I'm seeing the same behavior.

**Comment by rmosolgo** [comment]
I think what happened is that `Schema.to_definition` _used_ to delegate to the legacy-compatible `Schema.graphql_definition.to_definition`, but that changed in 1.10. In 1.10.0, `to_definition` became a proper class method and doesn't generate the legacy singleton instance anymore ([removal of delegated method](https://github.com/rmosolgo/graphql-ruby/compare/v1.9.18...v1.10.0#diff-a6531664eb34e7e9f807b7f37c740ea1L724), [addition of class method](https://github.com/rmosolgo/graphql-ruby/compare/v1.9.18...v1.10.0#diff-a6531664eb34e7e9f807b7f37c740ea1R816-R823)). 

As a work-around, `MySchema.graphql_definition.to_definition` might still work in this case. 

Given that nobody else has encountered this, I'm considering it an edge case, and I'm afraid I don't have the bandwidth to look into it further 😖 . 

If someone runs into this and can't update their `function:`s to `resolver:`s, please open a new issue with the specific situation and we'll see what we can do!

**Comment by ih-denis-simonchik** [comment]
When attempting to implement an interface within an `EdgeBehaviour` building a schema definition fails with the same error for `Schema.to_definition`:
```
NoMethodError: undefined method `visible?' for nil:NilClass
```
in .rvm/gems/ruby-2.6.9@qnaire-rails-4/gems/graphql-1.13.12/lib/graphql/types/relay/edge_behaviors.rb:48:in `visible?'
```
class Base::BaseEdge < GraphQL::Schema::Object
  include Concerns::BaseEdgeBehaviors
  implements TestInterface
end

module Concerns
  module BaseEdgeBehaviors
    extend ActiveSupport::Concern

    included do
      include GraphQL::Types::Relay::EdgeBehaviors

      node_nullable false
    end
  end
end

module TestInterface
  include Base::BaseInterface

  graphql_name 'Test'

  field :test, String, null: true
end
```
It seems that we should have the same fix for [EdgeBehaviour](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/types/relay/edge_behaviors.rb#L47) as for the [ConnectionBehaviour](https://github.com/rmosolgo/graphql-ruby/pull/3859) :
```
 def visible?(ctx)
    node_type.visible?(ctx)
    # if this is an abstract base class, there may be no `node_type`
    node_type ? node_type.visible?(ctx) : super
  end
```
cc @rmosolgo
