### ISSUE TITLE
Guide: Ahead-of-Time Analysis

### ISSUE THREAD

**Issue by kouwasi** [rmosolgo/graphql-ruby#2771]
https://github.com/rmosolgo/graphql-ruby/blob/master/guides/queries/analysis.md

The example code in this documentation is not executable in 1.10.3 + default generated schema.

```ruby
class MySchema < GraphQL::Schema
  mutation(Types::MutationType)
  query(Types::QueryType)

  # Opt in to the new runtime (default in future graphql-ruby versions)
  use GraphQL::Execution::Interpreter
  use GraphQL::Analysis::AST

  # Add built-in connections for pagination
  use GraphQL::Pagination::Connections

  query_analyzer MyAnalyzer
end

class MyAnalyzer
  def analyze?(query)
    true
  end

  def initial_value(query)
  end

  def call(memo, visit_type, irep_node)
  end

  def final_value(memo)
  end
end
```

The default schema generator has generate the below code.

```ruby
class MySchema < GraphQL::Schema
  mutation(Types::MutationType)
  query(Types::QueryType)

  # Opt in to the new runtime (default in future graphql-ruby versions)
  use GraphQL::Execution::Interpreter
  use GraphQL::Analysis::AST

  # Add built-in connections for pagination
  use GraphQL::Pagination::Connections
end
```

But, Can't use the MyAnalyzer in that code.
Should exclude plugins for `GraphQL::Execution::Interpreter` and  `GraphQL::Analysis::AST`.

So I confused.
And it is not kindness.

I propose appending to that note in the documentation.
Do you think it is good?

**Comment by swalkinshaw** [comment]
Yeah looks like the docs need some note about which versions they apply to.

Here's the proper AST analyzer docs for 1.10+: https://graphql-ruby.org/queries/ast_analysis.html

**Comment by rmosolgo** [comment]
Sorry for the trouble! I removed the old docs altogether in f38340a
