### ISSUE TITLE
Very broken behavior if field name begins with a capital letter

### ISSUE THREAD

**Issue by breathe** [rmosolgo/graphql-ruby#2772]
1. Try to define a field which starts with a capital letter
2. Use camelize :true, false or leave camelize unspecified as argument to field
3. Very broken behavior results in all cases

Doesn't work but should
```
class Types::SomeType < Types::BaseObject
  field :Foo, [String], null: false

  def Foo
    ["asdf"]
  end
end
```

Does work but shouldn't
```
class Types::SomeType < Types::BaseObject
  field :Foo, [String], null: false

  def foo
    ["asdf"]
  end
end
```

**Comment by breathe** [comment]
It appears that camelize : true/false affects the behavior of the graphql schema -- but not the behavior of the names of the field resolver methods ...

God I hate ruby.

**Comment by rmosolgo** [comment]
Sorry it didn't work the way you expected 😖 Before it auto-magically transformed resolver names, I got as many complaints about the previous behavior!

**Comment by breathe** [comment]
I guess this behavior is the best — my understanding (now) is that capitalized method names would not have worked correctly in ruby ...
