### ISSUE TITLE
Use same graphql_name for different types

### ISSUE THREAD

**Issue by christophweegen** [rmosolgo/graphql-ruby#2774]
Hello!

I'm trying to dynamically generate types with a `graphql_name` of `Success`.

These types are possible result type of mutations/resolvers.

Each `Success` type has a `payload` field whose type is differing each time.

Trying to generate multiple types with `graphql_name` of `Success` this way yields following error message:

```
Conflicting type definitions for `Success`: ...
```

is there a workaround to this, because I would like to have a result schema like I described in issue https://github.com/rmosolgo/graphql-ruby/issues/2737 or isn't that possible because the spec doesn't allow for different types to have the same name? 

I guess this could/would break introspection and the type system in general by having ambiguous type names..

Thanks a lot!

**Comment by swalkinshaw** [comment]
> or isn't that possible because the spec doesn't allow for different types to have the same name?

That's correct. You'll need to prefix/suffix `Success` with something unique to the mutation/resolver like the other issue you linked. It uses `resolver_name` to make it unique.

**Comment by rmosolgo** [comment]
☝️  yep, it's not allowed by the spec, and the system wouldn't work if types had the same name. Let me know if you run into any trouble using `Success` as a prefix or suffix!

**Comment by christophweegen** [comment]
@swalkinshaw @rmosolgo thanks for answering.

Now my first idea of having a union type `Result` with `Success` and `Failure` doesn't work as intended. I got them to work correctly but these `Success` / `Failure` names get quite long for querying them elegantly with inline fragments now. Will think about another solution. But thanks either way! :+1:
