### ISSUE TITLE
Providing method instance attribute to field does not suppress method conflict warning

### ISSUE THREAD

**Issue by DanielEFrampton** [rmosolgo/graphql-ruby#2775]
### Description

Providing a `method:` instance attribute to a field on a `Type` does not suppress the `method_conflict_warning` message. 

In our app we have a `module` field on the UserType which correctly flags the warning. We want the behavior provided by the `method:` instance attribute, calling a method other than the field name, namely `mod`. After doing so, we still receive the `method_conflict_warning` when running GraphQL query endpoint tests against that type. The warning message instructs us to use `resolver_method:`, but we would prefer not to write a resolver method just to wrap the existing `mod` attribute.

For the time being we resolved this by suppressing the warning, but unless there's something I don't understand about the situation it seems like that should be unnecessary because `method:` avoids the use of the conflicting method.

The field in question in our `user_type.rb` file:

```ruby
module Types
  class UserType < Types::BaseObject
    #  ...
    field :module, String,
          null: false,
          method: :mod,
          method_conflict_warning: false
    # ... 
  end
end
```

### Graphql version and other applicable versions (Rails, graphql-batch, etc)
- rails (6.0.2.1)
- graphql (1.10.3)
- graphiql-rails (1.7.0)

### Definitions of schema or relevant types and fields (in Ruby is best, in GraphQL IDL is ok)

The relevant portion of our PostgreSQL schema:

```ruby
  create_table "users", force: :cascade do |t|
    # ...
    t.string "mod"
   # ...
  end
```

### Example GraphQL query and response (if query execution is involved)

Running our test suite produces no errors but prints this warning message:
```
User's `field :module` conflicts with a built-in method, use `resolver_method:` to pick a different resolver method for this field (for example, `resolver_method: :resolve_module` and `def resolve_module`). Or use `method_conflict_warning: false` to suppress this warning.
```

### Side note

This is my first GitHub Issue outside of my own projects; I would welcome any feedback on how I presented the problem.

**Comment by rmosolgo** [comment]
Hi, thanks for the detailed bug report! I _think_ you're right, that setting a `method:` should make this message go away. 

I'll have to take a look at the implementation -- I don't think it smartly prioritizes whether to call a method on the GraphQL object type, or on the underlying application object, even if `method:` is given. But it seems like a better behavior would be to _recognize_ when `method:` is given, and not even look for an instance method on the GraphQL object type in that case. Similar to #2723 

> feedback

It was great, thanks! It described the problem, outlined a desired solution, and provided all the relevant background info. I wish all my bug reports looked like this 😉
