### ISSUE TITLE
Subscription triggers empty query

### ISSUE THREAD

**Issue by vlad-iml** [rmosolgo/graphql-ruby#2776]
When I use a subscription in an Angular component I notice that the subscription triggers a query containing the subscription.
Currently I have found a workaround to prevent my code from blowing up by adding `null: true` to the subscription type field.

Is this expected behaviour, or am I doing something wrong? Thanks!

Screenshot of the logs from `/cable`:
![Screenshot 2020-02-25 at 14 24 10](https://user-images.githubusercontent.com/54025859/75251271-88554c80-57da-11ea-8581-b8ed58fd660a.png)

My subscription type:
```
  class SubscriptionType < BaseObject
    extend GraphQL::Subscriptions::SubscriptionRoot

    field :previews_generated, QuestionGroup, null: true do
      argument :question_group_id, ID, required: true
    end

    def previews_generated(question_group_id:)
      object
    end
  end
```

**Comment by rmosolgo** [comment]
🤔  Hmm, I think it _should_ work better if you remove `def previews_generated ... end`. That way, you should get default behavior from here: 

https://github.com/rmosolgo/graphql-ruby/blob/f38340a7ff57af25c9fe4ed7ef9896f8a931476a/lib/graphql/subscriptions/subscription_root.rb#L16-L20

That would result in an empty response after the initial subscription. 

Want to give that a try? 

```diff
-     def previews_generated(question_group_id:)
-       object
-     end
```

**Comment by vlad-iml** [comment]
That solved the issue!

In this case my `def previews_generated` doesn't do much, so removing it is not a problem.
But let's say I wanted to do some manipulations on the object, how would I write this method?
Would I have to check the context to make sure it's a subscription update, like so?
```ruby
def previews_generated(question_group_id:)
  if context.query.subscription_update? 
    # do something with object
  else 
    context.skip 
  end 
end

```

**Comment by rmosolgo** [comment]
Yes, you could do it like that. First-class support for that kind of code comes in `GraphQL::Schema::Subscription`, a kind of resolver: https://graphql-ruby.org/subscriptions/subscription_classes.html

Glad it worked for you!
