### ISSUE TITLE
#arguments_for behavior changed between 1.9 and 1.10 when using variables vs inlining

### ISSUE THREAD

**Issue by modosc** [rmosolgo/graphql-ruby#2778]
we are already using the new interpreter/ast classes on 1.9. in that case, inside of `on_enter_field`, calling `visitor.query.arguments_for(ast_node, visitor.field_definition)` returns something like the following, regardless of whether the `input` arguments are passed inline or as a variable:
```
=> #<#<Class:0x00007fee09340978>:0x00007fedf0a11d88
 @argument_values=
  {"input"=>
    #<GraphQL::Query::Arguments::ArgumentValue:0x00007fedf0a11c70
     @default_used=false,
     @definition=
      #<GraphQL::Argument:0x00007fee0b7a8a90
       @as=nil,
       @clean_type=UpdateJobInput!,
       @description=nil,
       @dirty_type=#<Proc:0x00007fee0b7a8a40@/Users/jon/.rvm/gems/ruby-2.6.5@swoop/gems/graphql-1.9.18/lib/graphql/schema/argument.rb:103 (lambda)>,
       @expose_as="input",
       @metadata=
```

with `1.10`, the same call returns a plain hash with `:input` as the root key, and all other keys stringified when the `input` arguments are passed as a variable, but the above structure when the input values are inlined into the mutation:
```
{:input=>
  {"asdf"=>
    {"id"=>"6Hx2yeCQaGDnRf1EnqOt5U"
...
```

**Comment by rmosolgo** [comment]
I think this is _half_ a bug.  The interpreter and 1.10 are moving towards plain Ruby hashes for arguments, for simplicity's sake and to work better with Ruby `**kwargs` handling. 

But, they should be _symbol_-keyed hashes, not strings as seen here!

**Comment by modosc** [comment]
is the idea that the ruby hashes will also be converted to underscore when they come in?

**Comment by rmosolgo** [comment]
Yes, that's right -- similar to how field names are :sparkles: automagically ✨ 😩  underscored.
