### ISSUE TITLE
arguments_for #dig behavior changed between 1.9 and 1.10 

### ISSUE THREAD

**Issue by modosc** [rmosolgo/graphql-ruby#2779]
in 1.9 with the new ast/runtime we could do this:
```
visitor.query.arguments_for(ast_node, visitor.field_definition).dig(:input, :someCamelCasedField)
```

but with 1.10 this doesn't work - we have to snake case everything:
```
visitor.query.arguments_for(ast_node, visitor.field_definition).dig(:input, :some_camel_cased_field)
```

is there a way to get the previous behavior? alternately, is this in the docs anywhere?

**Comment by modosc** [comment]
in digging deeper, here:

https://github.com/modosc/graphql-ruby/blob/master/lib/graphql/schema/input_object.rb#L16

curious why when `ruby_kwargs` aren't provided both `@ruby_style_hash` and `@arguments` are populated but when `ruby_kwargs` are provided only `@ruby_style_hash` is populated.  would it be reasonable to always construct both here?

**Comment by modosc** [comment]
is this similar to #2778 in that ideally the results would be just a plain ruby hash, or is there more complexity to think about?

**Comment by rmosolgo** [comment]
> plain ruby hash

I think the ideal behavior in 1.10 is: 

- Hash, with snake-cased keys (like arguments passed into resolve methods)
- Except that input objects are _instances_ of their input object type 

So, dig _should_ work with snake-cased keys, as you noted in your original post. 

But I don't think this is a bug. The auto-snake-casing is described here https://graphql-ruby.org/fields/arguments.html.

**Comment by modosc** [comment]
i'll just convert our usage to snake case then, thanks!
