### ISSUE TITLE
Variable validators don't work for variables in non-nullable lists in mutations

### ISSUE THREAD

**Issue by jemminger** [rmosolgo/graphql-ruby#2780]
Basically the same (I think) as https://github.com/rmosolgo/graphql-ruby/issues/878 but for mutations.

I have a mutation defined as:
```ruby
module Mutations
  class UserDeleteByEmail < Mutations::Base

    argument :emails, [String], required: true

    field :node, [Types::User], null: true
    field :errors, [Types::Error], null: true

    def resolve(emails:)
      ...
    end
  end
end
```

And in a spec:
```graphql
mutation($emails: [String!]) {
  userDeleteByEmail(emails: $emails) {
    node {
      email
    }
    errors {
      field
      reason
      placeholders
    }
  }
}
```

The spec will fail with 
```ruby
GraphQL::ExecutionError:
[{"message"=>
   "Nullability mismatch on variable $emails and argument emails ([String]! / [String!]!)",
  "locations"=>[{"line"=>2, "column"=>21}],
  "path"=>["mutation", "userDeleteByEmail", "emails"],
  "extensions"=>
   {"code"=>"variableMismatch",
    "variableName"=>"emails",
    "typeName"=>"[String]!",
    "argumentName"=>"emails",
    "errorMessage"=>"Nullability mismatch"}}]
=> [{"message"=>"Nullability mismatch on variable $emails and argument emails ([String]! / [String!]!)",
  "locations"=>[{"line"=>2, "column"=>21}],
  "path"=>["mutation", "userDeleteByEmail", "emails"],
  "extensions"=>
   {"code"=>"variableMismatch",
    "variableName"=>"emails",
    "typeName"=>"[String]!",
    "argumentName"=>"emails",
    "errorMessage"=>"Nullability mismatch"}}]
```

If I paste that mutation into GraphiQL, it shows an error at `mutation($emails:`, with the error being
```
Variable "$emails" of type "[String!]" used in position expecting type "[String!]!".
```

**Comment by rmosolgo** [comment]
Hi, thanks for the report! It looks like GraphQL-Ruby is showing the _wrong type_ in the error message -- it's showing `[String]!` but it should show `[String!]`, is that right?

**Comment by jemminger** [comment]
Perhaps, but the problem is that I can't execute the mutation, it throws this error.

**Comment by rmosolgo** [comment]
> problem is that I can't execute the mutation

It's a _feature_ 😅 

The argument `emails` was defined as `required: true`: 

```ruby
    argument :emails, [String], required: true
```

That means that the GraphQL type is `[String!]!` (a non-null list of non-null strings). 

In order to use a variable for that argument, you have to use the _same_ type for your variable. So you should update your query to include another `!`: 

```diff 
- mutation($emails: [String!]) {
+ mutation($emails: [String!]!) {
```

It's valid after that change because `$emails` is marked as _required_ (non-null), just like the argument definition. 

Does that work for you?

**Comment by jemminger** [comment]
I see now, I'll give that a try

**Comment by rmosolgo** [comment]
I added a test for the error message but it worked for me -- maybe the error message you posted was from a slightly different query? (Was the `!` _inside_ the square brackets, or _outside_ them?) 

Anyways, let me know if you're still having trouble with this!

**Comment by jemminger** [comment]
@rmosolgo Using `[String!]!)` works 😄
