### ISSUE TITLE
1.10: In subscriptions with multiple fields only first field is being subscribed

### ISSUE THREAD

**Issue by Envek** [rmosolgo/graphql-ruby#2795]
GraphQL-Ruby: 1.10.3

In multifield subscription queries only first field is usable. Other fields are ignored. This is regression in 1.10 (it works in 1.9.19).

Also it seems that it is only broken when subscription classes are **not** used.

**Query**:
```graphql
subscription SomeSubscription {
  productCreated { id title }
  productUpdated { id }
}
```

**Schema**:
```ruby
class Product < GraphQL::Schema::Object
  field :id, ID, null: false, hash_key: :id
  field :title, String, null: true, hash_key: :title
end

class SubscriptionType < GraphQL::Schema::Object
  field :product_created, Product, null: false
  field :product_updated, Product, null: false

  def product_created; end
  def product_updated; end
end

class ApplicationSchema < GraphQL::Schema
  subscription SubscriptionType
end
```

**Expected result**:

Both fields are registered in subscription backend (two events are passed into `GraphQL::Subscriptions#write_subscription`: one for every field)

**Actual result**:

Only first field is registered in subscription backend (only one event for first field is passed into `GraphQL::Subscriptions#write_subscription`)

**Test**:
<details>
  <summary>to be included in `spec/graphql/subscriptions_spec.rb:286` </summary>

```ruby
        it "sends updated data for multifield subscriptions" do
          query_str = <<-GRAPHQL
          subscription ($id: ID!){
            payload(id: $id) { str, int }
            event { int }
          }
          GRAPHQL

          # Initial subscriptions
          res = schema.execute(query_str, context: { socket: "1" }, variables: { "id" => "100" }, root_value: root_object)

          empty_response = TESTING_INTERPRETER ? {} : nil

          # Initial response is nil, no broadcasts yet
          assert_equal(empty_response, res["data"])
          assert_equal [], deliveries["1"]

          # Application stuff happens.
          # The application signals graphql via `subscriptions.trigger`:
          schema.subscriptions.trigger(:payload, {"id" => "100"}, root_object.payload)

          # Let's see what GraphQL sent over the wire:
          assert_equal({"str" => "Update", "int" => 1}, deliveries["1"][0]["data"]["payload"])
          assert_equal(nil,                             deliveries["1"][0]["data"]["event"])

          # Trigger another field subscription
          schema.subscriptions.trigger(:event, {}, root_object.event)

          # Now we should get result for another field (HERE IT FAILS)
          assert_equal(nil,          deliveries["1"][1]["data"]["payload"])
          assert_equal({"int" => 1}, deliveries["1"][1]["data"]["event"])
        end
```
</details>

**Reasons**:

In `GraphQL::Subscriptions::Instrumentation::SubscriptionRegistrationResolve#call` is passed context bound to the first field of a subscription, so there is no access to other subscription fields.

https://github.com/rmosolgo/graphql-ruby/blob/610cdef960893d68ae7592b66b058a2f4e394fb7/lib/graphql/subscriptions/instrumentation.rb#L46-L61

Here `ctx` is a `#<GraphQL Context @ Subscription.productCreated>`.

**Related links**:

Failing test in graphql-anycable gem: [code](https://github.com/Envek/graphql-anycable/blob/f24e61dc401e7ecdae472ce87f22eb05625e0019/spec/graphql/anycable_spec.rb#L52-L68), [CI output](https://travis-ci.org/Envek/graphql-anycable/jobs/657744407).

---

Hope I was able to provide enough details to fix it. Thank you for graphql-ruby!

**Comment by rmosolgo** [comment]
Weird! Thanks for sharing the failing test 👀

**Comment by rmosolgo** [comment]
Thanks again for reporting this. I added your test (with a small change -- `root_object.event` is `nil`, so I replaced it with `OpenStruct.new(int: 1)`) in e9e98a2d5. 

I found that it passed with `TESTING_INTERPRETER=1`, so my recommended "fix" here is to use the new runtime! I don't have bandwidth to hunt this bug in the previous runtime, but if someone wants to contribute a fix, I'd happily merge and release it.

**Comment by Envek** [comment]
What fixed it for old non-interpreter runtime is subscription resolver redefinition as you suggested in https://github.com/rmosolgo/graphql-ruby/issues/2754#issuecomment-587557702

```ruby
class SubscriptionType < GraphQL::Schema::Object
  field :product_created, Product, null: false, resolver_method: :default_resolver
  field :product_updated, Product, null: false, resolver_method: :default_resolver

  def default_resolver
    return object if context.query.subscription_update?

    context.skip
  end
end
```
