### ISSUE TITLE
Schema.unauthorized_field is not called when using graphql-pro and pundit

### ISSUE THREAD

**Issue by scottserok** [rmosolgo/graphql-ruby#2800]
I am testing out `graphql-pro` with Pundit for authorization, but I'm unable to raise an unauthorized exception by following [the authorization docs](https://github.com/rmosolgo/graphql-ruby/blob/master/guides/pro/authorization.md).
```
GEM
  remote: https://rubygems.org/
  remote: https://gems.graphql.pro/
  specs:
    graphql (1.10.3)
    graphql-pro (1.13.0)
      graphql (>= 1.7.5)
    pundit (2.1.0)
      activesupport (>= 3.0.0)

PLATFORMS
  ruby

RUBY VERSION
   ruby 2.6.5p114

BUNDLED WITH
   2.1.4
```
I have a schema defined with
```ruby
class MySchema
  query MyQueryType
  authorization :pundit, namesapce: Policies

  def self.unauthorized_field(error)
   raise GraphQL::ExecutionError, "An object of type #{error.type.graphql_name} was hidden due to permissions"
  end
```
and another class for `MyQueryType`
```ruby
class MyQueryType < GraphQL::Schema::Object
  field :users, UserType do
    authorize :read
```
and my policy defined as
```ruby
module Policies
  class UserPolicy < ApplicationPolicy
    def read?
      false
    end
```
when I test this I'd expect the exception to be raised from `MySchema.unauthorized_field` but instead I'm seeing the backtrace leads the program to call `GraphQL::Pro::Access::Instrumentation::UnauthorizedObject.call(obj, tc)` which returns nil. I've also tried to define `MySchema.unauthorized_object` but the results are the same.

If it's helpful I'm seeing the following schema metadata configuration when I set a breakpoint inside of the query field execution.
```
context.schema.metadata
{:__pro_access_current_user__=>:current_user, :__pro_access_strategy__=>GraphQL::Pro::Access::PunditStrategy, :__pro_access_strategy_options__=>{:ability_class=>nil}, :__pro_access_unauthorized_fields__=>GraphQL::Pro::Access::Analyzer::UnauthorizedFields, :__pro_access_unauthorized_object__=>GraphQL::Pro::Access::Instrumentation::UnauthorizedObject, :__pro_access_operation_store_strategy__=>nil}
```

I'm new to GraphQL, maybe I am using this wrong? How can I configure my schema to raise an exception when the pundit policy fails to authorize the user?

**Comment by rmosolgo** [comment]
Sorry for the confusion here! The Pundit integration is in a bit of flux. The docs you linked are for a previous implementation; if you check the "Note" at the top of the page, you'll see a link here: 

https://graphql-ruby.org/authorization/pundit_integration.html

☝️ That integration will call the unauthorized_field hook. Could you try setting it up _that_ way and let me know how it goes?

**Comment by rmosolgo** [comment]
(I just removed that old doc in 2cc2ba46c)

**Comment by scottserok** [comment]
Thanks @rmosolgo! I enjoyed the simplicity of `authorize :pundit, namespace: Policy` 😄. I'm struggling to set up the new pundit integration to the point where I can test the original problem reported. Let me know if you'd prefer separate GH issues for these.

When I set `pundit_role nil` in a class like BaseField or BaseObject, I'm expecting the authorization check to be skipped but instead the integration is looking for a NilClassPolicy to check `pundit_role` value against.  [Based on these docs](https://graphql-ruby.org/authorization/pundit_integration.html#authorizing-objects). Is that expected behavior?

When my CustomPolicyLookup class is executed as part of executing a query requesting a field from my QueryType object, the object argument in `pundit_policy(context, object)` is always nil. I was expecting to have some object (either the return type object or the result of executing the query type field). How do I get access to an object for looking up the appropriate policy class?

All of my testing so far is based on request specs that were passing before implementing the pundit integration, so I'm confident that the queries work and return records (not nil). The above behavior leaves me feeling like something isn't set up right, but I've updated the base type classes as indicated in the docs. I'm not setting `pundit_role` anywhere else yet, only at the parent type level.

Minor/pedantic feedback: The `pundit_role` method name seems misleading if we're not defining roles (staff, admin, contractor) on our policy but rather permissions (read, update, create, destroy), we may use RBAC but that's an implementation detail of the policy. I'm curious to learn if there are any experiences from projects that started down the path of using read, update, create, etc. but decided it was better to go with role names instead?

**Comment by rmosolgo** [comment]
> looking for a NilClassPolicy

No, that's not expected! Could you please share the full error message and stack trace? 

> requesting a field from my QueryType object, the object argument in `pundit_policy(context, object)` is always nil

The `object` there is the application object "behind" the current GraphQL type. For root types, the application object is whatever you pass as `root_value:` in `MySchema.execute(..., root_value: ...)`. If you don't pass anything, it will be nil. 

It can only be `nil` in the context of root level fields. When `nil` appears in other contexts, it's returned in in the GraphQL response as-is. So, you can either pass a `root_value:` or handle `nil` in that case. 

> `pundit_role` method name seems misleading

Yes, perhaps a poor choice of name on my part, also reported at #2181

**Comment by scottserok** [comment]
```
          GraphQL::Pro::PunditIntegration::PolicyNotFoundError:
            No policy found for:

            - Type: Query
            - Runtime value: `nil`

            Pundit error: Pundit::NotDefinedError, unable to find policy `NilClassPolicy` for `nil`
          # /usr/local/bundle/ruby/2.6.0/gems/graphql-pro-1.13.0/lib/graphql/pro/pundit_integration.rb:295:in `rescue in pundit_policy'
          # /usr/local/bundle/ruby/2.6.0/gems/graphql-pro-1.13.0/lib/graphql/pro/pundit_integration.rb:286:in `pundit_policy'
          # /usr/local/bundle/ruby/2.6.0/gems/graphql-pro-1.13.0/lib/graphql/pro/pundit_integration.rb:315:in `authorized_by_policy?'
          # /usr/local/bundle/ruby/2.6.0/gems/graphql-pro-1.13.0/lib/graphql/pro/pundit_integration.rb:108:in `authorized?'
          # /usr/local/bundle/ruby/2.6.0/gems/graphql-1.10.3/lib/graphql/schema/object.rb:40:in `block in authorized_new'
          # /usr/local/bundle/ruby/2.6.0/gems/graphql-1.10.3/lib/graphql/query.rb:311:in `block in with_error_handling'
          # /usr/local/bundle/ruby/2.6.0/gems/graphql-1.10.3/lib/graphql/execution/errors.rb:30:in `with_error_handling'
          # /usr/local/bundle/ruby/2.6.0/gems/graphql-1.10.3/lib/graphql/query.rb:310:in `with_error_handling'
          # /usr/local/bundle/ruby/2.6.0/gems/graphql-1.10.3/lib/graphql/schema/object.rb:38:in `authorized_new'
          # /usr/local/bundle/ruby/2.6.0/gems/graphql-1.10.3/lib/graphql/schema/member/instrumentation.rb:30:in `before_query'
          # /usr/local/bundle/ruby/2.6.0/gems/graphql-1.10.3/lib/graphql/execution/instrumentation.rb:58:in `public_send'
          # /usr/local/bundle/ruby/2.6.0/gems/graphql-1.10.3/lib/graphql/execution/instrumentation.rb:58:in `block in call_hooks'
          # /usr/local/bundle/ruby/2.6.0/gems/graphql-1.10.3/lib/graphql/execution/instrumentation.rb:57:in `each'
          # /usr/local/bundle/ruby/2.6.0/gems/graphql-1.10.3/lib/graphql/execution/instrumentation.rb:57:in `call_hooks'
          # /usr/local/bundle/ruby/2.6.0/gems/graphql-1.10.3/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
          # /usr/local/bundle/ruby/2.6.0/gems/graphql-1.10.3/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
          # /usr/local/bundle/ruby/2.6.0/gems/graphql-1.10.3/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
          # /usr/local/bundle/ruby/2.6.0/gems/graphql-1.10.3/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
          # /usr/local/bundle/ruby/2.6.0/gems/graphql-1.10.3/lib/graphql/execution/multiplex.rb:175:in `instrument_and_analyze'
          # /usr/local/bundle/ruby/2.6.0/gems/graphql-1.10.3/lib/graphql/execution/multiplex.rb:61:in `block in run_queries'
          # /usr/local/bundle/ruby/2.6.0/gems/graphql-1.10.3/lib/graphql/tracing.rb:66:in `block in trace'
          # /usr/local/bundle/ruby/2.6.0/gems/graphql-1.10.3/lib/graphql/tracing.rb:80:in `call_tracers'
          # /usr/local/bundle/ruby/2.6.0/gems/graphql-1.10.3/lib/graphql/tracing.rb:66:in `trace'
          # /usr/local/bundle/ruby/2.6.0/gems/graphql-1.10.3/lib/graphql/execution/multiplex.rb:59:in `run_queries'
          # /usr/local/bundle/ruby/2.6.0/gems/graphql-1.10.3/lib/graphql/execution/multiplex.rb:49:in `run_all'
          # /usr/local/bundle/ruby/2.6.0/gems/graphql-1.10.3/lib/graphql/schema.rb:1557:in `multiplex'
          # /usr/local/bundle/ruby/2.6.0/gems/graphql-1.10.3/lib/graphql/schema.rb:1528:in `execute'
          # ./spec/support/graphql_spec_helpers.rb:3:in `graphql_result'
          # ./spec/graphql/queries/my_query_spec.rb:2:in `block (2 levels) in <top (required)>'
          # ./spec/spec_helper.rb:77:in `block (2 levels) in <top (required)>'
          # ./spec/spec_helper.rb:66:in `block (3 levels) in <top (required)>'
          # /usr/local/bundle/ruby/2.6.0/gems/database_cleaner-1.8.3/lib/database_cleaner/generic/base.rb:16:in `cleaning'
          # /usr/local/bundle/ruby/2.6.0/gems/database_cleaner-1.8.3/lib/database_cleaner/configuration.rb:87:in `block (2 levels) in cleaning'
          # /usr/local/bundle/ruby/2.6.0/gems/database_cleaner-1.8.3/lib/database_cleaner/configuration.rb:88:in `cleaning'
          # ./spec/spec_helper.rb:65:in `block (2 levels) in <top (required)>'
          # ------------------
          # --- Caused by: ---
          # Pundit::NotDefinedError:
          #   unable to find policy `NilClassPolicy` for `nil`
          #   /usr/local/bundle/ruby/2.6.0/gems/pundit-2.1.0/lib/pundit/policy_finder.rb:54:in `policy!'
```
Here's more concrete description of the changes to my base types
```patch
 module Types
   class BaseField < GraphQL::Schema::Field
+    include GraphQL::Pro::PunditIntegration::FieldIntegration
+    include CustomPolicyLookup
+    pundit_role :read
   end
 end

 module Types
   module BaseInterface
     include GraphQL::Schema::Interface
+    include GraphQL::Pro::PunditIntegration::InterfaceIntegration
+    field_class Types::BaseField
   end
 end

 module Types
   class BaseObject < GraphQL::Schema::Object
+    include GraphQL::Pro::PunditIntegration::ObjectIntegration
+    field_class Types::BaseField
+    pundit_role :read
   end
 end
```

**Comment by scottserok** [comment]
I noticed I changed my top level `pundit_role` from `nil` to `:read` while testing. I went ahead and set them back to `nil`. I no longer get the error `unable to find policy NilClassPolicy for nil` :tada: / 😕 .

**Comment by scottserok** [comment]
Alright so the issue seems to be with using `pundit_role :read` at the top level BaseObject class or even in the QueryType class. Those trigger the NilClassPolicy error.  

When I set the `pundit_role nil` at top level classes and only set the `pundit_role :read` inside of a custom type like UserType, then I can confirm the Schema.unauthorized_field is called when the policy returns false. So the original problem described in this issue is solved by using the new pundit integration. Thanks for pointing me to the correct docs @rmosolgo 🙏 

I can open a separate issue if you think there's an issue worth addressing with regards to the stack trace + `pundit_role :read` configuration in BaseObject.
