### ISSUE TITLE
How can I prevent access for schema part in 1.10

### ISSUE THREAD

**Issue by wis-ekubesh** [rmosolgo/graphql-ruby#2801]
Hi,

in pervious versions we have had **accessible?** method where we could put a check for user auth.
It was really useful in my case - I have ~5 public queries and if user wants to have an access for another - he must provide some key before. I had class AuthorizedQuery which extends BaseQuery and all my private queries extends AuthorizedQuery. In AuthorizedQuery I just checked provided key.

After 1.10 **accessible?** was deprecated and I not sure that I understand how can I do this now? 

**authorized?** calls twice (before and after query), **visible?** is another thing.... Could you clarify please what is your idea was?

Thanks, have a good day!

**Comment by rmosolgo** [comment]
My idea was to use `authorized?` for this. Could you please share the details about your situation? What happened when you tried `authorized?`?

**Comment by rmosolgo** [comment]
Feel free to share more details here if you'd like to continue the conversation.
