### ISSUE TITLE
Document use of custom scalars with .from_definition()

### ISSUE THREAD

**Issue by leehambley** [rmosolgo/graphql-ruby#2813]
**Is your feature request related to a problem? Please describe.**

Due to interop with other services, I want to use the GraphQL IDL not the Ruby DSL to define my schema. That has no documentation I can find (nor any test cases, or open GitHub issues) on how to make the decoder implementation for the scalar type known to the `Schema`.

**Describe the solution you'd like**

Ideally I'd love to see a way documented to use custom scalars with the IDL. Alternatively if someone can point me in the right direction in this feature request, I can write up the docs, and maybe a test-case myself and submit a correct implementation.

**Describe alternatives you've considered**

I've tried the following:

``` ruby
class TestSch3ma < Minitest::Test
  def setup
    resolvers = {
      "Query" => {
        "echo" => ->(obj, args, ctx)  {
          # args.class => Hash
          # => "{:rfc3339_date=>\"HELLO WORLD\"}"
        }
      }
    }
    definition = <<~EOF
      scalar RFC3339Date
      type Query {
        echo(rfc3339Date: RFC3339Date!): String!
      }
    EOF
    @schema = GraphQL::Schema.from_definition(definition, default_resolve: resolvers)
  end
  def test_supporting_custom_scalars_in_resolvers
    @schema.execute('query { echo(rfc3339Date: "HELLO WORLD")}')
  end
end
```

The output in the resolver shows that the input is not parsed, and the coercion error is not raised.

A type definition for that custom scalar is defined, and required already, and would be available, but of course the schema has no way to know about it:

``` ruby
require 'time'

module Types
  class BaseScalar < GraphQL::Schema::Scalar
  end
  class RFC3339DateTime < Types::BaseScalar
    def self.coerce_input(input_value, _context)
      DateTime.rfc3339(input_value)
    rescue Date::Error
      err = "#{input_value.inspect} does not conform to RFC3339"
      raise GraphQL::CoercionError, err
    end

    def self.coerce_result(ruby_value, _context)
      ruby_value.to_s
    end
  end
end
```

**Comment by rmosolgo** [comment]
Hey @leehambley, when you pass a Hash to `.from_defintion`, it can contain keys that match the names of custom scalars, and those keys can point to hashes like `{ coerce_input:, coerce_result: }`. Here's an example from the tests: 

https://github.com/rmosolgo/graphql-ruby/blob/c2f750033061bc1f910ba15866236a1552b89cc2/spec/graphql/schema/build_from_definition_spec.rb#L1034-L1041

Alternatively, if a non-Hash object is given as `default_resolve`, if that object implements `.coerce_input` and `.coerce_result`, those methods are called. I don't see tests for that behavior, but the implementation is here: 

https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/build_from_definition.rb#L183-L191

(And the hash-based behavior uses those hooks too, see: https://github.com/rmosolgo/graphql-ruby/blob/c2f750033061bc1f910ba15866236a1552b89cc2/lib/graphql/schema/build_from_definition/resolve_map.rb#L66-L72) 

Sorry it's not documented! That'd be a great improvement if you'd like to contribute the docs.

**Comment by leehambley** [comment]
Hi @rmosolgo thanks so much for a super fast and comprehensive answer. I overlooked that test, but have confirmed (to nobody's surprise) that this works perfectly for me now! :tada: 

I think the most appropriate place for documentation might be in the `.from_definition` rdocs with an inline example or two (I had to do some digging on what format the default resolver hash/class was supposed to be)

So I could generally improve the (rdoc) docs for .from_definition in a quick PR, would you like that?
