### ISSUE TITLE
Warn when there's an interface with no implementations

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#2817]
When an interface's implementations are all orphan types, it gets added to the schema with no implementations. Then at runtime, the interfaces is hidden ... and so are its fields, and so on, because of schema hiding. 

I think we could do better by warning at the end of `query(...)` and `mutation(...)` if any empty interfaces were added to the schema. It's technically possible that it would be _over-warning_, but it might still help.

**Comment by eapache** [comment]
An interface should only be hidden if it has no references, not if it has no implementations? I'd think
```graphql
type QueryRoot {
  foo: Foo!
}

interface Foo {
  bar: String!
}
```

Should be a valid, queryable schema?

**Comment by rmosolgo** [comment]
What queries would it be able to serve? 

At least in GraphQL-Ruby, the only ones I can think of are introspection-related -- anything accessing `foo { ... }` would fail because it couldn't resolve the type of the underlying object (and there's no `GraphQL::Schema::Object` class to initialize for it).

I definitely agree that the spec _allows for_ interfaces with no implementations, but I don't understand _why_ 🤔

**Comment by eapache** [comment]
🤔 without thinking about the implementation too much I'd think `{ foo { bar } }` should be an executable query on the schema I provided. But I guess `{ foo { __typename } }` would fail in a way that effectively makes the schema malformed?

**Comment by michal-samluk** [comment]
Question:
So if I have a private and public schema, does it mean that when I am using the second one I will get warning while executing and/or dumping it? 

E.g. some types may use interface, and those types may have hidden visibility.

**Comment by rmosolgo** [comment]
>  private and public schema

No, it wouldn't warn in that case. I'm considering adding a warning when the _whole_ schema has _no_ implementations for an interface (including hidden ones), and trying to warn during schema initialization. 

In the case you mentioned, I think the current behavior is good: an interface with no implementations is hidden.

In fact, that's what made me think about this. Currently, if you configure a schema with no implementations, GraphQL-Ruby hides it at runtime because it thinks that all of its implementations are hidden.
