### ISSUE TITLE
Document usage of middlewares when using from_schema

### ISSUE THREAD

**Issue by leehambley** [rmosolgo/graphql-ruby#2818]
**Is your feature request related to a problem? Please describe.**

I'm unable to use Middlewares, and it's not clear from the docs how to do it. Middlewares, plugins, and surprising uses of the `schema.middleware << Foo` in the existing specs have left me clueless.

**Describe the solution you'd like**

- To know the function signature for a `callable`.
- To know if the usage 

**Describe alternatives you've considered**

```
# frozen_string_literal: true

require 'test_helper'

class TestUsingAMiddleware < Minitest::Test
   def definition
    <<~EOSCHEMA
      type Foo {
        pong: String!
      } 
      type Query {
        ping: Foo!
      }
    EOSCHEMA
  end

  def resolvers
    {
      'Query' => {
        'ping' => ->(_obj, _args, _ctx) { {pong:"hello world"} }
      },
      'Foo' => {
        'pong' => ->(obj, _args, _ctx) { obj[:pong] }
      }
    }
  end

  def schema
    s = GraphQL::Schema.from_definition(
      definition,
      default_resolve: resolvers
    )
    s.middleware lambda {|foo, &block| raise "boom"; binding.pry; yield }
    # ... or ...
    s.middleware << lambda {|foo, &block| raise "boom"; binding.pry; yield }
    s
  end

  def test_applying_middleware
    s = schema
    res = s.execute(<<~EOQUERY)
      query { ping { pong } }
    EOQUERY
    assert_equal res['data']['ping']['pong'], 'hello world'
  end
end
```

Two things about the implementation (which I've been stepping through with a debugger all morning) are confusing:

- The timeout middleware spec here https://github.com/rmosolgo/graphql-ruby/blob/master/spec/graphql/schema/timeout_middleware_spec.rb#L40 uses the `<<` method, but the implementation here https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema.rb#L1511 that receives that looks like the assignment will go nowhere? (no argument given so we go into the `else` branch, where a new instance of `MiddlewareChain` is instantiated and not remembered anywhere, and no changes are made to `all_middlewares`?). This leaves me wondering how the timeout spec works at all, of course I trust that it does, and I'm just missing something.

- Whether middlewares are the right solution here or there's something else?

**Additional context**

We're trying to write a middleware to process an incoming JWT (which callers will inject into the context, which we will decode, and use to augment the context with user & claim metadata. It's possible there's a preferable approach)

**Comment by rmosolgo** [comment]
> Whether middlewares are the right solution here or there's something else?

Middlewares are deprecated-ish. They don't work with the new Interpreter runtime, which is used by default with `.from_definition`. 

Did you find docs about middlewares somewhere? I meant to remove it all, but maybe I missed a spot! 

>  process an incoming JWT

Is this a once-per-query operation? How about using a query instrumenter? https://graphql-ruby.org/queries/instrumentation This seems like a good fit for the `before_query` hook.

**Comment by leehambley** [comment]
> Middlewares are deprecated-ish. They don't work with the new Interpreter runtime, which is used by default with .from_definition.

That makes a lot of sense, I saw the internals are pretty convoluted between strategies, etc, etc.

Honestly I don't know that I found an explicit mention anywhere in the official docs, except that the API is still there, doesn't emit any warnings, and didn't warn when I used `schema.middleware <<..` on a `from_definition` schema.

I'd offer to send a PR for raising a `Kernel.warn` if using `schema.middleware <<` call where the runtime `is_a? Interpreter`.

I mostly assumed middlware was a thing, because it is in most other graphql implementations, adn in Rack and Rails and everywhere else, and there's still plenty of code in the repository dealing with it, and reference code I could find in specs/tests/etc. (Although I understand, of course why those must continue to exist, even though they're deprecated(ish))

>Middlewares are deprecated-ish. They don't work with the new Interpreter runtime, which is used by default with .from_definition.

Indeed it'd be there to process the `ctx` hash  and mutate it. I see from what you linked that the return value isn't used, given that `query` is a `GraphQL::Query` and I could access the `#context` that certainly seems viable. I'll report back.

Is there something useful I could do (simple doc PR, etc, as suggested above) to help reduce confusion for the next traveller on this road?

**Comment by rmosolgo** [comment]
A warning like you mentioned would be great. Warning during schema setup is a little tricky because the order of different configurations varies from setup to setup. But I think you could warn when executing a query, for example, I think the best place for it would be here: 

https://github.com/rmosolgo/graphql-ruby/blob/5f22e5475ef191047b702bae156febc82dfa0a63/lib/graphql/execution/interpreter.rb#L58-L64

You could check for `query.schema.middlewares.any?` and warn if there are any.

**Comment by rmosolgo** [comment]
I don't plan to work on this any further, but if anyone wants to submit a patch to warn in the cases discussed above, I'd welcome a PR!
