### ISSUE TITLE
[pro] GraphQL::Pro::Encoder explodes with an empty string

### ISSUE THREAD

**Issue by modosc** [rmosolgo/graphql-ruby#2819]
we're getting these now: `RuntimeError: A GraphQL::Pro::Encoder failed to decode a cipher, can't do anything with the result`

previously (with pro-1.11) an empty string was acceptable and treated the same as null. is it possible to restore the previous behavior?

**Comment by rmosolgo** [comment]
🤔 definitely didn't _mean_ to break this! Do you know _where_ the empty string is coming from (is it user input?), or could you share the full stack trace?

**Comment by modosc** [comment]
it's coming in as input, ie `query(first: 10, after: "")`

**Comment by modosc** [comment]
@rmosolgo i can pm you a stack trace if it would help, don't want to post it publicly
