### ISSUE TITLE
Cannot access pagination arguments in connection field resolvers

### ISSUE THREAD

**Issue by vecerek** [rmosolgo/graphql-ruby#2822]
Hey @rmosolgo 👋 

I've just updated to `1.10.4`, so that I can start experimenting with custom connections in order to implement proper cursor-based pagination. That is, I want to be able to pass the cursor (`before` or `after`) to a method that constructs a SQL query, so that I don't have to load all results into memory. I was surprised that the example code below would not let me access the pagination arguments. They would always be `nil` to be precise. I tried to construct a minimalistic example. Am I trying to use the tool wrong? If so, what is the expected way to do this? I couldn't find the answer on the [Pagination Guides](https://graphql-ruby.org/guides#pagination-guides) pages nor the [Relay Guides](https://graphql-ruby.org/guides#relay-guides) pages.

```rb
# query_type.rb

module GraphQL
  module Types
    class QueryType < ::GraphQL::Schema::Object
      graphql_name 'Query'

      field :search_something, Types::SomethingConnectionType, null: false, connection: true

      def search_something(first: nil, after: nil, last: nil, before: nil)
        # the named arguments are always `nil`
        Repo::Something.fetch(first, after, last, before) # This should build and execute a SQL query using one of the cursors
      end
    end
  end
end
```

```rb
# schema.rb

module GraphQL
  class Schema < ::GraphQL::Schema
    query Types::QueryType
    mutation Types::MutationType

    use ::GraphQL::Pagination::Connections

    cursor_encoder(UrlSafeBase64Encoder)
  end
end
```

```gql
{
  searchSomething(first: 2, after: "abcd1234") {
    edges {
      cursor
      node {
        id
      }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
    }
  }
}
```

**Comment by rmosolgo** [comment]
When you use `connection: true`, GraphQL-Ruby adds automatic connection handling: 

- It adds some argument definitions 
- It removes those argument values from resolvers 
- After calling a resolver, it applies a connection wrappers and uses the connection arguments for pagination 

You can disable these by using `connection: false` instead. But, when you use `connection: false`, you'll have to add the arguments yourself, too. 

I think that's what you're looking for, though! Let me know if you have other trouble with it.

**Comment by vecerek** [comment]
Thanks, @rmosolgo. I was able to explore a different approach based on your feedback which now fully works and is quite generic. The only assumption it makes is that all the query needs to know are the pagination arguments (`after`, `before`, `first` and `last`) and that each query should be able to define its own cursor encoding.

In spite of the above, I still found myself re-implementing a lot of basic things like determining whether there is a next/prev page (based on the [Relay spec](https://facebook.github.io/relay/graphql/connections.htm#HasPreviousPage())), what the actual page size should be, etc. This would otherwise be solved by the tool as I understand. I'll show you what I ended up doing and I'll try to add the smallest possible example here. However, I would expect a library like `graphql-ruby` to be more helpful here. But maybe I'm just not realizing something and not utilizing the full power of the tool. Maybe you can tell me 🙂I can also share the implementation details of the classes I omitted, for the sake of brevity, if you wish.

```rb
# query.rb

module GraphQL
  module Types
    class QueryType < ::GraphQL::Schema::Object
      graphql_name 'Query'

      field :search_something, Types::SomethingConnection, null: false, max_page_size: 20

      def search_something
        Types::SomethingConnection.page
      end
    end
  end
end
```
```rb
# something_connection.rb

module GraphQL
  module Types
    class SomethingConnection < ::GraphQL::Types::Relay::BaseConnection
      graphql_name 'SomethingConnection'
      edge_type SomethingEdgeType

      field :total, Int, null: false

      def total
        Repo::Something.count() # this runs a sql query
      end

      def self.page
        Pages::SomethingPage.new
      end
    end
  end
end
```
The `Page` interface assumes that every query will need a different cursor structure but all are json stringified and url safe base64 encoded in the end.
```rb
# pages/something_page.rb

module GraphQL
  module Types
    module Pages
      class SomethingPage < Base
        def page
          @page ||= Utils::Page.new(
            results: Repo::Something.fetch(
              param_1: 'something',
              param_2: 'something else',
              paginator: paginator,
            ), # this runs a sql query, it gets the cursor from the `paginator` object
            paginator: paginator,
            cursor_for: ->(item) { { created_at: item[:created_at], sort_order: 'asc' } },
          )
        end
      end
    end
  end
end
```

I had to re-implement the pagination logic using a `Page` and `Paginator` class. Through `Paginator` objects I can pass information around into the repositories (the thing that in the end runs some SQL). I will only include the methods signature but not the actual implementation of the classes to keep the comment as short as possible:
```rb
# pages/base.rb

module GraphQL
  module Types
    module Pages
      class Base < ::GraphQL::Pagination::Connection
        def initialize
          super([]) # Some object has to be passed in here 😕 
        end

        def nodes; end

        def has_next_page; end

        def has_previous_page; end

        def cursor_for(item); end

        private

        def page
          raise NotImplementedError
        end

        # Returns a Paginator object
        def paginator;end
      end
    end
  end
end
```
```rb
# utils/paginator.rb

module GraphQL
  module Utils
    class Paginator
      def initialize(after: nil, before: nil, first: nil, last: nil, max_page_size:); end
      def cursor; end
      def cursor?; end

      # Returns whether it should be the first/last/some next/some prev page
      def pagination; end

      # Actual page size
      def page_size; end

      # In SQL, alway ask for +1 to be able to determine next/prev page presence
      def limit
        page_size + 1
      end
    end
  end
end
```
```rb
# utils/page.rb

module GraphQL
  module Utils
    class Page
      def initialize(results:, paginator:, cursor_for:); end

      # Returns the correct nodes based on paginator#pagination
      def nodes; end

      # hasNextPage value based on the requested size and the actual (+1 present?)
      def next_page?; end

      #hasPrevPage: same as above
      def prev_page?; end

      # Only encodes what the lambda returns
      def cursor_for(item); end
    end
  end
end
```

**Comment by vecerek** [comment]
@rmosolgo bump ☝️

**Comment by aserafin** [comment]
@rmosolgo is there any way to access those values, for example in the context somewhere? I need to know the page size bc. I want to be able to show a page that contains some specific record (think slack when you search for sth and then click "view in channel" - you're taken to a "page" that contains this message and x previous messages and y next messages)
