### ISSUE TITLE
How to detect lazy fields during tracing to prevent double-tracing?

### ISSUE THREAD

**Issue by Envek** [rmosolgo/graphql-ruby#2828]
I'm writing yet another tracing adapter for graphql-ruby and counting number of times each field was requested (e.g. to estimate deprecated fields usage, search for slow resolvers, etc).

However, there is a problem with lazy fields (e.g. if using graphql-batch gem): there are two events for them are being fired: `execute_field` and `execute_field_lazy`

I want to count only `execute_field` for non-lazy fields and only `execute_field_lazy` for lazy ones as correct timings for lazy fields can be obtained only from “lazy” events.

**Question**: how to detect lazy fields from inside a tracer?

---

**Versions**

`graphql` version: 1.9 and 1.10 both interpreter and non-interpreter
`graphql-batch`: any (tested with 0.4.2)

**GraphQL schema**

<details>
<summary>Click to view schema</summary>

```ruby
require "graphql"
require "graphql/batch"

class PriceLoader < GraphQL::Batch::Loader
  def perform(ids)
    sleep 0.02
    ids.each { |id| fulfill(id, { currency: "USD", amount: 1.0 }) } # just hardcode
  end
end

class Price < GraphQL::Schema::Object
  field :currency, String, null: false, hash_key: :currency
  field :amount,   Float,  null: false, hash_key: :amount
end

class ProductType < GraphQL::Schema::Object
  field :id, ID, null: false
  field :title, String, null: true
  field :price, Price,  null: true

  def price
    PriceLoader.load(object.id)
  end
end

class Product < OpenStruct
  def title
    sleep 0.01
    super
  end
end

class QueryType < GraphQL::Schema::Object
  field :products, [ProductType], null: false

  def products
    [
      Product.new(id: 1, title: "Foo", price: { currency: "USD", amount: 1.0 }),
      Product.new(id: 2, title: "Foo", price: { currency: "RUB", amount: 75.0 }),
    ]
  end
end


class YabedaSchema < GraphQL::Schema
  query QueryType

  use GraphQL::Batch

  tracer GraphQL::Tracing::ActiveSupportNotificationsTracing
end
```

</details>

**Steps to reproduce**

1. Collect events with any tracer (e.g. using activesupport notifications):

    ```ruby
    ActiveSupport::Notifications.subscribe /execute_field.*\.graphql/ do |*args|
      event = ActiveSupport::Notifications::Event.new(*args)
      path = event.payload[:path] || event.payload[:context].path
      Rails.logger.debug "Event: #{event.name}, #{path.join('.')}, duration: #{event.duration.round} ms"
    end
    ```

2. Execute query using both lazy and non-lazy fields
    ```graphql
    query {
      products {
        id
        title
        price  { amount currency }
      }
    }
    ```

3. Watch for events:

    ```
    Event: execute_field.graphql, products, duration: 0 ms
    Event: execute_field.graphql, products.0.id, duration: 0 ms
    Event: execute_field.graphql, products.0.title, duration: 10 ms
    Event: execute_field.graphql, products.0.price, duration: 0 ms
    Event: execute_field.graphql, products.1.id, duration: 0 ms
    Event: execute_field.graphql, products.1.title, duration: 10 ms
    Event: execute_field.graphql, products.1.price, duration: 0 ms
    Event: execute_field_lazy.graphql, products.0.price, duration: 20 ms
    Event: execute_field.graphql, products.0.price.amount, duration: 0 ms
    Event: execute_field.graphql, products.0.price.currency, duration: 0 ms
    Event: execute_field_lazy.graphql, products.1.price, duration: 0 ms
    Event: execute_field.graphql, products.1.price.amount, duration: 0 ms
    Event: execute_field.graphql, products.1.price.currency, duration: 0 ms
    ```

    Non-lazy field:

    ```
    Event: execute_field.graphql, products.0.title, duration: 10 ms
    ```

    Lazy field:

    ```
    Event: execute_field.graphql, products.0.price, duration: 0 ms
    Event: execute_field_lazy.graphql, products.0.price, duration: 20 ms
    ```

**Additional context**

For non-interpreter mode I can detect field laziness in following way (not sure whether it is correct):

```ruby
field = event.payload[:field] || event.payload[:context].field
lazy_field = field.lazy_resolve_proc != ::GraphQL::Field::DefaultLazyResolve
```

However, I can't figure any way for interpreter mode.

Can you please recommend anything?

**Comment by rmosolgo** [comment]
Hi, great question. My approach is: 

- Assume that every field will have _both_ an eager component _and_ a lazy component. (This is not _true_, but the assumption simplifies the implementation) 
- After execution, merge results using `path`. For example, sum the observed duration values. 

For eager-only fields, the merge is a no-op; there's no lazy component to merge. For eager-and-lazy fields, observations are merged by `path`.

In your example above, `products.0.price` would require a merge -- merging the eager and lazy observations into a single one. 

Would that work in your case?

**Comment by Envek** [comment]
On initial problem @DmitryTsepelev found solution for me:

Ask schema whether that field was resolved lazily:

```ruby
class MyCustomTracer
  def self.trace(key, data)
    result = yield
    if ["execute_field", "execute_field_lazy"].include?(key)
      if data[:query].schema.lazy?(result)
        puts "#{data[:path].join('.')} was computed lazily"
      end
    end
    result
  end
end
```
Is it good by any means?

**Comment by Envek** [comment]
> After execution, merge results using `path`

Yeah, I already have thought about it. I think it should work.

But **when is “after execution”?** At which step I can merge the results and push them into monitoring? Is `execute_multiplex` tracing event is good for this?

Another question is **where to store the intermediate results before merging?** Is something like `query.context.namespace(MyCoolTracer)[:field_runtime_cache]` is good (I think I need something that will last until request end and will be garbage collected then)

**Comment by swalkinshaw** [comment]
You could take a look at https://github.com/Shopify/graphql-metrics for an example of this (hopefully correctly).

**Comment by rmosolgo** [comment]
> Ask schema whether that field was resolved lazily: ... Is it good by any means?

Yes, it will work, but I think you could do it even more simply: 

```ruby 
class MyCustomTracer
  def self.trace(key, data)
    result = yield
    if key == "execute_field_lazy"
      puts "#{data[:path].join('.')} was computed lazily"
    end 
    result
  end
end
```

(It works differently than your example above, though -- your example will detect lazy values returned from field resolvers. Mine will only detect lazy resolves _after_ they happen. So yours might be better if you need to detect it earlier. You can see that the runtime uses the same approach: 

https://github.com/rmosolgo/graphql-ruby/blob/4d4fdb948221cd7d21a3f9ed333a06d5a17343ff/lib/graphql/execution/interpreter/runtime.rb#L403
)

> But when is “after execution”? ... Is `execute_multiplex` tracing event is good for this?

Yes!

>  Where to store the intermediate results before merging? Is something like this is good... 

Yes! That's exactly what `context.namespace(...)` is for 😎  

Sorry for the late reply here. Anyways, it looks like you've got it figured out!
