### ISSUE TITLE
Document how validations work

### ISSUE THREAD

**Issue by gucki** [rmosolgo/graphql-ruby#283]
I have a very basic update mutation like this and wonder how to perform custom field validations:

      GraphQL::Relay::Mutation.define do
        name "UpdateBrand"

        input_field :id, !types.ID
        input_field :name, !types.String

        return_field :brand, BrandType

        resolve do |inputs, ctx|
          brand = NodeIdentification.object_from_id(inputs[:id], ctx)
          if inputs[:name] == "test"
            result = GraphQL::Query::InputValidationResult.new
            result.add_problem("Name must not be test")
            next result
          end
          brand.update_attributes!(name: inputs[:name])
          {brand: brand}
        end
      end

As you can see I tried returning an instance of `GraphQL::Query::InputValidationResult` but this causes an exception:

    NoMethodError - undefined method `key?' for #<GraphQL::Query::InputValidationResult:0x007fbac791fb20>:
      graphql (0.18.15) lib/graphql/relay/mutation.rb:136:in `method_missing'
      graphql (0.18.15) lib/graphql/field/resolve.rb:52:in `call'
      graphql (0.18.15) lib/graphql/field.rb:162:in `resolve'
      graphql (0.18.15) lib/graphql/query/serial_execution/field_resolution.rb:71:in `block in get_middleware_proc_from_field_resolve'
      graphql (0.18.15) lib/graphql/schema/middleware_chain.rb:24:in `call'
      graphql (0.18.15) lib/graphql/schema/rescue_middleware.rb:34:in `call'
      graphql (0.18.15) lib/graphql/schema/middleware_chain.rb:24:in `call'
      graphql (0.18.15) lib/graphql/query/serial_execution/field_resolution.rb:59:in `get_raw_value'
      graphql (0.18.15) lib/graphql/query/serial_execution/field_resolution.rb:19:in `result'
      graphql (0.18.15) lib/graphql/query/serial_execution/selection_resolution.rb:22:in `block in result'
      graphql (0.18.15) lib/graphql/query/serial_execution/selection_resolution.rb:15:in `result'
      graphql (0.18.15) lib/graphql/query/serial_execution/value_resolution.rb:82:in `non_null_result'
      graphql (0.18.15) lib/graphql/query/serial_execution/value_resolution.rb:23:in `result'
      graphql (0.18.15) lib/graphql/query/serial_execution/field_resolution.rb:44:in `get_finished_value'
      graphql (0.18.15) lib/graphql/query/serial_execution/field_resolution.rb:20:in `result'
      graphql (0.18.15) lib/graphql/query/serial_execution/selection_resolution.rb:22:in `block in result'
      graphql (0.18.15) lib/graphql/query/serial_execution/selection_resolution.rb:15:in `result'
      graphql (0.18.15) lib/graphql/query/serial_execution/operation_resolution.rb:19:in `result'
      graphql (0.18.15) lib/graphql/query/serial_execution.rb:25:in `execute'
      graphql (0.18.15) lib/graphql/query/executor.rb:33:in `execute'
      graphql (0.18.15) lib/graphql/query/executor.rb:15:in `result'
      graphql (0.18.15) lib/graphql/query.rb:82:in `result'
      graphql (0.18.15) lib/graphql/schema.rb:132:in `execute'
      app/controllers/graph_ql_controller.rb:7:in `execute'

I wonder how to do it correctly? It'd be great to have this documented in the wiki somewhere, including how to access the generated errors in relay.

**Comment by rmosolgo** [comment]
At this point, you have basically two options: 

- A resolve function may return a `GraphQL::ExecutionError`, whose message will be added to the response's `"errors"` key. (Or, if you must, you can also `raise` this error!)
- You can handle errors at the GraphQL level, for example, putting an `errors` field on the Mutation's return type, and including `{ errors: [...] }` in the mutation's return value. In that case, they'll appear in the `"data"` key, not the `"errors"` key. 

`GraphQL::Query::InputValidationResult` is not meant for public use, but you could use `GraphQL::ExecutionError` in the example above!

**Comment by gucki** [comment]
Thank you for your reply! 

    class ValidationError < GraphQL::ExecutionError
      attr_reader :model

      def initialize(model)
        @model = model
      end

      def to_h
        model.errors.to_hash
      end
    end

Raising an instance of this inside the resolve method works perfectly. In the `onFailure` callback of relay I can then access the errors with `transaction.getError().source.errors[0]`.

I also tried adding `return_field :errors, types[types.String]` to my mutation and added it to the fragment in `getFatQuery`but somehow it never got replied to the client. Not sure what I did wrong, but the other approach works and looks cleaner to me anyway *g*

BTW: Why always wrap the errors inside an array - is it needed by the graphql spec? (executor.rb:18)

**Comment by rmosolgo** [comment]
Yes, from http://facebook.github.io/graphql/#sec-Errors

> The `error`s entry in the response is a non‐empty list of errors, where each error is a map.

**Comment by rmosolgo** [comment]
I hope those answers were helpful for you!

**Comment by ianks** [comment]
tuyere yes esteemed tell you we e a good E the firsteE the E we err E we have E e ew the e ew the e ew ewwwwwww E e ere the errr ere ew ewwwwwww E the E the E the E the E the E we have a
