### ISSUE TITLE
Calling methods on lazy-initialized fields

### ISSUE THREAD

**Issue by StandardGiraffe** [rmosolgo/graphql-ruby#2830]
Hi ho.  I'm having difficulty implementing your `ArbitraryModelType.connection_type` method, as described [here](https://graphql-ruby.org/relay/connections.html#connection-fields), on fields that I need to declare as strings to manage inheritence and dependency, as you mentioned [here](https://github.com/rmosolgo/graphql-ruby/issues/1929#issuecomment-434037910).  The stringified approach was tremendously helpful, but when I try `"ArbitraryModelType".connection_type`, naturally my string doesn't know what to do.

Elsewhere, where I wasn't bumping into dependency issues but wanted to programmatically build common sets of fields, I tried to pre-constantize the stringified type (see below), but calling `connection_type` on a variable containing it fails (see below).

I've pasted my failing field-stamper method below.  Sorry for this mess, and thank you for your patience, again.

```
# Model names that pluralize with an 'es' instead of an 's'
MODEL_PLURALIZATION_EXCEPTIONS = Set.new([
  Address,
  Batch
])

def self.standard_queries_for(model, input_object: :identifiers)
  type, connection_resolver, node_resolver =
    if MODEL_PLURALIZATION_EXCEPTIONS.include?(model)
      [
        "Pistachio::Models::#{model}es::#{model}Type".constantize,
        "Pistachio::Models::#{model}es::#{model}esQuery".constantize,
        "Pistachio::Models::#{model}es::#{model}Query".constantize,
      ]
    else
      [
        "Pistachio::Models::#{model}s::#{model}Type".constantize,
        "Pistachio::Models::#{model}s::#{model}sQuery".constantize,
        "Pistachio::Models::#{model}s::#{model}Query".constantize,
      ]
    end

  field model.table_name.to_sym, type.connection_type, resolver: connection_resolver

  field model.to_s.underscore.to_sym, type, resolver: node_resolver do
    case input_object
    when :identifiers
      argument :identifiers, Pistachio::Inputs::IdentifiersAttributes, required: true
    when :common_identifiers
      argument :identifiers, Pistachio::Inputs::CommonIdentifiersAttributes, required: true
    end
  end
end
```

**Versions**

`graphql` version: `graphql (1.10.2, 1.10.0)`, `graphql-pro (1.13.0, 1.12.2)`
`rails` (or other framework): `rails (6.0.2.1)`

**Steps to reproduce**

Calling the node version of the field stamped out with `standard_queries_for(List)` ---the single `list` query---works precisely as if I'd done it longhand, which is the desired behaviour.  When I try to call the `lists` query, though, it explodes:

**Actual behavior**

```
No connection implementation to wrap Class (List)
/home/danny/.rvm/gems/ruby-2.7.0/gems/graphql-1.10.2/lib/graphql/relay/base_connection.rb:40:in `connection_for_nodes'
/home/danny/.rvm/gems/ruby-2.7.0/gems/graphql-1.10.2/lib/graphql/schema/field/connection_extension.rb:46:in `after_resolve'
/home/danny/.rvm/gems/ruby-2.7.0/gems/graphql-1.10.2/lib/graphql/schema/field.rb:708:in `block (2 levels) in with_extensions'
```

Thanks again!

**Comment by rmosolgo** [comment]
This error: 

> No connection implementation to wrap Class (List)

Suggests to me that `Pistachio::Models::Lists::ListsQuery` is returning `List`, the Ruby class. GraphQL-Ruby is trying to wrap that object (the class) in a connection, but it doesn't know how to -- probably because it's a mistake. Could you share the source of `Lists::ListQuery`?

**Comment by StandardGiraffe** [comment]
Well, yep.  That was the trouble---I'd been trying to scope based on privilege level, and had returned `List` rather than `List.all` for the highest privilege-level.  I feel a proper fool.  (Thanks!)
