### ISSUE TITLE
Auto-loading field arguments doesn't resolve lazy values

### ISSUE THREAD

**Issue by lucthev** [rmosolgo/graphql-ruby#2832]
**Describe the bug**

If `object_from_id` returns a lazy value, using `loads` in a field argument definition will result in an instance of `GraphQL::Execution::Lazy` being passed to the resolver method instead of the lazily-loaded object.

**Versions**

`graphql` version: master

**Steps to reproduce**

I modified an existing test case to demonstrate the issue:  https://github.com/rmosolgo/graphql-ruby/compare/master...lucthev:lt/lazy-autoloading

Using those changes, [this spec](https://github.com/lucthev/graphql-ruby/blob/15e49a95bb92e07fcffcd6ebde389d6550a0c7e5/spec/graphql/schema/argument_spec.rb#L208) fails with the following error:

```
Failure:
GraphQL::Schema::Argument::loads#test_0001_loads input object arguments [graphql-ruby/spec/graphql/schema/argument_spec.rb:215]
Minitest::Assertion: --- expected
+++ actual
@@ -1 +1 @@
-"{:instrument=>#<struct Jazz::Models::Instrument name=\"Drum Kit\", family=\"PERCUSSION\">, :required_with_default_arg=>1}"
+"{:instrument=>#<GraphQL::Execution::Lazy:0xXXXXXX @get_value_func=#<Proc:0xXXXXXX@graphql-ruby/lib/graphql/schema.rb:1883>, @resolved=false, @path=nil, @field=nil>, :required_with_default_arg=>1}"
```

**Expected behavior**

The `instrument` argument to the resolver method should be an instance of `Jazz::Models::Instrument`

**Actual behavior**

The `instrument` argument to the resolver method is an instance of `GraphQL::Execution::Lazy` wrapping the `Jazz::Models::Instrument`.

---

Is this indeed a bug, or is it expected behaviour? I'd be happy to attempt a fix, although I'm not quite sure where to start — any pointers?

**Comment by rmosolgo** [comment]
Yes, this is a bug! It's the same as #2671 . Honestly, I think the fix will require a pretty big change to how input objects are initialized :( That code isn't prepared for lazy values, if I remember correctly. Thanks for sharing the steps to add a failing test case -- I'm going to take a look!
