### ISSUE TITLE
Type's fields not reloaded on unicorn app restart (production)

### ISSUE THREAD

**Issue by Ex-Ark** [rmosolgo/graphql-ruby#2856]
**Describe the bug**

When deploying to production and gracefully restarting the app (unicorn server), everything gets reloaded  (no downtime), except the type's fields.
New types and new mutations do show up with the same setup and deploy, so this only concerns the type's field so far. 

**Versions**

`graphql` version: 1.10.5
`rails` (or other framework): 6.0.2.1

**GraphQL schema**
```ruby
class Types::PromotionType < Types::BaseObject
    field :hello, String, null: false
    # field :hi, String, null: false

    def hello
      "world"
    end

    # def hi
    #  "yo"
    # end
end

class ApplicationSchema < GraphQL::Schema
  max_depth 13
  query(Types::QueryType)
  mutation(Types::MutationType)
  use GraphQL::Execution::Interpreter
  use GraphQL::Pagination::Connections
  use GraphQL::Analysis::AST
end

class Types::QueryType < BaseObject
 field :all_promotions, resolver: Resolvers::PromotionsSearch
end

class Resolvers::PromotionsSearch < Resolvers::Base
  scope { Promotion.all }

  type types[Types::PromotionType]
end
```

**GraphQL query**

```graphql
query {
  allPromotions {
    hello
    hi
  }
}
```

```json
{
  "errors": [
    {
      "message": "Field 'hi' doesn't exist on type 'Promotion'",
      "locations": [
        {
          "line": 19,
          "column": 5
        }
      ],
      "path": [
        "query mutation_mutation_up559",
        "allPromotions",
        "hi"
      ],
      "extensions": {
        "code": "undefinedField",
        "typeName": "Promotion",
        "fieldName": "hi"
      }
    }
  ]
}
```

**Steps to reproduce**

- Modify a type's definition (i.e: add a field)
- Deploy ( `git commit` , `git push` , `cap production deploy`
- Request the newly created field

**Expected behavior**

The field's types should be updated like the rest of the classes (mutations, queries)

**Actual behavior**
Type's fields are likely not reloaded

**Additional context**
I tried many ruby tricks like manually unloading `PromotionType ` and loading the file again , problems are : 
- it doesn't work with ActiveSupport::Reloader because I'm in production env and cache_classes is true (RunTimeError is raised)
- in my dummy example I have only one type to reload, what if all my types have changed ?
- the only success I had so far is to set `cache_classes` to `false` in `production.rb` ! this is not a viable solution as it had 400ms to every request - the time it takes to reload all my app - !
- GraphQL raises error because it see two query objects (even if I unset `:@query_object`) if I try to it manually

```ruby
class ApplicationSchema < GraphQL::Schema
 def self.reload!
    @graphql_definition = nil
    remove_instance_variable(:@query_object)
    Types.send(:remove_const, :QueryType) if defined?(Types::QueryType)
    Types.send(:remove_const, :PromotionType) if defined?(Types::PromotionType)

    load "#{Rails.root}/app/graphql/types/promotion_type.rb"
    load "#{Rails.root}/app/graphql/types/query_type.rb"

    query(Types::QueryType)

    graphql_definition
  end
end
```

What can I do, if this is intended behaviour, to force reload type's fields on app gracefully restart ?

**Comment by rmosolgo** [comment]
Wow, so it sounds like you're using Rails constant reloading in _production_, is that right? (I've never heard of that! I've always heard of using it in development. Instead, I'm used to production deploys that spin up new Ruby processes and direct new traffic to those processes, shutting down the old ones when their traffic is finished.)

When you modify that type in _developement_, then query for new fields, does it work properly?

**Comment by Ex-Ark** [comment]
> Rails constant reloading in production

No that's what I want to avoid :)

Unicorn has one master process and two workers process, each one loading the app on start and then nothing is reloaded (preload_app + cache_classes rails).

My update deployment process is as you specify : the master fork itself and the sub workers, and then it kills itself when the app changes have been loaded in the new workers.
It requires indeed an nginx to do the load balancing between the old workers and the new workers.

The thing is : 
when I do my auto deploy (unicorn soft restart), everything get's reloaded in the new workers, it's good for mutations, routes, except graphql type fields :(

I have to manually ssh to my production server, shut down completely all my workers, and start them again, just so that the graphql field definition is reloaded. Thus shutting down completely my production for a few seconds and destroying the sole purpose of zero downtime deploy

Do you have any hints about what's special in type definition, (perhaps schema definition?) that could make unicorn not be able to reload theses changes specifically ?

**Comment by rmosolgo** [comment]
I'm sorry, I really don't have a clue ... Looking over the sample code above, the only thing that stood out is, maybe `Types::` would help:

```diff 
- class Types::QueryType < BaseObject
+ class Types::QueryType < Types::BaseObject
```

But, I can't _think_ of any reason why _some_ GraphQL files would behave differently than _other ones_, and I've never heard of this issue before 😖  

Sorry I can't be more help, please do let me know if you discover the source of the problem!
