### ISSUE TITLE
Node.resolve_type is deprecated

### ISSUE THREAD

**Issue by cberkom** [rmosolgo/graphql-ruby#286]
I've been able to fix most of the deprecation warnings related to `resolve_type` by defining it on the Schema, [as described here](https://github.com/rmosolgo/graphql-ruby/blob/f14f76167c32926c8b6d199d5d9b62736c79869f/CHANGELOG.md#0185-27-aug-2016), but one warning still appears in the logs:

```
Node.resolve_type is deprecated; define Schema.resolve_type instead
```

We're not using `resolve_type` anywhere else in the app; cause for concern?

**Comment by rmosolgo** [comment]
Have you switched from `GlobalNodeIdentification.type_from_object` to `Schema.resolve_type`? 

If not, `GlobalNodeIdentification` is falling back to a `resolve_type` hook in its generated interface: https://github.com/rmosolgo/graphql-ruby/blob/f14f76167c32926c8b6d199d5d9b62736c79869f/lib/graphql/relay/global_node_identification.rb#L35-L49

It's _intended_ to skip that if you have `resolve_type` in your schema definition! Does it work for you to update that?

**Comment by cberkom** [comment]
Well, our current setup is:

```ruby
  RelaySchema = GraphQL::Schema.define do
    query QueryType
    mutation MutationType
    resolve_type -> (obj, ctx) { (obj.class.name + 'Type').constantize }
  end
  
  RelaySchema.node_identification = NodeIdentification

  ...

  NodeIdentification = GraphQL::Relay::GlobalNodeIdentification.define do
    # Given a UUID & the query context,
    # return the corresponding application object
    object_from_id -> (id, ctx) do
      type, id = NodeIdentification.from_global_id(id)
      "API::#{type}".constantize.find(id)
    end

    # Given an application object,
    # return a GraphQL ObjectType to expose that object
    type_from_object -> (object) do
      (object.class.name + 'Type').constantize
    end
  end
```

If I comment out `type_from_object` from `NodeIdentification`, the deprecation warning still appears, so I must be missing something.

**Comment by rmosolgo** [comment]
> comment out `type_from_object`

That's what I was going to suggest! Huh, I wonder why we didn't get that deprecation in the test suite. 

I'm about to cut 0.19.0 which removes `GlobalNodeIdentification` altogether, so I think if you use `Schema.resolve_type` instead of `type_from_object`, that's the best we can do!

**Comment by rmosolgo** [comment]
This hook is gone, gone, gone, I hope your migration went (or, goes) smoothly! Sorry about the hang-up in deprecation :S
