### ISSUE TITLE
to_global_id field to all subclasses

### ISSUE THREAD

**Issue by msroot** [rmosolgo/graphql-ruby#2865]
I would like to implement `global_id_field` to all types subclasses but when i add it to `Types::BaseObject` i can see it as a query `gid` and `id`

```ruby 
module Types
  class BaseObject < GraphQL::Schema::Object
    field_class Types::BaseField
   
    implements GraphQL::Types::Relay::Node
    global_id_field :gid
    field :gid, ID, null: false, method: :to_gid
  end
end
```

I try also with an Interface:
```ruby 
module Types
  class BaseObject < GraphQL::Schema::Object
    field_class Types::BaseField
    
    include Types::BaseInterface
    to_global_id    
  end
end



module Types
  module BaseInterface
    include GraphQL::Schema::Interface

    field_class Types::BaseField
    
    definition_methods do
      def to_global_id
        implements GraphQL::Types::Relay::Node
        global_id_field :gid
        field :gid, ID, null: false, method: :to_gid
      end
    end
    
  end
end

```
I get an error: 

```
Attach interfaces using `implements(Types::BaseInterface)`, not `include(Types::BaseInterface)`
```

Is there a better way to add methods to `BaseObject` for subclasses?

**Comment by rmosolgo** [comment]
`BaseObject` is the right place to add a method for all subclasses. 

What's wrong with the first example you posted? It seems like it should add two fields, `id` (added by the `global_id_field` helper) and `gid` (added by `field :gid, ...`). Did you want it to do something else?

**Comment by msroot** [comment]
Hi @rmosolgo and thanks for the reply

The problem is that it shows in in the Documentation `Query`

```ruby
currentUser: User
-> gid: ID!
-> id: ID!
node(id: ID!): Node
nodes(ids: [ID!]!): [Node]!
retailer(id: ID!): Retailer
```

So i have to hide it? I mean `currentUser, retailer node and nodes` are a query but `id` and `gid` its not

**Comment by msroot** [comment]
Ok i can use `orphan_types` if i wanna hide it! Thank you anyway
