### ISSUE TITLE
MySchema.subscriptions.trigger does nothing.

### ISSUE THREAD

**Issue by bdsimmons** [rmosolgo/graphql-ruby#2867]
**Describe the bug**

I have followed the documentation closely (i am sure i am missing something simple). Everything is working perfectly except the `subscriptions.trigger` method seems to do nothing. While debugging, I noticed that if I use `stream_from "graphql_channel"` in the subscribed method of the graphql_channel and I call `ActionCable.server.broadcast('graphql_channel', 'test')` from the rails console, then I see that the cable is connected and the client receives the message, but if i call `TableneedsApiSchema.subscriptions.trigger(:request_was_posted, {table_id: 1}, table.requests)` then i get the following output `[ActionCable] Broadcasting to graphql-event::requestWasPosted:tableId:1: "\"#<Request::ActiveRecord_Associations_CollectionProxy:0x00007fcf7ddaf1c0>\""` but nothing happens at all in the client. If i hard code the same stream name that trigger built out and use it as stream_from then i receive the data, but in a string format and ActionCableLink does not parse it correctly just like this [issue](https://github.com/rmosolgo/graphql-ruby/issues/2499).

Another thing to note. If i use stream_from I see channels available in Redis, but `Redis.new.pubsub('channels')` returns an empty array if i leave this out. All the examples I find tell me nothing about using stream_from and so I am assuming that I am doing something wrong. Below is my GraphQL Channel.

```ruby
class GraphqlChannel < ApplicationCable::Channel
  def subscribed
    @subscription_ids = []
  end

  def execute(data)
    query = data["query"]
    variables = ensure_hash(data["variables"])
    operation_name = data["operationName"]
    context = {
      # Re-implement whatever context methods you need
      # in this channel or ApplicationCable::Channel
      # current_user: current_user,
      # Make sure the channel is in the context
      channel: self,
    }

    result = TableneedsApiSchema.execute({
      query: query,
      context: context,
      variables: variables,
      operation_name: operation_name
    })

    payload = {
      result: result.to_h,
      more: result.subscription?,
    }

    # Track the subscription here so we can remove it
    # on unsubscribe.
    if result.context[:subscription_id]
      @subscription_ids << result.context[:subscription_id]
    end

    transmit(payload)
  end

  def unsubscribed
    @subscription_ids.each { |sid|
      TableneedsApiSchema.subscriptions.delete_subscription(sid)
    }
  end

  private

    def ensure_hash(ambiguous_param)
      case ambiguous_param
      when String
        if ambiguous_param.present?
          ensure_hash(JSON.parse(ambiguous_param))
        else
          {}
        end
      when Hash, ActionController::Parameters
        ambiguous_param
      when nil
        {}
      else
        raise ArgumentError, "Unexpected parameter: #{ambiguous_param}"
      end
    end
end
```

**Versions**

`graphql` version: graphql (1.10.4)
`rails` (or other framework): rails (~> 5.2.3)
other applicable versions (`graphql-batch`, etc)

**GraphQL schema**

Schema
```ruby
class TableneedsApiSchema < GraphQL::Schema
  use GraphQL::Subscriptions::ActionCableSubscriptions, redis: Redis.new
  mutation(Types::MutationType)
  query(Types::QueryType)
  subscription(Types::SubscriptionType)

  # Opt in to the new runtime (default in future graphql-ruby versions)
  use GraphQL::Execution::Interpreter
  use GraphQL::Analysis::AST

  # Add built-in connections for pagination
  use GraphQL::Pagination::Connections

  def self.id_from_object(object, type, context)
    object.to_global_id.to_s
  end

  def self.object_from_id(unique_id, context)
    GlobalID::Locator.locate(unique_id)
  end
end
```

Subscription Types
```ruby
module Types
  class SubscriptionType < Types::BaseObject
    field :request_was_posted, subscription: Subscriptions::RequestWasPosted
  end
end
```

Subscription Type Class
```ruby
class Subscriptions::RequestWasPosted < Subscriptions::BaseSubscription
  argument :table_id, ID, required: true
  field :requests, [Types::RequestType], null: true

  def subscribe(table_id:)
    puts "SUBSCRIBE"
    table = Table.find(table_id)
    {
      requests: table.requests
    }
  end

  def update(table_id:)
    puts "UPDATE"
    table = Table.find(table_id)
    {
      requests: table.requests
    }
  end

end
```

Base Subscription Class
```ruby
class Subscriptions::BaseSubscription < GraphQL::Schema::Subscription
  # Hook up base classes
  object_class Types::BaseObject
  field_class Types::BaseField
  argument_class Types::BaseArgument
end
```

**GraphQL query**

```graphql
  subscription RequestWasPosted($tableId:ID!) {
    requestWasPosted(tableId: $tableId) {
      requests {
        name
        uid
        tableId
      }
    }
  }
```

```json
{
  "data": {
    "requestWasPosted": {
      "requests": [
        {
          "name": "Request Name",
          "uid": "user_id",
          "tableId": "1"
        }
      ]
    }
  }
}
```

We are using Rails as an API to connect to an Ionic/React SPA on the frontend and the React connection code looks like this:

```typescript
import { ApolloClient } from 'apollo-client';
import { InMemoryCache } from 'apollo-cache-inmemory';
import { HttpLink } from 'apollo-link-http';
import { ApolloLink } from 'apollo-link';
import { ApolloProvider } from '@apollo/react-hooks';
import ActionCable from 'actioncable';
import { ActionCableLink } from 'graphql-ruby-client';

const cache = new InMemoryCache();
const uri = 'http://localhost:3000/graphql';

interface IHasSubscriptionOperationType {
  query: {
    definitions: any
  }
}

const hasSubscriptionOperation = ({ query: { definitions } }: IHasSubscriptionOperationType) => {
  return definitions.some(
    ({ kind, operation }: {kind: any, operation: any}) => kind === 'OperationDefinition' && operation === 'subscription',
  )
}

const httpLink = new HttpLink({
  uri: uri
});

const cable = ActionCable.createConsumer(`ws://localhost:3000/cable`);

const link = ApolloLink.split(
  hasSubscriptionOperation,
  new ActionCableLink({cable}),
  httpLink
);
const client = new ApolloClient({
  link,
  cache,
});

ReactDOM.render(
  <ApolloProvider client={client}>
    <App />
  </ApolloProvider>,
  document.getElementById('root')
);

```

**Steps to reproduce**

Run a web application with this subscription query and it connects properly. I see the subscription, and the server confirming the subscription and the initial response, but nothing I do from the server with trigger does anything on the client.

**Expected behavior**

Calling `TableneedsApiSchema.subscriptions.trigger(:request_was_posted, {table_id: table.id}, table.requests)` on the API side would trigger a WS connection to the connected client.

**Actual behavior**

No triggers called seem to have any connected clients.

**Comment by rmosolgo** [comment]
Try adding this to your root subscription type: 

```ruby
extend GraphQL::Subscriptions::SubscriptionRoot
```

It's required in the new interpreter runtime (https://graphql-ruby.org/queries/interpreter.html#installation). Does that help? 

I'm hoping to remove the need for that in the next version!

**Comment by rmosolgo** [comment]
(That solution worked in https://github.com/rmosolgo/graphql-ruby/issues/2727#issuecomment-584870542, but other solutions described there might help, too)

**Comment by bdsimmons** [comment]
That was indeed it @rmosolgo. Thanks!

I did not see that anywhere in the docs, but I probably missed it!

THANKS!

**Comment by rmosolgo** [comment]
Glad to hear it! I've added a more clear call-out in the docs. Hopefully it won't be necessary after landing #2770
