### ISSUE TITLE
Null values are filtered out from my input array

### ISSUE THREAD

**Issue by JakeDluhy** [rmosolgo/graphql-ruby#2868]
**Describe the bug**

I have a query that accepts variable arguments. One of my arguments is an array of strings that can also accept null values. However when I send a null value in that array it gets filtered out by the time I try to access arguments.

**Versions**

`graphql` version: `1.9.14`
`rails` (or other framework): `5.2.0`
other applicable versions (`graphql-batch`, etc)
`graphql-batch`: `0.3.10`

**GraphQL schema**

```rb
# (Partial) Filter input definition
class Types::SoliReportFiltersInput < Types::BaseInputObject
  argument :shipped_from_country, [String, null: true], required: false
  argument :salesperson_name, [String, null: true], required: false
end

# Field definition in query.rb
field :soli_report_filters, Types::SoliReportFilter, null: true do
    argument :filters, Types::SoliReportFiltersInput, required: false

    extension(Extensions::AuthenticatedNodeExtension)
    extension(Extensions::CompanyNodeExtension)
end
```

**GraphQL query**

Here's an example of a JS inspection of the query I'm sending
<img width="822" alt="Screen Shot 2020-04-08 at 4 12 17 PM" src="https://user-images.githubusercontent.com/6790323/78842051-d5206b80-79b3-11ea-9565-c25e83961115.png">

But by the time it gets to the rails console logging this is what it looks like:
```ruby
"cvFilters"=>{
  "key"=>"last_365_days",
  "startDate"=>"2019-04-09T22:57:17.686Z",
  "endDate"=>"2020-04-08T22:57:17.686Z",
  "shippedFromCountry"=>[]
}
```

**Steps to reproduce**

Define a field as I demonstrate above, sending an array with null values, and log the resulting filter value

**Expected behavior**

I would expect that I would be able to access an array through `args[:filters][:shipped_from_country] == [nil]`

**Actual behavior**

This is the result that I get: `args[:filters][:shipped_from_country] == []`

**Additional context**

I'm using Apollo on the frontend, but as you can see from the network inspection it appears that the variable is being sent correctly from the frontend.

**Comment by rmosolgo** [comment]
It sounds like Rails is modifying the input value in `params`, is that right? 

If so, check the discussion and work-arounds here: https://github.com/rmosolgo/graphql-ruby/issues/1770#issuecomment-601725677

Let me know if that works for you!

**Comment by JakeDluhy** [comment]
Yes this worked thanks so much!!!

**Comment by oleksandr-danylchenko** [comment]
> If so, check the discussion and work-arounds here: [#1770 (comment)](https://github.com/rmosolgo/graphql-ruby/issues/1770#issuecomment-601725677)

Thanks! Obtaining the `request.body.read` was exactly what I needed!
