### ISSUE TITLE
Regression in GraphQL 1.10: no way to get access to query args in their original form

### ISSUE THREAD

**Issue by myronmarston** [rmosolgo/graphql-ruby#2869]
**Describe the bug**

We've built an indexing and search framework on top of graphql-ruby that operates on GraphQL schemas generically, by translating a GraphQL query to an elastic search query to query our indexed data.  The framework is designed to work with either `camelCase` schemas or `snake_case` schemas (really, it doesn't care; as long as the user of the framework uses the same casing for a field in their GraphQL schema and their ElasticSearch JSON field schema, it'll "just work" without us having to think about it).  This all worked great with graphql-1.9, but I've been trying to upgrade to graphql-1.10 and I'm running into problems. Specifically, graphql-1.10 coerces all inputs to ruby keyword-style syntax (e.g. symbols keys instead of strings, `snake_case` over `camelCase`, etc).  This is causing us a problem because when we get a user of our framework is using a `camelCase` schema (as most GraphQL schemas are...) our framework is now receiving the field name in `snake_case` instead of `camelCase`, which causes the ElasticSearch query to fail to match anything.  I've spent a few hours trying to figure out an alternate way to get the original argument hash in whatever casing it started in, and I haven't found a way that works.

I can understand why most users probably prefer getting the query arguments in ruby keyword style syntax, but for those of us who want the argument hash as it was provided in the query, it's frustrating not to have access to it anymore, and I haven't yet found a work around I'm satisfied with.

Can the graphql gem provide access to the original args hash as it was provided in 1.9 using an alternate method or something?

**Versions**

`graphql` version: worked as desired in all 1.9.x versions, fails to work as I need it to in 1.10.x

**GraphQL schema**

See my example script below.

**GraphQL query**

See my example script below.

**Steps to reproduce**

Put this script in a file like `script/demo_args_coercion_issue.rb`:

``` ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'graphql', ENV.fetch('VERSION')
end

require 'graphql'
require 'pp'

schema_string = <<~SCHEMA
  input IdFilter {
    anyOf: [ID!]!
  }

  input IntFilter {
    anyOf: [Int!]
    gt: Int
    gte: Int
    lt: Int
    lte: Int
  }

  type Widget {
    id: ID!
    amountCents: Int!
    name: String!
  }

  input WidgetFilter {
    id: IdFilter
    amountCents: IntFilter
  }

  type Query {
    widgets(filter: WidgetFilter): [Widget!]!
  }
SCHEMA

schema = GraphQL::Schema.from_definition(schema_string, default_resolve: -> (parent_type, field, object, args, context) {
  puts "Got :filter arguments: #{args[:filter].to_h.inspect}"
  puts "Got 'filter' arguments: #{args["filter"].to_h.inspect}"
})

query = <<~QUERY
  query {
    widgets(filter: {amountCents: {gt: 100}}) {
      id
    }
  }
QUERY

schema.execute(query)
```

Then you can run it with `VERSION=1.9.19 ruby script/demo_args_coercion_issue.rb` and `VERSION=1.10.6 ruby script/demo_args_coercion_issue.rb` to compare the behavior.

**Expected behavior**

I expect to continue to get the args in the casing defined by my schema (camelCase, in this example case).

**Actual behavior**

graphql-1.10.x presents the field name from my query as `amount_cents` instead of `amountCents`.

**Additional context**

Example output from my script above:

```
$ VERSION=1.9.19 ruby script/demo_args_coercion_issue.rb
Got :filter arguments {"amountCents"=>{"gt"=>100}}
Got 'filter' arguments {"amountCents"=>{"gt"=>100}}
$ VERSION=1.10.6 ruby script/demo_args_coercion_issue.rb
Got :filter arguments: {:amount_cents=>{:gt=>100}}
Got 'filter' arguments: {}
```

As you can see, on 1.9.x, I could access the arguments with string or symbol keys, and it preserved the casing of `amountCents`; in 1.10.x, I can only access the arguments using symbol keys, and it converts `amountCents` to `amount_cents`, which breaks my logic with no clear work around since my framework doesn't know what the "original" casing of that element in the schema was.  (The symbol vs string access doesn't matter to me much compared to the casing issue).

**Comment by rmosolgo** [comment]
Thanks for the details on the issue here! Similar in a way to #2841 in that detailed argument metadata isn't available anymore, and I think the same fix would apply to both (namely, some way to access "unadulterated" argument names and values). 

Your example uses `Schema.from_definition` -- do you need a solution that support `.from_definition`, or is that just an example? (I ask because it's much harder to customize schemas built from definition :sweat_smile: .)

**Comment by myronmarston** [comment]
> Your example uses `Schema.from_definition` -- do you need a solution that support `.from_definition`, or is that just an example?

Our project _only_ uses `from_definition`, so I absolutely need this to work with `from_definition`.

> (I ask because it's much harder to customize schemas built from definition 😅 .)

What do you mean by "customize schemas"?  FWIW we use lots of custom directives to configure how our framework treats the schema...

**Comment by rmosolgo** [comment]
> lots of custom directives to configure how our framework treats the schema

That's awesome 🍻 😁 . I'm glad you found something that works. 

I started looking into the larger issue, and realized that this problem is a little different. Since you're using `default_resolve: -> ...`, you can't use field extras and don't easily have access to the current AST node. 

So, I recommend making the transformation manually. I think something like this could build camel-case named hashes out of symbol hashes:

```ruby 
# Recursively transform a symbol-keyed hash of GraphQL arguments into a string-keyed, camelized hash.
def camelize_args(args_value, arg_owner) 
  case args_value 
  when Hash, GraphQL::Schema::InputObject
    arg_defns = arg_owner.arguments.values
    camelized_args = {} 
    args_value.each do |key, value| 
      arg_defn = arg_defns.find { |a| a.keyword == key }
      next_owner = arg_defn.type.unwrap
      camelized_args[arg_defn.name] = camelize_args(value, next_owner)
    end 
    camelized_args 
  when Array 
    args_value.map { |arg_value| camelize_args(arg_value, arg_owner) }
  else 
    args_value
  end 
end 
```

Then, I can update the example script above: 

```ruby 
schema = GraphQL::Schema.from_definition(schema_string, default_resolve: -> (parent_type, field, object, args, context) {
  arg_type = field.arguments["filter"].type.unwrap
  camelized_filter = camelize_args(args[:filter], arg_type)
  puts "Camelized filter: #{camelized_filter.inspect}"
})
```

And I get a camelized hash: 

```
$ VERSION=1.10.6 ruby test.rb
Camelized filter: {"amountCents"=>{"gt"=>100}}
```

Do you think something like that would work in this case?

**Comment by myronmarston** [comment]
I have a work around like that already in place, but it doesn't work in all cases.  The users of my framework aren't required to exclusively use `camelCase` names for everything and there times when it makes sense to insert an underscore to separate two separate parts of one field name, such as when you've denormalized a field from some parent object (e.g. `legalEntity_firstName` for the `firstName` field of the `legalEntity` being denormalized onto an `account` type).

Ideally I'd be able to get the query arguments in the casing defined in the schema (and passed in the query)...

**Comment by rmosolgo** [comment]
> casing defined in the schema

Sorry, I didn't clarify that well. I called my helper `camelize_`, but in fact, it uses `arg_defn.name`, which will be the name _as configured_ in the schema. 

For example, if we get wild with the example above:

```diff 
-     amountCents: IntFilter
+     widgetAmount_AmountInCents: IntFilter
```

The method above will use the irregularly-cased name: 

```
$ VERSION=1.10.6 ruby test.rb
Camelized filter: {"widgetAmount_AmountInCents"=>{"gt"=>100}}
```

(Maybe a better name for the helper is "argument_keywords_to_names" or something like that.)

**Comment by myronmarston** [comment]
Ah, I didn't read the code in detail to see that it uses the `arg_defn.name` to convert back to the original casing.  So yes, that should work!  Thanks for writing it up and tolerating my questions :).

Does the code you wrote use any non-public APIs (public in the SemVer sense not public in the ruby public vs private sense)?  Would it make sense for the graphql gem to expose a method I could delegate to to do the conversion?  

If you think it makes sense to provide a public API to do this conversion, I can contribute that if you'll recommend where it should go and what you'd like it to be called :).

**Comment by myronmarston** [comment]
I've implemented a solution like what @rmosolgo posted above in our codebase, and it's working well, so I'm going to close this issue.
