### ISSUE TITLE
GraphQL::Types::Relay::PageInfo doesn't follow relay spec for startCursor and EndCursor

### ISSUE THREAD

**Issue by Derenge** [rmosolgo/graphql-ruby#2872]
**Describe the bug**

The `PageInfo` fields `startCursor` and `endCursor` should be non-null according to the spec. 

https://relay.dev/graphql/connections.htm#sec-undefined.PageInfo.Fields

I'm willing to submit a PR if this is something we want to fix!

**Comment by rmosolgo** [comment]
Yes, that'd be great, thanks!

**Comment by rmosolgo** [comment]
See the discussion on #2886: I was mistaken in my above suggestion to make this change. 

In fact, Relay's _behavior_ differs from the spec. Relay expects `null` for `startCursor` and `endCursor` on empty collections. There's an open, unmerged PR to fix the spec. 

So, we'll keep GraphQL-Ruby's behavior matching Relay's, even though the spec is wrong.
