### ISSUE TITLE
Raise type-specific errors for better bug tracker integration

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#2889]
Currently, when some kinds of things go wrong in GraphQL-Ruby, errors are raised all the way up to the application. For example: 

- unexpected nil errors (when a field that shouldn't return `nil` _does_ return `nil`) 
- unresolved type errors (when a `.resolve_type` call returns an invalid type for a certain runtime context)

Some are _not_ raised all the way, but are still related to specific types: 

- unauthorized errors (when a `.authorized?` call fails)  

If these bubble all the way to the application, they might end up in a bug tracker. 

Some bug trackers group errors by _class_, and that means that `UnresolveTypeError`s all get grouped together, even if they came from _entirely_ different scenarios -- which is frustrating, because unrelated bugs get lumped into the same category. 

The solution is to make type-specific error classes. For example: 

```ruby
class Types::Node::UnresolvedTypeError < GraphQL::UnresolvedTypeError 
```

If we raised _that_ error instead of a top-level error, we'd get better groupings by default in bug trackers. We can make those subclasses automatically in library code, and raise them instead of top-level errors just fine. 

And, since they inherit from the top-level errors, `rescue` and `rescue_from` will still work just fine. Nice. 

(We already do this in GitHub for some errors, but we recently switched bug trackers which has exposed more cases where this could be improved.)

**Comment by Fadi25** [comment]
Hello,

Please find a failed test for example, which states the following:
 Failure/Error: MySchema.execute(query, context: { user: user }).as_json
     
     NoMethodError:
       undefined method `to_i' for Wed, 08 Jul 2020:Date
       Did you mean?  to_s

Is there a way to get a more specific error,
which points to the specific field or resolver that causes it, rather than the schema execute line? 

Thanks

**Comment by rmosolgo** [comment]
Hi @Fadi25 , could you please share the full stack trace that you got with that error? 

If it happened in  a resolver or field, then the stack trace would include that info.

**Comment by Fadi25** [comment]
Sure

# /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/types/int.rb:17:in `coerce_result'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/interpreter/runtime.rb:305:in `continue_field'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/interpreter/runtime.rb:238:in `block (4 levels) in evaluate_selections'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/interpreter/runtime.rb:457:in `after_lazy'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/interpreter/runtime.rb:232:in `block (3 levels) in evaluate_selections'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/interpreter/runtime.rb:382:in `resolve_with_directives'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/interpreter/runtime.rb:221:in `block (2 levels) in evaluate_selections'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/interpreter/runtime.rb:457:in `after_lazy'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/interpreter/runtime.rb:177:in `block in evaluate_selections'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/interpreter/runtime.rb:124:in `each'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/interpreter/runtime.rb:124:in `evaluate_selections'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/interpreter/runtime.rb:334:in `block in continue_field'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/interpreter/runtime.rb:457:in `after_lazy'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/interpreter/runtime.rb:329:in `continue_field'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/interpreter/runtime.rb:238:in `block (4 levels) in evaluate_selections'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/interpreter/runtime.rb:457:in `after_lazy'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/interpreter/runtime.rb:447:in `block in after_lazy'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/lazy.rb:41:in `value'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/interpreter/resolve.rb:37:in `resolve'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/interpreter/resolve.rb:11:in `resolve_all'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/interpreter.rb:94:in `block in sync_lazies'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/tracing.rb:82:in `call_tracers'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/tracing.rb:84:in `block in call_tracers'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/tracing/platform_tracing.rb:26:in `block in trace'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/tracing/data_dog_tracing.rb:37:in `block in platform_trace'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/ddtrace-0.31.1/lib/ddtrace/tracer.rb:270:in `trace'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/tracing/data_dog_tracing.rb:18:in `platform_trace'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/tracing/platform_tracing.rb:25:in `trace'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/tracing.rb:84:in `call_tracers'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/tracing.rb:68:in `trace'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/interpreter.rb:93:in `sync_lazies'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/interpreter.rb:51:in `finish_multiplex'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/multiplex.rb:88:in `run_as_multiplex'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/multiplex.rb:62:in `block (2 levels) in run_queries'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/multiplex.rb:196:in `block in instrument_and_analyze'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/multiplex.rb:175:in `instrument_and_analyze'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/multiplex.rb:61:in `block in run_queries'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/tracing.rb:82:in `call_tracers'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/tracing.rb:84:in `block in call_tracers'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/tracing/platform_tracing.rb:26:in `block in trace'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/tracing/data_dog_tracing.rb:37:in `block in platform_trace'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/ddtrace-0.31.1/lib/ddtrace/tracer.rb:270:in `trace'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/tracing/data_dog_tracing.rb:18:in `platform_trace'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/tracing/platform_tracing.rb:25:in `trace'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/tracing.rb:84:in `call_tracers'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/tracing.rb:68:in `trace'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/multiplex.rb:59:in `run_queries'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/execution/multiplex.rb:49:in `run_all'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/schema.rb:1633:in `multiplex'
     # /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/schema.rb:1604:in `execute'
     # ./spec/graphql/queries/restaurant_spec.rb:265:in `block (4 levels) in <module:Queries>'

line:265 is this MySchema.execute(query, context: { user: user }).as_json

**Comment by rmosolgo** [comment]
Great, so your error didn't happen in a field or a resolver. Look at the top line of the backtrace: 

>  /Users/fadi/.rvm/gems/ruby-2.5.5/gems/graphql-1.10.9/lib/graphql/types/int.rb:17:in `coerce_result'

`GraphQL::Types::Int` was trying to coerce a result: 

https://github.com/rmosolgo/graphql-ruby/blob/0ee20fa3eb35a2c69eed61333929431a2f246ec0/lib/graphql/types/int.rb#L17

But the value it received didn't respond to `.to_i`. (Looking at the error message from your first post, it received an instance of `Date`.) 

To fix this error, you should find the field or resolver that returned a `Date` instead of an integer, and update that field to return and integer.

**Comment by Fadi25** [comment]
@rmosolgo thanks so much for the response, you are absolutely right,

my question is how can I get  a deeper stack that would eventually point to, for example, this line:
field :start_date, GraphQL::Types::Int, null: true

or this

def start_date
some_date_time.to_date
end

otherwise, I'll need to go over all the candidate fields

**Comment by rmosolgo** [comment]
>  a deeper stack 

The problem is, `def start_date` is not in the stack anymore. The method was called, and it returned a value, so it's no longer part of the call stack. 

You might be able to use the current GraphQL path to debug, here's an example of accessing that info: 

https://github.com/rmosolgo/graphql-ruby/blob/79b8c0bb4b0a3a2f22db3d262bafe36756d4ae6e/spec/graphql/execution/interpreter_spec.rb#L106

But, it's not very well supported right now :S (and certainly not automatic!)

**Comment by rmosolgo** [comment]
Done in #2957
