### ISSUE TITLE
fragments shallowly merging causing dropped fields

### ISSUE THREAD

**Issue by charlieschwabacher** [rmosolgo/graphql-ruby#29]
I noticed an issue when using two fragments containing the same key, w/ others nested below.  It should be deep merging, but instead the last fragment replaces any earlier ones.  It ends up being an issue because Relay generates a lot of repetitive fragments.

this query:

```
{
  viewer {
    ...fragmentWithTwoFields
    ...fragmentWithOneField
  }
}

fragment fragmentWithTwoFields on User {
  todos {
    totalCount,
    completedCount,
  }
}

fragment fragmentWithOneField on User {
  todos {
    totalCount,
  }
}
```

produces:

```
{
  "data": {
    "viewer": {
      "todos": {
        "totalCount": 2
      }
    }
  }
}
```

when it should also include `completedCount`:

```
{
  "data": {
    "viewer": {
      "todos": {
        "totalCount": 2,
        "completedCount": 1
      }
    }
  }
}
```

Going to take a stab at fixing this tonight.

**Comment by rmosolgo** [comment]
wow! what a bummer. 

Maybe you found it already, but I think this is the faulty merge:

https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/query/serial_execution/selection_resolution.rb#L24

It `field_value` there is actually a hash. In the case of a field, it's `name => value`, but in the case of fragments (inline or fragment spread) it has many names and values. 

So, in the case of fragments with the same key, the first fragment is merged in, but then the second on overwrites that key! 

Seems like there's two approaches:
- Make that merge better -- make it handle this case 
- Flatten fields on the way in. Not really sure how this would work but it would also address the issue of selecting the _same_ field in 2 fragments, eg 

  ```
  { myField { ...frag1, ...frag2 } }
   fragment frag1 on Type { name }
   fragment frag2 on Type { name } 
  ```

  right now, graphql-ruby evaluates the name field twice :weary: !

**Comment by charlieschwabacher** [comment]
thanks! I was still kind of wrapping my head around parslet, so this was really helpful.  I think the second approach you mention is the right one, because deep merge falls apart when the values are arrays, i.e:

```
{
  viewer {
    ...fragmentWithTwoFields
    ...fragmentWithOneField
  }
}

fragment fragmentWithTwoFields on User {
  todos {
    edges {
      node {
        text,
        id
      }
    }
  }
}

fragment fragmentWithOneField on User {
  todos {
    edges {
      node {
        id
      }
    }
  }
```

I don't think I'll finish tonight, but will come back to this and try to find a way to merge the trees before resolving.

**Comment by rmosolgo** [comment]
ohh i see what you mean, yeah that merge would get out of hand fast!

**Comment by charlieschwabacher** [comment]
So i was thinking we could flatten selections once at the beginning of operation resolution, but I think it needs to happen later in order to handle union types where some fragments may not be included.

I was not thinking correctly about deep merge though - I thought there would be an issue w/ arrays because we would have to manually match up members, but I realize now that it is safe to just map deep_merge across members.

I'll pull w/ that now, and then when I have a chance I'll look a little deeper at how things are working and try to come up w/ a way to merge the ast nodes before resolving.

also just for reference, here is the query produced by the relay todos example: https://gist.github.com/charlieschwabacher/539c9d36f5db26134d04#file-gistfile1-txt-L118:L125
