### ISSUE TITLE
Is this a proper use of instrumentations?

### ISSUE THREAD

**Issue by rtymchyk** [rmosolgo/graphql-ruby#2903]
So I'm using the `graphql-batch` tool to alleviate some N+1 query problems. I don't like it directly because it gets repetitive in resolvers, so instead, I was hoping to extend the DSL in a way that lets me do something like:
```ruby
class Article < BaseObject
  field :topic, TopicType, null: false, record_loader: true
end

...

class CityType < BaseObject
  field :neighborhood, NeighborhoodType, null: true, record_loader: {
    column: :slug,
    load: ->(_obj, args, _ctx) { args[:slug]&.downcase },
  }
end
```

I've chosen to use instrumentation, alongside field metadata to achieve the above.

```ruby
# frozen_string_literal: true
class RecordLoader < GraphQL::Batch::Loader
  class Resolver
    attr_accessor :type, :field, :load_arg, :column_arg, :where_arg, :then_arg, :model_arg

    def initialize(type, field, config)
      @type  = type
      @field = field

      config = {} unless config.is_a?(Hash)
      @load_arg = config[:load]
      @column_arg = config[:column]
      @where_arg = config[:where]
      @then_arg = config[:then]
      @model_arg = config[:model]
    end

    def call(object, args, ctx)
      old_resolver = field.resolve_proc
      application_object = object.object

      model ||= model_arg.call(application_object, args, ctx) if model_arg&.respond_to?(:call)
      model ||= application_object.public_send(model_arg) if model_arg&.is_a?(Symbol)
      model ||= model_arg
      model ||= field.metadata[:type_class].instance_variable_get(:@return_type_expr).instance_variable_get(:@model_class)

      column ||= column_arg.call(application_object, args, ctx) if column_arg&.respond_to?(:call)
      column ||= column_arg if column_arg&.is_a?(Symbol)
      column ||= model.primary_key

      load_by ||= load_arg.call(application_object, args, ctx) if load_arg&.respond_to?(:call)
      load_by ||= application_object.public_send(load_arg) if load_arg&.is_a?(Symbol)
      return nil if load_arg && !load_by

      load_by ||= application_object.public_send("#{field.name.underscore}_id".to_sym)
      return nil unless load_by

      where = where_arg.call(application_object, args, ctx) if where_arg.respond_to?(:call)
      where ||= where_arg

      RecordLoader.for(model, column: column, where: where)
        .load(load_by)
        .then { |data| then_arg ? then_arg.call(data, object, args, ctx) : data }
    end
  end

  class Instrumentation
    def instrument(type, field)
      return field unless field.metadata[:record_loader]

      field.redefine do
        resolve(Resolver.new(type, field, field.metadata[:record_loader]))
      end
    end
  end

  # Rest in here is typical RecordLoader taken from https://github.com/Shopify/graphql-batch/blob/master/examples/record_loader.rb
end
```

My questions are:
1) Is this an appropriate use of instrumentation? Just want to future proof a bit.
2) This feels really bad to me:
`field.metadata[:type_class].instance_variable_get(:@return_type_expr).instance_variable_get(:@model_class)
`

We have another DSL extension that specifies the model on the type.
```ruby
class ArticleType < BaseObject
  model Article
end
```

```ruby
class BaseObject < GraphQL::Schema::Object
  def self.model(model_class)
    @model_class = model_class
  end
end
```

What I'm trying to do is infer the model from the type, is there a cleaner way to do that? In particular the `instance_variable_get(:@return_type_expr)` feels off.

**Comment by rmosolgo** [comment]
Yes, that's a fine use of instrumentation. However, field instrumentation isn't supported in the Interpreter runtime because it uses the legacy schema definition objects (which hog memory). The replacement is called field extensions: https://graphql-ruby.org/type_definitions/field_extensions.html


> `field.metadata[:type_class].instance_variable_get(:@return_type_expr).instance_variable_get(:@model_class)`

In recent graphql-ruby versions, you should be able to do 

```diff 
- field.metadata[:type_class]
+ field.type_class
```

And, why not use `Field#type` instead of `@return_type_expr`? 

```ruby 
- .instance_variable_get(:@return_type_expr)
+ .type.unwrap # `.unwrap` will remove any list or non-null modifiers 
```

Then, if you add a reader to your base object, you could remove another instance_variable_get call: 

```ruby 
class BaseObject < GraphQL::Schema::Object
  def self.model(model_class = nil)
    if model_class # it's a configuration call
      @model_class = model_class
    else # it's a reader call 
      @model_class 
    end 
  end
end
```

```diff 
- .instance_variable_get(:@model_class)
+ .model_class
```

Hope that helps! Let me know if you run into any trouble.

**Comment by rtymchyk** [comment]
> And, why not use `Field#type` instead of `@return_type_expr`?
> 
> ```diff
> - .instance_variable_get(:@return_type_expr)
> + .type.unwrap # `.unwrap` will remove any list or non-null modifiers 
> ```
>

Ah, the non-null is what I struggled with, perfect!

> Then, if you add a reader to your base object, you could remove another instance_variable_get call:
> 
> ```ruby
> class BaseObject < GraphQL::Schema::Object
>   def self.model(model_class = nil)
>     if model_class # it's a configuration call
>       @model_class = model_class
>     else # it's a reader call 
>       @model_class 
>     end 
>   end
> end
> ```
> 
> ```diff
> - .instance_variable_get(:@model_class)
> + .model_class
> ```
>
Really neat trick, did not think of this.

> Hope that helps! Let me know if you run into any trouble.

Thanks a lot of your help.
