### ISSUE TITLE
Module definition in mutation results in uninitialized constant error

### ISSUE THREAD

**Issue by Jimicious** [rmosolgo/graphql-ruby#2904]
**Describe the bug**

When I try to set a folder structure for mutation I get `unitialized constant`, when defining a module inside Mutations module

**Versions**

`graphql`: 1.9.17
`rails`: 5.1.0
`graphql-guard`: 1.2.2

**GraphQL schema**

In `mutation_type.rb` I have
```GraphQL
module Types
  class MutationType < BaseObject
    field :close, mutation: Mutations::PeriodExpense::Close
  end
end
```

This is my folder structure idea:
![image](https://user-images.githubusercontent.com/2679219/80159790-dd72cc00-8599-11ea-9e68-2c5dcc380ed5.png)

**GraphQL mutation**
```GraphQL
module Mutations
  class PeriodExpense::Close < BaseMutation
    field :message, String, null: false

    def resolve()
      { message: "I do something" }
    end
  end
end
```
**Expected behavior**

Get a folder structure, separated in modules, like I can get in Queries

**Actual behavior**

This is what I get:

```batch
uninitialized constant PeriodExpense::Unclose
/Users/matias/Documents/Web/app/graphql/types/mutation_type.rb:22:in `<class:MutationType>'
/Users/matias/Documents/Web/app/graphql/types/mutation_type.rb:2:in `<module:Types>'
/Users/matias/Documents/Web/app/graphql/types/mutation_type.rb:1:in `<top (required)>'
/Users/matias/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/activesupport-5.1.0/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
/Users/matias/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/activesupport-5.1.0/lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
/Users/matias/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/activesupport-5.1.0/lib/active_support/dependencies/interlock.rb:11:in `loading'
/Users/matias/Documents/Web/app/graphql/default_init_schema.rb:2:in `<class:DefaultInitSchema>'
/Users/matias/Documents/Web/app/graphql/default_init_schema.rb:1:in `<top (required)>'
```

**Comment by rmosolgo** [comment]
Your folder structure doesn't match Rails's expectations. Since Rails can't auto-load the constant, it raises that error.

To work with Rails, the folder names should be _underscored_ equivalents of the module names. 

Try renaming `graphql/mutations/PeriodExpense` to `graphql/mutations/period_expense`, and let me know if it doesn't work for you!
