### ISSUE TITLE
Unexpected behavior when running authorized? in a Mutation

### ISSUE THREAD

**Issue by mateosuburu** [rmosolgo/graphql-ruby#2916]
Hi! Thanks a lot to all the maintainers for this project!
 
**Describe the bug**
According to the documentation regarding [mutation_authorization](https://graphql-ruby.org/mutations/mutation_authorization.html#can-this-user-perform-this-action) (last code snippet), I think that returning nil from `authorized?` should not stop the execution of the mutation, but this is currently happening. If I got it right, this behavior isn't documented in [the method](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/resolver.rb#L128-L134) either.

I get that nil evals to false and that's probably the _problem?_ [here](https://github.com/rmosolgo/graphql-ruby/blob/1a0e2552efc99021a5de69550ac93582dab212dd/lib/graphql/schema/resolver.rb#L140). Please let me know if the behavior is actually expected! In that case maybe the documentation could be updated, otherwise I could try to get a fix myself. Thanks!

**Versions**

`graphql` version: `1.10.8`
`ruby` version: `2.6.2`
`rails`: `6.0.2.2`

**GraphQL schema**

Are you using [interpreter](https://graphql-ruby.org/queries/interpreter.html)? `Yes`
Any custom instrumentation, etc? `No`

```ruby
module Mutations
  class SampleMutation < Mutations::BaseMutation
    description 'Sample mutation'

    argument :sample_id, ID, 'ID of the sample object', required: true

    type Types::Objects::SampleType

    def authorized?(sample_id:)
      # if block evals nil, just returning nil is the same but this code block makes sense in a lot of situations
      if false
        raise GraphQL::ExecutionError, "sample"
      end
    end

    def resolve(sample_id:)
      # THIS NEVER RUNS
    end
  end
end

module Types
  module Objects
    class MutationType < Types::Objects::BaseObject
      field :sample_mutation, mutation: Mutations::SampleMutation
    end
  end
end


class ApplicationSchema < GraphQL::Schema
  mutation(Types::Objects::MutationType)
  query(Types::Objects::QueryType)

  # Opt in to the new runtime (default in future graphql-ruby versions)
  use GraphQL::Execution::Interpreter
  use GraphQL::Analysis::AST

  # Add built-in connections for pagination
  use GraphQL::Pagination::Connections
end
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
mutation {
    sample(input: {sampleId: "ID"}) {
        id
    }
}
```

```json
{
    "data": {
        "sample": null
    }
}
```

**Steps to reproduce**
- Override `authorize?` in a mutation and make it return nil.

**Expected behavior**
- Resolve method is executed

**Actual behavior**
- Resolve method is not executed

**Workaround**
```ruby
def authorized?(sample_id:)
  if false
    raise GraphQL::ExecutionError, "sample"
  end
  true
end
```

**Comment by rmosolgo** [comment]
Yes, I'm sorry for the confusion but this _is_ the intended behavior! The docs should say "falsey" or "false or nil", since both of those evaluate to false in a conditional check.

**Comment by mateosuburu** [comment]
Makes sense! Thanks for the quick reply. If you want, I can open a PR to update the documentation and the last example.
