### ISSUE TITLE
https://graphql-ruby.org/ is 404'ing

### ISSUE THREAD

**Issue by nratter** [rmosolgo/graphql-ruby#2920]
https://graphql-ruby.org/ is 404ing right now

**Comment by mishkinf** [comment]
+1

**Comment by rohanmendon** [comment]
+1

**Comment by tipsypastels** [comment]
+1

**Comment by rmosolgo** [comment]
Sorry, the GH Action to build the site failed, I think because of a conflict between the API docs job and the website job. I'll try to fix those jobs to avoid that race condition in the future!
