### ISSUE TITLE
Duplicate type definition found for name 'Value' at 'Field Query.tteesstt's return type'

### ISSUE THREAD

**Issue by afuno** [rmosolgo/graphql-ruby#2922]
Rails 6.0.3, Graphql 1.10.9

---

I have two types with the same names (classes), but they are in different modules:

```ruby
V1::Types::Categories::ValueType
```
```ruby
V1::Types::Tags::ValueType
```

Also inside them are different fields.

Why is this error occurring and how to fix this problem?

> Duplicate type definition found for name 'Value' at 'Field Query.tteesstt's return type' (V1::Types::Categories::ValueType, V1::Types::Tags::ValueType)

**Comment by rmosolgo** [comment]
GraphQL-Ruby uses the class name to infer a GraphQL type name. You can use `graphql_name "..."` or `def self.default_graphql_name` to  customize this behavior, see https://github.com/rmosolgo/graphql-ruby/issues/1243#issuecomment-564049740
