### ISSUE TITLE
Does asynch resolution of resolver exists ?

### ISSUE THREAD

**Issue by nekogami** [rmosolgo/graphql-ruby#2926]
I am sorry to ask it here but I don't know here to look anymore.

In our current company, we migrated to the class based syntax as soon as it was released.
All of our resolver are actually sub-classed from GraphQL::Schema::Resolver.

Right now we have types that have multiple fields bound to different resolver

```
class Types::TestType < Types::BaseObject
  field :subresolver_one, resolver: SubResolverOne
  field :subresolver_two, resolver: SubResolverTwo
  field :subresolver_three, resolver: SubResolverThree
end
```

When all three are requested in the query, we've noticed that subresolver_two was only entered after the full resolution of subresolver_one .

The closest thing that may solve the issue is lazy_resolve but from the documentation I couldn't figure out how to make it work when I bind a resolver to a field for resolution (like in the example).

I was wondering if something already existed to do this or, if not, any hint on where to look to help you for potential implementation ? I tried but kind of got lost in the code when reading the field declaration code.

Again, sorry to bother you with that here.

**Comment by rmosolgo** [comment]
Hi, no problem. Resolvers can use any kind of lazy objects (Promises, etc) just like any field method. 

I don't understand what you want to do. 

> subresolver_two was only entered after the full resolution of subresolver_one

Yes, that's how GraphQL works: it resolves fields one after the other. If the fields return lazy objects, then those objects are resolved in a second pass after all fields have been resolved. Then the cycle repeats. 

Could you share some example code that might help me understand your use case?

**Comment by nekogami** [comment]
@rmosolgo Ok, for some reason, your answer this sunday somehow triggered a "aHA" moment in my head and I finally understood that lazy_resolve was just a way to state that if a field returns that kind of instance with the resolution methiod passed, graphql takes care of the rest.

I still lost like 8h because I misunderstood Threading, but that's on me hahaha.

I am not sure if it is necessary, but, would you be open to a PR than details more on how lazy_resolve works ?

I just would like to add some example with different libs on how lazy_resolve works.
