### ISSUE TITLE
Rails multi DB support based on operation

### ISSUE THREAD

**Issue by chadwilken** [rmosolgo/graphql-ruby#2929]
**Is your feature request related to a problem? Please describe.**
Rails 6 uses the `writing` role for *all* GraphQL requests since it uses the HTTP Verb to select the role.

**Describe the solution you'd like**
On each invocation of `execute` check the operation type and select the correct role.

**Describe alternatives you've considered**
Hooking into the execute call or writing an analyzer to determine which to use.

**Additional context**
I don't know exactly how to check if the user has enabled multi-db support for Rails but I know you can check `ActiveRecord::Base.writing_role` and `reading_role`. It also looks like `ActiveRecord::Base.connection_handlers` returns a hash with *only* the `writing` role if they haven't added a replica.

**Comment by rmosolgo** [comment]
Implementation-wise, I think it could be implemented as a multiplex tracer. My thoughts go there first because: 

- A multiplex _could_ include queries _and_ mutations, and they're run concurrently. So, you'd want to pick `writing_role` if the multiplex contains any non-queries. 
- The Rails API expects a block. A tracer seems like the best GraphQL-Ruby API in that case. 

Here's some pseudocode:

```ruby 
class DatabaseConnectionTracer 
  def trace(event, data) 
    if event == "execute_multiplex" # IIRC this is the top-level event that covers everything else
      multiplex = data[:multiplex]
      # Make sure they're all queries (no mutations or subscriptions)
      role = multiplex.queries.all?(&:query?) ? :reading : :writing 
      # Continue execution with the proper DB role
      ActiveRecord::Base.connected_to(role: role) do 
        yield 
      end 
    else 
      yield
    end 
  end 
end 

# ... 
class MySchema 
  tracer DatabaseConnectionTracer.new 
end 
```

(Under the hood, GraphQL-Ruby treats single queries as a "multiplex-of-one".) 

I don't have a great situation to test this, but if you want to give it a try, let me know how it goes!

**Comment by chadwilken** [comment]
That seems simple enough. I can test it on our staging environment pretty easily. I'll post back results and if I have some time I can open a PR.

**Comment by chadwilken** [comment]
That worked perfectly. Do you think it is something that should be standardized into a feature or just something in the docs that they can look at if they hit the specific use-case?

**Comment by rmosolgo** [comment]
I'm game to include it in GraphQL-Ruby, but I think it should be opt-in for now. I'll take a look.

**Comment by chadwilken** [comment]
I ended up with the following and am using it in production right now. Granted it doesn't take into account the feature of multiple databases, just the reading and writing roles.

```
# frozen_string_literal: true

module Tracers
  class DatabaseRoleTracer
    EVENT_NAME = 'execute_multiplex'.freeze

    def trace(event, data)
      if event == EVENT_NAME
        multiplex = data[:multiplex]

        role = multiplex.queries.all?(&:query?) ?
          ActiveRecord::Base.reading_role :
          ActiveRecord::Base.writing_role

        ActiveRecord::Base.connected_to(role: role) do
          yield
        end
      else
        yield
      end
    end
  end
end

```

**Comment by jasonknebel** [comment]
@chadwilken Hello! I have added your tracer to my schema and it sets the role correctly. However, I still do not see queries going to my reader. Are you still using this setup? Just checking before I go further down the rabbit hole. Thanks!

**Comment by chadwilken** [comment]
@jasonknebel I am still using it but will have to revisit if it is still working. We upgraded all of our GQL gems recently so something may have changed. It's tricky to look at monitoring and know since we have a lot of mutations, which causes the queries for that user to go to the writing role for a few seconds.

**Comment by jasonknebel** [comment]
@chadwilken Got everything working! That code works just fine. You were right; the monitoring can be tricky. Thanks for your code! :bow:

**Comment by grantspeelman** [comment]
Not sure if anyone will find this useful. But here is an example of where i extended the rails middleware.
To make use of the delay switch.

in `lib/graphql_database_selector.rb`
```ruby
class GraphqlDatabaseSelector < ActiveRecord::Middleware::DatabaseSelector
  private

  def reading_request?(request)
    if request.path.include?('/graphql') && request.post?
      graphql_body = request.body.read
      request.body.rewind
      return true if graphql_body.downcase.exclude?('mutation')
    end
    request.get? || request.head?
  end
end
```

in `environments/production.rb` or in `application.rb`
```ruby
require 'graphql_database_selector'
config.middleware.insert_after Rack::TempfileReaper, GraphqlDatabaseSelector, nil, nil, delay: 4.seconds
```

**Comment by rmosolgo** [comment]
Thanks for sharing what you found, everyone. I don't have plans to work on this further so I'm going to close the issue, but I'd welcome a PR with code and docs for this if anyone wants to upstream their implementation.

**Comment by Nealsoni00** [comment]
FYI this is now out of date given `Schema.tracer` deprecation.

> `Schema.tracer(#<Tracers:: DatabaseRoleTracer>)` is deprecated; use module-based `trace_with` instead. See: https://graphql-ruby.org/queries/tracing.html


What I've updated it to:

```ruby
module Tracers
  module DatabaseRoleTracer
    include GraphQL::Tracing

    def execute_multiplex(multiplex)
      set_database_role(multiplex: multiplex[:multiplex]) { super(multiplex:) }
    end

    def set_database_role(multiplex:)
      queries = valid_queries(multiplex:)
      role = valid_queries.all?(&:query?) ?
          ActiveRecord::Base.reading_role :
          ActiveRecord::Base.writing_role

      ActiveRecord::Base.connected_to(role:) do
        yield
      end
    end

    def valid_queries(multiplex:)
      multiplex.queries.filter { |q| q.valid? && q.static_errors.empty? }
    end
  end
end
```

Usage:
```ruby
  trace_with Tracers::DatabaseRoleTracer
```

**Comment by carlos-soto** [comment]
> https://graphql-ruby.org/queries/tracing.html

hi @Nealsoni00, thank you so much for this. One question, what Ruby/Rails version are you using? this code does not work for me:
```
carlos@nfx.com@MacBookPro signal % rails -v
Rails 6.1.4.1
carlos@nfx.com@MacBookPro signal % ruby --version
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [arm64-darwin21]
``

I get:
```
Failure/Error: trace_with Tracers::DatabaseRoleTracer
     
     SyntaxError:
       /Users/carlos@nfx.com/Dev/signal/app/graphql/tracers/database_role_tracer.rb:6: syntax error, unexpected ')'
       ...multiplex]) { super(multiplex:) }
       ...                              ^
       /Users/carlos@nfx.com/Dev/signal/app/graphql/tracers/database_role_tracer.rb:10: syntax error, unexpected ')'
       ...ies = valid_queries(multiplex:)
       ...                              ^
       /Users/carlos@nfx.com/Dev/signal/app/graphql/tracers/database_role_tracer.rb:15: syntax error, unexpected ')'
       ...ecord::Base.connected_to(role:) do
       ...                              ^
       /Users/carlos@nfx.com/Dev/signal/app/graphql/tracers/database_role_tracer.rb:18: syntax error, unexpected `end', expecting '}'
           end
           ^~~
       /Users/carlos@nfx.com/Dev/signal/app/graphql/tracers/database_role_tracer.rb:24: syntax error, unexpected end-of-input, expecting `end'
```

Appreciate the help!

**Comment by rmosolgo** [comment]
That syntax was added in Ruby 3.1 (released in 2021). For old Rubies, pass the local variable with the same name as the symbol: 

```diff 
- super(multiplex:)
+ super(multiplex: multiplex)
```

```diff
- connected_to(role:)
+ connected_to(role: role)
```

**Comment by carlos-soto** [comment]
> That syntax was added in Ruby 3.1 (released in 2021). For old Rubies, pass the local variable with the same name as the symbol:
> 
> ```diff
> - super(multiplex:)
> + super(multiplex: multiplex)
> ```
> 
> ```diff
> - connected_to(role:)
> + connected_to(role: role)
> ```

ah, that makes sense, thank you @rmosolgo! There was also an error in the code on:
```
 queries = valid_queries(multiplex:)
  role = valid_queries.all?(&:query?) ?
```

I changed it to:
```
 role = valid_queries(multiplex:).all?(&:query?) ?
```

The code in the old Ruby version looks like this:

```
module Tracers
  module DatabaseRoleTracer
    include GraphQL::Tracing

    def execute_multiplex(multiplex)
      set_database_role(multiplex: multiplex[:multiplex]) { super(multiplex: multiplex) }
    end

    def set_database_role(multiplex:)
      role = valid_queries(multiplex: multiplex).all?(&:query?) ?
          ActiveRecord::Base.reading_role :
          ActiveRecord::Base.writing_role

      ActiveRecord::Base.connected_to(role: role) do
        yield
      end
    end

    def valid_queries(multiplex:)
      byebug
      multiplex.queries.filter { |q| q.valid? && q.static_errors.empty? }
    end
  end
end
```

Thank you!

**Comment by kaito0228** [comment]
The following code broke after upgrading to graphql-ruby 2.5.0.
The environment is as follows:

- Ruby 3.4.2
- Ruby on Rails 7.2.2.1
- graphql-ruby 2.4.15 → 2.5.0

The error and the relevant code are as follows:
```
NoMethodError: undefined method 'start_child' for nil (NoMethodError)

              @span.start_child(op: span_name)
                   ^^^^^^^^^^^^
/usr/app/app/graphql/concerns/tracers/database_role_tracer.rb:7:in 'block in Tracers::DatabaseRoleTracer#execute_multiplex'
/usr/app/app/graphql/concerns/tracers/database_role_tracer.rb:17:in 'Tracers::DatabaseRoleTracer#set_database_role'
/usr/app/app/graphql/concerns/tracers/database_role_tracer.rb:7:in 'Tracers::DatabaseRoleTracer#execute_multiplex'
```

Code
``` ruby
# https://github.com/rmosolgo/graphql-ruby/issues/2929
module Tracers
  module DatabaseRoleTracer
    include GraphQL::Tracing

    def execute_multiplex(multiplex:)
      set_database_role(multiplex:) { super(multiplex:) }
    end

    def set_database_role(multiplex:, &)
      role = if valid_queries(multiplex:).all?(&:query?)
               ActiveRecord.reading_role
             else
               ActiveRecord.writing_role
             end

      ActiveRecord::Base.connected_to(role:, &)
    end

    def valid_queries(multiplex:)
      multiplex.queries.filter { |q| q.valid? && q.static_errors.empty? }
    end
  end
end

```

**Comment by rmosolgo** [comment]
Hey @kaito0228 , sorry for the trouble and thanks for reporting this. It seems like this error is coming from the `super(multiplex:)` call, which calls other tracers in the app. Do you have other tracers installed in your schema, probably with `trace_with` in your schema class definition?

**Comment by neocoin** [comment]
```ruby
module Tracing
  module SelectReadingDatabaseForQueryTrace
    # @param [GraphQL::Query] query
    def execute_query(query:)
      if query&.valid? && query.query?
        ApplicationRecord.connected_to(role: ActiveRecord.reading_role) { yield }
      else
        yield
      end
    end
  end
end
```

@kaito0228 Thank you, snippet.

We were in a similar situation, and after reviewing it, we found that the following was sufficient.

This code excludes the dataloader and lazy execution, as we believe those components should each be responsible for choosing how to read from the database.

ref
https://graphql-ruby.org/dataloader/overview.html
https://graphql-ruby.org/schema/lazy_execution

**Comment by kaito0228** [comment]
@rmosolgo 
Thank you very much.
I was using the following TRACER together.

``` ruby
  trace_with Tracers::DatabaseRoleTracer
  trace_with GraphQL::Tracing::SentryTrace
```

**Comment by sirwolfgang** [comment]
Building from @neocoin but with reading being the default role:
```ruby
module Tracers
  module DatabaseRoleTracer
    include GraphQL::Tracing

    # @param [GraphQL::Query] query
    def execute_query(query:, &)
      role = query&.valid? && !query.query? ? ActiveRecord.writing_role : ActiveRecord.reading_role

      ActiveRecord::Base.connected_to(role:, &)
    end
  end
end
```

**Comment by rmosolgo** [comment]
For future readers, it's worth reiterating the downside to choosing `execute_query` instead of `execute_multiplex`: it won't play nice with `GraphQL::Dataloader` or `GraphQL::Batch` (or any other lazy loading framework). `execute_query` covers the part of execution _until_ GraphQL encounters a pause of some kind (depends on the lazy loading approach), but doesn't wrap the code that comes after the pause. 

On the other hand, `execute_multiplex` covers the _whole_ execution of all queries in the multiplex. (If you're not using `MySchema.multiplex(...)`, then it's just one single query.)

If you're receiving a batch of queries and passing them to `MySchema.multiplex(...)`, there's no way to separate the `query ...`s from the `mutation ...`s: they're run together in the order that they're passed to `multiplex(...)`. (The GraphQL spec describes how fields should be evaluated _within_ a `mutation ...`, but doesn't cover batch execution.) You'll want to use `writing_role` in that case, or split queries vs mutations in your controller and call `multiplex(...)` twice.

**Comment by sirwolfgang** [comment]
Here's a version that includes few optimizations
```ruby
# frozen_string_literal: true

module Tracers
  # @see https://github.com/rmosolgo/graphql-ruby/issues/2929
  module DatabaseRoleTracer
    include GraphQL::Tracing

    def execute_multiplex(multiplex:)
      role = if valid_queries(multiplex).any? { !it.query? }
               ActiveRecord.writing_role
             else
               ActiveRecord.reading_role
             end

      ActiveRecord::Base.connected_to(role:) do
        super
      end
    end

    def valid_queries(multiplex)
      multiplex.queries.filter { it.valid? && it.static_errors.empty? }
    end
  end
end
```
