### ISSUE TITLE
The GraphQL Playground option to install generator installs GraphiQL

### ISSUE THREAD

**Issue by conradwt** [rmosolgo/graphql-ruby#2932]
**Describe the bug**

The playground option to install generator installs GraphiQL instead of GraphQL Playground when performing the following command:

```bash
rails generate graphql:install --playground
```

**Versions**

`graphql` version:  1.9
`rails` (or other framework): Rails 6.0.3

**Steps to reproduce**

rails generate graphql:install --playground

**Expected behavior**

routes:
```ruby
  if Rails.env.development?
    mount GraphqlPlayground::Rails::Engine, at: "/playground", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
```

Gemfile:
```ruby
gem'graphql_playground-rails', group: :development
```

**Actual behavior**

routes:rb:
```ruby
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
```

Gemfile:
```ruby
gem 'graphiql-rails', group: :development
```

**Comment by rmosolgo** [comment]
I'm not sure if this was a mistake or not. Maybe it's supposed to be at `/graphiql` as a matter of convention. cc @joeytepp as the author of #2839 -- Did you mean to use `at: "/graphiql"` here? 

(Did I understand the problem correctly, @conradwt ? I see `GraphiQL::Rails::Engine` in both "expected behavior" and "actual behavior" above, but I noticed the path is different.)

**Comment by joeytepp** [comment]
Ya it wasn’t a mistake, there’s still the `—skip-graphiql` option to skip installing graphiql but I decided that installing playground shouldn’t implicitly mean that you’re skipping `graphiql`. I’m happy to add a PR to change this if enough people think this should be the case.

**Comment by joeytepp** [comment]
https://github.com/rmosolgo/graphql-ruby/pull/2839/files#diff-7b984d2a8a4fee86fd67b72d37dcfaa5L142 with the playground option you should have a route that looks like:

```ruby
  if Rails.env.development?
    mount GraphqlPlayground::Rails::Engine, at: "/playground", graphql_path: "/graphql"
  end
```
The install generator hasn't been touched since I added this so not sure what could be causing this behavior

**Comment by conradwt** [comment]
> I'm not sure if this was a mistake or not. Maybe it's supposed to be at `/graphiql` as a matter of convention. cc @joeytepp as the author of #2839 -- Did you mean to use `at: "/graphiql"` here?
> 
> (Did I understand the problem correctly, @conradwt ? I see `GraphiQL::Rails::Engine` in both "expected behavior" and "actual behavior" above, but I noticed the path is different.)

Just corrected the original post.

**Comment by joeytepp** [comment]
@conradwt ah I see what the problem is. This feature is only available in version `1.10.6` and up of the `graphql` gem so your gem must be out of date. If you update and re-run the install generator with the `--playground` option you should have graphql playground at `/playground`, and you can avoid setting up `graphiql` as well by adding the `--skip-graphiql` option. Hope that's helpful!

**Comment by conradwt** [comment]
@joeytepp Yes, I just updated the application and realized that I was using a much older version of `graphql`.  Is the expected behavior correct?

`Gemfile`:
```ruby
gem 'graphiql-rails', group: :development
gem 'graphql_playground-rails', group: :development
```

`routes.rb`:
```ruby
  if Rails.env.development?
    mount GraphqlPlayground::Rails::Engine, at: "/playground", graphql_path: "/graphql"
  end
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
```

**Comment by joeytepp** [comment]
Yup that’s the correct behavior!

**Comment by conradwt** [comment]
Can one use the `Playground` interface without the `GraphiQL` interface?

**Comment by joeytepp** [comment]
Yup, you just need to add the `--skip-graphiql` option to the generator as well, ie.
```bash
$ rails g graphql:install --playground --skip-graphiql
```

**Comment by conradwt** [comment]
Thanks for the information and this issue can be closed.
