### ISSUE TITLE
Graphql::Types::BigInt field being returned as String in Query Response.

### ISSUE THREAD

**Issue by mubashirkamran4** [rmosolgo/graphql-ruby#2943]
Hi,
I am using graphql gem version 1.9.19 with Rails 6.0.2.1. When I execute a mutation for a model having BigInt field, works perfectly fine but when I execute the query,  the field shows up as String in response?

**Comment by rmosolgo** [comment]
This is the intended behavior, please see the `Int` section of the GraphQL spec: http://spec.graphql.org/June2018/#sec-Int

> Numeric integer values larger than 32‐bit should either use String or a custom‐defined Scalar type, as not all platforms and transports support encoding integer numbers larger than 32‐bit.

If you want to return large integers using Ruby integers, I recommend implementing a custom scalar type. You could use `BigInt` as inspiration, and remove the parts that stringify output. Hope that helps!
