### ISSUE TITLE
Seeing Infinite Loop On Application Start Using GraphQL Playground UI

### ISSUE THREAD

**Issue by conradwt** [rmosolgo/graphql-ruby#2952]
**Describe the bug**

When I run `rails s` from the terminal, the application goes into an infinite loop.  It simply generates the following requests:

```
Started POST "/graphql"
```

This started happening after migrating the application to use `GraphQL Playground` instead of the `GraphiQL`.  Again, this issue doesn't happen when using `GraphiQL` UI.

**Versions**

`graphql` version: 1.10.9
`rails` (or other framework): 6.0.3
other applicable versions (`graphql-batch`, etc)

**Steps to reproduce**

```
rails s
```

**Expected behavior**

The application wouldn't go into an infinite loop.

**Actual behavior**

The application goes into an infinite loop.

**Comment by rmosolgo** [comment]
It sounds like the browser is repeatedly sending requests to the server, is that right? 

Could you please reproduce the issue on a restarted Rails server and browser tab, then share the full Rails logs and browser log (at least the network tab)?

**Comment by conradwt** [comment]
> It sounds like the browser is repeatedly sending requests to the server, is that right?
> 

Yes, it feels like the browser is sending the request over and over again.

> Could you please reproduce the issue on a restarted Rails server and browser tab, then share the full Rails logs and browser log (at least the network tab)?

*  [development.log.zip](https://github.com/rmosolgo/graphql-ruby/files/4654270/development.log.zip)

* [firefox-logging.txt-main.3752.moz_log.zip](https://github.com/rmosolgo/graphql-ruby/files/4654257/firefox-logging.txt-main.3752.moz_log.zip)

Note:  When you see zero bytes being returned from the server, it means that I have stopped the `rails server`.  The odd thing here is the browser continued making requests.  The above data is using `Firefox` but I'm also seeing the same issue within `Chrome`.

**Comment by rmosolgo** [comment]
Thanks for sharing those logs. Sure 'nuf, it looks like the browser is sending the introspection query over and over. GraphQL-Ruby includes a framework for building the graphql server and running queries, and there's a generator for installing graphql-playground, but GraphQL-Ruby doesn't have control over the JavaScript code running in the browser. 

You could try opening an issue on https://github.com/papodaca/graphql_playground-rails or https://github.com/prisma-labs/graphql-playground, but I'm afraid I don't really have any insight into how graphql-playground is really supposed to work! (I've never used it.)
