### ISSUE TITLE
`GraphQL::TypeKinds::ENUM.scalar?` oddly returns `false`

### ISSUE THREAD

**Issue by myronmarston** [rmosolgo/graphql-ruby#2962]
**Is your feature request related to a problem? Please describe.**

I was surprised to see that `GraphQL::TypeKinds::ENUM.scalar?` returns `false` when I expected it to return `true`.  While this is probably intentional, it feels like a bug to me because my understanding of the GraphQL type system is that enums are a kind of scalar type.  For example, here's the wording from the [GraphQL spec](https://spec.graphql.org/June2018/#sec-Scalars) in the scalar section:

> Scalar types represent primitive leaf values in a GraphQL type system. GraphQL responses take the form of a hierarchical tree; the leaves on these trees are GraphQL scalars.

It doesn't say "some leaves on these trees are GraphQL scalars" or "most leaves on these trees are GraphQL scalars".  It says "the leaves on these trees are GraphQL scalars" which implies (to me, at least) that every leaf type is a scalar type, and enums are a leaf type.

Apart from the GraphQL spec, my informal understanding of "scalar" in a type system is that any type that is an individual value (as opposed to some kind of collection of values, such as a list, map, set, or tuple) is a scalar, so it was quite surprising to me to see that graphql gem considers enums to not be scalars.  

**Describe the solution you'd like**

Ideally `GraphQL::TypeKinds::ENUM.scalar?` would return `true`.

**Describe alternatives you've considered**

I understand there are repercussions to changing this, as clients may currently be using `scalar?` to distinguish "normal" scalar types from enums.  If we get agreement on my suggested change I'm happy to submit a PR making the change.

**Comment by rmosolgo** [comment]
Hey, sorry about the confusion and thanks for the detailed writeup. I guess the existing distinction between enums and scalars is based on bits from the spec like this: 

> GraphQL Enum types, like scalar types, also represent leaf values in a GraphQL type system. However Enum types describe the set of possible values.

(https://spec.graphql.org/June2018/#sec-Enums)

So, I see enums as _like scalars_, but not scalars. When it comes to transporting GraphQL (eg, JSON), enums are usually expressed as scalars in the transport language. 

How about adding a `.leaf?` method to TypeKind? That would give a method which is true for both enum and scalar, but not for anything else. (As you mentioned, changing the implementation of `.scalar?` is pretty risky at this point.)

**Comment by myronmarston** [comment]
It's unfortunate that the spec is kinda ambiguous about whether enums are type of scalar, or just a type that is scalar-like.

Anyhow, we've worked around this issue in our code base (we're just checking `scalar? || enum?`).  I'm not sure if we'd use `.leaf?` or not but it sounds like a good solution if you want to add it.

**Comment by myronmarston** [comment]
Another possible idea is `scalar_like?`

**Comment by rmosolgo** [comment]
:+1: Glad you found something that works for you. I don't plan to add `.leaf?` but I'd welcome the PR if someone finds a use for it down the road!
