### ISSUE TITLE
Guide: Interpreter

### ISSUE THREAD

**Issue by benrbrook** [rmosolgo/graphql-ruby#2963]
The guide for the new interpreter includes a note about migration.

> You can migrate to Interpreter before migrating to Analysis::AST. In that case, the irep_node tree will still be constructed and used for analysis, even though it will not be used for execution.

However, if you try to use the new interpreter without `use GraphQL::Analysis::AST`, it crashes with the message:
```Can't use GraphQL::Execution::Interpreter without GraphQL::Analysis::AST, please add this plugin to your schema: use GraphQL::Analysis::AST```

Are these migration notes still relevant or should they be updated to specify that both need to be included? We are on version `1.10.8` of the gem.

**Comment by rmosolgo** [comment]
Thanks for reporting this! Yeah, 1.10+ _requires_ Analysis::AST for interpreter; 1.9.x _doesn't_. I updated the docs in 3621e9d89
