### ISSUE TITLE
Web site search for "API" docs is returning 404s

### ISSUE THREAD

**Issue by bbugh** [rmosolgo/graphql-ruby#2967]
**Describe the bug**

Using Search on the documentation page and clicking on any API search link results in a 404.

**Steps to reproduce**

1. https://graphql-ruby.org/
2. Search for an API thing, like `Tracing`, `Backtrace`
3. Click on the API link

Voila, 404.

**Expected behavior**

The documentation exists!

**Additional context**

The bad links are like this:

- https://graphql-ruby.org/api-doc/1.10.10/GraphQL/Backtrace/Tracer
- https://graphql-ruby.org/api-doc/1.10.10/GraphQL/Tracing#sending-custom-events

**Comment by rmosolgo** [comment]
Thanks for reporting this. Sometimes my job for publishing API docs from tags fails 😖  I re-ran it and now we're up. I really have to improve the job, but I'll have to take a look later. 1.10.10 docs are up now!

**Comment by opiation** [comment]
Sorry @rmosolgo, not sure if this is the same thing but I'm getting errors in the web site's search bar:

From the Chrome web console at `https://graphql-ruby.org/`

```
Uncaught ReferenceError: GraphQLRubySearch is not defined
    at HTMLInputElement.onkeyup ((index):31)
```

If this is unrelated, I'm happy to create a new issue.  Just seems interestingly coincidental with your most recent re-deployment of docs...

**Comment by rmosolgo** [comment]
🤦  Now, apparently my build task is rendering `search.js` inside an HTML template: 

https://graphql-ruby.org/js/search.js

I guess I'll figure out how to straighten that out. Thanks for letting me know.

**Comment by rmosolgo** [comment]
Aaaand we're back. It looks like GH Actions was building with Jekyll 4.x. When I `bundle update`d locally, I saw the same problem. Fix by https://github.com/rmosolgo/graphql-ruby/commit/d0195313bb90576c59397b1b767780e6862360e6 (removing yaml front matter from `.js` file)
