### ISSUE TITLE
ScoutTracing does not set the transaction name like NewRelicTracing

### ISSUE THREAD

**Issue by bbugh** [rmosolgo/graphql-ruby#2968]
**Is your feature request related to a problem? Please describe.**

We switched from New Relic to Scout for APM, and noticed that the `NewRelicTracing` sets the transaction name when it's a single query, but Scout doesn't. The code for this is almost identical (just calling the Scout equivalent of set transaction name):

```ruby
# NewRelicTracing (current)
NewRelic::Agent.set_transaction_name("GraphQL/#{op_type}.#{op_name}")

# ScoutTracing (proposed)
ScoutApm::Transaction.rename("GraphQL/#{op_type}.#{op_name}")
```

**Describe the solution you'd like**

`GraphQL::Tracing::ScoutTracing` sets the transaction name for `execute_query` just like `GraphQL::Tracing::NewRelicTracing` does.

**Describe alternatives you've considered**

We made a subclass of `GraphQL::Tracing::ScoutTracing` to do this, but I think it's a feature of the tracer itself.

**Additional context**

I am happy to PR this to add to `GraphQL::Tracing::ScoutTracing`. It's a very simple change.

**Comment by rmosolgo** [comment]
:+1: That'd be a great addition, I'd really appreciate a PR for it!

**Comment by jimytc** [comment]
Hi @bbugh 

We are also trying ScoutAPM and rename the endpoint.
Thank you for making this change which saved a lot of time.
But we have some issue about reporting.

We had our own implementation for rename endpoints and adapted this solution with 1.10.11+ release.
In both ways we did not get the endpoint renamed to the form `GraphQL/#{op_type}.#{op_name}`.
Further, many queries/mutations are missing.
We've reached out to ScoutAPM support for help but we still don't know what's the cause.

I'd like to know if this works as what you expected with ScoutAPM?
Here's my setup.

```
Ruby 2.4.1
Rails 5.1.6
graphql-ruby 1.10.13
scout_apm 2.6.7

Run on docker
```

```ruby
# Add the following line to graphql schema
use(GraphQL::Tracing::ScoutTracing, set_transaction_name: true)
```

@bbugh and @rmosolgo 

I'm not sure if this is the right place to ask but it seems to be only place for this context.
If there's other channel to discuss this further, please let me know and we could continue the conversation there.
Thank you.

**Comment by bbugh** [comment]
Hi @jimytc! 👋 Glad this saved you some time. We did indeed have the same issue with Scout. While debugging it, it appeared that this patch was sending all of the right information, but Scout wasn't capturing and/or displaying it immediately. My best guess is that they were doing batch releases or some kind of slow processing; I think it does eventually show up on their site. If you find out otherwise, I'd love to know too.

**Comment by jimytc** [comment]
@bbugh 

We have pushed it for a while but looks like those logs are just missing. 🤔 
Anyway, I hope this is just our issue.

I'm trying to set up a clean project to see if this can be reproduced.

Thank you!
