### ISSUE TITLE
Unit testing mutations

### ISSUE THREAD

**Issue by TomasBarry** [rmosolgo/graphql-ruby#2971]
I have not been able to confirm whether or not this is possible but let's say that I have a mutation:

```ruby
module Mutations
  class MyMutation < BaseMutation
    argument :param, Inputs::ParamInput, required: true

    type Types::MyType

    def resolve(param:)
      # do something
    end
  end
end
```

Where `Inputs::ParamInput` is defined as:

```ruby
module Inputs
  class ParamInput < Types::BaseInputObject
    argument :number, Integer, required: true

	# some prepare statement as I'd like to be able to use this
    # in the mutation if possible
    def prepare
      if number < 10
        'small'
      else
        'large'
      end
    end
  end
end

```

I would like to be able to unit test `Mutations::MyMutation` in the following manner:

```ruby
require 'rails_helper'

RSpec.describe Mutations::Box::OneOffBoxCreate do
  describe '#resolve' do
    context 'when the param number is less than 10' do
      it 'should do something' do
        args = {
          param: Input::ParamInput.new(
            {
              number: 5
            },
            context: {},
            defaults_used: {}
          )
        }

        described_class.new(
          object: nil,
          context: {}
        ).resolve(args)

        # expectations
      end
    end
```

Is this possible? I am getting the error:

```
NoMethodError:
  undefined method `new' for nil:NilClass
  # .../.rvm/gems/ruby-2.6.0/gems/graphql-1.9.15/lib/graphql/schema/input_object.rb:15:in `initialize'
  ...
```

**Comment by rmosolgo** [comment]
GraphQL primitives are only meant to be used for GraphQL queries. If you have logic that needs testing outside GraphQL, I recommend extracting _from_ your interface layer and _into_ your application layer, then writing unit tests for it. 

Or, if you want to test GraphQL code, I recommend running GraphQL queries and testing the result. 

The methods and lifecycle of GraphQL primitives aren't really stable enough to test in isolation, either. They're really only intended to work as documented!

**Comment by TomasBarry** [comment]
Thanks for the response @rmosolgo.
