### ISSUE TITLE
pageInfo returns incorrect results if called before nodes in a query

### ISSUE THREAD

**Issue by vpetkar** [rmosolgo/graphql-ruby#2972]
**Describe the bug**
`pageInfo` returns incorrect results if it is queried before `nodes`, while it works if it is queried after `nodes`.

**Versions**

`graphql` version: 1.10.10
`rails` (or other framework): 6.0.3
`graphql-batch`: 0.4.3
`graphql-pro`: 1.13.5

**GraphQL schema**

Note: Using new interpreter

```ruby
# frozen_string_literal: true
  module Types
    class SampleType < GraphQL::Types::Relay::BaseConnection
      edge_type(SampleEdgeType)
    end
  end
```

**GraphQL query**

```graphql
# Works as expected
query {
  samples(handle: 'abc', first: 12, after: 'somegeneratedidentifier' {
    nodes {
      id
    }
    pageInfo {
      hasPreviousPage
      hasNextPage
    }
  }
}
```
```graphql
# Does not work, hasPreviousPage is always false and hasNextPage is always true
query {
  samples(handle: 'abc', first: 12, after: 'somegeneratedidentifier' {
    pageInfo {
      hasPreviousPage
      hasNextPage
    }
    nodes {
      id
    }
  }
}
```
**Steps to reproduce**
- Switch up the ordering of where `pageInfo` is called within a query.

**Expected behavior**
Calling pageInfo before nodes should have no effect on the pageInfo data

**Additional context**
Probably related to this: https://github.com/rmosolgo/graphql-ruby/pull/2845#issuecomment-639109923

**Comment by rmosolgo** [comment]
Thanks for the detailed report! I was able to replicated just like you said, and I released `graphql-pro 1.13.6` with a fix. Please give it a try and let me know if you run into any other trouble! It looks like it wasn't properly distinguishing between value-based cursors and offset-based cursors for has_next_page and has_previous_page, when they weren't already set when loading nodes.
