### ISSUE TITLE
Support Ably presence notifications

### ISSUE THREAD

**Issue by jscheid** [rmosolgo/graphql-ruby#2990]
**Is your feature request related to a problem? Please describe.**

When using graphql-ruby-client with Ably, after a subscription terminates, it takes about a minute before the graphql-ruby server is notified.

This means that any triggers during that time period will cause unnecessary Ably messages to be sent, as well as potentially consumption of other resources (CPU, memory, database) depending on the subscription query.

Ably doesn't close the channel until after a delay:
> channels are asynchronously gc'd about a minute after the last activity on the channel, see https://support.ably.io/en/support/solutions/articles/3000061294-how-does-ably-count-peak-channels-

**Describe the solution you'd like**

graphql-ruby should respond to Ably _presence_ events instead of _channel lifecycle_ events. I have verified that presence events are sent more or less immediately after the subscription has been disposed.

**Describe alternatives you've considered**

N/A

**Additional context**

~I've also verified that subscribing _just_ to presence events isn't sufficient, as the leave event isn't fired if (for example) the browser tab running the app is simply closed.~

Ably pointed out that this is incorrect, not sure why I got the wrong reading:
>  If a connection disconnects abruptly, leave events should be fired for all of that connection's presence members 15s after the server notices that the connection has disconnected. In the worst case (tcp connection not closed properly) detecting that the connection is gone can take half a minute after the connection drops (detected using heartbeats). In the best/common case it should be immediate (closing the tab triggers the beforeunload  handler which by default closes the connection).

**Comment by sguha00** [comment]
Do the instructions here https://graphql-ruby.org/subscriptions/ably_implementation#ably indicate that presence events are now supported?

**Comment by rmosolgo** [comment]
Hey, thanks for asking. Yes, it does! But I forgot to close this issue. Listening for `presence.leave` was added in GraphQL-Pro v1.23.5: https://github.com/rmosolgo/graphql-ruby/blob/master/CHANGELOG-pro.md#1235-29-december-2022
