### ISSUE TITLE
InvalidNullError is not defined on mutation classes

### ISSUE THREAD

**Issue by srgoldman** [rmosolgo/graphql-ruby#2995]
**Describe the bug**

```
class MyMutation < GraphQL::Schema::Mutation
  field :x, ..., null: false

  def resolve
     { x: nil }
  end
end
```
You'll get an error: uninitialized constant `MyMutation::InvalidNullError`

**Versions**

`graphql` version: 1.10.11
`rails` (or other framework): 6.0.3.1
other applicable versions (`graphql-batch`, etc)

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok).
Are you using [interpreter](https://graphql-ruby.org/queries/interpreter.html)? Any custom instrumentation, etc?

```ruby
class Product < GraphQL::Schema::Object
  field :id, ID, null: false, hash_key: :id
  # …
end

class ApplicationSchema < GraphQL::Schema
  query QueryType
  # …
end
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
query {
  products { id title }
}
```

```json
{
  "data": {
    "products": […]
  }
}
```

**Steps to reproduce**

Steps to reproduce the behavior

**Expected behavior**

**Actual behavior**

What specifically went wrong?

Place full backtrace here (if a Ruby exception is involved):

<details>
<summary>Click to view exception backtrace</summary>

```
Something went wrong
2.6.0/gems/graphql-1.9.17/lib/graphql/subscriptions/instrumentation.rb:34:in `after_query'
… don't hesitate to include all the rows here: they will be collapsed
```

</details>

**Additional context**

With these details, we can efficiently hunt down the bug!

**Comment by rmosolgo** [comment]
Oops, thanks for the report! I guess I missed a spot in #2957
