### ISSUE TITLE
Multiple definitions error for classes that share class name but are in different modules

### ISSUE THREAD

**Issue by jasonayre** [rmosolgo/graphql-ruby#2998]
**Describe the bug**

I'm trying to hook my existing lower level Schema/typing library, into graphql, by creating custom types which do basic coercion. -- I am running into the folowing error:

Previously found Client::ExportTemplate::Fields::Kind::GraphQLObject (Class), then found Client::ExportTemplates::SurveyParticipationsExportTemplate::Fields::FieldMappings::GraphQLObject (Class) at Query.participationsExportTemplate.fieldMappings (GraphQL::Schema::DuplicateTypeNamesError)

-- So it appears that the check for duplicate type names isn't checking the fully qualified constant, but rather just the demodulized constant name and is causing it to blowup

**Versions**

`graphql` version: 1.11
`rails` 4.2.0):

**GraphQL schema**

See example type below, in which I am mapping my value objects to graphql compatible ones, as well as example base object in which it's occuring -- Note I am storing the GraphQLObject class object on the value object itself, since the namespace already exists that way and it should allow multiple fields to point to the same field while using same underlying class, since it is the same underlying class.

```ruby

module Types
  class TraxStruct < Types::BaseScalar
    def self.for(klass)
      _name = "::#{klass.name}::GraphQLObject"
      _name.safe_constantize || ::Trax::Core::NamedClass.new(_name, "::Types::TraxStruct".constantize, :trax_klass => klass)
    end

    def self.coerce_input(value, _context)
      trax_klass.new(value)
    end

    def self.coerce_result(value, _context)
      value.to_hash
    end
  end
end

module Admin
  module Types
    class ParticipationsExportTemplate < ::Types::BaseObject
      description "participationsExportTemplate"
      field :kind, :type => ::Types::TraxEnum.for(::Client::ExportTemplate::Fields::Kind), null: false
      field :field_mappings, :type => ::Types::TraxStruct.for(::Client::ExportTemplates::SurveyParticipationsExportTemplate::Fields::FieldMappings), null: false
    end
  end
end

```

**Steps to reproduce**

Define two classes with the same name in different modules and you should see the error, try using them both as types and error should occur

**Expected behavior**

Error to not be raised

**Comment by jasonayre** [comment]
(Also in case of confusion, Trax::Core::NamedClass just defines an anonymous class, assigns it a fully qualified constant name in the correct namespace, 2nd param is the class it's inheriting from)

**Comment by rmosolgo** [comment]
That's right -- GraphQL ruby doesn't use module namespaces by default. If you want to change that behavior, override `def self.default_graphql_name` in your base classes. See also https://github.com/rmosolgo/graphql-ruby/issues/1243#issuecomment-564049740

Let me know if you run into any trouble with that!
