### ISSUE TITLE
Arguments should prevent _both_ default_value and required: true

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#3001]
I don't think there's any reason to permit `default_value:` _and_ `required: true`, because a required argument will never apply a default value. 

This was previously validated by legacy schemas, but it seems like class-based schemas aren't validating it properly.

**Comment by Diego-Thomaz** [comment]
Hi @rmosolgo I'm new with graphql-ruby, but I think I can help you with this one. Do you think this validation should be a new rule, or it can be implemented with required argument rule?

**Comment by rmosolgo** [comment]
👋 @Diego-Thomaz, that'd be great! 

Honestly, I think the best place to add this check is inside `GraphQL::Schema::Argument#initialize`. There, you could check the `required:` and `default_value:` keyword arguments to make sure they don't conflict. 

One advantage to putting the validation _there_ is that, when it raises an error, the application code with the invalid configuration will be present in the backtrace. 

Let me know if you give it a try and there's anything I can help with!

**Comment by Diego-Thomaz** [comment]
> 👋 @Diego-Thomaz, that'd be great!
> 
> Honestly, I think the best place to add this check is inside `GraphQL::Schema::Argument#initialize`. There, you could check the `required:` and `default_value:` keyword arguments to make sure they don't conflict.
> 
> One advantage to putting the validation _there_ is that, when it raises an error, the application code with the invalid configuration will be present in the backtrace.
> 
> Let me know if you give it a try and there's anything I can help with!

Thanks for the answer @rmosolgo 

I'll give it a try!

**Comment by swalkinshaw** [comment]
Pretty sure this is against the spec *and* reverts behaviour which previously fixed: https://github.com/rmosolgo/graphql-ruby/issues/2356

cc @eapache

**Comment by rmosolgo** [comment]
Ugh, sorry. Looking back that the PR that implemented this change, it didn't jump out that those tests were for this explicit behavior. But I guess it was `it 'uses default_value: with no input' do`. 

Anyways, sorry I was mistaken on this one, I'll get a revert together.
