### ISSUE TITLE
[Pro] Authorize model attributes with can? and hide schema objects

### ISSUE THREAD

**Issue by fshauge** [rmosolgo/graphql-ruby#3002]
Hey! Thanks for GraphQL and GraphQL::Pro, they are amazing tools! We currently have two issues with GraphQL::Pro (specifically the CanCan integration) that prevent us from using it in our product.

## 1. Limiting model attributes with CanCan

CanCanCan 3.0.0 added support for checking access against model attributes when using `can?`/`cannot?`. This is useful for deciding whether a field of a GraphQL type should be accessible by a user or not. We have configured Devise with two user types, candidates and employees, and would like to use GraphQL::Pro's CanCan integration to lock down specific fields that a candidate should not have access to. For example, a candidate should not have access to the review an employee has written for an application. As far as I can tell, checking against a specific attribute on a Rails model with CanCan is not possible through GraphQL::Pro's API.

[Here](https://github.com/CanCanCommunity/cancancan/pull/474) is the pull request that introduced the API change. There are several options here, but we thought about sending `method_sym` from `GraphQL::Schema::Field` to `can?` as the third argument. This works fine because sending an attribute to `can?` that is not specifically permitted will return `true`.

## 2. Hiding schema objects

The [documentation](https://imaharu.github.io/graphql-ruby-doc-ja/schema/limiting_visibility.html) for GraphQL suggests using whitelist/blacklist for schema hiding/masking. Whitelisting the schema seemed like a good idea to us in the beginning, but revealed a couple of weaknesses.

1. All schema objects are hidden. This includes objects that we have no control over. The result of using a whitelist is that introspection does not work. We can probably work around this issue with minimal effort, but it is an annoyance nonetheless.
2. Schema hiding logic is not colocated with GraphQL types. This felt unstructured as `can_can_action` is already declared in the respective objects, fields, arguments etc.

A solution to the problem is defining a new `can_can_visible` option that takes `[action, type, attribute]` and decides whether a object, field, argument, etc. is visible or not. 

Example usage:

```ruby
module Types
  class ApplicationType < Base::Object
    can_can_visible [:read, Application]

    field :id, ID, null: false
    field :user, UserType, null: false
    field :posting, PostingType, null: false
    field :review, Integer, null: true, can_can_visible: [:read, Application]
  end
end
```

Any user with the ability to read an `Application` have access to all fields returning an `ApplicationType`. Both user types can read applications. Any user with the ability to read the `review` attribute on `Application` has access to the `review` field. Only employees have access to the `review` attribute.

Are these changes feasible to implement, or are there better ways to solve our problems?

**Comment by rmosolgo** [comment]
👋 Hi! Thanks for the writeup and suggestions. I think the changes are definitely feasible. Let me take a look at how they can best be implemented and I'll follow up here.

**Comment by rmosolgo** [comment]
I've just released graphql-pro 1.14.1 which adds a `can_can_attribute:` configuration. You can find the docs for it (as well as a suggestions for adding a default value, like you described) here: https://graphql-ruby.org/authorization/can_can_integration#authorizing-by-attribute

Regarding schema visibility, the best think I can think of would be to implement `def self.visible?` in the type classes, as described here: https://graphql-ruby.org/authorization/visibility.html

To implement an API like you described, you could do this: 

```ruby 
class Types::BaseObject 
  # Accept the array in the class definition 
  def self.can_can_visible(config) 
    @can_can_visible_config = config 
  end 
  
  def self.visible?(context)
    if @can_can_visible_config
      # Get the memoized Ability instance from `context` (this is implemented in GraphQL-Pro)
      ability = get_can_can_ability(context)
      ability.can?(*@can_can_visible_config)
    else 
      true 
    end 
  end 
end 
```

(I implemented it to accept an array as shown in the original post, you might update it to take named params instead. But that's the gist of it!) 


 If you wanted to use that same API in other other base classes, you could extract it to a module and `extend`/`include` it in those other base classes. 

Want to give it a try?

**Comment by rmosolgo** [comment]
Let me know if you give it a try, or if you run into any trouble!

**Comment by fshauge** [comment]
Sorry for the late reply. We have finally been able to test 1.14.1 thoroughly, and the additional `can_can_attribute` configuration is exactly what we need! 😊 As per your suggestion, we implemented a module to control visibility with integrations for objects, fields etc., and it also works great together with the CanCan integration provided by GraphQL::Pro.

Thanks for the help!
