### ISSUE TITLE
Error message doesn't show for invalid cursor that has 8 characters

### ISSUE THREAD

**Issue by olichka12** [rmosolgo/graphql-ruby#3010]
I have two different cursors for example:
`{
      "cursor": "AB"
   },
   {
      "cursor": "Ac"
   }`
If cursor 'before' or 'after' has invalid value less than 8 or more than 8 characters it works fine and I have error message about this.  For example "message": "Invalid input: \"Abfffff\"" 

But when I try to set invalid cursor with 8 characters, the error message doesn't appear and I see all my data. It can be different characters but count should be 8.
`query {
    names(before:"12345678") {....}
}`

graphql version: 1.10.10

**Comment by rmosolgo** [comment]
😱 That's so wild. Thanks for the detailed bug report.

**Comment by rmosolgo** [comment]
I tried to replicate this error in 9ba5b6786, but it seemed to work for me. Does that test match your scenario? 

To debug further, could you please share: 

- Are you using the new pagination system (`use GraphQL::Pagination::Connections` in your schema)? 
- Are you using graphql-pro, and if so, what version?

**Comment by rmosolgo** [comment]
Please let me know if you can share a reproduction of this bug, or answer the questions above. I'd be happy to look into it further!
