### ISSUE TITLE
Unable to return nil or something different from rescue_from

### ISSUE THREAD

**Issue by gonzar11** [rmosolgo/graphql-ruby#3012]
Hello,
I am trying to rescue from RecordNotFound and return nil but instead the exception is raised. As I understood with #2139, this feature is already implemented, right?

`graphql` version: 1.10.9
`rails` version: 6.0.2

**GraphQL schema**

```ruby
class ApplicatinSchema < GraphQL::Schema
  query(Types::Query)
  mutation(Types::Mutation)

  use GraphQL::Execution::Errors

  rescue_from(ActiveRecord::RecordNotFound) do |_err, _obj, _args, _ctx, _field|
    nil
  end
end
```

Regards

**Comment by rmosolgo** [comment]
Yes, it should work, but as noted in https://graphql-ruby.org/errors/error_handling.html, it requires the new interpreter runtime (`use GraphQL::Execution::Interpreter` in your schema definition). Are you using that new feature?

**Comment by gonzar11** [comment]
Hello @rmosolgo I had forgotten to use the new interpreter runtime. Thank you!!
