### ISSUE TITLE
GraphQL Custom directive not part of execution

### ISSUE THREAD

**Issue by zyqxd** [rmosolgo/graphql-ruby#3016]
**Describe the bug**

Defined a custom directive using [docs here](https://graphql-ruby.org/type_definitions/directives). Cannot get the class methods `#include?` or `#resolve` to run

**Versions**

`graphql` version: 1.11.1
`rails` (or other framework): 6.0.3.2

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok).
Are you using [interpreter](https://graphql-ruby.org/queries/interpreter.html)? Any custom instrumentation, etc?

```ruby
class Directives::SomeTest < GraphQL::Schema::Directive
  description 'test'

  locations GraphQL::Schema::Directive::FIELD

  argument :key, String, required: true, description: 'test'

  def self.include?(obj, args, ctx)
     # no break
     debugger
  end

  def self.static_include?(a, b)
     # no break
    debugger
  end

  def self.resolve(obj, args, ctx)
    # no break
    debugger
  end
end

class MySchema < GraphQL::Schema
  directive Directives::SomeTest
  ...
end

```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
query {
  profiles(first: 3, after: $cursor) @someTest(key: 'profiles_connection' { 
    id 
    title 
  }
}
```

**Steps to reproduce**

- Build schema
- include `Directives::SomeTest`
- execute query

**Expected behavior**

any of the breakpoints to happen

**Actual behavior**

data is returned without hitting any breakpoint

**Additional context**

At one point I copied the `@skip` directive, renamed it and it, and put in a breakpoint. It still would not run.

**Comment by rmosolgo** [comment]
Hi, sorry about the hangup. Just to double-check, are you using the new Interpreter runtime (`use GraphQL::Execution::Interpreter` in your schema definition)? Custom directives are only enabled with that runtime.

**Comment by zyqxd** [comment]
> Hi, sorry about the hangup. Just to double-check, are you using the new Interpreter runtime (`use GraphQL::Execution::Interpreter` in your schema definition)? Custom directives are only enabled with that runtime.

Thanks for the quick reply.

Adding this worked
```ruby
use GraphQL::Analysis::AST
use GraphQL::Execution::Interpreter
```

Now I'm getting runtime schema issues on an argument that is passed in as `String!` and used for two field arguments, one is non-null and the other is nullable.

```
Type mismatch on variable $slug and argument forPage (String! / String)
```

This seems like a separate issue, but passing a non-null arg into something that is nullable should be fine right?

**Comment by zyqxd** [comment]
Side note: Would be nice to have a note in the `#directives` guide about the interpreter.

**Comment by zyqxd** [comment]
Should I open a new issue for the interpreter error I'm getting? @rmosolgo

**Comment by rmosolgo** [comment]
Sorry I missed that before. That can happen when there's a field using the old-style `types.String` (or `GraphQL::STRING_TYPE`) configuration, and another field is using new-style `String` or `GraphQL::Types::String` configuration. Unfortunately the runtime doesn't recognize that those are the same GraphQL types (they're different ruby objects). 

Check the configuration of those fields -- can either of them be updated to use `argument :..., String`?
