### ISSUE TITLE
Raise error when illegally adding an interface to a union

### ISSUE THREAD

**Issue by rusterholz** [rmosolgo/graphql-ruby#3018]
### Is your feature request related to a problem? Please describe.

I was trying (with gem version 1.10.9) to do something that turns out to be [invalid according to the GraphQL spec](http://spec.graphql.org/June2018/#sec-Unions), which is adding an interface as a member of a union:

```ruby
module MyInterface
  include GraphQL::Schema::Interface
end

class MyUnion < GraphQL::Schema::Union
  possible_types MyInterface, SomeOtherObject #, etc., ...
end
```

I didn't know this was invalid until a client (GraphiQL) started throwing schema validation errors. The gem accepted `MyInterface` as one of the `possible_types` just fine, and successfully built the schema and responded 200 to an introspection query. 

I considered filing this as a bug report, but AFAIK this is not necessarily behavior that the gem claims to define.

### Describe the solution you'd like

It might be nice for `possible_types` to raise an error when an interface is passed as one of its arguments.

### Describe alternatives you've considered

The other option I see would be to support this usage, but transparently decompose it when building the schema (that is, under the hood this would actually add all implementers of MyInterface as individual members of MyUnion). [This discussion of the reasoning](https://github.com/graphql/graphql-js/issues/451#issuecomment-234614808) behind the prohibition says this behavior "could be easily implemented as a helper method on the server that inlined all of the implementations of [the interface] into [the union]," so at least we know that such a behind-the-scenes implementation wouldn't necessarily violate the spec. 

However, I think you'd probably prefer to keep the gem simple, and raising an error is certainly simpler and less surprising (and probably more informative for folks who blunder into this like I did).

### Additional context

Note that this is **unrelated** to the [open RFC](https://github.com/graphql/graphql-spec/issues/518) about if/how unions could _implement_ interfaces (the converse of the relationship I attempted).

**Comment by rmosolgo** [comment]
Sorry about the hangup and thanks for the suggestion. I've pushed a patch with a validation like that in https://github.com/rmosolgo/graphql-ruby/pull/3024!
