### ISSUE TITLE
query logging

### ISSUE THREAD

**Issue by quinn-freshly** [rmosolgo/graphql-ruby#3019]
it would be great to have information about queries logged. not values in the response but the fields that were requested

**Comment by quinn-freshly** [comment]
Especially log if a field with a deprecation reason is used.

**Comment by rmosolgo** [comment]
👋 Hey, thanks for the suggestions. 

For deprecated fields, you might hook up the [`FieldUsage` analyzer](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/analysis/ast/field_usage.rb) which is included in this gem. You could make a subclass and override `def result` to handle the list of deprecated fields in the incoming query: 

https://github.com/rmosolgo/graphql-ruby/blob/9c4b7ebbdcbd32885a80bc813a50fd12e1817e14/lib/graphql/analysis/ast/field_usage.rb#L19-L24

You can find more details about hooking up analyzers in the guide: https://graphql-ruby.org/queries/ast_analysis.html

As for more detailed logging, have you taken a look at [Shopify's graphql-metrics](https://github.com/Shopify/graphql-metrics) project? I haven't used it, but I know Shopify uses it extensively.

Let me know if you run into any trouble with those!
