### ISSUE TITLE
undefined method `loads' for #<GraphQL::Argument:0x00007fc396407d18>

### ISSUE THREAD

**Issue by farahharis** [rmosolgo/graphql-ruby#3020]
Hello 👋🏼, 

I am trying to implement GraphQL Subscription inside my project. Long short story, I want to let a channel receives only new message that's created inside a channel. From my understanding, I should pass ID of the channel of the new message. Right now, I am having problem to pass argument channel_id to my subscription. I am having this error `undefined method 'loads' for #<GraphQL::Argument:0x00007fc396407d18>`. 
Below is my code: 

_**app/graphql/types/subscription_type.rb**_

```ruby
module Types
 SubscriptionType = GraphQL::ObjectType.define do
      name 'SubscriptionType'
      field :new_message_added, Types::MessageType do
        argument :channel_id, types.ID
      end
      def new_message_added(channel_id:)
        object
      end
      field :message_updated, Types::MessageType 
      field :message_deleted, Types::MessageType 
      field :new_channel_added, Types::ChannelType  
    end
end

### Trigger function is called inside Message model during after_create callback
MySchema.subscriptions.trigger(:new_message_added,{ channel_id: channel_id },self)

```
The subscription is working fine if I don't include the argument inside trigger function but all channel will subscribe every time a new message is added. Any help would be so much appreciated 😇

**Comment by rmosolgo** [comment]
Sorry about the hangup! Could you please share the full backtrace of the error you encountered? 

It sounds like part of the subscription system _assumes_ people use class-based GraphQL schemas, but you're still using `.define`, so there's some broken compatibility there. The backtrace will point us to where that bug is.

**Comment by farahharis** [comment]
> Sorry about the hangup! Could you please share the full backtrace of the error you encountered?
> 
> It sounds like part of the subscription system _assumes_ people use class-based GraphQL schemas, but you're still using `.define`, so there's some broken compatibility there. The backtrace will point us to where that bug is.

Hi there, thanks for the fast response! Sorry for the late reply. Here's the backtrace: 
`undefined method `loads' for #<GraphQL::Argument:0x00007ffa2559b380>
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/subscriptions.rb:216:in `block in normalize_arguments'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/subscriptions.rb:205:in `each'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/subscriptions.rb:205:in `normalize_arguments'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/subscriptions.rb:66:in `trigger'
/Users/macbook/kingpin-backend/app/models/message.rb:10:in `after_create'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:236:in `block in halting_and_conditional'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:517:in `block in invoke_after'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:517:in `each'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:517:in `invoke_after'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:133:in `run_callbacks'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:816:in `_run_create_callbacks'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.2/lib/active_record/callbacks.rb:346:in `_create_record'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.2/lib/active_record/timestamp.rb:102:in `_create_record'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.2/lib/active_record/persistence.rb:705:in `create_or_update'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.2/lib/active_record/callbacks.rb:342:in `block in create_or_update'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:132:in `run_callbacks'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:816:in `_run_save_callbacks'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.2/lib/active_record/callbacks.rb:342:in `create_or_update'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.2/lib/active_record/persistence.rb:308:in `save!'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.2/lib/active_record/validations.rb:52:in `save!'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.2/lib/active_record/transactions.rb:315:in `block in save!'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.2/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/database_statements.rb:265:in `transaction'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.2/lib/active_record/transactions.rb:212:in `transaction'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.2/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.2/lib/active_record/transactions.rb:315:in `save!'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.2/lib/active_record/suppressor.rb:48:in `save!'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.2/lib/active_record/associations/collection_association.rb:375:in `insert_record'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.2/lib/active_record/associations/has_many_association.rb:36:in `insert_record'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.2/lib/active_record/associations/collection_association.rb:362:in `block (2 levels) in _create_record'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.2/lib/active_record/associations/collection_association.rb:458:in `replace_on_target'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.2/lib/active_record/associations/collection_association.rb:283:in `add_to_target'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.2/lib/active_record/associations/collection_association.rb:361:in `block in _create_record'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.2/lib/active_record/associations/collection_association.rb:135:in `block in transaction'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/Users/macbook/.rvm/rubies/ruby-2.5.7/lib/ruby/2.5.0/monitor.rb:235:in `mon_synchronize'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.2/lib/active_record/transactions.rb:212:in `transaction'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.2/lib/active_record/associations/collection_association.rb:134:in `transaction'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.2/lib/active_record/associations/collection_association.rb:359:in `_create_record'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.2/lib/active_record/associations/has_many_association.rb:124:in `_create_record'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.2/lib/active_record/associations/association.rb:194:in `create!'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.2/lib/active_record/associations/collection_proxy.rb:366:in `create!'
/Users/macbook/kingpin-backend/app/graphql/types/mutation_type.rb:399:in `block (3 levels) in <top (required)>'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/field.rb:136:in `resolve'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/execution/execute.rb:321:in `call'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/schema/middleware_chain.rb:49:in `invoke_core'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/schema/middleware_chain.rb:38:in `invoke'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/execution/execute.rb:129:in `block in resolve_field'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/tracing.rb:67:in `block in trace'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/tracing.rb:81:in `call_tracers'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/tracing.rb:67:in `trace'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/execution/execute.rb:128:in `resolve_field'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/execution/execute.rb:92:in `block in resolve_selection'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/execution/execute.rb:85:in `each'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/execution/execute.rb:85:in `resolve_selection'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/execution/execute.rb:56:in `block in resolve_root_selection'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/tracing.rb:67:in `block in trace'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/tracing.rb:81:in `call_tracers'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/tracing.rb:67:in `trace'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/execution/execute.rb:49:in `resolve_root_selection'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/execution/execute.rb:31:in `begin_query'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/execution/multiplex.rb:113:in `begin_query'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/execution/multiplex.rb:84:in `block in run_as_multiplex'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/execution/multiplex.rb:83:in `map'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/execution/multiplex.rb:83:in `run_as_multiplex'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/execution/multiplex.rb:62:in `block (2 levels) in run_queries'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/execution/multiplex.rb:196:in `block in instrument_and_analyze'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/execution/multiplex.rb:175:in `instrument_and_analyze'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/execution/multiplex.rb:61:in `block in run_queries'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/tracing.rb:67:in `block in trace'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/tracing.rb:81:in `call_tracers'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/tracing.rb:67:in `trace'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/execution/multiplex.rb:59:in `run_queries'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/execution/multiplex.rb:49:in `run_all'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/schema.rb:435:in `block in multiplex'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/schema.rb:1947:in `with_definition_error_check'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/schema.rb:434:in `multiplex'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/schema.rb:411:in `execute'
/Users/macbook/kingpin-backend/app/controllers/graphql_controller.rb:19:in `execute'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/actionpack-5.2.4.2/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/actionpack-5.2.4.2/lib/abstract_controller/base.rb:194:in `process_action'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/actionpack-5.2.4.2/lib/action_controller/metal/rendering.rb:30:in `process_action'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/actionpack-5.2.4.2/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/react-rails-2.6.1/lib/react/rails/controller_lifecycle.rb:31:in `use_react_component_helper'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:136:in `run_callbacks'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/actionpack-5.2.4.2/lib/abstract_controller/callbacks.rb:41:in `process_action'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/actionpack-5.2.4.2/lib/action_controller/metal/rescue.rb:22:in `process_action'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/actionpack-5.2.4.2/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:168:in `block in instrument'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:168:in `instrument'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/actionpack-5.2.4.2/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/actionpack-5.2.4.2/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.2/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/actionpack-5.2.4.2/lib/abstract_controller/base.rb:134:in `process'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/actionview-5.2.4.2/lib/action_view/rendering.rb:32:in `process'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/actionpack-5.2.4.2/lib/action_controller/metal.rb:191:in `dispatch'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/actionpack-5.2.4.2/lib/action_controller/metal.rb:252:in `dispatch'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/actionpack-5.2.4.2/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/actionpack-5.2.4.2/lib/action_dispatch/routing/route_set.rb:34:in `serve'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/actionpack-5.2.4.2/lib/action_dispatch/journey/router.rb:52:in `block in serve'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/actionpack-5.2.4.2/lib/action_dispatch/journey/router.rb:35:in `each'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/actionpack-5.2.4.2/lib/action_dispatch/journey/router.rb:35:in `serve'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/actionpack-5.2.4.2/lib/action_dispatch/routing/route_set.rb:840:in `call'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/warden-1.2.8/lib/warden/manager.rb:36:in `block in call'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/warden-1.2.8/lib/warden/manager.rb:34:in `catch'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/warden-1.2.8/lib/warden/manager.rb:34:in `call'
/Users/macbook/.rvm/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/tempfile_reaper.rb:15:in `call'
/Users/macbook/.rvm/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/etag.rb:27:in `call'
/Users/macbook/.rvm/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/conditional_get.rb:40:in `call'
/Users/macbook/.rvm/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/head.rb:12:in `call'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/actionpack-5.2.4.2/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/Users/macbook/.rvm/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:266:in `context'
/Users/macbook/.rvm/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:260:in `call'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/cookies.rb:670:in `call'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activerecord-5.2.4.2/lib/active_record/migration.rb:559:in `call'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:98:in `run_callbacks'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/executor.rb:14:in `call'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/web-console-3.7.0/lib/web_console/middleware.rb:135:in `call_app'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/web-console-3.7.0/lib/web_console/middleware.rb:30:in `block in call'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/web-console-3.7.0/lib/web_console/middleware.rb:20:in `catch'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/web-console-3.7.0/lib/web_console/middleware.rb:20:in `call'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/railties-5.2.4.2/lib/rails/rack/logger.rb:38:in `call_app'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/railties-5.2.4.2/lib/rails/rack/logger.rb:26:in `block in call'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/tagged_logging.rb:28:in `tagged'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/tagged_logging.rb:71:in `tagged'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/railties-5.2.4.2/lib/rails/rack/logger.rb:26:in `call'
/Users/macbook/.rvm/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:13:in `call'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/Users/macbook/.rvm/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/method_override.rb:24:in `call'
/Users/macbook/.rvm/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.4.2/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/executor.rb:14:in `call'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/static.rb:127:in `call'
/Users/macbook/.rvm/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/railties-5.2.4.2/lib/rails/engine.rb:524:in `call'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/puma-3.12.4/lib/puma/configuration.rb:227:in `call'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/puma-3.12.4/lib/puma/server.rb:675:in `handle_request'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/puma-3.12.4/lib/puma/server.rb:476:in `process_client'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/puma-3.12.4/lib/puma/server.rb:334:in `block in run'
/Users/macbook/.rvm/gems/ruby-2.5.7/gems/puma-3.12.4/lib/puma/thread_pool.rb:135:in `block in spawn_thread'`

**Comment by farahharis** [comment]
**UPDATE**:

Hello, while waiting for your response, I was playing around with the file from the backtrace above. I removed `.loads` inside `_/.rvm/gems/ruby-2.5.7/gems/graphql-1.10.5/lib/graphql/subscriptions.rb_` and I finally can subscribe messages in a specific channel. Here are the screenshots: 

![image](https://user-images.githubusercontent.com/47730957/87514907-933b4b80-c6ad-11ea-9c3f-53b0e4e1f7e4.png)

![image](https://user-images.githubusercontent.com/47730957/87514950-a64e1b80-c6ad-11ea-8e47-b38753a8c3dd.png)

**Comment by farahharis** [comment]
@rmosolgo Hello, any updates on this?

**Comment by rmosolgo** [comment]
Sorry I haven't had time to address this. I think it's time to admit that I can't get to it. The fix would be to migrate `SubscriptionType` to a class-based definition. I would accept a PR to the library to improve the compatibility here, but I don't have the bandwidth to replicate the issue with a test then find a fix. Sorry! 

If you try the migration to a class-based type and run into trouble, please open a new issue. I'd be happy to help with that migration, since class-based will be the only supported type definition in a future graphql-ruby version.
