### ISSUE TITLE
Pundit + Subscriptions, Unexpected role checks

### ISSUE THREAD

**Issue by rgraff** [rmosolgo/graphql-ruby#3022]
**Describe the bug**

When using Pundit and Subscriptions, the policy is checked against the BaseObject's pundit_role and the object's pundit_role. I would expect it to only be checked only against the object's.

**Versions**

ruby 2.6.6
rails 6.0.3
graphql-pro 1.14.0

**GraphQL schema**

For example, given a BaseObject with `pundit_role :admin`

```
module GraphQL
    module Types
      class BaseObject < GraphQL::Schema::Object
        include GraphQL::Pro::PunditIntegration::ObjectIntegration
        pundit_role :admin

        field_class Types::BaseField
      end
    end
  end
end
```

And another object with `pundit_role :anyone`

```
module GraphQL
  module Types
      class ReactionType < Base::Types::BaseObject
        pundit_role :anyone
        
        field :id, ID , null: false
        field :message, String, null: true
      end
  end
end
```

and a subscription.... 

```
module GraphQL
    module Subscriptions
      class ReactionAdded < Base::Subscription
        field :reactions, [Types::ReactionType], null: true

        def subscribe
          { reactions: [] }
        end

        def update
          { reactions: [object] }
        end
    end
  end
end
```

**Steps to reproduce**

When the subscriptions is triggered the `ReactionPolicy` receives `admin?` and then `anyone?`. 

**Expected behavior**

I would expect it to only receive `anyone?`

**Comment by rmosolgo** [comment]
Hey, thanks for the detailed report and sorry for the hangup. 

I suspect this is because you also have a `Types::SubscriptionType`that inherits from `Base::Types::BaseObject`. Is that true? 

If so, then `Types::SubscriptionType` is applying the `admin?` check, which it inherited from `BaseObject`. You can override that with `pundit_role nil` in `SubscriptionType`'s class definition. 

If that doesn't fix it, could you share the source of your subscription root type?

**Comment by rgraff** [comment]
@rmosolgo Setting pundit_role to nil in my SubscriptionType definition fixes the issue. Thanks!

I do think this is still unexpected behavior because the (inherited) role requirement for the subscription was queried against the ReactionPolicy.  It would make sense if it was applied to a SubscriptionPolicy.  The ReactionType does not inherit from the SubscriptionType.
