### ISSUE TITLE
handle unauthorized objects differently in mutations vs queries

### ISSUE THREAD

**Issue by stevecrozz** [rmosolgo/graphql-ruby#3023]
**Is your feature request related to a problem? Please describe.**

I like the default nil replacement behavior for unauthorized objects for queries, but within the context of a mutation, especially on a required field, the response should include some kind of error.

In this example, I have a mutation which uses `argument loads: Types::Document` to load my argument. It successfully runs my Schema's `object_from_id` class method and finds the Document object.

We get to https://github.com/rmosolgo/graphql-ruby/blob/v1.11.1/lib/graphql/schema/member/has_arguments.rb#L192 where we call `authorized?` on my loaded object. But when the object's own `authorized?` method returns false, we handle it by calling the Schema's `unauthorized_object` class method which returns nil. Now that's great for queries, but for when it happens in a mutation for a required argument, that seems like information we should return back to the user.

Request:
~~~graphql
mutation { 
  documentRename(name: "foo", documentId: "ODpEb2N1bWVudDVmMDQ5Zjg5YzhlOGQzNGM1NjQ1OGZhOQ==") {
    document { id name }
  }
}
~~~

Response:
~~~json
{
  "data": {
    "documentRename": null
  }
}
~~~

~~~ruby
module Mutations
  class DocumentRename < Mutations::BaseMutation
    argument :document_id, ID, required: true, loads: Types::Document
    argument :name, String, required: true
    field :document, Types::Document, null: true
  end
end
~~~

**Describe the solution you'd like**

I'm not sure exactly what to suggest, but if a mutation's required argument can't be loaded, I think we need to be able to present that error back to the requester.

**Describe alternatives you've considered**

I tried implementing an `authorized?` class method on my BaseObject that guards with `return true if context.query.mutation?` in order to bypass authorization on objects during a mutation, delegating authorization to the mutation's own `authorized?` method. But this by itself is not good because it then also disables authorization on the values returned by the mutation.

**Comment by rmosolgo** [comment]
> if a mutation's required argument can't be loaded, ... present that error back to the requester.

Thanks for the detailed writeup, and I agree, that would be a great feature! I know that arguments would benefit from a slew of "rails-y" validators, but I haven't had the bandwidth to implement them yet 😖 

In the meantime, the best work-around is to check manually in resolve, eg 

```ruby 
def resolve(document: nil)
  if document.nil? # Although this argument is required, it could return `nil` if the `loads:` lookup failed 
    raise GraphQL::Error, "No document found for documentId"
  end 
  # ...
end 
```

**Comment by alexkalderimis** [comment]
We would love the same thing - we override `unauthorized_object` to provide this behavior at GitLab, but would love to see a cleaner way to do this.

**Comment by rmosolgo** [comment]
I've got a patch in the works that will add Resolver-specific (and Mutation-specific, since mutations are resolvers) `def unauthorized_object` hooks for this scenario. It'll also add docs for that hook and the existing, but undocumented, `load_application_object_failed` hook! #3689

**Comment by stevecrozz** [comment]
Very cool @rmosolgo !
