### ISSUE TITLE
GraphQL::Backtrace not working with GraphQL::Execution::Interpreter / GraphQL::Analysis::AST

### ISSUE THREAD

**Issue by 23tux** [rmosolgo/graphql-ruby#3026]
**Describe the bug**

When I use `GraphQL::Execution::Interpreter` and `GraphQL::Analysis::AST` in my schema, I don't get a proper backtrace from `GraphQL::Backtrace` when an error occurs.

**Versions**
`graphql` version: 1.10.10
`rails` (or other framework): 5.5.2.4.3

**GraphQL schema**
```ruby
class Schema < GraphQL::Schema
  use GraphQL::Execution::Interpreter
  use GraphQL::Analysis::AST
  query Queries
  use GraphQL::Backtrace
end
```

**GraphQL query**

```graphql
query {
  blok { _json }
}
```

```json
{
  "error": {
    "errors": [
      {
        "message": "no implicit conversion of Hash into String",
        "locations": [],
        "extensions": {
          "error_class": "TypeError",
          "status": "internal_server_error"
        }
      }
    ]
  }
}
```

**Steps to reproduce**

Add `GraphQL::Backtrace`, `GraphQL::Execution::Interpreter` and `GraphQL::Analysis::AST` to your schema and trigger a query that results in a Ruby error.

**Expected behavior**

A formatted stacktrace that provides information where the error happened, like this:

```
{
  "error": {
    "errors": [
      {
        "message": "Unhandled error during GraphQL execution:\n\n  no implicit conversion of Hash into String\n    /usr/local/bundle/gems/json-2.3.0/lib/json/common.rb:156:in `initialize'\n    /usr/local/bundle/gems/json-2.3.0/lib/json/common.rb:156:in `new'\n    /usr/local/bundle/gems/json-2.3.0/lib/json/common.rb:156:in `parse'\n    /usr/src/app/app/lib/graphql/bloks/blok_queries.rb:16:in `block in blok'\n    /usr/src/app/app/lib/graphql/promise_mutator.rb:20:in `wait'\n    /usr/local/bundle/gems/promise.rb-0.7.4/lib/promise.rb:80:in `sync'\n    /usr/local/bundle/gems/graphql-1.10.10/lib/graphql/schema.rb:123:in `public_send'\n    /usr/local/bundle/gems/graphql-1.10.10/lib/graphql/schema.rb:123:in `sync_lazy'\n    /usr/local/bundle/gems/graphql-1.10.10/lib/graphql/schema.rb:107:in `block in after_lazy'\n    /usr/local/bundle/gems/graphql-1.10.10/lib/graphql/execution/lazy.rb:41:in `value'\n    ... and 147 more lines\n\nUse #cause to access the original exception (including #cause.backtrace).\n\nGraphQL Backtrace:\nLoc  | Field        | Object | Arguments               | Result\n2:3  | Queries.blok | nil    | {\"slug\"=>\"wochenmarkt\"} | #<TypeError: no implicit conversion of Hash into String>\n1:1  | query        | nil    | {}                      | {blok: (unresolved)}\n\n",
        "locations": [],
        "extensions": {
          "error_class": "GraphQL::Backtrace::TracedError",
          "status": "internal_server_error"
        }
      }
    ]
  }
}
```

**Actual behavior**

Just the error message, no backtrace.

```
no implicit conversion of Hash into String
```

**Additional context**

When I remove `GraphQL::Execution::Interpreter` and `GraphQL::Analysis::AST` I get a proper backtrace.

**Comment by rmosolgo** [comment]
The PR I linked to earlier made the _error_ go away, but it still doesn't render a useful backtrace. 

I spent some time trying to update it to work with the interpreter, but it didn't _just work_. Anyways, I'll reopen this to track adding that behavior some other way.

**Comment by rmosolgo** [comment]
v1.12.0 has an updated `Backtrace` plugin that works with the interpreter. In fact, you have to add `use GraphQL::Backtrace, legacy: true` to make it continue to work with the old runtime. (The old runtime is marked deprecated in 1.12.0.) 

Please open a new issue if you run into trouble with it on 1.12.0, thanks again for reporting this!
