### ISSUE TITLE
Extend GraphQL::Language::Visitor with schema

### ISSUE THREAD

**Issue by 23tux** [rmosolgo/graphql-ruby#3037]
**Is your feature request related to a problem? Please describe.**

We are using GraphQL both for our public API and from within Ruby to fetch data, build views etc. I've come to notice a pattern, that when using `GraphQL::Language::Visitor`, I often need more information about a node from the actual schema, e.g. if a specific type is given, I'd like to inject a field into the query, or if the field is a list of objects, I'm preparing a datastore based on the selected fields where the response would be put in...

**Describe the solution you'd like**

`GraphQL::Language::Visitor` should get an optional, second argument, where you can define the schema that is used:

```
GraphQL::Language::Visitor.new(doc, schema)
```

The `node` and `parent` arguments in the `on_node` hook would then have more information from the actual schema:

```
def on_field(node, parent)
  node.field # <-- would be an instance of GraphQL::Schema::Field
  super
end
```

**Describe alternatives you've considered**

For now, I'm doing it with an introspection query:
I'm storing the path from my current node to the root (called `breadcrumbs`), and later you can use those breadcrumbs to look into the result of an introspection query, what field from the schema was used:

```
class AnnotateQuery < GraphQL::Language::Visitor
  def on_field(node, parent)
    define_parent(node, parent)
    define_breadcrumbs(node)
    super
  end

  private def define_parent(node, parent_node)
    node.define_singleton_method(:parent) do
      parent_node if parent_node.is_a?(GraphQL::Language::Nodes::Field)
    end
  end

  private def define_breadcrumbs(node)
    node.define_singleton_method(:breadcrumbs) do
      crumbs = [node = self]
      crumbs.push(node) while node = node.parent
      crumbs.reverse
    end
  end
end
```

```
doc = GraphQL.parse(query)
AnnotateQuery.new(doc).visit

introspection = Introspection.for(MySchema)
doc.selections.each do |node|
  type = introspection.find_type(node.breadcrumbs)
  # => this returns actual type information from MySchema
end
```

**Comment by rmosolgo** [comment]
Hey, great question. I've also wondered the best way to mix schema-related concerns with AST. Lately, I've been using the new "AST Analysis" system: https://graphql-ruby.org/queries/ast_analysis.html

Have you given that a try? If you check the tests, you'll see how you can run it _apart_ from normal execution: 

https://github.com/rmosolgo/graphql-ruby/blob/a1df05cf467aefc97d96ef4990b917e861807a11/spec/graphql/analysis/ast_spec.rb#L138-L149

**Comment by 23tux** [comment]
That looks very promising, thanks!

**Comment by 23tux** [comment]
@rmosolgo I just tried it out and it works for fields, arguments... But it seems not to work for variables:

```
class MyQueries < Graphql::Types::BaseObject
  field :article, String, null: false do
    argument :id, String, required: true
  end
end

class MySchema < GraphQL::Schema
  query MyQueries
end

class MyAnalyzer < GraphQL::Analysis::AST::Analyzer
  def on_enter_variable_identifier(node, parent, visitor)
    binding.pry
  end

  def on_enter_variable_definition(node, parent, visitor)
    binding.pry
  end

  def result
    nil
  end
end

query_string = %(query($id: ID!) { article(id: $id) })
query = GraphQL::Query.new(MySchema, query_string, variables: { id: "FOOBAR" })
GraphQL::Analysis::AST.analyze_query(query, [MyAnalyzer])
```

When you copy-paste this code you'll see that `on_enter_variable_identifier` and `on_enter_variable_definition` are never called.

Am I doing something wrong?

**Comment by 23tux** [comment]
I just stumbled upon another question: How would you change the selection of a query with `GraphQL::Analysis::AST::Analyzer`? I tried 

```
def on_enter_field(node, parent, visitor)
  node = node.merge_selection(name: "foobar") if visitor.field_definition.type.unwrap == MyCustomType
  super(node, parent, visitor)
end

def result
  query.query_string # <-- this is still the old query
  @result
end
```

but this does not seem to change the query itself. Is there a way to do this?

**Comment by rmosolgo** [comment]
Ah, yeah, analyzers don't modify the AST, sorry 😖 . You might find the source of `Analysis::AST::Visitor` interesting because it adds schema/type information to the visitor: https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/analysis/ast/visitor.rb

You might be able to use that kind of logic in your code. If you find something generally useful, please share your results! Maybe we could add something like that to GraphQL-Ruby.

**Comment by 23tux** [comment]
Sorry to bother you again: I had a look into it, but I can't get it to work with `GraphQL::Analysis::AST::Visitor`:

```
class MyQueries < Graphql::Types::BaseObject
  field :article, String, null: false
end

class MySchema < GraphQL::Schema
  query MyQueries
end

class MyAnalyzer < GraphQL::Analysis::AST::Visitor
  def on_field(node, parent)
    node = node.merge_selection(name: "foobar") if node.name=="article"
    super(node, parent)
  end
end

query_string = %(query { article { title } })
query = GraphQL::Query.new(MySchema, query_string)
puts MyAnalyzer.new(query: query, analyzers: []).visit.to_query_string
```

I would expect this output:

```
query {
  article {
    title
    foobar
  }
}
```

but I'm getting
```
query {
  article {
    title
  }
}
```

Am I doing something wrong?

And could you have a look at this too? https://github.com/rmosolgo/graphql-ruby/issues/3037#issuecomment-663431419 It seems like it's not working for variables.

**Comment by rmosolgo** [comment]
Sorry that visitor doesn't work in this case 😖 Personally, I think the best thing would be either: 

- If there's anything useful in that class, copy it into your own app to use for this purpose;
- Or, extract the schema/type information part of that visitor and roll it into a new class in the gem that _works_ for what you're trying to do; Update the existing class to inherit from the new one. (In that case, it improves graphql-ruby's built-in support for your use case.) 


Regarding variables, that's right, analyzers don't visit variables. When I recommended AST analysis, I thought you were trying to make some calculation based on incoming queries. I didn't understand you were trying to make detailed modifications to the AST. Sorry that my recommendation missed the mark!

**Comment by 23tux** [comment]
Ok, I'll have a deeper look into the class and will try a few things. It seems if I change the return value of the `on_*` methods to the one from the base class `GraphQL::Language::Visitor` that is called via `super` it could work. I'll let you know if I've found something.

Variables: That seems strange, as the class `GraphQL::Analysis::AST::Analyzer` implements those methods. Is there a reason?
