### ISSUE TITLE
Query type could not be resolved to Union Type

### ISSUE THREAD

**Issue by abhinaykumar** [rmosolgo/graphql-ruby#3046]
Hi, I have recently started working with `Graphql-ruby`(1.8.0.pre6 version) so pardon for my question if the solution looks trivial. Also, I'm using `graphql-sugar` on top of it.

I'm trying to implement a search functionality using `UnionType`. Not sure what am I missing here but when I make a request using the query:

```ruby
query Search($queryString: String!, $scope: String!, $projectId: ID!){
    search(queryString: $queryString, scope: $scope, projectId: $projectId) {
        ... on Entity {
            __typename
            id
            name
        }
        ... on Record {
            __typename
            id
        }
    }
}
```
It returns an error like this:
```ruby
GraphQL::UnresolvedTypeError in GraphqlController#execute

The value from "search" on "Query" could not be resolved to "SearchResultUnion". (Received: `nil`, Expected: [Entity, Record]) Make sure you have defined a `type_from_object` proc on your schema and that value `#<ActiveRecord::Relation [#<Entity id: 4, project_id: 2, name: "new_image", label: "New Image".....>]>` gets resolved to a valid type.
```
Query and Union Type looks like below:

```ruby
module Types
  class SearchResultUnionType < BaseUnionType
    possible_types EntityType, RecordType

    def self.resolve_type(_abstract_type, object, _context)
      case object.klass
      when Entity then EntityType
      when Record then RecordType
      else
        raise 'Unknown search result type'
      end
    end
  end
end
```
```ruby
module Types
  class EntityType < ApplicationType
    :
  end
end
```

```ruby
module Types
  class RecordType < ApplicationType
    :
  end
end

```
```ruby
class SearchResolver < ApplicationResolver
  parameter :queryString, !types.String
  parameter :scope, !types.String
  parameter :projectId, !types.ID

  type Types::SearchResultUnionType

  def resolve
    Search.scope(
      query: params[:query_string],
      scope: params[:scope],
      project_id: params[:project_id]
    )
  end
end
```

```ruby
module Roots
  class QueryType < GraphQL::Schema::Object
    include GraphQL::Sugar::Query
    resolver :search
  end
end
```

```ruby
class MySchema < GraphQL::Schema
  query Roots::QueryType
  mutation Roots::MutationType

  def self.resolve_type(abstract_type, object, context)
  end
end
```

**Comment by rmosolgo** [comment]
It's failing to resolve your union for two reasons: 

- Your schema's `def self.resolve_type` always returns `nil` because it has no implementation. 
- The `search` field returned an ActiveRecord::Relation, but it's configured to return a single object (`type Types::SearchResultUnionType`)

To address these: 

- Add a body to `def self.resolve_type` to handle incoming values 
- Update your search resolver to return a list type (`type [Types::SearchResultUnionType]`), since the field returns an active record relation 

Let me know if you have trouble after that!

**Comment by abhinaykumar** [comment]
Hi @rmosolgo , thank you so much for the response and apologies if this is not the right place to ask these questions. I did override the `resolve_type` inside `SearchResultUnionType`, Do I need to do something at the schema level as well? Also, 
tried this:
```ruby
class SearchResolver < ApplicationResolver
  parameter :queryString, !types.String
  parameter :scope, !types.String
  parameter :projectId, !types.ID

  type Types::SearchResultUnionType.to_list_type

  def resolve
    parent = resolved_object || Project.find(params[:project_id])
    authorize! parent, :view_entities?

    Search.scope(
      query: params[:query_string],
      scope: params[:scope],
      project_id: params[:project_id]
    )
  end
end
```
but it throws the same error except for this time it says `[SearchResultUnion]`.
```ruby
The value from "search" on "Query" could not be resolved to "[SearchResultUnion]". (Received: `nil`, Expected: [Entity, Record]) Make sure you have defined a `type_from_object` proc on your schema and that value `#<Entity id: 4, project_id: 2, name: "new_image", label: "New Image"...>` gets resolved to a valid type.
```

**Comment by abhinaykumar** [comment]
Also, doing this: `type [Types::SearchResultUnionType]` throws an error:

```ruby
GraphQL::Schema::InvalidTypeError in GraphqlController#execute

Query is invalid: field "search" type must return GraphQL::BaseType, not Array ([Types::SearchResultUnionType])
```

**Comment by rmosolgo** [comment]
Sorry, 1.8.0 is very old, I guess I forgot the API for that version! 🙈 

Yeah, it seems like the next thing is to address this part of the error message you received: 

> Make sure you have defined a `type_from_object` proc on your schema and that value `#<Entity id: 4, project_id: 2, name: "new_image", label: "New Image"...>` gets resolved to a valid type.

I don't remember exactly what that method is called in 1.8.0, you could try browsing the source/guides for that version to see if you can find an example: https://github.com/rmosolgo/graphql-ruby/tree/v1.8.0.pre6

**Comment by abhinaykumar** [comment]
Yeah, the closest thing I found while googling was this: 
```ruby
# File 'lib/graphql/relay/monkey_patches/definition_config.rb', line 23

def type_from_object(proc)
  @type_from_object_proc = proc
end
```
```ruby
# File 'lib/graphql/relay/global_node_identification.rb', line 77

def type_from_object(object)
  type_result = @type_from_object_proc.call(object)
  if !type_result.is_a?(GraphQL::BaseType)
    type_str = "#{type_result} (#{type_result.class.name})"
    raise "type_from_object(#{object}) returned #{type_str}, but it should return a GraphQL type"
  else
    type_result
  end
end
```
```ruby
# File 'lib/graphql/relay/global_node_identification.rb', line 16

def type_from_object_proc=(value)
  @type_from_object_proc = value
end
```
tried adding them to the schema but same result. Can you please tell me if the code wise the implementation looks fine? If yes, then I'll try updating the gem version and see if it solves the problem.

**Comment by abhinaykumar** [comment]
I found the changelog files(https://github.com/rmosolgo/graphql-ruby/blob/daf2e6a87ee36460b7d3d2570bad845d96a4963c/CHANGELOG.md) and apparently, `type_from_object` has been deprecated in `0.19.0` version itself. Is there something else you think I can try?

**Comment by abhinaykumar** [comment]
just for the closure, I moved the `resolve_type` to MySchema as I realized it never reaches the UnionType level `resolve_type` and it worked like a charm. Thank you for all the help @rmosolgo and maintaining this gem.

**Comment by rmosolgo** [comment]
Glad you found something that works! Thanks for sharing your solution.
