### ISSUE TITLE
GraphQL::StaticValidation::VariablesAreUsedAndDefinedError with anonymous operation has no usage or declaration context in message

### ISSUE THREAD

**Issue by jhhb** [rmosolgo/graphql-ruby#3047]
**Is your feature request related to a problem? Please describe.**

When writing tests for my GraphQL queries, I noticed that if I received a `GraphQL::StaticValidation::VariablesAreUsedAndDefinedError` error when using an anonymous query, the error message would come back like so:

`Variable $undefinedVar is used by  but not declared` -- I expected to see some indication of what was using the variable similar to the behavior for named operations, rather than an extra space.

I then looked in the code and saw that this was the expected behavior for when `usage.used_by.name` is `nil`, as in the case of an anonymous operation, see: https://github.com/rmosolgo/graphql-ruby/blob/dda92abbbd9fdcddcbe65278a2301fbe3047004c/lib/graphql/static_validation/rules/variables_are_used_and_defined.rb#L143

**Describe the solution you'd like**

I would like some indication of what is using the variable, even if it is an unnamed query -- perhaps:
- `Variable $undefinedVar is used by query but not declared`
- `Variable $undefinedVar is used by anonymous query but not declared`

I would also like these semantics to be applied to cases where the variable is declared but not used.

**Describe alternatives you've considered**
- I've considered surfacing `anonymous <operation_type>` in the case where the operation is anonymous, so the original message would become:

`Variable $undefinedVar is used by anonymous query but not declared`

Extending this to the declared-but-not-used case, we also get:

`Variable $undefinedVar is declared by anonymous query but not used`

**Additional context (links to draft PR in my fork)**
- Draft PR against my fork with proposed changeset
  - https://github.com/jhhb/graphql-ruby/pull/1

**Comment by rmosolgo** [comment]
:+1: Thanks for the great error report. I totally agree with your suggested fixes, want to open a PR for this?

**Comment by jhhb** [comment]
👍 

Done: #3050
