### ISSUE TITLE
Multiple values for `resolve_type` and `node:`, best approach?

### ISSUE THREAD

**Issue by sayduck-daniel** [rmosolgo/graphql-ruby#3049]
We are trying to create multiple GraphQL Types that would be behind the same "model"
 
For example:

**app/model/user.rb**

```ruby
class User < ApplicationRecord
  # ...
  def hidden_value
    42
  end
end
```

**app/graphql/types/user_type.rb**
```ruby
module Types
  class UserType < BaseCustomObject
    field :email, String, null: false
    field :hidden_value, String, null: false
  end
end
```

**app/graphql/types/collaborator_type.rb**
```ruby
module Types
  class CollaboratorType < BaseCustomObject
    field :email, String, null: false
  end
end
```

**GraphQL**
```graphql
  query {
    node(id: "my-user-id") {
      ... on User { email, hiddenValue } # returns values
    }
  }

  query {
    node(id: "my-user-id") {
      ... on Collaborator { email } # returns { }
    }
  }
```

An user in our database, could be seen as a Collaborator or an User.

This code works when we would associated Collaborators within a defined field or a connection but won't work with code relying on `resolve_type` (see bellow for our resolve_type method)

**self.resolve_type**
```ruby
  def self.resolve_type(_type, object, _context)
    "Types::#{object.graphql_class_name}Type".safe_constantize
  end
```

What would be the best way to tell GraphQL that this record could be either a Collaborator or an User?

**Comment by swalkinshaw** [comment]
This is related (or maybe a duplicate) of https://github.com/rmosolgo/graphql-ruby/issues/1802

**Comment by rmosolgo** [comment]
>  #1802

It seems a _little_ different, though, since that issue (iirc) involves _different IDs_ loading the same object. In this case, it seems like the _same ID_ loading an object, then letting it be treated as either type. 

I think the GraphQL semantic for this case is an Interface type. In your context, why should User and Collaborator be separate? Why isn't there just one graphql object type? Are there objects that are Users but _not_ Collaborators? (Or, Collaborators but not Users?) Or, should/could Collaborator (or User?) be an interface type instead of an object type?

**Comment by sayduck-daniel** [comment]
Both point to the same rails ActiveRecord and therefore are the same DB object.

Depending on Who and Where we are using them, we return a different GraphQL Type:

- `UserType` is returned by mutations made by an authenticated user. He has therefore access to all his information.
    - authenticateUser
    - changePasswordWithToken
    - AccessTokenType

- `CollaboratorType` is returned by mutations and queries depending on an User but not in direct ownership. For example, I could list the users of my organisation. This would return me a collection of Collaborators for which I have limited visibility and access.
    - acceptCustomerInvitation
    - customer.collaborators

The idea was to have a different `authorized`:

- UserType: `context[:current_user] == object`
- CollaboratorType: `context[:current_user].customer.collaborators.include?(object)`

**Comment by sayduck-daniel** [comment]
(Now that I wrote it up, it looks like I should maybe only have a UserType and an `authorized?` on the field level)

**Comment by rmosolgo** [comment]
Yes, I agree that arrows point to having one type, with authorization-related behavior on sensitive fields. Another option would be to have a related type, eg, `ViewerInformation`, that returned `nil` unless the viewer was the same object as the user being returned.
