### ISSUE TITLE
Fields named after ruby Object methods get resolved to those methods on the resolver instance instead of on the actual object

### ISSUE THREAD

**Issue by jornvandebeek** [rmosolgo/graphql-ruby#3058]
EDIT: The analysis below was incomplete. `display` is a method on Object, so it's not just Hashes that show this problem. Furthermore, the `obj` in the `if obj.respond_to?(@resolver_method)` line is actually the resolver instance, not the object itself. 

-----------------
If you use a hash object and the field name you are trying to return is also the name of a method on Hash, that method gets called instead of the key value being returned.

An example is `display`, which is a method on hash that always returns nil after displaying the hash.

The order of checks in `public_send_field` makes the issue clear:
```ruby
if obj.respond_to?(@resolver_method)
...
elsif obj.object.is_a?(Hash)
...
  if inner_object.key?(@method_sym)
```

So any time a hash object also responds to one the keys inside of it, that method gets called instead of the key's value being retrieved.

There are quite a few methods on hash that would clash this way, and it seems unlikely it is ever the intended effect. In the `display` case, it is also hard to debug because it will not generate an error, but just resolve the field as `nil`. 

I suggest reversing the order of resolution, so the `is_a?(Hash)` resolution takes priority and the `respond_to?` resolution is second.

`graphql` version: 1.11.2

**Comment by rmosolgo** [comment]
:+1: Thanks for the detailed report, I agree that reordering those checks is a good fix. Want to take a try at it?

**Comment by jornvandebeek** [comment]
Actually, investigating some more, it seems the `:display` method makes a more complicated problem than I suggested. The case of most other regular hash keys being named after a hash method actually is resolved correctly.

`display` is defined on ruby's Object, so anything will respond to it. This makes the *resolver itself* respond to the field name:

From schena/field.rb
```
# obj here is a resolver_class instance, not the resolved object itself
if obj.respond_to?(@resolver_method)
# ... this branch is taken for `display`
elsif obj.object.is_a?(Hash)
elsif obj.object.respond_to?(@method_sym)
```

I am not sure about the how and why of resolving through the resolver instance itself. Maybe adding Object's method names to the ruby keywords is a better option?

**Comment by jornvandebeek** [comment]
I have not figured out a workaround. Using `resolver_method` in the field declaration to avoid a `respond_to(:display)` call on the resolver instance does not seem to help (still resolves as `nil`). I am unable to investigate further because my rubymine hangs on opening this repo.

**Comment by rmosolgo** [comment]
:+1:, `resolver_method:` is the workaround here. That's the recommended solution when a field conflicts with a Ruby built-in method, too: 

https://github.com/rmosolgo/graphql-ruby/blob/23032f37aac5252533c6c6209a7da9862961ebdc/lib/graphql/schema/member/has_fields.rb#L63

:+1: I think adding `Object`'s instance methods to `CONFLICT_FIELD_NAMES` (somehow) would be a good improvement: 

https://github.com/rmosolgo/graphql-ruby/blob/23032f37aac5252533c6c6209a7da9862961ebdc/lib/graphql/schema/member/has_fields.rb#L42-L56

**Comment by jornvandebeek** [comment]
The `resolver_method` solution did work out in the end. 

Looking at it more, I think having Hash key value resolution taking priority over using resolver methods is not advisable. It would make it impossible to use the resolver class for defining static defaults for hash fields while you could still use it that way for regular object fields. 

I have made an MR to add Object.instance_methods to CONFLICT_FIELD_NAMES. It surfaced an interesting case of the resolver/object confusion: https://github.com/rmosolgo/graphql-ruby/pull/3062

**Comment by jornvandebeek** [comment]
With the MR merged I think we can close the issue as resolved.
