### ISSUE TITLE
missing keyword arguments with required false

### ISSUE THREAD

**Issue by mmahalwy** [rmosolgo/graphql-ruby#3060]
Curious if there are any opinions on how to handle and avoid `ArgumentError: missing keyword:` for arguments that are not required. For example:
```ruby
class UpdateProfile < BaseMutation
    type Types::ProfileType

    argument :id, ID, required: true
    argument :live, String, required: false
    argument :verified, String, required: false
    argument :first_name, String, required: false
    argument :last_name, String, required: false
    argument :image_url, String, required: false

    def resolve(id:, first_name:, last_name:, image_url:, live:, verified:)
      Profile.update(id, {
        first_name: first_name,
        last_name: last_name,
        image_url: image_url,
        live: live,
        verified: verified,
      }.select { |key, value| value.present? })
    end
  end
```

This is a case where all the arguments in `resolve` need to be passed (even if `nil` on client or at least should default to `nil` on server) although according to graphql schema, they are not required. 

Any advice would be great!

**Comment by rmosolgo** [comment]
You have to provide a default value in Ruby, for example: 

```ruby 
-    def resolve(id:, first_name:, last_name:, image_url:, live:, verified:)
+     def resolve(id: nil, first_name: nil, last_name: nil, image_url: nil, live: nil, verified: nil)
```

Alternatively, you could use a `**` catch-all to catch any optional args: 

```
-     def resolve(id:, first_name:, last_name:, image_url:, live:, verified:)
+     def resolve(**kwargs)
```

(Then, check `kwargs.key?(...)` to determine which arguments were given.)

If the client doesn't provide an argument, then we don't pass any argument to `resolve`. That's how you can tell if the client provided an argument or not. (If you want to require an argument from the client, use `required: true` instead.) 

I hope one of those helps! Let me know if they don't work for some reason.
