### ISSUE TITLE
Overriding methods in GraphQL::Schema post 1.10. Breaking workaround for max_depth on introspection.

### ISSUE THREAD

**Issue by jhirn** [rmosolgo/graphql-ruby#3061]
Hi @rmosolgo. I used to work around the Introspection query max_depth (from this issue #2437) by implementing in my Schema, but upgrading from 1.9.19 to the anything past 1.10.0 it no longer works. 

```ruby
def as_json(only: nil, except: nil, context: {})
    execute(GraphQL::Introspection::INTROSPECTION_QUERY, only: only, except:
      except, context: context, max_depth: 13).to_h
  end
```

In fact, I can't seem to override any methods in the schema object. 

Putting a pry for execute or as_json it never gets called. I'm not sure what the proper way to upgrade my Schema definition. I've used Instrumentation to work around the inability to override `execute`, but not sure from the change log exactly what is going on. I'm sure there's a way but it's unclear after perusing the documents.

**Comment by rmosolgo** [comment]
Hi, great question! 

In 1.9.x, a lot of `Schema`'s methods were delegated to a singleton of the instance. However, in 1.10.x, those methods were re-implemented directly on the schema class. 

I think you could continue overriding those by moving the definition to the class, for example: 

```diff 
-  def as_json(only: nil, except: nil, context: {})
+  def self.as_json(only: nil, except: nil, context: {})
     execute(GraphQL::Introspection::INTROSPECTION_QUERY, only: only, except:
       except, context: context, max_depth: 13).to_h
   end
```

In short, this switch is part of moving graphql-ruby internals _away_ from the old `.define { ... }`-based APIs to class-based APIs. 

Does that work for you?

**Comment by jhirn** [comment]
🙏 thx for the response. I will try and report back.

**Comment by jhirn** [comment]
So `def self.execute` definitely works for me. I'm actually able to remove my Instrumentation class and hit a pry. Unfortunately, `def self.as_json` not hitting thje pry or setting the max_depth. I'm not too concerned with bumping up max_depth temporarily, but would love to have this working like before. Here is my entire Schema object for you 


```ruby
class MySchema < GraphQL::Schema
  max_depth 8
  mutation(Mutations::MutationType)
  query(Types::QueryType)

  use GraphQL::Execution::Interpreter
  use GraphQL::Analysis::AST

  # Add built-in connections for pagination
  use GraphQL::Pagination::Connections

  def self.execute(query, **args)
    super
  end

  def self.to_definition(only: nil, except: nil, context: {})
    GraphQL::Schema::Printer.print_schema(self, only: only, except: except, context: context)
  end

  # We limited max_depth to 8 and it prevents exporting introspection query as json.
  # There is a breaking change in 1.9.11.
  # See https://github.com/rmosolgo/graphql-ruby/pull/2437#issuecomment-527543621
  def self.as_json(only: nil, except: nil, context: {})
    binding.pry
    execute(GraphQL::Introspection::INTROSPECTION_QUERY, only: only, except: except, context: context, max_depth: 13).to_h
  end
end

```

**Comment by rmosolgo** [comment]
GraphiQL doesn't use `.to_json` or `.as_json`, it sends a query string from the browser to the server, and (presumably) the server executes it with `.execute`. 

Did GraphiQL properly load the schema in 1.9.11? That's when we started enforcing max depth on introspection (https://github.com/rmosolgo/graphql-ruby/blob/master/CHANGELOG.md#breaking-changes-10).

**Comment by jhirn** [comment]
Hmm, I remember doing this now to generate the schema for ESLint checking. I don't think we used to get this error prior to 1.10 in graphiql. In graphiql, i actually am getting the schema loaded despite the error so i'm not really sure what it's complaining about. Let me see if I can recreate this on a clean install or if I just have some cruft over time causing the issue.

**Comment by jhirn** [comment]
Closing as I think this isn't an error with the gem per-se but more how graphIQL might be hitting our endpoint for introspection. Hopefully someone finds this if they're experiencing the same and we can consider a fix. 

Thanks as always @rmosolgo

**Comment by richard-kramer** [comment]
Did you find a fix for this? I'm currently dealing with the same problem. My schema limits the depth to 6 and after an update to the latest graphql version the introspection from graphiql is not working anymore.

**Comment by jhirn** [comment]
> Did you find a fix for this? I'm currently dealing with the same problem. My schema limits the depth to 6 and after an update to the latest graphql version the introspection from graphiql is not working anymore.

I stopped using grahpIQL loaded from the rails engine in favor of the build in graphIQL in apollo devtools.

**Comment by aovertus** [comment]
@richard-kramer 

I guess its too late but here is a quick hack to get around the issue if anyone come across this again:

```
      graphql_params = { variables: variables, context: context, operation_name: operation_name }
      graphql_params.merge!(max_depth: nil) if !Rails.env.production? && query.match?(/IntrospectionQuery/)
      result = ApplicationSchema.execute(query, **graphql_params)
```

**Comment by parahall** [comment]
This one is really bothering me, even though it's closed. 
Using max_depth in proper queries/mutations to protect the system from load/circle resolving of entities is something that is requested in every system. 
The concept of an Introspection Query is different from that of other queries. There's no impact on any system resources since it's just the query schema, so applying the same max_depth to an introspection query just doesn't make sense. We have many external tools (e.g. Workato) that inspect our API and use different queries with 13 levels of depth and it's totally fine since it's not affecting the system resource and it's just plain network request. 
Recently, we upgraded gem and discovered that the behavior had changed. 
Now, max_depth is applied to introspection queries. Which just doesn't make sense.
Apart from all the workarounds/hacks mentioned, are we planning anything else?


@rmosolgo :)
