### ISSUE TITLE
Cannot use interface type for possible types of union types

### ISSUE THREAD

**Issue by leoc** [rmosolgo/graphql-ruby#3063]
I have recently updated `graphql-ruby` from `1.8.0` to `1.11.0` and since then this construction doesn't work anymore:

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'

  gem 'graphql', '1.11.0', require: true
  gem 'awesome_print'
end

Country = Struct.new(:id, :name)
Node = Struct.new(:id, :name, :path_id)
class Folder < Node; end

module Types; end

class Types::Country < GraphQL::Schema::Object
  description 'Resembles a Speaker Object Type'

  field :id, ID, null: false
  field :name, String, null: false
end

module Types::Node
  include GraphQL::Schema::Interface

  field :id, ID, null: false
  field :name, String, null: false
  field :path_id, String, null: false

  definition_methods do
    def resolve_type(object, _context)
      case object
      when ::Folder
        Types::Folder
      # ... more
      end
    end
  end
end

class Types::Folder < GraphQL::Schema::Object
  implements Types::Node
end

class Types::ScopableItem < GraphQL::Schema::Union
  possible_types(Types::Folder, Types::Country)

  def self.resolve_type(object, _context)
    case object
    when ::Folder then Types::Folder
    when ::Country then Types::Country
    end
  end
end

class QueryType < GraphQL::Schema::Object
  description "The query root of this schema"

  field :scopable_items, [Types::ScopableItem], null: false
  def scopable_items
    [
      ::Country.new(1, "Bizarro"),
      ::Folder.new(2, "Entry", "01.01.05 Entry")
    ]
  end
end

class AppSchema < GraphQL::Schema
  query QueryType
end

ap AppSchema.execute(<<QUERY).to_h
query {
  scopableItems {
    ... on Node {
      id
      label : pathId
    }
    ... on Country {
      id
      label : name
    }
  }
}
QUERY
```

When running it, I get:

```
{
    "errors" => [
        [0] {
               "message" => "Field 'label' has a field conflict: name or pathId?",
             "locations" => [
                [0] {
                      "line" => 5,
                    "column" => 7
                },
                [1] {
                      "line" => 9,
                    "column" => 7
                }
            ],
                  "path" => [],
            "extensions" => {
                     "code" => "fieldConflict",
                "fieldName" => "label",
                "conflicts" => "name or pathId"
            }
        }
    ]
}
```

I would have expected that I could use `Node` as a discriminator for this union type. I tried using `possible_types(Types::Node, Types::Country)`, but it seems I am not allowed to specify interface types there. The only fix here is to copy the `... on Node` part for all object types implementing `Types::Node` (e.g. `... on Folder`, etc).

Maybe this is a bug, maybe this is intended behavior and I am doing something wrong. Either way I would love to discuss whether there are other possibilities <3

Also maybe this relates to #2426

In any case, thanks and cheers!

![](https://media0.giphy.com/media/Zw3oBUuOlDJ3W/giphy.gif)

**Comment by rmosolgo** [comment]
Hi, thanks for the detailed report! My guess is that this broke in https://github.com/rmosolgo/graphql-ruby/pull/1824, which was released in 1.9.0. 

Does your app work on 1.9.0, or does it break on that version? (If it works on that version, what about 1.10.0?) 

I couldn't quite tell by reading the changelog exactly _why_ this would have changed, but if we can narrow down the version it change it, maybe we can figure it out.

**Comment by leoc** [comment]
Ah, I checked the snippet with a few version. The problem was introduced with graphql-ruby `1.9.0`. So:

- It works with `1.8.15`
- It fails with `1.9.0` and onwards (`1.10.x` & `1.11.x` have the same issue)

I cannot say which changelog entry might have introduced this issue. :crying_cat_face:

**Comment by rmosolgo** [comment]
It's been a while, but I finally got a patch to address this issue: #3440 

Thanks for the detailed report!

**Comment by leoc** [comment]
Awesome, thank you! I really love this gem!

![](https://media1.giphy.com/media/dkGhBWE3SyzXW/giphy.gif)
