### ISSUE TITLE
GraphQL Subscription not streaming on Heroku

### ISSUE THREAD

**Issue by Schorts99** [rmosolgo/graphql-ruby#3065]
Everything works on development and production environment locally, when I deploy on Heroku the subscription is created and everything looks good in the client.

![image](https://user-images.githubusercontent.com/20830415/89602527-89c87d80-d82c-11ea-88fe-51defd910630.png)

But I check the logs from Heroku and I realized that in the logs never appear that was streaming.

![image](https://user-images.githubusercontent.com/20830415/89602661-d90eae00-d82c-11ea-91b8-0534ece59973.png)

At first I try to reproduce it locally using all the vars that Heroku pass and of course, using the production environment, but it works.
This issue only happen on Heroku.

By the way, I'm using GraphQL::Subscriptions::ActionCableSubscriptions, redis: Redis.new.

Thanks for reading me :)

**Comment by rmosolgo** [comment]
Hey, sorry I don't have any experience with ActionCable on Heroku. 

Does ActionCable work at all when you deploy to Heroku? It seems possible that it might need some additional setup to work, but I'm not sure what. 

If you find that _ActionCable works_ but GraphQL subscriptions _don't work_, then let me know! Otherwise, I'm going to assume it's a deployment issue with ActionCable/Redis/Heroku, which I'm afraid I can't help much with.

**Comment by rmosolgo** [comment]
Sorry, reading it more closely, I see that the _initial subscription_ seems to work on Heroku, but the later streaming doesn't work. 

Are you sure that `.trigger` is being called, and that the arguments to `.trigger` apply to the subscription you've created? (Is there a chance that GraphQL doesn't think that the client you've set up is listening for that data?)

**Comment by Schorts99** [comment]
Yes, it's called. If it wasn't, locally it wouldn't work either.

How can I check if GraphQL think that client is listening? 🤔

And also, yes, Heroku works with ActionCable,

**Comment by Schorts99** [comment]
Locally
![image](https://user-images.githubusercontent.com/20830415/89686074-3e14e300-d8c3-11ea-9afb-042285a25ebe.png)

**Comment by Schorts99** [comment]
I find the problem, It wasn't an issue from GraphQL Subscription, was ActionCable itself.
Didn't stream when it didn't find an auth session which is weird because it has... anyway, sorry for my issue.

And again, thank you for reading me.
Nice day.

**Comment by Schorts99** [comment]
The solution was to send the auth token as param. For some reason Heroku didn't receive cookies from client so ActionCable wasn't able to create the connection for streaming.

**Comment by rmosolgo** [comment]
Glad to hear that you tracked it down! Thanks for sharing your solution.
