### ISSUE TITLE
Generate enums from models

### ISSUE THREAD

**Issue by jazzdragon** [rmosolgo/graphql-ruby#3074]
**Is your feature request related to a problem? Please describe.**

Would it be possible to generate graphql enums from enums on an associated model?
It doesn't feel good to manage those in two places that are totally disconnected.

**Describe the solution you'd like**

```Ruby
class Payment < ApplicationRecord
  enum status: %i[pending success rejected]
end

class Enums::PaymentStatus < Enums::BaseEnum
  # use here Payment.statuses.keys somehow
end
```

**Comment by rmosolgo** [comment]
Yes, sure., how about something like: 

```ruby 
class Enums::PaymentStatus < Enums::BaseEnum
  # Set up a GraphQL enum type based on the AR enum in the model.
  # The AR enum name is upcased to become the GraphQL name. 
  # Use `value:` so that GraphQL-Ruby converts the upcased name into the integer value for the enum.
  Payment.statuses.each do |name, int_value| 
    value(name.to_s.upcase, value: int_value)
  end 
end
```

Depending on how your app works, you might not want to use the `int_value` that way, maybe you just want the name instead:

```ruby 
value(name.to_s.upcase, name)
```

Let me know if that doesn't work!

**Comment by mmahalwy** [comment]
Heads up, if you decide to only use the key, make sure to add the second argument to the block:
```ruby
Client.statuses.each do |key, _| // <---- have the _
  value(key.to_s.upcase, value: key.to_s)
end
```
