### ISSUE TITLE
Add `replace_null` to optional arguments to fall back to default

### ISSUE THREAD

**Issue by hschne** [rmosolgo/graphql-ruby#3080]
**Is your feature request related to a problem? Please describe.**

The GraphQL spec does not distinguish between null and optional arguments, so if an argument is optional it is possible to just pass null instead. `graphql-ruby` then treats this as the actual value being passed, so you have to explictly check for null in those cases (as outlined in #2864). The default argument is ignored:

```ruby
field :echo, String do 
  argument :input, String, optional: true, default_value: ''
end

def echo(input: )
  if input.nil?
    input = false 
  end 
  # ...
end 
```

If you use a bunch of optional fields (for example when using [graphql-search-object](https://github.com/RStankov/SearchObjectGraphQL)) adding a check like above can become *quite* cumbersome.

**Describe the solution you'd like**

An option on the argument would reduce overhead. `replace_null` was already suggested in [this comment](https://github.com/rmosolgo/graphql-ruby/issues/2864#issuecomment-610011047). 

The argument definition would then look like:

```
field :echo, String do 
  argument :input, String, optional: true, default_value: '', replace_null: true
end
```

The behavior would be such that if a null value is passed it is replaced by the default value. If the `default_value`  is not set but `replace_null` is, we may raise an error or fall back to just passing null anyways.

**Describe alternatives you've considered**

Using the `prepare` hook is another option, but that might be deprecated soon (?), see #2749. 

I've also considered if it makes sense to change the option a bit, so more configuration is possible. For example, to treat blank values as 'empty' as well (thus falling back to the default value). Something like this: 

```ruby
argument :input, String, optional: true, default_value: 'default', replace: :null # replace only null values with default
argument :input, String, optional: true, default_value: 'default', replace: :blank # replace blank values with default as well
```

I would actually prefer this variant, as it does not seem to be that much additional effort, and covers additional use cases as well (like dealing with empty arrays)

**Comment by hschne** [comment]
I'd be happy to create a PR for this, would love to hear what you think before starting to work on this though. 

Open questions for me: 
- I'd prefer `replace: :null`, `replace :blank`, do you think this would fit the project? 
- What should happen in the case where the replace option is set by no default argument is provided?

**Comment by ExplosiveGM** [comment]
I think it will be more flexible
`replace: %i[null blank]`
**If it possible this way will be best!**
`replace: -> { param.nil? || param.blank? || param == 5 }`

**Comment by ExplosiveGM** [comment]
But possible it must be called _replace_default_
In _replace_ i expect 
```
OLD_ATTRIBUTE = 1
NEW_ATTRIBUTE = 5
replace: { OLD_ATTRIBUTE => NEW_ATTRIBUTE }
```
For example, your change your code in database, but mobile pass old param

**Comment by rmosolgo** [comment]
> `replace: ...` 

I can recommend `prepare:` for such flexible replacements, for example: 

```ruby
require "bundler/inline"

gemfile do
  gem "graphql"
end

class MySchema < GraphQL::Schema
  class Query < GraphQL::Schema::Object
    field :add, Integer do
      argument :left, Integer
      argument :right, Integer, required: false, default_value: nil, prepare: ->(val, ctx) { val.nil? || val == 1 ? 5 : val }
    end

    def add(left:, right:)
      left + right
    end
  end
  query(Query)
end

# No substitutions
pp MySchema.execute("{ add(left: 3, right: 3) }").to_h
# {"data"=>{"add"=>6}}

# Replace `nil`
pp MySchema.execute("{ add(left: 3, right: null) }").to_h
# {"data"=>{"add"=>8}}

pp MySchema.execute("{ add(left: 3) }").to_h
# {"data"=>{"add"=>8}}

# Replace `1`
pp MySchema.execute("{ add(left: 3, right: 1) }").to_h
# {"data"=>{"add"=>8}}
```

You could even modify your `BaseArgument` class to accept a `replace:` option and create a `prepare: ...` proc if it's provided.
