### ISSUE TITLE
Add `context[:current_...]` values in Interpreter

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#3085]
It's currently possible to get current runtime values, but it's a bit of a pain, eg: 

https://github.com/rmosolgo/graphql-ruby/blob/a4624789f2f1d13acde4ab8b28e2d8056c54b91b/lib/graphql/schema/directive/transform.rb#L37

There's no reason not to make a simple public API with that information, _with_ the well-documented caveat that those context keys are repeatedly overwritten during execution, so they return different objects at different time. Also, `current_path` would be frozen.

**Comment by swalkinshaw** [comment]
👍 we use `current_path` and `current_field` in a few places
