### ISSUE TITLE
Deeply nested query raises 'stack level too deep' even if max query depth is enforced

### ISSUE THREAD

**Issue by toneymathews** [rmosolgo/graphql-ruby#3089]
**Describe the bug**

Though a max query depth is enforced, executing this [query](https://gist.github.com/eapache/a4bef04ded8a624d2a41c27e36fbe2d4) raises the below error in the gem.

![Screen Shot 2020-08-17 at 3 43 36 PM](https://user-images.githubusercontent.com/19610799/90447281-f9eac500-e0b0-11ea-918d-0f663be46f75.png)

**Versions**

`graphql` version: 1.10.14
other applicable versions (`graphql-batch`, etc)

graphql-batch : 0.4.3
Max query depth enforced is 17

**Steps to reproduce**

Execute the above mentioned query

**Expected behavior**

Expected an error message stating that the query depth exceeds max query depth

**Actual behavior**

SystemStackError (stack level too deep) is raised during validation phase

![Screen Shot 2020-08-05 at 2 50 53 PM](https://user-images.githubusercontent.com/19610799/90448529-89917300-e0b3-11ea-833f-eb0877a175fb.png)

**Comment by rmosolgo** [comment]
Wow, that's intense! Even the _validator_ runs out of stack space 🙈 . 

Could you share an example query?

**Comment by rmosolgo** [comment]
Fix in the works at https://github.com/rmosolgo/graphql-ruby/pull/3107

**Comment by toneymathews** [comment]
Reopening this issue since the expected error is not returned. 
Currently the error is returned as  `{"errors"=>[]}`
Ref : https://github.com/rmosolgo/graphql-ruby/pull/3107#discussion_r478417203

**Comment by rmosolgo** [comment]
Thanks for opening that new issue :+1:
