### ISSUE TITLE
Allow InputObject to be defined based on a GraphQL type (GraphQL::Schema::Object)

### ISSUE THREAD

**Issue by blevine** [rmosolgo/graphql-ruby#3091]
**Is your feature request related to a problem? Please describe.**
This is more of an "efficiency of coding" request.  When I define a new type (GraphQL::Schema::Object), typically the first thing I do is define CRUD operations on that type. In fact, I've written a number of helper functions to generate find_all, find_by_id queries and delete_by_id mutations in which all I do is pass the name of the field and the GraphQL type.  What's missing are the create and update mutations. To implement those, I first have to define a new InputObject.  I find that in the majority of cases, the InputObject looks just like the type except that fields are replaced with arguments.  Some fields are read-only and so they are left out of the InputObject. It would be nice to be able to define a single type from which both the GraphQL::Schema::Object and the InputObject are defined.

**Describe the solution you'd like**
 1. Add a "readonly" keyword to Field to indicate that the field should not appear as an argument in the associated InputObject. 
 1. Add "generate_input_object" declaration in the type that indicates that you want an InputObject (named <type_name>Input to be dynamically generated.

This is just a convenience that would handle the "easy" cases.  If some custom handling of arguments is required, this mechanism can't be used.

**Comment by blevine** [comment]
Thanks @rmosolgo. I've prototyped this and created a gist [here](https://gist.github.com/blevine/cdf6cd5ae4d5edd99dcc8810331103e1) to give you an idea of the direction I'm taking. This seems to work well, but I'd appreciate any feedback you might have before I take this any further.

**Comment by rmosolgo** [comment]
I don't have any plans to work on this further, but I'd welcome a PR if anyone has found something that they'd like to share!
