### ISSUE TITLE
Union of primitive objects throws error with undefined `graphql_name`

### ISSUE THREAD

**Issue by mmahalwy** [rmosolgo/graphql-ruby#3092]
**Describe the bug**
Given union:
```ruby
# frozen_string_literal: true

module Types
  class StringOrStringArrayType < Types::BaseUnion
    possible_types String, [String]
  end
end
```
This results to error on `String` object with undefined method `graphql_name`

**Versions**

`graphql` version: (1.11.1
`rails` (or other framework): 6
other applicable versions (`graphql-batch`, etc)

**GraphQL schema**

**GraphQL query**

**Steps to reproduce**

Introspection

**Expected behavior**

Should not error

**Actual behavior**

Error with undefined method `graphql_name`

**Additional context**

**Comment by jturkel** [comment]
The [GraphQL Specification](https://spec.graphql.org/June2018/#sec-Unions) doesn't allow scalars to be union members so this schema isn't valid. I agree the error message could be better though.

**Comment by mmahalwy** [comment]
Ah makes sense @jturkel. Any ideas on how to achieve the same thing here? Having a field be either or of `String` or `[String]`? 

Thanks

**Comment by jturkel** [comment]
I think the best you can do with the currently limitations of unions (no scalar, list, interface, or union members) is create an object type that wraps a `String` and an object type that wraps a `[String]` and then create a union of those two wrapper types (or just normalize everything to a string array) e.g.

```graphql
union StringOrStringArray = StringWrapper | StringArrayWrapper

type StringWrapper {
  value: String!
}

type StringArrayWrapper {
  value: [String!]!
}
```
