### ISSUE TITLE
Extending graphql-ruby to support eager loading 

### ISSUE THREAD

**Issue by arzavj** [rmosolgo/graphql-ruby#3093]
As an alternative to [graphql-batch](https://github.com/Shopify/graphql-batch) (which relies on promises and batching of queries to the db), I'm looking to build a gem that extends `graphql-ruby` and supports eager loading to get the performance benefits. The corresponding ORM I have in mind is the popular [Sequel gem](https://github.com/jeremyevans/sequel). 

I've been able to accomplish this by mucking around with the internals of some objects but because these internals are not part of the standard API and subject to change as `graphql-ruby` evolves over time, I'm curious to know what the standard way to do it is. Let me explain with a concrete example as well as my source code.

Here are the basic types that have been extended to track an `eager` value for the association that needs to be eager loaded when that field is present in the query:
```ruby
# Use a custom Field class that stores an association to 
# eager load as an instance variable.
class Field < ::GraphQL::Schema::Field
  attr_reader :eager

  # Override #initialize to take a new argument `eager`:
  def initialize(*args, eager: nil, **kwargs, &block)
    @eager = eager
    super(*args, **kwargs, &block)
  end
end

class Base < GraphQL::Schema::Object
  field_class Field
end

class PostType < Base
  description 'A blog post'
  field :id, ID, null: false
  field :title, String, null: false

  field(
    :comments, 
    [Types::CommentType], 
    null: true,
    description: 'Comments on this blog post',
    eager: :comments, # <------ usage
  )
end

class CommentType < Base
  field :id, ID, null: false
  field :author, AuthorType, null: false, eager: :author # <------ usage
end

class AuthorType < Base
  field :id, ID, null: false
  field :first_name, String, null: false
  field :last_name, String, null: false
end
```

And here is the root `QueryType` which has the meat of the logic for how to automatically compute the eager hash based on the fields that have been queried for:
```ruby
class QueryType < Base
  description 'The query root of this schema'

  field :post, PostType, null: true do
    description 'Find a post by ID'
    argument :id, ID, required: true
  end

  def post(id:)
    # We must use `.all` for Sequel's eager loading to kick in
    Post.where(id: id).eager(eager_graph).all.first
  end

  private

  # Returns a hash specifying the nested associations to eager
  # load. This is to be used by the .eager() method on a Sequel
  # dataset. e.g. {comments: {author: nil}}
  def eager_graph
    # The root node in this example will always be a 
    # GraphQL::Language::Nodes::Field object representing :post.
    root = context.irep_node.ast_node.children[0]
    build_eager_graph(root, self.class.fields[root.name])
  end

  # This method traverses the nodes present in the query tree,
  # finds the corresponding field type for each node and 
  # recursively builds the tree (represented as a Hash) of 
  # associations to eager load.
  def build_eager_graph(node, field)
    graph = {}
    field_type = field_type(field)
    return graph if !field_type

    sub_fields = field_type.fields

    node.children.each do |child|
      sub_field = sub_fields[child.name]
      if sub_field.eager
        graph[sub_field.eager] = build_eager_graph(child, sub_field)
      end
    end

    graph
  end

  # Returns the root field type of the given field. So if the 
  # field is an object of GraphQL::Schema::NonNull or 
  # GraphQL::Schema::List, this method will keep going deeper
  # until it finds a type that is a sublcass of Base (i.e. a 
  # custom type defined by me). Returns nil if the field is
  # of a scalar/primitive type like String.
  def field_type(field)
    t = field.type

    loop do
      break if t.instance_of?(Class) && t < Base

      begin
        t = t.of_type
      rescue NoMethodError
        t = nil
        break
      end
    end

    t
  end
end
```

As you can see in the `eager_graph`, `build_eager_graph` and `field_type` methods, I'm using the following internal APIs:
1. `context`'s AST node tree to traverse the query tree
2. the `fields` class instance variable to get which fields are defined for a Type
3. `field.type.of_type.of_type...` to get the root Type for a Field so that I can pull out the `eager` instance variable

**Is there a more robust way to use the standard API and access these things?**

**Comment by swalkinshaw** [comment]
You want the lookahead API for this use case: https://graphql-ruby.org/queries/lookahead.html

**Comment by owen2345** [comment]
Hi guys, 
I tried with "graphql-batch" but it was not very efficient. So, I had to create this one:
https://github.com/owen2345/graphql_preload_queries
Comments and observations are welcome.
