### ISSUE TITLE
Validation breaking with variables sent by Relay

### ISSUE THREAD

**Issue by sgwilym** [rmosolgo/graphql-ruby#31]
I'm not sure if this is an issue with this gem or `graphql-relay-ruby`, but when querying a connection field with an EnumType argument, `graphql-ruby` breaks without an error message, and raises the following:

`undefined method 'type' for nil:NilClass`

This error is being raised from `/lib/graphql/static_validation/rules/variable_usages_are_allowed.rb:36:in validate_usage`

This is because the caller of this method in the same file, `validate`, is setting `var_defn_ast` to `nil`, presumably because `declared_variables[node.value.name]` doesn't actually return anything (it's empty).

And when inspecting `node` here, it can be seen that it doesn’t even have a `variables` key:

```#<GraphQL::Language::Nodes::Argument:0x007fb2a75f3870 @name="status", @value=#<GraphQL::Language::Nodes::VariableIdentifier:0x007fb2a34624b0 @name="status_0", @line=23, @col=44>, @line=23, @col=36>```

Below are the breaking query and variable params:

```
query Landing {
    viewer{
        ..._0spmx34
      }
    }
    fragment _18n1pkt on Comic {
      title,
      slug,
      author {
        name,
        username,
        id
      },
      coverPage {
        aspectRatio,
        _imageqpcky9:image(size:\"thumb\") {
          uri
        },
        id},
      id
    }
    fragment _0spmx34 on Viewer {
      _comics56iyr5:comics(first:5,status:$status_0) {
        edges {
          node {
            id,
            coverPage {
              aspectRatio,
              _imageqpcky9:image(size:\"thumb\") {
                uri
              },
              id
            },
            ..._18n1pkt
          },
          cursor
        },
        pageInfo {
          hasNextPage,
          hasPreviousPage
        }
      }
    }
```

```{"status_0" => "PUBLISHED"}```

 And just in case I'm defining something wrong, here’s my `ViewerType`:

```ruby
ViewerType = GraphQL::ObjectType.define do

  name "Viewer"
  description "This is a workaround type for Relay's inability to handle root fields with more than one argument."

  connection :comics, ComicType.connection_type do

    argument :status, ComicStatusEnum, "The status of the requested comics"

    resolve -> (obj, args, ctx) {
      if args["status"]
        Comic.where(status: args['status'])
      else
        Comic.all
      end
    }
  end

end
```

Let me know if this is something that was never going to work in the first place 😅

**Comment by rmosolgo** [comment]
Hmm definitely broken :(
 
One thing about that query, I see that _uses_ `$status_0`, but `$status_0` isn't declared in the query. 

For example, [here](http://facebook.github.io/graphql/#sec-Language.Query-Document.Variables), the variable `$devicePicSize` is _declared_ in the query definition, then _used_ later on, inside the query body. 

Does this query still fail if you define the variable, eg 

```graphql
query Landing($status_0: ComicStatus) { 
  # ... 
}
```

?

Maybe it will, I've hit a couple issues along the way where validations are in the wrong order and that causes :boom:. And this one should definitely fail with ["$status_0 is used but not defined"](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/static_validation/rules/variables_are_used_and_defined.rb#L16), so there's a bug in there somewhere!

**Comment by sgwilym** [comment]
But `status_0` _is_ defined in the `variables` sent to the GraphQL server. Shouldn't that work? If I had control over the query I'd put it in there, but this is what Relay’s coming up with.

**Comment by rmosolgo** [comment]
Interesting that the example here doesn't include variables in the operation definition: https://facebook.github.io/relay/docs/guides-routes.html#queries-vs-fragments

let me ask someone about that ...

**Comment by rmosolgo** [comment]
I think it's the same bug as this: https://github.com/facebook/relay/issues/203

**Comment by sgwilym** [comment]
Yeah, that looks similar. I'll give this another go when the next Relay release comes out, thanks!

**Comment by sgwilym** [comment]
Okay, so here’s what I got with Relay 0.2.1:

```
query RouteQueries($status_0:enum) {
  viewer{
    ..._0cvzi8y
  }
} 

fragment _0cvzi8y on Viewer{
  _comics9j97ye:comics(first:5,status:$status_0){
    ..._1mly5s3
  }
}

/* ... */
```

and variables:

```{"status_0"=>"published"}```

This seems to break: 

`undefined method `kind' for nil:NilClass`
`/Users/gwil/.rvm/gems/ruby-2.2.0/gems/graphql-0.7.1/lib/graphql/static_validation/rules/variables_are_input_types.rb:15:in `validate_is_input_type'`

**Comment by rmosolgo** [comment]
Ick, bad error message :( 

It's failing to pull a type out of the schema whose name is `"enum"`, is that the right name for that type?

Not sure if graphql-ruby is publishing the wrong schema info or if Relay is building the wrong query 

Todo: better error if type isn't found!

**Comment by josephsavona** [comment]
This was a bug in Relay, fixed in https://github.com/facebook/relay/issues/203

**Comment by sgwilym** [comment]
That's odd, because like I mentioned, this request was made by react-relay@0.2.1.

But like @rmosolgo suggested, it could be something with the schema: internally the enum's name is ComicStatus.

**Comment by rmosolgo** [comment]
could you put up a gist of your schema instrospection JSON, and also the definition of that enum? Very well seems like it could be graphql-ruby since relay is supposed to be fixed

**Comment by rmosolgo** [comment]
Just pushed to raise on duplicate or missing types: 08874a8

**Comment by sgwilym** [comment]
Here's the definition of ComicStatus, and my schema.json: https://gist.github.com/sgwilym/66429124fbfe84af0a34

**Comment by rmosolgo** [comment]
Thanks for sharing. I thought maybe the JSON would have the wrong info, but it looks right to me! 

```json
   {
          "kind" : "ENUM",
          "name" : "ComicStatus",
          "description" : "Possible states for comics to be in",
          "fields" : null,
          "inputFields" : null,
          "interfaces" : null,
          "enumValues" : [
            {
              "name" : "DRAFT",
              "description" : "Possible states for comics to be in",
              "isDeprecated" : false,
              "deprecationReason" : null
            },
            {
              "name" : "PUBLISHED",
              "description" : "Possible states for comics to be in",
              "isDeprecated" : false,
              "deprecationReason" : null
            }
          ],
          "possibleTypes" : null
        },
```

**Comment by josephsavona** [comment]
@rmosolgo An earlier version of `babel-relay-plugin` output generic type information for enums and input objects, and these were printed inline eg (`field(enum: VALUE)`). The `"enum"` value you're seeing suggests that the code is being compiled with that outdated plugin version. Can you reproduce this on the latest version, `0.2.2`?

**Comment by rmosolgo** [comment]
@sgwilym how's this looking lately?

**Comment by josephsavona** [comment]
@rmosolgo This was definitely an issue in Relay and has been fixed (see the compiled query output at https://github.com/facebook/relay/blob/master/scripts/babel-relay-plugin/src/__fixtures__/fieldWithEnumArg.fixture#L48-L50 - previously the `type` would have been `enum`, now we record the type name as `Gender`). 

It's probably ok to close.

**Comment by rmosolgo** [comment]
Ok, thanks for following up!

**Comment by sgwilym** [comment]
Sorry for dragging my heels on this, I think this issue may need to be reopened:

The query from Relay, now correctly showing `ComicStatus` in the root query:
```
query RouteQueries($status_0:ComicStatus){
  viewer{
    ...__RelayQueryFragment16p69yi
  }
} 

fragment __RelayQueryFragment39q7490 on Comic{
  /* bla bla bla */
} 

fragment __RelayQueryFragment2hdbh5f on ComicConnection{
  /* bla bla bla */
} 

fragment __RelayQueryFragment16p69yi on Viewer{
  _comicsuun144:comics(first:10,status:$status_0){
    ...__RelayQueryFragment2hdbh5f
  }
}
```

Variables:
```ruby
{"status_0"=>"PUBLISHED"}
```

And the error returned by `graphql-ruby`: 
```
Variable $status_0 is declared but not used
```

**Comment by rmosolgo** [comment]
definitely seems like a bug, thanks for pasting the queries, i'll see if i can reproduce in a test!

**Comment by rmosolgo** [comment]
@sgwilym can you try the current master branch? I hope this commit fixed it: 

https://github.com/rmosolgo/graphql-ruby/commit/1862c3ead0e87d3a39906e4e1a9736df95d5a893

**Comment by sgwilym** [comment]
That fixed it! 🎉
