### ISSUE TITLE
Union type generator creates a list of types in possible_types

### ISSUE THREAD

**Issue by mheld** [rmosolgo/graphql-ruby#3102]
**Describe the bug**

`rails g graphql:union SearchResult X Y Z` should create a SearchResultType with:
`possible_types Types::XType, Types::YType, Types::ZType
`
but instead creates with 
`possible_types [Types::XType, Types::YType, Types::ZType]
` 
(note the list)

**Versions**

`graphql` version: graphql-1.11.3
`rails` (or other framework): Rails 6.0.3.2
other applicable versions (`graphql-batch`, etc)

**Steps to reproduce**

rails g graphql:union SearchResult X Y Z

**Expected behavior**

In SearchResultType.rb:
`possible_types Types::XType, Types::YType, Types::ZType
`

**Actual behavior**

In SearchResultType.rb:
`possible_types [Types::XType, Types::YType, Types::ZType]
` (note the list)

Which will lead to an exception down the road:
<details>
undefined method `graphql_name' for #<Array:0x00007f5e0c9695a8>
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/graphql-1.11.3/lib/graphql/schema.rb:1849:in `add_type'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/graphql-1.11.3/lib/graphql/schema.rb:1895:in `block in add_type'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/graphql-1.11.3/lib/graphql/schema.rb:1894:in `each'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/graphql-1.11.3/lib/graphql/schema.rb:1894:in `add_type'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/graphql-1.11.3/lib/graphql/schema.rb:1877:in `block in add_type'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/graphql-1.11.3/lib/graphql/schema.rb:1873:in `each'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/graphql-1.11.3/lib/graphql/schema.rb:1873:in `add_type'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/graphql-1.11.3/lib/graphql/schema.rb:1746:in `block in add_type_and_traverse'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/graphql-1.11.3/lib/graphql/schema.rb:1746:in `each'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/graphql-1.11.3/lib/graphql/schema.rb:1746:in `add_type_and_traverse'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/graphql-1.11.3/lib/graphql/schema.rb:1050:in `query'
/home/mheld/projects/customs-bear-backend/app/graphql/customs_bear_schema.rb:3:in `<class:CustomsBearSchema>'
/home/mheld/projects/customs-bear-backend/app/graphql/customs_bear_schema.rb:1:in `<main>'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.0/lib/zeitwerk/kernel.rb:27:in `require'
/home/mheld/projects/customs-bear-backend/app/controllers/graphql_controller.rb:15:in `execute'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/abstract_controller/base.rb:195:in `process_action'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_controller/metal/rendering.rb:30:in `process_action'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:101:in `run_callbacks'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/abstract_controller/callbacks.rb:41:in `process_action'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_controller/metal/rescue.rb:22:in `process_action'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/notifications.rb:180:in `block in instrument'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/notifications.rb:180:in `instrument'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/searchkick-4.4.1/lib/searchkick/logging.rb:212:in `process_action'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.2/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/abstract_controller/base.rb:136:in `process'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_controller/metal.rb:190:in `dispatch'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_controller/metal.rb:254:in `dispatch'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/routing/route_set.rb:33:in `serve'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/journey/router.rb:49:in `block in serve'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/journey/router.rb:32:in `each'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/journey/router.rb:32:in `serve'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/routing/route_set.rb:834:in `call'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:40:in `call'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:567:in `call'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:101:in `run_callbacks'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/executor.rb:14:in `call'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.2/lib/rails/rack/logger.rb:37:in `call_app'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.2/lib/rails/rack/logger.rb:26:in `block in call'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:80:in `block in tagged'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:28:in `tagged'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:80:in `tagged'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.2/lib/rails/rack/logger.rb:26:in `call'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/executor.rb:14:in `call'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/static.rb:126:in `call'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.0.3.2/lib/rails/engine.rb:527:in `call'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/puma-4.3.5/lib/puma/configuration.rb:228:in `call'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/puma-4.3.5/lib/puma/server.rb:713:in `handle_request'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/puma-4.3.5/lib/puma/server.rb:472:in `process_client'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/puma-4.3.5/lib/puma/server.rb:328:in `block in run'
/home/mheld/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/puma-4.3.5/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
</details>

**Comment by rmosolgo** [comment]
Oops, I guess the template needs an update! Here's the line where square brackets need to be removed: 

https://github.com/rmosolgo/graphql-ruby/blob/558a43fb1ce444d673267d241ea41b612f5b57c5/lib/generators/graphql/templates/union.erb#L3

Feel free to give it a shot, otherwise I'll try to make time for it. (Some tests will also need updating.)
