### ISSUE TITLE
Guide: Interfaces

### ISSUE THREAD

**Issue by dkassen** [rmosolgo/graphql-ruby#3114]
I have confusion about the first sentence in the Orphan Types section about what it means to be "properly" included in the schema. If that could be elaborated on in a concise way, that'd be great.

**Comment by rmosolgo** [comment]
Hey, sorry that wasn't clear. I tried to add some detail in https://github.com/rmosolgo/graphql-ruby/commit/64bbd5d38db4064bcda9c19f07cd3fa9bda40612, what do you think?
