### ISSUE TITLE
Serverside implicit `__typename` for queries before resolving them

### ISSUE THREAD

**Issue by MarcusRiemer** [rmosolgo/graphql-ruby#3118]
I am using GraphQL-Ruby with a set of pre-defined queries that clients may execute. The permitted queries are stored on the server and are effectively files with normal GraphQL-queries. So when a client makes a request, instead of sending a query it sends the name of a query and then the server loads whatever it deems appropriate.

But some clients, e.g. Apollo, [require the introspection type information like `__typename` fields for caching](https://www.apollographql.com/docs/react/caching/cache-configuration/). As far as I can see the ability to automatically add those has already been added to the client (https://github.com/rmosolgo/graphql-ruby/issues/961), would it be possible to also expose this transformation on the server? This would save me the hassle to write `__typename` into quite a few documents ...

**Comment by rmosolgo** [comment]
Sure, you could make an AST visitor to do this. The built-in visitor class includes support for modifying visited nodes, for example: https://graphql-ruby.org/language_tools/visitor.html#insert-a-node. You could add a `__typename` field to any field that has subselections and doesn't _already_ have a selection named `__typename`. 

Let me know how it goes if you give it a try!

**Comment by MarcusRiemer** [comment]
Thanks alot, this put me in the right direction. Finding out that I can work with the incoming queries on an AST level is a very welcome surprise!

I have probably made some dumb mistake, but the `node.add_selection(name: "emailAddress")` method that is mentioned in the doc doesn't seem to exist? At least it doesn't appear either in the [docs](https://graphql-ruby.org/api-doc/1.11.4/GraphQL/Language/Nodes/Field.html) nor on the actual instance that I briefly checked with `byebug`.

The code I ended up with just rolled with the "These `.add_*` helpers are wrappers around `GraphQL::Language::Nodes::AbstractNode#merge`." hint in the docs and reads as follows:

```ruby
class InsertTypenameVisitor < GraphQL::Language::Visitor
  def on_field(node, parent)
    names = node.selections.map {|s| s.name }
    if not names.empty? and not names.include? "__typename"
      typename_node = GraphQL::Language::Nodes::Field.new(name: "__typename");
      node = node.merge(selections: node.selections + [typename_node])
    end
    super
  end
end
```

This at least passes some superflous tests I have written for some of the queries and mutations that are in my system.
