### ISSUE TITLE
Schema instance possible types behaves different than class method

### ISSUE THREAD

**Issue by grcooper** [rmosolgo/graphql-ruby#3123]
**Describe the bug**

The two methods for `possible_types` do not behave the same on the schema instance vs the schema class.

The schema instance method uses the class `PossibleTypes` [here](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema.rb#L555).

The schema class method uses a built in hashmap [here](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema.rb#L1109). 

This has some correct logic for possible types on unions, but interfaces are not handled the same way they were previously. The main difference being that `context` is not taken into account for the interfaces which causes some issues for interface type membership visibility.

**Versions**

`graphql` version: `1.11.4`
`rails` (or other framework): 
other applicable versions (`graphql-batch`, etc)

**GraphQL schema**

```ruby
class TypeMembership < TypeMembershipVisibility
  def visible?(context)
    context[:private]
  end
end

module MyInterface
   include GraphQL::Schema::Interface
  type_membership_class TypeMembership

  field :test, :string, null: false
end

class Product < GraphQL::Schema::Object
  implements MyInterface

  field :id, ID, null: false
end

class QueryRoot < GraphQL::SchemaObject
  field :my_interfaces, [MyInterface], null: false
end

class ApplicationSchema < GraphQL::Schema
  query QueryType
end
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
query {
  myInterfaces { test  ... on Product { id } }
}
```

Assuming we pass through `context = { private: false }`:

Expected:

```json
{
  "errors": [{ "Object type Product cannot be spread inside of myInterfaces }]
}
```

Actual:

```json
{
  "data": {
    "myInterfaces": [ { "test": "test", "id": 1234 }]
  }
}
```

**Additional context**

I believe this is a bug because of the different behaviour between what is expected in the instance method vs the class method. The code around the class method `possible_types` on Schema is a bit confusing and I didn't want to dive into it too hard and add `context` without first getting your opinion on if this should be solved and is indeed a bug.

**Comment by rmosolgo** [comment]
Yes, agreed that it's a bug, and it should work the way you expected :+1:
