### ISSUE TITLE
Suggest increase with namespace

### ISSUE THREAD

**Issue by 308820773** [rmosolgo/graphql-ruby#3148]
like mutation, input. In the production, we need to write more,  If  they in one dir, it is not beautiful. 

example:  Mutations::CreatePost Mutations::SignInUser
In the schema, the mutation is createPost, signInUser.

---
Suggest: Mutations::Post::Create, Mutations::User::SignIn is good.
And the schema is postCreate, userSignIn

**Comment by 308820773** [comment]
In the rails convention over configuration. Example a mutation default find with a same name input, I think the graphql is very easy. The user use it is very comfort and easy.

**Comment by rmosolgo** [comment]
Hi! Thanks for the suggestion. Here's how you could accomplish that: 

```ruby 
class Mutations::Base < ... 
  def default_graphql_name 
    self.name
      .sub("Mutations", "") # Remove the Mutations namespace
      .gsub("::", "") # Join the remaining module names 
      .camelize(:lower) # Downcase the first letter
  end 
end 
```

Then hook up the mutations with the field names you want, eg 

```ruby 
class Types::Mutation < Types::BaseObject 
  field :user_create, mutation: Mutations::User::Create 
end 
```

Give it a try, and let me know if you run into any trouble!

**Comment by 308820773** [comment]
It's ok, Thank you.
