### ISSUE TITLE
Class based example for Field::GraphQL

### ISSUE THREAD

**Issue by amronrails** [rmosolgo/graphql-ruby#3158]
I wish if there is a class-based example to use GraphQL::Field

 like this one
```
name_field = GraphQL::Field.define do
  name("Name")
  type(!types.String)
  description("The name of this thing")
  resolve ->(object, arguments, context) { object.name }
end
```

```
NamedType = GraphQL::ObjectType.define do
  # The second argument may be a GraphQL::Field
  field :name, name_field
end
```

**Comment by rmosolgo** [comment]
`GraphQL::Field` doesn't work with class-based types; the replacement is `GraphQL::Schema::Field`. However, I don't recommend using that class directly. 

Instead, create class method "macro" for defining a name field, then use that macro in your type definitions. For example: 

```ruby 
class Types::BaseObject < GraphQL::Schema::Object 
  def self.add_name_field 
    field(:name, String, null: false, description: "The name of this thing")
  end 
end 

# ... 

class Types::NamedType < Types::BaseObject 
  add_name_field # creates a field just like the one in the OP 
end 
```

Hope that helps! If you try something like that and run into trouble, please share the code you tried and details about the trouble you encounter.
