### ISSUE TITLE
Action Cable Subscription sometimes not sent back to the client, but saved on DB

### ISSUE THREAD

**Issue by semoal** [rmosolgo/graphql-ruby#3159]
**Describe the bug**

Graphql Subscription via action cable works 90% of times, but sometimes the message is saved on the db, but not broadcasted back to the websocket connection.
If we reload the page, the messages are displayed.

**Versions**

`graphql` version: '~ > 1.10'
`rails` (or other framework): 6.0.0
other applicable versions (`graphql-batch`, etc): graphql-batch: '~>0.4'

**GraphQL schema**

```ruby
class Types::SubscriptionType < GraphQL::Schema::Object
  extend GraphQL::Subscriptions::SubscriptionRoot

  Field :incoming_message, Types::MessageType, null: true do
    Argument :receiver_user_id, ID, required: true
    Argument :sender_user_id, ID, required: true
  end
  def incoming_message(receiver_user_id:, sender_user_id:)
    object
  end
end

class GraphqlSchema < GraphQL::Schema
  query Types::QueryType
  mutation Types::MutationType
  subscription Types::SubscriptionType

  use GraphQL::Batch
  use GraphQL::Subscriptions::ActionCableSubscriptions, redis: Redis.new
  use GraphQL::Tracing::AppsignalTracing

  lazy_resolve(Concurrent::Future, :value)

...
end

```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```js
import { createConsumer } from "@rails/actioncable";
import { ActionCableLink } from "graphql-ruby-client";
import { split, from, HttpLink, ApolloClient, InMemoryCache } from "@apollo/client";
import { onError } from "@apollo/client/link/error";
import { getMainDefinition } from "@apollo/client/utilities";

import provideUserSession from "src/core/infrastructure/UserSession";

const URI = process.env.API_PROD_ENV === "true" ? process.env.API_PROD_URI : process.env.API_DEV_URI;
const WS_URI = process.env.API_PROD_ENV === "true" ? process.env.WS_PROD_URI : process.env.WS_DEV_URI;

const cable = createConsumer(WS_URI);
const wsLink = new ActionCableLink({
  cable,
});

const httpLink = new HttpLink({
  uri: URI,
  credentials: "include",
});

const splitLink = split(
  ({ query }) => {
    const definition = getMainDefinition(query);
    return (
      definition.kind === "OperationDefinition" &&
      definition.operation === "subscription"
    );
  },
  wsLink,
  httpLink,
);
```

```json
{
"command": "message",
"data": "{"query":"subscription getIncomingMessages($receiver_user_id: ID!, $sender_user_id: ID!) {\n  incoming_message(receiver_user_id: $receiver_user_id, sender_user_id: $sender_user_id) {\n    text\n    created_at\n    __typename\n  }\n}\n","variables":{"receiver_user_id":15226,"sender_user_id":16301},"operationName":"getIncomingMessages","action":"execute"}",
"identifier": "{"channel":"GraphqlChannel","channelId":"174a1e31cac"}"
}
```

**Steps to reproduce**

Build an simple application with action cable + redis + and graphql-ruby

**Expected behavior**

Always return the correct messages

**Additional context**

On local development I couldn't reproduce this error.
I though in first instance the problem is channelId changes, so when the other user send the message, the receiver got another channelId, and that's why isn't showed. 
If i keep sending messages, it works some of them (and they are sent with other channelIds, so probably this is the problem?)

**Comment by rmosolgo** [comment]
A couple things: 

- You can remove the `redis:` option from your subscription setup. ActionCableSubscriptions uses ActionCable's own adapter, not its own Redis connection. 
- Which ActionCable adapter are you using? (https://edgeguides.rubyonrails.org/action_cable_overview.html#subscription-adapter). If you're using `async`, then environments with multiple Ruby processes (usually production, but not development) won't broadcast messages from one process to another. Make sure you're using the `redis` or PostgresQL adapter, which broadcast messages across processes using one of those databases. Does that help?

**Comment by semoal** [comment]
> A couple things:
> 
> * You can remove the `redis:` option from your subscription setup. ActionCableSubscriptions uses ActionCable's own adapter, not its own Redis connection.
> * Which ActionCable adapter are you using? ([edgeguides.rubyonrails.org/action_cable_overview.html#subscription-adapter](https://edgeguides.rubyonrails.org/action_cable_overview.html#subscription-adapter)). If you're using `async`, then environments with multiple Ruby processes (usually production, but not development) won't broadcast messages from one process to another. Make sure you're using the `redis` or PostgresQL adapter, which broadcast messages across processes using one of those databases. Does that help?

I'm using redis on dev and production
```
development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: connect-api_development

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: connect-api_production

```

**Comment by semoal** [comment]
Nothing, same situation.
I saw the cable connection 101 protocols on Chrome, is recreating every 30 seconds without killing the other, could be that the problem?

**Comment by semoal** [comment]
Looks an issue with GCP load balancers cutting the connection after 30seconds. If I fix the issue i'll post the changes here for possible future users!

**Comment by semoal** [comment]
Alright solved @rmosolgo was the google cloud load balancer, was set a default timeout of 30 seconds.

Thanks for your help!!

Related post [Medium](https://medium.com/johnjjung/how-to-use-gcp-loadbalancer-with-websockets-on-kubernetes-using-services-ingresses-and-backend-16a5565e4702#:~:text=The%20Problem%3A%20GCP%20LoadBalancers%20are,that%20causes%20connections%20to%20close.)

**Comment by rmosolgo** [comment]
Glad you got to the bottom of it, and thanks for sharing your solution!
