### ISSUE TITLE
Scaffold graphql:object from models subfolder 

### ISSUE THREAD

**Issue by aldd-dpulidog** [rmosolgo/graphql-ruby#3160]
I have a structure in models folder like the following:

models
--subfolder1
----model
--subfolder2
----model

How can I scaffold with graphql:object by providing the model from the subfolder I want?

I ask this because executing the generator with the name of the model it generates no fields, I assume that it is not finding the model name in the models root (each subfolder has its own database configuration in its application record).

**Comment by rmosolgo** [comment]
Hey, I'm not sure if that'd be properly supported here. This is where typenames are converted to model classes: 

https://github.com/rmosolgo/graphql-ruby/blob/88a2ebf89e14c7b09b6e9c259b8b4c67ff62d214/lib/generators/graphql/object_generator.rb#L71-L73

Maybe it could be improved to take a model name as an option, to to improve the way that the corresponding model class is looked up. I don't have plans to work on this further, but I'll leave the issue open for a while in case someone wants to give it a try. I'd be happy to review a PR for it!

**Comment by rmosolgo** [comment]
I'd be happy to support this, but I don't have plans to work on so I'm going to close this issue.
