### ISSUE TITLE
Support For multiple QueryType objects at top level

### ISSUE THREAD

**Issue by mattcamuto** [rmosolgo/graphql-ruby#3170]
Firstly thanks for all the work on this gem @rmosolgo. This might straddle between 'feature' or 'best practice. I came back to GQL after a few years and noticed that resolvers are not really used as much and PORO's are more desired at the top level.

However with this it seems that my QueryType class gets pretty huge. With a definition and then a delegate method. As opposed to using a resolver. I guess I can use resolvers to clean the code a bit. For example I have a lot of code like this.

~~~
module Types
  class QueryType < Types::BaseObject

  # lots of code like this.
   field :get_brand_policy, Types::BrandPolicy, null: false
   def get_brand_policy
      BrandService.new(context[:viewer]).get_brand_policy
    end

  end
end
~~~

I could go back to using resolvers, but that again has its own set of extra code.

However, my bigger thought is about supporting multiple top level queries or mutations. For example

~~~
class MainAppSchema < GraphQL::Schema
  ....

  add_query(Types::QueryType)
  add_query(Types::MyUserQueryType)
  add_query(Types::MyAccountQueryType)

  ...
end
~~~

I realize I can add in modules and so some includes/meta programming if needed at the QueryType object if needed. Just looking for any suggestions or ideas if something like this is worthwhile or already advised. I kind of like the ability to compose a bit at the top level. Or something similar. But also see a lot of stuff in the code tied to just having one query/mutation type.

Thanks

**Comment by rmosolgo** [comment]
👋  As you noted, there's nothing built into graphql-ruby for this. Personally, it's not a priority, so I haven't looked into it. There are some suggestions in #1825 , hopefully one of those will help!

**Comment by mattcamuto** [comment]
@rmosolgo - thanks. I wish I had seen something like that ticket prior! Will go that route.
