### ISSUE TITLE
Allow authorization configuration to omit nil records in a collection

### ISSUE THREAD

**Issue by cablett** [rmosolgo/graphql-ruby#3175]
**Is your feature request related to a problem? Please describe.**

When unauthorised records are returned as `nil`, this can have security implications (even the count of unauthorised records can present a security vulnerability, especially when customised inputs, such as search, are used).

**Describe the solution you'd like**

I'd love to be able to customise the authorisation behaviour to omit unauthorised records entirely (like, with a `compact` call before returning the final results) rather than being replaced with `nil`.

**Describe alternatives you've considered**

We previously wrote a homecooked authorisation framework that omits unauthorised records, but we'd like to use the native gem auth framework instead, because it's much easier and we can remove a bunch of code! :+1: 

Could we call `compact` on the results of a collection after authorisation? :thinking:

**Comment by rmosolgo** [comment]
Hey, thanks for the great question. GraphQL-Ruby has a feature called "Scoping" that's meant to cover this case: 

https://graphql-ruby.org/authorization/scoping.html

But it's a little different than you describe here. `def self.scope(ctx, items)` is called _before_ authorizing each item in `items`. It's done that way so that if `items` is a query class (like `ActiveRecord::Relation`), you can perform authorization _before_ running the database. The goal is to _avoid_ those `nil`s in results rather than `.compact` them. The downside is that each item in `items` might be authorized twice: once by `def self.scope(ctx, items)`, and then again by `def self.authorized?(object, ctx)`.  Personally, I consider the trade-off (of simplicity & predictability vs. optimization) _worth it_, so I haven't implemented a step in GraphQL-Ruby where you could call `.compact` on a list containing `nil`s. (You could call in it a resolver, but that would happen _before_ authorization.) 

How about giving scopes a try?

**Comment by cablett** [comment]
Cheers, thanks! I'll give it a try. :slightly_smiling_face:

**Comment by cablett** [comment]
Thank you so much for the suggestion. :slightly_smiling_face: 

Prima facie, `scope` might be where we put in our Authorize code, but it only performs at the `Type` level. We need something at the `field` level, as we declare authorisation there for finer-grained control.

For reference, we currently use a declarative approach, for example, in a type:

```
# ProjectType.rb
  class ProjectType < BaseObject # BaseObject subclasses GraphQL::Schema::Object
    graphql_name 'Project'

    authorize :read_project # a user must have permission to read the project for this object to be returned
```

or as part of field metadata:

```
# ProjectType.rb
field :release,
      Types::ReleaseType,
      authorize: :download_code # a user must have permission to download code from the project to view this field
```

In the field example above, the check is run against the current user, and the field is shown authorised to `download_code` on the project object (the parent of the field).

The above is used by our `Authorize` instrumentation that wraps the original field proc to filter out unauthorised records using `keep_if`. However, this doesn't handle promises properly, as we have to call `.sync` on the object to make sure we're not dealing with a delayed promise. This means we can't batch load things, as the authorisation logic interrupts the batch loading and renders it useless (and that's why we're looking to replace our homecooked auth logic with the native gem code).

(I hope I've explained myself correctly) :slightly_smiling_face: 

Do you have any ideas as to how I might achieve type field level auth that is post-lazy/promise resolution, that might work with the declarative form above? :thinking: I'm happy to collaborate on a PR, but if you feel our case is a bit specific for a generalised, any guidance would be helpful :bow:

**Comment by cablett** [comment]
I thought about overriding `after_lazy` in our Schema to `compact` then, but if feels rather hacky (if it works at all) :sweat_smile:

**Comment by rmosolgo** [comment]
>  auth that is post-lazy/promise resolution

I expect the built-in authorization framework to work with batch loading. Auth checks should all be called with application objects, not promises (etc). 

To give it a try, in your base type/field classes: 

- Implement `def self.authorize(config)` to store the authorize name (or `def initialize(*args, authorize: nil, **kwargs, &block)` for Fields) 
- Implement `def self.authorized?(...)` (or `def authorized?(...)` for fields) to read the stored authorize config and apply it to the given inputs

**Comment by rmosolgo** [comment]
I hope you found something that works for you!

**Comment by thisismydesign** [comment]
@rmosolgo This is a valid request. Scoping is not the same as authorization. Not authorized objects should not be part of a returned collection. It doesn't make sense to return them, but worse, it will break type definitions:

`type [MyType]` will produce the error: `Cannot return null for non-nullable field xxxx`. The workaround would be to use type [MyType, null: true] fo every collection :(
