### ISSUE TITLE
Add support for lambda to be passed as a field method argument

### ISSUE THREAD

**Issue by TikiTDO** [rmosolgo/graphql-ruby#3178]
**Is your feature request related to a problem? Please describe.**

Currently when defining a field that uses a method to resolve a value the only options are to use a resolver, an instance method defined in the schema type, or a helper method on an object. It feels like it would be more ruby-like to also allow passing a lambda as a `:method`, which would allow everything related to a simple field to live in one place.

This issue is to gauge the interest in such a feature. In the maintainers are open to it I can see about submitting a PR with some tests.

**Describe the solution you'd like**

Add support to allow the [method](https://github.com/rmosolgo/graphql-ruby/blob/bebd78c0d5fddae997aec959506c6f42f71564ea/lib/graphql/schema/field.rb#L185) argument of the `GraphQL::Schema::Field` take a lambda/proc instance as well as a symbol.

Currently, a simple example would look like this:

```ruby
class ExampleType < GraphQL::Schema::Object
  field :example_field, AnotherType, null: true, method: :resolve_example_field
  def resolve_example_field
    object.something.something_else || { some: :fallback }
  end
end
```

I would like to do this:

```ruby
class ExampleType < GraphQL::Schema::Object
  field :example_field, AnotherType, null: true, 
    method: lambda { object.something.something_else || { some: :fallback } }
end
```

This could reduce the amount of boilerplate code for fairly simple, but otherwise non-trivial fields.

**Describe alternatives you've considered**

The existing approach of defining a method in the schema class requires a lot of boilerplate for fairly simple functionality, which can make an otherwise manageable schema into a large, difficult to read blob. 

It is also possible to also add extra helpers onto the `object` under consideration, but that runs the risk of spreading tightly-coupled code to multiple files where other people on a team might not be aware of all the uses of such a method. 

Finally, using resolvers is a more explicit option, but it can be overkill for an otherwise simple field.

Having in-line method definitions like above can make fields easier to explain and describe, while reducing the risk that someone might change important functionality without being aware that it is used for resolving fields.

**Comment by rmosolgo** [comment]
Hey, sorry for the slow response. I think this could be implemented in your base field like this: 


```ruby 
class BaseField < GraphQL::Schema::Field 
  def initialize(method: nil, name:, **kwargs, &block)
    if method && method.is_a?(Proc)
      method_name = "resolve_#{name}_with_proc"
      define_method(method_name, &method)
      method = method_name 
    end 
    
    super(name: name, method: method, **kwargs, &block)
  end 
end 
```

(Given a proc, use it to define a method, then replace the proc with the method name and call `super`.) 

If you give it a try in your application, I'd welcome a PR that adds it to the gem (along with a report of how you end up using it). But it's not a priority for me, so I don't plan to implement it.
