### ISSUE TITLE
Schema execution inside RubyProf#profile causes object allocation error

### ISSUE THREAD

**Issue by arthurwozniak** [rmosolgo/graphql-ruby#3183]
**Describe the bug**

First of all, I hope I'm not inventing the wheel. In our project, we would like to have possibility of benchmarking queries in production environment with `RubyProf`. So I have taken public controller action and wrapped graphql execution with `RubyProf#profile`. 

**Versions**

`graphql` version: 1.9.15 and 1.11.5
`rails` (or other framework):  6.0.2.2
other applicable versions (`graphql-batch`, etc)

**GraphQL schema**

I think not relevant for this case

**GraphQL query**

I think not relevant for this case

**Steps to reproduce**

Create controller action with `RubyProf` usage. In my case, it looks like

```ruby
def analyzed_execute
    authorize! :execute, :graph_ql

    Thread.current[:current_user] = current_user
    @result = nil
    prof_result = RubyProf.profile do
      @result = GraphqlRunner.new(params, prepare_context).multiplex_execute
    end
    printer = RubyProf::GraphHtmlPrinter.new(prof_result)
    File.open("tmp/profile_data.html", 'w') { |file| printer.print(file) }

    render json: @result
  end

```

where `GraphqlRunner` executes `C2eBackendSchema` with `multiplex` or `execute` method regarding to request data.

So I expect wrapping `Schema.execute` with `RubyProf` should reproduce error for you.

**Expected behavior**

Rendered json as result of API call with `tmp/profile_data.html` file written.

**Actual behavior**

I have pasted full log to gist - https://gist.github.com/arthurwozniak/0bd5e4c3c8222803a1c9c9a746898acc

**Additional context**

Not sure if this bug relates to `graphql-ruby` or `ruby-prof`. Thanks for help!

**Comment by rmosolgo** [comment]
🤔 

> [BUG] object allocation during garbage collection phase

that's a very low-level error and I've never _heard_ of it coming from GraphQL-Ruby before. I'm inclined to think it's some kind of conflict from the two libraries, the ruby version, and the environment. 

Does it run properly without `ruby-prof`? 

You might try it on a newer ruby version, in case there was a Ruby bug that was fixed along the way.

**Comment by arthurwozniak** [comment]
Code runs properly without `ruby-prof`. But you were right about upgrading ruby! Switching to 2.7 solved the problem. Thank you
