### ISSUE TITLE
How to load a record with a non-id argument

### ISSUE THREAD

**Issue by gopeter** [rmosolgo/graphql-ruby#3184]
I'm trying to load the record of a mutation for any arbitrary argument, but can't find a way to do this:

```ruby
module Mutations
  module User
    class Update < Inputs
      graphql_name "UpdateUser"
      pundit_role nil

      argument :id, ID, required: true, loads: Types::UserType, pundit_role: :can_update
      argument :is_admin, Boolean, required: false, loads: Types::UserType, pundit_role: :can_set_admin
      field :user, Types::UserType, null: true

      def load_id(user_id)
        Helpers::GlobalId.find_record(::User, user_id)
      end

      def load_is_admin(is_admin)
        # ... is there a way to get the `id` argument here to load the record?
      end

      def resolve(inputs)
        Functions::Mutate.new(model: ::User, record: inputs[:id], fields: inputs.except(:id)).update
      end
    end
  end
end
```

My `UserPolicy` contains a rule which needs access to the record that is going to change:

```ruby
def can_set_admin?
  user.admin? && record.id != user.id
end
```

Otherwise admins could revoke their own admin rights.

**Comment by rmosolgo** [comment]
Hi! Sorry for the very slow response here. I'm not sure how I missed this when it came in. 

Inside a `def load_...` method, there's no way to get other arguments. Those `load_...` methods are meant to load objects based on given IDs, not perform business logic.  

(There _is_ an `arguments` accessor, but it's only populated _after_ all arguments have been loaded: https://github.com/rmosolgo/graphql-ruby/blob/e5c261c53313e6730012bf9b420469c90ca89075/lib/graphql/schema/resolver.rb#L61-L63)

I think a check like this would have to be performed later. 

In fact, shouldn't this check be inside `Functions::Mutate` above? (Should `Functions::Mutate` _ever_ succeed when `user.admin? && user.id == record.id`?) 

Anyhow, sorry I don't have anything more helpful on this one 😅

**Comment by gopeter** [comment]
Dear @rmosolgo,

no worries, thanks for the response!

I tried to dive again into this one and found out, that the arguments are resolved now? Using `argument :is_admin, Boolean, required: false, pundit_role: :can_set_admin` and the following policy ...

```ruby
  def can_set_admin?
    puts "####"
    puts record.arguments[:id].id
    puts user.id
    puts user.admin? && record.arguments[:id].id != user.id
    puts "####"

    user.admin? && record.arguments[:id].id != user.id
  end
```

... I get this:

```ruby
1
1
false
```

But ... I can execute the mutation without any errors. Even if I do ...

```ruby
  def can_set_admin?
    false
  end
```

... I can set this argument in the mutation without any errors. Is there anything new that I've missed?

This is my `BaseMutation` and I'm using `graphql 1.12.5` and `graphql-pro 1.17.9`:

# frozen_string_literal: true

```ruby
module Mutations
  class BaseMutation < GraphQL::Schema::RelayClassicMutation
    include GraphQL::Pro::PunditIntegration::MutationIntegration

    object_class Types::BaseMutationPayload
    field_class Types::BaseField
    argument_class Types::BaseArgument

    field :errors, Types::Scalars::Json, null: true

    def unauthorized_by_pundit(owner, value)
      # Return errors as data:
      if value.is_a?(ActiveRecord::Base)
        { errors: ["Missing required permission: `#{owner.pundit_role}` for #{value.model_name} with ID #{value.id}"] }
      else
        { errors: ["Missing required permission: `#{owner.pundit_role}`"] }
      end
    end
  end
end
```
