### ISSUE TITLE
Multiple definitions error question

### ISSUE THREAD

**Issue by bubbaspaarx** [rmosolgo/graphql-ruby#3188]
We are receiving a multiple definitions error whenever we make a change to our backend code, we can make an arbitrary change like adding a whitespace and the error will occur. oddly though, the error clears if we restart the server and will work without a problem. 

```
Multiple definitions for `Book`. Previously found Types::BookType (Class), then found Types::BookType (Class) at Query.book
```

We think it's because we have set up our query files to serve as a sort of controller where multiple queries can take place. It works but this error will pop up. I imagine if there was a significant problem with our code, we wouldn't be able to proceed with it but the server restart allows us to continue. 

How our query classes are written

```ruby
module Queries
  class Book < BaseQuery
    argument :id, ID, required: true

    type Types::BookType, null: false

    def resolve(id:)
      ::Book.find(id)
    end
  end

  class Books < BaseQuery
    argument :author_id, ID, required: false, default_value: nil

    type [Types::BookType], null: false

    def resolve(author_id:)
      if author_id
        ::Book.where(author_id: author_id).reverse
      else
        ::Book.all
      end
    end
  end
end

```

**Comment by bubbaspaarx** [comment]
Just FYI. We split the queries into two files and still getting the same error message

**Comment by dmc2015** [comment]
Are you trying to define `QueryType`'s ?
I checked the repo, `BaseQuery` isn't a thing from what I can see.

https://github.com/search?q=repo%3Armosolgo%2Fgraphql-ruby+BaseQuery&type=code

**Comment by rmosolgo** [comment]
Hey, sorry I missed this before. Usually, these errors come from incompatibility between application code and Rails autoloading. Rails assumes that each constant is defined in a file whose name corresponds to the constant name. When files are changed, it reloads any files that it determined to be dependent on the changed file. If application code doesn't comply with Rails's expectations, then a few things can happen: 

- The wrong files can be reloaded (or not) when code is changed in development 
- Stale references can be retained after a file is reloaded. (For example, when Rails reloads a GraphQL type, some _other_ type might retain a reference to the previously-defined type class.) 


Make sure that all your filenames match Rails conventions. Then, if it's still happening, please share: 

- The full error message _and_ backtrace 
- The source for any classes mentioned by the error 
- Additional source for any lines of code that reference the class mentioned by the error (one of these lines of code likely retains a stale reference to the old class) 

And then I'll reopen this issue and we can keep looking into it!
