### ISSUE TITLE
[PRO] Is "ConnectionType" a reserved word when it comes to Pundit Policy magic?

### ISSUE THREAD

**Issue by thornomad** [rmosolgo/graphql-ruby#3190]
I am using graphql-pro with Pundit integration and just ran into this issue and wanted to check if this was expected or unexpected.  I happen to have a model in my Rails app called `RemoteConnection`, so:

```ruby
module Types
  class RemoteConnectionType < Types::BaseObject
    pundit_role :show
    field :id, ID, null: false
  end
end
```

And then adding this as a field on another type:

```ruby
    field :test, Types::RemoteConnectionType, null: true
    def test
      RemoteConnection.first # => just to keep it simple
    end
```
and the policy (not really relevant I don't think but here it is anyway):

```ruby
class RemoteConnectionPolicy < ApplicationPolicy
  def show?
    true
  end

  class Scope < ApplicationPolicy::Scope
    def resolve
      scope.all
    end
  end
end
```
### the problem

When the `RemoteConnectionPolicy` is resolved for this field/type, instead of calling the policy's `show?` method it actually is trying to load the `Scope` (which isn't working because its passing the scope the instance and not the class).  Getting an error at the `scope.all` call: `undefined method 'all' for #<RemoteConnection:xxx>`

I banged my head for a while on this wondering why scope is being called and not `show?` and then had the though: _is this because of the words `ConnectionType` at the end here?_  If I change my type name to `Types::RemoteConnType` (and only change that it works).

Is `XxxxConnectionType` a reserved word?

PS: I saw the answer on my scope/batch question and have it queued to look at soon.  Thanks so much!

**Comment by rmosolgo** [comment]
It _is_ a magic word, but it's pagination-related, not Pundit-related: 

> (GraphQL-Ruby applies connection logic because the return type’s name ends in Connection. You can manually override this with `connection: true` or `connection: false`.)

(https://graphql-ruby.org/relay/connections.html#connection-fields)

or 

> If the type name ends in Connection, the field is treated as a connection field.
>
> This default may be overridden by passing a connection: true or connection: false keyword.

(https://graphql-ruby.org/schema/class_based_api.html#connection-fields--types)

So, you'll want to either: 

- Choose a different type name to avoid that magic behavior 
- Or, always use `connection: false` when a field returns `RemoteConnectionType` 
- Or, in your base field, use `connection: false` when the field's return type is `RemoteConnectionType`: 

  ```ruby 
  class Types::BaseField 
    def initialize(*args, type: nil, connection: nil, **kwargs, &block)
      # If we don't explicitly pass a `connection: true|false` here, GraphQL-Ruby will treat this field like a connection (pagination) field
      if type == Types::RemoteConnectionType 
        connection = false 
      end 
      super(*args, type: type, connection: connection, **kwargs, &block)
    end 
  end 
  ```

Let me know if that helps!

**Comment by thornomad** [comment]
Yup!  That solves it.  Was looking in the wrong place.  Thanks again for the detailed solutions.

**Comment by rmosolgo** [comment]
Glad it worked!
