### ISSUE TITLE
Are the Relay based classes deprecated in favour of the Pagination based ones?

### ISSUE THREAD

**Issue by Sam-Killgallon** [rmosolgo/graphql-ruby#3199]
Hi, thanks for the great work on this project!

I'm looking at implementing a connection to support paginating the data we fetch from Elasticsearch, and during my research through the docs and issues and I am getting the impression that the Relay based classes (ie `GraphQL::Types::Relay::BaseConnection`) are being deprecated in favour of the Pagination classes (ie `GraphQL::Pagination::Connection`), however I couldn't find anything the definitively said that was case. The closest reference I found was:
https://github.com/rmosolgo/graphql-ruby/issues/3056
> * Deprecate everything that will be removed in GraphQL-Ruby 2.0, remove docs for them:
>   * Old Relay helpers (connections, mutation, node Id)

But was unsure if that means the whole Relay framework?

We are currently using the Relay classes throughout our app and I wanted to clarify if we should start migrating over, or if there is something I am missing.

Thanks :smile:

**Comment by rmosolgo** [comment]
Yes, I expect to deprecate everything in `GraphQL::Relay`, while providing new options, for example: 

- GraphQL::Relay::Mutation -> GraphQL::Schema::RelayClassicMutation 
- GraphQL::Relay::Connection -> GraphQL::Pagination::Connection 
- GraphQL::Relay::{Node,EdgeType,ConnectionType,PageInfo} -> GraphQL::Types::Relay::{...}
- GraphQL::Relay::RangeAdd -> ?? TODO 

I think those will reflect the adoption of Relay patterns as best practices and also give me a chance to integrate them better with the rest of the gem. 

I don't expect anything to _break_ in 1.12, but I expect them to start emitting warnings, and I'll make sure they aren't in the docs anymore.

**Comment by Sam-Killgallon** [comment]
Good to know, thank you
