### ISSUE TITLE
Field-level instrumentation not working

### ISSUE THREAD

**Issue by gmac** [rmosolgo/graphql-ruby#3200]
**Describe the bug**

In upgrading to GraphQL 1.10+ (from 1.8), the `schema.instrument(:field, ...)` feature no longer seems to work as expected. Here's the setup:

```ruby
class QueryInstrumentation
  def self.before_query(query)
    puts "query started"
  end
end

class FieldInstrumentation
  def self.instrument(type, field)
    puts "#{type.name} #{field.name}"
  end
end

schema = GraphQL::Schema.from_definition("schema { ... }", default_resolve: MyResolutionHandler)
schema.instrument(:query, QueryInstrumentation)
schema.instrument(:field, FieldInstrumentation)
```

When running a query, the query instrumentation runs as expected, but the field instrumentation never fires. So, I tried using the old way:

```ruby
schema.define { instrument(:field, FieldInstrumentation) }
```

This method does now trigger instrumentation calls, however it only seems to visit fields of internal types:

```
__Type name
__Type description
__Field name
__Field description
__Field isDeprecated
__Field deprecationReason
__Directive name
__Directive description
__Directive onOperation
__Directive onFragment
__Directive onField
__EnumValue name
__EnumValue description
__EnumValue isDeprecated
__EnumValue deprecationReason
``` 

**Versions**

`graphql` version: 1.11 with `Schema.from_definition`

**Expected behavior**

In the above example, I would expect the `"#{type.name} #{field.name}"` output to describe fields defined within my own schema, such as `Post title`.

**Actual behavior**

The only fields instrumented are internal fields such as `__Field isDeprecated`.

**Additional context**

Thanks!

**Comment by rmosolgo** [comment]
Hi! In 1.10, `.from_definition` started building class-based schemas that use the new interpreter runtime. That new runtime doesn't support field instrumenters. (That was a conscious decision: field instrumenters have a big negative performance impact for big schemas.) The replacement for field instrumenters is "field extensions": https://graphql-ruby.org/type_definitions/field_extensions.html

For now, you can use `.from_definition(..., interpreter: false)` to get the old behavior. But in GraphQL-Ruby 2.0 (2021? 🤞 ), the interpreter will be the only option, just a heads up. 

Hope that helps! If you look into migrating to field extensions and run into trouble, don't hesitate to open a new issue :+1:
