### ISSUE TITLE
An idea for resolvers [documentation only]

### ISSUE THREAD

**Issue by iGEL** [rmosolgo/graphql-ruby#3201]
With great interest, I've read #1880. We started to extract more and more logic into Resolver classes, but we struggled to parametrize the resolver, to reduce duplication. We saw your proposal in #1655 and also the functions, but even better I liked your idea of using just POROs.

They're easy to understand and test. And all the definitions return type, null or arguments stay in the type. What I didn't like was the resolver method in the type definition, that mostly just forwarded the arguments.

My idea is to document an example, that works already today:

```ruby
module Types
  class UserType < Types::BaseObject
    alias user object

    field(
      :articles, [Types::ArticleType],
      null: false,
      resolve: Resolvers::ArticleResolver.attach
    ) {
      argument :published, Boolean, required: false
      argument :category_id, ID, required: false
    }
  end
end

module Resolvers
  class ArticleResolver
    # can take parameters from the field, so it's easy to reuse the same Resolver for other fields
    def self.attach
      ->(user, args, context) {
        resolver = new(user, context)
        # do other things with the resolver.
        resolver.resolve(**args)
      }
    end

    def initialize(user, context)
      @user = user
      @context = context
    end

    def resolve(published: true, category_id: nil)
      # business logic
    end

    attr_reader :user, :context
    private :user, :context
  end
end
```

Even though this has a bit of plumbing, I think it's very easy to understand and easy to modify. And also, it's easy to test, as there is no magic involved.

**Comment by rmosolgo** [comment]
Glad you found something you liked! In the interest of reducing "choice overload", I don't plan to add it to the docs. The method signature of `ArticleResolver` there is _very close_ to to `GraphQL::Schema::Resolver`. If you find that this continues to work well for you, maybe we could improve `Resolver` to work better with field-defined types and arguments, as you've shown in your sample :+1:
