### ISSUE TITLE
Int scalar type: #input_coercion does not raise error as per the spec

### ISSUE THREAD

**Issue by toneymathews** [rmosolgo/graphql-ruby#3202]
More of a question than an issue, 

As per the [spec](http://spec.graphql.org/June2018/#sec-Int), integer input value should not be less than -2^31 or greater than (2^31 -1). If so, an error needs to be raised. This does not seem to be enforced here though #coerce_result does seem to do so.

https://github.com/rmosolgo/graphql-ruby/blob/61fbc549a2c9d77bb9a8ab0e25887b48b32043f9/lib/graphql/types/int.rb#L12-L14

We were wondering why this was not enforced?

**Comment by rmosolgo** [comment]
I bet it was just an oversight in my first implementation of this scalar, and nobody has _needed_ it since then. I'm not sure why only coerce_result was updated in https://github.com/rmosolgo/graphql-ruby/pull/2101 (was there a particular reason, @eapache?)

**Comment by eapache** [comment]
🤔 not that I recall. It was either a complete oversight, or I assumed that `value.is_a?(Numeric)` would already do a bounds check (though I'm not sure why I'd think that).

**Comment by toneymathews** [comment]
Ok, will put up a PR to bind this type within the limits.
