### ISSUE TITLE
ConnectionResolver.call not being invoked on custom connection field

### ISSUE THREAD

**Issue by farism** [rmosolgo/graphql-ruby#321]
I am extending `GraphQL::ObjectType` to create a resource type that automatically sets the node interface and global id. I am also trying to create a custom `connection_field` helper that returns a connection field which accepts `order` and `filter` arguments.

Using the guide https://github.com/rmosolgo/graphql-ruby/blob/master/guides/relay.md#creating-connection-fields-by-hand

```rb
class ConnectionField < GraphQL::Field

  def initialize(type)
    self.type = type.connection_type
    self.description = ''
    self.arguments = {
      'order' => GraphQL::Argument.define do
        name 'order'
        type types.String
      end
     'filter' => GraphQL::Argument.define do
        name 'filter'
        type types.String
      end
    }
  end

  def resolve(obj, args, ctx)
    obj.comments.order(args[:order])
  end

end
```
```rb
class ResourceType < GraphQL::ObjectType

    def initialize
      super
      self.interfaces = [GraphQL::Relay::Node.interface]
      GraphQL::Define::AssignGlobalIdField.call(self, :id)
    end

    def connection_field
      ensure_defined
      GraphQL::Relay::ConnectionField.create(
        ConnectionField.new(self)
      )
    end

  end
```
```rb
CommentType = ResourceType.define

    field :body, types.String

end
```
```rb
PostType = ResourceType.define

  field :comments, CommentType.connection_field

end
```

This schema appears to work correctly. The `comments` field says it is returning a `CommentConnection`, and it gives me the option of querying `pageInfo` and `edges`. However, when I go to query either of those fields on the connection type, I get errors.

Looking into it a bit, it seems like the `ConnectionResolver` being instantiated with `GraphQL::Relay::ConnectionField.create` is not being called. Instead, the underlying resolve is being called, and an `AR:Relation` object is being passed to the connection type's `resolve`, instead of a `RelationConnection` object (hence the missing `page_info` and `edges` methods)

`PostType.fields.comments.resolve_proc` returns the `ConnectionResolver`, so I'm just not sure why it isn't being called.

**Comment by farism** [comment]
It looks like this was user error 😢 due to me being a novice Ruby programmer. Moving the `resolve` into `initialize` and assigning to `self` fixed the issue:

```rb
self.resolve = ->(obj, args, ctx) {
  obj.reports.order(args[:order])
}
```

Having a little difficulty understanding the difference between class/instance references I suppose.

**Comment by rmosolgo** [comment]
Extending built-in classes is not supported, with the exception of `BaseConnection` or `Edge`.

How about programmatically generating a Field instance instead? For example 

```ruby 
module OrderAndFilterField 
  # Make a GraphQL::Field which returns `return_type`
  # and applies `args["filter"]` and `args["order"]` to the result of the given block.
  def self.build(return_type, &get_items_proc) 
    GraphQL::Field.define do 
      type return_type
      argument :order, types.String 
      argument :filter, types.String
      resolve -> (obj, args, ctx) { 
        items = get_items_proc.call(obj, args, ctx) 
        if args["filter"]
          items = items.filter(args["filter"])      
        end 
        if args["order"]
          items = items.order(args["order"])
        end 
        items 
      }
    end 
  end 
end 

# ... 
connection :comments, OrderAndFilterField.build(CommentType.connection_type) { |obj, args, ctx| obj.comments } 
```

Would something like that work?

**Comment by farism** [comment]
I ended up doing something similar (although I am still extending `GraphQL::ObjectType` 😐 ... will probably migrate all the helper defs over to builder defs like in your suggestion). 

I was able to accomplish this by using `accept_definitions` on `GraphQL::Field`. Is this supported behavior?

```rb
GraphQL::Field.accepts_definitions(
  sortable: GraphQL::Define.assign_metadata_key(:sortable),
  filterable: GraphQL::Define.assign_metadata_key(:filterable)
)
```
```rb
class Type < GraphQL::ObjectType

    def order_type
      ensure_defined
      type = self

      GraphQL::EnumType.define do
        name "#{type.name}Order"
        type.fields.each do |name, field|
          if field.metadata[:sortable]
            value "#{field.property || name}_ASC".upcase, value: "#{field.property || name} ASC"
            value "#{field.property || name}_DESC".upcase, value: "#{field.property || name} DESC"
          end
        end
      end
    end

    def filter_type
      ensure_defined
      type = self

      GraphQL::InputObjectType.define do
        name "#{type.name}Filter"
        type.fields.each do |name, field|
          if field.metadata[:filterable]
            input_field name.to_sym, FilterOperator::Type
          end
        end
      end
    end

    def connection_type
      self.define_connection do
        field :totalCount do
          type types.Int
          resolve -> (obj, args, ctx) { obj.object.count }
        end
      end
    end

    def connection_field
      ensure_defined
      type = self

      GraphQL::Relay::ConnectionField.create(
        GraphQL::Field.define do

          type type.connection_type

          description ''

          if type.order_type.values.length > 0
            argument :order, types[type.order_type], ''
          end

          if type.filter_type.input_fields.length > 0
            argument :filter, filter_type, ''
          end

          resolve -> (obj, args, ctx) {
            relation = obj.send(:reports)

            if args[:filter]
              # puts args[:filter].to_h
              args[:filter].each do |name, filter|
                filter.each do |operator, value|
                  relation = relation.where("#{name} #{FilterOperator.to_sql_operator(operator)} ?", value)
                end
              end
            end

            if args[:order]
              relation = relation.order(args[:order].join(', '))
            end

            relation
          }
        end
      )
    end

  end

**Comment by rmosolgo** [comment]
> using `accept_definitions` on `GraphQL::Field`. Is this supported behavior?

yep! that's the go-to spot for custom data attached to graphql objects. 

I'm glad you found something that works! Just my two cents, but I think you could get the _convenience_ of a monkey-patch and the _portability_ of a pure function by implementing monkey patches this way: 

```ruby 
class GraphQL::ObjectType < GraphQL::BaseType 
  def order_type
    ensure_defined 
    OrderType.build(self) 
  end 
end 

module OrderType 
  def self.build(object_type) 
    # do stuff here 
  end 
end 
```

That way, your footprint in the "host" class (`GraphQL::ObjectType`) is quite small, and it's clear to a reader that no private methods from the "host" class are required for the `build` function. Just a thought, good luck! :D

**Comment by farism** [comment]
Thank you for your time/feedback!
