### ISSUE TITLE
GraphQL::Pro::AblySubscriptions doesn't support cipher key.

### ISSUE THREAD

**Issue by zreisman** [rmosolgo/graphql-ruby#3214]
`#deliver` and `#still_subscribed?` must be overridden to use Ably encryption.

```
@ably.channel(subscription_id, cipher: { key: ENV['ABLY_ENCRYPTION_KEY'] })
```

**Comment by rmosolgo** [comment]
Hey, thanks for mentioning this. I received a similar request by email, and I'm hoping to ship support for it this week! I'll follow up here when it's ready.
