### ISSUE TITLE
Option to skip updating the server side and only create the output file

### ISSUE THREAD

**Issue by justin808** [rmosolgo/graphql-ruby#3218]
**Is your feature request related to a problem? Please describe.**
Deployment is React on Rails pro where we have SSR of React.

We would like to have the creation of the output JSON file done as part of the build process before running webpack.

Then during the release phase on Heroku, we run the DB sync after DB migrations.

**Describe the solution you'd like**

Need to be able to omit the `--url` of the command, as shown here: https://graphql-ruby.org/operation_store/client_workflow#syncing 

![image](https://user-images.githubusercontent.com/1118459/98863094-f3e45600-240b-11eb-8e70-f1c384e4fcec.png)

We'd change:

https://github.com/rmosolgo/graphql-ruby/blob/master/javascript_client/src/sync/index.ts#L44-L47

```js
  var url = options.url
  if (!url) {
    throw new Error("URL must be provided for sync")
  }
```

to allow having no URL.

**Describe alternatives you've considered**

The full details of what we've been trying to do are are spelled out in here [#3067: OperationStore docs should include deployment sequence notes](https://github.com/rmosolgo/graphql-ruby/issues/3067#issuecomment-682411205).

If we can't get confirmation on this suggestion to change the `graphql-ruby-client` params, we'll create a separate NPM package that has the functionality that we need.
 

**Additional context**

TBD

**Comment by rmosolgo** [comment]
:+1: I think it's a great idea, I started exploring it a bit here: https://github.com/rmosolgo/graphql-ruby/pull/3219 

If that looks like what you had in mind, I'm happy to go with it; also happy to take another PR if you were thinking of something else!

**Comment by justin808** [comment]
@rmosolgo Looks great. Any idea if you can push a beta (or real release) to make this easier for us to try this out?

**Comment by rmosolgo** [comment]
Yep, 🚢 in `graphql-ruby-client` 1.8.1! Let me know how it goes when you get to give it a try.
