### ISSUE TITLE
Caching and early returning

### ISSUE THREAD

**Issue by matthewjf** [rmosolgo/graphql-ruby#3220]
**Is your feature request related to a problem? Please describe.**

We'd like to build a caching solution for graphql-ruby, using the new interpreter. This solution should not execute resolver code on a cache hit.

**Describe the solution you'd like**

We'd like a way to stop and early return during execution, ideally at the field level, but the query level could work as well.

A possible solution to this is a public API for setting the query result in instrumentation.

**Describe alternatives you've considered**

We could try handling caching outside of graphql-ruby. We'd like to use `Query#fingerprint` for cache keys. I suspect we could instantiate the query with the schema and query param and call `#fingerprint`. That would mean we could only cache the whole response. Ideally we could come up with a way to cache field level responses, but don't know how feasible that would be.

**Additional context**

It's early and we're digging around trying to figure out what options are available to us.

I couldn't find any documentation on field level instrumentation. Also couldn't get it to run any field level instrumentation when trying to create a sample.

Couple of existing solutions and why they don't work for us:
- [graphql-cache](https://github.com/stackshareio/graphql-cache): doesn't work with the new interpreter
- [graphql-ruby-fragment_cache](https://github.com/DmitryTsepelev/graphql-ruby-fragment_cache): still runs all the code to instantiate records and build the responses as far as I can tell, which would defeat the purpose

I also tried something like so
```ruby
module CacheInstrumentation
  module_function

  def before_query(query)
    if Rails.cache.read(query.fingerprint)
      query.result_values = Rails.cache.read(query.fingerprint)

      Rails.logger.info('~~~~~~~~~~~~~~~~~~~~~~~~~ CACHE HIT ~~~~~~~~~~~~~~~~~~~~~~~~~')
    end
  end

  def after_query(query)
    Rails.cache.write(query.fingerprint, query.result_values, expires_in: 1.hour)
  end
end
```

but get the totally expected error:
```
     RuntimeError:
       Invariant: Can't reassign result
```

Mostly looking for some feedback. Maybe there's something we aren't thinking of.

We'd also like to be able to see the return values of each `Resolver#resolve` if those are active record objects. This would help us with cache expiration when the underlying records change. This is a bit of a secondary concern.

**Comment by matthewjf** [comment]
I misunderstood the fragment cache implementation: https://github.com/DmitryTsepelev/graphql-ruby-fragment_cache

We tested it and it helped a bit, but we think we could really improve on that if there was a way to early return a field with a cached response.

**Comment by swalkinshaw** [comment]
I believe that fragment cache gem uses the `raw_value` feature that @DmitryTsepelev added in https://github.com/rmosolgo/graphql-ruby/pull/2699.

If a field's resolver returns data with `raw_value` then no child field/resolvers are executed so it should do exactly what you want.

**Comment by matthewjf** [comment]
@swalkinshaw thanks! I'll dig into that and close the issue for now.

**Comment by DmitryTsepelev** [comment]
> If a field's resolver returns data with raw_value then no child field/resolvers are executed so it should do exactly what you want.

Exactly! The idea is that when there is a cache hit we stop executing the field (and nested subtree) and return the cached value [as is](https://github.com/DmitryTsepelev/graphql-ruby-fragment_cache/blob/master/lib/graphql/fragment_cache/object_helpers.rb#L33), [otherwise](https://github.com/DmitryTsepelev/graphql-ruby-fragment_cache/blob/master/lib/graphql/fragment_cache/object_helpers.rb#L36) — call the defined resolver.

@matthewjf Feel free to reach me out if you have any questions, problems or ideas
