### ISSUE TITLE
Error executing mutation with additional fields

### ISSUE THREAD

**Issue by antarr** [rmosolgo/graphql-ruby#3221]
**Describe the bug**

I get an error when calling a mutation using query variables. It works fine if I only include `email` ,`password` and `passwordconfirmation`. After adding `first_name` and `last_name` I get an error.
**Versions**

`graphql` version: 1.11.4
`rails` : 6.0
`graphql_playground-rails` : 2.1.0

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok).
Are you using [interpreter](https://graphql-ruby.org/queries/interpreter.html)? Any custom instrumentation, etc?

```ruby
module Mutations
  class CreateUser < Mutations::BaseMutation
    argument :email, String, required: true
    argument :password, String, required: true
    argument :passwordconfirmation, String, required: true
    argument :first_name, String, required: false
    argument :last_name, String, required: false

    field :user, Types::UserType, null: true
    field :token, String, null: true

    def resolve(email:, password:, passwordconfirmation:, first_name: nil, last_name: nil)
      user = User.new(password: password, password_confirmation: passwordconfirmation, email: email)
      user.build_profile
      user.save
      if first_name || last_name
        user.profile.first_name = first_name
        user.profile.last_name = last_name
        user.profile.save
      end

      # current_user needs to be set so authenticationToken can be returned
      context[:current_user] = user

      MutationResult.call(
        obj: { user: user },
        success: user.persisted?,
        errors: user.errors
      )
    rescue ActiveRecord::RecordInvalid => e
      GraphQL::ExecutionError.new(
        "Invalid Attributes for #{e.record.class.name}: " \
        "#{e.record.errors.full_messages.join(', ')}"
      )
    end
  end
end

# frozen_string_literal: true

module Mutations
  class BaseMutation < GraphQL::Schema::RelayClassicMutation
    # Add your custom classes if you have them:
    # This is used for generating payload types
    object_class Types::BaseObject

    # This is used for return fields on the mutation's payload
    field_class Types::BaseField

    # This is used for generating the `input: { ... }` object type
    input_object_class Types::BaseInputObject

    # https://github.com/rmosolgo/graphql-ruby/issues/1837
    field :success, Boolean, null: false
    field :errors, [String], null: true

    protected

    def authorize_user
      return true if current_user.present?

      raise GraphQL::ExecutionError, 'User not signed in'
    end

    def current_user
      context[:current_user]
    end
  end
end

```

**GraphQL query**

```graphql
mutation createUser($input: CreateUserInput!){
  createUser(input: $input){
    user{
      firstName
      lastName
      authenticationToken
    }
    errors
  }
}
```

```json
{
  "input": {
      "passwordconfirmation": "Password123!",
      "password": "Password123!",
      "email": "user+12@example.com",
    	"firstName": "Tony",
    	"lastName": "Montana"
    }
}
```

**Steps to reproduce**

Execute query and graphql playground

**Expected behavior**

Respond like 
```
{
  "data": {
    "createUser": {
      "user": {
        "firstName": "Tony",
        "lastName": "Montana",
        "authenticationToken": "SVC88NxuKGUwZ_mG9i7Q"
      },
      "errors": []
    }
  }
}
```
**Actual behavior**

Responds with error
```

  "errors": [
    {
      "message": "Variable $input of type CreateUserInput! was provided invalid value for first_name (Field is not defined on CreateUserInput), last_name (Field is not defined on CreateUserInput)",
      "locations": [
        {
          "line": 1,
          "column": 21
        }
      ],
      "extensions": {
        "value": {
          "passwordconfirmation": "Password123!",
          "password": "Password123!",
          "email": "user+12@example.com",
          "first_name": "Tony",
          "last_name": "Montana"
        },
        "problems": [
          {
            "path": [
              "first_name"
            ],
            "explanation": "Field is not defined on CreateUserInput"
          },
          {
            "path": [
              "last_name"
            ],
            "explanation": "Field is not defined on CreateUserInput"
          }
        ]
      }
    }
  ]
}
```

**Comment by rmosolgo** [comment]
Hi, thanks for the detailed writeup! I think you should swap `first_name` => `firstName` and `last_name` => `lastName`. 

By default, GraphQL-Ruby converts underscore-cased field and argument names (Ruby-style) to camelized field and argument names (GraphQL-style). To disable that, see: https://graphql-ruby.org/fields/introduction.html#field-parameter-default-values

Does that help? 

I see that your example query uses camelized input names: 

```
{
  "input": {
      "passwordconfirmation": "Password123!",
      "password": "Password123!",
      "email": "user+12@example.com",
    	"firstName": "Tony",
    	"lastName": "Montana"
    }
}
```

But the error from GraphQL-Ruby suggests that it received underscored names: 

```
      "extensions": {
        "value": {
          "passwordconfirmation": "Password123!",
          "password": "Password123!",
          "email": "user+12@example.com",
          "first_name": "Tony",
          "last_name": "Montana"
        },
```

If switching the case doesn't help, please share:

- the output of `MySchema.to_definition`, at least the part that says `input CreateUserInput { ... }`. 
- the rails log output for: starting your app in development and replicating this issue 

Let me know what you find!

**Comment by antarr** [comment]
@rmosolgo Thanks for the response. I've already tried changing the casing of the params in the mutation definition. I think that is what you are suggesting. Below is a picture of the schema

![Snip20201117_1](https://user-images.githubusercontent.com/974295/99403854-8d9a8000-28b0-11eb-976e-58f7a0824214.png)

The JSON export is [here](https://gist.github.com/antarr/9bc5058f7efde393ebecfcb24924a9fc)

**Comment by rmosolgo** [comment]
Thanks. Could you please share the Rails logs from replicating the issue, too? That will help me confirm exactly what inputs GraphQL-Ruby is receiving.

**Comment by antarr** [comment]
This is what I get in the log when the request is posted

```
Started POST "/graphql" for ::1 at 2020-11-17 21:39:43 -0600
Processing by GraphqlController#execute as */*
  Parameters: {"operation_name"=>"createUser", "variables"=>{"input"=>{"passwordconfirmation"=>"[FILTERED]", "password"=>"[FILTERED]", "email"=>"user+12@example.com", "first_name"=>"Tony", "last_name"=>"Montana"}}, "query"=>"mutation createUser($input: CreateUserInput!) {\n  createUser(input: $input) {\n    user {\n      firstName\n      lastName\n      authenticationToken\n    }\n    errors\n  }\n}\n", "graphql"=>{"operation_name"=>"createUser", "variables"=>{"input"=>{"passwordconfirmation"=>"[FILTERED]", "password"=>"[FILTERED]", "email"=>"user+12@example.com", "first_name"=>"Tony", "last_name"=>"Montana"}}, "query"=>"mutation createUser($input: CreateUserInput!) {\n  createUser(input: $input) {\n    user {\n      firstName\n      lastName\n      authenticationToken\n    }\n    errors\n  }\n}\n"}}
Can't verify CSRF token authenticity.
[active_model_serializers] Rendered ActiveModel::Serializer::Null with GraphQL::Query::Result (0.18ms)
Completed 200 OK in 7ms (Views: 0.9ms | ActiveRecord: 0.0ms | Allocations: 4539)


```

**Comment by antarr** [comment]
I was able to get around it for now by not using casing at all. So I have pass as `firstname` instead of `firstName` or `first_name`

**Comment by rmosolgo** [comment]
I see in the logs above that rails received underscored inputs: 

> `"first_name"=>"Tony", "last_name"=>"Montana"`

The screenshot of your docs panel suggests that the input expects `firstName` and `lastName`. 

When I see those two things, it looks to me like the client is sending the wrong input. It should send `firstName` (as shown in the docs panel) but Rails logged `first_name`. 

Can you update the client to send `firstName` instead of `first_name`?

**Comment by antarr** [comment]
> I see in the logs above that rails received underscored inputs:
> 
> > `"first_name"=>"Tony", "last_name"=>"Montana"`
> 
> The screenshot of your docs panel suggests that the input expects `firstName` and `lastName`.
> 
> When I see those two things, it looks to me like the client is sending the wrong input. It should send `firstName` (as shown in the docs panel) but Rails logged `first_name`.
> 
> Can you update the client to send `firstName` instead of `first_name`?

I'm not sure why the server is receiving `first_name` I'm passing it as `firstName`

**Comment by rmosolgo** [comment]
I'm not sure either! Are you using a client library to interact with the server. Since we're debugging the client, why not share some client code?
