### ISSUE TITLE
Examples for mutation field arguments

### ISSUE THREAD

**Issue by panSarin** [rmosolgo/graphql-ruby#3231]
**I think documentation is missing important part**

API documentation is missing any examples of passing arguments to field in mutation.

As we can see in https://graphql-ruby.org/fields/arguments.html :

*Fields can take arguments as input. These can be used to determine the return value (eg, filtering search results) or to modify the application state (eg, updating the database in MutationType).*

But we only have examples of passing arguments to query fields

**It would be great to have any example**

How to pass it in graphql query and how to access it in field method.

**Comment by rmosolgo** [comment]
Hi! There's an example mutation class here: https://graphql-ruby.org/mutations/mutation_classes. It includes some example argument definitions. If you think that it should have more detail, please use the "Edit this page" link to make a suggestion!
