### ISSUE TITLE
Graphql s3 caching

### ISSUE THREAD

**Issue by nmelon** [rmosolgo/graphql-ruby#3232]
Hi, we have one public type we would like to cache, we would want to save a query response as JSON in s3 and then check whether the hash of some request params matches the saved hash, is it possible to do using a ready function. I.e. check if the cached hash exists already send the s3 response and if not continue query? Or they may be a better solution for such use case? Thank you.

**Comment by rmosolgo** [comment]
Hi! Thanks for the question. I don't have a great solution to this, but you could check out: 

- A different approach to caching: https://github.com/DmitryTsepelev/graphql-ruby-fragment_cache
- Query#fingerprint, which may serve as the basis for your cached response: https://github.com/rmosolgo/graphql-ruby/blob/3d11f0f2eeb51b7d82172d90d947b631e96d5de6/lib/graphql/query.rb#L271-L285


But besides that, I don't know of any existing work on a system like you're describing. I hope those are helpful!
