### ISSUE TITLE
Argument of type 'ActionCableLink' is not assignable to parameter of type 'ApolloLink | RequestHandler'

### ISSUE THREAD

**Issue by 1awaleed** [rmosolgo/graphql-ruby#3236]
**Describe the bug**
I am trying to integrate graphql-ruby-client with my `apollo-client` frontend which is written in typescript. 

Initializing wss link
```typescript 
import ActionCable from 'actioncable';
import ActionCableLink from 'graphql-ruby-client/dist/subscriptions/ActionCableLink';

const cable = ActionCable.createConsumer(backendwss);
const wsLink = new ActionCableLink({ cable });
```

then when I am trying to pass the newly created `wslink` to the `ApolloClient`

```typescript
const client = new ApolloClient({
  link: rootLink,
  cache: new InMemoryCache(),
});

```

A clear and concise description of what the bug is:

Typescript is complaining:
`Argument of type 'ActionCableLink' is not assignable to parameter of type 'ApolloLink | RequestHandler'.`
`Type 'ActionCableLink' is missing the following properties from type 'ApolloLink': onError, setOnError`

**Versions**
`graphql-ruby-client`: "^1.8.1"
`actioncable`: "^5.2.4-4"
`graphql`: "^15.3.0"
`apollo-client`: "^3.1.3"

**Comment by rmosolgo** [comment]
Hi, thanks for the bug report here! It sounds like that class will need a few more methods to pass Apollo's typechecking. Here's the source for that class: 

https://github.com/rmosolgo/graphql-ruby/blob/3d11f0f2eeb51b7d82172d90d947b631e96d5de6/javascript_client/src/subscriptions/ActionCableLink.ts#L8

(Interesting that it uses `extends ApolloLink`, I wonder why TypeScript isn't finding those "inherited" methods!?)

**Comment by 1awaleed** [comment]
> Hi, thanks for the bug report here! It sounds like that class will need a few more methods to pass Apollo's typechecking. Here's the source for that class:
> 
> https://github.com/rmosolgo/graphql-ruby/blob/3d11f0f2eeb51b7d82172d90d947b631e96d5de6/javascript_client/src/subscriptions/ActionCableLink.ts#L8
> 
> (Interesting that it uses `extends ApolloLink`, I wonder why TypeScript isn't finding those "inherited" methods!?)

Hi @rmosolgo , no problem. I think that [apollographql/apollo-link](https://github.com/apollographql/apollo-link) is now deprecated and is currently still a dependency here:
https://github.com/rmosolgo/graphql-ruby/blob/3d11f0f2eeb51b7d82172d90d947b631e96d5de6/javascript_client/package.json#L30

`Apollo-link` has moved to [`apollo-client`](https://github.com/apollographql/apollo-client) after apollo client launched version 3.x.

I have updated my issue to include my `apollo-client` version number.

**Comment by marlosirapuan** [comment]
Same here, i fixed (for now), with this:

```ts
const link = ApolloLink.from([
  createErrorLink,
  createLinkWithToken,
  ApolloLink.split(
    hasSubscriptionOperation,
    createActionCableLink() as any, // <-- FIX
    createHttpLink
  )
])
```

**Comment by 1awaleed** [comment]
@marlosirapuan Yes this is a solution to bypass typescript and I have one. I am just raising a flag that there is a problem here.

**Comment by sirwolfgang** [comment]
I just ran into this, while chasing it down notice that the lib is still using the `apollo-link` package, which has now been superseded by the `@apollo/client` package. The current version of the client looks to implement the "missing" methods.

**Comment by rmosolgo** [comment]
🚢 js 1.9.0 with @sirwolfgang 's upgrade to this project's dependencies. If you encounter an error on that issue, please open a new issue!
