### ISSUE TITLE
`[Scalar]` input value passed for `Scalar` input field is not property validated

### ISSUE THREAD

**Issue by myronmarston** [rmosolgo/graphql-ruby#3237]
**Describe the bug**

With a schema like:

``` graphql
input MyInput {
  foo: Int
}
```

...when `foo: [3]` is passed in a query, the GraphQL gem automatically rejects the query with an error like `"message": "Argument 'foo' on InputObject 'MyInput' has an invalid value ([3]). Expected type 'Int'."`

But when you change `foo` to use a custom scalar type, and the client passes an array of scalar values, no similar error results -- instead the value gets through to the resolver logic.

While the GraphQL gem can't do complete custom scalar validation, scalars are not arrays, and I do not think it is ever valid for a client to pass an array for a non-array scalar input field.  For consistency with non-custom scalars, I think the graphql gem should reject such a query with a similar error.

**Versions**

`graphql` version: 1.11.6

**GraphQL schema**

```graphql
  scalar Long

  type Query {
    echoInt(int: Int!): Int
    echoLong(long: Long!): Long
  }
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
  query {
    echoLong(long: [7])
  }
```

**Steps to reproduce**

Create a `graphql_bug.rb` file with these contents:

``` ruby
require 'graphql'
require 'json'

SCHEMA_STRING = <<~EOS
  scalar Long

  type Query {
    echoInt(int: Int!): Int
    echoLong(long: Long!): Long
  }
EOS

class Application
  def initialize
    @schema = GraphQL::Schema.from_definition(SCHEMA_STRING, default_resolve: self)
  end

  def execute_query(query_string)
    puts "=" * 80
    puts "Executing query:"
    puts query_string
    puts

    begin
      response = @schema.execute(query_string)

      puts
      puts "Got a response:"
      puts JSON.pretty_generate(response)
    rescue => e
      puts
      puts "Got an exception:"
      puts e.inspect
    end
  end

  def call(parent_type, field, object, args, context)
    bad_args = args.select { |k, v| v.is_a?(Array) }

    if bad_args.any?
      raise "Bad arguments: #{bad_args.inspect}"
    end

    case field.name
    when "echoInt" then args.fetch(:int)
    when "echoLong" then args.fetch(:long)
    else
      raise "Unrecognized field: #{field.inspect}"
    end
  end
end

app = Application.new

app.execute_query(<<~EOS)
  query {
    echoInt(int: 7)
  }
EOS

app.execute_query(<<~EOS)
  query {
    echoLong(long: 7)
  }
EOS

app.execute_query(<<~EOS)
  query {
    echoInt(int: [7])
  }
EOS

app.execute_query(<<~EOS)
  query {
    echoLong(long: [7])
  }
EOS
```

Run the script.  The output is:

```
Executing query:
query {
  echoInt(int: 7)
}


Got a response:
{
  "data": {
    "echoInt": 7
  }
}
================================================================================
Executing query:
query {
  echoLong(long: 7)
}


Got a response:
{
  "data": {
    "echoLong": 7
  }
}
================================================================================
Executing query:
query {
  echoInt(int: [7])
}


Got a response:
{
  "errors": [
    {
      "message": "Argument 'int' on Field 'echoInt' has an invalid value ([7]). Expected type 'Int!'.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "query",
        "echoInt",
        "int"
      ],
      "extensions": {
        "code": "argumentLiteralsIncompatible",
        "typeName": "Field",
        "argumentName": "int"
      }
    }
  ]
}
================================================================================
Executing query:
query {
  echoLong(long: [7])
}


Got an exception:
#<RuntimeError: Bad arguments: {:long=>[7]}>
```

**Expected behavior**

The last query in the script should get a response like the 2nd-to-last query: a clear error from the GraphQL gem.

**Actual behavior**

The GraphQL gem calls the resolver logic even though the query is invalid.

**Comment by rmosolgo** [comment]
Hi, thanks for the detailed writeup and replication script. This is a great point. 

> scalars are not arrays

Funny enough, there _is_ an exception to that rule. GraphQL-Ruby has a "JSON" scalar that accepts _any_ structure as input. But I agree with your point; JSONType should be an _exception_ to the rule, and the script you posted should work the way you suggest.

**Comment by rmosolgo** [comment]
In the end, I'm not totally convinced that the default behavior (accepting any input) should be changed. In general, custom scalars should define `coerce_input` and `coerce result` hooks, which addresses this issue. Here's how the script above could be modified: 

```ruby 
class Application 
  # ...
  def coerce_input(type, value, ctx)
    case type.graphql_name
    when "Long"
      if value.is_a?(Integer)
        value
      else
        nil
      end
    else
      raise "Unknown custom scalar: #{type.graphql_name.inspect}"
    end
  end
  
  # ...
end 
```

Then, the script prints the expected result: 


```
Executing query:
query {
  echoLong(long: [7])
}


Got a response:
{
  "errors": [
    {
      "message": "Argument 'long' on Field 'echoLong' has an invalid value ([7]). Expected type 'Long!'.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "query",
        "echoLong",
        "long"
      ],
      "extensions": {
        "code": "argumentLiteralsIncompatible",
        "typeName": "Field",
        "argumentName": "long"
      }
    }
  ]
}
```

If there's some reason a solution like that won't work for you, please let me know!

**Comment by myronmarston** [comment]
I didn't know about `coerce_input` but it looks like that'll work.  Is there documentation on `coerce_input` and `coerce_results` somewhere?

**Comment by rmosolgo** [comment]
Yep!

- Class-based: https://graphql-ruby.org/type_definitions/scalars.html#custom-scalars
- SDL-based: https://graphql-ruby.org/schema/sdl.html#implementation-object

**Comment by myronmarston** [comment]
Thanks, I hadn't seen that.  The class-based docs are particularly helpful (they do a better job of explaining the contract of these methods).  I'm curious about your example, though; [the class documentation](https://graphql-ruby.org/type_definitions/scalars.html#custom-scalars) says that `GraphQL::CoercionError` should be raised on invalid input, but in your example you return `nil` for invalid input.  Is the SDL-based callback intended to handle invalid input in a different way?  Or does raising `GraphQL::CoercionError` work there, too?  (And likewise, does returning `nil` from a custom scalar class's callback also get treated the same way?)

**Comment by rmosolgo** [comment]
I'd _expect_ them to work the same way -- `.from_definition` parses the SDL and builds classes, then implements methods on those classes using the given `default_resolver:`. But I could be wrong 😅 If you give it a try, let me know if you run into any trouble (or, update those docs!).
