### ISSUE TITLE
Followups to updating operation store without starting the Rails server

### ISSUE THREAD

**Issue by justin808** [rmosolgo/graphql-ruby#3239]
**Is your feature request related to a problem? Please describe.**

The issue the followup to [Support generating outfile without a URL #3219](https://github.com/rmosolgo/graphql-ruby/pull/3219) and [Option to skip updating the server side and only create the output file #3218](https://github.com/rmosolgo/graphql-ruby/issues/3218)

We need a rake task to update the database using the operationStore.json data.

**Describe the solution you'd like**

See below for deficiencies that could be addressed in the Gem.

**Describe alternatives you've considered**

We can hack it, but then our solution is brittle to changes in the base gen.

# Current Deficiencies

## 1. Need data parsed from the output file requiring this logic:

https://github.com/rmosolgo/graphql-ruby/blob/3aaaf5a33cc2820ddeb53b5d7376eea42f8aa08f/javascript_client/src/sync/generateClient.ts#L47-L91

We'd like the cli to generate a file similar to operationStore.json but with such structure:

```json
        [
          {
            "name": "...",
            "alias": "...",
            "body": "..."
          },
          ...
        ]
```

Without this, we need to do something like:

```js
const { gatherOperations } = require('graphql-ruby-client/dist/sync/generateClient');
const ops = gatherOperations({
  path: 'app/javascript/libs/gql/**/*.gql',
  mode: 'project',
  addTypename: true,
  clientType: 'json',
  client: 'PopmenuClientDev',
  verbose: false
})
```

## 2. We need logic in private pro Ruby code

Another issue is that it’s not that simple for the backend to just parse this resulting JSON and to then insert them into tables. There is some complicated logic inside the gem so we need to use internal functions to insert/update operations. I attached a file where this procedure performing.

So, we need to copy and paste this part of pro code into our rake task and rewrite it:

`graphql/pro/operation_store/endpoint.rb`

We'd have something like this:

```ruby
              payload = JSON.parse(payload_json)
              operations = payload.fetch("operations")
              response_data = {
                added: [],
                not_modified: [],
                failed: [],
                errors: {},
              }
              response_code = 200
              committed = true
              @operation_store = schema.operation_store || raise("Can't mount endpoint; Schema is not configured for OperationStore")

              @operation_store.transaction do |rollback|
                operations.each do |operation|
                  op_alias = operation.fetch("alias")
                  op_result = @operation_store.add(
                    body: operation.fetch("body"),
                    operation_alias: op_alias,
                    client_name: client_name
                  )
                  if op_result.added?
                    response_data[:added] << op_alias
                  elsif op_result.not_modified?
                    response_data[:not_modified] << op_alias
                  elsif op_result.failed?
                    response_data[:failed] << op_alias
                    response_data[:errors][op_alias] = op_result.errors
                    break
                  end
```       

The main part of the logic is that we'd be calling: `graphql/pro/operation_store.rb`

```ruby
      # Ensure that `body` is registered to `client_name` as `client_alias`.
      # This may insert several records:
      #
      # - Add an operation if `body` is not found
      # - Add a client_operation if `operation_alias` is not found for this client
      #
      # Or, if all those are found, it performs no changes.
      #
      # The addition is run in a transaction. If the `add` fails,
      # the whole transaction is rolled back.
      #
      # @param body [String] GraphQL string containing one operation
      # @param client_name [String] Name of a client
      # @param operation_alias [String] This client's alias for `body`
      # @return [OperationStore::AddOperation::AddResult]
      def add(body:, client_name:, operation_alias:)
```

## Solution?

Would it make sense for us to use our hacks or to have the base Gem address deficiencies 1 and 2 above?

Would you be open to a PR on Deficiency 1, either adding a param to change the output format or only generating the more useful output format?

**Comment by rmosolgo** [comment]
Hey, thanks for opening this feature request! Let's see... 

Regarding the first point, it looks like you want to use the result of `gatherOperations` to generate a different kind of outfile, is that right? I think that's fine. I haven't supported this as a public API so far, but I'm willing to treat it more carefully if you'd like to use it that way. 

On the second point, it sounds like you want to call `OperationStore#add` _outside_ of the `Endpoint` class, is that right? That should be fine; again, I haven't considered this public, but if you want to make custom use of it, I can add some examples to the test suite to make sure I don't break it in the future 👍  

Both of those suggestions seem fine to me. As far as gem support, I'm not interested in upstreaming these yet, since I don't know of a general interest in them or need for them. But like I said, I'd be happy to improve the compatibility guarantees on these functions to support your use case! Would that do the job here?
