### ISSUE TITLE
Graphql Pagination

### ISSUE THREAD

**Issue by adrianotadao** [rmosolgo/graphql-ruby#324]
Hello!
I have a question… imagine that you have 100 entries on database, when you call "first:3" from graphql pagination, Will rails pick the 100 entries and the graphql will paginate them? Have we another way to do that?

Thank you!

**Comment by rmosolgo** [comment]
`GraphQL::Relay::RelationConnection` uses `limit` and `offset` to do a small database query. However, this is currently broken on Rails 3 :( https://github.com/rmosolgo/graphql-ruby/issues/302

**Comment by adrianotadao** [comment]
@rmosolgo Thanks for your answer, the problem is the way that I was doing here.

Thanks a lot man!
