### ISSUE TITLE
respond_to? or respond_to_missing? in query_type.rb

### ISSUE THREAD

**Issue by tbpeder** [rmosolgo/graphql-ruby#3241]
In an effort to keep my code DRY, I would like to implement some dynamic methods in query_type.rb so I don't have to implement finder methods for every single class in my app.

However, neither method seems to be firing.

    def respond_to_missing?
      Rails.logger.info "RESPOND TO MISSING"
    end

    def respond_to?
      Rails.logger.info "RESPOND TO"
    end

**Comment by rmosolgo** [comment]
Here's how you might use `def method_missing(...)` and `def respond_to_missing?(...)` in a GraphQL type: 

```ruby 
require "bundler/inline"

gemfile do
  source 'https://rubygems.org'
  gem 'graphql'
end

class Query < GraphQL::Schema::Object
  field :one, Integer, null: false
  field :two, Integer, null: false
  field :three, Integer, null: false

  def method_missing(method_name, *args, &block)
    case method_name
    when :one
      1
    when :two
      2
    else
      super
    end
  end

  def respond_to_missing?(method_name, include_private)
    case method_name
    when :one, :two
      true
    else
      super
    end
  end
end

class Schema < GraphQL::Schema
  query(Query)
  use GraphQL::Execution::Interpreter
  use GraphQL::Analysis::AST
end

pp Schema.execute("{ one two }").to_h
# => {"data"=>{"one"=>1, "two"=>2}}
pp Schema.execute("{ three }").to_h
# (RuntimeError) Failed to implement Query.three, tried:
#
# - `Query#three`, which did not exist
# - `NilClass#three`, which did not exist
# - Looking up hash key `:three` or `"three"` on ``, but it wasn't a Hash
#
# To implement this field, define one of the methods above (and check for typos)
```

(`{ three }` fails because `def respond_to_missing?` returns false for that `method_name`.)

How does that compare with what you're trying to do? 

If that doesn't help, could you please share the full source for the GraphQL type when you tried to add this, and the result you got when you tried to run a query?

**Comment by tbpeder** [comment]
Normally, in query_type.rb, you would implement the following for every object in the API.

    field :contact, Types::ContactType, null: false do
      argument :id, ID, required: true
    end

    def contacts
      current_tenant.contacts.all
    end

    def contact(id:)
      current_tenant.contacts.find(id)
    end

In the code below, I have generalized the last two methods (for contacts and contact(:id)). 

    def method_missing(method_name, *args, &block)      
      field = method_name.to_s.singularize
      obj_class = Object.const_get(field.classify)

      if field == method_name.to_s
        [obj_class.where(tenant_id: current_tenant.id).find(args[:id])]
      else
        obj_class.where(tenant_id: current_tenant.id).all
      end
    end

    def respond_to_missing?(method_name, include_private)
      field = method_name.to_s.singularize
      @objs = MetadataService.load_objects
      @objs[field].nil? ? true : false
    end

The first one works, but when calling the second I get an error message that the field doesn't accept arguments, which is expected since I dont have "field :contact..." defined for that object.

Any suggestions as to how I can do that dynamically too?

**Comment by rmosolgo** [comment]
> an error message that the field doesn't accept arguments

Could you please share the  query string, full error message and backtrace? Without that information, it's hard for me to tell whether you've encountered a Ruby error during schema boot, a GraphQL validation error, a GraphQL execution error, or an unhandled Ruby error during execution. 

> I dont have "field :contact..." defined for that object.

I see `field :contact ...` in the code snippet you posted above: 

```ruby
field :contact, Types::ContactType, null: false do
  argument :id, ID, required: true
end
```

The query string, error message and backtrace would help me understand what's going wrong there, too.

**Comment by rmosolgo** [comment]
Happy to investigate this further if you're interested in sharing the debugging info requested above!
