### ISSUE TITLE
Cache customer facing field

### ISSUE THREAD

**Issue by sayduck-daniel** [rmosolgo/graphql-ruby#3243]
Hi @rmosolgo 👋 

Coming here to ask if you would have some clues and could point us in the right direction where to start to look. The idea would be to implement some basic cache on publicly available field on our API.

Some resources in our API have a "Public" type. `ProductType` -> `PublicProductType`. Our public types are available after the resources goes trough a publishing process and its data will bee frozen once published. As our API deals with 3D representations of products, the payload can be quite verbose and end up with in 8000 lines JSON payloads.

So far, we used the `fingerprint` method from `query` as you suggested in #3232 but I'm hitting a rock here.

Let me take a concrete example:

query_type.rb
```ruby
module Types
  class QueryType < BaseObject
    add_field FieldTypes::CacheField
  end
end
```

cache_field.rb
```ruby
# frozen_string_literal: true

module FieldTypes
  CacheField = BaseField.new(name: :cache, type: Types::PublicProductType, null: true) do
    argument :uuid, GraphQL::Types::ID, required: false

    def resolve(_object, arguments, context)
      Rails.cache.fetch("#{arguments[:uuid]}/#{context.query.fingerprint}", expires_in: 7.days) do
        Product.find_by(uuid: arguments[:uuid])
        # here
      end
    end
  end
end
```
public_product_type.rb

```ruby
module Types
  class PublicProductType < BaseCustomObject
    field :name,
          String,
          null: false

    field :customer,
          Types::PublicCustomerType,
          null: true
    
    def customer
      # here 2   
      RecordLoader.for(Customer).load(object.customer_id)
    end
  end
end
```

I can run:

```graphql
query {
  cache(uuid: 'uuid-1') {
    name
  }
}
```

This will miss the cache and return the right thing the first time, but the second time, it won't return the payload.

My questions:

1. How can I get the "final payload" on my comment `# here` in order to save it in the cache.

1. We are using `graphql-batch` to avoid N+1 and those are stored in the type methods (see `def customer`). I think the best way would be to carry a value from the `PublicProductField` saying "this is a cached payload, skip Load". What is the best way in your opinion? I tried with the context but I'm not sure if this is the best place. Or would it be possible to say on the field level something like: `method: -> { :customer unless cache? }`

1. We were looking into an alternative using `ready?` where we would output the saved payload, but we hit the same problems.

**Comment by rmosolgo** [comment]
> How can I get the "final payload" on my comment `# here` in order to save it in the cache.

The resolver must return an object in order for GraphQL-Ruby to create the final payload, so I'm not sure how you could possible access the final payload _inside_ the resolver. 

Have you looked at https://github.com/DmitryTsepelev/graphql-ruby-fragment_cache ? It seems like they've figured out how to do what you have in mind. Even if it's not a perfect match, you might investigate the source to find some tips for implementing your own. (🙈 I don't know how that gem works!)
