### ISSUE TITLE
ActiveRecord fields of type decimal should be translated to floats by the generator

### ISSUE THREAD

**Issue by tbpeder** [rmosolgo/graphql-ruby#3244]
Consider the following ActiveRecord schema.

```
create_table "product", force: :cascade do |t|
  t.decimal "amount", precision: 10, scale: 2
end
```

"rails g graphql:object product" will produce the following product_type.rb:

```
module Types
  class ProductType < Types::BaseObject
    field :amount, [Types::DecimalType], null: false
  end
end
```

DecimalType makes graphql explode and should be a Float instead. This only seems to happen with decimal fields that have precision and scale.

Same problem happens with uuid types. They should just be converted to String in GraphQL.

**Comment by rmosolgo** [comment]
Fixed by #3246! To try it out, you can bundle `gem "graphql", github: "rmosolgo/graphql-ruby"` to get the changes on master, or you can wait for 1.11.7 to be released soon.
