### ISSUE TITLE
Need to restart Rails server every time when changing query_type or any other file.

### ISSUE THREAD

**Issue by bipashant** [rmosolgo/graphql-ruby#3245]
I'm not sure whether it is the issue with my setup but every time when I make changes to the graphql query_type or any other graphql related files such as(graphql_controller, type files, etc), I need to restart the server. Otherwise, changes do not get reflected in the response. You can feel the pain because of this during the development. Any help will be appreciated. Thank you!

**Versions**

`graphql: 1.9.21`
`rails: 5.2.0` 
`graphql-pundit: 0.7.1`

**Comment by newx** [comment]
Hi @bipashant 

It may be something on your local setup.

Please check `config.file_watcher` and `config.reload_classes_only_on_change` options on `config/environments/development.rb` and its documentation at https://guides.rubyonrails.org/configuring.html

I tested this locally and changes are reflected without restarting the server on development.

**Comment by bipashant** [comment]
Thank you @newx 
Looks like I'm using the default value, no config found for both of these. 
I also tried setting `config.reload_classes_only_on_change = true` and `config.file_watcher = ActiveSupport::FileUpdateChecker` but no luck. 
I will be so thankful.

**Comment by rmosolgo** [comment]
What directory are your GraphQL type definitions in? Are those directories covered by your app's [autoload paths](https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#autoload-paths)?

**Comment by bipashant** [comment]
Hi @rmosolgo !

`app/graphql/types` is the directory for GraphQL type files. 

I even tried adding `config.autoload_paths += Dir[Rails.root.join('app', 'graphql', 'types', '**/')]` but still the same issue.

**Comment by rmosolgo** [comment]
🤔  Sorry, I'm not sure what else to suggest! This isn't a widespread problem, so it's probably some conflict between settings in your development environment and application.

**Comment by bipashant** [comment]
@rmosolgo 
Looks like some issue with the namespacing.
Adding `::` before the `Types` solved the problem. 

```ruby
class MyXyzSchema < GraphQL::Schema
  mutation(::Types::MutationType)
  query(::Types::QueryType)
  ....
  ....
end
```

**Comment by bipashant** [comment]
Above solution credit goes to @livanuj

**Comment by bipashant** [comment]
Above solution's credit goes to @livanuj
