### ISSUE TITLE
Arguments re-composition in Middleware

### ISSUE THREAD

**Issue by colepatrickturner** [rmosolgo/graphql-ruby#325]
Since 0.19.3, the signature to `GraphQL::Query::Arguments` has changed to include the field's argument definitions. With this change, The Arguments object cannot be re-composed from the outside-in. 

For example to convert argument keys from camelCase to snake_case, one would normally use Middleware to transform the keys before calling the final resolve proc. I've tried to bring this up to date by including the definitions from `field_definition.arguments.`

This works well with regular queries, but seems to fail given a mutation with InputObjectType. An InputObject is converted to a hash and cannot be inferred from this hash.

A fix for the meantime, per @rmosolgo, is to convert the Arguments object to a hash to give to the final resolve proc. Ideally, we would be able to re-compose the Arguments object with the definitions so that it could play nice with other middleware.

**Comment by rmosolgo** [comment]
Sorry about this! I'll patch `Arguments` soon so that it keeps the necessary type info and provides it in a useful way.

**Comment by rmosolgo** [comment]
I introduced `Arguments#each_value` to expose type info for each argument, you can see an example usage in the spec: https://github.com/rmosolgo/graphql-ruby/blob/29c9c44502f53ae1177244995f79f753cd4dd734/spec/graphql/query/arguments_spec.rb#L62

Does that look like it'll do the job? (It's in 0.19.4)

**Comment by colepatrickturner** [comment]
Thank you @rmosolgo this has made it easy to do camelCase -> snake_case conversion conversion.

I just wanted to raise your awareness to one abnormality in regards to the `clientMutationId` in which case this particular argument's key should not be mutated under any circumstances, or else it will fail to look it up in the MutationResolve method here:

https://github.com/rmosolgo/graphql-ruby/blob/2e59be6482ce94a6124ce27766ad4a7910e6c589/lib/graphql/relay/mutation.rb#L199
