### ISSUE TITLE
Specify max_page_size on field resolvers

### ISSUE THREAD

**Issue by KieranP** [rmosolgo/graphql-ruby#3257]
Current code:

```ruby
module Objects
  class Post < Types::Object
    field :id, ID, null: false
  end
end

module Types
  class Queries < Types::Object
    field :all_posts, resolver: ::Resolvers::Post::Index
  end
end

module Resolvers::Post
  class Index < Types::Resolver
    type Objects::Post.connection_type, null: false

    def resolve(**args)
      Post.all
    end
  end
end
```

Currently, max_page_size is only support on the direct field declaration:

```ruby
field :all_posts, resolver: ::Resolvers::Post::Index, max_page_size: 20
```

But this separates logic. It would be nice to have support for max_page_size in the resolver class

```ruby
type Objects::Post.connection_type, null: false, max_page_size: 20
```

or as a main class method:

```ruby
module Resolvers::Post
  class Index < Types::Resolver
    type Objects::Post.connection_type, null: false
    max_page_size 20
  end
end
```

**Comment by rmosolgo** [comment]
:+1: Thanks for the suggestion, I agree that your last suggestion ("main class method") would be a good improvement here! I think it could implemented by adding the configured value as `max_page_size:` to the field options here: 

https://github.com/rmosolgo/graphql-ruby/blob/ef77d027a9d7545ecd067b0713050412560e027d/lib/graphql/schema/resolver.rb#L272-L285

Those options are eventually passed along to a `field(...)` call.
