### ISSUE TITLE
How to override default resolver

### ISSUE THREAD

**Issue by KKzLEO** [rmosolgo/graphql-ruby#3260]
Hi, this gem is awesome and it helps me use GraphQL very easily.

But I encountered a problem about default resolver. If we don't give a resolver to the field, it will use `obj.[field_name]` as a default resolver to get the data, it will throw exception if the parent(or called obj) doesn't have this method or attribute.

I wanna create a default resolver to override this behavior for every field, using `obj.try(field_name)` or `obj[field_name.to_sym]` or `obj[field_name]` instead, but I can't figure out how to do it. I am wondering if you could give me some tips about it? thanks.

rails version: 4.1.16
ruby: 2.3.7
graphql ruby: 1.7.14

**Comment by rmosolgo** [comment]
Hi, thanks for the great question. There's not an easy way to override the default behavior. In recent GraphQL-Ruby versions, you could accomplish this by defining a method whenever a field is defined. For example:

```ruby 
class Types::BaseObject < GraphQL::Schema::Object
  def self.field(*args, **kwargs, &block)
    field_defn = super 
    method_name = field_defn.method_sym
    # Define a method that will be used for this field:
    class_eval(<<-RUBY, __FILE__, __LINE__)
      def #{method_name}
        object.try(#{method_name.inspect})
      end 
    RUBY
  end 
end  
```

That will get a little tricky with inheritance, but it should be a start! 

However, I see you're using graphql-ruby 1.7.14. I don't think that version has the class-based API that I described above (maybe it does?), and I don't have the bandwidth to support the legacy API anymore. 

Let me know how it goes if you give it a try!

**Comment by KKzLEO** [comment]
Hi, thanks for your reply! I have tried this solution but seems it would throw error `undefined method `object' for nil:NilClass`.
Where is the object? does it exist in `field_defn `?

**Comment by rmosolgo** [comment]
Sorry for the hangup! `object` is defined on `GraphQL::Schema::Object`; it's a reference to the application object returned by the previous field. (So, it's the application object being used to resolve the current GraphQL object.)

Here's a working example: 

```ruby
require "bundler/inline"

gemfile do
  source 'https://rubygems.org'
  gem 'graphql'
  gem 'rails'
end

class BaseObject < GraphQL::Schema::Object
  def self.field(*args, **kwargs, &block)
    field_defn = super
    method_name = field_defn.method_sym
    # Define a method that will be used for this field:
    class_eval <<-RUBY, __FILE__, __LINE__
      def #{method_name}
        object.try(#{method_name.inspect})
      end
    RUBY
  end
end

class Query < BaseObject
  field :thing, String, null: true
end

class Schema < GraphQL::Schema
  query(Query)
end

result = Schema.execute("{ thing }", root_value: OpenStruct.new(thing: "OK!"))
pp result.to_h
# {"data"=>{"thing"=>"OK!"}}

result = Schema.execute("{ thing }", root_value: nil)
pp result.to_h
# {"data"=>{"thing"=>nil}}
```

hope that helps!

**Comment by KKzLEO** [comment]
Hi, thanks for your help, it seems that I used an old way to create my schema (GraphQL::Schema.define) so it will throw the error. I did a complete migration to class-based and it's working fine now, thank you so mush
