### ISSUE TITLE
Enums with optional name validation

### ISSUE THREAD

**Issue by ExplosiveGM** [rmosolgo/graphql-ruby#3261]
```
class Enums::Timezone < GraphQL::Schema::Enum
  ActiveSupport::TimeZone::MAPPING.values.uniq.each do |timezone|
    value(timezone)
  end
end
```
Timezone name example _America/Juneau_
**GraphQL::InvalidNameError: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but 'America/Juneau' does not**
Can you make it optional?
Something like this
```
class Enums::Timezone < GraphQL::Schema::Enum
  disable_name_validation { true }
end
```

**Comment by rmosolgo** [comment]
Enums are required to match that regexp; `America/Juneau` is not a valid enum value in GraphQL: http://spec.graphql.org/draft/#sec-Enum-Value

Consider using a string instead, or converting timezone names into SCREAMING_CASE.
