### ISSUE TITLE
Allow array of input types when defining mutations

### ISSUE THREAD

**Issue by tadman** [rmosolgo/graphql-ruby#3269]
**Is your feature request related to a problem? Please describe.**

Presently it does not seem like the mutation resolver system allows for arrays of input objects directly, as in:

```ruby
input_type [ MyType ]
```

Where while the schema generates correctly, running a mutation of this sort inevitably results in:

```
undefined method `to_kwargs' for #<Array:0x00007fcf5989c850> (NoMethodError)
```

Where it's assumed that the input is something that can be converted into a Ruby Hash. This is due to how GraphQL::Schema::Field converts arguments when calling the `resolve` method.

**Describe the solution you'd like**

To make it easy to create *N* of something, allowing for an array of input objects is the simplest approach.

**Describe alternatives you've considered**

The alternative is to have an input object with a single field which is an array of some other type. This seems like a pointless step.

**Comment by rmosolgo** [comment]
Hi! Thanks for reporting this bug. I agree that what you posted _should_ work. 

Could you please share the full backtrace of the error you encountered? The backtrace likely includes many lines of GraphQL-Ruby internals that would inform debugging and solving this problem.

**Comment by tadman** [comment]
It's easy to reproduce by just switching `input_type X` to `input_type X` which does properly reflect in the schema output as `[X!]!` which is great, but the resolver preparation stage chokes on it:

```ruby
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/field.rb:625:in `to_ruby_args'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/field.rb:551:in `block in resolve_field'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema.rb:112:in `after_lazy'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/field.rb:545:in `resolve_field'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/relay/mutation/resolve.rb:19:in `call'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/relay/mutation/resolve.rb:19:in `call'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/member/instrumentation.rb:80:in `call'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/field.rb:136:in `resolve'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/execute.rb:321:in `call'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/middleware_chain.rb:49:in `invoke_core'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/middleware_chain.rb:38:in `invoke'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/execute.rb:129:in `block in resolve_field'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/tracing.rb:66:in `trace'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/execute.rb:128:in `resolve_field'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/execute.rb:92:in `block in resolve_selection'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/execute.rb:85:in `each'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/execute.rb:85:in `resolve_selection'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/execute.rb:56:in `block in resolve_root_selection'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/tracing.rb:66:in `trace'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/execute.rb:49:in `resolve_root_selection'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/execute.rb:31:in `begin_query'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:112:in `begin_query'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:83:in `block in run_as_multiplex'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:82:in `map'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:82:in `run_as_multiplex'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:61:in `block (2 levels) in run_queries'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:195:in `block in instrument_and_analyze'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:174:in `instrument_and_analyze'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:60:in `block in run_queries'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/tracing.rb:66:in `trace'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:58:in `run_queries'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:48:in `run_all'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema.rb:1656:in `multiplex'
.../gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema.rb:1627:in `execute'
.../app/controllers/graphql_controller.rb:56:in `execute'
```

**Comment by tadman** [comment]
Here's my super hack workaround for now:

```ruby
class Array
  def to_kwargs
    {
      input: map(&:to_kwargs)
    }
  end
end
```

Using `map` alone isn't enough, there's expectations deeper in the chain that `key?` will work, so to avoid patching Array even further, this just returns an `input:`-keyed Hash.

**Comment by tadman** [comment]
There's also an issue in GraphQL::Relay::Mutation::Resolve when it comes to fetching `args[:input][:client_mutation_id]` with this earlier patch.

**Comment by rmosolgo** [comment]
`GraphQL::Relay::Mutation` and its replacement, `GraphQL::Schema::RelayClassicMutation`, are both meant to implement the Relay classic spec for mutations. It's been removed from Relay's codebase, but the old version is still available [in the git history](https://github.com/facebook/relay/blob/c988815ff9b1b4dd236c83413c55b352bbae0266/website/spec/Mutations.md#mutation-inputs). It says: 

> In particular, all mutations must expose exactly one argument, named input. This argument's type must be a `NON_NULL` wrapper around an `INPUT_OBJECT`. That input object type may contain an argument named `clientMutationId`. If provided, that argument must be a `String`. That argument may be non-null.

I don't expect to change the behavior of RelayClassicMutation, since it's made to work with Relay classic. 

How about using `GraphQL::Schema::Mutation` instead of `GraphQL::Schema::RelayClassicMutation`? It works the same, except it doesn't generate the `input: SomeMutationInput` structure. You could implement your desired structure with: 


```ruby 
class SomeMutation < GraphQL::Schema::Mutation 
  argument :input, [SomeInput], required: true 
  
  # ... 
end 
```

If you give it a try and run into any trouble, please let me know!

**Comment by tadman** [comment]
This seems to resolve the issue. Thanks for the specific feedback and advice!
