### ISSUE TITLE
rails generate duplicate gem delaration on gemfile when run twice

### ISSUE THREAD

**Issue by edimossilva** [rmosolgo/graphql-ruby#3273]
**Describe the bug**

When run `rails generate graphql:install` twice it adds `gem 'graphiql-rails', group: :development` twice to the Gemfile

**Versions**

`graphql` version: 1.11.6
`rails`

**Steps to reproduce**
1. rails new app
1. cd app
1. add `gem 'graphql'` to the Gemfile
1. bundle install
1. bundle exec rails generate graphql:install
1. bundle exec rails generate graphql:install
1. Y

**Expected behavior**

It should not be added again if already exists  `gem 'graphiql-rails', group: :development` once in the Gemfile

**Actual behavior**

Gemfile will have duplicated `gem 'graphiql-rails', group: :development` 

**I would like to work on it if possible**

**Comment by rmosolgo** [comment]
Thanks for reporting this issue! Here's the code that adds that gem: 

https://github.com/rmosolgo/graphql-ruby/blob/c29214a2a8f0a2bc3ee8ef645ea86ebd72a108a6/lib/generators/graphql/install_generator.rb#L126

Maybe it should somehow check the gemfile contents before adding it. 

Here are the tests: https://github.com/rmosolgo/graphql-ruby/blob/master/spec/integration/rails/generators/graphql/install_generator_spec.rb

I suppose you could test by adding a second `run_generator` call to an example and making sure that the generated gemfile only contains one `graphiql-rails` entry.

If you get a chance to give it a try, let me know if I can help with anything!

**Comment by edimossilva** [comment]
Thanks @rmosolgo , I will work on it tomorrow. :)

**Comment by edimossilva** [comment]
@rmosolgo  when I run `BUNDLE_GEMFILE=gemfiles/rails_6.0.gemfile bundle exec rake test TEST=spec/integration/rails/generators/graphql/install_generator_spec.rb` without `binding.pry` in `lib/generators/graphql/install_generator.rb` the tests work.

But if I put a `binding.pry` in `lib/generators/graphql/install_generator.rb` and run `BUNDLE_GEMFILE=gemfiles/rails_6.0.gemfile bundle exec rake test TEST=spec/integration/rails/generators/graphql/install_generator_spec.rb`  it stuck. Do you know why? is there another approach to debug on integration specs?

**Comment by edimossilva** [comment]
@rmosolgo , any tip?
