### ISSUE TITLE
Using connections disallows specifying arguments

### ISSUE THREAD

**Issue by ntaylor89** [rmosolgo/graphql-ruby#3277]
**Describe the bug**
If a query returns a `.connection_type`, then the field returning it ignores all arguments specified. I can declare the arguments, and the endpoint will work, but without the arguments.

**Versions**

`graphql` version: 1.11.5
`rails`: 6.0.33
`graphql-groups`: 0.1.4
`ar_lazy_preload`: 0.3.2

**GraphQL schema**

In `query.rb` (so top level of schema) I have:

```rb
  field :classrooms, Types::Classroom.connection_type, null: true do
    argument :school_id, ID, required: false
  end

  def classrooms(**args)
    Classroom.where(args).order(name: :asc)
  end
```

The `Classroom` type is very straightforward. I've slimmed it down for testing this issue:

```rb
class Types::Classroom < Types::BaseObject
  field :id, ID, null: false
  field :name, String, null: false
  field :student_count, Integer, null: false
  
  def student_count
    object.students.count
  end
  
end
```

**GraphQL query**

Here's an example of a query I'm sending with pagination.

```graphql
query(schoolId: 'someSchoolId') {
  classrooms {
    pageInfo {
      endCursor
      hasNextPage
    }
    edges {
      node {
        id
        name
        studentCount
    }
  }
}
```

with variables: `{ schoolId: 'someid' }`

This will return the data, but _all_ the data. No scoping by `schoolId`

**Steps to reproduce**

- Make a top level (or probably any) field return a connection via `Types::Something.connection_type`
- add any `argument` to that field
- declare a resolver method for the field, accepting the defined arguments
- Execute a query with the right variables

**Expected behavior**

The arguments will make it to the resolver.

**Actual behavior**

The arguments don't make it to the resolver.

**Additional context**

I've verified that
- The front-end is correctly sending the arguments
- My `GraphqlController` is receiving the arguments and passing them through properly
- If I change this field and my query to not use connections and just return an array, the arguments work
- If I add additional arguments, they don't go through either.

**Comment by rmosolgo** [comment]
Hi, thanks for the bug report. To clarify, what if you add an argument to your query? For example: 

```diff 
- query {
+ query($schoolId: ID!)
  ...
- classrooms {
+ classrooms(schoolId: $schoolId) {
```

By making those changes: 

1. GraphQL-Ruby will use the given `"schoolId" => ...` value for `$schoolId`
2. `$schoolId` will be given as the value to the `schoolId:` argument

Does that work for you?

**Comment by ntaylor89** [comment]
I am doing that. That was a typo in my query. I"ll fix it.

**Comment by ntaylor89** [comment]
I have validated that the front-end is sending it, and I'm seeing it get through to my controller, and even passing it to the lib properly.

And if I make this endpoint just return an array (changing my query, since the return is different) it does work properly.

**Comment by rmosolgo** [comment]
I see that you added above: 

```graphql
query(schoolId: 'someSchoolId') {
```

That's not valid GraphQL -- please try with: 

- A variable definition at the top level (`query($schoolId: ID!) { ...`) 
- Using the variable as an argument (`classrooms(schoolId: $schoolId)`) 

I don't expect it to work unless both of those are present in the query. If it's still not working, please share: 

- The code you're using to debug your controller, and what it outputs (eg, `puts` statement and the Rails terminal output) 
- The output of `p args` inside `def classrooms(**args)` shown above.

**Comment by ntaylor89** [comment]
Sorry, I"m ust giving you this as a hand written example, the actual stuff is coming from Apollo client in a react component and it is a bit complex, so I was trying to simplify it. Here's the full JS code.

```jsx
export const GET_CLASSROOMS = gql`
  query getClasses($schoolID: ID, $after: String) {
    classrooms(first: 10, after: $after, schoolId: $schoolID) {
      pageInfo {
        endCursor
        hasNextPage
      }
      edges {
        node {
          id
          name
          studentCount
        }
      }
    }
  }
`
```

I'm using `binding.pry` to inspect in the controller. Here's the execute with a pry

```rb
  def execute
    variables = ensure_hash(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      current_user: current_user
    }
    binding.pry
    result = OurSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  rescue => e
    raise e unless Rails.env.development?
    handle_error_in_development e
  end
```

When I inspect `variables` I see the values there

```rb
<ActionController::Parameters {"schoolId"=>"the_id_that_i_send_in_the_request"} permitted: false>
```

And we have other requests using params that work.

If I instead `binding.pry` in the resolver and inpsect the args, then I get an empty hash.

Then `args` is an empty Hash.

```rb
    40: def classrooms(**args)
 => 41:   binding.pry
    42:   Classroom.where(args).order(name: :asc)
    43: end

[1] pry(#<Types::Query>)> args
=> {}
```


If I change this signature to accept the _names_ of the args like so

```rb
  def classrooms(school_id:)
    Classroom.where(school_id: school_id).order(name: :asc)
  end
```

Then I'll get an error about the `school_id` missing (because I didn't provide a default arg)

```
missing keyword: :school_id
/Users/nate/Workspace/sbt/citadel/app/graphql/types/query.rb:40:in `classrooms'
```

**Comment by rmosolgo** [comment]
Sorry, I'm really not sure where to look next. Here's a simple case demonstrating custom arguments with a connection: 

<details>
<summary> Connection with custom arguments </summary>

<p>
```ruby
# connection_test.rb
require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "graphql", "1.11.6"
end

class Schema < GraphQL::Schema
  class Item < GraphQL::Schema::Object
    field :name, String, null: false
  end

  class Query < GraphQL::Schema::Object
    field :items, Item.connection_type, null: false do
      argument :order_by, String, required: true
    end

    def items(order_by:)
      items = [{name: "Apple"}, {name: "Banana"}, {name: "Cucumber"}, {name: "Damson Plum"}]
      case order_by
      when "name"
        # already ordered
        items
      when "-name"
        items.reverse
      else
        raise ArgumentError, "Unhandled orderBy: #{order_by.inspect}"
      end
    end
  end

  query(Query)
end

query_str = <<-GRAPHQL
query($orderBy: String!) {
  items(first: 2, orderBy: $orderBy) {
    nodes {
      name
    }
  }
}
GRAPHQL

pp Schema.execute(query_str, variables: { "orderBy" => "name" }).to_h
# {"data"=>{"items"=>{"nodes"=>[{"name"=>"Apple"}, {"name"=>"Banana"}]}}}

pp Schema.execute(query_str, variables: { "orderBy" => "-name" }).to_h
# {"data"=>{"items"=>{"nodes"=>[{"name"=>"Damson Plum"}, {"name"=>"Cucumber"}]}}}

```
</p>
</details>

This is what I get for that script: 

```
% ruby connection_tests.rb
{"data"=>{"items"=>{"nodes"=>[{"name"=>"Apple"}, {"name"=>"Banana"}]}}}
{"data"=>{"items"=>{"nodes"=>[{"name"=>"Damson Plum"}, {"name"=>"Cucumber"}]}}}
```

Does it work for you locally? 

If not, the main difference I could think of is `ActionController::Parameters`. You could investigate that further by: 

- Do other uses of variables/arguments work in your GraphQL setup? If they're _all_ broken, then maybe something should be improved on the whole. 
- If you manually create a hash with `{ "schoolId" => params[:variables][:schoolId] }`, does that work? If so, it would suggest that ActionController::Parameters is involved in the problem. 

If you get to give one of those a try, let me know what you find!

**Comment by rmosolgo** [comment]
Happy to keep investigating this if you get a chance to follow up on those questions!
