### ISSUE TITLE
Use before_action in mutation

### ISSUE THREAD

**Issue by xxSkyy** [rmosolgo/graphql-ruby#3280]
Hey
I'm doing graphql integration with JWT authorization on rails. But I want to restrict some mutations only to authorized users. But to auth I need to use before_action

How can I do it? normal usage of before actions doesnt work, its very problematic - or I dont see something.
Can someone help?

**Comment by rmosolgo** [comment]
Hi! Good question. Here's how that usually works: 

- Authenticate in the Rails controller (maybe using a before_action, like you said) 
- Pass the current user to GraphQL using `context:`, for example: 

  ```ruby
   context = { current_user: current_user }
   MySchema.execute(query_string, context: context, variables: variables)
   ```
- During resolvers, use `context[:current_user]` to check authentication/authorization, for example: 

  ```ruby 
  def resolve 
    if context[:current_user].nil?
      raise GraphQL::ExecutionError, "You must be logged in for ..."
    end 
    # ...
  end 
  ```
  
  (For built-in authorization hooks, see https://graphql-ruby.org/authorization/authorization)
 
I hope that helps! If you give it a try and run into trouble, please paste your code here and share the results (graphql response, error and backtrace, etc) here.

**Comment by xxSkyy** [comment]
Thanks for reply but sadly it doesnt seems to be helpful in my case.

I forgot to mention I use (vue) apollo for API integration so there's no controller for some of items as requests comes directly to graphql with headers that should pass before_action to get current user. Passing requests through controller is not an option

If I'm wrong please correct me but its how I see it atm.
