### ISSUE TITLE
Documentation issue about null cascades

### ISSUE THREAD

**Issue by ckritzinger** [rmosolgo/graphql-ruby#3282]
I'm not sure if this is an actual issue or just an issue with my understanding, please bear with me.

The documentation site for the library states that:

> If a non-null field ever returns nil, then the entire selection will be removed from the response and replaced with nil. If this removal would result in another invalid nil, then it cascades upward, until it reaches the root "data" key. This is to support clients in strongly-typed languages. Any non-null field will never return null, and client developers can depend on that.

See: https://graphql-ruby.org/type_definitions/non_nulls#non-null-error-propagation

My understanding is that this is the correct behaviour according to the GQL spec.

However, the internall documentation in the codebase states that:

> If the implementation returns nil, GraphQL-Ruby will return an error to the client.

See: https://github.com/rmosolgo/graphql-ruby/blob/c60d7db6046bb4fe2bb1eda2d366b25a748ca8ff/guides/fields/introduction.md

This seems to be what the library is actually doing when presented with a null in a non-null field. I can't see any issues related to this behaviour, is this due for change at any point?

**Comment by rmosolgo** [comment]
AFAIK both of those bits of documentation hold. When GraphQL-Ruby receives `nil` for a field defined as `null: false`, then: 

- GraphQL-Ruby bubbles that `nil` _upward_ until it encounters a nullabile field 
- GraphQL-Ruby returns an error to the client 

Are you suggesting to stop returning an error in this case? That's OK with me :+1: In any case, the error behavior can be customized with the `def self.type_error` hook in the schema class. 

Or, is there something else that you think should be changed?

**Comment by ckritzinger** [comment]
Thanks very much for the detailed feedback. I think that is pretty reasonable.

I was not expecting the error response, since it seemed to me that the cascading null was not really an error per se, but I can see how that could be debatable, and I don't have a strong opinion.

Being able to remove the error with the hook would completely solve my case, except that can't make global changes to our schema (large API shared by many devs). However, I can just filter those records out in the resolver. Tiny bit less elegant, but sufficient for my needs.

Thanks again for the response and a fantastic library.

**Comment by rmosolgo** [comment]
> since it seemed to me that the cascading null was not really an error per se

I think you're right about that. It's not an error on the _client's_ part -- it's an error for the backend to address. It's useful in the bug tracker, but not the response. 

I've added this to the 1.13 release issue :+1:
