### ISSUE TITLE
Subscriptions authorize code doesn't run when event is broadcast

### ISSUE THREAD

**Issue by pedro-pedrosa** [rmosolgo/graphql-ruby#3284]
**Describe the bug**

When a subscription's fingerprint allows for broadcasting, the `execute_update` (and therefore `update` and `authorized?` methods on subscription classes) only run for the first event in the fingerprint's list.

**Versions**

`graphql` version: `1.11.6`
`rails` (or other framework): `3.0`
other applicable versions (`graphql-batch`, etc)

**GraphQL schema**

N/A

**GraphQL query**

N/A

**Steps to reproduce**

Subscribe multiple times to the same event with the same arguments with `broadcast: true, default_broadcast: true` on the subscriptions adapter. Add a log to the `update` and `authorized?` code of the subscription.

**Expected behavior**

I'm expecting that at least the `authorized?` code runs for each subscription as the user may be different and may not have permissions.

**Actual behavior**

`update` and `authorized?` only run once for each trigger.

**Additional context**

This happens at least with the actioncable adapter.

**Comment by rmosolgo** [comment]
Hey, thanks for reporting this. Yes, that's right -- broadcasts skip viewer-related checks. It's documented here: 

https://graphql-ruby.org/subscriptions/broadcast.html#what-fields-are-broadcastable

> A field is not broadcastable if its value is different for different clients. For example:
>
> - __Viewer-specific information:__ if a field is specifically viewer-based, then it can’t be broadcasted to other viewers. For example, `discussion { viewerCanModerate }` might be true for a moderator, but it shouldn’t be broadcasted to other viewers.

You should disable broadcasting for this field if it requires authorization. 

Or, if I've misunderstood the issue, please tell me more about it!

**Comment by pedro-pedrosa** [comment]
when I read that I thought broadcastability was related to the data being sent, not the user subscribing to updates. so I assumed since the data is the same for everyone then I could broadcast it. thanks for the clarification.
