### ISSUE TITLE
Guide: Action Cable Implementation

### ISSUE THREAD

**Issue by bubbaspaarx** [rmosolgo/graphql-ruby#3288]
Links in guide direct to 404

**Comment by rmosolgo** [comment]
Hey, thanks for reporting this! Which links didn't work for you? I tried all the links in the body of https://graphql-ruby.org/subscriptions/action_cable_implementation.html and they worked alright for me, but maybe I'm missing something ...

**Comment by bubbaspaarx** [comment]
Yesterday the actioncable links were directing to 
https://graphql-ruby.org/api-doc/1.11.7/GraphQL/Subscriptions/ActionCableSubscriptions
now they appear to be directing to 1.12.0 and working.

**Comment by rmosolgo** [comment]
Ahh, thanks. It looks like the build failed for those API docs: https://github.com/rmosolgo/graphql-ruby/actions/runs/494624446

I'll re-run it, and then those links should work, in case anyone goes looking for 1.11.7 docs in the future.
