### ISSUE TITLE
CHANGELOG.md for 1.11.7 : work around for IntegerDecodingError is not correct

### ISSUE THREAD

**Issue by toddjeff** [rmosolgo/graphql-ruby#3289]
**Describe the bug**

CHANGELOG.md for 1.11.7   has a workaround for a breaking change, but it's not correct:
```
  if err.is_a?(GraphQL::IntegerDecodingError)
    return err.value # return it anyways, since this is how graphql-ruby used to work
  end
```
Doesn't work, needs to be:
```
  if err.is_a?(GraphQL::IntegerDecodingError)
    return err.integer_value # return it anyways, since this is how graphql-ruby used to work
  end
```
see: https://github.com/rmosolgo/graphql-ruby/blob/5ed03edb034df7643e5e08eb0ef747e92adeb757/lib/graphql/integer_decoding_error.rb#L10

**Versions**

`graphql` version:  1.11.7

**Comment by rmosolgo** [comment]
Thanks for reporting this! I updated it in https://github.com/rmosolgo/graphql-ruby/commit/6585111214651d30a1214fe10614400762f076a7, sorry about the hangup.
