### ISSUE TITLE
Actioncable setup - Unable to access cookies or context

### ISSUE THREAD

**Issue by bubbaspaarx** [rmosolgo/graphql-ruby#3291]
I have searched high and low for a way to access cookies within the application_cable/connection class. 

This leads to a problem where I'm unable to set current_user for context in the graphql_channel

My application_cable/connection file

```ruby
module ApplicationCable
  class Connection < ActionCable::Connection::Base
    include ::ActionController::Cookies
    
    identified_by :current_user

    def connect 
        self.current_user = find_verified_user 
    end 
  
    private
    def find_verified_user 
     if current_user = User.find_by(id: cookies.signed[:user_id])
         current_user 
     else
         reject_unauthorized_connection 
     end 
    end
  end
end
``` 
is there a method i need to use to access cookies in this area or should I be able to access them from within graphql_channel. 

My set up works without current_user or cookies but this leads to a security concern.

**Comment by rmosolgo** [comment]
Judging by the docs, you should: 

- _not_ `include ::ActionController::Cookies`
- use `cookies.encrypted[...]`

https://guides.rubyonrails.org/action_cable_overview.html#connection-setup

However, I don't have a ton of experience with ActionCable, so I'm afraid I don't have any suggestions beyond that.
