### ISSUE TITLE
RangeAdd is depricated with no replacement.

### ISSUE THREAD

**Issue by anark** [rmosolgo/graphql-ruby#3300]
**Describe the bug**

In several places in our app we are using the `GraphQL::Relay::RangeAdd.new` to return the newly added edge from a mutation that creates the edge.

We are now seeing the following depreciation message when using this
```
GraphQL::Relay::BaseConnection (used for GraphQL::Relay::RelationConnection) will be removed from GraphQL-Ruby 2.0, use GraphQL::Pagination::Connections instead: https://graphql-ruby.org/pagination/overview.html
```

Is there a new alternative or another way to return the newly created edge?  If so can this depreciation message be updated to better direct users?

**Versions**

`graphql` version: 1.12.0
`rails` : 6.0.3.2

**Comment by rmosolgo** [comment]
Hey! Thanks for reporting this. I don't get this message from the example in the specs:

https://github.com/rmosolgo/graphql-ruby/blob/master/spec/integration/rails/graphql/relay/range_add_spec.rb#L62-L74

Could you please share the source of you're mutation where you're using `RangeAdd`? 

My plan is to continue to support `RangeAdd`. If you're not using the new `Pagination::Connections` module, it will complain at you, but that module _should_ be the default now, so I wouldn't expect trouble...

**Comment by anark** [comment]
Sure.  I'm seeing this in all the mutations I have that I use RangeAdd in.  One of them is included below
```
class Mutations::AddFolder < Mutations::BaseMutation
  field :new_folder_edge, Types::Models::FolderType.edge_type, null: true
  field :errors, [Types::Errors::ValidationError], null: false

  argument :title, String, required: true
  argument :root_folder_id, ID, required: true
  argument :folder_id, ID, required: false

  def resolve(root_folder_id:, title:, folder_id: nil)
    folder = current_user.folders.find_by_graphql_id!(root_folder_id)

    new_folder = folder.folders.build(
      title: title,
      parent: folder
    )

    if new_folder.save
      range_add = GraphQL::Relay::RangeAdd.new(
        parent: folder,
        collection: folder.folders,
        item: new_folder
      )

      {
        new_folder_edge: range_add.edge,
        errors: []
      }
    else
      {
        new_folder_edge: nil,
        errors: new_folder.errors.messages.map { |attribute, messages| { attribute: attribute, messages: messages } }
      }
    end
  end
end
```
I get the same depreciation message even if I explicitly add `use GraphQL::Pagination::Connections` to my schema

**Comment by rmosolgo** [comment]
What if you add `context: context` to RangeAdd's parameters?

```diff
      range_add = GraphQL::Relay::RangeAdd.new(
        parent: folder,
        collection: folder.folders,
        item: new_folder,
+       context: context
      )
```

RangeAdd uses context to reach your schema, which provides the connection wrappers: 

https://github.com/rmosolgo/graphql-ruby/blob/4c8bebafad0c46a4c394e4c84db701a572c4f0a6/lib/graphql/relay/range_add.rb#L38

If that works for you, I'll add a better warning to require `context:` is provided.

**Comment by anark** [comment]
Adding the context got rid of the depreciation message.  Thank you!
