### ISSUE TITLE
Guide: Lookahead on Mutations

### ISSUE THREAD

**Issue by Adeynack** [rmosolgo/graphql-ruby#3302]
# Issue with the Guide

The article on _Lookahead_ in the Guides does not mention that it is impossible to have a lookahead inside of a **mutation**, nor does it give any explanation or example of how to do it.

# Concrete problem to solve

(and why I was looking at that article)

I have a mutation that has this return field

```ruby
    field :seats, [Types::AdminGraph::SeatStatusType], null: false, extras: [:lookahead]
```

If the client requires the `status` field of the `SeatStatusType` object, there is extra SQL to be performed. If the client only is interested in the success or failure of the mutation, I do not want to perform that extra bit of SQL (potentially not even any SQL query at all, if the client is not even interested in the `seats` return field).

So, I tried adding the `extras: [:lookahead]` parameter, as shown on my field definition. However, if I add `lookahead:` to my `resolve` signature like this

```ruby
    def resolve(event_id:, item_ids:, block_reason:, lookahead:)
```

the request fails, only mentioning "_The server encountered an unexpected condition that prevented it from fulfilling the request_" in the error field.

**Comment by rmosolgo** [comment]
Hey, thanks for the detailed writeup. It sounds like: 

- You have a mutation 
- One of the mutation's fields is `seats`, which returns a `SeatStatusType`. 
- If `seats { status }` is selected, some expensive SQL should be run ahead-of-time; if not, it can be skipped. 

Here's how you might implement that:

```ruby
require "bundler/inline"

gemfile do
  gem "graphql", "1.12.4"
end

class Schema < GraphQL::Schema
  class SeatStatus < GraphQL::Schema::Object
    field :status, String, null: false
  end

  class WithLookahead < GraphQL::Schema::Mutation
    field :seats, SeatStatus, null: false

    extras [:lookahead]
    def resolve(lookahead:)
      if lookahead.selection(:seats).selects?(:status)
        puts "Selects seats.status, running expensive SQL..."
        { seats: { status: "OK" } }
      else
        puts "Doesn't select seats.status, skipping expensive SQL"
        { seats: {} }
      end
    end
  end

  class Mutation < GraphQL::Schema::Object
    field :with_lookahead, mutation: WithLookahead
  end
  mutation(Mutation)
end

puts Schema.to_definition
# type Mutation {
#   withLookahead: WithLookaheadPayload
# }

# type SeatStatus {
#   status: String!
# }

# """
# Autogenerated return type of WithLookahead
# """
# type WithLookaheadPayload {
#   seats: SeatStatus!
# }

pp Schema.execute(<<-GRAPHQL).to_h
mutation {
  withLookahead { seats { status } }
}
GRAPHQL
# Selects status, running expensive SQL...
# {"data"=>{"withLookahead"=>{"seats"=>{"status"=>"OK"}}}}

pp Schema.execute(<<-GRAPHQL).to_h
mutation {
  withLookahead { seats { __typename } }
}
GRAPHQL
# Doesn't select seats, skipping expensive SQL
# {"data"=>{"withLookahead"=>{"seats"=>{"__typename"=>"SeatStatus"}}}}


pp Schema.execute(<<-GRAPHQL).to_h
mutation {
  withLookahead { __typename }
}
GRAPHQL
# Doesn't select seats.status, skipping expensive SQL
# {"data"=>{"withLookahead"=>{"__typename"=>"WithLookaheadPayload"}}}
```

It sounds like you tried something like that, but got back an error: 

> "The server encountered an unexpected condition that prevented it from fulfilling the request"

That's not a GraphQL error, it must be coming from somewhere else. 

If you try out a setup like my example above, please share: 

- The code you tried (`def resolve` body, query string, GraphQL response)
- The full message and backtrace of any error you encounter along the way. (Maybe it will turn up in your Rails logs, if not in the response body.)

Then we can keep investigating!
