### ISSUE TITLE
[PRO] - after updating to 1.17.1, all of our subscription tests fail when run as a suite in parallel

### ISSUE THREAD

**Issue by xxx** [rmosolgo/graphql-ruby#3307]
**Describe the bug**

Weird issue. While upgrading graphql-pro from 1.17.0 to 1.17.1 today, all subscription specs that we have, that test if Pusher is receiving the `trigger` call, will fail when run as a suite, but pass when run focused. Downgrading to 1.17.0 resolves the problem.

We use [parallel_tests](https://github.com/grosser/parallel_tests) (with separate processes, not threads) for our suite. Running without parallel also works, but is a no-go for our team.

This is only a break in our spec suite. 1.17.1 works fine when actually running.

Is there a better way to write these tests?

**Versions**

`graphql` version: 1.12.3
`rails` (or other framework): 6.0.3.4
other applicable versions (`graphql-batch`, etc)

**GraphQL schema**

```ruby
module Subscriptions
  class BaseSubscription < GraphQL::Schema::Subscription
    include Pundit

    object_class Types::BaseObject
    field_class Types::BaseField
    argument_class Types::BaseArgument

    def object_from_id(type, id, context)
      context.schema.object_from_type_and_id(type, id, context)
    end

    private

    def current_user
      context[:current_user]
    end
  end
end
```

```ruby
module Subscriptions
  class NotificationUpdated < BaseSubscription
    description 'A notification was updated'
    subscription_scope :current_user_id

    field :notification, Types::NotificationType, null: false, description: 'The updated Notification'
    field :unread_notifications_count, Int, null: false, description: 'Number of unread notifications for the user'

    def authorized?
      raise NotAuthorizedError, I18n.t('graphql.errors.common.unauthorized') if current_user.nil?

      true
    end

    def update
      {
        notification: object,
        unread_notifications_count: current_user.notifications.unopened.size
      }
    end
  end
end
```

An example of a failing spec:

```ruby
it 'fires the subscription event on update' do
  notification.open!

  expected_result = {
    data: {
      notificationUpdated: {
        notification: {
          id: notification.id.to_s,
          openedAt: notification.reload.opened_at.iso8601
        },
        unreadNotificationsCount: current_user.notifications.unopened.size
      }
    }
  }.with_indifferent_access

  expect(Pusher).to have_received(:trigger).with(
    an_instance_of(String),
    'update',
    hash_including({ result: expected_result })
  )
end
```

We're using the [Pusher instructions from here](https://graphql-ruby.org/subscriptions/pusher_implementation).

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

n/a

**Steps to reproduce**

Run our specs as a suite. Unfortunately I cannot share the entire suite here.

**Expected behavior**

That these specs would pass when run as a suite, the same way they do when run focused.

**Actual behavior**

What specifically went wrong?

The `Pusher.trigger` call is never made, and the specs fail.

**Additional context**

n/a

**Comment by rmosolgo** [comment]
Hey, thanks for the detailed report of this issue. How odd! 

Maybe you noticed, the main subscriptions change in 1.17.1 was consolidating Redis calls into Lua scripts (to reduce overhead in round-trips). 

How is your connection to Redis managed in tests? Is it possible that one process is clobbering the database which is used by those other processes? (I'm not sure why 1.17.1 would have _broken_ that, but if you can share some details about how Redis is set up and torn down by these tests, it might help.)

**Comment by xxx** [comment]
We use a single Redis DB in our test suite, separated by test process using the [redis-namespace](https://github.com/resque/redis-namespace) gem. We've had this in place for over 5 years. Is this something that the addition of Lua could break?

This is our entire initializer:

```ruby
# frozen_string_literal: true

redis_config = YAML.safe_load(File.open(Rails.root.join('config/redis.yml'))).symbolize_keys
rails_env = Rails.env.to_sym
default = redis_config[:default].symbolize_keys
conf = default.merge(redis_config[rails_env].symbolize_keys) if redis_config[rails_env]

namespace = ENV['TEST_ENV_NUMBER'] ? "test_#{ENV['TEST_ENV_NUMBER']}" : nil

connection = if ENV['REDIS_URL'].present?
               Redis.new(url: ENV['REDIS_URL'])
             else
               Redis.new(conf)
             end

Redis.current = Redis::Namespace.new(namespace, redis: connection)
```

**Comment by rmosolgo** [comment]
Thanks for sharing those details. It came to me while I was reading last night: I did a "no-no" in my Lua scripts. In a couple of cases, the scripts take values from Redis and convert them to keys for making another call. (I did this to avoid sending those values back and forth to Ruby.) However, a flow like that won't work with `redis-namespace` since the keys never enter Ruby-land. 

I'm going to read up on _fair_ use of key generation in Lua and either: 

- Refactor the script so that the values from Redis are returned to Ruby and sent back to Redis as keys (adding a round-trip, but playing by the rules)
- Or, send the _key prefix_ as one of the keys to `eval` (so it can be properly prefixed by `redis-namespace`), and use that prefix to generate keys. (It's currently hardcoded into the Lua script.) 

I'll follow up here after that.

**Comment by rmosolgo** [comment]
I just shipped 1.17.2 with a refactor to pass all keys properly to `EVAL` using the `KEYS` argument. Could you give it another try with that version and let me know how it goes?

**Comment by xxx** [comment]
@rmosolgo 1.17.2 is working perfectly. Thanks for the fast assist!

**Comment by rmosolgo** [comment]
Glad to hear it 🍻 !
