### ISSUE TITLE
Dataloader is not batching

### ISSUE THREAD

**Issue by coding-chimp** [rmosolgo/graphql-ruby#3308]
**Describe the bug**

I am trying to switch our code base from `graphql-batch` to the new built-in dataloader. So far the transition was pretty smooth and I like how the dataloader is working, but sadly, the batching isn't working as expected.

It's quite possible it's not working because I'm doing something wrong, though I can't figure out what could be. 😅

**Versions**

`graphql` version: 1.12.3
`activercord` version: 6.0.3.4

**GraphQL schema, query & steps to reproduce**

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"

  gem "activerecord", "6.0.3.4"
  gem "database_cleaner-active_record"
  gem "graphql", "1.12.3"
  gem "graphql-batch"
  gem "pg"
end

require "graphql"
require "active_record"
require "database_cleaner/active_record"
require "logger"

DatabaseCleaner.strategy = :truncation
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Base.establish_connection(
  adapter: "postgresql",
  database: "graphql_batching_bug"
)

ActiveRecord::Schema.define do
  self.verbose = false

  create_table :authors, force: :cascade do |t|
    t.timestamps
  end

  create_table :books, force: :cascade do |t|
    t.integer :author_id
    t.timestamps
  end
end

class Author < ActiveRecord::Base
  has_many :books
end

class Book < ActiveRecord::Base
  belongs_to :author
end

class AuthorType < GraphQL::Schema::Object
  field :id, ID, null: false
end

class BookType < GraphQL::Schema::Object
  field :id, ID, null: false
  field :author, AuthorType, null: false

  def author
    dataloader.with(RecordSource, Author).load(object.author_id)
    # RecordLoader.for(Author).load(object.author_id)
  end
end

class Query < GraphQL::Schema::Object
  field :books, [BookType], null: false

  def books
    Book.all
  end
end

class RecordSource < GraphQL::Dataloader::Source
  def initialize(model, column: model.primary_key)
    @model = model
    @column = column.to_s
    @column_type = model.type_for_attribute(@column)
  end

  def fetch(keys)
    casted_keys = keys.map { |key| @column_type.cast(key) }
    records = query(casted_keys)

    casted_keys.map do |key|
      records.find { |record| record.public_send(@column) == key }
    end
  end

  private

  def query(keys)
    scope = @model
    scope.where(@column => keys).to_a
  end
end

class RecordLoader < GraphQL::Batch::Loader
  def initialize(model, column: model.primary_key)
    @model = model
    @column = column.to_s
    @column_type = model.type_for_attribute(@column)
  end

  def load(key)
    super(@column_type.cast(key))
  end

  def perform(keys)
    query(keys).each { |record| fulfill(record.public_send(@column), record) }
    keys.each { |key| fulfill(key, nil) unless fulfilled?(key) }
  end

  private

  def query(keys)
    scope = @model
    scope.where(@column => keys).to_a
  end
end

class Schema < GraphQL::Schema
  use GraphQL::Dataloader
  # use GraphQL::Batch

  query Query
end

10.times do
  author = Author.create!
  Book.create!(author: author)
end

result = Schema.execute(<<-GRAPHQL)
{
  books {
    id
    author { id }
  }
}
GRAPHQL

puts result.to_h

DatabaseCleaner.clean
```

**Expected behavior**

I would expect all the authors to be fetched with a single request from the database. Here is how I expect the log to look and how it looks when I use `graphql-batch`:

```
DEBUG -- :   Book Load (0.3ms)  SELECT "books".* FROM "books"
DEBUG -- :   Author Load (0.4ms)  SELECT "authors".* FROM "authors" WHERE "authors"."id" IN ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)  [["id", 1], ["id", 2], ["id", 3], ["id", 4], ["id", 5], ["id", 6], ["id", 7], ["id", 8], ["id", 9], ["id", 10]]
```

**Actual behavior**

It's actually making a request for every author:

```
DEBUG -- :   Book Load (0.2ms)  SELECT "books".* FROM "books"
DEBUG -- :   Author Load (0.2ms)  SELECT "authors".* FROM "authors" WHERE "authors"."id" = $1  [["id", 1]]
DEBUG -- :   Author Load (0.1ms)  SELECT "authors".* FROM "authors" WHERE "authors"."id" = $1  [["id", 2]]
DEBUG -- :   Author Load (0.1ms)  SELECT "authors".* FROM "authors" WHERE "authors"."id" = $1  [["id", 3]]
DEBUG -- :   Author Load (0.1ms)  SELECT "authors".* FROM "authors" WHERE "authors"."id" = $1  [["id", 4]]
DEBUG -- :   Author Load (0.2ms)  SELECT "authors".* FROM "authors" WHERE "authors"."id" = $1  [["id", 5]]
DEBUG -- :   Author Load (0.1ms)  SELECT "authors".* FROM "authors" WHERE "authors"."id" = $1  [["id", 6]]
DEBUG -- :   Author Load (0.1ms)  SELECT "authors".* FROM "authors" WHERE "authors"."id" = $1  [["id", 7]]
DEBUG -- :   Author Load (0.1ms)  SELECT "authors".* FROM "authors" WHERE "authors"."id" = $1  [["id", 8]]
DEBUG -- :   Author Load (0.1ms)  SELECT "authors".* FROM "authors" WHERE "authors"."id" = $1  [["id", 9]]
DEBUG -- :   Author Load (0.2ms)  SELECT "authors".* FROM "authors" WHERE "authors"."id" = $1  [["id", 10]]
```

**Comment by DmitryTsepelev** [comment]
Faced the same thing the last weekend, maybe it worth rewording docs 🙂 The problem is that `#load` causes dataloader to perform loading _right now_:

```ruby
def author
    dataloader.with(RecordSource, Author).load(object.author_id)
end
```

Replace `load` with `request` (which tells dataloader to load this data later) and it will do a trick

**Comment by coding-chimp** [comment]
Yeah, I did not get that from the docs. Okay, if I use `request` instead of `load` this case is working as expected. Thanks for clarifying this! 🙂

Though I guess I'm now a little confused about the dataloader in general. 🤔 Letting the field resolver method return a request works fine, but what if I want to use batch loaded records in my code? Let's assume I want to add a `authorName` field to my book type. From the documentation I would've assumed this fetches the author in batches and then returns the name:

```ruby
def author_name
  dataloader.with(RecordSource, Author).load(object.author_id).name
end
```

Now that I learned `load` will load the data immediately, I would've thought I need to do this instead:

```ruby
def author_name
  request = dataloader.with(RecordSource, Author).request(object.author_id)
  author = request.load
  author.name
end
```

But in my logs I can see that this also triggers a n+1 query. Does that I need to write a dataloader source to handle something like this?

**Comment by rmosolgo** [comment]
I _expect_ `.load` to have caused `Fiber.yield` until the batch was run. I'll take a look at why this isn't working properly. Thanks so much for the excellent reproduction script!

**Comment by rmosolgo** [comment]
I dug in earlier this morning, and it looks like it misbehaves when the parent field _didn't_ yield to the dataloader. I've got a failing test in 0cdb2e3ec ... now, to find a _fix_!

**Comment by rmosolgo** [comment]
🎉  It turned out to be a ... _total rebuild_, but over on #3312, the output for this script is the expected: 

```sql
Book Load (0.1ms)  SELECT "books".* FROM "books"
Author Load (0.2ms)  SELECT "authors".* FROM "authors" WHERE "authors"."id" IN ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)  [["id", 1], ["id", 2], ["id", 3], ["id", 4], ["id", 5], ["id", 6], ["id", 7], ["id", 8], ["id", 9], ["id", 10]]
```

I still have some cleanup to do on that branch, but I'll cut 1.12.4 soon!

**Comment by coding-chimp** [comment]
@rmosolgo Well, sorry about that? 😅 But thanks for your great work! Really looking forward to giving this a spin after the next release. 🙂

**Comment by rmosolgo** [comment]
> Well, sorry about that? 

Haha, not at all! Evidently it _never_ worked, I just overlooked it. Anyways, I'm really excited about the refactor. I'm hoping to someday adopt an evented runtime architecture powed by Ruby 3's `Fiber.scheduler` API, and this refactor (turning execution basically into a job queue) lays the groundwork for that.
