### ISSUE TITLE
New GraphQL::Pagination::Connections breaks when using GraphQL::Relay::RelationConnection

### ISSUE THREAD

**Issue by TikiTDO** [rmosolgo/graphql-ruby#3318]
**Describe the bug**

The `GraphQL::Pagination::Connections` sends invalid parameters when trying to render a field configured to use a subclass of `GraphQL::Relay::RelationConnection` as the connection type. The most immediately apparent issue is that [this code](https://github.com/rmosolgo/graphql-ruby/blob/345ebb2e3833909963067d81e0e8378717b5bdbf/lib/graphql/pagination/connections.rb#L77) passes in `items` and a bunch of named parameters, whereas [this code](https://github.com/rmosolgo/graphql-ruby/blob/345ebb2e3833909963067d81e0e8378717b5bdbf/lib/graphql/relay/base_connection.rb#L61) expects `(nodes, items, **named_params)`. That said on a conceptual level it feels like the relay connection should be handing it's own pagination logic, in which case it doesn't make sense for it to be wrapped in another pagination manager.

Following the CHANGELOG instructions for 1.12.0 and doing `self.connections = nil` fixes the problem, but I'm concerned about how long that will last.

**Versions**

`graphql` version: 1.12.3
`rails` (or other framework): 6.1

**GraphQL schema**

Simplified below. Let me know if you need a full repro repo and I should be able to make one over the weekend.

```ruby
class SearchkickConnection < GraphQL::Relay::RelationConnection
  # ...
end

class RelayObject < GraphQL::Schema::Object
  implements GraphQL::Types::Relay::Node
  connection_type_class SearchkickConnection
end

class TreeType < RelayObject
  field :name, String, null: true
  field :children, TreeType.connection_type, null: true
end

class Query < GraphQL::Schema::Object
  add_field GraphQL::Types::Relay::NodeField
  add_field GraphQL::Types::Relay::NodesField
end


class Schema < GraphQL::Schema
  query Query
end

GraphQL::Relay::BaseConnection.register_connection_implementation("Searchkick::Results", SearchkickConnection)
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
query example($id: ID!) {
  node(id: $id) {
    ...on TreeType {
      name
      children {
        edges {
          node { name }
        },
      }
    }
  }
}
```

**Steps to reproduce**

Any query that goes through a `GraphQL::Relay::RelationConnection` will fail.

**Expected behavior**

I'm not sure what the intended interpaly is between the `Relay::RelationConnection` and `Pagination::Connections`. It feels like they are both trying to serve the same role. I'm open to ideas or discussion about the proper way to make these two play together.

**Comment by TikiTDO** [comment]
Found [the docs](https://graphql-ruby.org/pagination/custom_connections) that helped me figure out the migration process.

**Comment by rmosolgo** [comment]
Glad you got to the bottom of it! Yep, GraphQL::Relay::BaseConnection is deprecated for that new approach. It's a lot more flexible, please do open another issue if you into any trouble in the migration.
