### ISSUE TITLE
Automatically strip whitespace from user input

### ISSUE THREAD

**Issue by thibaultcouraud** [rmosolgo/graphql-ruby#3328]
**Is your feature request related to a problem? Please describe.**

I have many schema objects in my app, with many fields for each one. Sometime the input fields filled by the user includes trailing or leading spaces.

**Describe the solution you'd like**

I would like to automatically strip whitespace from the user's inputs. And if possible without changing the type of all the actual fields in my code.

**Describe alternatives you've considered**

I tried many solutions, included:

- `Field Extensions` by automatically load a custom extension to all fields with type `String`. But I can't return a stripped value easily
- Overwrite the default `GraphQL::Types::String` by my own `String` type that strip value directly in `coerce_result` or `coerce_input`, but I can't get my overwritten type to be loaded

So I wonder if you have an idea to do it so. I already searched on your actual issues but I didn't found something relevant for my need.

Thank you very much.

**Comment by rmosolgo** [comment]
👋  Great question, I agree there's not a perfect out-of-the-box solution here. 

A custom scalar is a good idea, you could do it like this: 

```ruby 
# app/graphql/types/string.rb
class Types::String < GraphQL::Types::String 
  # Override the default behavior to _always_ trim trailing whitespace
  def coerce_input(value, ctx)
    if value.is_a?(String)
      value.strip 
    else 
      nil 
    end
  end 
end 
```

Then, replace all uses of `String` in your schema definition with `Types::String` (so it stops referencing Ruby's `::String` class and starts referencing your custom class). 


If these strings with extra whitespace are _always_ passed as `variables`, then you could also implement this in your controller, cleaning up the bad input _before_ passing it to graphql, for example: 

```
variables = trim_trailing_whitespace(params[:variables].to_unsafe_h)

# ... 

def trim_trailing_whitespace(value)
  case value
  when String
    value.strip
  when Array 
    value.map { |v| trim_trailing_whitespace(v) }
  when Hash 
    value.each_with_object({}) { |(k, v), new_h| new_h[k] = trim_trailing_whitespace(v) }
  else 
    value 
  end 
end 
```


If you try one of those and it doesn't work out, please share the code you tried and what happened when you tried it!

**Comment by thibaultcouraud** [comment]
Thank you very much for this explanation and the two examples! I'll try them and let you know.
