### ISSUE TITLE
`throw` from GraphQL::Dataloader jobs results in `UncaughtThrowError`

### ISSUE THREAD

**Issue by mclark** [rmosolgo/graphql-ruby#3331]
This is a bit of an unconventional situation, I'm trying out the dataloader outside of a graphql context but I thought it's worth logging this problem just in case it can surface in graphql, perhaps in fields. This is probably best explained with a short example:

```ruby
catch(:hello) do
  dataloader = GraphQL::Dataloader.new
  dataloader.append_job do
    throw :hello
  end
  dataloader.run # => UncaughtThrowError: uncaught throw :hello
end
```

Currently, the `GraphQL::Dataloader` class detects error classes and raises them as expected. However, a `throw` inside the client code gets turned into a `UncaughtThrowError` instead of just propagating up until a `catch` is encountered. If the code that handles the other errors is updated to handle `UncaughtThrowError` and re-throw the `tag` attribute, it should be seamless.

**Versions**

`graphql` version: 1.12.4
`rails` (or other framework): rails 6
other applicable versions (`graphql-batch`, etc)

**Steps to reproduce**

See description above ☝️ 

**Expected behavior**

Something thrown from within a Fiber running a Dataloader job can be caught by code outside the job.

**Actual behavior**

The fiber finishes without the thrown value ever being caught, resulting in `UncaughtThrowError`.

**Comment by rmosolgo** [comment]
Thanks for reporting this! I agree, the throw should be "transparently" passed along to main Fiber, so that any existing handlers can catch it.
