### ISSUE TITLE
Types in namespaces

### ISSUE THREAD

**Issue by stoivo** [rmosolgo/graphql-ruby#3344]
**Is your feature request related to a problem? Please describe.**

I have the following code:. Wrapped all several types together since they will only be used here.
```ruby
module Types
  module PaycheckReport
    class StatusReportType < Types::AltinnPaycheckStatusReportDataType
      field :running_base, Float, null: false
    end

    class StatusReportSumsType < Types::BaseObject
      field :salary, Float, null: false
      field :employer_tax, Float, null: false
    end

    class StatusReportsType < Types::BaseObject
      field :reports, [StatusReportType], null: false
      field :sum, StatusReportSumsType, null: false
    end

    class RootType < Types::BaseObject
      field :year, Integer, null: false
      field :reports,
            StatusReportsType,
            null: false
    end
  end
end
```
This will generate 

```gql
type Root {
  reports: StatusReports!
  year: Int!
}

type StatusReport {
  id: ID!
  employerTax: Float!
  runningBase: Float!
  salary: Float!
}

type StatusReportSums {
  employerTax: Float!
  salary: Float!
}

type StatusReports {
  reports: [StatusReport!]!
  sum: StatusReportSums!
}
```

If you had two of these modules which would define a RootType it would raise GraphQL::Schema::DuplicateTypeNamesError. 

**Describe the solution you'd like**

One solution would be to just add graphql_name to each of them like
```
module Types
  module AReport
    class RootType < Types::BaseObject
      graphql_name "AReportRoot"
      field :one, Int, null: false
    end
  end
end

module Types
  module BReport
    class RootType < Types::BaseObject
      graphql_name "BReportRoot"
      field :one, Int, null: false
    end
  end
end
```

Another solution would be to change the code to use the module namespace. I did try to patch the code. https://github.com/rmosolgo/graphql-ruby/blob/63ae8309e5ad1e6e426080c6c7cf224a9b28673f/lib/graphql/schema/member/base_dsl_methods.rb#L104-L113
```
```

https://github.com/rmosolgo/graphql-ruby/blob/63ae8309e5ad1e6e426080c6c7cf224a9b28673f/lib/graphql/schema/member/base_dsl_methods.rb#L104-L113
```ruby 
# Creates the default name for a schema member.
# The default name is the Ruby constant name,
# without any namespaces and with any `-Type` suffix removed
def default_graphql_name
  @default_graphql_name ||= begin
    raise GraphQL::RequiredImplementationMissingError, 'Anonymous class should declare a `graphql_name`' if name.nil?

    if name.starts_with?("GraphQL::")
      name.split("::").last.sub(/Type\Z/, "")
    else
      name
        .split("::")
        .difference(%w[GraphQL Types Attributes Mutations Subscriptions Introspection Schema Directive Relay])
        .join("")
        .sub(/Type\Z/, "")
    end
  end
end
```

I don't think the code perfect but it works. Is this a feature you would like to have or do I have to use `graphql_name`

**Describe alternatives you've considered**

Described above

**Additional context**

none

And thanks for all the work on graphql-ruby

**Comment by rmosolgo** [comment]
Hi, thanks for the great write-up! I think you've foudn everything that's there.

> Is this a feature you would like to have or do I have to use `graphql_name`?

Personally, I'm happy to keep graphql-ruby the way it is. 

But, if you want this behavior more broadly, you can also override `def default_graphql_name` in your base class to get the behavior you want. If you give it a try and run into trouble, please share the code you tried and what happened when you tried it!

**Comment by stoivo** [comment]
We added a monkeypatch to achive this. This works for up just want to share it with all of you

```ruby 
# https://github.com/rmosolgo/graphql-ruby/issues/3344
module GraphQL::Schema::Member::BaseDSLMethods
  def default_graphql_name
    @default_graphql_name ||= begin
      raise ::GraphQL::RequiredImplementationMissingError, 'Anonymous class should declare a `graphql_name`' if name.nil?

      if name.starts_with?("GraphQL::")
        name.split("::").last.sub(/Type\Z/, "")
      else
        name
          .split("::")
          .difference(%w[Types Attributes Mutations Subscriptions])
          .join("")
          .sub(/Type\Z/, "")
      end
    end
  end
end
```

**Comment by fameoflight** [comment]
@rmosolgo any way to achieve this natively. This comes in handy while combining schemas.

Use case is microservice serving graphql data. Would great to automatically prepend to all objects generated.
