### ISSUE TITLE
[PRO]  another warning: "Passing 'script' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 "

### ISSUE THREAD

**Issue by xxx** [rmosolgo/graphql-ruby#3347]
**Describe the bug**

Heya, got another one. We see the following warning now after updating to graphql-pro 1.17.5:

Passing 'script' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /home/mpd/.rvm/gems/ruby-2.7.2/gems/graphql-pro-1.17.5/lib/graphql/pro/subscriptions/redis_storage.rb:457:in `rescue in eval_lua')

<snipped the rest because I don't think it matters for this>

**Comment by rmosolgo** [comment]
Ugh, sorry about that. This time I've learned my lesson: I'll add `redis-namespace` to my test suite and make sure it passes without warnings. I'll follow up here when a new version is ready.

**Comment by rmosolgo** [comment]
🚢 'd 1.17.7. It now uses `redis.redis` for that `script` call if it detects a `Redis::Namespace` instance, and the _tests_ pass without any warnings when they use `Redis::Namespace`. So, please let me know if you see another warning, but I think we're in a good place here!
