### ISSUE TITLE
Allow setting subject for GraphQL::Pro CanCan checks

### ISSUE THREAD

**Issue by thomasmarshall** [rmosolgo/graphql-ruby#3350]
**Is your feature request related to a problem? Please describe.**

The GraphQL::Pro CanCan integration sets the `subject` used for CanCan checks automatically:

- For types and fields, the subject is the current object.
  
  ```ruby
  class Types::UserType < Types::BaseObject
    # can?(:read, object)
    can_can_action :read

    # can?(:manage, object)
    field :email, String, null: false, can_can_action: :manage
  end
  ```
- For mutations, the subject is an instance of the mutation class.
  
  ```ruby
  class Mutations::UserUpdate < Mutations::BaseMutation
    # can?(:run_mutation, Mutations::UserUpdate)
    can_can_action :run_mutation
  end
  ```

However, this approach can't work for root query type fields:

```ruby
class Types::QueryType < Types::BaseObject
  # can?(:manage, ???)
  field :user_by_email, Types::UserType, null: true, can_can_action: :manage
end
```

In this case, GraphQL::Pro won't attempt to do a CanCan check because `object` is `nil`. That makes sense, because both an `action` and `subject` are required for a CanCan check, but it does mean we're unable to use the CanCan integration for this use-case.

**Describe the solution you'd like**

I'd like to be able to pass in a custom subject to CanCan checks, such as a model class or symbol:

```ruby
class Types::QueryType < Types::BaseObject
  # can?(:manage, User)
  field :user_by_email, Types::UserType, null: true,
    can_can_action: :manage,
    can_can_subject: User

  # can?(:access, :dashboard)
  field :dashboard, Types::DashboardType, null: false,
    can_can_action: :access,
    can_can_subject: :dashboard
end
```

```ruby
class Mutations::UserUpdate < Mutations::BaseMutation
  # can?(:manage, User)
  can_can_action :manage
  can_can_subject User
end
```

**Describe alternatives you've considered**

Instead of authorizing the root query fields, I tried using resolver classes with the mutation integration:

```ruby
Resolvers::BaseResolver.include(GraphQL::Pro::CanCanIntegration::MutationIntegration)

class Resolvers::UserByEmail < Resolvers::BaseResolver
  # can?(:run_resolver, Resolvers::UserByEmail)
  can_can_action :run_resolver
end
```

This works, but is obviously an unintended/unsupported solution. It also doesn't enable standard CanCan checks like `can? :manage, User` or `can? :access, :dashboard`.

I also considered using `#authorized?` on field definitions, but that would mean some fields using the CanCan integration and others using a different mechanism.

```ruby
  field :user_by_email, Types::UserType, null: true do
    def authorized?(object, args, context)
      context[:can_can_ability].can?(:manage, User)
    end
  end
```

**Comment by rmosolgo** [comment]
Hey, thanks for the great writeup on this issue. I agree that the `can_can_subject:` option like you suggested is a good one. I'll add it and follow up here!

**Comment by rmosolgo** [comment]
🚢 'd in graphql-pro 1.17.7! Please let me know if you give it a try and run into any trouble. Thanks again for the great suggestion.

**Comment by thomasmarshall** [comment]
Fantastic, it's working great so far – thanks @rmosolgo!
