### ISSUE TITLE
Allow FieldExtension to have access to lookahead

### ISSUE THREAD

**Issue by bbugh** [rmosolgo/graphql-ruby#3351]
**Is your feature request related to a problem? Please describe.**

We have a `FieldExtension` that needs access to `lookahead`, but if we add it to `extras` on the field, it breaks if the field resolver method doesn't consume extra values, or we have to manually check for and delete it.

**Describe the solution you'd like**

Some way to reliably access the field's lookahead in `FieldExtension` `resolve` and `after_resolve`, without specifying `extras: [:lookahead]`.

**Describe alternatives you've considered**

context.query.lookahead accesses the query-level lookahead, and you can finagle the lookahead with nested checks, but it's error prone, e.g.: `context.query.lookahead.selections[0].selections` only works for the top level selections.

**Additional context**

From Slack conversation: https://app.slack.com/client/T044QJ50C/C07MVL1AB/thread/C07MVL1AB-1613760442.150200

**Comment by rmosolgo** [comment]
For a work-around, here's what I've done in the past: 

```ruby
        def apply
          if field.extras.include?(:ast_node)
            @delete_ast_node = false
          else
            field.extras([:ast_node])
            @delete_ast_node = true
          end
        end
        
        def resolve(arguments:, object:, **_rest)
          ast_node = arguments[:ast_node]

          if @delete_ast_node
            arguments = arguments.dup
            arguments.delete(:ast_node)
          end

          do_something(arguments, ast_node)
          yield(object, arguments)
        end
```


Basically: 


1. Check if the field already has the `extra` that you need, and if it does, set the `@delete_...` flag to false
2. If it doesn't, then add the extra and set the `@delete_...` flag to true 
3. During resolution, delete the arg if `@delete_...` is true 

But I think there are still edge cases where that isn't going to work -- it'd be better to have an API that was _scoped_ to the extension itself. I don't have a clue how it'll _work_ though 🙈

**Comment by bbugh** [comment]
I was imagining something like `GraphQL::Schema::FieldExtension` having a getter for `lookahead` that can be called. Alternatively, maybe query can look up a lookahead for a field, like `context.query.lookahead_for(field)` or something.

Yours is similar to how I worked around it, though it's more verbose because I'm passing a memo to `after_resolve`. 

```ruby
class FieldSelectExtension < GraphQL::Schema::FieldExtension
  def apply(*args)
    if field.extras.include?(:lookahead)
      @field_select_keep_lookahead = true
    end
    field.extras([:lookahead])
    super
  end

  def resolve(object:, arguments:, **rest)
    memo = {}

    unless @field_select_keep_lookahead
      memo[:lookahead] = arguments[:lookahead]
      field.extras.delete(:lookahead)
      arguments = arguments.dup.tap { |args| args.delete(:lookahead) }
    end

    yield(object, arguments, memo, **rest)
  end

  def after_resolve(value:, memo:, **rest)
    return super unless value.is_a?(ActiveRecord::Relation) && memo[:lookahead]

    lookahead = memo[:lookahead]

    fields_to_select = lookahead.selections.map { |x| x.name.to_s }
    model_column_names = value.klass.column_names
    database_columns = fields_to_select & model_column_names

    value.select(database_columns)
  end
end
```

If not for the lookahead workaround, it would be much smaller:

```ruby
class FieldSelectExtension < GraphQL::Schema::FieldExtension
  def after_resolve(value:, **rest)
    return super unless value.is_a?(ActiveRecord::Relation) && lookahead

    fields_to_select = lookahead.selections.map { |x| x.name.to_s }
    model_column_names = value.klass.column_names
    database_columns = fields_to_select & model_column_names

    value.select(database_columns)
  end
end
```
