### ISSUE TITLE
Two subscriptions with the same name on different schemas get triggered whenever one of them is triggered

### ISSUE THREAD

**Issue by khamusa** [rmosolgo/graphql-ruby#3353]
First of all, thanks for this amazing gem!

Here's my stack:
graphql-ruby 1.11.4
ruby 2.7.1
rails 6.0.3

I have two subscriptions on two different schemas. They have the same name and accept the same arguments. I'm using Action Cable. Here's the basic schema / subscription setup:
```ruby
# First schema:
class ParticipantsSchema < LetsConfSchema
  use GraphQL::Subscriptions::ActionCableSubscriptions,
    broadcast: true,
    default_broadcastable: true
  
  mutation(Types::Participant::MutationType)
  query(Types::Participant::QueryType)
  subscription(Types::Participant::SubscriptionType)
end

# First schema subscription
module Types::Participant
  class SubscriptionType < Types::BaseObject
    graphql_name 'LetsConfParticipantSubscriptions'

    field :room_live_widget_changed,
          subscription: Subscriptions::Participants::Room::LiveWidgetChangedSubscription
  end
end

# Second Schema
class HostsSchema < LetsConfSchema
  use GraphQL::Subscriptions::ActionCableSubscriptions,
    broadcast: true,
    default_broadcastable: true

  mutation(Types::Host::MutationType)
  query(Types::Host::QueryType)
  subscription(Types::Host::SubscriptionType)
end

# Second schema subscription
module Types::Host
  class SubscriptionType < Types::BaseObject
    graphql_name 'LetsConfHostSubscriptions'

    field :room_live_widget_changed,
          subscription: Subscriptions::Hosts::Room::LiveWidgetChangedSubscription
  end
end
```

The following trigger on the HostsSchema sends an pdate to a user that subscribed through the ParticipantsSchema (and vice-versa) with the same room_id:
```ruby
HostsSchema.subscriptions.trigger(
 :room_live_widget_changed,
 { room_id: widgetable.room_id },
 { room: widgetable.room }
)
```
What we actually do is that we always trigger both subscriptions at the same time (we use two different schemas to control public information according to user types, but in this case, they're pretty much the same), which causes someone subscribed to either one of the schemas to receive the message twice.

I believe the issue is on the fact that the schema name is not included onto the redis keys used to identify the connections and subscriptions.

Thoughts?

**Comment by rmosolgo** [comment]
Yes, that's right -- under the hood, it all goes through ActionCable and the ActionCable event name doesn't include the schema name. `ActionCableSubscriptions` supports a `namespace:` option: 

https://github.com/rmosolgo/graphql-ruby/blob/a17a46ee1fd8265237eb2c29880a4f98703e6451/lib/graphql/subscriptions/action_cable_subscriptions.rb#L89

You can use that in your schemas to distinguish them:

```ruby 
use GraphQL::Subscriptions::ActionCableSubscriptions, namespace: self.name
````

Let me know if that doesn't work for you!
