### ISSUE TITLE
Enabling custom schema introspection throws an error

### ISSUE THREAD

**Issue by moustacheful** [rmosolgo/graphql-ruby#3356]
**Describe the bug**

When introducing an introspection module for a schema, it throws an error when attempting to query on versions < 1.12.0.
This is done as stated here: https://graphql-ruby.org/schema/introspection.html#customizing-introspection

**Versions**

`graphql` version: 1.10.x~1.11.x (tried many, fails on all versions up to 1.12.x which works)
`rails` (or other framework): 6.0.3.5
other applicable versions (`graphql-batch`, etc): graphql-batch: 0.4.3

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok).
Are you using [interpreter](https://graphql-ruby.org/queries/interpreter.html)? Any custom instrumentation, etc?

api_schema.rb
```rb
class ApiSchema < GraphQL::Schema
  introspection ApiIntrospection # if we comment this line, it works without issues.

  # ... rest of the code
end
```

api_introspection.rb
```rb
# frozen_string_literal: true

module ApiIntrospection
  def self.introspection_enabled?(context)
    context.fetch(:introspection_enabled, false)
  end

  class SchemaType < GraphQL::Introspection::SchemaType
    def self.authorized?(_, context)
      super && ApiIntrospection.introspection_enabled?(context)
    end
  end

  class TypeType < GraphQL::Introspection::TypeType
    def self.authorized?(_, context)
      super && ApiIntrospection.introspection_enabled?(context)
    end
  end
end
```

**Steps to reproduce**

When introducing an introspection module for a schema, it throws an error when attempting to query on versions < 1.12.0

**Expected behavior**

I expect to be able to use the introspection and being able to query successfully. In my particular case, I'm trying to make the introspection results only available to some users via custom logic and a boolean passed to the gql context.

**Actual behavior**

I get the following error (and stacktrace)

```
NoMethodError: undefined method `arguments_class=' for #<GraphQL::Schema::Field:0x00007fc9a6584cc0>\nDid you mean?  argument_class
/Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.11.8/lib/graphql/query/arguments.rb:13:in `construct_arguments_class',
/Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.11.8/lib/graphql/schema/traversal.rb:217:in `visit_field_on_type',
/Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.11.8/lib/graphql/schema/traversal.rb:70:in `block in resolve_late_bound_fields',
/Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.11.8/lib/graphql/schema/traversal.rb:63:in `each',
/Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.11.8/lib/graphql/schema/traversal.rb:63:in `resolve_late_bound_fields',
/Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.11.8/lib/graphql/schema/traversal.rb:48:in `initialize',
/Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.11.8/lib/graphql/schema.rb:1978:in `new',
/Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.11.8/lib/graphql/schema.rb:1978:in `rebuild_artifacts',
/Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.11.8/lib/graphql/schema.rb:1007:in `to_graphql',
/Users/user/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.11.8/lib/graphql/schema/member/accepts_definition.rb:120:in `to_graphql'
```

**Additional context**

With these details, we can efficiently hunt down the bug!

**Comment by rmosolgo** [comment]
Hey, thanks for reporting this. I was able to add a failing test case for it: 

<details>
<summary>Failing test diff</summary>
<p>

```diff
diff --git a/spec/graphql/schema/introspection_system_spec.rb b/spec/graphql/schema/introspection_system_spec.rb
index b55bb5a13..dc11b9268 100644
--- a/spec/graphql/schema/introspection_system_spec.rb
+++ b/spec/graphql/schema/introspection_system_spec.rb
@@ -244,4 +244,39 @@ describe GraphQL::Schema::IntrospectionSystem do
       end
     end
   end
+
+
+  class AuthIntrospectionSchema < GraphQL::Schema
+    module ApiIntrospection
+      def self.introspection_enabled?(context)
+        context.fetch(:introspection_enabled, false)
+      end
+
+      class SchemaType < GraphQL::Introspection::SchemaType
+        def self.authorized?(_, context)
+          super && ApiIntrospection.introspection_enabled?(context)
+        end
+      end
+
+      class TypeType < GraphQL::Introspection::TypeType
+        def self.authorized?(_, context)
+          super && ApiIntrospection.introspection_enabled?(context)
+        end
+      end
+    end
+
+    class Query < GraphQL::Schema::Object
+      field :echo, String, null: false do
+        argument :message, String, required: true
+      end
+    end
+
+    introspection(ApiIntrospection)
+    query(Query)
+  end
+
+  it "works with authorized" do
+    pp AuthIntrospectionSchema.execute(GraphQL::Introspection::INTROSPECTION_QUERY).to_h
+    pp AuthIntrospectionSchema.execute(GraphQL::Introspection::INTROSPECTION_QUERY, context: { introspection_enabled: true }).to_h
+  end
 end
 ```
 
</p>
</details>

I could make it pass by switching the test to use the new runtime modules: 

```diff 
+ use GraphQL::Execution::Interpreter 
+ use GraphQL::Analysis::AST 
```

Those modules are enabled by default in 1.12.0, which is probably why your code worked fine on that version. 

It looks like the graphql-ruby test suite was missing an example with a _class-based_ schema, a _non-interpreter_ runtime, _and_ custom introspection. I tried a quick fix for this issue, but it didn't work: 

```diff
diff --git a/lib/graphql/schema/traversal.rb b/lib/graphql/schema/traversal.rb
index 8c6759b98..1fa8041af 100644
--- a/lib/graphql/schema/traversal.rb
+++ b/lib/graphql/schema/traversal.rb
@@ -119,7 +119,7 @@ Some late-bound types couldn't be resolved:
               member.introspection_system.entry_points.each do |introspection_field|
                 # Visit this so that arguments class is preconstructed
                 # Skip validation since it begins with "__"
-                visit_field_on_type(schema, member.query, introspection_field, dynamic_field: true)
+                visit_field_on_type(schema, member.query, introspection_field.graphql_definition, dynamic_field: true)
               end
             end
           end
```

However, I don't plan to spend more time fixing this because I don't have enough bandwidth to support the legacy runtime. I recommend either: 

- Switch to the new runtime modules, as shown above, 
- Or, if you want to find the fix in GraphQL-Ruby, I'd be happy to merge it and release a new version. Hopefully my failing test above would get you started in the right direction. 

Sorry I can't be more help, but I hope that's something!

**Comment by dacuna-ic** [comment]
Thanks for the thorough explanation! I would've upgraded but versions 1.12.x onward also seem to eschew the usage of `GraphQL::Relay::BaseConnection` (e.g. register_connection_implementation, etc) in favor of `GraphQL::Pagination::Connection` which seems like a bigger endeavor code-wise.

Is there a way of using 1.12.x with the old Relay connections?

I'll see if I have time for creating a PR otherwise.

**Comment by moustacheful** [comment]
Thanks for the thorough explanation! I would've upgraded but versions 1.12.x onward also seem to eschew the usage of `GraphQL::Relay::BaseConnection` (e.g. register_connection_implementation, etc) in favor of `GraphQL::Pagination::Connection` which seems like a bigger endeavor code-wise.

Is there a way of using 1.12.x with the old Relay connections?

I'll see if I have time for creating a PR otherwise.

**Comment by rmosolgo** [comment]
Yes, you'll find a code snippet for getting the old behavior in the changelog: 

https://github.com/rmosolgo/graphql-ruby/blob/master/CHANGELOG.md#1120-20-january-2021
