### ISSUE TITLE
ActiveSupportNotificationsTracing doc says "prefix" instead of "suffix"

### ISSUE THREAD

**Issue by bbugh** [rmosolgo/graphql-ruby#3358]
**Describe the bug**

On this page: https://graphql-ruby.org/api-doc/1.12.5/GraphQL/Tracing/ActiveSupportNotificationsTracing

It says "prefix" and not "suffix". I didn't look at the names of the events, so I spent some time confused why my subscribe wasn't picking up the graphql events.

**Versions**

`graphql` version: 1.12.5, maybe others

**Additional context**

I looked at the `gh-pages` and it looks like it's maybe generated? Not sure where the best place is to fix that doc.

**Comment by rmosolgo** [comment]
Derp, thanks for pointing that out! Yes, it's generated from comments in the source: 

https://github.com/rmosolgo/graphql-ruby/blob/377fd26bde60757d2fbd05f65191a70c4004bce8/lib/graphql/tracing/active_support_notifications_tracing.rb#L5-L7

If you update the source, then the next rubygems release will cause those API docs to be updated. 

The implementation was updated in #2562, but naturally, the docs fell behind 😖
