### ISSUE TITLE
Support for read arguments inside GraphQL::Pagination::Connection

### ISSUE THREAD

**Issue by gtkatakura** [rmosolgo/graphql-ruby#3359]
**Is your feature request related to a problem? Please describe.**

Today we only can use the arguments first/after/last/before into `GraphQL::Pagination::Connection`, but I try to access an argument like a `sorting_field` inside my custom `Connection`, but I can't because any data inside `GraphQL::Pagination::Connection` have access to arguments.

**Describe the solution you'd like**

Add `@args` inside to `GraphQL::Pagination::Connection`

**Additional context**

Example:

```ruby
class MyCustomRelation < GraphQL::Pagination::Connection
  def nodes
    # access to all args of the connection
    args[:sorting_field]
  end
end
```

**Comment by rmosolgo** [comment]
Hi! Thanks for opening this issue. I ran into this problem in my day job, too, and we'll have to update 1.12 so you can access `arguments` inside these new classes. 

I think it could be implemented by: 

- Adding `arguments:` to the constructor here: https://github.com/rmosolgo/graphql-ruby/blob/377fd26bde60757d2fbd05f65191a70c4004bce8/lib/graphql/pagination/connection.rb#L56
- Adding it to the initialization params here: https://github.com/rmosolgo/graphql-ruby/blob/377fd26bde60757d2fbd05f65191a70c4004bce8/lib/graphql/pagination/connections.rb#L77-L89
- And adding an assignment here: https://github.com/rmosolgo/graphql-ruby/blob/377fd26bde60757d2fbd05f65191a70c4004bce8/lib/graphql/schema/field/connection_extension.rb#L38-L51

I think those changes (along with a test) would do the trick. I'll take a look soon if nobody gets to it in the meantime.

(cc @parkr)
