### ISSUE TITLE
Pro: subscriptions can't be atomic

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#3363]
The current Pusher and Ably implementations have the same flow: 

1. HTTP Post `subscription { ... }` which returns a X-Subscription-ID header 
2. Client subscribes to the vendor's channel with that name 
3. Updates come over the channel, until the client unsubscribes from it 

However, some server events may occur _between_ the response in 1. and the subscribe in 2., and the framework doesn't have any way to account for this. 

Somehow, ["atomic" subscriptions](https://github.com/graphql/graphql-spec/issues/283) should be possible with GraphQL-Pro. (I don't think it's _possible_ with ActionCable -- if clients disconnect, then events are lost. But at least _Ably_ will replay events for clients.)

**Comment by jscheid** [comment]
@rmosolgo I don't think this is accurate for Ably, thanks to https://github.com/rmosolgo/graphql-ruby/pull/3210
Let me know if you'd like me to elaborate.

I can't speak to Pusher, which I haven't used so far.

**Comment by rmosolgo** [comment]
Discussing this in more detail here: https://github.com/rmosolgo/graphql-ruby/issues/5138
