### ISSUE TITLE
GraphQL::Dataloader appears to break trace chain for Datadog

### ISSUE THREAD

**Issue by srgoldman** [rmosolgo/graphql-ruby#3366]
**Describe the bug**

When inspecting the flame graph or span list in Datadog, I expect to see the related spans aggregated under their parents. When I introduced GraphQL::Dataloader into my schema, that appeared to break the chain (in the datadog debug output, many of the graphql.execute spans ended up with a parent id of 0).

**Versions**

`graphql` version: 1.12.5
`rails` (or other framework): rails
other applicable versions (`graphql-batch`, etc)

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok).

```
class FigsCatalogSchema < GraphQL::Schema
  include ApolloFederation::Schema
  TRACING_SERVICE_NAME = ENV.fetch('DD_SERVICE', 'figs-catalog-misconfigured')

  mutation(Types::MutationType)
  query(Types::QueryType)

  use GraphQL::Dataloader
  use GraphQL::Tracing::DataDogTracing, analytics_enabled: true, service: "#{TRACING_SERVICE_NAME}-graphql"
  use ApolloFederation::Tracing

  def self.execute(query_str = nil, variables: {}, context: {}, **kwargs)
    # make sure we can see the variables passed to queries and mutations.
    # filter out sensitive data the same way we do for the logs
    f = ActiveSupport::ParameterFilter.new(Rails.application.config.filter_parameters)
    filtered_vars = variables.blank? ? variables : f.filter(variables)
    current_span = Datadog.tracer.active_span
    current_span.set_tags(query: query_str, variables: filtered_vars) if current_span

    super.tap do |result|
      h = result.to_h
      if h.dig('errors').present? || h.dig('data', 'errors').present?
        Rails.logger.warn("query: #{query_str}, variables: #{filtered_vars}, result: #{h}")
        current_span.set_tag('result', h) if current_span
      end
    end
  end
end
```

**Steps to reproduce**

Just add `use GraphQL::Dataloader` to a schema and make a query that will pull some data from the database.
Inspect the trace in Datadog.
When Dataloader is part of the schema, the database calls do not get reported properly under the graphql.execute call (some do but ones under the schema don't).

**Expected behavior**

![image (1)](https://user-images.githubusercontent.com/251189/109333416-4b200200-7814-11eb-8d59-e973139dab66.png)

**Actual behavior**

![image](https://user-images.githubusercontent.com/251189/109333389-40fe0380-7814-11eb-9534-3bc4ffe12fb1.png)

Place full backtrace here (if a Ruby exception is involved):

<details>
<summary>Click to view exception backtrace</summary>

```
Something went wrong
2.6.0/gems/graphql-1.9.17/lib/graphql/subscriptions/instrumentation.rb:34:in `after_query'
… don't hesitate to include all the rows here: they will be collapsed
```

</details>

**Additional context**

Seth Goldman  4:09 PM
Greetings. I've been working on a new rails project (basically splitting off functionality from an existing project). I'm having some performance issues and am trying to understand why my datadog APM flame graphs appear to be missing data. While the underlying code is different, I would still expect to see some postgres spans under the execute.graphql span but I don't. Here's what the old graph looks like and the new one. As far as I can tell, the configurations are identical (although the ddtrace versions are different).
2 files 
image.png

image.png

4:10
the datadog tracer code is identical
4:11
the versions of graphql-ruby are different though. The working one on the left is 1.11.6 and on the right is 1.12.5

Seth Goldman  5:43 PM
There seems to be a disconnect between the execute.graphql span and the Query.collections span. The latter appears to have the database and active record calls rolled up as I expect but it is created with a parent id of 0 so it doesn't roll up under the execute.graphql span.

Seth Goldman  5:49 PM
of course the execute.graphql span is also missing a parent id.

Seth Goldman  6:31 PM
it appears to be related to my disabling graphql-batch and instead using dataloaders.
6:32
If I restore use GraphQL::Batch and remove use GraphQL::Dataloader from the schema, the tracing works as expected.

rmosolgo  5:59 AM
@Seth Goldman GraphQL::Dataloader uses Fibers under the hood, I bet it has to do with that. Could you please open an issue with those screenshots and some info about how your tracer is setup? I’d like to try to fix that.

**Comment by rmosolgo** [comment]
Thanks for opening this issue! I bet there's a problem with `yield` blocks being called after-the-fact. I'll look into it as soon as I get a chance. The only way I can think to hunt it down is to improve the tests to use the _real_ DataDog library, and see if I can replicate this bug that way.

**Comment by srgoldman** [comment]
Sounds like fun ;-). Let me know if I can help in any way. I can easily repro in my environment but wouldn't know where to put the breakpoints to debug the yield blocks.

**Comment by coding-chimp** [comment]
I'm not really too familiar with the datadog client, but I think the problem might be that it's keeping track of the currently active span in a [fiber-local variable](https://github.com/DataDog/dd-trace-rb/blob/079f18f410f590252030578aa240576f3fc4c6e5/lib/ddtrace/opentracer/thread_local_scope_manager.rb#L35-L37), so it's getting lost every time a new fiber is spawned. 

Skylight's agent has a similar problem where it's keeping track of the current trace in fiber-local variable. I've [opened a PR](https://github.com/skylightio/skylight-ruby/pull/174) on their side to fix this issue. I have no idea how this could be solved here. 🤷‍♂️

**Comment by rmosolgo** [comment]
Thanks for sharing what you found on that, @coding-chimp -- I'm sure you're spot-on about what's wrong here. I opened https://github.com/DataDog/dd-trace-rb/issues/1389 to see if the folks there have a suggestion.

**Comment by rmosolgo** [comment]
Could you give this a try on 1.12.9? It includes a change to copy `Thread.current[...]` pairs into new fibers (#3461) and I bet it will make this start working again...

**Comment by srgoldman** [comment]
Happy to. Have to wait until next week but will put it on my todo list :-)

On May 7, 2021, at 1:51 PM, Robert Mosolgo ***@***.******@***.***>> wrote:



Could you give this a try on 1.12.9? It includes a change to copy Thread.current[...] pairs into new fibers (#3461<https://github.com/rmosolgo/graphql-ruby/pull/3461>) and I bet it will make this start working again...
