### ISSUE TITLE
Is there a way to hook into the rescue of GraphQL::ExecutionError for external bug reporting?

### ISSUE THREAD

**Issue by thornomad** [rmosolgo/graphql-ruby#3371]
Been searching a bit but not seeing what I am looking for—so I thought I would ask: _do you have suggestions for how to hook into the rescue of `GraphQL::ExecutionError` so that we may send a "bug report" to our reporter before the valid `errors` payload is returned?_

Because the `GraphQL::ExecutionError` are rescued the errors don't propagate all the way to be caught by our reporter.  This is good because we want the client to receive a valid payload.  But it's not good because the exception has been silenced.  

I had thought about just sending the `errors` array that comes in the JSON payload but realize I really want to get at some of the underlying information that we have stored in our errors (we have subclassed `GraphQL::ExecutionError` in some cases.

Any suggestions?

**Comment by rmosolgo** [comment]
There's not a built-in hook for this, hmmm 🤔 . You mentioned that you've subclassed that error. How about _always_ using a subclass, then reporting the error in `def initialize`? 

Alternatively, you could get the error _objects_ after running the query like this: 

```ruby 
response = MySchema.execute(...)
response.context.errors.each do |err|
  log_error(err)
end 
```

That _should_ contain all the error objects that will end up in the top-level `"errors"` key in the response. 

To do that for _every_ query, you could use the `after_query` hook on a query instrumenter: https://graphql-ruby.org/queries/instrumentation.html

Want to give one of those a try? Let me know how it goes!

**Comment by thornomad** [comment]
Well, it's good to know at least I am not missing some fun!  

I actually went ahead and implemented a simpler approach was just to check for the `response["errors"]` array.  That does work fine and we see exactly what the client would see.  However, in our case, the `errors` payload doesn't have quite enough information to be useful to the reporter (we don't show the stacktrace, for example).  It looks like the `response.context.errors` approach gives me more of that (and also leads to sublcassing!).

However, there are some errors that graphql-ruby will raise on it's own that we still miss; for example, if a field is incorrectly requested it raises an error to the effect of `"Field 'bob' doesn't exist on type 'Schedule'"`.  Our sublcass never sees those errors but we do want to see them in our reporter.  Sone of these also don't show up in `response.context.errors`.

So I ended up with a two tier approach: if `response.context.errors` has errors then use those; otherwise report the `response["errors"]` array.

I was hoping for a grand unifying theory of everything.  But in the meantime I think this will do well enough.  Thanks for the informative response.

**Comment by niclas-ahden** [comment]
Thanks for this issue, it helped a lot!
 
I'd love to see this issue re-opened. The suggestions above are great workarounds but seem to miss some errors and won't include full context on others.

I stumbled on the same issue of not all errors being accessible through different methods and was hoping for an officially supported way. E.g. a hook with args similar to `rescue_from` that all errors pass through. That'd let users:

1. Report any error with full context and customization as needed.
2. Find `graphql-ruby`'s intended way of handling error reporting.
3. Know that future errors will be reported as the gem develops.

I think this is a common need and that many users _think_ that they're reporting well-enough when in fact they're missing errors and/or context with their current setup.

That said, thank you for `graphql-ruby`, I'm so glad we're able to use it!

**Comment by mzanini** [comment]
Same, I would love to be able to implement a hook in the schema or somewhere else to log or report the error in our bug reporter! I spent some time going through all of the documentation to try to find such hook because I think logging these errors is a pretty common need especially in an enterprise setting.
