### ISSUE TITLE
default_value prevent mutation to resolve if attached to not unauthorized field

### ISSUE THREAD

**Issue by arekk** [rmosolgo/graphql-ruby#3372]
**Describe the bug**

I have a mutation with two fields with separate authorisations (https://graphql-ruby.org/authorization/authorization.html)

- field A for user A
- field B for user B, with default value

When user A is updating only field A, default value at B is forcing B field authorisation, which is obviuosly not accesable for user A and prevent him from resolving mutation.
For user B updating field B everything is fine.

This sutuation resulting null response while `def unauthorized_field(error)` is defined to raise `GraphQL::ExecutionError` what looks like separate issue.

**Versions**

gem 'graphql', 1.12.5
gem 'rails', 5.2.4.5
other applicable versions (`graphql-batch`, etc): none

**Steps to reproduce**

Steps to reproduce the behavior

**Expected behavior**

Field B shouldn't be authorized at all, because its value was not passed to mutation.

**Actual behavior**

Authorisation fails silently and mutation isn't resolved

**Comment by rmosolgo** [comment]
Thanks for reporting this, I agree, it should work like you expect. Authorization should only be run _if_ the client explicitly provided a value for an argument; if the default value is used, it doesn't have to be authorized. 

This means we'll have to add some default-value detection to the authorization routine.
