### ISSUE TITLE
Schema directive doesn't get called?

### ISSUE THREAD

**Issue by meliborn** [rmosolgo/graphql-ruby#3377]
**Describe the bug**

I’m trying to implement @authenticated directive, but it doesn’t get called.

**Versions**

`graphql` version: 1.12.5
`rails` (or other framework): 6.1.3
other applicable versions (`graphql-batch`, etc)

**GraphQL schema**

```ruby
field :residential_complex, Types::ResidentialComplexType, null: false,
                                                               directives: { Directives::Authenticated => {} } do
      argument :slug, String, required: true
    end
```

```ruby
module Directives
  class Authenticated < GraphQL::Schema::Directive
    locations FIELD_DEFINITION, OBJECT, QUERY

    def self.resolve(_object)
      raise 'asdasd'
    end
  end
end
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
query {
  residentialComplex(slug: "zhk-akvamarin"){
    id
  }
}
```

**Expected behavior**

Exception should be thrown

**Actual behavior**

I'm getting the response with data

**Comment by rmosolgo** [comment]
Hey, sorry you ran into trouble. 

GraphQL-Ruby currently has two _distinct_ directive systems: 

1. Schema directives, which annotate types, fields, and arguments in `.graphql` dumps and populate the `.directives` Array on schema members 
2. Runtime directives, which affect execution whenever they're present in client-provided query strings 

In your example above, you've defined a _schema directive_ and attached it to a field. 

If you want to define a runtime directive, that works a little different. Here's a quick example with a directive that raises an error: 

```ruby
require "bundler/inline"

gemfile do
  gem "graphql", "1.12.5"
end

class Schema < GraphQL::Schema
  class Query < GraphQL::Schema::Object
    field :secret, String, null: false

    def secret
      "boo!"
    end
  end

  class RaiseMe < GraphQL::Schema::Directive
    locations FIELD
    def self.resolve(*)
      raise "Here's an error"
    end
  end

  query(Query)
  directive(RaiseMe)
end

pp Schema.execute("{ secret }").to_h
# {"data"=>{"secret"=>"boo!"}}

begin
  pp Schema.execute("{ secret @raiseMe }").to_h
rescue => err
  pp err.message
end
# "Here's an error"
```

Runtime directives only apply if a client puts the directive in the query string. So, if you want to apply an authorization check on a field, I recommend defining `def authorized?` instead, for example: 


```ruby
require "bundler/inline"

gemfile do
  gem "graphql", "1.12.5"
end

class Schema < GraphQL::Schema
  class RequiresAuthorization < GraphQL::Schema::Directive
    locations FIELD_DEFINITION
  end

  class BaseField < GraphQL::Schema::Field
    def authorized?(obj, args, ctx)
      if directives.any? { |d| d.is_a?(RequiresAuthorization) }
        ctx[:authorized]
      else
        true
      end
    end
  end

  class Query < GraphQL::Schema::Object
    field_class BaseField

    field :secret, String, null: true, directives: { RequiresAuthorization => {} }

    def secret
      "boo!"
    end
  end

  query(Query)
end

# Authorized:
pp Schema.execute("{ secret }", context: { authorized: true }).to_h
# {"data"=>{"secret"=>"boo!"}}

# Unauthorized:
pp Schema.execute("{ secret }").to_h
# {"data"=>{"secret"=>nil}}

# Annotated schema dump:
puts Schema.to_definition
# directive @requiresAuthorization on FIELD_DEFINITION
#
# type Query {
#   secret: String @requiresAuthorization
# }
```

I hope that helps! If you give something like that a try and run into any trouble, please let me know what code you tried and what happened when you tried it.
