### ISSUE TITLE
Field resolve not working

### ISSUE THREAD

**Issue by bduvignaud** [rmosolgo/graphql-ruby#3378]
**Describe the bug**
I'm having issues with a `resolve` method on one of my type where I was fetching the parent object using the context like this : 
```ruby   
  field :available_quantity, Integer, null: true, resolve: ->(obj, args, ctx) {
      obj.available_quantity_for(meal: ctx.parent.parent.object.object)
    }
```
(I know this looks bad, but it was, when I wrote it, the only I could make it work)

However, since the 1.12.x release, this resolve method is no longer called, and so it's no longer working as intended.

**Versions**

`graphql` version: 1.12.5 (previous version: 1.11.7
`rails` (or other framework):
other applicable versions (`graphql-batch`, etc)

**GraphQL schema**

```ruby
module Types
  class MealItemType < Types::BaseObject
    field :id, ID, null: false
    field :name, String, null: false
    field :description, String, null: true
    field :kind, KindType, null: false
    field :options_groups, [OptionsGroupType], null: true
    field :tags, [TagType], null: true
    field :allergens, [AllergenType], null: true
    field :price_cents, Integer, null: true
    field :available_quantity, Integer, null: true, resolve: ->(obj, args, ctx) {
      obj.available_quantity_for(meal: ctx.parent.parent.object.object)
    }
  end
end
```
```ruby
module Types
  class MealType < Types::BaseObject
    field :id, ID, null: false
    field :starts_at, GraphQL::Types::ISO8601DateTime, null: false
    field :ends_at, GraphQL::Types::ISO8601DateTime, null: false, deprecation_reason: "Use orderableUntil instead."
    field :orderable_until, GraphQL::Types::ISO8601DateTime, null: false
    field :meal_items, [MealItemType], null: false
    field :order, [OrderType], null: true
    field :title, String, null: false
    field :description, String, null: true
    field :absence, [AbsenceType], null: true

    def order
      context[:current_user].orders.active_for_meal(meal: object)
    end

    def absence
      context[:current_user].absences.for_meal(meal: object)
    end

    def ends_at
      object.orderable_until
    end
  end
end
```
```ruby
module Types
  class QueryType < Types::BaseObject
    field :meal, MealType, null: false do
      argument :id, ID, required: true
    end
    
    def meal(id:)
      if context[:current_organization].present? && context[:current_user].present?
        meal = context[:current_organization].meals.find(id)
        analytics.track_meal_viewed(meal: meal)
        meal
      end
    end
  end
end

```

**Expected behavior**

I'm expecting my resolve method to be reached using the `obj` and `ctx` params that I need to retrieve my `quantity` attribute

**Actual behavior**

Nothing happen, my field just return `nil`

I hope I gave enough information.

**Comment by swalkinshaw** [comment]
You are using the legacy/deprecated API with resolve procs and 1.12 defaulted to the new interpreter. See: https://github.com/rmosolgo/graphql-ruby/blob/master/CHANGELOG.md#breaking-changes-1

You'll have to set those options to revert to the deprecated functionality

**Comment by bduvignaud** [comment]
Okkk ! So that was the part I wasn't understanding well in the patch notes. Thank you !

I guess I'll might still have to get rid of this deprecated stuff.
