### ISSUE TITLE
Support nullable nodes with the `connection_type` helper

### ISSUE THREAD

**Issue by amomchilov** [rmosolgo/graphql-ruby#3383]
**Is your feature request related to a problem? Please describe.**

The default behavior of `Foo.connection_type` produces a type like so:

```graphql
type FooConnection {
  # A list of edges.
  edges: [FooEdge!]!

  # A list of nodes.
  nodes: [Foo!]!

  # Information to aid in pagination.
  pageInfo: PageInfo!
}
```

Notice that the edges and nodes are both not nullable. If you want to support null nodes, you're forced to write the boilerplate like so:

```ruby
module Types
  class fooConnectionType < BaseObject
    field :nodes, [Foo], null: false
    field :page_info, GraphQL::Types::Relay::PageInfo, null: false
  end
end
```

While not the worst, our small codebase has around 8 such connection types, and growing. 

**Describe the solution you'd like**

It would be nice to have `connection_type` be able to synthesize such types for us.

As an example, a defaulted parameter could be added:

```ruby
def connection_type(nullable_nodes: false)
```

Which could be used like `Foo.connection_type` to yield the same results as before. If you want nullable nodes, you could write `Foo.connection_type(nullable_nodes: true)`, to get this type:

```graphql
type FooConnection {
  # A list of edges.
  edges: [FooEdge!]!

  # A list of nodes.
  nodes: [Foo]!

  # Information to aid in pagination.
  pageInfo: PageInfo!
}
```

**Describe alternatives you've considered**

Do nothing. Users of the library will either need to write repeated boilerplate to hand-roll these types, or they can come up with their own abstractions to reduce the repetition.

However, I reckon this is a common enough problem that I think this is worth considering.

**Additional context**

I would be happy to implement this, if there's interest :)

**Comment by rmosolgo** [comment]
Hmmm ...

> The default behavior of `Foo.connection_type` produces a type like so:
> 
> ```graphql
> type FooConnection {
>   # A list of edges.
>   edges: [FooEdge!]!
> 
>   # A list of nodes.
>   nodes: [Foo!]!
> 
>   # Information to aid in pagination.
>   pageInfo: PageInfo!
> }
> ```


I'm not able to replicate that. What do you get for this script?

```ruby
require "bundler/inline"

gemfile do
  gem "graphql", "1.12.5"
end

class Schema < GraphQL::Schema
  class Thing < GraphQL::Schema::Object
    field :name, String, null: false
  end

  class Query < GraphQL::Schema::Object
    field :things, Thing.connection_type, null: false
  end

  query(Query)
end

puts Schema.to_definition
# ... 
# """
# The connection type for Thing.
# """
# type ThingConnection {
#   """
#   A list of edges.
#   """
#   edges: [ThingEdge]

#   """
#   A list of nodes.
#   """
#   nodes: [Thing]

#   """
#   Information to aid in pagination.
#   """
#   pageInfo: PageInfo!
# }
```

In any case, to reduce the boilerplate, write a custom Connection base type: 

```ruby 
# app/graphql/types/base_connection.rb 
  class Types::BaseConnection < Types::BaseObject 
    include GraphQL::Types::Relay::ConnectionBehaviors 
    nodes_nullable(false)
  end 

# app/graphql/types/base_object 
  class Types::BaseObject < GraphQL::Schema::Object
    connection_type_class(Types::BaseConnection)
  end 
```

After that, calls to `Foo.connection_type` will generate classes using `Types::BaseConnection`. 

On `master`, you'll also find `edges_nullable` and `edge_nullable` options, since #3376

If implementing a base connection class doesn't work for you, please follow up with the code you tried and what happened when you tried it, and I'll reopen this issue to investigate!

**Comment by amomchilov** [comment]
🤦 Nevermind, this was a result of a custom `BaseConnection` we have that I confused with `GraphQL::Types::Relay::BaseConnection`

Indeed, your snippet behaved just as you described it.

**Comment by connorshea** [comment]
FWIW the code example for BaseConnection above is wrong, is should be `node_nullable`, not `nodes_nullable`.
