### ISSUE TITLE
Tracing inconsistency

### ISSUE THREAD

**Issue by eapache** [rmosolgo/graphql-ruby#3393]
**Describe the bug**

The order of tracing events is inconsistent depending on how you execute a query.

If you instantiate a `GraphQL::Query` with a query string and schema, then call `#result` on it, then the `lex` and `parse` trace events fire outside of `execute_multiplex`.

If instead you call `Schema.execute` or `Schema.multiplex`, then the `lex` and `parse` trace events fire inside of `execute_multiplex`.

This is because `Query` calls `Multiplex.run_queries` inside of `with_prepared_ast`: https://github.com/rmosolgo/graphql-ruby/blob/5c3a8ec6f45319f40cb59f2ffb5961bb1071aa80/lib/graphql/query.rb#L198-L200

Where-as  `Schema.multiplex` calls `Multiplex.run_all` directly which fires the `execute_multiplex` tracer before it does anything that triggers lexing and parsing.

@rmosolgo maybe this isn't technically a bug but it's surprising enough it should at least be called out in the documentation.

**Versions**

1.12.5, efcedefd04d9e8d40ccdac99f867edb1cc3e667d, probably master

cc @chrisbutcher

**Comment by eapache** [comment]
It might be as simple as not calling `with_prepared_ast` in `Query.result`?

**Comment by rmosolgo** [comment]
Thanks for reporting this -- I agree it would be better if it was consistent!

> It might be as simple as not calling `with_prepared_ast` in `Query.result`?

I believe it -- since execution will eventually call some _other_ method that causes the query to prepare its AST.
