### ISSUE TITLE
Optimise GraphQL::Pagination::RelationConnection has_next_page query

### ISSUE THREAD

**Issue by dylansmithing** [rmosolgo/graphql-ruby#3401]
**Is your feature request related to a problem? Please describe.**

We recently updated the gem version from 1.11.5 to 1.12.6 and as a result of this the default type of connections for ActiveRecord::Relation was changed from the using the GrahpQL::Relay::RelationConnection to GraphQL::Pagination::Connection as defined by [v1.12.0](https://github.com/rmosolgo/graphql-ruby/blob/master/CHANGELOG.md#1120-20-january-2021)

Unfortunately we started getting timeouts on some of our complex queries that were requesting `hasNextPage` due to the different type of query being generated by `has_next_page` in the connection class. [GraphQL::Pagination::Connection](https://github.com/rmosolgo/graphql-ruby/blob/e1516208593ce15c059c4066a8b045e5e5cf9f1b/lib/graphql/pagination/relation_connection.rb#L38) is generating a count query as opposed to [GrahpQL::Relay::RelationConnection](https://github.com/rmosolgo/graphql-ruby/blob/9069ba310846dea7636dd24ca0c743eccf4beb3d/lib/graphql/relay/relation_connection.rb#L30) which uses `.exists?`

**Describe the solution you'd like**

The same problem was actually addressed previously for GrahpQL::Relay::RelationConnection with [this](https://github.com/rmosolgo/graphql-ruby/issues/2332) issue and [this](https://github.com/rmosolgo/graphql-ruby/pull/2547/files) PR, handling ActiveRecord::Relations differently. If GraphQL::Pagination::Connection is going to be the new default connection, including for ActiveRecord::Relations, can we copy across that optimisation in to `has_next_page` on that class as well?

**Describe alternatives you've considered**

We've reverted to using the Relay connections in the meantime with `self.connections = nil` in the schema but with the new connection type written this way it's not going to work for some of the queries we're doing. So if it wasn't optimised we would probably have to roll our own connection with a different type of query in `has_next_page` but I doubt we would be the only people having this issue with complex queries and counts so I think it should be addressed by the gem.

**Comment by rmosolgo** [comment]
Hi! Thanks for the detailed report. I definitely want to address the regression here, thanks for sharing those details!
