### ISSUE TITLE
createRelaySubscriptionHandler not compatible with Relay 11 (TypeScript)

### ISSUE THREAD

**Issue by nirvdrum** [rmosolgo/graphql-ruby#3413]
**Describe the bug**

I'm following the documentation on using _graphql-ruby_'s subscription mechanism with ActionCable to start. I've pulled in the _graphql-ruby-client_ project into my TypeScript project using React 17 and Relay 11. Following [the docs](https://graphql-ruby.org/javascript_client/relay_subscriptions#actioncable), I've attempted to create my Relay network object with `createRelaySubscriptionHandler`, but its type definition just doesn't match what Relay is expecting.

**Versions**

`graphql` version: 1.12.6
`rails` (or other framework): 6.1.3
other applicable versions (`graphql-batch`, etc): Relay 11.0.0

**Steps to reproduce**

Pull in Relay type definitions from _@types/relay-runtime_ and attempt to create a subscription function for the Relay network with `createRelaySubscriptionHandler`.

**Expected behavior**

I'd expect the return type of `createRelaySubscriptionHandler` to satisfy the type definition of the Relay network.

**Actual behavior**

I encounter an issue with in compatible type definitions:

```
Error:(69, 7) TS2322: Type '((operation: { text: string; name: string; }, variables: object, _cacheConfig: object, observer: { onError: Function; onNext: Function; onCompleted: Function; }) => { ...; }) | null | undefined' is not assignable to type 'SubscribeFunction | undefined'.
  Type 'null' is not assignable to type 'SubscribeFunction | undefined'.
```

If I use the `!` operator to indicate that the return of `createRelaySubscriptionHandler` will not be `null`, I see:

```
Error:(69, 7) TS2322: Type '(operation: { text: string; name: string; }, variables: object, _cacheConfig: object, observer: { onError: Function; onNext: Function; onCompleted: Function; }) => { ...; }' is not assignable to type 'SubscribeFunction'.
  Types of parameters 'operation' and 'operation' are incompatible.
    Type 'ConcreteBatch' is not assignable to type '{ text: string; name: string; }'.
      Types of property 'text' are incompatible.
        Type 'string | null' is not assignable to type 'string'.
          Type 'null' is not assignable to type 'string'.
```

**Additional context**

With these details, we can efficiently hunt down the bug!

**Comment by rmosolgo** [comment]
Wow, I wonder when that changed ... the corresponding relay docs look pretty different: 

https://relay.dev/docs/guided-tour/updating-data/graphql-subscriptions/#configuring-the-network-layer

It looks like, somewhere along the line, the switched from expecting a `.dispose()`able to wanting an `Observable.from(...)`, but this is the first time it's come up here!

**Comment by fazo96** [comment]
I am getting a similar typescript error

![immagine](https://user-images.githubusercontent.com/2546805/119855162-fa529f00-bf11-11eb-9892-256001189ed7.png)

It's minor, but I thought reporting it might be useful

**Comment by butsjoh** [comment]
Any update on this? It seems relay 11 support is going to be needed.

**Comment by butsjoh** [comment]
This might be a workaround for now when using relay 11: https://github.com/anycable/graphql-anycable/issues/17#issuecomment-902740285

**Comment by rmosolgo** [comment]
Thanks for sharing that work-around, @butsjoh. I adapted it to work in the library in #3594, which I'll release in 1.10 soon!
