### ISSUE TITLE
JS Client: Remove dependency on Node built-ins

### ISSUE THREAD

**Issue by KieranP** [rmosolgo/graphql-ruby#3415]
I am using the JS client on a web application but getting errors because browsers do not support node built-ins (specifically `process.platform` and `process.version`), which the GraphQL JS clients dependency `glob` uses.

Webpack 4 uses to polyfill node built-ins, but webpack 5 doesn't any longer so will cause issues for anyone upgrading to webpack 5. Additionally, tools like Snowpack or Vite do not support node built-ins either.

So the JS client should move away from using dependencies that use node built-ins (like `glob`) to avoid these issues.

**Comment by rmosolgo** [comment]
Hey, thanks for highlighting this issue. It's what happens when you have a Ruby developer writing JavaScript 😆 . I'd welcome an improvement like this, as well as an improvement to the test suite or build chain to avoid I don't accidentally reintroduce dependencies on those built-ins. Are you interested in taking a crack at it?

**Comment by KieranP** [comment]
@rmosolgo Unfortunately I'm in the same boat, a Ruby developer writing Javascript. So I might not be of much help in this regard sorry.

**Comment by rmosolgo** [comment]
I think the best approach here is to only require the files you need. 1.9.0 _should_ allow you to do that (https://github.com/rmosolgo/graphql-ruby/issues/2815#issuecomment-778650536),  for example, if you just need a subscriptions client, then you can require that file directly. The docs should give examples for that, too. 

`glob` and `process.` are use by the CLI, and I don't know of any great alternative to using them there 🙈 If the approach described above doesn't work for you, please open a new bug report!

**Comment by KieranP** [comment]
@rmosolgo Yes, that worked well. I can include just the ActionCable JS file without the CLI stuff now. Thank you.
