### ISSUE TITLE
Breaking change in 1.12.6: Int variable no longer accepted for ID argument

### ISSUE THREAD

**Issue by RobinDaugherty** [rmosolgo/graphql-ruby#3418]
**Describe the bug**

#3370 fixed a bug with input object argument validation.

Prior to this fix, an `Int` variable could be passed for an `ID`-type argument, and it would succeed. As of the change in #3370, which was released in 1.12.6, this will now result in an error:

```
{"message"=>"Type mismatch on variable $id and argument id (Int! / ID!)", "locations"=>[{"line"=>2, "column"=>31}], "path"=>["mutation Xxx", "xxx", "input", "id"], "extensions"=>{"code"=>"variableMismatch", "variableName"=>"id", "typeName"=>"Int!", "argumentName"=>"id", "errorMessage"=>"Type mismatch"}}
```

**Versions**

`graphql` version: 1.12.6
`rails` (or other framework): 6.1.2.1
`newrelic_rpm` 6.15.0 included via `use(GraphQL::Tracing::NewRelicTracing, set_transaction_name: true)`

**GraphQL schema**

> Are you using [interpreter](https://graphql-ruby.org/queries/interpreter.html)?

Yes.

> Any custom instrumentation, etc?

New Relic (listed above)

Here's a stripped-down example of the mutation clas:

```ruby
class TestMutation < BaseMutation
  field :success, Boolean, null: true
  argument :id, ID, required: true
  def resolve(id:)
    { success: true }
  end
end

class MutationType < Types::BaseObject
  field :test, mutation: TestMutation
end
```

**GraphQL query**

Example GraphQL query and response

```graphql
mutation Test($id: Int!) {
  test(input: {id: $id) {
    success
  }
}
```

With 1.12.5
```json
{
  "data": {
    "test": { "success" : true }
  }
}
```

With 1.12.6
```json
{
  "errors" : [
    {
      "path" : [
        "mutation Test",
        "test",
        "input",
        "id"
      ],
      "message" : "Type mismatch on variable $id and argument id (Int! / ID!)",
      "extensions" : {
        "code" : "variableMismatch",
        "typeName" : "Int!",
        "argumentName" : "id",
        "variableName" : "id",
        "errorMessage" : "Type mismatch"
      },
      "locations" : [
        {
          "line" : 2,
          "column" : 31
        }
      ]
    }
  ]
}
```

**Steps to reproduce**

1. Use graphql gem version 1.12.6
1. Create a mutation that accepts an `ID!` argument
1. Execute the mutation with an argument of type `Int!`

**Expected behavior**

Behavior before 1.12.6 was to accept the `Int` variable as an ID type.

**Actual behavior**

As of 1.12.6, this results in an error.

This might conform better to the GraphQL spec, but it's unexpected in a patch version, since it breaks backward compatibility.

**Additional context**

This only affects variables passed to `ID!` arguments. You can still pass an integer value for an `ID!` argument, and this succeeds in 1.12.6.

```graphql
mutation {
  test(input: {id: 5) {
    success
  }
}
```

**Comment by rmosolgo** [comment]
Sorry for the unpleasant surprise 😖 I don't plan to revert the change, since, as you noted, it's a fix to properly implement the specification. However, I updated the changelog in dcd0e11d1 to alert any future readers.
