### ISSUE TITLE
How to properly update model?

### ISSUE THREAD

**Issue by jimmiejackson414** [rmosolgo/graphql-ruby#3419]
First off, I want to apologize for asking a question here. I know Issues are generally reserved for Bugs or Feature Requests. I've asked this question in both [StackOverflow](https://stackoverflow.com/questions/66896441/how-to-properly-update-model-using-graphql-ruby) and [Reddit](https://www.reddit.com/r/rubyonrails/comments/mh9c3l/how_to_properly_update_model_using_graphqlruby/), and still can't _quite_ get it to work right.

I've got a simple mutation to update a model that looks like this:

```
module Mutations
  module Media
    class UpdateMedia < GraphQL::Schema::Mutation
      include ::GraphqlAuthenticationConcerns
      include ::GraphqlActiveModelConcerns

      description 'Update Media'
      argument :id, Integer, required: true
      argument :title, String, required: false
      argument :preview_url, String, required: false
      argument :preview_image, String, required: false
      argument :watched, Boolean, required: false
      field :success, Boolean, null: false
      field :errors, [Types::ActiveModelError], null: false
      field :media, Types::MediumType, null: false

      def resolve(id:, title:, release_date:, preview_url:, preview_image:, watched:)
        authenticate_user!

        media = Medium.find(id)

        media_params = {
          title: title,
          preview_url: preview_url,
          preview_image: preview_image,
          watched: watched,
        }

        if media.update(media_params)
          success_response(media)
        else
          failed_response(media)
        end
      end

      private

      def success_response(media)
        {
          success: true,
          errors: [],
          media: media
        }
      end

      def failed_response(media)
        {
          success: false,
          errors: errors(media)
        }
      end
    end
  end
end
```
Passing through a playground test with a payload that might look something like `{id: 1, watched: true}` gives me the warning `missing keywords: :title, :release_date, :preview_url, :preview_image`.

I saw that in #3060 it was recommended to set default values to `nil`. I tried this, passed through the same playground test to only update the `watched` field, and it ended up setting all of the fields in my model to `nil` and only actually updating the `watched` field.

I've also tried defining the function as:

```
def resolve(id:, **args)
  ...
  if media.update(args)
 ...
end
```

however this allows me to pass through _any_ arguments, and I essentially lose my argument validation.

So with all of this said, what's the best way to only update the model attributes that are being passed through as arguments, while maintaining the argument validation defined above the method?

Thank you!

**Comment by rmosolgo** [comment]
>  the best way to only update the model attributes that are being passed through as arguments?

I think it's the approach you shared with `**args`: 

```ruby
def resolve(id:, **args)
  ...
  if media.update(args)
 ...
end
```

> while maintaining the argument validation defined above the method

I _expect_ GraphQL-Ruby to still validate all inputs when it executes queries, even if they aren't explicitly named in `def resolve`. (This would be part of the "static validation" process before execution.) 

If you observe this isn't the case, could you please share: 

- The full error and backtrace, or other log output that proves that the unexpected outcome occurred (eg, Rails logs)
- The Ruby code and/or GraphQL query you execute to demonstrate the problem 

? 

If those validations aren't happening, it's a bug!
