### ISSUE TITLE
Implementing multiple interface with relay node loading support not working?

### ISSUE THREAD

**Issue by butsjoh** [rmosolgo/graphql-ruby#3420]
I would like to know the current status on this and if it is expected to work like this.

I also have an interface with some orphan types

```
module Graph
  module Types
    module FileInterface
      include ::GraphQL::Schema::Interface
      include ::GraphQL::Types::Relay::Node
      
      graphql_name 'File'

      connection_type_class Graph::BaseConnection
      edge_type_class Types::FileEdgeType

      orphan_types Types::ImageType, Types::AudioType, Types::VideoType, Types::DocumentType
     ...
     end
   end
end
```

Example orphan type:

```
module Graph
  module Types
    class DocumentType < GraphQL::Schema::Object
      implements Types::FileInterface

      graphql_name 'Document'
    end
  end
end

```

But when i then do the node query:

```
query file($id: ID!) {
  node(id: $id) {
    __typename
    ... on File {
      id
    }
  }
}
```

i always get:

```
#<GraphQL::Query::Result @query=... @to_h={"errors"=>[{"message"=>"Fragment on File can't be spread inside Node", "locations"=>[{"line"=>5, "column"=>11}], "path"=>["query file", "node", "... on File"], "extensions"=>{"code"=>"cannotSpreadFragment", "typeName"=>"File", "fragmentName"=>"unknown", "parentName"=>"Node"}}]}>
```

and indeed in the generated schema it is as follows:

```
interface File {
  """
  The id of the file
  """
  id: ID!

 ...
```

I also tried moving ```implements GraphQL::Types::Relay::Node``` to each of the orphan types but same errors pop up even if i would do ... on Document. Would like to know what i am doing wrong.

_Originally posted by @butsjoh in https://github.com/rmosolgo/graphql-ruby/issues/2804#issuecomment-812010828_

**Comment by butsjoh** [comment]
For clarity i am using version 1.12.4.

**Comment by butsjoh** [comment]
Ok i can get it to work if i do the following:

```
module Graph
  module Types
    class DocumentType < GraphQL::Schema::Object
      implements Types::FileInterface
      implements GraphQL::Types::Relay::Node

      graphql_name 'Document'
    end
  end
end
```

```
module Graph
  module Types
    module FileInterface
      include ::GraphQL::Schema::Interface
      
      graphql_name 'File'

      connection_type_class Graph::BaseConnection
      edge_type_class Types::FileEdgeType

      orphan_types Types::ImageType, Types::AudioType, Types::VideoType, Types::DocumentType
     ...
     end
   end
end
```

```
query file($id: ID!) {
  node(id: $id) {
    __typename
    ... on Document {
      id
    }
  }
}
```

```
type Document implements File & Node {
  """
  ID of the object.
  """
  id: ID!
...
```

So i am wondering if there would be a way to pass ::GraphQL::Types::Relay::Node in the file interface so i don't need to put that in each of the orphan types?

**Comment by rmosolgo** [comment]
> a way to pass ::GraphQL::Types::Relay::Node in the file interface so i don't need to put that in each of the orphan types?

Not out-of-the-box. Using `include ...` inside an interface caries the parent interface's _properties_ (like fields and methods), but it doesn't copy the parent interface's _identity_ (it doesn't apply the parent interface to the child interface by _name_). 

One thing you could do is leverage Ruby's built-in `def self.included` hook, for example: 

```ruby 
module FileInterface
  # All `File`s are also `Node`s, so declare that whenever this module is included: 
  def self.included(child_class)
    child_class.implements(GraphQL::Types::Relay::Node)
  end 
end 
```

This works, because, under the hood, `implements ...` does a Ruby `include`:

https://github.com/rmosolgo/graphql-ruby/blob/a7591a913cd001fa28a3e9ac3613c858ae667b3c/lib/graphql/schema/object.rb#L102-L105

I hope that helps! Please let me know if you give it a try and run into any trouble.

**Comment by butsjoh** [comment]
Yes that helps :) At least less boilerplate.

I did not test afterwards but following works as well :)

```
query file($id: ID!) {
  node(id: $id) {
    __typename
    ... on File {
      id
    }
  }
}
```
