### ISSUE TITLE
[PRO] Cursor Pagination does not handle custom complex SQL SELECT with alias

### ISSUE THREAD

**Issue by jpalumickas** [rmosolgo/graphql-ruby#3421]
## Describe the bug

Currently, when we have complex SQL select and using alias, then trying to order by that alias, GraphQL Pro stable cursor connection tries to make that alias as another alias. For example
```rb
User
  .select('"users".*', "date(created_at) AS created_date")
  .order('created_date' => :desc)
  .order('name' => :asc)
```
**Note: we cannot add this column directly to order column, because we use much more complex SQL select there. date(created_at) AS created_date is used for example only.**

GraphQL Ruby Pro generates this SQL

```sql
SELECT "users".*, date(created_at) AS created_date, "created_date" AS cursor_0, users.name AS cursor_1, users.id AS cursor_2 FROM "users" ORDER BY "created_d
ate" DESC, "users"."name" ASC, users.id asc LIMIT 3
```
In PostgreSQL, we cannot alias already aliased column, so we get an error:
```
PG::UndefinedColumn: ERROR:  column "created_date" does not exist
```

## Possible quick solution

I can alias this column to `cursor_0` manually 

```rb
User
  .select('"users".*', "date(created_at) AS cursor_0")
  .order('created_date' => :desc)
  .order('name' => :asc)
```

GraphQL Ruby Pro generates this SQL

```sql
SELECT "users".*, date(created_at) AS cursor_0, "cursor_0" AS cursor_0, users.name AS cursor_1, users.id AS cursor_2 FROM "users" ORDER BY "created_d
ate" DESC, "users"."name" ASC, users.id asc LIMIT 3
```

As we see, now we get this alias : `"cursor_0" AS cursor_0`

So maybe in `graphql/pro/relation_connection/selects.rb` `apply` method,
insetead of this
```rb
relation = relation.select("#{selection} AS cursor_#{idx}")
```

 we can do 

```rb
if selection != "cursor_#{idx}" && selection != "\"cursor_#{idx}\""
  relation = relation.select("#{selection} AS cursor_#{idx}")
end
```

This will not add alias if name of the alias is the same.

## Versions

`graphql` version: 1.12.6
`graphql-pro` version: 1.17.11
`rails` version: 6.1.3.1

**Comment by rmosolgo** [comment]
Thanks for the bug report! This one hasn't come up before. I'll take a look and work out some kind of fix, then follow up here.

**Comment by rmosolgo** [comment]
Thanks again for the detailed report. I've release graphql-pro 1.17.12 with a fix. 

I took a slightly different approach, because I want to keep the `cursor_{idx}` alias as an _internal_ concern of the library. (That implementation has changed some over the years, and I don't think it makes a very user-friendly public API.) So instead, I made it _detect_ whether each `ORDER BY` field refers to an aliased field in `SELECT`, and if it does, then re-add that field with a _new_ alias. For example: 

```sql
SELECT "users".*, date(created_at) AS created_date FROM "users" ORDER BY "created_date" DESC
-- Will become: 
SELECT "users".*, date(created_at) AS created_date, date(created_at) AS cursor_0, users.id AS cursor_1 FROM "users" ORDER BY "created_date" DESC, users.id ASC LIMIT 3
```


Please give it a try, and let me know if you run into any more trouble with it!

**Comment by jpalumickas** [comment]
Hey @rmosolgo,

It's working as expected. 🎉 

I had only 1 issue, when using casting, for example `some_function(column) / other_function(column)::float AS  my_column` (`::float` before `AS`) but then I solved in other way, so it's not an issue for now 🙂 

Thank you!

**Comment by rmosolgo** [comment]
Glad to hear it! Let me know if the casting problem comes up again -- I'm sure the regexps for parsing those bits of the queries could be improved to accommodate them.
