### ISSUE TITLE
graphql-ruby-client TS error "Could not find a declaration file for module 'actioncable'"

### ISSUE THREAD

**Issue by escapedcat** [rmosolgo/graphql-ruby#3422]
**Describe the bug**
This started to happen with `1.9.3`.   

```bash
$ tsc --noEmit
node_modules/graphql-ruby-client/subscriptions/ActionCableLink.d.ts:3:23 - error TS7016: Could not find a declaration file for module 'actioncable'. '/[PROJECT]/node_modules/actioncable/lib/assets/compiled/action_cable.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/actioncable` if it exists or add a new declaration (.d.ts) file containing `declare module 'actioncable';`

3 import { Cable } from "actioncable";
                        ~~~~~~~~~~~~~
```

[Checking the changlog](https://github.com/rmosolgo/graphql-ruby/blob/master/javascript_client/CHANGELOG.md#193-31-mar-2021) only two deps were moved to peerDeps. Installing these doesn't seem to help.  

Maybe I'm missing something.   
Let me know what else you need to know or what I can try to solve this. Thanks!

**Versions**
```
    "graphql": "^15.5.0",
    "graphql-ruby-client": "^1.9.3",
    "graphql-tag": "^2.11.0",
```

**Steps to reproduce**
- `yarn`
- `tsc --noEmit`

**Expected behavior**

TS compiler does not complain

**Actual behavior**

See compiler error above

**Comment by maximeg** [comment]
Same here, I had to add 

```ts
declare module "actioncable" {
  import { Consumer } from "@rails/actioncable";

  type Cable = Consumer;
}
```

to a `.d.ts` file to make it quiet, and preserve the typing on my code.

Could we bump the dependency and make the change as new version are released as `@rails/actioncable` ?
I could do the PR.

**Comment by rmosolgo** [comment]
What happens when you try the fix suggested by `tsc`?


```
Try `npm i --save-dev @types/actioncable` 
```

`@types/actioncable` isn't a dependency of this project because it's published in plain javascript. I don't _think_ javascript projects should include `@types/...` in their dependencies, but I could be wrong :sweat_smile: 

But, I'm not sure why that would have just started on 1.9.3 🤔

**Comment by escapedcat** [comment]
On these now and everything is fine:
```
"@types/actioncable": "^5.2.7",
"actioncable": "^5.2.6",
"graphql-ruby-client": "^1.9.4",
```

No idea what changed. Sorry for bothering @rmosolgo

**Comment by EvHaus** [comment]
I'm having issues as well. Using:

```
"@types/actioncable": "^5.2.7",
"actioncable": "^5.2.6",
"graphql-ruby-client": "^1.10.5"
```

I get:

```
../node_modules/graphql-ruby-client/subscriptions/ActionCableLink.d.ts:3:31 - error TS2307: Cannot find module '@rails/actioncable' or its corresponding type declarations.

3 import type { Consumer } from "@rails/actioncable";
```

If I install the `@rails/actioncable@7.0.0` dependency, then I get this instead:

```
../node_modules/graphql-ruby-client/subscriptions/ActionCableLink.d.ts:9:12 - error TS2709: Cannot use namespace 'Consumer' as a type.

9     cable: Consumer;
             ~~~~~~~~

../node_modules/graphql-ruby-client/subscriptions/ActionCableLink.d.ts:14:16 - error TS2709: Cannot use namespace 'Consumer' as a type.

14         cable: Consumer;
                  ~~~~~~~~
```

If I try again after installing `@types/rails__actioncable@6.1.6`, I finally get all the errors to go away.

So it seems like there are still some issues here because `@types/rails__actioncable` is marked as a deprecated package.

**Comment by escapedcat** [comment]
@EvHaus also getting this, but I think this is a new issue. Will open a new one.
