### ISSUE TITLE
GraphQL::Subscriptions::Serialize fails for Single Key Hashes

### ISSUE THREAD

**Issue by hschne** [rmosolgo/graphql-ruby#3425]
**Describe the bug**

When loading subscriptions using `GraphQL::Subscriptions::Serialize`, single-size hashes are erroneously serialized to `nil`. This causes significant problems when using GraphQL subscriptions.

**Versions**

`graphql` version: 1.12.6
`rails` (or other framework):  6.1

**Steps to reproduce**

The behaviour can be reproduced by the following test: 

```ruby
test 'serialize' do
  subscription = JSON.dump(subscription: '12345', variables: { id: 1})

  result = GraphQL::Subscriptions::Serialize.load(subscription)

  assert_not_nil(result['variables'])
end
```

The above test will fail, as `{ id: 1 }` is loaded is `nil`. 

**Expected behavior**

The expected behavior would be, of course, to receive `{ id: 1 }`

**Additional context**

For context, we use a variant of the `ActionCableSubscription` where we implement `read_subscription` similar to this (we load subscriptions from a shared Redis instance):

```ruby
def read_subscription(subscription_id)
    query = @serializer.load(@subscriptions.get(subscription_id)).with_indifferent_access
    ...
end
```

I believe I have found the root cause of this issue in [this commit](https://github.com/rmosolgo/graphql-ruby/commit/8160028564ab167ad37bfb958536567fa2317f09). Previously, a condition like this was present: 

```ruby 
if value.size == 1 && value.key?(GLOBALID_KEY)
  GlobalID::Locator.locate(value[GLOBALID_KEY])
elsif value.size == 1 && value.key?(SYMBOL_KEY)
  value[SYMBOL_KEY].to_sym
else 
  # handle 'normal' hashes
end
```

However, the commit referenced above changed it to: 

```ruby 
 if value.size == 1
    case value.keys.first # there's only 1 key
    when GLOBALID_KEY
      ...
    when TIMESTAMP_KEY
     ...
    end # There is no else block here
else 
  # handle 'normal' hashes
end
```

Because of the way the conditions are structured here, the case where the value (aka. `{ id: 1}`) has size 1, but *hasn't* some sort of special key is missing - which then results in `nil` being returned. 

The issue can be fixed by adding an else statement: 

```ruby
else 
   key = value[value.keys.first]
  value = load_value(value[key]) 
  { key: value } # something like that
end
```

**Comment by hschne** [comment]
I'm prepared to do a PR, if you agree with my assessment :)

**Comment by rmosolgo** [comment]
Thanks for the detailed report! I agree with your diagnosis and proposed solution, I'd appreciate a PR for it. Let me know if I can help along the way!
