### ISSUE TITLE
GraphQL::Subscriptions stream_from makes extra DB queries when using __gid__  serialization

### ISSUE THREAD

**Issue by EugeneGrigorenko** [rmosolgo/graphql-ruby#3426]
**Describe the bug**

I'm trying to do some triggers to broadcast a list of AR records to subscribers. I have a standalone AC app. The code the main app code that does triggering looks like this:
```ruby
MySchema.subscriptions.trigger('postUpdates', { post_id: 'Z2lkOi8vcFwdG9yLlzc3VlLzY3' }, {updates: {comments: [Comment.last, Comment.first],  action: 'comments_added' }} )
```
My `PostSubscription` is broadcastable with 
`use GraphQL::Subscriptions::ActionCableSubscriptions, broadcast: true, default_broadcastable: true`

And I have 2 active subscribers.

When I execute the trigger I can see 4 DB queries performed on the action cable side
```
  Comment Load (1.9ms)  SELECT "comments".* FROM "comments" WHERE "comments"."id" = 71 LIMIT 1
  Comment Load (2.3ms)  SELECT "comments".* FROM "comments" WHERE "comments"."id" = 14 LIMIT 1
  ...
  Comment Load (1.7ms)  SELECT "comments".* FROM "comments" WHERE "comments"."id" = 71 LIMIT 1
  Comment Load (2.0ms)  SELECT "comments".* FROM "comments" WHERE "comments"."id" = 14 LIMIT 1
```
After doing some investigation I found that deserialization [here](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/subscriptions/action_cable_subscriptions.rb#L149) is calculated for every subscriber even though the value it returns is only used to calculate the message once for the first subscriber and then skip it for anybody else with [this](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/subscriptions/action_cable_subscriptions.rb#L152) condition.

I'm wondering if that was done intentionally or there is a case I don't know about. If not I can probably make a PR to fix this 

**Versions**
    graphql (1.12.6)
    graphql-batch (0.4.3)
    graphql-pro (1.17.11)
    rails (6.0.3.6)

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok).
Are you using [interpreter](https://graphql-ruby.org/queries/interpreter.html)? Any custom instrumentation, etc?

```ruby
module Subscriptions
  class Post < BaseSubscription
    argument :post_id, ID, required: true # , loads: Types::PostType

    field :updates, Types::Subscriptions::PostBroadcastType, null: false
  end
end
```

**Expected behavior**

Only call deserialization once 

**Actual behavior**

DeSerialization is called for each subscriber

**Comment by rmosolgo** [comment]
Hmm, I think it would be OK to only load those objects once, but I'm not sure how it could be done safely and effectively. 

I don't think there are authorization concerns at this point in schema updates (authorization would be performed later, during query execution). But if we somehow cache the loaded objects, we have to be sure not to serve stale data if the same message is broadcasted later. 

In any case, if you can find a way to cache the lookup while avoiding stale caches for later broadcasts, I'd love to see it!

**Comment by EugeneGrigorenko** [comment]
@rmosolgo can't we just move `object = @serializer.load(message)` into the `events_by_fingerprint`  loop where it's actually used. i.e. [on the line 156](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/subscriptions/action_cable_subscriptions.rb#L157)? 

In this case, it'd rely on the channel in a "primary position" and a fingerprint to decide if the calculation for each subscriber is required or not.

**Comment by rmosolgo** [comment]
Oh, yeah, I think that'd be good! That way, you'd skip the lookup on any Ruby processes that didn't have that _first_ subscription for a fingerprint. Nice find.
