### ISSUE TITLE
GraphQL::Subscriptions::Serialize load array of gid-s

### ISSUE THREAD

**Issue by EugeneGrigorenko** [rmosolgo/graphql-ruby#3427]
**Describe the bug**

While working on [this](https://github.com/rmosolgo/graphql-ruby/issues/3426#?repos=30337170) issue I've also noticed that `GraphQL::Subscriptions::Serialize#load_value` doesn't properly handle an array of gids. See [here](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/subscriptions/serialize.rb#L58).
I.e. when doing a trigger with an array of records the value parameter for `load_value` might be something similar to 
```
[{"__gid__"=>"Z2lkOi8vcmwdGyL0VzdGltYXRpb25WRlLzcz"}, {"__gid__"=>"Z2lkOi8mFwdG9yL0VzdGtYXpb25b3RlLzE0"}]
```
The current implementation would just call `load_value` recursively for each element which will end up calling 
`GlobalID::Locator.locate(value[GLOBALID_KEY])` for every record. 

In my understanding, the solution might be to make use of `GlobalID::Locator.locate_many`[[ref](https://github.com/rails/globalid#locating-many-global-ids)] to load all of the records with a single call. I.e.

```
          if value.is_a?(Array) && value.first.is_a?(Hash) && value.first[GLOBALID_KEY]
            GlobalID::Locator.locate_many(value.map { _1[GLOBALID_KEY] })
          else
             value.map{|item| load_value(item)}
          end
```
Please confirm that it looks like a good course of actions and I'll try to make a pr for this change. 

**Versions**

graphql (1.12.6)
graphql-batch (0.4.3)
graphql-pro (1.17.11)
rails (6.0.3.6)

**Comment by rmosolgo** [comment]
:+1: That sounds like a nice improvement, thanks for the suggestion! (I don't think `_1` will work because we support older versions of Ruby, but besides that, looks good to me.)
