### ISSUE TITLE
Allow disabling authorization checks if they are not used

### ISSUE THREAD

**Issue by bbugh** [rmosolgo/graphql-ruby#3429]
**Is your feature request related to a problem? Please describe.**

We have a few large queries and the authorization checks take up a very large part of the response time, sometimes up to twice as long as the actual response. We do not use the built-in authorization at all.

**Describe the solution you'd like**

Some way to disable authorization checks, or change authorization to an opt-in setting rather than always happening?

**Describe alternatives you've considered**

Uncertain 

**Additional context**

From this [Slack thread](https://app.slack.com/client/T044QJ50C/threads/thread/C07MVL1AB-1615923548.001800)

**Comment by rmosolgo** [comment]
Hey, thanks for raising this for discussion. I'd love to investigate options for reducing the overhead of built-in authorization, including possibly adding a way to opt out entirely. 

You mention that, sometimes, authorization takes as long as the rest of execution, is that right? Do you have any profiling info you can share about that (screenshots, profiler output, whatever)? I'd to learn more which _parts_ (fields, objects) of authorization take up so much time in these cases.

**Comment by srgoldman** [comment]
Here are a couple of screenshots from Datadog. Perhaps not the most egregious example but it does reflect that most of the processing time is in the graphql layer and the .authorized calls contribute to that in a meaningful way. I can generate more traces as necessary.

![Screen Shot 2021-04-07 at 2 08 11 PM](https://user-images.githubusercontent.com/251189/113934666-e2c92680-97aa-11eb-970f-efe2bafb91b1.png)
![Screen Shot 2021-04-07 at 2 06 43 PM](https://user-images.githubusercontent.com/251189/113934671-e52b8080-97aa-11eb-9527-c8e818a36cc3.png)

**Comment by bbugh** [comment]
It seems to be `GraphQL/Authorize/DynamicFields`. I mentioned that at the start of the Slack thread but failed to copy it over to this issue, sorry about that. 

Here's some info from our New Relic from a couple of different requests:

![image](https://user-images.githubusercontent.com/438465/113944299-ec15bb80-97c9-11eb-8c0e-267c971ec9e2.png)


<img width="557" alt="Pasted_Image_4_7_21__5_47_PM" src="https://user-images.githubusercontent.com/438465/113943995-68f46580-97c9-11eb-8577-ca26149c7a05.png">

**Comment by rmosolgo** [comment]
Thanks for sharing these, that's really helpful. I'm really surprised to see it -- I haven't noticed it myself before. I think the next thing is to try to replicate it in a stand-alone benchmark, then iterate on improvements to improve that benchmark.

**Comment by rmosolgo** [comment]
I spent some time with this issue and I propose adding a path to opt-out as described in #3446, please let me know what you think on that PR if you have time to take a look!

**Comment by srgoldman** [comment]
Thanks @rmosolgo. I looked over the code and it seems pretty clean. I'd like to run some tests in the next few days with this branch and see what the impact is.

**Comment by rmosolgo** [comment]
@srgoldman, are you still investigating? I'm happy to wait a bit more if you'd like to confirm the patch before I merge it. Otherwise, I'll 🚢 !

**Comment by srgoldman** [comment]
@rmosolgo sorry to keep you hanging - had a couple of high priority things dumped on my plate. if you don't see any downsides (and I don't), then I'd say :shipit:. I'll run some experiments when I get a chance and report back what I find. Thanks again for being so responsive! Your support is highly leveraged :-).
