### ISSUE TITLE
[PRO] Cursor Pagination does not handle custom complex SQL SELECT with alias [2]

### ISSUE THREAD

**Issue by jpalumickas** [rmosolgo/graphql-ruby#3433]
## Describe the bug

Hey @rmosolgo,

Related to https://github.com/rmosolgo/graphql-ruby/issues/3421, I found 1 more issue. 

Using pagination with `first` and `after` and `endCursor`, stable connection uses `HAVING` but HAVING cannot handle aliases and I have `column "my_alias_column" does not exist`. Maybe GraphQL Ruby stable connection cursors should clone SELECT in HAVING too, like we have now in ORDER?

## Versions

`graphql` version: 1.12.7
`graphql-pro` version: 1.17.12
`rails` version: 6.1.3.1

**Comment by rmosolgo** [comment]
Yes, thanks for reporting this. I've just shipped graphql-pro `1.17.13` with a fix like you suggested. When it detects a filter condition based on an aliased field, it replaces it with the original selection expression. 

Let me know if you have any more trouble with it!

**Comment by jpalumickas** [comment]
@rmosolgo thanks, I think it's working now 🙂
