### ISSUE TITLE
Make clientMutationId optional for RelayClassicMutation

### ISSUE THREAD

**Issue by rylanc** [rmosolgo/graphql-ruby#3437]
**Is your feature request related to a problem? Please describe.**

I find the automatic generation of an input type a useful feature of the `RelayClassicMutation`, but the addition of the `clientMutationId` doesn't apply to my client (I use Apollo). Leaving it in the schema can be confusing for consumers who aren't familiar with Relay (it doesn't even look like Relay uses these IDs anymore). 

**Describe the solution you'd like**

It would be handy if the client mutation ID field/argument were optional. I think it would probably be the easiest to configure (while maintaining backward compatibility) to create a separate `InputArgumentMutation` (name TBD) class that `RelayClassicMutation` inherits from. The base class would include the logic for creating and handling the input argument, and `RelayClassicMutation` would just add and handle the client mutation ID field/argument.

Another option might be to have a class method on `RelayClassicMutation` called `add_client_mutation_id` that would accept a boolean and would be enabled by default. That approach seems to me to be a little more confusing than using composability/inheritance.

**Additional context**

I'm happy to do the work to add this feature, but I wanted to get some feedback before I started.

**Comment by rmosolgo** [comment]
Hey, thanks for the suggestion. I've definitely heard folks confused by the presence of that argument, just like you described. 

Either approach that you proposed sounds good to me, and I'd welcome a PR for either one. Please let me know if I can help out along the way!

**Comment by rmosolgo** [comment]
I don't have plans to work on this, but in case it's still an issue for anyone, here's an approach to make `clientMutationId` go away in your schema. Basically, you intercept the calls that would add that field and mutation, and make them no-ops instead. It's a bit brittle, since the gem's internal flow might change over time, so if you adopt it, I recommend adding a test to your application to make sure it's having the desired effect. That way, if the gem changes later on, you'll know when you update it.

```
require "bundler/inline"

gemfile do
  gem "graphql", "1.12.17"
end

class BaseObject < GraphQL::Schema::Object
  # ... your app's base object here
end

class BaseMutationPayload < BaseObject
  def self.add_field(field, *args, **kwargs)
    if field.graphql_name == "clientMutationId"
      # do nothing -- don't want this field
    else
      super
    end
  end
end

class BaseInputObject < GraphQL::Schema::InputObject
  # ... your app's base input object here
end

class BaseMutationInput < BaseInputObject
  def self.argument(name, *args, **kwargs, &block)
    if name == :client_mutation_id
      # do nothing -- don't want this argument
    else
      super
    end
  end
end

class BaseMutation < GraphQL::Schema::RelayClassicMutation
  object_class(BaseMutationPayload)
  input_object_class(BaseMutationInput)
end

class UpdateUser < BaseMutation
  argument :user_id, ID, required: true
  argument :user_name, String, required: true

  field :new_user_name, String, null: false
end

class Mutation < BaseObject
  field :update_user, mutation: UpdateUser
end

class Schema < GraphQL::Schema
  mutation(::Mutation)
end

puts Schema.to_definition
# type Mutation {
#   updateUser(
#     """
#     Parameters for UpdateUser
#     """
#     input: UpdateUserInput!
#   ): UpdateUserPayload
# }

# """
# Autogenerated input type of UpdateUser
# """
# input UpdateUserInput {
#   userId: ID!
#   userName: String!
# }

# """
# Autogenerated return type of UpdateUser
# """
# type UpdateUserPayload {
#   newUserName: String!
# }
```
