### ISSUE TITLE
Troubleshoot performance of a query

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#3442]
Copied from https://github.com/rmosolgo/graphql-ruby/issues/3379#issuecomment-820782913

------

Hi @rmosolgo, I'm having a similar performance problem in my application where a large number of objects in the response results in a very slow(10-15 seconds) turnaround. We've identified that most of this time is spent in application code and not the DB. I used the profiling tools you suggested above and got the following:

[stackprof dump in wall, cpu and object mode](https://github.com/rmosolgo/graphql-ruby/files/6321476/stackprof.txt)
[memory profiler logs](https://github.com/rmosolgo/graphql-ruby/files/6321479/memory_profiler.txt)

I was wondering if you can help us track down the bottleneck using the logs above? Is there a way we can enhance the query performance? 

Here is the query we're making in case it helps:
[sample query](https://github.com/rmosolgo/graphql-ruby/files/6321485/sample_query.txt)

Our Stack:
```
ruby 2.7.1
rails (6.0.3.6)
graphiql-rails (1.7.0)
graphql (1.12.8)
graphql-batch (0.4.3)
graphql-pro (1.17.12)
```

Sidenote: I can make this into a separate issue if you'd prefer.

_Originally posted by @siav92 in https://github.com/rmosolgo/graphql-ruby/issues/3379#issuecomment-820782913_

**Comment by rmosolgo** [comment]
Hey @siav92, Looking at the profiling information, here's what stands out to me: 

1. __Lots of time spent in GC__: About 10% of runtime is spent in GC, which means the code is making _lots_ of objects:

    ```
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
       818   (6.0%)         818   (6.0%)     (marking)
       632   (4.6%)         623   (4.6%)     ActiveModel::AttributeMethods#respond_to?
       593   (4.3%)         593   (4.3%)     (sweeping)
       526   (3.9%)         526   (3.9%)     #<Module:0x00007fa9f0e9d2b0>.generate_guid
       912   (6.7%)         478   (3.5%)     ActiveRecord::AttributeMethods::Read#_read_attribute
       964   (7.1%)         441   (3.2%)     ActiveRecord::DynamicMatchers#respond_to_missing?
       362   (2.6%)         362   (2.6%)     GraphQL::Query::Context#[]=
       323   (2.4%)         323   (2.4%)     ActiveRecord::DynamicMatchers::Method.pattern
       297   (2.2%)         295   (2.2%)     Concurrent::Collection::MriMapBackend#compute_if_absent
       290   (2.1%)         290   (2.1%)     Puma::Cluster::Worker#run
       328   (2.4%)         277   (2.0%)     ActiveModel::LazyAttributeHash#[]
      4837  (35.4%)         262   (1.9%)     GraphQL::Execution::Interpreter::Runtime#evaluate_selection
       263   (1.9%)         259   (1.9%)     StoreModel::ParentAssignment#assign_parent_to_singular_store_model
       210   (1.5%)         210   (1.5%)     GraphQL::Execution::Interpreter::Runtime#set_type_at_path
       523   (3.8%)         200   (1.5%)     ActiveRecord::DynamicMatchers::Method.match
      2244  (16.4%)         190   (1.4%)     Object#bullet_key
       181   (1.3%)         181   (1.3%)     String#bullet_class_name
    ```
    
    The good news is, if we can find what objects are being created so much, and remove those allocations, then we'll have a double-win: we can save the time _allocating_ those objects, then we can save the time _GCing_ those objects. 
    
2. It looks like most of those objects are coming from ActiveRecord and Bullet: 

    ```
    allocated objects by location
    -----------------------------------
    923606  /Users/siavosh/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bullet-6.1.4/lib/bullet/ext/object.rb:5
    723231  /Users/siavosh/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.6/lib/active_record/attribute_methods/primary_key.rb:20
    491400  /Users/siavosh/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/core_ext/numeric/conversions.rb:108
    346491  /Users/siavosh/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bullet-6.1.4/lib/bullet/ext/string.rb:5
    247560  /Users/siavosh/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/core_ext/object/json.rb:172
    150544  /Users/siavosh/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.6/lib/active_record/reflection.rb:806
    129466  /Users/siavosh/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.6/lib/active_record/relation/delegation.rb:117
     96583  /Users/siavosh/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.12.8/lib/graphql/execution/interpreter/runtime.rb:181
     96583  /Users/siavosh/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.12.8/lib/graphql/execution/interpreter/runtime.rb:271
     ```
     
     Above, I see the normal "offenders" from graphql-ruby (`interpreter/runtime.rb`), but they are eclipsed by tons of allocations from ActiveRecord. I'm guessing that some of those lines of code point to the methods that appear in the stackprof output above, for example:
     
     - `lib/bullet/ext/object.rb:5` => `Object#bullet_key`
     - `lib/bullet/ext/string.rb:5` => `String#bullet_class_name`
     - `lib/active_support/core_ext/numeric/conversions.rb:108` => `Numeric#to_s` ([source](https://github.com/rails/rails/blob/0d91d4aa07cd69d97e8390176d43a93a862cca0a/activesupport/lib/active_support/core_ext/numeric/conversions.rb#L109)
     - `lib/active_record/attribute_methods/primary_key.rb:20` => `ActiveRecord::Base#id` ([source](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/attribute_methods/primary_key.rb#L17-L20)]
     - `active_record/relation/delegation.rb:117` => `#create` ?? ([source](https://github.com/rails/rails/blob/0073c7b29339b2ee1e11aa5c9622ea452d0633fc/activerecord/lib/active_record/relation/delegation.rb#L117))
     - `active_record/reflection.rb:806` => `#through_reflection` ([source](https://github.com/rails/rails/blob/0073c7b29339b2ee1e11aa5c9622ea452d0633fc/activerecord/lib/active_record/reflection.rb#L806))
     
     
My take-aways from this investigation are: 

- Bullet is adding a lot of overhead; you could try removing bullet from the Gemfile, then re-running your benchmark to confirm this. What does the profiler output look like with bullet disabled or removed?
- ActiveRecord is adding a lot of overhead. Interestingly, some very _dynamic_ features of ActiveRecord show up above (eg, reflecting on associations).

Are any parts of the example GraphQL query powered by those dynamic ActiveRecord features? Could they be refactored _not_ to use those features? Maybe reducing the use of those would also reduce the overhead from Bullet. 


I don't see anything in the benchmark above that indicates that graphql-ruby is a problem. In both stackprof output and memory_profiler output, graphql-ruby makes up a substantial, but reasonable, portion of the overhead.

**Comment by siav92** [comment]
Many thanks for the quick response, much appreciated. I disabled both bullet and Newrelic to remove their overhead and regenerated the profiles. Our response time didn't improve by a lot, but the reports have better visibility now:
[stackprof_v2.txt](https://github.com/rmosolgo/graphql-ruby/files/6327645/stackprof_v2.txt)
[memory_profiler_v2.txt](https://github.com/rmosolgo/graphql-ruby/files/6327647/memory_profiler_v2.txt)

I will try to dig deeper into our code and see where those ActiveRecord objects are being used and see if we can make some improvements there. I also noticed that GC fluctuates between 5%-15% every time I run the query.

**Comment by siav92** [comment]
Hey @rmosolgo, I've done more investigation in our codebase and tried disabling different types of data manipulation we have (stuff that resulted in a large number of ActiveRecord operations in the profiles) but it didn't really help much with performance. 

I also wanted to point out that the profiles I sent before did not include pagination, as I thought the source of our slow response would stand out that way. However, upon re-generating them with pagination, I noticed that the order of used resources in the profiles changes noticeably:
[stackprof_with_pagination.txt](https://github.com/rmosolgo/graphql-ruby/files/6354079/stackprof_with_pagination.txt)
[memory_profiler_with_pagination.txt](https://github.com/rmosolgo/graphql-ruby/files/6354080/memory_profiler_with_pagination.txt)

I can also explain our use case to shed more light on the problem. We have a page where we display multiple lists and we need to fetch the contents of each list on page load. Therefore we make a batched request of the aforementioned query, using GraphQl multiplexing. This query is now taking around 500-700 milliseconds for each pipeline so the batched request has a response time of 5,6 seconds which is far from ideal.

I'm not sure if you had a chance to check out our [sample query](https://github.com/rmosolgo/graphql-ruby/files/6321485/sample_query.txt) above but we do ask for a long list of fields in there, lots of which are connections coming through ActiveRecord associations. I've confirmed that each field is taking a reasonable chunk of the overall duration and it's not one or two being super inefficient. 

Is it safe to assume that the response time is slow, simply because we require too many fields? If so, could we speed it up by sending raw values instead?

**Comment by rmosolgo** [comment]
> Is it safe to assume that the response time is slow, simply because we require too many fields? 

I will say, I don't see any opportunities to greatly reduce GraphQL's overhead here. The main culprits, looking at stackprof and memory_profiler outputs, are the runtime's internal bookkeeping (paths, runtime context, etc), which I have tried many times to improve, but can't quite find a way. So, does that mean the problem is "too many fields"? Maybe -- the GraphQL overhead would definitely be reduced if the query was smaller. But if GraphQL had less overhead, then it wouldn't be a problem 😖 

> If so, could we speed it up by sending raw values instead?

Yes, this would definitely help, since any fields served by `raw_value(...)` don't require all the GraphQL runtime bookkeeping that shows up in the traces above. (The trick is making that work _properly_, I don't really know how to, but I know plenty of folks use it!)

**Comment by rmosolgo** [comment]
#3494 was just merged to master, and I recommend giving it a shot: 

```ruby 
gem "graphql", github: "rmosolgo/graphql-ruby" 
```

I'll cut a new version soon, but if you want to try your benchmarks, you can bundle master with ☝️  

I hope it helps, but I don't have any more plans to inspect performance, so I'm going to close this issue. If you run into problems on master or on the next release, please open a new issue with new profiling artifacts. Thanks!
