### ISSUE TITLE
How to stitch queries together

### ISSUE THREAD

**Issue by KKzLEO** [rmosolgo/graphql-ruby#3455]
Hi, thanks for inventing this gem, I have a question about how to combine queries together, for example:
I have a query named `Item` that calls an external API to get item information with arguments `itemId` and `shopId`
, my resolver will look like
```
class ItemQuery < GraphQL::Schema::Resolver
    type ItemType, null: false
    
    argument :shop_id, String, required: true
    argument :item_id, String, required: true

    def resolve(shop_id:, item_id:)
        ## Call external API
    end
end

class QueryType < Types::BaseObject
    field :item, resolver: ItemQuery
end

class Schema < GraphQL::Schema
    query(QueryType)
end
```

it works pretty good, but what if I can't get `shopId` from frontend, I need to call another query that will help us call another external API to get shop's information, so I created a `shop` query, like:
```
class ShopQuery < GraphQL::Schema::Resolver
    type ShopType, null: false
    
    argument :shop_url, String, required: true

    def resolve(shop_url:)
        ## Call external API
    end
end

def ShopType < GraphQL::Schema::Object
     field :shopId, String, null: false
     # ... other fields
end
```

My original thought is to use `@export` directive to export `shopId` so `ItemQuery` can get `shopId`, but it seems to complex to implement, so I decided to put `ItemQuery` below `ShopQuery`, like:
```
class ShopQuery < GraphQL::Schema::Resolver
    type ShopType, null: false
    
    argument :shop_url, String, required: true

    def resolve(shop_url:)
        ## Call external API
    end
end

def ShopType < GraphQL::Schema::Object
     field :shopId, String, null: false
     
     field :item, resolver: ItemQuery
     # ... other fields
end
```
then modify `ItemQuery` to 
```
class ItemQuery < GraphQL::Schema::Resolver
    type ItemType, null: false
    
    # argument :shop_id, String, required: true
    argument :item_id, String, required: true

    def resolve(item_id:)
        shop_id = object['shop_id']
        
        ## Call external API
    end
end
```
```
Query String: 
fetch($shopUrl: String, $itemId: String){
    shop(shopUrl: $shopUrl) {
         item(itemId: $itemId) {
             name
             ....
         }
    }
}
```
It works fine but .... in some situations I can get `shop_id` from frontend, I don't want to create two similar queries(one has `shop_id` argument, another doesn't), so I modified `ShopType` and `ItemQuery` to
```
def ShopType < GraphQL::Schema::Object
     field :shopId, String, null: false
     
     field :item, ItemType, null: false do
         argument :item_id, String, required: true
     end
     
     def item(item_id:)
         ItemQuery.new(object: object, context: context, field: nil).resolve(item_id: item_id, shop_id: object['shopId'])
     end
end

class ItemQuery < GraphQL::Schema::Resolver
    type ItemType, null: false
    
    argument :shop_id, String, required: true
    argument :item_id, String, required: true

    def resolve(shop_id:, item_id:)
        ## Call external API
    end
end
```

I don't know if it's good or not but It will ignore arguments validation and `extension` ... etc, cuz I didn't use interpreter to resolve the field, it makes me feel upset to handle this situation, so I created a method named `find_value` that will find the data from `object`, `arguments` and `context`, but it looks a little bit weird... I am wondering if you could give me some tips for handing this, many thanks

```
class ItemQuery < BaseQuery
    type ItemType, null: false
    
    argument :shop_id, String, required: false
    argument :item_id, String, required: true

    def resolve(_)
        shop_id = find_value('shop_id')
    
        ## Call external API
    end
end

class ShopQuery < BaseQuery
    type ShopType, null: false
    
    argument :shop_url, String, required: true

    def resolve(shop_url:)
        ## Call external API
    end
end

def ShopType < GraphQL::Schema::Object
     field :shopId, String, null: false
     
     field :item, resolver: ItemQuery
     # ... other fields
end

class BaseQuery < GraphQL::Schema::Resolver
    def find_value(name, first: object, second: arguments, third: context)
        first.try(name) || second.try(name) || third.try(name)
    end
end
```

**Comment by rmosolgo** [comment]
Thanks for the detailed question, it's a great one. 

`Resolver.new(...).resolve(...)` isn't a supported API; there's no guarantee that it will keep working in future GraphQL-Ruby versions, so I don't recommend using it. 

But I think you're on to something there. How about implementing a similar class _in your application_? for example: 

```ruby 
# app/models/shop/find_item.rb
class Shop::FindItem 
  def initialize(shop_id:, item_id:)
    @shop_id = shop_id 
    @item_id = item_id 
  end 
  
  def lookup_item 
    # Use `@shop_id` and `@item_id` to fetch the object from the external service, then return it 
  end 
end 
```

Then, you could use that object to implement _both_ fields in your GraphQL schema: 

```ruby 
def ShopType < GraphQL::Schema::Object     
  field :item, ItemType, null: true do 
    argument :item_id, String, required: true 
  end 
  
  def item(item_id:)   
    finder = Shop::FindItem.new(item_id: item_id, shop_id: object['shop_id'])
    finder.lookup_item 
  end 
end
```

and 

```ruby 
class QueryType < Types::BaseObject
    field :item, ItemType, null: true do 
      argument :item_id, String, required: true 
      argument :shop_id, String, required: true 
    end 
    
    def item(item_id:, shop_id:)
      finder = Shop::ItemFinder.new(item_id: item_id, shop_id: shop_id)
      finder.lookup_item
    end
end
```

I think an approach like this covers all the goals:

- External service call is DRY; it's only made inside `Shop::ItemFinder`
- You can unit test `Shop::ItemFinder` in isolation; you don't have to run GraphQL queries to test the implementation of that class. 
- It only uses public GraphQL-Ruby APIs

How about trying an approach like that?

**Comment by KKzLEO** [comment]
Hi, thanks for answering, I am trying to use this way to refactor my code, many thanks

**Comment by rmosolgo** [comment]
Let me know if you run into any trouble with it!
