### ISSUE TITLE
rake task does not insert final newline

### ISSUE THREAD

**Issue by thinceller** [rmosolgo/graphql-ruby#3462]
**Is your feature request related to a problem? Please describe.**

The IDL generated by the rake task does not have a final newline.

It is defined in POSIX that a line contains a newline at the end.
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206
So, tools such as diff may show something like `No newline at end of file`, or unintended differences may be created by the editor.

Since `String#chomp` is used as the expected IDL String in tests, I think that the above is intentional behavior.
ref: https://github.com/rmosolgo/graphql-ruby/blob/e58e649241452ba673e90cf4c2062c4e970df0b4/spec/graphql/schema/printer_spec.rb#L401
But, I'm not sure if there is any advantage to this behavior.

**Describe the solution you'd like**

Insert a final newline in the generated IDL.

**Describe alternatives you've considered**

Insert a final newline around https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/rake_task.rb#L101,  or make a change to `GraphQL::Language::Printer`.

**Additional context**

**Comment by rmosolgo** [comment]
:+1: Yes, I think a final newline would be an improvement. I'm not sure which place would be better; either one would be fine with me. 

I suspect `chomp` was added to get the test to pass, not because it was squarely a better behavior! 🙈

**Comment by thinceller** [comment]
@rmosolgo 
Thanks! 😄

**Comment by jgrau** [comment]
For those of us that dump the schema and expect that the current schema (the schema that would be generated based on the current schema definition) matches the dumped schema: this change requires `chomp`ing when reading the dumped file.

In my case the spec now looks like:

```
  it 'matches the dumped schema (rails graphql:generate:schema)' do
    aggregate_failures do
      expect(described_class.to_definition).to eq(
        File.read(Rails.root.join('schema.graphql')).chomp,
      )
      expect(described_class.to_json).to eq(
        File.read(Rails.root.join('schema.json')).chomp,
      )
    end
  end
```
