### ISSUE TITLE
Potential (Sentry) SQL Tracing Issues with Interpreter

### ISSUE THREAD

**Issue by rtymchyk** [rmosolgo/graphql-ruby#3466]
**Describe the bug**

I've upgraded `graphql-ruby` recently to 1.12. So far everything looks great, I'm digging all the new APIs and toys like Dataloader. However, I am using Sentry to do performance tracing, and have noticed that the traces have stopped including SQL spans/logs with the new version. 

Obviously this could very well be a problem with Sentry but my assumption is that this SQL logging is universal to Rails, not specific to Sentry, and the issue came up with the version bump. I am happy to shoot this over to Sentry if there's nothing obvious about this. Could be related to https://github.com/rmosolgo/graphql-ruby/issues/3366?

**Versions**

`graphql` version: 1.12.8
`graphql-pro` version: 1.17.15
`rails`: 6.0.3.6
`sentry-ruby`: 4.3.1
`sentry-rails`: 4.3.3

**GraphQL schema**
Probably not relevant, but only thing worth mentioned is that I am using `use GraphQL::Dataloader`

**GraphQL query**
Any query.

**Expected behavior**

Full SQL logging is present.

![Screen Shot 2021-05-06 at 5 42 16 PM](https://user-images.githubusercontent.com/3498278/117369229-a31d5980-ae92-11eb-9576-6e4562dddfc9.png)

**Actual behavior**
No SQL logging is present from our GraphQL controller. The single SQL entry that shows is a rails `before_action` hook that loads the current user before the GraphQL execution happens, so it indicates that it partially works with regular Rails-y stuff.

![Screen Shot 2021-05-06 at 5 41 48 PM](https://user-images.githubusercontent.com/3498278/117369394-d9f36f80-ae92-11eb-8c20-d7242243d982.png)

**Comment by rmosolgo** [comment]
Hey, thanks for the detailed report. 

Without looking into the details, I'd _guess_ it's an issue with `Thread.current[...]` (Fiber-local variables), which aren't copied to new threads in GraphQL-Ruby 1.12.8. 

I just merged a PR to copy Fiber-local variables into Dataloader-created Fibers (#3461), you can give it a try on master if you want: 

```ruby 
# Gemfile 
gem "graphql", github: "rmosolgo/graphql-ruby"
```

Otherwise, I'll try to cut 1.12.9 tomorrow and follow up here!

**Comment by rtymchyk** [comment]
Thanks for the quick reply! I'll give it a shot :)

**Comment by rmosolgo** [comment]
I just released 1.12.9 -- let me know how it goes if you give it a try!

**Comment by rtymchyk** [comment]
@rmosolgo looks good! Thanks for quick fix :)
