### ISSUE TITLE
How to handle global IDs in field arguments?

### ISSUE THREAD

**Issue by marten** [rmosolgo/graphql-ruby#3467]
I'm looking into adding relay-style global IDs to our GraphQL API. With mutations, it all works wonderfully using `loads`, runs through Pundit automatically and the world is great.

However, in the query part of our API, we have fields where you can use other model's IDs to filter lists, for instance:

```graphql
  dossier(id: "Dossier-4") {
    id
    responses(questionnaireIds: ["Questionnaire-534"]) {
      id
      questionnaire { id }
    }
  }
```

In the Dossier type, before going to global IDs, we have (simplified, insecure) code that can just pass database IDs from the arguments directly to ActiveRecord:

```ruby
  field :responses, [Types::ResponseType], null: false do
    argument :questionnaire_ids, Array[ID], required: false
  end

  def responses(questionnaire_ids: [])
    object.responses.where(questionnaire_ids: questionnaire_ids)
  end
```

With global IDs, we don't want to do a `loads:` on the argument here, because we don't actually care about the `questionnaire` objects, we just need their IDs. But we do want to decode from global ID back to database ID. And I don't want to have to deal with that in every field that takes IDs as arguments.

For now, I've worked around this by implementing a method markes as private API in BaseArgument like so:

```ruby
module Types
  class BaseArgument < GraphQL::Schema::Argument
    def prepare_value(obj, value, context: nil)
      if type.unwrap == GraphQL::Types::ID && !loads && !owner.relay_node_field
        if type.list?
          super(obj, RecordId.id_part(value), context: context)
        else
          super(obj, value.map { |record_id| RecordId.id_part(record_id) }, context: context)
        end
      else
        super(obj, value, context: context)
      end
    end
  end
end
```

Which leaves me with two questions:

1. Is this an acceptable, recommended approach to solve this? I can't find any built-in things to handle this conversion for me, but maybe I've missed something.
2. I see that for 1.13 there is an overhaul planned to the whole global ID approach. Is this issue something that's on your radar for that? I'd be happy to help draft out plans for it. We don't really care about relay support being Apollo users ourselves, but we do really like the automatic object loading for mutations and it seems global IDs is the only way to achieve that right now (possibly ever, given interfaces and type unions need to be supported too), leading me to believe this is a less-walked path that might be good to hear about?

**Comment by rmosolgo** [comment]
Hey, thanks for the detailed writeup.

Yes, I think this is a fine way to handle this. There's been some discussion about better tooling for preparing argument values (eg https://github.com/rmosolgo/graphql-ruby/issues/2749#issuecomment-728185805, https://github.com/rmosolgo/graphql-ruby/issues/3144#issuecomment-692233203), but I haven't built anything else. If you determined that the overhead of this implementation, you could add it on a case-by-case basis with a [field extension](https://graphql-ruby.org/type_definitions/field_extensions.html).

For 1.13, I don't plan to change how IDs are _used_, but I plan to recommend a different system for encoding and decoding IDs (something more like Rails's GlobalID module). So I wouldn't expect you to have any trouble with it.

>  less-walked path that might be good to hear about?

What do you mean by that? (It sounds like you're using global IDs in the conventional and expected way here.)

**Comment by rmosolgo** [comment]
Let me know if you run into any more trouble with the code you're using!

**Comment by benbonnet** [comment]
shouldn't it be the inverse condition ?

```
module Types
  class BaseArgument < GraphQL::Schema::Argument
    def prepare_value(obj, value, context: nil)
      if type.unwrap == GraphQL::Types::ID && !loads && !owner.relay_node_field
        if type.list?
          super(obj, value.map { |record_id| RecordId.id_part(record_id) }, context: context)
        else
          super(obj, RecordId.id_part(value), context: context)
        end
      else
        super(obj, value, context: context)
      end
    end
  end
end
```
