### ISSUE TITLE
Dynamic connection params in ActionCableLink.ts

### ISSUE THREAD

**Issue by arathunku** [rmosolgo/graphql-ruby#3468]
**Is your feature request related to a problem? Please describe.**

Due to technical limitations and cross origin requests, we cannot authenticate the ActionCable connection (no option to pass additional headers, cookies are not available) and have to authenticate individual channels. 

**Describe the solution you'd like**

https://github.com/rmosolgo/graphql-ruby/blob/master/javascript_client/src/subscriptions/ActionCableLink.ts#L31

If `this.connectionParams` supported function instead of object, it would be easier to pass additional auth token. Unfortunately, it cannot be provided during initialization because the auth token is also stored inside Apollo context. 

```diff
-      }, this.connectionParams), {
+      }, (typeof this.connectionParams === "function") ? this.connectionParams(operation) : this.connectionParams), {
```

**Describe alternatives you've considered**

I've started by "packaging" ActionCableLink inside another Apollo Link but it becomes overly complicated just for such a simple thing. I've also tried creating an additional auth subscription that would use a separate channel and set auth on the connection but same, very complex with a lot of edge cases to handle.

**Additional context**

If there's another/different way of authentication, please share. Cookies/headers are not an option in our case. 

I'm happy to submit PR with the change and test if this is acceptable proposal.

**Comment by wolak88** [comment]
@arathunku @rmosolgo 
I'm using apollo 3 and wanted to authenticate my websocket, I did (I'm on version 1.9.4):
```
const subscription = (new ActionCableLink({
  cable: createConsumer(`${URL}/cable`),
  connectionParams: { paramFirst: 'paramFirst', paramSecond: 'paramSecond' },
})
```

How can I access those parameters in my rails connection controller?
This is the request made by my browser:
<img width="591" alt="Screenshot 2021-06-16 at 12 28 51" src="https://user-images.githubusercontent.com/5196691/122203626-8404e500-ce9e-11eb-8473-496f2f7d88ea.png">
