### ISSUE TITLE
Mac issue installing graphql-libgraphqlparser

### ISSUE THREAD

**Issue by kimegede** [rmosolgo/graphql-ruby#347]
Had an issue on Mac installing `graphql-libgraphqlparser`.
Needed to run `brew install libgraphqlparser` and depending if the verision of `libgraphqlparser` [see link](https://github.com/rmosolgo/graphql-libgraphqlparser-ruby#libgraphqlparser-versions).

You will need to change the `Gemfile` & `Gemfile.lock` with different version.

**Comment by rmosolgo** [comment]
I there anything I can help you with here?

**Comment by kimegede** [comment]
No thanks, I did fix it, but needed to follow these steps.

**Comment by rmosolgo** [comment]
Ok, thanks for documenting them!
