### ISSUE TITLE
Mutation Authorization method definition for many mutations

### ISSUE THREAD

**Issue by kaczor1984** [rmosolgo/graphql-ruby#3473]
**Describe the bug**

I am not able to query eg. the `load_something(id)` method when it is defined outside of the mutation file.
I wanted to use this approach:
https://github.com/rmosolgo/graphql-ruby/blob/master/guides/mutations/mutation_authorization.md#loading-and-authorizing-objects

When it is included in the file that is queried - it looks to be working ok.
But I've got a lot of files where I would like to have the same `load_something(id)` method.
And when I define it outside of the mutation file - it is not called anymore.

**Versions**

`graphql` version: 1.12.6
`rails` (or other framework): 6.1.3.1

**GraphQL schema**

```ruby
module Mutations
  module Group
    class Create < BaseMutation
      argument :something_id, ID, required: true, loads: Types::SomethingType
      
      # def load_something(id)
      #   puts "will work when uncommented here"
      # end
    end
  end
end

base_mutation.rb
module Mutations
  class BaseMutation < GraphQL::Schema::RelayClassicMutation
    def load_something(id)
      # does not work even though it is defined in the class that is treated as a parent of my class
      # so it should work ? Or am I doing something wrong ?
    end
  end
end

my_app_schema.rb
# the obfuscator is used by us to 'encrypt' the id's of the objects
require 'obfuscator'

class MyAppSchema < GraphQL::Schema
  mutation(Types::MutationType)
  query(Types::QueryType)

  def self.resolve_type(type, obj, _ctx)
    type.to_s.start_with?('Interfaces') ? "Types::#{obj.class.name}Type".constantize : type
  end

  rescue_from(ActiveRecord::RecordNotFound) do |err, _obj, _args, _ctx, _field|
    # Raise a graphql-friendly error with a custom message
    raise GraphQL::ExecutionError, err.message
  end

  use GraphQL::Dataloader

  def self.id_from_object(object, _type_definition, _query_ctx)
    # Call your application's UUID method here
    # It should return a string
    Obfuscator.encrypt(object.class.name, object.id)
  end
end
```

**Steps to reproduce**

execute a query that runs this mutation

**Expected behavior**

I expected that the `load_something` will be called from a base_mutation file

**Actual behavior**

It is ignored unless I will define it in the Mutation Class.

**Comment by rmosolgo** [comment]
Thanks for the detailed report. I agree it should work the way you expect. I think the problem is that, whenever resolvers get an `argument(..., loads: ...)` configuration, they define a method with that name: 

https://github.com/rmosolgo/graphql-ruby/blob/bd574f70354e6435f06f50020a4c6bf26a8975e0/lib/graphql/schema/resolver.rb#L336-L360

But maybe, instead, it should not define a method if there's already a definition for it!
