### ISSUE TITLE
ActionCable Subscriptions failing with Heroku Redis 6

### ISSUE THREAD

**Issue by annienero** [rmosolgo/graphql-ruby#3484]
**Describe the bug**
Graphql subscriptions aren't working due to OpenSSL::SSL::SSLError errors after upgrading to heroku-redis 6.

**Versions**
`graphql` version: 1.11.1
`rails`: 6.0.3.7
`graphql-batch`: 0.4.2 but probably unrelated
`heroku-redis`: 6.0.12

**GraphQL schema**
```ruby
class ApplicationSchema < GraphQL::Schema
    mutation(Types::MutationType)
  query(Types::QueryType)
  subscription(Types::SubscriptionType)

  use(GraphQL::Execution::Interpreter)
  use(GraphQL::Analysis::AST)
  use(GraphQL::Batch)
  use(GraphQL::Tracing::ScoutTracing)
  use(
    GraphQL::Subscriptions::ActionCableSubscriptions,
    redis: Redis.new(url: ENV['REDIS_URL'], ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE })
  )
  use(BatchLoader::GraphQL)
end
```

in our `cable.yml`:
```
production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>
```

I also tried setting `config.cache_store = :redis_cache_store, { url: ENV['REDIS_URL'], ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE } }` in `config/environments/production.rb` but haven't had any luck with any combination of the above.

**Steps to reproduce**
Any Rails project with GrahpQL subscriptions using ActionCable configured using the Redis adapter and a Redis url pointing to a Heroku Redis instance. Then upgrade (or already use) Redis 6 for this instance. Heroku requires TLS/SSL connections for Premium Redis 6 instances and I think that causes the problem.
After rebooting the application and visiting any page that uses subscriptions, the subscriptions fail.

**Expected behavior**
Subscriptions continue to work as before the redis upgrade.

**Actual behavior**
Getting `OpenSSL::SSL::SSLError` errors and no data back from subscriptions.

**Additional context**
Similar issue with rails: https://github.com/rails/rails/issues/42036

Any ideas? Do any of these seem like the right place to update my config? Not sure if this is a bug or docs just need to clarify. Thanks in advance!

**Comment by rmosolgo** [comment]
Sorry, from a GraphQL perspective, I have to assume that ActionCable Just Works :tm:. If it's not working, I recommend looking into the networking or Rails setup, but I don't have any insight into that. Hopefully something will turn up on the Rails issue that you linked!

**Comment by smenor** [comment]
Did you ever solve this @annienero ?
