### ISSUE TITLE
Unexpected behavior with validation of empty string argument 

### ISSUE THREAD

**Issue by denisahearn** [rmosolgo/graphql-ruby#3492]
**Describe the bug**

We have a string argument on a field that we want to ensure is not null and not blank/empty. We can achieve the not null by adding `required: true` to the argument definition, however achieving the not empty has been tricky. I didn't find a [built-in validator](https://graphql-ruby.org/fields/validation.html#built-in-validations) that I could use to ensure not blank, so I wrote a custom `NotBlankValidator` class to do this. Once I defined this validator on my argument, I started getting the expected "{argument name} can't be blank" validation error message, but not for the expected reason.

The "{argument name} can't be blank" validation error message is coming from the graphgql gem from [this line of code](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/validator.rb#L41). My custom validator doesn't get called when the argument's value is an empty string. It looks like the `GraphQL::Schema:: Validator#apply` method [only gets called](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/validator.rb#L125) when the argument has validators defined on it. If I remove my custom validator from the argument then the `GraphQL::Schema:: Validator#apply` method doesn't get called, and the query happily accepts an empty string for this argument.

I want the "not blank" behavior for this argument, but it seems odd to have to define some/any validator on the argument just to get the built-in "not blank" check that the `GraphQL::Schema:: Validator#apply` method provides. Perhaps there should be a built-in `not_blank` validator that can be used for an argument when you want this behavior.

Please let me know if you need me to provide a sample application that demonstrates this behavior. I'm hoping my explanation above is sufficient to define the problem. Thanks.

**Versions**

`graphql` version: 1.12.8
`rails` version: 6.1.3.1

**GraphQL schema**

**GraphQL query**

**Steps to reproduce**

**Expected behavior**

**Actual behavior**

**Additional context**

**Comment by rmosolgo** [comment]
Thanks for the suggestion. Funny that the `allow_blank: false` option is applied in that case ... but there's no way to use it on its _own_ 🙈 . I agree it should be available one way or another, thanks for the suggestion!

**Comment by fabn** [comment]
I agree, `allow_blank` should be usable on its own, or maybe as an option of required, something like:

```ruby
argument :full_name, String, required: {allow_blank: false}
```

**Comment by masterkain** [comment]
how can I allow to nullify a field?

`argument :album, String, 'Album name', required: false, validates: { length: { allow_blank: true, maximum: 250 } }`

does not work
