### ISSUE TITLE
Shared extensions across resolvers

### ISSUE THREAD

**Issue by sidwatal** [rmosolgo/graphql-ruby#3493]
I am trying to create an extension that is shared across a number of resolvers but adding `extension ResolverExtension` into the `BaseResolver` that they all inherit from doesn't seem to work. The extension is working as designed when added to the resolvers directly. We can obviously just add the extension to each resolver as needed but I am trying to avoid that.

gem versions if that helps
```
graphql (1.11.1)
graphql-pro (1.17.4)
```

**Comment by rmosolgo** [comment]
Hey, thanks for the bug report. I agree it should work the way you expect. Here's the code in question: 

https://github.com/rmosolgo/graphql-ruby/blob/cd337dc89eb0ef0b82825b5d2879313ec2b9646c/lib/graphql/schema/resolver.rb#L373-L383

It sounds like it should check the `superclass`, similar to how this one does: https://github.com/rmosolgo/graphql-ruby/blob/cd337dc89eb0ef0b82825b5d2879313ec2b9646c/lib/graphql/schema/object.rb#L172

In the meantime, you could work around this shortcoming by adding the extension in the `def inherited(child_class)` hook, for example: 

```ruby 
class BaseResolver < GraphQL::Schema::Resolver 
  def inherited(child_class)
    # apply this extension to all our resolvers 
    # check https://github.com/rmosolgo/graphql-ruby/issues/3493 for when graphql-ruby supports this properly
    child_class.extension(ResolverExtension) 
  end 
end 
```

I'll take a look soon and follow up here!
