### ISSUE TITLE
Wrong total_count size for offset pagination and extended field.

### ISSUE THREAD

**Issue by denis-mironov** [rmosolgo/graphql-ruby#3503]
I'm doing offset pagination and after results paginated and field resolved getting wrong total_count size in custom connection. It returns paginated results size. I'm using field extension to make pagination reusable with only keyword argument `paginate: true`. Keyword argument is added in BaseObject class. How to get right total_count size? What am i doing wrong? 

![Screen Shot 2021-05-27 at 13 52 36](https://user-images.githubusercontent.com/13961302/119821405-d03db480-bef2-11eb-92b3-961ee6dbf88c.png)

**Versions**
`graphql: 1.12.8`

Here is my code:

Field:
 ```
module Queries
  module SeoSettings
    extend ActiveSupport::Concern

    included do
      field :seo_settings, Types::SeoSettingType.connection_type, null: false,
        preauthorize: {to: :index?, with: SeoSettingPolicy}, paginate: true
    end

    def seo_settings
      SeoSetting.all.order(created_at: :desc)
    end
  end
end
```
Pagination field extension:
```
module Extensions
  class Pagination < GraphQL::Schema::FieldExtension
    class MissingAttributes < StandardError; end

    def apply
      field.argument(:pagination, Types::Pagination::Attributes, required: true)
    end

    # rubocop:disable Lint/UnusedMethodArgument
    def resolve(object:, arguments:, context:)
      field_relation = yield(object, arguments.except(:pagination))
      paginate(arguments, field_relation)
    end
    # rubocop:enable Lint/UnusedMethodArgument

    private
```
Custom pagination connection:
```
module Types
  module Pagination
    class CustomConnection < Types::BaseConnection
      field :total_count, Integer, null: false

      def total_count
        object.items.size
      end
    end
  end
end
```
BaseObject class:
```
module Types
  class BaseObject < GraphQL::Schema::Object
    include ActionPolicy::GraphQL::Behaviour

    field_class Types::BaseField

    field_class.prepend(
      Module.new do
        def initialize(*args, **kwargs, &block)
          kwargs[:extensions] = []
          extensions = {
            paginate: Extensions::Pagination,
          }

          extensions.each { |arg, ext| kwargs[:extensions] << ext if kwargs.delete(arg) }

          super
        end
      end
    )

    connection_type_class Types::Pagination::CustomConnection
  end
end
```
Request query:
```
query seoSettings(
  $limit: Int!,
  $offset: Int
  $page: Int
  ) {
  seoSettings(
    pagination: {
      limit: $limit
      offset: $offset
      page: $page
    }
  ) {
    totalCount
    nodes {
      id
      path
    }
  }
}
```

**Comment by denis-mironov** [comment]
@rmosolgo can you please help me with this situation?

**Comment by rmosolgo** [comment]
It looks like you're applying pagination during the extension's `def resolve(...)` step. This means that, when the connection system receives the ActiveRecord::Relation, it already has pagination applied. (`object.items` in your code above was already `LIMIT`ed, so `.count` was bounded by the limit.) 

The way that the connection system works is: 

- The whole AR::Relation is given to the connection object (it's `items`) 
- A second relation is created by applying pagination to the first one (`nodes`) 
- At runtime, `nodes` is used for the `nodes {...}` and `edges { ... }` fields, but `items` is used for `totalCount`. 

So, if you want the system to work that way, you'd have to create custom `Pagination::Connection` classes which accept the `pagination` argument and apply it as-needed. (Sounds tricky!) 

Alternatively, it sounds like you're not using cursor-based pagination, so why use connections at all? Instead, you could create `Page` objects and `*Page` types that work the way you want here. That'd probably be easier than trying to modify or extend connections to _also_ do offset-based pagination.
