### ISSUE TITLE
I got this when I defined a interface type and tried to implemented it.

### ISSUE THREAD

**Issue by jackalcooper** [rmosolgo/graphql-ruby#351]
```
in `define': schema contains Interfaces or Unions, so you must define a `resolve_type (obj, ctx) -> { ... }` function (NotImplementedError)
```

**Comment by jackalcooper** [comment]
That's my obj type's definition:
```
ALicenseType = GraphQL::ObjectType.define do
  name "ALicense"

  interfaces [LicenseInterfaceType]
end
```

**Comment by rmosolgo** [comment]
You need to provide a `resolve_type` function in your schema definition:

https://github.com/rmosolgo/graphql-ruby/blob/master/guides/schema/configuration_options.md#execution-functions

I'll update the error message to provide better guidance!

**Comment by jackalcooper** [comment]
The link of 
```
See "Object Identification" for more information about Relay IDs.
```
is broken

**Comment by jackalcooper** [comment]
quote:
```
When we have a member of an interface or union, which object type should we use?
```
I don't quite understand this. Could you please explain it a little bit more?
a member of an interface = an implementation of an interface?

**Comment by rmosolgo** [comment]
Sorry, I liked to the github guides, but the link works on the website: http://rmosolgo.github.io/graphql-ruby/schema/configuration_options

>  explain it a little bit more?

Happy to! Let's say you have a query like this: 

```graphql 
{
  node(id: "xyz123") {
    ... on SomeInterface {
      someField 
    }
  }
}
```

To execute this query: 

- First, we fetch an object from the database using the unique ID `xyz123` 
- Then, we resolve fields 

To resolve fields, we have to know: does the fetched object implement `SomeInterface`? 

This is where `resolve_type` is used. We call `resolve_type` with the fetched object to find its GraphQL type. Then we can check if the GraphQL type implements `SomeInterface`. 

Does that help?

**Comment by jackalcooper** [comment]
Thanks for your explain and being nice! Now I can see the point.

**Comment by thefliik** [comment]
@rmosolgo Awesome explanation!
