### ISSUE TITLE
v1.12.11 causes "stack level too deep" with rspec

### ISSUE THREAD

**Issue by Mathieuu** [rmosolgo/graphql-ruby#3512]
Upgrading to 1.12.11 broke one of our tests posting a graphql query with rspec. The query crashes with `stack level too deep` on ` ApiSchema.execute`.

What is strange is that it only breaks when running in rspec. The same request being called with the development server works perfectly. And the overflow is pretty since the same request on 1.12.10 and with `rails server` works with  `RUBY_THREAD_VM_STACK_SIZE=200000` (200kb) but on 1.12.11 crashes even with 10MB.

By bisecting I pinned down the problem down to that particular commit: https://github.com/rmosolgo/graphql-ruby/commit/d3e97e48f07ebb14ae00ce31c2c8a6f4d16025f8.

I imagine something in Rspec must interfere with the logic but despite trying to strip down my test from any other third-party gem, it still crashes. 

The test:
```rb
  it 'returns a 200 and the object' do
    object = create(:object)
    variables = { id: object.id }

    post graphql_path,
         params: { query: QUERY, variables: variables }
    expect(response.status).to eq(200)
  end
```

The GQL query is pretty big with 400 lines, 4 levels of nesting (complexity between O(1) and O(n) though), multiple fragments but nowhere big enough to fill the entire call stack.

Would love to hear your thoughts on what might be happening or how I can debug that further.

**Versions**

`graphql` version: 1.12.11 and 1.12.12
`rails`: 6.1.3
`rspec-rails`: 5.0.1
`graphql-batch`: 0.4.3

**Comment by rmosolgo** [comment]
Hi, sorry for the trouble! Thanks for the detailed report. If you're able, I'd love to see however much stack trace Ruby gives you. 

The `while ...` is certainly suspect in the commit you linked. If, somehow, an object is its _own_ `.graphql_parent`, then it could go infinite, though I can't imagine _how_ that'd happen 😖 

That bit of code was due for another refactor -- even in a normal case, the recursion there is one of the big inefficiencies of the current runtime code. 

I'm going to take a look at improving the algorithm to _not_ use `while ...`, and if I can't come up with something, I'll dig in further on this particular issue.

**Comment by rmosolgo** [comment]
Ok, I took a crack at a refactor in #3513, do you mind giving it a try locally to confirm that it fixes your issue? 

```ruby 
gem "graphql", github: "rmosolgo/graphql-ruby", ref: "non-recursive-dead-marking" 
```

Let me know what you find! Or, if you're not able to try it out locally, let me know and I'll 🚢  to rubygems and you can try that.

**Comment by Mathieuu** [comment]
Thanks for the quick try. Unfortunately, the problem is still happening with #3513 

My stack trace is not super helpful to find the problem:
```
  1) GraphQL - queries - offer_letter with short_id in query returns a 200 and the offer letter
     Failure/Error: render json: result

     SystemStackError:
       stack level too deep
     # ./app/controllers/graphql_controller.rb:20:in `execute'
     # ./spec/support/graphql_helpers.rb:12:in `post_graphql'
     # ./spec/requests/graphql/queries/offer_letter_spec.rb:23:in `block (3 levels) in <top (required)>'
     # ./spec/support/vcr.rb:28:in `block (2 levels) in <main>'
     # ./spec/support/sidekiq.rb:12:in `block (2 levels) in <main>'
```

Let me know if you know a good way to get more useful information. I have tried:
```rb
      $enable_tracing = false
      $trace_out = open('trace.txt', 'w')

      set_trace_func proc { |event, file, line, id, _binding, classname|
        $trace_out.puts "#{file}:#{line} #{classname}##{id}" if $enable_tracing && event == 'call'
      }

      $enable_tracing = true
      post_graphql(query, variables: variables)
      $enable_tracing = false
```

But it generates a 165mb file which is not super convenient to share. There are a lot of things happening in that file but I could not find an obvious pattern that repeats undefinitely.

**Comment by rmosolgo** [comment]
Ick, it doesn't include the `graphql` backtrace at all 😖 

I guess if it's the problem I guessed before (somehow an object has itself as `.graphql_parent`), the recursive `set_result` call at line 347 of the commit you linked might go infinite, too. I'll keep hunting for some way that it might be possible 🤔 !

**Comment by rmosolgo** [comment]
I added a check to the graphql-ruby tests to try to detect when the result relationships were getting messed up, but I couldn't find anything. Reading over the code, I can't come up with any way that a circular reference would come about. But it seems like it must be possible _somehow_! If you could, seeing the whole GraphQL query would be really helpful. If it's easier: 

- You could email me (rmosolgo@graphql.pro) instead of posting it here, and 
- You could reduce all the leaf field selections to just `__typename`. (Actually, if you run a query with just `__typename` instead of all the leaf field selections, does it still :boom: ? I'm _guessing_ so -- I bet it has something to do with the fragments -- but it'd be good to try.) 
- You could even obscure the query by replacing all the field names with just "field". Like I said, my _guess_ is that it's the fragments somehow... 🤔 

Hopefully that will yield another avenue to search!
