### ISSUE TITLE
Boolean Fields Should Delegate to Underlying Object's Predicate Method

### ISSUE THREAD

**Issue by sshaw** [rmosolgo/graphql-ruby#3519]
**Is your feature request related to a problem? Please describe.**

Field names matching underlying object methods are delegate automatically:

```rb
field :foo, String, :null => true # calls object.foo
```

But for predicate methods one must be explicit:
```rb
field :amaaaaazing, Boolean, :null => false
def amaaaaazing
  object.amaaaaazing?
end
```

**Describe the solution you'd like**

Delegate boolean field names to their matching predicate method 

**Describe alternatives you've considered**

Plugin

**Comment by rmosolgo** [comment]
Hi! Thanks for the suggestion. Personally, I prefix my boolean fields with `is_`, `has_`, or `can_` -- some helper verb to indicate that the resulting boolean is the answer to a question. 

If you want the behavior described above, I recommend adding the following to your base field class: 

```ruby 
class Types::BaseField < GraphQL::Schema::Field 
  def initialize(*args, **kwargs, &block) 
    # If this is a boolean field and no other `method:...` is specified, then 
    # use a predicate method with the given name to resolve it. 
    if kwargs[:type] == Boolean && !kwargs.key?(:method)
      kwargs[:method] = "#{kwargs[:name]}?"
    end 
    super
end 
```

That way, any boolean fields would use `#{name}?` to resolve values by default. Let me know if you run into any trouble with that approach!

**Comment by sshaw** [comment]
Thanks for this. I noticed that in 1.11.5 `Boolean` can be `"Boolean"` or `GraphQL::Types::Boolean`. 

One question: is there a more pluggable way to do this? For example if I have this across several projects can I just include a library while still respecting anything in the project's `Types::BaseField `?

**Comment by rmosolgo** [comment]
Sure, you could use a plain Ruby module:

```ruby 
module PredicateMethodsForBooleanFields
  def initialize(*args, **kwargs, &block) 
    # If this is a boolean field and no other `method:...` is specified, then 
    # use a predicate method with the given name to resolve it. 
    if kwargs[:type] == Boolean && !kwargs.key?(:method)
      kwargs[:method] = "#{kwargs[:name]}?"
    end 
    super
  end 
end 
```

and include it in any base class:

```ruby
class Types::BaseField < GraphQL::Schema::Field
  include PredicateMethodsForBooleanFields
end 
```

Hope that helps!
