### ISSUE TITLE
LIST and NON_NULL types should be nameless

### ISSUE THREAD

**Issue by jamesmacaulay** [rmosolgo/graphql-ruby#352]
The GraphQL spec requires that in an introspection response, types with a kind of "LIST" or "NON_NULL" must only have `kind` and `ofType` values present; all other properties must have null values:

https://facebook.github.io/graphql/#sec-List
https://facebook.github.io/graphql/#sec-Type-Kinds.Non-Null

Right now this library provides the names "List" and "Non-Null" for these types, respectively:

https://github.com/rmosolgo/graphql-ruby/blob/e9cc6c5790eb492bc288ed77541c1a29f94aa0c5/lib/graphql/list_type.rb#L28-L30
https://github.com/rmosolgo/graphql-ruby/blob/e9cc6c5790eb492bc288ed77541c1a29f94aa0c5/lib/graphql/non_null_type.rb#L38-L40

These names are propagated into introspection responses, which is invalid according to the spec. Instead, these types should always have a name of `null`. I propose that the `ListType` and `NonNullType` classes should return `nil` for their `.name`, which would then propagate valid `null` values to introspection responses.

**Comment by rmosolgo** [comment]
oops! Perhaps implementing `resolve` in [`__Type.name`](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/introspection/type_type.rb#L15) to return nil when [`type.kind.wraps?`](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/type_kinds.rb#L21-L22) would do the trick!

**Comment by jamesmacaulay** [comment]
Does other code rely on `ListType#name` and `NonNullType#name` being present?

**Comment by rmosolgo** [comment]
I don't know 😬  if you want to try removing those instead, if the tests pass, it's good by me

**Comment by jamesmacaulay** [comment]
Gotcha 👍  I'm working on a patch right now.
