### ISSUE TITLE
ISO8601DateTime.coerce_result minor change suggestion

### ISSUE THREAD

**Issue by panSarin** [rmosolgo/graphql-ruby#3523]
**Is your feature request related to a problem? Please describe.**

So far what I know, is that as a Rails community ( and I know that gem is not designed to be used only in Rails ecosystem ), we agreed on using Application timezones when it comes to Application timezone vs Server timezone. (correct me if I am wrong). 

But .coerce_result takes server timezone when we will pass DateTime without timezone. (Time.parse instead of Time.zone.parse).

**Describe the solution you'd like**

So when we will pass f.e. 12:00 from CEST based FE application that is communicating with CEST BE application, graphql-ruby will parse it into server/linux/anyother OS timezone, which for example can be 10:00 UTC. I would prefer it to be saved as 12:00

**Describe alternatives you've considered**

Since graphql is using ruby Time class 
```ruby
(from gem) Time.ancestors
[Time, Comparable, Object, ErrorBubblingHelpers, Minitest::Expectations, 
PP::ObjectMixin, JSON::Ext::Generator::GeneratorMethods::Object, Kernel, BasicObject]
```
instead of Time inherting from DateAndTime::Zones
```ruby
(from rails console) Time.ancestors
=> [Time, DateAndTime::Compatibility, DateAndTime::Calculations, DateAndTime::Zones, Comparable, ActiveSupport::ToJsonWithActiveSupportEncoder, Object, ActiveSupport::Dependencies::Loadable, PP::ObjectMixin, JSON::Ext::Generator::GeneratorMethods::Object, ActiveSupport::Tryable, Kernel, BasicObject]
```
which provides us handling timezones. 

Due to that reason, I am not perfectly sure if that edge case is worth adding another logic / libraries to graphql-ruby gem that would handle that. 

Maybe checking if we have timezone specifiec in our application ( which doesn't have to be rails ) is specified and then adding it to a DateTime string that was received, and then parsing it would be a solution. 

**Additional context**

If not, I will be just happy to add some PR to some documentation/wiki part about that so noone else will have to do the same research i just did :)

https://graphql-ruby.org/api-doc/1.12.12/GraphQL/Types/ISO8601DateTime.html#coerce_input-class_method - quick not there maybe would be useful, or maybe it is fine as it is :)

**Comment by rmosolgo** [comment]
Hi! Sorry for the slow response on this. I'd recommend a custom scalar for this. That way, you can use whatever logic you need for your application behavior. For example

```ruby 
# app/graphql/types/date_time.rb
class Types::DateTime < GraphQL::Schema::Scalar 
  def self.coerce_input(context, input_s)
    Time.zone.parse(input_s)
  end 
  
  def self.coerce_result(context, result_datetime)
    result_datetime.to_s  # <= your string format here
  end 
end 
```

Then, use `Types::DateTime` instead of the one from GraphQL-Ruby. Let me know if you have any trouble with this approach!
