### ISSUE TITLE
QueryAnalyzers: class or instance?

### ISSUE THREAD

**Issue by aviscasillas** [rmosolgo/graphql-ruby#353]
Hi guys!

I've just started playing with QueryAnalyzers since I've found them in the guide as a good option to validate permissions.

Following the documentation [here](https://github.com/rmosolgo/graphql-ruby/blob/master/guides/queries/authorization.md) run into a small issue.

The `MyQueryAnalyzer` example defines a class with instance methods:
```ruby
class MyQueryAnalyzer
  # Called before the visit.
  # Returns the initial value for `memo`
  def initial_value(query)
  end

  # This is like the `reduce` callback.
  # The return value is passed to the next call as `memo`
  def call(memo, visit_type, irep_node)
  end

  # Called when we're done the whole visit.
  # The return value may be a GraphQL::AnalysisError (or an array of them).
  # Or, you can use this hook to write to a log, etc
  def final_value(memo)
  end
end
```
While the example to set up it in the schema uses the class itself:
```ruby
MySchema = GraphQL::Schema.define do
  query_analyzer MyQueryAnalyzer
end
```

My first thought was that the `query_anlyzer` was internally creating an instance, but this setup didn't worked at first time. So, I've got it working by making the QueryAnalyzer methods as class methods.

I'm not sure if it's an issue or I missed something. 
In case of an issue, what do you think we coulde fix here... documentation? or query_analyzer to make it create an instance of the analyzer? (I personally like the way described in the documentation, so I would make a fix in the query_analyzer to create the instance internally).

**Comment by rmosolgo** [comment]
It's a bug in the documentation! Thanks for reporting this. I pushed a fix in 3d50397

It should be 

```ruby
MySchema = GraphQL::Schema.define do
  query_analyzer MyQueryAnalyzer.new
end
```

I don't want to to create an instance internally because I want to leave that space open for parameterizing analyzers. For example `GraphQL::Query` creates instances based on schema configuration: 

https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/query.rb#L38-L43
