### ISSUE TITLE
Ability to change encryption cypher used by GraphQL::Pro::Encoder

### ISSUE THREAD

**Issue by joelwarrington-jobber** [rmosolgo/graphql-ruby#3531]
**Is your feature request related to a problem? Please describe.**

Would like for the ability to specify a different cypher than the default key-based encryption using the `aes-128-gcm` cypher.

**Describe the solution you'd like**

Ability to specify a either class/method to encrypt or change which cypher is used, similar to how the encryptor is defined.

```ruby
MyURLSafeEncoder = GraphQL::Pro::Encoder.define do
  cypher CYPHER_HERE
  encoder URLSafeEncoder
end
```

or

```ruby
MyURLSafeEncoder = GraphQL::Pro::Encoder.define do
  encryptor METHOD_WHICH_ENCRYPTS_HERE
  encoder URLSafeEncoder
end
```

**Describe alternatives you've considered**

No alternatives have been considered, other than defining our own type and using a different gem to encrypt.

**Additional context**

Wanting to use `AES-256-GCM` cypher as opposed to `AES-128-GCM`, but I could see others wanting to use an entirely different cypher.

**Comment by joelwarrington-jobber** [comment]
We have found the following approach by doing the following:

```ruby
  EncryptedEncoder = GraphQL::Pro::Encoder.define do
    cipher "AES-256-GCM"
    key("\x82\xBD\xF7\xA1i\xD9\xE6>1\x91\x17\x90\x89\xD0\x9B\x867\xC7%dhm\aW\xB31\x80\xBE\xBC\xEE\t\xA1")
  end
```

Is this considered a supported approach? Maybe we could get more documentation on this?

**Comment by rmosolgo** [comment]
Hi! Sorry for the slow response. I was AFK last week and checking my email, but not my github notifications 😅 . 

Yes, this is a supported approach! If you check the source, you'll find that that string is passed to `OpenSSL::Cipher.new(...)`, so anything supported by that Ruby standard library component will work there. I'll update the docs soon and follow up here. Sorry for the hangup!

**Comment by joelwarrington-jobber** [comment]
Awesome, thank you! I'm going to close this issue.
