### ISSUE TITLE
[Help/Explain] Why does it happen with queries?

### ISSUE THREAD

**Issue by xxSkyy** [rmosolgo/graphql-ruby#3532]
Hey
I've got question about why does one thing happen doing queries with arguments
Having this query
```ruby
    field :items,
          [Types::ItemType],
          null: false,
          description: 'Returns a list of items in the martian library'
    def items
      Item.all
    end
```
With of course properly made type everything works well, but when doing it with argument
```ruby
    field :item,
          [Types::ItemType],
          null: false,
          description: 'Returns one item found by id' do
      argument :id, ID, required: true
    end


    def item(id:)
      Item.find(id)
    end
```

it gives error

`SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data`

and in console
```tarted POST "/graphql" for 127.0.0.1 at 2021-06-18 04:40:10 +0200
Processing by GraphqlController#execute as */*
  Parameters: {"query"=>"{\n  item(id: 3){\n    name\n  }\n}\n", "variables"=>nil, "graphql"=>{"query"=>"{\n  item(id: 3){\n    name\n  }\n}\n", "variables"=>nil}}
  Item Load (1.1ms)  SELECT "items".* FROM "items" WHERE "items"."id" = $1 LIMIT $2  [["id", 3], ["LIMIT", 1]]
  ↳ app/graphql/types/query_type.rb:85:in `item'
No template found for GraphqlController#execute, rendering head :no_content
Completed 204 No Content in 40ms (ActiveRecord: 22.9ms | Allocations: 5809)
```

When I'll remove square brackets from type so code looks like that
```ruby
    field :item,
          Types::ItemType,
          null: false,
          description: 'Returns one item found by id' do
      argument :id, ID, required: true
    end


    def item(id:)
      Item.find(id)
    end
```

it works fine, why are those square brackets on type though? is it nessessary for not argument queries or can I stop using it? can someone explain?

**Comment by acoffman** [comment]
The square brackets mean you're returning a `List`of whatever type is inside the brackets. 

In your first example, `Item.all` will return an ActiveRecord relation which can be turned into a list of `Items`. In your second example you are using `Item.find` which will return a single item, not a collection, and thus it can't be turned into a GraphQL list. When you remove the square brackets you change the type of the field to be a singular `Item` and thus it works with `Item.find`.

**Comment by xxSkyy** [comment]
Oh that makes it fully clear, thank you!
