### ISSUE TITLE
Is there a way to access arbitrary field keys at runtime?

### ISSUE THREAD

**Issue by dudo** [rmosolgo/graphql-ruby#3534]
**Describe the solution you'd like**

I'm trying to add some information to the `execute.graphql` trace that's emitted to DataDog. I'm trying to wrap it, actually... so that I have a `business.feature` wrapping the `execute.graphql` span. I'd like to make this as easy as possible for folks implementing it, so I'm thinking of adding an option of some sort to the `field` definition, so that when the code gets executed, a new span is created. 

```ruby
module Types
  class Query < Types::BaseObject
    field :things, field: Queries::Things, feature: "Awesome Thing"
    ...
```

The `feature` key here is arbitrary. I feel like I just need access to the arguments of `field` during `GraphQL::Tracing::DataDogTracing`. I'd like to do something like...

```ruby
def platform_trace(platform_key, key, data, &blk)
  if platform_key == 'execute.graphql' && data[:context][:feature]
    Datadog.tracer.trace('business.feature',  { resource: data[:context][:feature] }) do |span|
      # Awesome Thing
      super
    end
  end
end
```

That's obviously contrived... but something like that.

**Describe alternatives you've considered**

I've tried subclassing the above platform call, but I don't seem to have access to anything within the field definition when `platform_trace(platform_key, key, data, &blk)` is called. 

I looked into how `resolve` is called, in runtime.rb - hoping to use prepend to wrap the method. That ended nowhere, as I don't have access to _that_ resolve method without monkey patching the library.

**Comment by rmosolgo** [comment]
Hi, Thanks for the detailed writeup. I can't _think_ of an easy way to add arbitrary datadog keys to the existing tracer, but I can make a few suggestions: 

1. If Datadog has a way to get the current span, maybe you could access it and add keys to it. If that works, you could generalize it with a field extension (https://graphql-ruby.org/type_definitions/field_extensions.html)
2. If you see a way to improve graphql-ruby's datadog tracer, I'd welcome a PR for it! The main consideration from my perspective is performance: we'd need an approach that adds little-to-no overhead for anyone who's _not_ using custom tags, since it's a hot codepath.

I'd be happy to help with either of those if you investigate it and run into trouble!

**Comment by dudo** [comment]
Hey Rob! I don't need to change the built in tracer, per se... I just want a way to wrap it with a new one. Great callout on the field extension! Here's what I have so far:

```ruby
module Extensions
  class Feature < GraphQL::Schema::FieldExtension
    def resolve(object:, arguments:, **rest)
      tags = options[:tags] || {}
      trace_options = {
        service: options[:service],
        resource: options[:name],
        tags: tags.merge(original_service: options[:service] && ENV['DD_SERVICE']).compact,
      }.compact
      span = Datadog.tracer.trace('feature.execution', trace_options)
      Datadog::Analytics.set_measured(span)
      span.start

      yield(object, arguments, span)
    end

    def after_resolve(value:, memo:, **rest)
      memo.finish

      value
    end
  end
end
```

`.trace` also takes a block, which I tried wrapping around `yield`. Both implementations "work" in that a span is reported! I don't seem to understand what I'm measuring, though, lol. What I'm trying to get to here is a wrapper around the execution itself, so that we have a consistent span representing the work being done. This field extension executes _very_ quickly.

**Example using span.start / finish across both methods** (I was experimenting with parent methods, too):

![image](https://user-images.githubusercontent.com/2963800/123700814-d1297500-d815-11eb-8e00-6120e3588a8c.png)

**Example using resolve:**

```ruby
def resolve(object:, arguments:, **rest)
  ...
  Datadog.tracer.trace('feature.execution', trace_options) do |span|
    Datadog::Analytics.set_measured(span)

    yield(object, arguments)
  end
end
```

![image](https://user-images.githubusercontent.com/2963800/123700621-90c9f700-d815-11eb-9083-8e818222609f.png)

**Example using after_resolve** (this didn't actually work, as it swallowed an error):

```ruby
def after_resolve(value:, memo:, **rest)
  ...
  Datadog.tracer.trace('feature.execution', trace_options) do |span|
    Datadog::Analytics.set_measured(span)

    value
  end
end
```

![image](https://user-images.githubusercontent.com/2963800/123700737-b525d380-d815-11eb-9c84-ed9bc81991db.png)

Hopefully that explains what I'm after a bit better... I'm thinking of wrapping the controller action with this new trace... then using the field extension to find the appropriate parent span, and tag it appropriately - unless you can think of something else "within" your gem that would expose the start/finish time of the field's execution, and wrap the block appropriately.

Thanks for your help!

**Comment by rmosolgo** [comment]
The field extension would wrap the resolution of the _single_ field that uses it. So if the selection has any _child_ fields, those wouldn't be wrapped. Other parts of execution, like authorization, resolving union or interface types, or runtime overhead, wouldn't be wrapped by those spans either. 

If you're looking for a span that covers the whole query, then doing it in the controller (or a custom tracer, https://graphql-ruby.org/queries/tracing.html), would be a better choice :+1:

**Comment by dudo** [comment]
Wrapped the controller, and just looked for the correct span during execution:

```ruby
module Extensions
  class Feature < GraphQL::Schema::FieldExtension
    def resolve(object:, arguments:, **rest)
      if feature_span
        feature_span.resource = options[:name]
        feature_span.service = options[:service] if options[:service]
        feature_span.set_tags(options[:tags]) if options[:tags]
        feature_span.set_tag(:original_service, ENV['DD_SERVICE']) if options[:service]
      end

      yield(object, arguments)
    end

    private

    def feature_span
      span = Datadog.tracer.active_span
      while span
        break span if span.name == 'feature.execution'
        span = span.parent
      end
    end
  end
end
```

Returns exactly what I'm after!
![image](https://user-images.githubusercontent.com/2963800/123704910-0edccc80-d81b-11eb-84d3-762ae3ae64c5.png)

Thanks again!

**Comment by dudo** [comment]
Actually... thinking about this some more - I don't know if wrapping the controller is going to work. It'd be possible to set the field extension on nested fields, and 1 would override the other, no? 

Interestingly, while testing this, I received 

```
GraphQL::Define::NoDefinitionError: GraphQL::Field can't define 'extension'
```

Not sure if that protects me from defining multiple extensions, or what... lemme know if you have any more insight, @rmosolgo =)

**Comment by dudo** [comment]
Bleh... that was a different issue with the old `define` format - sorry.

**Comment by dudo** [comment]
For anyone else that stumbles across this - If you have nested extensions, and want to know which field will take precedence.

- `resolve` will give you the most granular, deeper nested field
- `after_resolve` will give you the outermost, top level field
