### ISSUE TITLE
Protected/Authorized fields

### ISSUE THREAD

**Issue by no-itsbackpack** [rmosolgo/graphql-ruby#3544]
👋🏾 @rmosolgo quick question, I was wondering if graphql-ruby supports authenticating or authorizing specific fields instead of the whole type object? 

I read through the docs but did not find any mention of this, could it be achieved by just subclassing the field class and checking for a key in the context. eg. Checking if context has :current_user and raising an error if it doesn't 🤔. I'd love your thoughts on this.

ps: super excited about taking the Dataloader out for a spin

**Comment by rmosolgo** [comment]
👋 😁  Hi! Yep, it's possible. On your custom field class, you can implement `def authorized?(object, arguments, context)` and it will be called before instances of that field are resolved. (It's mentioned here, but no example code: https://graphql-ruby.org/authorization/authorization.html#adding-authorization-checks.)

There's a contrived example in the tests: 

https://github.com/rmosolgo/graphql-ruby/blob/7516851a3f01595bf276c87ebd22d5c20fc17925/spec/graphql/authorization_spec.rb#L60-L67

But hopefully that gives a hint to how it works... If you give it a try and run into trouble, please let me know!

**Comment by no-itsbackpack** [comment]
Thanks @rmosolgo ❤️ ❤️
