### ISSUE TITLE
Doc Improve: Add demo code for Field visible

### ISSUE THREAD

**Issue by 1c7** [rmosolgo/graphql-ruby#3551]
https://graphql-ruby.org/authorization/visibility.html
![image](https://user-images.githubusercontent.com/1804755/125277715-61060d80-e344-11eb-8f88-24d814aca9cc.png)

**Comment by 1c7** [comment]
https://www.rubydoc.info/github/rmosolgo/graphql-ruby/GraphQL/Field
I am not sure how to add instance method for `visible?`

**Comment by 1c7** [comment]
## I am trying to hide some field in query type
![image](https://user-images.githubusercontent.com/1804755/125278007-c35f0e00-e344-11eb-8f8a-9263febac71a.png)

**Comment by 1c7** [comment]
only `context[:current_user].has_role?(:admin) == true` can see these fields

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/125278153-f30e1600-e344-11eb-95ba-d2dbf5f88c20.png)

**Comment by 1c7** [comment]
https://imaharu.github.io/graphql-ruby-doc-ja/type_definitions/extensions.html

![image](https://user-images.githubusercontent.com/1804755/125278530-716ab800-e345-11eb-9888-36b64e782d58.png)
![image](https://user-images.githubusercontent.com/1804755/125278602-847d8800-e345-11eb-84e6-5390261f5e99.png)

**Comment by 1c7** [comment]
# Mind to provider some example in the doc?

**Comment by rmosolgo** [comment]
👋  Sorry for the trouble! I added some examples for this in https://github.com/rmosolgo/graphql-ruby/commit/c2395b3887b87066ff9882fb8df126c89f4104b9 and 7a7796a52. Hmmm... it looks like the [site generator job](https://github.com/rmosolgo/graphql-ruby/runs/3047153607?check_suite_focus=true) is broken, so I'll have to fix it to make my changes show up on graphql-ruby.org. 

Anyways, I hope those examples help! Let me know if I can help with anything else.

**Comment by 1c7** [comment]
@rmosolgo  Thank you very much!
