### ISSUE TITLE
Union types don't resolve with lists

### ISSUE THREAD

**Issue by nickmealey** [rmosolgo/graphql-ruby#3552]
**Describe the bug**

I could be missing something obvious here, but it seems as though Union types don't resolve each object when used in a list, but only seems to resolve the first item in the list and used for any other items later down the line.

**Versions**

`graphql` version: 1.12.8
`rails`: 6.1.3.1

**GraphQL schema**

```ruby
module Types
  class ColorType < BaseObject
    field :hex, String, null: false
  end

  class CloudFileType < BaseObject
    field :provider, CloudProvider, null: false
    field :provider_id, String, null: false
    field :public_url, String, null: false
    field :type, String, null: false
    field :bytes, Integer, null: false
  end

  class BackdropType < BaseUnion
    possible_types Types::ColorType, Types::CloudFileType

    def self.resolve_type(object, _context)
      puts "Resolving type..." # This only gets called once, but there's two objects
      if object.image.present?
        Types::CloudFileType
      else
        Types::ColorType
      end
    end
  end

  class PhotoType < BaseNode
    field :backdrops, [BackdropType], null: true
  end

  class QueryType < Types::BaseObject
    field :photos ...
  end
end
```

**GraphQL query**

Example GraphQL query and response

```graphql
query {
  photos {
    backdrops {
      ...on Color {
         hex
      }
      ...on CloudFile {
        publicUrl
        providerId
      }
    }
  }
}
```

```json
{
  "data": {
    "photos": {
      "backdrops": [
         { "hex": "#FF0000" },
         { "publicUrl": "https://....", "providerId": 43958320 }
       ]
    }
  }
}
```

**Steps to reproduce**

Run this query, providing multiple backdrops.

**Expected behavior**

The `resolve_type` method should be called for each object (under backdrops) in the list.

**Actual behavior**
`resolve_type` is only being called once, and any items after the first are used for the type. In this case, the second item in the list should be a `CloudFileType` but instead it is returned as a `ColorType`. Because of this, we receive an error saying that you can't provide a null value for a non-nullable field (in this case `backdrop.hex` is null for the second one).

**Comment by nickmealey** [comment]
Looking more into this, it happens the same for me when using outside the context of a list as well.
```ruby
module Types
  class PhotoType < BaseNode
    field :backdrop1, BackdropType, null: true
    field :backdrop2, BackdropType, null: true
  end
end
```

```json
{
  "data": {
    "photos": {
      "backdrop1": { "hex": "#FF0000" },
      "backdrop2": { "publicUrl": "https://....", "providerId": 43958320 }
    }
  }
}
```

In this case as well, `resolve_type` is only called once, and `backdrop2` is considered a `ColorType`.

**Comment by rmosolgo** [comment]
Hi! Thanks for the detailed report and sorry for the trouble. I wrote up a little replication script: 

<details>
<summary>Union type list test</summary>

<p>

```ruby
require "bundler/inline"

gemfile do
  gem "graphql", "1.12.8"
end


class ColorType < GraphQL::Schema::Object
  field :hex, String, null: false
end

class CloudFileType < GraphQL::Schema::Object
  field :public_url, String, null: false
end

class BackdropType < GraphQL::Schema::Union
  possible_types ColorType, CloudFileType

  def self.resolve_type(object, _context)
    puts "Resolving type for #{object}"
    if object.public_url
      CloudFileType
    else
      ColorType
    end
  end
end

class QueryType < GraphQL::Schema::Object
  field :backdrops, [BackdropType], null: true

  def backdrops
    [
      OpenStruct.new(public_url: "https://google.com"),
      OpenStruct.new(hex: "#faff0f"),
    ]
  end
end


class Schema < GraphQL::Schema
  query(QueryType)
end


pp Schema.execute(<<-GRAPHQL).to_h
{
  backdrops {
    ... on Color { hex }
    ... on CloudFile { publicUrl }
  }
}
GRAPHQL

```
</p>
</details>

But for me, it worked as expected: 

```
$ ruby union_list_test.rb
Resolving type for #<OpenStruct public_url="https://google.com">
Resolving type for #<OpenStruct hex="#faff0f">
{"data"=>
  {"backdrops"=>[{"publicUrl"=>"https://google.com"}, {"hex"=>"#faff0f"}]}}
```


🤔 So, what could it be? 

The only thing that came to mind is that GraphQL assumes that each Ruby object will resolve to one object type per interface or union type: 

https://github.com/rmosolgo/graphql-ruby/blob/7a7796a526be9ccebdcd205d8ed917b2f2cab482/lib/graphql/query.rb#L321-L335

(It caches the result of `resolve_type(abstract_type, object)` for the life of the query.) 

Is it possible that that either: 

- The items in the list are actually the _same_ object? 
- Or, the items in the list have implemented some equality methods (`.eql?`, `.hash`) that would make them collide in a Hash? 

To debug further, could you please share some information about how the field is resolved? For example, the field method, resolver, and/or application code that provides values for `backdrops`.

**Comment by nickmealey** [comment]
Thanks for the quick reply! I'll do some more digging and see what I can come up with.

**Comment by nickmealey** [comment]
@rmosolgo bah, found the source of the issue! Our `Backdrop` class implements a suggestion provided by MongoID to [remove the ID field](https://docs.mongodb.com/mongoid/current/tutorials/mongoid-relations/#omitting-id-fields), since we don't need ID fields for this embedded document.

Turns out you were on to something, MongoID compares objects [by there ID](https://www.rubydoc.info/github/mongoid/mongoid/Mongoid%2FEquality:==), thus any instance of `Backdrop` will always equal each other. In this case we'll likely overwrite the equality method or just settle for using an ID field after all. Thanks @rmosolgo  for looking into this, I was a real puzzler! Closing this issue, but hopefully documenting this helps others having a similar issue.

```ruby
class Backdrop
  include Mongoid::Document
  field :_id, type: Object
  field :color, type: String
end

Backdrop.new(color: "red") == Backdrop.new(color: "blue") # => true
```
