### ISSUE TITLE
Enums (or fields) can't start with an integer value in the string

### ISSUE THREAD

**Issue by TomasBarry** [rmosolgo/graphql-ruby#3554]
**Describe the bug**

Trying to create an enum for '125' fails with the following message:

```
Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but '125' does not
```

**Versions**

`graphql` version: 1.12.12
`rails` (or other framework): Rails 6.0.3.7

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok).
Are you using [interpreter](https://graphql-ruby.org/queries/interpreter.html)? Any custom instrumentation, etc?

```ruby
module Types
  module Enums
    class TheEnum < Types::BaseEnum
      value '125'
    end
  end
end


module Types
  class TheType < Types::BaseObject
    field :thing, Types::Enums::TheEnum, null: false

    def thing
      '125'
    end
  end
end
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
query {
  theType {
    thing
  }
}
```

```json
{
  "error": {
    "message": "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but '125' does not",
    "backtrace": [
      ...
    ]
  }
}
```

**Expected behavior**

All strings should be valid - I can't find in the GraphQL spec, at least not for enums, where this Regex is specified (apologies if it is, this issue isn't for this project if it is).

**Additional context**

If this regex is specified for enums in the GraphQL spec then this is a non-issue but I couldn't find it. I suspect it might be a requirement for fields but the `NameValidator` (https://github.com/rmosolgo/graphql-ruby/blob/bace1e4027900fc8779a5c2fd393ff6456046cea/lib/graphql/name_validator.rb) seems to be across enums and fields.

**Comment by rmosolgo** [comment]
Hi! Thanks for the detailed report. 

The GraphQL spec defines a "Name" which begins with either a letter or an underscore, then may contain any number of letters, digits or underscores: 

>  - Name:
>      - NameStart NameContinue _(list,opt)_ [lookahead ∉ NameContinue)]
> - NameStart:
>     - Letter
>     - _
> - NameContinue:
>     - Letter
>     - Digit
>     - _


(https://spec.graphql.org/draft/#Name)


Both Enum values and field names are "Names" by this spec (https://spec.graphql.org/draft/#EnumValue, https://spec.graphql.org/draft/#sec-Language.Fields)

So, in light of this, fields and enums _may not_ begin with a number (and they must begin with a letter or `_`). Hope this clarifies that regexp a bit!

**Comment by TomasBarry** [comment]
@rmosolgo, thank you - I thought that must be the case but I just couldn't find the definition.

Thanks for confirming.
