### ISSUE TITLE
Access to underlying objects

### ISSUE THREAD

**Issue by 23tux** [rmosolgo/graphql-ruby#3556]
**Is your feature request related to a problem? Please describe.**

I know that this is a very specific use case, but maybe somebody can give me some hints:

We rely heavily on using graphql-ruby from within ruby, e.g. we use the same endpoints in our Rails app that our customers use from outside. This way, if we fix bugs, improve performance... in our GraphQL API, it has a positive effect on multiple sides.

But sometimes, we need a little bit more than a plain response hash, e.g. the underlying ActiveRecord objects for legacy interfaces. In conjunction with graphql-batch you get very nice, eager loaded objects.

So I was looking around for a way to access the underlying active record objects, from which the response was constructed.

One solution I found, but a really hacky one, is to remember an object by its `#object_id` inside the context. After the response is returned, I iterate over the hash and try to replace the values by it's corresponding memory object:

```
# ArticleType
field :_object_id, String, null: false

def _object_id
  object.object_id.to_s.tap do |object_id|
    (context[:object_ids] ||= {})[object_id] = object
  end
end

# response
{ "data" => { "article" => { "_object_id" => "120380" } } }

_object_id = response["data"]["article"]["_object_id"]
context[:object_ids][_object_id]
=> #<ArticleType:0x000056181058b898>
```

I'm not sure about the performance impact, or if this could cause any other problems I can't think of right now.

**Describe the solution you'd like**

Some kind of hook, where I can replace / modify the actual object before a response is constructed.

**Describe alternatives you've considered**

I tried using a field extension and it's `#after_resolve` method, but it seems like this is too early in the chain.

**Comment by rmosolgo** [comment]
Hi! How interesting 😅  But that's life.

I don't see any particular problems with this approach. I _like_ how requesting the `_object_id` causes the cache to be created and populated. 

If you wanted another approach, you could probably use `def initialize` to do something similar: 

```ruby 
class Types::BaseObject < GraphQL::Schema::Object 
  def initialize(obj, ctx)
    super 
    ctx[:object_ids][obj.object_id.to_s] = obj 
  end 
end 
```

I think that would do the same thing, even without selecting `_object_id`. If you give that approach a try and run into trouble, let me know. I'd be happy to brainstorm other options, too!

**Comment by 23tux** [comment]
Thanks for the quick response! If I don't select anything, the parser gives me an error about the missing selection. So I think I have to select at least one field, but with your approach, it doesn't matter which one.

Can you think of a more elegant way, to inject the actual objects into the hash? I can iterate over them, and everytime I find the key `_object_id` I replace the parent objects with the object from memory:

```
# original response
{ "data" => { "article" => { "_object_id" => "120380" } } }

# injected response
{ "data" => { "article" => #<ArticleType:0x000056181058b898> } }
```

It kinda works, but I find it ugly as hell 🙈

**Comment by rmosolgo** [comment]
Yes, there _is_ a way to do that, there's a method called `raw_value`:

https://github.com/rmosolgo/graphql-ruby/blob/5ab3e5e96a95a52d8c2d353346132fcac188fa3f/lib/graphql/schema/object.rb#L22-L26

You could use it in your resolver, for example: 

```ruby 
field :article, Types::Article, null: true 

def article 
  article = Article.find(...) # somehow find the article
  raw_value(article)
end 
```

That will insert the `article` value into GraphQL-Ruby's final result hash.

However, if you use `raw_value`, then GraphQL-Ruby will _ignore_ any selections on `article`. (`raw_value` was added for caching purposes -- it's _meant_ for inserting an already-prepared GraphQL result.) So, if you _also_ want to select fields, then `raw_value` won't work. 

But maybe you could add something like 

```ruby 
class ArticleType < BaseObject
  field :raw_object, Integer, null: false # not actually an integer, it uses `raw_value`
  
  def raw_object
    raw_value(object)
  end 
end 
```

Then you could use it like:

```
{
  article { rawObject }
}
```

It might be worth a try!

**Comment by 23tux** [comment]
Oooohh, thats really cool! (you just have a solution for everything! ❤️ )

What do you think, could this work with a directive? I just tried it this way:
```
{
  article { field1 field2 } @rawObject
}
```

```
class RawObject < GraphQL::Schema::Directive
  locations(GraphQL::Schema::Directive::FIELD)

  def self.resolve(_obj, args, _ctx)
    GraphQL::Execution::Interpreter::RawValue.new(yield)
  end
end
```

But it doesn't seem to work. However, I'd really like the syntax using a directive, as I could keep existing selections (`field1 field2`), and STILL be able to decide when I want those raw memory object.

Any chance to get this to work?

**Comment by rmosolgo** [comment]
Oh! That's a really cool idea. I _think_ `yield` will return the GraphQL-ready result hash. So maybe you want something like: 

```ruby 
def self.resolve(obj, args, ctx)
  result = yield 
  result["rawObject"] = object 
  result 
end 
```

It seems like it _should_ work, something like that (maybe you need `RawValue.new(...)` like you have above), but I'm not exactly sure. If you try it out and run into problems, please let me know what kind of problems you encounter!

**Comment by 23tux** [comment]
Hmmm... I'm not sure if this works, when using GraphQL Batch, I get

```
[2] pry(ContentGraph::Directives::RawObject)> result["rawObject"] = object
NoMethodError: undefined method `[]=' for #<GraphQL::Execution::Lazy:0x0000557a4ad49238>
```

I'm not sure if I understand this part of the directive correctly. Would it be possible to replace the field itself with the memory object?

**Comment by rmosolgo** [comment]
Oh, sure. If you want to return the raw object _instead of_ the selections, you could do 

```
def self.resolve(obj, args, ctx)
   obj
end 
```

Since it doesn't `yield`, the part of the query tagged by the directive won't be executed. Instead, `obj` will be treated as the result of the tagged field (eg `article` above). I _think_ that'll work, want to give it a try?

**Comment by 23tux** [comment]
Thanks for your answer, and sorry for the ping pong 🙈 

But when I skip the `yield` inside the directive, the whole node is omitted:

Instead of
```
{ "data" => { "article" => #<ArticleType:0x000056181058b898> } }
```

it's just
```
{ "data" => { } }
```

When `yield` is skipped, the method `def article`, which returns either an instance of article, or a GraphQL Batch lazy loader, is never called. So I assume, one must call yield, and somehow inject it into the response by hand? I played around with the objects, but didn't get it to work.

Do you have any other idea I could try?

**Comment by rmosolgo** [comment]
Hmm, I'd sure _like_ it to be the right thing here, I just can't quite figure out how it should work. I think _this_ is where the `self.resolve` call is made:

https://github.com/rmosolgo/graphql-ruby/blob/7a7796a526be9ccebdcd205d8ed917b2f2cab482/lib/graphql/execution/interpreter/runtime.rb#L490

Although the value there is _returned_, I don't think the runtime actually writes that returned value into the response (as you noted above 😖 ). 

Maybe using a field is the best way for now...

**Comment by 23tux** [comment]
Ok, I think using a field is ok for now, even if I'd like the directive approach better.

Thank you so much for your help! 👍
