### ISSUE TITLE
Relation connection with `last` but without `before` yields wrong result

### ISSUE THREAD

**Issue by sjchmiela** [rmosolgo/graphql-ruby#356]
When querying connection field query with arguments `first: 2` yields the same result as `last: 2`.

**Comment by rmosolgo** [comment]
Hmm, I have to check the spec. Here's where the `offset 0` comes from: 

https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/relay/relation_connection.rb#L60-L61

But doing a `count` could be a bad behavior there.

**Comment by sjchmiela** [comment]
Yup, I found reason for this… And yes, I think doing a `count` can be a bad behavior… Maybe a better solution would be handling this case (only `last` set) separately, by eg. reversing the node relation?

**Comment by sjchmiela** [comment]
After consideration and further thinking I think doing a `count` is the only solution I can imagine.

**Comment by sjchmiela** [comment]
Although it's not as performant as it maybe could be… But I think there is no better way to count the offset of the last rows.
https://www.varvet.com/blog/retrieving-the-last-n-ordered-records-with-activerecord/

**Comment by sjchmiela** [comment]
In fact I noticed the library does `count` well… always when accessing `hasNextPage`:

https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/relay/relation_connection.rb#L20
```
      def has_next_page
        !!(first && sliced_nodes.limit(limit + 1).count > limit)
      end
```

If that's so, doing a `count` somewhere else may be not so bad behavior after all.

**Comment by rmosolgo** [comment]
I _think_ that's different because of the `limit`: if your table is a billion rows, it will only count as many as it takes to satisfy the `limit`!

I have been thinking about this bug, there's no other way to fix it so I think soon I will merge your previous PR and add some documentation with a warning!
