### ISSUE TITLE
[PRO] Pundit integration: authorize mutation using argument values

### ISSUE THREAD

**Issue by mmudge** [rmosolgo/graphql-ruby#3569]
Hello,

I would like to authorize a gql mutation based on an argument value using the ruby-gql pundit pro integration. I have two models with a normal `has_many` and `belongs_to` relationship. In my case it is an `Enterprise` `has_many` `Brokerages` and a `Brokerage` `belongs_to` an `Enterprise`. I would like to expose creating a `Brokerage` in our public API but need to authorize that users have the correct permission on the parent `Enterprise` before letting them create a `Brokerage` within the `Enterprise`.

For now my I got similar behavior working [using the ready? method](https://graphql-ruby.org/mutations/mutation_authorization.html#checking-the-user-permissions) although if possible I would like for all our authorization logic to live inside a Pundit Policy class.

Here is some example code of my mutation

```
class CreateBrokerageMutation < BaseMutation
  graphql_name 'CreateBrokerage'

  pundit_role :manager

  class Policy < BaseMutationPolicy
    def manager?
      # would like the logic in #ready? to live here
      viewer.is_a?(Manager)
    end
  end

  def ready?(**args)
    # would like to move this authorization logic into the Policy class above

    enterprise = Enterprise.find(args[:enterprise_id])
    if !context[:current_manager]&.manageable_enterprise_ids&.include?(enterprise&.id)
      raise Schema::AuthorizationError.new('Unauthorized')
    else
      true
    end
  end

  argument :name, String, 'The name of the Brokerage', required: true
  argument :enterprise_id, ID, 'ID of the Enterprise the Brokerage belongs to', required: true

  # Return fields
  field :brokerage, BrokerageType, null: true

  def resolve(**inputs)
    CreateBrokerageResolver.new.call(object, inputs)
  end
end
```

Is there a way to access the mutation arguments inside the policy class? I have tried digging into the mutation object but that doesn't seem correct. Am I missing something obvious? Any help or suggestions would be greatly appreciated. Thanks!

Versions:
ruby - `2.6.6`
rails - `4.2.11.3`
graphql - `1.9.17`
graphql-pro - `1.15.7`

**Comment by rmosolgo** [comment]
Hi! Probably the best way to do this is to attach a `pundit_role: ...` to the argument itself ([doc](https://graphql-ruby.org/authorization/pundit_integration.html#authorizing-arguments)).

Here's a little sketch of how it might work: 

```ruby
require "bundler/inline"

gemfile do
  gem "graphql", "1.12.14"
  gem "graphql-pro", "1.18.0"
  gem "pundit"
end

class Schema < GraphQL::Schema
  class BaseArgument < GraphQL::Schema::Argument
    include GraphQL::Pro::PunditIntegration::ArgumentIntegration
    pundit_role nil
  end

  class BaseMutation < GraphQL::Schema::Mutation
    argument_class BaseArgument
    include GraphQL::Pro::PunditIntegration::MutationIntegration
    pundit_role nil

    def self.pundit_policy_class
      self::Policy
    end
  end

  class CreateBrokerage < BaseMutation
    class Policy
      def initialize(current_user, mutation)
        @current_user = current_user
        @mutation = mutation
      end

      def manager?
        enterprise_id = @mutation.arguments[:enterprise_id]
        if !@current_user.manageable_enterprise_ids.include?(enterprise_id)
          raise GraphQL::ExecutionError.new("Unauthorized (#{enterprise_id.inspect} not in #{@current_user.manageable_enterprise_ids.inspect}")
        else
          true
        end
      end
    end

    argument :name, String, required: true
    argument :enterprise_id, ID, required: true, pundit_role: :manager

    field :message, String, null: false

    def resolve(name:, enterprise_id:)
      { message: "Created #{name} in Enterprise #{enterprise_id}!"}
    end
  end

  class Mutation < GraphQL::Schema::Object
    field :create_brokerage, mutation: CreateBrokerage
  end

  mutation(Mutation)
  query(Mutation) # just because we have to have _something_
end

query_str = "mutation($enterpriseId: ID!) { createBrokerage(name: \"Friends & Co.\", enterpriseId: $enterpriseId) { message } }"
context = { current_user: OpenStruct.new(manageable_enterprise_ids: ["456"])}

pp Schema.execute(query_str, context: context, variables: { enterpriseId: "123" })
#<GraphQL::Query::Result @query=... @to_h={"data"=>{"createBrokerage"=>nil}, "errors"=>[{"message"=>"Unauthorized (\"123\" not in [\"456\"]", "locations"=>[{"line"=>1, "column"=>32}], "path"=>["createBrokerage"]}]}>

pp Schema.execute(query_str, context: context, variables: { enterpriseId: "456" })
#<GraphQL::Query::Result @query=... @to_h={"data"=>{"createBrokerage"=>{"message"=>"Created Friends & Co. in Enterprise 456!"}}}>
```

In that example, `pundit_role: :manager` causes the mutation to check the `manager?` role whenever the `enterpriseId` argument is present (which is _all the time_, since it's required). 

If `enterpriseId` was a GraphQL-style global ID, you could use `loads: Types::Enterprise`, and it would change the signature of what's passed to the policy. Instead of being the `mutation`, it would be the `enterprise` object. But that's not relevant here, unless you decide to use `loads:` later on. 


One thing is, if you want `context[:current_manager]` to be present in the pundit policy, you have a couple of options: 

- Set it as `context[:current_user]` instead (or _also_), that's what the pundit integration uses by default;
- Or, use `mutation.context[:current_manager]` to reference it;
- Or, customize the current user lookup to find `:current_manager` instead of `:current_user` ([doc](https://graphql-ruby.org/authorization/pundit_integration.html#custom-user-lookup))

Ok, I hope that helps! If you get a chance to try it out, let me know what you find.

**Comment by rmosolgo** [comment]
Let me know if there's anything else I can help with on this!

**Comment by Amnesthesia** [comment]
@rmosolgo I'm trying to figure out why setting `pundit_role:` on my arguments never gets to any policy. I tried to override `def authorized?` on my `BaseArgument` and it never even gets there. It authorizes my fields, resolvers, mutations and everything else, but it never authorizes arguments, even if they have `loads: Types::Model`

The example above no longer works either, as you get `RuntimeError: Arguments have not been prepared yet, still waiting for #load_arguments to resolve. (Call `.arguments` later in the code.) (RuntimeError)`
