### ISSUE TITLE
parse.y union_type_definition or union_type_members seems incompatible with working draft spec and 2018 spec

### ISSUE THREAD

**Issue by leehambley** [rmosolgo/graphql-ruby#3571]
**Describe the bug**

Unless I'm misreading something both the June 2018 and the working draft specs from the GraphQL permit definition of a memberless union, but it seems not to work in the `master` version of this gem.

- https://spec.graphql.org/draft/#sec-Unions
- https://spec.graphql.org/June2018/#sec-Unions

![screen shot of section 3.8 of the graphql specs](https://user-images.githubusercontent.com/18952/127215566-697e1074-317f-45c1-b81b-21ab146fa3aa.png)

This seems to suggest that the member list should be optional.

I suggest that maybe this part of [`parser.y`](https://github.com/rmosolgo/graphql-ruby/blob/a518a03b1c90bc47bfb7b6eff2fb840495817ae8/lib/graphql/language/parser.y#L404-L411) should change:

```
union_members:
      name                    { result = [make_node(:TypeName, name: val[0], position_source: val[0])]}
    | union_members PIPE name { val[0] << make_node(:TypeName, name: val[2], position_source: val[2]) }

  union_type_definition:
      description_opt UNION name directives_list_opt EQUALS union_members {
        result = make_node(:UnionTypeDefinition, name: val[2], directives: val[3], types: val[5], description: val[0] || get_description(val[1]), definition_line: val[1].line, position_source: val[0] || val[1])
      }
```

**Versions**

```
commit a518a03b1c90bc47bfb7b6eff2fb840495817ae8 (HEAD -> master, tag: v1.12.14, upstream/master, origin/master, origin/HEAD)
Author: Robert Mosolgo <rmosolgo@github.com>
Date:   Thu Jul 22 10:58:31 2021 -0400

    1.12.14
```

**GraphQL schema**

Essentially trying to include some fragments from the Apollo Federation spec, which seems to rely on two key things which are not supported. (`repeatable` keyword on `@directive`, and unions with no members, which is the bug I'm reporting here)

```
schema {
  query: Query
}
type Query {}
union AnEmptyUnion
type Foo {} # required to get a parser error "on type" rather than unexpected EOF error.
```

**Expected behavior**

Unions with no members should parse successfully.

**Actual behavior**

Parser error something like this:

```
Error:
GraphQL::Language::Parser::.from_definition#test_0001_is able to parse an Apollo Federated schema:
GraphQL::ParseError: Parse error on "type" (TYPE) at [4, 9]
    parser.y:527:in `on_error'
    (eval):3:in `_racc_do_parse_c'
    (eval):3:in `do_parse'
    parser.y:459:in `block in parse_document'
    /home/leeh/code/graphql-ruby/lib/graphql/tracing.rb:91:in `trace'
    parser.y:455:in `parse_document'
    parser.y:469:in `parse'
    /home/leeh/code/graphql-ruby/lib/graphql/schema/build_from_definition.rb:15:in `from_definition'
    /home/leeh/code/graphql-ruby/lib/graphql/schema.rb:788:in `from_definition'
    /home/leeh/code/graphql-ruby/spec/graphql/language/parser_spec.rb:219:in `block (3 levels) in <top (required)>'

Something went wrong
2.6.0/gems/graphql-1.9.17/lib/graphql/subscriptions/instrumentation.rb:34:in `after_query'
… don't hesitate to include all the rows here: they will be collapsed
```

</details>

**Additional context**

I'm trying to add support for the Apollo Federated Schema to the `GraphQL::Schema.from_definition` codepath, fully aware that it's better supported in the Ruby DSL with the accompanying Gem which handles this.

**Comment by swalkinshaw** [comment]
The spec also says a union type must have at least one member in the validation section

> A Union type must include one or more unique member types.

https://spec.graphql.org/draft/#sel-HAHdfFBABAB6Bw3R

**Comment by leehambley** [comment]
Thanks for that @swalkinshaw - I wonder why they didn't just define that requirement in the grammar, rather than having ambiguous grammar and then additional rules on top?!

I suppose you'd prefer to close this, then?

**Comment by swalkinshaw** [comment]
Agreed it's confusing and has some up before for object types: https://github.com/rmosolgo/graphql-ruby/issues/2549

I think this is the main spec issue about empty objects: https://github.com/graphql/graphql-spec/issues/568

**Comment by leehambley** [comment]
Thanks so much for the context @swalkinshaw 

We're still stumbling around trying to find out the _exact_ IDL/SDL requirements for the Apollo Federated schema, so far we know it's the memberless union (although I'll validate that with our consumer team tomorrow), and the `repeatable` keyword on directives which doesn't seem to be supported in this gem yet.

Would you consider a patch for the draft spec `repeatable` word, or would it be better for us to plan to maintain a fork targeting the draft spec? (and, probably you plan to accept nothing that would allow memberless union types?)

**Comment by rmosolgo** [comment]
Hey @leehambley, yes, I'd be happy to support `repeatable` :+1:
