### ISSUE TITLE
Deprecation warning GraphQL::ExecutionError class

### ISSUE THREAD

**Issue by nekogami** [rmosolgo/graphql-ruby#3573]
**Describe the bug**

Mix between positional and kwargs argument are supposed to be deprecated, but I just noticed that GraphQL::ExecutionError#initialize still contains both 

```ruby
    def initialize(message, ast_node: nil, options: nil, extensions: nil)
```

Wouldn't that be an issue starting ruby 3.0 ?

**Versions**

`graphql` version: 1.12.13
`rails` (or other framework): 6.0.3.7
other applicable versions (`graphql-batch`, etc)

**GraphQL schema**

Are you using [interpreter](https://graphql-ruby.org/queries/interpreter.html)? Any custom instrumentation, etc?
Yes

**Comment by rmosolgo** [comment]
I _expect_ the code above to work fine. If it's emitting a warning, please share it! But I think the Ruby 3 arguments change is a little different: https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/

Having positional arguments and keyword arguments in the _method signature_ is OK, but what's _not_ OK is passing keyword arguments as a single positional argument. 

If you find that it's emitting a warning, please share it, and we'll see how it should be addressed!

**Comment by nekogami** [comment]
Yes right, I misunderstood the meaning, sorry for that.
