### ISSUE TITLE
Define a convention/idiomatic way for query definitions, and document it

### ISSUE THREAD

**Issue by camiloforero** [rmosolgo/graphql-ruby#3579]
Right now, there is a well documented way to structure mutations within a project: Create a `Mutation` class with arguments, fields and a resolver, and hook it up with `Types::MutationType`. It's all explained in its own section of the docs, here: https://graphql-ruby.org/mutations/mutation_classes.html

However, there is no such thing for queries, devs are left to figure it out by themselves, or search in google/StackOverflow.

My proposal is then to define what the best pattern for structuring queries is and document it, so people start using it. 
Also, as I'm working right now in generators, the query generators could be made using whichever pattern we decide is the best one

The patterns I know of are:
1. **Everything inside the root `QueryType`**: All fields and resolver methods are there, so there is a single, very large, `Types::QueryType`
2. **Namespaced query interfaces**: Classes with names like `user_query_type` are defined, which inherit from GraphQL Interfaces. Fields and resolver methods go into these interfaces, and these interfaces are implemented in `Types::QueryType`
3. **One resolver per query**: Similar to the current structure for mutations, a whole `Resolver` class is created for each query, and instead of having resolver methods in the root query type, each field references its resolver.

Right now I use method 2, **namespaced queries**, because
- It allows me to distribute my code over several files, organized by namespace/functionality, instead of having one very large and unwieldy file, as it's the case with the first option
- It doesn't require as much boilerplate as the third option, and queries are most of the time simpler than mutations, so having several queries in one file is not so bad.

So I'd personally vote for the second, but I want to hear everybody's opinions on this, as whichever standard we set would become the official and documented one.

**Comment by rmosolgo** [comment]
Thanks for sharing what worked for you! I don't have plans to work further on this so I'm closing it out.
