### ISSUE TITLE
Policy scoping and authorization with Pundit

### ISSUE THREAD

**Issue by joshio1** [rmosolgo/graphql-ruby#3580]
Hi,

I'm having a little trouble in understanding how policy scoping and authorization is supposed to work with the Pundit gem. We also have the GraphQL Pro subscription.

We have objects defined like this:

```

module Types::Objects
  class MovieType < Types::BaseObject
    pundit_role :show

    field :id, Int, null: false
    field :theatres, [Types::Objects::TheatreType], null: false
    field :producer, Types::Objects::ProducerType, null: false
  end
end 

module Types::Objects
  class TheatreType < Types::BaseObject
    pundit_role :show

    field :id, Int, null: false
    ... other fields ...
  end
end 

module Types::Objects
  class ProducerType < Types::BaseObject
    pundit_role :show

    field :id, Int, null: false
    ... other fields ..
  end
end 

```

and these are the two ways this movie type can be fetched, as defined in the `query_type.rb`:

```

  class QueryType < Types::BaseObject
    # Add `node(id: ID!) and `nodes(ids: [ID!]!)`
    include GraphQL::Types::Relay::HasNodeField
    include GraphQL::Types::Relay::HasNodesField

    pundit_role nil

    # Add root-level fields here.
    # They will be entry points for queries on your schema.
    field :fetch_movie, Objects::MovieType, null: true do
      description 'Find a movie by ID'

      argument :id, Int, required: true
    end

    def fetch_movie(id:)
      Movie.find(id)
    end


    field :fetch_movies, Objects::Movie.connection_type, null: false do
      description 'find all movies for the current user'

      argument :filter, Types::Inputs::FilterableMovieAttributes, required: false
      argument :sort, [Types::Inputs::SortableMovieAttributes], required: false
    end

    def fetch_movies(filter: nil, sort: nil)

      result = Facades::FetchMoviesFacade.call(user: context[:current_user],
                                               filter: filter,
                                               sort: sort)
      result.movies
    end
 end
```

Now, when a  `fetchMovie` is queried from the front-end.
- `MoviePolicy#show?` is called for the single movie object
- `ProducerPolicy#show?` is called for `movie.producer`
- `TheatrePolicy#resolve` is called for the `movie.theatres` list
- `Theatre#show` is called per theatre in the list of `movie.theatres`
 
 When a `fetchMovies` query is requested from the front-end:
 -  `MoviePolicy#resolve` method is called once since scope is true by default.
 -  `MoviePolicy#show?` is called per movie object.
 - `TheatrePolicy#resolve` is called for scoping the `movie.theatres` list per movie object
 - `TheatrePolicy#show?` is called per theatre from `movie.theatres`
- `ProducerPolicy#show?` is called per `movie.producer`
 
I was thinking if we could do with not calling the policy#show every time per entity in case of `fetchMovies`. i.e. this is what I was thinking:

For `fetchMovie`:
- `MoviePolicy#show?` is called for the single movie object

 For `fetchMovies`:
 -  `MoviePolicy#resolve` method is called once since scope is true by default.
 -  `MoviePolicy#index` method is called once.

Now, I know that we can do `scope: false` on the fields so that many of the policy methods are not called. However, even if we do that, the `MoviePolicy#show?` method is still called per movie in the movies list for `fetchMovies`. This is because we need the `pundit_role: show` for the `fetchMovie` type. i.e. the Authorization for the Movie type is governed by how the type is called, i.e. whether it's called via `fetchMovie` or `fetchMovies`.

Please let me know if there's something missing in my understanding about the usage of the gem with Pundit.

**Comment by rmosolgo** [comment]
Hi! Thanks for the detailed writeup. In short, you've understood everything correctly: even when a list objects is scoped, each one is _also_ passed to the object-level authorization hook. There's no built-in way to skip that behavior. You might be able to skip it at the application-level, by setting a flag on any objects authorized by scoping, then checking for that flag in the object's authorized hook. For example:


```ruby
class Scope 
  def resolve
    # add a flag to objects fetched from this AR::Relation
    scope = scope.select("*, 1 as graphql_already_authorized")
    # ...
  end 
end 
```

Then, check for the flag in `def self.authorized?`:

```ruby 
def self.authorized?(object, context)
  # don't re-check if this object came from a validated AR::Relation
  object.attributes[:graphql_already_authorized] || super
end 
```

Want to give that a try? Depending how that works, I can also investigate a library-level approach for this.

**Comment by rmosolgo** [comment]
Let me know if you run into any more trouble with this!
