### ISSUE TITLE
is `authorized?` truly apart of the private API even though it's called out in documentation?

### ISSUE THREAD

**Issue by joelwarrington-jobber** [rmosolgo/graphql-ruby#3583]
https://graphql-ruby.org/api-doc/1.12.14/GraphQL/Schema/Member/BaseDSLMethods.html#authorized%3F-instance_method

![image](https://user-images.githubusercontent.com/80279872/129115692-39ff876b-1f2e-4a80-b76c-30d328a40fd7.png)

It is documented here: https://graphql-ruby.org/authorization/authorization.html

![image](https://user-images.githubusercontent.com/80279872/129115779-48fd6dde-ee49-4ceb-ae4e-2df55009b168.png)

**Comment by rmosolgo** [comment]
Hmm, to clarify, that method should be _implemented_ by the schema, but never called except by graphql-ruby. If you think there's a better way of documenting that expectation, I'd welcome a suggestion or PR!
