### ISSUE TITLE
Allow validators to specify extensions to the error being raised

### ISSUE THREAD

**Issue by cocoahero** [rmosolgo/graphql-ruby#3584]
### Problem Summary
A common issue with handling execution errors client-side is understanding what the actual error was and how to proceed. Typically client's resort to regex matching on the human description. GraphQL (and this library) offers the ability add `extensions` to errors to give more context. To make it easier for the client to understand, a common approach is to add an enumerable error code to the errors extensions.

Unfortunately, the current validator implementation does not expose a way to add extensions to the error being raised.

### Proposed Options

- One possible solution would be to support returning a Hash from the `validate` method which supports an `extensions` key which is applied to the error when raised upstream.
- Alternatively, users could raise directly within a custom validator with their desired extensions?

**Comment by rmosolgo** [comment]
>  raise directly

This appeals to me from a flexibility standpoint -- it provides an "escape hatch" where validators can do whatever they want (as long as they only need _one_ error, anyways). I don't remember the implementation well enough to know if it's viable, but I like the idea. Want to give it a shot?

**Comment by cocoahero** [comment]
I've tested it briefly and it does *work*. However, it seems to be currently an all or nothing situation as things like support for `allow_blank`, `allow_null`, and error message variable interpolation happen outside of `Validator#validate` in private API. 

Perhaps those implementations could be moved into `validate` instead of `apply` and `validate!` respectively?

**Comment by rmosolgo** [comment]
Yeah, I'm game for shuffling those around a bit. one nice thing to preserve would be, if I write a custom validator, I can get `allow_blank` (etc) without manually coding those behaviors.

**Comment by rmosolgo** [comment]
I added a test for raising errors with custom extensions in #3671. There's also a method called `permitted_empty_value?(val)` which the built-in validators use to apply `allow_nil`/`allow_blank` configurations. `def apply` has been removed altogether.

Please let me know if there are other improvements I can make there!
