### ISSUE TITLE
Support filtering subscription streams by arguments

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#3588]
Currently, subscriptions are turned into "topics" using the field name, argument values, and subscription scope. This makes it impossible to implement a scenario where:

- The application emits events of a certain kind
- Clients want to subscribe to a subset of those events -- dynamically, using graphql arguments

See https://github.com/rmosolgo/graphql-ruby/issues/2474#issuecomment-760956808 for a discussion of this.

I think the existing system _could_ be modified to support that scenario:

1. Add a `#topic` method to subscription classes. Default it to the current implementation, but allow it to be overridden to _not_ include the arguments
2. Use `#update` to filter the stream, avoiding updates 
3. Probably, a configuration option could be added to provide that behavior

**Comment by gastonmorixe** [comment]
Thank you for the quick follow up Robert
