### ISSUE TITLE
Wrapping blocks in functional composition documentation

### ISSUE THREAD

**Issue by aviscasillas** [rmosolgo/graphql-ruby#359]
Hi guys!

I'm now following the "Functional composition" section to DRY some parts of my code:
https://github.com/rmosolgo/graphql-ruby/blob/master/guides/schema/code_reuse.md#functional-composition--resolve

Implementing the exact syntax (with ruby version 2.2.5) leads me to an error:
```
NoMethodError (undefined method `call' for nil:NilClass)
```

AFAIK, this is because there's no block given. My guess is that it's because the syntax here is not correct:
```ruby
resolve Auth.can_read(:post) do |obj, args, ctx|
  Post.find(args[:id])
end
```
Using `do`/`end` syntax without parentheses, makes the block being passed to the `resolve` method instead of being passed to the `can_read` one. 

I've just changed to the following and It worked:
```ruby
resolve(Auth.can_read(:post) do |obj, args, ctx|
          Post.find(args[:id])
        end)
```

Please let me know if I'm missing something...

Thanks!

**Comment by rmosolgo** [comment]
Oops, my mistake! I've just pushed a fix, thanks for pointing that out.

**Comment by aviscasillas** [comment]
Btw! @rmosolgo if you want, for the next time, I can just open PR 😉
