### ISSUE TITLE
introspection __schema query returns duplicate types

### ISSUE THREAD

**Issue by anazar** [rmosolgo/graphql-ruby#3592]
**Describe the bug**

If a custom type like an enum is used as an argument in multiple resolvers it is listed twice in introspection queries.  The list of schema types should be unique.

**Versions**

`graphql` version: 1.12.15
`rails` (or other framework): rails

**GraphQL schema**

```ruby
module Resolvers
  class Resolver1 < BaseResolver
    ...
    argument :user_status, Types::UserStatus, required: false
  end
end

module Resolvers
  class Resolver2 < BaseResolver
    ...
    argument :user_status, Types::UserStatus, required: false
  end
end
```

```
query IntrospectionQuery { 
  __schema { 
    types {
      name
    }
  }
}
```
returns...
```
{
  "data": {
    "__schema": {
      "types": [
        {
          "name": "UserStatus"
        },
        {
          "name": "UserStatus"
        },
      ]
    }
  }
}
```

**Comment by rmosolgo** [comment]
hmmm, how _strange_! There's supposed to be code preventing duplicate types. I wrote up a quick test script and it worked fine: 

```ruby
require "bundler/inline"

gemfile do
  gem "graphql", "1.12.15"
end

class Thing < GraphQL::Schema::Enum
  value :A
  value :B
end

class Resolver1 < GraphQL::Schema::Resolver
  argument :thing, Thing, required: false
  type Boolean, null: false
end

class Resolver2 < GraphQL::Schema::Resolver
  argument :thing, Thing, required: false
  type Boolean, null: false
end

class Query < GraphQL::Schema::Object
  field :f1, resolver: Resolver1
  field :f2, resolver: Resolver2
end

class Schema < GraphQL::Schema
  query(Query)
end

pp Schema.execute("{ __schema { types { name } } }").to_h

# $ ruby enum_test.rb
# {"data"=>
#   {"__schema"=>
#     {"types"=>
#       [{"name"=>"Boolean"},
#        {"name"=>"Query"},
#        {"name"=>"String"},
#        {"name"=>"Thing"},
#        {"name"=>"__Directive"},
#        {"name"=>"__DirectiveLocation"},
#        {"name"=>"__EnumValue"},
#        {"name"=>"__Field"},
#        {"name"=>"__InputValue"},
#        {"name"=>"__Schema"},
#        {"name"=>"__Type"},
#        {"name"=>"__TypeKind"}]}}}
```

Does it behave this way in production, or only development? I wonder if there's some kind of rails reloading issue causing those types to be double-loaded.

**Comment by anazar** [comment]
Thanks for the quick reply @rmosolgo. It's happening in all environments. I'm using puma.  I also tested in the same app using a much older version of the graphql gem (1.9.3) and did not have the issue. Looking like it may be caused by the Interpreter/AST.

I'm including the following in my schema:
```
  use GraphQL::Execution::Interpreter
  use GraphQL::Analysis::AST
```

**Comment by rmosolgo** [comment]
Ok, thanks. It seems like the map of type_name -> type is getting messed up _somewhere_. Can you give me a few more details about where these types appear in your system?

- Does you schema inherit directly from `GraphQL::Schema` or are there other classes "in between"? Maybe it's not merging types correctly across the inheritance chain. 
- Do these resolvers appear in different root types (mutation, query, subscription), or do they all fall under the same root type? Maybe it's wrongly merging them across root types.

**Comment by anazar** [comment]
@rmosolgo 
- Yep, Schema inherits directly from `GraphQL::Schema` 
- The resolvers are only declared once in the query type

**Comment by rmosolgo** [comment]
Ok, thanks for that. I have no idea 😖 

I don't know what else to investigate without a replication of the bug. Here's where the schema's list of types is created: 

https://github.com/rmosolgo/graphql-ruby/blob/efd0711298bde27c7ff23cb6c70f675da564affc/lib/graphql/schema.rb#L1726-L1727

Here's the code that's meant to prevent conflicts by name: 

https://github.com/rmosolgo/graphql-ruby/blob/efd0711298bde27c7ff23cb6c70f675da564affc/lib/graphql/schema/addition.rb#L151-L161

Here's how `__schema { types }` is executed: 

https://github.com/rmosolgo/graphql-ruby/blob/efd0711298bde27c7ff23cb6c70f675da564affc/lib/graphql/introspection/schema_type.rb#L17-L19

They're even accumulated in a `Set`, so I don't see how you could get duplicates 😖 

I guess you could open up that file (with `bundle open graphql`) and drop a binding.pry in there to investigate those _two_ types with the same name. Are they really the same class defined in your project? Do they have the same `object_id`?

**Comment by anazar** [comment]
@rmosolgo Thanks for helping me see where to debug. It looks that the issue may have to do with the difference between the class and the graphql name. When I view the `reachable_types` I see both:
```
Types::UserStatus
EnumUserStatus
```
where EnumUserStatus is the defined graphql_name.

**Comment by anazar** [comment]
@rmosolgo Ugh.. well this is dumb. I tracked it down to one place where we are dynamically adding a mutation field.

```
Types::MutationType.field(mutation_name, mutation: new_mutation_class)
```

Is there a way to do this that would update the schema and remove any duplicates? It appears this is causing the duplicates.

**Comment by rmosolgo** [comment]
I hope you found a solution for this!
