### ISSUE TITLE
Stop supporting versions of ruby < 2.6, rails < 5

### ISSUE THREAD

**Issue by camiloforero** [rmosolgo/graphql-ruby#3596]
### Ruby
source: https://www.ruby-lang.org/en/downloads/branches/

Ruby 2.5 went EOL on the last day of March, this year.
Ruby 2.3, the earliest version used on the CI tests, went EOL on 2016, two years and a half ago
Ruby 2.2, the rubocop linter target, went EOL three years and a half ago.

### Rails

Rails 3 went EOL on 2016, 5(!) years ago, with [the launch of Rails 5](https://weblog.rubyonrails.org/2016/6/30/Rails-5-0-final/)
Rails 4 went EOL on August 2019, 2 years ago, with [the launch of Rails 6](https://weblog.rubyonrails.org/2019/8/15/Rails-6-0-final-release/).

However, in the automated tests that run on the CI, backwards compatibility is maintained with all of those versions.

I'd suggest that if the official maintainers aren't supporting those versions anymore, we shouldn't either for future GraphQL versions. If someone using a very old version of Ruby/Rails wants to keep using this library, they can always lock their `graphql` version to the current one.

However, @rmosolgo, you'd know better about who is using this gem, and in which versions of ruby/rails. Is there a reason you've been supporting such old versions for this long?

If you don't want to be so drastic, and also for the purposes of merging #3577, I'd suggest
- Support rails 4.2+, to be able to use the newer ORM generators
- Support ruby 2.4+, mostly because versions 2.3 and earlier can't be easily installed on newer OSses (for example, in my Ubuntu 20.04 laptop I couldn't, as it required gcc and g++ v6, which isn't even available in the default repositories)

I can make the changes in the CI configuration as needed, according to the decision made

**Comment by rmosolgo** [comment]
👋  Thanks for asking. I'm hesitant to remove support for these versions very quickly; many of them were added by people who still used those versions in production. I don't know if they still do or not, but in any case, I don't want to remove it without checking with them. 

For #3577, I recommend updating the PR to pass the current CI configuration. Then, if you're interested in removing support for these old versions, you can open new PRs for them to start the discussion around it.
