### ISSUE TITLE
After resolve callback?

### ISSUE THREAD

**Issue by richardadrian** [rmosolgo/graphql-ruby#3598]
My resolver performs a query on > 1000 items in an in a clause.  I'm using a table to store the items and do a scope. join.

But I need to clean up that data after the response.  Are there any type of callbacks?

**Comment by rmosolgo** [comment]
Hi! There are a few different kinds of hooks, depending on the specifics of what you need: 

- https://graphql-ruby.org/queries/instrumentation.html
- https://graphql-ruby.org/type_definitions/field_extensions.html
- https://graphql-ruby.org/queries/tracing.html

If you give one of those a try and it doesn't work out for you, please open a new issue with details about your field or resolver, the kinds of queries it does, what you need to clean up, and when you need to clean it up. Hope that helps!
