### ISSUE TITLE
Wonder if this could be used with relay?

### ISSUE THREAD

**Issue by ncri** [rmosolgo/graphql-ruby#36]
Looking into using Rails with Relay, wondering if this could be used with 

https://github.com/facebook/relay

Would be awesome ;-)

**Comment by rmosolgo** [comment]
Here's what I've got for that: https://github.com/rmosolgo/graphql-ruby#use-with-relay

How does that look?

**Comment by ncri** [comment]
Great! Will give it a try. Thx. Btw.: Link broken here at the bottom:

https://github.com/rmosolgo/graphql-relay-ruby (GraphQL Slack)

**Comment by rmosolgo** [comment]
oh thanks, I'll fix it!
