### ISSUE TITLE
Graphql ruby client: sync with collocated fragments

### ISSUE THREAD

**Issue by such** [rmosolgo/graphql-ruby#3603]
Hello,

I'm trying to figure out if I can easily plug in the Operation Store but my React frontend with Apollo client does not include `.graphql` files. Instead, fragments and queries are collocated with the components in .tsx files.
I'm able to use `apollo client:codegen` to generate typescript types, or a big json file with all the operation but I'm yet to find a wait to generate the kind of `.graphql` files that `graphql-ruby-client sync` expects.
Can you help me here?

**Comment by rmosolgo** [comment]
Hey, good question -- it's not supported yet. However, I'm open to adding it. Would you like me to take a look (or would you rather take a crack at it yourself)?

**Comment by such** [comment]
It would be great if you could take a look!

After spending a couple hours on this, I think there are 3 possible way to support our way of doing things):
- Use https://www.graphql-code-generator.com/ and add a plugin that spits .graphql files
- Allow graphql-ruby-client to understand the JSON format that is generated by `apollo client:codegen`
- Allow graphql-ruby-client to understand graphql-tag format in JS/TS files

**Comment by rmosolgo** [comment]
> Allow graphql-ruby-client to understand the JSON format that is generated by `apollo client:codegen`

Ahh, these seems like a great approach. It gives us some degree of isolation from what's really in the code, and we can be sure that the operations sent to the backend match the ones that apollo will use at runtime. Thanks for the suggestion 👀

**Comment by such** [comment]
Hey @rmosolgo,

Did you get the chance to start working on this?
If you have not I'll see how I can prioritize it

**Comment by rmosolgo** [comment]
D'oh -- thanks for the ping on this, sorry it slipped off my radar. Let me take a look this week!

**Comment by rmosolgo** [comment]
I've given it a shot in https://github.com/rmosolgo/graphql-ruby/pull/3616. @such, does that look like the workflow you had in mind? If it looks good to you, I'll 🚢 !

**Comment by such** [comment]
Hey, thank you I was able to confirm that it works perfectly! You can ship!

Sidenote/Off topic: while testing i've had to default the is_archived column to false to make it work:

`t.column :is_archived, :boolean, default: false`

**Comment by rmosolgo** [comment]
Glad to hear it, thanks for taking a look :+1: And thanks for pointing out `default: false`, too -- that's what I have in code, but not in the docs 😖  I'll update the docs, thanks. 

Shipped in `graphql-ruby-client` 1.10.1! Please let me know if you run into any more trouble with it.
