### ISSUE TITLE
Dataloader batch parameter uniqeness behaves in an unexpected way

### ISSUE THREAD

**Issue by mroach** [rmosolgo/graphql-ruby#3608]
**Is your feature request related to a problem? Please describe.**

While implementing a new schema making use of data loaders for loading all relations, I was surprised to find I had N+1 problems, but only sometimes.

I have a few dataloaders for loading ActiveRecord objects. As an example, there's one for loading foreign objects that takes a base scope and foreign key field as a param. Here's how I might fetch records from a `has_many` relation:

```ruby
dataloader.with(Sources::ActiveRecordForeignObjects, ::Comment, :commentable).load(object)
```

This works fine and the records are all loaded in one query.

I realised the N+1 problem happened only when I sent an `ActiveRecord::Relation` instead of a bare class. Calling any method on a model class causes a `Relation` instance to be created and this causes a separate batch to be created for every invocation, thus creating an N+1.

This can be as simple as:

```ruby
dataloader.with(Sources::ActiveRecordForeignObjects, ::Comment.published, :commentable).load(object)
```

Now instead of a `Class`, an `ActiveRecord::Relation` is passed.

In `ActiveRecord::Relation`, the [#==](https://api.rubyonrails.org/v6.1.4/classes/ActiveRecord/Relation.html#method-i-3D-3D) method is overridden so that the generated SQL of each relation is used for equality (that's why the ones with preload are considered equal)

```ruby
irb> Comment.all == Comment.all
=> true

irb> Comment.all.object_id == Comment.all.object_id
=> false

irb> Comment.preload(:commentable) == Comment.preload(:commentable)
=> true

irb> Comment.preload(:commentable) == Comment.joins(:user)
=> false

irb> Comment.preload(:commentable) == Comment.unscoped
=> true
```

In [dataloader.rb](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/dataloader.rb#L39) it appears that the batch parameters are being used as hash keys.

The [documentation page for Hash](https://ruby-doc.org/core-2.5.1/Hash.html#method-i-update) says about every method that does key equality checking:
> Note that include? and member? do not test member equality using == as do other Enumerables.

This can be proven with:

```ruby
x = {}
5.times { x[Comment.unscoped] = 1 }
x.count
=> 5
```

The result is that you can accidentally introduce N+1 problems even when using scopes that produce identical SQL.

**Describe the solution you'd like**

Since all the arguments are used as a big composite key, it's hard to imagine a solution where equality is checked in a different way for each element in the args array without causing a performance problem.

One option might be to allow the batch uniqueness to be defined in a custom way. In my case, I might do:

```ruby
def args_to_unique_id(args)
  args.map { |arg| arg.is_a?(ActiveRecord::Relation) ? arg.to_sql.hash : arg.hash }.hash
end
```

I've confirmed this would do the trick for me:

```ruby
irb(main):076:0> [Comment.unscoped, :commentable].map { |arg| arg.is_a?(ActiveRecord::Relation) ? arg.to_sql.hash : arg.hash }.hash
=> -1352645948997896458
irb(main):077:0> [Comment.unscoped, :commentable].map { |arg| arg.is_a?(ActiveRecord::Relation) ? arg.to_sql.hash : arg.hash }.hash
=> -1352645948997896458
```

**Describe alternatives you've considered**

For now, I'm guarding the initializers of my custom sources to stop this from happening

```ruby
def initialize(model_class, fk)
  raise "model_class must be Class and not an instance." unless model_class.is_a?(Class)
  ...
end
```

**Additional context**

**Comment by rmosolgo** [comment]
Hey, thanks for the really helpful writeup. What a doozy!

Agreed that some way of customizing the key used internally is the way to go. IIRC that's how graphql-batch does it, too: 

https://github.com/Shopify/graphql-batch/blob/211b11a516f526e675dec78fbbd8aeac1d18d8e1/lib/graphql/batch/loader.rb#L16-L18

If you want to take a crack at it, please do, and let me know if I can help. Otherwise, I'll take a look soon and follow up back here!

**Comment by mroach** [comment]
@rmosolgo I like that idea of having a class method in the source/loader to define how the key is computed since the source/loader will know what kinds of arguments to expect and how to compare them.

For the moment I've been able to work-around the issue in my schema. If the issue is still open when I return from vacation, I'll get in touch about my taking a stab at it :)
