### ISSUE TITLE
Dynamic schema relationships

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#3622]
By the spec, GraphQL is _versionless_. Instead, schemas are supposed to receive _additive_ changes only. 

For Facebook, this works great, because GraphQL is for internal use only. There's no shame in a `friendsCountV2` or `unfollowFinalFinal`, and so on ... but what about for public GraphQL APIs? We'd like some way to change the schema over time so that we can make improvements to the "current" schema while maintaining compatibility for existing clients. 

For example, if you release a schema with `id: Int` fields, but you want to migrate them to `id: ID` fields, it'd be nice to have a way to do that while maintaining compatibility for clients that expect `Int`s there. (GraphQL-Ruby already has a mechanism for _hiding_ parts of the schema on a per-request basis, but this would involve _swapping_ or _modifying_ parts of the schema on a per-request basis.)

Besides field return types (illustrated above), there are many other parts of configuration that would be nice to change on-the-fly: 

- argument types
- `deprecation_reason:`s 
- directives (definition directives, like `@deprecated`)

In practice, I think this could be implemented by migrating the internal structure of `SomeType.fields` from a `Hash<String => GraphQL::Schema::Field>` (where each name points to one field definition) to `Hash<String => Hash<Condition => GraphQL::Schema::Field>` (where each name points to a list of fields, each one having a condition to determine whether it applies or not -- the condition might be string to match, or version number, or a function). Something similar would be adding a `def field_for(name, context) # => @returns GraphQL::Schema::Field` method where the definition is chosen _dynamically_ for a given name; it might be implemented by default to draw from a structure as described above. 

__One outstanding question:__ Can we get all the desired behaviors while _retaining_ the assumption that a schema contains only one type for each name? That is, do we _need_ to support multiple-types-per-name within a schema? 

I _think_ one-type-per-name will still work fine. Instead of saying "there are two different definitions for this type", you'd merge the definitions into a single type, but make the diverging behaviors subject to a runtime condition. Is there a case where that _doesn't work_ or isn't feasible?

**Comment by cocoahero** [comment]
> One outstanding question: Can we get all the desired behaviors while retaining the assumption that a schema contains only one type for each name? That is, do we need to support multiple-types-per-name within a schema?

For the sake of illustrating this question, I'm considering the following example:
```graphql
# "legacy" type used in certain older API releases
scalar Money 

# preferred typed 
type Money { 
  amount: Float!
  currency: String!
}
```

I think it is desirable to say that these two "types" should be able to coexist within the `GraphQL::Schema` graph, however only one should be able to exist within the context of a query. In other words, if a client were to run an introspection query, only one of those types should be returned.

**Comment by cocoahero** [comment]
Another solution that @grcooper and I hypothesized revolved around adding two new "hooks" to field and argument definitions:
```ruby
def possible_types
  # returns a set of all the possible types this field could resolve to
  [self.type]
end

def resolve_type(context)
  # examine the context and determine which type should be used to coerce the resolved value
  self.type
end
```

This would likely also mean that the schema given to the `Warden` would have to already contain all the possible types, and then maybe use `visibility` to hide the ones not used?

**Comment by rmosolgo** [comment]
:+1: Thanks for that example of a scalar-to-object migration. That's a great point. It will complicate the implementation, but I agree it's worth it, and I'm sure it's possible one way or another.

> the schema ... would have to already contain all the possible types, and then ... hide the ones not used?

Yeah, that's how visibility works _now_, and I have a hard time imagining an alternative. The main difference between today and a "multiple types with the same name" world is that, today, GraphQL-Ruby assumes that the "whole" Schema is _always_ valid. But in that case, the "whole" schema may be _invalid_ (multiple types with the same name, multiple fields with the same name, etc), therefore only _subsets_ of the schema may be used.

**Comment by rmosolgo** [comment]
Released in 1.13.0 :+1:

**Comment by joelzwarrington** [comment]
@rmosolgo had a question, how would I use the functionality added here to use `global_id_field` conditionally?

Assuming `version` would apply visibility in `visible?` correctly...
```ruby
global_id_field :id

field :id, ID, null: false, version: Semantic::Version.new("1.0.0")
```

How would I enable usage of `global_id_field` in version `Semantic::Version.new("2.0.0")`

**Comment by rmosolgo** [comment]
Any extra keyword arguments given to `global_id_field(:id, ...)` are passed along to the underlying field call: 

https://github.com/rmosolgo/graphql-ruby/blob/850faa39ef11e4a4afe92f7f9fa8cd3f3c01a6e6/lib/graphql/schema/member/has_fields.rb#L105-L111

So if you had `global_id_field :id, version: Semantic::Version.new("2.0.0")`, that would be come `field :id, ID, null: false, version: Semantic::Version.new("2.0.0")`. Your base field would need to do two things:

- Implement `def initialize(*args, version: nil, **kwargs, &block)` to call `super` and store `@version = version` 
- Implement `def visible?(context)` to compare `@version` to something in `context` and return true/false

That would cause the ID field to be hidden in one case and visible in another case. `.fields(context)` will automatically remove any fields that return `false` for `visible?(context)`, and afaict, that's all you'd need for that case.

>  manually call `schema.id_from_object`

In my opinion, that's not a bad idea _anyway_ -- the `global_id_field` helper does almost nothing, the indirection it brings isn't worth it, especially when you start customizing it. 

Hope that helps!

**Comment by ravangen** [comment]
I recently made a small [demo](https://github.com/ravangen/graphql-conf-2021/blob/main/demo/app/graphql/types/base_field.rb) of essentially exactly what you are describing, just replace the work "schema" with "version".

**Comment by rmosolgo** [comment]
Also, FWIW, I rolled a (paid) take on this, riffing on [Stripe's versioning system](https://stripe.com/blog/api-versioning): https://graphql-ruby.org/changesets/overview.html

**Comment by joelzwarrington** [comment]
Thanks @rmosolgo, I assumed and taking a look saw that the `kwargs` were being passed to the underling field call. Will take a look into the changesets, looks like a cool feature and can help reduce the amount of home-rolled versioning 😄
