### ISSUE TITLE
Additional duplicate params added to params[:graphql] — can't figure out from where

### ISSUE THREAD

**Issue by thornomad** [rmosolgo/graphql-ruby#3624]
> This seems similar to what @tap349 described in [this issue](https://github.com/rmosolgo/graphql-ruby/issues/1435). 

**Describe the bug**

In our controller the `params` payload has an additional nested hash under `params[:graphql]` that contains duplicate values from the top level `params` hash.

```json
# => params
{
  "graphql": {
    "operationName": "CurrentUser",
    "query": "query CurrentUser {\n  currentUser {\n    id\n    }\n}\n",
    "variables": {}
  },
  "operationName": "CurrentUser",
  "query": "query CurrentUser {\n  currentUser {\n    id\n    }\n}\n",
  "variables": {}
}
```

The `query`, `variables` and `operationName` data is duplicated.

```ruby
params[:query] == params[:graphql][:query]
params[:variables] == params[:graphql][:variables]
params[:operationName] == params[:graphql][:operationName]
```

I can't figure out where/why these are being injected as the params are already duplicated before `ApiSchema.execute` is even run.  

Here is an example with curl:

```bash
curl --request POST \
  --url http://localhost:4001/graphql \
  --header 'Content-Type: application/json' \
  --data '{"query":"query ($filter: RecordsSearchFilter!) {\n  recordsSearch(filter: $filter) {\n    id\n    label\n  }\n}\n","variables":{"filter":{"query":"Foo"}}}'
```

But immediately in the console we can see it's been duplicated/nested for some reason:

```text
Started POST "/graphql" for ::1 at 2021-09-28 09:53:38 -0400
Processing by GraphqlController#execute as */*
  Parameters: {"query"=>"query ($filter: RecordsSearchFilter!) {\n  recordsSearch(filter: $filter) {\n    id\n    label\n  }\n}\n", "variables"=>{"filter"=>{"query"=>"Foo"}}, "graphql"=>{"query"=>"query ($filter: RecordsSearchFilter!) {\n  recordsSearch(filter: $filter) {\n    id\n    label\n  }\n}\n", "variables"=>{"filter"=>{"query"=>"Foo"}}}}
```

I can't figure out what is putting them there and why.  

Any ideas where that might be coming from?  Do other people experience this same thing (or is my setup wrong)?

**Versions**

`graphql` version: 1.12.16
`rails` (or other framework): 6.1.4.1

**Comment by rmosolgo** [comment]
Seems like something Rails does "for you": https://guides.rubyonrails.org/action_controller_overview.html#json-parameters

I found that link from here: https://stackoverflow.com/a/27673892

Does `wrap_parameters false` in your controller make that behavior go away? Can you find any `wrap_parameters` configuration in your code (maybe from `rails new` all that time ago)?

**Comment by thornomad** [comment]
Ah that totally is the magic I was seeking.  Nicely done tracking that down.  Thank you!  Simply adding `wrap_parameters false` in the `graphql_controller.rb` did the trick.
