### ISSUE TITLE
Issue with forward compatibility between 1.8.8 and 1.10.14

### ISSUE THREAD

**Issue by flovilmart** [rmosolgo/graphql-ruby#3630]
**Is your feature request related to a problem? Please describe.**
We are late to the party and only migrating to 1.10.14 from 1.8.8 and having a hard time with the [changes on Float / Int coercion](https://github.com/rmosolgo/graphql-ruby/pull/2404).

the client sends queries in this form:

```
query myQuery($param: Int) {
   call(param: $param)
}

// Client is sending float values which were coerced on the server on 1.8.8
{ param: 1.1 }
```
While we completely support the decision, we would love to have some form of escape hatch before type coercion occur.

We've tried various tricks from monkey patching, to method redefinition, but none worked.

We also considered using the `prepare: ` directive, but it occurs that `prepare:` is called after coercion has happened. (understandably).

**Describe the solution you'd like**

Ideally, we'd like to have an escape hatch before the field's argument gets processed from a variable, something like the prepare, but that occurs before the coercion.

**Describe alternatives you've considered**

Other alternatives may be more costly, we've investigated hooking on the analysis engine, with success, but that seemed a bit extreme.

Thanks for the help and the library!

**Comment by flovilmart** [comment]
Yeah it's not logging there; I'm with 1.10.14:

```
module GraphQL
  class Types::Int < Schema::Scalar
    def self.coerce_input(value, _ctx)
      puts "COERCE!"
      value.is_a?(Numeric) ? value.to_i : nil
    end
  end

  class MySchema < Schema
```

and it does not work

**Comment by rmosolgo** [comment]
And to be clear, could you share an example query you use to test the behavior, and what response you get for it?

**Comment by rmosolgo** [comment]
Ok, got it! Sorry. The thing that's missing is 

```ruby 
GraphQL::INT_TYPE.coerce_input = GraphQL::Types::Int.method(:coerce_input)
```

Here's a successful example script: 

```ruby
require "bundler/inline"

gemfile do
  gem "graphql", "1.10.14"
end

class Query < GraphQL::Schema::Object
  field :add, Int, null: false do
    argument :left, Int, required: true
    argument :right, Int, required: true
  end

  def add(left:, right:)
    left + right
  end
end


class AddSchema < GraphQL::Schema
  query(Query)
end

query_str = "{ add(left: 1.1, right: 2.3) }"
pp AddSchema.execute(query_str).to_h
# {"errors"=>
#   [{"message"=>
#      "Argument 'left' on Field 'add' has an invalid value (1.1). Expected type 'Int!'.",
#     "locations"=>[{"line"=>1, "column"=>3}],
#     "path"=>["query", "add", "left"],
#     "extensions"=>
#      {"code"=>"argumentLiteralsIncompatible",
#       "typeName"=>"Field",
#       "argumentName"=>"left"}},
#    {"message"=>
#      "Argument 'right' on Field 'add' has an invalid value (2.3). Expected type 'Int!'.",
#     "locations"=>[{"line"=>1, "column"=>3}],
#     "path"=>["query", "add", "right"],
#     "extensions"=>
#      {"code"=>"argumentLiteralsIncompatible",
#       "typeName"=>"Field",
#       "argumentName"=>"right"}}]}

class GraphQL::Types::Int
  def self.coerce_input(value, _ctx)
    value.to_i
  end
end

GraphQL::INT_TYPE.coerce_input = GraphQL::Types::Int.method(:coerce_input)

pp AddSchema.execute(query_str).to_h
# {"data"=>{"add"=>3}}
```

I forgot that on 1.10, the default is the legacy runtime, which uses some singleton objects initialized when the library is loaded. `GraphQL::INT_TYPE` is _derived_ from `GraphQL::Types::Int`, but after we update it, the derived singleton isn't updated. So we have to propage our update to that singleton, too. 

Try adding that line above :point_up: to your application -- does that work for you?
