### ISSUE TITLE
Add support for sentry tracing

### ISSUE THREAD

**Issue by Frederik-Baetens** [rmosolgo/graphql-ruby#3655]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to use graphql-ruby together with sentry's tracing.

**Describe the solution you'd like**

It would be nice if i could see separate traces for all graphql queries in sentry's tracing.

**Describe alternatives you've considered**

I've tried appsignal since they also have a plan for non-profits, but there there's also no per query tracing yet.

**Additional context**

https://docs.sentry.io/product/sentry-basics/tracing/distributed-tracing/

**Comment by Frederik-Baetens** [comment]
@penso we switched to appsignal for our tracing bc they offered a non-profit plan and that works great after one of our team members made a PR here to separate the spans by graphql query.

I also used skylight, and actually preferred that, but they didn't offer a plan for non-profits.

**Comment by penso** [comment]
@Frederik-Baetens looks like that changed: https://www.skylight.io/oss

**Comment by Frederik-Baetens** [comment]
@penso i'm aware of that, but we're a non profit with a closed source stack unfortunately, so we're not eligible for that.

**Comment by abhinaykumar** [comment]
Hi @rmosolgo, Is the support sentry is something that is in the roadmap?

**Comment by rmosolgo** [comment]
Personally, I don't have any plans to add it, no. I'd welcome a PR for it though!

**Comment by rmosolgo** [comment]
I'm going to close this since I don't have plans to work on it. But I'd welcome an addition if anyone is interested!

**Comment by patch0** [comment]
I've opened a PR to address this in #4775
