### ISSUE TITLE
Span information not available when tracing 

### ISSUE THREAD

**Issue by adrys-lab** [rmosolgo/graphql-ruby#3673]
**Describe the bug**

We are trying to add GraphQL Tracing Instrumentation to our new GraphQL API.

After configure the tracing under our schema as:
```
    module GraphQL
      class Schema < ::GraphQL::Schema
        use(::GraphQL::Tracing::DataDogTracing, {
          service: 'backend-graphql-api',
          analytics_enabled: true
        })
      end
    end
```
We don't see any SPAN information in the traces.

We correctly see the requested resource, the operation name, also the Hits and Latency in Datadog,

But we loose all the spans such as Database Queries, Redis....etc (which are present for all the rest of traces in the application).

![image](https://user-images.githubusercontent.com/35842560/139072367-c91276b5-6893-4a68-96b9-6983c5931322.png)

We also tried to instrument it when the application bootstraps, on the Datadog.configure, but this did not work neither.

**Comment by rmosolgo** [comment]
Please let me know if you're still having trouble with this and can find the answers to those questions!
