### ISSUE TITLE
Accessing resolver state async

### ISSUE THREAD

**Issue by josh** [rmosolgo/graphql-ruby#368]
GitHub uses [graphql-batch](https://github.com/Shopify/graphql-batch) pattern for most of its data loading. This leads to most resolvers returning Promises. Thats been great.

However, there are some subtle issues accessing certain resolver `context` properties async.

The resolver process uses many **mutable** values that are updated as the resolve walks the query tree. So unless a resolve block captures the state at the start of the block, it maybe different by the time the promise is resolved.

``` ruby
resolve -> (foo, args, ctx) {
  expected_ast_node = context.ast_node
  loadDataAndReturnAPromise().then {
    actual_ast_node = context.ast_node
    expected_ast_node != actual_ast_node
  }
}
```

I think its going to be a pain, but I think we really need to start ensuring any context values passed to a resolver are immutable.

<hr>

To: @rmosolgo 
CC: @charliesome @mcolyer

**Comment by rmosolgo** [comment]
You ask hard questions! :P 

I think we need some new object, I hate to write it after just disowning ExecutionContext but 


```ruby 
class FieldContext
  def initialize(query_ctx, irep_node, path); end 
  # delegate stuff to context and irep_node 
  attr_reader :irep_node, :path
end 
```

somehow have to prevent going crazy and making those when we don't need 'em though

**Comment by rmosolgo** [comment]
(I guess that's like an `ExecFrame` from `DeferredExecution`, maybe it's time to polish that baby up ...)

**Comment by rmosolgo** [comment]
1.2.0 puts a `FieldResolutionContext` into the resolve function, which not modified as the query continues. I think that should do the trick, let me know if not!
