### ISSUE TITLE
Add field information to coercion errors

### ISSUE THREAD

**Issue by sbeckeriv** [rmosolgo/graphql-ruby#3693]
**Is your feature request related to a problem? Please describe.**

Problem: In production i get an error report that says: `GraphQL::IntegerEncodingError: Integer out of bounds: -62116733627. Consider using ID or GraphQL::Types::BigInt instead.`  I have clearly have bad data but i am unsure which field the user requested that is the issue. 

**Describe the solution you'd like**

I would like to know what field caused the issue. 
`GraphQL::IntegerEncodingError: Integer out of bounds: -62116733627 for `UserRating::rating`. Consider using ID or GraphQL::Types::BigInt instead.`

The error has the bad integer_value as a field. Maybe it could also carry the original data object or field? 

**Describe alternatives you've considered**

I am going to have to dive in to the production data or bisect the 34 fields that are loaded. I also considered patching the code at some level and logging it myself. 

**Additional context**

**Comment by rmosolgo** [comment]
Thanks for the suggestion! I agree it'd be a nice improvement, working it up at #3697
