### ISSUE TITLE
`required: :nullable` argument definition

### ISSUE THREAD

**Issue by FunkyloverOne** [rmosolgo/graphql-ruby#3700]
### The problem

[GraphQL Null Input Value spec](https://spec.graphql.org/October2021/#sec-Null-Value) states the following:

> GraphQL has two semantically different ways to represent the lack of a value:
> - Explicitly providing the literal value: `null`.
> - Implicitly not providing a value at all.

And also:
> ... **These two forms may be interpreted differently**. For example, a mutation representing deleting a field vs not altering a field, respectively. Neither form may be used for an input expecting a Non-Null type.

And so here's the problem with a classic `required: true` argument definition: it won't allow explicit `null` input. However, we might indeed want to have an argument (key?) required but allow explicit `null` value.

### Solution

We might introduce a new `required: :nullable` argument definition, that essentially means `required: false`, but with an extra validation that the argument was **explicitly** provided.

PS: I'm down to provide a PR if it is considered reasonable.

**Comment by rmosolgo** [comment]
Hey, thanks for the suggestion! On 1.12.18, this should be possible with: 

```ruby 
argument ... required: false, validates: { allow_null: false }
```

In that configuration, if an value is given for that argument, it must not be `null` (from GraphQL) or `nil` (from Ruby). See: https://graphql-ruby.org/fields/validation.html#built-in-validations

Let me know if that doesn't work for you!

**Comment by FunkyloverOne** [comment]
Hey @rmosolgo, I believe we're not on the same page here. Here's a pseudo-code for a kind of behavior I would like to achieve:
```ruby
argument ... required: true, validates: { allow_null: true }
```
So an argument is _required_ to be explicitly passed, e.g. **it cannot be omitted**, however, the value for it **can** be `null`.
How does this sound?

**Comment by rmosolgo** [comment]
Oh, I see -- thanks for clarifying. From a GraphQL perspective, you'd want `required: false` (which causes the argument type to be nullable) but then a runtime validation that asserts that _some_ value was given.

**Comment by rmosolgo** [comment]
I took a look at this, and while working through it, I found a way to accomplish it with the existing validators. Does this look like the behavior you're looking for? 

```ruby
require "bundler/inline"

gemfile do
  gem "graphql", "1.13.0"
end

class Schema < GraphQL::Schema
  class Query < GraphQL::Schema::Object
    field :f, Integer, null: true do
      validates required: {
        one_of: [:arg],
        message: "Provide a value for `arg`, even if it's null"
      }
      argument :arg, Integer, required: false
    end

    def f(arg:)
      arg
    end
  end

  query(Query)
end

pp Schema.execute("{ f(arg: 1) }").to_h
# {"data"=>{"f"=>1}}

pp Schema.execute("{ f(arg: null) }").to_h
# {"data"=>{"f"=>nil}}

pp Schema.execute("{ f }").to_h
# {"data"=>{"f"=>nil},
#  "errors"=>
#   [{"message"=>"Provide a value for `arg`, even if it's null",
#     "locations"=>[{"line"=>1, "column"=>3}],
#     "path"=>["f"]}]}
```

Would that work for you?

**Comment by FunkyloverOne** [comment]
@rmosolgo that is exactly the behavior needed, thank you!
Do you think it's worth adding this case to the documentation, or maybe even having some helper to make it more appealing?

**Comment by rmosolgo** [comment]
Agreed, what do you think of the proposal in #3784?
