### ISSUE TITLE
Add utilities to support pagination fields resolved by a remote RESTful (like) API

### ISSUE THREAD

**Issue by jackrr** [rmosolgo/graphql-ruby#3719]
**Is your feature request related to a problem? Please describe.**

My team has a single Ruby on Rails backend that provides a `graphql-ruby` GraphQL server for a few React.js/Relay SPAs. We recently added a separately-hosted CMS (just a [Strapi](https://strapi.io/) deployment) to our ecosystem. This CMS is going to contain data that has relationships to data in the RoR backend.

We could have our frontend SPAs fetch data from the CMS and our RoR backend independently, and stitch together any data in the client. While this would theoretically work, it has two major flaws: 1) it requires the duplication of logic responsible for managing relationships between data in the RoR backend and the CMS across all the frontend clients and 2) it would undermine the convenience that a GraphQL API provides -- abstracting away the imperative details of _how_ data is related and gathered to build a UI. So, I would like for the SPAs to be able to fetch both the CMS and our core backend data via a single `graphql-ruby` API on the RoR backend.

**Describe the solution you'd like**

I would like for `graphql-ruby` to add some built-in support for remote-resolving fields from APIs that meet certain REST-like specifications. As a user of the `graphql-ruby` gem, I should be able to specify some types for my API resources, field names, and any argument -> query arg transformation, and then `graphql-ruby` should be able to handle resolving my relations from the remote APIs just as though they were fetched from a database.

I have a prototype of this running in production on our application that breaks down into a few major components, some of which I think are core to this feature request:

- Adding an `HttpRelation` class that can lazily fetch from a remote API and provides an `ActiveRecord`-like interface 
  - The remote API must provide index, get one, and count endpoints. These can be configurable on the `HttpRelation` constructor
  - Additional configuration for GraphQL arguments -> remote API request params/body translation can be added here
- Adding a new `HttpConnection` subclass of [`RelationConnection`](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/pagination/relation_connection.rb) to control pagination for the `HttpRelation`
-  A `graphql-ruby` interface module that provides some convenience helpers for adding fields that will use `HttpRelation` as a resolver

I'm also generating the GraphQL schema types from a ruby client library produced by a [OpenAPI ruby codegen](https://github.com/OpenAPITools/openapi-generator), but I believe this portion probably belongs in a separate, supplemental gem to `graphql-ruby` as it may not be as widely applicable as the more general remote API resolver capabilities, above.

**Describe alternatives you've considered**

Another solution has the CMS expose GraphQL APIs instead of RESTful ones, and then adds the capability for [schema stitching](https://www.graphql-tools.com/docs/schema-stitching/stitch-combining-schemas) to `graphql-ruby` on the RoR server. I explored this solution a little bit, but this seemed like a much more complicated solution to achieve than the approach I'm proposing here. I believe ultimately both the RESTful resolving proposed in this feature request and schema stitching could coexist and provide a lot of value for users of this library, but I figure the two implementations can be entirely separate problems to explore and best to start with the simpler approach to solve my problem.

A third option would be to add an API gateway layer that supports stitching together multiple backends _in front of_ both the CMS and the RoR APIs, such as [Hasura](https://hasura.io/). While this option is appealing, I like having our RoR backend act as our gateway/auth layer on the API and am not sure how to build a system that achieves our complex business requirements on a more off-the-shelf solution like one of these.

**Additional context**

As mentioned in the solution section, above, I have a working prototype for this. I'd be more than happy to submit a PR and see it through to merge, but I wanted to first give the maintainers a chance to guide the direction of the implementation.

**Comment by rmosolgo** [comment]
Hi, thanks for sharing your work in this area. I think the best way to share this code is: 

- Create a library that provides a plain-Ruby interface to an OpenAPI client; 
- In that library, include a connection implementation (https://graphql-ruby.org/pagination/custom_connections.html) which fetches data from a compliant service using library APIs 

(This is similar to how ActiveRecord provides a plain-Ruby interface to a relational database, the GraphQL-Ruby provides connection implementations on top of that library.) 

Personally, I'm not interested in maintaining the API client code. But if you implement it and publish it, I'd be happy to include a link from GraphQL-Ruby's connection docs!
