### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#3729]
My only plans for 2.0 are to remove deprecated code: 

- [x] Remove: 
  - [x] `.define`, old type classes, old field and argument classes, `def to_graphql`, Query::Arguments
  - [x] Migration docs, any mentions of the Interpreter as an option or alternative
  - [x] SerialExecution, `GraphQL::Execution::Execute`, Query::ArgumentsCache (because interpreter has a new one)
  - [x] Old `Relay` helpers (connections, mutation, node Id)
  - [x] Old execution extension points: field instrumentation, middleware
  - [x] Irep & irep analysis
  - [x] GraphQL::Compatibility -- no external runtimes are supported, no external parsers are supported (libgraphqlparser-ruby hasn't worked since 1.9.x)
  - [x] Rework execution to bypass executor? 
  - [x] Schema::Validation
  - [x] Schema::Upgrader, Railtie
  - [x] Schema instance behaviors (associated with `.define`-returned instances)
  - [x] GraphQL::Function
  - [x] GraphQL::BackwardsCompatibility (which was for `.define`)
  - [x] GraphQL::DeprecatedDSL
  - [x] Legacy validator classes with `.validate`
  - [x] SCREAMING_CASE scalar type constants
  - [x] `Multiplex#run_one_legacy` etc
  - [x] GraphQL::Deprecate
  - [x] Remove SkylightTracing which has been deprecated for some time
  - [x] There should be no checks for `.interpreter?` and that method should always return true -- same for `.using_ast_analysis?`
  - ~~Deprecate `.interpreter?` and `.using_ast_analysis?`~~ -- no, leave them in case libraries or applications are using them for feature detection. They can be removed later.
  - [x] Remove warnings about new defaults (Interpreter, connections, ast analysis, subscription setup
  - more? Search for `warn`, etc
 - ~~Move `Analysis::AST` to `Analysis`, but re-assign it to `Analysis::AST` for compatibility~~ push this off to 2.1 or so
 - [x] Remove TESTING_INTERPRETER, legacy CI build
- [ ] Add code coverage, assess other untested code #3806 
- [ ] Add some profiles to source control, to monitor performance #3806

**Comment by rmosolgo** [comment]
😗 👌 

![image](https://user-images.githubusercontent.com/2231765/151837823-abafc656-da81-4f95-9e40-4472e5b74015.png)

**Comment by joelzwarrington** [comment]
> 😗 👌
> 
> ![image](https://user-images.githubusercontent.com/2231765/151837823-abafc656-da81-4f95-9e40-4472e5b74015.png)

👨‍🍳  💋

**Comment by rmosolgo** [comment]
💥 https://rubygems.org/gems/graphql/versions/2.0.0 🚢

**Comment by rmosolgo** [comment]
I didn't accomplish my goal on the workflow improvements :( I got code coverage set up, and I used it to find and destroy legacy code, but I didn't get a good project workflow in place. I'm hoping to keep up with that in #3880, using gh-actions and artifacts. Then, hopefully I'll find a better workflow for benchmarks.
