### ISSUE TITLE
Unable to use per dynamic types and fields, provided with `two visible definitions` error

### ISSUE THREAD

**Issue by joelzwarrington** [rmosolgo/graphql-ruby#3732]
**Describe the bug**

I am unable to use the dynamic types and fields functionality described [here](https://graphql-ruby.org/schema/dynamic_types.html) because of the error:

```
Found two visible definitions for `Query.id`: #<Types::BaseField Query.id: Scalar1>, #<Types::BaseField Query.id: Scalar2>
```

**Versions**

| Gem       | Version |
|-----------|---------|
| `graphql` | 1.13.0  |
| `rails`   | 6.0     |

**GraphQL schema**

```ruby
class BaseField < GraphQL::Schema::Field
  def initialize(*args, is_visible: true, **kwargs)
    super(*args, **kwargs)
    @is_visible = is_visible
  end

  def visible?(context)
    super && @is_visible
  end
end

class BaseObject < GraphQL::Schema::Object
  field_class BaseField
end

class QueryType < GraphQL::Schema::Object
  field :id, Scalar1, is_visible: false
  field :id, Scalar2, is_visible: true
end

class Schema < GraphQL::Schema
  query QueryType
end
```

**GraphQL query**

Am unable to get to the stage of execution, as a simple introspection query or schema dump fails

**Steps to reproduce**

Steps to reproduce the behavior

**Expected behavior**

I expect that `id` with type `Scalar1` would not be visible, and that `id` with type `Scalar2` would be visible

**Actual behavior**

Thrown an error with two visible definitions.

<details>
<summary>Click to view exception backtrace</summary>

```
Found two visible definitions for `Query.id`: #<Types::BaseField Query.id: Scalar1>, #<Types::BaseField Query.id: Scalar2>
gems/ruby-2.7.2/gems/graphql-1.13.0/lib/graphql/schema/warden.rb:58:in `block in visible_entry?'
gems/ruby-2.7.2/gems/graphql-1.13.0/lib/graphql/schema/warden.rb:53:in `each'
gems/ruby-2.7.2/gems/graphql-1.13.0/lib/graphql/schema/warden.rb:53:in `visible_entry?'
gems/ruby-2.7.2/gems/graphql-1.13.0/lib/graphql/schema/member/has_fields.rb:30:in `block (2 levels) in fields'
gems/ruby-2.7.2/gems/graphql-1.13.0/lib/graphql/schema/member/has_fields.rb:27:in `each'
gems/ruby-2.7.2/gems/graphql-1.13.0/lib/graphql/schema/member/has_fields.rb:27:in `block in fields'
gems/ruby-2.7.2/gems/graphql-1.13.0/lib/graphql/schema/member/has_fields.rb:23:in `each'
gems/ruby-2.7.2/gems/graphql-1.13.0/lib/graphql/schema/member/has_fields.rb:23:in `fields'
gems/ruby-2.7.2/gems/graphql-1.13.0/lib/graphql/schema/object.rb:110:in `fields'
gems/ruby-2.7.2/gems/graphql-1.13.0/lib/graphql/schema/object.rb:134:in `to_graphql'
gems/ruby-2.7.2/gems/graphql-1.13.0/lib/graphql/schema/member/accepts_definition.rb:127:in `to_graphql'
gems/ruby-2.7.2/gems/graphql-1.13.0/lib/graphql/schema/member/cached_graphql_definition.rb:15:in `graphql_definition'
gems/ruby-2.7.2/gems/graphql-1.13.0/lib/graphql/schema.rb:935:in `to_graphql'
gems/ruby-2.7.2/gems/graphql-1.13.0/lib/graphql/schema/member/accepts_definition.rb:127:in `to_graphql'
gems/ruby-2.7.2/gems/graphql-1.13.0/lib/graphql/schema.rb:900:in `graphql_definition'
```

</details>

**Comment by joelzwarrington** [comment]
I'm hoping that I'm doing something goofy and missing something small, I tried defining `self.visible?(context)` on the scalars but I don't think that I should need to considering the GraphQL names are not conflicting.

I followed the example [here](https://graphql-ruby.org/schema/dynamic_types.html#different-definitions-for-the-same-type) excluding adding visibility checks to the scalar/types.

Essentially a simplified version of:

```ruby
class Types::BaseField < GraphQL::Schema::Field
  def initialize(*args, legacy_money: false, **kwargs, &block)
    super(*args, **kwargs, &block)
    @legacy_money = legacy_money
  end

  def visible?(context)
    super && (@legacy_money ? !!context[:requests_legacy_money] : !context[:requests_legacy_money])
  end
end

class Types::Invoice < Types::BaseObject
  # Add one definition for each possible return type
  # (one definition will be hidden at runtime)
  field :amount, Types::LegacyMoney, null: false, legacy_money: true
  field :amount, Types::Money, null: false, legacy_money: false
end
```

**Comment by rmosolgo** [comment]
Here's an example based on the script above, but it works fine for me: 

```ruby
require "bundler/inline"

gemfile do
  gem "graphql", "1.13.0"
end

class BaseField < GraphQL::Schema::Field
  def initialize(*args, is_visible: true, **kwargs)
    super(*args, **kwargs)
    @is_visible = is_visible
  end

  def visible?(context)
    super && @is_visible
  end
end

class BaseObject < GraphQL::Schema::Object
  field_class BaseField
end

class QueryType < BaseObject
  field :id, ID, is_visible: false
  field :id, String, is_visible: true
end

class Schema < GraphQL::Schema
  query QueryType
end


pp Schema.execute("{ id }", root_value: { id: "abc" })
# $ ruby visible_fields.rb
# => #<GraphQL::Query::Result @query=... @to_h={"data"=>{"id"=>"abc"}}>
```

I noticed in the exception backtrace that `.graphql_definition` and `.to_graphql` are in the call stack. I think that's the problem -- this new visibility stuff won't work with legacy definitions. 

Is there more in the backtrace than that? I wonder what's causing the schema to generate legacy-compatible schema objects -- that'll have to be removed to use this feature.

**Comment by joelzwarrington** [comment]
@rmosolgo thanks for getting back to me. I wasn't truly forthcoming with all of the code as there's a lot going on and we've customized fields a bunch. I'm going to look into these customizations with more care to see if there's anything which might be worth noting here.

Now that you mentioned `.graphql_definition` and `.to_graphql` I recall some field extensions calling this which is probably a nono on our part, but will add any findings if I either continue to encounter issues or resolve it, to help others in the same boat!

**Comment by rmosolgo** [comment]
> look into these customizations

Is there anything more in the backtrace than what's posted above? I would _expect_ the caller of those methods to appear in the backtrace, but the last entry above is 

```
gems/ruby-2.7.2/gems/graphql-1.13.0/lib/graphql/schema.rb:900:in `graphql_definition'
```

, where the method is already called 🤔

**Comment by joelzwarrington** [comment]
@rmosolgo, thanks for pointing out the `.graphql_definition` and `.to_graphql`, I was able to find out the root cause, see below. As well I've included the full-stack trace for your pleasure 😄 

<details>
<summary>Click to view exception backtrace</summary>

```
Found two visible definitions for `Query.id`: #<Types::BaseField Query.id: String>, #<Types::BaseField Query.id: ID>
.rvm/gems/ruby-2.7.2/gems/graphql-1.13.0/lib/graphql/schema/warden.rb:58:in `block in visible_entry?'
.rvm/gems/ruby-2.7.2/gems/graphql-1.13.0/lib/graphql/schema/warden.rb:53:in `each'
.rvm/gems/ruby-2.7.2/gems/graphql-1.13.0/lib/graphql/schema/warden.rb:53:in `visible_entry?'
.rvm/gems/ruby-2.7.2/gems/graphql-1.13.0/lib/graphql/schema/member/has_fields.rb:30:in `block (2 levels) in fields'
.rvm/gems/ruby-2.7.2/gems/graphql-1.13.0/lib/graphql/schema/member/has_fields.rb:27:in `each'
.rvm/gems/ruby-2.7.2/gems/graphql-1.13.0/lib/graphql/schema/member/has_fields.rb:27:in `block in fields'
.rvm/gems/ruby-2.7.2/gems/graphql-1.13.0/lib/graphql/schema/member/has_fields.rb:23:in `each'
.rvm/gems/ruby-2.7.2/gems/graphql-1.13.0/lib/graphql/schema/member/has_fields.rb:23:in `fields'
.rvm/gems/ruby-2.7.2/gems/graphql-1.13.0/lib/graphql/schema/object.rb:110:in `fields'
.rvm/gems/ruby-2.7.2/gems/graphql-1.13.0/lib/graphql/schema/object.rb:134:in `to_graphql'
.rvm/gems/ruby-2.7.2/gems/graphql-1.13.0/lib/graphql/schema/member/accepts_definition.rb:127:in `to_graphql'
.rvm/gems/ruby-2.7.2/gems/graphql-1.13.0/lib/graphql/schema/member/cached_graphql_definition.rb:15:in `graphql_definition'
.rvm/gems/ruby-2.7.2/gems/graphql-1.13.0/lib/graphql/schema.rb:935:in `to_graphql'
.rvm/gems/ruby-2.7.2/gems/graphql-1.13.0/lib/graphql/schema/member/accepts_definition.rb:127:in `to_graphql'
.rvm/gems/ruby-2.7.2/gems/graphql-1.13.0/lib/graphql/schema.rb:900:in `graphql_definition'
app/graphql/schema.rb:31:in `<main>'

----- bootsnap, puma, and other errors ( I don't think these are relevant so I've excluded them) ----

Completed 500 Internal Server Error in 1347ms (Views: 1.6ms | ActiveRecord: 54.0ms | Allocations: 360643)
```

</details>

Looking at the stack-trace again, I made a goof and didn't read it fully (and also cut-off pasting relevant error in my report above) as the it provides the exact line providing the error:
```
app/graphql/schema.rb:31:in '<main>'.
```

Below is my investigation before looking fully at the stack-trace:
I found two instances of `.graphql_definition` and `.to_graphql` in our implementation:

```ruby
module Extensions
  class PreventNull < GraphQL::Schema::FieldExtension
    def resolve(object:, arguments:, context:)
      result = yield(object, arguments, context)

      result = "" if result.nil? && field.type.to_graphql.to_s == "String!"

      return result
    end
  end
end
```

^ this was not the cause of the issue and works okay - but I'm wondering if you might have a better suggestion as to implement this?

and at the end of our schema file:

```ruby
class Schema < GraphQL::Schema
  query QueryType
  # Schema definition abbreviated... let me know if you need this info
end

Schema.graphql_definition
```

We have added the `.graphql_definition` to the Schema per this comment: https://github.com/rmosolgo/graphql-ruby/issues/1505#issuecomment-408209171 so that we can eagerly warm the cache at load time to better process requests. We're still uncertain if this can be safely removed, what are your thoughts/suggestions?

**Comment by joelzwarrington** [comment]
I'm going to be closing this issue as it was resolved by removing `Schema.graphql_definition` and I have been able to implement it in a way that works quite well.

As well `use GraphQL::Execution::Interpreter` and `use GraphQL::Analysis::AST` are both the default now, as adding them to the schema warned be.

@rmosolgo, thank you so much for this feature; it's a game changer! Managing breaking changes with this is going to be soooooooooooooo much easier and actually possible without insane amounts of code duplication and new fields. ❤️

**Comment by rmosolgo** [comment]
Thanks for sharing what you found, @joelzwarrington :+1: 

You can confidently remove `.graphql_definition` -- since 1.10, class-based schemas didn't use their legacy `.graphql_definition`s any more. 

I added deprecation warnings to every feature that _used_ `.graphql_definition`, but not to `.graphql_definition` itself 🤦 . I'll make sure to include that warning in 1.13.x before that method is removed entirely in GraphQL-Ruby 2.0.
