### ISSUE TITLE
Raise error / add a hook to check when illogical pagination params are supplied

### ISSUE THREAD

**Issue by vladiangelov** [rmosolgo/graphql-ruby#3742]
**Is your feature request related to a problem? Please describe.**

The out-of-the-box pagination params (`before`, `after`, `first` and `last`) can be supplied with illogical values / combinations, without raising an error. This leads to unexpected or even unpredictable behaviour. Also it can lead to wrong data being supplied, if we use the number of nodes returned to derive transient properties (i.e. averages) on a custom connections for example.

1. Supply conflicting pagination params together - i.e. (`first` and `before`) or (`last` and `after`)
2. Supply `first` and/or `last` a value of 0 or supply them together.
3. Supply an odd combination of the pagination params (i.e. three of them together).

**Describe the solution you'd like**

There are two potential solutions:
1. Throw errors when illogical parameters are supplied (needs an extensive list).
2. Implement a hook at schema level, which has access to pagination parameters that can then be customised and evaluated on a project-by-project basis.

**Describe alternatives you've considered**

We could create a custom connection that evaluates supplied pagination parameters, but that then needs to implement the `nodes`, `has_next_page`, etc. mandatory methods, then be added to all collection types and also maintained according to your internal code changes.

**Comment by rmosolgo** [comment]
Hi! I can understand why you'd want to check these arguments. I don't have plans to add any checks to the library, because AFAIK they aren't part of the spec, but if you want to add some constraints, you could hook into the library with a module like this: 

```ruby 
module CheckConnectionParams 
  def nodes 
    check_params 
    super 
  end 
  
  def has_next_page 
    check_params 
    super 
  end 

  def has_next_page
    check_params 
    super 
  end 

  private 
  
  def check_params 
    if !defined?(@params_checked)
      @params_checked = true 
      # check first, last, after, and before here 
    end 
  end 
end 
```

Then, prepend it in any connection implementations you're using: 

```ruby 
GraphQL::Pagination::ArrayConnection.prepend(CheckConnectionParams)
GraphQL::Pagination::RelationConnection.prepend(CheckConnectionParams)
GraphQL::Pro::StableRelationConnection.prepend(CheckConnectionParams)
# etc ... 
```

That would insert the checks you have in mind before those methods are called. I hope that helps!

**Comment by vladiangelov** [comment]
Thank you for that @rmosolgo - it will definitely be something for us to consider.
