### ISSUE TITLE
allow_blank with length validator not working as before

### ISSUE THREAD

**Issue by butsjoh** [rmosolgo/graphql-ruby#3745]
I am experiencing a similar issue with the length validator that might be related to https://github.com/rmosolgo/graphql-ruby/pull/3671

before the version bump: (i was on 1.12.16)

```
      argument :name, String, required: true, validates: {
        length: { allow_blank: false, maximum: 255 }
      }
```

When you give an empty string "" it would throw a validation error.

In the new version it does not, so i tried to adapt to:

```
      argument :name, String, required: true, validates: {
        length: { maximum: 255 }, allow_blank: false
      }
```

Still no validation error on blank string. Is this expected? I have the impression that multiple validations are consider || and not && and i don't see that in the documentation. Am i misunderstanding something?

_Originally posted by @butsjoh in https://github.com/rmosolgo/graphql-ruby/issues/3723#issuecomment-982791981_

**Comment by butsjoh** [comment]
I does work if i do the following

```
   argument :name, String, required: true, validates: {
        length: { minimum: 1, maximum: 255 }
      }

```

but then the error message changes from "name can't be blank" to "name is too short (minimum is 1)".

I agree that changing to minimum: 1 has the same intent as allow_blank: false but i was not expecting this to happend with the version bump.

**Comment by rmosolgo** [comment]
Thanks for opening this issue. I saw your previous comment and started investigating a fix... but I never wrote back. Sorry about that! The first thing I checked is, how does Rails handle it? I wrote up a script: 

```ruby
require "bundler/inline"

gemfile do
  gem "rails"
  gem "sqlite3"
  gem "pry"
end

require "active_record"
ActiveRecord::Base.establish_connection({ adapter: "sqlite3", database: ":memory:"
})
ActiveRecord::Schema.define do
  self.verbose = false

  create_table :foods, force: true do |t|
    t.column :name, :string
  end
end


class Food < ActiveRecord::Base
  validates :name, length: { maximum: 5 }, allow_blank: false
end

f = Food.new(name: "")
p [f.name, f.valid?, f.errors.full_messages]
# $ ruby rails_blank_test.rb
# ["", false, ["Name is too short (minimum is 1 character)"]]
```

I found that Rails treats `allow_blank: false` the _same_ as `minimum: 1`. Fair enough. 

(Interestingly, `allow_nil` is handled by making the _default_ error message: 

```ruby
class Food < ActiveRecord::Base
  validates :name, length: { maximum: 5 }, allow_nil: false
end

f = Food.new(name: nil)
p [f.name, f.valid?, f.errors.full_messages]
# $ ruby rails_blank_test.rb
# [nil, false, ["Name is too long (maximum is 5 characters)"]]
```

In any case, the change in behavior you noticed was accidental -- I'll push a fix for it. Thanks for reporting this!
