### ISSUE TITLE
Cursors in pageInfo return null when specified before hasNextPage/hasPreviousPage

### ISSUE THREAD

**Issue by davidbyttow** [rmosolgo/graphql-ruby#3753]
Similar to https://github.com/rmosolgo/graphql-ruby/issues/2972, but slightly nuanced. It appears that when cursors are specified before the boolean types, the cursors are returned as null.

**Versions**

`graphql` version: 1.12.21
`graphql-pro` version: 1.20.3
`graphql-batch` version: 0.4.3
`rails` (or other framework): 6.1.4.1

**GraphQL query**

This returns a start/endCursor appropriately:
```graphql
{
    products {
        items(first: 3) {
            pageInfo {
                hasNextPage
                hasPreviousPage
                startCursor
                endCursor
            }
            nodes {
                id
            }
        }
    }
}
```

**Steps to reproduce**
Swap the cursors with the pagination booleans.
```graphql
{
    products {
        items(first: 3) {
            pageInfo {
                startCursor
                endCursor
                hasNextPage
                hasPreviousPage
            }
            nodes {
                id
            }
        }
    }
}
```

**Expected behavior**

These should return the same results, IIRC.

**Actual behavior**

`startCursor` and `endCursor` return `null` in the reproduction case.

**Comment by rmosolgo** [comment]
Sorry! I overlooked a case when fixing #3735 and messed this up. I just released graphql-pro 1.20.4 with a fix for it. Please give it a try and let me know if you run into any more trouble. (This issue was also reported in #3752)
