### ISSUE TITLE
Implement Introspection types according to the standard Oct 2021

### ISSUE THREAD

**Issue by jdehaan** [rmosolgo/graphql-ruby#3757]
**Is your feature request related to a problem? Please describe.**

The latest Graphiql implementation uses an introspection query that is not working in the case of GraphQL ruby.
By looking a bit deeper into it I saw that parts of the [Schema Introspection Schema
](https://spec.graphql.org/October2021/#sec-Schema-Introspection.Schema-Introspection-Schema) are not implemented
- [__Schema: `description`](https://spec.graphql.org/October2021/#sec-The-__Schema-Type) is missing
- [__Type: `specifiedByUrl`](https://spec.graphql.org/October2021/#sec-The-__Type-Type) is missing

To make Graphiql work that would be enough but to be complete in implementing the latest standard also following fields are needed:
- [__Directive: `isRepeatable`](https://spec.graphql.org/October2021/#sec-The-__Directive-Type)
- [__DirectiveLocation: `VARIABLE_DEFINITION`](https://spec.graphql.org/October2021/#sec-The-__Directive-Type) enum value

**Describe the solution you'd like**

* Implement Introspection types according to the standard 
* Support Graphiql default introspection query (automatically there if introspection types are implemented)

**Related files in this repos**

* [ ] [__Schema](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/introspection/schema_type.rb)
* [ ] [__Type](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/introspection/type_type.rb)
* [ ] [__Directive](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/introspection/directive_type.rb)
* [ ] [__DirectiveLocation](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/introspection/directive_type.rb)

**Additional context**

I think this is maybe just the tip of the iceberg in order to support more up to date graphql toolsets. Graphiql being one of the most widespread.

**Comment by rmosolgo** [comment]
Thanks for reporting this! It should be straightforward to add these new attributes to schema members. I'll take a look soon if nobody else gets to it first.

**Comment by jdehaan** [comment]
I gave that a try myself, while it is not really difficult to add the corresponding items as "dummies", it is somehow unclear to me how to wire up correctly the things in order to make that usable as well in a proper manner and write the corresponding tests as well. I fear I need to dig deeper into the code until I can provide some merge-worthy PR....
