### ISSUE TITLE
Exception while dumping schema

### ISSUE THREAD

**Issue by teoljungberg** [rmosolgo/graphql-ruby#3764]
**Describe the bug**

As a part of our tooling, we dump the GraphQL schema to see deletions that we can give to our frontend developers to ensure that the deletions are sound. This stopped working with the following exception:

```
irb(main):004:1> SiteSchema.to_graphql.to_definition.class
.bundle/vendor/ruby/3.0.0/gems/graphql-1.13.0/lib/graphql/schema/warden.rb:176:in `block in arguments': wrong number of arguments (given 1, expected 0) (ArgumentError)
``` 

This looks like an internal error to GraphQL that is outside of our application.

**Versions**

`graphql` version: 1.13.0 (pro: 1.20.4)
`rails` (or other framework): 6.1.4.1

**Comment by rmosolgo** [comment]
Sorry for the trouble! Here's the context on that line in the backtrace: 

https://github.com/rmosolgo/graphql-ruby/blob/8d4cfb574e094a2c15dcaa5196717bbdd6a90040/lib/graphql/schema/warden.rb#L173-L178

Is there anything more in the backtrace than that? I wonder what's begin passed in that doesn't support the new `arguments(context)` signature 🤔

**Comment by rmosolgo** [comment]
Oh, I see you're calling `.to_graphql` before calling `.to_definition` -- I bet that's not supported well. What if you remove the `.to_graphql` call and just call `SiteSchema.to_definition`?  (Why are you calling `.to_graphql` first?)

**Comment by teoljungberg** [comment]
I have no idea why we built that in the first place, I can see that `SiteSchema.to_definition` works as it should though!

**Comment by rmosolgo** [comment]
:+1: Good to hear. I would certainly _expect_ those to have identical output. All features using legacy `.graphql_definition` objects have already been deprecated, and that method (which calls `.to_graphql` under the hood) will be deprecated in 1.13.1, so I recommend removing `.to_graphql` if possible. Would that work for you?

**Comment by teoljungberg** [comment]
Sure thing, that sounds fair to me. It would be good if these unsupported methods were to warn the user, somehow.

**Comment by rmosolgo** [comment]
> warn the user

Yeah, I made a mistake there. I deprecated all the old features that _used_ legacy objects, but underestimated how many direct uses of `.graphql_definition` there were out there. (And I didn't even consider `.to_graphql` -- I'll add a warning to that one, too!)

**Comment by teoljungberg** [comment]
Awesome, thanks for the quick turnaround!

**Comment by teoljungberg** [comment]
That was the full stacktrace from IRB btw.
