### ISSUE TITLE
Rubocop extension

### ISSUE THREAD

**Issue by cjoudrey** [rmosolgo/graphql-ruby#377]
It would be interesting to provide a set of Rubocop cops in the repo that people can optionally enable in their own `rubocop.yml` to do checks on their schema.

Some example checks:

- Naming conventions for Mutations and other parts of the Schema
- Relay conventions
  - All mutations should include a `clientMutationId` field
  - Mutations that remove nodes should include a `deletedId` field
  - Single `input` argument on mutations
- Detect breaking schema changes by comparing checked-in IDL with current commits IDL
- Detect N+1 (if possible) or provide tools to enable people to check this

Feel free to add more ideas.

cc @xuorig @Willianvdv @brandonblack 

**Edit:** Rubocop might not be a silver bullet here since in some cases we might have to run the Ruby code, for instance detecting N+1s with static code analysis might not be feasible.

**Comment by kdaigle** [comment]
cc @gjtorikian @josh

**Comment by josh** [comment]
Nice. I started working on some graphql-client specific cops already. https://github.com/github/graphql-client/tree/master/lib/rubocop/cop/graphql Would be rad to have some basic ones here as well.

**Comment by gjtorikian** [comment]
We don't have a cop for this (we use tests) but "has a description" would be grand, as well as conventions for resolve styling (`-> {...}` vs `do ... end`).

**Comment by Willianvdv** [comment]
What do you think about a linter that checks if the name of a mutation starts with capital letter?
 So:
```
# Good
AddCommentMutation = GraphQL::Relay::Mutation.define do
  name "AddComment"
end

# Bad
AddCommentMutation = GraphQL::Relay::Mutation.define do
  name "addComment"
end
```

**Comment by rmosolgo** [comment]
Also relevant: https://github.com/cjoudrey/graphql-schema-linter

**Comment by rmosolgo** [comment]
I have no plans to work on this but I would welcome suggestions here or in another issue if someone else wants to do it!

**Comment by DmitryTsepelev** [comment]
I've implemented some _graphql-ruby_ checks in [rubocop-graphql](https://github.com/DmitryTsepelev/rubocop-graphql), would be happy to hear back ideas and feedback
