### ISSUE TITLE
Undefined method 'key' for Graphql - context[:current_arguments]

### ISSUE THREAD

**Issue by bubbaspaarx** [rmosolgo/graphql-ruby#3779]
**Describe the bug**

Inside 'object_from_id' we would use the following method to extract the model for the request

```ruby
context[:current_arguments].key(id)
```

We now receive an error 'Undefined method 'key' for Graphql ' which appears to be related to a change here -
https://github.com/rmosolgo/graphql-ruby/pull/3665

Is there now an alternative to extract the model from context?

**Versions**

`graphql` version: 1.13.0

**Comment by rmosolgo** [comment]
Sorry for the trouble. One option is to get the underlying hash like this: 

```ruby
args_hash = context[:current_arguments].keyword_arguments
args_hash.key(id)
```

Alternatively, we could add `:key` to the list of delegated methods here:

https://github.com/rmosolgo/graphql-ruby/blob/097890bc6eaa2cd308d24be083afba9fa7a3c73c/lib/graphql/execution/interpreter/arguments.rb#L62

Happy to take a look into that approach if you prefer it, let me know what you think.

**Comment by bubbaspaarx** [comment]
Thank you for coming back. We just found this worked for a small test of our project

```ruby
model = context[:current_arguments].keys[0]
```

Not entirely sure how robust this will be though. I'll try your method above and report back

**Comment by bubbaspaarx** [comment]
I just tried your method and works absolutely fine and definitely more robust. Thank you for your help.

**Comment by rmosolgo** [comment]
Glad to hear it! Sorry for the trouble.
