### ISSUE TITLE
:+1: I guess this part should be expanded:

### ISSUE THREAD

**Issue by Mobina1419** [rmosolgo/graphql-ruby#3781]
:+1: I guess this part should be expanded:

![image](https://cloud.githubusercontent.com/assets/2231765/24482056/92d68dea-14bc-11e7-8d2f-cec95e6c0381.png)

There are also `BaseType#to_list_type` and `BaseType#to_non_null_type` if you prefer them!

_Originally posted by @rmosolgo in https://github.com/rmosolgo/graphql-ruby/issues/648#issuecomment-290264597_

**Comment by rmosolgo** [comment]
Hi! That's a very old doc for part of GraphQL-Ruby that's now deprecated. I don't plan to update it.
