### ISSUE TITLE
Runtime invalidates nullable variable passed to non-null argument that has a default value

### ISSUE THREAD

**Issue by ivanbrennan** [rmosolgo/graphql-ruby#3793]
**Describe the bug**

If the schema provides a default value for a non-Null argument, e.g. a default `sort`
```graphql
songs(sort: SongSort! = {name: asc}): [Song!]!
```
a client query that passes a nullable variable to that argument, e.g.
```graphql
query($sort: SongSort) {
  songs(sort: $sort) {
    name
  }
}
```
should be considered valid, and the argument's default value applied. Instead, the runtime is invalidating such a query:
```json
{"errors":[{"message":"Nullability mismatch on variable $sort and argument sort (SongSort / SongSort!)","locations":[{"line":2,"column":9}],"path":["query","songs","sort"],"extensions":{"code":"variableMismatch","variableName":"sort","typeName":"SongSort","argumentName":"sort","errorMessage":"Nullability mismatch"}}]}
```

According to the spec,
> An argument is required if the argument type is non-null and does not have a default value. Otherwise, the argument is optional.

https://spec.graphql.org/October2021/#sec-Required-Arguments.Explanatory-Text

The spec also describes how to validate a variable's type against the argument it's being passed to, confirming the above statement.
https://spec.graphql.org/October2021/#IsVariableUsageAllowed()

Btw, thank you for all your great work! I've tried to make my description clear and direct. I wasn't sure at first whether this was a bug or a misunderstanding on my part, but after reading through the relevant sections of the spec (linked above), I think it's a bug.

**Versions**

`graphql` version: 1.13.2
`rails` (or other framework): 6.1.3.1

**GraphQL schema**

```graphql
type Query {
  songs(sort: SongSort! = {name: asc}): [Song!]!
}

type Song {
  name: String!
}

input SongSort {
  name: SortDirection
}

enum SortDirection {
  asc
  desc
}
```

**GraphQL query**

The runtime correctly applies the default argument value if a client query makes no mention of `sort`:
```graphql
query {
  songs {
    name
  }
}
```
```json
{"data":{"songs":[{"name":"A"},{"name":"B"}]}}
```

The runtime incorrectly rejects a query that declares a nullable `sort` variable:
```graphql
query($sort: SongSort) {
  songs(sort: $sort) {
    name
  }
}
```
```json
{"errors":[{"message":"Nullability mismatch on variable $sort and argument sort (SongSort / SongSort!)","locations":[{"line":1,"column":32}],"path":["query","songs","sort"],"extensions":{"code":"variableMismatch","variableName":"sort","typeName":"SongSort","argumentName":"sort","errorMessage":"Nullability mismatch"}}]}
```

A sub-optimal workaround is for the client query to also declare a default value:
```graphql
query($sort: SongSort = {name: asc}) {
  songs(sort: $sort) {
    name
  }
}
```
But that means we're declaring default values on the server (argument) and the client (variable).

**Steps to reproduce**

Steps to reproduce the behavior
```ruby
schema_graphql = <<~GRAPHQL
  type Query {
    songs(sort: SongSort! = {name: asc}): [Song!]!
  }

  type Song {
    name: String!
  }

  input SongSort {
    name: SortDirection
  }

  enum SortDirection {
    asc
    desc
  }
GRAPHQL

class Song
  def self.order(**exprs)
    names = ["asc", nil].include?(exprs[:name]) ? ["A", "B"] : ["B", "A"]
    names.map { |name| Struct.new(:name).new(name) }
  end
end

schema = GraphQL::Schema.from_definition(
  schema_graphql,
  default_resolve: {
    "Query" => {
      "songs" => ->(obj, args, ctx) { Song.order(args[:sort].to_h) }
    }
  }
)

puts schema.execute(
  "query($sort: SongSort) { songs(sort: $sort) { name } }",
  variables: {}
).to_json
```
**Expected behavior**

The `sort` argument's default value is applied, and results are sorted by name ascending:
```json
{"data":{"songs":[{"name":"A"},{"name":"B"}]}}
```

**Actual behavior**

The runtime rejects the query as invalid:
```json
{"errors":[{"message":"Nullability mismatch on variable $sort and argument sort (SongSort / SongSort!)","locations":[{"line":1,"column":32}],"path":["query","songs","sort"],"extensions":{"code":"variableMismatch","variableName":"sort","typeName":"SongSort","argumentName":"sort","errorMessage":"Nullability mismatch"}}]}
```

**Comment by rmosolgo** [comment]
Thanks for the detailed writeup! I think you're right about how it should work, especially this part from the section you linked above: 

> - If locationType is a non-null type AND variableType is NOT a non-null type:
>     - Let hasNonNullVariableDefaultValue be true if a default value exists for variableDefinition and is not the value null.
>     - Let **hasLocationDefaultValue be true if a default value exists for the Argument** or ObjectField where variableUsage is located.

emphasis mine -- that's what _should_ apply here, but evidently doesn't. I'll take a look soon and update it! In the meantime, if you get to take a look, we should also take care to see that, besides fixing the static validation, the default value is correctly applied at runtime.
