### ISSUE TITLE
GraphQL::Relay::BaseConnection (used for GraphQL::Relay::RelationConnection) will be removed from GraphQL-Ruby 2.0, use GraphQL::Pagination::Connections instead: https://graphql-ruby.org/pagination/overview.html

### ISSUE THREAD

**Issue by JasonBarnabe** [rmosolgo/graphql-ruby#3796]
**Describe the bug**

Trying to upgrade from graphql 1.11.10 to 1.12.23. Running my test suite, I get multiple messages output:

```
GraphQL::Relay::BaseConnection (used for GraphQL::Relay::RelationConnection) will be removed from GraphQL-Ruby 2.0, use GraphQL::Pagination::Connections instead: https://graphql-ruby.org/pagination/overview.html
```

This seems to be because [RelationConnection is registered as the implementation for ActiveRecord::Relation](https://github.com/rmosolgo/graphql-ruby/blob/c44aee192734a3b762d6030ed4a1cb352724ffc9/lib/graphql/relay/relation_connection.rb#L182), and [it inherits from BaseConnection](https://github.com/rmosolgo/graphql-ruby/blob/c44aee192734a3b762d6030ed4a1cb352724ffc9/lib/graphql/relay/relation_connection.rb#L8).

This all seems to be defined in graphql rather than anything in my project. Am I supposed to make changes to something in my project to resolve? Ignore until graphql 2.0? Something else?

**Versions**

`graphql` version: 1.12.23
`rails` (or other framework): 6.1.4.4
`graphql-batch`: 0.4.3

**Comment by rmosolgo** [comment]
Hi! Hmmm, that warning is emitted at _runtime_, which means some graphql query is definitely _using_ `Relay::RelationConnection`: 

https://github.com/rmosolgo/graphql-ruby/blob/c44aee192734a3b762d6030ed4a1cb352724ffc9/lib/graphql/relay/base_connection.rb#L62

This might happen if you manually disable the new connections module in your schema: 

```ruby 
class MySchema < GraphQL::Schema 
  # ...
  self.connections = nil 
end 
```

Does your schema have a config like that? That module will be required (the only option) in GraphQL-Ruby 2.0, so it's worth figuring out how to enable it.

**Comment by rmosolgo** [comment]
Please let me know if you find any more clues on this one!
