### ISSUE TITLE
[PRO] GraphQL::UnauthorizedError

### ISSUE THREAD

**Issue by danlo** [rmosolgo/graphql-ruby#3801]
**Is your feature request related to a problem? Please describe.**

When an GraphQL::UnauthorizedError is raised, I would like to have access to the GraphQL query that invoked the issue for a more complete bug report.

**Describe the solution you'd like**

GraphQL::UnauthorizedError would support a "query" attribute to contain the GraphQL query in question.

**Describe alternatives you've considered**

The GraphQL query string is available on the client side of the request and can be processed there when an authorization error is encountered.

**Additional context**

While the GraphQL query, context, and everything else is available on the client side.  I'm not sure this is a good idea to handle error reporting there.  In the (hopefully) unlikely event a program/machine was compromised, I would rather error messages about security issues were fully answered and reported from the server rather than the client.  This would provide less information to the compromised program/machine.  Much in the same manner, "forgot password" should not say "Email account was not found" (which verifies that the email is NOT present on the site in question)

**Comment by rmosolgo** [comment]
Hey, thanks for the suggestion! It looks like this error already has a `.context` attribute:

https://github.com/rmosolgo/graphql-ruby/blob/c44aee192734a3b762d6030ed4a1cb352724ffc9/lib/graphql/unauthorized_error.rb#L14-L15

So, I'd _expect_ 

```
error.context.query # => #<GraphQL::Query ...>
```

to return the `GraphQL::Query` instance that raised the error. Would that work in your case?

**Comment by danlo** [comment]
I would have no objection to that, you are more familiar with how various graphql platforms work.  

I believe that the below option is forward compatible and prevents an overlap in which someone passes a "query" field in the context and then it is overwritten by the query we are adding to it.  This may mean more work, however, 100% prevents any future name collisions. 

https://github.com/rmosolgo/graphql-ruby/blob/c44aee192734a3b762d6030ed4a1cb352724ffc9/lib/graphql/unauthorized_error.rb#L14-L28

```
    # @return [GraphQL::Query::Context] the context for the current query
    attr_accessor :context
  
    # @return [String] query
    attr_reader :query

    def initialize(message = nil, object: nil, type: nil, context: nil, query: nil)
      if message.nil? && object.nil? && type.nil?
        raise ArgumentError, "#{self.class.name} requires either a message or keywords"
      end

      @object = object
      @type = type
      @context = context
      @query = query
      message ||= "An instance of #{object.class} failed #{type.graphql_name}'s authorization check"
      super(message)
    end
```

**Comment by rmosolgo** [comment]
Did `context.query` work for you? If you're looking for the query _string_, then you might want `context.query.query_string` instead. 

I'd rather not add `query:` to `def initialize` because it's redundant with `context:`. (That is, there's no need to add `query:` to the initializer since it's already accessible as `context.query`.) 

Anyways, if getting to the query via `context` didn't work for you, let me know what happened when you tried it and we'll see where we can go from there!
