### ISSUE TITLE
Erro on principal node is object

### ISSUE THREAD

**Issue by heliocaruccio** [rmosolgo/graphql-ruby#3807]
Hi! I using gem 'graphql-batch'. In my query value returned is one object `Project.find(id)`

This schema return one error

`Failed to build a GraphQL list result for field `Project.Items` at path `project.items`.\nExpected `#<BatchLoader::GraphQL:0x000055f6101402b0 @batch_loader=#<BatchLoader:0x62120>>` (BatchLoader::GraphQL) to implement `.each` to satisfy the GraphQL return type `[Item!]`.\n"`

field :items, [Types::ItemType], null: true

def items
      BatchLoader::GraphQL.for(object.id).batch(default_value: []) do |project_ids, loader|
        Item.where(project_id: project_ids).each do |data|
          loader.call(data.project_id) { |memo| memo << data }
        end
      end
end

One ideia?

**Comment by rmosolgo** [comment]
Hi! 

A couple of questions: 

- what version of graphql-ruby are you using? 
- did you setup graphql batch with `use GraphQL::Batch` in your schema definition?

**Comment by heliocaruccio** [comment]
>

**Comment by heliocaruccio** [comment]
Hi @rmosolgo 
Tested in 1.11.4 and 1.13.2
Yes `use GraphQL::Batch` is set. 

It works when projects are a array

**Comment by heliocaruccio** [comment]
Sorry my error. Set only in an inherited class
