### ISSUE TITLE
graphql-ruby-client TS error "Cannot find module '@rails/actioncable' or its corresponding type declarations." (not a bug, more FYI)

### ISSUE THREAD

**Issue by escapedcat** [rmosolgo/graphql-ruby#3812]
**Describe the bug**
This started to happen with `1.10.5`.   

```bash
$ tsc --noEmit
node_modules/graphql-ruby-client/subscriptions/ActionCableLink.d.ts:3:31 - error TS2307: Cannot find module '@rails/actioncable' or its corresponding type declarations.

3 import type { Consumer } from "@rails/actioncable";
                                ~~~~~~~~~~~~~~~~~~~~


Found 1 error.
```

[According to the changelog](https://github.com/rmosolgo/graphql-ruby/blob/master/javascript_client/CHANGELOG.md#1105-17-dec-2021) the `actioncable`-package was switched. This explains the error.\
I assume this should have been a *breaking change*?  

## Solution

1. Install these packages (remove the two old ones):
    * [@rails/actioncable](https://www.npmjs.com/package/@rails/actioncable) 
    * [@types/rails__actioncable](https://www.npmjs.com/package/@types/rails__actioncable)

1. [Switch to new actioncable](https://edgeguides.rubyonrails.org/action_cable_overview.html#client-side-logging)
   ```js
     import * as ActionCable from '@rails/actioncable'
   ```

**Versions**
```
    "graphql": "^15.8.0",
    "graphql-ruby-client": "^1.9.3",
```

**Steps to reproduce**
- `yarn`
- `tsc --noEmit`

**Comment by rmosolgo** [comment]
I think what is, is that the client code _requires_ those packages. But I didn't add them to `"dependencies": ...` in package.json because you only need them if you're using actioncable subscription, not if you're using the other features of the javascript client.

Are you using ActionCable in your project? Was `@rails/actioncable` already in your `package.json`?

**Comment by escapedcat** [comment]
> I think what is, is that the client code _requires_ those packages. But I didn't add them to `"dependencies": ...` in package.json because you only need them if you're using actioncable subscription, not if you're using the other features of the javascript client.

I think not adding them as dependencies is fine. `actioncable` also wasn't one.

> Are you using ActionCable in your project? Was `@rails/actioncable` already in your `package.json`?

We used these before:  
```json
    "@types/actioncable": "^5.2.7",
    "actioncable": "^5.2.6",
```
We needed to switch to the new packages. That's pretty much it.  
Just didn't expect this to be *patch*-version I guess.
