### ISSUE TITLE
Introspection miss deprecated field args and input object fields

### ISSUE THREAD

**Issue by gael-ian** [rmosolgo/graphql-ruby#3814]
Hello,

Built-in schema inspection allow to explicitly include or exclude deprecated fields on an object and deprecated values on a enum but the same is not supported on input type fields nor field arguments.

In the [example implementation in `graphql-js`](https://github.com/graphql/graphql-js/blob/main/src/type/introspection.ts), referenced on graphql.org, it looks like a boolean `includeDeprecated` argument is supported for object fields, input object fields, field arguments and enum values.

Without an equivalent support in `graphql-ruby`, deprecated fields / arguments are not shown in GraphiQL and introspection can't be used to detect (and warn developpers about) uses of them.

````graphql
{
  __schema {
    types {
      name
      
      enumValues(includeDeprecated: true) {
        name
        deprecationReason
      }
      
      fields(includeDeprecated: true) {
        name
        deprecationReason
        # Should support the same `includeDeprecated: Boolean` argument
        args {
          name
          # deprecationReason is not exposed here
        }
      }
      
      # Should support the same `includeDeprecated: Boolean` argument
      inputFields {
        name
        # deprecationReason is not exposed here
      }
    }
  }
}
````

**Comment by gael-ian** [comment]
I tried to add the missing arguments to my query and run it in GraphiQL (_via_ 'graphiql-rails ~> 1.4.11'):

````graphql
{
  __schema {
    types {
      name
      enumValues(includeDeprecated: true) {
        name
        deprecationReason
      }
      fields(includeDeprecated: true) {
        name
        deprecationReason
        args(includeDeprecated: true) {
          name
          deprecationReason
        }
      }
      inputFields(includeDeprecated: true) {
        name
        deprecationReason
      }
    }
  }
}
````

The `graphql-ruby` server (running ~> 1.12.0) responds without errors. The question becomes why GraphiQL does not show these arguments in its `__Type` documentation…

Sorry to have missed that :/

**Comment by rmosolgo** [comment]
Glad to hear the server is working alright, thanks for checking into it. Maybe it needs a newer graphiql versions, it looks like that was changed recently: https://github.com/graphql/graphiql/blob/main/packages/graphiql/CHANGELOG.md#159

Anyways, let me know if anything else comes up server-side!
