### ISSUE TITLE
Adding default key to validators

### ISSUE THREAD

**Issue by ab320012** [rmosolgo/graphql-ruby#3817]
**Is your feature request related to a problem? Please describe.**

I need to add a default value to the validations
**Describe the solution you'd like**
I'd like to see something like this as an interface
```
      argument :limit, Int, required: false, description: 'Number of records to limit on each pull.',
                            validates: { numericality: { less_than_or_equal_to: 100, default: 100 } }
```
**Describe alternatives you've considered**

**Additional context**

**Comment by rmosolgo** [comment]
Hi! What does `default` do there? How is it different from `argument :limit, Int, ..., default_value: 100`?

**Comment by rmosolgo** [comment]
Let me know if you want to discus this further :+1:
