### ISSUE TITLE
1.13.3 regresssion NoMethodError: undefined method '>' for nil:NilClass

### ISSUE THREAD

**Issue by jeffperrin** [rmosolgo/graphql-ruby#3821]
**Describe the bug**

After updating from `1.13.2` to `1.13.3` I started receiving `NoMethodError: undefined method '>' for nil:NilClass` when calling `MyAppSchema.execute(...)`. This only appears to happen when queries have a node with pagination 

**Versions**

`graphql` version: 1.13.3
`rails` (or other framework): Rails 6.1
other applicable versions (`graphql-batch`, etc)

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok).
Are you using [interpreter](https://graphql-ruby.org/queries/interpreter.html)? Any custom instrumentation, etc?

We're using new relic:

```ruby
class MyAppSchema < GraphQL::Schema
  mutation(Types::MutationType)
  query(Types::QueryType)

  # add better new relic tracing: https://graphql-ruby.org/queries/tracing.html#new-relic
  use GraphQL::Tracing::NewRelicTracing, set_transaction_name: true
end
```

```ruby
class Types::UserType < Types::BaseObject
  field :id, ID, null: false
  field :lab_requisitions, Types::LabRequisitionType.connection_type, "Lab requisitions for this user", null: false
end
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

The following query will fail:

```graphql
{
	user(id: 999) {
		id
		labRequisitions {
			nodes { id }
		}
	}
}
```

But this will work:

```graphql
{
	user(id: 999) {
		id
	}
}
```

**Steps to reproduce**

Update to 1.13.3 and run a graphql query that uses pagination

**Expected behavior**

Query should work

**Actual behavior**

Receive a non-useful error from graphql-ruby: `NoMethodError: undefined method '>' for nil:NilClass` when calling `MyAppSchema.execute`. There is nothing else in the backtrace.

**Comment by keithlayne** [comment]
Doing some quick debugging:

In the error I immediately hit, there is no limit or offset specified, and the mutation (in this case) has no pagination parameters.

I get here:

https://github.com/rmosolgo/graphql-ruby/blob/f91fe9a4ec9d81f807c07e8f37b6a2622bd08ec6/lib/graphql/pagination/relation_connection.rb#L211

And `relation_limit` is `nil`, which throws the error. 

Certainly looks like tests are covering the no-param case, so it's not overly clear to me what's going on without some more digging.

**Comment by rmosolgo** [comment]
Hi! could you please share the full backtrace for the error? That would really help me understand what graphql-ruby was doing when it caused the error.

**Comment by keithlayne** [comment]
<details>
  <summary>backtrace</summary>
<code><pre>
16:57:33 rails.1 |   ↳ app/models/network.rb:58:in `for_user'
16:57:33 rails.1 | undefined method `>' for nil:NilClass
/gems/graphql-1.13.3/lib/graphql/pagination/relation_connection.rb:106:in `set_limit'
/gems/graphql-1.13.3/lib/graphql/pagination/active_record_relation_connection.rb:64:in `set_limit'
/gems/graphql-1.13.3/lib/graphql/pagination/relation_connection.rb:211:in `limited_nodes'
/gems/graphql-1.13.3/lib/graphql/pagination/relation_connection.rb:219:in `load_nodes'
/gems/graphql-1.13.3/lib/graphql/pagination/relation_connection.rb:9:in `nodes'
/gems/graphql-1.13.3/lib/graphql/pagination/connection.rb:130:in `edges'
/gems/graphql-1.13.3/lib/graphql/types/relay/connection_behaviors.rb:160:in `edges'
/gems/graphql-1.13.3/lib/graphql/schema/field.rb:821:in `public_send'
/gems/graphql-1.13.3/lib/graphql/schema/field.rb:821:in `block in public_send_field'
/gems/graphql-1.13.3/lib/graphql/schema/field.rb:913:in `block in with_extensions'
/gems/graphql-1.13.3/lib/graphql/schema/field.rb:949:in `block (2 levels) in run_extensions_before_resolve'
/gems/graphql-1.13.3/lib/graphql/schema/field.rb:952:in `run_extensions_before_resolve'
/gems/graphql-1.13.3/lib/graphql/schema/field.rb:949:in `block in run_extensions_before_resolve'
/gems/graphql-1.13.3/lib/graphql/schema/field_extension.rb:137:in `resolve'
/gems/graphql-1.13.3/lib/graphql/schema/field.rb:936:in `run_extensions_before_resolve'
/gems/graphql-1.13.3/lib/graphql/schema/field.rb:908:in `with_extensions'
/gems/graphql-1.13.3/lib/graphql/schema/field.rb:796:in `public_send_field'
/gems/graphql-1.13.3/lib/graphql/schema/field.rb:710:in `block in resolve'
/gems/graphql-1.13.3/lib/graphql/schema.rb:118:in `after_lazy'
/gems/graphql-1.13.3/lib/graphql/schema/field.rb:708:in `resolve'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:510:in `block (4 levels) in evaluate_selection_with_args'
/gems/graphql-1.13.3/lib/graphql/tracing.rb:66:in `trace'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:509:in `block (3 levels) in evaluate_selection_with_args'
/gems/graphql-1.13.3/lib/graphql/query.rb:366:in `block in with_error_handling'
/gems/graphql-1.13.3/lib/graphql/execution/errors.rb:107:in `with_error_handling'
/gems/graphql-1.13.3/lib/graphql/query.rb:365:in `with_error_handling'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:508:in `block (2 levels) in evaluate_selection_with_args'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:796:in `resolve_with_directives'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:505:in `block in evaluate_selection_with_args'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:899:in `after_lazy'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:439:in `evaluate_selection_with_args'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:427:in `evaluate_selection'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:358:in `block (2 levels) in evaluate_selections'
/gems/graphql-1.13.3/lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:357:in `block in evaluate_selections'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:356:in `each'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:356:in `evaluate_selections'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:738:in `block (3 levels) in continue_field'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:796:in `resolve_with_directives'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:737:in `block (2 levels) in continue_field'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:189:in `tap_or_each'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:728:in `block in continue_field'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:899:in `after_lazy'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:714:in `continue_field'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:519:in `block (3 levels) in evaluate_selection_with_args'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:899:in `after_lazy'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:516:in `block (2 levels) in evaluate_selection_with_args'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:796:in `resolve_with_directives'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:505:in `block in evaluate_selection_with_args'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:899:in `after_lazy'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:439:in `evaluate_selection_with_args'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:431:in `block in evaluate_selection'
/gems/graphql-1.13.3/lib/graphql/schema/member/has_arguments.rb:204:in `block (3 levels) in coerce_arguments'
/gems/graphql-1.13.3/lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'
/gems/graphql-1.13.3/lib/graphql/schema/member/has_arguments.rb:185:in `block (2 levels) in coerce_arguments'
/gems/graphql-1.13.3/lib/graphql/schema/member/has_arguments.rb:184:in `each'
/gems/graphql-1.13.3/lib/graphql/schema/member/has_arguments.rb:184:in `block in coerce_arguments'
/gems/graphql-1.13.3/lib/graphql/schema/member/has_arguments.rb:213:in `coerce_arguments'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/arguments_cache.rb:50:in `dataload_for'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:430:in `evaluate_selection'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:358:in `block (2 levels) in evaluate_selections'
/gems/graphql-1.13.3/lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:357:in `block in evaluate_selections'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:356:in `each'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:356:in `evaluate_selections'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:738:in `block (3 levels) in continue_field'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:796:in `resolve_with_directives'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:737:in `block (2 levels) in continue_field'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:189:in `tap_or_each'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:728:in `block in continue_field'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:899:in `after_lazy'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:714:in `continue_field'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:519:in `block (3 levels) in evaluate_selection_with_args'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:899:in `after_lazy'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:516:in `block (2 levels) in evaluate_selection_with_args'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:796:in `resolve_with_directives'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:505:in `block in evaluate_selection_with_args'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:899:in `after_lazy'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:439:in `evaluate_selection_with_args'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:427:in `evaluate_selection'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:358:in `block (2 levels) in evaluate_selections'
/gems/graphql-1.13.3/lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:357:in `block in evaluate_selections'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:356:in `each'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:356:in `evaluate_selections'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:738:in `block (3 levels) in continue_field'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:796:in `resolve_with_directives'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:737:in `block (2 levels) in continue_field'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:189:in `tap_or_each'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:728:in `block in continue_field'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:899:in `after_lazy'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:714:in `continue_field'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:519:in `block (3 levels) in evaluate_selection_with_args'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:899:in `after_lazy'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:516:in `block (2 levels) in evaluate_selection_with_args'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:796:in `resolve_with_directives'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:505:in `block in evaluate_selection_with_args'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:899:in `after_lazy'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:439:in `evaluate_selection_with_args'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:431:in `block in evaluate_selection'
/gems/graphql-1.13.3/lib/graphql/schema/member/has_arguments.rb:204:in `block (3 levels) in coerce_arguments'
/gems/graphql-1.13.3/lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'
/gems/graphql-1.13.3/lib/graphql/schema/member/has_arguments.rb:185:in `block (2 levels) in coerce_arguments'
/gems/graphql-1.13.3/lib/graphql/schema/member/has_arguments.rb:184:in `each'
/gems/graphql-1.13.3/lib/graphql/schema/member/has_arguments.rb:184:in `block in coerce_arguments'
/gems/graphql-1.13.3/lib/graphql/schema/member/has_arguments.rb:213:in `coerce_arguments'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/arguments_cache.rb:50:in `dataload_for'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:430:in `evaluate_selection'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:358:in `block (2 levels) in evaluate_selections'
/gems/graphql-1.13.3/lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:357:in `block in evaluate_selections'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:356:in `each'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:356:in `evaluate_selections'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:230:in `block (4 levels) in run_eager'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:796:in `resolve_with_directives'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:229:in `block (3 levels) in run_eager'
/gems/graphql-1.13.3/lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:227:in `block (2 levels) in run_eager'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:189:in `tap_or_each'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:218:in `block in run_eager'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:796:in `resolve_with_directives'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter/runtime.rb:209:in `run_eager'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter.rb:73:in `block in evaluate'
/gems/graphql-1.13.3/lib/graphql/tracing.rb:66:in `trace'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter.rb:72:in `evaluate'
/gems/graphql-1.13.3/lib/graphql/execution/interpreter.rb:48:in `begin_query'
/gems/graphql-1.13.3/lib/graphql/execution/multiplex.rb:85:in `begin_query'
/gems/graphql-1.13.3/lib/graphql/execution/multiplex.rb:104:in `block (2 levels) in run_as_multiplex'
/gems/graphql-1.13.3/lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'
/gems/graphql-1.13.3/lib/graphql/execution/multiplex.rb:104:in `block in run_as_multiplex'
/gems/graphql-1.13.3/lib/graphql/execution/multiplex.rb:103:in `each'
/gems/graphql-1.13.3/lib/graphql/execution/multiplex.rb:103:in `each_with_index'
/gems/graphql-1.13.3/lib/graphql/execution/multiplex.rb:103:in `run_as_multiplex'
/gems/graphql-1.13.3/lib/graphql/execution/multiplex.rb:63:in `block (2 levels) in run_queries'
/gems/graphql-1.13.3/lib/graphql/execution/multiplex.rb:211:in `block in instrument_and_analyze'
/gems/graphql-1.13.3/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
/gems/graphql-1.13.3/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
/gems/graphql-1.13.3/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
/gems/graphql-1.13.3/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
/gems/graphql-1.13.3/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
/gems/graphql-1.13.3/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
/gems/graphql-1.13.3/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
/gems/graphql-1.13.3/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
/gems/graphql-1.13.3/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
/gems/graphql-1.13.3/lib/graphql/execution/multiplex.rb:190:in `instrument_and_analyze'
/gems/graphql-1.13.3/lib/graphql/execution/multiplex.rb:62:in `block in run_queries'
/gems/graphql-1.13.3/lib/graphql/tracing.rb:66:in `trace'
/gems/graphql-1.13.3/lib/graphql/execution/multiplex.rb:60:in `run_queries'
/gems/graphql-1.13.3/lib/graphql/execution/multiplex.rb:50:in `run_all'
/gems/graphql-1.13.3/lib/graphql/schema.rb:1760:in `multiplex'
/gems/graphql-1.13.3/lib/graphql/schema.rb:1731:in `execute'
16:57:33 rails.1 | /Users/keith/fc/neo-rails/app/controllers/graphql_controller.rb:14:in `execute'
/gems/actionpack-6.1.4.4/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/gems/actionpack-6.1.4.4/lib/abstract_controller/base.rb:228:in `process_action'
/gems/actionpack-6.1.4.4/lib/action_controller/metal/rendering.rb:30:in `process_action'
/gems/actionpack-6.1.4.4/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/gems/activesupport-6.1.4.4/lib/active_support/callbacks.rb:106:in `run_callbacks'
/gems/actionpack-6.1.4.4/lib/abstract_controller/callbacks.rb:41:in `process_action'
/gems/actionpack-6.1.4.4/lib/action_controller/metal/rescue.rb:22:in `process_action'
/gems/actionpack-6.1.4.4/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
/gems/activesupport-6.1.4.4/lib/active_support/notifications.rb:203:in `block in instrument'
/gems/activesupport-6.1.4.4/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/gems/activesupport-6.1.4.4/lib/active_support/notifications.rb:203:in `instrument'
/gems/actionpack-6.1.4.4/lib/action_controller/metal/instrumentation.rb:33:in `process_action'
/gems/actionpack-6.1.4.4/lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
/gems/activerecord-6.1.4.4/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/gems/actionpack-6.1.4.4/lib/abstract_controller/base.rb:165:in `process'
/gems/actionview-6.1.4.4/lib/action_view/rendering.rb:39:in `process'
/gems/actionpack-6.1.4.4/lib/action_controller/metal.rb:190:in `dispatch'
/gems/actionpack-6.1.4.4/lib/action_controller/metal.rb:254:in `dispatch'
/gems/actionpack-6.1.4.4/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
/gems/actionpack-6.1.4.4/lib/action_dispatch/routing/route_set.rb:33:in `serve'
/gems/actionpack-6.1.4.4/lib/action_dispatch/journey/router.rb:50:in `block in serve'
/gems/actionpack-6.1.4.4/lib/action_dispatch/journey/router.rb:32:in `each'
/gems/actionpack-6.1.4.4/lib/action_dispatch/journey/router.rb:32:in `serve'
/gems/actionpack-6.1.4.4/lib/action_dispatch/routing/route_set.rb:842:in `call'
/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
/gems/rack-2.2.3/lib/rack/conditional_get.rb:40:in `call'
/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
/gems/actionpack-6.1.4.4/lib/action_dispatch/http/permissions_policy.rb:22:in `call'
/gems/actionpack-6.1.4.4/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
/gems/actionpack-6.1.4.4/lib/action_dispatch/middleware/cookies.rb:689:in `call'
/gems/activerecord-6.1.4.4/lib/active_record/migration.rb:601:in `call'
/gems/actionpack-6.1.4.4/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
/gems/activesupport-6.1.4.4/lib/active_support/callbacks.rb:98:in `run_callbacks'
/gems/actionpack-6.1.4.4/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/gems/actionpack-6.1.4.4/lib/action_dispatch/middleware/executor.rb:14:in `call'
/gems/actionpack-6.1.4.4/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
/gems/sentry-rails-4.8.3/lib/sentry/rails/rescued_exception_interceptor.rb:12:in `call'
/gems/actionpack-6.1.4.4/lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
/gems/sentry-ruby-core-4.8.3/lib/sentry/rack/capture_exceptions.rb:25:in `block in call'
/gems/sentry-ruby-core-4.8.3/lib/sentry/hub.rb:58:in `with_scope'
/gems/sentry-ruby-core-4.8.3/lib/sentry-ruby.rb:238:in `with_scope'
/gems/sentry-ruby-core-4.8.3/lib/sentry/rack/capture_exceptions.rb:16:in `call'
/gems/actionpack-6.1.4.4/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/gems/railties-6.1.4.4/lib/rails/rack/logger.rb:37:in `call_app'
/gems/railties-6.1.4.4/lib/rails/rack/logger.rb:26:in `block in call'
/gems/activesupport-6.1.4.4/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/gems/activesupport-6.1.4.4/lib/active_support/tagged_logging.rb:37:in `tagged'
/gems/activesupport-6.1.4.4/lib/active_support/tagged_logging.rb:99:in `tagged'
/gems/railties-6.1.4.4/lib/rails/rack/logger.rb:26:in `call'
/gems/actionpack-6.1.4.4/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/gems/actionpack-6.1.4.4/lib/action_dispatch/middleware/request_id.rb:26:in `call'
/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
/gems/activesupport-6.1.4.4/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/gems/actionpack-6.1.4.4/lib/action_dispatch/middleware/executor.rb:14:in `call'
/gems/actionpack-6.1.4.4/lib/action_dispatch/middleware/static.rb:24:in `call'
/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
/gems/actionpack-6.1.4.4/lib/action_dispatch/middleware/host_authorization.rb:119:in `call'
/gems/vite_ruby-3.0.7/lib/vite_ruby/dev_server_proxy.rb:22:in `perform_request'
/gems/rack-proxy-0.7.2/lib/rack/proxy.rb:67:in `call'
/gems/railties-6.1.4.4/lib/rails/engine.rb:539:in `call'
/gems/puma-5.5.2/lib/puma/configuration.rb:249:in `call'
/gems/puma-5.5.2/lib/puma/request.rb:77:in `block in handle_request'
/gems/puma-5.5.2/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
/gems/puma-5.5.2/lib/puma/request.rb:76:in `handle_request'
/gems/puma-5.5.2/lib/puma/server.rb:447:in `process_client'
/gems/puma-5.5.2/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
16:57:33 rails.1 | Completed 500 Internal Server Error in 248ms (Views: 3.2ms | ActiveRecord: 8.6ms | Allocations: 12302)
</pre></code>
</details>

I just tried to clean that up a little. I know I have plenty more going on that a tiny repro in my app, but hope that helps.

**Comment by rmosolgo** [comment]
Thanks, that's really helpful! I'll take a look 👀

**Comment by jeffperrin** [comment]
Thanks for the quick turnaround @rmosolgo and your help debugging @keithlayne. I can confirm that `1.13.4` fixes the issue.
