### ISSUE TITLE
AnyCable JS Client Support

### ISSUE THREAD

**Issue by KieranP** [rmosolgo/graphql-ruby#3825]
Currently, the graphql-ruby-client javascript library works with ActionCable.

Recently, I've been trying to switch to AnyCable, which supports better response time and throughput.

However, after switching over, the graphl-ruby-client ActionCableLink class doesn't appear to work well with AnyCable (nothing happens)

Would be nice if a AnyCable adapter were able to be provided as well.

**Comment by rmosolgo** [comment]
Hi! Sorry to hear the included javascript bits don't work right with AnyCable. I'd be happy to ship AnyCable client code in graphql-ruby-client, but I don't have the bandwidth to implement it myself. If anyone else wants to contribute it, I'd welcome a PR and I'd be happy to 🚢 it in the npm package!
