### ISSUE TITLE
'Deprecations' on version 1.13.3 are breaking changes with no deprecation period

### ISSUE THREAD

**Issue by josh-long-raylo** [rmosolgo/graphql-ruby#3831]
**Describe the bug**

Version 1.13.3 is not backwards compatible and includes _breaking changes_ mentioning the changes as _deprecations_ in a patch version.

**Versions**

`graphql` version: 1.13.3
`rails` version: <= 7.0.1

**Steps to reproduce**
1. upgrade graphql from version < 1.13.3 to 1.13.3 not making the changes specified in the [change-log](https://github.com/rmosolgo/graphql-ruby/blob/master/CHANGELOG.md#1133-6-january-2022)

> GraphQL::Relay::NodeField and GraphQL::Relay::NodesField are deprecated; use GraphQL::Relay::HasNodesField or GraphQL::Relay::HasNodeField instead.

**Comment by rmosolgo** [comment]
Hi! Sorry for the trouble. I don't quite understand what went wrong. 

It looks like you updated to 1.13.3 and got a warning from the gem. Did your application crash with that new version? If so, could you please share the error and stack trace that it crashed with? 

If `NodeField` was working for you so far, I'd _expect_ it to keep working in 1.13.3. (There some cases it doesn't work with, and hasn't worked with for quite some time, hence the deprecation.) 

That deprecated code will be removed in GraphQL-Ruby 2.0.0, due out in the next month or so, depending.  

Did you try using `HasNodeField` instead, as mentioned by the warning? What happened when you tried it?

**Comment by josh-long-raylo** [comment]
No worries thanks for your quick reply!

Yeah our application did crash with the new version. Updating to `HasNodeField` does fix the problem but thought I'd raise this issue as the patch requires code changes so others will likely have the same issue.

Here is the stacktrace:
```NameError: uninitialized constant GraphQL::Types::Relay::NodeField
Did you mean?  GraphQL::Types::Relay::HasNodeField
/home/runner/work/api/api/vendor/bundle/ruby/3.0.0/gems/graphql-1.13.4/lib/graphql/types/relay/nodes_field.rb:31:in `const_missing'
/home/runner/work/api/api/app/graphql/types/query_type.rb:21:in `<class:QueryType>'
/home/runner/work/api/api/app/graphql/types/query_type.rb:6:in `<module:Types>'
/home/runner/work/api/api/app/graphql/types/query_type.rb:3:in `<main>'
/home/runner/work/api/api/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/runner/work/api/api/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/runner/work/api/api/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
/home/runner/work/api/api/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/runner/work/api/api/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/runner/work/api/api/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:27:in `require'
/home/runner/work/api/api/app/graphql/public_schema.rb:10:in `<class:PublicSchema>'
/home/runner/work/api/api/app/graphql/public_schema.rb:6:in `<main>'```

**Comment by rmosolgo** [comment]
Thanks for sharing this backtrace ... I think this is actually a _bug_ in my warning 😖 

I think the problem is, I defined `Relay.const_missing` _twice_, and instead of working _together_, one was clobbering the other. I'll work up a fix so that it properly warns! Thanks again for reporting this.

**Comment by josh-long-raylo** [comment]
Thanks for fixing @rmosolgo
