### ISSUE TITLE
How to validate a field of type defined in schema is always non nullable?

### ISSUE THREAD

**Issue by joelzwarrington** [rmosolgo/graphql-ruby#3834]
Hi @rmosolgo,

Hoping to get some help/direction. I am wanting to statically validate a schema doesn't contain non-nullable fields of type `ID` (or custom scalar) to prevent usage of nullable IDs being defined on types (such as when running a test suite). Did you have any recommendations?

So far I've thought about two approaches which might work:
- Use Rubocop rule with AST to identify fields of the particular type and confirm `null` is always `true`
- Use `GraphQL::Schema.validate` with custom `rules` similar to the static validations rules within the project

Do you think it'd be odd to hook into the `.validate` method with our own rule? By looking at the source code of rules in `lib/graphql/static_validation/rules`, I'd need to define a module which would likely visit `on_field` and check `type` & `type_of`?

**Comment by joelzwarrington** [comment]
I hadn't paid attention, but `GraphQL::Schema.validate` is used to validate a query string against the schema, which is not useful in this particular case.

**Comment by joelzwarrington** [comment]
This is how I have been able to tackle the problem, but understanding that this is likely very fragile and could be broken quite easily.

```ruby
def visit_definition(definition)
  return if definition.is_a? GraphQL::Language::Nodes::InputValueDefinition

  definition.fields.each { |field_definition| visit_definition(field_definition) } if definition.respond_to?(:fields)

  return unless definition.respond_to?(:type)

  type = visit_definition_type(definition.type)
  name = type.respond_to?(:of_type, :name) ? type.of_type.name : type.try(:name)
  return unless name == "ID" # or any other scalar name

  # can do assertion here, that `definition.type` is a GraphQL::Language::Nodes::NonNullType, or raise errors
end

def visit_definition_type(type)
  return type unless type.respond_to?(:of_type)

  visit_definition_type(type.of_type)
end

schema = GraphqlSchema::Main::Schema.to_document
schema.definitions.each do |definition|
  visit_definition(definition)
end
```

**Comment by rmosolgo** [comment]
I basically recommend an approach like you shared there, except I'd implement it to check the `Schema` directly instead of making a document, for example: 

```ruby 
def test_all_ids_are_non_null
  fields_with_nullable_id_return_types = [] 
  schema.types.each do |name, type| 
    if type.kind.fields? # Object, Interface 
      type.fields.each do |name, field_defn|
        if field_defn.type.to_type_signature == "ID"
          fields_with_nullable_id_return_types << field_defn.path
        end 
      end 
  end 
  assert_equal [], fields_with_nullable_id_return_types, "All fields that return `ID`s should be non-null (`ID!`), remove `null: true` from these field definitions"
end 
```

And put it my test suite so it validates every commit! At GitHub, we had several tests like that to enforce that various conventions were actually followed.

**Comment by joelzwarrington** [comment]
Thank you @rmosolgo ❤️
