### ISSUE TITLE
Object generator does not add namespaces to the class hierarchy

### ISSUE THREAD

**Issue by khamusa** [rmosolgo/graphql-ruby#3836]
First of all, thank you for the amazing work on this gem! :tada: 

**Describe the bug**

Running the generator in the following way:
```
rails g graphql:object Countries::ObjectType isoAlpha2Code:CountryIsoCodeEnum
```

**Expected behavior:**
```
      create  app/graphql/types/countries/object_type.rb
```

And the contents of such a file are:
```ruby
module Types
  module Countries    # <---- I expect this to be here
    class ObjectType < Types::BaseObject
      field :isoAlpha2Code, Types::CountryIsoCodeEnumType, null: true
    end
  end
end
```

**Actual result:**

The same file is created:
```
      create  app/graphql/types/countries/object_type.rb
```

But the contents do not include the **Countries** namespace:

```ruby
module Types
  class ObjectType < Types::BaseObject
    field :isoAlpha2Code, Types::CountryIsoCodeEnumType, null: true
  end
end
```

Am I doing anything wrong, or is this the expected behavior? I've looked for additional documentation around this and checked the changelog to see if related changes were made in more recent versions of the gem, and couldn't find any.

Thank you

**Comment by rmosolgo** [comment]
It looks like the generator doesn't support namespaces like that yet, there's no place in the template for inserting them: 

https://github.com/rmosolgo/graphql-ruby/blob/9ae3dffb85ba57644e4b60b4e9cd610e2224be91/lib/generators/graphql/templates/base_object.erb#L2-L3

But it'd be a nice improvement!

**Comment by khamusa** [comment]
Thank you @rmosolgo.
