### ISSUE TITLE
Possible argument default value regression in v1.13.x

### ISSUE THREAD

**Issue by cocoahero** [rmosolgo/graphql-ruby#3839]
**Describe the bug**

There appears to be a slight behavior change between v1.12.x and v1.13.x regards to argument default values and visibility. In v1.12, if an argument is determined to be hidden (`.visible?(ctx) == false`), the default value for the argument is still passed to the resolver as a keyword arg. In v1.13, this results in a crash if the resolver's keyword arg does not provide a default itself.

To be clear I'm not sure if this is a regression or a bug fix in disguise. 😅 

**Versions**

Tested with 1.12.22 and 1.13.5.

**GraphQL schema**

```ruby
class BaseArgument < GraphQL::Schema::Argument
  def initialize(name, type, desc = nil, internal:, **kwargs)
    super(name, type, desc, **kwargs)
    @internal = internal
  end

  def visible?(context)
    return false if @internal && !context[:internal_client]
    return super
  end
end

class BaseField < GraphQL::Schema::Field
  argument_class BaseArgument
end

class Query < GraphQL::Schema::Object
  field_class BaseField

  field :hello, String, null: true do |f|
    f.argument(:foo, String, required: false, default_value: "my_default_value", internal: true)
  end

  def hello(foo:)
    foo
  end
end

class Schema < GraphQL::Schema
  query Query
end

gql = <<~GQL
{
  hello
}
GQL

context = { internal_client: false }

visible = Query.get_field("hello").get_argument("foo").visible?(context)

puts "Argument Visible: #{visible}"

result = Schema.execute(gql, context: context)

puts result.to_h
```
### Results
GraphQL v1.12.22
```
Argument Visible: false
{"data"=>{"hello"=>"my_default_value"}}
```
GraphQL v1.13.5
```
/Users/jbaker/.gem/ruby/3.1.0/gems/graphql-1.13.5/lib/graphql/schema/field.rb:886:in `assert_satisfactory_implementation': 
    Failed to call hello on #<Query:0x0000000106d07d28 @object=nil, @context=#<Query::Context ...>> because the Ruby method params were incompatible with the GraphQL arguments: (GraphQL::Schema::Field::FieldImplementationFailed) - `foo:` is required by Ruby, but not by GraphQL. Consider `foo: nil` instead, or making this argument required in GraphQL.
from /Users/jbaker/.gem/ruby/3.1.0/gems/graphql-1.13.5/lib/graphql/schema/field.rb:850:in `rescue in block in public_send_field'
from /Users/jbaker/.gem/ruby/3.1.0/gems/graphql-1.13.5/lib/graphql/schema/field.rb:797:in `block in public_send_field'
from /Users/jbaker/.gem/ruby/3.1.0/gems/graphql-1.13.5/lib/graphql/schema/field.rb:902:in `with_extensions'
from /Users/jbaker/.gem/ruby/3.1.0/gems/graphql-1.13.5/lib/graphql/schema/field.rb:796:in `public_send_field'
```

**Comment by rmosolgo** [comment]
thanks for the detailed report! 

> not sure if this is a regression or a bug fix in disguise

phew... me either... 🤔 At least if that's how it _used_ to work, then the first step is to un-break it.

**Comment by cocoahero** [comment]
To be honest, I'm not sure how it should work in this new world. If there are for example two argument definitions for the same name, but they are both hidden, which default value is used?

I think it's more reasonable at this point to say that if you're using dynamic arguments but want to use kwargs, you need to handle the case yourself. The downside is duplication of values.

**Comment by rmosolgo** [comment]
> two argument definitions for the same name, but they are both hidden, which default value is used?

That's a zinger right there, I think you're right that the new behavior happens to be right-er. I've added some tests for the current behavior (and retroactively updated the changelog) in #3860

**Comment by maximbond** [comment]
Can anyone point me to the commit/PR where the default values started being omitted for invisible arguments? 
We've been using these options like 
`argument :user_id, ID, visible: false, default_value: nil, prepare: -> (_value, context) { context[:current_user_id] }`

We'd like to quickly monkey patch it until we fix every place where such argument is used, but don't know where to look. Thanks.

**Comment by manuelpuyol** [comment]
👋 @rmosolgo, sorry for reviving this issue, but do you have any tips on how to circumvent this "bug"?
We have tons of arguments that were depending on their default value to work properly and I'd love to find a way to keep them working 😅 

maybe a patch to `GraphQL::Schema::Member::HasArguments#coerce_arguments`?

**Comment by rmosolgo** [comment]
Did you try duplicating the default values? It's been a while, but I think copying the default value from the GraphQL definition and posting it in the method definition should work.
