### ISSUE TITLE
Issue with `offset` after `v1.13.3`

### ISSUE THREAD

**Issue by awiddersheim** [rmosolgo/graphql-ruby#3843]
**Describe the bug**

It looks like https://github.com/rmosolgo/graphql-ruby/commit/afd9b9207e19281f80ee35de1ebdc02d6c5f2342 from https://github.com/rmosolgo/graphql-ruby/pull/3790 has made using `offset` no longer work for us. The PR calls this potential out a bit which we seem to be hitting:

>  What if the relation has some other LIMIT or OFFSET applied, will this break?

We set `offset` on our relations but `graphql-ruby` is now resetting that `offset` outside of our control.

**Versions**

`graphql` version: `v1.13.3`
`rails` (or other framework): `6.1.4.4`
other applicable versions (`graphql-batch`, etc): `graphql-batch -> 0.4.3`

**Example of the problem**

This is a contrived example of what we do:

```
  field :items, Types::Items.connection_type, "A list of items.", connection: true, null: false, max_page_size: 25 do
    argument :offset, Integer, default_value: nil, required: false, description: "The number of records to skip when returning results. Useful for pagination."
  end

  def items(offset:)
    items = ::Items.all
    items = items.offset(offset) unless offset.nil?
    # Doing `pp items.to_sql` here would show that `OFFSET` is set properly but when `graphql-ruby`
    # executes this it adds the `LIMIT` properly as it's always done but resets `OFFSET` to zero.
    items
  end
```

**Comment by rmosolgo** [comment]
Sorry for the trouble, and thanks for reporting this! This is definitely a bug -- I'll take a look soon and follow up here.

**Comment by awiddersheim** [comment]
@rmosolgo No worries. Thanks for the project!
