### ISSUE TITLE
Support nested hash key as argument to field

### ISSUE THREAD

**Issue by joelzwarrington** [rmosolgo/graphql-ruby#3855]
**Is your feature request related to a problem? Please describe.**

Trying to resolve nested attributes on a hash ends up creating a significant amount of boilerplate resolver methods.

```ruby
field :first_field, String
field :second_field, String

def my_user_facing_name
  object[:attributes][:first_nested_attribute]
end

def second_field
  object[:attributes][:second_nested_attribute]
end
```

**Describe the solution you'd like**

It would be nice to be able to use the `hash_key` argument on a field definition to determine how to resolve the field.

```
field :my_field, String, hash_key: [:attributes, :nested_attribute]
```

---

I would be open to working on this! My approach would be to modify the conditional block in `public_send_field` in `lib/graphql/schema/field.rb` so that it would look something like this:

```diff
- elsif obj.object.is_a?(Hash)
-   inner_object = obj.object
-   if inner_object.key?(@method_sym)
-     inner_object[@method_sym]
-   else
-     inner_object[@method_str]
-   end
+ elsif obj.object.is_a?(Hash)
+   inner_object = obj.object.with_indifferent_access
+   inner_object.dig(*@method_sym)
```

**Comment by rmosolgo** [comment]
Sounds good to me! However, we can't assume that `.with_indifferent_access` will be present, since not all GraphQL-Ruby applications are also Rails applications.

Interestingly, it's _possible_ that swapping `inner_object[key]` for `inner_object.dig(*key)` would be a breaking change -- it could happen if someone was using arrays for hash keys. Maybe we could pick a _new_ keyword option for this, something like 

```ruby 
field ... dig: [:key_1, :key_2]
```

What do you think?

**Comment by joelzwarrington** [comment]
- would you be opposed to including ActiveSupport?
- I'm not opposed to `dig`, but it'd likely add more complexity to the argument validation in `initialize` which isn't bad, but less code is more

re: breaking change, do you mean that someone using it like this would break?
```ruby
field :thing, String, hash_key: 0

# thing is provided an array ["Hello World"]
```

```ruby
if method && hash_key
  raise ArgumentError, "Provide `method:` _or_ `hash_key:`, not both. (called with: `method: #{method.inspect}, hash_key: #{hash_key.inspect}`)"
end

if resolver_method
  if method
    raise ArgumentError, "Provide `method:` _or_ `resolver_method:`, not both. (called with: `method: #{method.inspect}, resolver_method: #{resolver_method.inspect}`)"
  end

  if hash_key
    raise ArgumentError, "Provide `hash_key:` _or_ `resolver_method:`, not both. (called with: `hash_key: #{hash_key.inspect}, resolver_method: #{resolver_method.inspect}`)"
  end
end
```

**Comment by rmosolgo** [comment]
> opposed to including ActiveSupport

Yep, I'd be opposed to adding it. (One of the [first external PRs](https://github.com/rmosolgo/graphql-ruby/pull/8) to this project was to remove ActiveSupport -- from Stripe, no less -- so I'd like to stick to it!)

Personally, I'm not worried about the complexity in `def initialize` -- it's worth the flexibility provided to `field ...` configurations in my opinion. 


> breaking change 

Imagine someone had an object like this: 

```ruby 
{
  type: "ChessGame",
  started_at: #<DateTime ...>
  # chess board locations encoded as a matrix:
  [0, 0] => nil,
  [0, 1] => :white_bishop,
  [0, 2] => :white_knight,
  [0, 3] => :black_queen,
  # ...
}
```

And used those hash keys to serve fields: 

```ruby 
# Convert conventional coordinates to x-y coordinates: 
field :a_1, ChessPiece, hash_key: [0, 0]
```

In that case, the `a1` field would be resolved with `object[[0, 0]]`. If we changed the behavior to use `dig(*key)`, then the default behavior would be `object.dig([0, 0])` (that is, `object[0][0]`), which wouldn't work. (Maybe you could work around that by wrapping the given hash key in an Array -- but then how would you distinguish between Arrays that are _meant_ to be used as keys vs Arrays that are meant to be paths into nested hashes?)

**Comment by joelzwarrington** [comment]
Sounds good, I'll take your suggested approach of using `dig` on field! 👍
