### ISSUE TITLE
Cleanup & refactor field class API

### ISSUE THREAD

**Issue by joelzwarrington** [rmosolgo/graphql-ruby#3861]
@rmosolgo I didn't have anything particular in mind but I'm open to helping out how I can.

Is there anything in particular you think time would be best spent? I was thinking of looking into how a field is resolved (`resolve_field`, `resolve`, `public_send_field`) unless you had other suggestions!

This issue was created as follow up to https://github.com/rmosolgo/graphql-ruby/pull/3856

**Comment by rmosolgo** [comment]
Well, I guess what makes me think "ew" is the way that several different values are created and tracked: 

- `graphql_name`, a String which is used at runtime to match selections in the GraphQL AST to a field definition 
- `original_name`, which is whatever was given to the `field ...` configuration call 
- `method_sym` and `method_str`. I honestly don't know that there's any reason to keep those both around anymore, except for compatibility's sake. They're used _if_ the object is a hash and there's no `resolver_method`. I wonder if those methods could be eliminated in any cases, or else lazily assigned to their `Field` instances if they're ever needed (`method_str`, especially). If so, that would reduce the memory footprint significantly for large schemas (thousands of fields).
- Oh, and `resolver_method` ... so many. 

Are _all_ those really necessary? Are there cases where we can skip them, or stop merging them into each other (` || ... || ...`)?

As mentioned in a code comment, do non-string/symbol hash keys actually work (eg `field :first, ... hash_key: 0`)?

Anyhow, less of a _plan_ and more of a hunch that something could be improved over there.


And by the way, if you're eyeing any ambitious refactors, I can suggest working on the `2.0-dev` branch to avoid messy merges down the line. A lot of the old execution-related code was removed there too, so it might be a bit _clearer_ what to work on: https://github.com/rmosolgo/graphql-ruby/blob/2.0-dev/lib/graphql/schema/field.rb#L614
