### ISSUE TITLE
Returned name for schema in introspection

### ISSUE THREAD

**Issue by toots** [rmosolgo/graphql-ruby#3866]
Hi,

I've been looking around but haven't found an issue or answer to this.

The doc states:
<img width="1021" alt="Screen Shot 2022-01-25 at 4 56 05 PM" src="https://user-images.githubusercontent.com/871060/151073596-e2618ca4-92a0-4c48-aece-e7e8b0d3572c.png">

And, indeed, with a simple JS graphql server, one gets:
<img width="769" alt="Screen Shot 2022-01-25 at 4 56 54 PM" src="https://user-images.githubusercontent.com/871060/151073683-befb01d9-4537-4996-a946-e7e4f195cb8d.png">

However, with a `rails` graphql server configured with the default doc, one gets:
<img width="749" alt="Screen Shot 2022-01-25 at 4 57 42 PM" src="https://user-images.githubusercontent.com/871060/151073766-73e06351-d9ae-4752-8fa0-53d01a35de6a.png">

Any reason for that? This doesn't seem to match the doc and breaks a lot of automated tools around the schema introspection.

**Comment by rmosolgo** [comment]
How strange! The behavior for `__schema` is well-tested in GraphQL-Ruby, for example: 

https://github.com/rmosolgo/graphql-ruby/blob/cb5ed7482aafbafe90ded3494a5653c483e9c357/spec/graphql/introspection/schema_type_spec.rb#L18-L21

https://github.com/rmosolgo/graphql-ruby/blob/cb5ed7482aafbafe90ded3494a5653c483e9c357/spec/graphql/introspection/type_type_spec.rb#L213-L226

https://github.com/rmosolgo/graphql-ruby/blob/e56654ee33733ad6a399edc1f7fad8300f997f92/spec/graphql/schema/input_object_spec.rb#L692-L712

https://github.com/rmosolgo/graphql-ruby/blob/b7fc1ae9b59fd2ee1556df85c77982f9dd09a8b0/spec/graphql/schema/dynamic_members_spec.rb#L878-L881

So I wonder why it's doing that ... I have never heard of this problem before, but maybe something in a new version of Rails 🤔 ?

**Comment by toots** [comment]
It's possible. This is with Rails `6.1.4.1` so fairly recent one. Ruby version is `2.6.8`, I'll be testing with a more recent one.

Is there a workaround tho this?

**Comment by rmosolgo** [comment]
I tried replicating this issue in a new rails app:

```
rails new graphql_schema_test
cd graphql_schema_test
bundle add graphql
rails g graphql:install
bundle exec rails server
# visit localhost:3000/graphql
```

But for me, it worked as expected, returning `"__schema": ...`:

<img width="788" alt="image" src="https://user-images.githubusercontent.com/2231765/151156642-a2a20860-7617-49f0-898c-a2f04efd50b4.png">

A few things to check in your local setup: 

- Can you confirm the query that the server is receiving? For example, what does `puts params[:query]` write in your rails logs? 
- Is there anything in your application that might be transforming the result hash before it's returned to the client? For example, does `p result.to_h` include `"__schema"=> ...` or `"Schema": ...`

**Comment by toots** [comment]
Ok, very sorry. Turns out there was a middleware in charge of normalizing our JSON responses which was causing troubles. This is not an issue with this gem. Thanks for your time. For reference, the gem is https://github.com/vigetlabs/olive_branch.

**Comment by rmosolgo** [comment]
Glad you got to the bottom of it! Thanks for letting me know.
