### ISSUE TITLE
Better error message when Field#owner_type fails

### ISSUE THREAD

**Issue by batamire** [rmosolgo/graphql-ruby#3867]
An uninformative error like this pops for me every now and then while developing :)

```
undefined method `<' for nil:NilClass
/usr/local/rvm/gems/ruby-2.6.8/gems/graphql-1.13.2/lib/graphql/schema/field.rb:39:in `owner_type'
/usr/local/rvm/gems/ruby-2.6.8/gems/graphql-1.13.2/lib/graphql/execution/interpreter/runtime.rb:698:in `block in continue_field'
/usr/local/rvm/gems/ruby-2.6.8/gems/graphql-1.13.2/lib/graphql/execution/interpreter/runtime.rb:899:in `after_lazy'
...
```

This time I was using `node(id: ...)` query on a Type that I forgot to `implements GraphQL::Types::Relay::Node`

**Comment by rmosolgo** [comment]
Thanks for reporting this issue.  It's a situation that's never _supposed_ to happen... but obviously it does sometime! I'll improve the error message in any case.
