### ISSUE TITLE
Mutation argument loads "No object found for..." error

### ISSUE THREAD

**Issue by bessey** [rmosolgo/graphql-ruby#3869]
Background: I am trying to create a minimum reproduction case for a different issue in the GraphQL Pro Pundit integration, but this is blocking me from building that out!

**Describe the bug**

I am attempting to follow 
https://graphql-ruby.org/mutations/mutation_classes.html#auto-loading-arguments
to create a simple schema that loads a mutation argument. I can see that the code that loads the argument is reached, however this object is discarded it seems.

I am probably missing something really stupid, but until I get past this I can't validate my much more interesting bug report, so here I am.

**Demo**

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'graphql', '1.13.6'
  gem 'graphql-pro',  '1.21.1', source: 'https://gems.graphql.pro/'
end

class Impact
  def initialize(id)
    @id = id
  end

  attr_reader :id
end

class SimpleMutation < GraphQL::Schema::Mutation
end
class ImpactType < GraphQL::Schema::Object
  field :impact, Float, null: true
end

class SimpleOptionUpdate < SimpleMutation
  argument :id, ID, required: false, loads: ImpactType, as: :impact #, pundit_role: :manage


  field :thing, String

  def resolve(impact: nil)
    "hi"
  end

end

class MutationType < GraphQL::Schema::Object
  field :simple_option_update, mutation: SimpleOptionUpdate
end


class MySchema < GraphQL::Schema
  mutation(MutationType)

  def self.object_from_id(id, _ctx)
    puts "Object ran #{id}"
    Impact.new(id)
  end

  def self.id_from_object(object, _type_definition, _ctx)
    puts "ID FROM OBJECT RAN"
    object.id
  end
end

query = <<-GRAPHQL
  mutation {
    simpleOptionUpdate(id: "123") {
      thing
    }
  }
GRAPHQL

result = MySchema.execute(query, variables: {}, context: {})
puts result.to_h
```

I also tried including this in the schema but it did not change the outcome

```ruby
  def self.resolve_type(type, obj, context)
    puts "RESOLVED TYPE #{obj.class}"
    case obj
    when Impact
      ImpactType
    else
      raise("Unexpected object: #{obj}")
    end.tap do |type|
      puts "we chose #{type}"
    end
  end
```

**Expected behavior**

Loads the object, enters the resolver code.

**Actual behavior**

Resolver is never reached because argument load fails:

```
$ ruby ./pundit-authz.rb
Object ran 123
{"data"=>{"simpleOptionUpdate"=>nil}, "errors"=>[{"message"=>"No object found for `id: \"123\"`", "locations"=>[{"line"=>2, "column"=>5}], "path"=>["simpleOptionUpdate"]}]}
```

**Comment by rmosolgo** [comment]
Hey -- I'll read the content of this issue in a few minutes, but I noticed that the original body included your graphql pro bundler credential. 

I've created a new credential and added it to https://billing.graphql.pro. Could you please log on there, get the new credential, and update your application to to use it? Then let me know and I'll disable the old one. Thanks!

**Comment by bessey** [comment]
Ah bugger sorry Robert! Shall do

**Comment by bessey** [comment]
I've launched the new credentials to production, and I have deleted my revision from the history in GH. It will take a few days to naturally progress to actively developed branches. If you can stomach it I would appreciate delaying the revoke a week, but if not I can expedite on our side.

Feel free to delete these comments too.

**Comment by rmosolgo** [comment]
The problem is, you can't `loads: ...` a type that isn't part of the schema. Since impact type isn't the return type of any fields, GraphQL-Ruby thinks it's hidden from the current viewer. (Sadly, it doesn't _tell_ you, the developer, this, TODO: #2286 .)

To make it work again: 


```diff 
    field :thing, String 
+   # add `ImpactType` to the schema somehow
+   field :impact, ImpactType

    def resolve(impact: nil)
-     "hi"
+     # just to make sure it's really getting through:
+     { thing: impact.id.to_s }
    end
```

For me, that outputs:

```
{"data"=>{"simpleOptionUpdate"=>{"thing"=>"123"}}}
```

Does that unblock you?

**Comment by bessey** [comment]
It does, thank you!

**Comment by bessey** [comment]
I just got bitten by this again in a new context in a greenfield project. Luckily, I found my own ticket when Googling for answers :laughing: but just wanted to note that its common enough that I ran into it twice in 6 months. Could be me being stupid too though :yum:

**Comment by rmosolgo** [comment]
No, it should really be better. I think logging some graphql info would be a good start, see #2286 for a suggestion

**Comment by jsierles** [comment]
The solution posted here still didn't work for me - adding the unexpected type as a field. Also the type appears to be in the schema already.
