### ISSUE TITLE
GraphQL::Introspection.query introduced in 1.13.6 incompatible with GitHub GraphQL API

### ISSUE THREAD

**Issue by tadman** [rmosolgo/graphql-ruby#3873]
**Describe the bug**

Starting in 1.13.5 the `GraphQL::Introspection.query` generated query contains elements that do not work with the GitHub GraphQL API and causes the GraphQL client, which depends on this query, to fail.

The error generated looks like:

```
.../graphql-1.13.7/lib/graphql/schema/loader.rb:17:in `fetch': key not found: "data" (KeyError)
```

That's because the result contains:

```ruby
{"errors"=>
  [{"path"=>["query IntrospectionQuery", "__schema", "description"],
    "extensions"=>{"code"=>"undefinedField", "typeName"=>"__Schema", "fieldName"=>"description"},
    "locations"=>[{"line"=>3, "column"=>5}],
    "message"=>"Field 'description' doesn't exist on type '__Schema'"},
   {"path"=>["query IntrospectionQuery", "__schema", "directives", "isRepeatable"],
    "extensions"=>{"code"=>"undefinedField", "typeName"=>"__Directive", "fieldName"=>"isRepeatable"},
    "locations"=>[{"line"=>20, "column"=>7}],
    "message"=>"Field 'isRepeatable' doesn't exist on type '__Directive'"},
   {"path"=>["fragment FullType", "specifiedByUrl"],
    "extensions"=>{"code"=>"undefinedField", "typeName"=>"__Type", "fieldName"=>"specifiedByUrl"},
    "locations"=>[{"line"=>32, "column"=>3}],
    "message"=>"Field 'specifiedByUrl' doesn't exist on type '__Type'"}]}
```

**Versions**

`graphql` version: 1.13.6+

**GraphQL schema**

GitHub's GraphQL schema as seen in [the explorer](https://docs.github.com/en/graphql/overview/explorer).

**GraphQL query**

The 1.13.5 query looks like:

```gql
query IntrospectionQuery {
  __schema {
    queryType { name }
    mutationType { name }
    subscriptionType { name }
    types {
      ...FullType
    }
    directives {
      name
      description
      locations
      args {
        ...InputValue
      }
    }
  }
}
```

The updated version in 1.13.6 looks like:

```gql
query IntrospectionQuery {
  __schema {
    description
    queryType { name }
    mutationType { name }
    subscriptionType { name }
    types {
      ...FullType
    }
    directives {
      name
      description
      locations
      isRepeatable
      args {
        ...InputValue
      }
    }
  }
}
```

Where these `description` fields appear to be a problem.

In a bizarre twist GitHub's Explorer does seem to acknowledge these fields exist using the auto-complete feature, but refuses to acknowledge them when executing queries.

**Steps to reproduce**

Use GraphQL client on GitHub's GraphQL API.

**Expected behavior**

As with 1.13.5 and prior, GraphQL client operates normally.

**Actual behavior**

GraphQL client can't parse response and crashes with exception.

**Comment by Kukunin** [comment]
Should we implement any versioning in the graphql client? 

In my case, Hasura Cloud fails with this error:

```
{"errors":[{"extensions":{"path":"$.selectionSet.__schema.selectionSet.types.selectionSet.specifiedByUrl","code":"validation-failed"},"message":"field \"specifiedByUrl\" not found in type: '__Type'"}]}                                                                                                            
```

It seems like it's too new for that

**Comment by rmosolgo** [comment]
Sorry for the trouble. Other additions to that query were gated by arguments (like `include_deprecated_args: ...`: 

https://github.com/rmosolgo/graphql-ruby/blob/1f91e6fe19c9e9393e40240920a22544e220b363/lib/graphql/introspection.rb#L4

). I recently updated this query to reflect the new spec, but I guess I should have kept an option for backwards compatibility! Sorry about that -- I'll go back and add an option for it soon. (Or, if you'd rather give it a shot yourself, I'd welcome a PR for it!)

**Comment by tadman** [comment]
That helps, but since this is being utilized by the [GitHub GraphQL client](https://github.com/github/graphql-client) to reflect on the schema on initialization, and no such parameter is given, it requires some pretty ugly patching to get that on board too.

Is there a way to set this as a global default?

**Comment by rmosolgo** [comment]
> `false` for now?

Yes, I made it so those new fields are hidden by default: 

https://github.com/rmosolgo/graphql-ruby/blob/6a708cb71ec3420b4b27716984da59d5933cc004/lib/graphql/introspection.rb#L4

So in 1.13.8, those new fields won't be in INTROSPECTION_QUERY: 

```ruby
$ irb
irb(main):001:0> require "graphql"
# => true
irb(main):002:0> GraphQL::VERSION
# => "1.13.8"
irb(main):003:0> GraphQL::Introspection::INTROSPECTION_QUERY.include?("isRepeatable")
# => false
irb(main):004:0> GraphQL::Introspection::INTROSPECTION_QUERY.include?("specifiedByUrl")
# => false
```

What happens for you when you try 1.13.8 ?

**Comment by tadman** [comment]
Looks good when constrained with `gem 'graphql', '>= 1.13.8'`.

The reflection query looks like:

```gql
query IntrospectionQuery {
  __schema {
    
    queryType { name }
    mutationType { name }
    subscriptionType { name }
    types {
      ...FullType
    }
    directives {
      name
      description
      locations
      
      args {
        ...InputValue
      }
    }
  }
}
```
