### ISSUE TITLE
Guide: Use lookahead with subscriptions

### ISSUE THREAD

**Issue by penso** [rmosolgo/graphql-ruby#3876]
Using version 1.12.16 I tried using:

```
module Subscriptions
    class MyObjectTypeUpdated < Subscriptions::BaseSubscription
      field :my_object, Types::MyObjectType, null: false, extras: [:lookahead]

      def subscribe
        :no_response
      end

      def update
      end
    end
end
```
 
but `context.lookahead` is nil within the update method. I found no documentation about using lookaheads in subscriptions, is this supposed to work and could we have documentation about it?

Thanks!

**Comment by penso** [comment]
Thanks @rmosolgo 

I use subscription to subscribe to specific field of `field :my_object` for example:

```
subscription { myObjectTypeUpdated { myObject  { attribute1 attribute2 }}}`
```

and would like to know what was asked from within `def update` so I don't computer unnecessary things when not requested.

**Comment by penso** [comment]
Thanks! That worked perfectly. Maybe it should be documented somewhere in the subscriptions part of the documentation?

**Comment by rmosolgo** [comment]
Sure! I added a mention in dc3e8412a. Glad it worked for you.
