### ISSUE TITLE
Input objects that use `prepare` aren't authorized (regression?)

### ISSUE THREAD

**Issue by bessey** [rmosolgo/graphql-ruby#3878]
**Describe the bug**

This bug is similarly to #2633, possibly an identical regression.

Upgrading from 1.12 to 1.13 I discovered a test failure in our suite that evidenced that argument level authorization was being skipped. I include a fairly minimal reproduction of this, and show that `prepare` is most certainly the culprit

(Edit: I have further simplified the example, it does appear to be the same as the prior issue)

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'graphql', '1.13.6'
  gem 'graphql-pro', '1.21.1', source: 'https://gems.graphql.pro/'
  gem 'pundit', '2.0.1'
end

class ApplicationPolicy
  def initialize(me, object)
  end
end

class Impact
  def initialize(id)
    @id = id
  end

  attr_reader :id
end

class ImpactPolicy < ApplicationPolicy
  def manage?
    puts "MANAGE RAN"
    true
  end
end

class BaseArgument < GraphQL::Schema::Argument
  include GraphQL::Pro::PunditIntegration::ArgumentIntegration

  pundit_role nil
end

class BaseField < GraphQL::Schema::Field
  argument_class BaseArgument
end

class BaseObject < GraphQL::Schema::Object
  field_class BaseField
end

class BaseInputObject < GraphQL::Schema::InputObject
  argument_class BaseArgument
end

class BaseMutation < GraphQL::Schema::RelayClassicMutation
  field_class BaseField
  argument_class BaseArgument
  input_object_class BaseInputObject
end

class ImpactType < BaseObject
  field :impact, Float, null: true
end

class OptionInput < BaseInputObject
  argument :id, ID, required: false, loads: ImpactType, pundit_role: :manage
end
class OptionUpdate < BaseMutation
  # Bug cause
  I_BREAK_EVERYTHING = { prepare: ->(val, _ctx) { val.to_h } }
  ## Swap in for the fix
  # I_BREAK_EVERYTHING = { }

  argument :option, OptionInput, required: true, **I_BREAK_EVERYTHING

  field :thing, ImpactType

  def resolve(option:)
    {thing: Impact.new("123")}
  end
end

class MutationType < BaseObject
  field :option_update, mutation: OptionUpdate
end


class TestSchema < GraphQL::Schema
  mutation(MutationType)

  def self.object_from_id(id, _ctx)
    Impact.new(id)
  end

  def self.id_from_object(object, _type_definition, _ctx)
    object.id
  end
end

query = <<-GRAPHQL
  mutation {
    optionUpdate(
      input: {
        option: {
          id: "123"
        }
      }
    ) {
      thing {
        __typename
      }
    }
  }
GRAPHQL

puts "Running query, you should see some output from the Pundit policy"
result = TestSchema.execute(query, variables: {}, context: {})
puts "Query complete, result:"
puts result.to_h

```

**Expected behavior**

"MANAGE RAN" is output.

**Actual behavior**

"MANAGE RAN" is not output because the loads: authorization is not run.

**Comment by rmosolgo** [comment]
Wow ... thanks for the details on this! The funny thing is, the "bug" described in #2633 was actually added in v1.9.15 (#1869). Recently, I tried to fix it (#3786) -- but evidently I broke something else along the way! I'll take a look at the scenario you've outlined here and see how to reconcile them.

**Comment by bessey** [comment]
I am just about to log off for the day so can't verify this right now, but as I imagine this is important information... I am almost positive this test passes on 1.12. The test flipped from success to failure during the upgrade

**Comment by rmosolgo** [comment]
:+1: Thanks, I got that impression from the initial write-up, too. I'm assuming my changes in #3786 had some unintended consequences, breaking the scenario you outlined above in 1.13 😖

**Comment by rmosolgo** [comment]
Is there a version of GraphQL-Ruby that makes the script above behave as expected? When I use 

```ruby 
  gem "graphql", "1.12.24"
```

and keep the `prepare:` config, I do _not_ see `MANAGE RAN`. But if I comment out `prepare: ...`, then I see `MANAGE RAN` printed out. 

So for me, this looks the same on 1.12.x as 1.13.x (and that's what I expect -- I think `prepare: ...` has always disabled argument authorization on input objects.

**Comment by bessey** [comment]
I can verify that both this script and my application's non-simplified case go from working to broken going from **GraphQL 1.12.10 + GraphQL Pro 1.17.15** to 1.12.24 + 1.21.2.

**Comment by rmosolgo** [comment]
Ahh -- thanks for sharing that. I was able to narrow it down to graphql-ruby 1.12.16-1.12.17 (Regardless of pro version), and I bet it was https://github.com/rmosolgo/graphql-ruby/pull/3606. Before that change, a `Hash` would have been authorized just like an InputObject, but after that change, it'd be silently skipped. I'll work up a fix to restore that old behavior without re-introducing the issue that initiated that patch in the first place...
