### ISSUE TITLE
GraphQL Enterprise: ability to modify resolver class in changeset 

### ISSUE THREAD

**Issue by joelzwarrington** [rmosolgo/graphql-ruby#3883]
I want to change the type on a resolver class in a changeset. Looking at the documentation and performing the installation of the changeset functionality doesn't appear to add anything to resolver classes (of `GraphQL::Schema::Resolver`).

To work around this issue, I'm doing the following:
- change my resolver class so that it's `deprecated` like: `MovieResolver` ➡️  `DeprecatedMovieResolver`
- update my field outside of the changeset to use that deprecated resolver by default
- add new `MovieResolver` which has the correct type and arguments
- add new changeset which will change the field that's connected to this resolver so that it switches from using `DeprecatedMovieResolver` to `MovieResolver` (the new one)

If it is possible to do this but I'm missing the documentation let me know!

**Comment by rmosolgo** [comment]
Yeah, I don't think this is possible in a better way yet. (From a GraphQL-Ruby perspective, `resolver: ...` is one of many `field(...)` options, and to re-define a field with different options, you do it the way you described above. But from an actual human developer perspective, this is not right!) 

I think it should be possible to support a `modifies MovieResolver do ... end`-type API, just like the other modifications. I'll follow up here when there's a better way to handle this case. Thanks for the detailed suggestion!

**Comment by rmosolgo** [comment]
I just wrapped up some preliminary work for this in #3916. Before that change, resolver configurations were _copied_ to `GraphQL::Schema::Field` instances at build-time, so any later change to the resolver would be ignored by the schema. After that change, fields based on resolvers now delegate many of their configurations and behaviors to the resolvers instead, so that any later change to a resolver (say, adding a changeset config) can also be reflected in the derived field. 

I still have to add changeset support to resolvers, then make sure it works from end-to-end, but, getting there!

**Comment by joelzwarrington** [comment]
@rmosolgo thanks for the investigation and follow up comment, I'll review them a bit more in detail tomorrow.

We're just now adopting changesets so will definitely let you know how the workflow goes.

I would assume this to be an infrequent change anyway, so even if the workflow is somewhat painful, that would be okay. We'll be making a bunch of changes like this because we're still in the phase of adopting GraphQL and implementing/finding best patterns as we go so this change would have been nice.

---

Maybe something to consider:

We really like using resolvers in top level fields within Query type, so that the methods to resolve those fields are defined elsewhere and so our Query type isn't massive. 

Maybe if there was someway to still define the field with its type but define a class to handle resolving ('resolve' method on resolver classes) of the field might be beneficial.
