### ISSUE TITLE
Error handling documentation issue

### ISSUE THREAD

**Issue by aviscasillas** [rmosolgo/graphql-ruby#389]
Hi guys!

I'm playing with validation on mutations and following the documentation I found something that I guess it's a mistake...

In the section [Exposing Errors](https://github.com/rmosolgo/graphql-ruby/blob/master/guides/queries/error_handling.md#exposing-errors), in the code example where it says `Then, when creating a post, return the Post, even if the save failed`:
```ruby
resolve ->(obj, args, ctx) {
  post = Post.new(args["post"].to_h)
  # Maybe this fails, no big deal:
  post.save
  post
}
```

I guess the returned value should be a hash:
```ruby
{ post: post }
```

Am I wrong?

Thanks in advance!

**Comment by aviscasillas** [comment]
Sorry my bad, as I assumed usage of `return_field` while it could be using `return_type`.

**Comment by rmosolgo** [comment]
Oh, for a `Relay::Mutation`, you'd be right! Maybe I should update that example to use a `Relay::Mutation` instead of a plain field on the Mutation type.
