### ISSUE TITLE
Pundit Integration - Scope and Object Authorization

### ISSUE THREAD

**Issue by hvenables** [rmosolgo/graphql-ruby#3893]
**Is your feature request related to a problem? Please describe.**

The request relates to graphql pundit integration and the way the scopes and object authorization works together.

We are currently experiencing some performance issues with the way that the pundit integration works. Currently once an association has been scoped which should remove all unauthorized objects. We then check for each of the objects to see if they are authorized. This should have already been covered by the scope.

This would only work in the case where you authorize your objects with a `show?` like action, which we expect to have equal restrictiveness to the scope. In REST nomenclature that's easy, its show?, but in GraphQL there is no inherent equivalent, but we went with `view?`

If you look at the scope docs from pundit https://github.com/varvet/pundit#scopes once a record has been scoped the gem doesn't try to then authorize the individual objects.

I have put together a minimal reproduction steps to make it a little clearer what i mean

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'activerecord'
  gem 'graphql', '1.13.6'
  gem 'graphql-pro', '1.21.1', source: 'https://gems.graphql.pro/'
  gem 'pundit', '2.0.1'
  gem 'sqlite3'
end

require "active_record"

ActiveRecord::Base.establish_connection(
  :adapter => "sqlite3",
  :database  => ":memory:"
)

ActiveRecord::Schema.define do
  create_table :items do |table|
  end
end

class Item < ActiveRecord::Base
end

2.times { |n| Item.create }

class ApplicationPolicy
  def initialize(me, object)
  end

  class Scope
    def initialize(_account, scope)
      @scope = scope
    end

    def resolve
      puts "scoping"
      @scope.all
    end
  end
end

class ItemPolicy < ApplicationPolicy
  def view?
    puts "View ran"
    true
  end
end

class BaseObject < GraphQL::Schema::Object
  include GraphQL::Pro::PunditIntegration::ObjectIntegration
end

class ItemType < BaseObject
  pundit_role :view

  field :id, Integer, null: true
end

class QueryType < BaseObject
  pundit_role nil

  field :items, [ItemType], null: false, scope: true

  def items
    Item.all
  end
end

class TestSchema < GraphQL::Schema
  query(QueryType)
end

query = <<-GRAPHQL
  query {
    items {
      id
    }
  }
GRAPHQL

TestSchema.execute(query, variables: {}, context: {})
```
which outputs

```
scoping
View ran
View ran
```

**Describe the solution you'd like**

Ideally we would like to be able to define some kind of base authorization that the scope and a single action like `show?` agree on. Then if the relation has already been scoped and it would call that method it skips it as it knows that the scope has already restricted any items that would fail that check. This would remove the performance issues we are currently seeing.

I think ideally the only change that we would make is that somewhere we would define a `base_role` or something equivalent that if the pundit_role matches would skip the object level authorization. 

**Describe alternatives you've considered**

We currently have tried to use a cache that helps to make the object level authorization hit the db less but in an ideal world we wouldn't have to maintain that cache that even tho is more efficient than hitting the db is still wasteful. 

I hope that all makes sense, let me know what you think. Im happy to help in any way i can if you think the idea is of merit :)

**Comment by rmosolgo** [comment]
This makes a ton of sense, and I've definitely heard other requests for this in the past. Thanks for such a detailed writeup. I can think of a few solutions: 

- A per-query cache, like you described. Y'know, it _should_ work, but the cache could balloon in size. Also, turning application objects into cache keys isn't always an easy operation. Could use the Schema's `id_from_object` hook for this (that's what ObjectCache does). One advantage to this approach is that it doesn't care _where_ in the query objects are authorized, so if the same object is fetched with `loads: ...`, then returned in the response, it would only be authorized once. 
- Some kind of "flag" that rides along with scoped records, to make sure they aren't authorized a second time. (Unlike the cache, this doesn't require accessing individual objects -- but it's more couple to GraphQL runtime, and it leaves the door open to authorizing the same object twice if it pops up multiple places in the query.) One challenge here is knowing whether or not a list _was_ scoped. Implementation-wise, every GraphQL type _does_ have a `scope` method, but it's a no-op. How should the library detect the difference between a no-op `def scope` and a "real" `def scope`? (Maybe the no-op should be removed, so the gem could assume _any_ call to `.scope(items, ctx)` would effectively authorize all the returned items.)
- Interestingly, your suggestion above is something a little different, IIUC. You could look at the current `pundit_policy_class`, and if it has a `Scope`, and if the current object came from a list field, and if the current `pundit_role` is the default role (eg `show`), then assume that the current object already passed authorization and _don't_ call `.show?` with it. This makes sense, it's just more Pundit-centric than the other two possibilities. 

Let me do some head-scratching and some experimentation and I'll follow up here soon!

**Comment by hvenables** [comment]
Awesome :raised_hands: thanks for the quick response and i look forward to hearing from you :)

**Comment by rmosolgo** [comment]
Sorry I didn't follow up here sooner, but this can be addressed with `reauthorize_scoped_objects(false)` in GraphQL-Ruby 2.1.0+ :+1: Let me know how it goes if you give it a try!
