### ISSUE TITLE
Testing types like old Rails views

### ISSUE THREAD

**Issue by zeitnot** [rmosolgo/graphql-ruby#3896]
Hi @rmosolgo, thank you very much for this great library. To me, you deserve the best. I do not know whether this place is the correct to ask a question regarding to testing types.  Without hitting `SomeSchema.execute` I want to test types in isolation like Rails views. I want this because I have `if` branches on some fields like the following code.

```ruby
# frozen_string_literal: true

module Admin
  module Users
    class Type < Admin::Types::BaseObject
      graphql_name 'Me'

      field :email, String, null: false
      field :first_name, String, null: true
      field :last_name, String, null: true
      field :full_name, String, null: true
      field :token, String, null: false

      def full_name
        "#{object[:first_name]} #{object[:last_name]}".squish
      end

      def token
        return object.token if object.respond_to?(:token)
        return object['token'] if object.is_a?(Hash)
        ''
      end
    end
  end
end
``` 

Here  is the `token` field has branch. Testing branches through controller is cumbersome so I tried to test types in isolation but to compose the type object requires to many dependencies. I have searched on google, analyzed some popular codebases like Gitlab, but I could not find any proper and easy way. On Gitlab's codebase, they test type's properties like field names or graphql name not values or branches. Do you have any guide or best practice to test types in isolation easily? 

Thank you in advance!

**Comment by rmosolgo** [comment]
Hey @zeitnot , great question, but unfortunately, no, I don't have any advice for testing GraphQL fields outside of GraphQL queries. As you noticed, executing a GraphQL query has lots of dependencies, and there's no easy way to stub them all. 

Instead, I'd recommend extracting the logic out of the interface layer, and testing it independently, for example:


```ruby 
def token 
  UserToken.for(object)
end 

# then, in app/models/user_token.rb:
module UserToken 
  def self.for(object)
    if object.respond_to?(:token)
      object.token 
    elsif object.is_a?(Hash)
      object[:token]
    else 
      ""
    end 
  end 
end 
```

Then, you could test `UserToken` in unit tests, along with an integration test or two to make sure that the GraphQL field actually reaches `UserToken`. I hope that helps!
