### ISSUE TITLE
Dynamic schema field for Subscription using `.visible?(context)`

### ISSUE THREAD

**Issue by choznerol** [rmosolgo/graphql-ruby#3897]
**Is your feature request related to a problem? Please describe.**

[1.13.0](https://github.com/rmosolgo/graphql-ruby/blob/master/CHANGELOG.md#1130-24-november-2021) introduced dynamic schema based with `.visible?(context)`

> _Visibility: A schema may contain multiple members with the same name. For each name, GraphQL-Ruby will use the one that returns true for .visible?(context) for each query (and raise an error if multiple objects with the same name are visible). #3651 #3716 #3725_

The related test added in #3651 covers `query` and `mutation`, but not `subscription`.

https://github.com/rmosolgo/graphql-ruby/blob/79ab2eadbd56602d12b989f3dc361b1212f9cddf/spec/graphql/schema/dynamic_members_spec.rb#L357-L358

Looking through the doc and changed files in related PR, I'm not sure if this feature also supports subscription.

I'm using [dynamic fields using `.visible(context)`](https://graphql-ruby.org/schema/dynamic_types.html#using-visiblecontext) to separate implementations for different contexts.

```rb
module Types
  class SubscriptionType < Types::BaseObject
    field :foo, subscription: Subscriptions::Foo::ForUser
    field :foo, subscription: Subscriptions::Foo::ForAdmin
  end
end

module Subscriptions
  module Foo
    class Base < BaseSubscription
      def visible?(context)
        result = self == { User => ForUser, Admin => ForAdmin }.fetch(context[:current_account].class)
        p("visible? -> #{result}") # This prints two times, once `true` and once `false`

        result
      end
    end
  end
end

module Subscriptions
  module Foo
    class ForUser < Base
      def authorized?(**args)
        # Authorization logic for user account
      end

      def subscribe(**args)
        # Implementation for user account
      end
    end
  end
end

module Subscriptions
  module Foo
    class ForAdmin < Base
      def authorized?(**args)
        # Authorization logic for admin account
      end

      def subscribe(**args)
        # Implementation for admin account
      end
    end
  end
end
```

Doing similar things in query will work, but in subscription like above I'll get a `DuplicateNamesError` from `warden.rb` when `trigger`.

```log
GraphQL::Schema::DuplicateNamesError: Found two visible definitions for `Subscription.foo`: #<Types::BaseField Subscription.foo(...): ForUserload!>, #<Types::BaseField Subscription.foo(...): ForAdminPayload!>

/Users/apple/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.13.2/lib/graphql/schema/warden.rb:58:in `block in visible_entry?'
/Users/apple/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.13.2/lib/graphql/schema/warden.rb:53:in `each'
/Users/apple/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.13.2/lib/graphql/schema/warden.rb:53:in `visible_entry?'
/Users/apple/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.13.2/lib/graphql/schema/member/has_fields.rb:46:in `block in get_field'
/Users/apple/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.13.2/lib/graphql/schema/member/has_fields.rb:42:in `each'
/Users/apple/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.13.2/lib/graphql/schema/member/has_fields.rb:42:in `get_field'
/Users/apple/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.13.2/lib/graphql/schema.rb:1253:in `get_field'
/Users/apple/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.13.2/lib/graphql/subscriptions.rb:76:in `trigger'
...
```

**Describe the solution you'd like**

I haven't looked deep into #3651. If this is technically achievable then I'd love to help.

Looking through the call stack, I'm suspecting if this is related to [`GraphQL::Schema#get_field`](https://github.com/rmosolgo/graphql-ruby/blob/v1.13.2/lib/graphql/schema.rb#L1241) has its third argument `context` defaults to `GraphQL::Query::NullContext`.

Perhaps allowing passing context to [`GraphQL::Subscriptions#trigger`](https://github.com/rmosolgo/graphql-ruby/blob/v1.13.2/lib/graphql/subscriptions.rb#L67-L76) can solve this problem?
```diff
-    def trigger(event_name, args, object, scope: nil)
+    def trigger(event_name, args, object, scope: nil, context: GraphQL::Query::NullContext)
    def trigger(event_name, args, object, scope: nil)
      event_name = event_name.to_s

      # Try with the verbatim input first:
      field = @schema.get_field(@schema.subscription, event_name)

      if field.nil?
        # And if it wasn't found, normalize it:
        normalized_event_name = normalize_name(event_name)
-        field = @schema.get_field(@schema.subscription, normalized_event_name)
+        field = @schema.get_field(@schema.subscription, normalized_event_name, context)
```

**Describe alternatives you've considered**

If this is technically difficult to implement for subscriptions, I can also help update the [related documentation](https://graphql-ruby.org/schema/dynamic_types.html#using-visiblecontext) to mention this limitation.

**Additional context**

**Comment by rmosolgo** [comment]
Thanks for the detailed write-up! I think you're exactly right about what went wrong and how to fix it. If it was me, I'd add some test (maybe in `subscriptions_spec.rb`) to replicate the bug. Then add a fix like you suggest above and make sure it makes it _work_ :+1: 

You mentioned you're game to give it a try -- just let me know if I can help out along the way!
