### ISSUE TITLE
Need help for creating a simple mutation

### ISSUE THREAD

**Issue by albertomg994** [rmosolgo/graphql-ruby#390]
Hi!

I'm really having a lot of trouble trying to make my first mutation in a rails project using GraphQL (I had no problem running normal queries).

I've read several times the instructions [here](https://rmosolgo.github.io/graphql-ruby/relay/mutations) and [here](http://graphql.org/learn/queries/#mutations), but obviously I'm doing something wrong.

I've been stuck with this for several days, so I'd really appreciate a lot if someone could take a look at my code and give me some feedback about what's my mistake.

This is how my **schema** looks like:

```ruby
# app/graph/sag_schema.rb
SagSchema = GraphQL::Schema.define do
  query QueryRoot
  mutation MutationType
end
```

This is how my **MutationType** looks like:

```ruby
# app/graph/mutations/mutation_type.rb
MutationType = GraphQL::ObjectType.define do
  name "Mutation"
  description "The mutation root for this schema"

  field :addActivity, field: AddActivityMutation.field
end
```

This is how the actual **mutation** looks like (I've simplified the migration code as much as I could to try to narrow the problem cause, that's why it's almost empty):

```ruby
# app/graph/mutations/add_activity_mutation.rb
AddActivityMutation = GraphQL::Relay::Mutation.define do
  # Used to name derived types, eg `"AddActivityInput"`:
  name "AddActivity"

  # Accessible from `input` in the resolve function:
  input_field :title, types.String

  # The result has access to these fields, resolve must return a hash with these keys
  return_field :activity, types.String

  # The resolve proc is where you alter the system state.
  resolve ->(object, inputs, ctx) {

    puts "\n\n\n(!!!!)     RESOLVING MUTATION   (!!!!)\n\n\n"

    # The keys in this hash correspond to `return_field`s above:
    { activity: "Mutation resolved successfully" }
  }
end
```

This is the **controller** that handles GraphQL queries:

```ruby
# app/controllers/graphql_controller.rb
class GraphqlController < ApplicationController

  skip_authorization_check

  def query
    query_string = params[:query]
    puts "\n#{"="*60}\nThe query string is:\n #{query_string}\n#{"="*60}\n"

    variables = params[:variables] || {}
    puts "\n#{"="*60}\nThe query variables are:\n #{query_string}\n#{"="*60}\n"

    result = SagSchema.execute(
      query_string,
      variables: variables,
      context: {
        current_user: current_user
      }
    )

    render json: result
  end
end
```

And this is how I'm trying to run the actual mutation through GraphiQL:

![captura de pantalla 2016-11-09 a las 20 15 07](https://cloud.githubusercontent.com/assets/9287468/20151391/45f23864-a6ba-11e6-81ab-0a1ed2ec36e4.png)

No matter what I do, the query never gets to be executed properly since the rails server always ends up throwing a `500 Internal Server Error`. The output looks like this:

![captura de pantalla 2016-11-09 a las 20 25 36](https://cloud.githubusercontent.com/assets/9287468/20151834/04d758f8-a6bc-11e6-85fe-8f4950a8fc6c.png)

Other info:

* `rails` version: 4.2.7.1
* `graphql` version: 1.0.0
* `graphiql-rails` version: 1.3.0
* ruby version: 2.3.1

Thanks a lot in advance for your time!

**Comment by rmosolgo** [comment]
GraphiQL sends its variables as a JSON string, so to convert them to a Ruby hash, you should add 

```ruby 
JSON.parse(params[:variables])
```

Does that work for you?

**Comment by albertomg994** [comment]
Yes!!! Thank you very much! 🙏  🙏  😀

**Comment by rmosolgo** [comment]
Glad to hear it! This happens from time to time, I'll try to add a typecheck soon!
