### ISSUE TITLE
[2.0 update] Missing GraphQL::Relay::ConnectionType

### ISSUE THREAD

**Issue by axelerator** [rmosolgo/graphql-ruby#3915]
We're running a rails application with an initializer to activate bidirectional_pagination.

```ruby
# config/initializers/graphql.rb
GraphQL::Relay::ConnectionType.bidirectional_pagination = true
```

This constant ([defined here in the 0.13 version](https://github.com/rmosolgo/graphql-ruby/blob/1.13.x/lib/graphql/relay/connection_type.rb)) doesn't seem to exist in the `2.0` version anymore.

**Versions**

`graphql` version: Bump graphql from `1.13.8` to `2.0.0`
`rails`: `7.0.1`

**Steps to reproduce**

Create a rails 7 app with the initializer shown above

**Expected behavior**

Starts up

**Actual behavior**

Rails fails to start with

`config/initializers/graphql.rb:5:in `<top (required)>': uninitialized constant GraphQL::Relay::ConnectionType (NameError)`

**Comment by rmosolgo** [comment]
Sorry for the trouble! The new connections module handles backwards pagination flags (`has*Page`) by saying, if the cursor is _beyond_ any records, then assume that there is a page back there. (If `after:` is present, then `hasPreviousPage` is true; if `before:` is present, then `hasNextPage` is true.) This flag is a no-op and the assignment can be safely removed. 

Sorry it didn't warn! I'll update 1.13.x in the meantime to include a warning.

**Comment by axelerator** [comment]
No worries, thanks for the quick feedback!
