### ISSUE TITLE
Question: how might one access class fields on schema in the context of a specific changeset version?

### ISSUE THREAD

**Issue by joelzwarrington** [rmosolgo/graphql-ruby#3921]
Assuming I have the following:
```ruby
class MyChangeset < GraphQL::Enterprise::Changeset
  release "2022-01-01"
  # ...
end

class Schema < GraphQL::Schema
  # ...
  use GraphQL::Enterprise::Changeset::Release, changesets: [
    MyChangeset
  ]
end
```

How can I do this (or any class method) in the context of version `2022-01-01` or without a version `nil`?:
```
Schema.types
```

**Comment by joelzwarrington** [comment]
One of the ways I have found it's possible to do this, is with introspection and using:

```
Schema.execute(introspection_query, context: { changeset_version: "2022-01-01" })
```

**Comment by joelzwarrington** [comment]
@rmosolgo would you have any insights as to how I could do this, or is the work-around of making an introspection query the best way to do this?

**Comment by rmosolgo** [comment]
I would _expect_ `Schema.types` to accept a `context` parameter:

https://github.com/rmosolgo/graphql-ruby/blob/11ec9c3aff36e0597a5af852eaff3bc343dc5612/lib/graphql/schema.rb#L214-L217

For example, in the specs: 

https://github.com/rmosolgo/graphql-ruby/blob/11ec9c3aff36e0597a5af852eaff3bc343dc5612/spec/graphql/schema/dynamic_members_spec.rb#L1013 

or used internally by the library: 

https://github.com/rmosolgo/graphql-ruby/blob/11ec9c3aff36e0597a5af852eaff3bc343dc5612/lib/graphql/schema/warden.rb#L101

So, I think you could do: 


```ruby 
changeset_types = Schema.types({ changeset_version: "2022-01-01" })
```

and that would return the set of types that apply to `2022-01-01`. Does that work for you, or, what happens when you try it?

**Comment by joelzwarrington** [comment]
After playing around a bit, I'm encountering issues when trying to use `.types(context)` as seen here:

```ruby
## Minimum base class setup (there are others, but focused on minimum to reproduce)
class BaseField < GraphQL::Schema::Field
  include GraphQL::Enterprise::Changeset::FieldIntegration
end

class BaseTypeMembership < GraphQL::Schema::TypeMembership
  include GraphQL::Enterprise::Changeset::TypeMembershipIntegration
end

class BaseUnion < GraphQL::Schema::Union
  type_membership_class BaseTypeMembership
end

class BaseObject < GraphQL::Schema::Object
  field_class BaseField
end
## End base class setup

class Show < BaseObject
  field :id, ID, null: false
end

class Movie < BaseObject
  field :id, ID, null: false
end

class Film < BaseObject
  field :id, ID, null: false
end

class PurchasedEntertainment < BaseUnion
  possible_types Show, Movie
end

class Query < BaseObject
  field :favourite_list, [Movie], null: false
  field :purchased, [PurchasedEntertainment], null: false
end

class V1 < GraphQL::Enterprise::Changeset
  release "2022-01-01"
  
  modifies Query do
    field :favourite_list, [Film], null: false
  end

  modifies PurchasedEntertainment do
    possible_types Film
    remove_possible_types Movie
  end
end

class Schema < GraphQL::Schema
  query Query
  use GraphQL::Enterprise::Changeset::Release, changesets: [
    V1
  ]
end
```

I get visible definition conflicts when trying to change the type of a field:

```ruby
Schema.types["Query"].fields
# GraphQL::Schema::DuplicateNamesError: Found two visible definitions for `Query.favouriteList`: #<BaseField Query.favouriteList: [Movie!]!>, #<BaseField Query.favouriteList: [Film!]!>
# from /Users/joelwarrington/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.4/lib/graphql/schema/warden.rb:58:in `block in visible_entry?'
```


Even when specifying the version, get the conflict:

```ruby
Schema.types({ changeset_version: "2022-01-01" })["Query"].fields
# GraphQL::Schema::DuplicateNamesError: Found two visible definitions for `Query.favouriteList`: #<BaseField Query.favouriteList: [Movie!]!>, #<BaseField Query.favouriteList: [Film!]!>
# from /Users/joelwarrington/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.4/lib/graphql/schema/warden.rb:58:in `block in visible_entry?'
```

I can't seem to get the possible types for a union in a certain changeset version:

```ruby
Schema.types({ changeset_version: "2022-01-01" })["PurchasedEntertainment"].possible_types
# => [Show, Movie, Film]

Schema.types({ changeset_version: "2022-01-01" })["PurchasedEntertainment"].all_possible_types
# => [Show, Movie, Film]
```

Introspection through `Schema.execute` appears to work as expected.
```ruby
Schema.execute("query { __type(name: \"PurchasedEntertainment\") { possibleTypes { name } } }", context: { changeset_version: "2022-01-01" }).to_h
# => {"data"=>{"__type"=>{"possibleTypes"=>[{"name"=>"Film"}, {"name"=>"Show"}]}}}
```

@rmosolgo would you like for me to create a bug report for these issues, or is this issue sufficient?

**Comment by rmosolgo** [comment]
Sorry for the unexpected behavior here -- I guess I didn't realize the breadth of your question. You're the _second_ one to walk these new code paths 😅 

 Essentially, _all_ the introspection methods accept a `context` for this purpose. For backwards compatibility, they also make a best-effort when no context is provided -- but they :boom: when they encounter a scenario that requires `context` to be provided. 

For the methods above: 

- `Schema.types(context = ...)` accepts a context positional argument ([api doc](https://graphql-ruby.org/api-doc/2.0.0/GraphQL/Schema.html#types-class_method))
- Likewise, `.fields(context = ...)` accepts a context positional argument ([api doc](https://graphql-ruby.org/api-doc/2.0.0/GraphQL/Schema/Member/HasFields.html#fields-instance_method)). I think providing `context` would fix the error you hit above: 

    ```ruby
    pp Schema.types["Query"].fields({ changeset_version: "2022-01-05" })
    # {"favouriteList"=>#<BaseField Query.favouriteList: [Movie!]!>,
    #  "purchased"=>#<BaseField Query.purchased: [PurchasedEntertainment!]!>}
    ```
    
    Maybe I should update that error message to suggest adding a context to the method call. 
    
    Also, for some reason, it's returning the wrong implementation of `favoriteList` (wrong return type) 🤔 Investigating in https://github.com/rmosolgo/graphql-ruby/issues/3929
    
- Similarly but differently, `.possible_types(context: ...)` accepts a context _keyword_ argument. (This method already accepted a positional argument for adding new possible types to the union or interface.) I think that would filter down the set of possible types like you expect: 

    ```ruby
    Schema.get_type("PurchasedEntertainment").possible_types(context: { changeset_version: "2022-01-01" })
    # => [Show, Movie]
    ```
    

At first, I thought you just wanted to look up a thing here or a thing there. But another option (back to your earlier suggestion!) is to create a copy of the schema for a certain changeset. For example: 


```ruby 
changeset_sdl = Schema.to_definition(context: { changeset_version: "2022-01-01" })
changeset_schema = GraphQL::Schema.from_definition(changeset_sdl)
```

Then, you can interact with `changeset_schema` without bothering with `context`: 

```ruby
changeset_schema.get_type("PurchasedEntertainment").possible_types.map {|t| t.graphql_name }
# => ["Film", "Show"]
changeset_schema.get_field("Query", "favouriteList").type.to_type_signature
# => "[Film!]!"
```


I think those methods _are_ working as expected ... aside from the wrong return value described above.

**Comment by joelzwarrington** [comment]
Ahhh, after reading your initial suggestion and pointing to specs I can see that you do need to pass context to each method.

It wasn't immediately clear that each method needed to specify a context, and I expected the `.types(context)` to carry over into the chained methods such as `.fields`, will try this out and your suggestion for creating a new schema!

**Comment by joelzwarrington** [comment]
I'm going to close this issue, but will add a few issues/feature requests based on the usage of this and likely some documentation to save others from going digging in the rabbit hole or having to open an issue!
