### ISSUE TITLE
Cannot return null for non-nullable field error for 2 queries of the same type 

### ISSUE THREAD

**Issue by whuang8** [rmosolgo/graphql-ruby#3922]
**Describe the bug**

A `Cannot return null for non-nullable field` error is returned when a query string contains 2 or more queries of the same type that differ in non-null fields 

**Versions**

`graphql` version: 1.13.8
`rails` (or other framework): 5.2.6

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok). Any custom extensions, etc?

```ruby
# Query.viewer
field :viewer, Account, null: false, extras: %i[ast_node]

def viewer(ast_node:)
  # A call to another service is called. Ultimately, the following ruby hash is returned:

  # for the first viewer query where the name field is requested
  {"name"=>"William Huang"}
  # OR
  # for the second viewer query where the id field is requested
   {"id"=>"12345678-1234-1234-1234-123412341234"}
end

# Account
module Account
  include Base::Types::BaseInterface

  field :id, Scalars::UUID, 'The identifier for the account', null: false
  field :name, String, 'A name for the account used for display purposes', null: false
end

# UUID
module Scalars
  class UUID < Base::Types::BaseScalar
    def self.coerce_input(input_value, _context)
      input_value
    end

    def self.coerce_result(ruby_value, _context)
      ruby_value
    end
  end
end

# Sitter
class Sitter < Base::Types::BaseObject
  implements Account

  # extra contents omitted 
end
```

**GraphQL query**

Example GraphQL query and response

```graphql
{
  viewer {
    name
  }
  viewer {
    id
  }
}
```

```json
{
  "data": null,
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Sitter.id"
    }
  ]
}
```

**Steps to reproduce**

1. Implement the schema detailed above
2. Send the graphql query shown above

**Expected behavior**

I expect a response body that looks like
```json
{
  "data": {
    "viewer": {
      "name": "William Huang",
      "id": "12345678-1234-1234-1234-123412341234"
    }
  }
}
```

**Actual behavior**

What specifically went wrong?

I am getting the following error
```json
{
  "data": null,
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Sitter.id"
    }
  ]
}
```

**Additional context**
When putting a breakpoint in the `viewer` resolver function,
```ruby
def viewer(ast_node:)
  binding.pry
  # A call to another service is called. Ultimately, the following ruby hash is returned:

  # for the first viewer query where the name field is requested
  {"name"=>"William Huang"}
  # OR
  # for the second viewer query where the id field is requested
  {"id"=>"12345678-1234-1234-1234-123412341234"}
end
```

I see that the `viewer` is only being invoked once with `ast_node.to_query_string`:
```sh
[5] pry(#<Types::QueryType>)> ast_node.to_query_string
=> "viewer {\n  name\n}"
```

Is it expected for the `viewer` resolver function to only be called once despite having 2 viewer queries defined in the query string?

Thank you so much for your help!

**Comment by rmosolgo** [comment]
> `viewer` called once despite having 2 viewer queries defined in the query string?

Yes, that's to be expected. Under the hood, GraphQL-Ruby merges identical selections into a single selection, so these two are equivalent:

```graphql
query {
  a { b } 
  a { c }
}

# is the same as: 
query {
  a { b c }
}
```

This is described by the spec, too: https://spec.graphql.org/draft/#sec-Field-Collection

GraphQL-Ruby is returning the "non-null field return null" error because the returned hash doesn't include enough data to satisfy the query, as described by the schema. To fix this error: 

- remove the `null: false` constraint from the `id` field (then `null` will be permitted)
- return a hash with _all_ the required data (that is, `{ "name" => "...", "id" => "..." }`), so that GraphQL-Ruby will be able to resolve fields as described in the schema. 

If you try one of those solutions but still encounter this error, please share what you tried and what happened when you tried it. Hope it helps!

**Comment by whuang8** [comment]
Thank you for explaining @rmosolgo!
