### ISSUE TITLE
Specify Field Options for HasNodeField and HasNodesField

### ISSUE THREAD

**Issue by tchamberland-bookjane** [rmosolgo/graphql-ruby#3942]
We are currently adding graphql support to our mobile application and we have decided to cautiously exposes and test individual  Query/Mutation fields to ensure functionality is correct.  In order to do this, I've implemented a custom Field class for our Query type.

```ruby
module Types
  class QueryType < Types::BaseObject
    field_class(Types::Fields::QueryField)

    include GraphQL::Types::Relay::HasNodeField
    include GraphQL::Types::Relay::HasNodesField

module Types::Fields
  class QueryField < GraphQL::Schema::Field

  def visible?
    super && (
        case ctx[:current_user]
        when MobileUser
          @mobile
        else
           # web application visibility logic
```

we also use the RelayID HasNode and HasNodes module

I'm just wondering if there's a way to pass `mobile: true` using a "supported" way?  Currently I am monkey patching the modules:

ie.
```ruby
module GraphQL
  module Types
    module Relay
      module HasNodeField
        class << self
          def field_options
            {
              # this part is from the original relay node module
              name: "node",
              type: GraphQL::Types::Relay::Node,
              null: true,
              description: "Fetches an object given its ID.",
              relay_node_field: true,

              # add this so mobile can see this graphql field
              mobile: true
            }
          end
``` 

**Is your feature request related to a problem? Please describe.**

Would prefer to do this without monkeypatching

**Describe the solution you'd like**
A supported way to pass field options to the node/nodes fields generated by the module

**Describe alternatives you've considered**

currently we are monkeypatching, I cannot find another way of doing this.

**Comment by rmosolgo** [comment]
Hmm, good question! No, there's not a built-in way to extend those settings. Honestly, I'd recommend just defining the field on your query type:


```ruby 
field :node, GraphQL::Types::Relay::Node, null: true, description: "Fetches an object given its ID", mobile: true

def node(id:)
  context.schema.object_from_id(id, ctx)
end 
```


In my opinion, the tradeoff of using the gem (indirection, complication) vs defining it "manually" doesn't really make sense once you start customizing it.

How does that approach sound to you?

**Comment by tchamberland-bookjane** [comment]
this makes sense and is straightforward enough thanks
