### ISSUE TITLE
Arguments are not taken from resolvers

### ISSUE THREAD

**Issue by woarewe** [rmosolgo/graphql-ruby#3943]
**Describe the bug**

Hi! I was playing with custom resolvers and bumped into strange behavior.
I have two models `Post` and `Category` having `many to many` relations.
I would like to make the following queries be valid for my schema:

```graphql
query {
  categories(ids: [1,2,3]) {
    id
    posts(ids: [1,2,3]) {
      id
    }
  }
}
```

The above query doesn't work because it says that the field `posts` doesn't accept argument `ids`, despite the following facts:
1. If I rearrange the query that way it will work
```graphql
query {
  posts(ids: [1,2,3]) {
    id
    categories(ids: [1,2,3]) {
      id
    }
  }
}
```
2. Just `posts` and `categories` with `ids` work fine as well.
```graphql
query {
  posts(ids: [1,2,3]) {
    id
  }
  categories(ids: [1,2,3]) {
    id
  }
}
```
3. The top-level fields and type-level fields use the same resolvers.
- Query.categories, Post.categories - `Resolvers::Categories`
- Query.posts, Category.posts - `Resolvers::Posts`

**Steps to reproduce**

1. Clone a GitHub repo https://github.com/woarewe/graphql-investigation and install all the things

```shell
git clone https://github.com/woarewe/graphql-investigation
cd graphql-investigation
git checkout bugs/arguments-are-not-taken-from-resolvers
bundle
bin/rake db:create
bin/rake db:migrate
bin/rake db:seed
bin/rails s
```

2. Run the above graphql queries and get following the errors
```json
{
  "errors": [
    {
      "message": "Field 'posts' doesn't accept argument 'ids'",
      "locations": [
        {
          "line": 4,
          "column": 11
        }
      ],
      "path": [
        "query",
        "categories",
        "posts",
        "ids"
      ],
      "extensions": {
        "code": "argumentNotAccepted",
        "name": "posts",
        "typeName": "Field",
        "argumentName": "ids"
      }
    }
  ]
}
```

3. Also you can notice [the generated schema](https://github.com/woarewe/graphql-investigation/blob/bugs/arguments-are-not-taken-from-resolvers/schema.graphql) [**does contain ids arg**](https://github.com/woarewe/graphql-investigation/blob/bugs/arguments-are-not-taken-from-resolvers/schema.graphql#L15) for `Post.categories` but [**does not**](https://github.com/woarewe/graphql-investigation/blob/bugs/arguments-are-not-taken-from-resolvers/schema.graphql#L4) for `Category.posts`.

4. Resolvers are placed there
-  [Categories](https://github.com/woarewe/graphql-investigation/blob/bugs/arguments-are-not-taken-from-resolvers/app/graphql/resolvers/categories.rb)
-  [Posts](https://github.com/woarewe/graphql-investigation/blob/bugs/arguments-are-not-taken-from-resolvers/app/graphql/resolvers/posts.rb)

5. The way how they are used:

- [In query as top-level fields](https://github.com/woarewe/graphql-investigation/blob/bugs/arguments-are-not-taken-from-resolvers/app/graphql/types/query_type.rb#L8-L9)
- [In Post type](https://github.com/woarewe/graphql-investigation/blob/bugs/arguments-are-not-taken-from-resolvers/app/graphql/types/post.rb#L5)
- [In Category](https://github.com/woarewe/graphql-investigation/blob/bugs/arguments-are-not-taken-from-resolvers/app/graphql/types/category.rb#L5)

**URL to the branch**
https://github.com/woarewe/graphql-investigation/tree/bugs/arguments-are-not-taken-from-resolvers

**Versions**

`graphql` 2.0.0
`rails` 7.0.2.2
`ruby` 3.1.0

Thank you very much for your work and time!

**Comment by rmosolgo** [comment]
Woah! Thanks for the detailed report. 

My guess is that this bug comes from the circular dependency between `Resolvers::Categories` and `Resolvers::Posts`. I think you might be able to test that by moving the `type ...` configuration for each resolver to the _bottom_ of the class (after the argument definitions). That way, when the circular load happens, the resolver class already has its configured argument. Another approach might be to use a string for `type ...`, for example `type "[Types::Post]"` -- that will make GraphQL-Ruby defer loading `types/post.rb`. 

If it turns out to be a circular dependency issue, maybe #3916 will fix it (when I finish it)! In any case, even if one of the work-arounds above works for you, I'd like to keep this open and make sure that your replication repo works properly in a future release.

**Comment by woarewe** [comment]
@rmosolgo Moving the `type` declaration under the args has fixed the problem. Thank you very much!

**Comment by rmosolgo** [comment]
Thanks again for the replication code on this. I confirmed that #3916 fixed this error by: 

- cloning & starting as described above 
- running the bad query described above -- i got the same error 
- update the gemfile to use `gem "graphql", github: "rmosolgo/graphql-ruby"`, `bundle update graphql`
- restart the server, retry the query -- it works!

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/2231765/154725314-18c65250-683f-423c-8992-7da490f34e96.png">

Thanks again, and please let me know if you have more trouble with this after 2.0.1 is released.
