### ISSUE TITLE
Looks like schema types in rspec are different from generated schema

### ISSUE THREAD

**Issue by macanton** [rmosolgo/graphql-ruby#3948]
**Describe the bug**

We have two types.
`item_type` and `field_configuration_type`

In dev and production env it works ok and all fields are fetched / updated and so on, but in rspec I receive errors like:
`Field 'translations' doesn't exist on type 'FieldConfiguration'` (with item_type if works ok and what is more interesting resolvers and mutations for these 2 objects are identical except object classes)
No errors on the other fields of FieldConfiguration.
So it seems like only certain fields are not defined for some reason in rspec.

Can it be due to the name of the type 'FieldConfiguration' or smth?

**Versions**
`graphql` version: 1.12.24
`rails` (or other framework): 3.X
**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok). Any custom extensions, etc?

```ruby

# Here it returns
# Field 'fieldConfiguration' doesn't exist on type 'FieldConfigurationsDestroyMutationPayload'
Mutations::FieldConfigurations::DestroyMutation < Mutations::BaseRelayMutation
  field :field_configuration, Types::FieldConfigurationType, null: true
end

# Here it returns
# Field 'translations' doesn't exist on type 'FieldConfiguration
# Field 'fields' doesn't exist on type 'FieldConfiguration
class Queries::FieldConfigurationResolver < Queries::BaseQueryResolver
  type Types::FieldConfigurationType, null: true
end


class Types::FieldConfigurationType < Types::BaseObject
  field :id, ID, null: false
  field  :translatedName, String, null: false
  field :translations, Types::FieldConfigurations::TranslationsType, null: false
  field :fields, [Types::FieldConfigurations::FieldType], null: true
  field :userId, ID, null: false
  field :user, Types::UserType, null: false
end
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
query getFieldConfigurations(
                $page: Int!,
                $perPage: Int!,
                $userId: ID!,
              ) {
                fieldConfigurations(page: $page,
                                 perPage: $perPage,
                                 userId: $organizationId,
                                 ) {
                  nodes {
                    id
                    translatedName
                    translations {
                      en
                    }
                    fields {
                      name
                      section
                    }
                    userId
                    user {
                      id
                    }
                  }
                  metadata {
                    offset
                    totalCount
                  }
                }
              }
```

```ruby
{"errors"=>[{"message"=>"Field 'translations' doesn't exist on type 'FieldConfiguration'", "locations"=>[{"line"=>16, "column"=>21}], "path"=>["query getFieldConfigurations", "fieldConfigurations", "nodes", "translations"], "extensions"=>{"code"=>"undefinedField", "typeName"=>"FieldConfiguration", "fieldName"=>"translations"}}, {"message"=>"Field 'fields' doesn't exist on type 'FieldConfiguration'", "locations"=>[{"line"=>21, "column"=>21}], "path"=>["query getFieldConfigurations", "fieldConfigurations", "nodes", "fields"], "extensions"=>{"code"=>"undefinedField", "typeName"=>"FieldConfiguration", "fieldName"=>"fields"}}]}
```

**Steps to reproduce**

Explained config above

**Expected behavior**

Type fields list in schema generated with rake task should be the same as in rspec

**Actual behavior**

What specifically went wrong?

Rspec type fields for one specific type are different from what I receive from the running server

**Additional context**

If you can direct me which direction to go, that would be awesome :D
```
  def self.default_graphql_name
    if name.starts_with?("GraphQL::")
      name.split("::").last.sub(/Type\Z/, "")
    else
      (name.split("::") - ["Inputs", "Enums", "Mutations", "Types", "Resolvers", "Queries"]).join("").sub(/Type\Z/, "")
    end
  end

```

**Comment by rmosolgo** [comment]
Very strange! A couple possibilities I can think of: 


- Maybe some _other_ error is interrupting schema initialization. If you check the output from RSpec, is there anything else in the terminal? 
- Is `field_configuration_type.rb` being evaluated the whole way? You could add `pp self.fields` to the bottom of that class definition to make sure it's completely evaluated. If you share the output from that, maybe it will have some clues where to look next. 
- Are you using "visibility" (eg, `def self.visible?` or `def visible?`) to hide any parts of your schema? If anything is hidden from the viewer, it fails with error messages like the ones you mentioned above.

I can't _think_ of a reason that the name would cause any trouble (especially _only_ in test), but I could be wrong...

**Comment by macanton** [comment]
Thank you for your answer :)

First of all:
After I did `bundle clean --force` I started to receive an exception:
`GraphQL::Schema::Field::MissingReturnTypeError:
  Can't determine the return type for Query.fieldConfigurations (it has `resolver: Queries::FieldConfigurationsResolver`, consider configuration a `type ...` for that class)`
What is interesting is that I have the following chain:
1. ```field :field_configurations, resolver: Queries::FieldConfigurationsResolver```
2. 
```
class Queries::FieldConfigurationsResolver
   type Types::FieldConfigurationType.collection_type(
       metadata_type: Types::DatabasePaginatedCollectionMetadataType
    ), null: true
end
```
`pp self.fields` in fieldConfigurationType not printed, but in another class printed. 
What can be the reason that fieldConfgirutaionType not initialized silently and crashes only in tests execution?

**Comment by macanton** [comment]
Hello again :D
I think I found a stable sequence of actions that can fail it.
Just to re-call I have chain of classes like:
```
class Queries::FieldConfigurationsResolver < Queries::BaseQueryResolver
  type Types::FieldConfigurationType.collection_type(
    metadata_type: Types::DatabasePaginatedCollectionMetadataType
  ), null: true
end

class Types::FieldConfigurationType < Types::BaseObject
  field :translations, Types::FieldConfigurations::TranslationsType, null: false
end

class Types::FieldConfigurations::TranslationsType < Types::BaseObject
  field :en, ::Types::FieldConfigurations::TranslationType, null: true
end

class Types::FieldConfigurations::TranslationType < Types::BaseObject
  field :name, String, null: true
end
```

I start rails console and if I first print resolver, than I get the error:
`uninitialized constant Types::FieldConfigurations::TranslationType`

But if after starting the console print `Types::FieldConfigurations::TranslationType`
and after that I print `Queries::FieldConfigurationsResolver`, then it returns returns:
`Can't determine the return type for Query.fieldConfigurations (it has `resolver: Queries::FieldConfigurationsResolver`, consider configuration a `type ...` for that class)`

And at the end if I print classes in following sequence from the beginning:
```
Types::FieldConfigurations::TranslationType
Types::FieldConfigurations::TranslationsType
Queries::FieldConfigurationsResolver
```
Then classes are initialized with errors

**Comment by macanton** [comment]
I think I solved it and it is totally my mistake
I defined `["Inputs", "Enums", "Mutations", "Types", "Resolvers", "Queries"]` as constant in Schema and then referred to it in base object, base type and so on. That was my circular dependency. After I removed that reference - these errors disappear. Thank you for the help :)
