### ISSUE TITLE
[pro] Usage of redis.pipelined in redis backend triggers deprecation warning from redis gem

### ISSUE THREAD

**Issue by tim-heighes-fishbrain** [rmosolgo/graphql-ruby#3953]
If I am reading the code correctly, `GraphQL::Pro::OperationStore::RedisBackend.get_operation` (graphql-pro v1.21.3) triggers a deprecation warning from redis gem v4.6.0.

The deprecation suggests that code like:
```
@redis.pipelined do
  @redis.hset...
end
```

should be replaced by:

```
@redis.pipelined do |pipeline
  pipeline.hset...
end
```

**Comment by rmosolgo** [comment]
Hey, thanks for reporting this! Could you try upgrading to graphql-pro 1.21.4? I updated that code in that release but forgot to mention it in the changelog. (I just added it to the changelog in d6a8a277d). Please let me know if you're still seeing the warning after updating to that version!
