### ISSUE TITLE
A pattern to expose offset pagination metadata?

### ISSUE THREAD

**Issue by reicolee** [rmosolgo/graphql-ruby#3958]
Because of strict product requirements, I am not able to use cursor-based pagination from `Connections`, and have to use offset-based pagination

is there a way to pass metadata such as `total_count`,  `has_next_page`, etc with offset pagination similar to how `Connection` wrapper pass those metadata for cursor-based pagination, but without using `Connections` objects? 

One of the queries I have right now accepts `limit` and `offset` as pagination arguments, and return an array of the items, but I am not sure how to return metadata along with these items

I have googled but did not seem to find a pattern to achieve this, wonder if anyone has encountered this issue / requirement and have a way forward?

Thanks!

```
module Resolvers
  module Item
    class ItemsResolver < AuthorizedResolver
      type [Types::Items], null: false

      argument :user_id, ID, required: true
      argument :pagination, Types::Pagination::OffsetInput, required: true

      def resolve(user_id:, pagination:)
        base_query = ItemsService.get_items(user_id)
        base_query.limit(pagination[:limit]).offset(pagination[:offset])
      end
    end
  end
end


```

**Comment by reicolee** [comment]
Just actually found this snippet from a while ago.. and it works
https://gist.github.com/rmosolgo/da1dd95c297d8ed218a319ac83a05d91

**Comment by rmosolgo** [comment]
Glad you found your way to it - I forgot all about it, but I was about to recommend the same thing!
