### ISSUE TITLE
GraphQL Enterprise: Method on Schema to retrieve defined Changesets

### ISSUE THREAD

**Issue by joelzwarrington** [rmosolgo/graphql-ruby#3966]
It would be nice to get which changesets have been loaded into a Schema by being able to call a method on the schema to retrieve changesets. This information is useful for tooling which automates referencing changesets via the schema as opposed to referencing them directly.

I have written the following in a personal project but would like to get thoughts on potentially including something like this in the package?

```ruby
class Schema < GraphQL::Schema
  class << self
    def changesets
      @changesets ||= begin
        if module_parent.const_defined?(:Changesets)
          changesets_module = module_parent.const_get(:Changesets)

          # get changesets automatically via module -
          # not the goal of this feature request, but showing how I'm using this
          if changesets_module
            changesets = changesets_module.constants.filter_map do |c|
            klass = changesets_module.const_get(c)
            klass if klass < BaseChangeset && klass&.release&.present?
          end

          use GraphQL::Enterprise::Changeset::Release, changesets: changesets

          changesets
        end
      end
    end
  end
end
```

- is there anything to be worried about this approach?
- is it possible to include something similar in the library?

**Comment by rmosolgo** [comment]
Yes, that definitely makes sense! I just released GraphQL-Enterprise v1.1.2 which includes some new introspection methods, documented here: https://graphql-ruby.org/changesets/releases.html#introspection-methods

Let me know if you run into any trouble with them or have any suggestions for improving them. 

As for the code above, the only thing that stands out to me is the constant detection -- I doubt it would play nice with a normal Rails development setup where constants aren't loaded until they're referenced. (That's _why_ I opted for an API based on explicitly naming the changeset classes in the schema definition: it guarantees that Rails will load the changeset classes in development!)

**Comment by crpahl** [comment]
@rmosolgo 

> I doubt it would play nice with a normal Rails development setup where constants aren't loaded until they're referenced.

We actually have have `config.eager_load = false` set in our development environment and this code works for us. I think this will actually be safe for any development environment based on how `const_defined?` works?

<img width="650" alt="image" src="https://user-images.githubusercontent.com/506155/156468506-59a6edbe-9b15-4337-b6a6-eb0bc04be830.png">

And then the following `const_get` will work since it triggers autoloading.

**Comment by rmosolgo** [comment]
Wow, that's cool. I wonder if that was improved when Rails adopted Zeitwerk -- IIRC it uses `autoload(...)` under the hood. Thanks for sharing that -- TIL!
