### ISSUE TITLE
GraphQL::Pro::PostgresStableRelationConnection breaks custom SQL scopes

### ISSUE THREAD

**Issue by gopeter** [rmosolgo/graphql-ruby#3976]
**Describe the bug**

I've built a scope in my `Project` model which allows me to order projects by their progress:

```ruby
scope :order_by_progress_relative, ->(order) {
  null = order == "DESC" ? "NULLS LAST" : "NULLS FIRST"
  select_append("(tickets_closed::decimal / NULLIF(tickets_open + tickets_closed, 0)) as tickets_relative").order(Arel.sql("tickets_relative #{order} #{null}"))
}
```

`select_append` allows me to select additional fields in my scopes:

```ruby
# see https://stackoverflow.com/a/41401552/1184904
module ActiveRecord
  module QueryMethods
    def select_append(*fields)
      fields.unshift(arel_table[Arel.star]) if select_values.none?
      select(*fields)
    end
  end
end
```

Using this together with `connections.add(ActiveRecord::Relation, GraphQL::Pro::PostgresStableRelationConnection)` breaks the SQL query:

```sql
SELECT COUNT(*) 
FROM (
	SELECT DISTINCT 
		"projects".*, 
		LOWER(customers.company),
		(tickets_closed::decimal / NULLIF(tickets_open + tickets_closed, 0)) as tickets_relative,
		LOWER(customers.company) AS cursor_0,
		NULLIF(tickets_open + tickets_closed, 0)) AS cursor_1, projects.id AS cursor_2 FROM "projects" # "(tickets_closed::decimal / " is missing which leads into the double closed ")" before "AS cursor_1"
...
```

So the part which creates the `AS cursor_X` statement does not include the whole `(tickets_closed::decimal / NULLIF(tickets_open + tickets_closed, 0))` part and just `NULLIF(tickets_open + tickets_closed, 0))`, which then throws a SQL syntax error.

**Versions**

`graphql`: `1.13.10`
`graphql-pro`: `1.21.4`
`graphql-batch`: `0.5.0`
`rails`: `6.1.4.6`

**Comment by gopeter** [comment]
I just looked into the source code of the pro gem and found out that `ALIASED_SELECT` extracts just the part hat I've mentioned above.

**Comment by rmosolgo** [comment]
Hey, thanks for the detailed report! I just released graphql-pro 1.21.5 which includes a more generous option in the expression for matching aliased selects (`\(.*\)`) that worked for me with a query like the one you showed above. Could you give that new version a try and let me know if it works for you?

**Comment by gopeter** [comment]
Works fine, thank you very much! 👍

**Comment by gopeter** [comment]
Oh, but doesn't select this now more than it should 🤔 

![image](https://user-images.githubusercontent.com/1242960/157038904-2654d2b3-01ec-4eec-9bab-121a491c7de3.png)

**Comment by rmosolgo** [comment]
Ruh roh, sorry it's not working quite right yet. Could you share some more details? I'm having trouble constructing the context around that truncated screenshot. For example: 

- Did that SQL query come from your ruby application? Could you share the code that prepared it? 
- When you ran it, did you encounter a runtime error? Could you share the error message and backtrace? 
- Or, did the system misbehave? Could you please describe what you expected to happen vs what _actually_ happened?

Thanks!

**Comment by gopeter** [comment]
Oh my gosh, sorry! The screenshot was just my try on regexr.com to get why it didn't worked - your regex + the query that Rails generates. But your regex is used for the `select` parts only and does not run against the whole query string. So my worries are unfounded.

Sorry for the confusion and thanks for the fast fix!
