### ISSUE TITLE
Undefined method `use' for custom GraphQL::Pagination::Connections

### ISSUE THREAD

**Issue by 23tux** [rmosolgo/graphql-ruby#3981]
**Describe the bug**

A custom implementation using `GraphQL::Pagination::Connections` throws an error since graphql-ruby 2.0.0. The implementation was a suggestion from this comment back in 2020: https://github.com/rmosolgo/graphql-ruby/issues/2923#issuecomment-625805397

Is the `GraphQL::Pagination::Connections` class deprecated (I did not find it in this list https://github.com/rmosolgo/graphql-ruby/issues/3729), or did the implementation change?

**Versions**

`graphql` version: 2.0.0
`rails` (or other framework): 6.0.4.7
`graphql-batch`: 0.5.1

**GraphQL schema**

```ruby
class CustomMaxPageSizeConnections < GraphQL::Pagination::Connections
  def wrap(field, parent, items, arguments, context)
    super.tap do |connection|
      connection.max_page_size = context[:max_page_size] if context[:max_page_size]
    end
  end
end

class Schema < GraphQL::Schema
  use CustomMaxPageSizeConnections
end
```

**Backtrace**

```
NoMethodError: undefined method `use' for CustomMaxPageSizeConnections:Class
from /usr/local/bundle/gems/graphql-2.0.0/lib/graphql/schema.rb:205:in `use'
```

**Comment by 23tux** [comment]
Just had a look what changed between those releases (https://github.com/rmosolgo/graphql-ruby/compare/v1.13.10...v2.0.0) and in https://github.com/rmosolgo/graphql-ruby/commit/1a4d951c99067efef4d9ca1b975fe782b89a73c8 the `GraphQL::Pagination::Connections.use` method was removed.

If I add this, everything works fine again:

```
class Schema < GraphQL::Schema
  self.connections = CustomMaxPageSizeConnections.new(schema: self)
end
```

Is this the right way? I have a custom `ActiveRecordRelationStableConnection` for `ActiveRecord::Relation`, and use the `GraphQL::Pagination::ArrayConnection` for `Array`. Both of them should be able to receive the custom `max_page_size` parameter that gets injected into `context[:max_page_size]` by my controller.

**Comment by rmosolgo** [comment]
:+1: That looks like a decent migration to me. Sorry for the breakage -- I totally forgot that someone might be `.use`-ing a custom subclass!

**Comment by 23tux** [comment]
haha, `.use`-ing... Thanks!

**Comment by nevesenin** [comment]
Just stumbled upon this, because I had the same issue. I re-added the `use` method to my custom class. I'd like to suggest maybe having a `.connection` method on the schema for convenience and to be more explicit about having custom connection class.
