### ISSUE TITLE
[PRO] Documentation at guides/pro/encoders.md needs to be updated to utilize class based definitions

### ISSUE THREAD

**Issue by thornomad** [rmosolgo/graphql-ruby#3991]
This is just a request to update the documentation at `guides/pro/encoders.md`.  It is using `.define` but that approach is deprecated.  See https://github.com/rmosolgo/graphql-ruby/issues/3161#issuecomment-1072456057

**Comment by rmosolgo** [comment]
Thanks for reporting this! Sorry I missed it before 🤦 and thanks to @joelzwarrington for taking care of it.
