### ISSUE TITLE
No more data after query with failure since 2.0.1

### ISSUE THREAD

**Issue by butsjoh** [rmosolgo/graphql-ruby#3999]
**Describe the bug**

No more partial responses when there is an error one of the fields.

**Versions**

`graphql` version: 2.0.1

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
      query partialResponseQuery($somethingId: ID!, $something2Id: ID!) {
        sessionInfo {
          tenant {
            name
          }
        }
        resp1: events(ids: [$somethingId]) {
          totalCount
        }
        resp2: events(ids: [$something2Id]) {
          totalCount
        }
        resp3: events(ids: [$somethingId, $something2Id]) {
          totalCount
        }
      }
```

Response as of 2.0.1 and higher:

```json
{
  "data": null,
  "errors": [
    {
      "message": "No object found for `ids: \"xxx\"`",
      "locations": [
        {
          "line": 10,
          "column": 3
        }
      ],
      "path": [
        "resp2"
      ]
    },
    {
      "message": "No object found for `ids: \"xxx\"`",
      "locations": [
        {
          "line": 13,
          "column": 3
        }
      ],
      "path": [
        "resp3"
      ]
    }
  ]
}
```

Response before 2.0.1:

```json
{
  "data": {
    "sessionInfo": {
      "tenant": {
        "name": "Somebody"
      }
    },
    "resp1": {
      "totalCount": 0
    },
    "resp2": null,
    "resp3": null
  },
  "errors": [
    {
      "message": "No object found for `ids: \"yyy\"`",
      "locations": [
        {
          "line": 10,
          "column": 3
        }
      ],
      "path": [
        "resp2"
      ]
    },
    {
      "message": "No object found for `ids: \"yyy\"`",
      "locations": [
        {
          "line": 13,
          "column": 3
        }
      ],
      "path": [
        "resp3"
      ]
    }
  ]
}
```

**Steps to reproduce**

See examples above

**Expected behavior**

We would expect that all responses are still coming back partially and the ones that have errors return null as their data result and that errors contains the actual error.

**Actual behavior**

Since 2.0.1 it seems whenever there is an error the return is always data:  nil and only the errors are returned. The fields that actually resolve fine are not returned anymore.

**Additional context**

I checked the changelog of 2.0.1 and also looked at some PR's but it is not clear to me what is causing this. Is this a configuration that needs to be turned on? We bumped from 1.13.10 to the latest 2.0.3 and then backtracked to 2.0.0 where the problem was not happening. The bump to 2.0.1 caused this issue.

**Comment by rmosolgo** [comment]
Hmm! Thanks for the detailed report. My guess is that it's some bug caused by https://github.com/rmosolgo/graphql-ruby/pull/3916 -- it's been hard to figure out all the repercussions of that change. 

Could you please share the configuration for the `events` field, and, assuming it's backed with a resolver, the source for the resolver (especially its argument configs and return type configs)? I bet something is getting dropped there. 

Another thing to investigate is, did your schema SDL change between 2.0.0 and 2.0.1? In the responses above, the 2.0.1 result looks as though `events` has a non-null return type, but the 2.0.0 result looks as though `events` has a nullable return type (`null: true`). I'm curious whether that change is reflected in SDL, or whether it's just a bug in configuration/schema definition. 

Let me know what you find!

**Comment by butsjoh** [comment]
Hi,

Here you go:

The ruby graph related stuff

```ruby
class QueryType < GraphQL::Schema::Object
      field :events, resolver: Resolvers::Events::CollectionQuery, null: true
end

module Resolvers
  class Events::CollectionQuery < PublicGraph::BaseQuery

    type Types::EventType.connection_type, null: false

    argument :scope, Types::EventScopeType, required: false

     resolve! do
         context.loader(:events).load(scope: scope) # uses graphql-batch
     end
  end
end
```

Regarding your question about schema change i can say that we only bumped the graphql gem with bundle update after modifying the Gemfile to use the 2.x version so no other changes were added when we ran the tests locally. If we switch back to 2.0.0 it works fine.

**Comment by butsjoh** [comment]
After looking into the PR it might be related to how we have implemented our own dsl for the resolve! block you see in the code.

We are doing something like this.

```ruby
class BaseMutation < GraphQL::Schema::RelayClassicMutation
  include ResolveWithArguments
end

 module ResolveWithArguments

    def self.included(base)
       base.extend(ClassMethods)
    end

    module ClassMethods

      def resolve!(&block)
        if block_given?
          @resolve_block = block
        else
          @resolve_block || ->() { fail NotImplementedError }
        end
      end
   end

    def resolve(**args)
      instance_exec(&self.class.resolve!)
    end
  end
```

Because in the PR you mentioned stuff gets changed related to resolve this might not longer be compatible?

**Comment by rmosolgo** [comment]
Thanks for those details -- that's really helpful. I think I've got a fix together in #4000, could you give it a try in your app to confirm? You can install it in your gemfile with this: 

```ruby
gem "graphql", github: "rmosolgo/graphql-ruby", ref: "use-field-null-config"
```

If it works for you locally, I'll prepare a 2.0.4 release with that fix.

**Comment by butsjoh** [comment]
I can confirm it is working 👍

**Comment by butsjoh** [comment]
Like always i will :) Thnx for the quick follow up and resolution, much appreciated !
