### ISSUE TITLE
Seems like #3916 broke argument inheritance in mutation resolvers?

### ISSUE THREAD

**Issue by srgoldman** [rmosolgo/graphql-ruby#4005]
**Describe the bug**

I have a base mutation class which implements common arguments shared by some subclasses.
With version 2.0.0, it works as it previously did.
With version 2.0.1, it no longer works, the arguments I expect to be inherited do not show up on the subclasses.

**Versions**

`graphql` version: 2.0.1
`rails` (or other framework): rails 7.0.1
other applicable versions (`graphql-batch`, etc)

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok). Any custom extensions, etc?

```ruby
module Mutations
  module Carts
    class ModifyCartItemsBase < Mutations::BaseMutation
      description I18n.t('api.docs.mutation.carts.modify_items.api')

      field :errors, [Types::UserError], null: true

      argument :cart_id, ID, required: true, description: I18n.t('api.docs.mutation.carts.modify_items.args.cart_id')
      argument :details, Types::Inputs::CartDetailsInput, required: false, description: I18n.t('api.docs.types.inputs.cart_update_input.desc')
      argument :add_items, [Types::Inputs::CartAddItemInput], required: false, description: I18n.t('api.docs.mutation.carts.modify_items.args.add_items')
      argument :update_items, [Types::Inputs::CartUpdateItemInput], required: false, description: I18n.t('api.docs.mutation.carts.modify_items.args.update_items')

      def resolve(cart_id:, details: {}, add_items: [], update_items: [], email: nil)
      end
   end
  end
end

module Mutations
  module Carts
    class ModifyTeamCartItems < Mutations::Carts::ModifyCartItemsBase
      field :team_cart, Types::TeamCart, null: false

      argument :email, String, required: false, description: I18n.t('api.docs.mutation.team_carts.modify_items.args.email')

      def resolve(cart_id:, details: {}, add_items: [], update_items: [], email: nil)
      end
    end
  end
end
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

Standard inspection of the schema.

**Steps to reproduce**

Steps to reproduce the behavior

**Expected behavior**

This is what I expect to see in the schema:
<img width="348" alt="image" src="https://user-images.githubusercontent.com/251189/160009228-2fb69089-d596-4fd6-af50-2805647ff3a9.png">

**Actual behavior**

This is what I actually see:
<img width="356" alt="image" src="https://user-images.githubusercontent.com/251189/160009362-78079cd0-2ebb-4784-8969-ac2f293cf80d.png">

The breakage appears to be a result of #3916. The inherited arguments are not carrying through.

Place full backtrace here (if a Ruby exception is involved):

<details>
<summary>Click to view exception backtrace</summary>

```
```

</details>

**Additional context**

With these details, we can efficiently hunt down the bug!

**Comment by rmosolgo** [comment]
Thanks for the detailed report. I tried to replicate it locally, and I found that it fails when the parent class isn't hooked up to the schema 🤔 ! The script below is _broken_, unless you uncomment the lines that attach the parent class to the schema. 

<details>
<summary>Replication</summary>

<p>

```ruby
require "bundler/inline"

gemfile do
  gem "graphql", "2.0.3"
end

class TestSchema < GraphQL::Schema
  class BaseMutation < GraphQL::Schema::Mutation
  end

  class ParentMutation < BaseMutation
    argument :cart_id, ID
    field :inputs, String

    def resolve(**inputs)
      { inputs: inputs.inspect }
    end
  end

  class ChildMutation < ParentMutation
    argument :email, String
  end

  class Mutation < GraphQL::Schema::Object
    # field :parent, mutation: ParentMutation
    field :child, mutation: ChildMutation
  end

  mutation(Mutation)
end

# pp TestSchema.execute("mutation { parent(cartId: \"123\") { inputs } }")

pp TestSchema.execute("mutation { child(email: \"abc\", cartId: \"123\") { inputs } }")
```

</p>
</details>

I'll work up a fix soon!

**Comment by srgoldman** [comment]
Awesome! Confirmed that did the trick. Thanks for the speedy resolution, really appreciate it.
