### ISSUE TITLE
Passing null to GraphQL::Types::ISO8601 type results in an error.

### ISSUE THREAD

**Issue by ofnhwx** [rmosolgo/graphql-ruby#4019]
**Describe the bug**

Passing null to the argument of GraphQL::Types::ISO8601Date type of mutation occurs GraphQL::DateEncodingError.

**Versions**

`graphql` version: 1.13.6
`rails`: 6.1.5

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok). Any custom extensions, etc?

```ruby
class Task < GraphQL::Schema::Object
  field :id, ID, null: false
  field :due_on, GraphQL::Types::ISO8601Date, null: true
  # …
end

class UpdateTask < Mutations::BaseMutation
  argument :id, ID, required: true

  argument :due_on, GraphQL::Types::ISO8601Date, required: false
  # …

  field :result, Task, null: false
end

class MutationType < Types::BaseObject
  field :update_task, mutation: UpdateTask
end

class ApplicationSchema < GraphQL::Schema
  mutation MutationType

  def self.type_error(err, _query_ctx)
    p err
    super
  end
end
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
mutation {
  updateTask(input: { id: "xxx", dueOn: null }) {
    result {
      id
      dueOn
    }
  }
}
```

```json
{
  "data": {
    "updateTask": […]
  }
}
```

**Steps to reproduce**

Always occurs.

**Expected behavior**

GraphQL::DateEncodingError is not occurs.

**Actual behavior**

> #<GraphQL::DateEncodingError: Date cannot be parsed: . \nDate must be be able to be parsed as a Ruby Date object.>

**Additional context**

This change causes a GraphQL::DateEncodingError to be raised if nil is passed.
https://github.com/rmosolgo/graphql-ruby/commit/d7a723ed453a49cf1a500dec12718845342b0cb3

**Comment by rmosolgo** [comment]
Thanks for this detailed report! I guess that method should just handle `nil` nicely. For reference: 


https://github.com/rmosolgo/graphql-ruby/blob/8d1a5b12de0733c09ed8fc3bad83ee0e80ceb73a/lib/graphql/types/string.rb#L22-L24

https://github.com/rmosolgo/graphql-ruby/blob/8d1a5b12de0733c09ed8fc3bad83ee0e80ceb73a/lib/graphql/types/int.rb#L12-L13

Feel free to take a crack at it if you're interested, otherwise, I'll take a look soon!

**Comment by choznerol** [comment]
If nobody is currently working on it, I would like to try making a fix.
