### ISSUE TITLE
Default/Fallback Implementation of Interface Fields

### ISSUE THREAD

**Issue by dleavitt** [rmosolgo/graphql-ruby#4020]
**Is your feature request related to a problem? Please describe.**

Currently if you define a field implementation on an interface, it will take precedence over `public_send` and hash lookup for that field on objects that implement the interface. This is probably for the best, but on interfaces it's perhaps more useful to specify a _fallback_ implementation.

**Scenario**

I have a data model that has lots of entity types. All of them have an `id` property. Most of them have a `name` property, but some of them don't. I want all of them to implement an interface (`Node`) that has a required `id` property and an optional `name` property.

```graphql
interface Node { id: ID! name: String }
```

If I add an implementation like `def name= nil` to my interface, it'll make _all_ my nodes come back with `nil` for the name. If I don't, I'll get an error b/c some of my data objects don't have a "name" property.

**Describe the solution you'd like**

This may already be achievable in some way I haven't discovered. If not, there are a bunch of possible solutions:

1. Add something to the interface DSL allowing you to define `fallback_methods` for fields. These would called instead of erroring  if `key?`, `respond_to?`, etc. fail. Seems annoying to implement/maintain.
2. ⭐  Add a new property to Field, `fallback_value` or `default` or something, that behaves similarly to option 1. Seems easier to implement and potentially useful in other situations where you might want to return nil instead of erroring.
3. Make it so `public_send` etc., _always_ take precedence over methods defined on interfaces. Backwards-incompatible, potentially surprising.
5. ⭐ Do something with `Field#resolve` so it's easier for a field implementation to provide a fallback on top of the default behavior. E.g. I want to do:
```ruby
field :name, String
def name
  context[:current_field].try_resolve_from_object(self) || "default_value"
  # or ideally
  yield || "default_value"
end
```

Happy to start a PR if any of these sound good to you.

**Describe alternatives you've considered**

It's not a big deal to work around the absence of this feature. If the fallback behavior you want is trivial, It's easy to add an empty implementation to each of your GQL objects or data objects. If the fallback behavior is fancier, it can be put in a mixin or something.

**Repro-ish**

Let's say my schema looks like this:

```graphql
interface Node { id: ID! name: String }
type Query { nodes: [Node!] }

type NamedObj implements Node { id: ID! name: String! }
type Obj      implements Node { id: ID! name: String }
```

here's `Node` in Ruby:

```ruby
module NodeType
  include GraphQL::Schema::Interface

  field :id, ID, null: false
  field :name, String
end
```

And here's the underlying data:
```ruby
DATA = [
  # NamedObj
  OpenStruct.new(id: "1", name: "Name"),
  # Obj
  OpenStruct.new(id: "2"),
]
```

When I run this query against the schema:
```graphql
{ nodes { id, name, __typename } }
```

I'll get "Failed to implement Node.name..." b/c my second object doesn't respond to `name`.

So I'll add an implementation of `name` to `NoteType`:

```ruby
def name
  "fallback"
end
```

No more errors, but now `name` is "fallback" for _all_ my nodes, even the ones with names.

**Comment by rmosolgo** [comment]
I can appreciate how you'd like it to work differently, but given the maintenance and compatibility challenges you mention for the other options, how about implementing something like this?

```
module NoteType 
  # ... 
  def name 
    if object.respond_to?(:name)
      object.name 
     else 
       "fallback" 
      end 
    end 
  end 
  ```
  
  Would that give you the behavior you're looking for?

**Comment by dleavitt** [comment]
That would indeed work for a lot of cases but it would be nicer to be able to use the logic that the library uses to do the value lookup. I think options 2 and especially 4 could accomplish this in a way that doesn't create much additional maintenance surface area. Would you be open to a PR?

**Comment by rmosolgo** [comment]
Yeah, I guess option 2 described above could work. I'm open to a `fallback_value:` option whose value is returned instead of raising this error: 

https://github.com/rmosolgo/graphql-ruby/blob/170b40245756a9d485c9f388a51f1e9c09f18da9/lib/graphql/schema/field.rb#L669-L670

(As for option 4, I doubt that `yield` can be efficiently implemented, and even if it can, it creates a challenging coupling between application-provided resolve methods and the rest of the GraphQL-Ruby runtime.)

**Comment by dleavitt** [comment]
Great! How about `default_value` for consistency with arguments? It looks like [Graphene](https://github.com/graphql-python/graphene/blob/03277a55123fd2f8a8465c5fa671f7fb0d004c26/graphene/types/field.py#L61) and [Absinthe](https://github.com/absinthe-graphql/absinthe/blob/e869dbb1864fd5d8cba463d3c6cae8ba8e4f1ff7/lib/absinthe/type/field.ex#L81) support something similar.

**Comment by dleavitt** [comment]
Makes sense + agree, thanks for explaining. I'll close this and open a new ticket for `fallback_value`
