### ISSUE TITLE
Wierd interaction between Lazy's and Dataloader.

### ISSUE THREAD

**Issue by palasha** [rmosolgo/graphql-ruby#4021]
Scenario: We have an app that currently makes extensive use of lazy loading with graphql-batch, RecordLoader, etc. I'm attempting to migrate to the Dataloader+Fibers model. That means both are currently enabled together in the schema, and I'm trying to move the first fields over to dataloader.

Symptom: In some cases, when Dataloader sources and RecordLoader are invoked in the same query, even in different objects and fields, a `SystemStackError` occurs when rendering the result to JSON. I am still working constructing a minimal repro case for this.

Investigation:
1. I added a byebug into the GraphQLController before `render json: result`
2. Inspecting the result object.
3. Seeing that a `GraphQL::Execution::Lazy` was being returned as the result for the field that was using Dataloader (teacherNote). The fields that were using RecordLoader and graphql-batch had no issues.
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/1360979/162531679-397f84d2-9687-4060-b0bb-34184b015435.png">
4. The lazy object is marked as `@resolved=false`, however, calling `.value` on that lazy object returns the unwrapped value immediately, without any db queries.

Theory:

The symptom is almost definitely caused by trying to `.to_json` a Lazy object.

But as to the root case, I'm at a bit of a loss on how to investigate beyond this point. My plan is to start reading the interpreter code (which I'm somewhat familiar with having read a lot of it over the past 2 years) and understanding how this could happen. Figured I would post here first in case there's something obvious I'm missing.

**Versions**

`graphql` version: 2.0.5. It was happening on 1.18.x as well, and I upgraded to see if it went away.
`rails` (or other framework): 6.1.4
other applicable versions (`graphql-batch`, etc)
`graphql-batch`: 0.5.1

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok). Any custom extensions, etc?

```ruby
class ApplicationSchema < GraphQL::Schema
  query(Types::QueryType)
  use GraphQL::Batch
  use GraphQL::Dataloader

  ...
end
```

**GraphQL query**

Still working on a minimized / reliable repro query.

**Comment by rmosolgo** [comment]
Yowza...I can't say I'm _surprised_ that there are some buggy interactions between the two systems -- it was very hard to keep them all straight and cover all the cases I could think of. Evidently, I missed a spot :S 

From my standpoint, it'd be helpful for debugging if you could share: 

- The minimal query in your application that shows this bug (does `teacherNote` by itself have this problem, or only with those other fields?)
- The resolution code for `teacherNote` (eg method, resolver, batch loader, and/or dataloader source, etc...)

I'm not _sure_ it'll be enough to get to the bottom of it, but it's certainly a start!

**Comment by palasha** [comment]
> Evidently, I missed a spot :S

You might not have!

I narrowed it down to a field extension I wrote that attempts to automatically preload associations on ActiveRecord objects. 

I wrote this 2 years ago when I first started working on our graphql-ruby implementation and probably didnt understand things properly.

Even so, it's worked perfectly until dataloader came along. However, when i go back and re-read the documentation and runtime/interpreter code around field extensions, it does look like this might cause problems because it isn't the intended use of this extension point in the api?

```
    class FieldExtension < GraphQL::Schema::FieldExtension
      def resolve(object:, arguments:, **_rest, &_block)
        graphql_schema_object = object
        active_record_object = object.object
        if !active_record_object.is_a?(ApplicationRecord)
          return yield(graphql_schema_object, arguments)
        end

        delegated_method_name = field.method_sym
        delegated_method_is_association = AssociationLoader.valid?(
          active_record_object.class,
          delegated_method_name,
        )
        if !delegated_method_is_association
          return yield(graphql_schema_object, arguments)
        end

        AssociationLoader.for(
          active_record_object.class,
          delegated_method_name,
        ).preload(active_record_object).then do
          yield graphql_schema_object, arguments
        end
      end
    end
```

The intention of this was to automate N+1 removal in situations like the following:

```
class Teacher < ApplicationRecord
  has_many :students
end

class TeacherType < BaseObject
  field :students, [StudentType]
end
```

without having to override the resolver method and put in a boilerplate association loader call.

**Comment by rmosolgo** [comment]
Hmmm... I'm really not exactly sure, but I have doubts about `then { yield(...) }`. 

how about trying this instead: 

```ruby
        # returns a graphql-batch Promise/graphql Lazy object.
        loader_promise = AssociationLoader.for(
          active_record_object.class,
          delegated_method_name,
        ).preload(active_record_object)
        
        object_promise = loader_promise.then { graphql_schema_object }
        yield(object_promise, arguments)
```

I _think_ that graphql-ruby will wait for the lazy object (`object_promise`) and use the value it resolves to (`graphql_schema_object`), calling the association preloader in the meantime. 

Let me know how it goes for you!

**Comment by palasha** [comment]
Ah, thats subtle. Unfortunately, it doesn't seem to be working. I'll continue to investigate a bit though.

I will also probably try working around this by wrapping the `object` in a SimpleDelegator to intercept the resolver method call and inject the preloading logic that way instead. Unless there's a better extension point for that I didnt see.

**Comment by palasha** [comment]
OK! I think I narrowed this down much further, and I have a direct reproduction now. I feel more certain that this is a bug internal to graphql-ruby, and not something wrong code that I wrote.

```
require "graphql"
require "graphql/batch"

class Source < ::GraphQL::Dataloader::Source
  def fetch(ids)
    return ids.map {|i| i * 2}
  end
end

class Loader < GraphQL::Batch::Loader
  def initialize(_)
  end

  def perform(ids)
    ids.each { |i| fulfill(i, i * 2) }
  end
end

module Types
  class BaseArgument < GraphQL::Schema::Argument
  end

  class BaseField < GraphQL::Schema::Field
    argument_class BaseArgument
  end

  class BaseObject < GraphQL::Schema::Object
    field_class BaseField
  end

  class BarType < BaseObject
    field :id, Integer

    def id
      object
    end

    def self.authorized?(object, context)
      # Uncomment either line to "fix" the problem
      # return true
      # return context.dataloader.with(Source).load(1)
      Loader.for(Integer).load(1).then do |i|
        true
      end
    end
  end

  class FooType < BaseObject
    field :static_value, BarType
    field :dataloader_value, BarType
    field :loader_value, BarType

    def self.authorized?(object, context)
      # Uncomment either line to "fix" the problem
      # return true
      # return context.dataloader.with(Source).load(1)
      Loader.for(Integer).load(1).then do |i|
        true
      end
    end

    def dataloader_value
      dataloader.with(Source).load(1)
    end

    def loader_value
      Loader.for(Integer).load(1).then {|i| i}
    end

    def static_value
      2
    end
  end

  class QueryType < GraphQL::Schema::Object
    field :foo, FooType

    def foo
      {}
    end
  end
end

class TestSchema < GraphQL::Schema
  use GraphQL::Batch
  use GraphQL::Dataloader
  query Types::QueryType
end

static_query = """
  query {
    foo {
      staticValue {
        id
      }
    }
  }
"""
static_result = TestSchema.execute(static_query)
puts "static result:"
puts static_result.to_h



loader_query = """
  query {
    foo {
      loaderValue {
        id
      }
    }
  }
"""
loader_result = TestSchema.execute(loader_query)
puts "loader result:"
pp loader_result.to_h



dataloader_query = """
  query {
    foo {
      dataloaderValue {
        id
      }
    }
  }
"""
dataloader_result = TestSchema.execute(dataloader_query)
puts "dataloader result:"
pp dataloader_result.to_h

# binding.pry

puts "DONE"
```

If you save this to a ruby file and run with the graphql and graphql-batch gems available: eg `bundle exec testfile.rb`, you will see the query result include an un-synced Lazy value.

```
static result:
{"data"=>{"foo"=>{"staticValue"=>{"id"=>2}}}}
loader result:
{"data"=>{"foo"=>{"loaderValue"=>{"id"=>2}}}}
dataloader result:
{"data"=>
  {"foo"=>
    {"dataloaderValue"=>
      #<GraphQL::Execution::Lazy:0x00007fa3960c9b30
       @field=#<Types::BaseField Foo.dataloaderValue: Bar>,
       @get_value_func=
        #<Proc:0x00007fa3960c98b0 /Users/pagarwal/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:882>,
       @path=["foo", "dataloaderValue"],
       @resolved=false>}}}
DONE
```

As commented inline, if you change the implementation of either authorized? method to not use graphql-batch, then things work fine as well.

I can reproduce this problem with the latest graphql 2.0.6 and graphql-batch 0.5.1 installed as well.

**Comment by rmosolgo** [comment]
Awesome, thanks for your work isolating it! I think I've got a fix ready in in #4036, could you give it a try in your tests to confirm? 

```ruby
gem "graphql", github: "rmosolgo/graphql-ruby", ref: "8c30306e1"
```

**Comment by palasha** [comment]
It does appear to be fixed! With the patch, I cant reproduce this anymore for array fields or single objects, nor for cases where scope_items returns a lazy either, which was previously also causing the same problems.

Thanks so much!

Any recommendations for the best way to include this patch locally while we're waiting for the next release?

**Comment by rmosolgo** [comment]
Sorry for the delayed response -- this is now released to rubygems!
