### ISSUE TITLE
Document is not spec compliant

### ISSUE THREAD

**Issue by rebeccajfriedman** [rmosolgo/graphql-ruby#4027]
**Is your feature request related to a problem? Please describe.**

The generated GraphQL document is not spec compliant, as it allows for unescaped `\n` and `"` characters in [String Value](https://spec.graphql.org/June2018/#StringValue) comments and directive arguments. This means that it is not compatible with the official `graphql-js` parser implementation.

**Describe the solution you'd like**

This should not be supported: https://github.com/rmosolgo/graphql-ruby/blob/master/spec/graphql/language/document_from_schema_definition_spec.rb#L502
Directive arguments (such as the deprecated reason) should strip out trailing newline characters or escape them.

**Comment by rmosolgo** [comment]
Hi! Thanks for reporting this -- I definitely want to stay compatible with GraphQL-JS. I'm not _quite_ sure what's wrong with the spec that you linked... IIUC, that part of the document is a `Comment` ([doc](https://spec.graphql.org/June2018/#sec-Comments)), not a `StringValue`. 

Could you share an example string (even just part of a GraphQL document) that contains invalid characters? Or, help me understand why that spec is invalid?

**Comment by rmosolgo** [comment]
> a comment if it starts with a `#` 

Derp, you're right about that. I'm getting my wires crossed. 

When a string begins and ends with triple-quotes, it's a block string: https://spec.graphql.org/draft/#sec-String-Value.Block-Strings

> White space, line terminators, quote, and backslash characters may all be used unescaped to enable verbatim text. Characters must all be valid _[SourceCharacter](https://spec.graphql.org/draft/#SourceCharacter)_.

Based on that, my understanding is: 

- When strings are written with _single_ quotes, then newlines and quotes must be escaped inside the string 
- But, when strings are written with _triple_ quotes, newlines and quotes can be used unescaped inside the string

What do you think, does this bit about "block strings" clarify it, or is there something else to consider here?

**Comment by rebeccajfriedman** [comment]
That makes a lot of sense. So then the second example I shared (the unescaped newline in the deprecation reason) is still a valid concern. But the first example with the block comment is totally compliant.

**Comment by rmosolgo** [comment]
When you say "unescaped newline", do you mean the `\n` at the end of the string? If I'm reading that right, I think that it's an _escaped_ newline (an unescaped newline would appear as a line break). 

That deprecation reason looks similar to the example here: https://spec.graphql.org/draft/#example-c6521

> ```graphql
> mutation {
>   sendEmail(message: "Hello,\n  World!\n\nYours,\n  GraphQL.")
> }
> ```

In that string, `\n` is used instead of a line break (the preceding example showed the same string, but with a line break). 

Does that address the issue with the deprecation reason? Or was there a different part of the string you had in mind?

**Comment by rebeccajfriedman** [comment]
I'm derping too. Let's close this out 😅
