### ISSUE TITLE
API documentation is not available for version 2.0.6

### ISSUE THREAD

**Issue by joelzwarrington** [rmosolgo/graphql-ruby#4034]
**Describe the bug**

Go to https://graphql-ruby.org/api-doc/2.0.6

Documentation is not available

![image](https://user-images.githubusercontent.com/80279872/163650345-233129a6-13cc-4db5-8824-b879d33b2354.png)

**Comment by rmosolgo** [comment]
Derp, thanks for linking that. It happens sometimes when I release a version where the "publish API docs" and "publish website" jobs conflict and one fails (https://github.com/rmosolgo/graphql-ruby/actions/runs/2167893883). I just have to re-run it. Sorry about that!
