### ISSUE TITLE
Returning GraphQL::ExecutionError in a Mutation using return_fields is unsupported

### ISSUE THREAD

**Issue by aldrinmartoq** [rmosolgo/graphql-ruby#404]
First, thank you for your awesome job in this gem.

I'm trying to implement Mutations and following the [Error Page handling](https://rmosolgo.github.io/graphql-ruby/queries/error_handling), I'm trying to return an GraphQL::ExecutionError but it doesn't work, something like:

```ruby
CreateUserMutation = GraphQL::Relay::Mutation.define do
  name 'CreateUser'

  input_field :name, !types.String

  return_field :id, !types.Int
  return_field :user, UserType

  resolve -> (obj, input, ctx) {
    if input[:name] == 'admin'
      GraphQL::ExecutionError.new("Invalid Admin")
      # NoMethodError (undefined method `each' for #<GraphQL::ExecutionError: Invalid Admin>):
    else
      { id: 1, user: User.last }
    end
  }
end
```

If I change return_field to return_type it works as expected:

```ruby
CreateUserMutation = GraphQL::Relay::Mutation.define do
  name 'CreateUser'

  input_field :name, !types.String

  return_type UserType

  resolve -> (obj, input, ctx) {
    if input[:name] == 'admin'
      GraphQL::ExecutionError.new("Invalid Admin")
    else
      User.last
    end
  }
end
```

Would you accept a patch that implements the first case?

Tell me to implement it or what do you think should be the correct way. Thanks,

**Comment by rmosolgo** [comment]
Yes, it would be great to support this! 

You can see here where it starts iterating over `result`, which it _expects_ to be a hash: 

https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/relay/mutation.rb#L151-L153

But, we should accept an error there too!

**Comment by aldrinmartoq** [comment]
Ok, I have an initial [implementation](https://github.com/rmosolgo/graphql-ruby/pull/405) but I think we should change the docs to raise GraphQL::ExecutionError instead of returning. For example:

```ruby
  resolve ->(root_obj, inputs, ctx) {
    faction_id = inputs["factionId"]
    raise GraphQL::ExecutionError.new("Sorry, Millennium Falcon ship is reserved") if inputs["shipName"] == 'Millennium Falcon'
    ship = STAR_WARS_DATA.create_ship(inputs["shipName"], faction_id)
    faction = STAR_WARS_DATA["Faction"][faction_id]
    connection_class = GraphQL::Relay::BaseConnection.connection_for_nodes(faction.ships)
    ships_connection = connection_class.new(faction.ships, inputs)
    ship_edge = GraphQL::Relay::Edge.new(ship, ships_connection)
    { shipEdge: ship_edge, faction: faction }
  }
```

**Comment by rmosolgo** [comment]
Thanks for fixing this! 

I don't want to recommend `raise` in the documentation because I don't think it's a good way of expressing control flow in a program. It's hard to tell where `raise` _goes_! 

But, I support it in this gem because I know many people have a different opinion :) 

Thanks again for the fix!
