### ISSUE TITLE
Rendered document not compliant

### ISSUE THREAD

**Issue by col** [rmosolgo/graphql-ruby#4041]
According to [the GraphQL object spec](https://spec.graphql.org/June2018/#sec-Objects), for a given type Foo the fields definition for that type is optional. As far as I can tell, if you want to not specify a fields list, you need to also omit the wrapping {...}. i.e:

```
// This is invalid
type Foo {
}

// This is valid
type Foo
```

Currently, `GraphQL::Language::Printer` always prints schema with the wrapping {...}, even if there are no fields for the type, which I believe is invalid. I tested this against our schema in Apollo and saw the below. Sensitive parts are omitted, but the important part is the AST parse failure.

```
$ echo 'schema {query: Q} type Q {}' | rover subgraph check [...]
Checking the proposed schema for subgraph [...]
error: Could not parse partial schema as AST.

$ echo 'schema {query: Q} type Q' | rover subgraph check [...]
Checking the proposed schema for [...]
Compared 108 schema changes against 25 operations
```

**Versions**

`graphql` version: 1.13.12
`rails` (or other framework): 6.1.4

**GraphQL schema**

```ruby
module Types
  class MutationType < Types::Base::BaseObject
  end
end

class ApplicationSchema < GraphQL::Schema
  mutation(Types::MutationType)
  # …
end
```

**Output GraphQL schema**

```ruby
  document_from_schema = GraphQL::Language::DocumentFromSchemaDefinition.new(self, context: nil)
  GraphQL::Language::Printer.new.print(document_from_schema.document)
```

**Expected behavior**

The output should not include brackets { ... } when the type has no fields

**Actual behavior**

The output includes brackets { ... } even when the type has no fields

**Additional context**

Found a very similar bug (and stole the description from) here: https://github.com/ghostdogpr/caliban/pull/1220
Thanks @Fluxx

**Comment by rmosolgo** [comment]
Thanks for the detailed report! Sorry for the trouble. I'll release 2.0.7 soon with a fix.
