### ISSUE TITLE
GraphQL::ParseError: Parse error on "type" (TYPE) when updating from graphql 2.0.6 to 2.0.7

### ISSUE THREAD

**Issue by eddiecheung-shopify** [rmosolgo/graphql-ruby#4045]
**Describe the bug**

When I updating the `graphql` gem from `2.0.6` to `2.0.7`, I got the exception when running graphql schema comparison unit test.

*Unit test sample code:*
```ruby
test "schema should not have changed" do
    schema = GraphQL::Schema::Printer.print_schema(IdentityGraphSchema)
    current_schema_path = Rails.root.join("tmp", "schema.graphql")
    File.write(current_schema_path, schema)

    snapshot_schema_path = file_fixture("../../../db/graphql/schema.graphql")
    snapshot = snapshot_schema_path.read

    result = GraphQL::SchemaComparator.compare(snapshot, schema)

    assert_not result.breaking?, "Graphql schema has breaking changes:\n" \
      "please run `bin/schema_comparator compare #{snapshot_schema_path} #{current_schema_path}` to see the changes"
    assert result.identical?, "Graphql schema has changed:\n" \
      "please run `bin/rake graphql:schema:dump` to update the snapshot"
  end
```

*Exception:* (Error triggered by `result = GraphQL::SchemaComparator.compare(snapshot, schema)`)

```
Error:                                                                                                                                                                          
GraphQL::ParseError: Parse error on "type" (TYPE) at [54, 1]
    (eval):3:in `_racc_do_parse_c'
    (eval):3:in `do_parse'
```

**Versions**

`graphql` version: 2.0.7
`graphql-schema_comparator` version: 1.1.1
`rails` (or other framework) version: 3.1.1
other applicable versions (`graphql-batch`, etc)

**GraphQL schema**

```graphql
type ClickId {
  date: String!
  type: String!
  value: String!
}

type ClientId {
  date: String!
  value: String!
}

type CustomerId {
  date: String!
  value: ID!
}

enum DatastoreName {
  BIG_TABLE_INVERTED_INDEX
  BIG_TABLE_MATRIX
}

type Email {
  date: String!
  value: String!
}

type Fingerprint {
  identifier: String!
  identifierType: IdentifierType!
  shopId: ID!
}

input FingerprintInput {
  identifier: String!
  identifierType: IdentifierType!
  shopId: ID!
}

enum IdentifierType {
  CLIENT_ID
  EMAIL
}

type Identity {
  clickIds: [ClickId!]
  clientIds: [ClientId!]
  customerIds: [CustomerId!]
  emails: [Email!]
  fingerprint: Fingerprint!
}

type Mutation

type Query {
  """
  Find an identity by fingerprints
  """
  identity(datastoreName: DatastoreName!, fingerprints: [FingerprintInput!]!): [Identity!]
}
```

**Steps to reproduce**

Run unit test.

**Expected behavior**

The unit test should either pass or failure with reasoning. No exception should be raised.

**Actual behavior**

`GraphQL::ParseError` exception being raised.

**Additional context**

I don't have issue with `graphql 2.0.6` gem. And the issue seems like is related `type Mutation` from the `schema.graphql`. I have used `bin/rake graphql:schema:dump` to generate this schema based on version 2.0.7.

My graphql API does not have mutation.

**Comment by eddiecheung-shopify** [comment]
I found a solution. What I need to do is removing `mutation(Types::MutationType)` from class my graphql schema class since this graphql API does not have mutation (only query). After removing it and update schema by `bin/rake graphql:schema:dump`, the schema comparison unit test works.

**Comment by rmosolgo** [comment]
Thanks for mentioning this -- I think there _is_ actually a bug here. In #4042 I updated the printer to print empty types (like `type Mutation` above) without any curly braces. But the parser needs an update, too -- it's still looking for curly braces!
