### ISSUE TITLE
mutation classes of different modules name collision 

### ISSUE THREAD

**Issue by dimerman** [rmosolgo/graphql-ruby#4048]
**Describe the bug**

There are two mutations:
```graphql
...
field :discard_a, mutation: Mutations::NameSpaceA::Discard
field :discard_b, mutation: Mutations::NameSpaceB::Discard
...
```

When querying the schema from graphiql I get the error:
```
Found two visible type definitions for `DiscardInput`
```

**Versions**

`graphql` version:
`graphql-pro` version: 1.21.6
`rails` (or other framework): 6.1.5
other applicable versions (`graphql-batch`, etc)

**GraphQL schema**

**GraphQL query**

**Steps to reproduce**

1. two mutations that resolve to different classes in separate namespaces but with the same class name
2. try to use graphiql

**Expected behavior**
since these are separate classes, there should be no conflict/collision

**Actual behavior**

see error above

**Additional context**

**Comment by rmosolgo** [comment]
Hi! That's right, mutations derive their name from their _class name_ (without module namespaces) by default:

https://github.com/rmosolgo/graphql-ruby/blob/1f8b198e00f69b08b9cd7eee00a799c4a304033b/lib/graphql/schema/member/base_dsl_methods.rb#L99-L108

To give each of those mutation different names, you could use one of two approaches: 


1. Call `graphql_name` in each mutation to provide a custom name: 

   ```ruby
    class Mutations::NameSpaceA::Discard < Mutations::Base 
      graphql_name "NameSpaceADiscard"
    end 
    # ... 
    class Mutations::NameSpaceB::Discard < Mutations::Base
      graphql_name "NameSpaceBDiscard"
    end 
    ```
    
2. In your base mutation class, redefine `def self.default_graphql_name` to generate a name based on your namespacing: 

   ```ruby 
   class Mutations::Base < GraphQL::Schema::Mutation 
     def self.default_graphql_name 
      self.name
        .sub("Mutation::", "") # remove the `Mutation::` prefix
        .gsub("::", "") # remove the other module delimiters (`:` isn't allowed in GraphQL names)
      end 
    end 
    ```
    
Want to give one of those a try? Let me know what you find.

**Comment by dimerman** [comment]
went with option 2
thanks!
