### ISSUE TITLE
Mutation within field object doesn't work

### ISSUE THREAD

**Issue by fameoflight** [rmosolgo/graphql-ruby#4051]
My mutation_type 
```ruby

module Types
  class MutationType < Types::Base::BaseObject
    field :spoke, Types::Model::Spoke::MutationType
  end
end
```

And mutation SpokeMutationType 
```ruby
module Types
  module Model
    module Spoke
      class MutationType < Types::Base::BaseObject
        graphql_name 'SpokeMutation'

        field :spoke_update, mutation: Mutations::Model::SpokeUpdate
      end
    end
  end
end
```

I am able send the mutation from frontend, but on backend it throws this error 
```
              Failed to implement Mutation.spoke, tried:

              - `Types::MutationType#spoke`, which did not exist
              - `NilClass#spoke`, which did not exist
              - Looking up hash key `:spoke` or `"spoke"` on ``, but it wasn't a Hash

              To implement this field, define one of the methods above (and check for typos)
```
I am using the latest version of graphql if that's helpful

This can be superhelpful in namespacing mutations, otherwise it become one giant file.

**Comment by rmosolgo** [comment]
This field: 


```ruby
field :spoke, Types::Model::Spoke::MutationType
```

has no implementation. How should GraphQL-Ruby resolve that field? You can see in the error message all the things it tried. 

If you don't care about the value of `spoke`, then you can implement a dummy resolution behavior like this: 

```ruby
field :spoke, Types::Model::Spoke::MutationType

def spoke 
  :spoke # just some truthy object so GraphQL-Ruby will continue resolving 
end
```

Does that work for you?

**Comment by fameoflight** [comment]
It feels hack. But it does work for me,  I can wrap this field with resolve proc.  Thanks for taking a look. 

Is there default resolution can define in mutationtype that eliminate the needs to write this again and again?
