### ISSUE TITLE
Control schema introspection with context awareness

### ISSUE THREAD

**Issue by mroach** [rmosolgo/graphql-ruby#4058]
**Describe the solution you'd like**

Currently schema introspection can be disabled using the `disable_introspection_entry_points` macro in your schema.
This could be wrapped in an environment variable check to say, permit this in development and disable it in production.

This makes it an all-or-nothing switch in release environments. If schema introspection should be available to some users, say in a trusted developer programme, this does not appear to be possible. If controlling schema introspection had context awareness, this would be achievable. e.g.

```ruby
class MySchema < GraphQL::Schema
  def self.allow_introspection?(context)
    return true if ENV.fetch("GRAPHQL_ALLOW_INTROSPECTION", "off") == "on"

    context.fetch(:viewer).has_role?(:graphql_developer)
  end
end
```

**Describe alternatives you've considered**

Making our current schema the "base" schema and then having two children that inherit from it. One, call it `DeveloperSchema`, would allow introspection but its controller would check the user's roles before allowing it to be used. The other schema would have introspection disabled and this would be the normal schema for our private first-party apps.

Perhaps the generated schema for introspection could allow a custom `visible?(context)` method somehow?

**Comment by rmosolgo** [comment]
Hey, great question. This is currently possible by customizing the introspection, described here: https://graphql-ruby.org/schema/introspection.html#customizing-introspection

Just like with your own types and fields, you can implement `def visible?(ctx)` for custom introspection types and fields to return false, in which case they'll be hidden. I just pushed a commit with some examples of that: 6d544ef73

What do you think of that approach?

**Comment by mroach** [comment]
@rmosolgo Sorry I lost track of this during house-moving week. Thank you for the example of how to do this. This makes perfect sense to me and should solve my problem. Thanks for taking the time :)
