### ISSUE TITLE
[PRO] using loads: on an argument ignores the specified pundit role

### ISSUE THREAD

**Issue by xxx** [rmosolgo/graphql-ruby#4063]
Hello!

When using `loads` with an `argument`, the `pundit_role` set on the field is ignored entirely. Without `loads`, it uses the specified `pundit_role` as expected.

Maybe this is intended behavior (it would not be too hard to convince me), but I couldn't find it documented. It did surprise me when I discovered it.

edit: I did find it sort-of referenced [here](https://graphql-ruby.org/mutations/mutation_authorization.html#loading-and-authorizing-objects), but still not sure if the specific interaction happening here is intended behavior or not

edit 2: This is an argument for a mutation, if that ends up mattering.

```ruby
    argument :workstream_id, ID,
             required: true,
             description: 'ID of the Workstream',
             loads: Types::WorkstreamType,
             pundit_role: :public_or_member # this is ignored in favor of the `pundit_role` on Types::WorkstreamType
```

**Versions**

`graphql` version: 1.13.10
`rails` (or other framework): Rails 7.0.2.3
other applicable versions (`graphql-batch`, etc) `graphql-pro` 1.21.4

**Comment by rmosolgo** [comment]
Thanks for the detailed report! I Think it _should_ work the way you expect, I'll take a look soon and follow up here.

**Comment by juliantrueflynn** [comment]
If any reassurance was needed that this is a regression: I bumped graphql-pro gem from 1.18.3 to 1.22.2, and graphql gem from 1.11.6 to 1.13.12 and started experiencing this same issue.

**Comment by rmosolgo** [comment]
Hey, I'd love to track this down, but I'm not sure where to look next. Can either of you share any more details about what's misbehaving here?

**Comment by xxx** [comment]
I'll try to dig back into this sometime today. it's been a minute :grimacing:
