### ISSUE TITLE
Support for OneOf Input Objects

### ISSUE THREAD

**Issue by erikkessler1** [rmosolgo/graphql-ruby#4064]
**Is your feature request related to a problem? Please describe.**

The OneOf Input Objects RFC, graphql/graphql-spec#825, which introduces a form of input polymorphism to GraphQL, has entered stage 2. Given that the proposal is moving along, we should think about how we could implement the feature in this library.

**Describe the solution you'd like**

This issue is intended to foster a discussion of options, so to start the discussion, one approach would be to add a new `GraphQL::Schema::OneOfInputObject` type. For example:

```ruby
class PetInput < GraphQL::Schema::OneOfInputObject
  member :cat, CatInput
  member :dog, DogInput
end
```
_Ruby DSL_

```graphql
input PetInput @oneOf {
  cat: CatInput
  dog: DogInput
}
```
_Generated GraphQL SDL_

With this approach, we'd be able to ensure arguments are nullable and don't have defaults. However, a downside to this approach is sharing code with an application's `BaseInputObject` becomes harder unless the logic is already factored into composeable modules.

**Describe alternatives you've considered**

Another option would be to add a new DSL method to `GraphQL::Schema::InputObject` that turns it into a OneOf Input Object. For example,

```ruby
class PetInput < GraphQL::Schema::InputObject
  one_of

  argument :cat, CatInput
  argument :dog, DogInput
end
```

This approach makes it easier to share logic with a `BaseInputObject`, but makes it less clear to developers that not all the argument configuration options are available (e.g., a default can't be provided). Furthermore, it glosses over that fact that Input Objects and OneOf Input Objects are truly different concepts in the type system and serve different purposes.

**Comment by rmosolgo** [comment]
:+1: I'm definitely game to start supporting this feature. 

Here's another implementation suggestion: what if the existing `required: { one_of: [...] }` validation added the `@oneOf` directive to the SDL for input objects when all their arguments are named by `one_of: [...]`? ([guide](https://graphql-ruby.org/fields/validation.html#built-in-validations), [API doc](https://graphql-ruby.org/api-doc/2.0.7/GraphQL/Schema/Validator/RequiredValidator)).


My second choice would have been the `one_of` configuration method as described above. The issue about `default_value` can be solved by checking for invalid configuration while the input object is being defined. But about this part: 

>  truly different concepts in the type system and serve different purposes

could you help me understand that better? (It seems to me like `@oneOf` is basically a _special kind_ of Input Object, but maybe I'm missing a perspective on it.)

**Comment by erikkessler1** [comment]
> Here's another implementation suggestion: what if the existing `required: { one_of: [...] }` validation added the `@oneOf` directive to the SDL for input objects when all their arguments are named by `one_of: [...]`?

My understanding of the `RequiredValidator` is that it applies to field arguments, not input objects. The `@oneOf` directive would currently only apply to input objects. Furthermore, although not part of the RFC, there could be OneOf Objects for output as well, so I think we'd want something that allows for that future as well. In that case, we could add a `GraphQL::Schema::OneOfObject`, but I'm not sure how we'd represent that though the `required` validator. Additionally, I think requiring the schema author to list _every_ field in the `required: { one_of: [...] }` list would be burdensome and error prone (e.g., it would be easy to add a new field to an input object and forget to add it to the validation which would cause the `@oneOf` directive to drop).

> The issue about default_value can be solved by checking for invalid configuration while the input object is being defined.

That's true, but it does add what might feel like confusing / surprising behavior to the schema author as they see other Input Objects can take a default value but now adding a `one_of` call changes that behavior.

> could you help me understand that better? (It seems to me like `@oneOf` is basically a special kind of Input Object, but maybe I'm missing a perspective on it.)

OneOf Input objects are designed to be a solution for "input unions", so while, yes, they are special kind of Input Object, they really serve a different purpose. Regular Input Objects allow us to pass a complex object as an argument to a field while OneOf Input objects allow us to pass a union of different types as an argument to a field. For example, `PetInputUnion` and `PetInput` below _look_ similar but are solving different problems, so I do not imagine there would be a world where schema authors would be changing regular Input Object into OneOf Input Objects or vice versa (unless they had proactively intended their regular Input Object serve the purpose of an input union before `@oneOf` existed).

```graphql
input PetInputUnion @oneOf {
  cat: CatInput
  dog: DogInput
}

input PetInput {
  cat: CatInput
  dog: DogInput
}
```

**Comment by rmosolgo** [comment]
I just sketched out an implementation here: https://github.com/rmosolgo/graphql-ruby/pull/4184

**Comment by erikkessler1** [comment]
Awesome! I just opened https://github.com/rmosolgo/graphql-ruby/pull/4185 so we can compare it against the `GraphQL::Schema::OneOfInputObject` approach.
