### ISSUE TITLE
Enable a callback to send custom tags to datadog tracing

### ISSUE THREAD

**Issue by nithinpb** [rmosolgo/graphql-ruby#4066]
**Is your feature request related to a problem? Please describe.**

We'd like to be able send custom tags along with the logs for datadog traces. We need this to classify some of our logs based on custom business logic. This can be done via setting the tag on DataDog::Span object.

**Describe the solution you'd like**

We'd like to set a callback method from our code while initializing datadog tracing class. Before yielding the control back to the graphql resolution method, we'd like to invoke the callback method with span argument. Doing so, we can set the tag on the span as per our business requirement. 

```ruby
module GraphQL
  module Tracing
    class DataDogTracing < PlatformTracing
      def initialize(options = nil)
        @callback = options[:callback] unless options.nil?
        super options
      end
```

```ruby
...
          @callback.call(span)
          yield
...
```

**Describe alternatives you've considered**

There does not seem to be any other alternative to this solution as we need access to the DataDog::Span object while tracer.trace is invoked. 

**Additional context**

No

**Comment by rmosolgo** [comment]
What do you think of the approach described in https://github.com/rmosolgo/graphql-ruby/pull/4067?

In that approach, you can make a subclass and implement `def prepare_span(...)` to apply tags. (Method calls are faster than proc calls, and IMO, a more Ruby-ish style!)

**Comment by nithinpb** [comment]
@rmosolgo : This works as well. Thanks!
