### ISSUE TITLE
URQL Subscriptions

### ISSUE THREAD

**Issue by mikecx** [rmosolgo/graphql-ruby#4070]
**Is your feature request related to a problem? Please describe.**

Apollo GraphQL doesn't seem to be moving forward and [doesn't support suspense](https://github.com/apollographql/apollo-client/issues/8245). We use [urql](https://formidable.com/open-source/urql/) which has great support for just about everything. Unfortunately, it doesn't work with the graphql-ruby subscriptions.

**Describe the solution you'd like**

A [Subscription Exchange client](https://formidable.com/open-source/urql/docs/advanced/subscriptions/) for urql that supports graphql-ruby

**Describe alternatives you've considered**

Switching to Apollo, but we lose suspense and that's a ton of work to replace it, and again, we lose suspense.

**Additional context**

I've tried writing it myself but I just don't seem to understand all the pieces well enough to write something that works. It seems like either [graphql-ws](https://github.com/enisdenjo/graphql-ws) or [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws) should be adaptable but I haven't yet figured it out.

**Comment by rmosolgo** [comment]
Hey @mikecx, I'd be happy to investigate `urql` subscriptions support. I bet we could implement an exchange and maintain it in this library similar to the Apollo and Relay subscription adapters. 

Do you have a subscription transport in mind (ActionCable, Pusher, Ably, or something else)? The details of the subscription exchange will depend on which transport you want to use.

**Comment by mikecx** [comment]
We've been looking primarily at Pusher as it allows us to offload any load on the servers in the easiest way and we're also looking at Pusher presence channels for another part of our product (unrelated to graphql-ruby). 

We could also do ActionCable/AnyCable but Pusher would certainly be the easiest for us.

**Comment by sumitngupta** [comment]
+1 on Pusher or Ably.  Not having to manage the infrastructure would be a huge win.

**Comment by rmosolgo** [comment]
Ok, I sketched out a client here: https://gist.github.com/rmosolgo/a4c098de02af63ec1cdd09a3573a216b

As described there, one caveat is that you have to implement the `fetch(...)` call yourself. (For Pusher subscriptions, the initial subscription is sent over HTTP POST, just like a mutation or query. But `urql` doesn't seem to support that, and I couldn't find any way to hook into the existing `fetchExchange`.) 

Other than that, server setup should be the same as described in the docs (https://graphql-ruby.org/subscriptions/pusher_implementation.html). Want to give it a shot?

**Comment by rmosolgo** [comment]
Glad to hear it worked for you, and thanks for sharing your tweaks. I just released this code in `graphql-ruby-client` 1.11.0. If you get a chance to try that version out, please let me know what you think of it!

**Comment by dimitrikochnev** [comment]
@rmosolgo are you going to implement urql for Ably?
