### ISSUE TITLE
Field connections - failed to implement Edge.node

### ISSUE THREAD

**Issue by reneerenyes** [rmosolgo/graphql-ruby#4080]
**Describe the bug**
Hello, I am in the process of upgrading the gem and found that from version 2.0.3 onwards, custom connections for queries with 
`edges{ node { ... } } `are erroring out. 

Error message:

```
Failed to implement xxEdge.node, tried:
        
                      - `#<Class:0x00007...>#node`, which did not exist
                      - `Statement#node`, which did not exist
                      - Looking up hash key `:node` or `"node"` on `#<Statement...>`, but it wasn't a Hash
        
                      To implement this field, define one of the methods above (and check for typos)
```

**Versions**

`graphql` version: 2.0.3 onwards
`rails` (or other framework): 7.0.3
other applicable versions (`graphql-batch`, etc)

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok). Any custom extensions, etc?

```ruby
field :statements_paginated, SomeStatement.connection_type, null: false,
        description: "list of statements" do
        argument :some_date, Types::Date, required: false, description: "some date"
end

def statements_paginated(**arguments)
        GraphQL::Pagination::ArrayConnection.new(
          ...
        )
end
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql

          query {
              statementsPaginated(someDate: "2020-06-01") {
                edges{
                  node {
                    date
                  }
              }
            }
          }

```

**Steps to reproduce**
- create a field thats using custom connections and use the built-in `GraphQL::Pagination::ArrayConnection`.
- query with `edges { node {... }}`

**Expected behavior**
- should return list of nodes 

**Actual behavior**
- error thrown
What specifically went wrong?

Place full backtrace here (if a Ruby exception is involved):

<details>
<summary>Click to view exception backtrace</summary>

```
Something went wrong
2.6.0/gems/graphql-1.9.17/lib/graphql/subscriptions/instrumentation.rb:34:in `after_query'
… don't hesitate to include all the rows here: they will be collapsed
```

</details>

**Additional context**

I think the issue might be introduced [from this PR](https://github.com/rmosolgo/graphql-ruby/pull/3995).

`ArrayConnection` inherits `edges` method from [`Connection` class](https://graphql-ruby.org/api-doc/2.0.8/GraphQL/Pagination/Connection.html), which looks like deprecated `edge_nodes`, but edges -> nodes should still work. 

With these details, we can efficiently hunt down the bug!

**Comment by rmosolgo** [comment]
Hi, sorry for the trouble and thanks for the detailed report! I bet you're right about that PR. Could you try a patch in your application to confirm that it would fix this problem? You could add this to your schema definition file: 

```ruby 
module GraphQL::Types::Relay::ConnectionBehavior 
  # put back this method that was removed from GraphQL-Ruby to see if it fixes pagination 
  def nodes 
    @object.edge_nodes 
  end 
end 

# ... 
```

After that, does your API start working again?

**Comment by reneerenyes** [comment]
Nope, still the same error. It looks like when the test runs, debugger doesn't stop within the nodes method either.

**Comment by reneerenyes** [comment]
🤦‍♀️  it looks like we were using the deprecated edge_nodes in our BaseConnection class. Going to close this ticket! Thanks.
