### ISSUE TITLE
Client support for @defer with urql

### ISSUE THREAD

**Issue by rlisowski** [rmosolgo/graphql-ruby#4082]
Hey,

[urql](https://formidable.com/open-source/urql/) says in [changelog](https://github.com/FormidableLabs/urql/blob/main/packages/core/CHANGELOG.md#230) that they support `@defer` but I cannot find any info on how to setup in with graphq-ruby.

Any help will be highly appreciated.

**Comment by rlisowski** [comment]
nvm

urql do not like the response graphql-pro generates

instead
```
if (deferred = result.context[:defer])
  response.headers['Last-Modified'] = Time.now.httpdate
  deferred.stream_http_multipart(response)
else
  render json: result
end
```

do

```
if (deferred = result.context[:defer])
  response.headers['Last-Modified'] = Time.now.httpdate
  response.headers['Content-Type'] = 'multipart/mixed; boundary="-"'
  response.stream.write('---')
  deferred.deferrals.each do |deferral|
    patch = JSON.generate(deferral.to_h)
    patch_str = "\r\nContent-Type: application/json; charset=utf-8\r\n\r\n#{patch}#{deferral.has_next? ? "\r\n---" : ''}"
    response.stream.write(patch_str)
  end
  response.stream.write("\r\n-----\r\n")
else
  render json: result
end
```

**Comment by rmosolgo** [comment]
Hi! sorry you had trouble with this but glad you found a solution. 

Out of curiousity, what version of `graphql-pro` do you have installed? I ask because I _think_ the latest version will write patches just like the ones described in your code sample, but if the latest version didn't work for you, then maybe I'd better double-check it!

**Comment by rlisowski** [comment]
@rmosolgo I use graphql-pro (1.22.2). The formatting is different.

graphql-ruby:
```

---
Content-Type: application/json
Content-Length: 99

{"hasNext":true,"data":{"serviceGroupMembership":{"id":"1","__typename":"ServiceGroupMembership"}}}
---
Content-Type: application/json
Content-Length: 141

{"path":["serviceGroupMembership"],"hasNext":false,"data":{"usage":{"perMonth":"6","perDay":"0","__typename":"ServiceGroupMembershipUsage"}}}
-----%
```

my code
```
---
Content-Type: application/json; charset=utf-8

{"hasNext":true,"data":{"serviceGroupMembership":{"id":"1","__typename":"ServiceGroupMembership"}}}
---
Content-Type: application/json; charset=utf-8

{"path":["serviceGroupMembership"],"hasNext":false,"data":{"usage":{"perMonth":"6","perDay":"0","__typename":"ServiceGroupMembershipUsage"}}}
-----

```

**Comment by rmosolgo** [comment]
Ahh -- thanks for pointing that out. I see: 

- Added `; charset=utf-8` to the Content-Type header 
- No `Content-Length` header

I guess I was working for this old spec: https://github.com/apollographql/apollo-server/blob/defer-support/docs/source/defer-support.md#response-specification

I'll keep this in mind, and maybe update the default behavior in graphql-pro if anyone else runs into trouble here. Thanks again for sharing what you found!
