### ISSUE TITLE
Mutation type no longer resolved as field after after upgrading from 1.13 to 2.0.8

### ISSUE THREAD

**Issue by aandrieu** [rmosolgo/graphql-ruby#4083]
**Describe the bug**

I have a custom type returned by my mutation using `type` function. This type was correctly resolved as a Field before the migration. After it was no longer the case.

**Versions**

`graphql` version: 2.0.8
`rails` (or other framework): 6.1.6
other applicable versions (`graphql-batch`, etc)

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok). Any custom extensions, etc?

```ruby
module Types
  class BasePage < BaseObject
    field :has_previous_page, Boolean, null: false
    field :has_next_page, Boolean, null: false
    field :total_count, Integer, null: false
  end
end

module Types
  class BaseField < GraphQL::Schema::Field
    argument_class Types::BaseArgument

    def initialize(**kwargs, &block)
      super
      return_type = kwargs[:type]
      if return_type.is_a?(Class) && return_type < BasePage
        puts 'Define page extension'
        # here I extends the field using extension
      end
    end
  end
end

module Types
  module Todos
    class TodoType < Types::BaseObject
      field :id, ID, null: false
    end
  end
end

module Types
  module Todos
    class TodosPageType < Types::BasePage
      field :nodes, [Types::Todos::TodoType], null: false
    end
  end
end

module Queries
  module Todos
    class TodosQuery < BaseQuery
      type Types::Todos::TodosPageType, null: false

      def resolve(*)
        Todo.all
      end
    end
  end
end
```

In 1.13: 'Define page extension' is logged. The extension is correctly loaded and all is working fine!
In 2.0.8: Nothing is logged. The extension is not loaded. 

It works fine if I wrap the returned `type` in another type.

 ```ruby
module Types
  module Todos
    class TodosResultType < Types::BaseObject
      field :result, Types::Todos::TodosPageType, null: false
    end
  end
end

module Queries
  module Todos
    class TodosQuery < BaseQuery
      type Types::Todos::TodosResultType, null: false

      def resolve(*)
        Todo.all
      end
    end
  end
end
```

In this second case `Define page extension` is logged in both case. I think it is a regression where types are no longer resolved as fields. I found nothing in the changelog about that but maybe I missed something.

Is it possible to have help on this please? 😃

**Comment by rmosolgo** [comment]
Hi! sorry for the trouble. I think the issue came from this PR: https://github.com/rmosolgo/graphql-ruby/pull/3916

Previously, Resolver classes were converted to field options (using `.field_options`), then those options were passed to `Field.new(...)`. But this created a problem: if the resolver definition was modified _after_ field initialization, the field definition didn't reflect the changes to the resolver. 

So instead, many methods on the field check `@resolver_class` to see if they received a value from their resolver definition. For example, `def type`: 

https://github.com/rmosolgo/graphql-ruby/blob/973135bfcb7809721e14268134b15538cf94f03d/lib/graphql/schema/field.rb#L564-L571

So, I recommend updating your code to _either_ check for `kwargs[:resolver_class]&.type` or call `self.type` to get the resolved type. For example:

```ruby 
# Either this: 
resolver_class_type = kwargs[:resolver_class]&.type
if resolver_class_type.is_a?(Class) && resolver_class_type < BasePage
  puts 'Define page extension'

# or this 
if self.type.is_a?(Class) && self.type < BasePage 
  puts "Define page extension"
 ```
 
 How about giving one of those a try?

**Comment by aandrieu** [comment]
Tried, and it is not working. It is because the `initialize` method from BaseField is not even call for type only declared as `type` in Query :/

**Comment by rmosolgo** [comment]
How is `TodosQuery` attached to the schema? I'd expect something like `field :todos, resolver: TodosQuery`. That's where `initialize` would be called, and during that call, I'd expect `type` to be the same `type` defined in `TodosQuery`.

**Comment by aandrieu** [comment]
Hello again @rmosolgo.
 
I finally find some time to make some investigations. It seems that we have a conflict with our code base and the v2.

In the v2 non-null fields are wrapped into `GraphQL::Schema::NonNull`. This wrapper makes the sub type checking unusable.

Based on our example above we have some stuff like that
```
<GraphQL::Schema::NonNull @of_type=Types::Todos::TodosPageType>
```

I tried to solved that by this new code and seems to work but don't know if it is expected or even correct
```ruby
module Types
  class BaseField < GraphQL::Schema::Field
    argument_class Types::BaseArgument

    def initialize(**kwargs, &block)
      super
      
      # ... other stuff
      
      # Check wrapped types
      resolver_class_type = kwargs[:resolver_class]&.type
      if resolver_class_type.is_a?(GraphQL::Schema::NonNull)
        unwrapped = resolver_class_type.unwrap
        if unwrapped.is_a?(Class) && unwrapped < BasePage
          extension(Extensions::PageWrapperExtension)
        end
      end
    end
  end
end
```

In order to cover all cases that we have in our code base, our BaseField looks like this:

```
module Types
  class BaseField < GraphQL::Schema::Field
    argument_class Types::BaseArgument

    def initialize(**kwargs, &block)
      super
      
      return_type = kwargs[:type]
      if return_type.is_a?(Class) && return_type < BasePage
        extension(Extensions::PageWrapperExtension)
      end

      resolver_class_type = kwargs[:resolver_class]&.type

      if resolver_class_type.is_a?(Class) && resolver_class_type < BasePage
        extension(Extensions::PageWrapperExtension)
      end

      if resolver_class_type.is_a?(GraphQL::Schema::NonNull)
        unwrapped = resolver_class_type.unwrap
        if unwrapped.is_a?(Class) && unwrapped < BasePage
          extension(Extensions::PageWrapperExtension)
        end
      end
    end
  end
end
```

I find it very unclear, especially if we look like at the old one 😄 
Can we make it better on our side? Or it is something that can be adresses in the lib?

Thank you!

**Comment by rmosolgo** [comment]
Oh, I see -- yes, I think you could simplify the code by always calling `.unwrap` on the type that you get from keyword arguments, for example:


```ruby
      return_type = kwargs[:type]&.unwrap
      resolver_class_type = kwargs[:resolver_class]&.type&.unwrap
      if return_type.is_a?(Class) && return_type < BasePage
        extension(Extensions::PageWrapperExtension)
      elsif resolver_class_type.is_a?(Class) && resolver_class_type < BasePage
        extension(Extensions::PageWrapperExtension)
      end
```

(For non-wrapper types, `.unwrap` returns `.itself`:  https://github.com/rmosolgo/graphql-ruby/blob/6e080068223d2e29f1610d992cb5304a88d813a6/lib/graphql/schema/member/base_dsl_methods.rb#L97.)

How about using that?

**Comment by aandrieu** [comment]
It does not work because kwargs[:type] seems to be a string some time 🤷‍♂️ 

```
def unwrapped_resolved_type
        resolved_type =
          if @resolver_class
            @resolver_class.type
          else
            self.type
          end

        if resolved_type.is_a?(GraphQL::Schema::Wrapper)
          resolved_type.unwrap
        else
          resolved_type
        end
      end
      ```
      
This is the best condensed working version I have. Since the problem seems to be on our side and we solved it I think we can close this issue 😄 
Thank you for your help 👍

**Comment by rmosolgo** [comment]
Ahh, fair enough. It really _seems_ like it should be easier than this! What about checking `self.type` _after_ `super`? 

```ruby 
super 

if self.type.unwrap < BasePage 
  extension(Extensions::PageWrapperExtension)
end 
```

I expect `self.type` to take care of strings:

https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/field.rb#L566-L582

Anyhow, I'm glad you found something that works for you! Sorry for the trouble along the way.
