### ISSUE TITLE
Can't return null values from union resolve_type when using tuples

### ISSUE THREAD

**Issue by alvaromat** [rmosolgo/graphql-ruby#4085]
**Describe the bug**

I'm having an union in which there is a `resolve_type` returning a tuple with an special value that does not map directly to the object given to the union:

```ruby
class NfcTagTaggableType < Types::BaseUnion
        possible_types Types::DynamicChecklists::TaskType

        def self.resolve_type(object, ctx)
          case object
          when ::DynamicChecklists::TaskConfig # Logbooks checklists
            [Types::DynamicChecklists::TaskType, find_appropiate_task(object, ctx)]
          end
        end

        def self.find_appropiate_task(domain_object, ctx)
            # Return nil to exemplificate the edge case
            nil
        end
      end
    end
```

However, when I return nil in the second element of the tuple, which is the value returned by `find_appropiate_task` in the example, the framework returns the domain object (object given to resolve.type). 
I think this is because of these lines in the runtime interpreter:

https://github.com/rmosolgo/graphql-ruby/blob/973135bfcb7809721e14268134b15538cf94f03d/lib/graphql/execution/interpreter/runtime.rb#L688-L689

As it is returning nil, it assumes we are not returning a tuple, causing an incorrect object being return.

**Versions**

`graphql` version: 2.0.4
`rails` (or other framework): 5.2
other applicable versions (`graphql-batch`, etc)

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok). Any custom extensions, etc?

```ruby
class NfcTagTaggableType < Types::BaseUnion
        possible_types Types::DynamicChecklists::TaskType

        def self.resolve_type(object, ctx)
          case object
          when ::DynamicChecklists::TaskConfig # Logbooks checklists
            [Types::DynamicChecklists::TaskType, find_appropiate_task(object, ctx)]
          end
        end

        def self.find_appropiate_task(domain_object, ctx)
           Task.find_by(app: domain_object.app, id: domain_object.id) # IMPORTANT: can be nil
        end
      end
    end
```

**Steps to reproduce**

Just create one union type and return a tuple from resolve_type, like 
```ruby
 def self.resolve_type(object, ctx)
   [AnyTypeInTheSchema, nil]
 end
```
and you will see it returns given object instead of nil

**Expected behavior**

If you intentionally return [Type, nil], nil should be returned in the union field.

**Comment by rmosolgo** [comment]
Thanks for the detailed report! I agree it should work the way you expect. I bet a refactor like this: 

```diff 

- resolved_type_or_lazy, resolved_value = resolve_type(current_type, value, path)
-  resolved_value ||= value 
+ resolve_type_result = resolve_type(current_type, value, path)
+ if resolve_type_result.is_a?(Array) && resolve_type_result.length == 2 
+   resolved_type_or_lazy, resolved_value = resolve_type_result
+ else 
+   resolved_type_or_lazy = resolve_type_result 
+   resolved_value = value 
+ end 
```

Would do the job. I'll take a look soon!

**Comment by alvaromat** [comment]
> Thanks for the detailed report! I agree it should work the way you expect. I bet a refactor like this:
> 
> ```diff
> - resolved_type_or_lazy, resolved_value = resolve_type(current_type, value, path)
> -  resolved_value ||= value 
> + resolve_type_result = resolve_type(current_type, value, path)
> + if resolve_type_result.is_a?(Array) && resolve_type_result.length == 2 
> +   resolved_type_or_lazy, resolved_value = resolve_type_result
> + else 
> +   resolved_type_or_lazy = resolve_type_result 
> +   resolved_value = value 
> + end 
> ```
> 
> Would do the job. I'll take a look soon!

Looks good, thank you so much.
