### ISSUE TITLE
Dataloader & scope_items / Pundit integration

### ISSUE THREAD

**Issue by bmulholland** [rmosolgo/graphql-ruby#4087]
We rely on scope_items for access control, but it seems to me that the dataloader would bypass this. There's nothing in the documentation about it, which would lead me to assume it just works out of the box. Does it? Are all the items somehow filtered to incorporate `scope_items`? Is `authorized?` run on each returned item from a dataloader? What happens when `authorized?` fails for one of those items -- is an error raised? Does the direct Pundit integration work with dataloaders? What are best practices here?

**Comment by bmulholland** [comment]
If dataloader does ignore scope_items, then [the suggested example for ActiveRecord](https://graphql-ruby.org/dataloader/sources.html#example-loading-activerecord-objects-by-id) will also expose data to other users, or throw errors when authorized? fails

**Comment by bmulholland** [comment]
> scope_items is called for any value returned where GraphQL returns a List type. It's called for Arrays except when using the Pundit integration. Additionally, each object in the list is still authorized at the object level and any unauthorized objects are replaced with nil.

Thanks, that's helpful to know. So worst case, implementing Dataloader in a Pundit scenario will end up returning a collection with nil items. That's still a very indirect consequence of implementing a Dataloader, and may be worth calling out in the Dataloader docs.

> When it comes to has_many relations, personally, I think you should skip batch-loading altogether. Any batch-loading implementation I've ever seen (except [one](https://pganalyze.com/blog/efficient-graphql-queries-in-ruby-on-rails-and-postgres)) depends on unbounded SELECTs to load all record into memory 😅

This seems strange, especially as I've seen Dataloader presented explicitly as an alternative to a lookahead with `.includes`, which of course would mostly make sense for a sub-resource/has_many.

`has_many` relations are the primary source of N+1 queries in our app, and are resulting in multi-second requests that I am trying to tame. In fact, they strike me as one of the primary scenarios where this pattern is needed. I've adopted the Dataloader pattern as the recommended approach for graphql-ruby. If that's not the case for some scenarios, a note in the docs would have been appreciated. What other approaches do you suggest for a `has_many`?

> How about an integration test?

Yep, I'm writing quite a lot of integration tests as I add these. It's hard to think of all the interactions, though, especially for scenarios where some data is shared and some is independent. And of course I'd prefer to be less paranoid about it.

**Comment by rmosolgo** [comment]
Taking a look at the example in that blog post: 

> ```ruby
> class Types::Tweet < Types::BaseObject
>   def author
>     dataloader.with(::Sources::ActiveRecord, ::User).load(object.author_id)
>   end
> end 
> ```

To me, that looks like a `belongs_to` association, that is, `Tweet.belongs_to(:author, class_name: "User")`, and then the `tweets` table would have an `author_id`. The loader in that example returns a single record (or `nil`), but not a Relation or an Array. 

And indeed, that _would_ solve an N+1: in the poorly-performing implementation, you'd fetch the tweets (the "1" in N+1), then fetch each tweet's author (the "N" in N+1). But after refactoring to use Dataloader like that, it'd be two queries: one to load the tweets and another to load all the authors of those tweets. 

Maybe we're using different words to talk about the same thing... could you clarify by sharing an example query that demonstrates the bad behavior you're looking at? That would put us on the same page here.

**Comment by bmulholland** [comment]
Me again :)

I've had more experience here now. If I can summarize what I wanted to know before (these are things I'd have liked to have known as part of a "here's how to adopt dataloader" doc page):
1. Dataloaders _must_ return an array, not an ActiveRecord relation. If you try to return a relation, then N+1 queries will still happen. I wish there were a logged warning when the return type is wrong, it would likely have saved me some time.
2. Dataloaders _should_ do any policy checks as part of their function. While it's true that authorization checks (`authorized?` on each object) will catch anything later, it's inefficient. Also, as I understand it, these may result in null entries in your returned array, which may expect only non-null entries.
3. The [ActiveRecord example from the docs](https://graphql-ruby.org/dataloader/sources.html#example-loading-activerecord-objects-by-id) does indeed ignore scope_items. `authorized?` will catch them, so make sure to implement that.
4. It _does_ seem helpful to use dataloaders for has_many attributes, especially when queries include >1 level of these.
5. Assuming scope_items operates on ActiveRecord relations/collections: Just as [the Pundit integration skips scoping arrays](https://graphql-ruby.org/authorization/pundit_integration.html#scopes), any manual implementation of `scope_items` must have a check if the list of items being passed in is an array, skipping any policy checks if so.  That's okay as long as this only happens for dataloaders, and as long as all dataloaders apply permissions checks. This is a worrisome foot-gun: it could silently skip permissions when forgetting the permission checks in a dataloader, or when adding an errant `to_a` when resolving a field.

New questions I have:
1. Is it actually helpful to [use a Dataloader in `object_from_id` as a default](https://graphql-ruby.org/dataloader/overview.html#loads-and-object_from_id)? Barring exceptional scenarios, that is probably called for only a handful of objects per request, isn't it?

**Comment by jhirn** [comment]
First of all, wow @rmosolgo. I have left graphql for two years and what you've done with this gem is just fantastic. 

I found this gist to be a completely adequate `has_many` Source for batching AR via Dataloader. I there's more to use with merge and it also still breaks my default scope_items policy application by side stepping git entirely. 

https://gist.github.com/itkrt2y/1e1a947c71772044f5d67f358b4772fc#file-example-rb-L16

I've added this to my base object 

```ruby
    def policy_scope!(current_user, scope)
      Pundit.policy_scope!(current_user, scope)
    end

    # works with collections but I need to figure out how to get it to work with batching. 
    def self.scope_items(items, context)
      if items.is_a?(Array) || items.is_a?(GraphQL::ExecutionError)
        items
      elsif policy_scope_class.blank?
        policy_scope!(context[:current_user], items)
      else
        policy_scope_class.new(context[:current_user], items).resolve
      end
    end

    def batch_has_many(object, association, scope)
      dataloader.with(DataLoaders::Association, association, scope).load(object)
    end
```

Using the loader above modified for Rails 7
```ruby
module DataLoaders
  class Association < GraphQL::Dataloader::Source
    def initialize(association_name, scope = nil)
      @association_name = association_name
      @scope = scope
    end

    def fetch(records)
      ::ActiveRecord::Associations::Preloader.new(records: records, associations: @association_name, scope: @scope).call
      records.map { |record| record.public_send(@association_name) }
    end

    # https://github.com/rmosolgo/graphql-ruby/blob/821ca53048fa5803fb90596719b4fedd65029ecb/lib/graphql/dataloader/source.rb#L113-L129
    def self.batch_key_for(*batch_args, **batch_kwargs)
      [*batch_args.map { |arg| arg.try(:to_sql) || arg }, **batch_kwargs]
    end
  end
end
```

And I can get policies to apply by manually passing the Pundit scope in, but I'd like to avoid this. However I've had to comment out scope_items above. 

```
# app/graphql/types/project_type.rb

field :documents, [Documents], null: false
def documents
  batch_has_many(object, :documents, policy_scope(Document))
end
```

This is what I could do from scratch with about 3 hours yesterday so I can provide another gist but lmk if htis helps you out @bmulholland .

@rmosolgo I cannot thank you enough for this gem and don't wish to force any opinions onto it or devalue the pro edition's Pundit integration, but I do feel the AR record example and documentation is a little light making the day-to-day rails-graphql integration at-hand. I think the best way I could help would be to provide a DataLoader-ActiveRecord page devoted to dealing with the has_ones, has_many, and belongs_to batching operations once I get something that is complete. I can leave all of the scope_items and Pundit stuff out of it  or leave it a a simple note the user must consider how it changes with batching. I completely understand DataLoder is agnostic to the ORM and framework being used, however I'm sure AR/Rails is pretty popular. 

Another alternative is I could push up an example app with the rails'y things. That might actually work better as it will isolate the nitpicking and improvements to Rails integration from your document maintenance. I still have a lot to grok about DataLoader before pushing up a canonical example, but perhaps people can nitpick it to death over there and it could serve as a resource to point people towards. PRs would definitely get it there and hopefully keep it current as scouring for gists and issues bothering you isn't great for anyone.

**Comment by rmosolgo** [comment]
Hey @jhirn, Sorry I didn't respond before but if you're still interested in writing AR-related docs or example code, that'd be great! I don't have plans to work further on any particular items mentioned here so I'll close this out.
