### ISSUE TITLE
`GraphQL::Types::JSON` is treated differently when passed in as a field on an input type

### ISSUE THREAD

**Issue by danielvdao** [rmosolgo/graphql-ruby#4099]
**Describe the bug**

When a field that is a `GraphQL::Types::JSON` scalar type is passed in on an input type as a query variable in a query string, the value is converted to an instance of `ActionController::Parameters`. The example query below should be more illustrative.

**Note** that if one isn't passing in query variables and just passes in the query with the values interpolated into the query string, this doesn't happen. Let me know if this isn't a bug - but it seems a bit odd.

In the resolver downstream, what we're having to do is something like:

```ruby
class InputObjectExample < Types::BaseInputObject
  field :json_value, GraphQL::Types::JSON, null: false
end
```

```ruby
class ExampleMutation < Types::BaseMutation

  ...
  argument :input_object_example, Types::InputObjectExample, required: true

  def resolve(input_object_example:)
    if argument.json_value.is_a?(ActionController::Parameters)
      input_object_example.json_value.to_unsafe_h 
    end
  end
end
```

**Versions**

`graphql` version: 2.0.9
`rails` (or other framework): 6.0.5

**GraphQL schema**

```ruby
class BarInputObject < GraphQL::Schema::InputObject
  argument :json_value, GraphQL::Types::JSON
end

class Product < GraphQL::Schema::Object
  field :foo, String do
    argument :bar, BarInputObject, required: true
  end

  def foo(bar:)
    # bar.json_value is an instance of `ActionController::Parameters`
    return 'Example'
  end
end

class QueryType < GraphQL::Schema::Object
  field :products, Product, null: false
end

class ApplicationSchema < GraphQL::Schema
  query QueryType
end
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
query($bar: BarInputObject!) {
  products { foo }
}
```

Query Variables:
```graphql
{
  "jsonValue": {
    "key1": "value1"
  }
}

```

**Steps to reproduce**

I think something like the schema above should suffice, but if not, please let me know!

**Expected behavior**

I think ideally - we would get a `Hash` object since that's what I think the JSON scalar should do and that's also the behavior with normal query strings.

**Actual behavior**

What specifically went wrong?

Trying to use certain `Hash` methods doesn't work like we thought (unfortunately I lost the stacktrace).

**Comment by rmosolgo** [comment]
Yep, `Types::JSON` just passes along whatever kind of object is given to it: 

https://github.com/rmosolgo/graphql-ruby/blob/f4d99f692d393cf5a1abbfe0e9bb61972ffba37f/lib/graphql/types/json.rb#L16-L18

So, if you're sending values through Rails `params`, it'll be an `ActionController::Parameters`, just like you noticed. My suggestion is to convert those parameters to a Hash in the controller. For example, here's what's in this library's Rails generator: 

https://github.com/rmosolgo/graphql-ruby/blob/f4d99f692d393cf5a1abbfe0e9bb61972ffba37f/lib/generators/graphql/templates/graphql_controller.erb#L36-L37

Does your controller have a conversion like that?
