### ISSUE TITLE
Question about deprecation of .to_graphql & .graphql_definition

### ISSUE THREAD

**Issue by ptsavdar** [rmosolgo/graphql-ruby#4110]
Hello,
I know the question is related to an older version of the Gem but we recently decided to update our gem from 1.13.0 to the latest one. We're doing this progressively and the first step for us it to move to 1.13.1 and get rid of the deprecated methods `.to_graphql` and `.graphql_definition`.

In the changelog we find this bit [here](https://github.com/rmosolgo/graphql-ruby/blob/master/CHANGELOG.md#deprecations-4) in which is stated that: `all behaviors should have been ported to class-based definitions` and we were unsure what this phrase really meant.

A few of the cases we were using these methods were:
- To dynamically add some options to Enums (we were using `.to_graphql` to actually add these extra options and then calling super in the enum classes themselves)
- We were dynamically extending some types with extra fields or options and then were using `Schema.graphql_definition` (in an initialiser) to reload the schema so that the newly added fields/options were present.

So we were wondering how we may achieve these now and if we could use any of the `class-based definitions` for them.

Thanks in advance for any information. Really appreciate it!

**Comment by rmosolgo** [comment]
Hey, great question. I'd be happy to help you find new implementations for these features. Could you please share some example code for those two cases? It really _depends_ what you mean by "options"! 

In short, any method that you would use in a class-based definition (for example `field(...)` for defining fields or `value(...)` for defining enum values) can be called on those classes after-the-fact, and they'll be present in the class-based schema. All the schema relationship code was rewritten to support dynamic updates to schema members. But please share some concrete examples and we'll see what we can do!

**Comment by rmosolgo** [comment]
Thanks for sharing those examples. How about: 

```ruby
class TargetTypeEnum < ::Types::BaseEnum
  # Define these enum values while the file is being loaded: 
  # (this will only work if `.target_types` is available while the application 
  # is booting up, and if it always returns the same set of values)
  Notifications::Types.target_types.each { |name| value(name) }
end
```

and

```ruby
# custom argument class:
class Argument < GraphQL::Schema::Argument
  # Override #initialize to take a new argument:
  def initialize(*args, public_api: false, **kwargs, &block)
    @public_api = public_api
     # Pass on the default args:
     super(*args, **kwargs, &block)
  end

  # This argument is visible if:
  # 1. It is configured to be part of the public API (always visible)
  # 2. Or, if the current request is _not_ `:public_api_ionly` (that is, it can see the private API, too)
  def visible?(context)
    @public_api || !context[:public_api_only] 
  end 
end
```

Before each query, GraphQL-Ruby will call `visible?` on each part of the schema that the query will use, see: https://graphql-ruby.org/authorization/visibility.html#hiding-parts-of-the-schema

I hope that helps! Please let me know what you encounter if you give it a try but run into trouble.
