### ISSUE TITLE
`UnauthorizedFieldError` should not inherit `UnauthorizedError`

### ISSUE THREAD

**Issue by FunkyloverOne** [rmosolgo/graphql-ruby#4113]
**Describe the bug**

I believe that `GraphQL::UnauthorizedFieldError` should not be inherited from `GraphQL::UnauthorizedError`, as it opens up possibilities of "false" rescues of `UnauthorizedFieldError`, and it brings inconsistency in its handling.

**Versions**

`graphql` version: 1.13.14

**Steps to reproduce**

if there's an unauthorized field, and authorization logic is wrapped in a promise the resulting error will look as if it's `UnauthorizedError`, instead of `UnauthorizedFieldError`.

**Expected behavior**

`UnauthorizedFieldError` should be rescued with its specific logic.

**Actual behavior**

`UnauthorizedFieldError` is rescued with `UnauthorizedError`'s logic.

**Comment by rmosolgo** [comment]
If anyone has specific issues with this inheritance, please share an example here or in a new issue and I'd be happy to look into further solutions :+1:
