### ISSUE TITLE
default_value: nil

### ISSUE THREAD

**Issue by dgodd** [rmosolgo/graphql-ruby#4116]
**Describe the bug**

It appears to me that if I state `default_value: nil` for an argument, then the resulting graphql.json will have
```
"defaultValue": "null"
```
instead of
```
"defaultValue": null
```

I think that this is a bug. Removing the default_value results in my expected schema.json. Now this could be an instance where I should simply not state a default_value, and indeed that is the fix for my software. However, this feels like an unexpected trap for the unwary.

PS. I am open to working on the PR for this if you agree it is a bug and are open to a PR.

**Versions**

`graphql`: 2.0.9
`rails`: 6.0.4.8
`graphql-batch`: 0.5.1
`graphql-schema_comparator`: 1.1.1

**GraphQL schema**

An example would be

```ruby
class MyMutation < Mutations::BaseMutation
  argument :name, String, required: false, default_value: nil
end
```

**GraphQL query**

The introspection query, or running `rake graphql:schema:json`

**Steps to reproduce**

`rake graphql:schema:json`

**Expected behavior**

schema.new.json to contain

```
"defaultValue": null
```

**Actual behavior**

schema.new.json contained

```
"defaultValue": "null"
```

**Comment by rmosolgo** [comment]
Hmm, I'm actually thinking that `"null"` is correct. From the [spec](https://spec.graphql.org/October2021/#sec-The-__InputValue-Type): 

> `defaultValue` may return a String encoding (using the GraphQL language) of the default value used by this input value in the condition a value is not provided at runtime. If this input value has no default value, returns `null`.

So, I think `"defaultValue": null` would be for inputs that _have no default value_, whereas `"defaultValue": "null"` is for inputs that _have_ a default value of **null**. 

To confirm this, could you try out the example in GraphQL-JS? I'd expect that implementation to follow the spec exactly.

**Comment by dgodd** [comment]
Thank you @rmosolgo , you are completely correct. 
I used [index.txt](https://github.com/rmosolgo/graphql-ruby/files/9024171/index.txt) to test it out, and I received

```
"defaultValue": "\"Friend\""
"defaultValue": "null"
"defaultValue": null
```

in exactly the way that you suggested I would.

Sorry for using your time up with my misunderstanding, and thank you very much for helping me.
