### ISSUE TITLE
Max validation errors on list elements 

### ISSUE THREAD

**Issue by stefanosx** [rmosolgo/graphql-ruby#4117]
Hello There, 
I have a question/suggestion. At the moment when we have a `Query` with a `List` argument with invalid items in the `List`, we are checking if each item is valid and at the end we return 1 error message with all the errors, like this:
``` JSON
{ 
  "message": "Variable $description of type [String!] was provided invalid value for 0 (Could not coerce value 1 to String), 1 (Could not coerce value 2 to String), 2 (Could not coerce value 3 to String), 3 (Could not coerce value 4 to String), 4 (Could not coerce value 5 to String)" 
}
```
is it possible at the moment to have a maximum validation errors for the items in the `List`? Like we do with the `validate_max_errors`? 
If it is not possible what do you think about adding this validation? or make it work with the existing `validate_max_errors`?

**Comment by rmosolgo** [comment]
Making it work with `validate_max_errors` sounds good to me, thanks for the suggestion!

**Comment by stefanosx** [comment]
> Making it work with `validate_max_errors` sounds good to me, thanks for the suggestion!

Thank you!! I will try to make a PR next days!

**Comment by stefanosx** [comment]
@rmosolgo I have an idea regarding that and I will like to chat with you about before i open a PR.

I can see that when we have a query with variables, the `validate_max_errors` is not checked at all. 
So if the value for the `validate_max_errors` is 2 and we have 3 invalid variables, we are going to return 3 errors. 
In the code, we are creating the `VariableValidationErrors` [here](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/query/variables.rb#L56) and we are appending them in the query validation errors [here](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/query/validation_pipeline.rb#L75).

What we can do in order to respect the limit, is to change the [code](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/query/variables.rb#L20) and break the loop in case the errors are bigger or equal with the max value. like that:
```ruby
  @storage = ast_variables.each_with_object({}) do |ast_variable, memo|
    break if schema.validate_max_errors && schema.validate_max_errors <= @errors.count
    ... 
    ...
```

With this change, the above example I mention, it will only return 2 errors.

But that still not solves the case when there are some big arrays with invalid variables, as we are checking if each element of the array is valid, and then we are merging all the errors into 1 `VariableValidationError`.

In combination with the above solution, I can suggest 3, kind of easy, ways of fixing that:
1. to break the [iteration in the list](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/list.rb#L50), when we are facing the first invalid element, and return the error result with just 1 problem. Similar to what is happening now with the [literal validator](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/static_validation/literal_validator.rb#L75)

2. pass an optional `errors_count` argument in the [validate_input](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/query/variables.rb#L33) method, like:

```ruby
  validation_result = variable_type.validate_input(provided_value, ctx, errors_count: @errors.count)
```

and change this method in the [List class](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/list.rb#L48) to add this optional argument and break the loop when the value is over the `validate_max_errors`, like:
```ruby
def validate_non_null_input(value, ctx, errors_count: nil)
  result = nil
  ensure_array(value).each_with_index do |item, index|
    item_result = of_type.validate_input(item, ctx)
    unless item_result.valid?
      break if ctx.schema.validate_max_errors && errors_count && ctx.schema.validate_max_errors <= errors_count
      errors_count += 1 if errors_count
      result ||= GraphQL::Query::InputValidationResult.new
      result.merge_result!(index, item_result)
    end
  end
  result
end
```

3. Change the code in the list class to raise multiple errors for each invalid element instead of one. instead of raising 1 `VariableValidationError`, we will raise as many as the invalid elements in the array.

What do you think about it?
