### ISSUE TITLE
Skipping static validation does not work.

### ISSUE THREAD

**Issue by toneymathews** [rmosolgo/graphql-ruby#4120]
**Describe the bug**

https://github.com/rmosolgo/graphql-ruby/pull/3881 was shipped to allow static validation to be skipped. `ValidationPipeline` called `@query.validate` to fetch the value. It was tagged with 1.13.9 but is not fully there in that version. 

It is present in 2.0 +.

Can we pls get a 1.13.x version with the changes from https://github.com/rmosolgo/graphql-ruby/pull/3881 ?

**Versions**

`graphql` version: 1.13.9 to 1.13.14

**Steps to reproduce**
This should be `validate: @query.validate`.

https://github.com/rmosolgo/graphql-ruby/blob/f119cf7519130b7f05214392b27d04efddb02f1e/lib/graphql/query/validation_pipeline.rb#L75

**Comment by rmosolgo** [comment]
Derp, sorry about overlooking this the first time. I just released 1.13.15 with code from those to PRs. Please let me know if you encounter any trouble with it!
