### ISSUE TITLE
Applying max_page_size to field causing an additional db query to be made

### ISSUE THREAD

**Issue by cnagadya** [rmosolgo/graphql-ruby#4121]
**Describe the bug**

When a [max_page_size](https://graphql-ruby.org/pagination/using_connections.html#max-page-size) is applied to a field, two db queries are made: 1st query fetches all items and a 2nd similar one with the limit applied. Is this expected behaviour? I would have expected that the limit is always applied and no call to fetch all items is passed. On upgrade to version 1.13.3, the limit does not even get applied. 
For additional context, we have Multiple DBs with [manual connection switching](https://guides.rubyonrails.org/v6.0.4/active_record_multiple_databases.html#using-manual-connection-switching) in our project 

**Versions**
`graphql` version: 1.13.2
`rails` : 6.0.4

```ruby
class Product < GraphQL::Schema::Object
  field :products, Product.connection_type, null: false, max_page_size: 20
  # …
end
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
query {
  products { id title }
}
```

```json
{
  "data": {
    "products": […]
  }
}
```

**Comment by rmosolgo** [comment]
Hi! Thanks for the detailed report. This is _not_ the expected behavior. Like you mentioned, I would expect a single query with the limit applied. To debug further, could you please share: 

- The implementation of `products` (is it a has-many relation, or is there `def products` in the object type, or is there a resolver class?) 
- The queries executed by `products`, from your Rails log 


That should give some clues as to where this is coming from.

**Comment by cnagadya** [comment]
The parent, say shop has many products. I probably oversimplified the query in the example because I am only getting the issue on the products but a more accurate one is 
```
query  {
  shops(locationId: 3) {
    edges {
      node {
        products {
          edges {
            node {
              id
              title
            }
          }
        }
      }
    }
  }
}
```

> SELECT `shops`.* FROM `shops` INNER JOIN `locations` ON `locations`.`id` = `shops`.`location_id` WHERE `locations`.`id` = 3 
> SELECT `products`.*  FROM products WHERE `products`.shop_id = 1234 ORDER BY package_name ASC    
> SELECT `products`.*   FROM products WHERE `products`.shop_id = 1234 ORDER BY package_name ASC  LIMIT 25

**Comment by cnagadya** [comment]
@rmosolgo, have you had any chance to further look into this yet?

**Comment by rmosolgo** [comment]
Hey, I wrote up a minimal replication which shows only one query: 

<details>
<summary>Active-Record based connection with max_page_size</summary>

<p>
```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'activerecord'
  gem 'graphql', '~> 2.0'
  gem 'sqlite3'
end

require "active_record"

ActiveRecord::Base.establish_connection(
  :adapter => "sqlite3",
  :database  => ":memory:"
)


ActiveRecord::Schema.define do
  create_table :items do |table|
  end
end

class Item < ActiveRecord::Base
end

25.times { |n| Item.create }

class ItemType < GraphQL::Schema::Object
  field :id, Integer, null: true
end

class QueryType < GraphQL::Schema::Object
  field :items, ItemType.connection_type, null: false, max_page_size: 10

  def items
    Item.all
  end
end

class TestSchema < GraphQL::Schema
  query(QueryType)
end

query = <<-GRAPHQL
  query {
    items {
      nodes {
        id
      }
    }
  }
GRAPHQL

ActiveRecord::Base.logger = Logger.new(STDOUT)
result = TestSchema.execute(query)
pp result.to_h

# D, [2022-07-04T12:04:02.534366 #34514] DEBUG -- :   Item Load (0.1ms)  SELECT "items".* FROM "items" LIMIT ? OFFSET ?  [["LIMIT", 10], ["OFFSET", 0]]
# {"data"=>
#   {"items"=>
#     {"nodes"=>
#       [{"id"=>1},
#        {"id"=>2},
#        {"id"=>3},
#        {"id"=>4},
#        {"id"=>5},
#        {"id"=>6},
#        {"id"=>7},
#        {"id"=>8},
#        {"id"=>9},
#        {"id"=>10}]}}}
```
</p>
</details>

Could you please share the implementation of the `shops` field? Perhaps it's a method or a resolver. I'd like to rule out the possibility that the extra query is coming from application code, not GraphQL-Ruby source code. 

Alternatively, you could add some debug output right after your implementation to help us make sense of the log, for example:

```ruby 
# if it's implemented with a method: 
def shops(...) 
  shops = # all the code to get a list of shops goes here 
  puts "Done preparing shops, returning a value to GraphQL now"
  shops 
end 
```

Then, share the log again. I'm curious where the newly-added log method will fall in the sequence of SQL queries 🤔

**Comment by cnagadya** [comment]
Yes, I think you are right, it has something to do with our field implementations. I tried to setup a [test project ](https://github.com/cnagadya/bug-free-octo-umbrella)with the same dependencies and versions and didnt run into the issue either
