### ISSUE TITLE
Context scoped_set! not working when it is called after dataloader

### ISSUE THREAD

**Issue by alvaromat** [rmosolgo/graphql-ruby#4125]
**Describe the bug**

I have a query like this:

```graphql
query {
 posts { # posts returns multiple posts. context[:form_owner] is set in the post object.
   form {
     question {
       # context[:post_owner] is read here. 
       answer  {
         textValue
       }
     }
   }
 }
}
```

In the post object, I'm using the dataloader and then calling context.scoped_set!
```ruby
class PostObject < ::Types::Base::ObjectType

  field :form, ....
  def form
    context.dataloader
                 .with(Sources::ActiveRecordAssociation, ::Post, :form)
                 .load(object)
    context.scoped_set!(:form_owner, object)
    object.form
  end
end
```

In the QuestionType, I use the context to resolve the answer:
```ruby
field :answer, AnswerType, null: true
        def answer
          owner = context[:form_owner]
          return nil unless owner

         ::Templates::Answer.find_by(owner: owner, question: object.id)
        end
```

But when graphql is resolving this field, context[:form_owner] is always nil.

Now it comes the interesting part. After debugging for a while, I realised that setting the context **before** dataloader is called solves the issue. So the new implementation of Post.form would be:
```ruby
field :form, ....
def form
  context.scoped_set!(:form_owner, object)
  context.dataloader
               .with(Sources::ActiveRecordAssociation, ::Post, :form)
               .load(object)
  object.form
end
```

The order might not seem to be a big issue, but it matters because we have extracted the dataloader call to a field extension:
```ruby
class PreloadExtension < GraphQL::Schema::FieldExtension
  def resolve(object:, arguments:, context:, **_rest)
    # object is the GQL type. i.e: StaffType
    # object.object is the object assigned to the gql type, which will likely be a model. i.e: an User for StaffType.
    model = object.object

    # Preload association in case field maps to an association that can be preloaded
    if can_preload(model)
      context.dataloader
             .with(Sources::ActiveRecordAssociation, model.class, association_name)
             .load(model)
    end

    yield(object, arguments)
  end
end
```

So in our schema, the dataloader is always called before the context can be set.

**Versions**

`graphql` version: 2.0.11
`rails` (or other framework): 5.2.7

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok). Any custom extensions, etc?

```ruby
class Sources::ActiveRecordAssociation < GraphQL::Dataloader::Source
  def initialize(model_class, association_name)
    @model_class = model_class
    @association_name = association_name
  end

  def fetch(records)
    ::ActiveRecord::Associations::Preloader.new.preload(records, @association_name)
  end
end
```

**Expected behavior**

`context.scoped_set!` call should work even if it is called after dataloader.

**Actual behavior**

What specifically went wrong?

Calling `context.scoped_set!` after `dataloader.with().load()` causes the context not to be set in children fields.

**Additional context**

I realised that this problem is not happening during rspec execution, only when running `rails s`.

**Comment by rmosolgo** [comment]
Wow, what a tricky one! Thanks for the details on this.

I wonder if the runtime's tracking of `context[:current_path]` isn't working right. Under the hood, scoped_context uses that to look up values: 

https://github.com/rmosolgo/graphql-ruby/blob/2a4824db498dc0c3595cf0341f4dea7f5ecbd9e1/lib/graphql/query/context.rb#L113-L115

But maybe it's not being properly reset after dataloader hands control back to the runtime. I'll take a look soon!

**Comment by rmosolgo** [comment]
This turned out to be a lot more complicated than I expected. The thing is, with Dataloader (or GraphQL-Batch, really), GraphQL execution can pause in the middle of one field, then run on another field for a while, then come back to the original one. 

`context` is shared by the whole query -- this is essential from a performance standpoint -- but it's also mutable. So when execution switches from one field to another, things like `context[:current_path]` become stale. 

When the switch is handled by GraphQL's runtime code, it always calls `set_interpreter_context(...)` to reset all those mutable values to reflect the currently-running field. But when it's Dataloader, it doesn't have a way to reset them (it doesn't know about `context` at all, since it can even span multiple queries). 

So, I'm not exactly sure what to do yet. I first tried refactoring the code to use fiber-local variables for this runtime info (eff783a13). It didn't even fix the problem. I'll have to keep thinking about it!

**Comment by alvaromat** [comment]
Thanks for doing the research. It seems to have become a bit of a problem. It would be good to have it as we are probably not the only ones using field extensions to extract functionality out.
