### ISSUE TITLE
Custom Argument to Validate JSON in Model 

### ISSUE THREAD

**Issue by fameoflight** [rmosolgo/graphql-ruby#4126]
I know this is stretch, but would love for you to point me in right direction. 

Right now I have json fields in some of model, I write separate validation for them in model and then also write separate ArgumentType in Graphql and Object Type for them. 

I am wondering how would I go about using Argument to validate JSON schema in ActiveRecord. I understand this is out of scope for this library, also bit hacky. Would love not to have to write these three different code pieces.  Any example in test or anything of little guidance would be great help.

**Comment by rmosolgo** [comment]
I would suggest a slightly different code organization strategy: 

1. Implement your validation logic in a class method on your model (or another code reuse container of your choosing), for example:

    ```ruby
    class Thing < ActiveRecord::Base 
      def self.validate_something_custom(thing)
        # apply a validation to `thing` here, adding errors if anything is invalid 
      end 
     end 
     ```

2. Connect the validation logic to the model with `validate ...` and an instance method which calls the already-defined class method, for example:

    ```ruby
    class Thing < ActiveRecord::Base 
      validate :something_custom 
      
      private 
      
      def something_custom 
        self.class.validate_something_custom(self)
      end 
    end 
    ```

3. Add a GraphQL-Ruby validator based on the same class method, for example: 

    ```ruby
    class ThingType < GraphQL::Schema::Object 
      class SomethingCustomValidator < GraphQL::Schema::Validator
        def validate(object, context, value) 
          ::Thing.validate_something_custom(object)
          object.errors.full_messages # return any validation errors as GraphQL errors
        end 
      end 
       
      # hook up the custom validator (with an empty options Hash, in this case)
      field :something, ..., validates: { SomethingCustomValidator => {} }
    end   
    ```

I see that you want to perform some validation on incoming JSON, so maybe you'll have to tweak that a bit, but I hope it helps! If you run into trouble after giving it a try, please share the code that you tried and what error message (or misbehavior) you encountered when you tried it.
