### ISSUE TITLE
Cannot rescue errors raised inside actioncable worker thread

### ISSUE THREAD

**Issue by Maaarcocr** [rmosolgo/graphql-ruby#4131]
**Describe the bug**

When using the ActionCable implementation for subscriptions it is impossible to rescue errors that happen inside the worker thread where messages are handled after a `.trigger` is invoked. For example, if a trigger sends some invalid data for an enum, this would raise, but it cannot be rescued anywhere. Even defining a `rescue_from` in the schema does not help with this.

This makes error reporting impossible and it's a major concern for production applications.

**Versions**

`graphql` version: 2.0.11
`rails` (or other framework): 7.01
other applicable versions (`graphql-batch`, etc)

**GraphQL schema**

The schema and the different types can be found at the repro repo at https://github.com/Maaarcocr/graphql-ruby-repro

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
subscription Subscription {
  test {
    number
  }
}
```

**Steps to reproduce**

Go to https://github.com/Maaarcocr/graphql-ruby-repro and clone the repo

run `npm i && npm run build`

run `bundle install && bin/rails s`

Open (http://127.0.2.3:3000/)[http://127.0.2.3:3000/] in your browser. This is a react page that uses `useSubscription` from Apollo.
Open (http://127.0.2.3:3000/number)[http://127.0.2.3:3000/number] in your browser. This is a rails page that on `index` just invokes `RailsRuby3Schema.subscriptions.trigger(:test, {}, {number: 2})`. Note that 2 is not a value for the NumberType, so this will raise an error on update.

**Expected behavior**

If I define `rescue_from` in the schema, any error that happens on the worker thread of actioncable should also be rescued.

**Actual behavior**

The error is logged into the console, but from the log you'll be able to see that it was not rescued by: 

```
rescue_from StandardError do |error|
    puts "AN ERROR: #{error}"
  end
```

which is defined on the schema, as it does not contain the string `AN ERROR`, but it's just logged by https://github.com/rails/rails/blob/b3175b953cf5e7d0f3afb3cc4268ec452993b2ad/actioncable/lib/action_cable/server/worker.rb#L60

**Additional context**

I think the easiest solution would be to have a rescue block in https://github.com/rmosolgo/graphql-ruby/blob/2998a6e63b697823475058e6d94bf2aa40db771f/lib/graphql/subscriptions/action_cable_subscriptions.rb#L163 that just calls `@schema.handle_or_reraise`.

**Comment by jessie-JNing** [comment]
cc: @rmosolgo

**Comment by rmosolgo** [comment]
Thanks for the ping on this -- sorry I missed it earlier. In order to get the full error message and backtrace, I cloned the repository and replicated the bug. Here it is:

```
There was an exception - Types::NumberType::UnresolvedValueError(`Test.number` returned `2` at `test.number`, but this isn't a valid value for `Number`. Update the field or resolver to return one of `Number`'s values instead.)
/Users/rmosolgo/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/graphql-2.0.11/lib/graphql/schema/enum.rb:143:in `coerce_result'
/Users/rmosolgo/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/graphql-2.0.11/lib/graphql/execution/interpreter/runtime.rb:684:in `continue_field'
/Users/rmosolgo/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/graphql-2.0.11/lib/graphql/execution/interpreter/runtime.rb:516:in `block (3 levels) in evaluate_selection_with_args'
/Users/rmosolgo/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/graphql-2.0.11/lib/graphql/execution/interpreter/runtime.rb:925:in `after_lazy'
/Users/rmosolgo/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/graphql-2.0.11/lib/graphql/execution/interpreter/runtime.rb:513:in `block (2 levels) in evaluate_selection_with_args'
/Users/rmosolgo/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/graphql-2.0.11/lib/graphql/execution/interpreter/runtime.rb:826:in `call_method_on_directives'
/Users/rmosolgo/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/graphql-2.0.11/lib/graphql/execution/interpreter/runtime.rb:498:in `block in evaluate_selection_with_args'
/Users/rmosolgo/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/graphql-2.0.11/lib/graphql/execution/interpreter/runtime.rb:925:in `after_lazy'
/Users/rmosolgo/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/graphql-2.0.11/lib/graphql/execution/interpreter/runtime.rb:436:in `evaluate_selection_with_args'
/Users/rmosolgo/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/graphql-2.0.11/lib/graphql/execution/interpreter/runtime.rb:425:in `evaluate_selection'
/Users/rmosolgo/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/graphql-2.0.11/lib/graphql/execution/interpreter/runtime.rb:358:in `block (2 levels) in evaluate_selections'
/Users/rmosolgo/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/graphql-2.0.11/lib/graphql/dataloader.rb:181:in `block in run'
/Users/rmosolgo/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/graphql-2.0.11/lib/graphql/dataloader.rb:303:in `block in spawn_fiber'
```

It looks to me like the problem is that GraphQL-Ruby's call to `coerce_result` isn't wrapped by error handling, but it should be. I opened #4206 to add that.

After pointing the reproduction code at that branch and visiting `/number`, I get this message in the Rails logs: 

```
AN ERROR: `Test.number` returned `2` at `test.number`, but this isn't a valid value for `Number`. Update the field or resolver to return one of `Number`'s values instead.
```

ActionCable-wise, I think ActionCable's own `rescue_from` method would be the way to improve error handling: https://edgeguides.rubyonrails.org/action_cable_overview.html#server-side-components-connections-exception-handling

How does that all sound to you?

**Comment by jessie-JNing** [comment]
Thanks @rmosolgo , that is much helpful!
