### ISSUE TITLE
rake graphql:schema:idl does not include fields hidden by policies

### ISSUE THREAD

**Issue by qshanahan-springhealth** [rmosolgo/graphql-ruby#4140]
`rake graphql:schema:idl` seems to generate a schema as it would be for an anonymous user. Is there a way to generate the whole schema?

**Comment by rmosolgo** [comment]
Yup, that's right -- by default, it uses an _empty_ context object, so it would behave as if no user is present. 

To generate a schema dump with some information in `context`, I honestly recommend writing your own task. (The built-in Rake task has options, but I'm not exactly sure how to hook them up, [api doc](https://graphql-ruby.org/api-doc/2.0.11/GraphQL/RakeTask).) For example: 


```ruby 
task dump_admin_schema: :environment do
  # Create an object that will look like an Admin user to your schema
  # (You could also initialize or fetch a real `User` object if that works in your case)
  admin_user = OpenStruct.new(admin?: true)
  # Generate a SDL string using your schema: 
  admin_schema_dump = MyAppSchema.to_definition(context: { current_user: admin_user })
  # Write the string to a file:
  admin_schema_path = "app/graphql/admin_schema.graphql"
  File.write(Rails.root.join(admin_schema_path), admin_schema_dump)
end
```

Want to give that approach a try?

**Comment by qshanahan-springhealth** [comment]
@rmosolgo this works thank you!
