### ISSUE TITLE
`require_admin` or custom Field Authorization not sending to `initialize` method in `GraphQL::Schema::Object` 

### ISSUE THREAD

**Issue by Nealsoni00** [rmosolgo/graphql-ruby#4143]
**Describe the bug**

I'm trying to implement [Field Authorization](https://graphql-ruby.org/authorization/authorization#field-authorization) as shown in the documentation for `require_admin` added to a field but I'm getting an error saying:

`Minitest::UnexpectedError: ArgumentError: unknown keyword: :require_admin`

It is not sending the argument to the `initialize` method in `GraphQL::Schema::Object` 

**Versions**

`graphql` version: 1.12
`rails`: 7

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok). Any custom extensions, etc?

```ruby
module Types
  class Chatroom < BaseObject
    field :id, ID, null: false, require_admin: true  #<-- This line errors only when require admin is included
    def initialize(*args, require_admin: false, **kwargs, &block)
      @require_admin = require_admin
      super(*args, **kwargs, &block)
    end
    def self.authorized?(object, context)
      authroized_read = context[:current_identity].is_admin if @require_admin                  
      super && authroized_read
    end
end
```

**Steps to reproduce**

1. Add a custom authorization argument on any `field` and it will error

Would love any and all feedback on how to get this custom field level authorization to work!

**Comment by rmosolgo** [comment]
Perhaps you got to the bottom of it -- `def initialize(*args, require_admin: false, **kwargs, &block)` belongs in the _field_ class, not the object class. (Because, under the hood, `field(...)` becomes `Field.new(...)` :+1:)
