### ISSUE TITLE
GraphQL::Subscriptions::InvalidTriggerError encountered after upgrading past 2.0.0

### ISSUE THREAD

**Issue by hueter** [rmosolgo/graphql-ruby#4150]
**Describe the bug**

Hello, we have been using GraphQL Ruby subscriptions without issue for a few years, but our subscriptions broke when we recently attempted to update the gem to 2.0.1+

This shows up as a runtime error in our server logs when our background jobs call:

`MySchema.subscriptions.trigger('contactsBulkActionsProcessed', {}, true, scope: #<Account:0x00012345>)`

```
20:15:35 web.1                 | [194d537c-723e-4dec-a148-293eb2021b87] method=POST path=/graphql format=*/* controller=GraphqlController action=execute status=200 duration=143.94 view=0.12 db=72.15 current_user_id=1
20:16:19 default_worker.1      | 2022-07-26T00:16:19.465Z pid=59741 tid=9b4p class=GraphqlSubscriptionJob jid=3c84f9b2565b5c6d61eb9a79 INFO: start
20:16:20 default_worker.1      | 2022-07-26T00:16:20.757Z pid=59741 tid=9b4p class=GraphqlSubscriptionJob jid=3c84f9b2565b5c6d61eb9a79 INFO: Performing GraphqlSubscriptionJob (Job ID: d558641f-e2b7-40e4-ab48-b44b37d6b74d) from Sidekiq(default) enqueued at 2022-07-26T00:06:56Z with arguments: "contactsBulkActionsProcessed", true, #<GlobalID:0x000000012cd06ce0 @uri=#<URI::GID gid://myapp/Account/1>>
20:16:20 default_worker.1      | 2022-07-26T00:16:20.758Z pid=59741 tid=9b4p class=GraphqlSubscriptionJob jid=3c84f9b2565b5c6d61eb9a79 ERROR: Error performing GraphqlSubscriptionJob (Job ID: d558641f-e2b7-40e4-ab48-b44b37d6b74d) from Sidekiq(default) in 15.39ms: GraphQL::Subscriptions::InvalidTriggerError (No subscription matching trigger: contactsBulkActionsProcessed (looked for Subscription.contactsBulkActionsProcessed)):
20:16:20 default_worker.1      | /Users/hueter/.rvm/gems/ruby-3.1.2/gems/graphql-2.0.12/lib/graphql/subscriptions.rb:80:in `trigger'
```

Our client appears to be initiating the subscription successfully: 

```sh
20:11:20 web.1                 | method= path= format= params={"query"=>"subscription contactsBulkActionsProcessed {\n  contactsBulkActionsProcessed\n}", "variables"=>{}, "operationName"=>"contactsBulkActionsProcessed", "action"=>"execute"} controller=GraphqlChannel action=execute status=200 duration=11.28
```

<img width="717" alt="Screen Shot 2022-07-25 at 8 14 02 PM" src="https://user-images.githubusercontent.com/13444851/180895888-d22b441d-a3fc-4ca5-bb4f-eb2365dc5de8.png">

**Versions**

`graphql`: 2.0.1+
`rails` (or other framework):  Rails 7.0.3.1
`ruby`: 3.1.2

**JS**

`graphql-ruby-client`: 1.11.1
`@apollo/client`: 3.6.9

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok). Any custom extensions, etc?

```ruby
class MySchema < GraphQL::Schema
  use GraphQL::Subscriptions::ActionCableSubscriptions

  mutation(Types::MutationType)
  query(Types::QueryType)
  subscription(Types::SubscriptionType)
end

module Subscriptions
  class BaseSubscription < GraphQL::Schema::Subscription
    # Hook up base classes
    object_class Types::BaseObject
    field_class Types::BaseField
    argument_class Types::BaseArgument
  end
end

module Types
  class SubscriptionType < Types::BaseObject
    field :contacts_bulk_actions_processed,
          Boolean,
          null: true,
          subscription_scope: :current_account
  end
end
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
subscription contactsBulkActionsProcessed {
  contactsBulkActionsProcessed
}
```

**Steps to reproduce**

1. Establish a subscription using the client
2. call `MySchema.trigger`

**Additional Context**

The `graphql_channel.rb` is the same as [the recommended Action Cable implementation](https://graphql-ruby.org/api-doc/2.0.12/GraphQL/Subscriptions/ActionCableSubscriptions)

Wondering if we missed some configuration change or what this type of error results from? If there was anything we could try with it

Thank you

**Comment by rmosolgo** [comment]
Wow... it definitely all looks _right_! 

The big change from 2.0.0 to 2.0.1 is that `.trigger` started checking `.visible?` before matching triggers to fields: https://github.com/rmosolgo/graphql-ruby/pull/3924/files

Do you implement `visible?` in any types, fields, or resolvers? If so, you might need to add `context: { ... }` to your trigger call to make it find the right field implementation. (Or if you not sure, could you share any `visible?` method definitions from your schema code?)

**Comment by hueter** [comment]
oh @rmosolgo thank you, that was definitely it. We implemented `visible?` for auth purposes, to hide fields from unauthorized users, something like this in `base_field.rb`:

```rb
  def visible?(context)
    super && (min_role.nil? ? true : role_authorized?(min_role, context[:current_role]))
  end
```

so we needed to:

- specify the role required on subscription fields
- and also pass in the `current_role` to the `context` argument where we invoke `.trigger`

it started working after that 🙂 thanks for the quick reply!
