### ISSUE TITLE
Is it possible to set a max_page_size on a custom connection?

### ISSUE THREAD

**Issue by anujbiyani** [rmosolgo/graphql-ruby#4151]
Firstly, thank you so much for your work on this project! Love the library, and how helpful you are in responding to issues.

**Is your feature request related to a problem? Please describe.**

When creating a custom connection like https://graphql-ruby.org/type_definitions/extensions.html#customizing-connections, is it possible to set a `max_page_size` and `default_page_size`?

I see how to do it with the [other style of custom connection](https://graphql-ruby.org/pagination/custom_connections.html#using-a-custom-connection) (where you create a `Connections::CustomConnection` class), but I have a use case where I don't need to create a custom connection class, I just need a custom connection _type_ (so that I can add a `total_page_count` field).

The only solution I've found is to set `max_page_size` on the field that returns that connection type, but then every field using that connection type has to specify a max page size.

Here's some sample code to show the issue, and my ideal solution (assuming one doesn't already exist):
```ruby
class Types::QueryType < Types::BaseObject
  field :users, Types::User.connection_type, null: false, max_page_size: 10 # prefer not to have to specify `max_page_size` here
  def users
    User.active # made up scope that returns an `ActiveRecord` query
  end
end

class Types::User < Types::BaseObject
  connection_type_class Types::UsersConnection

  [... fields ...]
end

class Types::UsersConnection < GraphQL::Types::Relay::BaseConnection
  max_page_size 10 # this doesn't work, but something like this would be nice

  field :total_page_count, Integer, null: false
  def total_page_count
    # custom logic
  end
end
```

Is there a better way to set the `max_page_size` than on each field that returns the connection type?

**Comment by rmosolgo** [comment]
Great question! Y'know, even though there's no pretty API for it (yet?), I think you _could_ accomplish this by adding it to `def initialize` in your base field class definition, for example: 

```ruby 
class Types::BaseField < GraphQL::Schema::Field 
  def initialize(*args, **kwargs, &block)
    super
    # Use `.unwrap` here to handle fields with `null: false`
    if type.unwrap == Types::User.connection_type && !@has_max_page_size 
      @has_max_page_size = true # This is a little janky, have to also set this to `true`, usually it's set at https://github.com/rmosolgo/graphql-ruby/blob/16c90841eb039f38ef5394b9fdd5aa7cffcf9dbe/lib/graphql/schema/field.rb#L273
      @max_page_size = 10 
    end 
  end 
end 
```

Want to give that a try?

**Comment by anujbiyani** [comment]
Interesting, I'll give that a shot! For a longer-term fix, would you be open to a PR along the API I proposed?

**Comment by rmosolgo** [comment]
Yes, I think that'd be a nice improvement! The trick would be finding a good way to apply _that_ `max_page_size` in a way that somewhat makes sense with the existing possible `max_page_size`s ... or at least, is easy to document alongside them. If you want to give it a shot, that'd be great -- just let me know if I can help with anything along the way.

**Comment by rmosolgo** [comment]
I don't have any plans to work further on this, but if someone wants to pursue the improvement described above, please open a new PR or issue to discuss it :+1:
