### ISSUE TITLE
Configurable headers in sync/sendPayload

### ISSUE THREAD

**Issue by utay** [rmosolgo/graphql-ruby#4157]
**Is your feature request related to a problem? Please describe.**

Currently I can't pass custom headers to the sync `sendPayload` HTTP call. 

**Describe the solution you'd like**

It'd be great to be able to pass extra headers in https://github.com/rmosolgo/graphql-ruby/blob/230a91ab211d3cb7a5ce7243abeb5817e23d59da/javascript_client/src/sync/sendPayload.ts#L49 via the CLI such as `--headers 'Header1:value1,Header2:value2'` or something along those lines. It could certainly be a `SendPayloadOptions` field.

**Describe alternatives you've considered**

For now I've used a script with `const { sync } = require('graphql-ruby-client')` and my custom `sendPayload` function instead of using the CLI.

**Comment by rmosolgo** [comment]
:+1: Thanks for the suggestion, I agree this would be a nice feature to add. I'll take a look soon and follow up here!

**Comment by utay** [comment]
@rmosolgo Thank you!

**Comment by rmosolgo** [comment]
Thanks again for this suggestion. I just released `graphql-ruby-client` v1.11.2 with a new `--header={key}:{value}` option. Please let me know what you think if you give it a try!

**Comment by utay** [comment]
@rmosolgo Just saw this now, thank you it works like a charm!
