### ISSUE TITLE
`InvalidNull` exceptions created without backtraces

### ISSUE THREAD

**Issue by brasic** [rmosolgo/graphql-ruby#4158]
https://github.com/rmosolgo/graphql-ruby/blob/2c92f83438b6601b430a23611409cb2e715b7500/lib/graphql/execution/interpreter/runtime.rb#L587

`InvalidNullError` objects are created via `#new` rather than `raise` so they don't have a backtrace. This is inconvenient since these errors might be passed to an exception tracker or in a result extension, where the full backtrace could be useful.  Any reason not to populate the backtrace using `set_backtrace(caller)` or similar?

**Comment by rmosolgo** [comment]
Ah, good point! I'm definitely open to `set_backtrace`.  From a debugging standpoint, I _think_ that the backtrace would always point to GraphQL internals, but you might also use `error.field.path` or `context[:current_path]` (in the error handler) to figure out where _in the query_ the invalid null was encountered. Anyhow, agreed a proper backtrace would be a good improvement!

**Comment by brasic** [comment]
Hmm, I was debugging an issue that led me here and altering the code to call `set_backtrace(caller)` did result in a pretty frameworky stack but there was _just_ enough there to figure out what was going on. Perhaps in general the call to `caller()` isn't worth the expense.

Agreed that a representation of the query execution path is much more useful than a ruby backtrace,  I will look into adding that in the error handler as exception context in the case I was looking at.
