### ISSUE TITLE
Unable to modify the `type` of the existing field via change set feature

### ISSUE THREAD

**Issue by ashikajith** [rmosolgo/graphql-ruby#4161]
I am trying to change the `type` of the field and make the field accept an argument. I intend to make use of the changeset feature, which is available in the enterprise version.

From
```ruby
# Old field type in post_type.rb
class Types::Objects::PostType < BaseObject
  field :post_logo, ::Types::Objects::LogoType, null: true
  ...
end
```
To
```ruby
class Types::Objects::PostType < BaseObject
  field :post_logo, ::Types::Objects::NewLogoType, null: true do
    argument :size_to_limit, ::Types::Enums::VariantSize,
                    description: "resize the image to fit these dimensions",
                     required: true
  end
  ...
end
```

### First Try
I was referring to the official Graphql doc [here](https://graphql-ruby.org/changesets/definition.html) and it mentioned the use of `update_field` to define a new type from the existing field.  

```ruby
  module Changesets
    class FixPostLogoFieldType < ::GraphQL::Enterprise::Changeset
      release "2022-09-21"

      modifies Types::Objects::PostType do
        modifies :post_logo do
          argument :size_to_limit, ::Types::Enums::VariantSize,
                   description: "resize the image to fit these dimensions",
                   required: true
        end
        update_field :post_logo, ::Types::Objects::NewLogoType  # here it is erroring out since update_field is undefined
      end
    end
  end

```

But I got the error `update_field` is **undefined** in the above changeset. So I inspected the enterprise source code but could not find any definition/method_name called `update_field`. So I think we have a mistake in the doc [here](https://graphql-ruby.org/changesets/definition.html#types); it says it is present.

### Second try
My next try was to modify the whole field with the below change set

```ruby
  module Changesets
    class FixProfileAvatarFieldType < ::GraphQL::Enterprise::Changeset
      release "2022-09-21"

      modifies ::Types::Objects::AccountType do
        field :post_logo, ::Types::Objects::NewLogoType, null: true do
          argument :size_to_limit, ::Types::Enums::VariantSize,
                   description: "resize the image to fit these dimensions",
                   required: true
        end
      end
    end
  end
```

I was able to see the changesets in the schema from the console
```bash
APISchema.changesets.first.changes
=> 
[#<GraphQL::Enterprise::Changeset::Change:0x00007fe983c8f388 @member=#<Types::BaseField Post.postLogo(...): NewLogo>, @type=:addition>,
 #<GraphQL::Enterprise::Changeset::Change:0x00007fe983c87f70 @member=#<Types::BaseField Post.postLogo: Logo>, @type=:removal>]
```
But it throws the below error when I try to call the query. I think the `argument` option is not supported in this case.
``` console
GraphQL Query Error!
#<Query::Context ...>> because the Ruby method params were incompatible with the GraphQL arguments:\n\n- `size_to_limit: [100, 100]` was given by GraphQL but not defined in the Ruby method. Add `size_to_limit:` to the method parameters.\n
```

Is there any better way to update the existing field, or is there something I'm missing here?

**Versions**

`graphql` version: 1.13.5
`graphql-enterprise` version: 1.1.4
`graphql-pro`: 1.22
`rails` version: 6.1
`ruby` version: 3.0.4

**Comment by rmosolgo** [comment]
Hi! Sorry for the trouble and thanks for the detailed write-up. 

Your _second_ approach was the one that I expect to work. From GraphQL-Ruby's perspective, there are two different `post_logo` fields: 

- The first `post_logo` field returns `LogoType` and accepts no arguments;
- The second `post_logo` field returns `NewLogoType` and accepts a `size_to_limit` argument.


The second `post_logo` field would be released in your upcoming changeset. 

Taking a look at the error message you posted: 

```
[...] `size_to_limit: [100, 100]` was given by GraphQL but not defined in the Ruby method. Add `size_to_limit:` to the method parameters.
```

It looks like the resolver or method for `post_logo` doesn't have a `size_to_limit:` argument yet, so GraphQL-Ruby can't successfully resolve that field. Could you please share the implementation for that field (method or resolver)? I bet if we add a `size_to_limit: nil` keyword argument to it, it will start working as expected.

**Comment by ashikajith** [comment]
Thanks for the response. And appreciate your time in helping me with this. Adding a nil check in the method definition fixed the issue. With the below changes, it worked like a charm. :tada: 

```ruby
  module Changesets
    class FixProfileAvatarFieldType < ::GraphQL::Enterprise::Changeset
      release "2022-09-21"

      modifies ::Types::Objects::AccountType do
        field :post_logo, ::Types::Objects::NewLogoType, null: true, resolver_method: :new_post_logo do
          argument :size_to_limit, ::Types::Enums::VariantSize,
                   description: "resize the image to fit these dimensions",
                   required: true
        end
      end
    end
  end
```
```ruby
# post_type.rb

class Types::Objects::PostType < BaseObject
  field :post_logo, ::Types::Objects::LogoType, null: true
  ...
  def post_logo
     Asset.find(object.logo_id, context_type: "Post")
  end
  
  def new_post_logo(size_to_limit: nil)
     PostLogoWrapper.new(object.new_logo, size: size_to_limit)
  end
end
```
Sorry for the trouble. I am happy to close this issue.

**Comment by rmosolgo** [comment]
Glad it worked for you! Thanks for sharing your solution. Please let me know if anything else comes up that I can help with 👍
