### ISSUE TITLE
Conditionally handle missing fields

### ISSUE THREAD

**Issue by cablett** [rmosolgo/graphql-ruby#4162]
Hi @rmosolgo ! Thanks for all your work on this project 🙌 as always.

**Is your feature request related to a problem? Please describe.**

In projects with zero-downtime or canary deployments, occasionally we can run into multi-version compatibility.

Consider the following example: 
1. A new field `:bar` is introduced on `FooType` and is released for Version 11.4.
2. A frontend page is served to a browser by a web node running 11.4, which contains an XHR request containing a GraphQL query with the new field `:bar`
3. Most of the time, it hits a backend node of the same version, but not always since the deployment is rolling. If the request is handled by a backend or API node that is running a previous version 11.3, a GraphQL validation error occurs and the entire query is aborted due to the one field being missing from the schema.
4. Developers have to do a lot of work to get around this constraint, so it's a nontrivial pain point.

**Describe the solution you'd like**

We have a few options here (depending on whether or not it adheres to GraphQL spec):

- conditionally handle missing fields in the way that we handle unauthorised fields. We can stub it as `nil` or we can raise a custom error and it's ultimately up to our implementation. We could perhaps leverage `validate_max_errors` to error out completely if there are more than that limit. Perhaps add the missing fields to `errors`?
- run the validation beforehand to determine what's missing and perhaps strip it out of the AST before it moves on?

I'm not sure if these go against the GraphQL spec - so please advise if there are any other ways you think this could be addressed.

I'm happy to collaborate on a PR if you think there's a solution at this level. 👍

**Describe alternatives you've considered**

- Using visibility somehow? e.g. I know we'll be releasing `:foo` soon so let's add it in now and simply return `nil`. Requires possibly more work from devs? :thinking: 
- Using a version in the header of requests. The load-balancer can potentially route requests with a version header to nodes that are labelled that version. I think this solution might be quite complex. I'm seeing if there's some solution here to explore.

Thank you in advance for your time!

**Comment by cablett** [comment]
I thought it would be nice to have something like:

```graphql
query {
  foo(id: "123") {
    title
    bar
  }
}
```

A node returning v11.3 would return


```
{
  "data": {
    "foo": {
      "title": "Fabulous Foo"
      "bar": nil
      }
    }
"errors": [
    {
      "message": "Field 'bar' doesn't exist on type 'Foo'",
      # etc etc etc
    ]
  }
}
```

A node running 11.4 would return:

```
{
  "data": {
    "foo": {
      "bar": {
        "title": "Fabulous Foo",
        "bar": "no problem 🤘"
        }
      }
    }
  }
}
```

Whether or not we would bother to return `bar: nil` or strip it out would depend on the best solution.

WDYT?

**Comment by rmosolgo** [comment]
My first impression is that I don't really want to add features to the gem that encourage people to build non-spec-compliant APIs. Often enough, what starts as a good idea for an edge case becomes a compatibility problem down the road. 

> Developers have to do a lot of work to get around this constraint

To be clear, are we talking about releasing the API changes first, and letting that deploy finish, then releasing the frontend changes? Considering how similar this is to Rails migrations, where first, you deploy and run the migrations, then release the Ruby code that uses migrations, it's not obvious to me that this _should_ constitute "a lot of work" -- shouldn't the developer build the feature locally, test it on staging, then (after review, QA, etc) split the code and release it to production in three steps: migrations, backend, frontend? Or, is there more more to it than this? 

In any case, if you want to build this functionality for your app, I think you could use the `.get_field` and `.fields` methods as described here: 

https://graphql-ruby.org/schema/dynamic_types.html#using-fieldscontext-and-get_fieldname-context

The difference being, you want to make sure that `nil` is never returned to GraphQL-Ruby. So you might implement them like this: 

```ruby 
class Types::BaseObject < GraphQL::Schema::Object 
  def self.fields(context)
    all_fields_hash = super
    all_fields_with_fallback_hash = Hash.new { |h, k|
      if k.start_with?("__") # don't replace introspection fields
        nil
      else
        h[k] = self.fallback_field
      end
    }
    all_fields_with_fallback_hash.merge!(all_fields_hash)
    # return a hash which has the fields that actually exist, but also
    # returns the fallback field when a non-existing field is looked up
    all_fields_with_fallback_hash
  end

  def self.get_field(field_name, context)
    real_field = super
    if real_field.nil? && !field_name.start_with?("__")
      # return the fallback field instead of `nil`
      self.fallback_field(name: field_name)
    else
      real_field
    end
  end

  def self.fallback_field(name:)
    # usually, you'd use the `field(...)` helper to make a field, but I think it should work to make one on-the-fly
    GraphQL::Schema::Field.new(
      owner: self,
      name: name,
      type: GraphQL::Types::Boolean, # can be anything, since it will resolve to nil
      fallback_value: nil,
    )
  end
end 
```

(In fact, you'd want to extract this into a module and mix it into your base object _and_ your base interface, since both those kinds of types have fields.) 

Here's a little script demonstrating this behavior: 

<details>
<summary> Handling missing fields with `nil`</summary>

<p>

```
require "bundler/inline"

gemfile do
  gem "graphql"
end

class BaseObject < GraphQL::Schema::Object
  def self.fields(context)
    all_fields_hash = super
    all_fields_with_fallback_hash = Hash.new { |h, k|
      if k.start_with?("__") # don't replace introspection fields
        nil
      else
        h[k] = self.fallback_field
      end
    }
    all_fields_with_fallback_hash.merge!(all_fields_hash)
    # return a hash which has the fields that actually exist, but also
    # returns the fallback field when a non-existing field is looked up
    all_fields_with_fallback_hash
  end

  def self.get_field(field_name, context)
    real_field = super
    if real_field.nil? && !field_name.start_with?("__")
      # return the fallback field instead of `nil`
      self.fallback_field(name: field_name)
    else
      real_field
    end
  end

  def self.fallback_field(name:)
    # usually, you'd use the `field(...)` helper to make a field, but I think it should work to make one on-the-fly
    GraphQL::Schema::Field.new(
      owner: self,
      name: name,
      type: GraphQL::Types::Boolean, # can be anything, since it will resolve to nil
      fallback_value: nil,
    )
  end
end


class Query < BaseObject
  field :real_value, Int

  def real_value
    100
  end
end


class Schema < GraphQL::Schema
  query(Query)
end


pp Schema.execute("{ realValue fakeValue }").to_h
# {"data"=>{"realValue"=>100, "fakeValue"=>nil}}

pp Schema.execute("{ __type(name: \"Query\") { fields { name } } }").to_h
# {"data"=>{"__type"=>{"fields"=>[{"name"=>"realValue"}]}}}
```

</p>
</details>

How about giving that approach a try?

**Comment by cablett** [comment]
Thank you for your reply @rmosolgo ! It's given me a lot to think about :+1: 

You're right that "a lot of work" is a bit wooley, but since our deployment is quite complex and we must also support deployments in some other frameworks and situations we don't control, we need to make the solution a bit more failsafe. I've been exploring that route first for that reason 👍 At the moment we release backend and then release the frontend in the following release. It's rather disruptive 😅

> My first impression is that I don't really want to add features to the gem that encourage people to build non-spec-compliant APIs. Often enough, what starts as a good idea for an edge case becomes a compatibility problem down the road.

You're absolutely right. I think while it's well-intentioned, these things can get out of control :thinking: 

I'll give this a go, thank you for taking the time to consider my request. Much appreciated!

**Comment by rmosolgo** [comment]
Please let me know if you run into trouble with that approach, but since I don't plan to work on this further, I'm going to close the issue.
