### ISSUE TITLE
Latest GitHub schema doesn't load

### ISSUE THREAD

**Issue by johntopleyons** [rmosolgo/graphql-ruby#4164]
**Describe the bug**

The `GraphQL::Client.load_schema` method expects a JSON schema to have a top-level `data` key. The latest [GitHub public schema.json](https://github.com/octokit/graphql-schema) doesn't have such a key.

**Versions**

`graphql` version: 2.0.13
`rails` (or other framework): N/A

**Steps to reproduce**

Download GitHub's `schema.json` from https://github.com/octokit/graphql-schema/blob/master/schema.json

```
require 'graphql/client'
require 'graphql/client/http'

schema = GraphQL::Client.load_schema(File.join(__dir__, '.', 'schema.json'))
```

**Expected behavior**

The schema should load without errors.

**Actual behavior**

```
irb(main):001:0> require 'graphql/client'
=> true
irb(main):002:0> require 'graphql/client/http'
=> true
irb(main):003:0> schema = GraphQL::Client.load_schema(File.join(__dir__, '.', 'schema.json'))
/usr/local/Cellar/ruby/3.1.1/lib/ruby/gems/2.5.0/gems/graphql-2.0.13/lib/graphql/schema/loader.rb:17:in `fetch': key not found: "data" (KeyError)
        from /usr/local/Cellar/ruby/3.1.1/lib/ruby/gems/2.5.0/gems/graphql-2.0.13/lib/graphql/schema/loader.rb:17:in `load'
        from /usr/local/Cellar/ruby/3.1.1/lib/ruby/gems/2.5.0/gems/graphql-2.0.13/lib/graphql/schema.rb:102:in `from_introspection'
        from /usr/local/Cellar/ruby/3.1.1/lib/ruby/gems/2.5.0/gems/graphql-client-0.18.0/lib/graphql/client.rb:52:in `load_schema'
        from /usr/local/Cellar/ruby/3.1.1/lib/ruby/gems/2.5.0/gems/graphql-client-0.18.0/lib/graphql/client.rb:57:in `load_schema'
        from /usr/local/Cellar/ruby/3.1.1/lib/ruby/gems/2.5.0/gems/graphql-client-0.18.0/lib/graphql/client.rb:55:in `load_schema'
        from (irb):3:in `<main>'                                                                             
        from /Users/johntopley/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
        from /Users/johntopley/.rbenv/versions/3.1.1/bin/irb:25:in `load'                                    
        from /Users/johntopley/.rbenv/versions/3.1.1/bin/irb:25:in `<main>'      
```                            

**Additional context**

I have confirmed that manually adding the top-level `data` key to the local copy of GitHub's `schema.json` enables the schema to load successfully.

**Comment by rmosolgo** [comment]
As far as graphql-ruby is concerned, `Schema.from_introspection` is made for initializing a `Schema` based on the result of the introspection query from a GraphQL API -- including the `"data"` key, as you noticed. 

I don't have plans to work further on it. If it stopped working, maybe the format of the `.json` file should be corrected or GraphQL-Client should be changed? Alternatively, if you want to change the implementation of `.from_introspection`, I'm open to supporting cases when `{ "data" => { ... } }` isn't present.
