### ISSUE TITLE
Instrumenters break relay connections

### ISSUE THREAD

**Issue by tmeasday** [rmosolgo/graphql-ruby#417]
Using the simple field instrumenter documented [here](https://rmosolgo.github.io/graphql-ruby/schema/instrumentation), `connection` fields lose their arguments and fail with

```
{"errors"=>[{"message"=>"Field 'people' doesn't accept argument 'first'", "locations"=>[{"line"=>1, "column"=>3}], "fields"=>["query", "people", "first"]}]}
```

I believe the reason is that this [line](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/relay/connection_field.rb#L34) is incompatible with `field.redefine` (i.e. it gets forgotten).

[This workaround](https://github.com/apollostack/optics-agent-ruby/commit/5311c3dc975880e6979998e1c91d3e4ecc867596) appears to work.

**Comment by rmosolgo** [comment]
😖 I was eyeing this dubious code for #411 but didn't dig deep enough. Let me add a test case for this and explore using `#dup` as the basis for `#redefine`, which will rule out any more errors like this one and others identified in #399.

**Comment by tmeasday** [comment]
Oh yeah, my terrible memory just completely failed to remind me about your comments from #399 which would have probably helped me figure this one out a bit quicker. 

Let me know if I can help out with some tests or something.

**Comment by rmosolgo** [comment]
Ugh, the problem with `#dup` is that, by default, the old and new objects share hashes (like `field.arguments` or `type.fields`) ... hmmm
