### ISSUE TITLE
Variable validation: respect validate_max_error limit in `1.13.*` version

### ISSUE THREAD

**Issue by stefanosx** [rmosolgo/graphql-ruby#4173]
Hello, I see that you have already released [this change](https://github.com/rmosolgo/graphql-ruby/pull/4137) in version `2.0.13`, is it possible to add this fix to `1.13.*` too?

**Comment by rmosolgo** [comment]
Sure thing -- I just released it in 1.13.16! Thanks for the improvement on that.
