### ISSUE TITLE
[PRO] Override only specific functions in a custom connection

### ISSUE THREAD

**Issue by davidr64** [rmosolgo/graphql-ruby#4182]
**Is your feature request related to a problem? Please describe.**

We have a specific resolver with long load times due to query complexity. We optimized the query for the data fetching which works well. However when we include the has_next_page on the request the resulting query `SELECT 1 AS one FROM .... LIMIT 1 OFFSET 20` is worse with the new version of the query than before. 

In our case we believe that for this specific query it is actually more performant to just select count(*) then subtract the offset and page size. Though some experimentation will have to be done and we will be consulting our DB Designer. We will want to be able to have control of the individual queries.

**Describe the solution you'd like**

We have begun looking at using the custom [Connection Wrapper](https://graphql-ruby.org/pagination/custom_connections#connection-wrapper) however we don't want to have to re-implement the #cursor_for, and #nodes functionality. Is there a way to continue using the default relay connection implementation for those fields?

**Describe alternatives you've considered**
I am considering duplicating the code from the library for those fields but would prefer to continue using the library implementation to capture any future improvements that might be made in these areas. 

Are we sure that generating a query like `SELECT 1 AS one FROM .... LIMIT 1 OFFSET 20` is generally the most performant way to figure out if there is another page?

**Additional context**

**Comment by davidr64** [comment]
Thanks for the detailed answer honestly I think the main thing I needed was to use GraphQL::Pagination::ActiveRecordRelationConnection as my base class instead of GraphQL::Pagination::Connection. Now I can update HasNextPage without having to implement the other functions. Thanks for also providing the implementation for that function. 

Ya I like the lookahead approach, are there other examples of using lookahead in the library code or code that isn't directly tied to a resolver? I think your assumption about count(*) is probably correct, though I am no DB expert.

**Comment by davidr64** [comment]
I have been reading over the ActiveRecordRelationConnection and RelationConnection to get a better understanding. I am wondering if you think I should specifically avoid overriding `relation_larger_than` as that seems to make the most sense to me. Perhaps it is related to my next question. I noticed you pass `sliced_nodes` into `relation_larger_than` in the default implementation of `has_next_page` but rather than using `relation` as the passed in value you reference `sliced_nodes` again on [line 14](https://github.com/rmosolgo/graphql-ruby/blob/ff484253cf3a3898fa9c05d12403d8b785d95f12/lib/graphql/pagination/active_record_relation_connection.rb#L14).

**Comment by rmosolgo** [comment]
It looks to me like overriding `relation_larger_than` should work fine  -- plus, you'll get the advantage of those early returns from `has_next_page` :+1:

> rather than using `relation` as the passed in value 

I bet that's a bug 😅  but maybe we've gotten away with it since `sliced_nodes` is the only value passed to that method.
