### ISSUE TITLE
Modularize Interpreter#run_all

### ISSUE THREAD

**Issue by DmitryTsepelev** [rmosolgo/graphql-ruby#4201]
**Is your feature request related to a problem? Please describe.**

I maintain https://github.com/DmitryTsepelev/graphql-ruby-persisted_queries. After the last update #4183 I had to fix the gem [this way](https://github.com/DmitryTsepelev/graphql-ruby-persisted_queries/pull/56/files#diff-f489c136acd8a2c601e123e873b678c885ea4808883de3148815d591ac9c9f3fR56). The problem is that I'd like to not patch methods by copying them 😀

**Describe the solution you'd like**

I'd like to add a way to change a logic of how query is resolved: right now it goes through queries and skips invalid ones, but I need a way to handle a specific case (when there is a persisted query hash coming, but there is no query).

Maybe it will be enough to just split that huge methods into smaller pieces as it was before. 

**Describe alternatives you've considered**

0. we can just keep things as is 🙂
1. we (I mean I) can fix just this exact case and wait for other cases to appear

**Comment by rmosolgo** [comment]
Hey, sorry about the trouble with this! I definitely want to support your use case properly. 

Have you considered query instrumentation (https://graphql-ruby.org/queries/instrumentation)? For example: 

```ruby 
module MissingPersistedQueryErrorInstrumentation 
  def self.before_query(query) 
    if query.persisted_query_not_found?
      query.context.errors.clear
      query.context.errors << GraphQL::ExecutionError.new("PersistedQueryNotFound")
    end 
  end 
end 

# ... 
class MySchema < GraphQL::Schema 
  instrument :query, MissingPersistedQueryErrorInstrumentation
end 
```


Looking at the persisted_queries source, you might need to manually try to fetch the persisted query in that instrumentation, too -- I don't think there's any guarantee that `prepare_ast { ... }` will have been _already_ called at that point. 

What do you think, want to give it a try?

**Comment by rmosolgo** [comment]
(Also, perhaps relevant to your interests, monkeypatching the runtime code will get worse before it gets better! 🙈 #4195)

**Comment by DmitryTsepelev** [comment]
Hey, I'll give instrumentation a shot!

**Comment by rmosolgo** [comment]
Please let me know if you have any trouble with it :+1:

**Comment by bbugh** [comment]
Thanks for this workaround. The change on that update broke Apollo Persisted Queries (previous request for APQ has some more context https://github.com/rmosolgo/graphql-ruby/issues/2719). 

In order for this to work for us, we also had to add `self.after_query` with the same code:

```ruby
module MissingPersistedQueryErrorInstrumentation 
  def self.before_query(query) 
    if query.persisted_query_not_found?
      query.context.errors.clear
      query.context.errors << GraphQL::ExecutionError.new("PersistedQueryNotFound")
    end
  end 

  def self.after_query(query) 
    if query.persisted_query_not_found?
      query.context.errors.clear
      query.context.errors << GraphQL::ExecutionError.new("PersistedQueryNotFound")
    end 
  end 
end 
```

We also had to make sure the `instrument` line was below the `use GraphQL::PersistedQueries` line:

```ruby
# ... 
class MySchema < GraphQL::Schema 
  use GraphQL::PersistedQueries, ... 
  instrument :query, MissingPersistedQueryErrorInstrumentation
end 
```
