### ISSUE TITLE
Add "bang"-style methods for expressing non-nullable types

### ISSUE THREAD

**Issue by amomchilov** [rmosolgo/graphql-ruby#4207]
**Is your feature request related to a problem? Please describe.**

The `field` DSL method has a required `null:` keyword argument. In my opinion this causes two issues:

1. Null is mentioned all over the place, and you just go noise-blind to it. It's hard to distinguish a nullable field in a sea of non-nullable fields (or vice versa).
2. It adds to the line length, which already typically have a fair bit of other params:
    * The field name (mandatory, obviously)
    * The field's type (which can be long, if it's a qualified constant of a resolver instead of a type)
    * A description (not strictly mandatory, but very common)
    * A `do` block for specifying arguments
    * etc.
    
    This often causes a pattern like:
    
    ```ruby
    field :my_field_foo, Resolvers::FieldFoo, null: false,
      description: "A foo field with some longish description ..."
    field :my_field_bar, GraphqlApi::Types::CustomScalars::DateTime,
      description: "A bar field with some longish description ..."
    field :my_field_baz, GraphqlApi::Types::ImageType, null: false, null: true,
      description: "A baz field with some longish description ..."
    ```
    
And this is just the simple case, there's 10s of other possible fields that are situationally added to fields, which blows up their length or line count.
    
    
**Describe the solution you'd like**

IMO this could be better expressed with some bang-methods like `field!` (implies `null: false`, for `argument!` it implies `required: true`, etc):
    
```ruby
field :my_field_foo, Resolvers::FieldFoo, description: "A foo field with some longish description ..."
field :my_field_bar, GraphqlApi::Types::CustomScalars::DateTime, description: "A bar field with some longish description ..."
field! :my_field_baz, GraphqlApi::Types::ImageType, description: "A baz field with some longish description ..."
```

* It's happens to be more concise overall, which isn't itself that important, but more critically...
* ...the nullability is easier to spot, since it's a consistent earlier position (that doesn't shift depending on the name/type/resolver) in the start of the expression, right near the name and type, and not lost among the `description:`, `connection:`, `method:`, etc.
* The meaning of `!` matches up perfectly with the GraphQL syntax for non-nullable type (`String!` vs `String`)

**Describe alternatives you've considered**

Just leave it as-is.

**Additional context**

Everything here could apply to other cases where types are described, like `argument`,  `type` (as in, the return type of resolvers/mutations), etc.

We've been using these in our codebase, and they'd been pretty convenient. If there's desire to have these, I'll gladly contribute a PR to implement them (just gauging interest here first)

**Comment by rmosolgo** [comment]
Personally, I'm not interested -- `null: true` is the default for fields, so you only ever need to add `null: false`. 

But, I'm glad to hear it's been working well for you, and if anyone wants this API in their application, it can be implemented in your base object class with: 

```ruby 
def field!(*args, **kwargs, &block) 
  kwargs[:null] = false 
  super 
end 
```

And likewise with `def argument!` in your base field and base input object class. 

If anyone else gives this approach a try and has a good experience, please leave a comment here -- I'm open to including it if it turns out to be popular.
