### ISSUE TITLE
Guide: Releasing Changesets - Version comparison

### ISSUE THREAD

**Issue by mroach** [rmosolgo/graphql-ruby#4210]
I'm considering upgrading to GraphQL Enterprise largely for the changeset feature. I've been looking over the docs to see how we'd use it for our needs. An aspect that's not totally clear to me is how the release version comparison is done.
In the documentation, stringified dates are used, e.g. `release "2021-06-01"`.

It states:
> The `release ...` configuration in the changeset will be compared to `context[:changeset_version]` to determine if the changeset applies to the current request

How is this comparison done? Is it purely using the `>` operator?

What I want to be clear about is that for example if a client wants to be bleeding edge and passes a release version of today's date, that all previous changesets would be applied because they're considered as being "before" it.

**Comment by bessey** [comment]
I'm not the author, but saw your Q while coming to post my own!

We are doing the same thing, and I have come to the conclusion through experience that yes, its just doing `>` string comparison. It just happens that ISO dates are lexicographically sortable. 

Certainly, the behaviour you mention does appear to happen in practice.

**Comment by rmosolgo** [comment]
To confirm (and clarify), yes, it's just a plain string comparison. Under the hood, it uses `>=`, for example, `context[:changeset_version] >=  release.version`. 

> all previous changesets would be applied because they're considered as being "before" it

Yes, exactly. In theory, the versioning of the API is like a timeline, with releases appearing as points along the line. Incoming requests can place _themselves_ on that line, too (even in the future 🤷 ), and see the API as it appears at that time, with all previous changesets applied and no future changesets applied.

**Comment by mroach** [comment]
Thanks for the clarification @rmosolgo and @bessey! Good to know exactly how it works, and using datestamps in that format thus seems like a perfectly sensible way to do it.
