### ISSUE TITLE
Repeated directives get dropped when parsing an SDL file

### ISSUE THREAD

**Issue by myronmarston** [rmosolgo/graphql-ruby#4216]
**Describe the bug**

When you have an SDL file with schema elements that have repeated directives, the graphql-ruby parser seems to drop all but the last directive on the floor.

**Versions**

`graphql` version: 2.0.14

**GraphQL schema**

See script below.

**GraphQL query**

N/A

**Steps to reproduce**

Create a `tmp/graphql_ruby_bug.rb` file with these contents:

``` ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "graphql", "2.0.14"
end

schema_sdl = <<~EOS
  directive @tag(name: String!) repeatable on ARGUMENT_DEFINITION | ENUM | ENUM_VALUE | FIELD_DEFINITION | INPUT_FIELD_DEFINITION | INPUT_OBJECT | INTERFACE | OBJECT | SCALAR | UNION

  type Query {
    something: Int @tag(name: "t1") @tag(name: "t2")
  }
EOS

require "graphql"

schema = GraphQL::Schema.from_definition(schema_sdl)

field = schema.types["Query"].fields["something"]
puts "Directives:"
puts field.directives.map { |dir| "#{dir.graphql_name} #{dir.arguments.inspect}" }

puts
puts "Full Schema:"
puts schema.to_definition
```

Run it to observe the bug:

``` 
$ ruby tmp/graphql_ruby_bug.rb
Directives:
tag #<GraphQL::Execution::Interpreter::Arguments @keyword_arguments={:name=>"t2"}>

Full Schema:
directive @tag(name: String!) repeatable on ARGUMENT_DEFINITION | ENUM | ENUM_VALUE | FIELD_DEFINITION | INPUT_FIELD_DEFINITION | INPUT_OBJECT | INTERFACE | OBJECT | SCALAR | UNION

type Query {
  something: Int @tag(name: "t2")
}
```

**Expected behavior**

Since the directive is defined as `repeatable`, I expect the graphql-ruby parser to preserve all copies of that directive on the schema element.

**Actual behavior**

As shown above, the parser only kept the last directive.

**Comment by rmosolgo** [comment]
Thanks for the detailed report! It turns out the SDL-to-Schema builder was still using a `{ Class => options }` hash for storing directives before creating types and fields. I've prepared an update in #4218
