### ISSUE TITLE
Can't use loads_{argument} when autoloading mutation arguments with an Input Object

### ISSUE THREAD

**Issue by presho-anna** [rmosolgo/graphql-ruby#4234]
We have a mutation which we are updating to use argument autoloading and authorizing. The argument uses an InputObject. We would like to utilize the `load_{argument}` function to override our `Schema.object_from_id` logic. I have tried implementing the `loads_{argument}` override in both the mutation and the input object class, but it gets skipped and goes straight to `object_from_id`.

I see that this override is only mentioned in the context of mutations, but would have expected it to work in conjunction with an Input Object.

**Versions**

`graphql` version: 1.13.5
`rails` (or other framework): 6.1.6.1

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok). Any custom extensions, etc?

```ruby
class BaseMutation < GraphQL::Schema::Mutation
    argument_class Types::BaseArgument
    field_class Types::BaseField
    object_class Types::BaseMutationPayload

    def input_object_class
      Types::BaseInputObject
    end
end
```

**GraphQL query**

```ruby
class someMutation < BaseMutation
    argument :input, [ID], someMutationInput, required: true
    
    def resolve(input:)
    end
end

class someMutationInput
    argument example_ids, [ID], loads: ExampleType, required: true
    
    def load_examples(ids)
    end
end
```

**Steps to reproduce**
Create an input object that auto loads related data using `loads:` in an argument, try to use the `loads_{argument}` override.

**Expected behavior**

The `loads_{argument}` api is used in place of `Schema.object_from_id`

**Actual behavior**

`Schema.object_from_id` is used instead

**Comment by rmosolgo** [comment]
Hi! Sorry for the trouble and thanks for the detailed report. It looks like Input Objects need to have _class methods_ for loading inputs, for example:

```ruby 
def self.load_examples(ids, context)
  # ... 
end 
```

Here's an example script that worked for me: 

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "graphql", "2.0.15"
end

class MySchema < GraphQL::Schema
  class Thing < GraphQL::Schema::Object
    field :name, String
  end

  class UpdateThingsInput < GraphQL::Schema::InputObject
    argument :thing_ids, [ID], loads: Thing

    def self.load_things(_value, _context)
      [
        { name: "Some Thing" },
        { name: "Another Thing"},
      ]
    end
  end

  class UpdateThings < GraphQL::Schema::Mutation
    argument :input, UpdateThingsInput
    field :things, [Thing]

    def resolve(input:)
      {
        things: input[:things]
      }
    end
  end

  class Mutation < GraphQL::Schema::Object
    field :update_things, mutation: UpdateThings
  end

  mutation(Mutation)
end

query_str = "mutation { updateThings(input: { thingIds: [1234, 567] }) { things { name } } }"
pp MySchema.execute(query_str).to_h
# {"data"=>
#   {"updateThings"=>
#     {"things"=>[{"name"=>"Some Thing"}, {"name"=>"Another Thing"}]}}}
```

Please let me know if that fix doesn't work for you!
