### ISSUE TITLE
Full JSON representation of Graphql Object

### ISSUE THREAD

**Issue by fameoflight** [rmosolgo/graphql-ruby#4236]
Any way I can automatically get a full JSON representation of Graphql Object without writing the full query by hand? 

This will come in handy for tests to ensure all the fields are working as expected.

**Comment by tchak** [comment]
There might be tools to build such a query based on introspection query result

**Comment by rmosolgo** [comment]
There's nothing built-in, but you could do it like this, assuming you can fetch an object by ID: 

```ruby 
def print_object_as_type(object, graphql_type)
  field_names = graphql_type.fields.keys 
  query_str = <<-GRAPHQL 
    query printObject($id: ID!) { 
      node(id: $id) { 
        ... on #{graphql_type.graphql_name} {
          #{field_names.join(" ")}
        }
      }
    }
    GRAPHQL 
    
    object_id = MySchema.id_from_object(object, graphql_type, {})
    result = MySchema.execute(query_str, variables: { id: object_id })
    # return just the object:
    result["data"]["node"]  
end 
```

Please let me know if you run into any trouble with it!
