### ISSUE TITLE
"Input invalid" validation error on single quote String input

### ISSUE THREAD

**Issue by FlXlT** [rmosolgo/graphql-ruby#4237]
**Describe the bug**

Using a single quote such as `"'test"`, `"te'st"` in a String GraphQL input results in the following
`"errors" => [{"error_key"=>"validation_error", "message"=>"Input invalid"}]`

I also found out it is not working with single quoted strings when using a double quote, such as `'"test'` or `'t"est'`.

**Versions**

`graphql` version: 2.0.15
`rails` (or other framework): 6.1.4.6
`graphql_playground-rails`: 2.1.0

**GraphQL schema**

```ruby
class CustomQuery < Queries::ResolverTypes::Query
  description 'List query results'
  argument :user_query, String, required: true
  type [Types::CustomType], null: false

  def resolve(query:)
    custom_result
  end
end
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
query {
  cbsSearchSuggestions(query: "'test") {
    customTypeColumn
  }
}
```

```json
{
  "data": { },
  "errors": [
    {
      "error_key": "validation_error",
      "message": "Input invalid"
    }
  ]
}
```

**Steps to reproduce**

1. Create a GraphQL argument with String as its type
2. Input a double quoted string with a single quote in it or a single quoted string with a double quote in it
3. See the validation error

**Expected behavior**

The string with single or double quotes are expected to pass as valid input.

**Comment by rmosolgo** [comment]
Hi! Sorry for the trouble and thanks for the report. I tried to replicate this issue in the following script: 

```ruby
require "bundler/inline"

gemfile do
  gem "graphql"
end

class MySchema < GraphQL::Schema
  class Query < GraphQL::Schema::Object
    field :echo, String do
      argument :input, String
    end

    def echo(input)
      input
    end
  end

  query(Query)
end

query_str = %|{ echo(input: "hello 'world") }|
puts query_str
pp MySchema.execute(query_str).to_h
```

But it seemed to work fine for me: 

```
$ ruby strings_test.rb
{ echo(input: "hello 'world") }
{"data"=>{"echo"=>"hello 'world"}}
```

So, it seems like the problem might be a bit more subtle. 

One thing that stands out to me is the `"error_key" => "validation_error"` in your example response. That key-value pair is not from GraphQL-Ruby. If you search your application for `error_key`, can you find any code that might be creating that key-value pair? Maybe it will lead to another source of this error.

**Comment by rmosolgo** [comment]
If you want to look into this further, please let me know if you can find any code in your app adding "error_key", and we'll see what else we can do!
