### ISSUE TITLE
Ability to dump schema via the Rake task with `specifiedByURL` included in the introspection query

### ISSUE THREAD

**Issue by bubba** [rmosolgo/graphql-ruby#4240]
**Is your feature request related to a problem? Please describe.**

Hi there, I’ve been happily crafting up my GraphQL API with graphql-ruby and it’s been great so far.

My client generates code based on the schema, and as a part of it it uses the `specifiedByURL` field on scalar types to determine what to generate for each one.

Currently `rails graphql:schema:json` doesn’t include the specifiedByURL fields in the output, since `include_specified_by_url` isn’t passed to `Introspection.query` in `schema.rb`:

```ruby
def as_json(only: nil, except: nil, context: {})
  execute(Introspection.query(include_deprecated_args: true), only: only, except: except, context: context).to_h
end
```

**Describe the solution you'd like**

Would it be possible to enable `include_specified_by_url`, and possibly the other fields? I understand that the default introspection query needs to not include any fancy fields for backwards compatibility with other servers in `graphql-client`, but if this is running against the latest and greatest `graphql-ruby` which supports it anyway, it should be fine to turn on right?

**Describe alternatives you've considered**

Maybe there could also be options passed to the task to enable certain introspection fields

**Comment by rmosolgo** [comment]
Hey, thanks for the suggestion, I agree this would be a nice improvement! In the meantime, you could override `def self..as_json` in your schema class to use the introspection query you prefer.
