### ISSUE TITLE
graphql-ruby allows scalar types in the Union

### ISSUE THREAD

**Issue by ojab** [rmosolgo/graphql-ruby#4243]
**Describe the bug**

I found kinda related issue https://github.com/rmosolgo/graphql-ruby/issues/3092 and it was proposed to use wrapper types, but
```ruby
module Types
  class XxUnionType < GraphQL::Schema::Union
    possible_types GraphQL::Types::Float, GraphQL::Types::String
  end
end
```
works and generates
```graphql
union XxUnion = Float | String
```
It probably shouldn't, because scalar types are not allowed in the unions by the spec (https://github.com/graphql/graphql-spec/issues/215)

**Versions**

`graphql` version: 2.0.15

**Comment by rmosolgo** [comment]
Oops! Agreed this should not be possible.
