### ISSUE TITLE
graphql-2.10.0 is still tagged in the repo

### ISSUE THREAD

**Issue by ojab** [rmosolgo/graphql-ruby#4244]
**Describe the bug**

>Oops, this version was accidentally released to RubyGems as "2.10.0". I yanked it. See 2.0.11 instead.
https://github.com/rmosolgo/graphql-ruby/releases/tag/v2.10.0

and it always confuses me to see 
![image](https://user-images.githubusercontent.com/153388/201350221-52c4873a-9355-4381-9ca9-d85f96f092d2.png)
in the repo. 

Could you please `git push --delete origin v2.10.0`?

**Comment by rmosolgo** [comment]
Oops! Sorry for the trouble and thanks for reporting this. I just deleted that tag, please let me know if you have any other issues with it.
