### ISSUE TITLE
Cannot get the value of `other_key` in a call to `context.dig(:current_arguments, :other_key)`

### ISSUE THREAD

**Issue by tsuchi84** [rmosolgo/graphql-ruby#4246]
Hi! I may have found a glitch, I'll report it.

**Describe the bug**

When I try to get a value with `context.dig(:current_arguments, :other_key)`, I seem to get the value of `:current_arguments` without getting the value of `:other_key`.

```ruby
class Extension < GraphQL::Schema::FieldExtension
  def apply
    field.argument :other_key, Integer, required: false
  end

  def after_resolve(object:, arguments:, context:, value:, memo:)
    value = context.dig(:current_arguments, :other_key)  # value is `GraphQL::Execution::Interpreter::Arguments`
    value.to_h # { other_key: 123 }
  end
end
```

If the first argument of `dig` is `RUNTIME_METADATA_KEYS`, the second and subsequent arguments seem to be ignored.

https://github.com/rmosolgo/graphql-ruby/blob/v2.0.15/lib/graphql/query/context.rb#L235-L238

( `thread_info.dig(key)` is `thread_info.dig(key, *other_keys)` correct? )
 
**Versions**

`graphql` version: 2.0.15
`rails` : 6.1.7
`ruby` : 2.7.6

**Comment by rmosolgo** [comment]
Derp -- thanks for the report, definitely a bug!
