### ISSUE TITLE
Directives on `schema` do not behave correctly in the SDL parser and printer

### ISSUE THREAD

**Issue by myronmarston** [rmosolgo/graphql-ruby#4250]
**Describe the bug**

There are multiple bugs in the area of the SDL parser and printer related to how directives on `schema` behave:

1. If I define a `schema` with directives on it, the SDL string produced by `GraphQL::Schema#to_definition` omits that part of my SDL entirely.
2. If I use `extend schema` to add directives to my schema, the SDL string produced by `GraphQL::Schema#to_definition` weirdly converts it to no longer use `extend`.
3. If I then try to parse the SDL string that `GraphQL::Schema#to_definition` produced, I get an error--in other words `GraphQL::Schema#to_definition` produces an SDL string that `GraphQL::Schema.from_definition` cannot itself parse!

**Versions**

`graphql` version: 2.0.15
`rails` (or other framework): n/a

**GraphQL schema**

See the examples below.

**GraphQL query**

N/A

**Steps to reproduce**

Put this in `graphql_ruby_bug1.rb`:

``` ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "graphql", "2.0.15"
end

require "graphql"

schema_sdl = <<~EOS
  directive @link(as: String, for: link__Purpose, import: [link__Import], url: String!) repeatable on SCHEMA

  scalar link__Import

  enum link__Purpose {
    EXECUTION
    SECURITY
  }

  schema
    @link(url: "https://specs.apollo.dev/federation/v2.0", import: ["@key", "@shareable"])
  { query: Query }

  type Query {
    something: Int
  }
EOS

puts GraphQL::Schema.from_definition(schema_sdl).to_definition
```

And put this in `graphql_ruby_bug2.rb`:

``` ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "graphql", "2.0.15"
end

require "graphql"

schema_sdl = <<~EOS
  directive @link(as: String, for: link__Purpose, import: [link__Import], url: String!) repeatable on SCHEMA

  scalar link__Import

  enum link__Purpose {
    EXECUTION
    SECURITY
  }

  extend schema @link(url: "https://specs.apollo.dev/federation/v2.0", import: ["@key", "@shareable"])

  type Query {
    something: Int
  }
EOS

dumped = GraphQL::Schema.from_definition(schema_sdl).to_definition
puts dumped

GraphQL::Schema.from_definition(dumped)
```

Run these scripts to reproduce the bugs.

**Expected behavior**

When both scripts are run, I expect it to print the SDL in a slightly reformatted form (e.g. different whitespace, re-order the schema elements, etc) but not to change the tokens themselves from the original input SDL.  In addition, I expect `GraphQL::Schema#to_definition` to only produce SDL strings that `GraphQL::Schema.from_definition` can itself parse.

**Actual behavior**

```
$ ruby graphql_ruby_bug1.rb
directive @link(as: String, for: link__Purpose, import: [link__Import], url: String!) repeatable on SCHEMA

type Query {
  something: Int
}

scalar link__Import

enum link__Purpose {
  EXECUTION
  SECURITY
}
```

Here the bug is that the `@link` directive I've attached to `schema` is nowhere to be found in the SDL output even though it was in my original SDL string.

```
$ ruby graphql_ruby_bug2.rb
schema
  @link(import: ["@key", "@shareable"], url: "https://specs.apollo.dev/federation/v2.0")

directive @link(as: String, for: link__Purpose, import: [link__Import], url: String!) repeatable on SCHEMA

type Query {
  something: Int
}

scalar link__Import

enum link__Purpose {
  EXECUTION
  SECURITY
}
Traceback (most recent call last):
        9: from graphql_ruby_bug2.rb:30:in `<main>'
        8: from /Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.15/lib/graphql/schema.rb:123:in `from_definition'
        7: from /Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.15/lib/graphql/schema/build_from_definition.rb:10:in `from_definition'
        6: from parser.y:480:in `parse'
        5: from parser.y:466:in `parse_document'
        4: from /Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.15/lib/graphql/tracing.rb:90:in `trace'
        3: from parser.y:470:in `block in parse_document'
        2: from (eval):3:in `do_parse'
        1: from (eval):3:in `_racc_do_parse_c'
parser.y:538:in `on_error': Parse error on "directive" (DIRECTIVE) at [4, 1] (GraphQL::ParseError)
```

Here it prints `schema @link(...)`, appearing to preserve the directive I've tried to add, but:

1. It dropped the `extend` keyword that was in my original SDL, which is unexpected.
2. The resulting SDL isn't parseable by `GraphQL::Schema.from_definition`, as shown by the exception.

**Comment by rmosolgo** [comment]
Thanks for the details on these bugs -- I'm sure there's a lot to improve here.

Under the hood, `extend` is implemented to modify the already-defined schema members, and it doesn't retain any record of which definitions came from which part of the SDL. So, as you found, it can't reliably produce the same `extend` arrangements. 

Likewise, I would expect the directives to be properly printed in the SDL. Here's the code that turns the schema into an AST (before the AST is stringified): 

https://github.com/rmosolgo/graphql-ruby/blob/e788218deafdee4250f1f7bd4146acff7d2db3b0/lib/graphql/language/document_from_schema_definition.rb#L259-L260

I wonder if `include_schema_node?` is wrongly returning `false` here (although I can see that it _does_ check for schema directives 🤔 ). 

Also, I guess it should insert directive nodes before the schema node -- I think that would help with parsing the SDL output. In any case, I agree that GraphQL-Ruby should be able to parse any SDL that it creates!
 

Regarding `extend`, that will be a pretty challenging addition, since there's currently nothing tracking that in the Ruby schema definition right now. Just in case there's another approach that would work for you, do you mind sharing how this has become a problem for you? (That is, what were you trying to do when you got hung up on it? Maybe pure AST manipulation would help in your case.)

**Comment by myronmarston** [comment]
> Just in case there's another approach that would work for you, do you mind sharing how this has become a problem for you?

Sure! Let me see if I can explain what we're doing without getting too far into the weeds...

We have an internal GraphQL-based framework that builds on the graphql gem.  That framework provides a schema definition API that generates multiple schema artifacts, one of which is a `schema.graphql` SDL file.  We later use that file in multiple ways:

* The framework's GraphQL server component reads the SDL file at boot time using `GraphQL::Schema.from_definition(sdl, default_resolve: ...)` in order to provide the GraphQL API.
* As part of our CI build, we also submit the SDL file into our federated Apollo gateway so that the GraphQL service can function as a subgraph in a larger Apollo-based supergraph.

Notably:

* To produce a nice "canonically formatted" SDL string, our schema definition API round-trips the SDL through the graphql gem (e.g. `GraphQL::Schema.from_definition(raw_sdl).to_definition`): that way we can leverage all the work that's gone in to the GraphQL gem to have it generate nicely formatted SDL strings (e.g. with field names in alphabetical order, etc).
* To submit our SDL into Apollo, we need to [extend the schema with a directive](https://www.apollographql.com/docs/federation/federation-2/moving-to-federation-2/#opt-in-to-federation-2) that opts us into Apollo federation V2. 

When I tried using the snippet that Apollo recommends:

``` graphql
extend schema
  @link(url: "https://specs.apollo.dev/federation/v2.0",
        import: ["@key", "@shareable"])
```

...I ran into the bug demonstrated with the second script: when we later try to parse the SDL we dumped, we get parse-time errors.

As a work around, I tried switching away from `extend` to this form:

``` graphql
  schema
    @link(url: "https://specs.apollo.dev/federation/v2.0", import: ["@key", "@shareable"])
  { query: Query }
```

...but then I ran into the bugs from the first script: my schema directive was nowhere to be found in the dumped SDL.

For now I'm working around these issues by maintaining two different SDL files, and adding the `schema @link(...)` snippet only to the one that gets submitted to Apollo--but I'd like to move in the direction of only having to maintain one schema file.

> Regarding `extend`, that will be a pretty challenging addition, since there's currently nothing tracking that in the Ruby schema definition right now.

Actually, I need to get this to work without `extend`.  I've been told by a coworker who works on some shared company GraphQL tooling that the graphql library they are using (a golang one, IIRC) doesn't yet support `extend schema` so I actually need to not have `extend` in the SDL.  I reported that just because it surprised me.  My mental model was that round-tripping my raw SDL string through your parser and printer would change formatting (e.g. whitespace, alphabetize field orderings, etc) but not remove tokens or do other things that might change the meaning of the SDL.  That's just my mental model though.  I think it can be argued that it "canonicalizes" the SDL string and that the form without `extend` is more "canonical".  By that interpretation, it would make sense that you don't preserve the `extend` keyword in the dumped SDL and I'm 100% ok with that.

**Comment by myronmarston** [comment]
👋 @rmosolgo I imagine this ticket has fallen off your radar.  I'd still love to see it fixed. Is it something I could help with?  I'm not sure what the fix would be but if you describe how you'd like to see this fixed I can take a stab at it.

**Comment by rmosolgo** [comment]
Sorry for the slow turn-around on this!

**Comment by myronmarston** [comment]
Thanks for tackling this! I'm looking forward to being able to use it in the next release :).
