### ISSUE TITLE
before_resolve & after_resolve 

### ISSUE THREAD

**Issue by danlo** [rmosolgo/graphql-ruby#4257]
I'm changing all of our error messages from a string as such to returning a ruby Hash (.to_json).  However, I'd like to have some ability to control over what happens before and after.

```ruby
def resolve
   { errors: [ 'made up error' ] }
end
```

**Describe the solution you'd like**

I would like to be able to create the following kind of code
```ruby
module ErrorChecking
  extend ActiveSupport::Concern
  
  included do
    after_save do | doc | 
      next unless doc.key?(:error)

      doc[:errors].map! { | error | 
        if error.is_a?(String)
          { message: error, extensions: { ... } }
        else
          error
        end
      end
    end
  end
end

class Mutations::MyMutation < Mutations::BaseMutation
  include ErrorChecking

  def resolve
    return { errors: [ 'ops' ] }
  end
end
```

**Describe alternatives you've considered**

I thought about overloading resolve, that magic felt bad... I then thought about doing this
```
def resolve
  before_action
  my_resolve
  after_action
end

def my_resolve
end
```

This seamed a bit counter productive to the community given ActiveModel's:: Before/After call backs and ruby's natural object traits ( heresy)

**Comment by rmosolgo** [comment]
How about using `prepend`, for example: 

```ruby 
module ErrorChecking 
  def resolve(*args, **kwargs)
    doc = super # call the mutation's resolve method
    
    if doc.key?(:errors)
      # if the result had errors, decorate them
      doc[:errors].map! do |error| 
        if error.is_a?(String)
          { message: error, extensions: { ... } }
        else
          error
        end
      end
    end 

    # return the original result, perhaps modified above
    doc 
  end 
end 


# ... 

class Mutations::MyMutation < Mutations::BaseMutation
  # Add error checking
  prepend ErrorChecking

  def resolve
    return { errors: [ 'oops' ] }
  end
end
```

If you don't want to use plain Ruby, you could also use [Field extensions](https://graphql-ruby.org/type_definitions/field_extensions.html). You could use a field extension's `after_resolve` method to modify the original return value, then add that extension by calling `extension(...)` inside your resolver or mutation classes. 

Let me know if you try one of those approaches and run into any trouble!
