### ISSUE TITLE
Pre-compile query?

### ISSUE THREAD

**Issue by danlo** [rmosolgo/graphql-ruby#4258]
I was looking at our queries and I was thinking that a lot of this is pretty repetitive

```
query = "query($variables ) { .... }"
MySchema.execute(query, variables: variables, context: context)
```

it would be great to pre-compile these queries that are used quite often... 

**Describe the solution you'd like**

I thought code like this would be useful.

```
query = "query($variables ) { .... }"

MySchema.cached_queries = {
   'my_query' => { 
      used: 1
      last_used: Time.now,
      schema: '...'
   }
}

MySchema.execute(query, variables: variables, context: context, name: 'my_query')
# if name: 'my_query' is present, then the author is guarrenting that there query is re-usable
# MySchema.execute would save the cached query parsing/validation in MySchema.cached_queries with the following hash
  # key => String: name provided by user
  # value => Hash 
    # used -> numbers of times this item was used
    # last_used: (if we ever need to clear it out)
    # schema: after GraphQL-ruby was done parsing it.
```

**Comment by rmosolgo** [comment]
Hi! I don't know of anything like this and I don't have plans to add it, but in case you'd like inspiration in exploring the possibility, here are a few different cache-related projects for GraphQL-Ruby: 


- https://github.com/DmitryTsepelev/graphql-ruby-fragment_cache
- https://github.com/DmitryTsepelev/graphql-ruby-persisted_queries
- https://github.com/stackshareio/graphql-cache (inactive)
- https://graphql-ruby.org/operation_store/overview.html
- https://gist.github.com/rmosolgo/9d77fa2742d2734321d41432a9674c45 (works with OperationStore listed above, but could be adapted to use queries from Ruby, instead.) 
- https://graphql-ruby.org/object_cache/overview.html

I hope those help!
