### ISSUE TITLE
Standalone field definition should not require return object's connection_type

### ISSUE THREAD

**Issue by dleequri** [rmosolgo/graphql-ruby#426]
In the field definition it would be great if I could declare  `type types[Object]` instead `type Object.connection_type`.  The reason is because `connection` transforms my existing field to a `GraphQL::Relay::ConnectionField` so I should be able to define my field without knowledge of connections.

Example in my object type definition I have:
`connection :posts, Post.connection_type, field: FetchPosts`

and in a separate file I'm required to declare `type Post.connection_type`
```
FetchPosts = GraphQL::Field.define do
  type Post.connection_type
  resolve ...
end
```
instead of `type types[Post]`

**Comment by rmosolgo** [comment]
That's a very good point! `connection` should be all-or-nothing, but right now it only does "half" the job. 

I will keep this in mind. I would like to make `connection` more predictable in the future, avoiding bugs like #422 and #419, where the misdirection of connection "helpers" surprises people. 

Probably not in 1.3.0, but maybe in the next release I will start improving this!

**Comment by rmosolgo** [comment]
There is no `connection` helper anymore, instead, the default is to infer connection behavior from types names ending in `*Connection`
