### ISSUE TITLE
Unauthorized Objects in Arguments of GraphQL Input Objects Nullify Entire Mutation

### ISSUE THREAD

**Issue by mintyfresh** [rmosolgo/graphql-ruby#4260]
**Describe the bug**

When using `loads: Type` on arguments in GraphQL input objects, unauthorized objects will nullify the entire mutation field, rather than the just the one argument or input object.

**Versions**

`graphql` version: 2.0.15
`rails` version: 7.0.4

**GraphQL schema**

Sample schema:

```ruby
class Types::ProductType < GraphQL::Schema::Object
  field :id, ID, null: false

  def self.authorized?(object, context)
    false # treat all products as unauthorized for simplicity
  end
end

class Types::CartAddItemInputType < GraphQL::Schema::Object
  argument :product_id, ID, required: true, loads: Types::ProductType
  argument :quantity, Integer, required: true

  def self.load_product(product_id, context)
    ::Product.find(product_id) # Load an ActiveRecord model by ID
  end
end

class Mutations::CartAddItem < GraphQL::Schema::Mutation
  argument :input, Types::CartAddItemInputType, required: true

  field :success, Boolean, null: false

  def resolve(input:)
    { success: true } # this won't be reached
  end
end

class Types::MutationType < GraphQL::Schema::Object
  field :cart_add_item, mutation: Mutations::CartAddItem
end

class ApplicationSchema < GraphQL::Schema
  mutation MutationType

  def self.resolve_type(_type, object, _context)
    "Types::#{object.class.name}Type".constantize
  end
end
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
mutation {
  cartAddItem(input: {
    productId: 1,
    quantity:  1
  }) {
    success
  }
}
```

```json
{
  "data": {
    "cartAddItem": null
  }
}
```

The entire mutation field (`cartAddItem`) comes back as `null`, `Mutations::CartAddItem#resolve` is not called, and no errors are raised or returned.

**Steps to reproduce**

1. Define an input object with an argument that `loads:` a type
2. Define an authorization hook on the loaded type which return false

**Expected behavior**

In the above example, I would expect that `CartAddItemInput.product` argument would be nullified, and thereby an error would be thrown as the argument is marked required. (The issue occurs regardless of whether the argument is marked as required or not, however.)

**Actual behavior**

The mutation resolver is never called and the entire mutation field comes back as null.

**Comment by rmosolgo** [comment]
Hi! Thanks for the detailed report and sorry for the surprise. Now that I look, I see the question, "what happens if the argument value fails authorization?" isn't answered in the docs. I'd've expected to find that in one of these places: 

- https://graphql-ruby.org/mutations/mutation_authorization.html#loading-and-authorizing-objects
- https://graphql-ruby.org/authorization/authorization#argument-authorization

But it's not described. 

However, halting execution _is_ the intended behavior, for example: 

https://github.com/rmosolgo/graphql-ruby/blob/7cf0361a3cc080d18b4c82aee6dbf67447c79b4d/spec/graphql/schema/argument_spec.rb#L315-L323

https://github.com/rmosolgo/graphql-ruby/blob/7cf0361a3cc080d18b4c82aee6dbf67447c79b4d/spec/graphql/authorization_spec.rb#L722-L728

So, I think the best fix here is to update the docs linked above, and, if you want to _ignore_ provided values in your application, you could either: 

- Put the logic for that in `def resolve`, deleting arguments that don't pass a check; 
- Or, use `prepare` to replace values with `nil` if they don't pass a check ([doc](https://graphql-ruby.org/fields/arguments.html#preprocessing)). 


I'll keep this open until I update those docs accordingly. In the meantime, please let me know if you run into trouble trying the approaches above!

**Comment by mintyfresh** [comment]
@rmosolgo 
Putting logic into the `resolve` method of the mutation is highly limiting, especially when a given input object is either deeply nested into a data structure, appears in a list, or is used in multiple mutations (as is the case in my actual scenario).
Using `prepare` also doesn't adequately address this as it requires manually calling out to the `.authorized?` method of the corresponding GraphQL type, which is far less than optimal.

Would it not make sense to provide an `unauthorized_argument` hook, similar to the field and counterpart hooks that already exist? The default implementation could bubble-up the error to be consistent with existing behaviour, but would allow for more fine-grained logic to handle these cases.

Also, halting execution without reporting any error is a really bizarre behaviour. The entire mutation field is nulled out without any indication to either the client or the developer as to what happened.
No indication of which argument failed authorization, no indication that an argument even failed authorization.

In the linked examples, the field being nullified is in a query with the argument declared directly on the field. While still unintuitive behaviour, at least the lack of error or explanation can be rationalized.
However, this behaviour becomes much more problematic when the arugment failing authorization is nested 3 levels deep in an input object and is being passed as an input to a mutation.

**Comment by rmosolgo** [comment]
> provide an `unauthorized_argument` hook

Yeah, agreed that'd be a nice improvement. I took a quick look at where this would have to be called: 

https://github.com/rmosolgo/graphql-ruby/blob/c9ae52324454e22a5e3b08a214467fc0bf8ea0b0/lib/graphql/schema/resolver.rb#L166-L172

https://github.com/rmosolgo/graphql-ruby/blob/c9ae52324454e22a5e3b08a214467fc0bf8ea0b0/lib/graphql/schema/input_object.rb#L61-L66


I think each of those would have to be included to use the new `.unauthorized_argument` hook which works the same way as [`.unauthorized_field`](https://graphql-ruby.org/api-doc/2.0.15/GraphQL/Schema#unauthorized_field-class_method).

**Comment by mrdaniellewis** [comment]
The way this works is quite counter intuitive compared to fields and objects where you just get nils returned.

The result is using `authorized?` on an argument has a very similar practical effect to using `visible?`expect you get better errors with `visible?`.  (At least for my application, could be quite different for other setups)

I've ended up overriding the private method `prepare_value` so my authorisation check can nullify the value and I can keep using `prepare` normally.

**Comment by gregawoods** [comment]
I ran into this today and would very much benefit from a `unauthorized_argument` hook.
