### ISSUE TITLE
Polymorphic dataloader

### ISSUE THREAD

**Issue by jstrojil** [rmosolgo/graphql-ruby#4261]
**Is your feature request related to a problem? Please describe.**
Currently, dataloaders for polymorphic objects are not supported. This leads to N+1s.

**Describe the solution you'd like**
Something like, very open to a better solution
```
module Sources
  class PolymorphicActiveRecordObject < GraphQL::Dataloader::Source
    # rubocop:disable Lint/MissingSuper
    # There is no super to call in `GraphQL::Dataloader::Source`
    def initialize(model_whitelist: [])
      raise ArgumentError, 'You need to explicitly whitelist allowed models' if model_whitelist.empty?

      @model_whitelist = model_whitelist
    end
    # rubocop:enable Lint/MissingSuper

    attr_reader :model_whitelist

    def fetch(polymorphic_objects)
      models_map = {}
      lookup_map = {}

      polymorphic_objects.each do |polymorphic_object|
        models_map[polymorphic_object[:type]] ||= []
        models_map[polymorphic_object[:type]] << polymorphic_object

        lookup_map[lookup_key(polymorphic_object)] = polymorphic_object
      end

      records = {}

      (models_map.keys & @model_whitelist.map(&:to_s)).each do |model|
        # collect ids from this specific model
        model_ids = models_map[model].pluck(:id)

        # query the model and index results
        model.constantize.where({ id: model_ids }).each do |record|
          records[lookup_key({ id: record.id, type: model })] = record
        end
      end

      lookup_map.map { |key, _value| records[key] }
    end

    private

    def lookup_key(polymorphic_object)
      "#{polymorphic_object[:id]}-#{polymorphic_object[:type]}"
    end
  end
end

```
Return N queries for N business model types.

Thank you :)

**Comment by jstrojil** [comment]
@rmosolgo That is correct, should be fully functional. 
We just wanted to share this code and maybe include it in the graphql-ruby gem so other people can use it as well. 

I will leave the decision up to you - include it or simply drop it :)

Thanks!

**Comment by rmosolgo** [comment]
Great, thanks for sharing! I don't have any Source implementations in the library since application needs vary, but I'll keep this in mind and direct people here if I hear any questions about a situation like this.

**Comment by fedefa** [comment]
@jstrojil can you give us an example of usage? Also, did you check it using rails preloader? I want to understand the problem. Thank you!!

**Comment by jstrojil** [comment]
```
module Types
  class DocumentAutocompleteType < BaseObject
    field :id, ID, null: false
    field :document, Types::DocumentType

    def id
      [object.id, object.type].join(',')
    end

    def document
      dataloader.with(Sources::PolymorphicObjectLoader,
                      model_whitelist: [Invoice, Reminder, Agreement])
        .load(id: object.document_object_id, type: object.document_object_type)
    end
  end
end

```

If you have a query that returns multiple polymorphic types as an association, you need to preload it to avoid N+1s. In my case, the query `document_object` result can come from 3 different tables so that's why I am using the polymorphic dataloader.
