### ISSUE TITLE
Allow conditional introspection

### ISSUE THREAD

**Issue by sporto** [rmosolgo/graphql-ruby#4262]
**Is your feature request related to a problem? Please describe.**

We want to disable instrospection based on the current user. So in the controller we would like to have something like

```
def graphql
  if !current_user.super_admin? && Rails.env.production?
      Schema.disable_introspection_entry_points
  end
  ...
end
```

But `disable_introspection_entry_points` cannot be easily reverted. 

**Describe the solution you'd like**

Add some way to disable this conditionally

```
allow_instrospection = ...
MySchema.execute(query_string, context: context, allow_instrospection: allow_instrospection)
```

Thanks

**Comment by justisb** [comment]
I needed to perform this conditional authorization for our application as well, as we only want admin users to be able to access the full schema/field introspection in production, and conditionally build docs for GraphiQL accordingly.

I ended up using the custom introspection system to extend the existing SchemaType and FieldType classes but with authorization built into each field resolution.

e.x.:
```
class FooSchema < GraphQL::Schema
  introspection FooIntrospection
end
```

```
module FooIntrospection
  module Authorizable
    private

    def authorize_introspection!
      # Perform your custom authorization logic based on the instance `context`
      # and raise an error on failure-
      # then have your GraphQLController catch the error and respond with a 403
    end
  end

  class SchemaType < GraphQL::Introspection::SchemaType
    include Authorizable

    def types
      authorize_introspection!

      super
    end

    def query_type
      authorize_introspection!

      super
    end

    def mutation_type
      authorize_introspection!

      super
    end

    def subscription_type
      authorize_introspection!

      super
    end

    def directives
      authorize_introspection!

      super
    end
  end

  class FieldType < GraphQL::Introspection::FieldType
    include Authorizable

    def name
      authorize_introspection!

      object.name
    end

    def description
      authorize_introspection!

      object.description
    end

    def args(...)
      authorize_introspection!

      super
    end

    def type
      authorize_introspection!

      object.type
    end

    def is_deprecated
      authorize_introspection!

      super
    end

    def deprecation_reason
      authorize_introspection!

      object.deprecation_reason
    end
  end
end

```

I think ideally the introspection type fields would use the same policy extensions as the rest of the application's GQL types. However, that seemed even more complicated to implement, so manually overriding each field seemed like a straightforward solution for now.

@rmosolgo I'd be interested to know if this is similar to what you had in mind by using custom introspection system, or if you see any major issues with this kind of implementation and/or clear areas for improvement?

Perhaps it'd simplify things if we could make the default `GraphQL::Introspection::FieldType` etc inherit from our custom `field_class` and run any field extensions?

**Comment by rmosolgo** [comment]
Here's an approach for implementing something _like_ this using [custom introspection](https://graphql-ruby.org/schema/introspection#customizing-introspection): https://gist.github.com/rmosolgo/bd885348da2e39615b0ac55f369ce44c
