### ISSUE TITLE
Apollo PusherLink does not pass through initial response

### ISSUE THREAD

**Issue by Ataraxic** [rmosolgo/graphql-ruby#4276]
**Describe the bug**

This is an issue with the initial subscription response using Apollo, Pusher, graphql-ruby, GraphQL::Pro::PusherSubscriptions. 

When I subscribe, I believe I am allowed to return a response as documented in this [graphql-ruby PR](https://github.com/rmosolgo/graphql-ruby/issues/1910), and [graphql-ruby docs](https://graphql-ruby.org/subscriptions/subscription_classes#initial-subscription-with-subscribe). 

I do not receive this initial response when using Apollo's `useSubscription`

I believe the issue is inside of the `PusherLink` component. Based on my reading of the code, when `PusherLink#request` is called we check to see if the headers contain the `X-Subscription-ID`. This is used to subscribe to the pusher channel. If we do not detect a subscription ID we just call `observer.next(data)` and then complete. I believe we still need to call `observer.next(data)` when we initially subscribe to the pusher channel so that the initial response data is not swallowed up. 

**Versions**

`graphql-ruby` version: 1.23.1
`rails` (or other framework): Rails 7
`@apollo/client`: 3.6.5
`graphql-ruby-client`: 1.10.7

**GraphQL schema**
n/a

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
subscription AsyncTaskProgress($id: ID!) {
  asyncTaskProgress(id: $id) {
    asyncTask {
       id
       status
    }
  }
}
```

**Steps to reproduce**

example
```javascript
function SomeReactComponent({ id }) {
  const { data, loading, ...rest } = useSubscription(ASYNC_TASK_PROGRESS, { variables: { id } })

  console.log(data, loading, rest);

  return null;
}
```
1. Use Apollo Client and set it up using graphql-pro and pusher as described in the docs [here](https://graphql-ruby.org/subscriptions/pusher_implementation.html) and [here](https://graphql-ruby.org/javascript_client/apollo_subscriptions)
2. Subscribe and send back an initial response
3. Inspect network tab and see that the HTTP Post to register subscription returns a response with data. (I can see the response to the HTTP Post that subscribes in my network tab).
4. Verify using console that no data is ever received and printed. 

**Expected behavior**

1. I expect that the variable named data should contain the response body of the HTTP post that initiated the subscription. 
2. It is initially undefined in my example code when the subscription is first initiated but should become defined one the response is received and processed by the apollo links.

**Actual behavior**

1. data is undefined

**Comment by rmosolgo** [comment]
Hi -- sorry for the slow response on this! I agree it should work the way you expect. I'll take a look soon and follow up here.

**Comment by Ataraxic** [comment]
No worries, happy holidays, and thanks for following up! 🎉

**Comment by rmosolgo** [comment]
I released a patch to pass along the initial response in graphql-ruby-client 1.11.4. Please give it a try and let me know if you run into any trouble with it!
