### ISSUE TITLE
Documentation includes broken/compromised links

### ISSUE THREAD

**Issue by wiktor-td** [rmosolgo/graphql-ruby#4284]
The file https://github.com/rmosolgo/graphql-ruby/blob/master/guides/related_projects.md includes various urls to [http://mgiroux.me](https://example.com) (link is to examle.com on purpose for security). This domain seems compromised and redirects readers to scammy looking pages. Please take care when investigating as these link look like they could be potentially harmful.

Running safe browsing reports doesn't indicate issues, but the content is definitely not there any more.

https://transparencyreport.google.com/safe-browsing/search?url=http:%2F%2Fmgiroux.me%2F2015%2Fuploading-files-using-relay-with-rails%2F
https://www.virustotal.com/gui/url/e5a8881b21d5a3b8b8b1a7f480de76edc31014db288ac3ca88846db5f9ed6cb9

Working Web Archive links:

* https://web.archive.org/web/20200208101346/http://mgiroux.me/2015/getting-started-with-rails-graphql-relay/
* https://web.archive.org/web/20200221012123/http://mgiroux.me/2015/uploading-files-using-relay-with-rails/
* https://web.archive.org/web/20180303163826/http://mgiroux.me/2016/journey-into-graphql-ruby-query-execution/

**Comment by rmosolgo** [comment]
Yikes! Thanks for reporting these. Since those blog posts reference now-removed GraphQL-Ruby features, I decided to remove them entirely (c9f8aadf4)
