### ISSUE TITLE
Top level modules are fairly generic, can we use something more specific?

### ISSUE THREAD

**Issue by ioquatix** [rmosolgo/graphql-ruby#4287]
Top level module names like "Types" are fairly generic and could clash with gems of the same name. e.g. I use a gem called "types".

Why not change it from:

```ruby
# app/graphql/types/post_type.rb
module Types
```
to

```ruby
# app/graphql/types/post_type.rb
module GraphQL::Types
```

is that possible?

**Comment by rmosolgo** [comment]
Hey! Sure, the Ruby constants you use for your types is totally up to you -- the gem doesn't require anything particular there. (Although `GraphQL::Types` will be a conflict, too 😅 https://github.com/rmosolgo/graphql-ruby/blob/ba27e9a20436bf639116231839512271b4b60c5f/lib/graphql/types/string.rb#L3-L4) 

Let me know if you run into any trouble using custom namespaces in your app!

**Comment by ioquatix** [comment]
The automatic generation of code uses those as defaults, what about changing it?

As mentioned, I'm the author of a gem called "types" so this clashes.

https://rubygems.org/gems/types
