### ISSUE TITLE
Allow ability to skip unauthorized objects

### ISSUE THREAD

**Issue by AlexaCampusano** [rmosolgo/graphql-ruby#4301]
**Is your feature request related to a problem? Please describe.**

I have the following scenario in which I have a connection that returns a list of items and one of the items' object fail authorization. The implementation of the _unauthorized_object_ hook returns an exception because returning nil would break non-nullable fields/connections.

Right now, returning nil (which is the default) and raising an exception are the only two ways (that I'm aware of) of implementing the _unauthorized_object_ hook. And as mentioned before nil does not work if the object is non-nullable, and the exception may be too aggressive.

**Describe the solution you'd like**

Have available a way in which we could skip unauthorized objects and not return them as part of the connection/field, but still return the ones that did pass authorization. And in the case of regular fields, return the default value if it fails authorization.

- Is this possible?
- Is there something available now that fits this request?

**Comment by rmosolgo** [comment]
For filtering connections so that unauthorized items are not included, GraphQL-Ruby has "scoping" (doc: https://graphql-ruby.org/authorization/scoping.html). Does that look like it would work in your case?

**Comment by rmosolgo** [comment]
Let me know if you give scoping a try and run into any trouble!
