### ISSUE TITLE
As of 1.13.7 parsing an ISO8601DateTime without seconds fails

### ISSUE THREAD

**Issue by markijbema** [rmosolgo/graphql-ruby#4302]
**Describe the bug**

parsing an ISO8601DateTime without seconds fails

**Versions**

`graphql` version: 1.13.7
As of this version it will not parse, whereas before this it would parse incorrectly. Change was made in https://github.com/rmosolgo/graphql-ruby/pull/3862

**Steps to reproduce**

```
irb> GraphQL::Types::ISO8601DateTime.coerce_input "2023-01-19T08:01" , nil
=> nil
```

**Expected behavior**

```
irb> GraphQL::Types::ISO8601DateTime.coerce_input "2023-01-19T08:01" , nil
=> 2023-01-19 08:01:00 +0000
```

(I'd expect this as ISO8601 does not require seconds)

**Actual behavior**

```
irb> GraphQL::Types::ISO8601DateTime.coerce_input "2023-01-19T08:01" , nil
=> nil
```

If you agree that this is erroneous I'd be willing to create a PR (but I thought I'd check first to be sure that this is unwanted behaviour)

**Comment by rmosolgo** [comment]
Hi! Thanks for the detailed writeup. I don't plan to revert the changes in #3862, but for compatibility, you could add a scalar to your application that behaves just the same as the built-in one from previous GraphQL-Ruby versions. For example: 


```ruby
# app/graphql/types/iso_8601_date_time_with_zeroing.rb
class Types::Iso8691DateTimeWithZeroing < GraphQL::Types::ISO8691DateTime 
  # This custom scalar is for backwards compatibility, 
  # see https://github.com/rmosolgo/graphql-ruby/issues/4302
  graphql_name "ISO8691DateTime"
  
  def self.coerce_input(str_value, _ctx) 
    Time.iso8601(str_value) 
  rescue ArgumentError, TypeError 
    # Warning: in this branch, any hours or minutes in `str_value` will be silently zeroed out
    begin 
      Date.iso8601(str_value).to_time 
    rescue ArgumentError, TypeError 
      # Invalid input 
      nil 
    end 
  end 
end 
```


Then, update references of `GraphQL::Types::ISO8601DateTime` to your own custom one. 

How does that approach sound to you?

**Comment by markijbema** [comment]
Sure, I already did that, but since this was a fix in a patch release I assumed it was not intended to break consumers. And because I don't quite understand the current, fix, I was proposing a different one.

I think the old zeroeing out behaviour is clearly wrong, and I agree the your pull-request should not be converted, but I don't understand why the format "2023-01-19T08:01" should be refused, as far as I understand it is a valid ISO8601DateTime?

If you do think it's better to only support a subset of ISO8601DateTime while coercing, then maybe it would be better to expand the documentation to make this clear? For context, it took me quite a while to figure out what went wrong in our application, as we were sending valid strings and they suddenly stopped working when upgrading
