### ISSUE TITLE
Method to access the directive arguments passed to a query asides ast_node?

### ISSUE THREAD

**Issue by Tripple-A** [rmosolgo/graphql-ruby#4331]
**Bug Description**

I'm trying to access the directives and their argument values if provided, but no method within the directive is being called during execution

Version: 2.0.14

```ruby
class Directive < GraphQL::Schema::Member
  class DataSource < GraphQL::Schema::Directive
      locations(FIELD_DEFINITION, FIELD)
      argument :value, String, required: false
      description 'A data source indicator'

    def resolve(obj, args, ctx)
        byebug
    end
 end
end


def create_fields(query)
  query.field("MyConnection", connection_type, connection: true, null: false) do |field|
     field.directive(Directive::DataSource)
    # field.arguments are also created here
  end
end
```
        
How does one create custom directives and have access to the values provided within a query. The second question would be if there is a means of identifying when a directive is referenced in a query and when it is not, can this only be realized via ast nodes?.

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
query {
  products @dataSource { 
       nodes {
         id
        }   
     }
}
```

```json
{
  "data": {
    "products": […]
  }
}
```

**Steps to reproduce**

- Create a custom directive
- Add within it a `resolve` method
- Add it to a field using `field.directive(Directive)`
- Set the locations as FIELD and FIELD_DEFINITION
- Reference this directive in a query

**Expected behavior**

`.resolve` should be called.

**Actual behavior**
The query is executed with no breakpoint.

**Comment by rmosolgo** [comment]
> can this only be realized via ast nodes


Yes, it can only be accessed that way. For example, you'd add `extras: [:ast_node]` to the field definition, then handle `ast_node:` in your field method. Here's an example how it might work: 

```ruby
require "bundler/inline"

gemfile do
  gem "graphql", "2.0.16"
end

class MySchema < GraphQL::Schema
  class ExampleDirective < GraphQL::Schema::Directive
    locations(FIELD)
    argument :int, Integer

    def self.resolve(obj, args, ctx)
      pp [self, :resolve, args.to_h]
      yield
    end
  end

  class Query < GraphQL::Schema::Object
    field :field1, String, extras: [:ast_node]

    def field1(ast_node:)
      example_directive_node = ast_node.directives.find { |d| d.name == "exampleDirective"}
      example_directive_args =  context.query.arguments_for(example_directive_node, ExampleDirective)
      pp [:field1, example_directive_node.name, example_directive_args.to_h]
      "OK"
    end
  end

  query(Query)
  directives(ExampleDirective)
end

pp MySchema.execute("{ field1 @exampleDirective(int: 5) }").to_h
# [MySchema::ExampleDirective, :resolve, {:int=>5}]
# [:field1, "exampleDirective", {:int=>5}]
# {"data"=>{"field1"=>"OK"}}
```

Let me know if you run into any trouble with that approach!

**Comment by Tripple-A** [comment]
This works perfectly. It was just what I needed. Thanks for responding!
