### ISSUE TITLE
"arguments_for" missing some fields for an input object 

### ISSUE THREAD

**Issue by rperryng** [rmosolgo/graphql-ruby#4332]
**Describe the bug**

`visitor.query.arguments_for(node, visitor.field_definition)` does not return values more than one level deep when using explicit input object fields in a query argument

**Versions**

`graphql` version: 2.0.16

**GraphQL schema**

```graphql
type Query {
  projects(filter: FilterInput): [Project!]!
}

input FilterInput {
  type: ProjectType
  pagination: PaginationInput
  order: [ProjectOrderByInput!]
}

input PaginationInput {
  limit: Int
  offset: Int
}

input ProjectOrderByInput {
  field: String!
  direction: OrderDirection
}

enum OrderDirection {
  ASC
  DESC
}

type Project {
  id: ID!
  cleanId: ID!
  name: String!
  type: ProjectType!
  buildUrl: String
  validationUrl: String
}

enum ProjectType {
  FEDERATION
  STITCHING
  SINGLE
  CUSTOM
}
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
query getProjects($limit: Int!, $type: ProjectType!) {
  projects(filter: { pagination: { limit: $limit }, type: $type }) {
    id
  }
}
```

**Steps to reproduce**

execute query with an analyzer that calls `Visitor#arguments_for` during the `on_leave_field` hook for the `projects` node in query above.  Inspect the result for the missing values.

I've prepared a spec ([code](https://github.com/rperryng/graphql-ruby-hive/blob/36b6648e5a31743f3259a75e59ac34282f16b4ac/spec/graphql/graphql-hive/analyzer_spec.rb#L158-L184)) to test this.

It can be run by:
1. cloning [rperryng/graphql-ruby-hive](https://github.com/rperryng/graphql-ruby-hive/tree/argument-extraction) and entering directory
2. `git checkout argument-extraction` (`36b6648e5a31743f3259a75e59ac34282f16b4ac` as of writing)
3. `bundle install`
4. `bundle exec rspec spec/graphql/graphql-hive/analyzer_spec.rb:170`

**Expected behavior**

when visiting the `on_leave_field` hook while visiting the `projects` field, I expected
`visitor.query.arguments_for(node, visitor.field_definition)` to return an object that roughly has the shape:
```graphql
{
  filter: {
    pagination: { limit: $limit }
    type: $type
  }
}
```

**Actual behavior**

`visitor.query.arguments_for(node, visitor.field_definition)` to return an object that roughly has the shape:
```graphql
{
  filter: {
    pagination: {}
  }
}
```

**Additional context**

I am doing something similar to the field usag analyzer to also include used arguments.  Specifically, my goal for the query above would be for the analyzer to produce a list that includes the following strings:

```
FilterInput
FilterInput.pagination
FilterInput.type
PaginationInput
PaginationInput.limit
Query.projects.filter
```

However I can't seem to collect the `FilterInput.type` and `PaginationInput.limit` IDs, since the `arguments_for` call doesn't return the hash with these elements

I tried following the existing `FieldUsage` code analyzer to recursively visit the input object fields just like it does ([original code](https://github.com/rmosolgo/graphql-ruby/blob/66b005cb0d387b85a15657105fab5fdd400935d3/lib/graphql/analysis/ast/field_usage.rb#L45)) but found that the `pagination` node was empty in my case, as well as the `limit` field missing as well.

Perhaps this is not what this API is meant for, but what other tools can I use to visit input object fields and having a reference to the input object type name itself?

---

I also explored using the `on_leave_argument` hook to visit the input object fields, since it does get triggered for the each of the input object fields, however I can't seem to get a reference to the field's parent InputObject type `graphql_name` (i.e. `FilterInput` / `PaginationInput` in this case) while visiting the `pagination`, `type`, and `limit` fields in the query above.

For example, when `on_leave_argument` is triggered for the input object field `limit` node:
- `parent` is the `InputObject` node but it has no `name` or `graphql_name` in this context (whereas `name` is present when visiting a regular argument node)
- `visitor.parent_type_definition.graphql_name` yields `Query` rather than the `PaginationInput` type.

For what it's worth, I found that the GraphQL JS visitor implementation exposes `ObjectField` hooks instead of re-using the `Argument` hook.  The JS visitor has a method like `typeInfo.getParentInputType()` ([code example](https://github.com/kamilkisiela/graphql-hive/blob/9ba16512159bb320c2f4e91486087dd571d8bd7f/packages/libraries/client/src/internal/usage.ts#L390)) (similar/analogous to `visitor.get_parent_type_definition` method?) to yield this information

**Comment by rmosolgo** [comment]
Thanks for the detailed report! I agree it should work like you expect, I'll take a closer look soon and follow up back here.

**Comment by rperryng** [comment]
No rush on this one! in the end I was able to use the `on_enter_argument` hook for all my needs (https://github.com/charlypoly/graphql-ruby-hive/issues/12):
- `node.value.arguments.map(&:name)` to get the used field names
- `visitor.argument_definition.type.all_argument_definitions.map(&:graphql_name)` to get _all_ field names
- `visitor.argument_definition.type.unwrap` to get the type name

In hindsight the solution is quite simple and straightforward.  I think using `*argument*`-named methods threw me off a bit, but I'm thankful for how feature-complete the API is 😇

**Comment by rperryng** [comment]
Hmm, I think I made a critical error here.

My tests are not actually _executing_ the queries against the schema with values, they are currently setup by manually instantiating the visitor and calling its `visit` method.  SInce it's not a real schema execution with variables presend, `visitor.query.arguments_for(node, visitor.field_definition)` obviously doesn't have values to return.

Sorry for the confusion.

**Comment by rmosolgo** [comment]
Glad you got to the bottom of it!
