### ISSUE TITLE
Pagination connection handles loaded and unloaded active record relations differently

### ISSUE THREAD

**Issue by yurik256** [rmosolgo/graphql-ruby#4337]
**Describe the bug**
We discovered a bug with graphql-ruby, where an incorrect value for `hasNextPage` would be returned when the resolver fetches the data from the database, when the records are loaded.

Initially, we thought that the problem is related to the `ActiveRecord::Base.connected_to` that we are using to connect to the read replica. However, after some investigation, we found that under the hood, `ActiveRecord::Base.connected_to` is loading ActiveRecord relation when returning the result: https://github.com/rails/rails/blob/d18fc329993df5a583ef721330cffb248ef9a213/activerecord/lib/active_record/connection_handling.rb#L355 using `.load`

We were able to reproduce the same bug, by loading records using `.load` in the schema resolver

**Versions**

`graphql` version: `2.0.16`
`rails` (or other framework): `rails 6.1`
other applicable versions (`graphql-batch,` etc)

**GraphQL schema**
Using the integration test schema

**Steps to reproduce**

We created a test which replicates this behaviour https://github.com/rmosolgo/graphql-ruby/commit/bdc66d5967e769daba291b8a4d41272197516bce#diff-2901ee3b79d555a6ec361d354412fe1fa0a1ac5c433e147c6b6215db35896e05R51-R54

* We have 3 `base` records in the database
* Schema resolver is updated to load records https://github.com/rmosolgo/graphql-ruby/compare/master...yurik256:graphql-ruby:reproduce-a-bug?expand=1#diff-17a1a40b12e1f517921f6223660ca10de669b73f36f92afbf2905967c1475981R179
* The first query loads the first 2 records. `hasNextPage` returns `true` as expected
* The second query loads the next 2 records

**Expected behavior**
* Since there are only 3 records, `hasNextPage` should return `false`

**Actual behavior**
* `hasNextPage` returns `true`

**Additional context**
After debugging the graphql ruby library, we found the [following code](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/pagination/active_record_relation_connection.rb#L10-L16), which is likely the culprit. 
This is where we have different behaviour for loaded & unloaded records. 
We would expect both branches of the condition, to return the same result.

**Comment by yurik256** [comment]
@rmosolgo unfortunately, I don't think I have enough context to fix it on my own 😔
I would really appreciate it, if you could take a look at it.

**Comment by calebpowell** [comment]
@rmosolgo I spotted this issue on something I was working on and have been reviewing the code. I ran a git bisect using @yurik256 's example test and it looks like this problem was introduced  on commit afd9b920.

**Comment by rmosolgo** [comment]
Fixed by #4349 -- thanks @calebpowell!
