### ISSUE TITLE
Eliminate dynamic dispatch from field resolution?

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#4339]
I heard somewhere that GraphQL runtime might be faster if we could eliminate `public_send` usage. Some was done in #4338 , but there's more in field resolution: 

https://github.com/rmosolgo/graphql-ruby/blob/413984bd0d24508fddaa5928571ae2cf7f5be89d/lib/graphql/schema/field.rb#L680-L685

https://github.com/rmosolgo/graphql-ruby/blob/413984bd0d24508fddaa5928571ae2cf7f5be89d/lib/graphql/schema/field.rb#L700-L705

Those are basically the default behavior, so I bet it's a hot path. Would eliminating those make it run faster? If so, how could it be _done_? 

I think we'd need something like:

```ruby
field_instance.singleton_class.module_eval <<-RUBY 
  def resolve_on_object(object, args)
    object.#{field_instance.resolver_method}(**args)
  end 
RUBY
```

But, IIUC, that would _create_ a singleton class for every field instance. That would be a big memory hit -- would it still be worth it?

**Comment by rmosolgo** [comment]
cc @casperisfine do you have any hunches or advice about this kind of work?

**Comment by casperisfine** [comment]
> do you have any hunches or advice about this kind of work?

Yeah, I'd advise against method generation on instances (singleton_classes), that would cause a pretty big memory overhead.

I'm not sure I quite understand the architecture enough to offer an alternative though.
