### ISSUE TITLE
Caching Question - Get fully resolved response to cache

### ISSUE THREAD

**Issue by bolandrm** [rmosolgo/graphql-ruby#4340]
Hello,

My app has a query that returns an array with a large number of graphql objects, and i'd like to improve the performance.  Something like this:

```
field :many_users, [Types::UserType], null: false
def many_users
  User.all
end
```

It returns an array of users, and i'd like to cache on a per-user basis rather than caching the entire response.  Some users may be cached, some may not be.

I can see how I can fetch cached results and output them via `raw_value`.   However, I can't figure out where to hook in to insert the graphql response hash into the cache in the first place.   Is there a way that I can get a callback or override a function so that I can access a fully processed graphql response hash to put into the cache?

Thanks.

**Comment by rmosolgo** [comment]
Hi! To get totally finished response, you could use a [Query instrumenter](https://graphql-ruby.org/queries/instrumentation.html), using `query.result` to access the response. (Another option is using the value returned from `MySchema.execute(...)`.) 

For inspiration, you could also check out https://github.com/DmitryTsepelev/graphql-ruby-fragment_cache. Does that help?

**Comment by bolandrm** [comment]
Thanks for the response!  I was hoping to get a more localized response, i.e. the response of each `Types::UserType`, but this should work if getting a more granular response isn't possible.

**Comment by rmosolgo** [comment]
Yeah, there isn't a good way to get the partial response from a single field or object, except by picking it out of the final response. That's because of how graphql-ruby runs queries in a non-linear way -- you never know when child fields will _actually_ be resolved, until everything is done!
