### ISSUE TITLE
API docs for v2.0.17 not published

### ISSUE THREAD

**Issue by jmpage** [rmosolgo/graphql-ruby#4346]
**Describe the bug**

It appears that the API docs for `2.0.17` have not been generated and pushed to the `gh-pages` branch despite links being updated to point to them in 676c8ce3f1e60d5f6bb6beba87ab770a7e0f4083. This results in a bunch of broken links on graphql-ruby.org

**Versions**

`graphql` version: 2.0.17

**Steps to reproduce**

1. Visit [graphql-ruby.org](https://graphql-ruby.org)
2. Click "API" nav link
3. Browser should navigate to https://graphql-ruby.org/api-doc/2.0.17/
4. A 404 page should be displayed.

**Comment by rmosolgo** [comment]
Derp, thaks for reporting this! Evidently my GH Action for publishing those docs needed an update. It's up now!

**Comment by jmpage** [comment]
Thank you for the fix, Robert!
