### ISSUE TITLE
Remember `Deprecated` directive reference

### ISSUE THREAD

**Issue by ravangen** [rmosolgo/graphql-ruby#4350]
This is a super minor thing, but in [`HasDeprecationReason`](https://github.com/rmosolgo/graphql-ruby/blob/0545517b38f735551dde9fbfa4501daab8f4a818/lib/graphql/schema/member/has_deprecation_reason.rb#L9), instead of searching for a specific directive type, perhaps `deprecation_reason=` can remember the reference to the directive it created?

**Comment by rmosolgo** [comment]
Sure -- it would work. And I guess it would make introspection a hair faster!
