### ISSUE TITLE
Pass two same parameters

### ISSUE THREAD

**Issue by tony123S** [rmosolgo/graphql-ruby#4371]
In `GraphiQL`, how to pass two same parameter using ransack? I want to get data where status not equal to "A" and "B"

```
 {
      invoice(
        q: {id_eq: 7, status_not_eq: "A",status_not_eq:"B"}
      ) {
        status
        paymentStatus
      }
    }
```
**Error**

`"There can be only one input field named \"status_not_eq\""`

**Comment by rmosolgo** [comment]
You can't pass two arguments with the same name, see https://spec.graphql.org/draft/#sec-Argument-Uniqueness. 

Instead, if you control the schema definition, you could change `status_not_eq` to be `List` type, for example: 

```
argument :status_not_eq, [String], required: false
```

Then, you could pass multiple statuses: 

```
{
  invoice(q: { status_not_eq: ["A", "B"] }) { ... } 
}
```

Interestingly, passing a single value without `[...]` would _still_ work, for example: 

```
{
  # this is valid, even if status_not_eq is a List type:
  invoice(q: { status_not_eq: "A" }) { ... } 
}
```

(See https://spec.graphql.org/draft/#sel-FAHjBJFCAACEhCx6I: 

> If the value passed as an input to a list type is not a list and not the null value, then the result of input coercion is a list of size one

)

I hope this helps! Please let me know if you run into any more trouble with it.
