### ISSUE TITLE
Dataloader & Pagination: avoiding unbounded queries

### ISSUE THREAD

**Issue by dominicfollett** [rmosolgo/graphql-ruby#4374]
This is not a bug -- just a question. If this is not the correct place to be asking, I will move it elsewhere.

First off, thank you for the graphql-ruby gem. It is fantastic. We're running into the common problem of N+1 queries tanking our database and have upgraded to 2.x to leverage Dataloader to remove some of these queries from our Rails backend.

However, after reading through the issues on this repository, I've come to understand that while the connection pattern delegates its pagination offsets to the Database, using Dataloader especially in the context of a 1 --> many relationship, executes an unbounded query and instead performs pagination in memory. This kind of makes sense because the Datasources are returning arrays of ActiveRecord relations. And indeed the question of how graphql-ruby would be able to paginate (via the DB) batch loaded records seems pretty difficult if not intractable.

So for our case, we are instead removing Dataloader from those particular relationships, and just setting max page size, and leveraging pagination in our queries. I'd like to know if our understanding of the situation and our approach seems correct/reasonable to you?

(We do use Dataloader in _some_ 1 --> many relationships but only when there is a finite number of records in that association, e.g. a document that can only have at most two signatures)

**Comment by rmosolgo** [comment]
> removing Dataloader from those particular relationships

Yes, I think that's the best way. If you search the issues, you'll find some people who either prefer those unbounded queries or claim to have implemented simultaneous batching and pagination, but the only implementation of batched, paginated queries I've ever seen is with Postgres window functions, from this old blog post: https://pganalyze.com/blog/efficient-graphql-queries-in-ruby-on-rails-and-postgres#batch-loading-many-records-more-efficiently

> pretty difficult if not intractable

That's my estimation of the problem, too 😅 !

**Comment by rmosolgo** [comment]
I hope my response was helpful. I don't think there's any further work to do on this issue, so I'll close it out.
