### ISSUE TITLE
Optional argument matching for subscriptions

### ISSUE THREAD

**Issue by octartem** [rmosolgo/graphql-ruby#4375]
Hello, thanks for your great work here.

We are currently migrating our realtime logic to use subscriptions and during our migrations we wanted to check if it is possible to match arguments partially or not at all.

We couldn't find anything related to this in the docs other than it must always match the same arguments.

Here is our use-case, we have a `messageCreated` subscription that can accept a `conversationId` optionally. If it is not provided then it all message creation events should pass through (this is the current behavior and is working fine).

But if it is provided, we would like to limit that subscription events to that specific conversation.

```gql
subscription MessageCreated($cId: ID) {
  messageCreated(conversationId: $cId) {
    ....
  }
}
```

This is just one example, we have a real-time heavy application that could make use of this behavior in multiple subscriptions.

**Describe the solution you'd like**

I can think of two ways here to make this doable without breaking changes. 

We could have a `must_match: false` when configuring an argument:

Then it is up to the `update` method to determine if it should be updated or not if it returns `NO_UPDATE`.

```ruby
argument :conversation_id, ::Integer, required: false, must_match: false

def update(conversation_id:)
  return NO_UPDATE if conversation_id.present? && object.conversation_id != conversation_id

  object
end
```

Another solution is leave it up to the developer to determine if arguments match or not, something like allowing us to override an `args_match` method to the subscription class.

```ruby
def args_match(conversation_id:)
 return conversation_id.blank? || object.conversation_id == conversation_id
end
```

**Describe alternatives you've considered**

Right now we just design such events in a way that they never require an argument and rely on the client side to filter these events out.

For example we could create `conversationMessageCreated` to serve as the scoped version of this event but feels like a waste, it would be great if we could re-use subscriptions in that way to toggle between filtered subscriptions and unfiltered ones.

**Additional context**

This is in no way a blocker for us but would unlock so much potential for us and will help drop redundant code for ignoring events on the client side since the BE is in a better position to determine if the event should occur or not for that user.

**Comment by rmosolgo** [comment]
Hey, thanks for the great suggestion. There _is_ a "manual" approach like the second possibility you mention: 

https://github.com/rmosolgo/graphql-ruby/blob/86b75b4de7dbe3716a2d9b1cec4b394efcfd23e3/lib/graphql/schema/subscription.rb#L127-L145

So, you can re-implement `def self.topic_for` in the subscription class to create a string which is compared for each `.trigger`, then filter in `def update`. For example:

```ruby
class MessageCreated < Subscriptions::Base 
  argument :conversation_id, ID, required: false 

  def self.topic_for(field:, arguments:, scope:)
    "#{field.path}:#{scope}:no-arguments" # leave out the arguments here -- we'll check them later
  end 

  def update(conversation_id:)
    return NO_UPDATE if conversation_id.present? && object.conversation_id != conversation_id
    super
  end 
end 
```

That way, initial subscriptions and calls to trigger would create a "topic" string that didn't include the `conversationId`, so the subscription storage backend would find them as matches even when the `conversationId` doesn't match. Then, your application could filter out updates that shouldn't continue in `def update`. 

One more caveat: it won't work with `broadcast: true`!

How does that approach sound to you?

**Comment by octartem** [comment]
This is brilliant, it worked well once I made sure it uses the `dump_recursive` function. I think this is perfect, so we can close this.

As for the broadcast caveat, I don't think it is much of an issue at the moment.

Thanks a lot for responding and answering, have a great day.
