### ISSUE TITLE
Tracer inheritance no longer working in 2.0.18

### ISSUE THREAD

**Issue by jturkel** [rmosolgo/graphql-ruby#4378]
**Describe the bug**

As of 2.0.18, tracers are no longer inherited down the `GraphQL::Schema` class hierarchy. 

**Versions**

`graphql` version: 2.0.18
`rails` (or other framework): n/a
other applicable versions (`graphql-batch`, etc): n/a

**GraphQL schema**

```ruby
module CustomTracer
  extend self

  def trace(key, data)
    puts "Custom Tracing!!!"
    yield
  end
end

class TestQueryType < GraphQL::Schema::Object
  field :ping, String, null: false

  def ping
    'ok'
  end
end

class BaseSchema < GraphQL::Schema
  tracer CustomTracer
end

class TestSchema < BaseSchema
  query TestQueryType
end
```
**GraphQL query**

```graphql
{
  ping
}
```

**Steps to reproduce**

The following script reproduces the problem:

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'graphql', '2.0.18' # works in 2.0.17
end

module CustomTracer
  extend self

  def trace(key, data)
    puts "Custom Tracing!!!"
    yield
  end
end

class TestQueryType < GraphQL::Schema::Object
  field :ping, String, null: false

  def ping
    'ok'
  end
end

class BaseSchema < GraphQL::Schema
  tracer CustomTracer
end

class TestSchema < BaseSchema
  query TestQueryType
end

TestSchema.execute('{ ping }')
```

The problem can also be reproduced with the new tracing API:

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'graphql', '2.0.18'
end

module CustomTrace
  def execute_multiplex(...)
    puts "Custom Tracing!!!"
    super
  end
end

class TestQueryType < GraphQL::Schema::Object
  field :ping, String, null: false

  def ping
    'ok'
  end
end

class BaseSchema < GraphQL::Schema
  trace_with CustomTrace
end

class TestSchema < BaseSchema
  query TestQueryType
end

TestSchema.execute('{ ping }')
```

**Expected behavior**

The above test case should output several lines that say `Custom Tracing!!!`.

**Actual behavior**

The above test case doesn't output anything because the customer tracer is never invoked.

**Comment by rmosolgo** [comment]
Thanks for the detailed report, and sorry for the trouble! I'm sure it's from #4344. I'll work up a patch soon and follow up here.

**Comment by khaiql** [comment]
I observed that adding `use GraphQL::Tracing::PrometheusTracing` also breaks the app with error `key not found: :state (KeyError)`, which is from this file https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/timeout.rb#L72. 

Is it relevant or should I file another issue?

**Comment by arielvalentin** [comment]
We are also seeing a change in behavior where the platform tracing `data[:owner].graphql_name` now returns the interface name and not the concrete type. Is this an expected change?

https://github.com/open-telemetry/opentelemetry-ruby-contrib/actions/runs/4411652907/jobs/7730375857#step:3:264

```console
# 2.0.18
{:field=>#<GraphQL::Schema::Field Vehicle.model: String>,
 :query=>query ...,
 :ast_node=>#<GraphQL::Language::Nodes::Field:0x0000000109dd4c08 @alias=nil, @arguments=[], @col=13, @directives=[], @filename=nil, @line=1, @name="model", @selections=[]>,
 :arguments=>{},
 :object=>#<Car:0x0000000107f1a6f0 @context=#<Query::Context ...>, @object=#<struct Old::Truck price=50, model="Model T">>,
 :owner=>Vehicle,
 :path=>["vehicle", "model"]}
{:field=>#<GraphQL::Schema::Field Vehicle.model: String>, :query=>query ..., :ast_node=>#<GraphQL::Language::Nodes::Field:0x0000000109dd4c08 @line=1, @col=13, @filename=nil, @name="model", @arguments=[], @directives=[], @selections=[], @alias=nil>, :arguments=>{}, :object=>#<Car:0x0000000107f1a6f0 @object=#<struct Old::Truck price=50, model="Model T">, @context=#<Query::Context ...>>, :owner=>Vehicle, :path=>["vehicle", "model"]}
```

```console
# 2.0.17
{:owner=>Car,
 :field=>#<GraphQL::Schema::Field Vehicle.model: String>,
 :path=>["vehicle", "model"],
 :ast_node=>#<GraphQL::Language::Nodes::Field:0x0000000107415de0 @alias=nil, @arguments=[], @col=13, @directives=[], @filename=nil, @line=1, @name="model", @selections=[]>,
 :query=>query ...,
 :object=>#<Car:0x0000000106627df0 @context=#<Query::Context ...>, @object=#<struct Old::Truck price=50, model="Model T">>,
 :arguments=>{}}
{:owner=>Car, :field=>#<GraphQL::Schema::Field Vehicle.model: String>, :path=>["vehicle", "model"], :ast_node=>#<GraphQL::Language::Nodes::Field:0x0000000107415de0 @line=1, @col=13, @filename=nil, @name="model", @arguments=[], @directives=[], @selections=[], @alias=nil>, :query=>query ..., :object=>#<Car:0x0000000106627df0 @object=#<struct Old::Truck price=50, model="Model T">, @context=#<Query::Context ...>>, :arguments=>{}}
```

**Comment by rmosolgo** [comment]
Good catch on that `yield`, @jturkel 😅 I've worked up a fix here: https://github.com/rmosolgo/graphql-ruby/pull/4383


> `data[:owner].graphql_name`

Sorry about that, @arielvalentin ! It _was_ an expected change, addressing this issue: https://github.com/rmosolgo/graphql-ruby/issues/4292

But, since I rolled the fix into another PR, I forgot to call it out on the changelog 😖 

You can get the old behavior with `data[:object].class.graphql_name`, but it might be buggy as described in the original issue. I just updated the changelog in df8b36de5.

**Comment by rmosolgo** [comment]
> does the `@platform_field_key_cache` in `GraphQL::Tracing::PlatformTrace` work properly if multiple platform tracers are active?

No, I don't suppose it would. If people are using multiple metrics systems that will need work 🙈

**Comment by jturkel** [comment]
> > does the @platform_field_key_cache in GraphQL::Tracing::PlatformTrace work properly if multiple platform tracers are active?
>
> No, I don't suppose it would. If people are using multiple metrics systems that will need work 🙈

FWIW - We've found using multiple metrics systems really useful when transitioning between providers (not that I want to go through that migration again!).

**Comment by khaiql** [comment]
> I suspect the problem is the call to `yield` rather than `super` in `GraphQL::Schema::Timeout#execute_field`: https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/timeout.rb#L84.
> 
> On a related note, I wonder if there are any method or instance variable conflicts between tracers now that all tracer modules get included into a single class. For example, does the `@platform_field_key_cache` in `GraphQL::Tracing::PlatformTrace` work properly if multiple platform tracers are active?

I still faced the same problem after upgrading to 2.0.19 for the timeout issue. I'm using `GraphQL::Tracing::PrometheusTracing`

**Comment by rmosolgo** [comment]
Sorry to hear it, @khaiql 😖 Could you please open a new issue with the full backtrace and error message that you encounter on 2.0.19? Then we'll hunt it down...
