### ISSUE TITLE
A way to access Context @values

### ISSUE THREAD

**Issue by maxim** [rmosolgo/graphql-ruby#438]
In some cases it's inconvenient to access each individual `context[:field]`. For example, I have an authorization library that takes an input hash, and I simply need to pass the entire context hash to it. Since I'm the one putting the values in there, wouldn't it be convenient to be able to take them out? I propose either adding this to `Context`:

```ruby
attr_reader :values
```

or perhaps

```ruby
def to_h
  @values
end
```

What are your thoughts?

**Comment by rmosolgo** [comment]
I think the implementation of `to_h` that you suggest could work, but it's also worth considering another approach. Why not assign the input hash as a _single member_ of context, instead of passing the input hash as the entire context? eg, 

```ruby 
# from:
# Pass `auth_data` as the query context:
MySchema.execute(query_str, context: auth_data) 
# to:
# Pass `auth_data` as `context[:auth_data]`:
MySchema.execute(query_str, context: { auth_data: auth_data }) 

# from: 
-> (o, a, ctx) { authorize(ctx.to_h) }
# to:
-> (o, a, ctx) { authorize(ctx[:auth_data]) }
```


The advantage to that other approach is that it has some protection against other writes to `context`. For example, instrumentation or other field resolvers may add keys to `context`. Would you want those to "come through" with `to_h`?

**Comment by maxim** [comment]
@rmosolgo that's a great point! Thanks for the advice. I will do something like that for now.

Couple of my additional thoughts on this:

1. If I'm given a clean place to put my stuff, then I would be surprised to find somebody else's stuff in it. :) As in, perhaps context I write and read should already be scoped for me. I can see problems with this in a sense that it complicates the api.

2. If I'm putting `:current_user` into `:auth_data`, then that means the structure of my context was dictated by the tool I used. Technically, `:current_user` could belong in other nested structures, but really it's more of a top level thing. It turns a bit into a "which tool got dibs on claiming the field"? I guess it encourages me to use a scope like `:my_app_context` and put everything in there.

It's also true that allowing full hash access widens the api, and may hurt in the future. Hard to tell what's right in this case.

**Comment by rmosolgo** [comment]
Wow, that would be really strong, if the gem managed namespacing _for_ you. I will keep this on my radar!

**Comment by rmosolgo** [comment]
I don't have the bandwidth to implement something like this myself, but i suppose it could be implemented as 

```ruby 
context.namespace(MyModule)[:key] = value
```

I've been using prefixed keys and although it's simple, it works! I'm going to close this issue as it's not high-priority in the foreseeable future, but if someone would like to take a crack at this feature, I'd happily accept it!

**Comment by rmosolgo** [comment]
Adding these features at https://github.com/rmosolgo/graphql-ruby/pull/689
