### ISSUE TITLE
OpenTelemetry Tracing API Support

### ISSUE THREAD

**Issue by arielvalentin** [rmosolgo/graphql-ruby#4380]
**Is your feature request related to a problem? Please describe.**

Add support for the OpenTelemetry Tracing API. 

**Describe the solution you'd like**

👋🏼 On behalf of @open-telemetry/ruby-contrib-maintainers 

We have been maintaining a tracer for the OpenTelemetry API and were made aware of recent changes to the tracer API released in graphql 2.0.18. I was hoping to submit a 1st party tracer library that would allow us to ensure we avoid incompatibilities in the future. 

https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/374

**Describe alternatives you've considered**

Continue maintaining 3rd party tracers with the help of the GraphQL maintainers :)

**Additional context**

**Comment by rmosolgo** [comment]
:+1: I'm certainly happy to maintain an opentelemetry implementation alongside the other platform tracers in the is library. But FWIW, I bet #4379 (just released in 2.0.19) will fix the linked bug. I accidentally broke inheritance of tracers in 2.0.18 🤦

**Comment by rmosolgo** [comment]
I don't have plans to work further on this, and it looks like support is continuing in the other repo. I'm still happy to manage that tracer in this codebase if you'd prefer, either way suits me. But since I don't have work planned for this issue, I'll close it out.

**Comment by arielvalentin** [comment]
Thank you @rmosolgo 

For now I will ask for your help reviewing PRs as part of opentelemetry-ruby-contrib repo and we can discuss transferring the code to this repo so that it is included as a first party integration in the future!
