### ISSUE TITLE
Typo in ArgumentError raised for legacy tracers

### ISSUE THREAD

**Issue by jazairi** [rmosolgo/graphql-ruby#4392]
**Describe the bug**

Hopefully I'm opening the right type of issue. This is not exactly a bug, but it feels closer to a bug than a feature request. 🙂 

There's a small typo in the ArgumentError raised here: `https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/query.rb#L107-L109`.

The error message suggests adding `tracer_class(GraphQL::Tracing::LegacyTrace)` to the schema configuration, but the correct code is `trace_class(GraphQL::Tracing::LegacyTrace)`.

**Versions**

`graphql` version: 2.0.19
`rails` (or other framework): 7.0.4.3

**Comment by rmosolgo** [comment]
Thanks for reporting this and sorry for the trouble! I addressed it in https://github.com/rmosolgo/graphql-ruby/commit/34e8164c0c7426b62cda4e464725d5fbfe950fdc.

**Comment by jazairi** [comment]
Thanks, @rmosolgo!
