### ISSUE TITLE
Unable to parse `schema.graphql` containing `@oneOf` directive

### ISSUE THREAD

**Issue by jdeff** [rmosolgo/graphql-ruby#4396]
**Describe the bug**

We are using the `@oneOf` directive in our schema and we noticed that the generated `schema.graphql` dump is not able to be parsed by the latest `graphql` NPM package. We are getting an `Unknown directive "@oneOf"` error. The `@oneOf` directive is not yet added as a built-in directive in the spec, and no directive definition can be found. 

If I add the following line to my `schema.graphql`, then everything parses correctly:

```
directive @oneOf on INPUT_OBJECT
```

Should we consider adding the directive definition to the generated dump until `@oneOf` is officially added to the spec?

**Versions**

`graphql` version: 2.0.19
`rails`: 7.0.4.1

NPM package:
`graphql`: 16.6.0

**Expected behavior**

I should be able to parse the `schema.graphql` file generated by `graphql-ruby` with other graphql libraries.

**Comment by jdeff** [comment]
I think `ruby-graphql` can parse it just fine. Just to be clear, I am trying to use https://www.npmjs.com/package/graphql which doesn't define `oneOf` as a default directive:

https://github.com/graphql/graphql-js/blob/aa43fec435c52d86ff0ff66b2df6bb20ec358e51/src/type/directives.ts#L253

**Comment by rmosolgo** [comment]
Oh -- I see, thanks for setting me straight. I guess the best fix would be to print `directive @oneOf ...` _if_ it's actually used by the schema. (That way it doesn't add noise to other schema dumps.)
