### ISSUE TITLE
Emit More Authorization Metrics

### ISSUE THREAD

**Issue by larry-reid-shopify** [rmosolgo/graphql-ruby#4405]
As near as we can tell, the gem emits `authorization` or `authorization_lazy` metrics during [`GraphQL::Schema::Object.authorized_new`](https://github.com/rmosolgo/graphql-ruby/blob/a16c512a55a1f8e5743d446d48a7c99bd06ddd3a/lib/graphql/schema/object.rb#L50). There are other contexts where an `authorized?` method can be called. We _may_ be interested in the performance of some of those other contexts. 

If we're not missing something:

- Was this a deliberate decision to only emit metrics only for classes derived from `GraphQL::Schema::Metrics`?
- If not, would it make sense to add this to `graphql-ruby`, or is that something that should be done by downstream code (code that uses `graphql-ruby`)? (NOTE: we're not asking for any actual implementation. We're just trying to understand the situation.)
- If we're misunderstanding how the code works, please let us know.

Thanks in advance for your answers!

**Comment by rmosolgo** [comment]
Hi, great question! No, this was not a deliberate decision, it would be best if all the different calls to `def authorized?` were profiled properly. I think it'd make sense to improve graphql-ruby so that any time an object is checked of `.authorized?`, it called the appropriate trace method.

**Comment by rmosolgo** [comment]
I don't have plans to work on this right now but if anyone gets the chance, I'd welcome a PR adding field- and argument- level authorized tracing!
