### ISSUE TITLE
Reopening: AppSignal Tracer: undefined method platform_authorized

### ISSUE THREAD

**Issue by gastonmorixe** [rmosolgo/graphql-ruby#4408]
[AppSignal Tracer: undefined method platform_authorized](https://github.com/rmosolgo/graphql-ruby/issues/4387) Issue#4387

[Comment here](https://github.com/rmosolgo/graphql-ruby/issues/4387#issuecomment-1487289699)

**Comment by rmosolgo** [comment]
The fix was recently released in 2.0.20 -- please let me know if that version doesn't fix it for you!
