### ISSUE TITLE
Debouncing Subscription Triggers

### ISSUE THREAD

**Issue by Amnesthesia** [rmosolgo/graphql-ruby#4441]
**Is your feature request related to a problem? Please describe.**

When subscriptions are fired in Rails callbacks, especially in `after_update` or `after_commit`, these subscriptions can fire a lot. Especially when code is running inside transaction blocks, and updates have not yet been committed

**Describe the solution you'd like**

It would be amazing if subscriptions could be deduped / debounced with some magic, e.g

```
class Subscriptions::AppointmentUpdated < Subscriptions::Base
  dedup wait: 1.second
end
```

or something similar to this, where if the same arguments / context keys are passed within a certain time frame, wait until the given time has passed before firing and deduplicate the triggers

**Describe alternatives you've considered**

* Fire subscriptions manually, ALWAYS (this is tedious and easy to miss)
* Fire subscriptions with an `after_update` hook, but then it must also be fired `after_commit, on: :update` or the subscriptions will either not fire if within a transaction, or if outside of a transaction, depending on which callback
* Debounce the trigger with Sidekiq
* Debounce the trigger with concurrent-ruby

We've ended up creating a very ... hacky? solution using `concurrent-ruby`, where we fire a subscription after 1 second, but cancel that threadpool and reset the timer if a new call is made with the same argument before that.

Before that, we used a Sidekiq job that would be cancelled and rescheduled, essentially doing the same thing, but I felt bad for our little redis friend. 

**Additional context**

**Comment by rmosolgo** [comment]
Hey, great question. How about creating a job like this?

```ruby
class AppointmentSubscriptionUpdateJob < ApplicationJob 
  def perform(appointment) 
    if appointment.updated_at < 5.seconds.ago 
      MySchema.subscriptions.trigger(...)
    else 
      # assume that a more recent update to this appointment enqueued a new job
    end 
  end 
end 
```

And enqueuing it with a wait (from `after_update` _and_ `after_commit on: :update`): 

```ruby 
AppointmentSubscriptionUpdateJob.set(wait: 5.seconds).perform_later(appointment)
```

That way, when it runs, it can check whether there was another update in the meantime, and if there was, it can no-op and let the later update send a trigger. (I wrote for ActiveJob but I assume Sidekiq has some similar options.) 

Would that approach work for you?

**Comment by rmosolgo** [comment]
Let me know how it goes if you give an approach like that a try!
