### ISSUE TITLE
Graphql-ruby is in violation graphql spec point 6.2.2 when used with dataloader

### ISSUE THREAD

**Issue by Bertg** [rmosolgo/graphql-ruby#4446]
**Describe the bug**

Given I have a mutation with multiple top-level fields
When I execute this query
Then [according to the spec](http://spec.graphql.org/June2018/#sec-Mutation) these should execute serially
But when dataloader is in use
Then field resolving is not guaranteed to happen serially

> If the operation is a mutation, the result of the operation is the result of executing the mutation’s top level selection set on the mutation root object type. **This selection set should be executed serially.** (emphasis mine)
> 
> It is expected that the top level fields in a mutation operation perform side‐effects on the underlying data system. Serial execution of the provided mutations ensures against race conditions during these side‐effects.

**Versions**

`graphql` version: 2.0.21
`rails` (or other framework): rails (7.0.4.3)

**GraphQL schema**

```ruby
# pseudocode
class PublishMutation < GraphQL::Schema::RelayClassicMutation
  def resolve
    some_setup_work_using_dataloader
    result = mutation_to_database
    return result
  end
end

class NotifyMutation < GraphQL::Schema::RelayClassicMutation
  def resolve
    validate_if_publish_mutation_happend
    result = enqueue_notification_work
    return result
  end
end
```

**GraphQL query**

```graphql
mutation PublishAndNotify($id: ID!) {
  publish(input: { id: $id))  { id state }
  notify(input: { id: $id))  { result }
}
```

**Expected behavior**

When dataloader is not in use, this works as expected. The publish mutation publishes the record, and the notify mutation can proceed.

**Actual behavior**

When dataloader in use, the sequence of events is different.

The `PublishMutation` starts, however when `some_setup_work_using_dataloader` is invoked, the fiber scheduler will start resolving the next field. In `NotifyMutation` the `validate_if_publish_mutation_happend` now doesn't see the record as being published (that mutation has not completed) and fails.
Then `PublishMutation` can continue and succeeds in publishing the record.

**Comment by rmosolgo** [comment]
Uh oh, sorry, and thanks for reporting this! I would have _expected_ this was covered by: 

https://github.com/rmosolgo/graphql-ruby/blob/054206dbdf0b52e40c0706666c29d9fdda4db404/lib/graphql/execution/interpreter/runtime.rb#L573-L581

But, I don't see a test for it. I'll take a look soon and follow up back here!
