### ISSUE TITLE
uninitialized constant Types::UserType::Type

### ISSUE THREAD

**Issue by jsvelte** [rmosolgo/graphql-ruby#4454]
**Describe the bug**

I'm getting an error messages in my graphiql interface 

**Versions**

`graphql` version: latest
`rails` (or other framework): "~> 7.0.4", ">= 7.0.4.3"
other applicable versions (`graphql-batch`, etc)

I followed all the installation here: https://web-crunch.com/posts/how-to-use-graphql-with-ruby-on-rails

I fixed some issue in regards of `ActionDispatch::Request::Session::DisabledSessionError in GraphiQL::Rails::Editors[#show](https://www.youtube.com/hashtag/show)`

![image](https://user-images.githubusercontent.com/108642414/234743940-e4f53d15-c61d-4f75-b9bf-b9f116ce3298.png)

and now I have a problem like this

![image](https://user-images.githubusercontent.com/108642414/234744190-69be7957-d12c-4df2-b303-3b25ddec8262.png)

Help me how to fix this
### user_type
![image](https://user-images.githubusercontent.com/108642414/234744250-d0586f76-f74c-4246-9c3d-7cd8d40d03c9.png)

### post_type
![image](https://user-images.githubusercontent.com/108642414/234744303-def91056-68ba-4c6c-8725-7a072bef2982.png)

### query_type
![image](https://user-images.githubusercontent.com/108642414/234744358-59f60982-1f1b-4604-97ca-8e67231d5b73.png)

**Comment by rmosolgo** [comment]
Hi! Sorry for the trouble and thanks for such a detailed report. Try changing `Type::PostType` into `Types::PostType` (with an `s`): 

```diff 
- field :posts, [Type::PostType], null: true
+ field :posts, [Types::PostType], null: true
```

That way, it will properly reference the class defined in `post_type.rb`. Does that work for you?
