### ISSUE TITLE
v2.0.21 breaks Query::Context#dig with single argument

### ISSUE THREAD

**Issue by anaclair** [rmosolgo/graphql-ruby#4457]
**Describe the bug**
We were calling `dig` on a `Query::Context` object, passing in a single symbolized argument, `:current_arguments` (which is in `RUNTIME_METADATA_KEYS`) e.g. `context.dig(:current_arguments)`. In trying to upgrade from v2.0.20 to v2.0.21 we're getting the following error from this call to `dig`:
```
ArgumentError:
       wrong number of arguments (given 0, expected 1+)
```
It looks like the error may be occurring here:
https://github.com/rmosolgo/graphql-ruby/blob/bb676ae43c8048fe0b07d9c04573a4420ef1900f/lib/graphql/query/context.rb#L281
Since this is a patch upgrade, I didn't expect anything to break so thought I would reach out. Or maybe there's something else I'm missing. Thank you for taking a look!

**Versions**

`graphql` version: v2.0.21
`rails` (or other framework): 7.0.4.3

**Steps to reproduce**
We were calling `dig` on a `Query::Context` object, passing in a single symbolized argument, `:current_arguments` (which is in `RUNTIME_METADATA_KEYS`) e.g. `context.dig(:current_arguments)`.

**Expected behavior**
Get back a `GraphQL::Execution::Interpreter::Arguments` object without issue.

**Actual behavior**
```
ArgumentError:
       wrong number of arguments (given 0, expected 1+)
```
**Additional context**
It works as expected when passing in more than 1 argument e.g. `context.dig(:current_arguments, :some_other_key)` or when using `[]` e.g. `context[:current_arguments]`

**Comment by rmosolgo** [comment]
Sorry for the trouble and thanks for the detailed report! It looks like I botched it here: 

https://github.com/rmosolgo/graphql-ruby/commit/bb676ae43c8048fe0b07d9c04573a4420ef1900f#diff-2c8869b38ea62e69d0aa4fc7e571e6dc3b8c9f05fba9c25bc79fc17cfee2a335R279-R281

I'm working up a fix at https://github.com/rmosolgo/graphql-ruby/pull/4458
