### ISSUE TITLE
Configurable ActionCable channel name in `graphql-ruby-client`

### ISSUE THREAD

**Issue by ajswis** [rmosolgo/graphql-ruby#4459]
**Is your feature request related to a problem? Please describe.**

I use an inflection in my Rails app for GraphQL (`inflect.acronym "GraphQL"`). `graphql-ruby-client` contains [hardcoded channel names for the GraphQL channel](https://github.com/rmosolgo/graphql-ruby/blob/27762aa781de5c98039098ca5eaf6bb3fa86702f/javascript_client/src/subscriptions/createActionCableHandler.ts#L24). Rails [converts this value to a constant](https://github.com/rails/rails/blob/8049d7983f3f8fa9679e5ccfb21814554cd60297/actioncable/lib/action_cable/connection/subscriptions.rb#L36) to find the correct channel. My channel class is `GraphQLChannel` and not `GraphqlChannel`.

**Describe the solution you'd like**

I think configurable channel names would be fantastic. It would be nice if this could be passed in with the `options` object.

**Describe alternatives you've considered**

1. Vendoring the relevant portions of `graphql-ruby-client` into my frontend so I can change the channel name.
2. Removing the GraphQL inflection.

I would be more than happy to write this feature if you think it would be accepted.

**Comment by rmosolgo** [comment]
Hi! I agree that this would be a nice improvement. The `ActionCableLink` already accepts a channelName option: 

https://github.com/rmosolgo/graphql-ruby/blob/master/javascript_client/src/subscriptions/ActionCableLink.ts#L19

But `createActionCableHandler` and `ActionCableSubscriber` don't: 

https://github.com/rmosolgo/graphql-ruby/blob/master/javascript_client/src/subscriptions/createActionCableHandler.ts#L24

https://github.com/rmosolgo/graphql-ruby/blob/27762aa781de5c98039098ca5eaf6bb3fa86702f/javascript_client/src/subscriptions/ActionCableSubscriber.ts#L34

Sure, if you'd like to go ahead and add it, please do!
