### ISSUE TITLE
Access graphql result just before response

### ISSUE THREAD

**Issue by Tripple-A** [rmosolgo/graphql-ruby#4465]
We run Domain-driven design in my company and as a result, each domain has data that is accessed from a public repository, although domains can be related, we avoid joining tables, as the data from a domain can be stored anywhere (eg. TinyBird) and not necessarily in SQL.
We would like to filter data by relationships and we have some options:
- We can aggregate the data on the first level of the graphql query and filter that data, so the correct `ids` are available for other relationship data fetching.
- We can allow all that data to be fetched, along with the relationships, and just before graphql sends the result, access that data and carry out the filtering in memory.

## QUERY SAMPLE
```
{
  employees {
    id
    name
    team {
      name
      leader
    }
  }
}
```
In the case above, the employees data comes from its repository, and the team data is fetched using the `ids` present in the employee data. It also has its own repository. We can filter by `team.name` in memory if we intercept the result. However, we can also do that by fetching the team data in the employees' repository, creating an aggregate, and carrying out that filtering on that level before the data for `team` is fetched by the data loader.
 
**Additional context**
I would like to know if there's a way to intercept the graphql result, just to know the options we have.

**Comment by rmosolgo** [comment]
Hi, great question! My first suggestion would be the `def after_query(query)` hook described here: 

https://graphql-ruby.org/queries/instrumentation.html

By the time a query reaches that point, it's totally done execution. 


Another option is the `def execute_multiplex(multiplex: ...)` hook of a "trace" module (https://graphql-ruby.org/queries/tracing.html). In that hook, anything after calling `super` will have access to finished query results, for example: 

```
module MyTrace
  def execute_multiplex(multiplex:)
    super # call through so that the multiplex is executed
    multiplex.queries.each do |query| 
      filter_in_memory(query.result)
    end 
  end 
end 

# ... 

class MySchema < GraphQL::Schema
  trace_with(MyTrace)
end 
```

I hope one of those is helpful! Let me know how it goes if you give it a try.

**Comment by Tripple-A** [comment]
Yeah, using `after_query` worked perfectly for me. Thanks a lot!
