### ISSUE TITLE
[DOCS][PRO] pundit integration custom policy lookup

### ISSUE THREAD

**Issue by k0i** [rmosolgo/graphql-ruby#4466]
# Motivation
We are using graphql-ruby pro and trying to integrate Pundit. (Thank you for creating the excellent gem :) )
Now we are seeing docs to implement custom policy lookup.
[This line](https://github.com/rmosolgo/graphql-ruby/blob/master/guides/authorization/pundit_integration.md?plain=1#L414)  looks to us that we can return an policy instance(`policy_class.new(current_user, object)`) from `pundit_policy_class_for` method.

However, it raises an error if we return a policy instance.
```
NoMethodError Exception: undefined method `new' for (our instance...)
```

After some investigation, we confirmed that we are not allowed to return any instance in the method.
( We verified the `pundit_policy_class_for` method's comment and it says the return type should be Class)

# Suggestion
If our conclusion is correct, is there room for changing the doc like the following for clarity...?

```ruby
    if current_user.system_admin?
      # return Class, not instance
      SystemAdmin.const_get("#{object.class.name}Policy")
    else
      super
    end
```

Thank you for your time 🙇  😃

**Comment by rmosolgo** [comment]
😖 Sorry for the trouble with those docs! It sounds like you got to the bottom of it: it should return a _class_, not an instance. I just pushed a fix to the docs in 18b0b72ce, please let me know if there's anything else I can help with while you're getting it set up!
