### ISSUE TITLE
Breaking Change in 2.0.17: Enum values break if mapped to a Proc

### ISSUE THREAD

**Issue by mintyfresh** [rmosolgo/graphql-ruby#4469]
**Describe the bug**

Prior to 2.0.17, it was possible to map Procs to enum values, and they'd be passed to the resolver without issue.
As of 2.0.17, the Proc is called in `lib/graphql/schema/enum_value.rb:37:in 'initialize'` (being passed the `UNDEFINED_VALUE` object, or `NOT_CONFIGURED` in 2.0.21) which causes unexpected results.

I think this is a result of using the case-equality `===` operator. 
(`-> (_) { puts 1 } === Object.new` calls the Proc)

**Versions**

`graphql` version: 2.0.21
`rails` (or other framework): 7.0.4.3

**GraphQL schema**

```ruby
class UserSortType < GraphQL::Schema::Enum
  value 'BY_NAME', value: -> (scope, direction: :asc) {
    scope.order(name: direction)
  }
  value 'BY_EMAIL', value: -> (scope, direction: :asc) {
    scope.order(email: direction)
  }
end
```

**Steps to reproduce**

Define an enum with Procs as mapped values.

**Expected behavior**

Prior to 2.0.16, no error is raised. The mapped value is passed to the resolver.

**Actual behavior**

As of 2.0.17:
`NoMethodError: undefined method 'order' for #<Object:0x00007ff688cb8280>`

Place full backtrace here (if a Ruby exception is involved):

<details>
<summary>Click to view exception backtrace</summary>

```
NoMethodError: undefined method `order' for #<Object:0x00007ff688cb8280>
/home/runner/work/api/api/app/graphql/types/user_sort_type.rb:5:in `block in <class:UserSortType>'
/home/runner/work/api/api/vendor/bundle/ruby/3.2.0/gems/graphql-2.0.21/lib/graphql/schema/enum_value.rb:37:in `initialize'
/home/runner/work/api/api/vendor/bundle/ruby/3.2.0/gems/graphql-2.0.21/lib/graphql/schema/enum.rb:54:in `new'
/home/runner/work/api/api/vendor/bundle/ruby/3.2.0/gems/graphql-2.0.21/lib/graphql/schema/enum.rb:54:in `value'
/home/runner/work/api/api/app/graphql/types/user_sort_type.rb:11:in `<class:UserSortType>'
/home/runner/work/api/api/app/graphql/types/user_sort_type.rb:3:in `<main>'
{...rails internals...}
```

</details>

**Comment by rmosolgo** [comment]
Wow! Sorry about that. I think the use of `===` instead of `==` was just a mistake. I worked up a test and fix here: #4474
