### ISSUE TITLE
[ENTERPRISE] Changeset for top-level mutation argument: Found two visible definitions

### ISSUE THREAD

**Issue by IvanChibisov** [rmosolgo/graphql-ruby#4475]
**Describe the bug**

We only want to modify the top-level argument in the mutation. We tried to do this by changing the `InputObject` of this mutation. But it returns a `Found two visible definitions` error even if the changeset is not enabled.

This only happened when `InputObject` was directly used in `input_object_class`. If the `InputObject` is nested, the modification works well.

**Versions**

`graphql` version:
  graphql-enterprise (1.2.0)
  graphql (>= 1.13.0)
  graphql (~> 2.0)
  graphql-pro (>= 1.24.0)
  graphql-pro (1.24.3)
  graphql (>= 1.7.5)

`rails` (or other framework): (7.0.4.3)
other applicable versions (`graphql-batch`, etc)

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok). Any custom extensions, etc?

Initial goal -> change argument type in mutation:
```ruby
# The mutation whose input argument we want to change
module Mutations
  class MutationExample < BaseMutation
    pundit_policy_class nil
    pundit_role nil

    argument :argument_should_change, Integer, required: true

    field :result, String, null: false

    def resolve(argument_should_change:)
      
    end
  end

# The argument in the changeset
modifies Mutations::MutationExample do
    argument :argument_should_change, String, required: true
  end
end
```
This returned a `Found two visible definitions` error, so we went through the InputObject(**_Maybe there is a way to do it differently?_**):
```ruby
# The mutation whose input argument we want to change
module Mutations
  module Inputs
    class MutationExampleInput < Types::BaseInputObject
      graphql_name "MutationExampleInput"

      argument :argument_should_change, Integer, required: true
    end
  end

  class MutationExample < BaseMutation
    pundit_policy_class nil
    pundit_role nil

    input_object_class(Inputs::MutationExampleInput)

    field :result, String, null: false

    def resolve(argument_should_change:)
      
    end
  end
  

# The argument in the changeset
modifies Mutations::Inputs::MutationExampleInput do
    argument :argument_should_change, String, required: true
  end
end
```

**Steps to reproduce**

- Create a changeset
- Try to change the `InputObject` which is used directly in the mutation in `input_object_class`.

**Expected behavior**

- Argument's type is modified when the changeset is enabled

**Actual behavior**

Found two visible definitions for `MutationExampleInput.argumentShouldChange`

Place full backtrace here (if a Ruby exception is involved):

<details>
<summary>Click to view exception backtrace</summary>

```
GraphQL::Schema::DuplicateNamesError:
       Found two visible definitions for `MutationExampleInput.argumentShouldChange`: #<Types::BaseArgument MutationExampleInput.argumentShouldChange: Int!>, #<Types::BaseArgument MutationExampleInput.argumentShouldChange: String!>
     # /usr/local/bundle/gems/graphql-2.0.21/lib/graphql/schema/warden.rb:60:in `block in visible_entry?'
     # /usr/local/bundle/gems/graphql-2.0.21/lib/graphql/schema/warden.rb:55:in `each'
     # /usr/local/bundle/gems/graphql-2.0.21/lib/graphql/schema/warden.rb:55:in `visible_entry?'
     # /usr/local/bundle/gems/graphql-2.0.21/lib/graphql/schema/member/has_arguments.rb:166:in `block in get_argument'
     # /usr/local/bundle/gems/graphql-2.0.21/lib/graphql/schema/member/has_arguments.rb:163:in `each'
     # /usr/local/bundle/gems/graphql-2.0.21/lib/graphql/schema/member/has_arguments.rb:163:in `get_argument'
     # /usr/local/bundle/gems/graphql-2.0.21/lib/graphql/schema/member/has_arguments.rb:62:in `load_notification'
     # /usr/local/bundle/gems/graphql-2.0.21/lib/graphql/schema/argument.rb:302:in `public_send'
     # /usr/local/bundle/gems/graphql-2.0.21/lib/graphql/schema/argument.rb:302:in `load_and_authorize_value'
     # /usr/local/bundle/gems/graphql-2.0.21/lib/graphql/schema/argument.rb:277:in `block in coerce_into_values'
     # /usr/local/bundle/gems/graphql-2.0.21/lib/graphql/schema.rb:1107:in `after_lazy'
     # /usr/local/bundle/gems/graphql-2.0.21/lib/graphql/schema/argument.rb:267:in `coerce_into_values'
     # /usr/local/bundle/gems/graphql-2.0.21/lib/graphql/schema/member/has_arguments.rb:271:in `block (3 levels) in coerce_arguments'
     # /usr/local/bundle/gems/graphql-2.0.21/lib/graphql/dataloader.rb:181:in `block in run'
     # /usr/local/bundle/gems/graphql-2.0.21/lib/graphql/dataloader.rb:306:in `block in spawn_fiber'
```

</details>

**Additional context**

As I wrote before, if the InputObject is nested, the modification works well:
```ruby
module Mutations
  module Inputs
    class NestedInput < BaseInputObject
      argument :argument_should_change, Integer, required: true
    end
  end

  class MutationExample < BaseMutation
    pundit_policy_class nil
    pundit_role nil

    argument :top_level_argument, Integer, required: true
    argument :nested_argument, Inputs::NestedInput, required: true

    field :result, String, null: false

    def resolve(top_level_argument:, nested_argument:)
      
    end
  end

# The argument in the changeset that works well
modifies Mutations::Inputs::NestedInput do
    argument :argument_should_change, String, required: true
  end
end
```

**Comment by nathanjsharpe** [comment]
This is probably not related to your issue, so I hope it isn't a distraction. But I thought it might help others that end up here, so I wanted to leave this here in case it does.

I was about to reply that we were seeing the same issue, but ours was due to `visible?` in a couple of custom directives not properly calling `super`. This resulted in fields not being removed by changesets, leaving the old field in addition to the new field.

**Comment by rmosolgo** [comment]
Hi! Sorry for my slow response. I certainly _expect_ it to work the way you describe. Here's a minimal example for modifying the arguments of a "Relay Classic" mutation with changesets: 

<details>
<summary>Versioned mutation arguments example</summary>
<p>

```ruby
require "bundler/inline"

gemfile do
  gem "graphql"
  gem "graphql-enterprise", source: "https://gems.graphql.pro"
end

class Schema < GraphQL::Schema
  # Base classes 
  class BaseArgument < GraphQL::Schema::Argument
    include GraphQL::Enterprise::Changeset::ArgumentIntegration
  end

  class BaseField < GraphQL::Schema::Field
    include GraphQL::Enterprise::Changeset::FieldIntegration
    argument_class(BaseArgument)
  end

  class BaseMutation < GraphQL::Schema::RelayClassicMutation
    argument_class(BaseArgument)
  end

  # Schema definition 
  class DoSomething < BaseMutation
    argument :something, Integer
    field :result, String

    def resolve(something:)
      { result: "#{something}-result" }
    end
  end

  class Mutation < GraphQL::Schema::Object
    field :do_something, mutation: DoSomething
  end

  mutation(Mutation)
  
  # Changeset configuration
  class ChangeSomething < GraphQL::Enterprise::Changeset
    release "2023-05-01"
    modifies DoSomething do
      argument :something, String
    end
  end

  use GraphQL::Enterprise::Changeset::Release, changesets: [
    ChangeSomething
  ]
end

# Using the original definition of `something`, with an integer:
res1 = Schema.execute("mutation { doSomething(input: { something: 1 }) { result } }", context: { changeset_version: "2023-01-01" })
pp res1.to_h
# {"data"=>{"doSomething"=>{"result"=>"1-result"}}}

# Using the modified definition of `something`, with a String:
res2 = Schema.execute("mutation { doSomething(input: { something: \"Hello\" }) { result } }", context: { changeset_version: "2023-05-01" })
pp res2.to_h
# {"data"=>{"doSomething"=>{"result"=>"Hello-result"}}}
```

</p>
</details>


How does that setup compare to yours? A couple of thoughts for debugging: 

- Does your base mutation extend `RelayClassicMutation` (I was thinking it did, since you tried `input_object_class`, but I'd better check)? 
- Does it have `argument_class(BaseArgument)` (or similar) to make sure it's using your custom argument class? 
- Does your changeset have a `release` configuration? Does the query run differently if you use a `context: { changeset_version: ... }` before or after the release date? 

(Also, in case this work-around helps, you could use `input_type(...)` instead of `input_object_class(...)` to directly connect a type to use for the mutation's `input: ...`.)

**Comment by IvanChibisov** [comment]
Yes, we have the same setup as you described. I have found the reason why the issue is occurring:
Our top-level argument is of type `ID` and we want to change it to our own `GlobalID` with changeset. So the configuration:
```ruby
class DoSomething < BaseMutation
  pundit_policy_class SomethingClassPolicy
  pundit role nil

  argument something_id, ID, loads: Types::SomethingType, pundit_role: :some_role

  field :result, String
  
  def resolve(something:)
    return "Hello, #{something.id}"
  end
end

# Changeset configuration
class ChangeSomething < GraphQL::Enterprise::Changeset
  release "2023-05-01"
  modifies DoSomething do
    argument :something_id, GlobalID, loads: Types::SomethingType, pundit_role: :some_role
  end
end
```
This configuration throws an error `GraphQL::Schema::DuplicateNamesError: Found two visible definitions`. But when we remove `loads: Types::SomethingType` from the current mutation config (we can leave this in the changeset) -> changeset works well. So the root reason is the use of `loads` in the mutation argument. This prevents it from being updated with the changeset.

Thanks for creating a detailed example on how to update a mutation argument in a changeset. This allowed me to think that this is still possible and the problem needs to be looked for deeper. :) With this knowledge, I can go further with updating the mutation arguments with a changeset :rocket:

**Comment by rmosolgo** [comment]
Oh... thanks for sharing these details. I bet there's some bug about how `loads: ...` converts the keyword argument from `something_id: ...` to `something: ...`. I'll take another look -- it _should_ work the way you expect! Glad you found something that works for now.

**Comment by bessey** [comment]
Adding a +1 as I've also just run into this while working on our higher order type renaming framework

**Comment by bessey** [comment]
I've done a little bit of pry debugging and established that this is the problem:
https://github.com/rmosolgo/graphql-ruby/blob/5b938754cdbcf0eefa3b0b70bc794e1b3336046b/lib/graphql/schema/member/has_arguments.rb#L62

Since `get_argument` is not passed a `context` it falls back to a `GraphQL::Query::NullContext` which doesn't have the information necessary to know that one of the implementations should not be visible.
