### ISSUE TITLE
[PRO] `GraphQL::Pro::Access` broken in `2.x`

### ISSUE THREAD

**Issue by dtcristo** [rmosolgo/graphql-ruby#4476]
**Describe the bug**

Regarding `GraphQL::Pro::Access::Extensions`, Eg:
- `authorize :foo` within `GraphQL::Schema::Mutation` instances
- `authorize :foo` on fields (`field :foo, mutation: Foo, authorize :foo`).

These don't work when updating `graphql` to `2.x` as the mixins are never applied. From the looks of it, this happens because `require "graphql/pro/access"` is conditional on `GraphQL::ObjectType` being defined (see `lib/graphql/pro.rb:5`). `GraphQL::ObjectType` got removed in `graphql 2.0.0`. This results in `GraphQL::Pro::Access` never being loaded, thus access extensions are never applied.

**Versions**

`graphql` version: `>= 2.0.0`
`graphql-pro` version: `1.23.4`

**Steps to reproduce**

Define a mutation that uses method from `GraphQL::Pro::Access::Extensions::MutationExtension` mixin (eg `authorize`)

```ruby
class MyMutation < GraphQL::Schema::Mutation
  authorize :anyone

  #...
end
```

Boot application.

**Expected behavior**

Application boots and authorization is correctly applied to mutation.

**Actual behavior**

Exception is raised when class is loaded.
```
NoMethodError - undefined method `authorize' for MyMutation:Class
```

**Comment by rmosolgo** [comment]
Hi! Sorry for the surprise -- as you noticed, `GraphQL::Pro::Access` isn't support on GraphQL-Ruby 2+. It is completely built on legacy APIs that were replaced one-by-one between 1.8 to 1.13 or so. 

I would have _expected_ those intervening versions issue warnings about those deprecated methods (especially `.to_graphql` and `.graphql_definition`). But, did you do a step-by-step upgrade _without_ any warnings, or did you jump from a smaller 1.x version straight to 2.x? 

In any case, the migration path is to use the built-in authorization in Class-based graphql types: https://graphql-ruby.org/authorization/authorization.html It was deeply influenced by my experience with `GraphQL::Pro::Access` but, in my opinion, anyway... better! There are also Pundit and CanCan plugins linked in that doc. 

How about migrating to that new system? If you can share some details of your setup (perhaps by email, if you like) I'd be happy to recommend some implementations of `def self.authorized?` that will use your existing code.

**Comment by dtcristo** [comment]
Thanks for your response.

> did you do a step-by-step upgrade without any warnings, or did you jump from a smaller 1.x version straight to 2.x?

I attempted an upgrade of `graphql` in our application from `1.13.17` to latest (`2.0.21`). I hadn't noticed any deprecation warnings when running `1.13.17`. They were likely there but I could have missed them.

> the migration path is to use the built-in authorization in Class-based graphql types: https://graphql-ruby.org/authorization/authorization.html

Thanks for this advice, I will give it a try.

Perhaps it's worth mentioning somewhere in the docs that `GraphQL::Pro::Access` does not work on `2.x`? Maybe it's already there and I didn't see it.

Anyway, keep up the great work!

**Comment by rmosolgo** [comment]
> somewhere in the docs

There aren't any docs for `GraphQL::Pro:Access` anymore 🙈 ! I figured people would be migrating as they found that it was deprecated so I removed those docs a while back. 

Let me know how it goes as you try to migrate -- I'd be happy to offer suggestions or make any compatibility fixes if you encounter problems!
