### ISSUE TITLE
[PRO] `@defer` issues with graphql-batch

### ISSUE THREAD

**Issue by zekenie** [rmosolgo/graphql-ruby#4477]
**Describe the bug**

We've been using graphql-ruby since 2017 on a large rails app. It's a wonderful piece of technology, thank you for building it. We recently purchased GraphQL::Pro, mainly for the `@defer` support. We also use [graphql-batch](https://github.com/Shopify/graphql-batch), which we installed before you added your dataloader feature.

The issue we're running into is that `@defer` only works on fields that are not making calls to graphql-batch.

![image (11)](https://github.com/rmosolgo/graphql-ruby/assets/962281/3bc5530b-cf33-41bb-8aa3-ead30785c515)

Is there a way for us to wrap deferred execution in `GraphQL::Batch.batch do; end`?

We also looked into migrating to your dataloader feature. The issue we have is that there's not a clear example of how to achieve what they describe in their [`AssociationLoader`](https://github.com/Shopify/graphql-batch/blob/master/examples/association_loader.rb). It might be pretty simple, but we don't quite understand the dataloader code enough to figure it out. Any guidance on that would be appreciated!

**Versions**

```
gem "graphql", "2.0.21"
gem "graphql-batch", "~> 0.3" # we also tried it with the latest version, didn't resolve the issue
```

**Comment by rmosolgo** [comment]
Hi! Thanks for the detailed report and sorry for the trouble. I worked it out for Dataloader but I should have looked into the GraphQL-Batch workflow. I have a suggestion for now but let's keep this open until I can work something out and get it in the docs.

The real "work" of `@defer` happens when you ask for its data, so you could wrap it like this: 

```ruby
if (deferrals = context[:defer])
  response.headers['Last-Modified'] = Time.now.httpdate
  response.headers["Content-Type"] = "multipart/mixed; boundary=\"-\""
  deferrals.each do |deferral|
    patch_str = GraphQL::Batch.batch do 
      deferral.to_http_multipart(pretty: false, delimiter: "-")
    end 
    response.stream.write(patch_str)
  end 
end 
```

How does that work for you? 

As for `AssociationLoader`, it's not clear to me it's actually _better_, performance-wise, but I guess it depends. Here's some past discussion on that: https://github.com/rmosolgo/graphql-ruby/issues/4075#issuecomment-1139708741 I'd be happy to revisit that on a new issue if you're interested.


<details>
<summary>Minimal example of `@defer` and `GraphQL-Batch`</summary>
<p>

```ruby
require "bundler/inline"

gemfile do
  source "https://gems.graphql.pro" do
    gem "graphql-pro", "1.24.4"
  end
  gem "graphql"
  gem "graphql-batch"
end


class Schema < GraphQL::Schema
  class ThingLoader < GraphQL::Batch::Loader
    def perform(ids)
      ids.map { |id| fulfill(id, { name: "thing-#{id}" } ) }
    end
  end

  class Thing < GraphQL::Schema::Object
    field :name, String
  end

  class Query < GraphQL::Schema::Object
    field :thing, Thing do
      argument :id, ID
    end

    def thing(id:)
      ThingLoader.load(id)
    end
  end

  query(Query)
  use GraphQL::Batch
  use GraphQL::Pro::Defer
end

result = Schema.execute("{
  t1: thing(id: \"one\") { name }
  t2: thing(id: \"two\") @defer { name }
}")


result.context[:defer].each do |deferral|
  GraphQL::Batch.batch do
    pp deferral.to_h
  end
end
```

</p>
</details>

**Comment by zekenie** [comment]
Thank you so much for the detailed response. I'll take a look at this today

**Comment by zekenie** [comment]
When I use the controller code you provided, I do get a reasonable response! But, it doesn't work with GraphiQL. I was getting it to work with GraphiQL before when I deferred non-batched fields, which makes me think I broke something... This is the controller code. I think something about `to_http_multipart` and `response.stream.write` vs `stream_http_multipart` is to blame?

```
if (deferred = result.context[:defer])
  # Required for Rack 2.2+, see https://github.com/rack/rack/issues/1619
  response.headers["Last-Modified"] = Time.now.httpdate
  deferred.each do |deferral|
    patch_str = GraphQL::Batch.batch do
      deferral.to_http_multipart(pretty: false, delimiter: "-")
    end
    response.stream.write(patch_str)
  end
else
  render json: result
end
```

<img width="466" alt="image" src="https://github.com/rmosolgo/graphql-ruby/assets/962281/e1b53520-78a2-4bf5-bb13-727dd8affae0">
<img width="324" alt="image" src="https://github.com/rmosolgo/graphql-ruby/assets/962281/cd67686b-e5fd-47c3-8c0b-06c255b80bad">

**Comment by zekenie** [comment]
it also doesn't seem to work with apollo client 3.7

**Comment by rmosolgo** [comment]
Yes, I bet you're right that it has to do with breaking out of `stream_http_multipart`. My _goal_ was to inline that method in your controller, wrapping the call to `deferall.to_http_multipart` with `GraphQL::Batch.batch { ... }` 

Did you add this line to your controller code? 

```ruby
  response.headers["Content-Type"] = "multipart/mixed; boundary=\"-\""
```

I think that'll be necessary to tell the client how to interpret the incoming chunks.

**Comment by zekenie** [comment]
That worked for GraphiQL! Don't know how I missed that from your initial code snippet. I'm still having some issues with Apollo Client. The initial data renders briefly and when subsequent data streams in the entire data payload becomes blank. I wonder if it might be related to [this issue](https://github.com/apollographql/apollo-client/issues/10555#issuecomment-1429987636). 

> Apollo Client has implemented @defer support based on the defer/stream spec proposal as of August 24, 2022 and expects an incremental array of objects with data and path keys on [incremental result](https://github.com/apollographql/apollo-client/blob/issue-8694-useBackgroundQuery/src/link/core/types.ts#L39:L39) chunks (all chunks that arrive after the initial chunk, which alone has a data property).

I'm also finding chrome dev tools to be lacking in terms of debugging. Do you have any recommendations for how you inspect incremental responses?

**Comment by rmosolgo** [comment]
Oh, good call. I wonder if updating it for Apollo Client will break it for GraphiQL 😖 

Here's a take on the controller code that should work for the latest Apollo Client: 

```ruby
if (deferrals = context[:defer])
  response.headers['Last-Modified'] = Time.now.httpdate
  response.headers["Content-Type"] = "multipart/mixed; boundary=\"-\""
  deferrals.each do |deferral|
     # Resolve the deferred result:
     result_h = GraphQL::Batch.batch do 
       deferral.to_h 
     end 
     # Transform this hash for the pending @defer spec:
     apollo_result_h = { incremental: [ result_h.except(:hasNext) ], hasNext: result_h[:hasNext] }
     # Make it into a multipart payload:
     result_str = JSON.dump(apollo_result_h)
     patch_str = "\r\n---\r\nContent-Type: application/json\r\nContent-Length: #{result_str.bytesize}\r\n\r\n#{result_str}#{result_h[:hasNext] ? "" : "\r\n-----"}"
    response.stream.write(patch_str)
  end 
end 
```

Want to give that a try? I'll build it into GraphQL-Pro soon -- it should definitely be there!

**Comment by rmosolgo** [comment]
Ohhh 👀 I bet it's a bug with the first payload. In GraphQL-Pro, it doesn't have `path: []`, (it has no `path:` key), so that would probably cause the error above. One way to address this would be to add a fallback path: 


```diff
      # Transform this hash for the pending @defer spec:
     apollo_result_h = { incremental: [ result_h.except(:hasNext) ], hasNext: result_h[:hasNext] }
+    # Add an empty path for the initial payload, for Apollo:
+    apollo_result_h[:incremental].first[:path] ||= [] 
```

However, the spec also doesn't seem to expect an `incremental: ...` for the first payload at all, so it might also work with controller code like this: 

```ruby
if (deferrals = context[:defer])
  response.headers['Last-Modified'] = Time.now.httpdate
  response.headers["Content-Type"] = "multipart/mixed; boundary=\"-\""
  deferrals.each_with_index do |deferral, idx|
    # Resolve the deferred result:
    result_h = GraphQL::Batch.batch do 
      deferral.to_h 
    end 
    payload_h = if idx == 0 
      # Return the initial payload like a normal one: 
      result_h 
    else 
      # Transform this hash for the pending @defer spec:
      { incremental: [ result_h.except(:hasNext) ], hasNext: result_h[:hasNext] }
    end 
    # Make it into a multipart payload:
    result_str = JSON.dump(payload_h)
    patch_str = "\r\n---\r\nContent-Type: application/json\r\nContent-Length: #{result_str.bytesize}\r\n\r\n#{result_str}#{result_h[:hasNext] ? "" : "\r\n-----"}"
    response.stream.write(patch_str)
  end
end
```

I bet one of those approaches will do the trick -- want to give them a try? 

As for chrome devtools, I'm not sure -- I develop with Firefox 🙈

**Comment by rmosolgo** [comment]
Great! Glad to hear it. I'm working in an `incremental: true` option which will prepare patches in this new format, then I'll sort out a proper way to integrate with GraphQL::Batch. Hopefully end of this week or beginning of next week I'll release a gem version that includes a "built-in" way to do the same thing we've worked out here :+1:

**Comment by rmosolgo** [comment]
Thanks again for working with me on this! I just pushed v1.24.6 with support for `deferred.stream_http_multipart(response, incremental: true)` for the new format and added documentation for integrating with GraphQL-Batch (see: https://github.com/rmosolgo/graphql-ruby/commit/3f5e22aa6e6d5be450409c64c581fab5ebf62cd0#diff-4705608019c4083cbf4b09c59b9fec5540dceb759265132283ea2dc275035c54R130). 

Please give it a try and let me know if you have any more trouble with it!
