### ISSUE TITLE
Performance bug? Very slow __type introspection

### ISSUE THREAD

**Issue by benhutton** [rmosolgo/graphql-ruby#4478]
**Describe the bug**

The following query spends 10.6ms on `EntryPoints.type` (per Datadog):

```
query EnumIntrospectionTest1 {
      types: __type(name: "AccountTypes") {
        enumValues {
          name
        }
      }
}
```

This seems to be the case for all `__type` introspection, though only happens on the first one. Querying for a second `__type` does not add extra overhead.

We expect that this should take a fraction of the time. Are we doing something wrong? Is graphql-ruby doing something wrong? Is there something that should be happening on-app-boot that is actually happening in each request-response cycle?
 
**Versions**

`graphql` version: 2.0.21

We are a custom ruby/rack app, not using rails

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok). Any custom extensions, etc?

```ruby
class Enums::AccountTypes < Enums::BaseEnum
  graphql_name 'AccountTypes'
  description 'Account types'
  Account::TYPES.each do |type|
    value format(type), "#{type} Account", value: type
  end
end

```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```
query EnumIntrospectionTest1 {
      types: __type(name: "AccountTypes") {
        enumValues {
          name
        }
      }
}
```

Response is correct and includes data I would rather not share. 9 total items

**Steps to reproduce**

Run the query.

**Expected behavior**

I expected this to take much less time.

**Actual behavior**

It took a long time.

![image](https://github.com/rmosolgo/graphql-ruby/assets/61645/b9212d49-7278-4dbd-b49f-669bb80bbaf0)

**Comment by rmosolgo** [comment]
Hi! Sorry for the unpleasant surprise on this. It's because, in order to return a type, GraphQL-Ruby has to check "is this type actually connected to the schema?" which requires traversing the whole schema. (GraphQL-Ruby has ways of hiding types and fields, and those hidden things aren't visible in introspection.) 

Admittedly, this isn't much use if you aren't actually _using_ that visibility feature. Did that inspire your comment here? https://github.com/rmosolgo/graphql-ruby/pull/4442#issuecomment-1548326017

Are you using `.visible?` at all? If not, then making `.warden` a no-op, as proposed in that PR, would work well in your case. If you are, do you mind sharing some details about your setup? Maybe we could come up with a more subtle approach that would work in your case.

**Comment by benhutton** [comment]
thanks @rmosolgo.

One thing I just realized is that I am probably not thinking properly about `visible?` vs. `authorized?`. We do not currently use `visible?` at all.

We use a lot of `def authorized?` methods on most of our mutations, but only on one of our types. In our datadog analysis, we are seeing a lot of time spent checking authorization and are eager to do what we can to minimize that.

Is the warden only dealing with `visible?` and not `authorized?`?

**Comment by benhutton** [comment]
I just ran my query with your `bypass-warden` branch and I save the 10ms I am looking to save!

Unfortunately, when I run my tests against that branch, it breaks a lot of `lookahead` code. I get errors like this:

```
Failure/Error: lookahead = lookahead.selection(:nodes) if lookahead.selects?(:nodes)                                                                                                    
                                                                                                                                                                                              
NoMethodError:                                                                                                                                                                          
  undefined method `original_name' for ["metrics", #<Types::BaseField Partnerships.metrics: PartnershipsMetrics!>]:Array   
```

**Comment by rmosolgo** [comment]
That's great to know -- thanks for sharing what you found. I'll add a test to my branch for the bug you encountered and get it patched up!
