### ISSUE TITLE
When will version 2.0.22 be released

### ISSUE THREAD

**Issue by Bertg** [rmosolgo/graphql-ruby#4479]
I've noticed a lot of work being done since 2.0.21 and was wondering when the next release will be?

From the project files it is unclear what the release target is here. Is it ad-hock, pre planned or every N-days? 
The reason I as is because we are waiting for a recent fix.
I also noticed that [2.0.22](https://github.com/rmosolgo/graphql-ruby/milestone/194) got an other issues added to it, which may delay the release.

To be clear, I'm not pushing for the release to be ASAP, but rather ask for clarity on how releases are managed, or that targeted date for 2.0.22. 

If there is a blocker, can the community help?

**Comment by rmosolgo** [comment]
Hi! There's no fixed release schedule. I cut releases when I know there's something urgent to go out, or I think there are enough changes, or I know someone is waiting on it. I realize you're not pushing for a release ASAP, but as you noticed, there are already plenty of changes on `master` waiting to be released -- I'll get them out later today or tomorrow!

**Comment by rmosolgo** [comment]
I know you weren't asking but .... 🚢 ! https://rubygems.org/gems/graphql/versions/2.0.22
