### ISSUE TITLE
Example of how to return a validation error from a mutation?

### ISSUE THREAD

**Issue by Plummat** [rmosolgo/graphql-ruby#448]
Sorry to use the "issues" like this but can you point me to documentation how to surface validation errors to the client on a mutation?

**Comment by rmosolgo** [comment]
The options inside a mutation resolve function are the same as other resolve functions: http://rmosolgo.github.io/graphql-ruby/queries/error_handling

Please reopen and let me know if that doesn't help for your case!

**Comment by Plummat** [comment]
Thanks!
So there is no way to just send a error response to the mutation query
which would trigger an onFail?

**Comment by nickpoorman** [comment]
@Plummat, you want your mutation resolver to return:

```
GraphQL::ExecutionError.new("Some error")
```

**Comment by Plummat** [comment]
Perfect. thanks Nick!
