### ISSUE TITLE
Scalar coercion context does not have current runtime metadata

### ISSUE THREAD

**Issue by swalkinshaw** [rmosolgo/graphql-ruby#4482]
**Describe the bug**
Runtime metadata is not available in `context` during scalar input coercion. eg: `context[:current_field]` is present during field resolving, but not scalar coercion which is a regression in 2.0.22

This was caused by https://github.com/rmosolgo/graphql-ruby/pull/4456 😅 re-using the cache is great for performance, but I'm assuming the cache was stored at a time when the interpreter runtime information was not present?

**Versions**

`graphql` version: 2.0.22

**GraphQL schema**
This could happen in any schema, but it's easiest to reproduce using the built-in `Int` type since it has integer out of bounds handling: https://github.com/rmosolgo/graphql-ruby/blob/cbdae7612372ac5d4edf04c5e6a2404f8471671c/lib/graphql/types/int.rb#L28

https://github.com/rmosolgo/graphql-ruby/blob/cbdae7612372ac5d4edf04c5e6a2404f8471671c/lib/graphql/integer_encoding_error.rb#L23-L32

```ruby
class QueryRoot < GraphQL::Schema::Object
  field :val, Integer, null: true do |f|
    f.argument :int, Integer, required: true
  end

  def val(int:)
    int
  end
end

class MySchema < GraphQL::Schema
  query_root(QueryRoot)
end
```

**GraphQL query**
```graphql
query {
  val(int: 2147483648)
}
```

**Steps to reproduce**

See the schema and query above.

**Expected behavior**
Exception message should contain field path

**Actual behavior**
Message does not contain field path

**Additional context**
It might be fine to just accept this limitation going forward, but ideally it's documented and the code that relies on this old behaviour is removed.

**Comment by rmosolgo** [comment]
Hmmm ... I guess this is related to the double-coercion of scalar values, where it calls the coercion routine twice. The first time, it's during validation so there's no runtime context. Previously, it wasn't cached, so it would be coerced again. But it's not anymore -- so maybe a "fix" would be to _not_ cache during validation.

**Comment by swalkinshaw** [comment]
Could we still cache during validation but just attach the current context during runtime to still get the benefit of caching?

**Comment by rmosolgo** [comment]
I added a spec like the one you described above, but I found that it returned a static validation error. I'd like to hunt a little more so I can understand what changed and consider fixing it, so I have a couple more questions: 

- Where did you observe the change in error message? Was it in a query response, or in a bug tracker? 
- Was it a problem with _incoming_ scalar values or _outgoing_ ones?

**Comment by swalkinshaw** [comment]
It changed in a unit test which tested input coercion. It looks like this:

```ruby
class QueryRoot < GraphModel::ObjectType
  field :int, Integer, null: false
end

class MutationRoot < GraphModel::ObjectType
  field :make_integer, Integer, null: false do |field|
    field.argument(:integer, Integer, required: false)
  end

  def make_integer(**)
    context[:integer]
  end
end

class Schema < GraphModel::Schema
  query(QueryRoot)
  mutation(MutationRoot)
end

test "logs a warning for overflow on input" do
  query = GraphModel::Query.new(
    "mutation { makeInteger(integer: 29999999992299) }",
    schema: Schema,
    context: { integer: 1 }
  )
  message = "[GraphModel::OutOfBoundsIntHandler] Integer out of bounds: 29999999992299. " \
    "The server may not be handling integer inputs according to the GraphQL specification. " \
    "Consider using GraphApi::Scalars::UnsignedInt64 instead. (while decoding field MutationRoot.makeInteger)"
  assert_logs(:warn, message) do
    query.result
  end
end
```

The failure:
```diff
- "Consider using GraphApi::Scalars::UnsignedInt64 instead. (while decoding field MutationRoot.makeInteger)"
+ "Consider using GraphApi::Scalars::UnsignedInt64 instead."
```

That part is appended by checking `context[:current_field]` just like the built-in https://github.com/rmosolgo/graphql-ruby/blob/cbdae7612372ac5d4edf04c5e6a2404f8471671c/lib/graphql/integer_encoding_error.rb#L23-L32

**Comment by rmosolgo** [comment]
Sorry, I couldn't track down this difference in behavior 😖 I don't have plans to look into it further because I can't think of what else to check, but if there are any other clues you can find, I'd be happy to keep searching.
