### ISSUE TITLE
`IntrospectionQuery` fails when `max_depth` < 13

### ISSUE THREAD

**Issue by RasimKhusaenov** [rmosolgo/graphql-ruby#4484]
**Describe the bug**

I ran into a problem that my Altair GraphQL Client was not displaying documentation. After researching it, I found out that it has to do with the `max_depth` value. Should query respect this value or is there a minimum allowed depth guideline somewhere that I missed?

**Versions**

`graphql` version: 2.0.22
`rails`: 7.0.4.3

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok). Any custom extensions, etc?

```ruby
class ApplicationSchema < GraphQL::Schema
  max_depth 12
  # …
end
```

**Steps to reproduce**

1. Set `max_depth` value to 12.
2. Call
```ruby
YourAppSchema.execute(GraphQL::Introspection.query).to_json
```

**Expected behavior**

It shows my app's API documentation.

**Actual behavior**

What specifically went wrong?

Place full backtrace here (if a Ruby exception is involved):

<details>
<summary>Click to view exception backtrace</summary>

```json
{
  "errors": [
    {
      "message": "Query has depth of 13, which exceeds max depth of 12"
    }
  ]
}
```

</details>

**Additional context**

I tried executing the query (https://github.com/rmosolgo/graphql-ruby/blob/v2.0.22/lib/graphql/introspection.rb) and got the following:
<img width="637" alt="image" src="https://github.com/rmosolgo/graphql-ruby/assets/35406008/6ff9ef41-c615-4af1-b248-0cb62b29405d">

**Comment by rmosolgo** [comment]
This is expected: the `max_depth` setting applies to queries on the root `__schema` fields and other introspection fields. How about changing your `max_depth` to 13 to allow the default introspection query?

**Comment by rmosolgo** [comment]
Ahh thanks for pointing out that doc -- I agree it's not helpful. I added a note about it in 9e6dcd879, thanks for the suggestion!
