### ISSUE TITLE
Tracers not working with Schema::Timeout

### ISSUE THREAD

**Issue by aericson** [rmosolgo/graphql-ruby#4486]
**Describe the bug**

This might be a usage issue and not actually a bug. The following is what I tried:

```ruby
class BaseSchema < GraphQL::Schema
    ...
    use GraphQL::Schema::Timeout
end

class ApplicationSchema < BaseSchema
    tracer GraphQL::Metrics::Tracer.new
end
```

On the above, the call to `tracer` removes the `GraphQL::Schema::Timeout::Trace` from `ApplicationSchema.trace_class.ancestors`.

I've also tried debugging this without the inheritance and a single class which then gave me the message:

``Can't add tracer after configuring a `trace_class`, use GraphQL::Tracing::LegacyTrace to merge legacy tracers into a trace class instead.``

I've tried to add `trace_class(GraphQL::Tracing::LegacyTrace)` but made no difference.

**Versions**

`graphql` version: 2.0.22
`rails` (or other framework): 7.0.4.3

**Steps to reproduce**

I think this test represents the issue, but not 100% sure:

```ruby
    it "issue tracer with trace_with" do
      class ATracer
        def trace(_key, data)
          yield
        end
      end

      parent_schema = Class.new(GraphQL::Schema) do
        trace_with NewTrace1, a: 1
      end

      child_schema = Class.new(parent_schema) do
        tracer ATracer
      end

      child_trace = child_schema.new_trace
      assert_equal({a: 1}, child_trace.trace_opts)
      assert_kind_of NewTrace1, child_trace
      assert_kind_of GraphQL::Tracing::Trace, child_trace
    end
  end
```

**Additional context**
I might be confused about LegacyTrace and `trace_with` usage so this might not be a bug. Any thoughts are appreciated.

**Comment by rmosolgo** [comment]
Thanks for the detailed report -- it's is definitely a bug and should work like you expect! Sorry for the trouble with it. "

Maybe a workable solution will be to covert `LegacyTrace` into a module that can be included alongside other `trace_with ...` modules, calling `tracer`s as part of the tracing stack (but not requiring the choice of one _or_ the other...).
