### ISSUE TITLE
Should `Timeout#max_seconds` be allowed to return a `Float`?

### ISSUE THREAD

**Issue by amomchilov** [rmosolgo/graphql-ruby#4500]
The documented behaviour is that only `[Integer, false]` is supported:

https://github.com/rmosolgo/graphql-ruby/blob/b359fc96933f852fa6c8afa9db1769a4ed027fc0/lib/graphql/schema/timeout.rb#L93-L94

The rest of the code in https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/timeout.rb can already handle a `Float` just fine (and in fact, we've been using a Float in production for months with no issue).

Should I update the docs to widen the support return type to `[Numeric, false]`?

**Comment by rmosolgo** [comment]
:+1: Sounds good!
