### ISSUE TITLE
Found an undocumented usage of subscription

### ISSUE THREAD

**Issue by cpunion** [rmosolgo/graphql-ruby#4501]
I found an undocumented usage of subscripion (or maybe I was missing something), it can simplify works of frontend and backend.

### Scene 1:

Query projects of current user, and subscript updates, we need to create a query and a subscription likes below.

```ruby
module Types
  class QueryType < Types::BaseObject
    field: projects, [Types::ProjectType], null: false
    def projects
      context[:current_user].projects
    end
  end
end

# See https://graphql-ruby.org/subscriptions/subscription_classes.html#extend-the-base-class-and-hook-it-up
module Types
  class SubscriptionType < Types::BaseObject
    field :projects_updated subscription: Types::Mutation::ProjectsUpdated
  end
end
```
And must add a query and a subscription in the page.

There is a simple way, just need a subscription, it receives data when first subscripts and updates then.

```ruby
module Types
  class SubscriptionType < Types::BaseObject
    field :projects, [Types::ProjectType], null: false, subscription_scope: :current_account_id
    def projects
      context[:current_user].projects.reload # Must call reload to send updated data, I think it can be optimized by graphql-ruby?
    end
  end
end
```

Trigger an update:
```ruby
MySchema.subscriptions.trigger(:projects, {}, {}, scope: project.user.id)
```

### Scene 2:

Query and subscription with some arguments, just need a subscription.
```ruby
module Types
  class SubscriptionType < Types::BaseObject
    field :images, [Types::ImageType], null: false do
      argument :projectId, ID, required: true
    end
    def images(projectId:)
      context[:current_user].projects.find(projectId).images.reload # Must call reload
    end
  end
end
```

Trigger an update:
```ruby
MySchema.subscriptions.trigger(:images, {project_id: image.project.id}, {})
```

And there is a scene 3, the subscription with a subscription_scope and some arguments, but I wasn't test.

I'm not sure it's a good way, but it very simple and lightweight for me. @rmosolgo Is it recommended or not recommended?

**Comment by rmosolgo** [comment]
Hey, sorry I didn't respond before -- yes, this is perfectly good way to use subscriptions. `GraphQL::Schema::Subscription` is "sugar" on top of this -- but it boils down to "plain"  GraphQL fields like you're using here :+1:
