### ISSUE TITLE
Decorator Support

### ISSUE THREAD

**Issue by crpahl** [rmosolgo/graphql-ruby#4531]
We have existing decorators in our app that we'd like to use in the resolver layer. Adding a DSL to decorate our types was pretty straight forward and roughly looks like the following:

```
class SomeType < GraphQL::Schema::Object
  decorator SomeDecorator
```

Using that decorator on resolved objects is also straight forward when the resolved value is a single object, or array of objects. Roughly something like the following which is done through a field extension:

```
def after_resolve(context:, value:, **_rest)
  decorator = decorator(field)

  return value if decorator.blank?

  if collection?(value)
    value.each.map do |item|
      decorator.new(item)
    end
  else
    decorator.new(value)
  end
end
```

This won't work when decorating a `value` resolved from a connection field though because the value is a `GraphQL::Pagination::ActiveRecordRelationConnection` in our case. And the code example I have won't work for decorating a connection object. I have a couple approaches in mind and I would love to get your feedback on!

### Decorate the nodes

I can get the actual nodes by calling `value.nodes` and then decorating those. I haven't explored this much though as working with the internal connection object to do this feels _wrong_.

### Use `resolve` instead

By using `resolve`, I would have the type object and could then call `object.object` to get the actual resolved items. I could then decorate those. I haven't explored this too much yet to know how viable that approach is. Also `object` is just an `attr_reader :object`. I could get around this to set the decorated objects, but again this also feels _wrong_.

### Override `initialize`, or `object`

Overriding either of these methods and adding our decorator logic there also works, but again this feels _wrong_.

### Add the ability to control what order extensions are added in

My code snippet _does_ work if:

```
      def extension(extension_class, options = nil)
        extension_inst = extension_class.new(field: self, options: options)
        if @extensions.frozen?
          @extensions = @extensions.dup
        end
        if @call_after_define
          extension_inst.after_define_apply
        end
        @extensions << extension_inst
        nil
      end
```

Is changed to:

```
      def extension(extension_class, options = nil)
        extension_inst = extension_class.new(field: self, options: options)
        if @extensions.frozen?
          @extensions = @extensions.dup
        end
        if @call_after_define
          extension_inst.after_define_apply
        end
        @extensions.prepend extension_inst
        nil
      end
```

This is just a hack I tried quickly to verify that adding the connection extension last would work. It's working because the `value` I get isn't a `GraphQL::Pagination::ActiveRecordRelationConnection`. It's a `Quote::ActiveRecord_AssociationRelation` which I can iterate over and decorate. Is that a possibly reasonable approach: updating the `extension` method to control where in the list the extension is added? I'm not aware of all the other possible consequences of allowing that though.

Or is there some other approach I should be considering here? I've looked at two other open source projects that implement decorators and they both take one of the approaches I've described above so I'm out of ideas myself at this point 😞

**Comment by crpahl** [comment]
I gave it a try and that's exactly what we need 🤩

**Comment by crpahl** [comment]
For our decorator use case, we _may_ want to only decorate for certain fields instead of always decorating the entire object for a type/object. Would it be reasonable and possible to also have a `self.wrap` method on `GraphQL::Schema::Field` as well?

No worries if not!

**Comment by rmosolgo** [comment]
It would be possible, but it limits use of `.wrap` to scenarios where a current field is available. (There's already _one_, which is the root value given to the query. It's wrapped by the Query type, but there isn't a field for it.) I'm interested in exploring other implementations. 

> specific fields instead of all fields on the type

Do you mean, you want the wrapper around the object to only apply for _some_ of the fields on the type? I don't think that will work -- the runtime assumes that each GraphQL selection set has one underlying object. I think you'd have to handle that in your application, for example, by calling in to the decorated object in the resolver. 

Or do you mean that in some cases, you return an object from a resolver but you _don't_ want it decorated? In that case, I'd suggest applying some kind of opt-out wrapper which you could detect later and skip decorating in that case, for example: 

```ruby 
def self.wrap(obj, ctx)
  if obj.is_a?(::DoNotDecorate)
    obj.undecorated_object # the field that returned this said not to use a decorator in this case. 
  else 
    # apply the decorator somehow
  end 
end 
```

Let me know more about what you have in mind and I bet we can find something that works.

**Comment by crpahl** [comment]
> Do you mean, you want the wrapper around the object to only apply for some of the fields on the type? I don't think that will work

Yeah exactly. This isn't a hard requirement for us and more of a nice to have. Here's an example of what our DSL would look like if this was possible (we have a similar DSL that applies authorization to specific fields which we do by using both the Field `#authorized and Type `.authorized` methods):

```
class SomeType < GraphQL::Schema::Object
  decorator SomeDecorator only: [:field_a, :field_b]

  decorator SomeOtherDecorator only: [:field_c, :field_d]
```

In most cases we would just be doing this though I think:

```
class SomeType < GraphQL::Schema::Object
  decorator SomeDecorator
```

Here's a real use case for example:

```
class InvoiceType < GraphQL::Schema::Object
  decorator TaxRateDecorator, only: [:tax_rate]

  field :tax_rate, Types::TaxRateType
  # Bunch of other fields
```

Ultimately, having the ability to do that would just be a nice to have and possibly over engineered honestly.  I was just curious to know if this would be possible with what you're working on. Since it _is_ a decorator, this would still be fine:

```
class InvoiceType < GraphQL::Schema::Object
  # Every field gets an object decorated with tax methods
  decorator TaxRateDecorator
```

Or we could really simplify this and just do:

```
class InvoiceType < GraphQL::Schema::Object
  decorator InvoiceDecorator
```

And just say every type gets its own decorator and leave it to the decorators themselves to share decoration logic somehow (multiple decorators will need to share tax rate methods for example through modules or some other Ruby mechanism).

**Comment by rmosolgo** [comment]
Oh, I see -- I think you'd need a combination of `self.wrap` _and_ field extensions to implement that in a totally "magic" way, since you'd have to apply (or remove) the decorator on a field-by-field basis.  You could do this with `def resolve` in the field extension: 

```ruby 
class DecoratorExtension < GraphQL::Schema::FieldExtension 
  def resolve(object:, arguments:, context:)
    # somehow get the decorator that should apply to the `field` that this extension was attached to 
    decorator_cls = field.owner.decorator_for(field.original_name) 
    if !object.is_a?(decorator_cls)
      inner_object = object.without_decorator # somehow remove the default decorator
      if decorator_cls # don't apply it if the per-field decorator is nil 
        object = decorator_cls.decorate(inner_object) # apply this decorator instead 
      else 
        object = inner_object 
      end 
    end 
    yield(object, arguments, context) # continue resolution with the possibly-reassigned `object`
  end 
end 
```

And you'd want to apply this extension to any field that had a `decorator ...` config, for example: 

```ruby 
class Types::BaseObject < GraphQL::Schema::Object 
  # ...
  
  def field(*args, **kwargs, &block)
    field_instance = super 
    if self.has_per_field_decorators? # somehow check this object type's configuration state
      field_instance.extensions(DecoratorExtension)
    end 
    field_instance 
  end 
end   
```

However, field extensions do add a lot of overhead, so I wouldn't suggest it in performance-critical fields or fields that are resolved a lot of times (1000+?) in a single query. 

I hope that helps! I'll polish up `.wrap` in the meantime.

**Comment by crpahl** [comment]
That helps a lot. Thank you for the support and information!

**Comment by rmosolgo** [comment]
I'll close this since I don't have plans to take further action on it. I'm about to release `.wrap` in 2.0.24. Let me know if you give it a try and run into any trouble with it!
