### ISSUE TITLE
"Failed to implement" when using `method:` and refinements

### ISSUE THREAD

**Issue by mroach** [rmosolgo/graphql-ruby#4532]
**Describe the bug**

We have a GraphQL type for a third party module, `Money` from the ruby-money library.

In various parts of our application we need a "universal format" string. To keep things DRY, we use a module and a Ruby refinement to add this as necessary so we can call `Money#to_universal_s`.

When implementing the field in GraphQL, I defined it as:

```ruby
class Types::Money
  using Formatting::Money
 
  field :universal_format, String, null: false, method: :to_universal_s
end
```

This cause an error:

```
Failed to implement Money.universalFormat, tried:     
   - `Types::Money#universal_format`, which did not exist
   - `Money#to_universal_s`, which did not exist
   - Looking up hash key `:to_universal_s` or `"to_universal_s"` on `1576.00`, but it wasn't a Hash
```

If I add a local resolver method, it works fine:

```ruby
def universal_format = object.to_universal_s
```

**Versions**

`graphql`: 2.0.22
`graphql-pro`: 1.24.7
`graphql-enterprise`: 1.3.1
`rails` 7.0.5
`Ruby` 3.2.2

**GraphQL schema**

Noted in the problem description.

**GraphQL query**

Any query that references the field e.g. `query { purchase { amount { universalFormat } } }`

**Steps to reproduce**

Noted in description

**Expected behavior**

That's a good question. I imagine this fails because the refinement is not in scope when the resolver [checks if the object responds to the method](https://github.com/rmosolgo/graphql-ruby/blob/28bccb5e68dffa95b8d8f452b15ee2ad3541fc0e/lib/graphql/schema/field.rb#L690)

Perhaps due the nature of refinements, this can't work this way and it'll always be necessary to define resolver methods locally in the type? If that's the case, the solution might be noting a caveat in the documentation about using refinements?

**Actual behavior**

When using a field's `method:` config to use a method that's defined in a refinement, resolution fails
When using the same method inside a resolver method, it works.

**Comment by rmosolgo** [comment]
Yeah, as you noted, GraphQL-Ruby's `.respond_to?` check is incompatible with Refinements. I _want_ to like them, but they just never quite work 😖 I think the best thing is a comment in the docs for now. 

In the long term, I can _imagine_ improving the default resolution behavior to be more deterministic, so that if a `method:` is giving, it just calls the method without the `respond_to?` check. This change has been on my mind from a performance standpoint, although, now that I think of it, even _that_ wouldn't work with a Refinement, would it? (Since the call to the method is outside the file scope of the refinement usage.)

**Comment by mroach** [comment]
I also don't think calling the method would work since the refinement isn't activated within the context of graphql-ruby itself. 

`respond_to?` in my limited tests does provide the right answer at least when the refinement is activated:

```
 m = Money.new(100, "EUR")
=> #<Money fractional:100 currency:EUR>
irb(main):018:0> m.respond_to?(:to_universal_s)
=> false
irb(main):019:0> using Formatting::Money
=> main
irb(main):020:0> m.respond_to?(:to_universal_s)
=> true
```

A workaround that I feel is kind of gross but does actually work is to put the `using` statement at the top of the actual Ruby code file and not inside a module or class. 

I don't think there's anything actionable here unfortunately as this is more of a Ruby issue than anything. Feel free to close this :)

**Comment by rmosolgo** [comment]
🥂
