### ISSUE TITLE
Offset argument on connections

### ISSUE THREAD

**Issue by crpahl** [rmosolgo/graphql-ruby#4534]
As you know, connection pagination is really [offset based](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/pagination/relation_connection.rb#L95). We're likely never going to use stable cursors. Due to the way our application is built, stable cursors will cause some challenges for us. So we really like the current offset based approach and we'd like to add an offset argument to connections as well. We also like the cursor based approach which keeps us Relay compliant and makes implementing infinite scrolling very straight forward. So we want the best of both worlds by adding an `offset` argument. This seems possible, but we'd love to get your feedback first to see if this is a sane path to go down.

Essentially what we're thinking of doing is:
- Adding `offset` as an argument to the [existing extension](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/field/connection_extension.rb#L8) in some way.
- Somehow making use of that argument in the [existing pagination classes](https://github.com/rmosolgo/graphql-ruby/tree/master/lib/graphql/pagination) (maybe by converting the `offset` argument to an `after` argument?)
- Possibly using `oneOf` for the pagination arguments to _only_ use one of `offset` or `before/after` (or just add some conditional logic to control this).

Would really appreciate any thoughts you have here! Including if you think this is just a silly path for us to go down 😛

**Comment by crpahl** [comment]
This isn't an approach we'd want to stick with it, but just to experiment more on this, we got it working by defining this extension:

```
class ConnectionWithOffset < GraphQL::Schema::Field::ConnectionExtension
  def apply
    super
    field.argument :offset, "Int", "Returns the elements in the list that come after the specified offset.", required: false
  end

  def resolve(object:, arguments:, context:)
    arguments = arguments.dup
    offset = arguments.delete(:offset)
    arguments[:after] = encode_offset_to_cursor(context, offset) if offset
    super
  end

  private

  def encode_offset_to_cursor(context, offset)
    context.schema.cursor_encoder.encode(offset.to_s, nonce: true)
  end
end
```

And then setting that in our base field:

```
class BaseField < GraphQL::Schema::Field
  connection_extension(GraphqlSchema::Common::Extensions::ConnectionWithOffset)

  ...
end
```

Ideally we'd like to do this through a custom connection, but we've been struggling to find way to make this work with one. We want to use all of the existing connection logic and just add the additional `offset` argument.

**Comment by davidr64** [comment]
We have found a  different possible solution to go through custom connections.
```
class ConnectionWithOffset < GraphQL::Schema::Field::ConnectionExtension
  def apply
    super
    field.argument(:offset, Integer, required: false, description: "Offset description if provided will ignore before and after #do better descripion")
  end

  def resolve(object:, arguments:, context:)
    arguments = arguments.dup
    #strip offset before resolver sees arguments
    context.namespace(:offset_arguments)[:offset] = arguments.delete(:offset)
    super
  end

  def after_resolve(context:, memo:, **kwargs)
    memo[:offset] = context.namespace(:offset_arguments)[:offset]
    super
  end
end

```

We have then useing  a OffsetConnection type
```
class OffsetConnection < GraphQL::Pagination::ActiveRecordRelationConnection
  def initialize(*args, **kwargs)
    @offset = kwargs[:arguments].delete(:offset)
    super
  end

  def after_offset
    @after_offset ||= @offset || after && offset_from_cursor(after)
  end
end
```


in our schema file
```
class Schema < GraphqlSchema::Common::Schema
  connections.delete(ActiveRecord::Relation)
  connections.add(ActiveRecord::Relation, GraphqlSchema::Common::Types::OffsetConnection)
  # we will need to support arrays as well
```

**Comment by rmosolgo** [comment]
:+1: These approaches both make sense to me as how to implement offset-based pagination -- make sense to use the same kind of tools as the built-in pagination implementation. Thanks for sharing what you found!
