### ISSUE TITLE
middleware: NoMethodError  

### ISSUE THREAD

**Issue by bigyansomethingfun** [rmosolgo/graphql-ruby#4538]
Hi, we have a BaseSchema class

```
# frozen_string_literal: true
module Api
  module Schemas
    class BaseSchema < GraphQL::Schema
      ... #other code here
      middleware Api::Middleware::ErrorMiddleware
    end
  end
end
```
The error is `NoMethodError: undefined method 'middleware' for class`

The **ErrorMiddleWare** extends **GraphQL::ExecutionError** something like this

```
class ApiError < GraphQL::ExecutionError
...
end
```
Is the `middleware` function deprecated? Thanks!

**Comment by rmosolgo** [comment]
Yes, `middleware` was deprecated in 1.12.0 (https://github.com/rmosolgo/graphql-ruby/blob/master/CHANGELOG.md#deprecations-6). Although that feature was easy to use, it added a lot of overhead even when it wasn't doing anything. There are a few new features for getting similar behaviors: 

- `rescue_from` adds error handing to query execution: https://graphql-ruby.org/errors/error_handling.html#add-error-handlers
- Field Extensions can wrap specific fields with extra behavior: https://graphql-ruby.org/type_definitions/field_extensions.html (Like middleware, it adds overhead -- but only to the fields you add it to.) 
- Tracing is good for observability but I wouldn't recommend it for error handling: https://graphql-ruby.org/queries/tracing.html

How about trying one of those? I'd be happy to suggest a replacement if you don't mind sharing the source for `ErrorMiddleware`.

**Comment by bigyansomethingfun** [comment]
Hi, our ErrorMiddleware looks something like this:

```
# frozen_string_literal: true

module Api
  module Middleware
    class ErrorMiddleware
      # Extension to gem's class to report backtrace and original error class
      class ApiError < GraphQL::ExecutionError
        attr_reader :original_error

        def initialize(err)
          @original_error = err
          super(OurApp::Errors.extract_message_from(original_error))
          set_backtrace(original_error.backtrace)
        end

        def to_h
          sup = super
          {}.tap do |h|
            h["error"] = original_error.class.name
            h["message"] = sup["message"]
            if (ENV["BACKTRACES_IN_OUTPUT"] == "true") || !Rails.env.production?
              bt = original_error.backtrace
              bt = Rails.backtrace_cleaner.clean(bt) if bt && (ENV["BACKTRACES_CLEANED"] == "true")
              h["backtrace"] = bt
            end
            h.merge!(sup.except("message"))
          end
        end
      end

      class << self
        # Rescue any error and replace it with a {GraphQL::ExecutionError}
        def call(_parent_type, _parent_obj, _field_def, _field_args, context)
          yield
        rescue => e
          if Rails.env.production? # true in all feature and upper envs
            ctx = context.to_h.deep_symbolize_keys.reject do |k, _|
              k.to_s[0..1] == "__" # skip hidden meta fields
            end
            OurApp::Errors.report_error(e, context: ctx)
          end

          ApiError.new(e)
        end
      end
    end
  end
end
```
We were actually using this to handle errors, what do you think would be the best replacement? Many thanks!

**Comment by rmosolgo** [comment]
My first suggestion would be `rescue_from` ([doc](https://graphql-ruby.org/errors/error_handling.html#add-error-handlers). It's available by default in GraphQL-Ruby 2+, but in GraphQL-Ruby 1.9+, you have to add to your schema: 

```ruby 
# Add error handling in 1.9+
use GraphQL::Execution::Errors 
``` 

Then, in your schema: 

```ruby 

  rescue_from(StandardError) do |err, _obj, _args, context, _field|
    if Rails.env.production? # true in all feature and upper envs
      ctx = context.to_h.deep_symbolize_keys.reject do |k, _|
        k.to_s[0..1] == "__" # skip hidden meta fields
      end
      OurApp::Errors.report_error(err, context: ctx)
    end  
    # Raise a graphql-friendly error with a custom message
    raise ApiError.new(err)
  end
```

This will be _slightly_ different than middleware because it covers more parts of GraphQL execution -- it might handle some errors that the middleware above didn't handle. But it's certainly the first thing to try. 

If that's not a good fit, it might work to use a field extension: https://graphql-ruby.org/type_definitions/field_extensions.html. It adds some performance overhead, but probably not more than a Middleware does. For example, you could implement an error handling extension:

```ruby 
In your base field class:
class Types::BaseField < GraphQL::Schema::Field 
  class ErrorHandlingExtension < GraphQL::Schema::FieldExtension 
    def resolve(object:, arguments:, context:)
      yield(object, arguments) # continue field execution 
    rescue => e
      if Rails.env.production? # true in all feature and upper envs
        ctx = context.to_h.deep_symbolize_keys.reject do |k, _|
          k.to_s[0..1] == "__" # skip hidden meta fields
        end
        OurApp::Errors.report_error(e, context: ctx)
      end

      ApiError.new(e)
    end
  end 
  
  def initialize(*args, **kwargs, &block)
    super 
    extension(ErrorHandlingExtension) # add this extension to every field in the schema 
  end 
end 
```

Finally, you could implement `def resolve` in your base field class to include this custom error handling. (In old GraphQL-Ruby versions, you might have to implement `def resolve_field` instead, [source](https://github.com/rmosolgo/graphql-ruby/blob/9dd43ac43161c353991fb88eafe795366e6017ef/lib/graphql/schema/field.rb#L445-L449)). For example: 

```ruby 
def resolve(object, arguments, context)
  super 
rescue => e
  if Rails.env.production? # true in all feature and upper envs
    ctx = context.to_h.deep_symbolize_keys.reject do |k, _|
      k.to_s[0..1] == "__" # skip hidden meta fields
    end
    OurApp::Errors.report_error(e, context: ctx)
  end

  ApiError.new(e)
end
```

It might also work -- but it's not a well supported API. 

Let me know what you think of those approaches!

**Comment by bigyansomethingfun** [comment]
Hi, this worked with some changes, thanks!
