### ISSUE TITLE
Associations loader with merge example

### ISSUE THREAD

**Issue by fedefa** [rmosolgo/graphql-ruby#4540]
**Is your feature request related to a problem? Please describe.**

I want to provide you just a simple implementation of associations loader that merge the results into the data store (using provided merge). This loader must be used only knowing that it's going to retrieve unbounded relationships.

Do you think that should be a valid example to add ?

Thank you so much for developing dataloader!

```
 def fetch(records)
    ActiveRecord::Associations::Preloader.new(records: records, associations: association_name).call
    records.map do |record|
      record.public_send(association_name).tap do |results|
        items = results.respond_to?(:size) ? results : Array.wrap(results)
        results_by_id = items.each_with_object({}) { |item, hash| hash[item.id] = item }
        # Merge the map into the source's cache
        dataloader.with(Sources::Record, record.class.reflect_on_association(association_name).class_name.constantize).merge(results_by_id)
      end
    end
  end
```

**Comment by rmosolgo** [comment]
Hi! Thanks for sharing this. I haven't included a loader for `has_many` relations because I think unbounded loads aren't a great default behavior. But, for someone who didn't mind that, this could be helpful!
