### ISSUE TITLE
use(GraphQL::Tracing::NewRelicTracing, set_transaction_name: true) doesn't work with NewRelic(newrelic_rpm) v9+ 

### ISSUE THREAD

**Issue by codebender** [rmosolgo/graphql-ruby#4546]
**Describe the bug**

`set_transaction_name: true` is not longer working with the latest version of the NewRelic gem(newrelic_rpm).  The transaction name is never set because of changes to the NewRelic gem

I believe I found the PR that changed how the transaction name is set: 

From the [NewRelic ruby agent changelog](https://github.com/newrelic/newrelic-ruby-agent/blame/dev/CHANGELOG.md#L257):
```
Updated API method set_transaction_name

When the method NewRelic::Agent.set_transaction_name is called, it will now always change the name and category of the currently running transaction to what is passed into the method. This is a change from previous agent versions.

Previously, if set_transaction_name was called with a new transaction name and a new category that did not match the category already assigned to a transaction, neither the new name nor category would be saved to the transaction. If this method is being called in a situation in which it was previously ignored due to category differences, this will now change the name and category of the transaction. https://github.com/newrelic/newrelic-ruby-agent/pull/1797
```

**Versions**

`graphql` version:
`rails` (or other framework): 6.1
`newrelic_rpm` version: >= 9.0

**GraphQL schema**

```ruby
class TestSchema < GraphQL::Schema
  use(GraphQL::Tracing::NewRelicTracing, set_transaction_name: true)
end
```

**Steps to reproduce**

- install newrelic_rpm v9+ in the Gemfile 
- set `use(GraphQL::Tracing::NewRelicTracing, set_transaction_name: true)` in the schema and configure NewRelic
- make queries against the schema
- check NewRelic for transaction data

**Expected behavior**

- expect that the query names and mutations to all be recorded as separate transactions in the NewRelic UI

**Actual behavior**

- all graphql transactions are listed as `api/graphql#execute` in the NewRelic UI

**Comment by rmosolgo** [comment]
Hi! Thanks for reporting this. To be clear, if you use NewRelic v8.x, does the transaction name work as you expect?

**Comment by codebender** [comment]
@rmosolgo Yep 8.x is good! We only noticed the issue after upgrading to 9.x

**Comment by rmosolgo** [comment]
Thanks for sharing what you found! I don't think there's anything further to do on GraphQL-Ruby for this, so I'll close it out :+1:
