### ISSUE TITLE
PageInfo#total - should it return a total without nodes field or page parameters defined?

### ISSUE THREAD

**Issue by arinhouck** [rmosolgo/graphql-ruby#4547]
**Describe the bug**

When requesting pageInfo.total, shouldn't it return a total count regardless of page, perPage, or nodes being defined?

**Versions**

`graphql` version: 2.0.14
`rails`: 6.1.7.4

**GraphQL schema**

```ruby
    field :categories,
      Types::Category.connection_type,
      null: true,
      description: 'Loads a list of categories.'
```

**GraphQL query**

Both queries below provide `null` total.

**Example 1**
```graphql
{
  categories {
    nodes {
      name
    }
    pageInfo {
      total
    }
  }
}
```

**Response**
```json
{
  "data": {
    "categories": {
      "nodes": [...],
      "pageInfo": {
        "total": null
      }
    }
  }
}
```

**Example 2 (without nodes)**
```graphql
{
  categories {
    pageInfo {
      total
    }
  }
}
```

**Response**
```json
{
  "data": {
    "categories": {
      "pageInfo": {
        "total": null
      }
    }
  }
}
```

**Steps to reproduce**

Run queries from above on any collection type.

**Expected behavior**

When requesting for pageInfo.total and without nodes, page & perPage. I'd expect the following response:
```
{
  "data": {
    "categories": {
      "pageInfo": {
        "total": 1679
      }
    }
  }
}
```

**Actual behavior**

getting `null` on pageInfo.total. Seems to have dependencies.

**Additional context**

Currently the following dependencies must be met:
- page must be defined
- perPage must be defined
- nodes must be defined

This query below is the only way I could achieve what I was looking for which is odd request in my opinion.

```graphql
{
  categories(page: 0, perPage: 0) {
    nodes {
      name
    }
    pageInfo {
      total
    }
  }
}
```

It seems acceptable that a client may want to only request the total and not load any records.
 
You could argue that I hand roll myself outside of connection type but then it's confusing for client side API to have two "total" fields to pull back.

**Comment by rmosolgo** [comment]
Hi! Thanks for the detailed writeup. Taking a quick look, I don't think `PageInfo.total` comes from GraphQL-Ruby. In the library, PageInfo only has `hasNextPage`, `hasPreviousPage`, `endCursor`, and `startCursor`: 

https://github.com/rmosolgo/graphql-ruby/blob/4b85eff435995d099ddce37c946c51ef5b943258/lib/graphql/types/relay/page_info_behaviors.rb#L5-L20

(These fields come from the Relay spec: https://relay.dev/graphql/connections.htm#sec-undefined.PageInfo.Fields) 

I suspect that `PageInfo.total` is defined in your application somewhere and perhaps it needs an update to behave the way you expect! 


Likewise, GraphQL-Ruby adds `first`, `last`, `before` and `after` to connection fields, but not `page` or `perPage`: 

https://github.com/rmosolgo/graphql-ruby/blob/4b85eff435995d099ddce37c946c51ef5b943258/lib/graphql/schema/field/connection_extension.rb#L7-L12

I hope you can track those down in your app and find a fix! Please let me know if you find further reason to think that these behaviors come from GraphQL-Ruby and I'll take another look :+1:

**Comment by arinhouck** [comment]
@rmosolgo Oh gosh! I'm so naive and new to GraphQL ruby I totally assumed it was apart of the package. You are right. I'll dig deeper as we do override the default behavior. Thanks so much for the quick feedback.
