### ISSUE TITLE
Support GraphOS Tracing for Apollo Studio

### ISSUE THREAD

**Issue by mjfaga** [rmosolgo/graphql-ruby#4549]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to leverage Apollo Studio for monitoring and analyzing GraphQL requests against my Rails GraphQL server.

**Describe the solution you'd like**

A custom tracer that matches the [recommended format for pushing metrics to GraphOS](https://www.apollographql.com/docs/graphos/metrics/sending-operation-metrics/#adding-support-to-a-third-party-server-advanced).

**Describe alternatives you've considered**

* Using a different analytics provider (though there are additional implications like breaking change protection, etc). While these exist in other solutions, I've found Apollo's implementation to be more robust.

**Additional context**

I currently work at [Hunt Club](https://www.huntclub.com) and we are a GraphQL Pro license holder.

**Comment by olivierbuffon** [comment]
+1 my team and I would be super interested as well

**Comment by rmosolgo** [comment]
Hey, thanks for the suggestion. I agree that this would be a good addition to GraphQL-Ruby. I'll take a look at the reporting requirements and follow up here!

**Comment by rmosolgo** [comment]
This is ... _intense_. It's not like sending some custom metrics by the ruby DataDog agent or NewRelic agent -- you've got to _write_ the agent: protobuf client, HTTP communications, batching, signature generation ... phew! It would be  quite a bit of work. I'm open to including it in this library or in a different gem, but I probably won't be able to make time for it for a while. I'm happy to keep this issue open for visibility and further discussion in the meantime.

**Comment by mjfaga** [comment]
Yeah, totally fair. I saw the same thing and decided to open this issue to see if you would land on the same thing or would see something I didn’t 😂

Depending on where we go with things here at Hunt Club, we may make this investment. Given the dependencies required, a separate gem feels appropriate here so that the base implementation doesn't carry that around. 

Cool keeping open for now and we can coordinate as needed 👍

**Comment by olivierbuffon** [comment]
@rmosolgo I started working on it few days ago and like you said it could be intense! 😄 
But anyway I can definitely try to help on this in the comming weeks. It's not a promess since I'm quite busy on my side too but I'll do my best to open a PR as soon as I've something acceptable 😅.
@mjfaga keep this feed updated if you guys decide to look into this too!

**Comment by smyrick** [comment]
Hey there! I am a Solutions Architect at Apollo and I just wanted to chime in to say that we actually don't expect many GraphQL libraries to adopt sending metrics to GraphOS. Instead we make it easier by shipping all this code in the Apollo Router and it can be the central place to track operation usage and talk with GraphOS. You event don't need to use Federation at all to use the Router and track you Ruby servers operations.

What can be additionally supported though is federated tracing (ftv1). Today that is handled by an extension library https://github.com/Gusto/apollo-federation-ruby/

That library is implementing the extra metrics here: https://www.apollographql.com/docs/federation/metrics/

With that Federation library + Apollo Router you will be able to 
* See operation count
* See the operations coming in
* See the clients making request
* Track the field/resolver level timing and timings across subgraphs
* Run schema checks through GraphOS to validate breaking changes

-------

What could be considered for this library is to add the Federation support as first-party support so server maintainers don't need to include two Ruby libraries to do Federation GraphQL

**Comment by olivierbuffon** [comment]
@smyrick Nice! Thanks for this great feedback, I'll definitely look into it!

**Comment by rmosolgo** [comment]
Implementing a client is beyond _me_ (and maybe beyond the scope of this library) so I'll close this issue. If anyone finds a good solution for Ruby, please let me know so that we can add it to the docs!
