### ISSUE TITLE
No such type XXXX, so it can't be a fragment condition

### ISSUE THREAD

**Issue by mackeee-orange** [rmosolgo/graphql-ruby#4555]
**Describe the bug**

I'm using this gem in medium sized application(Already deployed at production).
I added object types as usual.
However, the defined object type was not recognized.
When I tried to call query to get the CandidateThread object in id, I get error message "No such type CandadateThread, so it can't be a fragment condition.

**Versions**

`graphql` version: 2.0.14
`rails` (or other framework): '~> 7.0.0'
other applicable versions (`graphql-batch`, etc)
* graphql-batch (0.5.1)

**GraphQL schema**

```ruby
# app/graphql/types/candidate_thread_type.rb
module Types
  # ofcourse `CandidateThread` model is exist.
  class CandidateThreadType < Types::BaseObject
    implements GraphQL::Types::Relay::Node

    global_id_field :id
  end
end

module Types
  # BaseObject
  class BaseObject < GraphQL::Schema::Object
    include GraphqlAuthenticatable
    include Helpers::ContextAccessHelper

    prepend Coadmap::Graphql::Present

    field_class Types::BaseField
    connection_type_class(Types::Connections::BaseConnectionType)
  end
end

class ApplicationSchema < GraphQL::Schema
  include ::GraphqlExceptionHandler

  mutation(Types::MutationType)
  query(Types::QueryType)

  use GraphQL::Batch
  connections.add(ActiveRecord::Relation, Coadmap::Graphql::Pagination::ActiveRecordRelationConnection)

  class << self
    def resolve_type(_type, obj, _ctx = {})
      Types.const_get("#{obj.class}Type")
    end

    def object_from_id(node_id, _ctx = {})
      type_name, object_id = self::UniqueWithinType.decode(node_id, separator: ':')
      Object.const_get(type_name).find(object_id)
    end

    def id_from_object(object, _type = nil, _ctx = {})
      self::UniqueWithinType.encode(object.class.name, object.id, separator: ':')
    end
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
        query GetCandidateThread($id: ID!) {
          node(id: $id) {
            ...CandidateThreadDetail
          }
        }

        fragment CandidateThreadDetail on CandidateThread {
          id
        }
```
And give variable `id` make with `ApplicationSchema.id_from_object(candidate_thread, Types::CandidateThreadType)`

```json
{
    "errors": [
        {
            "message": "No such type CandidateThread, so it can't be a fragment condition",
            "locations": [
                {
                    "line": 7,
                    "column": 9
                }
            ],
            "path": [
                "fragment CandidateThreadDetail"
            ],
            "extensions": {
                "code": "undefinedType",
                "typeName": "CandidateThread"
            }
        },
    ]
}
```

**Additional Info**
To check typo or some human error, I tried some scripts in rails console.
1. id_from_object / object_from_id => OK
2. `Tyeps::CandidateThreadType.graphql_name`  => `CandidateThread`
3. call the query to get other objects => OK
    e.g.) AccountType
    ```ruby
    module Types
      # Account
      class AccountType < Types::BaseObject
        implements GraphQL::Types::Relay::Node

        global_id_field :id
        field :email, String, null: false
        field :username, String, null: false
    ```

**Comment by rmosolgo** [comment]
Hi! Thanks for the detailed report. I bet the problem is that `CandidateThread` isn't otherwise connected to the Schema, so GraphQL-Ruby doesn't think it should be visible to queries. 

You can fix this by manually attaching it to the schema: 

```ruby 
class ApplicationSchema < GraphQL::Schema
  # ... 
  orphan_types(Types::CandidateThreadType)
  # ...
end 
```

That will tell GraphQL-Ruby to include it in the schema even though it isn't a return type of a field anywhere. (Doc: https://graphql-ruby.org/type_definitions/interfaces#orphan-types)

Does that fix it for you?

**Comment by mackeee-orange** [comment]
@rmosolgo Problem solved!
Thanks for your time and quick response:)
