### ISSUE TITLE
C-Parser coerces zero-padded integers into floats

### ISSUE THREAD

**Issue by gmac** [rmosolgo/graphql-ruby#4556]
**Describe the bug**

Odd outcome with the new C-Parser. Given this input where the argument is type `Int` and the value literal is zero-padded:

```graphql
query {
  withIntArgument(int: 04)
}
```

The C-Parser coerces the value into a _float_, at which time the field fails static validations expecting an integer:

```
Argument 'int' on Field 'withIntArgument' has an invalid value (4.0). Expected type 'Int'.
```

Worth noting that the Ruby parser would fail on zero-padded integers with a syntax error.

**Versions**

C-parser 1.0.4

**GraphQL schema**

```ruby
require "graphql"
require "graphql-c_parser"

class ExampleSchema < GraphQL::Schema
  class Mutation < GraphQL::Schema::Object
    field :gimme_an_int, Int, null: false do
      argument :int, Int, required: true
    end

    def gimme_an_int(int:)
      int
    end
  end

  mutation Mutation
end

puts ExampleSchema.execute(
  query: %|
    mutation {
      gimmeAnInt(int: 04)
    }
  |
).to_h
```

```json
{"errors"=>[{"message"=>"Argument 'int' on Field 'gimmeAnInt' has an invalid value (4.0). Expected type 'Int!'.", "locations"=>[{"line"=>3, "column"=>7}], "path"=>["mutation", "gimmeAnInt", "int"], "extensions"=>{"code"=>"argumentLiteralsIncompatible", "typeName"=>"Field", "argumentName"=>"int"}}]}
```

**Comment by rmosolgo** [comment]
Thanks for the detailed report and sorry for the trouble! I just released graphql-cparser 1.0.5 with a fix for this issue, please let me know if you run into any problems with that version.
