### ISSUE TITLE
Current relay v15 compiler doesn't support `--persist-output` option

### ISSUE THREAD

**Issue by mjfaga** [rmosolgo/graphql-ruby#4557]
**Describe the bug**

`--persist-output` is no longer an option for the relay compiler. Current docs for the compiler are [here](https://github.com/facebook/relay/blob/main/packages/relay-compiler/README.md#supported-compiler-configuration-options).

**Versions**

```
    "react-relay": "15.0.0",
    "relay-runtime": "15.0.0"
```

**GraphQL schema**

N/A

**GraphQL query**

N/A

**Steps to reproduce**

A project set up with the latest version of the relay compiler.

**Expected behavior**

Compilation should generate a persisted queries file that can be used with `graphql-ruby-client sync`.

**Actual behavior**

Relay compiler errors with the following:
```sh
error: Found argument '--persist-output' which wasn't expected, or isn't valid in this context

	If you tried to supply `--persist-output` as a value rather than a flag, use `-- --persist-output`
```

**Additional context**

The working configuration I got things to properly process via a new `relay` section in my package.json:
```json
  "relay": {
    "src": "./src",
    "schema": "./src/schema.combined.graphql",
    "language": "typescript",
    "artifactDirectory": "__generated__",
    "persistConfig": {
      "file": "./persisted-queries.json"
    }
  },
```

I've also verified this configuration works using a `relay.config.json` file as well.

**Comment by rmosolgo** [comment]
Hey, thanks for the detailed report and for sharing what worked for you. I'll keep this open until I update the docs accordingly!
