### ISSUE TITLE
Improve RANGE_ADD support

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#456]
I'm not a Relay user, but I'm aware that it's a bit clunky to define a `RANGE_ADD` mutation, since you have to deal directly with `Connection` and `Edge` instances. It would be nice to make those objects private, as implementation details, but I don't have any insight on how to go about it!

**Comment by rmosolgo** [comment]
Sadly, even the github issue which described this was destroyed when I deleted `graphql-relay-ruby` 😖

**Comment by sgwilym** [comment]
I'll do my best to make a PR for the Relay Mutation docs soon, as we have a couple of these `RANGE_ADD` mutations in production on our GraphQL server.

**Comment by rmosolgo** [comment]
The old (current!) situation is not good: you really have to dig into the internals of `GraphQL::Relay`. What about a first-class API like: 

```ruby
# Adding a comment to list of comments 

# Load the parent:
post = Post.find(args[:postId])

# Load the collection (which will be wrapped by a connection)
comments = post.comments 

# Create the new item:
new_comment = comments.build(body: args[:body])
new_comment.save! 

# Now use an intermediate object (`range_add`) to access Relay objects:
range_add = GraphQL::Relay::RangeAdd.new(collection: comments, item: new_comment)

response = { 
  post: post,
  commentsConnection: range_add.connection,
  newCommentEdge: range_add.edge,
}
```

?

**Comment by rmosolgo** [comment]
It needs to be a little more nuanced to support connection-level settings like 

- max_page_size
- custom edge_class

and a few others, I'll keep looking ...

**Comment by rmosolgo** [comment]
Oh, here's the old issue description in case someone needs an example in the meantime:

> Relay's `RANGE_ADD` mutation requires that the mutation's payload returns a newly created edge. With older versions of this gem and `graphql-ruby`, you could get away with this:
> 
> ```ruby
> CreateChildOnParentMutation = GraphQL::Relay::Mutation.define do
>   name \"CreateChildOnParent\"
> 
>   input_field :parent, !types.ID
> 
>   return_field :parent, ParentType
>   return_field :newChildEdge, GraphQL::Relay::Edge.create_type(ChildType)
> 
>   resolve -> (inputs, ctx) {
>     parent = get_parent_by_id(inputs[\"parent\"])
>     child = child.create(parent: parent)
> 
>     connection = GraphQL::Relay::RelationConnection.new(parent, {})
>     edge = GraphQL::Relay::Edge.new(child, connection)
> 
>     { parent: parent, newChildEdge: edge }
>   }
> end
> ```
> 
> This could quickly break with multiple edge types being created, and looked a little messy manually creating connections and edges. This PR introduces `edge_type` and `Edge.between` to make defining mutations like this a little better:
> 
> ```ruby
>   CreateChildOnParentMutation = GraphQL::Relay::Mutation.define do
>   name \"CreateChildOnParent\"
> 
>   input_field :parent, !types.ID
> 
>   return_field :parent, ParentType
>   return_field :newChildEdge, ChildType.edge_type
> 
>   resolve -> (inputs, ctx) {
>     parent = get_parent_by_id(inputs[\"parent\"])
>     child = child.create(parent: parent)
> 
>     { parent: parent, newChildEdge: GraphQL::Relay::Edge.between(child, parent) }
>   }
> end
> ```

**Comment by rmosolgo** [comment]
🚢  in 1.5.0 via #587
