### ISSUE TITLE
edge_class is populating as nil after 2.x upgrade

### ISSUE THREAD

**Issue by kmcdevitt-rb** [rmosolgo/graphql-ruby#4560]
**Describe the bug**

After upgrading from 1.12.24 to 2.0.24 and opting into the new Connections API, I can't get the `edge_class` to populate with meaningful data, it is always `nil` (see output at bottom).

I've tried lining up my types with the [star wars](https://github.com/rmosolgo/graphql-ruby/blob/master/spec/support/star_wars/schema.rb#L76) specs and other examples, read the changelog and the [Connections docs](https://graphql-ruby.org/pagination/custom_connections). Not sure what I've missed in the upgrade or if `edge_class` is just not behaving as expected?
`DocumentEdge#node` does not appear to be executed, it's not clear if it's necessary or what the replacement is? It appears that's what was providing the node data prior to this upgrade.

**Versions**

`graphql` version: 2.0.24 upgraded from 1.12.24
`rails` (or other framework): 5.2.8
other applicable versions (`graphql-batch`, etc)

**GraphQL schema**

```ruby
class Schema < GraphQL::Schema
  query Types::QueryType
end

module Types
  class QueryType < GraphQL::Schema::Object
    include GraphQL::Types::Relay::HasNodeField
    include GraphQL::Types::Relay::HasNodesField

    field :document_history, Types::DocumentConnectionType, null: true, connection: true
    def document_history
      # backed by ActiveRecord
      ::Document.where(foo: 'bar')
    end
  end

  # connection_type_class
  class DocumentConnectionType < GraphQL::Types::Relay::BaseConnection
    edge_type(DocumentEdgeType, edge_class: DocumentEdge, nodes_field: false)
  end

  # edge_type_class
  class DocumentEdgeType < GraphQL::Types::Relay::BaseEdge
    node_type(DocumentType)
  end

  # edge_class
  class DocumentEdge < GraphQL::Pagination::Connection::Edge
    def node
      # BORK? this is never hit.
      Models::Document.new(@node)
    end
  end

  # node_type
  class DocumentType < GraphQL::Schema::Object
    implements GraphQL::Types::Relay::Node

    global_id_field :id
    field :item_count, Int, null: false
  end
end
```

**GraphQL query**

```graphql
query test($first: Int!) {
  DocumentHistory(first: $first) {
    edges {
      node {
        id
        itemCount
      }
    }
  }
}
```

```json
{
  "data": {
    "first": 2
  }
}
```

**Steps to reproduce**

I'm calling `Schema.execute` from rspec, not sure what other info I could provide, but happy to do so :)

**Expected behavior**

Nodes to contain meaningful data

```
{
  "DocumentHistory" => {
    "edges"=>[
      { "node"=>{ "id"=>1, itemCount=>1 } },
      { "node"=>{ "id"=>2, itemCount=>1 } }
    ]
  }
}
```

**Actual behavior**

Nodes are completely nil. No errors, warnings, deprecations etc.
```
{
  "DocumentHistory"=>{
    "edges"=>[
      {"node"=>nil},
      {"node"=>nil}
    ]
  }
}
```

**Comment by rmosolgo** [comment]
Hi! Thanks for the detailed report. I'm not sure what's wrong though 😖  I wrote up a minimal replication and it worked as you expected (and I expect): 

```ruby
require "bundler/inline"

gemfile do
  gem "graphql", "2.0.24"
end


class MySchema < GraphQL::Schema
  class ThingWrapper < GraphQL::Pagination::Connection::Edge
    def node
      {
        name: @node[:name].upcase
      }
    end
  end

  class Thing < GraphQL::Schema::Object
    field :name, String
  end

  class ThingEdge < GraphQL::Types::Relay::BaseEdge
    node_type(Thing)
  end

  class ThingConnection < GraphQL::Types::Relay::BaseConnection
    edge_type(ThingEdge, edge_class: ThingWrapper, nodes_field: false)
  end

  class Query < GraphQL::Schema::Object
    field :things, ThingConnection

    def things
      [{name: "Toothbrush", name: "Bucket"}]
    end
  end

  query(Query)
end

pp MySchema.execute("{ things { edges { node { name } } } }").to_h
# {"data"=>{"things"=>{"edges"=>[{"node"=>{"name"=>"BUCKET"}}]}}}
```


Out of curiousity, does `DocumentEdge#initialize` ever get called? For example, if you add: 

```ruby
class DocumentEdge < GraphQL::Pagination::Connection::Edge 
  def initialize(node, connection)
    p [self.class, node, connection]
    super 
  end 
end 
```

Does that print each node, as expected? (My best guess at debugging is to start climbing "up" the chain and figure out where it stops behaving like we expect. Maybe then we can find a clue to what might be making it act that way!)

**Comment by rmosolgo** [comment]
Let me know if you want to debug this any further! Til then, I'll close this out.
