### ISSUE TITLE
undefined method `to_type_signature' for #<LateBoundType @name=__Field>

### ISSUE THREAD

**Issue by bigyansomethingfun** [rmosolgo/graphql-ruby#4561]
**Describe the bug**

In `lib/graphql/schema/member/has_arguments.rb`, I am trying to print:

```
        def argument(*args, **kwargs, &block)
          puts "kwargs before is>>> #{kwargs.inspect}"
          kwargs[:owner] = self
          puts "kwargs inspect >>>#{kwargs.inspect}"
          loads = kwargs[:loads]
          ....
          
```          
It works for first 6-7 values, then after

```
kwargs before is>>> {:required=>false, :default_value=>false}
```
When it should print, the `kwargs after`, I get the error,

` NoMethodError: undefined method to_type_signature for #<LateBoundType @name=__Field>` 

I am not sure why it fails for this particular `kwargs`. 

Printing `self.inspect` returns `fields`. Any help would be appreaciated. Thanks!

Edit: I think I should clarify what I aim to solve.

We have a helper for our test, that looks like:

```
  let(:instance) do
    described_class.new(
      params, context:       GraphQL::Query.new(schema, context: {}).context,
              defaults_used: {}, ruby_kwargs:params
    )
  end
  
  ```
  `described_class` is `AbcInput` which is an extension of `GraphQL::Schema::InputObject`. The reason I went that deep into the source code is because, somehow, the as:: keyword is not being used by GraphQL.
  
  For example, we have something like this in `AbcInput`:
  
  `argument :line1, String, required: true, as: :address_line_1`
  
 and when I pass the `params` as:
 ```
 let(:params) do
      {
        line1: "1675 Larimer St",
       
      }
    end
 ```   
I expect `instance.to_h` to be:

` {:address_line_1=>"1675 Larimer St"} `

but instead i get `{:line1=>"1675 Larimer St"}`. I am just not sure, why the as:: is not used. 

This works fine in 1.x.x versions of GraphQL though.

**Comment by rmosolgo** [comment]
Hi! Sorry for the trouble. It looks like this class is missing that method: 

https://github.com/rmosolgo/graphql-ruby/blob/f05ea569af0ceea6eea41919b7bb61f3eb06f2cd/lib/graphql/schema/late_bound_type.rb#L7

For now, you could add it as a monkey-patch:

```ruby 
# config/initializers/graphql_ruby_fixes.rb
# Add this missing method, see graphql-ruby #4561 
class GraphQL::Schema::LateBoundType 
  def to_type_signature 
    name 
  end 
end 
```

I'll add that method soon -- let me know if that patch works for you if you try it out!

**Comment by bigyansomethingfun** [comment]
Hi, could I create a PR for this? I would love to contribute :)

**Comment by bigyansomethingfun** [comment]
Hi thanks! I made that change and now the inspect works but I am still facing the same issue. 

I expect `{:address_line_1=>"1675 Larimer St"}`

but instead i get `{:line1=>"1675 Larimer St"}`. For some reason, the as:: is not being used? Should I open this in a different issue? Thanks!

**Comment by rmosolgo** [comment]
Oh, that's right -- in new versions of the gem, the params are transformed during execution and passed to `InputObject.new` _after_ being renamed. Probably the best thing is to update the example hash in your test. (Initializing InputObjects outside of graphql execution isn't supported 😅 )

**Comment by rmosolgo** [comment]
Hey, I hope you found something that worked for you here! If you run into further trouble, please open a new issue.
