### ISSUE TITLE
Improve "field doesn't exist on type" errors by suggesting camelcasing

### ISSUE THREAD

**Issue by rp-oh** [rmosolgo/graphql-ruby#4563]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I'm making a new endpoint and start testing it out and find that for some reason my field doesn't exist. 99% of the time it's because I'm not context switching from the snake-casing in Ruby to the camel-casing in GraphQL. 

**Describe the solution you'd like**

It would be awesome if the type lookup could check for the correctly cased word and suggest that if it finds it. I think this could happen in 
https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/static_validation/rules/fields_are_defined_on_type.rb#L17-L22
with something like
```
cameled_field_name = camelize_field_name(node.name)
camel_field = context.warden.get_field(parent_type, cameled_field_name)
if camel_field
  # Give the better error, saying "did you mean #{cameled_field_name}"
```
(I assume there is a method to camelize field names somewhere in this codebase since it's doing that automatically)

\
Thanks for all the work!

**Comment by rp-oh** [comment]
I'll see if I can find some free time to make some actual code

**Comment by rmosolgo** [comment]
I'd be happy to review a PR for this, but I don't plan to work on it myself, so I'm going to close the issue.
