### ISSUE TITLE
Extensions only on requests?

### ISSUE THREAD

**Issue by dudo** [rmosolgo/graphql-ruby#4566]
We've created an extension that adds a span to a trace identifying the type making a request. This works lovely for types that are _making_ requests:

![Screenshot 2023-07-25 at 2 53 03 PM](https://github.com/rmosolgo/graphql-ruby/assets/2963800/df539c26-5152-4bc1-a6c9-96eed8268934)

but we're facing a side effect that all return types are also instrumented, which have no usable duration, and it just sorta litters our trace:

![Screenshot 2023-07-25 at 2 56 16 PM](https://github.com/rmosolgo/graphql-ruby/assets/2963800/acc37807-2c9f-4ba4-ad74-56b6c91d3f7b)

Is there a way that we can discern which types to include the extension on, so that we only get "useful" instrumentation?

**Comment by rmosolgo** [comment]
Hi! I'm glad you found something that works for you ... _mostly_ ! I'm sure there's a good way to adapt your customization to make it more useful, but in order to provide practical advice, I'd have to know how your customization is implemented and how it's connected to your schema. Do you mind sharing some details about it? If you don't mind sharing the source code for your custom behavior and some example code of how it's hooked up, that be really helpful.

**Comment by dudo** [comment]
Happy to share!

```rb
module Extensions
  class Feature < GraphQL::Schema::FieldExtension
    def resolve(object:, arguments:, **_rest)
      instance_options = instance_options(object, arguments)

      Chime::Atlas::Feature.trace(
        **instance_options,
        operation: Chime::Atlas::Feature::REQUEST_OPERATION,
        on_error: method(:handle_exception!),
      ) do
        span = Datadog.tracer.active_span

        promise = yield(object, arguments)
        return promise unless promise.is_a?(Concurrent::Promise)

        promise.catch { |exception| handle_exception!(span, exception) }
      end
    end

    private

    def instance_options(object, arguments)
      options.each_with_object(options.dup) do |(k, v), o|
        o[k] = v.call(object: object, arguments: arguments) if v.is_a?(Proc)
      end
    end

    def handle_exception!(span, exception)
      return if exception.respond_to?(:expected?) && exception.expected?

      span.set_error(exception)

      raise exception
    end
  end
end
```

We're currently adding this to individual fields that we'd like to instrument. We tested out adding it to our base field object

```rb
module Types
  class BaseField < GraphQL::Schema::Field
    argument_class Types::BaseArgument

    def initialize(*args, camelize: false, **kwargs, &block)
      super
      extension Extensions::Feature
    end
  end
end
```

and this is what produces all the noise (of the return fields being instrumented).

Again, would love to find a way to only get a handle on the fields that... have a resolver? I'm not even sure how to phrase it, but hopefully you get what I'm saying.

Thanks for the help!

**Comment by rmosolgo** [comment]
A good start might be to move your call to `extension Extensions::Feature` into a conditional check, for example: 

```ruby 
if resolver 
  extension Extensions::Feature
end 
```

That would add that extension to the field _only_ when the field has an attached Resolver class (Mutations count as resolvers under the hood, too). Depending on what you have in mind, you could change that `if ...` to match your requirement. For example: 

```
if !type.kind.leaf?
  # Add this extension to fields that have subfields 
  extension Extensions::Feature 
end 
```

How about giving something like that a try? If you can provide more examples about where this extension should and shouldn't be attached, we can probably narrow down the `if ...` check more precisely.

**Comment by rmosolgo** [comment]
I hope that worked for you! If you're still looking for something better here, please share what you tried and what happened when you tried it.
