### ISSUE TITLE
[PRO] Configure scalar behavior with schema directives

### ISSUE THREAD

**Issue by zekenie** [rmosolgo/graphql-ruby#4572]
(Hello, we are pro subscribers, even though this isn't a question about a pro feature per se)

I'm looking to create a scalar (for example `HTML`) that can sometimes sanitize the value. I want to configure that behavior with a schema directive. For example, I'd love something like this

```
type Query {
  something: HTML! @sanitize
}
```

I've been trying to implement it by writing to a `context[:sanitize]` hash in my directive implementation. I'm able to access the current `path`. So I can set `context[:sanitize]["Query.something"] = true`. And that seems to work great. The only problem is that in my scalar, I can't for the life of me figure out how to get the current path. I can see the data is set correctly in the context, though. Any advice? Am I even on a smart path here?

**Comment by rmosolgo** [comment]
Hi! Great question. I think you're probably looking for `context[:current_path]` -- that returns the current runtime path, as an array of strings and/or integers. So you could do: 

```
def coerce_result(value, context)
  this_path = context[:current_path]
  if context[:sanitize][this_path]
    # do sanitizing 
  else 
    # don't 
  end 
end 
```

Want to give that a try? Let me know how it goes!

**Comment by zekenie** [comment]
I could have sworn i tried that and found it to be an empty array... let me make sure!

**Comment by zekenie** [comment]
OK! That kind of worked. I expected it to return `["Query.something"]` or `["Query", "something"] but it returned `["something"]`. I think I can work with that, but is that expected?

**Comment by rmosolgo** [comment]
Yes, that's what I expected ... `context[:current_path]` is the current location within the `"data" => { ... }` part of the response hash, so it has strings for each field name in the query and integers for each list index.

**Comment by zekenie** [comment]
I think I can work with that! Thank you so much!

**Comment by zekenie** [comment]
OK, with some playing around in the REPL I got it working great for the `FIELD_DEFINITION` use case. But, I'm struggling to figure out how to handle for `INPUT_FIELD_DEFINITION, ARGUMENT_DEFINITION` (and also trying to understand the difference between those two!).

Here's what I've got for my directive

```
class Directives::Sanitize < GraphQL::Schema::Directive
  locations FIELD_DEFINITION, INPUT_FIELD_DEFINITION, ARGUMENT_DEFINITION
  # Inspired by: https://github.com/rmosolgo/graphql-ruby/blob/27762aa781de5c98039098ca5eaf6bb3fa86702f/lib/graphql/schema/directive/flagged.rb#L9-L21
  def initialize(target, **options)
    if target.is_a?(Module) && !target.ancestors.include?(Sanitize)
      target.include(Sanitize)
    elsif !target.is_a?(Sanitize)
      target.class.prepend(Sanitize)
    end

    super
  end

  module Sanitize
    def self.included(schema_class)
      schema_class.extend(self)
    end

    def sanitize_directive
      self.directives.find { |d| d.is_a?(::Directives::Sanitize) }
    end

    def configure_sanitize(context)
      context[:sanitize] ||= {}
      context[:sanitize][context[:current_field]] = true
    end

    def authorized?(_obj, _args, context)
      return super unless sanitize_directive.present?
      configure_sanitize(context)
      super
    end
  end
end
```

I picked `authorized?` instead of `resolve` because it fires for both the argument use case and the field use case, but the issue is that in either case it registers the field in use, and not the input. For example, consider this schema:

```
type Query {
  argSanitizedFieldNotSanitized(arg: HTML! @sanitize): HTML!
}
````

This ends up registering the _field_ in the `context[:sanitize]` hash and not the input, so when my `HTML` scalar runs, it sanitizes the output and not the input. For context, here's the scalar. 

```
class Scalars::Html < Types::BaseScalar
  graphql_name "HTML"

  def self.coerce_input(input_value, context)
    should_sanitize = context.dig(:sanitize, context[:current_field])
    return ::Sanitize.html(input_value) if should_sanitize
    input_value
  end

  def self.coerce_result(ruby_value, context)
    should_sanitize = context.dig(:sanitize, context[:current_field])
    return ::Sanitize.html(ruby_value) if should_sanitize
    ruby_value
  end
end
```

`should_sanitize` is never true in `coerce_input`

**Comment by zekenie** [comment]
Hey, just wanted to follow up, the above is a little long, so I think my open question can be boiled down to:

How do I make schema directives that consistently configure metadata that drives the behavior of scalars–both for fields and arguments? And, if the answer is "there's not a great way to do that," that's OK too!

**Comment by zekenie** [comment]
If I wanted to restrict the usage of the directive to only work on `HTML` fields, would that be possible? Or, if it was applied to non-html fields, it would do nothing?  Maybe something in `initialize(target, **options)` could let me know the type of the field/argument?

**Comment by zekenie** [comment]
that worked! if there was a good way to configure the behavior to only apply to certain scalars that'd be awesome. if not i think we can rely on common sense and code review

**Comment by rmosolgo** [comment]
Yep, you have `target` which is the field or argument, so you could check the configured type with: 

```ruby 
if target.type.unwrap == Types::HTML 
  # ... 
end 
```

(`.unwrap` would take away any list or non-null type modifiers, so it would also match `HTML!` or `[HTML]!`, etc)

**Comment by zekenie** [comment]
Thank you!
