### ISSUE TITLE
Default register_connection_implementation should not overwrite

### ISSUE THREAD

**Issue by Aryk** [rmosolgo/graphql-ruby#4573]
**Describe the bug**

After I upgrading to 1.13.19, I noticed that my connection implementation for Sequel::Dataset was not being used. 

I then found out that it was because it was getting overwritten when RelationConnection would get loaded in. register_connection_implementation

The implementation of the user should always take precedent and should not require one to have to `require "graphql/relay/relation_connection` to make sure it gets overwritten.

**Versions**

`graphql` version: 1.13.19
`rails` (or other framework): 7
other applicable versions (`graphql-batch`, etc)

**Proposal 1** 
register_connection_implementation should have an "overwrite" flag used internally which is set to false for defaults. 

```ruby

   def register_connection_implementation(nodes_class, connection_class, overwrite: true)
          if overwrite || !CONNECTION_IMPLEMENTATIONS.key?(nodes_class.name)
            CONNECTION_IMPLEMENTATIONS[nodes_class.name] = connection_class
          end
        end

## Then in the RelationConnection: 

    if defined?(Sequel::Dataset)
      BaseConnection.register_connection_implementation(Sequel::Dataset, RelationConnection, overwrite: false) # make sure not to overwrite
    end
```

**Proposal 2**
```ruby
   # Just check for the presence of a value there before overwriting it.
    if defined?(Sequel::Dataset) && !BaseConnection::CONNECTION_IMPLEMENTATIONS[Sequel::Dataset.name]
      BaseConnection.register_connection_implementation(Sequel::Dataset, RelationConnection)
    end
```

**Comment by rmosolgo** [comment]
Hi! Sorry for the trouble. Thanks for sharing the work-around you found.

`register_connection_implementation` isn't part of GraphQL-Ruby anymore. A new connections implementation was added several years ago and the old one was removed in GraphQL-Ruby 2.0. (Docs: https://graphql-ruby.org/pagination/custom_connections.html) 

I don't have plans to make changes to 1.13.x, so I'm going to close this out.
