### ISSUE TITLE
Fields validation - only one error at a time, the other errors are ignored

### ISSUE THREAD

**Issue by rwojnarowski** [rmosolgo/graphql-ruby#4582]
**Describe the bug**

According to docs we can validate fields at runtime https://graphql-ruby.org/fields/validation.html . And it works but returns only one error at the time. For example:

```ruby
argument :email,    String, required: true, validates: { format: { with: 'some regex' } }
argument :password, String, required: true, validates: { length: { minimum: 6 } }
```
If i run mutation with both field invalid:
```
mutation {
  signIn(input: { email: "invalid@", password: "12345" }) {
(...)
```
it will result in only one error, from last defined field. I would expect array of errors for email and password.
```
{
  "data": {
    "signIn": null
  },
  "errors": [
    {
      "message": "password is too short (minimum is 6)",
      "locations": [
        {
          "line": 3,
          "column": 3
        }
      ],
      "path": [
        "signIn"
      ]
    }
  ]
}
```

Is this the desired validation behavior? I would expect errors to be returned for the `password` and `email` fields in the same response

**Versions**

`graphql` version: `2.0.26`
`rails` version: `7.0.7`
`ruby` version `3.2.2`

**Comment by rmosolgo** [comment]
Hi! Thanks for the detailed report. I agree that performing more validations would be better -- I didn't _intentionally_ only perform one, but that was the easiest way to implement it...

**Comment by rmosolgo** [comment]
I don't have plans to work on this right now but I'd welcome a PR if anyone gets the chance to improve it!
