### ISSUE TITLE
Allow field complexity calculation procs access to a lookahead instance

### ISSUE THREAD

**Issue by khamusa** [rmosolgo/graphql-ruby#4588]
**Is your feature request related to a problem? Please describe.**

I recently implemented complexity calculation on top of an alternative pagination strategy, and I based my solution on the existing [implementation for connections](https://github.com/rmosolgo/graphql-ruby/blob/15cf025a2fd34518529c95054a10d4be1985ff22/lib/graphql/schema/field.rb#L481).

I originally thought I'd be able to achieve what I needed by just providing a `complexity` proc on the field definition, but I had to override the `#calculate_complexity` method in the Field class instead, as I needed to instantiate a lookahead, which requires an ast_nodes: argument, not available on the `complexity` proc.

**Describe the solution you'd like**

I'd like to be able to access a lookahead in the complexity calculation proc passed when defining a field, since the fact that complexity calculation may depend on the child selections seems like a reasonable assumption.

I could see two possible approaches:
- Allow the `complexity` proc access to `extras` in general (preferred, as a more general solution that could cover more use cases)
- Allow the `complexity` proc access to the `nodes` variable that is available on [#calculate_complexity](https://github.com/rmosolgo/graphql-ruby/blob/15cf025a2fd34518529c95054a10d4be1985ff22/lib/graphql/schema/field.rb#L456), so we can manually instantiate a Lookahead instance

**Describe alternatives you've considered**

I found a solution by overriding `#calculate_complexity`, so I'm not blocked by this. After reading the source code, however, I wondered if there was a strong reason for not passing the `nodes` variable to the complexity proc [here](https://github.com/rmosolgo/graphql-ruby/blob/15cf025a2fd34518529c95054a10d4be1985ff22/lib/graphql/schema/field.rb#L512), as it **seemed** a rather straightforward change. If that is an acceptable solution and there aren't caveats I'm unaware of, I'd be willing to contribute with a PR.

I believe this could lead to a friendlier API for complexity calculation, which could allow us to refactor the adhoc implementation for connections into a Field Extension. We could then deprecate `#calculate_complexity` as a public interface and make it a private API, since the proc would be able to cover all use cases that currently require monkey patching the gem. Let me know if any of this makes sense :)

(once again, thanks for this amazing gem :raised_hands:)

**Comment by rmosolgo** [comment]
Hey, thanks for the detailed writeup and suggestion. 

Honestly, I'm not interested in extending this API further. In general, it's good enough to cover most cases -- this is the first shortcoming I've heard in 7 years 😅 

Beyond those cases, you're better off writing your own system anyways, just like you did. The built-in complexity system is "just" a combination of field configurations, schema configurations, a query analyzer, and a runtime option. So, a custom system can be implemented in the same way, with whatever additional features are required. 

From my perspective, the drawback of breaking code that has worked well for many years isn't worth the benefit in this case. But I'm glad you found a workable solution for your app, and if you'd like to share the details of it, I'd be happy to review and see if I have any further suggestions on it! 

If anyone else finds that these changes to complexity would be helpful, please chime in here.
