### ISSUE TITLE
Fragment-based codegen 

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#459]
I use Immutable.js and it would be nice to generate `Immutable.Record`s from the GraphQL queries that populate them. 

Similarly, you could use fragments to define Ruby classes or Protobuf messages. 

Should graphql-ruby contain tools for this? Or should we wait for a third-party tool (perhaps the "language service") to do it for us?

**Comment by armstrjare** [comment]
Relevant: https://github.com/apollostack/apollo-codegen

**Comment by rmosolgo** [comment]
Cool! I hadn't seen that before, thanks for sharing the link.

**Comment by emilebosch** [comment]
Also relevant: https://github.com/swagger-api/swagger-codegen

**Comment by rmosolgo** [comment]
I'm not able to really work on this, so I'm closing it.
