### ISSUE TITLE
There was an error while trying to load the gem 'graphql'

### ISSUE THREAD

**Issue by FX-HAO** [rmosolgo/graphql-ruby#460]
I get the following error:

    ▶ bundle exec rake spec
    /usr/local/Cellar/ruby/2.3.1/bin/ruby -I/usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib:/usr/local/lib/ruby/gems/2.3.0/gems/rspec-support-3.5.0/lib /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
    Coverage report generated for RSpec to /Users/haofuxin/shundaojia/shundao-backend/coverage. 11 / 56 LOC (19.64%) covered.
    /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'graphql'. (Bundler::GemRequireError)
    Gem Load Error is: uninitialized constant GraphQL::ObjectType
    Backtrace for gem load error is:
    /Users/haofuxin/shundaojia/shundao-backend/lib/graphql/object_type.rb:3:in `<top (required)>'
    /usr/local/lib/ruby/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
    /usr/local/lib/ruby/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
    /usr/local/lib/ruby/gems/2.3.0/gems/graphql-1.2.6/lib/graphql.rb:46:in `<top (required)>'
    /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `require'
    /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
    /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `each'
    /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `block in require'
    /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `each'
    /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `require'
    /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:106:in `require'
    /Users/haofuxin/shundaojia/shundao-backend/config/application.rb:7:in `<top (required)>'
    /Users/haofuxin/shundaojia/shundao-backend/config/environment.rb:2:in `require'
    /Users/haofuxin/shundaojia/shundao-backend/config/environment.rb:2:in `<top (required)>'
    /Users/haofuxin/shundaojia/shundao-backend/spec/rails_helper.rb:3:in `require'
    /Users/haofuxin/shundaojia/shundao-backend/spec/rails_helper.rb:3:in `<top (required)>'
    /Users/haofuxin/shundaojia/shundao-backend/spec/controllers/spree/api/v1/carpool_controller_spec.rb:1:in `require'
    /Users/haofuxin/shundaojia/shundao-backend/spec/controllers/spree/api/v1/carpool_controller_spec.rb:1:in `<top (required)>'
    /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
    /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
    /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
    /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
    /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
    /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
    /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
    /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
    /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/exe/rspec:4:in `<main>'
    Bundler Error Backtrace:
      from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:90:in `block (2 levels) in require'
      from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `each'
      from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:86:in `block in require'
      from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `each'
      from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:75:in `require'
      from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:106:in `require'
      from /Users/haofuxin/shundaojia/shundao-backend/config/application.rb:7:in `<top (required)>'
      from /Users/haofuxin/shundaojia/shundao-backend/config/environment.rb:2:in `require'
      from /Users/haofuxin/shundaojia/shundao-backend/config/environment.rb:2:in `<top (required)>'
      from /Users/haofuxin/shundaojia/shundao-backend/spec/rails_helper.rb:3:in `require'
      from /Users/haofuxin/shundaojia/shundao-backend/spec/rails_helper.rb:3:in `<top (required)>'
      from /Users/haofuxin/shundaojia/shundao-backend/spec/controllers/spree/api/v1/carpool_controller_spec.rb:1:in `require'
      from /Users/haofuxin/shundaojia/shundao-backend/spec/controllers/spree/api/v1/carpool_controller_spec.rb:1:in `<top (required)>'
      from /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
      from /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
      from /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
      from /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
      from /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
      from /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
      from /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
      from /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
      from /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/exe/rspec:4:in `<main>'
    /usr/local/Cellar/ruby/2.3.1/bin/ruby -I/usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib:/usr/local/lib/ruby/gems/2.3.0/gems/rspec-support-3.5.0/lib /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed

I can't find a way to debug this properly, have any idea?

Thanks!

**Comment by FX-HAO** [comment]
Thanks a lot. It works fine.

**Comment by rmosolgo** [comment]
glad to hear it!
