### ISSUE TITLE
fiber-based dataloaders prevent reloading mutated objects

### ISSUE THREAD

**Issue by stevecrozz** [rmosolgo/graphql-ruby#4600]
**Describe the bug**

Mutations can use dataloaders to load objects from arguments, in my case, via the `loads:` argument. For example:
~~~ruby
def self.object_from_id(encoded_id, context)
  context.dataloader.with(Sources::ByGlobalID).load(encoded_id)
end
~~~

Dataloaders can also be used to authorize access to the loaded types before passing the object to the mutation's resolve method. For example:
~~~ruby
def self.authorized?(object, context)
  context.dataloader.with(MyLoader, SomeObject, context[:current_user]).load(object)
end
~~~

Whatever was loaded by dataloaders to prepare for a mutation's invocation, remains cached in that dataloader. Any fields exposed by the mutation can be traversed using regular GraphQL as expected, but any traversal from one type to another that:
A) uses a dataloader
and B) was loaded by that dataloader before the resolve function was called

Cannot be reloaded because the dataloader has that object cached internally.

**Versions**

`graphql` version: 2.0.13
`rails` (or other framework): 6.1.7.4
other applicable versions: using the fiber-based dataloaders provided with the graphql gem

**GraphQL query**

Mutation loads a B object via bId, and the mutation exposes A as a field. Traversing from a -> b in a query results in a stale lookup. In the following case, the old name is still visible.

```graphql
mutation {
  updateBName(input: { bId: "123", name: "new-name" }){
    a {
      b {
        name
      }
    }
  }
}
```

**Expected behavior**

Probably the dataloader cache should be purged directly before or maybe after resolving a mutation, but definitely before resolving the returned fields so that fresh objects can be fetched.

**Actual behavior**

What specifically went wrong?

Stale objects are returned. Mutations should be able to return fields that reflect the updates that were just made.

**Additional context**

Resetting dataloader cache in my own mutation resolve method seems to solve my issue, but its a hack since there is no exposed way to reset the dataloader cache:
`context.dataloader.instance_variable_set(:@source_cache, Hash.new { |h, k| h[k] = {} })`
-or-
`context.dataloader.instance_variable_get(:@source_cache).values.each(&:clear)`

**Comment by rmosolgo** [comment]
Hey, thanks for the detailed report. I agree that there should be some better way to properly clear this cache! I'll investigate some options and follow up here.

**Comment by rmosolgo** [comment]
I think GraphQL-Batch automatically clears all the caches before and after each mutation, that seems like a good approach: https://github.com/Shopify/graphql-batch/blob/main/lib/graphql/batch/mutation_field_extension.rb

**Comment by stevecrozz** [comment]
@rmosolgo That looks great
