### ISSUE TITLE
typo in createRelaySubscriptionHandler: `onComplete` instead of `onCompleted`

### ISSUE THREAD

**Issue by mjfaga** [rmosolgo/graphql-ruby#4604]
**Describe the bug**

When using this handle with the createActionCableHandler, , an error is thrown because it expects the observer object to have an onCompleted method, but onComplete is currently passed from the createRelaySubscriptionHandler.

For reference: [master/javascript_client/src/subscriptions/createActionCableHandler.ts#L60](https://github.com/rmosolgo/graphql-ruby/blob/master/javascript_client/src/subscriptions/createActionCableHandler.ts?rgh-link-date=2023-08-30T17%3A07%3A59Z#L60)

**Versions**

`graphql`: "^16.6.0"
`relay-runtime`: "15.0.0"
`graphql-ruby-client`: "^1.11.8",

**GraphQL schema**

```graphql
type Subscription {
  ping: Ping!
}

type Ping {
  id: ID!
  message: String!
}

```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
  subscription pingDemoSubscription {
    ping {
      id
      message
    }
  }
```

```json
{
  "data": {
    "ping": {
      "id": "1",
      "message": "some message"
    }
  }
}
```

**Steps to reproduce**

# relay-environment config
```js
import createRelaySubscriptionHandler from 'graphql-ruby-client/subscriptions/createRelaySubscriptionHandler';
import {createConsumer} from '@rails/actioncable';

function getSubscriptionHandler() {
  return createRelaySubscriptionHandler({
    cable: createConsumer(FE_WS_ENDPOINT),
    operations: {
      getOperationId: (operationName: string) => {
        return `${CLIENT_NAME}/${OPERATION_STORE[operationName]}`;
      },
    },
    channelName: 'GraphQLChannel',
  });
}

```

**Expected behavior**

Subscriptions should fail on connection

**Actual behavior**

observer.onCompleted does not exist error

**Additional context**

Fixed in https://github.com/rmosolgo/graphql-ruby/pull/4603

**Comment by rmosolgo** [comment]
Hey, thanks for reporting this! I'd like to get it worked out. I'm trying to confirm that `onComplete` is the right name for this, but looking back at old docs, it's hard to tell. This old doc names `onCompleted` _and_ `onComplete`: https://chentsulin.github.io/relay/docs/subscriptions.html. This old source file uses `onCompleted`:  https://github.com/facebook/relay/blob/ebd97cc489ef45bf47df3241706d25bdc5bb7a03/packages/relay-runtime/subscription/requestRelaySubscription.js But I'm not exactly sure that those apply to this case, since there's been so much turn-over in Relay APIs over time. 

Could you please share full error message and backtrace you encountered? That would help me look in the upstream code and make sure we've covered all our bases here.

**Comment by mjfaga** [comment]
Sure thing. See below.
```
Uncaught TypeError: observer.onCompleted is not a function
    at Subscription.received (webpack-internal:///(app-pages-browser)/./node_modules/graphql-ruby-client/subscriptions/createActionCableHandler.js:49:30)
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/@rails/actioncable/app/assets/javascripts/actioncable.esm.js:433:124)
    at Array.map (<anonymous>)
    at Subscriptions.notify (webpack-internal:///(app-pages-browser)/./node_modules/@rails/actioncable/app/assets/javascripts/actioncable.esm.js:433:26)
    at Connection.message (webpack-internal:///(app-pages-browser)/./node_modules/@rails/actioncable/app/assets/javascripts/actioncable.esm.js:279:33)
```

 Just to note, I don't think this has to do with relay's Observer implementation though. Based on what I see, in the `createRelaySubscriptionHandler`, the following [observer wrapper](https://github.com/rmosolgo/graphql-ruby/blob/master/javascript_client/src/subscriptions/createRelaySubscriptionHandler.ts#L53-L64) is defined:
```js
{
            onError: (_error: Error) => {
              observer.error;
            },
            onNext: (res: any) => {
              if (!res || !res.data) {
                return;
              }
              observer.next(res);
            },
            onComplete: observer.complete,
          }
```

That is injected as the 4th value into the handler derived from `createLegacyRelaySubscriptionHandler`, which for us is a `createActionCableHandler`. In that function, the following code is executed on the observer wrapper:
```js
```

**Comment by rmosolgo** [comment]
Ohhh, I see -- thanks for sharing your research on that, it makes sense!
