### ISSUE TITLE
Make tests more approachable 

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#461]
It's great to have good test coverage, but the tests are a real beast. 

- Files are misnamed (the file name doesn't match the constant it "exports") 
- DummySchema has been expanded to test, like, every possible case in the universe 
  - Changes to it mess with all the tests 
  - To change a test, you have to learn this nasty behemoth 

So, I think some changes would be an improvement: 

- Make filenames match their constants (or vice versa, either way) 
- Use more, but smaller, schemas for testing 
  - We have `Schema.from_definition` now which is a great way to make a schema quickly
  - See existing tests for spec-local schemas or schemas shared between only a few tests 

In reality, it's hard for me to prioritize this given the other demands on already-insufficient time, but I thought I'd make an issue in case anyone else had something to add!

**Comment by jsdnxx** [comment]
`Schema.from_definition` is perfect for this sort of thing! Lets you make a very specific schema for just the queries you want to test. This sounds like a great approach to me.

**Comment by rmosolgo** [comment]
I'm keeping this in mind for future tests, especially since `from_definition(default_resolve:)` makes those schemas runnable now 🎉 but I'm not going to allocate time for it as a first-class task so closing this for now :S
