### ISSUE TITLE
Duplicated fields in query cause long processing times, but does not increment query complexity

### ISSUE THREAD

**Issue by jeffgran-dox** [rmosolgo/graphql-ruby#4629]
**Describe the bug**

Given a query with the same field duplicated multiple times:

```ruby
query = <<QUERY
mutation($uuid: Uuid) {
  updateSomething(
    input: {
      uuid: $uuid
    }
  ) {
    #{"success " * 9999}
  }
}
QUERY
```

I expect this field to be "deduplicated" and only run once. But this query takes many seconds to execute, even though it only runs the mutation resolver and `success` method once.

Using a variation of the complexity analyzer from the docs:

```ruby
    class LogQueryComplexityAnalyzer < GraphQL::Analysis::AST::QueryComplexity
      def on_enter_field(node, parent, visitor)
        puts "on_enter_field" # this line is printed 9999 times.
        super(node, parent, visitor)
      end
      def result
        complexity = super
        message = "[GraphQL Query Complexity] #{complexity}}" 
        puts message # prints "[GraphQL Query Complexity]  5"
      end
    end
    query_analyzer(LogQueryComplexityAnalyzer)
```

I note that the AST seems to have parsed the query such that the duplicated field is represented 9999 times. I might expect the parser to deduplicate fields instead of instantiating the whole tree and then somehow skipping the duplicates while visiting them?

**Versions**

`graphql` version: `2.0.8`
`rails`:  `6.1.7.4`
`graphql-pro`: `1.22.2`

**Additional context**

This is relevant because it can be a DOS vector. A bad actor can execute relatively few queries that request any number of a single expensive field, without hitting an http request rate limit or a graphql complexity limit.

**Comment by jeffgran-dox** [comment]
I may have jumped the gun here. With some logging output I am not seeing the mutation resolver running multiple times. But _something_ is running multiple times and eating up CPU time. I'm still digging to find out what it is.

**Comment by rmosolgo** [comment]
Thanks for the detailed report. I'm not surprised that this increases analysis time, since analysis time is based on the document size and structure. For validation, we have [`validate_timeout`](https://graphql-ruby.org/queries/timeout.html#validation), but I don't think this covers analysis.

But I think a timeout is the best option here; I don't really want to mess with the incoming document before analysis (the _point_ of analysis is to see the incoming document), and as you noticed, those duplicate fields in the document aren't executed repeatedly.

**Comment by jeffgran-dox** [comment]
@rmosolgo Thanks for your response. Yes, an `analysis_timeout` could suffice here and maybe that's the way to go. I also had a hand-wavy idea that maybe this document should just be invalid syntactically and not even make it to analysis stage. But I suppose that the graphql spec says we should allow duplicate fields because sometimes queries are stitched together from pieces on the client and may end up with duplicates, or something?
