### ISSUE TITLE
`GraphQL::Schema.from_definition(sdl).to_definition` drops `extend` keyword when it should not

### ISSUE THREAD

**Issue by myronmarston** [rmosolgo/graphql-ruby#4635]
**Describe the bug**

When I have an SDL string with a schema extension, the `extend` keyword gets lost when I parse and dump the SDL using `GraphQL::Schema.from_definition(sdl).to_definition`.  In contrast, it is properly retained when using `GraphQL::Language::Printer.new.print(GraphQL.parse(sdl))`.

**Versions**

`graphql` version: `2.1.0`.
`rails` (or other framework): N/A

**GraphQL schema**

```graphql
  extend schema
    @customDirective

  directive @customDirective repeatable on SCHEMA

  type Query {
    foo: Int
  }
```

**GraphQL query**

N/A

**Steps to reproduce**

Put this Ruby script into a file named `extend_bug.rb`:

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "graphql", "2.1.0"
end

require "graphql"

schema = <<~EOS
  extend schema
    @customDirective

  directive @customDirective repeatable on SCHEMA

  type Query {
    foo: Int
  }
EOS

puts "Parsing and print the schema:"
puts "=" * 60
puts GraphQL::Language::Printer.new.print(GraphQL.parse(schema))

puts
puts

puts "Roundtripping the schema definition:"
puts "=" * 60
puts GraphQL::Schema.from_definition(schema).to_definition
```

Run it to observe the bug.  Here's the output I get:

```
Parsing and print the schema:
============================================================
extend schema
  @customDirective

directive @customDirective repeatable on SCHEMA

type Query {
  foo: Int
}


Roundtripping the schema definition:
============================================================
schema
  @customDirective

directive @customDirective repeatable on SCHEMA

type Query {
  foo: Int
}
```

**Expected behavior**

I expect the schema printed via `GraphQL::Schema.from_definition(sdl).to_definition` to include the `extend` keyword since my schema definition has an extension (and roundtripping it through `parse` + `print` includes it!).

**Actual behavior**

The `extend` keyword is omitted.

**Additional context**

This matters because I've found that other GraphQL SDL parsers give me errors when the `extend` keyword is missing in this case.

It looks like `extend schema` support was added in #4516. I'm not sure why it's not working through `GraphQL::Schema.from_definition(sdl).to_definition`.

**Comment by rmosolgo** [comment]
Thanks for the detailed report. 😅 Yeah, I don't think the schema objects actually _remember_ their `extend ...`s. Those `extend...`s modify the object, but then they're "thrown away," so it's a lossy process, resulting in the inconsistency you found here.

**Comment by rmosolgo** [comment]
The funny thing (😩 ) is that I just did all this work to losslessly re-print schema extensions, then I re-ran your test case above, and found it still failed. In fact, all that was needed in _this_ case was to change the printer a tiny bit! So I did it quickly in b24da546f in that same PR.

**Comment by myronmarston** [comment]
Thanks for tackling this so quickly!
