### ISSUE TITLE
Unclear how to implement edges that cover additional relationship data

### ISSUE THREAD

**Issue by fwolfst** [rmosolgo/graphql-ruby#4638]
**Describe the bug**

The documentation states that Edge can also be used to convey additional information (`User` and `Club`: the `UserEdge` might contain a `joinedAt` field), like in a jointable with additional columns (join-object).

https://graphql-ruby.org/pagination/connection_concepts.html#edges :
> The differences is that edges { node { ... } } has more room for relationship metadata. For example, when listing the members of a team, you might include when someone joined the team as edge metadata:

For this we can implement the Edge class and define fields on it.
```ruby
module Types
  class MemberEdge < Types::BaseEdge
    field joinedAt, String

    def joinedAt
      # ? How to access the "team" here (see example from documentation linked above)
    end
end
```

I see that with `self.node` we can access the `Member` itself, but how to access the `one` in the `one-to-many`, if its not explicitely modeled in the database (e.g. there is no `member.team`, or we have a many-to-many situation and need to know which team we are talking about)?

In the wild in gitlabs code, I see that `extras: [:parent]` is used, but as far as I can tell it can only yield the siblings, not the associated object.

If this is possible it would be great if the documentation that named the Team/Member-example also showed some code to hint on.

Also, how would we implement different Edge-Types for the different join tables (think of a Manager-Member, or Member-Member relation where other meta-data would be needed). I know that we could model that relation (`TeamMembership`, `ManagedPerson`, `Friend`, ...), but I want to explore the Edge-Concept, and adding yet (an)other model(s, that might themselves be node/edge-related) in between might convolut the schema.

**Versions**

`graphql` version: latest (2.1)
`rails` (or other framework): latest (7.0.x)

**GraphQL schema**

**GraphQL query**

Example GraphQL query from docs.

```graphql
team {
  members(first: 10) {
    edges {
      # when did this person join the team?
      joinedAt
      # information about the person:
      node {
        name
      }
    }
  }
}
```

**Comment by fwolfst** [comment]
It seems that `parent.parent` seems to be part of the answer.

**Comment by rmosolgo** [comment]
Yes, that's right, `parent` would probably be the object you want, something like: 

```ruby 
def joined_at 
  membership = parent.memberships.where(person: node)
  membership.created_at 
end 
```

(`parent` would be the `team` in this example.) 

Does that work for you?

I'm not quite sure what you mean about other join tables; do you mind sharing an example query that you'd run in those examples?

**Comment by rmosolgo** [comment]
I hope that was helpful!
