### ISSUE TITLE
Inconsistent return value when hash_key is specified for an array field

### ISSUE THREAD

**Issue by d4rky-pl** [rmosolgo/graphql-ruby#4649]
**Describe the bug**

When a Hash with default values is passed to the object, depending on if `hash_key` is specified explicitly or implicitly the return of array field is either `nil` or `[]`.

**Versions**

The inconsistency was introduced in 2.0.8 and is there until latest version (2.1.0)

**Minimal reproduction**

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'graphql', '2.0.8'
end

class Example < GraphQL::Schema::Object
  field :nil_when_empty, [String, null: true], null: true
  field :array_when_empty, [String, null: true], null: true, hash_key: :nonexistent
end

class Query < GraphQL::Schema::Object
  field :example, Example, null: false

  def example
    Hash.new { [] }
  end
end

class AppSchema < GraphQL::Schema
  query(Query)
end

p AppSchema.execute('query { example { nilWhenEmpty, arrayWhenEmpty } }').to_h
```

**Steps to reproduce**

1. Try the above code with `graphql` gem set to lower version (2.0.7, 1.9.0, you name it)
2. Try the above code with `graphql` gem set to affected version (2.0.8, 2.1.0, etc)

**Expected behavior**

The behaviour is consistent regardless of if `hash_key` is set implicitly or explicitly

**Actual behavior**

One of the fields returns `nil`, another returns `[]`

**Additional context**

Discovered when upgrading the library because we use `.errors.messages.to_h` from ActiveRecord and the Hash returned from this method has the default value set to `[]`

**Comment by rmosolgo** [comment]
Wow -- thanks for the detailed report, what a doozy! This change was definitely accidental. I'll take a look soon and see how the old behavior can be restored.
