### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by andricicezar** [rmosolgo/graphql-ruby#465]
There is any way to use `context.add_error` with an error which is not a ExecutionError? 

The first problem I have is that I should put my error message on the `message` field as a string and then from JavaScript parse it and extract the needed information.

The second problem is that field `errors` is an array of errors and I don't know how to treat an error until I parse the message, or if I search for an error, I should parse all of them.

How can I avoid this two problems?

**Comment by rmosolgo** [comment]
To have complex error support, what about adding an `Error` type to your schema? Then, any relevant types could include an `errors` field which returns `[Error]`. That would give you fine-grained control over how errors are presented to the user. 

I use that approach for Rails validation errors. Would it work in your case?

**Comment by andricicezar** [comment]
Your idea was my first idea, but I am using Relay and I don't want it to think that the request was successful. What I have done, was to standardize and create a big json object which I return and search for it on client. I don't think it is the fastest solution, but it works. What do you think? I will close this.
