### ISSUE TITLE
`GraphQL::ParseError: Unexpected end of document` when triggering a subscription

### ISSUE THREAD

**Issue by eapache-opslevel** [rmosolgo/graphql-ruby#4655]
**Describe the bug**

Gem crashes with `GraphQL::ParseError: Unexpected end of document` when calling `OurSchemaClass.subscriptions.trigger(...)`.

**Versions**

`graphql` version: 2.0.26 (don't see anything relevant in the changelog, but we will try upgrading)
`rails`: 7.0.8

**Steps to reproduce**

Pretty normal call to trigger a subcription. It's happening *inside* another graphql request though, maybe that's causing a state issue?

**Expected behavior**

No crash, the subscription is triggered.

**Actual behavior**

What specifically went wrong?

Place full backtrace here (if a Ruby exception is involved):

<details>
<summary>Click to view exception backtrace</summary>

```
parser.y:472:in `block in parse_document': Unexpected end of document (GraphQL::ParseError)
	from /home/opslevel/vendor/ruby/3.2.0/gems/graphql-2.0.26/lib/graphql/tracing/trace.rb:23:in `parse'
	from /home/opslevel/vendor/ruby/3.2.0/gems/graphql-2.0.26/lib/graphql/tracing/data_dog_trace.rb:47:in `block in parse'
	from /home/opslevel/vendor/ruby/3.2.0/gems/ddtrace-1.12.1/lib/datadog/tracing/trace_operation.rb:191:in `block in measure'
	from /home/opslevel/vendor/ruby/3.2.0/gems/ddtrace-1.12.1/lib/datadog/tracing/span_operation.rb:149:in `measure'
	from /home/opslevel/vendor/ruby/3.2.0/gems/ddtrace-1.12.1/lib/datadog/tracing/trace_operation.rb:191:in `measure'
	from /home/opslevel/vendor/ruby/3.2.0/gems/ddtrace-1.12.1/lib/datadog/tracing/tracer.rb:379:in `start_span'
	from /home/opslevel/vendor/ruby/3.2.0/gems/ddtrace-1.12.1/lib/datadog/tracing/tracer.rb:159:in `block in trace'
	from /home/opslevel/vendor/ruby/3.2.0/gems/ddtrace-1.12.1/lib/datadog/tracing/context.rb:45:in `activate!'
	from /home/opslevel/vendor/ruby/3.2.0/gems/ddtrace-1.12.1/lib/datadog/tracing/tracer.rb:158:in `trace'
	from /home/opslevel/vendor/ruby/3.2.0/gems/ddtrace-1.12.1/lib/datadog/tracing.rb:18:in `trace'
	from /home/opslevel/vendor/ruby/3.2.0/gems/graphql-2.0.26/lib/graphql/tracing/data_dog_trace.rb:36:in `parse'
	from parser.y:470:in `parse_document'
	from parser.y:484:in `parse'
	from /home/opslevel/vendor/ruby/3.2.0/gems/graphql-2.0.26/lib/graphql.rb:46:in `parse'
	from /home/opslevel/vendor/ruby/3.2.0/gems/graphql-2.0.26/lib/graphql/query.rb:407:in `prepare_ast'
	from /home/opslevel/vendor/ruby/3.2.0/gems/graphql-2.0.26/lib/graphql/query.rb:467:in `with_prepared_ast'
	from /home/opslevel/vendor/ruby/3.2.0/gems/graphql-2.0.26/lib/graphql/query.rb:328:in `warden'
	from /home/opslevel/vendor/ruby/3.2.0/gems/graphql-2.0.26/lib/graphql/query/context.rb:314:in `warden'
	from /home/opslevel/vendor/ruby/3.2.0/gems/graphql-2.0.26/lib/graphql/schema/warden.rb:41:in `from_context'
	from /home/opslevel/vendor/ruby/3.2.0/gems/graphql-2.0.26/lib/graphql/schema/member/has_fields.rb:135:in `get_field'
	from /home/opslevel/vendor/ruby/3.2.0/gems/graphql-2.0.26/lib/graphql/schema.rb:559:in `get_field'
	from /home/opslevel/vendor/ruby/3.2.0/gems/graphql-2.0.26/lib/graphql/subscriptions.rb:70:in `trigger'
	...our code that calls trigger
```

</details>

**Additional context**

At a glance:
- `GraphQL::Subscriptions#trigger` creates a dummy Query object with an empty query string to use for context
- It then calls `get_field` with that context
- `get_field` needs to check the field against the warden
- the warden doesn't exist yet so it tries to instantiate it 
- `GraphQL::Query#warden` calls `with_prepared_ast`
- tries to parse the dummy empty string from that `trigger` created, and blows up

I'm not sure how this ever works / is supposed to work?

@rmosolgo

**Comment by eapache-opslevel** [comment]
I guess it can't use `NullContext` because it does need the actual schema reference still...

**Comment by rmosolgo** [comment]
Woah! Thanks for the detailed report. I'm guessing it's choking on this blank query string: 

https://github.com/rmosolgo/graphql-ruby/blob/7c62eb1053f346b420b747a4d37c630b438ab597/lib/graphql/subscriptions.rb#L63-L65

But why _now_ 🤔 !? I don't see anything in the backtrace that changed much lately, but like you said, how did it _ever_ work ...

**Comment by rmosolgo** [comment]
Ah, here's why -- I think it used to be caught by this rescue, which was (properly) made more specific: https://github.com/rmosolgo/graphql-ruby/commit/c437a55d8d865577d04c6c66d12187070721584a 

But how do GraphQL-Ruby's tests still pass?!

**Comment by rmosolgo** [comment]
So, I looked into how GraphQL-Ruby actually works there. It turns out I _do_ find an error rescued here: 

https://github.com/rmosolgo/graphql-ruby/blob/2e267919352d129377dbd0119429d25f68f034ed/lib/graphql/query.rb#L392-L395

But it's rescued there, and pushed into `context.errors`, to be reported to the client later: 

https://github.com/rmosolgo/graphql-ruby/blob/2e267919352d129377dbd0119429d25f68f034ed/lib/graphql/schema.rb#L1002-L1011

I can replicate this error if I re-implement `def self.parse_error` to re-raise, for example: 

```ruby
    def self.parse_error(err, ctx)
      raise err
    end
```

Does your app implement the hook like that? 

If it does, you could work around this issue by adding a flag to your context: 

```ruby 
subscription.trigger(... context: { ignore_parse_error: true })
```

Then check it in your handler: 

```ruby
    def self.parse_error(err, ctx)
      if ctx[:ignore_parse_error]
        super 
      else 
        raise err
      end 
    end
```

Does that work for you? Let me know what you find!

**Comment by eapache-opslevel** [comment]
It's still happening regularly (multiple times per minute), and it's showing up in our datadog integration, attached to the `parse.graphql` span... I wonder if the datadog tracer is picking up the error unnecessarily?

**Comment by DougEdey** [comment]
@eapache-opslevel I suspect this is coming from DataDogs tracing where, even though it's being rescued further up, the specific trace span `lib/graphql/tracing/data_dog_trace.rb` is capturing the exception to the trace
