### ISSUE TITLE
How I should implement pagination?

### ISSUE THREAD

**Issue by andricicezar** [rmosolgo/graphql-ruby#466]
Relay connections require to use `first` and `after` field. I have no idea how to implement the resolve functions for this two arguments. On the `cursor` field I return the object id and what I have in resolve is something simple like this:
```
User
  .order(points: :desc)
  .limit(20)
```

How can I modify this to solve the query correctly?

Thank you!

**Comment by rmosolgo** [comment]
did you see the connection implementation contained in this library? 

http://rmosolgo.github.io/graphql-ruby/relay/connections

It's an offset-based approach which can be subject to bugs, but it's a good starting point!

**Comment by andricicezar** [comment]
I saw it, but I don't really understand how can I implement my cursor. I tried the default connection, which seems to work but I couldn't manage to order the nodes.

**Comment by andricicezar** [comment]
I mean, I tried something like this with the default connection:
```

**Comment by rmosolgo** [comment]
You can define arguments for connection fields. Here's an example of adding a filter: 

http://rmosolgo.github.io/graphql-ruby/relay/connections#connection-fields

You could use the same approach for ordering: define some arguments with `argument`, then apply those arguments in the `resolve` function. 

How does that sound?

**Comment by andricicezar** [comment]
It worked. I missed that paragraph when I was looking. Thank you.
