### ISSUE TITLE
How to trigger a nested subscription type?

### ISSUE THREAD

**Issue by roa-sh** [rmosolgo/graphql-ruby#4665]
Hi, i'm using this syntax: `MySchema.subscriptions.trigger(:updated_user_points, {task_id: task.id}, task)` to notify for a specific task when a field called points change, and it worked correctly.

Now, i'm modifying a little bit the graphql types since rubocop indicated it 
<details> 
<summary>so my subscription type looks something like this:</summary>

```
module Types
  class SubscriptionType < Types::BaseObject

    description "The subscription root of this schema"

    field :updated, Types::UpdatedSubscriptionType, null: false, description: "Update Subscriptions"

    def updated
      Types::UpdatedSubscriptionType
    end
  end
 end
```

</details>

<details> 
<summary>and my user_points field looks like this,</summary>

```
module Types
  class UpdatedSubscriptionType < Types::BaseObject
    field :user_points, ::Types::Task,
          null: false,
          subscription: Subscriptions::UpdatedUserPoints,
          description: 'Updates points for a task'
  end
end
```

</details>
The trigger is not working anymore.

I've tried some alternatives like, 
`MySchema.subscriptions.updated.trigger( {updated: :user_points}, {task_id: task.id}, task)
`
But it didn't work. Do you know how can i trigger it?

**Comment by rmosolgo** [comment]
Hi! Great question. There's no way to do a nested triggers; triggers only correspond to root-level subscription fields. Each root-level subscription field is a kind of event that can be subscribed to. 

So, you should switch the field definition back to the way it was. I hope that helps!
