### ISSUE TITLE
Query complexity check causes wrong GraphQL error response

### ISSUE THREAD

**Issue by mgruner** [rmosolgo/graphql-ruby#4666]
**Describe the bug**

In case of exceptions raised by input types, query complexity is calculated wrong, causing misleading error responses.

**Versions**

`graphql` version: 2.1.3
`rails` (or other framework): 7.0.8

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
query {
  description: ticketArticles(
  ticket: {ticketId: "gid://zammad/Ticket/1"},
  first: 1
) {
  edges {
    node {
      ...
    }
  }
}
```

**Expected behavior**

We have a query with an input type referring to a DB entity (`Ticket`). This is validated for user permissions, an exception is raised in case of unauthorized access.

This query fetches only the first ticket article. In case of authorized access, the article should be returned, in case of unauthorized access a GraphQL error response about unauthorized access.

**Actual behavior**

Authorized access works, but in case of unauthorized access there is a GraphQL error response about exceeded max query complexity, instead of the expected authorization error.

**Additional context**

It seems that `GraphQL::Schema::Field.calculate_complexity` gets it wrong when calculating the complexity of the `connection?` type. The reason is probably that it does not receive any input arguments for the field (specifically also not the `limit:` argument), but instead only the `GraphQL::ExecutionError` object. This means the `limit: 1` is no longer respected, so that the default page size is used to calculate the complexity instead, which leads to the exceeding of the configured max complexity.

**Comment by rmosolgo** [comment]
Hey, sorry I didn't respond to this sooner! I've worked up a fix in #4868 which I will release in 2.2.12 soon.

**Comment by mgruner** [comment]
Thank you @rmosolgo.

**Comment by mgruner** [comment]
@rmosolgo we are seeing the same issue again with a similar query (graphql 2.3.10):

```graphql
query ticketWithMentionLimit(
  $ticketId: ID
  $ticketInternalId: Int
  $ticketNumber: String
  $mentionsCount: Int = null
) {
  ticket(
    ticket: {
      ticketId: $ticketId
      ticketInternalId: $ticketInternalId
      ticketNumber: $ticketNumber
    }
  ) {
    ...ticketAttributes
    createArticleType {
      id
      name
    }
    mentions(first: $mentionsCount) {
      totalCount
      edges {
        node {
          ...ticketMention
        }
        cursor
      }
    }
  }
}
```
Once validation of the ticket input fails (because the ticket does not exist), it seems that the mentionsCount is not respected any longer, leading to the query complexity exceeded error. Looks like it might be very closely related.

**Comment by mgruner** [comment]
Guess I'll open a new bug for this finding.
