### ISSUE TITLE
Wrong number of arguments when calling to_definition in 1.13.20

### ISSUE THREAD

**Issue by JasonBarnabe** [rmosolgo/graphql-ruby#4677]
Calling `schema.to_definition` in 1.13.20 results in:

```
eval error: wrong number of arguments (given 1, expected 0)
  /home/jason/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-1.13.20/lib/graphql/schema/warden.rb:178:in `block in arguments'
  /home/jason/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-1.13.20/lib/graphql/schema/warden.rb:338:in `block in read_through'
  /home/jason/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-1.13.20/lib/graphql/schema/warden.rb:179:in `arguments'
  /home/jason/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-1.13.20/lib/graphql/schema/warden.rb:355:in `block in reachable_type_set'
  /home/jason/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-1.13.20/lib/graphql/schema/warden.rb:354:in `each'
  /home/jason/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-1.13.20/lib/graphql/schema/warden.rb:354:in `reachable_type_set'
  /home/jason/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-1.13.20/lib/graphql/schema/warden.rb:128:in `reachable_types'
  /home/jason/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-1.13.20/lib/graphql/language/document_from_schema_definition.rb:259:in `build_definition_nodes'
  /home/jason/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-1.13.20/lib/graphql/language/document_from_schema_definition.rb:42:in `document'
  /home/jason/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-1.13.20/lib/graphql/schema/printer.rb:51:in `initialize'
  /home/jason/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-1.13.20/lib/graphql/schema/printer.rb:79:in `new'
  /home/jason/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-1.13.20/lib/graphql/schema/printer.rb:79:in `print_schema'
  /home/jason/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-1.13.20/lib/graphql/schema.rb:886:in `to_definition'
```

Debugging shows the `o` variable on [that line](https://github.com/rmosolgo/graphql-ruby/blob/e91d9980ab77c4c0a37eb6733e6ab0da5e7aa44d/lib/graphql/schema/warden.rb#L178) to be `#<GraphQL::Directive include>`.

Did not occur in 1.12.24.

**Versions**

`graphql` version: 1.13.20
`rails`: 7.0.7.2
`graphql-batch`: 0.3.1

**Comment by rmosolgo** [comment]
Hey, thanks again for sharing this. I think there's a bigger issue here, where `.define`-based schemas were accidentally broken in 1.13.x. Are you using `.define` to create your schema and types? (The previous issue also related to that old API)

It's been about two years since I released 1.13.x and this is the first I've heard of it... And although I didn't _mean_ to break this, I'm not sure it'll be worth the game of wack-a-mole to track down the various incompatibilities. 

Is there anything in particular that you're updating to 1.13.x for? Is migrating away from `.define` an option for you?

**Comment by JasonBarnabe** [comment]
I'm trying to migrate to the new API with 1.12, running into some issues, and was hoping that 1.13 would have solved them.

**Comment by rmosolgo** [comment]
> 1.x releases did not drop support for the old API

I was also under that impression 😖  That branch even still has a CI build for legacy APIs, but obviously the test coverage wasn't there. 

Yeah, if you're _working_ on an update, I'd much rather help on that than hunt down little fixes on a very old gem version! Please do open a new issue if you'd like to share any of the trouble you ran into on the upgrade. I'd be happy to help work through them. 

In the meantime, I'm closing this as a wontfix -- unless we determine that finishing the update isn't possible without addressing this issue!
