### ISSUE TITLE
Relay guide problems

### ISSUE THREAD

**Issue by nuclearspike** [rmosolgo/graphql-ruby#468]
Following the steps in [this guide](https://rmosolgo.github.io/graphql-ruby/relay/object_identification) I added the following...

```
GraphSchema = GraphQL::Schema.define do
  query QueryGraph
  mutation MutationGraph

  # Create UUIDs by joining the type name & ID, then base64-encoding it

  id_from_object = ->(object, type_definition, query_ctx) {
    GraphQL::Schema::UniqueWithinType.encode(type_definition.name, object.id)
  }

  object_from_id = ->(id, query_ctx) {
    type_name, item_id = GraphQL::Schema::UniqueWithinType.decode(id)
    type_name.constantize.find(item_id)
  }

end
```

When I run a query against the endpoint, it works. 

But when I add the:

```
  interfaces [GraphQL::Relay::Node.interface]
```

I get: 
```
NotImplementedError - schema contains Interfaces or Unions, so you must define a `resolve_type (obj, ctx) -> { ... }` function:
  graphql (1.3.0) lib/graphql/schema.rb:148:in `define'
```
Which isn't in the guide as something to implement. Does it just return the type from a given UUID? But the error message says it has an object passed in.

And if I add the following to an ObjectType.define block:
```
global_id_field :id
```

I get:
```
NotImplementedError - schema contains `global_id_field`, so you must define a `id_from_object (obj, type, ctx) -> { ... }` function:
  graphql (1.3.0) lib/graphql/schema.rb:148:in `define'
```

But that function is defined, as shown in the first code snippet.

Is there a working, current example repo for implementing relay-compatibility? It seems that a lot of the tutorials out there are from before the relay code was brought in and the code is very different.

**Comment by Willianvdv** [comment]
It should be:
```
  id_from_object ->(object, type_definition, query_ctx) {
    GraphQL::Schema::UniqueWithinType.encode(type_definition.name, object.id)
  }
```
Here is an example: 
https://github.com/rmosolgo/graphql-ruby/blob/5c1269d594ba0150ac67d32aa1e0f953c1daf4ef/spec/support/star_wars_schema.rb#L237

**Comment by rmosolgo** [comment]
I think that's cleared up by #469. I've republished the docs from the `1.3.x` branch. Please let me know if you have any more trouble, sorry about that!!
