### ISSUE TITLE
orphan_types broken after 2.1.2

### ISSUE THREAD

**Issue by Amnesthesia** [rmosolgo/graphql-ruby#4681]
**Describe the bug**

Up until 2.1.1 `orphan_types` work as expected but for some strange reason, it has never worked for enums. We work around this by including enums in an object type that we reference in `orphan_types`, because we need those enums in our schema anyway. However, as of 2.1.2, `orphan_types` doesn't work *at all*, and none of our referenced types are included in orphan types, breaking our codegen typescript types as well

**Versions**

`graphql` version: 2.1.1
`rails` (or other framework): 7.0.8
other applicable versions (`graphql-batch`, etc)

**Steps to reproduce**

Reference an object type under `Schema#orphan_types` and run `graphql:schema:dump` 

**Expected behavior**

We expect referenced orphan_types to be contained within the schema

**Actual behavior**

Referenced orphan types are not in the schema

**Comment by rmosolgo** [comment]
Hi! Sorry for the trouble and thanks for the write-up. I _did_ prepare a visibility fix in 2.1.2 (#4589) and maybe that's what changed the behavior here. 

In general, I _wouldn't_ expect unreferenced types to appear in the schema dump, so I'm surprised they ever did. I certainly don't have any tests for that behavior in the gem 🙈  (`orphan_types` is really for object types which are only connected to the schema by interfaces...) 

Could you share some details about how you were using these types, even though they weren't inputs or return types in the schema? I'd like to make a way for this to keep working for you, but I don't quite have a vision of the use case.

**Comment by Amnesthesia** [comment]
@rmosolgo We have a lot of enums for different things, some of those using `EnumerateIt`. One of these use cases are custom ways that we inform the user their session is about to expire, by adding metadata to `extensions: {  }` for example:

```
context.add_error(
  ::SessionTimingOut.new(context[:strategy]&.expires_at).to_graphql
)
```

These errors have enum error codes, that we define in:

```
class Types::Errors::ApplicationExceptionType < Types::Base::Object
  implements Types::Errors::ExceptionInterface
  graphql_name 'ApplicationException'
  description %Q(
    This type only exists because graphql-ruby doesn't
    let us add enums to orphan_types, and instead only
    accepts objects. This object is the shape of a GraphQL
    execution error, but references the ExceptionType enum,
    including it in the schema
  )
end


module Types::Errors
  module ExceptionInterface
    include Types::Base::Interface
    description %Q(
      For some reason, only Object types that implement an interface
      will show up if included in orphan_types, so this interface
      just adds the error message and extension code to an error
    )

    field :message, String, null: true,
          description: 'Error message from the exception'
    field :extensions, Types::Errors::Custom::ExtensionsType, null: false,
          description: 'Extensions hash containing the error code for the message'

    orphan_types Types::Errors::ApplicationExceptionType
  end
end

class Types::Errors::Custom::ExtensionsType < Types::Base::Object
  graphql_name 'ApplicationExceptionExtension'
  description 'Hash containing the error type of the exception'
  field :code, Types::Errors::Custom::ExceptionTypeType, null: true
end

class Types::Errors::Custom::ExceptionTypeType < Types::Base::Enum
  graphql_name 'ApplicationExceptionType'
  [
    ::SessionExpired,
    ::AccountDeactivated,
    ::AccountSwitchingFailure,
    ::InsufficientPermissions,
    ::ModificationProhibited,
    ::SessionTimingOut,
    ::SessionInvalid,
  ].each do |error_klass|
    value error_klass.graphql_error_code
  end
end
```

Our `orphan_types` also includes other enums that technically aren't used in the schema because we dont want those fields to throw if there's a typo, but we use these in the frontend for various input fields, such as `Types::Locations::CountryType` which is an enum of our supported countries, and `Types::HealthFunds::Enums::DefaultHealthFundsType` which contains a list of health funds we support. `graphql-codegen` transforms that to typescript enums, which we use in the frontend

**Comment by Amnesthesia** [comment]
@rmosolgo any updates on this? Any way for us to force inclusion of enum types without making mock-resolvers just to include types in our schema? Is there any reason *not* to include enums/interfaces in the schema if they are explicitly passed to `orphan_types` (surely an orphan enum type is still an orphan type, whether or not its an object or an enum)?

Perhaps `orphan_types(..., allow_enums: true)` if its super important to remove them by default?

Otherwise I suppose we can work around it by making mock resolvers, but it seems like something we shouldn't have to do to include whatever types we want in our schema... We're now lagging behind a couple of versions and can't upgrade without either working around or resolving this, and I'm not sure about your reasoning behind this so I'm reluctant to make a PR :)

**Comment by rmosolgo** [comment]
Thanks for the bump on this issue and for outlining a couple more of your use cases. Sorry you've been stuck on upgrading! 

I think the thing to do is: 

- Add a new method, `extra_types ...` which are _always_ present in the schema, regardless of whether or not they are attached to other fields or arguments.  (TODO: should these check `.visible?`)
- Rename `orphan_types` to something like `interface_member_types(...)` (which I _think_ is the only practical use of this method, at this point)
- Make `orphan_types` issue a deprecation warning and call `interface_member_types` 
- Update `GraphQL::Schema::Inteface` the same way (rename the method, add a deprecation warning to the old method) 

I think that would support the cases you've described here (via `extra_types`) while clarifying the intent of the-method-formerly-known-as-`orphan_types` and preserving backwards compatibility. 

What do you think of that? Feel free to take a crack at it if it sounds promising to you, otherwise I'll give it a try in a few days :+1:

**Comment by rmosolgo** [comment]
I worked up a patch in #4781 to address this. @Amnesthesia, what do you think of that approach, would it work for you?

**Comment by Amnesthesia** [comment]
@rmosolgo Hey thanks a lot, I haven't had time to look into it myself yet but this is exactly what we need and this would let us drop our workaround!
