### ISSUE TITLE
Thread.current[:__graphql_runtime_info] is nil in GraphQL::Schema::Field::ScopeExtension#after_resolve in field tests

### ISSUE THREAD

**Issue by xxx** [rmosolgo/graphql-ruby#4683]
_or_: is there a better way to test fields directly for permissions, that doesn't require writing a separate query for each one.

**Describe the bug**

Since updating from 2.0.26, we're seeing failures for lazy fields in tests, due to `Thread.current[:__graphql_runtime_info]` coming back with `nil` in `GraphQL::Schema::Field::ScopeExtension#after_resolve`. Non-lazy fields work fine.

**Versions**

`graphql` version: 2.1.3
`rails` (or other framework): 7.0.8
`graphql-batch`: 0.5.3

Hi, we currently  have a lot of field tests that test the Pundit permissions on fields, via GraphQL-pro.

We're testing like this, essentially:

```ruby
context = { current_user: User.first }
query = GraphQL::Query.new(MySchema, context: context)
instance = Types::PostType.authorized_new(Post.first, query.context)
field = Types::PostType.get_field('title')
arguments = {}
resolved = begin
  result = GraphQL::Batch.batch { field.resolve(instance, arguments, context) }

  # the failure is here on the .value call for `Lazy`s
  result.is_a?(GraphQL::Execution::Lazy) ? result.value : result
end
```

This allows us to switch around users, arguments, etc, in a way that doesn't require the labor of writing and maintaining actual queries for every single case.

The failure is the same error as #4672, but remains when using HEAD of `master`.

Is there a better way to test this? 

I'm currently just monkey-patching around this with a file in `spec/support`, by skipping the block.

```ruby
module GraphqlFieldAfterResolvePatch
  def after_resolve(object:, arguments:, context:, value:, memo:)
    return super if Thread.current[:__graphql_runtime_info]

    if value.nil?
      value
    else
      ret_type = @field.type.unwrap
      if ret_type.respond_to?(:scope_items)
        ret_type.scope_items(value, context)
      else
        value
      end
    end
  end
end

GraphQL::Schema::Field::ScopeExtension.prepend(GraphqlFieldAfterResolvePatch)
```

**Comment by rmosolgo** [comment]
I can't _always_ promise that GraphQL-Ruby's internals will work outside of GraphQL execution, but it was easy enough to maintain compatibility in this case 🍻
