### ISSUE TITLE
Don't Pluralize Names

### ISSUE THREAD

**Issue by aaronmallen** [rmosolgo/graphql-ruby#4695]
**Is your feature request related to a problem? Please describe.**

Its an anti pattern in rails to have pluralized names for classes (i.e. `Types`). Additionally in most cases it doesn't make sense to have the base object or most objects generated by install to live in the root of the graphql folder.  I often find myself creating a folder structure that looks like this:

```
| graphql
--| type
----| field/base.rb
----| input/base.rb
----| object/base.rb
``` 

**Describe the solution you'd like**

I would like the install to not use pluralized naming and I would like the install to throw each object in its own directory inside of the graphql directory as described above.  Generators should be updated to match this pattern as well.

**Describe alternatives you've considered**

Leave it alone

**Additional context**

I am more than happy to put together a pull request if you agree on this enhancement.  But especially for things like enums, scalars, objects, inputs, and interfaces, it makes very little sense for those not to be nested in their own directories, as their is a good chance you'll be creating a good amount of them.

**Comment by aaronmallen** [comment]
Here is an example of what I would like to see this install do:
<img width="385" alt="Screenshot 2023-11-04 at 11 42 34 PM" src="https://github.com/rmosolgo/graphql-ruby/assets/931094/48706929-23b1-4867-bdf7-6c4f85ac6eb8">

And then the classes themselves should look like this:
```
# frozen_string_literal: true

module Type
  module Object
    class Base < GraphQL::Schema::Object
      edge_type_class(Type::Edge::Base)
      connection_type_class(Type::Connection::Base)
      field_class Type::Field::Base
    end
  end
end
```

**Comment by rmosolgo** [comment]
Hi, thanks for the suggestion! I'm interested in sticking to the Rails convention, anti-pattern or not, but I'd welcome the addition of an option (perhaps `--directory` or `--namespace` ?) to control that behavior. Maybe it could even check, and if `app/graphql/type/` already exists, it could default to using that instead of `types/`. What do you think of that solution?

**Comment by aaronmallen** [comment]
> Hi, thanks for the suggestion! I'm interested in sticking to the Rails convention, anti-pattern or not, but I'd welcome the addition of an option (perhaps `--directory` or `--namespace` ?) to control that behavior. Maybe it could even check, and if `app/graphql/type/` already exists, it could default to using that instead of `types/`. What do you think of that solution?

I'm always a fan of free agency
