### ISSUE TITLE
Scoped context doesn't work

### ISSUE THREAD

**Issue by semirart** [rmosolgo/graphql-ruby#4698]
Hi! I'm trying to set context in a parent field and read it in child. I have a query like in [this example](url).
```
{
  posts {
    id # context.scoped_set!(:a, 5)
    comments {
      id # context[:a] => nil
    }
  }
}
```

But the context that is set in resolver is seen in all underlying fields.

I've also checked in another project with graphql 1.13.19, still no luck.

**Versions**

graphql (2.1.6)
rails (7.0.8)
graphql-batch (0.5.3)
action_policy-graphql (0.5.3)

**Comment by rmosolgo** [comment]
Hi! Sorry you had trouble. Could you share the resolver code where you read and write scoped context? Maybe that would give some clues as to why your case doesn't work like this gem's [unit tests](https://github.com/rmosolgo/graphql-ruby/blob/e39b77f830b789f67672fec8772ed7aa1cdb688e/spec/graphql/query/context_spec.rb#L156-L459)

**Comment by semirart** [comment]
Here is a clean [demo app](https://github.com/semirart/graphql_test_app)

Query:
```graphql
query {
  posts {
    title
    comments {
      author
    }
  }
}
```

Result:
```json
{
  "data": {
    "posts": [
      {
        "title": "Post 1",
        "comments": [
          {
            "author": null
          }
        ]
      }
    ]
  }
}
```

Code:
```ruby
module Types
  class QueryType < Types::BaseObject
    field :posts, [Types::PostType], null: true

    def posts
      [
        {
          title: 'Post 1',
          comments: [{
            author: 'default'
          }]
        }
      ]
    end
  end
end

module Types
  class PostType < Types::BaseObject
    field :title, String
    field :comments, [Types::CommentType]

    def title
      context.scoped_set!(:author, 'Author 1')
      context[:author] # => 'Author 1'
      object[:title]
    end
  end
end

module Types
  class CommentType < Types::BaseObject
    field :author, String

    def author
      context[:author] # => nil
    end
  end
end
```

**Comment by rmosolgo** [comment]
Thanks for sharing that example! The problem is that `title` is a leaf field; it has no children. Scoped context is only available in child selections, so setting scoped context in the `title` resolver won't apply anywhere. 

Instead, you'd have to set scoped context in the `def posts` resolver. Here's a working example script with that implementation: 


```ruby
require "bundler/inline"

gemfile do
  gem "graphql", "2.1.6"
end

class MySchema < GraphQL::Schema
  class Comment < GraphQL::Schema::Object
    field :author, String

    def author
      context[:author]
    end
  end

  class Post < GraphQL::Schema::Object
    field :title, String
    field :comments, [Comment]
  end

  class Query < GraphQL::Schema::Object
    field :posts, [Post]

    def posts
      context.scoped_set!(:author, 'Author 1')

      [
        {
          title: 'Post 1',
          comments: [{
            author: 'default'
          }]
        }
      ]
    end
  end

  query(Query)
end


pp MySchema.execute("{ posts { title comments { author } } }").to_h
# {"data"=>{"posts"=>[{"title"=>"Post 1", "comments"=>[{"author"=>"Author 1"}]}]}}
```

You could also use `scoped_set!` in a `def comments` resolver, since `author` is a child field of a comment. 

I hope that helps! Let me know if you have any more trouble with it.

**Comment by semirart** [comment]
Thank you! That was not obvious for me.
What I want to do in this simplified example is memoizing the value in `posts.0.title` to use in its comments. Only if title is used in query. Can I store it somewhere?
I can see the context value in context.scoped internals (when author is evaluated) but its a bit hacky to get it.

I realize that I can also use dataloader cache (in real world I use it) but it's not as convenient as context would be.

**Comment by rmosolgo** [comment]
Besides a custom cache in context and the dataloader cache, no, I can't think of anything _else_ in GraphQL-Ruby that might help with this!
