### ISSUE TITLE
Cannot specify input coercion separately from result coercion

### ISSUE THREAD

**Issue by dylanahsmith** [rmosolgo/graphql-ruby#47]
The [GraphQL specification](http://facebook.github.io/graphql/#sec-Scalars) distinguishes between input and result coercion, but this library doesn't.

Being able to define these separately would be very useful for custom scalar types, since the input coercion can deserialize the value into an appropriate object (e.g. [Time](http://ruby-doc.org/core/Time.html)) for use in the resolver, then result coercion can serialize the value so it can be represented in JSON.  Otherwise, the resolver would always have to explicitly parse the input, so custom scalars would only be useful for validation.

**Comment by rmosolgo** [comment]
:+1: I didn't see the value in both helpers at first, but I get it for custom scalars!

**Comment by rmosolgo** [comment]
Fixed by #48
