### ISSUE TITLE
`prepare: :symbol` syntax looks on the parent object for resolver classes

### ISSUE THREAD

**Issue by eapache-opslevel** [rmosolgo/graphql-ruby#4715]
**Describe the bug**

If you define a mutation or resolver with an argument that uses the `prepare: :method_name` syntax, it looks for that method on the parent object instead of on the mutation/resolver.

**Versions**

`graphql` version: 2.0.27
`rails` (or other framework): 7.1.2

**GraphQL schema**

```ruby
class MyMutation < GraphQL::Schema::Mutation
  argument :foo, ID, required: true, prepare: :some_method
  class << self
    def some_method(in)
      123
    end
  end
end

class MutationRoot < GraphQL::Schema::Object
  field :my_mutation, mutation: MyMutation
end
```

**Behavior**

I would expect `foo` to be prepared by calling `some_method` on `MyMutation` but at https://github.com/rmosolgo/graphql-ruby/blob/109c26c5fa9118a9c69ed4c4823048c1ce1aea6d/lib/graphql/schema/argument.rb#L225 it looks on the object, which is `MutationRoot` (and thus hits `NoMethodError`).

**Comment by eapache-opslevel** [comment]
It might be as simple as switching that call to use `owner` instead? But I'm not sure if that is correct in all cases either, we might have to type-check and switch between `owner` and `obj`?

**Comment by eapache-opslevel** [comment]
> I wonder if there's a way to make this work as expected while preserving a way for existing users to maintain compatibility
Try the resolver-defined-method and if it's not defined fall back to the object-defined-method? Kind of like how we look for resolve methods?

**Comment by DougEdey** [comment]
I took a stab at this since I'm the one that spoke to Evan about it originally, lemme know if I misinterepreted the proposal!
