### ISSUE TITLE
Subscriptions don't handle ActiveRecord::Relations

### ISSUE THREAD

**Issue by apolzon** [rmosolgo/graphql-ruby#4719]
**Describe the bug**
If you pass a field to a subscription trigger call that is an `ActiveRecord::Relation` object (one that has not been resolved to an Array yet), `dump_value` does not handle it properly and the trigger never makes it to the frontend subscriber

**Versions**
Tested with v2.0.13, but verified the code in question is unchanged on current (11/30/2023) master branch

`graphql` version: 2.0.13
`rails` (or other framework): 6.1.7

```ruby
class ProductType < GraphQL::Schema::Object
  field :id, ID, hash_key: :id
  field :title, String
  # …
end

class ApplicationSchema < GraphQL::Schema
  query QueryType
  subscription SubscriptionType
end

class TestSubscription < GraphQL::Schema::Subscription
  field :products, [ProductType], null: true

  def resolve
    TestJob.perform_later
  end
end

class TestJob < ApplicationJob
  def perform
    ApplicationSchema.subscriptions.trigger(:test_subscription, {}, { products: Product.all })
  end
end
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
subscription {
  testSubscription {
    products { id title }
  }
}
```

**Steps to reproduce**
Subscribe to TestSubscription as above, observe no response is received from the trigger in a background job
Update TestSubscription to call `.to_a` on the `Product` relation and see that the frontend successfully receives the event

**Expected behavior**
`GraphQL::Subscriptions::Serialize#dump_value` should auto-convert any ActiveRecord::Relations to Arrays and handle them as such

**Actual behavior**
Passing an ActiveRecord::Relation results in the trigger being lost and never received on the frontend

What specifically went wrong?
The relation was not treated as an Array, so it was not dumped using the GID param

I believe all that is needed is to update #dump_value's Array check to: `if obj.is_a?(Array) || (defined?(ActiveRecord::Relation) && obj.is_a?(ActiveRecord::Relation))`, however since the current test suite does not look to have any database setup, I wasn't sure how you'd like to go about updating the test suite. I'm assuming that since this is only related to return fields that `dump_recursive` does not need to be updated

**Comment by rmosolgo** [comment]
Hey @apolzon, thanks for the great write-up. I agree that this situation should be handled better and I think that your proposed solution would work great. 

To test this, you'd have to add a new folder to `spec/integration/rails`, which contains test files that run when Rails is present. You could make a new `spec/integration/rails/graphql/subscriptions_spec.rb`, and copy a dummy schema out of the existing `subscriptions_spec.rb`, then write a test specifically for ActiveRecord::Relation. If you want to give it a try, I'd be happy to help out if you run into any snags!
