### ISSUE TITLE
NoMethodError: undefined method `validate_input` for invalid variable type

### ISSUE THREAD

**Issue by eapache-opslevel** [rmosolgo/graphql-ruby#4722]
**Describe the bug**

If a user passes a malformed query with a variable type that is a valid object type (instead of an input type):
- executing the query returns the correct graphql-layer error message of `Type isn't a valid input type (on $myVar)`
- however, calling `result.query.variables` crashes with a `NoMethodError`

It looks like the variables constructor code pulls the type from the schema and checks that the type exists https://github.com/rmosolgo/graphql-ruby/blob/52ec07bad6e617ef5d1954d4be13370520e4041f/lib/graphql/query/variables.rb#L28 

But does not check that the type is an input type before calling `validate_input` on it
https://github.com/rmosolgo/graphql-ruby/blob/52ec07bad6e617ef5d1954d4be13370520e4041f/lib/graphql/query/variables.rb#L38

**Versions**

`graphql` version: 2.0.27

**GraphQL query**

```graphql
# Account is an output type, not an input type
query ($test: Account!) {
  account {
    id
  }
}
```

The variable must be present (though it can be anything) to trigger the error:
```json
{
  "test": ["123"]
}
```

**Comment by rmosolgo** [comment]
Hey, thanks for the detailed writeup -- I agree it shouldn't crash! I guess it needs a `type.kind.input?` check (https://github.com/rmosolgo/graphql-ruby/blob/52ec07bad6e617ef5d1954d4be13370520e4041f/lib/graphql/type_kinds.rb#L29) in the `Variables` code.
