### ISSUE TITLE
Required input with default value cannot be omitted

### ISSUE THREAD

**Issue by eapache-opslevel** [rmosolgo/graphql-ruby#4728]
**Describe the bug**

I'm only about 80% sure this is actually a bug (vs me misunderstanding the spec), cause I know this area has been the source of a lot of confusion, both in writing the spec and in implementations.

But if I define
```ruby
argument :something,
      Boolean,
      required: true,
      default_value: true,
```
resulting in
```graphql
something: Boolean! = true
```

I expect that I can omit that argument from the input of my query/mutation, and it will be treated as true. Instead, graphql-ruby produces an error:
```
Argument 'something' on InputObject 'WhateverInput' is required. Expected type Boolean!
```

**Versions**

`graphql` version: 2.0.27

**Comment by rmosolgo** [comment]
Yeah, I think it's a bug, Input objects and arguments both say to use the default value in this case: 

- https://spec.graphql.org/draft/#sec-Input-Objects.Input-Coercion
- https://spec.graphql.org/draft/#sec-Required-Arguments

Thanks for reporting it!
