### ISSUE TITLE
Wrong option name is fetched

### ISSUE THREAD

**Issue by dougthomas** [rmosolgo/graphql-ruby#4731]
**Describe the bug**

The graphql datadog APM integration does not honor the `service_name` provided at Datadog APM initialization.  I see only traces that use the default service name, `ruby-graphql`.  

It appears that this line: https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/tracing/data_dog_tracing.rb#L55 is fetching an option named `service`, and defaulting to `ruby-graphql` if none is found.  The documentation and standard is for this option to be named `service_name`.  I believe that a simple, backward-compatible fix is to change that line to:

```ruby
   options.fetch(:service, options.fetch(:service_name, 'ruby-graphql'))
```

**Versions**
ddtrace 1.14.0

**Steps to reproduce**

Configure Datadog APM:

```ruby
service = 'myservice'  
::Datadog.configure do |c|
    c.service = service

    c.tracing.instrument :graphql, service_name: "#{service}-graphql"
end
```

**Expected behavior**

All graphql traces would have service_name `myservice-graphql`

**Actual behavior**

All graphql traces have service_name `ruby-graphql`

**Comment by rmosolgo** [comment]
HI! Sorry for the confusion. I checked the GraphQL-Ruby docs and found that `service` was documented here: 

https://graphql-ruby.org/queries/tracing.html#datadog

Where did you find `service_name` documented?

**Comment by rmosolgo** [comment]
Let me know if you have any more background on this, I'd be happy to revisit it later :+1:
