### ISSUE TITLE
Cannot run spec suite when using GraphQL::Dataloader::AsyncDataloader

### ISSUE THREAD

**Issue by swrobel** [rmosolgo/graphql-ruby#4735]
**Describe the bug**
From reading the docs, it seems that `GraphQL::Dataloader::AsyncDataloader` is a simple drop-in replacement for `GraphQL::Dataloader`, but that does not seem to be the case. The suite was entirely passing before switching over. Afterward, when it hits the first failure, all other specs fail with a `ThreadError`.

**Versions**

`graphql` version: 2.2.0
`rails` (or other framework): 7.1.0
other applicable versions (`graphql-batch`, etc)

* graphql-c_parser (1.0.7)
* graphql-sources (1.2.0)

**GraphQL schema**

My schema is very complex and it's hard to figure out where exactly the issue is because of the spec failures

**Steps to reproduce**

Run spec suite when using `GraphQL::Dataloader::AsyncDataloader`

**Expected behavior**

`714 examples, 0 failures`

Specs all passed as they did when using `GraphQL::Dataloader`

**Actual behavior**

`714 examples, 604 failures`

If one spec fails, the rest fail with a `ThreadError`

<details>
<summary>Click to view exception backtrace</summary>

```
Failure/Error: @mutex.lock if @owner != Thread.current

ThreadError:
  deadlock; lock already owned by another fiber belonging to the same thread
# gems/activesupport-7.1.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:55:in `lock'
# gems/activesupport-7.1.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:55:in `mon_enter'
# gems/activesupport-7.1.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:15:in `block in mon_enter'
# gems/activesupport-7.1.2/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
# gems/activesupport-7.1.2/lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'
# gems/activesupport-7.1.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:15:in `mon_enter'
# gems/activesupport-7.1.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:20:in `block in synchronize'
# gems/activesupport-7.1.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:19:in `handle_interrupt'
# gems/activesupport-7.1.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:19:in `synchronize'
# gems/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/transaction.rb:416:in `begin_transaction'
# gems/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:352:in `begin_transaction'
# gems/activerecord-7.1.2/lib/active_record/test_fixtures.rb:149:in `block in setup_fixtures'
# gems/activerecord-7.1.2/lib/active_record/test_fixtures.rb:148:in `each'
# gems/activerecord-7.1.2/lib/active_record/test_fixtures.rb:148:in `setup_fixtures'
# gems/activerecord-7.1.2/lib/active_record/test_fixtures.rb:10:in `before_setup'
# gems/rspec-rails-6.1.0/lib/rspec/rails/adapters.rb:74:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
# gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
# gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
# gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:390:in `execute_with'
# gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
# gems/rspec-core-3.12.2/lib/rspec/core/example.rb:352:in `call'
# gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:629:in `run_around_example_hooks_for'
# gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:486:in `run'
# gems/rspec-core-3.12.2/lib/rspec/core/example.rb:468:in `with_around_example_hooks'
# gems/rspec-core-3.12.2/lib/rspec/core/example.rb:511:in `with_around_and_singleton_context_hooks'
# gems/rspec-core-3.12.2/lib/rspec/core/example.rb:259:in `run'
# gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:646:in `block in run_examples'
# gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:642:in `map'
# gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:642:in `run_examples'
# gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:607:in `run'
# gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:608:in `block in run'
# gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:608:in `map'
# gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:608:in `run'
# gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
# gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:121:in `map'
# gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
# gems/rspec-core-3.12.2/lib/rspec/core/configuration.rb:2070:in `with_suite_hooks'
# gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:116:in `block in run_specs'
# gems/rspec-core-3.12.2/lib/rspec/core/reporter.rb:74:in `report'
# gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:115:in `run_specs'
# gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:89:in `run'
# gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:71:in `run'
# gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:45:in `invoke'
# gems/rspec-core-3.12.2/exe/rspec:4:in `<top (required)>'
```

</details>

**Additional context**

I make extensive use of [ActiveRecord enums](https://api.rubyonrails.org/classes/ActiveRecord/Enum.html) which seems to be the cause of some of the spec failures that pop up when switching to AsyncDataloader

**Comment by rmosolgo** [comment]
Hey, thanks for the detailed report and sorry for the trouble. I definitely _expect_ it to be a drop-in replacement. But looking back at the async docs (https://socketry.github.io/async/guides/compatibility/index#rails), maybe you'd also need to update this config: 

```ruby
class Application < Rails::Application
	config.active_support.isolation_level = :fiber
end
```

Have you tried that? Does it help? 


Besides that, I guess we'd have to look "upstream" to see where the lock is being held and not released -- unfortunately, by the time we get the error, the backtrace doesn't have anything GraphQL-related 😖 .

**Comment by swrobel** [comment]
> Have you tried that? Does it help?

Yes, that's a big improvement!

`714 examples, 38 failures`

I'll see if I can nail down any common thread with the remaining failures

**Comment by swrobel** [comment]
They all seem to be race conditions in mutations, which is odd, because I don't understand why using AsyncDataloader would be changing anything with the way ActiveRecord crud operations are sequenced... any ideas?

**Comment by rmosolgo** [comment]
AsyncDataloader (by way of Ruby's Fiber scheduler API) moves fibers to the background when they're waiting on I/O. So, I wouldn't _expect_ the actual order to change, but what Ruby's _doing_ might change, in the sense that some Fiber in the foreground would be waiting for the database queries in the mutation to finish. 

How did you determine that they're race conditions? What kind of symptoms does it show?

**Comment by swrobel** [comment]
Actually, it turns out they're all specs that are testing for an error response in cases where I'm rescuing an exception and turning it into a useful error message. I suppose using Async somehow prevents the exception from bubbling up correctly to the controller:

```ruby
class GraphqlController < ActionController::API
  class << self
    def execute(query, context:, variables:, operation_name: nil)
      [MyApiSchema.execute(query, variables:, context:, operation_name:), :ok]
    rescue Errors::ApiUnauthorizedError, Pundit::NotAuthorizedError => e
      [error_response(e), :unauthorized]
    rescue ActiveRecord::RecordNotFound => e
      [error_response(e), :not_found]
    rescue AASM::InvalidTransition => e
      [error_response(e, aasm_error: true), :unprocessable_entity]
    rescue => e
      raise e unless Rails.env.development?

      logger.error e.message
      logger.error Rails.backtrace_cleaner.clean(e.backtrace).join("\n")

      [error_response(e), :internal_server_error]
    end

    def error_response(error, aasm_error: false)
      message = error.message
      if aasm_error
        originating_state = error.originating_state
        target_state = Order.aasm.state_machine.events[error.event_name.to_sym].transitions.first.to
        message = (originating_state == target_state) ? "Your order is already in status '#{originating_state.to_s.titleize}'" : "Your order is in status '#{originating_state.to_s.titleize}' which can't be changed to status '#{target_state.to_s.titleize}'"
      end

      error_hash = {message:}
      error_hash[:backtrace] = error.backtrace unless Rails.env.production?

      {
        errors: [error_hash],
        data: {},
      }.deep_stringify_keys
    end
  end

  def execute
    variables = ensure_hash(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      current_user:,
      app_version:,
    }
    json, status = self.class.execute(query, variables:, context:, operation_name:)
    render json:, status:
  rescue Errors::ApiUnauthorizedError => e
    render json: self.class.error_response(e), status: :unauthorized
  end
end
```

This is all defined in this way so that I can do this in my specs:

```ruby
subject(:execute) do
  GraphqlController.execute(
    mutation_string,
    variables: {
      input:,
    },
    context: {
      current_user: user,
      app_version:,
    },
  ).first.to_h
end

let(:rescued_error) { execute.dig("errors").first["message"] }

context "when invalid state" do
  let(:state) { :pending_final_payment }
  let(:transition) { "requestFinalPayment" }

  it "raises an error" do
    expect(rescued_error).to eq("Your order is already in status 'Pending Final Payment'")
  end
end
```

**Comment by rmosolgo** [comment]
Ok, that's a great clue -- thanks for sharing what you found. It seems like some kind lock isn't being released when the error raised. (Or maybe some already-scheduled fiber is competing for lock even after the error propagates through?) 

In the meantime, I also updated the docs to include `isolation_level` in eea7871c2.

**Comment by rmosolgo** [comment]
I spent some time trying to replicate this exact error but couldn't quite get it. But what I _did_ find was that I wasn't properly re-raising errors from inside `Async::Task`s. I bet AsyncDataloader was swallowing errors so then Rails couldn't clean up those locks. Could you give the branch in this PR a try? https://github.com/rmosolgo/graphql-ruby/pull/4736

```ruby
gem "graphql", github: "rmosolgo/graphql-ruby", ref: "async-dataloader-error-handling"
```

Let me know how your tests do with that branch. If they fail in some _other_ way, that might be a good clue! And if it works for you then I'll go ahead and cut a release to Rubygems.
