### ISSUE TITLE
Access Posgres' JSONB columns

### ISSUE THREAD

**Issue by benoror** [rmosolgo/graphql-ruby#474]
Hi! How can I include JSONB attributes (using PostgreSQL) in my **GraphQL Schema**?

In my Rails app I usually access those column using [`store_accessor`](http://api.rubyonrails.org/classes/ActiveRecord/Store.html):

```ruby
store_accessor :jsonb_column, :prop_a, :prop_b
```

Disclaimer: I'm new to GraphQL 🙈 

Thanks!

**Comment by rmosolgo** [comment]
Does `store_accessor` make a method with the same name? If so, then you don't need anything special, just add a field, eg 

```ruby 
field :prop_a, types.String # or types.Int, whatever type is in that field
```

**Comment by benoror** [comment]
@rmosolgo mmm good point, I should have omitted the `store_accesor` stuff, since what I'm looking for is to keep it as a **nested record**. An example:

```ruby
# person_type
module Graph
  PersonType = GraphQL::ObjectType.define do
    name 'Person'
    description 'A person'

    field :id, types.ID
    field :medical_records do # this is the JSONB column
      type MedicalRecordsType
      resolve lambda { |obj, _args, _ctw|
        obj.medical_records
      }
    end
  end
end
```

```ruby
module Graph
  MedicalRecordsType = GraphQL::ObjectType.define do
    name 'MedicalicalRecords'
    description 'A pathological records'

    field :diabetes, types.String
    # ... other regular fields
  end
end
```

If I try to run the following query:

```graphql
query: {
  person(id: 1) {
    medical_records { 
      diabetes 
    }
  }
}
```

I get the following Exception:

```
NoMethodError in Api::V1::GraphController#index

undefined method `diabetes' for #<Hash:0x007fe143e36878>
```

**Comment by rmosolgo** [comment]
Oh I see! 

By default, fields perform a method call.  To resolve a field with `[...]`, You can specify a key with `hash_key:`, eg, 

```ruby 
field :diabetes, types.String, hash_key: :diabetes 
# will find a value by doing `medical_records[:diabetes]`
```

A few more examples here: http://www.rubydoc.info/gems/graphql/GraphQL/Field

Does that work for you? Please reopen this if not!

**Comment by rmosolgo** [comment]
Can you help me understand what "stops working" means here? Is there runtime error?

**Comment by benoror** [comment]
@rmosolgo sorry, I sent the comment before finishing it (freaking CMD + Enter). I updated the [code above ☝️](https://github.com/rmosolgo/graphql-ruby/issues/474#issuecomment-270532079)

Basically the issue is with the resulting repsonse:

Option A will return: `measurements: null`

Option A will return: `measurements: {weight: null, height: null}`

...while being the actual value in the JSONB record is: `measurements: {weight: 100, height: 70}`

**Comment by rmosolgo** [comment]
Option A has 

> `field :measurements, types[MeasurementsType]`

which means that `measurements` returns a _list_ of `MeasurementsType` objects. Should it be 

```ruby
field :measurements, MeasurementsType
```

which means it returns an object of type `MeasurementsType`?  (This would match Option B.)

**Comment by benoror** [comment]
@rmosolgo good catch, this was indeed a newbie mistake. Although both results didn't change *at all* for some reason

**Comment by benoror** [comment]
@rmosolgo yeah that did the trick!

thanks a lot for the help 😸 u're awesome!
