### ISSUE TITLE
new parser doesn't understand valid field names

### ISSUE THREAD

**Issue by krishantaylor** [rmosolgo/graphql-ruby#4758]
**Describe the bug**

The valid field name "on" is not respected by the new parser introduced in v2.2. This previously worked in v2.1.7. This problem may extend to other words that require special handling by the lexer.

**Versions**

`graphql` version: 2.2.3
`rails` (or other framework): 7.0.8

**Steps to reproduce**

1. Define a field named "on".
2. Try to query a type with that field.

**Expected behavior**

The field should return with a value.

**Actual behavior**

No data returns, and errors include the message "Expected NAME, actual: ON ...".

**Comment by rmosolgo** [comment]
Sorry for the trouble, and thanks for reporting this! I've opened up a fix for it in #4759.
