### ISSUE TITLE
Support for ActiveRecord::Promise

### ISSUE THREAD

**Issue by fazo96** [rmosolgo/graphql-ruby#4766]
**Is your feature request related to a problem? Please describe.**

Since Rails 7.1, ActiveRecord exposes methods such as `async_count`, `async_ids` which return a [ActiveRecord::Promise](https://api.rubyonrails.org/classes/ActiveRecord/Promise.html).

This allows parallel DB reads to run due to the DB I/O being async. However, graphql-ruby does not automatically unwrap the promise. Given the AsyncDataloader was implemented recently, it would be nice if promises were handled automatically in both dataloaders, with the ability to leverage the paralellism in the AsyncDataloader.

**Describe the solution you'd like**

Returning a ActiveRecord::Promise as the value of a field would result in graphql-ruby automatically unwrapping it to read its return value.

**Describe alternatives you've considered**

I could implement this myself I guess but I thought it might be worth it to have it in the library, or maybe as an example in the docs.

**Additional context**

The value here is being able to improve performance by making select operations async, for example reading totalCount on a connection.

**Comment by rmosolgo** [comment]
Here are two options for supporting `ActiveRecord::Promise`: 

- Use ["lazy resolution"](https://graphql-ruby.org/schema/lazy_execution): 

  ```ruby 
   class MySchema < GraphQL::Schema 
     # ...
     lazy_resolve(ActiveRecord::Promise, :value) 
   end 
   ```
   
   That tells GraphQL-Ruby that, whenever it encounters an `ActiveRecord::Promise`, to call its `value` method before returning a value to the client. 
   
- Or, integrate with Dataloader with [manual parallelism](https://graphql-ruby.org/dataloader/sources.html#example-loading-in-a-background-thread):

  ```ruby 
   count_promise = my_relation.async_count 
   dataloader.yield # let other sources resolve 
   count_promise.value 
   ```
   
   This would give you backgrounded I/O with `GraphQL::Dataloader` but it's redundant with `GraphQL::Dataloader::AsyncDataloader`, since `AsyncDataloader` would put a "plain" ActiveRecord query in the background anyway.
   
I'm not sure how Rails's `async` methods would integrate with `AsyncDataloader` since they're two different solutions to the same problem. Either of the above methods should allow GraphQL-Ruby to continue working while the SQL query runs.

Let me know how those options work for you if you give them a try!

**Comment by fazo96** [comment]
I tried lazy resolution, but I get this error:

```
undefined method `public_send' for #<ActiveRecord::Promise status=complete>
/usr/local/rvm/gems/ruby-3.2.2/gems/graphql-2.2.4/lib/graphql/schema.rb:1287:in `sync_lazy'
/usr/local/rvm/gems/ruby-3.2.2/gems/graphql-2.2.4/lib/graphql/execution/interpreter/runtime.rb:799:in `block (2 levels) in after_lazy'
/usr/local/rvm/gems/ruby-3.2.2/gems/graphql-2.2.4/lib/graphql/tracing/trace.rb:56:in `execute_field_lazy'
/usr/local/rvm/gems/ruby-3.2.2/gems/graphql-2.2.4/lib/graphql/tracing/platform_trace.rb:61:in `execute_field_lazy'
/usr/local/rvm/gems/ruby-3.2.2/gems/graphql-2.2.4/lib/graphql/execution/interpreter/runtime.rb:798:in `block in after_lazy'
/usr/local/rvm/gems/ruby-3.2.2/gems/graphql-2.2.4/lib/graphql/execution/lazy.rb:30:in `value'
/usr/local/rvm/gems/ruby-3.2.2/gems/graphql-2.2.4/lib/graphql/execution/interpreter/resolve.rb:23:in `each'
/usr/local/rvm/gems/ruby-3.2.2/gems/graphql-2.2.4/lib/graphql/execution/interpreter/resolve.rb:23:in `block in resolve_each_depth'
/usr/local/rvm/gems/ruby-3.2.2/gems/graphql-2.2.4/lib/graphql/dataloader.rb:252:in `block in spawn_job_fiber'
/usr/local/rvm/gems/ruby-3.2.2/gems/graphql-2.2.4/lib/graphql/dataloader.rb:233:in `block in spawn_fiber'
```

Interestingly, it works by using `lazy_resolve PromiseWrapper, :value`

Here's the implementation:

```ruby
class PromiseWrapper
  def initialize(promise)
    @promise = promise
  end

  def value
    @promise.value
  end
end
```

the promise must be returned as `PromiseWrapper.new(actual_promise)` though.

I tried writing a Dataloader Source as you recommended using the docs you linked but it doesn't work:

```
undefined method `hash' for #<ActiveRecord::Promise status=complete>
/usr/local/rvm/gems/ruby-3.2.2/gems/graphql-2.2.4/lib/graphql/dataloader/source.rb:56:in `load'
/workspaces/flexhire/backend/app/graphql/types/base_connection.rb:14:in `total_count'
```

For now I am going to use the PromiseWrapper solution. Thanks!

**Comment by trevorturk** [comment]
FWIW this might be worth documenting in the guides or something if it starts coming up a lot!

**Comment by rmosolgo** [comment]
Wow -- `ActiveRecord::Promise` doesn't extend `Object` -- it extends `BasicObject`! I wonder what their reason is for that. I'm going to investigate further. If nothing else, we can use `__send__` instead but ... 😓

**Comment by trevorturk** [comment]
Interesting result on the Rails thread! FWIW I don't think the workaround is too bad if we document, but I wonder if there's another strategy. I'm not sure if common cases get built in Sources or something more interesting. 

Also please ignore me, I'm just guessing this may come up an again in the future and it seems like an interesting little issue!

**Comment by rmosolgo** [comment]
I documented (and tested) how Rails `async_` methods might be used in #4768. 

@fazo96, looking at the backtrace again, it looks like you might have passed an `ActiveRecord::Promise` instance into `.load(...)`, but instead, that promise should be created _inside_ `def fetch`, and then waited on inside that method. (That way, we won't need its `#hash` method, anyways.)

@trevorturk, thanks for sharing your thoughts -- I agree it's good to have documented!

**Comment by fazo96** [comment]
@rmosolgo yes, I did pass an `ActiveRecord::Promise` into `load()`. Unfortunately I needed a generic way to deal with promises because the logic that comes up with the query for the total count is different every time and I can't move that into a dataloader source.

But that's ok as the `lazy_resolve` with the `PromiseWrapper` class worked

**Comment by jherdman** [comment]
Hold up... We shouldn't close this yet. The workaround may exist, but this is definitely a foot gun. How can we handle ActiveRecord::Promise as a first class citizen?
