### ISSUE TITLE
Re-use other already resolved field values in a lazy_resolve type

### ISSUE THREAD

**Issue by 23tux** [rmosolgo/graphql-ruby#4782]
**Is your feature request related to a problem? Please describe.**

I want to build some template support for graphql-ruby, where template strings like `"my records are: %{records}"` are interpolated upon resolving, and their variables can use other fields.

```
class Template
  def initialize(template, object, ctx)
    @template = template
    @object = object
    @ctx = ctx
  end

  def resolve
    @template % {records: @object.records.join(", ")}
  end
end

class Queries < GraphQL::Schema::Object
  field :template, String, null: false
  def template
    Template.new("my records are: %{records}", self, context)
  end

  field :records, [String], null: false
  def records
    puts "loading records..."
    %w[record1 record2] # in reality, these records come from the DB
  end
end

class Schema < GraphQL::Schema
  lazy_resolve(Template, :resolve)
  query Queries
end

resp = Schema.execute("query { template records }").to_h
puts JSON.pretty_generate(resp)
```

This _kinda_ works, but it calls `#records` twice. This is the output:

```
loading records...
loading records...
{
  "data": {
    "template": "my records are: record1, record2",
    "records": [
      "record1",
      "record2"
    ]
  }
}
```

**Describe the solution you'd like**

1. Having access to already resolved values from other fields, so that methods are not called twice.
2. We also use [graphql-batch](https://github.com/Shopify/graphql-batch) for optimized DB loading. It would be great, if I could somehow configure which lazy_resolve type to resolve last, so that my template could have access to the already eager loaded DB records. Maybe it depends on the order they are configured, but I'm not sure if I could rely on that.
3. Trigger the resolve of fields that are needed inside a template, but NOT present in the selection of the query, e.g. in my example above: When the `records` field is NOT selected in the query, but the template inside would need it, could I trigger the resolve in some way?

**Describe alternatives you've considered**

Storing the result form fields in instance variables, but I'm not sure if this causes any other side effects, AND in case of other lazy_resolve types, it would simply store the lazy_resolve instance, not the resolved value of that instance.

**Comment by rmosolgo** [comment]
Hi! Thanks for the interesting and detailed write-up.

My suggestion would be to: 

1. To get caching, use GraphQL-Batch's internal cache. Anything loaded with `def perform` will only be loaded once, so use batch loaders  to get values for a `Template` instance. 
2. To get dependency ordering, use GraphQL-Batch's `Promise`s to "wait" for required data before continuing. 
3. Similarly, a GraphQL-Batch based approach would allow you to call  whatever methods you need in `def resolve`. 

Here's a modification of your script which uses GraphQL-Batch and Promises to achieve the desired result: 

```ruby 
require "bundler/inline"

gemfile do
  gem "graphql"
  gem "graphql-batch"
end

class Template
  def initialize(template, object, ctx)
    @template = template
    @object = object
    @ctx = ctx
  end

  def resolve
    @object.records.then do |loaded_records|
      @template % {records: loaded_records.join(", ")}
    end
  end
end

class RecordLoader < GraphQL::Batch::Loader
  def perform(ids)
    puts "Loading records: #{ids}"
    ids.each do |id|
      fulfill(id, "<Record ##{id}>")
    end
  end
end

class Queries < GraphQL::Schema::Object
  field :template, String, null: false
  def template
    Template.new("my records are: %{records}", self, context)
  end

  field :records, [String], null: false
  def records
    RecordLoader.load_many([1, 2, 3])
  end
end

class Schema < GraphQL::Schema
  use GraphQL::Batch
  lazy_resolve Template, :resolve
  query Queries
end

resp = Schema.execute("query { template records }").to_h
puts JSON.pretty_generate(resp)
# Loading records: [1, 2, 3]
# {
#   "data": {
#     "template": "my records are: <Record #1>, <Record #2>, <Record #3>",
#     "records": [
#       "<Record #1>",
#       "<Record #2>",
#       "<Record #3>"
#     ]
#   }
# }
```

What do you think of an approach like that?

**Comment by 23tux** [comment]
Thanks for the quick response! I think this would solve the case with DB queries, very cool!

However, I'm also thinking of a more generic solution to this: How would you handle it, when `def records` can't use the graphql-batch tooling? For example, raw SQL calls, a call to a search index or a HTTP call to an API? Is there any way to get my hands on the resolved values from the internals of graphql-ruby?

I also think that it could have unintended side effects, or at least be surprising to the developer, that a method is called multiple times, depending on how often the value is used. I would try to do some caching by storing it on the `ctx` itself, but I'd still be curious if there is a more generic way.

**Comment by rmosolgo** [comment]
Raw SQL calls and HTTP calls could definitely be put inside GraphQL-Batch loaders. They'd be just like ActiveRecord calls except ... different :P For example: 

```ruby 
class RemoteObjectLoader < GraphQL::Batch::Loader 
  def perform(remote_ids)
    remote_ids.each do |remote_id|
      result = ApiClient.get(remote_id)
      fulfill(remote_id, result.data) 
    end 
  end 
end 
```

In your own code, you could improve that further by: 

- Making different loaders for different kinds of objects, so you could customize the URL or fetch multiple objects in the same call
- Use a concurrency library to kick off all the requests, then wait for each one and fulfill it after it returns. 

But the point is, GraphQL-Batch is well-suited to any kind of external data loading, not just ActiveRecord. 

I agree it would be strange to call field methods from non-GraphQL code. Another way it would be surprising is that if someone came later and modified the code for the `records` field in some way, they might not expect it to _also_ affect the behavior of the template-related code. 

You could address this by calling the batch loader directly inside `Template`. It would use the same cache as the `results` field, so you'd still only load any given record once. For example: 

```ruby 
record_ids = object.record_ids # somehow get the ids
RecordLoader.load_many(record_ids).then do |records|
  @template % {records: records.join(", ")}
end
```

That adds isolation between the GraphQL field and the template while using the same cache and handling the dependency for the template. 


To answer your questions directly: 

- No, there's not a way to get resolved values while a query is running. `GraphQL::Query#result=` isn't assigned until after the result is created: https://github.com/rmosolgo/graphql-ruby/blob/14796647ab906a5705fec59a94cba8057dc9a1c0/lib/graphql/execution/interpreter.rb#L107-L114

- There isn't a way to re-order the handling of `lazy_resolve`'d objects. They're resolved in the order that they're encountered in execution and there isn't a queue or buffer to put them on during resolution. (Fortunately, `Promise`s are designed for expressing dependency and sequence via `.then`.)

- For triggering fields even when they aren't selected, you can certainly call the field's method on the GraphQL type, as in my example above. But as you noticed, this creates some unexpected connections between bits of code. I think this "code smell" is a clue that this logic belongs in the application layer (eg, inside `Template` or inside the model), not the interface layer. 

It sure looks to me like this should be solved _before_ GraphQL (in application code), not mixed in with the GraphQL runtime. But is there any part of this feature that couldn't be implemented that way?

**Comment by 23tux** [comment]
Thanks for the elaborate response, I really appreciate your fast and quality responses 😍 

> But the point is, GraphQL-Batch is well-suited to any kind of external data loading, not just ActiveRecord.

Really good idea, haven't thought of this until now, this could indeed solve some of the problems.

> That adds isolation between the GraphQL field and the template while using the same cache and handling the dependency for the template.

I think some kind of separation between GraphQL and the template handling would be really good. But it should also be easy for developers to add template support to fields without having too much to worry about the implementation of the fields that the template relies on. I also try to wrap my head around what values inside the template should be supported, and I guess "just every field on the same level" is a good starting point.

> No, there's not a way to get resolved values while a query is running. ... There isn't a way to re-order the handling of lazy_resolve'd objects.  ... this creates some unexpected connections between bits of code...

That are the most important points to me, as it allows me to stop tampering around with the GraphQL runtime and focus on other solutions. If you don't mind, I would pitch some of the other ideas here, maybe you have some insights or ideas:

### Idea 1: Calling other fields from within template fields (abandoned)
- You have to keep an eye on stuff like eager loading and caching depending on the implementation of the field
- I can't use already resolved fields as stated above
- If an un-optimized field is used, two calls to that field will happen: First for the selection and then for the template. This could lead to performance issues as data is queried twice from the DB, some API, search index...
- Support for nested fields is harder to do: Calling `product.price` on a field like `field :product, ProductType` would call the method `#price` directly on the ActiveRecord object, not the resolved `ProductType#price` field. This can lead to inconsistent behaviour, as the interface to AR is intended for developers only, not for the customer to do selections on it. I would have to keep a manual list of methods that are approved, and IMO this is what the GraphQL fields are for

### Idea 2: Post-resolve template interpolations
- I could do all the template interpolations AFTER the GraphQL request is successfully resolved
- I would have to either traverse the whole tree and look for patterns like `%{template_var}` OR do some optimization and analyze the query beforehand and use the schema to lookup which fields can contain a template
- *Caveat:* When a template uses a field that is not present in the users' query, I would have to manipulate the query beforehand, so that this field is present in the resolved response from the GraphQL engine. And to keep the behaviour clean, I would have to delete the fields before returning the response to the client, as the client should be the one defining the structure of the response.
- Could I use instrumentation for that?

I guess this approach could work, I'm curious on your opinion.

### Idea 3: Turn template variables into separate queries and do a nested GraphQL query within the current GraphQL query
- I'm not sure if this is too complicated, but I like the idea as it doesn't manipulate things in a post process
- Instances of `Template` can collect all needed variables and turn them into a query, for example:

```
class MyPageType < GraphQL::Schema::Object
  field :title, String
  field :product, ProductType

  def product
    object.product
  end
end

class ProductType < GraphQL::Schema::Object
  field :name, String
end
```

- `MyPageType#title` contains `"Review of %{product.name}"`
- I would define a special field `field :__my_page_templates, MyPageType` where I provide the `object` as the backend
- Then, I would create a custom query `query { __myPageTemplates { product { name } } }`
- All needed fields would be collected using `lazy_resolve`, and I would do a separate, nested template query on each level
- The result of the nested template query can then be used to render the template
- **Caveats:** It feels like a lot of overhead, but I guess it depends on how fast the resolve is (maybe you can share some insights in that)
- **Caveats:** It also feels like the most complicated solution, I'm unsure about the real benefits over Idea 2
- **Caveats:** This could potentially lead to an infinite loop, if the nested query also triggers template responses. But I guess, a flag on the context should do the trick.

One aspect I have to think about is, how to deal with fields that have arguments? If they have required arguments, either these fields are not available as variables, or you have to somehow specify the arguments as filters in a liquid template. But I'm not sure if this works. And if the argument has a default value, I guess this could also lead to surprising results. So I guess for now, I'm just don't allow fields with arguments for template variables.

**Comment by rmosolgo** [comment]
If you decide to pursue "post-resolve template interpolations", you could build up a list of template strings during execution, for example: 

```ruby 
context[:template_strings] << my_template_with_variables.dup # make sure it's a mutable string 
```

Then, before returning the response, you could modify those strings in-place: 

```ruby 
response.context[:template_strings].each { |str| str.sub!(...) }
```

It ain't pretty, but I think it'd _work_. I hope one of those options works for you!

**Comment by 23tux** [comment]
Thanks for the answer, I'll look into it!
