### ISSUE TITLE
Runtime manipulation of arguments breaks with commit "Cache resolved arguments better"

### ISSUE THREAD

**Issue by 23tux** [rmosolgo/graphql-ruby#4784]
**Describe the bug**

- We have a custom argument class that reads arguments from `context` at runtime and manipulates it
- Until version 2.0.21 the method `GraphQL::Schema::Argument#coerce_into_values` was called for every element in a list that had an argument
- This commit introduced some performance improvements https://github.com/rmosolgo/graphql-ruby/commit/68994bb55310f275161dfe199fefd9c2648071fc
- I guess because of those improvements, the `#coerce_into_values` method is only called once, and not for every element in a list
- The problem is: We rely on this behaviour, as our tooling will provide special arguments for certain elements

**Versions**

`graphql` version: 2.0.22
`rails`: 7.0.7.2
`graphql-batch`: 0.5.3

**GraphQL schema**

```ruby
class MyArgument < GraphQL::Schema::Argument
  def coerce_into_values(object, values, context, argument_values)
    puts "-> coerce_into_values"
    values = values.dup
    values[graphql_name] = object.object.fetch(:secret) # here we read the configured arguments from our backend
    super(object, values.freeze, context, argument_values)
  end
end

class MyField < GraphQL::Schema::Field
  argument_class(MyArgument)
end

class UserType < GraphQL::Schema::Object
  field_class(MyField)

  field :name, String, null: false do
    argument :secret, Boolean, required: false
  end

  def name(secret: false)
    secret ? "*****" : object.fetch(:name)
  end
end

class EmployeeType < GraphQL::Schema::Object
  field :user, UserType, null: false

  def user
    object.fetch(:user)
  end
end

class Queries < GraphQL::Schema::Object
  field :employees, [EmployeeType], null: false

  def employees
    context.fetch(:employees)
  end
end

class Schema < GraphQL::Schema
  query Queries
end
```

**GraphQL query**

```graphql
context = {
  employees: [
    { user: { name: "Will", secret: false } },
    { user: { name: "Mark", secret: true } }
  ]
}
resp = Schema.execute("query { employees { user { name } } }", context:).to_h
puts JSON.pretty_generate(resp)
```

This is the output for version 2.0.21:
```json
-> coerce_into_values
-> coerce_into_values
{
  "data": {
    "employees": [
      {
        "user": {
          "name": "Will"
        }
      },
      {
        "user": {
          "name": "*****"
        }
      }
    ]
  }
}
```

And this is the output for 2.0.22:
```
-> coerce_into_values
{
  "data": {
    "employees": [
      {
        "user": {
          "name": "Will"
        }
      },
      {
        "user": {
          "name": "Mark"
        }
      }
    ]
  }
}
```

**Steps to reproduce**

Pin the gem to
```
gem "graphql", git: "https://github.com/rmosolgo/graphql-ruby", ref: "68994bb55310f275161dfe199fefd9c2648071fc"
```

**Expected behavior**

I know that we bend the rules here a bit, because normally every element in a list would get the same argument, because an argument is defined in the query, and therefore applies to all elements of that list. But unfortunately, our app relies on that behaviour: In our backend an admin can define lists of elements, and every element in that list can have it's own arguments.

So, we need a way to intercept passing an argument to a method, and inject values for it.

**Actual behavior**
After upgrading to 2.0.22, the `#coerce_into_values` method is only called once per argument. I understand it from a performance point, and also from a GraphQL specs point of view, as arguments are not intended to be used in such a way, I guess.

But I really hope, that there is a way to find a workaround where I can upgrade the gem AND have our requirements fulfilled.

**Comment by rmosolgo** [comment]
As you noted, that performance improvement _does_ fit the spirit of the specification -- I don't plan to roll it back. But I bet there is an implementation that will still work. 

In this specific case, the easiest thing would be to use `object` to determine the Ruby method argument's default value, for example: 


```ruby 
  def name(secret: object.fetch(:secret))
    secret ? "*****" : object.fetch(:name)
  end
```

But that only applies the `object`'s value when the GraphQL argument _isn't_ provided by the client .... 

If you wanted to use the object's value even when the argument is given, you could use that instead of the argument, eg: 

```ruby 
secret = object.fetch(:secret) 
secret ? "*****" : ... 
```

But maybe you need something more programatic. Another approach would be a field extension ([doc](https://graphql-ruby.org/type_definitions/field_extensions.html)), which can modify arguments before passing them on to be resolved: 

```ruby 
class SecretExtension < GraphQL::Schema::FieldExtension
  def resolve(object:, arguments:, context:)
    new_args = arguments.dup
    @field.arguments(context).each do |name, arg_defn|
      new_args[arg_defn.keyword] = object.object.fetch(:secret)
    end
    yield(object, new_args, context)
  end
end

class MyField < GraphQL::Schema::Field
  def initialize(...)
    super
    extension(SecretExtension)
  end
end
``` 

(This is how connections handle first and last, [source](https://github.com/rmosolgo/graphql-ruby/blob/14796647ab906a5705fec59a94cba8057dc9a1c0/lib/graphql/schema/field/connection_extension.rb#L14-L22).)

Do any of those options look like they would work for you? If not, please share a bit more about your usage and I bet we can find something...

**Comment by 23tux** [comment]
Thanks for the detailed answer! I played around with the extension, and it seems like this indeed solves my problem, very cool!

One thing remains: I would need a similar functionality for input objects, e.g.

```
class MyInputObject < GraphQL::Schema::InputObject
  argument :secret, Boolean, required: false
end

class UserType < GraphQL::Schema::Object
  field_class(MyField)

  field :name, String, null: false do
    argument :my_input, MyInputObject, required: false
  end

  def name(my_input: nil)
    my_input&.secret ? "*****" : object.fetch(:name)
  end
end
```

Is there a hook where I can manipulate an InputArguments' arguments like in your example with `#resolve` in a field extension?

I'm currently playing around with injecting the values from the field extensions `#resolve` method, but ran into some problems. Inside `#resolve` I only get the hook for the `:my_input` argument, not the `MyInputObject#secret` argument. I could try to replace the whole InputArgument value in `#resolve`, but I suspect that this will cause other problems when having nested input objects. I already have a custom argument class for my InputObjects, is there any hook that is called when an argument is build?

**Comment by 23tux** [comment]
Another point that I just stumbled upon: If an argument has `required: true` and also a `prepare` block, the prepare block is called BEFORE the extensions `#resolve`. I understand that this makes total sense when the argument values come from "outside". But in my case I'd like to have a way to manipulate the argument values before it is passed into the prepare block.

It's a chicken-and-egg situation: I want `#prepare` to be called before the extensions `#resolve`, but I also want to set the arguments value inside `#resolve`. When I somehow call `prepare` a second time inside `#resolve` this would mean, that the prepare blocks must deal with potential nil values AND I have to detect somehow if the prepare block has already been called.

So I guess, the extension resolve hook does solve a lot of my problems, but not all. Are there any other hooks or methods I could use to solve this? Something that runs BEFORE prepare? I wouldn't mind monkey patching some stuff, as we have a pretty good test coverage. Sure, using only public interfaces would be better, but I have to find a solution somehow.

**Comment by rmosolgo** [comment]
Wow... Yeah, that'd definitely tough. 

Seeing what a mess it is to hack this behavior into the GraphQL runtime, it makes me consider again putting in the application instead of customizing how GraphQL works. I realize it happened to _work_ before, due to needless inefficency in GraphQL-Ruby, but any monkey-patch we add now will just break later...

What about implementing this behavior on the objects themselves, for example: 

```ruby 
def name(secret: false)
  object.name_or_secret(secret_requested: secret) 
end 
```

Where `def name_or_secret` on the underlying object checks the backend, and optionally uses the given `requested_secret` parameter? (And it wouldn't _have_ to be implemented on `object` -- it could be in some helper module, called on that instead, for example: `SecretHelper.secret_or_value(context[:current_user], secret, object.name)`.

If you really want to monkey-patch GraphQL-Ruby, the runtime argument-related classes are here: 

- https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/execution/interpreter/arguments.rb
- https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/execution/interpreter/arguments_cache.rb
- https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/execution/interpreter/argument_value.rb

But I expect that any of those will have the same problem as the original monkey-patch, where it isn't called again for each item in the list. (My _guess_ is that prepare would have that issue too, since arguments are only built once...)

**Comment by 23tux** [comment]
Handling it inside the objects themselves is also not an option for another reason: We define a GraphQL schema and derive an ActiveModel backend from that, e.g.

```
class UserType < GraphQL::Schema::Object
  field :name, String, null: false do
    argument :secret, Boolean, required: true
  end
end
```

becomes
```
# UserType.backend is an ActiveModel class
validate :name, presence: true

# UserType.fields.fetch(:name).backend is also an ActiveModel class
validate :secret, presence: true
```

When handling the logic inside the objects, I would have to set all arguments to `required: false`, so that the GraphQL engine "let me through" until I reach `#name` where I then could handle the argument. But setting everything to `required: false` would then generate a wrong backend, because the presence validation would be missing.

As most of this logic is generated in meta programming, everything has to commit to "one way of doing this". And I really liked the idea, that resolver methods like `#name` don't know *anything* about all the backend related logic, as it is handled for them beforehand, everything at one point, and the methods get their arguments just as every other resolver method.

And you're right, the prepare block is indeed only called once, even for multiple arguments.

> ...since arguments are only built once...

Could you give me some hints, if this could be customized on a per-argument base? I guess the argument cache does some comparison using `#eql?` or `#hash` of the argument instance? Could this be customized to lever out the caching for certain argument instance? And would this lead to a behaviour, where my original monkey patch with `#coerce_into_values` is called multiple times again for each list item that has an argument?

**Comment by rmosolgo** [comment]
> derive an ActiveModel backend 

😰 Yikes, that's like constructing a house based on a photo of a house. You can't derive a robust implementation from an interface definition. (Well, at least not without customizing the interface layer to _be_ the application...) 

Anyway, that being what it is, I guess you could try monkey-patching to revert the fix that broke this for you.  Maybe copying `ArgumentsCache` from the commit _before_ that one would work: https://github.com/rmosolgo/graphql-ruby/blob/a692a75384b6d446d7b7ee1355a4307871f14a63/lib/graphql/execution/interpreter/arguments_cache.rb (I don't think that class's interface changed, just the implementation.) I can't promise it will work for very long; these are internal concerns of GraphQL execution. But it might work for a while 🤷 

The other thing I could suggest is staying on v2.0.21, or forking graphql-ruby and merging the patches you want into your fork. At least that would give you enough control over the interface layer that you could keep your application code inside it!

**Comment by 23tux** [comment]
Thanks for the hint, I'll try to restore the commit and see how it goes.

> 😰 Yikes, that's like constructing a house based on a photo of a house. You can't derive a robust implementation from an interface definition. (Well, at least not without customizing the interface layer to be the application...)

😂 So far it works pretty good, we call it ContentGraph as we define structured content with it. The main goal was for our customers to define content (think of articles), combine it with data from the DB (think of products) and consume it in our own frontend (our design, our slim templates, our CSS) as well as in their external frontend via API. It's kind of a eat-your-own-dog-food situation, where we consume our own API that is also used by external clients. As we have pretty heavy tooling around it, it leads to the situation where a developer can build new components by only defining a GraphQL schema and some slim templates. From that we automatically generate the backend editor where our clients can input data, and everything is available for them via API.

I'd really love to hear some challenges about our approach, it's surely not perfect, but works for us (so far).
