### ISSUE TITLE
two terms (filter + mask) for the same concept

### ISSUE THREAD

**Issue by bgentry** [rmosolgo/graphql-ruby#481]
After upgrading to try out #480, I ran into a new deprecation notice:

```
.Schema.execute(..., except:) filters now accept two arguments, `(member, ctx)`. One-argument filters are deprecated.
```

It seems that the docs only use the term "mask" to describe these, but the deprecation notice and lots of internals call them "filters". If I'm correct that these are the same thing, maybe it makes sense to consolidate on a single term so it's less confusing?

**Comment by rmosolgo** [comment]
Yeah, it should be updated to `filters` everywhere!
