### ISSUE TITLE
Scoped context example breaks normalized stores

### ISSUE THREAD

**Issue by benjie** [rmosolgo/graphql-ruby#4812]
**Describe the bug**

The "scoped context" feature detailed [in your docs](https://graphql-ruby.org/queries/executing_queries.html#scoped-context) can lead to outcomes that do not align with the expectations of the GraphQL specification, and thus lead to subtle data corruption in normalized stores and badly rendered data.

To understand this issue, please read this article: https://benjie.dev/graphql/ancestors (and if it's helpful the related articles on [Graph Traversal](https://benjie.dev/graphql/traversal) and [Normalized Stores](https://benjie.dev/graphql/normalized)).

Specifically, it would be possible to get the same User object (i.e. the object of type `User` with the same `id` value) in multiple places in a query response, and yet for them to have different `isOriginalPoster` values. In a normalized store, one of the `isOriginalPoster` values will be used in both positions, resulting in subtle and misleading rendered data.

**Versions**

Your current documentation, retrieved `2024-01-29T12:10:00Z`.

**GraphQL schema**

As detailed in the documentation page at https://graphql-ruby.org/queries/executing_queries.html#scoped-context

**GraphQL query**

```graphql
{
  posts {
    id
    comments {
      id
      author {
        id
        isOriginalPoster
      }
    }
  }
}
```

**Steps to reproduce**

As detailed in the documentation page at https://graphql-ruby.org/queries/executing_queries.html#scoped-context

**Expected behavior**

The perceived result of an operation should not be aware that context-sensitive actions have occurred.

> Conformance requirements expressed as algorithms can be fulfilled by an implementation of this specification in any way **as long as the perceived result is equivalent**. Algorithms described in this document are written to be easy to understand. Implementers are encouraged to include equivalent but optimized implementations.
> -- https://spec.graphql.org/draft/#sel-EABDLDFAACHAo3V

**Actual behavior**

A response such as:

```json
{
  "posts": [
    {
      "id": 1,
      "comments": [
        {
          "author": {
            "id": 2,
            "isOriginalPoster": true
          }
        }
      ]
    },
    {
      "id": 3,
      "comments": [
        {
          "author": {
            "id": 2,
            "isOriginalPoster": false
          }
        }
      ]
    }
  ]
}
```

reveals that the behavior of the `User.isOriginalPoster` field, which should only be dependent on the User with id 2 and the arguments to that field (none), is actually dependent on additional data - thus the perceived result differs to that of [`ResolveFieldValue()`](https://spec.graphql.org/draft/#ResolveFieldValue()).

(Note: this is arguable since arguably the `objectValue` itself could be context-dependent, however doing so breaks the concepts of object identity that are not detailed in the core specification but are nonetheless a _de facto_ expectation of clients that use normalized stores such as Apollo Client, Relay, urql, and others. Namely it is assumed that when you receive a result with `__typename: "User"` and `id: 2`, that entry represents the unique object "User with id 2", a single node in your data graph (see [Graph Traversal](https://benjie.dev/graphql/traversal)), independent of the path through which it was fetched.)

**Additional context**

I do not use Ruby at all, this concern was raised to me by a community member (I am a member of the GraphQL Technical Steering Committee).

**Comment by rmosolgo** [comment]
Hey, thanks for reporting this and sharing those great writeups on the subject. I'll add a call-out to docs highlighting this possible incompatibility and pointing readers towards these other two solutions.

**Comment by benjie** [comment]
Perfect; I think this is a good backwards-compatible solution!
