### ISSUE TITLE
Put errors first in response

### ISSUE THREAD

**Issue by eapache-opslevel** [rmosolgo/graphql-ruby#4822]
Managed to ship a small bug today because the payload of my test query was large, and the graphql errors were buried at the bottom of the response (we just serialize the response object from this gem directly). Did a bit of poking around and noticed that it's already even suggested in the spec: https://spec.graphql.org/October2021/#sel-EAPHNCCBCEjFzpf

> When `errors` is present in the response, it may be helpful for it to appear first when serialized to make it more clear when errors are present in a response during debugging.

We can put a shim in our serialization of course, but it would be very nice if the gem returned the result hash with the `errors` key first.

@rmosolgo this feels like one of those things that ought to be a trivial reordering of two lines somewhere, but I looked and given how the response is built up I'm starting to think that fixing this might actually be quite involved...

cc @sabeerzaman

**Comment by rmosolgo** [comment]
Interesting ... I think the _main_ spot where the result Hash is actually created is here: 

https://github.com/rmosolgo/graphql-ruby/blob/6779577d17cbc3d1b228d82acd70b773d56e9a73/lib/graphql/execution/interpreter.rb#L113-L124 

(There are a couple of edge cases handled above, one with _only_ errors and the other with an empty response.) 

I'd definitely welcome this change if you want to give it a try!
