### ISSUE TITLE
Complexity computations for fields on connections

### ISSUE THREAD

**Issue by cheald** [rmosolgo/graphql-ruby#4831]
**Describe the bug**

We have a schema where, in some cases, fields are implemented on connections, allowing us to query aggregate information about a scope, taking advantage of the fact that the underlying `object.items` for a connection is the unpaginated query scope:

```ruby
class UserConnection < GraphQL::Types::Relay::BaseConnection
  field :roles, [String], null: false
  def roles
    object.items.distinct.pluck("role")
  end
end
```

Given something like that, we might query it as:

```gql
query g {
  users(first: 100) {
    roles
    totalCount
    nodes {
      id
      name
    }
  }
}
```

But this becomes a problem WRT complexity calculations, especially if we end up with nested connections.

**Observed behavior**

Complexity for this ends up calculating as:

    nodes: 2 (inner) + 1 (self) = 3
    roles: 1
    totalCount: 1 (metadata)

    Total:
    1           # users node
    (3 * 100)   # users selections total cost [5 - 1 for the nodes field - 1 for totalCount] * users page size
    1           # nodes field
    1           # metadata - just totalCount in this case
    = 303

**Expected behavior**

However, I think it should be:

    1          # users node
    (2 * 100)  # node inner selection * users page size
    1          # users.nodes node
    1          # users.totalCount
    1          # users.roles
    = 204

The single extra point of cost on the connection gets multiplied by the connection page size, even though we're only resolving that field once. When you have inner connections, an additional selection on the inner connection results in an extra (inner_max_page_size * outer_max_page_size * inner_selection_field_complexity) complexity, rather than (outer_max_page_size * inner_selection_field_complexity). This can lead to rapidly ballooning complexities which do not accurately reflect the actual complexity of the query.

The current complexity calculations take the total cost and subtract the known metadata keys (totalCount, pageInfo) before mulitiplying the child complexity by the page size. However, I think this is backwards: ideally, the complexity calculation would compute the complexity of the nodes/edges selections, multiply those by the page size, and add in the complexity of the remaining fields from the selection.

**Versions**

graphql-ruby 2.2.7
Rails 6.1

**Comment by rmosolgo** [comment]
Hey, thanks for the suggestion and the detailed report. I agree it should work like you describe -- the cost of a custom field shouldn't be multiplied by the number of subselections. 

`totalCount` and `pageInfo` get special handling here: 

https://github.com/rmosolgo/graphql-ruby/blob/33bc196023e471b602d97d7f82aa8f16b6159d40/lib/graphql/schema/field.rb#L486-L493

But maybe all selections on the connection field that _aren't_ on `edges` or `nodes` should be subtracted from the child complexity before multiplying it by the list size (instead of just the fields named there). Does that sound right to you? 

Another approach would be to support some kind of opt-in flag that identifies a field (and its subfields) as metadata, and then subtract the complexity for those fields.

**Comment by cheald** [comment]
Yes, subtracting the non-edges/nodes (or something mathematically equivalent) would be the right approach. However, as best as I could tell, there's no easy way to do this, because `calculate_complexity` doesn't receive information on the complexities of the subselections; it just receives a single integer as the sum total complexity of all the children, and then uses domain-specific knowledge about the nature of connections to count totalCount as 1, and uses `page_info_lookahead.selections.size` as the complexity for pageInfo. `calculate_complexity` doesn't have enough information to be able to tell what the complexity of `roles` is, in my example. It would need to receive the list of complexities by child, so it knows what to multiply and what to add (or subtract).

(Incidentally, this means that it's currently not possible to change the complexity of pageInfo or totalCount, were one to desire it for some reason)

A flag approach to track paginated and non-paginated subfields, then passing both complexities to `calculate_complexity` would work. However, this potentially breaks complexity arguments on fields in userspace, because separating paged and unpaged child complexities requires one of:

1. the introduction of at least one new parameter (breaking arity), or
2. changes the semantics of the parameters (passing child_complexity as a map of subfield => complexity rather than an int)

I suppose that an arity check could be implemented, and if the callback accepts 4 parameters you could do something like `call(ctx, args, paged_child_complexity, unpaged_child_complexity)`, and if it accepts 3, use the existing `call(ctx, args, total_child_complexity)`, but that feels like a footgun to me, personally.

My inclination would be an opt-in flag to identify a field for page size multiplication, personally; paged fields on connections are almost always going to ONLY be the static nodes/edges fields, while metadata or data about the relationship could be more variant. If the field were implemented, and then were installed by default by ConnectionBehaviors, then it should Just Work for the vast majority of cases.

Either approach would enable `calculate_complexity` to generalize without having to have any knowledge of connections at all though - by separating the paged and unpaged child complexities, it could be as simple as something like:

```ruby
def calculate_complexity(query:, nodes:, paged_child_complexity:, unpaged_child_complexity:)
  lookahead = GraphQL::Execution::Lookahead.new(query: query, field: self, ast_nodes: nodes, owner_type: owner)
  arguments = query.arguments_for(nodes.first, self)
  total_child_complexity = paged_child_complexity + unpaged_child_complexity
  return total_child_complexity if arguments.is_a?(GraphQL::ExecutionError)

  if respond_to?(:complexity_for)
    return complexity_for(
      unpaged_child_complexity: unpaged_child_complexity,
      paged_child_complexity: paged_child_complexity,
      arguments: arguments,
      query: query,
      lookahead: lookahead
    )
  end
  
  defined_complexity = complexity
  case defined_complexity
  when Proc
    defined_complexity.call(query.context, arguments, paged_child_complexity, unpaged_child_complexity)
  when Numeric
    defined_complexity + total_child_complexity
  else
    raise("Invalid complexity: #{defined_complexity.inspect} on #{path} (#{inspect})")
  end
end
```

where ConnectionBehaviors then installs a `complexity_for` handler or `complexity` proc by default for the connection fields, which accepts args/paged subfields cost/unpaged subfields cost, extracts the page size, and returns `(page_size * paged_cost) + unpaged_cost`.

This would be a significant divergence from the current status quo, though.

**Comment by cheald** [comment]
I've run into another odd case with connection complexity. Given a query:

```graphql
    reports(accountTreeId: $accountId) {
      id
      recentOwners(first: $first) {
        nodes {
          id
          name
          mostRecentReport
        }
      }
    }
```

`reports` is a connection, as is `recentFolders`. So, I have a connection chained off of a connection; however, the recentOwners connection is being multiplied out by the `reports` max_page_size.

```
       reports {                                 20004.00 (max page size: 100, child complexity: 203.00
         id                                          1.00
         recentFolders {                           202.00 (max page size: 100, child complexity: 3.00
           nodes {                                   3.00 (child complexity: 2.00
             id                                      0.00
             mostRecentReport                        1.00
             name                                    1.00
           }
         }
       }
```

The "actual" complexity here should be reports.id (1) + recentFolders (which is correctly 202) = 203, rather than 203 * 100 + 1.

I haven't yet tracked down *why* it's behaving like this, but it's clearly wrong and I'm not quite sure how to go about addressing it. I did drop some debug code into Field#calculate_complexity:

```ruby
            lookahead = GraphQL::Execution::Lookahead.new(query: query, field: self, ast_nodes: nodes, owner_type: owner)

            lookahead.selections.each do |next_lookahead|
              ap [:next_lookahead, next_lookahead, "complexity", next_lookahead.field.complexity, "size", next_lookahead.selections.size]
              # ...
```

```
[
    [0] :next_lookahead,
    [1] #<GraphQL::Execution::Lookahead @field="ReportConnection.recentOwners" @ast_nodes.size=1>,
    [2] "complexity",
    [3] 1,
    [4] "size",
    [5] 1
]
```

The complexity here is 1 rather than the expected 203, which seems like a likely culprit, but the *why* of its complexity returning 1 rather than 203 eludes me.

**Comment by cheald** [comment]
Okay, I think it's because `#calculate_complexity` calls `next_lookahead.field.complexity`, but when called without a value, it retrieves `@complexity || 1`, which is 1 for the connection, rather than the *full* complexity for the field, which results in only 1 being subtracted from the outer connection complexity, rather than the full inner connection's complexity.

No idea what the right way to fix it is, though.
