### ISSUE TITLE
Getting error when testing mutation in Graphiql

### ISSUE THREAD

**Issue by cberkom** [rmosolgo/graphql-ruby#484]
The error is occuring in GraphQL::Query::Variables. Am I formatting something wrong?

![image](https://cloud.githubusercontent.com/assets/1186933/21950737/bb68c056-d9b2-11e6-81f3-20f08c66109e.png)

My mutation looks like this:
```ruby
  module SourceMutations
    AdjustMonthlySpendForSource = GraphQL::Relay::Mutation.define do
      name "AdjustMonthlySpendForSource"
      input_field :id,    !types.Int # not a UUID, by design
      input_field :year,  !types.Int
      input_field :month, !types.String
      input_field :cost,  !types.Int

      return_field :success, types.Boolean
      resolve -> (root_obj, inputs, ctx) {
        ...
        { success: success }
      }
    end
  end
```

**Comment by cberkom** [comment]
Actually, hang on. I just updated the `graphql` gem to `1.4.0`, and the error message changed to:

![image](https://cloud.githubusercontent.com/assets/1186933/21951005/827dda26-d9b5-11e6-8cb3-f39f048ee94d.png)

Any advice on how to fix this?

**Comment by delkopiso** [comment]
You'll have to call `JSON.parse(params[:variables])` before sending it to the schema execute function because GraphiQL json stringifies the variables before sending them out.

**Comment by rmosolgo** [comment]
@delkopiso is right :) 

please reopen if something like that doesnt work for you, eg https://github.com/rmosolgo/graphql-ruby-demo/blob/master/app/controllers/queries_controller.rb#L7

**Comment by cberkom** [comment]
Awesome, thanks. Couldn't figure out why Relay could send queries with variables but Graphiql couldn't. This fixed it.
