### ISSUE TITLE
Help with GraphQL OTel Errors as of 2.2.10

### ISSUE THREAD

**Issue by arielvalentin** [rmosolgo/graphql-ruby#4851]
Sorry for the noise but was hoping to get some help with this:

https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/882

**Comment by rmosolgo** [comment]
Oops, I just shipped graphql-c_parser 1.0.8 with the new call signature for #4847 Sorry about the trouble! Let me know if this pops up again after updating to that new version.
