### ISSUE TITLE
Previously-uninitialized trace modes don't include the default tracers

### ISSUE THREAD

**Issue by eapache-opslevel** [rmosolgo/graphql-ruby#4855]
**Describe the bug**

(moved from https://github.com/Shopify/graphql-batch/issues/169)

Our schema class includes up to two tracing modules depending on the rails env:
```ruby
  if Rails.env.production?
    trace_with(GraphQL::Tracing::DataDogTrace, mode: :full_tracing)
  end

  # under the hood this calls `trace_with` as of https://github.com/Shopify/graphql-batch/pull/164
  # it does not specify a trace mode
  use GraphQL::Batch
```

Our execution flow then does:
```ruby
context[:trace_mode] = :full_tracing if debug_flag_set?
result = Schema.execute(query, variables: variables, context: context, operation_name: operation_name)
```

The intent is, of course, that in prod we can turn datadog tracing on and off with a debug flag, but that the graphql-batch tracer should *always* be present, whether debug flag is set or not, whether production or development. This lines up with the docs:
> Any custom trace modes also include the default trace_with ... modules (that is, those added without any particular mode: ... configuration).

However, in a non-prod environment when a query has the debug flag set, things don't seem to work:
- the schema does not have the datadog tracer loaded, and thus does *not* a-priori know about `full_tracing` mode
- the query *does* set `context[:trace_mode] = :full_tracing` because of the debug flag

As best I can tell, this causes the graphql-batch tracer to not execute, leading to an exception as soon as any field in the query tries to do a batch load:
> Cannot create loader without an Executor. Wrap the call to for with GraphQL::Batch.batch or use GraphQL::Batch::SetupMultiplex as a query instrumenter if using with graphql-ruby

Somehow the schema seeing an unknown trace mode causes *no* traces to execute, not even the defaults, which seems incorrect?

I'll also happily admit that our tracing setup is a bit convoluted and we could probably simplify it to avoid this bug, but I'd ultimately still expect this setup to work.

**Versions**

`graphql` version: 2.1.11
`rails`: 7.1.3
`graphql-batch`: 0.5.4

**Comment by rmosolgo** [comment]
Hey, thanks for the detailed report. I agree it should do ... _something_ better here! I prepared a replication script: 

```ruby
require "bundler/inline"

gemfile do
  gem "graphql", "2.2.10"
  gem "graphql-batch", "0.5.4"
end

class MySchema < GraphQL::Schema
  class IntLoader < GraphQL::Batch::Loader
    def perform(ints)
      ints.each { |i| fulfill(i, i) }
    end
  end

  class Query < GraphQL::Schema::Object
    field :f, Int
    def f
      IntLoader.load(1)
    end
  end
  query(Query)

  use GraphQL::Batch
end

# Default:
pp MySchema.execute("{ f }").to_h

# Something unknown:
pp MySchema.execute("{ f }", context: { trace_mode: :unregistered }).to_h
```

Seems to me like it should use `:default` in this case. I'll work up a patch.

**Comment by rmosolgo** [comment]
#4856 fixed the replication script for me -- want to give it a try, @eapache-opslevel ?
