### ISSUE TITLE
Validations on Fields

### ISSUE THREAD

**Issue by Gbeschbacher** [rmosolgo/graphql-ruby#4857]
**Describe the bug**

In the documentation ([see here](https://graphql-ruby.org/fields/validation.html#custom-validators)), it's stated that

> Fields (and their arguments, and input object arguments) can be validated at runtime using built-in or custom validators.

However, validating a Field results in an error. 

**Versions**
graphql version: 2.2.8
rails: 7.0.7.2
graphql-batch: 0.5.4

**GraphQL schema**

```ruby
class ExampleType < GraphQL::Schema::Object
  field :name, String, null: false
  field :percent, Float, null: true do
    validates numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
  end

  def percent
    10.5
  end
end

class ExampleQueries < GraphQL::Schema::Object
  field :examples, [ExampleType], null: false

  def examples
    context.fetch(:examples)
  end
end

class ExampleSchema < GraphQL::Schema
  query ExampleQueries
end
```

**GraphQL query**

```ruby

context = {
  examples: [
    { name: "Example 1", percent: 5 },
    { name: "Example 2", percent: nil }
  ]
}
response = ExampleSchema.execute("query { examples { name percent } }", context:).to_h
```

**Expected behavior**

I would expect a normal graphql response.

**Actual behavior**

The following Error is thrown:
```ruby
TypeError: no implicit conversion of Integer into Hash
from /usr/local/bundle/gems/graphql-2.2.8/lib/graphql/schema/validator/numericality_validator.rb:61:in `<'
```

**Additional context**
From my point of view, it looks like the internal code of Graphql only ever validates Arguments. If I understand the code correctly, it all starts with the Field resolution [here](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/field.rb#L648). And the following line triggers validations: `@own_validators && Schema::Validator.validate!(validators, application_object, query_ctx, args)`. The field value is never passed in as a validation value and therefore the error occurs (because args is an empty object as default).

**Comment by rmosolgo** [comment]
Hey, thanks for raising this issue. I agree that the existing documentation is describes it poorly -- only arguments can be validated. There isn't any built-in mechanism for validating return values from fields. (Except maybe for custom scalars, but that's a whole other thing... ) 

Sorry for the confusion. I guess the best thing is just to update that documentation.

**Comment by Gbeschbacher** [comment]
Thanks for the quick response!

- Why is it even possible to call validate on fields? 
- How would you start with validating the return values from fields? I guess the trickiest part is to validate lazy resolved fields, right?

Thanks in advance!

**Comment by rmosolgo** [comment]
> Why is it even possible to call validate on fields?

Fields accept `required: { one_of: [...] }` in order to validate that _one of_ that set of arguments is present. It's really validating the _arguments_, but it's added to the field since the field is what can see all incoming arguments. 


> validating the return values from fields? 

GraphQL-Ruby doesn't have anything for that (except scalar types, which ensure that the returned values are coerced to the right GraphQL type). I'd suggest implementing that in application logic and testing it via unit tests, then calling those application methods from the GraphQL layer.
