### ISSUE TITLE
Validation for orphan types

### ISSUE THREAD

**Issue by swalkinshaw** [rmosolgo/graphql-ruby#4858]
**Is your feature request related to a problem? Please describe.**
This doesn't really cause any current problems but right now _any_ kind of type can be set as an `orphan_type` (either on the schema or an interface). However, only object types should be orphan types as the [docs](https://graphql-ruby.org/type_definitions/interfaces.html#orphan-types) describe.

We've had a few instances of developers adding non-object types which could cause a misunderstanding of the feature since it's allowed.

**Describe the solution you'd like**
Raise a descriptive error when trying to pass a non-object type to `orphan_types`

**Describe alternatives you've considered**
We could do this in our own application but I think it belongs in the gem.

If you agree this should be added we could probably contribute it 😄

**Comment by rmosolgo** [comment]
:+1: This sounds good to me. 

We now have `extra_types ...` which does the thing that `orphan_types` _sounds_ like it should do: https://github.com/rmosolgo/graphql-ruby/blob/1c4b1dcc3822fb90d455663298fa4e8be9971b14/lib/graphql/schema.rb#L829-L831
