### ISSUE TITLE
Using urql with ActionCable

### ISSUE THREAD

**Issue by udl** [rmosolgo/graphql-ruby#4872]
First of all thank you for your work on this gem, it's a really great library and I love working with it!

For my current project it would be great to have urql subscriptions in combination with a ActionCable backend. I don't have that many concurrent users to justify adding Pusher to the mix.
I might also be able to implement it myself and contribute back if you can give me a hint as to how it should work. I'm mostly working in backend, so I'm not so proficient in the JS/TS world.

Thank you!

**Comment by rmosolgo** [comment]
Hi! Yes, I'm no front-end wizard either, but I think this should be possible just fine. The approach I would take is: 

- modify the existing `SubscriptionExchange` to accept a `consumer: ActionCable.Consumer` option 
- modify `SubscriptionExchange.create` to handle that option and return a function which, when called with an `operation`, returns an object with an `unsubscribe()` function, just like it does when given a `pusher: ...` 

For implementing that function, you could lean heavily on `createActionCableHandler`. It works in a similar way: it creates a function which, when called, returns an object with an unsubscribe function (in that case, the function is named `dispose()`). 

I might be able to take a look at this soon, but that's the way I'd go about it -- please give it a shot if you're interested!

**Comment by udl** [comment]
Ok, I will give it a try. Thank you for pointing me towards the general direction!
