### ISSUE TITLE
No file descriptors available - IO_Event_Selector_EPoll_initialize:epoll_create

### ISSUE THREAD

**Issue by Amnesthesia** [rmosolgo/graphql-ruby#4881]
**Describe the bug**

After running for a while, we start getting these kind of errors related to open file descriptors, where the maximum allowed open files are exhausted.

Locally, this can be "fixed" or postponed by increasing the allowed number of file descriptors, but we get this in production as well.

**Versions**

`graphql` version: 2.2.7
`rails` (or other framework): 7.1
other applicable versions (`graphql-batch`, etc):

```
graphql-pro (1.26.1)
      graphql (>= 1.7.5)
      graphql (>= 1.8)
    graphql (2.2.7)
    graphql-c_parser (1.0.7)
      graphql
    graphql-fragment_cache (1.19.0)
      graphql (>= 1.12.0)
    graphql-metrics (5.0.8)
      graphql (>= 1.12.10)
    graphql-rails_logger (1.2.4)
    rubocop-graphql (1.4.0)
```

**Steps to reproduce**

This is kind of tricky to reproduce because it doesn't happen all the time. You can probably reproduce it by reducing allowed file listeners and running for a while, when using `use GraphQL::Dataloader::AsyncDataloader` with `Fiber.set_scheduler Evt::Scheduler.new`

**Expected behavior**

Not to exhaust file descriptors past limit

**Actual behavior**

What specifically went wrong?

Place full backtrace here (if a Ruby exception is involved):

<details>
<summary>Click to view exception backtrace</summary>

```
Unhandled error during GraphQL execution:

  No file descriptors available - IO_Event_Selector_EPoll_initialize:epoll_create
    /vendor/ruby/3.3.0/gems/io-event-1.3.3/lib/io/event/selector.rb:29:in `initialize'
    /vendor/ruby/3.3.0/gems/io-event-1.3.3/lib/io/event/selector.rb:29:in `new'
    /vendor/ruby/3.3.0/gems/io-event-1.3.3/lib/io/event/selector.rb:29:in `new'
    /vendor/ruby/3.3.0/gems/async-2.6.5/lib/async/scheduler.rb:35:in `initialize'
    /vendor/ruby/3.3.0/gems/async-2.6.5/lib/async/reactor.rb:19:in `initialize'
    /vendor/ruby/3.3.0/gems/async-2.6.5/lib/kernel/sync.rb:23:in `new'
    /vendor/ruby/3.3.0/gems/async-2.6.5/lib/kernel/sync.rb:23:in `Sync'
    /vendor/ruby/3.3.0/gems/graphql-2.2.7/lib/graphql/dataloader/async_dataloader.rb:36:in `block in run'
    /vendor/ruby/3.3.0/gems/graphql-2.2.7/lib/graphql/dataloader.rb:233:in `block in spawn_fiber'
    
Use #cause to access the original exception (including #cause.backtrace).

GraphQL Backtrace:
Loc  | Field                    | Object                                                                                               | Arguments                                | Result
21:3 | DynamicFields.__typename | #<Types::Reporting::SummaryType:0x00007f9d02fa7598 @object=#<Statistics::Summary... | {}                                       | #<Errno::EMFILE: No file descriptors available - IO_Event_Selector_EPoll_initialize:epoll_create>
2:3  | Query.statsSummary | nil                                                                                                  | {:user_practice_connection_id=>"270581"} | {completed: 1, cancelled: 0, missed: 0, lateCancellation: 0, inProgress: 0, scheduled: 0, unconfi...
1:1  | query StatsSummary | nil                                                                                                  | {"userPracticeConnectionId"=>"270581"}   | {statsSummary: {...}}
```

</details>

**Comment by rmosolgo** [comment]
Hey, thanks for the detailed report and sorry for the trouble. I kind of _doubt_ this is related to the problem, but starting in GraphQL-Ruby 2.2.0, `AsyncDataloader` uses the `async` gem directly, allowing that gem to use its own concurrency system. I'm assuming `async` removes the current scheduler and sets up its own, but it might help to stop setting up `Evt::Scheduler` since GraphQL-Ruby isn't actually using it. 

To use `Evt::Scheduler`, you could pass `use GraphQL::Dataloader, nonblocking: true`, but that approach is deprecated. 

Have you been successfully using `Evt::Scheduler` before this? 

What kind of conditions trigger this error? Is it particularly large queries? I'd like to replicate it myself if I can. One possibility may be limiting the number of active Fibers in Ruby -- I've explored that before -- but I'm not sure if that's really the fix here.

**Comment by Amnesthesia** [comment]
@rmosolgo Hey, no we haven't really used `Evt::Scheduler` before, but read somewhere in the docs that we needed to set up a Fiber scheduler, and went with one that worked. If graphql-ruby doesn't actually need Fiber.set_scheduler anymore, we can try removing it and see if that solves it

**Comment by Amnesthesia** [comment]
Awesome, thank you. We've removed this and seem to be unable to reproduce it so far. However, the docs mention setting `isolation_level = :fiber` — is this necessary with the async dataloader? Doing this significantly increases the response time for queries for us because of how we're stuck with Apartment, which I think affects this, and it also affects usage of `ActiveSupport::CurrentAttributes`

**Comment by rmosolgo** [comment]
Yeah, I'm pretty sure you need to tell Rails to use Fibers or weird stuff will happen (https://socketry.github.io/async/guides/compatibility/index#rails). 

If that's really not an option, you could check out these other approaches to parallelism on top of Dataloader (which can use Threads): https://graphql-ruby.org/dataloader/parallelism

**Comment by Amnesthesia** [comment]
@rmosolgo What kind of weird stuff would that be? For our use-case, because of outdated stuff in Apartment combined with how `Thread.current` was updated to set Fiber-local variables, when we use schema-based multi-tenancy, we lose the schema search path sometimes when switching Fiber. This causes a lot of overhead, if each Fiber needs to switch schema on the database connection instead of inherit it from the parent thread

We're currently running with isolation_level set back to thread because each thread (and its child fibers) should, as far as I'm aware, not need to switch schema or have any other need to not share local data that I'm aware of, and so far we haven't noticed any weird stuff. What should we look out for?

Switching this back to `isolation_level = :fiber` would almost double the response times for us because of this overhead. 

Are you aware of any other implementations of the dataloader ref the parallelism link, or is this all custom per app and use case? 

As for the original issue, getting rid of `Evt` seems to have resolved the original issue so this ticket can be closed. Thank you so much for your quick and helpful responses!

**Comment by rmosolgo** [comment]
> What kind of weird stuff would that be?

I honestly don't know. In _this_ project, we were debugging ActiveRecord's connection pool, where connections were being picked up by Fibers but not released. `isolation_level = :fiber` was _part_ of the solution, but may not have been the whole solution (the previous AsyncDataloader also suffered from a Fiber cleanup issue...)

I think the way to find out what might break would be to search for `ActiveSupport::IsolatedExecutionState.context` in Rails. (That's either the current Thread or the current Fiber, depending on the app setting.) I imagine that issues and PRs referencing that value would also give a clue. 

I don't know of other dataloader implementations. There's GraphQL-Batch, which solves the same problem in a similar way, but it doesn't have any built-in parallelism either. 

How about the `Concurrent::Future` approach mentioned in the GraphQL-Ruby docs? That uses threads under the hood, so I'd expect it to play nice with `isolation_level = :thread`. It's a custom solution, but as an upside, you could roll it out one `Dataloader::Source` at a time, minimizing the risk of deploying something new. 

I'll close this but feel free to continue the discussion if you decide to pursue parallelism further!
