### ISSUE TITLE
[How to]  define one of two arguments required in a mutation

### ISSUE THREAD

**Issue by Tao-Galasse** [rmosolgo/graphql-ruby#4909]
Hello!

First of all, thanks for your amazing gem @rmosolgo :)

Here is my issue: I want to create a mutation where the user can give me an ID or a list of attributes to create a new nested record.

So my mutation looks like this:
```ruby
module Mutations
  class myMutation < BaseMutation
    argument :product_id, ID, loads: Types::ProductType, required: false
    argument :product_attributes, Types::ProductInput, required: false
    # a bunch of other arguments here...
```
I want to specify that one of those is required, but not both.
I saw [this part of the doc](https://graphql-ruby.org/fields/validation.html) and tried to add `validates required: { one_of: %i[product_id product_attributes] }` below my arguments list, but it does not seem to work. I receive the error message `myMutation has the wrong arguments`.

With [this other part of the doc](https://graphql-ruby.org/type_definitions/input_objects.html#oneof), I found another example of implementation : I could change my mutation to something like this : `argument :product, Types::Inputs::ProductInput, required: true`, and define a ProductInput like this : 
```ruby
module Types
  class ProductInput < Types::BaseInputObject
    one_of
    argument :id, ID, loads: Types::ProductType, required: false
    argument :product_attributes, Types::ProductAttributesInput, required: false
  end
end
```
and it looks like it works!

But to be honest, I don't really like this solution. If you want to specify an ID, the request would look like this : 
```graphql
input: {
  product: {
    id: "my_id"
  }
  some_other_stuff: "here"
}
```
instead of a more simple `productId` ; and worse if you want to use attributes to create your own product : 
```graphql
input: {
  product: {
    productAttributes: {
      name: "my new product",
      price: 123
    }
  }
  some_other_stuff: "here"
}
```

Is there a way to specify which arguments should be included in the `one_of` without having to create a whole new Input class?

Thanks a lot for your help and your great work! 🚀

**Comment by rmosolgo** [comment]
Hi, thanks for your detailed question! 

Since you're using RelayClassicMutation, it's a bit tricky to access the generated type for the `input: ...` argument, but you can. For example, you could do this: 

```ruby 
    argument :product_id, ID, required: false
    argument :product_attributes, ProductAttributes, required: false
    # Access the generated `input: ...` type, 
    # and make it require one of its arguments:
    input_type.one_of
```

Which would return errors like this: 

```ruby 
{"errors"=>
  [{"message"=>
     "OneOf Input Object 'UpdateProductInput' must specify exactly one key.",
    "locations"=>[{"line"=>1, "column"=>33}],
    "path"=>["mutation", "updateProduct", "input"],
    "extensions"=>
     {"code"=>"invalidOneOfInputObject",
```

And generate a schema like this: 

```graphql 
"""
Autogenerated input type of UpdateProduct
"""
input UpdateProductInput @oneOf {
  """
  A unique identifier for the client performing the mutation.
  """
  clientMutationId: String
  productAttributes: ProductAttributes
  productId: ID
}
```

Alternatively,  you could modify that generated input object type like this: 

```ruby
    # Access the generated `input: ...` type,
    # and make it require one of its arguments:
    input_type.validates(required: { one_of: [:product_id, :product_attributes] })
```

And it would return a slightly different error: 

```ruby 
{"errors"=>
  [{"message"=>"UpdateProductInput has the wrong arguments",
    "locations"=>[{"line"=>1, "column"=>12}],
    "path"=>["updateProduct"]}],
 "data"=>{"updateProduct"=>nil}}
```

And it wouldn't put a `@oneOf` directive in the generated SDL. 


I hope one of those works for you! If it doesn't please let me know, sharing the code that you tried and what outcome you got when you tried it.
