### ISSUE TITLE
A way to apply some sort of default_scope for ONLY graphql queries/mutations

### ISSUE THREAD

**Issue by Austin-X** [rmosolgo/graphql-ruby#4913]
**Is your feature request related to a problem? Please describe.**

To illustrate what I mean by the title of this issue, I'm going to use an example.

Let's say that I have an `Author` model as defined below:
```ruby
class Author < ApplicationRecord
end
```
And let's also say that I have a simple mutation to update an author by id as defined below:
```ruby
module Mutations
  class AuthorUpdate < BaseMutation
    description "Updates an author by id"
    field :author, Types::AuthorType, null: false
    argument :auth, Types::AuthorInputType, required: true

    def resolve(auth:)
      author = Author.find(auth.id)

      if author.update(name: auth.name)
       { author: author }
      end
    end
  end
end
```

Now, let's say that I want this mutation to ONLY update the author when the author has an id of 1.

One way to do this is by obviously adding `default_scope { where(id: 1) }` to the Author model, but I saw that using `default_scope` is [bad practice](https://piechowski.io/post/why-is-default-scope-bad-rails/), so I was just wondering if there was a better way to apply some sort of default_scope to all GQL queries and mutations.

**Describe the solution you'd like**
I'm pretty sure a solution already exists but I was just wondering if the solution that I've been using is the intended solution for this type of problem. (See the next section for the solution I've been using)

**Describe alternatives you've considered**
The solution I've been using involves adding the line of code highlighted in green below and defining the necessary `self.authorized?` method in `base_object.rb`
![image](https://github.com/rmosolgo/graphql-ruby/assets/32133198/4220da09-4234-4621-88fe-6462ab77cb00)

**Comment by swalkinshaw** [comment]
Have you looked into the auto-loading argument feature? https://graphql-ruby.org/mutations/mutation_classes.html#auto-loading-arguments

It automatically runs `authorized?` like you're doing in addition to the loading

**Comment by Austin-X** [comment]
@swalkinshaw Thanks Scott! That auto-loading argument feature you suggested works for all of my mutations which take an Author as an argument.

I have another question which I will demonstrate with an example. In this example, I have a query named `allAuthors` and another query named `all_authors_with_id_less_than_ten` as shown in the code snippet below
```ruby
module Types
  class QueryType < Types::BaseObject
    field :all_authors, [Types::AuthorType], null: false
    def all_authors
      Author.all
    end

    field :all_authors_with_id_less_than_ten, [Types::AuthorType], null: false
    def all_authors_with_id_less_than_ten
      Author.where('id < 10')
    end
  end
end
```

Now, I want to restrict these two queries to only show authors that have an id of 1. My solution uses [`scope_items`](https://graphql-ruby.org/authorization/scoping.html#scope_itemsitems-ctx-method), and I was just wondering if using `scope_items` is the best way to solve this type of problem.

**Comment by rmosolgo** [comment]
Yes, that's just what `scope_items` is for -- sounds good! Please let me know if you have any other questions or trouble with it.
