### ISSUE TITLE
Private vulnerability reporting

### ISSUE THREAD

**Issue by Sim4n6** [rmosolgo/graphql-ruby#4914]
Hey ,

I have identified a potential vulnerability in the latest codebase [rmosolgo/graphql-ruby](https://github.com/rmosolgo/graphql-ruby).

Could you please consider enabling the GitHub feature for [private vulnerability reporting](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository) to smooth the disclosure process ? or in case if you have a bug bounty program, please send me an invitation.

Thank you
@Sim4n6

**Comment by rmosolgo** [comment]
Hi, sure -- it's enabled!

**Comment by rmosolgo** [comment]
For those keeping score at home, the suspected vulnerability was these lines _in the test suite:_ 

https://github.com/rmosolgo/graphql-ruby/blob/8eb9833e21cef02ef4dcab11155202affa79b41f/spec/graphql/analysis/ast/query_complexity_spec.rb#L574C20-L574C25

So, if you're running that spec file in production, take care 😆
