### ISSUE TITLE
`GraphQL::Language::Nodes::Document` is not compatible with Marshal in version 2.3

### ISSUE THREAD

**Issue by alexus37** [rmosolgo/graphql-ruby#4955]
**Describe the bug**

In the latest 2.3 version of the GraphQL gem, it's not possible to dump documents using Marshal.

**Versions**

`graphql` version: 2.3.3

**Steps to reproduce**

```ruby
require "bundler/inline"

gemfile do
    source 'https://rubygems.org'
    gem "base64", "~>0.2.0"
    gem "graphql", "~>2.3.3" 
end


class MySchema < GraphQL::Schema
  class User < GraphQL::Schema::Object
    field :login, String
  end

  class Query < GraphQL::Schema::Object
    field :viewer, User
  end

  query(Query)
end


query_string = "query { viewer { login  } }"
document = GraphQL.parse(query_string)
Marshal.dump(document)
# raises `dump': no _dump_data is defined for class StringScanner (TypeError)
```

**Expected behavior**

No error is raised .

**Actual behavior**

A `TypeError` is raised from the StringScanner

**Comment by rmosolgo** [comment]
Ah, sorry about that! I didn't have a test for usage with `Marshal` but it should be supported. I added a test and worked up a fix in #4958.
