### ISSUE TITLE
Incorrect Yarn doc: execute can return a Result, not only Hash

### ISSUE THREAD

**Issue by bmulholland** [rmosolgo/graphql-ruby#4982]
https://github.com/rmosolgo/graphql-ruby/blob/b7551b54d87355fd0d451cb335425272cbfdeb05/lib/graphql/execution/interpreter.rb#L23 says returns array of hashes

But https://github.com/rmosolgo/graphql-ruby/blob/b7551b54d87355fd0d451cb335425272cbfdeb05/lib/graphql/execution/interpreter.rb#L129 means it can also return a Result element

(relevant because these docs are used for some auto-generation of types and editor features, and because it's used for reference in situations like https://github.com/Shopify/rbi-central/issues/250)

**Comment by rmosolgo** [comment]
Thanks for reporting this! I definitely want to generate the best types I can 🍻  Fix in the works at #4984

**Comment by bmulholland** [comment]
Awesome -- thanks for the clarity! I've updated the RBI to match over at rbi-central.
