### ISSUE TITLE
Nil Fields

### ISSUE THREAD

**Issue by devknoll** [rmosolgo/graphql-ruby#5]
If a field is nil, graphql-ruby still tries to instantiate a node and read properties off a nil target. It seems like it should just return a nil object, though that might have to wait for the official spec.

**Comment by rmosolgo** [comment]
ditto :)

**Comment by rmosolgo** [comment]
under todos:

![image](https://cloud.githubusercontent.com/assets/2231765/7713098/515ebbc6-fe2a-11e4-97dd-7e174fe5bab3.png)

**Comment by devknoll** [comment]
:+1:
