### ISSUE TITLE
`GraphQL::Query#variables` raises `GraphQL::Schema::Enum::MissingValuesError` when the enum isn't visible

### ISSUE THREAD

**Issue by eapache-opslevel** [rmosolgo/graphql-ruby#5002]
**Describe the bug**

We have an enum with limited visibility. When that enum is used in an input variable (nested in an input object, though that may be irrelevant), and the enum isn't visible, and our ruby code calls `result.query.variables`, it crashes with the noted `MissingValuesError` because none of the values of the enum pass the warden.

The query itself returns the correct error to the user, but `result.query.variables` shouldn't crash here I don't think.

**Versions**

`graphql` version: 2.2.14
`rails` (or other framework): 7.1.3.4

**GraphQL schema**
(with some stuff elided of course)
```ruby
module Types
  class TypeEnum < Types::BaseEnum
    TYPES = [
      :contains,
      :equals,
    ]

    TYPES.each do |type|
      value(type)
    end
  end
end

module Types
  class FilterInput < Types::BaseInputObject
    argument :type,
      Types::TypeEnum,
      required: false,
      default_value: "equals",
      visibility: :public
  end
end
```

**GraphQL query**

```graphql
query servicesIndex($filter: [FilterInput!]) {
  account {
    services(filter: $filter) {
      nodes {
        id
      }
    }
  }
}
```
variables:
```json
{
  "filter": {
    "type": "equals",
  }
}
```

The query seems to return the right error message when executed normally:
```
(byebug) result.to_h
{"errors"=>[{"message"=>"Field 'services' doesn't accept argument 'filter'", "locations"=>[{"line"=>3, "column"=>14}], "path"=>["query servicesIndex", "account", "services", "filter"], "extensions"=>{"code"=>"argumentNotAccepted", "name"=>"services", "typeName"=>"Field", "argumentName"=>"filter"}}, {"message"=>"Variable $filter is declared by servicesIndex but not used", "locations"=>[{"line"=>1, "column"=>1}], "path"=>["query servicesIndex"], "extensions"=>{"code"=>"variableNotUsed", "variableName"=>"filter"}}]}
```

**Actual behavior**

<details>
<summary>Click to view exception backtrace</summary>

```
GraphQL::Schema::Enum::MissingValuesError: Enum types require at least one value, but TypeEnum didn't provide any for this query. Make sure at least one value is defined and visible for this query. (GraphQL::Schema::Enum::MissingValuesError)
  from graphql (2.2.14) lib/graphql/schema/warden.rb:216:in `block in enum_values'
  from graphql (2.2.14) lib/graphql/schema/warden.rb:380:in `block in read_through'
  from graphql (2.2.14) lib/graphql/schema/warden.rb:220:in `enum_values'
  from graphql (2.2.14) lib/graphql/schema/enum.rb:133:in `validate_non_null_input'
  from graphql (2.2.14) lib/graphql/schema/member/validates_input.rb:15:in `validate_input'
  from graphql (2.2.14) lib/graphql/schema/input_object.rb:181:in `block (2 levels) in validate_non_null_input'
  from actionpack (7.1.3.4) lib/action_controller/metal/strong_parameters.rb:400:in `block in each_pair'
  from actionpack (7.1.3.4) lib/action_controller/metal/strong_parameters.rb:399:in `each_pair'
  from actionpack (7.1.3.4) lib/action_controller/metal/strong_parameters.rb:399:in `each_pair'
  from graphql (2.2.14) lib/graphql/schema/input_object.rb:173:in `block in validate_non_null_input'
  from graphql (2.2.14) lib/graphql/schema/input_object.rb:172:in `each'
  from graphql (2.2.14) lib/graphql/schema/input_object.rb:172:in `validate_non_null_input'
  from graphql (2.2.14) lib/graphql/schema/member/validates_input.rb:15:in `validate_input'
  from graphql (2.2.14) lib/graphql/schema/non_null.rb:40:in `validate_input'
  from graphql (2.2.14) lib/graphql/schema/list.rb:51:in `block in validate_non_null_input'
  from graphql (2.2.14) lib/graphql/schema/list.rb:50:in `each'
  from graphql (2.2.14) lib/graphql/schema/list.rb:50:in `each_with_index'
  from graphql (2.2.14) lib/graphql/schema/list.rb:50:in `validate_non_null_input'
  from graphql (2.2.14) lib/graphql/schema/member/validates_input.rb:15:in `validate_input'
  from graphql (2.2.14) lib/graphql/query/variables.rb:38:in `block in initialize'
  from graphql (2.2.14) lib/graphql/query/variables.rb:19:in `each'
  from graphql (2.2.14) lib/graphql/query/variables.rb:19:in `each_with_object'
  from graphql (2.2.14) lib/graphql/query/variables.rb:19:in `initialize'
  from graphql (2.2.14) lib/graphql/query.rb:257:in `new'
  from graphql (2.2.14) lib/graphql/query.rb:257:in `block in variables'
  from graphql (2.2.14) lib/graphql/query.rb:460:in `with_prepared_ast'
  from graphql (2.2.14) lib/graphql/query.rb:256:in `variables'
```

</details>

**Comment by rmosolgo** [comment]
Hey, sorry it took me so long to get to this. It took a while to replicate this issue but finally I found the crux of it: all enum _values_ return `false` for `visible?`, but the enum itself still returns `true`. 

It might be possible to add a check to GraphQL-Ruby to catch this situation and hide the enum type when all values are hidden, but having maintained those kinds of checks for many years, I'm starting to shy away from them because they leave developers confused as to why things are hidden. 

Instead, I suggest adding a visibility condition to the enum _type_ itself which hides the enum in the same cases when all the values are hidden. Then, the argument will be hidden altogether just as when the query is executed. 

If that solution doesn't work in your application, could you please share some details about how your `visible?` checks are implemented? For example, how is that method defined for your Enum types and Enum values, and how is the data populated when running queries? Maybe we can find something else that works.

Honestly, I wasn't able to replicate the _exact_ situation you describe here, where `.variables` raises but `.result` succeeds (with `"errors" => ...`). In my test, I found that `.result` also raised `MissingValuesError`. That's the intended behavior: `MissingValuesError` is a developer-facing error which should be addressed by modifying the schema visibility code. I bet the set-up in my test doesn't match your application quite right, so if we need to find another solution, I can probably update the test to match your app more closely.

**Comment by eapache-opslevel** [comment]
Thanks for the detailed investigation! Some additional context from our side:
- we mostly don't bother setting visibility on an object/type level in our schema; we set it on individual fields/arguments/values, and allow the natural reachability of the API to do the rest; it doesn't usually matter what `visible?` on a schema object returns if it's only reachable via private fields
- so you're absolutely right that we had an Enum type that had no visible values, where the type itself had default ("public") visibility - but the Enum type was only ever used by private fields/arguments, so it was still effectively private
- I will note that this works just fine for object types; we have tons of objects with only private-visibility fields, where the object itself technically has the default ("public") visibility, but is only reachable via other private fields; this seems to work just fine
- I guess it's something specific about input variables that is the key factor here, since they let you reference a type more directly without worrying about whether it's "reachable" in the schema or not?
- overriding `def visible?` on the enum type itself does fix the crash 🎉 
- I'm still able to reproduce the distinction between calling `.variables` (crashes) and simply executing the query (returns the proper user-facing error)

My first instinct is still that graphql-ruby shouldn't even be evaluating the `TypeEnum` in this case. It should be seeing that the `filter` argument isn't visible and short-circuiting immediately with "Field 'services' doesn't accept argument 'filter'" - there's no reason for it to try and type-check the variable at all.

**Comment by eapache-opslevel** [comment]
I realize now that I didn't include this in the schema-snippet I originally provided, so maybe this is the critical missing piece that is the difference between our setups: the `services` field (on `AccountType`) is marked as public, but the `filter` argument on that field is marked private.

Perhaps that is why the query execution is able to short-circuit correctly without evaluating the type of the variable for me, but calling `.variables` still triggers the crash, since the latter ignores that the variable is only used for an inaccessible argument?

**Comment by rmosolgo** [comment]
Ah, I bet you're right!
