### ISSUE TITLE
NoMethodError - `context.types` not populated in 2.3.8

### ISSUE THREAD

**Issue by hwrdprkns** [rmosolgo/graphql-ruby#5042]
**Describe the bug**

On 2.3.7 this code passed in tests, but this breaks in 2.3.8. 

**Versions**

`graphql` version: 2.3.7
`rails` (or other framework): Rails 7.x 

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok). Any custom extensions, etc?

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile do
  gem "graphql", "2.3.7"
  gem "rspec"
  gem "factory_bot"
end

require "rspec/autorun"

class Schema < GraphQL::Schema
  class TestInput < GraphQL::Schema::InputObject
    argument :test, String, required: true
  end

  class QueryRoot < GraphQL::Schema::Object
    field :nested_query, String, null: false do
      argument :input, TestInput, required: true
    end

    def nested_query(input:)
      "Some Return!"
    end
  end

  query(QueryRoot)
end

FactoryBot.define do
  factory :test_input, class: "Schema::TestInput" do
    test { "Test" }

    initialize_with { new(attributes, ruby_kwargs: {}, context: {}, defaults_used: nil) }
  end
end

RSpec.describe Schema do
  it "passes these tests on 2.3.7 but not 2.3.8" do
    expect(FactoryBot.build(:test_input)).not_to be_nil
  end
end
```

**Steps to reproduce**

Run the above script with 2.3.7 - it passes
Run the above script with 2.3.8 - it fails

**Expected behavior**

I would have expected this to pass.

**Actual behavior**

Hit a `NoMethodError`

Place full backtrace here (if a Ruby exception is involved):

<details>
<summary>Click to view exception backtrace</summary>

```
  1) Schema passes these tests on 2.3.7 but not 2.3.8
     Failure/Error: initialize_with { new(attributes, ruby_kwargs: {}, context: {}, defaults_used: nil) }

     NoMethodError:
       undefined method `types' for {}:Hash

               arg_defns = context ? context.types.arguments(self.class) : self.class.arguments(context).each_value
```
</details>

**Additional context**

It looks like this is the PR that broke things: https://github.com/rmosolgo/graphql-ruby/pull/4998 . Is there a workaround to use to instantiate Inputs or Objects? 

With these details, we can efficiently hunt down the bug!

**Comment by x-eleos** [comment]
👋  from Github, we're looking to upgrade to 2.3.10 and are also experiencing the same issues as this author

```
Minitest::UnexpectedError:NoMethodError: undefined method `types' for an instance of Hash
    test/test_helpers/platform.rb:11:in `new'
    test/test_helpers/platform.rb:11:in `with_dummy_field'
    test/lib/platform/resolvers/security_advisories_test.rb:39:in `call_resolver'
    test/lib/platform/resolvers/security_advisories_test.rb:61:in `block (2 levels) in <class:SecurityAdvisoriesTest>'
    test/test_helpers/github/basic_test_case.rb:178:in `block in run'
```

**Comment by rmosolgo** [comment]
Hey, sorry for the trouble! Initializing GraphQL classes outside of GraphQL queries isn't really supported, but there are a few ways forward described here: https://github.com/rmosolgo/graphql-ruby/issues/5040#issuecomment-2253136394

How about trying one of those approaches?

**Comment by x-eleos** [comment]
> Hey, sorry for the trouble! Initializing GraphQL classes outside of GraphQL queries isn't really supported, but there are a few ways forward described here: [#5040 (comment)](https://github.com/rmosolgo/graphql-ruby/issues/5040#issuecomment-2253136394)
> 
> How about trying one of those approaches?

Hey we realized it was definitely our issue wrt to how we constructing our tests, we were thrown by them previously working 😅 . Thanks your fast response and we'll definitely look at this.

**Comment by hwrdprkns** [comment]
Thank you @rmosolgo - good to know for the future this isn't supported. I think we can close this issue for now!
