### ISSUE TITLE
Multiplexed mutations fail to share dataloader results and result in a "circular dependency" error

### ISSUE THREAD

**Issue by cheald** [rmosolgo/graphql-ruby#5046]
**Describe the bug**

When using multiplexed mutations, if dataloaders across mutations would load the same value in separate mutations, the second mutation fails to ever have a value yielded from its dataloader due to the cache being clobbered too early.

This appears to be due to a premature invocation of `dataloader.clear_cache`, which is called  from Mutation#call_resolve - this was changed in https://github.com/rmosolgo/graphql-ruby/pull/4903 as a result of https://github.com/rmosolgo/graphql-ruby/issues/4809

However, when you have multiple mutations in a single multiplex, then clobbering the cache when resolving mutation A leaves mutation B without any data to resolve with, and without any queued dataloads to produce said data.

Removing the `dataloader.clear_cache` invocation from `call_resolve` fixes the bug, but obviously regresses the fix for #4809.

**Versions**

`graphql` version: 2.3.10
`ruby` version: 3.0.5

**Reproduction case**

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem "graphql", "2.3.10"
end

class IdentityLoader < GraphQL::Dataloader::Source
  def fetch(ids)
    puts "fetching #{ids}"
    ids
  end

  def self.batch_key_for(**batch_kwargs)
    :identity
  end
end

class MutationOne < GraphQL::Schema::RelayClassicMutation
  argument :id, ID, required: false
  argument :name, ID, required: false
  field :id, ID, null: false

  def ready?(id:, name:)
    puts("[#{name}] Ready")
    context.dataloader.with(IdentityLoader).load(id)
    puts("[#{name}] Contining after dataload")
    true
  end

  def resolve(id:, name:)
    puts("[#{name}] Resolving")
    { id: id }
  end
end

class MutationType < GraphQL::Schema::Object
  field :mutation_one, mutation: MutationOne
end

class TestSchema < GraphQL::Schema
  use GraphQL::Dataloader
  mutation MutationType
end

queries = [
  "mutation a {
     one: mutationOne(input: {id: 1, name: \"a\"}) { id }
   }
  ",
  "mutation b {
     one: mutationOne(input: {id: 1, name: \"b\"}) { id }
   }
  ",
  "mutation c {
     one: mutationOne(input: {id: 2, name: \"c\"}) { id }
   }
  ",
]

p TestSchema.multiplex(queries.map {|q| { query: q } })
```

```
❯ ruby test.rb
[a] Ready
[b] Ready
[c] Ready
fetching ["1", "2"]
[a] Contining after dataload
[a] Resolving
# At this point, the dataloader for "b" should be trying to yield back, but the cache is gone.
/home/chris/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/graphql-2.3.10/lib/graphql/dataloader/source.rb:101:in `sync': IdentityLoader#sync tried 1000 times to load pending keys (["1"]), but they still weren't loaded. There is likely a circular dependency. (RuntimeError)
        from /home/chris/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/graphql-2.3.10/lib/graphql/dataloader/source.rb:57:in `load'
        from test.rb:27:in `ready?'
```

**Comment by rmosolgo** [comment]
Wow, thanks for this really detailed report. Sorry for the trouble - what a doozy! I think we _do_ want to clear loaded records between mutations ... but not pending requests for data. I guess that will need some careful rework...

**Comment by cheald** [comment]
No worries. I've just patched out the `dataloader.clear_cache` call locally, since we don't use dataloaders in mutations in a way that requires a cache clear, so we've got a functional workaround for now.

It's a thorny problem, for sure; imagine, for example:

mutation 1 loads some data with key "key" and gets "foo", then mutates the underlying data such that "foo" -> "bar" and needs to be re-read for mutation resolution, so that the mutation resolves with "bar".

mutation 2 also loads some data with key "key" - what data should it get? This is race-condition-y; under the dataloader pattern, I'd naively expect both mutation 1 and 2 to get "foo" for the "ready" phase, and then mutation 1 to mutate "key" to "bar", and resolve with "bar" in the resolution phase. However, one might just as well expect that mutation 2 would run serially after mutation 1, and should receive "bar" for its ready phase.

The REST analogy would be the firing of two POST requests in quick succession. Should request 1 (~ mutation 1) take an exclusive lock on "key", blocking request 2 (mutation 2) from continuing until it releases the lock (updating its value to bar), and allowing request 2 to continue with "bar" as the value? Or should request 1 and 2 both load "foo" asynchronously? There are application-dependent arguments for both cases.

My initial instinct is that the dataloader cache should be copied and scoped per-query. That is, the dataloader could resolve across a multiplex, loading keys [1, 2], and then provide a per-query cache of those keys. Query A could then clear its cache once it moves from ready -> resolve, and Query B would then still have its own copy of the cache to discard at its leisure. This approach would be analogous to a REST scenario where both queries read their own copy of "foo" from the database asynchronously and then operate on those snapshotted copies of the data. However, it's not immediately clear from source.rb if the current query context is available from within the source or its dataloader (and I don't think it is; while context has dataloader, I don't think that dataloader has context).

A more isolated approach would be a dataloader per query, but that would obviously mean duplicated dataloads. That may not be the worst approach for isolation, but comes at the cost of some extra work.

**Comment by rmosolgo** [comment]
Yes, definitely a tricky spot 😅 Fortunately, I think the spec provides enough guidance here: 

> If the operation is a mutation, the result of the operation is the result of executing the operation’s top level [selection set](https://spec.graphql.org/draft/#selection-set) on the mutation root object type. This selection set should be executed serially.


(https://spec.graphql.org/draft/#sel-FANPHDCAACCyC6jB)


My reading there is that each mutation (and all of its child selections) should be run atomically, in the sequence it appears in the incoming query string. 

I think part of this bug is that mutations are sharing caches from `ready?`, but instead, each one should have an empty cache at that point.

**Comment by cheald** [comment]
I think that suggests a separate dataload per multiplexed operation, then, which is somewhat unfortunate from a performance perspective.

What if the mechanism were something like:

* Aggregate keys and run the dataloader across all multiplexed queries
* Before each mutation's `resolve`, mark all keys as expired, but do not purge the cache
* If another `load` for an expired key is requested (say, during resolution), remove that key from the cache and queue another load
* If no subsequent `load` is requested, then the cached value may be considered reusable.

That seems like it would fulfill the goal is minimizing redundant loads while also updating the cache appropriate for serial multiplexed query resolution.
