### ISSUE TITLE
undefined method 'using_ast_analysis?'

### ISSUE THREAD

**Issue by analucia-t** [rmosolgo/graphql-ruby#5056]
Hello.
I'm getting this error: "NoMethodError: 59 undefined method `using_ast_analysis?'". This started to happen after update the gem.

Graphql version: 2.3.8
Ruby version: 3.3.4

**Comment by rmosolgo** [comment]
Hi! That internal method was recently removed because it has always returned `true` for quite a long time. It can be removed from your code, and whatever `else` branch followed can also be removed. 

Or, if this is a library issue, please share the full stack trace and we can debug further!

**Comment by celsoMartins** [comment]
Hi @rmosolgo. Thanks for your answer.

The stacktrace shows an issue in the persisted-queries module.

Should we open this issue there?

Thanks,

```
     NoMethodError:
       undefined method `using_ast_analysis?' for class OurSchemaClass
     # gems/graphql-persisted_queries-1.8.0/lib/graphql/persisted_queries/schema_patch.rb:101:in `prepare_analyzer'
     # gems/graphql-persisted_queries-1.8.0/lib/graphql/persisted_queries/schema_patch.rb:81:in `verify_http_method='
     # gems/graphql-persisted_queries-1.8.0/lib/graphql/persisted_queries.rb:28:in `use'
     # gems/graphql-2.3.11/lib/graphql/schema.rb:327:in `use'
```

**Comment by celsoMartins** [comment]
Just opened: https://github.com/DmitryTsepelev/graphql-ruby-persisted_queries/issues/80
