### ISSUE TITLE
Test helper run_graphql_field  does not autoload arguments with graphql-batch

### ISSUE THREAD

**Issue by jonathanJ7** [rmosolgo/graphql-ruby#5057]
**Describe the bug**

I'm attempting to write a unit test for my `PostType` class. To achieve this, I want to use the `run_graphql_field` helper to test my `comments` method.

Although the [documentation](https://graphql-ruby.org/testing/helpers.html) states that it should work even with data loaders, when I run the test, the object does not load correctly.

It's important to note that the application itself runs correctly.

Below is the code for my type, along with the different test implementation options I've tried (all of which failed), with an explanation of the error next to each one.

**Versions**

`graphql` version: `2.3.12`
`rails` version: `7.1.3`
`action_policy-graphql` version: `0.5.3`
`graphql-batch` version: `0.6.0`
`graphql-fragment_cache` version: `1.20.1`
`graphql-pagination` version: `2.1.3`

**GraphQL schema**

```ruby
module Types
  module Users
    class PostType < GraphQL::Schema::Object
      graphql_name 'Post'

      field :title, String, null: false
      field :comments, [Types::Users::CommentType], null: false do
        argument :author_id, ID, required: true, loads: Types::AuthorType
      end

      def comments(author:)
        object.comments.where(author_id: author.id)
      end
    end
  end
end
```

**Tests**

# SPEC option 1

```ruby
with_resolution_context(type: "Post", object: example_post, context: { current_user: user }) do |rc|
  result = c.run_graphql_field("comments", arguments: { author_id: author.global_id })
  expect(result.size).to eq(3)
end
     
# ArgumentError:
# missing keyword: :author
# path for post type file:in `resolve'
```

# SPEC option 2

```ruby
with_resolution_context(type: "Post", object: example_post, context: { current_user: user }) do |rc|
  result = c.run_graphql_field("comments", arguments: { author: author })
  expect(result.size).to eq(3)
end

# Error: undefined method `id' for nil:NilClass
# apparently, author arrives in nil, even though I pass an object
```

# SPEC option 3

```ruby
GraphQL::Batch.batch do
  # Code from SPEC option 1
end
     
# ArgumentError:
# missing keyword: :author
# path for post type file:in `resolve'
```

# SPEC option 4

```ruby
GraphQL::Batch.batch do
  # Code from SPEC option 2
end

# Error: undefined method `id' for nil:NilClass
# apparently, author arrives in nil, even though I pass an object
```

**Comment by rmosolgo** [comment]
Hey, sorry for the trouble and thanks for this detailed report. I agree that GraphQL-Batch should be run here, as you expect. I'm not exactly sure how to work it in but I'll take a look soon and follow up here!

**Comment by rmosolgo** [comment]
Hey, I took a look at this and added some tests for `loads:` in 4e07d3f41. I think it's working-_ish_, but you have to either pass: 

- `arguments: { "authorId" => author.global_id }` -- using the GraphQL-style `authorId`, passing the ID 
- `arguments: { author: author.global_id }`  -- using the Ruby-style `author: ...`, also passing the ID

Does one of those work for you?

**Comment by jonathanJ7** [comment]
Thanks for the quick resolution!
The only one that works for me in my current version is `arguments: { author: author.global_id }`
But it is more than enough to be able to do the tests I need.
Thanks!

**Comment by rmosolgo** [comment]
Ok, glad it's working! Let me know if you run into any more trouble  with it.
