### ISSUE TITLE
Introspection query w/ config default_value: nil  breaking some parsers

### ISSUE THREAD

**Issue by armstrjare** [rmosolgo/graphql-ruby#506]
Was having this issue with this from the introspection queries and some versions of the graphql-js parser. Namely, this was breaking the GraphQL plugin for Webstorm. It also breaks older versions of the GraphiQL.

With an argument configured:

```
argument :a, types.String, default_value: nil
```

the introspection query result is:

```
"defaultValue": "null"
```

Expected:
```
"defaultValue": null
```

The workaround is to never define `default_value: nil`, as the omitting the `default_value` option results in the intended `"defaultValue": null` result. However, this took me a while to track down and I'm sure other people may encounter this :-)

**Comment by rmosolgo** [comment]
Hmm, the use of _stringified_ `"null"` was intentional. That was my understanding of the spec: 

> `defaultValue` may return a String encoding (using the GraphQL language) of the default value used by this input value in the condition a value is not provided at runtime. If this input value has no default value, returns null.

https://facebook.github.io/graphql/#sec-The-__InputValue-Type

Have you checked how other implementations handle this case? I tried looking at graphql-js and Sangria but couldn't find a clear test case.

**Comment by armstrjare** [comment]
Ah, you're right - I misunderstood the spec.

It seems that older versions of https://github.com/graphql/graphql-js don't correctly parse `"null"`, but do correctly parse `"NULL"`. 

Looks like the current  version of https://github.com/jimkyndemeyer/js-graphql-intellij-plugin is using an older version of `graphql-js` (via a dependency) which is causing the issue while parsing.

I'll try my luck with getting them to release an updated/fixed version :-)

**Comment by rmosolgo** [comment]
Ok, thanks or taking a look. Please re-open this if you think we should do something differently to support this better!
