### ISSUE TITLE
Including a union type in extra_types doesn't include its possible_types

### ISSUE THREAD

**Issue by Amnesthesia** [rmosolgo/graphql-ruby#5076]
**Describe the bug**

As of 2.3.0, Unions were no longer allowed to be passed to `orphan_types`, but when you pass the union to `extra_types` instead, its `possible_types` dont get included and the union becomes empty in the generated schema, with no members. This happens even if you pass all the possible_types to `extra_types` as well

**Versions**

`graphql` version: graphql-pro 1.28.1, graphql 2.3.14
`rails` (or other framework): rails 7.0.3.4

**Comment by rmosolgo** [comment]
Oh! Well what if you pass the -- 

> This happens even if you pass all the possible_types to extra_types as well

Oh 😩 . Sorry for the trouble and thanks for reporting this -- I think it _should_ work when the possible_types are passed that way. I'll take a look soon and follow up back here!

**Comment by ryanseys** [comment]
I believe we are also encountering this issue:

```
/Users/ryanseys/.gem/ruby/3.3.4/gems/graphql-client-0.19.0/lib/graphql/client/schema/union_type.rb:29:in `define_class': undefined method `map' for nil (NoMethodError)
┃┃
┃┃           possible_type_names = definition.client.possible_types(type).map(&:graphql_name)
```
