### ISSUE TITLE
Negative offset breaks/crashes PostgreSQL

### ISSUE THREAD

**Issue by b8in** [rmosolgo/graphql-ruby#508]
Hello guys!

I've recently noticed that there's an issue:
PG::InvalidRowCountInResultOffsetClause: ERROR: OFFSET must not be negative

It appears here: http://joxi.ru/bmoW8eMhxygJEm when the value of param 'last' is more then the number of records in the appropriate table. I used ActiveRecord ORM.
I tried to write a test for that case, but passes flawlessly. I think it's because it's SQLite, not PostgreSQL.

I fixed this issue locally like this: http://joxi.ru/KAg8OD1F4KPl5r

P.S. If needed, I can leave a PR.

Thanks, would be great to hear your thoughts on this!
Alex

**Comment by rmosolgo** [comment]
Thanks for the details on this error! A PR would be great.  

Funny about the difference between SQLite and PostgreSQL, I didn't know that.

**Comment by b8in** [comment]
PR #510

**Comment by b8in** [comment]
#510

**Comment by rmosolgo** [comment]
Fixed by 508 👍

**Comment by karki011** [comment]
I keep running to this error, is there a solution for this.

I tried to look at past solution but the link is not found.

ActiveRecord::StatementInvalid · PG::InvalidRowCountInResultOffsetClause: ERROR: OFFSET must not be negative : SELECT DISTINCT "positions".* FROM "positions" WHERE "positions"."deleted_at" IS NULL ORDER BY "positions"."id" DESC LIMIT 10 OFFSET -10

Any help would be helpful.

thanks
