### ISSUE TITLE
Guide: Object Identification and SQIDs 🦑

### ISSUE THREAD

**Issue by lawrencegripper** [rmosolgo/graphql-ruby#5089]
I've done a write-up about my work recently to move from `to_gid_param` to [SQIDs](https://sqids.org/) for nicer Global IDs that don't break on class renaming. 

Originally we started by following this guide: https://graphql-ruby.org/schema/object_identification

Post: https://blog.gripdev.xyz/2024/06/09/sqids-graphql-and-ruby/

Would it be useful to add some of this to this guide as an option or link to the post for folks?

**Comment by rmosolgo** [comment]
Hey, thanks for sharing your work. Those look nice, I think it'd be great to add a mention of it to that guide somewhere :+1:

**Comment by lawrencegripper** [comment]
No worries, thanks for all the work on the library, we recently retrofitted it to a legacy rails codebase to expose out a modern API and it's been great :heart: 

Had a go add adding a bit about SQIDs here

- https://github.com/rmosolgo/graphql-ruby/pull/5091
