### ISSUE TITLE
[Enterprise] GraphqlController errors

### ISSUE THREAD

**Issue by jeperkins4** [rmosolgo/graphql-ruby#5104]
After upgrading to Enterprise GraphQL, we now receive the following error in multiple places within our Rails monolithic application:

```
NoMethodError - undefined method `size' for #<ActionController::Parameters {} permitted: true>
      @variables_fingerprint ||= "#{provided_variables.size}/#{Fingerprint.generate(provided_variables.to_json)}"
                                                      ^^^^^:
  app/controllers/graphql_controller.rb:37:in `execute'
```

**Comment by rmosolgo** [comment]
Hey, sorry for the trouble and thanks for reporting this! `ActionController::Parameters` _almost_ works for GraphQL variables, but there are a few cases where it doesn't have the methods that GraphQL-Ruby needs. (Another example is #4941.) To work around this, call `.to_unsafe_h` on the variables before passing them to `.execute`, for example: 

```ruby 
MySchema.execute(..., variables: params[:variables]&.to_unsafe_h)
```

Usually, that's not a good way of handling Rails params. But with GraphQL, you can be sure that GraphQL-Ruby will be doing validation during execution. `.to_unsafe_h` is what `rails g graphql:install` does: 

https://github.com/rmosolgo/graphql-ruby/blob/f82ed872464bf262dfd184a8e97517b2cb6f0ac6/lib/generators/graphql/templates/graphql_controller.erb#L38-L39

How about giving that a try?

**Comment by rmosolgo** [comment]
Glad to hear it -- let me know if I can help with anything else!
