### ISSUE TITLE
Pagination connection for aggregations on MongoDB

### ISSUE THREAD

**Issue by ppascualv** [rmosolgo/graphql-ruby#5120]
**Is your feature request related to a problem? Please describe.**

There is an existing connection for MongoDB queries, but it not work with aggregations

**Describe the solution you'd like**

It would be nice something like:
GraphQL::Pagination::MongoidAggregationRelationConnection.new(Contact.collection.aggregate(pipeline))

**Describe alternatives you've considered**

Create my own connection

**Additional context**

No needed

**Comment by rmosolgo** [comment]
Hi! Thanks for the suggestion. I'd be happy to maintain this and distribute it with GraphQL-Ruby, but I don't have plans to develop it myself. If you'd like to try adding to the project, please open a PR with some tests and an initial implementation and I'd be glad to help out if I can :+1:
