### ISSUE TITLE
Does global_id_field supports block?

### ISSUE THREAD

**Issue by andricicezar** [rmosolgo/graphql-ruby#514]
I try to do something like this, but doesn't seem to work.

```
global_id_field :id do
  resolve -> (entity, args, context) {
    entity["uid"]
  }
end
```

**Comment by rmosolgo** [comment]
`global_id_field`s are resolved by calling the schema's `id_from_object` block. So, you can specify the behavior there, eg: 

```ruby 
MySchema = GraphQL::Schema.define do 
  # ... 
  id_from_object -> (obj, type_defn, ctx) {
    case obj 
    when Hash 
      entity["uid"]
    else 
      raise("Can't derive UUID from #{obj.inspect}")
    end 
  }
end 
```

There's a little more documentation about these hooks here: 

https://rmosolgo.github.io/graphql-ruby/relay/object_identification#defining-uuids

How does that sound? Please reopen if that doesn't work for you!
