### ISSUE TITLE
Dataloader `prime`

### ISSUE THREAD

**Issue by ravangen** [rmosolgo/graphql-ruby#5160]
**Is your feature request related to a problem? Please describe.**

Provide an option to prime the dataloader's result cache with the provided key and value to avoid data being fetched needlessly.

Examples:
- [`graphql/dataloader`](https://github.com/graphql/dataloader?tab=readme-ov-file#primekey-value) 
- [`Shopify/graphql-batch`](https://github.com/Shopify/graphql-batch?tab=readme-ov-file#priming-the-cache)

**Describe the solution you'd like**

Mechanism to add a result into a `GraphQL::Dataloader::Source` instance.

EDIT: Looking more closely, is that the purpose of `merge`? Perhaps an alias could be of benefit?

```ruby
def prime(key, value)
  merge(key => value)
end
```

**Additional context**

Exploring feature parity between graphql-batch and dataloader, testing the wheels 😄

**Comment by rmosolgo** [comment]
Yes, that's exactly what `merge` is for :+1: I'm open to supporting `def prime` if you'd like to implement it. It could probably be implemented without creating the Hash, too: 

```ruby
  def prime(new_k, new_v)
    key = result_key_for(new_k)
    @results[key] = new_v
  end 
```

**Comment by ravangen** [comment]
Thanks, makes sense. Should have looked more closely.

I'm going to close the issue for now, since I have something working. But I'll keep this in mind for the future.

**Comment by rmosolgo** [comment]
👋  I was thinking about this and wondering, what did you find regarding parity between graphql-batch and dataloader?

**Comment by ravangen** [comment]
Regarding parity, I could get similar outcomes implemented in both approaches test case wise, but no traffic was tested.

The business case was around parallelizing sequential data access, and the tech case was consolidation. The work was deprioritized due to resourcing constraints. Was aiming to use `AsyncDataloader`, but the next big step was changing `config.active_support.isolation_level = :fiber` from `:thread` in the monolith. And then the retooling/reeducation.

**Comment by rmosolgo** [comment]
Thanks for sharing, @ravangen. It sounds like https://github.com/Shopify/graphql-batch/pull/173 was an exploration in a similar direction but without Fiber-specific difficulties.
