### ISSUE TITLE
Using argument :after in a field causes DuplicateNamesError when fetching the whole schema in Graphiql

### ISSUE THREAD

**Issue by tomwang57** [rmosolgo/graphql-ruby#5162]
**Describe the bug**

Using `argument :after` in a field causes `DuplicateNamesError` when fetching the whole schema in Graphiql:

```
GraphQL::Schema::DuplicateNamesError - Found two visible definitions for `Me.events_connection.after`:
 #<GraphQL::Schema::Argument Me.events_connection.after: String @description="Returns the elements in the list that come after the specified cursor.">, 
#<GraphQL::Schema::Argument Me.events_connection.after: String! @description="Fetch items after this cursor">
```

**Versions**

`graphql`: 1.13.23
`rails`: 6.1
`graphql-batch`: 0.6.0

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok). Any custom extensions, etc?

```ruby
field :events_connection, Types::EventsConnectionType do
    argument :after, String, description: "Fetch items after this cursor"
    # other arguments
 end
```

**GraphQL query**

Fetch the whole shema in Graphiql

**Comment by rmosolgo** [comment]
Hi! Thanks for the bug report. This could probably be fixed by adding a check here to see if a field with the given name was already defined: https://github.com/rmosolgo/graphql-ruby/blob/aff9fdfdc8b6cd79b940d7e675674d37d53d5a84/lib/graphql/schema/field/connection_extension.rb#L7-L12

Another approach would be to delete the one you don't want: 

```ruby 
# Define the field 
field :events_connection ... do 
end 

# Remove the argument that GraphQL-Ruby added automatically:
events_conn_field = get_field("eventsConnection")
duplicate_defn = events_conn_field.all_argument_definitions.find { |arg| arg.keyword == :after && arg.desciption != "Fetch items after this cursor" } 
events_conn_field.remove_argument(duplicate_defn) 
```

Another approach would be to pass `field ... connection: false` to opt out of GraphQL-Ruby's automatic connection handling. But if you did that, you'd have to _also_ define `:before`, `:first`, and `:last`, and manually wrap the list in a connection wrapper object. So it's probably a bit heavy-handed. 

Does one of those approaches work for you?

**Comment by rmosolgo** [comment]
If you try one of those approaches and it's still giving you trouble, please let me know! Share the new code that you tried and what happened when you tried it. Then we can dig in and see what else might work.

**Comment by tomwang57** [comment]
> If you try one of those approaches and it's still giving you trouble, please let me know! Share the new code that you tried and what happened when you tried it. Then we can dig in and see what else might work.

Hi, I used the last approach as `field ... connection: false` to opt out of GraphQL-Ruby's automatic connection handling and the schema can be successfully parsed.

But i don't really understand what you mean by:

>But if you did that, you'd have to also define :before, :first, and :last, and manually wrap the list in a connection wrapper object. So it's probably a bit heavy-handed

And don't take further action.

**Comment by rmosolgo** [comment]
Hi! I'm glad you got it working. 

I meant that when you add `connection: false`, then GraphQL-Ruby's connection system is turned off. Usually, the built-in system does two things: 


1. Adds the default arguments `first: Int, last: Int, before: String, after: String`. The code for that is here: https://github.com/rmosolgo/graphql-ruby/blob/db1dba5e9bd8812080d56ca14acd5b77d95972b1/lib/graphql/schema/field/connection_extension.rb#L8-L11
2. When given an Array, Sequel::Dataset, or ActiveRecord::Relation, it wraps the result in Connection object. The connection object (also called a "wrapper") supports connection-related metadata like `pageInfo` and supports connection-style pagination (`edges`, `nodes`). The code for applying those wrappers is here: https://github.com/rmosolgo/graphql-ruby/blob/db1dba5e9bd8812080d56ca14acd5b77d95972b1/lib/graphql/schema/field/connection_extension.rb#L58-L59


So, if you add `connection: false`, you might need to re-implement those two features, depending on what you're doing. But if things are working well for you now, great!
