### ISSUE TITLE
Getting FiberError after deploying with 2.4.4

### ISSUE THREAD

**Issue by aub** [rmosolgo/graphql-ruby#5168]
**Describe the bug**

We recently deployed with 2.4.4 and started getting errors like this:

<img width="869" alt="Screenshot 2024-11-21 at 12 28 41 PM" src="https://github.com/user-attachments/assets/41920942-8a6c-4487-88b2-8616ecc42acf">

Rolling back to 2.4.3 appears to have resolved the issue.

**Versions**

`graphql` version: 2.4.4
`rails` (or other framework): Rails 7.2.2
other applicable versions (`graphql-batch`, etc)

**Comment by aub** [comment]
Sorry, this was unrelated to graphql-ruby.

**Comment by rmosolgo** [comment]
Hi! I'm glad you got to the bottom of it. If you're able to share anything about how you addressed this problem, I'd love to hear it. It might help someone else who encounters this error, too!

**Comment by rmosolgo** [comment]
Oh, interesting -- so it was a logic error underneath, but it manifested in this Fiber-oriented way. Thanks for sharing!
