### ISSUE TITLE
Directives with `.visible?` -> `false` are not fully removed from the schema

### ISSUE THREAD

**Issue by erikkessler1** [rmosolgo/graphql-ruby#5172]
**Describe the bug**

I'm trying to make it so that certain directives of a schema are only present in certain contexts (e.g., federation directives only included in federated contexts). From playing around with the `.visible?` hook, it seems like a directive that isn't visible has its definition removed, but the usage of the directive still exists. For example, the following script:

```ruby
require 'bundler'
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'graphql', '2.4.4'
end

class MyDirective < GraphQL::Schema::Directive
  locations OBJECT

  def self.visible?(context)
    context.fetch(:show_directives)
  end
end

class Query < GraphQL::Schema::Object
  directive MyDirective
  field :my_string, String, null: false
end

class MySchema < GraphQL::Schema
  use GraphQL::Schema::Visibility
  query Query
end

puts "# show_directives: true"
puts MySchema.to_definition(context: { show_directives: true })
puts "\n# show_directives: false"
puts MySchema.to_definition(context: { show_directives: false })
```

Produces the following output:

```graphql
# show_directives: true
directive @myDirective on OBJECT

type Query @myDirective {
  myString: String!
}

# show_directives: false
type Query @myDirective {
  myString: String!
}
```

The output I would expect is:

```graphql
# show_directives: false
type Query {
  myString: String!
}
```

Is that the expected behavior of the `.visible?` hook on directives?

**Comment by rmosolgo** [comment]
Hey, thanks for the detailed report. I would _also_ expect that `type Query` would _not_ have `@myDirective` in this case. I'm guessing it just wasn't implemented yet.

I think this is the call that needs to be corrected: 

https://github.com/rmosolgo/graphql-ruby/blob/692b58a5ab067342712a83cf5ce768de532e9590/lib/graphql/language/document_from_schema_definition.rb#L352

It should skip over directives that fail a `@types.directive_exists?(directive_name)` check, similar to the one this code uses: https://github.com/rmosolgo/graphql-ruby/blob/692b58a5ab067342712a83cf5ce768de532e9590/lib/graphql/static_validation/rules/directives_are_defined.rb#L10

That would remove any directives that had been hidden. 

The "top-level" list of directives already uses `@types.directives` which excludes any hidden ones: 

https://github.com/rmosolgo/graphql-ruby/blob/692b58a5ab067342712a83cf5ce768de532e9590/lib/graphql/language/document_from_schema_definition.rb#L266
