### ISSUE TITLE
Possible bug with inline fragments and directives

### ISSUE THREAD

**Issue by keithpitt** [rmosolgo/graphql-ruby#518]
According to the spec her: https://facebook.github.io/graphql/#sec-Inline-Fragments this _should_ be possible:

```graphql
query inlineFragmentNoType($expandedInfo: Boolean) {
  user(handle: "zuck") {
    id
    name
    ... @include(if: $expandedInfo) {
      firstName
      lastName
      birthday
    }
  }
}
```

But when I try the above query in Relay:

```js
  fragments: {
    agent: () => Relay.QL`
      fragment on Agent {
        ${AgentStopMutation.getFragment('agent')}
        name
        organization {
          name
          slug
        }
        ... @include(if: $isMounted) {
          connectedAt
          connectionState
          disconnectedAt
          hostname
          id
          ipAddress
        }
      }
    `
  }
```

I get the following error:

```
'@include' can't be applied to fragment definitions (allowed: fields, fragment spreads, inline fragments)
   ragment F0 on Agent @include(if:true) {
```

**Comment by keithpitt** [comment]
After looking through the source code a lil'bit, it looks like there's a spec to ensure that this sort of behaviour _should't_ be possible! https://github.com/rmosolgo/graphql-ruby/blob/b5af7ad66dfddfcb219497f420f9baf8d08e1a65/spec/graphql/static_validation/rules/directives_are_in_valid_locations_spec.rb

But I may be totally reading the whole thing wrong!

**Comment by rmosolgo** [comment]
> applied to fragment definitions

It's weird that the error message says `applied to fragment definitions`, because the two samples you shared have directives on inline fragments (which is allowed). 

The error message includes a little bit of the invalid string, right? 

> `ragment F0 on Agent @include(if:true)`

Can you tell where _that_ is coming from? For example, do you have the whole query string which Relay sends to the server?

**Comment by keithpitt** [comment]
Sure thing! Here it is:

```graphql
query Show_AgentRelayQL($id_0:ID!) {
  node(id:$id_0) {
    ...F3
  }
}
fragment F0 on JobTypeCommand {
  label,
  command,
  url,
  build {
    number,
    pipeline {
      name,
      id
    },
    id
  },
  id
}
fragment F1 on Node {
  id,
  __typename
}
fragment F2 on Agent @include(if:true) {
  connectedAt,
  connectionState,
  disconnectedAt,
  hostname,
  id,
  ipAddress,
  job {
    __typename,
    ...F0,
    ...F1
  },
  lostAt,
  metaData,
  operatingSystem,
  permissions {
    agentStop {
      allowed,
      code,
      message
    }
  },
  pid,
  pingedAt,
  stoppedAt,
  stoppedBy {
    name,
    id
  },
  userAgent,
  uuid,
  version
}
fragment F3 on Agent {
  id,
  ...F2
}
```

And the Relay.Container thingy:

```js
export default Relay.createContainer(AgentShow, {
  initialVariables: {
    isMounted: false
  },
  fragments: {
    agent: () => Relay.QL`
      fragment on Agent {
        ${AgentStopMutation.getFragment('agent')}
        name
        organization {
          name
          slug
        }
        ... @include(if: $isMounted) {
          connectedAt
          connectionState
          disconnectedAt
          hostname
          id
          ipAddress
          job {
            ${JobLink.getFragment('job')}
          }
          lostAt
          metaData
          operatingSystem
          permissions {
            agentStop {
              allowed
              code
              message
            }
          }
          pid
          pingedAt
          stoppedAt
          stoppedBy {
            name
          }
          userAgent
          uuid
          version
        }
      }
    `
  }
});

```

**Comment by keithpitt** [comment]
And the full server response:

```
{"errors":[{"message":"'@include' can't be applied to fragment definitions (allowed: fields, fragment spreads, inline fragments)","locations":[{"line":24,"column":22}],"fields":["fragment F2"]}]}
```

**Comment by rmosolgo** [comment]
Awesome, thanks!

Here's the invalid part of the query: 

```graphql 
fragment F2 on Agent @include(if:true) {
  ... 
}
```

Here's a relevant snippet from [the spec](https://facebook.github.io/graphql/#sec--include): 

> The `@include` directive may be provided for fields, fragment spreads, and inline fragments...

Notice that `@include` may _not_ be provided for fragment _definitions_. 

You could change the query above by moving `@include` to the _spread_ instead of the definition, eg: 


```diff 
- fragment F2 on Agent @include(if:true) {
+ fragment F2 on Agent {

  # ...

  fragment F3 on Agent {
    id,
-   ...F2
+   ...F2 @include(if: true)
  }
```

Does that work for you?

**Comment by keithpitt** [comment]
Ah, I see! If I copy/paste the the Relay query into GraphQL explorer, and make your change, it works just fine!

So it sounds like the bug is actually in how Relay is taking the query and changing it?

**Comment by rmosolgo** [comment]
Yeah ... I think you're right! Because _you_ put the directive in the right place, right? It's this one: 

```graphql 
... @include(if: $isMounted) {
  connectedAt
  connectionState
  disconnectedAt
  hostname
  id
```

But then Relay moves it to 

```graphql 
fragment F2 on Agent @include(if:true) {
  connectedAt,
  connectionState,
  disconnectedAt,
  hostname,
  id,
```

which is not valid :( 

Want to open an issue there and see if they agree with our diagnosis?

**Comment by rmosolgo** [comment]
As far as I know, the Ruby side of things is in order. Please feel free to reopen this if you find any more info!
