### ISSUE TITLE
Guide: Connection Concepts | No __id generated for connection

### ISSUE THREAD

**Issue by lpender** [rmosolgo/graphql-ruby#5192]
Hi,

I have this in my query type:

```
    field :entities, Types::EntityType.connection_type, null: true
```

And I see this when I autocomplete in graphiql

![image](https://github.com/user-attachments/assets/b376b67e-fc75-4757-8ed1-3a578a0cc91b)

According to the [relay documentation](
![image](https://github.com/user-attachments/assets/3040eacb-f895-4b18-92c7-91d94f42e688)
):

```
// Get the connection record id
const connectionID = fragmentData?.comments?.__id;
```

But there _is_ no `__id` field being generated by GraphQL :/

**Comment by lpender** [comment]
Just saw this:

note
The __id field is NOT something that your GraphQL API needs to expose. Instead, it's an identifier that Relay automatically adds to identify the connection record.

**Comment by rmosolgo** [comment]
Glad you got to the bottom of it! Thanks for sharing the solution you found.
