### ISSUE TITLE
forceFetch returning error & failing to send original query field to server

### ISSUE THREAD

**Issue by dorthwein** [rmosolgo/graphql-ruby#523]
It seems that when using forceFetch within a component, the forced fetch does not send the field type resulting in a <code>Field 'node' doesn't exist on type 'Query' node(id:$id_0) </code> error being returned. 

This github issue articulates the same error however it is for a node implementation and seems his issue was simply an incorrect naming.  https://github.com/facebook/relay/issues/473

The initial call does work and returns the correct information.   

Any help is hugely appreciated! @rmosolgo - great job on this gem as well ;)

**graphql-ruby response**
```json
{"errors":[{"message":"Field 'node' doesn't exist on type 'Query'","locations":[{"line":2,"column":3}],"fields":["query Component_UserRelayQL","node"]},{"message":"Fragment F0 was defined, but not used","locations":[{"line":8,"column":1}],"fields":[]},{"message":"Variable $id_0 is declared by Component_UserRelayQL but not used","locations":[{"line":1,"column":1}],"fields":["query Component_UserRelayQL"]}]}

```

**Query Type**
```ruby
QueryType = GraphQL::ObjectType.define do
  name "Query"
  description "The query root for this schema"
  field :user do
    type UserType
    argument :id, !types.ID
    resolve -> (obj, args, ctx) {
      User.find(args[:id])
    }
  end
end

```
**GraphQL Type**
```ruby
UserType = GraphQL::ObjectType.define do
  name "User"
  field :id, types.String
  field :email, types.String


  connection :notifications, NotificationType.connection_type do
    argument :viewed, types.Boolean
    resolve ->(user, args, ctx) {
      result = user.notifications.where(viewed: args[:viewed]).to_a
      return result
    }
  end
end
```
**Component**
```javascript
class NotificationManagerComponent extends Component {
  fetchNotifications = () => {
    const self = this;
    this._notificationPoll = setTimeout(() => {
      self.props.relay.forceFetch({ viewed: false });
      self.displayNotifications();
      this.fetchNotifications();
    }, 5000);
    ...other stuff
  }
```

**Container**
```javascript
Relay.createContainer(NotificationManagerComponent, {
  initialVariables: { viewed: false },
  fragments: {
    user: () => Relay.QL`
      fragment on User {
        id
        notifications( last: 20, viewed: $viewed ) {
          edges {
            node {
              id
              title
              message
              image_url
              viewed
              _type
              user {
                id
              }
            }
          }
        }
      }
    `
  }
});

```

**Comment by rmosolgo** [comment]
Hi! Thanks for sharing the relevant code. For Relay to fetch objects by their ID, you need to add two things: 

1. You need to define an [`object_from_id` function](https://rmosolgo.github.io/graphql-ruby/relay/object_identification#defining-uuids) which returns an object for each unique ID. 
1. You need to [add a `node` field to your `Query` type](https://rmosolgo.github.io/graphql-ruby/relay/object_identification#node-field-find-by-uuid) which will use that function to respond to GraphQL queries.

That way, when Relay sends a query to find a node by ID, your GraphQL schema will be able to respond.

Please reopen if that doesn't solve your issue!

**Comment by dorthwein** [comment]
@rmosolgo - Awesome response - I've been able to get things working correctly.  

One quick question in the example your shared its not clear where the following code belongs so you can set the meta information.  Where should it be placed?

```ruby
GraphQL::ObjectType.accepts_definitions resolves_to_class_names: GraphQL::Define.assign_metadata_key(:resolves_to_class_names)
```

**Comment by rmosolgo** [comment]
Good question! It has to be called before any of your type definitions are executed. Putting it right before the schema definition should do the trick. 

I've [updated that page of the docs](https://rmosolgo.github.io/graphql-ruby/schema/types_and_fields#extending-type-and-field-definitions) with a bit of surrounding context to hopefully clarify that a bit!
