### ISSUE TITLE
Topical documentation

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#524]
I think a few "recipes" could help folks work through common problems with GraphQL + Ruby. A few that come to mind are: 

- File uploads with Rails + a GraphQL client (Apollo?)
- CSRF tokens with GraphQL clients (maybe this doesn't apply with Relay?)
- Activating & deactivating parts of the schema with Flipper 
- ... others?

These could be added to the gem's documentation or written elsewhere and linked from "Related Projects."

**Comment by hd719** [comment]
Hello I am new to open source and I would like to contribute to this project. 

-Thank you!

**Comment by github0013** [comment]
I could manage file-uploading using graphql-ruby + apollo-client + apollo-upload-client
https://gist.github.com/github0013/d79fa651be3d7450adcd447676d01921

gist is a concept of how you do it.
