### ISSUE TITLE
Specify property and/or encoding for arguments.

### ISSUE THREAD

**Issue by xuorig** [rmosolgo/graphql-ruby#540]
Thought about this while working on https://github.com/rmosolgo/graphql-ruby/issues/538

It would be pretty useful if you could specify a different name for internal use of arguments vs client facing. For example:

```ruby
field :addThing, !types.String do
  argument :myArgument, !types.String, as: :my_argument

  resolve ->(o, args, ctx) {
    AddThingService.new(args[:my_argument]).result
  }
end
```

It would be pretty useful to shape the arguments the way you want to to adapt to your business logic, but also would be useful for this issue: https://github.com/rmosolgo/graphql-ruby/issues/538

Other more complex cases could allow you to change argument values before they get to your resolver. Relay Global ids are a good example.

```ruby
field :updateThing, !types.String do
  argument :id, !types.ID, decoder: RelayGlobalIDDecoder

  resolve ->(o, args, ctx) {
    # id is already an active record obj id because RelayGlobalIDDecoder decoded the global id
    Thing.find(args[:id])
  }
end
```

WDYT ?

**Comment by rmosolgo** [comment]
:+1:

**Comment by lucaspolonio** [comment]
@rmosolgo any thoughts on @xuorig's second idea to add a `decoder` option to arguments? I'd be willing to work on a PR if you like the idea.

My current use case is argument reusability. I have a few custom arguments using `GraphQL::Field.accepts_definitions`and `Define::AssignArgument`. All they do now is provide default types and descriptions. It would be very useful if they could also provide a block as a `decoder` option (maybe `resolve` or `prepare`, or any other name) to validate/transform the argument value during execution before the resolver is called. One example could look something like this:

```ruby
field :my_field do
  date_argument :date
  resolve -> (obj, args, ctx) {
    args[:date]
  }
end
```

```ruby
module AssignDateArgument
  def self.call(target, name, type, description, **rest, &block)
    description = "...."
    prepare = ->(arg) { ValidateDateArgument.call(arg) }
    ...
    GraphQL::Define::AssignArgument.call(target, name, type, description, prepare: prepare, **rest, &block)
  end
end

GraphQL::Field.accepts_definitions(date_argument: AssignDateArgument)
```

```ruby
module ValidateDateArgument
  def self.call(arg)
    raise GraphQL::ExecutionError.new("Invalid date format") unless ...
  end
end
```

**Comment by rmosolgo** [comment]
I love the idea, I think `prepare:` is a great name for it, please give it a try!

**Comment by rmosolgo** [comment]
I think these are both done now :D
