### ISSUE TITLE
Schema filtering currently cannot fully whitelist introspection query

### ISSUE THREAD

**Issue by vergenzt** [rmosolgo/graphql-ruby#544]
## Goal

I'm adding a metadata field `:expose_to` to schema definitions to allow whitelisting schema members for consumption by particular roles.

Given a current user and their role, I'd like to

 1. only show domain-specific types/fields/arguments if the current user's role is contained in `schema_member.metadata[:expose_to]`, and
 2. allow full introspection by the user on the subset of the schema that is exposed to them.

## My approach

Currently I'm calling
```rb
Schema.execute(query, only: RoleFilter.new, variables: variables, context: context)
```

with the following defined:
```rb
class RoleFilter
  def call(schema_member, context)
    current_user_role = context[:current_user].try(:role)
    return true if current_user_role == :staff

    # TODO: whitelist introspection here

    expose_to = schema_member.metadata[:expose_to]
    return true if expose_to && expose_to.include?(current_user_role)
  end
end
```

## The problem:

**I can't figure out how to actually fully whitelist introspection queries.**

Here's the general structure I've found so far (inserted at "whitelist introspection here").

_Note_: This is already at the complexity that I definitely think it'd be worth it to implement this in the core codebase instead of in the client.
```rb
    case schema_member
    when GraphQL::BaseType
      if schema_member.unwrap.introspection?
        # Case 1a
        # Type is introspection-related. We can whitelist it.
        return true
      else
        # Case 1b
        # Type is not introspection-related. Check :expose_to.
      end

    when GraphQL::Field, GraphQL::Argument

      if schema_member.type.unwrap.introspection?
        # Case 2a
        # The return/input type of the field/argument is introspection-related. Whitelist.
        # e.g. `__schema` (GraphQL::Introspection::SchemaType)
        return true

      elsif false
        # ^^^ TODO: How to we detect this?
        # Case 2b
        # The parent type/field of the field/argument is introspection-related. Whitelist.
        # 
        # e.g. `deprecationReason` (types.String, but a parent is GraphQL::Introspection::FieldType)
        # or e.g. `fields(includeDeprecated: true) { ... }`

      else
        # Case 2c
        # The field/argument has nothing to do with introspection. Check :expose_to.
      end

    when GraphQL::EnumType::EnumValue
      # Case 3
      # ^^^ TODO: I have no idea how to check if the parent enum type is introspection-related.
    end
```

## Proposal

Could we either
 1. add `introspection?` methods to `GraphQL::Field`, `GraphQL::Argument` and `GraphQL::EnumType::EnumValue` to compute the above, or
 2. add `accepts_definition :introspection` to the above (or maybe to `InstanceDefineable`?) and make sure to include it in all introspection-related members?

Not really sure how to move forward with my second goal of including introspection in the schema whitelist without this.

**Comment by rmosolgo** [comment]
One thing that you can assume inside a filter is that, if you're checking a child object like a field, argument or enum value, then the parent object has already passed the filter. 

For enum values in particular, are there cases where you want to expose the enum type, but hide some of the values? 

Taking enum values as an example, would this work? 

```ruby 
case GraphQL::EnumType::EnumValue 
  expose_to = schema_member.metadata[:expose_to]
  if expose_to && expose_to.any?
    expose_to.include?(current_role)
  else 
    # this value appears to everyone 
    # (maybe it's introspection, maybe not)
    true
  end 
end 
```

**Comment by rmosolgo** [comment]
(I'm open to adding that other data, but I think it might be possible to do this with the existing API. The auth framework in graphql-pro does exactly this!)

**Comment by vergenzt** [comment]
> For enum values in particular, are there cases where you want to expose the enum type, but hide some of the values?

I'm not sure. I marked that case as a TODO because I wasn't sure how to handle it and the docs said `schema_member` could be an `EnumValue`. This isn't my main issue though--relying on the exposure of the parent type in this case is probably enough for now.

> One thing that you can assume inside a filter is that, if you're checking a child object like a field, argument or enum value, then the parent object has already passed the filter.

That makes sense--but I still don't see the solution from there. For security's sake I'd like the set of fields that are exposed to be a _whitelist_ rather than a blacklist--if I cannot verify that a given field _should_ be exposed (i.e. either it's marked as such or it's explicitly an introspection field) I'd rather not expose it.

Typing out the above made me realize though: is there some way I could implement a schema visitor to manually add `metadata[:expose_to]` to all children of an introspection query? If so that could work too.

> I think it might be possible to do this with the existing API. The auth framework in graphql-pro does exactly this!

Oh I hadn't realized that! That's super useful. Does the compile-time authorization for schema members also allow introspection (and does the introspection only return the authorized subset of the schema)?

I.e. It sounds like you've already solved goal 1 for me. :) Did you also solve goal 2?

**Comment by rmosolgo** [comment]
> manually add metadata[:expose_to]

This could be done with [instrumentation](http://rmosolgo.github.io/graphql-ruby/schema/instrumentation), eg 

```ruby 
def instrument(type, field) 
  if type.introspection?
    # Introspection is visible to everyone:
    field.redefine(expose_to: ALL_ROLES)
  else 
    previous_expose_to = field.metadata[:expose_to] 
    if previous_expose_to.nil? 
      # If a value wasn't assigned, default to an empty list:
      field.redefine(expose_to: [])
    else 
      # Leave it as-is 
      field 
    end 
  end 
end 
```

But someone recently asked for a similar feature, a "default value" for `accepts_definitions`, so I should think about that a bit!

> return the authorized subset of the schema

Yep! 

For example, `__schema { types { ... } }` only returns authorized types (and their authorized fields, arguments, enum values, etc) and `__type(name: $typeName) { ... }` returns `null` if the specified type isn't authorized.

**Comment by vergenzt** [comment]
> This could be done with instrumentation

Interesting! Since instrumentation only visits fields though, I assume that `GraphQL::Argument`s would have to be blanket whitelisted? (That's probably fine for now; I'm just making sure I understand where the limitations are.)

**Comment by rmosolgo** [comment]
:man_facepalming: Oh right, I was thinking only of fields, instrumentation wouldn't help you much with types, enum values, or arguments

**Comment by vergenzt** [comment]
How much work do you think it'd be to allow instrumentation of types, arguments, and/or enum values? I may be able to work on a PR.

I've actually already run into another potential use case for at least type-level instrumentation when I tried to look into automatically populating type and field descriptions based on Postgres table and column comments. (Field instrumentation works for the column comments but not the tables yet.)

**Comment by rmosolgo** [comment]
It's definitely possible. /cc @xuorig who was starting down the path of implementing camelization. A similar approach would be applied there: visit each item, make a renamed copy, and use the copy instead of the original. 

Weird stuff could happen if you copied types, for example:

```ruby 
Schema.types["Post"] == PostType
# => false 
```

That would be the case because `Schema.types["Post"]` was actually a modified copy of `PostType`. 

The alternative is to support modification in place. That could have its own bugs since there's no way to know who's using that shared data. :thinking: 

I'm definitely open to the idea, but it seems like either approach would need some feeling-out to see how the parts would work together. 

Just curious, why not populate the descriptions during the initial definition, eg

```ruby 
PostType = GraphQL::ObjectType.define do 
  description(DBDescription.table("posts"))
end 
```

?

**Comment by vergenzt** [comment]
Interesting points... some thoughts:

 - It seems like part of why this runs into trouble is because the type and field definitions have no knowledge of the context in which they're defined.

 - What if instead of declaring `PostType = GraphQL::ObjectType.define ...`, we were somehow declare it in a way where you're defining an ObjectType _within_ a particular Schema? Then that Schema could have configuration that modifies the return type of `.define` without being an "in-place" modification--rather, there just wouldn't be any more references to the old non-modified copy.

    E.g. perhaps this could look something like `PostType = MySchema::ObjectType.define`? I'm not sure whether Ruby has constructs that allow that to work, but it makes sense in my head. This could also obviate the need for the `orphan_types` construct, because `Schema` could register types as they get defined. (This part would be modification in place on part of the Schema--but it seems straightforward enough to me.)

    Then before returning, `define` could execute any of `MySchema`'s declared instrumentations.

Thoughts?

> Just curious, why not populate the descriptions during the initial definition, eg
> 
> ```rb
> PostType = GraphQL::ObjectType.define do 
>   description(DBDescription.table("posts"))
> end 
> 
> ?

Because there are 18 models with about 170 fields between them and that's a lot of boilerplate. :) Also it feels like the kind of effort that'd be useful in other cases so it's also partly just for fun. :P

**Comment by rmosolgo** [comment]
>  ObjectType _within_ a particular Schema

I've definitely considered the same thing! After the Redis Module API was published, I was thinking what we could learn for GraphQL. I think GraphQL has a lot in common with extensible runtimes like Ruby (er, Rub_ies_) and Redis. 

I couldn't sort out any clear wins from reordering the schema API that way, and it came with some challenges of its own: 

- Rails development loading becomes a bit trickier since we aren't loading types by constant name 
- How does it work to share types between schemas? How are built-in types installed to the schema?

However, it would also support a nice feature:

- you could reference types by _name_, eg `field :posts, "[Post]"`, since the strings would be looked up in the schema

So, I'm open to it, but I couldn't make it a priority for my own work!

**Comment by rmosolgo** [comment]
Closing as I don't see any clear action items here, please reopen if I've missed something!
