### ISSUE TITLE
Why raise RuntimeError instead of custom GraphQL error class?

### ISSUE THREAD

**Issue by TSMMark** [rmosolgo/graphql-ruby#551]
When a field resolves improperly, why do we raise `RuntimeError` instead of a `GraphQL::SomethingError`?

for example `Cannot return null for non-nullable field MyType.my_field`

As far as I can tell I have no way of rescuing specifically for these types of errors.

**Comment by TSMMark** [comment]
I may be incorrect about this. might reopen later

**Comment by rmosolgo** [comment]
Sure, I'll keep an eye on it! I know that the, um, "balance" of raising vs. handling errors is still a bit off, so I'm happy to hear how it might be improved. 

For non-null fields in particular, you can handle those with a [`Schema#type_error`](https://rmosolgo.github.io/graphql-ruby/schema/configuration_options#type-error-handling) handler.
