### ISSUE TITLE
Interesting thought on graphql-ruby's current architecture

### ISSUE THREAD

**Issue by vergenzt** [rmosolgo/graphql-ruby#558]
A colleague shared an article (["Write code that is easy to delete, not easy to extend"](http://programmingisterrible.com/post/139222674273/write-code-that-is-easy-to-delete-not-easy-to)) with me, and reading through it made me think very strongly of this library, especially at the tradeoff between the author's steps 2 & 3.

Just wanted to say kudos. 🎈 It would be easy to overengineer a project like this and I think you've done a good job keeping the API simple and expanding only as needed.

**Comment by rmosolgo** [comment]
😊 Thanks for saying so, this project has been a big experiment in library maintenance and I've definitely learned a lot!
