### ISSUE TITLE
argument_interfaces

### ISSUE THREAD

**Issue by anazar** [rmosolgo/graphql-ruby#559]
Is there a way to add argument_interfaces similar to return_interfaces to be able to share groups of arguments like pagination/search across multiple fields?

**Comment by rmosolgo** [comment]
There's no baked-in solution for that, but you can use plain Ruby to do it, see some suggestions here:

https://github.com/rmosolgo/graphql-ruby/issues/515

I'm interested in supporting this in the gem, so feel free to discuss there or subscribe to that issue!
