### ISSUE TITLE
Exceptions from within promises

### ISSUE THREAD

**Issue by staugaard** [rmosolgo/graphql-ruby#566]
It looks like the `RescueMiddleware` does not handle exceptions coming from within promises.

When we hit a `ActiveRecord::RecordNotFound` in a non-lazy resolver then the middleware takes care of it, but when we hit that same exception inside a lazy promise resolver, then the error makes it's way all the way out to the rails controller.

**Comment by rmosolgo** [comment]
Oh, interesting. I guess that's a flaw in the runtime design. Middleware only wraps `resolve`, not `lazy_resolve`. 

I guess the best "fix" is to introduce an error handling plugin like 

```ruby 
MySchema = GraphQL::Schema.define do 
  use GraphQL::Rescues
end 
```

which will wrap _both_ eager- and lazy-loading with error handling. (In my opinion, the _real_ best case would be to avoid raising errors altogether 😆 )

**Comment by ianks** [comment]
You can catch the error and return a `GraphQL::Exception`. This is how I handle promises in one of my resolvers. Note: al the `Rails.appliction.executor.wrap` stuff is to avoid autoload deadlocks in Rails 5 :disappointed: :

```
...
    def promise(&_blk)
      Rails.application.executor.wrap do
        Concurrent::Promise
          .execute { Rails.application.executor.wrap { yield } }
          .catch { |e| handle_error(e) }
      end
    end

    def handle_error(e)
      Rails.logger.error(e)
      Rails.logger.error(e.backtrace.join("\n"))
      GraphQL::ExecutionError.new(e.message)
    end
```

**Comment by rmosolgo** [comment]
I just merged some new error handling for the interpreter that properly catches errors in promises: https://github.com/rmosolgo/graphql-ruby/pull/2458

If you give it a try and have a problem, please open a new issue!
