### ISSUE TITLE
Sequel::Dataset not working for relationship types

### ISSUE THREAD

**Issue by anazar** [rmosolgo/graphql-ruby#581]
It doesn't appear the sequel datasets are working.  Since sequel creates a dynamic class it appears that it can't be recognized by the registered connection.

example:
``` 
connection :users do
    type UserType.connection_type

    resolve -> (obj, args, ctx) {
      SEQUEL_DB[:users]
    }
end
```

I would assume this should work but it's not recognizing the resolve data as a sequel dataset.

**Comment by rmosolgo** [comment]
Hi! Thanks for reporting this. Could you help me gather some information to debug the issue? 

Could you log the class of that return value, for example: 

```ruby 
    resolve -> (obj, args, ctx) {
      result = SEQUEL_DB[:users].limit 1000
      # Log the class:
      p result.class 
      result 
    }
```

Also, could you show the value of this connection registry for your application? 

```ruby 
p GraphQL::Relay::BaseConnection::CONNECTION_IMPLEMENTATIONS
```

That will help me understand why it's failing!

**Comment by anazar** [comment]
Sure,
`=> #<Sequel::Mysql2::Dataset: "SELECT * FROM `users` LIMIT 1000">`
The problem is that the .class value of what is returned is:
`=> #<Class:0x007fb98ec9d138>`

So i don't think it's able to determine the returned data type.

This returns true:
`SEQUEL_DB[:users].limit(1000).is_a?(Sequel::Dataset)`

**Comment by rmosolgo** [comment]
Could you show me the return value of this Ruby constant?

```ruby
p GraphQL::Relay::BaseConnection::CONNECTION_IMPLEMENTATIONS
```

(One of the keys should be `Sequel::Dataset`, added here: https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/relay/relation_connection.rb#L116-L118) 

Also, when you say it's "not working", can you share the specific error or misbehavior that you're getting?

**Comment by anazar** [comment]
it appears to be finding the correct connection implementation.  Looks like this issue is that a Sequel::Dataset returns a hash and to render the user type it's expecting an object.

Getting an error like: `Unexpected error while processing request: undefined method `status' for #<Hash:0x007f7fb977e468>`

**Comment by anazar** [comment]
yep, that was it.

doing: `field :status, types.String, hash_key: :status` fixes the issue.  

Seems like if we are to use Sequel::Datasets then it should expect hash by default?

**Comment by rmosolgo** [comment]
GraphQL doesn't do any runtime checks on user-provided objects to guess how to resolve fields. `hash_key:` exists for just this purpose, or you could wrap the results with another class that responded to the necessary methods. 

Glad we found the issue!
