### ISSUE TITLE
Returning a GraphQL::ExecutionError within a connection results in a RuntimeError

### ISSUE THREAD

**Issue by Carlows** [rmosolgo/graphql-ruby#591]
Returning a GraphQL::Execution error within a connection resolver like this:

```
connection :projects do
  type ProjectType.connection_type
  description "Projects created in the current Organization"

  resolve ->(obj, args, ctx) do
    return GraphQL::ExecutionError.new("Error ocurred") if not_supposed_to_be_here
    obj.projects
  end
end
```

Results in:

```
RuntimeError - No connection implementation to wrap GraphQL::ExecutionError (Error ocurred)
```

Is there something wrong with using these errors like this? using `raise GraphQL::ExecutionError` works, should I opt for using raise instead?

**Comment by rmosolgo** [comment]
Huh, strange! Returning an error should be [supported here](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/relay/mutation.rb#L245-L248) and [tested here](https://github.com/rmosolgo/graphql-ruby/blob/master/spec/graphql/relay/mutation_spec.rb#L265-L286). Could you share your gem version?

**Comment by Carlows** [comment]
I'm using: `graphql-1.4.4`

**Comment by rmosolgo** [comment]
:man_facepalming: I'm an idiot! I was looking at mutations, not connections. 

Apparently we don't support that, but we should. Looks like we need error checking here: https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/relay/connection_resolve.rb#L24-L27

Thanks for reporting this!

**Comment by Carlows** [comment]
Oh ok, cool, I'm going to have an eye on this, thanks!
