### ISSUE TITLE
Testing helpers

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#594]
I'd like to include some tools explicitly for testing a schema. These don't really depend on a test suite, but you could call them in your tests:

- `GraphQL::Lint`: ensure that schema members comply with user-defined rules 
- Calling fields in isolation, eg

  ```ruby 
  # Fetch a field from the schema and call it with GraphQL trappings (type checking, error handling)
  MySchema.call("Post.comments", post, { first: 5 }, { current_user: user })
  ```

 Testing fields apart from GraphQL is good too, but sometimes it's hard to tell how various instrumentation etc will apply to field resolution.

- Assert no breaking changes (compare in-memory schema with printed IDL). This would be a warning to the developer, to "approve" breaking changes, you clobber the IDL.
- Assert dumped files are up-to-date (eg, dumped IDL matches in-memory schema)

Anything else?

**Comment by chollier** [comment]
I've answered part of this in https://github.com/rmosolgo/graphql-ruby/issues/593#issuecomment-287237221

Here is what we use @quri to ensure the dumped schema matches the in-memory schema:
```ruby
describe Hermes::Schema do
  it 'dumped schema should be up to date' do
    actual_schema = GraphQL::Schema::Printer.print_schema(described_class)
    dumped_schema = File.read(Rails.root.join("app/graph/schema.graphql"))

    expect(actual_schema).to eq(dumped_schema), 'GraphQL Schema is out of date. Please run rake graphql:dump'
  end
end
```

**Comment by chollier** [comment]
We also have a bunch of customer RSpec Matchers that have done a great deal in helping us to fully test the types, example: 

### Testing a type
```ruby
describe Hermes::ForumTopicType do
  subject { create(:discussion_topic) }

  it { should have_a_relay_global_node_identification }
  it { should have_a_graphql_property_of(:__id, :id) }
  it { should have_a_graphql_property_of(:subject) }
  it { should have_a_graphql_property_of(:body) }
  it { should have_a_graphql_property_of(:newestPostedAt, :discussion_response_updated_at) }
  it { should have_a_graphql_property_of(:createdAt, :created_at) }
  it { should have_a_graphql_property_of(:isPinned, :is_pinned) }
  it { should have_a_fetched_graphql_property_of(:platform, Hermes::FetchPlatformField) }
  it { should have_a_fetched_graphql_property_of(:job, Hermes::ForumTopic::FetchJobField) }
  it { should have_a_fetched_graphql_property_of(:category, Hermes::ForumTopic::FetchCategoryField) }
  it { should have_a_fetched_graphql_property_of(:author, Hermes::ForumTopic::FetchAuthorField) }
  it { should have_a_fetched_graphql_connection_of(:responses, Hermes::ForumTopic::FetchResponsesField) }
end
```

Some of them imply passing the schema to them as we need it for the Relay Node ID one for instance, but let me know if it's something you would be interested in providing too.

**Comment by rmosolgo** [comment]
I don't think I'll get to this before releasing 1.6 but I hope to revisit soon. 

Another crazy idea: GraphQL snapshot testing. You run the query once in your tests and save the output to a file. Later tests run the query again and assert that the new result matches the previous result. We do that a lot in the tests of this gem, too.

**Comment by aaronklaassen** [comment]
@chollier Similarly, we've been using this gem: https://github.com/khamusa/rspec-graphql_matchers to test field types, etc.

**Comment by Willianvdv** [comment]
@aaronklaassen @chollier I've always wondered what you test with the `rspec-graphql_matchers`, to me if always feels a bit like it's testing the inner workings of the graphql-ruby gem. What errors do you typically catch with this test strategy?

What we currently do test are mutations, it's just too easy to make a typo when dealing with variables from `ctx` and `args`. We thought about "upgrading" args and ctx to an actual class/struct so that Ruby can catch some of the typos. But we didn't spend too much energy in this solution and went with the test solution.

**Comment by aaronklaassen** [comment]
@Willianvdv Yeah you're not wrong, and I'm a bit torn on it for exactly that reason. More complex resolvers get additional tests, obviously. It's more "this is the definition of my `User` type, and if that changes - intentionally or otherwise - I want my specs to let me know." And it's very little effort to get that.

**Comment by rmosolgo** [comment]
I don't have plans to work on this, and the conversation is stale, closing.
