### ISSUE TITLE
Improve doc & website

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#595]
I would like to fix some issues with graphql-ruby documentation:

- The website is ugly and hard to read 
- Specific features are hard to find because they're scattered among confusingly-named "guides"
- The list of guides is silly long and they don't all fit in the side column 

There are some things I would like to preserve with the current documentation: 

- Keeping the website source in the main repo 
- Keeping the great workflow for managing & deploying 

To fix the issues above, I'd like to: 

- Consider new designs for the website (visual and conceptual, perhaps taking hints from other OSS docs)
- Add some kind of categories & search to the site, perhaps include API docs in the website (instead of/along with rubydoc.info)

Do you have other issues with documentation and website that you'd like to have addressed? Or, do you have ideas for a new design? I'm entirely incapable at UX / visual design but I'm happy to write front-end code if someone has a design idea (also happy _not_ to write the front-end code of they want to do it themselves 😆 ).

**Comment by abelosorio** [comment]
Hey there! I would help you to write the new website, but I'm not very good at design time :stuck_out_tongue: 

Regards, Abel

**Comment by volkanunsal** [comment]
There is a more urgent problem with documentation. The default version of the API documentation on RubyDocs is fixed to 1.5.2.  I'm not sure how RubyDocs works, but when you click on a RubyDocs link from [here](http://graphql-ruby.org/schema/types_and_fields), you don't see the latest version of the API.

**Comment by rmosolgo** [comment]
Thanks for the heads up! 

There's a way to force a certain version, by adding the version number to the URL, for example: 

http://www.rubydoc.info/gems/graphql/1.5.13/GraphQL/ScalarType

Maybe I should improve the website's `api_doc` helper to include the latest version so that we don't get stale docs. 

>  I'm not sure how RubyDocs works

Me either 😬

**Comment by rmosolgo** [comment]
Added the version number to API links in f737947, thanks for pointing that out!
