### ISSUE TITLE
Parse error using field with argument

### ISSUE THREAD

**Issue by davidnorth** [rmosolgo/graphql-ruby#60]
In my schema I have a couple of fields that are computed rather than being attributes on the object in question so I use the block style + resolve to define them.

This works fine for one field that has no arguments e.g. the query:
    { some_model(id: 1) { id, some_computed_field } }

It causes a parse error (ParseError: Extra input after last repetition) if the field requires arguments
   { some_model(id: 1) { id, greeting(name: 'John') } }

Which is defined like this:

    field :greeting do
      type !types.String
      argument :name, !types.String
      resolve -> (obj, args, ctx) do
        "Hello #{ name }"
      end
    end

**Comment by rmosolgo** [comment]
I think it's a quotation-mark issue! Sorry the error isn't too helpful. From [the spec](http://facebook.github.io/graphql/#sec-String-Value):

> Strings are sequences of characters wrapped in double‐quotes (").

This works ok for me: 

```ruby 
GraphQL.parse(%|{ some_model(id: 1) { id, greeting(name: "John") } }|)
# => #<GraphQL::Language::Nodes::Document:0x007fcae3881840
```

Again, sorry about the error. They just bubble up from Parslet and I don't want to spend a lot of time on them because I really just want to use `libgraphqlparser` for parsing instead!

**Comment by davidnorth** [comment]
@rmosolgo Many thanks, that also works for me - I still need to study the spec more closely.

One other thing I noticed is that default values for arguments seem to not be implemented. I will have a go at a fix for this unless you happen to be working on that already.

**Comment by rmosolgo** [comment]
Oh, really?! I thought it was in tip-top shape on the latest version (0.10.1), but certainly if something is missing there, please report it or open a PR!

**Comment by davidnorth** [comment]
Sure, I'll look into that some more, I think its just the validator.

**Comment by davidnorth** [comment]
Default values are working fine, I needed to remove the '!' from that args type to allow null.
