### ISSUE TITLE
`rails generate graphql:install` doesn't work for me

### ISSUE THREAD

**Issue by yumikohey** [rmosolgo/graphql-ruby#617]
Rails -v 4.2.5
Ruby -v 2.4.0

gem `graphql`
gem `graphql-relay`

Errors
```
Running via Spring preloader in process 64505
Expected boolean default value for '--markerb'; got :erb (string)
Expected string default value for '--test-framework'; got false (boolean)
Expected string default value for '--test-framework'; got false (boolean)
Expected string default value for '--test-framework'; got false (boolean)
Expected string default value for '--helper'; got true (boolean)
Expected string default value for '--assets'; got true (boolean)
Expected string default value for '--test-framework'; got false (boolean)
Expected string default value for '--test-framework'; got false (boolean)
Expected string default value for '--test-framework'; got false (boolean)
Expected string default value for '--test-framework'; got false (boolean)
Expected string default value for '--test-framework'; got false (boolean)
Could not find generator 'graphql:install'. Maybe you meant 'react:install', 'pundit:install' or 'devise:install'
Run `rails generate --help` for more options.
```

**Comment by AjayBarot** [comment]
@yumikohey : 
looks like these two gems are not compatible with each other. Please follow these steps to overcome this issue.
    1. Remove `gem graphql-relay` from your `Gemfile`.
    2. `bundle install`
    3. Make sure you have latest version of graphql
        - Check your `Gemfile.lock` latest graphql version is 1.5.2
    4. execute generator `rails generate graphql:install`

Cheers

**Comment by rmosolgo** [comment]
Those steps above sound good to me! If they don't help, please reopen this issue and paste your full `Gemfile.lock`.

**Comment by alxx** [comment]
I started having the same problem, out of the blue. I didn't have graphql-relay; it was a brand new Rails 5.2.0 project in a previously empty gemset. Ruby 2.5.1p57. The error was: "Could not find generator 'graphql:install'.

In my case it was because of spring. I disabled spring and it worked perfectly well.

To kill existing spring processes:
`pkill -f spring`

To disable spring:
`bin/spring binstub --remove --all`

**Comment by brainmaniac** [comment]
... of some reason the [graphQl gem](https://rubygems.org/gems/graphql) wasn't added to my gem file. So I just added this row to the gemfile:

`gem 'graphql', '~> 1.9', '>= 1.9.3'`

... and ran `bundle`

then it worked

PS. the above row is the most resent version at the time of writng this. Make sure you have the latest version here : https://rubygems.org/gems/graphql .DS

**Comment by lonniemoss** [comment]
I have a error like too. For me it was because that I had put a space between : and graphql.
