### ISSUE TITLE
Adding multiple errors to the errors field.

### ISSUE THREAD

**Issue by hubertpompecki** [rmosolgo/graphql-ruby#629]
Hi there,

First of all, great job on this library! It is a very useful tool and an extremely valuable contribution to the community.

Just a quick question - I am aware how it is possible to return a `GraphQL::ExecutionError` from the `resolve` function to attach an error to the `errors` array in the response. However, I can't work out a way to add multiple errors, e.g. one entry in the array for each validation error generated by Rails. I know I could just `.join(', ')` the messages but I feel that creating a separate array entry for each would be cleaner.

Is there a way to do this or is it not currently supported?

I am not very keen on adding a custom `errors` field to my schema, I'd prefer to put all errors in the top-level field as suggested by the GraphQL spec and simply return a `null` data entry when a mutation fails.

Thanks!

**Comment by rmosolgo** [comment]
Hi! Glad you're enjoing it! 

The `ctx` argument to resolve has an [`add_error` method](http://www.rubydoc.info/github/rmosolgo/graphql-ruby/GraphQL/Query/Context/FieldResolutionContext#add_error-instance_method) which can be used to add ExecutionErrors to the response. For example: 

```ruby 
resolve ->(obj, args, ctx) {
  # ...
  ctx.add_error(GraphQL::ExecutionError.new("Oops, something went wrong"))
  ctx.add_error(GraphQL::ExecutionError.new("Oops, something went VERY wrong"))
  nil
}
```

Sorry that's not well documented! I'll try to revisit it soon. Does that work in your case?

**Comment by hubertpompecki** [comment]
Thanks! It works a treat and is exactly what I was looking for.

**Comment by cantino** [comment]
I needed this as well, thanks!

**Comment by nadiyaka** [comment]
Please help me to understand how to add multiple errors in the new syntax. It is still not documented :(

**Comment by veeral-patel** [comment]
@rmosolgo same here!

**Comment by mikeabney** [comment]
This was the top result from a search for "graphql ruby return multiple errors", so in case anyone else ends up looking for how to do this, here is a trivial example that seems to (roughly) work in 1.10:

```ruby
  def resolve(arg1:, arg2:)
    {
      result: MyAction.execute # raises a single error of a custom type wrapping validation errors
    }
  rescue ValidationFailure => failure
    failure.errors.each do |error|
      context.add_error(
        GraphQL::ExecutionError.new(
          error.message,
          path: error.path,
          extensions: error.extensions
        )
      )
    end
  end
end
```

Note that this is a trivial example with some less-than-best practices. The important thing to note is that the `GraphQL::Schema::Mutation` (in fact any `GraphQL::Schema::Resolver`) has an `attr_accessor` for the `context`, which still has the `add_error` method.

**Comment by pablosky** [comment]
> This was the top result from a search for "graphql ruby return multiple errors", so in case anyone else ends up looking for how to do this, here is a trivial example that seems to (roughly) work in 1.10:

is there anyway to use a wrapper as we are going to use a lot this rescue in every resolver

**Comment by mikeabney** [comment]
@pablosky : See the `rescue_from` mentioned on the [Error Handling page](https://graphql-ruby.org/errors/error_handling.html#add-error-handlers). It basically gets defined at the schema level.

**Comment by gmac** [comment]
I wrote a helper that allows error arrays to work correctly in 1.11:

```ruby
# In GraphQL Ruby, an array of all errors nullifies the entire array result
# This manually fixes the behavior so that errors are reported with their path,
# and their array position is nullified.
def self.map_array_errors(array, context)
  array.each_with_index.map do |item, idx|
    item = yield(item) if block_given?
    if item.is_a?(GraphQL::ExecutionError)
      item.path = [context[:current_path], idx].flatten
      context.add_error(item)
      nil
    else
      item
    end
  end
end
```
