### ISSUE TITLE
input_field with a description causes error

### ISSUE THREAD

**Issue by kliuless** [rmosolgo/graphql-ruby#63]
I tried both of these (in a `Mutation.define`):

```ruby
input_field :code, types.String do
  description "item code"
end
```
and
```ruby
input_field :code, types.String, "item code"
```

Both of them cause this error when I do an IntrospectionQuery.
```
NoMethodError (undefined method `desc=' for #<GraphQL::Argument:0x007fba1e85a
860>)
```

If I remove the description, the error goes away. I'm using graphql 0.10.3 and graphql-relay 0.4.5.

**Comment by rmosolgo** [comment]
Thanks for reporting this! Oops, it was a typo and i've pushed a fix to master. Could you give it a try?

**Comment by kliuless** [comment]
The fix works with both of the use cases. Thanks for the quick response.

**Comment by rmosolgo** [comment]
Cool, glad to hear it, i'll get a new version out soon!
