### ISSUE TITLE
Parse error when query has a not-null variable

### ISSUE THREAD

**Issue by davidnorth** [rmosolgo/graphql-ruby#64]
The following query from executing_queries.md doesn't parse:

    GraphQL::PARSER.parse('query getPost($postId: !Int){ post(id: $postId) { title } }')
    # => Parslet::ParseFailed: Extra input after last repetition at line 1 char 1.

If you remove the '!' in front of Int it works fine.
Since you plan to replace Parslet, maybe this isn't worth fixing but I thought I should mention it. I can just allow null for now.

**Comment by rmosolgo** [comment]
Derp, actually it was a typo on my part. In a query, the `!` goes _after_ the type name, but in the Ruby DSL, it goes _before_ the type name. So, this is the proper query:

```ruby 
GraphQL.parse('query getPost($postId: Int!){ post(id: $postId) { title } }')
# => #<GraphQL::Language::Nodes::Document:0x007fd7f198dc78...
```

Sorry about that, I've pushed a fix to master!

**Comment by davidnorth** [comment]
Thanks!
