### ISSUE TITLE
Allow GraphQL::Query::Arguments to be converted into a regular Ruby hash

### ISSUE THREAD

**Issue by davidnorth** [rmosolgo/graphql-ruby#65]
For better Rails integration it'd be nice to get a regular Hash from arguments. For example, ActiveRecord won't accept GraphQL args as an attributes hash. It'd be nice to be able to use other methods too like 'update'.  My workaround for now is instance_variable_get(''@values").

What do you think about adding 'to_h' or 'unwrap'? I can make a PR.

**Comment by rmosolgo** [comment]
That makes total sense, `#to_h` would be great!

**Comment by rmosolgo** [comment]
This is in master now, thanks :confetti_ball: :D
