### ISSUE TITLE
[Question] How to create a mutation without `input` field?

### ISSUE THREAD

**Issue by cpunion** [rmosolgo/graphql-ruby#653]
I want to create a mutation, likes:

```graphql
mutation createPost($title: String!, $body: String!) {
  createPost(title: $title, body: $body) {
    id
  }
}
```

When I create by `rails g graphql:mutation CreatePost`, and then use it with:

```ruby
Types::MutationType = GraphQL::ObjectType.define do
  name 'Mutation'

  field :createPost, field: Mutations::CreatePost.field
end
```

It generate a mutation:

```graphql
mutation createPost($input: CreatePost!) {
  createPost(input: $input) {
    id
  }
}
```

It just has one argument, needs less code, sometimes easy to write. But I want it seems like a function with some arguments.
**How to expand the input argument to its fields when use GraphQL::Relay::Mutation?**

If I define with below:

```ruby
Types::MutationType = GraphQL::ObjectType.define do
  name 'Mutation'

  field :createPost do
    argument :title, !types.String
    argument :body, !types.String
    resolve -> (...) {...}
  end
end
```

**How to separate fields to files in this way?**

**Comment by rmosolgo** [comment]
[All Relay mutations have an `input` argument](https://facebook.github.io/relay/graphql/mutations.htm#sec-Mutation-inputs), so you can't use `Relay::Mutation` for this. 

I think you might like `GraphQL::Function` ([API](http://www.rubydoc.info/github/rmosolgo/graphql-ruby/GraphQL/Function), [guide](https://rmosolgo.github.io/graphql-ruby/schema/code_reuse#functions)), how does that look?

**Comment by cpunion** [comment]
@rmosolgo thanks. I will try it.

**Comment by rmosolgo** [comment]
feel free to reopen this if it doens't work for you!

**Comment by cpunion** [comment]
I tried and read document about functions. It only can use builtin types for arguments. So if I want use custom types, and I don't want see `input`, do I must define the field with a block likes below?

```ruby
  field :createPost do
    argument :title, !types.String
    argument :body, !types.String
    resolve -> (...) {...}
  end
```

**Comment by rmosolgo** [comment]
> only can use builtin types

Is that right? It should support _any_ type!

**Comment by cpunion** [comment]
This is my code:

```ruby
class Functions::SignUp < GraphQL::Function
  type Types::UserInfoType

  argument :email, !types.String
  argument :password, !types.String

  def call(obj, args, ctx)
    UserInfo.new
  end
end
```

```ruby
Types::MutationType = GraphQL::ObjectType.define do
  name 'Mutation'

  field :signUp, function: Functions::SignUp.new
end
```

Some errors happen:
```
NameError (undefined local variable or method `types' for Functions::SignUp:Class
Did you mean?  type
               @type):
```

When I change `types.String` to `GraphQL::STRING_TYPE`, it works.

And I found a section in document https://rmosolgo.github.io/graphql-ruby/schema/code_reuse#types :

> Note that types. is not available. Instead, you should reference GraphQL’s built-in GraphQL::ScalarTypes directly.

And I found `types.` can be use in `QueryType` at https://rmosolgo.github.io/graphql-ruby/schema/code_reuse#extending-functions, but I want all code in that function.

Where did I wrong?

**Comment by rmosolgo** [comment]
Oh, my documentation there is not good enough! How about this: 

```ruby
class Functions::SignUp < GraphQL::Function
  type Types::UserInfoType

  argument :email, GraphQL::STRING_TYPE.to_non_null_type
  argument :password, GraphQL::STRING_TYPE.to_non_null_type

  def call(obj, args, ctx)
    UserInfo.new
  end
end
```

:thinking: Maybe I should just support `types.` within function classes ...

**Comment by cpunion** [comment]
Oh, I see. User defined types can be used, just not support `types.*`. I'd happy if you support that. ;-)

**Comment by rmosolgo** [comment]
I think the change should be straightforward. [`GraphQL::Function`](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/function.rb) needs a class method called `.types` which returns [`GraphQL::Define::TypeDefiner.instance`](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/define/type_definer.rb), similar to this [`#types` method](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/define/defined_object_proxy.rb#L16-L19). Then, the [existing test function](https://github.com/rmosolgo/graphql-ruby/blob/master/spec/graphql/function_spec.rb#L5-L18) could be extended to include the use of `types.*`. 

Feel free to take a try if you have the time!
