### ISSUE TITLE
Better visibility for non-UTF8 strings

### ISSUE THREAD

**Issue by gjtorikian** [rmosolgo/graphql-ruby#657]
https://github.com/rmosolgo/graphql-ruby/pull/517 mandated that all strings come back UTF-8 encoded, which is great. But in development practice, I and several other colleagues have been bitten by the mysterious `null` that comes back from a part of the Rails application that otherwise works fine.

Could I amend this check to do something like `raise ExecutionError if Rails.env.development? || Rails.env.test?`? Basically, when building a GraphQL schema around existing DB values, it would be extremely helpful to know that the values need to be force encoded. In production this would continue to return `nil`.

cc @rmosolgo @josh for thoughts
fyi @cheshire137

**Comment by rmosolgo** [comment]
:+1: 

As a stop-gap, you can override the built-in function:

```ruby 
GraphQL::STRING_TYPE.coerce_result = ->(value) { 
    str = value.to_s
    if str.encoding == Encoding::US_ASCII || str.encoding == Encoding::UTF_8 
      str
    elsif Rails.env.development? || Rails.env.test? 
      raise "Gotta be utf-8"
    else 
      nil
    end 
}
```

I'm open to a louder 💥  in the failing case, but as you saw on #517, I didn't have a great time selecting one 😖

**Comment by josh** [comment]
> I'm open to a louder 💥 in the failing case, but as you saw on #517, I didn't have a great time selecting one 😖

Ha, same!

**Comment by dylanahsmith** [comment]
I would prefer to get the exception in production too, since I don't want this to be hard to debug in production either

**Comment by gjtorikian** [comment]
> I didn't have a great time selecting one

I keep rolling this over in my head; I'm almost tempted to have it `raise` _always_. Is that crazy?

I looked back on the old thread and came across [this comment](https://github.com/rmosolgo/graphql-ruby/pull/517#issuecomment-281554702). Given that the spec requires UTF-8 I feel pretty good about making this 💥  always. What do you think?

**Comment by dylanahsmith** [comment]
Also, I think ExecutionError is for client errors.  In this case we would want a non-ExecutionError so that it would be treated as an internal server error, where usually that error would get reported to something like errbit.

**Comment by rmosolgo** [comment]
:+1: for some hard crash & non `ExecutionError` as @dylanahsmith suggested, so that schema owners can track down and address the issue. 

We _could_ make it configurable but it requires atoning for a design flaw. The scalar `coerce_*` functions have access to the `value` only. We could modify them to accept `ctx` also, then call a handler on the schema when a value fails coercion, something like:

```ruby 
err = GraphQL::ScalarCoerceError.new(type, value)
# Reuse the existing `type_error` handler, but with a new class of error:
ctx.schema.type_error(err, ctx)
```

This way, different folks could have different strokes. 

To maintain compatibility with current custom scalars, we could have the `coerce_*=` methods wrap a one-argument function, eg 

```ruby 
def coerce_input=(coerce_input_func)
  @coerce_input_proc = if method_or_proc_arity(coerce_input_func) == 1
   warn("...")
    -> (v, ctx) { coerce_input_func.call(v) }
  else 
    coerce_input_func
  end 
end 
```

but, if a hard crash works for ya, we could leave that until later.

**Comment by gjtorikian** [comment]
Yeah, I'd probably make it `ResolverError` or some such. Anyway, I'm on the case. 😎
