### ISSUE TITLE
connections: query results that exceed max_page_size do not set hasNextPage to true

### ISSUE THREAD

**Issue by blevine** [rmosolgo/graphql-ruby#659]
This might be expected behavior.  If so, feel free to close this issue.

If I issue a query that includes a connection field and do not specify any paging arguments (`first`, `last`, etc.), this translates into a "get all" query. If the results for that connection field exceeds `max_page_size`, then the result set will be truncated.  However, the `hasNextPage` field of `pageInfo` remains false. `hasNextPage` is set correctly only if paging arguments are included in the query. This means that, without including paging arguments, there's no way for the caller to know that his query has been truncated.

I suppose you could argue that the caller should have been including paging arguments in the first place.

**Comment by blevine** [comment]
Looks like this is related to #656 which is due to https://github.com/graphql/graphql-relay-js/issues/58

**Comment by rmosolgo** [comment]
It sounds like this behavior is spec-compliant, right? 

I'd be happy to support behavior this behavior but only if: 

- Someone else implements it, and it's not the default (that is, default behavior is spec-compliant)
- This behavior becomes part of the Relay spec
