### ISSUE TITLE
Breaks with concurrent-ruby 1.0.2

### ISSUE THREAD

**Issue by jscheid** [rmosolgo/graphql-ruby#662]
Map#each was added in concurrent-ruby 1.0.3, so either this should use Map#each_pair, or test for presence of Map#each, or it should declare an (optional) dependency somehow to ensure the correct version is being used.

**Comment by rmosolgo** [comment]
Oh my, I'm a novice with concurrent-ruby. I'm happy to take a try at this fix, but my real problem is that I haven't found solid API documentation. Can you point me to any docs for `each_pair`?

**Comment by jscheid** [comment]
I don't know anything about it either... I got an error when accessing `pair` with 1.0.2, and found this in the [CHANGELOG for 1.0.3](https://github.com/ruby-concurrency/concurrent-ruby/blob/master/CHANGELOG.md#release-v103-17-dec-2016):
> Adds Map#each as alias to Map#each_pair

After upgrading to 1.0.3 it works fine.

**Comment by jscheid** [comment]
Actually I haven't tried upgrading to 1.0.3... I went straight to 1.0.5. But presumably 1.0.3 would work as well.

**Comment by gjtorikian** [comment]
If I understand correctly, the issue is with older patch versions of the gem? It sounds like it doesn't work with 1.0.2 but does with 1.0.5?

If that's the case then I'd suggest it's not worth the effort/code rot to add for the prescience of `Map#each` or other workarounds.

**Comment by jscheid** [comment]
Sure, that's your call. The first thing I saw when I used your lib was an obscure error message that I had to debug... if you don't mind that then that's fine by me, I've already fixed it at our end.
