### ISSUE TITLE
The AST on the context object is not flattened

### ISSUE THREAD

**Issue by staugaard** [rmosolgo/graphql-ruby#67]
As discussed on Slack the AST on the context object is not flattened, but should be.

Here is an example that shows the problem:

```ruby
require 'graphql'

UserType = GraphQL::ObjectType.define do
  name 'User'
  description 'A user'

  field :id, !types.ID
  field :name, !types.String
end

PostType = GraphQL::ObjectType.define do
  name 'Post'
  description 'A post'

  field :id, !types.ID
  field :name, !types.String
  field :author, UserType
end

QueryType = GraphQL::ObjectType.define do
  field :posts do
    type types[PostType]
    resolve -> (_, args, context) do
      if context.ast_node.selections[1].selections[0].is_a?(GraphQL::Language::Nodes::FragmentSpread)
        raise "the AST is not flat"
      end
    end
  end
end

MySchema = GraphQL::Schema.new(query: QueryType)

query_string = "{
  posts {
    id
    author { ...userFields }
  }
}

fragment userFields on User {
  id
}
"

puts MySchema.execute(query_string, debug: true)

```

**Comment by rmosolgo** [comment]
At first, I thought I could do this ahead of time , but there are cases where you _need_ to execute some fields in order to know what kind of object you have. For example:

```graphql 
{
  search(query: "The Alamo") {
    ...imageFields
    ...documentFields
  }
}
fragment imageFields on Image { ... }
fragment documentFields on Document { ... }
```

You can't simply inline those fields because you don't know which ones will apply. 

I think the best you could do ahead of time was make those inline the _fragments_, as if it had been written: 


```graphql 
{
  search(query: "The Alamo") {
    ... on Image { ... }
    ... on Document { ... }
  }
}
```

Of course, that doesn't make it much nicer to traverse the AST by hand in a resolve function, but at least it would be _possible_!

**Comment by rmosolgo** [comment]
Here's a try at that preprocessor: https://github.com/rmosolgo/graphql-ruby/compare/preprocessor It seems pretty weird. 

In the meantime, I've [added `Context#query`](b469452670c81c7328ba65e734c0a9b3c313a5c7), so that if you find a fragment spread in the AST, you could look it up from `Query#fragments`, eg 

```ruby 
ctx.query.fragments["userFields"] 
# => GraphQL::Language::Nodes::FragmentDefinition`
```

**Comment by staugaard** [comment]
Yeah I see. Gaining access to the query from context enabled me to do what I wanted.

I needed a method to ask if a given field is in the flattened selection. Here is what I did:

```ruby

def find_field(name, ast: , context:)
  ast.selections.each do |node|
    case node
    when GraphQL::Language::Nodes::Field
      return node if node.name == name
    when GraphQL::Language::Nodes::FragmentSpread
      if definition = context.query.fragments[node.name]
        field = find_field(name, ast: definition, context: context)
        return field if field
      end
    end
  end

  nil
end
```

**Comment by chanks** [comment]
I'm interested in whatever flattening of the AST is possible, too, since I'm needing to traverse the AST in order to efficiently eager load the appropriate columns/associations. I have a recursive technique working reasonably well, but the presence of fragments is making things a bit messy.

**Comment by rmosolgo** [comment]
I haven't found a great way to do this, but if anyone wants to PR, I'm definitely open for it. 

Another approach might be to build a separate library for working with `GraphQL::Language::Nodes::Document` objects, it wouldn't have to be built-in here!

**Comment by rmosolgo** [comment]
0.16.0 introduces `ctx.irep_node`. You can inspect the node's `children` to see _all_ fields which were queried and what types they'll apply to: 

```ruby 
ctx.irep_node.children.each do |irep_child|
  irep_child.name # alias or field name 
  irep_child.definition # => <#GraphQL::Field ...> Field definition 
  irep_child.on_types # => Set<types...> Type definitions which this field will apply to
  irep_child.ast_node # => <#GraphQL::Language::Nodes::Field ... >
end 
```

I haven't had a ton of time to play around with it, but this is the data structure used for query execution now, I think it will provide better support for look-ahead too!

**Comment by staugaard** [comment]
Nice! I'll start using that immediately.
