### ISSUE TITLE
Get requested fields in resolve

### ISSUE THREAD

**Issue by jsnick** [rmosolgo/graphql-ruby#671]
Can I get requested fields in resolve ? 
I want to use includes, ActiveRecord::QueryMethods selectively.

**Comment by cpunion** [comment]
Found a way: 
```ruby
resolve -> (_, _, ctx) {
  ctx.selection.scoped_children.values[0].keys
}
```
But not sure if it is long supported, it used `GraphQL::InternalRepresentation::Node#scoped_children`.

**Comment by rmosolgo** [comment]
You can access child selections with 

```
ctx.irep_node.typed_children 
```

It returns  `Hash<ObjectType => Hash<String => InternalRepresentation::Node>` where: 

- `ObjectType` is the runtime type of the return values (for fields that return union or interface types, there may be _multiple_ object types as keys)
- `String` is the name in the _result_ (so, alias _or_ field name)
- `InternalRepresentation::Node` is the representation of the child selection. It has `.definition` to access the `GraphQL::Field` and `.definition_name` to access the name of that field. 

Sorry the API is a bit ... all of the place. I haven't solidified it much because I haven't _had_ to. If you want to share your use case, I'd be happy to consider some improvements! Hope that helps.

**Comment by jsnick** [comment]
Thank you !

For minimizing the number of queries in my app, I usually use [includes (ActiveRecord::QueryMethods)](https://apidock.com/rails/ActiveRecord/QueryMethods/includes) which pre-fetchs included rows associated.

I'll just check requested fields and if the associated rows in another table exists, then add it to includes methods.
But if don't need associated rows, I don't have to include that.

**Comment by rmosolgo** [comment]
Great!

**Comment by mengqing** [comment]
Is there a better API now or is this still the only way to check it?

**Comment by Leee-xx** [comment]
I have a field definition where `context.query.fragments` is nil, presumably because we're not using fragments? Anyway, I can get the query string via `context.query.query_string`, but I was wondering if there was a more elegant solution or alternative.

**Comment by SeanRoberts** [comment]
Given how difficult this is I have to ask: should I not be doing it at all? I'm trying to tune my database queries based on the fields the user selected. Is this an anti-pattern?

**Comment by rmosolgo** [comment]
I don't see it mentioned above, but there's a new API for this now: https://graphql-ruby.org/queries/lookahead.html

That said, I think Facebook would say not to do this. In _their_ architecture ([TAO](https://www.usenix.org/conference/atc13/technical-sessions/presentation/bronson)), all keys and values were stored together, so they didn't optimize `SELECT ...` fields. Instead, every object load included all fields 🤷

**Comment by swalkinshaw** [comment]
Personally I don't think it's an anti-pattern but I'd also be skeptical how useful this would be; it really depends on your database and structure. My hunch is it might not provide enough of a benefit in many cases. Depends how many columns you have on tables and the ratio of used to unused columns, etc. It could definitely have an impact if you could avoid selecting unused blob/large text columns (eg: serialized data).

**Comment by SeanRoberts** [comment]
In my case it's specifically where the value of a field comes from doing a subquery in the SELECT. I want to skip that subquery if someone doesn't care about that data. Maybe the data could be fetched with Dataloader but I don't think it would be as performant.  In any case, here's how I added this functionality to my resolver:

```ruby
class BaseQuery < GraphQL::Schema::Resolver
    def has_field?(*field_path)
      current_field = field_path.shift
      current_location = context.query.lookahead.ast_nodes[0]
      while current_field
        return false unless current_location&.respond_to?(:selections)

        next_location = current_location.selections.find { |s| s.name == current_field }
        # If we don't find the field directly, look in the fragments
        unless next_location
          fragment = find_in_fragments(current_location, current_field)
          # Return false if field is not found in any fragments
          return false unless fragment
          next_location = fragment
        end

        current_location = next_location
        current_field = field_path.shift
      end

      true
    end

    def find_in_fragments(selection, field_name)
      selection.selections.each do |sel|
        # Check if the selection is a fragment spread
        if sel.is_a?(GraphQL::Language::Nodes::FragmentSpread)
          fragment_name = sel.name
          fragment_def = context.query.document.definitions.find do |defn|
            defn.is_a?(GraphQL::Language::Nodes::FragmentDefinition) && defn.name == fragment_name
          end

          # If we found the fragment definition, search inside it
          if fragment_def
            found_in_fragment = fragment_def.selections.find { |s| s.name == field_name }
            return found_in_fragment if found_in_fragment

            # Recurse into the fragment for nested fragment spreads
            return find_in_fragments(fragment_def, field_name)
          end
        end
      end
end

# Usage
if has_field?("users", "edges", "node", "books")
  # do something in here that you only want to do if books are being selected
end
```

In most cases doing batching or dataloader is probably the better way to handle this but in some cases it's nice to be able to handcraft some SQL to solve your problem.
