### ISSUE TITLE
Better error message for malformed function definitions

### ISSUE THREAD

**Issue by gjtorikian** [rmosolgo/graphql-ruby#678]
I had defined a field like this:

``` ruby
connection :labels, function: Platform::Functions::Labels do
   ...
end
```

See the problem? Me either! When I ran the schema, I received the following error: `RuntimeError: Invalid complexity: nil on labels`

It took me some time to realize I had neglected the `.new` when defining `function: Platform::Functions::Labels.new do`.

I think it'd be pretty useful to bomb immediately if a `function` kwarg is not an instantiated object of some type.

**Comment by rmosolgo** [comment]
:+1: I guess `responds_to` isn't a good enough check because in the above example, the object _did_ respond to the method. (Maybe this was a design error in GraphQL::Function, it can be used as a class _or_ instance)

**Comment by rmosolgo** [comment]
(TBH the whole schema validation _thing_ needs a redo. The output doesn't help you find the right place  and it should include a backtrace)

**Comment by rmosolgo** [comment]
Functions are out, Resolvers are in, and Resolvers work as expected with regards to the snippet above
