### ISSUE TITLE
How to add a global_id field in input type?

### ISSUE THREAD

**Issue by cpunion** [rmosolgo/graphql-ruby#685]
I defined UUID with `global_id_field`, but can't see where is the way to add UUID in input type.

My mutation like below:
```ruby
Mutations::CreateComment = GraphQL::Relay::Mutation.define do
  name "CreateComment"

  input_field :postId, !types.ID
  input_field :title, !types.String
  input_field :body, !types.String
  return_field :comment, !Types::CommentType

  resolve -> (_, args, _) {
    params = args.to_h
    post = Post.find(params.delete('postId'))
    comment = Comment.create!(params)
    {comment: comment}
  }
end
```

How to declare `postId` to UUID type and decode to post's ID automatically?

**Comment by rmosolgo** [comment]
Something like this may be possible, but I haven't looked into it much. 

Recently, arguments started accepting `prepare` functions ([example](https://github.com/rmosolgo/graphql-ruby/blob/d903baa6af7c7a30f26b9fd0741b0c2fd88e3200/lib/graphql/argument.rb#L25-L34)). You could use that function to transform the incoming value. 

But I haven't tried it much, so I'm interested to hear how it goes if you try it!

**Comment by cpunion** [comment]
It works! And very easy to use.

Thank you.

**Comment by cpunion** [comment]
I tried the `prepare` function:

```ruby
input_field :postId, !types.ID, prepare: -> (id) {
   type_name, item_id = GraphQL::Schema::UniqueWithinType.decode(id)
   item_id
}
```

Then rewrite to a class:

```ruby
module Resolvers
  class GlobalId
    def call(globalId)
      type_name, item_id = GraphQL::Schema::UniqueWithinType.decode(globalId)
      item_id
    end
  end
end
```
```ruby
input_field :postId, !types.ID, prepare: Resolvers::GlobalID.new
```

All input types can share it.

I also want to add a `input_global_id_field` with patching some classes, it calls a `schema.prepare_from_global_id`, but no idea how to do it.

**Comment by lucaspolonio** [comment]
@cpunion I believe what you are looking for is a combination of `GraphQL::Field.accepts_definitions` and a `prepare` function. Here's an example for query arguments, not mutation inputs, but the idea should be the same:

```ruby
GraphQL::Field.accepts_definitions(global_id_argument: AssignGlobalIdArgument)
```

```ruby
module AssignGlobalIdArgument
  def self.call(target, *args, **kwargs, &block)
    argument = GraphQL::Define::AssignArgument.call(target, *args, **kwargs, &block)
    argument.type = GraphQL::ID_TYPE
    argument.prepare = -> (global_id) {
      # translate `global_id` to an object or object ID
    }
  end
end
```

Now you can use `global_id_argument` the same way you would use `argument`:

```ruby
Types::PostType = GraphQL::ObjectType.define do
  ...
  field :author, Types::AuthorType do
    global_id_argument :id
    resolve -> (_, args, _) {
      # use translated global ID in args[:id]
    }
  end
  ...
end
```

@rmosolgo We've been using `prepare` for this exact purpose at theScore. Would it help if I added a similar example to the guides?

**Comment by cpunion** [comment]
@lucaspolonio Great! It works fine. Thanks.
