### ISSUE TITLE
Mutations don't accept 'property' nor other options for 'return_field'

### ISSUE THREAD

**Issue by pabloh** [rmosolgo/graphql-ruby#686]
Using options on mutations' return fields have not effect:
```ruby
LoginMutation = GraphQL::Relay::Mutation.define do
  name 'Login'
  input_field :username, !types.String, as: :user_name
  input_field :password, !types.String

  return_field :token, String
  return_field :expiration, String, property: :expires_in # :property is ignored
end
```

**Comment by rmosolgo** [comment]
Thanks for opening this issue! Maybe we can find a way to implement `return_field` to use the exact same codepath as `field`.

**Comment by pabloh** [comment]
I'm not sure what you meant by `codepath`.

As a stop gap I solved it by changing `Mutation::Result` to use method_missing, but I'm  not sure if is the best solution:

```ruby
class Result
  attr_reader :client_mutation_id
  def initialize(client_mutation_id:, result:)
    @client_mutation_id = client_mutation_id
    @result = result.symbolize_keys
  end

  def method_missing(name, *rest)
    rest.empty? ? @result[name.to_sym] : super
  end
  # ...
end
```

**Comment by rmosolgo** [comment]
I added a quick test for this in 5dada789, but it passes. Could you share your full stack trace of whatever error you get?

**Comment by pabloh** [comment]
@rmosolgo, I think is working because the alias is called `:faction`, like the previously defined field, try this instead it should fail: https://github.com/pabloh/graphql-ruby/commit/11ae6ad93925d1a7bcf36f816b1c1abe1316287f.

**Comment by rmosolgo** [comment]
Thanks, I see now! Fixing in https://github.com/rmosolgo/graphql-ruby/pull/692

**Comment by pabloh** [comment]
@rmosolgo thanks a lot!
