### ISSUE TITLE
Rails 5.1: Client getting error: Expected "#<ActionController::Parameters:xxx>" to be a key, value object  responding to `to_h`.

### ISSUE THREAD

**Issue by eljago** [rmosolgo/graphql-ruby#690]
Hello. I'm getting the following error when running a mutation from the client:

`Expected "#<ActionController::Parameters:0x007fac56b00e00>" to be a key, value object  responding to `to_h`.`

It' a react app that uses apollo-client 1.0.4, rails 5.1.0.rc2 on the server, and graphql-ruby 1.5.9

The input object sent with the mutation and the error generated by apollo:

![screen shot 2017-04-23 at 4 18 42 am](https://cloud.githubusercontent.com/assets/2080977/25311616/0b76ed3a-27dc-11e7-833b-84cb1ad4c796.png)

It works fine if I run the mutation using the graphiql utility though. 
Here's an example of the mutation copied from graphiql:

    mutation {
      EditGame(input: {
        game_id:1
        name:"potato"
        description:"description of potato"
        game_images_attributes:[
        	{
            id: 6, _destroy: false
          },
          {
            id: 7, _destroy: false
          }
        ]
      }) {
        clientMutationId
      }
    }

My definition of the InputObjectType:

    GameImageInputObjectType = GraphQL::InputObjectType.define do
        name "GameImageInput"
        input_field :id, types.ID
        input_field :name, types.String
        input_field :description, types.Boolean
        input_field :_destroy, types.Boolean
    end

I have another app using rails 5.0, and it works fine. So I guess the problem is related to 5.1 and ActionController::Parameters. 

![screen shot 2017-04-23 at 4 32 18 am](https://cloud.githubusercontent.com/assets/2080977/25311688/e53983ba-27dd-11e7-8a1a-2f5e934c4b58.png)

**Comment by rmosolgo** [comment]
Thanks for reporting this! I guess we have some work to do for 5.1 compatibility.

The workaround is to `permit!` your query variables on the server, for example:

```ruby 
variables = params[:variables]
variables.permit!
MySchema.execute(..., variables: variables)
```

This is safe because GraphQL will only use keys found in the query string and it will typecheck all values. 

I'll follow up soon with some compatibility fix for the library!

**Comment by eljago** [comment]
Thanks, that did it. I can't believe I didn't even check my graphql_controller.

I just needed to modify the **ensure_hash** method I copied from somewhere and do the permit! thing there.

Sorry about that

**Comment by rmosolgo** [comment]
(I'd like to keep this open as a reminder to address this somehow for Rails 5.1)
