### ISSUE TITLE
Allow to pass a anonymous block to arguments without a type definition

### ISSUE THREAD

**Issue by gottfrois** [rmosolgo/graphql-ruby#696]
Would be nice to be able to define an argument object type without explicitely having to create a type for it.

Consider the following example:

```ruby
Types::PostType = GraphQL::ObjectType.define do
  field :title, types.String
  field :published, types.Boolean
end

Types::PostFilterInputType = GraphQL::InputObjectType.define do
  argument :published, types.Boolean
end

field :posts, Types::PostType do
  argument :filter, Types::PostFilterInputType
end
```

Which makes the following query possible:

```
query {
  posts(filter: { published: true }) {
    title
    published
  }
}
```

Now, I run into some usecases where the `filter` definition is coupled to the field. For example I could allow to filter against `published` in this case but not in another case.

I'm thinking it would be easier to manage those filters if we could pass an anonymous block to the `argument`:

```ruby
field :posts, Types::PostType do
  argument :filter, GraphQL::InputObjectType do
    argument :published, types.Boolean
  end
end
```

What do you think?

**Comment by pabloh** [comment]
@gottfrois is an interesting suggestion but I think It would need to break the current API, since `argument` already can take a block: https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/argument.rb#L98.

Maybe you need to define your own `InputObjectType` as the argument's `type`.

**Comment by gottfrois** [comment]
@pabloh thanks for the quick response, that's a shame, what's the purpose of this block exactly?

**Comment by pabloh** [comment]
It's part of the graphql common DSL to be able to define properties using a block instead of plain ruby keyword arguments.
Anyway, you could probably handle this use case by defining an inline `InputObjectType` for your `:filter` argument's type.

**Comment by gottfrois** [comment]
@pabloh sounds promising, can you paste some code sample please? not sure how that would look like

**Comment by pabloh** [comment]
```
field :posts, Types::PostType do
  argument :filter, (GraphQL::InputObjectType.define do
    argument :published, types.Boolea
  end)
end
```

**Comment by pabloh** [comment]
@gottfrois, I think you should close this there's already a lot of other issues opened...
