### ISSUE TITLE
Addition of `as:` option for args broke camel-case middleware

### ISSUE THREAD

**Issue by bgentry** [rmosolgo/graphql-ruby#698]
I upgraded from v1.4.1 and found that my app was broken. This turned out to be due to the middleware I was using to auto-convert args from camelCase to underscore_case (derived from https://gist.github.com/colepatrickturner/cdb99df21c7e07b287e13ed2bf7972ab ). The break was introduced by #542, first released in v1.4.4. With that version, my args are now only accessible with the camelCase form.

Before this change:

```
[1] pry(#<GraphQL::Define::DefinedObjectProxy>)> args[:serial_number]
=> "6b8bbc2a"
[2] pry(#<GraphQL::Define::DefinedObjectProxy>)> args[:serialNumber]
=> nil
[3] pry(#<GraphQL::Define::DefinedObjectProxy>)> args
=> #<GraphQL::Query::Arguments:0x007ff021ce7368
 @argument_values=
  {"serial_number"=>
    #<GraphQL::Query::Arguments::ArgumentValue:0x007ff021ce6e40
     @definition=
      #<GraphQL::Argument:0x007ff022c26518
       @clean_type=#<GraphQL::NonNullType:0x3ff811613408>,
       @dirty_type=#<GraphQL::NonNullType:0x3ff811613408>,
       @name="serialNumber">,
     @key="serial_number",
     @value="6b8bbc2a">},
```

After:

```
[1] pry(#<GraphQL::Define::DefinedObjectProxy>)> args[:serial_number]
=> nil
[2] pry(#<GraphQL::Define::DefinedObjectProxy>)> args[:serialNumber]
=> "3cec0898"
[3] pry(#<GraphQL::Define::DefinedObjectProxy>)> args
=> #<GraphQL::Query::Arguments:0x007fec5d48bb28
 @argument_values=
  {"serialNumber"=>
    #<GraphQL::Query::Arguments::ArgumentValue:0x007fec5d48b998
     @definition=
      #<GraphQL::Argument:0x007fec56bbb850
       @as=nil,
       @clean_type=#<GraphQL::NonNullType:0x3ff62b5ddd54>,
       @dirty_type=#<GraphQL::NonNullType:0x3ff62b5ddd54>,
       @expose_as="serialNumber",
       @name="serialNumber">,
     @key="serialNumber",
     @value="3cec0898">},
 @original_values={"serial_number"=>"3cec0898"}>
```

I understand this may not be something you care to fix, but thought I'd at least post it here in case others run into the same issue.

**Comment by bgentry** [comment]
Seems like I can just go through and add an `as: :underscored_name` to every input that includes capital letter to get the same effect as the middleware?

**Comment by rmosolgo** [comment]
yes, that would do the job. I have to take a moment to think about it, but it might be possible to apply the `as:` value during field instrumentation. That way you wouldn't have to do any transformation at runtime. 

But keep an eye on #684, it's one current shortcoming of `as:`

**Comment by lucaspolonio** [comment]
Here's an instrumentation I use to camelize fields and argument names. Not sure if it's the best way to do it, but it considers `as:`.

```ruby
class FieldNameCamelizer
  def instrument(type, field)
    field.property = field.name.underscore.to_sym if field.resolve_proc.is_a?(GraphQL::Field::Resolve::NameResolve)
    field.name = field.name.camelize(:lower)

    field.arguments = Hash[
      field.arguments.map do |name, argument|
        argument.as = argument.name.underscore
        argument.name = argument.name.camelize(:lower)
        [argument.name, argument]
      end
    ]

    field
  end
end

```

**Comment by bgentry** [comment]
Even when switching everything to `as: :underscored_name`, I did have some more breakage. I was using `args.to_h` to access the args in my resolvers, but that uses the field's actual camel case name instead of its `as:` name, so the resulting hashes are in camel instead of underscore.

Gonna give @lucaspolonio's idea a try too.

**Comment by bgentry** [comment]
As far as the `.to_h` breakage, the method on [this line here](https://github.com/xuorig/graphql-ruby/blob/b0a750f996913b1e6439a82c744bed49f0e253b2/lib/graphql/query/arguments.rb#L37) uses the `original_values` rather than the `expose_as` keys when constructing the hash. In fairness the docs do say "Get the original Ruby hash", and it's easy enough to have my code deep underscore everything, so I'll just do that.

**Comment by emilebosch** [comment]
@bgentry i was also expecting that `to_h` would return the `expose_as`. @rmosolgo any reason why it returns the original hash and not the as hash? Would it be breaking to so if we would do incorporate this? I don't know what the other use for `:as` would be expect index picking all the values.

Especially with rails this is handy when you just do:

```graphql
createPost(post:{name:"hello", content:"hello) 
```
in resolvers
```ruby
resolve -> (o,a,c) -> {
  Post.create(a.to_h)
}
```

**Comment by emilebosch** [comment]
Nevermind i see that its alrady planned for 1.6 https://github.com/rmosolgo/graphql-ruby/issues/684

**Comment by rmosolgo** [comment]
Took a crack at it in #714 but I don't think it will be completely fixed. 

Arguments looks at the whole definition of the argument, but in the [middleware](https://gist.github.com/colepatrickturner/cdb99df21c7e07b287e13ed2bf7972ab#file-camel_case_argument_middleware-rb-L17), the previous (camelized) definition is used. This means it will still show as camelized. 

I suggest an approach like lucaspolonio suggested: https://github.com/rmosolgo/graphql-ruby/issues/698#issuecomment-297854800 because it updates the underlying definitions.

@bgentry Did you find something that works for you?

**Comment by rmosolgo** [comment]
Feel free to reopen this if that instrumentation doesn't work for you!
