### ISSUE TITLE
Input fields to mutations aren't validated.

### ISSUE THREAD

**Issue by chanks** [rmosolgo/graphql-ruby#70]
I have a mutation that looks like (simplified):

```ruby
LaunchCourseMutation = GraphQL::Relay::Mutation.define do
  name "LaunchCourse"

  input_field :course_id, !UUIDType
  input_field :launched, !types.Boolean

  return_field :user_course, UserContentType

  resolve -> (inputs, ctx) {
    user_course = UserCourse.find_or_new(course_id: inputs['course_id'], user: User.current)
    user_course.launched_at = (Time.now if inputs['launched'.freeze])
    user_course.save
    {user_course: user_course}
  }
end
```

If the client leaves out the 'launched' param, though, the resolve function is still called without a 'launched' key in the inputs, when the gem should probably be returning an error before getting that far.

**Comment by rmosolgo** [comment]
Hmm I guess it's failing to validate fields on input object, it _should_ be handled by this code:

https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/static_validation/literal_validator.rb#L15-L19

**Comment by chanks** [comment]
I don't know the gem well enough to say, but I can try to put together a self-contained reproduction if it helps.

**Comment by rmosolgo** [comment]
i wouldn't bother about a self-contained example, but could you share an example query which causes this bug?

**Comment by chanks** [comment]
Sure, the query looks like:

```
mutation ClientMutation {
  launch_course(input: {clientMutationId: "94d38775-6fbd-4c13-a7f7-0a848b9f0af6", course_id: "577d2ec3-85b0-4c7f-af54-ab1f4d9548cc"}) {
    clientMutationId,
    user_course {
      id,
      launched_at
    }
  }
}
```

**Comment by rmosolgo** [comment]
Ohh, I was checking that any _present_ inputs were valid, but not that all _required_ inputs were present. 

I think it's fixed by this: https://github.com/rmosolgo/graphql-ruby/commit/481668ebf1b4d3b72447074542ec6eb00b6a1a76

I've just pushed 0.10.5, could you give it a try and let me know if it's better for you?

**Comment by chanks** [comment]
Yep, that did it, thanks!
