### ISSUE TITLE
No built-in way to chain together multiple filters

### ISSUE THREAD

**Issue by bgentry** [rmosolgo/graphql-ruby#702]
Reposting from Slack:

> is there a built-in way to use multiple filters at once? previously I had a filter that disallowed mutations on `GET`, but now I also want to use filters for field visibility. Do I just write my own filter that calls multiple filters in sequence?

I ended up writing the following for myself:

```ruby
    class ChainedFilter
      attr_reader :filters

      def initialize(*filters)
        @filters = filters
      end

      def call(schema_member, ctx)
        filters.any? { |filter| filter.call(schema_member, ctx) }
      end
    end
```

Which lets me construct a filter chain like so:

```ruby
    filters = [
      AdminOnlyBlacklist.new(current_entity),
    ]
    filters.unshift(NoMutationMask.new) if request.method != "POST"
    GraphSchema.execute(query, except: ChainedFilter.new(*filters))
```

Opening this issue per @rmosolgo's request in case it's something that others might want :)

**Comment by rmosolgo** [comment]
Thanks! I think I want to add a `GraphQL::Filter` class that includes methods for combining functions this way, something like 

```ruby 
class GraphQL::Filter 
  def initialize(only:, except:)
    # normalize the check somehow
  end 
  
  # @return [Boolean] if `true`, `obj` either passed the `only:` check or didn't fail the `except:` check
  def pass?(obj, ctx)
  end 
  
  # @return [GraphQL::Filter] A new filter whose `#pass?` method reflects `self` _and_ the new param.
  def merge(only:, except:)
  end 
end

**Comment by rmosolgo** [comment]
Took a crack at it in #713, so that `only:` and `except:` now accept an array of callables. Would that do the trick?

**Comment by rmosolgo** [comment]
This'll be in be in 1.6.0 via #713
