### ISSUE TITLE
Docs: for array fields, explain why "!" is needed twice

### ISSUE THREAD

**Issue by kliuless** [rmosolgo/graphql-ruby#72]
It's not clear what the difference is between these two type definitions:
```ruby
type !types[types.String]  # no "!" for wrapped type
```
and
```ruby
type !types[!types.String]  # wrapped type has "!" also
```

The tests seem to only use the 2nd form, but the first seems to work. Is there a difference?

**Comment by rmosolgo** [comment]
How's this for a start? http://facebook.github.io/graphql/#sec-Combining-List-and-Non-Null

**Comment by kliuless** [comment]
That makes sense.
It doesn't seem like the not-null is enforced though:
```ruby
      field :testArray do
        type types[!types.Int]
        resolve ->(_, args, ctx) do
          [nil]
        end
      end
```
Actually returns `[ null ]` instead of failing.

I was curious and then tried a scalar, and the same thing happens:
```ruby
      field :testScalar do
        type !types.Int
        resolve ->(_, args, ctx) { nil }
      end
```

Is non-null unenforced for result values?

I know it's enforced for *arguments*, because I get an error ("...is missing required arguments...")

**Comment by rmosolgo** [comment]
I never implemented that behavior! I wonder if graphql-js doesi t. 

I figured the type system was really for telling the client, "here's what you can expect from this field", not for runtime checks on `resolve` functions. 

If you wanted to add it, you could add it to field resolution ([here?](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/query/serial_execution/field_resolution.rb#L46-L53)), or you might even be able to make a middleware that performs the validation, eg:

```ruby 
class ReturnValueValidationMiddleware
  def call(parent_type, parent_object, field_definition, field_args, query_context, next_middleware)
    return_value = next_middleware.call 
    if !valid_return_value?(field_definition, return_value)
      raise("Invalid return #{return_value} for #{field_definition.name}")
    else 
      return_value 
    end
  end

  private 
  
  def valid_return_value?(field_defn, value) 
    # ... 
   end
end

# ... 

MySchema.middleware << ReturnValueValidationMiddleware.new
```

I think the logic would be quite similar to validating query variables ([here](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/query/variables.rb#L30-L41)).


This would be easy for scalars, lists & non-nulls, but `ObjectType`s are a bit harder. If you get an object, how do you know if it's a valid value for a given `ObjectType`? (maybe you just skip in that case)

**Comment by kliuless** [comment]
Thanks for the info. I think it's fine for the gem not to validate results; it was just my intuition that thought it was happening.
Would be good to mention in the docs if it's not already there.

**Comment by rmosolgo** [comment]
Non-null should result in an error after #94
