### ISSUE TITLE
Can metadata information be included in the introspection query?

### ISSUE THREAD

**Issue by gjtorikian** [rmosolgo/graphql-ruby#733]
I admit I haven't looked into the spec or the code much, but: one can define [metadata definitions](https://github.com/rmosolgo/graphql-ruby/blob/45a5a0f0be359060897b39f127bf4c09b41b5720/lib/graphql/define.rb) for new properties on GraphQL items. Could this be exposed in the introspection query? 

I think it'd be neat for tooling _cough_ https://github.com/gjtorikian/graphql-docs _cough_ to be able to represent this information. I am not sure if the use case is so narrow that it doesn't apply, and that's fine. I just want to open a discussion to see if it makes sense.

**Comment by rmosolgo** [comment]
The spec makes no mention of extending the introspection types: https://facebook.github.io/graphql/#sec-Schema-Introspection

I'm open to _supporting_ extending those types, but I don't have much of an idea how to do it. 

One way to do it might be, when IDL-to-Schema support is better ( #727 ), is to allow overrides of the built-in introspection types in the IDL, then use user-provided behaviors to resolve them.

**Comment by rmosolgo** [comment]
I'm trying to support this in 1.8 via https://github.com/rmosolgo/graphql-ruby/pull/1170, does that look like it would do the job?

**Comment by gjtorikian** [comment]
I'm not sure. It seems that the community is still deciding on what a metadata format should look like  (https://github.com/facebook/graphql/issues/300) so jumping ahead and defining a format for that might not be the best. As @xuorig mentioned in another thread:

> Given that no 3rd party tools can use this information right now since it breaks the spec, it almost seems like the only users would be ourselves.

**Comment by rmosolgo** [comment]
This is possible in GraphQL-Ruby now, we can track spec changes on the above-mentioned issue
