### ISSUE TITLE
Broken link in doc

### ISSUE THREAD

**Issue by timscott** [rmosolgo/graphql-ruby#748]
This page:

http://graphql-ruby.org/schema/limiting_visibility.html

Has a link "types and fields guide" that goes here:

http://graphql-ruby.org/schema/types_and_fields

Which is 404.

Maybe it should go here?

http://graphql-ruby.org/schema/extending_the_dsl.html

**Comment by rmosolgo** [comment]
Thanks for reporting this! Yes, I think you're right. I passed it through [HTML Proofer](https://github.com/gjtorikian/html-proofer) and fixed this issue and several others in 11315a84.
