### ISSUE TITLE
rescue_from method does not accept arrays

### ISSUE THREAD

**Issue by littlelazer** [rmosolgo/graphql-ruby#757]
Right now the rescue middleware only handles a single error class at a time. Sometimes it might be useful to accept an array of error classes that will all be handled in the same way. It's something I've run into a couple times. Is there any interest in a pull request adding that capability?

**Comment by rmosolgo** [comment]
Hi! Thanks for the suggestion, I agree that would be nice. 

How about accepting a splat, so that you can pass any number of error classes, but without the `[...]`? 

For example: 

```ruby 
# one 
rescue_from FirstError { ... }
# or several 
rescue_from SecondError, ThirdError, FourthError { ... }
```

**Comment by littlelazer** [comment]
Sounds good to me. I'll send a PR
