### ISSUE TITLE
How to optimize Relay connection's queries to the DB?

### ISSUE THREAD

**Issue by Defman21** [rmosolgo/graphql-ruby#759]
The docs says that I should not limit the returned collection. But in a case when you have a lot items in the database (e.g. a company with 20k employees), executing such a query could be a hard task for the database without applying any limits to the query (for example, MySQL stops selecting from the DB once the length of the data equals to the limit, so `SELECT * FROM employees WHERE company_id = 1 LIMIT 100` will select 100 items, not 20k and then return only 100 from the set). 
I don't think that adding an argument (e.g. `limit`) would be a good approach because it conflicts with the `first` (or `last`) argument.
So, is there a way to optimize these queries? I have `max_page_size` for the connection field but I can't access it in the resolve function.

**Comment by Willianvdv** [comment]
@Defman21 Your resolver can return the full connection when you're using Relay's connection type. The type itself does the pagination. 

Since the client can request any number of objects, it's wise to set the max_page_size to prevent an overload on your database.

**Comment by Defman21** [comment]
This is still doing a heavy query. Load 20k items, splice and paginate them and return the result..

**Comment by Willianvdv** [comment]
Right, you're not returning an `ActiveRecord::Relation` or `Sequel::Dataset`? If so, the connection resolver will fallback to an [ArrayConnection](https://github.com/rmosolgo/graphql-ruby/blob/df83ff81f11a133e17ac779302974038fdb60692/lib/graphql/relay/array_connection.rb). AFAIK, you've to implement a [custom connection](https://github.com/rmosolgo/graphql-ruby/blob/81aee3aaf4c8213f5e7101ee08f79aea3bab6e91/guides/relay/connections.md#custom-connections) that queries the database efficient.

**Comment by Defman21** [comment]
Gotcha, thanks :)
