### ISSUE TITLE
`rails g graphql:mutation` doesn't add all boilerplate for mutations

### ISSUE THREAD

**Issue by ThisIsMissEm** [rmosolgo/graphql-ruby#769]
Say you do:

```
rails g graphql:mutation createAccount
```

Then you have a few bits of extra work to do, from the result:

1) You have to fix the module name in `app/graphql/mutations/createAccount.rb` from `Mutations::createAccount` to `Mutations::CreateAccount`
2) You have to add the mutation root, which requires creating:

```
Types::MutationType = GraphQL::ObjectType.define do
  name "Mutation"

  field :createAccount, Mutations::CreateAccount.field
end
```

3) You have to add `mutation(Types::MutationType)` to the `Schema` file in `app/graphql/`

Whilst adding the `field :createAccount` in isn't strictly necessary, it is nice to do, considering that the `GraphQL::Relay::Mutation.define` returns an object that isn't like `GraphQL::ObjectType.define`

I'm not sure about the camelCasing issue in 1) though, I suspect that's just a bug and easily fixed.

Would be happy to do a pull request if these are changes the community would find helpful.

**Comment by rmosolgo** [comment]
:+1: for all the changes you recommend here!

**Comment by esjee** [comment]
Was all of this fixed in https://github.com/rmosolgo/graphql-ruby/pull/821?

**Comment by rmosolgo** [comment]
Yes, thanks for following up!
