### ISSUE TITLE
Guide: Introduction

### ISSUE THREAD

**Issue by timscott** [rmosolgo/graphql-ruby#771]
http://graphql-ruby.org/fields/limits.html

Perhaps it's more idiomatic to regulate the max limit in the `prepare` function of the argument instead of the resolve body?

**Comment by rmosolgo** [comment]
That's a great idea! This guide precedes `prepare:` and never got an update 😬

**Comment by timscott** [comment]
By the way, thank you for this awesome gem. I learned GraphQL last year with a NodeJS app, and am loving the programmer happiness of GraphQL + ruby!!!

**Comment by Willianvdv** [comment]
Hey @timscott, could you try to update this guide? I don't want to steal your internet points by PR-ing this myself :)

**Comment by timscott** [comment]
@Willianvdv, Did it. https://github.com/rmosolgo/graphql-ruby/pull/797

**Comment by Willianvdv** [comment]
@timscott Thanks!
