### ISSUE TITLE
max_per_page / default_max_page_size acting strange

### ISSUE THREAD

**Issue by mbajur** [rmosolgo/graphql-ruby#778]
Hello,

i have a trouble using relay pagination inside my graphql-powered app. App is pretty basic, all the source code of my graph is available here: https://github.com/hcxp/hcxp/tree/master/app/graphql

I have two issues that might be related but i'm not really sure about that:

1) Setting `max_per_page` or `default_max_page_size` is nto chainging the actual SQL query to the DB. I can clearly see in the logs that there is no any limit/offset added to the SQL query. So graph is returning all the records from the database - which is obviously a really bad thing.

2) (that's really weird one) on production, running a query without `after` argument returns a set of records and `pageInfo.hasNextPage` returns `false`. However, after setting `after` argument to `pageInfo.endCursor`, i can see that my graphql endpoint returns next set of results - which makes me think that pagination actually works (depsite of what i've written in point 1) but pageInfo is returning not-real `hasNextPage` and `hasPreviousPage`.

You can test that on your own here: https://hcxp.co/graphiql (sample queries to try are listed here: https://gist.github.com/mbajur/2638bf05081fdd084572a7528f2c1263)

I'm not sure if that's some kind of a bug or i'm misunderstanding something but thanks in advance for any clues!

PS. I'm on graphql 1.6.3

**Comment by rmosolgo** [comment]
Hi, sorry about that! Thanks for providing those links. I took a look. 

GraphiQL looks like it's working to me. I requested the first set of bands, and I got 25 entries. I pasted it into the Chrome console to make sure:

![image](https://user-images.githubusercontent.com/2231765/27055423-6d08beb0-4f92-11e7-968f-a6abc6cedbaa.png)

The pagination you're describing is according to the Relay specification: https://facebook.github.io/relay/graphql/connections.htm#sec-undefined.PageInfo.Fields

It's a bit unexpected though, isn't it! I'm thinking about adding an option to go beyond the spec for those fields.

**Comment by mbajur** [comment]
Oh! Now it makes sense

> `hasPreviousPage` will be false if the client is not paginating with `last`

so that was just me not reading the docs properly :) Anyway - i like the approach github did in this matter. They are forcing user to actually use the `first` argument, this way such scenario is not occuring. I know that's not a scope of that thread but it's probably such a small question that it's not even worth opening a new issue - is that possible to force/validate pagination arguments in graphql-ruby? or do i need to imlement that on my own? :)

Thanks for fast and handy reply, that's a second time i'm opening an issue here and you guys are always replying super fast and on point, that's awesome.
