### ISSUE TITLE
Testing with rspec

### ISSUE THREAD

**Issue by heri** [rmosolgo/graphql-ruby#78]
Hi
This is a big component in a new app I'm working on. How do you write tests with graphql-ruby? I haven't found any examples. I'm interested in testing queries, fragments and user authentification
Thank you

**Comment by rmosolgo** [comment]
Good question! I've added a guide with some strategies that have worked for me so far:

http://www.rubydoc.info/github/rmosolgo/graphql-ruby/file/guides/testing.md

How is that?

**Comment by heri** [comment]
Makes a lot of sense, esp. the end-to-end testing. 

I'll do extensive testing and see if I can write a quick blog post with examples (I searched on Google previously and didn't see anyone discussing this)

Thanks!

**Comment by rmosolgo** [comment]
That would be great, please let us know how it goes!

**Comment by onpaws** [comment]
@heri did you manage to publish a blog post?
trying to create a basic smoke test for my app and would quite helpful seeing an example.

**Comment by Dbz** [comment]
The guide link posted above is dead

**Comment by rmosolgo** [comment]
Here's a new link: http://graphql-ruby.org/schema/testing.html

**Comment by Dbz** [comment]
Thank you. The examples on that link are a bit different from the [how to graphql](https://github.com/howtographql/howtographql/blob/8614026b99e38dbf0a73aaecefd1f703efbedddf/content/backend/graphql-ruby/3-mutations.md#testing-with-unit-test) example in mutations. Do you have any thoughts on that?
