### ISSUE TITLE
Defining custom JSON input field

### ISSUE THREAD

**Issue by acadavid** [rmosolgo/graphql-ruby#780]
Using `graphql-ruby v1.6.3`

I'm trying to define my own JSON scalar type based on the example in #146. 

```ruby
MutationRoot = GraphQL::ObjectType.define do
  name "Mutation"

  field :updateClientConfig, ClientConfigType do
    description "Updates a client config"

    argument :code, types.String
    argument :settings do
      type JsonStringType
    end
  end
end

JsonStringType = GraphQL::ScalarType.define do
  name "JsonStringType"

  coerce_input -> (val, ctx) { JSON.parse(val) }
end
```

The query i'm running looks like this:

```graphql
mutation { updateClientConfig(code: "test1",  settings: {a: "a"})
  {
    active
  }
} 
```

But I keep getting:

```ruby
CondorSchema.execute(params[:query])
{"errors"=>[{"message"=>"Argument 'settings' on Field 'updateClientConfig' has an invalid value. Expected type 'JsonStringType'.", "locations"=>[{"line"=>1, "column"=>12}], "fields"=>["mutation", "updateClientConfig", "settings"]}]}
```

I've also tried disabling the validations(`CondorSchema.execute(params[:query], variables: params[:variables], validate: false)`) and using `GraphQL::Relay::Mutation.define` instead but run into the same issue.

I'm unsure how exactly is the validation done since it doesn't seem to be reaching the `coerce_input` lambda. Any ideas what could be going on? Am I missing something?

Thanks!

**Comment by rmosolgo** [comment]
You need to pass `settings` as a string, try this: 

```graphql
mutation { updateClientConfig(code: "test1",  settings: "{a: \"a\"}")
  {
    active
  }
} 
```

Does that work for you?

**Comment by acadavid** [comment]
I swear I tried this before and it didn't work, I'm sure I was messing it up somewhere else, and by reorganizing the code to fill in the ticket I think I fixed whatever other problem I was having. Thanks a lot, this indeed solves the problem! Sorry about that!

**Comment by rmosolgo** [comment]
Glad it's working!!
