### ISSUE TITLE
How to create object of service class inside resolve method for mutations?

### ISSUE THREAD

**Issue by dkumar431** [rmosolgo/graphql-ruby#784]
I have few service defined in my application. From Graphql mutations I want to create the object of those service class . Here is a code snippet,

```ruby
NewTranslationRequest = GraphQL::Relay::Mutation.define do
      name "CreateTranslation"
      input_field :release_id, !types.ID
      input_field :locale, !types.String

      return_field :translationrequest, TranslationRequestType
      return_field :errors, types.String

      resolve ->(object, inputs, ctx) {
        translation_request = CreateTranslationRequest.new("fr",24).perform
        { translationrequest: translation_request }
       }
end
```

But the `CreateTranslationRequest` is a service class present inside `app/services`. But the above code throws error saying, `undefined method `new' for #<GraphQL::Relay::Mutation:0x007fd1227d5370>` 

I think it is not able to load my service classes. I am following the below blog which says should use service objects inside graphql
https://medium.com/@DrawandCode/building-a-graphql-api-in-rails-part-3-best-practice-8e4a655463d4

**Comment by Willianvdv** [comment]
I'm not sure this solves anything, but in the return hash of the resolver you have to return the transaction_request instance instead of the type.

So:
```
{ translationrequest: TranslationRequestType }
```

Becomes:
```
{ translationrequest: translation_request }
```

**Comment by dkumar431** [comment]
@Willianvdv 
That was just a typing mistake.

**Comment by Willianvdv** [comment]
Ok, from the original exception it looks like something is returning the wrong thing. I don't think it's related to your code snippet or some service/class that can't be found. However, I could be wrong.  It would help if you share a bit more of the exception, the stack trace for example.

**Comment by dkumar431** [comment]
`
F, [2017-06-14T15:45:31.225823 #9727] FATAL -- : 
NoMethodError - undefined method `new' for #<GraphQL::Relay::Mutation:0x007fa9547182e8>:
  app/graphql/mutations/mutation_type.rb:124:in `block (2 levels) in <module:TranslationRequestMutation>'
  graphql (1.4.5) lib/graphql/relay/mutation.rb:190:in `call'
  graphql (1.4.5) lib/graphql/field.rb:196:in `resolve'
  graphql (1.4.5) lib/graphql/define/instance_definable.rb:179:in `block (3 levels) in ensure_defined'
  graphql (1.4.5) lib/graphql/execution/execute.rb:212:in `call'
  graphql (1.4.5) lib/graphql/schema/middleware_chain.rb:45:in `invoke_core'
  graphql (1.4.5) lib/graphql/schema/middleware_chain.rb:38:in `invoke'
  graphql (1.4.5) lib/graphql/execution/execute.rb:68:in `resolve_field'
  graphql (1.4.5) lib/graphql/execution/execute.rb:31:in `block in resolve_selection'
  graphql (1.4.5) lib/graphql/internal_representation/selection.rb:41:in `block in each_selection'
  graphql (1.4.5) lib/graphql/internal_representation/selection.rb:38:in `each_selection'
  graphql (1.4.5) lib/graphql/execution/execute.rb:29:in `resolve_selection'
  graphql (1.4.5) lib/graphql/execution/execute.rb:9:in `execute'
  graphql (1.4.5) lib/graphql/query/executor.rb:37:in `execute'
  graphql (1.4.5) lib/graphql/query/executor.rb:18:in `result'
  graphql (1.4.5) lib/graphql/query.rb:119:in `result'
  graphql (1.4.5) lib/graphql/schema.rb:184:in `execute'
  app/controllers/graphql_controller.rb:11:in `create'
`

**Comment by rmosolgo** [comment]
Is it possible that there are _two_ constants called `CreateTranslationRequest` ? 

For example, maybe one is: 

```ruby 
# app/services/create_translation_request.rb
class CreateTranslationRequest # ... 
```

and the other is a mutation: 

```ruby 
CreateTranslationRequest = GraphQL::Relay::Mutation.define do # ... 
```

Is that possible here? 

If so, try renaming the mutation: 

```ruby 
CreateTranslationRequestMutation = GraphQL::Relay::Mutation.define do # ... 
```

This will resolve the naming conflict between those to objects.

**Comment by dkumar431** [comment]
@rmosolgo 
Already figured out the same. Thanks for your help. 👍

**Comment by rmosolgo** [comment]
Glad to hear it!
