### ISSUE TITLE
How to use constant inside Type system?

### ISSUE THREAD

**Issue by eshaiju** [rmosolgo/graphql-ruby#785]
I am trying to set a default value to an argument like this
`argument :country, types.String, default_value: SupportedCountry::DEFAULT`

but got an error. How to use a constant defined in a class? 

NameError - uninitialized constant Types::SupportedCountry:
  activesupport (4.2.6) lib/active_support/dependencies.rb:533:in `load_missing_constant'
  activesupport (4.2.6) lib/active_support/dependencies.rb:184:in `const_missing'
  app/graph/query.rb:75:in `block (2 levels) in <module:Types>'
  graphql (1.5.13) lib/graphql/define/instance_definable.rb:161:in `ensure_defined'
  graphql (1.5.13) lib/graphql/define/instance_definable.rb:204:in `block (3 levels) in stash_dependent_methods'
  graphql (1.5.13) lib/graphql/schema/validation.rb:29:in `block in assert_property'
  graphql (1.5.13) lib/graphql/schema/validation.rb:19:in `block in validate'
  graphql (1.5.13) lib/graphql/schema/validation.rb:19:in `validate'
  graphql (1.5.13) lib/graphql/schema/validation.rb:79:in `block (2 levels) in assert_named_items_are_valid'
  graphql (1.5.13) lib/graphql/schema/validation.rb:78:in `block in assert_named_items_are_valid'
  graphql (1.5.13) lib/graphql/schema/validation.rb:19:in `block in validate'
  graphql (1.5.13) lib/graphql/schema/validation.rb:19:in `validate'
  graphql (1.5.13) lib/graphql/schema/reduce_types.rb:62:in `validate_type'
  graphql (1.5.13) lib/graphql/schema/reduce_types.rb:29:in `reduce_type'
  graphql (1.5.13) lib/graphql/schema/reduce_types.rb:10:in `block in reduce'

**Comment by rmosolgo** [comment]
Hmmm, interesting! Can you tell me about `SupportedCountry`? 

- Where is it defined? (What is the file path?)
- What kind of constant is it? (Class, module, something else?)

Also, a quick thing to try is add `::` prefix: 

```ruby
argument :country, types.String, default_value: ::SupportedCountry::DEFAULT
#                                               ^ here
```

This tells Ruby to always use the _top-level_ constant `SupportedCountry` and never look for a nested constant like `Types::SupportedCountry`.

**Comment by eshaiju** [comment]
SupportedCountry is in model 

class SupportedCountry
  DEFAULT = 'United States of America'.freeze
end
tried ::SupportedCountry::DEFAULT but got error like    **NameError - uninitialized constant SupportedCountry:**

**Comment by rmosolgo** [comment]
What's the filepath of the code you posted above?

**Comment by eshaiju** [comment]
this is a root query.
path app/graph/query.rb
```module Types
  QueryType = GraphQL::ObjectType.define do
    name 'Query'
    description 'The query root of this schema'

    field :locations, types[AuctionLocationType] do
      argument :country, types.String, default_value: 'United States of America'.freeze
      resolve lambda { |obj, args, ctx|
      }
    end
  end
end

**Comment by rmosolgo** [comment]
This code:

```
class SupportedCountry
  DEFAULT = 'United States of America'.freeze
end
```

What file is it in?

**Comment by eshaiju** [comment]
file path  : app/models/supported_country.rb

**Comment by Willianvdv** [comment]
@eshaiju still have this issue? It looks like something funky going on with your setup. Any chance you can share it, so we can take a look?

**Comment by Willianvdv** [comment]
@eshaiju feel free to reopen if you still have this issue!

**Comment by eshaiju** [comment]
@Willianvdv This working in my other sample application. so something related to the other project setup. thanks
