### ISSUE TITLE
Int isn't a defined input type (on $first)

### ISSUE THREAD

**Issue by eploko** [rmosolgo/graphql-ruby#788]
I’ve got a question I can’t seemingly resolve on my own.

Together with basic Query, Mutation and so on types I’ve made the following type definition:

```ruby
module Types
  UserType = GraphQL::ObjectType.define do
    name 'User'
    description 'A user'
    
    implements GraphQL::Relay::Node.interface
    global_id_field :id
    
    field :email, !types.String, 'Email address'
    
    connection :docs, DocType.connection_type, 'Available docs'
  end  
end
```

And I then try to query it with:

```graphql
query FileListQuery(
  $after: String
  $first: Int
) {
  viewer {
    currentUser {
      docs(first: $first, after: $after) {
        edges {
          node {
            id
            name
            __typename
          }
          cursor
        }
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
        }
      }
      id
    }
    id
  }
}
```

And I pass the following as query variables:

```json
{
  "first": 1,
  "after": null
}
```

The problem is it bails out with the following:

```json
{
  "errors": [
    {
      "message": "Int isn't a defined input type (on $first)",
      "locations": [
        {
          "line": 3,
          "column": 3
        }
      ],
      "fields": [
        "query FileListQuery"
      ]
    }
  ]
}
```

I honestly have no clue why it complains about the Int type…

If I get rid of the problematic `$first` query variable in the request, it works fine.

This:

```graphql
query FileListQuery(
  $after: String
) {
  viewer {
    currentUser {
      docs(first: 10, after: $after) {
        edges {
          node {
            id
            name
            __typename
          }
          cursor
        }
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
        }
      }
      id
    }
    id
  }
}
```

Produces this:

```json
{
  "data": {
    "viewer": {
      "currentUser": {
        "docs": {
          "edges": [
            {
              "node": {
                "id": "1",
                "name": "First Doc",
                "__typename": "Doc"
              },
              "cursor": "MQ=="
            }
          ],
          "pageInfo": {
            "endCursor": "MQ==",
            "hasNextPage": false,
            "hasPreviousPage": false,
            "startCursor": "MQ=="
          }
        },
        "id": "1"
      },
      "id": "VIEWER"
    }
  }
}
```

Any hints, ideas on how to fix this? I use the graphql gem v1.6.3.

**Comment by rmosolgo** [comment]
Oh my! What a pain, sorry about that :S 

The schema assembles itself by traversing the types & fields defined by Ruby code. I wonder if it's somehow _failing_ to find `Int` anywhere in those Ruby objects! It definitely _should_ be there, since `DocType.connection_type`'s `first` argument is `Int` type. 

I wonder if graphql-ruby has a bug where argument types aren't merged into the schema...

The first thing you could try is to _force_ `Int` to be included in your schema. Add a field like this to your `Query` type:

```ruby 
# Make sure Int is included in the schema:
field :testInt, types.Int
```

Then run your query again. Does that work? 

If it doesn't work, could you share a dump of your schema? You can generate one like this:

```ruby
# $ rails console
schema_dump = MySchema.to_definition
File.write("schema_dump.graphql", schema_dump)
```

If you don't want to share the whole thing, you could filter the lines including `Int`:

```
$ cat schema_dump.graphql | grep Int
```

That would show where `Int` is present in the schema, and maybe give us a clue why it isn't working here!

**Comment by eploko** [comment]
@rmosolgo, adding the `testInt` field definitely helps. The query runs fine afterwards.

**Comment by rmosolgo** [comment]
Glad to hear that works! 

Sorry, this is a bug in graphql-ruby 😬 . The work-around for now is to have a field _somewhere_ in the schema that returns `Int` . I'll hunt for a proper solution soon!

**Comment by eploko** [comment]
Thanks a ton for the quick head up. I wish I could provide a PR to fix this, but I'm afraid it's a bit more complicated than I'd like it to be. Thumbs up for the help anyway. 👍 :)
