### ISSUE TITLE
Only way to override introspection types is to reassign constants

### ISSUE THREAD

**Issue by minasmart** [rmosolgo/graphql-ruby#793]
I needed to add some fields to the `__Field` introspection type. The only way to do this was to reassign `GraphQL::Introspection::FieldType`, which is triggers a warning since it's a constant reassignment.

The only way to really do it in a clean way is like this:

```ruby
GraphQLIntrospectionFieldType = GraphQL::Introspection::FieldType
GraphQL::Introspection.send(:remove_const, :FieldType)
GraphQL::Introspection::FieldType = GraphQLIntrospectionFieldType.redefine do ... end
```

It'd be great if you could optionally specify the introspection types on construction of a schema.

**Comment by rmosolgo** [comment]
:+1: sounds along the same lines as https://github.com/rmosolgo/graphql-ruby/issues/733

I wonder what's the best way to support this ... d'ya mind my asking, what kind of things did you need to add to the introspection types?

**Comment by minasmart** [comment]
This is actually connected to #791. Since directives on fields aren't introspectable, I followed the pattern that `@deprecated` uses and added a `isAccessRestricted` field, and an `accessRestrictedReason` field,  so that things that know to ask for this information, can parse it. In my case, we're using it for docs generation.

**Comment by minasmart** [comment]
If it helps, this is what the redefinition is adding:
```ruby
GraphQL::Introspection::FieldType = GraphQLIntrospectionFieldType.redefine do
  field :isAccessRestricted, !types.Boolean do
    resolve ->(obj, _arguments, _ctx) { !!obj.metadata[:access_restricted] }
  end
  field :accessRestrictedReason, types.String do
    resolve ->(obj, _arguments, _ctx) { obj.metadata[:access_restricted] }
  end
end
```

**Comment by rmosolgo** [comment]
I'm trying to support this in 1.8 via https://github.com/rmosolgo/graphql-ruby/pull/1170, does that look like it would do the job?

**Comment by rmosolgo** [comment]
Here's the docs for the new base classes: https://github.com/rmosolgo/graphql-ruby/blob/698fda2e50b0844fecb7a35991c1afbf10e31c3b/guides/schema/class_based_api.md#custom-introspection

please open an issue if it doesn't work out!
