### ISSUE TITLE
Graphql sees variables as nulls

### ISSUE THREAD

**Issue by mbajur** [rmosolgo/graphql-ruby#796]
I've been using graphql-ruby in several projects now and never encountered such weird issue. Here is a basic **working** query:

```
query {
  user(id:1) {
    id
  }
}
```

That works perfectly fine. Variables are passed to the resolver, user is found - just perfect. However, when i'm trying to use named queries, variables are getting lost somewhere on the way to the resolver.

```
query FindUser($id:ID!) {
  user(id:$id) {
    id firstname
  }
}

# and variables:

{
  "id": 1
}
```

Graphql error says that "Variable id of type ID! was provided invalid value / Expected value to not be null". My graphql configuration is as follows: https://gist.github.com/mbajur/5ecda24a9ba34b00569afdfea7538c74

I have added a comment line in each place i was able to debug what are currently detectable arguments. These lines are prefixed with `DEBUG:`. First place i can actually see variables are present is in the controller. Next place is a resolver in UserField and variables are not there.

Have you guys any idea what's going on in here? I have literally wrote exact the same code in like 5 other projects and never had such weird issue. My graphql-ruby version is 1.6.3 / ruby 2.3.3

Thanks in advance!

**Comment by rmosolgo** [comment]
Weird!! 

what if we debug the controller: 

```ruby 
query_variables["id"] # => ??
```

What do you get there? (Variables are always expressed as strings, never with symbols. Previous Rubies don't GC symbols so that could be a DOS attack vector 😉 )

**Comment by mbajur** [comment]
Ha! yes, that was it :) Adding 

```
query_variables = query_variables.inject({}){|memo,(k,v)| memo[k.to_s] = v; memo}
```

line to my controller (to stringify the keys) fixed it for me. Btw - you think that would be a good idea to share that _discovery_ with Hanami guys or is that rather on developer side to take care of stringifying the keys?

**Comment by rmosolgo** [comment]
It looks like hanami-controller only supports Ruby 2.3+: 

https://github.com/hanami/controller/blob/master/hanami-controller.gemspec#L20

For them, using symbols is OK. I think this is just a graphql-ruby + hanami issue! I will keep it in mind and if someone else raises the question, I'll find a place to document this requirement. 

In the meantime, it looks like hanami-utils includes a helper for this case: http://www.rubydoc.info/gems/hanami-utils/Hanami/Utils/Hash#stringify!-instance_method

**Comment by mbajur** [comment]
Woah, great! Thanks so much <3
