### ISSUE TITLE
ExecutionError raised in argument's prepare function doesn't work with GraphQL::Batch

### ISSUE THREAD

**Issue by cmatheson** [rmosolgo/graphql-ruby#798]
When an object is loaded with a `GraphQL::Batch::Loader`, errors returned by a field argument for that object are not handled properly.  I've included a minimal test case for the following schema:

```
type Query {                 
  user(_id: ID!, async: Boolean): User    
}                            

type User {                  
  name(someArg: ID): String  
}
```
The full code sample (requires graphql-ruby and graphql-batch) is here (things to note are that the `someArg`'s prepare function just returns an error, and that the user resolve function will either directly return an object or return one via GraphQL::Batch::Loader depending on the async argument for that field)

```ruby
class DummyUser
  attr_reader :name

  def initialize(name)
    @name = name
  end
end

class UserLoader < GraphQL::Batch::Loader
  def initialize(_)
  end

  def perform(ids)
    ids.each do |id|
      fulfill(id, DummyUser.new("async loaded user"))
    end
  end
end

UserType = GraphQL::ObjectType.define do
  name "User"

  field :name, types.String do
    argument :someArg, types.ID,
      prepare: ->(s, _) { GraphQL::ExecutionError.new("uh oh") }
    resolve ->(user, args, _) {
      user.name
    }
  end
end

QueryType = GraphQL::ObjectType.define do
  name "Query"

  field :user, UserType do
    argument :_id, !types.ID
    argument :async, types.Boolean
    resolve ->(_, args, ctx) {
      # everything works as expected unless you use the +UserLoader+
      # (GraphQL::Batch) class
      args[:async] ?
        UserLoader.new(:asdf).load(args[:_id]) :
        DummyUser.new("test user")
    }
  end
end

TestSchema = GraphQL::Schema.define do
  query(QueryType)

  lazy_resolve(Promise, :sync)
  instrument(:query, GraphQL::Batch::Setup)
end
```
querying `{ user(_id: "5") { name } }` returns `{"data"=>{"u1"=>{"name"=>"test user"}}}` as expected.

querying `{ user(_id: "5") { name(someArg: "whatever") } }` returns `{"data"=>{}, "errors"=>[{"message"=>"uh oh", "locations"=>[{"line"=>1, "column"=>23}]}]}` (also expected).

querying `{ user(_id: "5", async: true) { name(someArg: "whatever") } }` returns `{"data"=>{"user"=>#<GraphQL::ExecutionError: uh oh>}}` (the execution error has somehow made its way into the data field instead of "errors".

**Comment by Willianvdv** [comment]
@cmatheson can you verify #801 solves your problem?

**Comment by cmatheson** [comment]
Hey @Willianvdv, it looks like that is maybe solving a different case than what I am experiencing.  I am hitting https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/query/literal_input.rb#L62, so the error is checked for and handled.  It seems like the error handlying in lazy.rb is the problem, see: https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/execution/lazy.rb#L36.  It just returns the error instead of adding an error to the query context and returning {} like the non-lazy case: https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/execution/multiplex.rb#L99
