### ISSUE TITLE
Better arguments and inputs validation

### ISSUE THREAD

**Issue by gustavovnicius** [rmosolgo/graphql-ruby#799]
It would be good to have something similar to how `grape` validates and coerce parameters: https://github.com/ruby-grape/grape#parameter-validation-and-coercion
Things like: `mutually_exclusive`, `exactly_one_of`, and custom validators

**Comment by rmosolgo** [comment]
Thanks for the suggestion! Best of all would be to implement these via query analyzers, so you can run validation _before_ starting to execute the query.

**Comment by modosc** [comment]
@rmosolgo do you have an example of accessing parameters inside of a `QueryAnalyzer`? i can find the giant params object but i can't figure out how to go from a given `irep_node` to the supplied value.

**Comment by modosc** [comment]
sorry - i should be more specific. i see how to get access to the single arguments object passed in but i don't want to parse that tree again since it's already been done once in static validation. would it be possible to get the `irep_node` in the static validation proc?

**Comment by rmosolgo** [comment]
No, it's not possible to get the irep_node during validation, because it hasn't been built yet! `InternalRepresentation::Rewrite` actually tags along behind the validation visitors, building irep_nodes as validation finishes.

**Comment by modosc** [comment]
hah, i figured this out the hard way yesterday - accessing the parameters in a debugger totally worked but doing it in code caused `stack too deep` exceptions.

it would be cool to have the equivalent of a `coerce_input` callback with the `irep_node` (maybe `analyze_input`?) - this would make it cleaner to write validations that are conditional based on other sibling / parent nodes or nodes that have to be coerced first. i think that would make some code like this cleaner - right now i'm writing a giant `FooValidationAnalyzer` for a `FooInputType` - i expected i'll have to continue this pattern along even though a lot of the logic could be shared via the field.
