### ISSUE TITLE
Return empty instead of null for String type

### ISSUE THREAD

**Issue by mbajur** [rmosolgo/graphql-ruby#807]
I was searching for such option for a bit but was not able to. Right now, when my String type field is empty, graphql returns `null`. Wouldn't that be a good idea to return an empty string `""` instead of null in such cases?

I'm not sure if there is any best-practice for that and i'm not able to find anything related to that topic but, from front-end point of view, when `String` field can produce two kind of results (null and String), i need to cover both scenarios instead of just, for instance, checking length of that field (which is impossible for `null`). That basically makes everything a bit more complex on frontend side.

**Comment by rmosolgo** [comment]
You can support this by doing two things: 

- Defining your field with a [non-null type](http://graphql.org/learn/schema/#lists-and-non-null): 

   ```ruby 
   field :name, !types.String 
  ```
- Then, always return a string from your resolver:

   ```ruby 
   ->(obj, args, ctx) { obj.name || "" } 
  ```

`graphql-ruby` doesn't automatically provide `""`. Instead, a field returns `nil` for a non-null type, it raises an error. 

Does that sound like it would work for you?

**Comment by mbajur** [comment]
These are the two solutions i've been aware of but it's kind of a no-go for me as i have LOADS of such string fields and providing a resolver for each one of them would add a lot of boilerplate code to my app. Way too much for such feature, that's for sure.

Anyway - i'm asked my question because i've been previously working with a lot of other ruby "api frameworks/builders" available out there and most of them has such option to overwride such default behaviour and return empty string instead of null. There are also a lot of threads all around the google on how to enable such feature for <enter api builder tool here> so i'm pretty sure this idea will be coming back in the future.

It's kind of like with arrays/collections - graphql-ruby returns `[]` when collection is empty, not `null` - that makes it 10 times easier to handle the result on the graph client side as you're just checking the length. Why not to make it able to also implement such feature for Strings? I'm not talking about hardcoding that behaviour, just making it able to change it in schema configuration so user can chose.

If i were better ruby programmer, i would definitely came up with a PR for that but i'm affraid that's too much for my skills. Anyway, to be honest, I'm actually not even sure if my way of thinking about this is even correct :)

**Comment by rmosolgo** [comment]
You can apply this programmatically using [field instrumentation](http://graphql-ruby.org/fields/instrumentation.html), for example:

```ruby 
module ApplyEmptyStringIfNull 
  REQUIRED_STRING = GraphQL::STRING_TYPE.to_non_null_type 
  def instrument(type, field)
    if field.type == REQUIRED_STRING 
      # Get the resolve proc from the field and wrap it with your logic:
      new_resolve = EnsureString.new(field.resolve_proc)
      # If you use graphql-batch to load any strings, you'll need this too:
      new_lazy_resolve = EnsuresString.new(field.lazy_resolve_proc)
      
      # Make a copy of the field which has the new behavior
      field.redefine(resolve: new_resolve, lazy_resolve: new_lazy_resolve)
    else 
      # return the field unchanged 
      field 
     end 
  end 

   class EnsureString 
      def initialize(inner_resolve)
        @inner_resolve = inner_resolve
      end 
      # Call the original resolve function, but fall back to "" if it's nil 
      def call(obj, args, ctx)
        @inner_resolve.call(obj, args, ctx) || ""
      end 
    end 
end 
```

**Comment by rmosolgo** [comment]
> graphql-ruby returns `[]` when collection is empty

That's because you returned an empty collection. Similarly, if you return an empty string, you get `""`!

**Comment by mbajur** [comment]
Yes, that makes sense because i've used `empty` word while i shouldn't :D The question should be "if im querying users table and there are no users in the database, should the returned value be an empty array `[]` or `null` ? (have in mind that if database field has no value, api returns null so why if there are no users present, api returns empty array instead of null?)". But after further thinking about it, i think that's actually a general question about graphql/json/api/programming, not about any specific tool like graphql-ruby.

Or maybe that's an obvious question and it's just me having some knowledge gaps. Anyway, thanks for replies and the code snippet - it looks promising, i'm gonna test it soon.

Cheers!
