### ISSUE TITLE
GraphQL Pro OrderedRelationConnection before = after

### ISSUE THREAD

**Issue by sj26** [rmosolgo/graphql-ruby#825]
I was having a poke around in graphql-pro v1.4.2, at OrderedRelationConnection in `lib/graphql/pro/ordered_relation/ordered_relation_connection.rb` which I'm playing with, and noticed that both before and after variables are assigned from the after argument. This seems to break the before cursor functionality.

Also, is there a better way to lodge these sorts of issues? Sorry, there's nothing to link to for examples. 😅

**Comment by sj26** [comment]
I just did a quick `bundle update` to see if this has been solved but it still seems to be the case in v1.4.4, too.

**Comment by rmosolgo** [comment]
This is a great place for opening this issue, thanks! Hmm, let me take a quick look at that ...

**Comment by sj26** [comment]
Wonderful, thank you! 🙇🏻

If this is only for backwards compat I guess it's time for me to update some code! 😅
