### ISSUE TITLE
Schema can contain non-null(non-null(foo))

### ISSUE THREAD

**Issue by Mange** [rmosolgo/graphql-ruby#826]
Schema generated by `graphql-ruby` can become invalid by wrapping a non-null (required) type in non-null again.

```ruby
field :foo, !!String
```

The introspection query will then return this part:

```json
            {
              "name": "foo",
              "description": null,
              "args": [

              ],
              "type": {
                "kind": "NON_NULL",
                "name": null,
                "ofType": {
                  "kind": "NON_NULL",
                  "name": null,
                  "ofType": {
                    "kind": "SCALAR",
                    "name": "String",
                    "ofType": null
                  }
                }
              },
              "isDeprecated": false,
              "deprecationReason": null
            },
```

Type is inspected as `String!!`.

---

This fails to load in (for example) GraphiQL with the error `Error: No nesting nonnull` as it explicitly checks for this problem.

**Comment by rmosolgo** [comment]
😆  oops! 

```ruby 
field :foo, !!types.String
```

Where did that code come from, was it a typo? Or did it come from graphql-ruby somehow? 

In any case, maybe we could improve `BaseType#to_non_null` type to raise if `self` is already a non-null type.

**Comment by Mange** [comment]
No, no this is a human error by our part. We generated types through a DSL
where you declared the plain type in one place and then specified if it was
required or not in another.

```ruby
field :foo, types.String do
  required
  # ...
end
```

When defining the "read" type field, it wrapped the plain type in non-null
for required fields. Someone accidentally wrapped the type in non-null in
the DSL and so it was wrapped twice. We added this as input validation to
the DSL to catch this mistake in the future.

This is because we deal with updates by splitting between "update" and
"unset" fields, so required fields are only marked as non-null on the
creation input type and read type, while the update type has it as nullable
to allow you to leave it alone.
More concrete:

A blog post has
* A required string title
* An optional string body

Then CreatePostInputType has `title: String!, body: String`.
UpdatePostInputType has `updates: PostUpdateFields!, deletions:
PostDeleteFields!`. The update one has `title: String, body: String`, and
the delete one has only `body: Boolean`.
That's because you should not be able to unset the title, but still leave
it out from a partial update. You must supply it on creation however as it
must not be unset.

Excuse the bad formatting, but I'm on mobile-only for the rest of the
evening and I wanted to reply now instead of tomorrow. I could reformat
then if anyone wants. I hope it makes sense anyway.

Den tor 6 juli 2017 15:31Robert Mosolgo <notifications@github.com> skrev:

**Comment by Mange** [comment]
No, no this is a human error by our part. We generated types through a DSL
where you declared the plain type in one place and then specified if it was
required or not in another.

```ruby
field :foo, types.String do
  required
  # ...
end
```

When defining the "read" type field, it wrapped the plain type in non-null
for required fields. Someone accidentally wrapped the type in non-null in
the DSL and so it was wrapped twice. We added this as input validation to
the DSL to catch this mistake in the future.

This is because we deal with updates by splitting between "update" and
"unset" fields, so required fields are only marked as non-null on the
creation input type and read type, while the update type has it as nullable
to allow you to leave it alone.
More concrete:

A blog post has
* A required string title
* An optional string body

Then CreatePostInputType has `title: String!, body: String`.
UpdatePostInputType has `updates: PostUpdateFields!, deletions:
PostDeleteFields!`. The update one has `title: String, body: String`, and
the delete one has only `body: Boolean`.
That's because you should not be able to unset the title, but still leave
it out from a partial update. You must supply it on creation however as it
must not be unset.

Excuse the bad formatting, but I'm on mobile-only for the rest of the
evening and I wanted to reply now instead of tomorrow. I could reformat
then if anyone wants. I hope it makes sense anyway.

**Comment by rmosolgo** [comment]
Here's `NonNullType#initialize`: https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/non_null_type.rb#L36-L39

We should check `of_type` and make sure it's _not_ an instance of `NonNullType`. If it _is_ a `NonNullType`, we should raise an error.

**Comment by esjee** [comment]
I'll take a stab at this!

**Comment by esjee** [comment]
Hey @Mange! I tried to fix this. Let me know if this works out for you.

**Comment by Mange** [comment]
Oh, I'm sure it will. Thanks!
