### ISSUE TITLE
Arguments for GraphQL::ObjectType

### ISSUE THREAD

**Issue by matthewowen** [rmosolgo/graphql-ruby#837]
When I define a field, I can define arguments that it takes and use those fields to determine how it is resolved.

I'd like to do the same for an `ObjectType`. Concretely, I'd like the `ObjectType` to take arguments, and for those arguments to be available to me when I am resolving fields within the object. This would be useful for a use case that has a degree of "perspective", where there's a single value that influences how the object is seen.

I couldn't see any trace in the docs of information on how to do this, so: is it possible?

**Comment by matthewowen** [comment]
To be slightly more concrete, something along the lines of 

```
FooType = GraphQL::ObjectType.define do
  argument(
    :bar, types.Boolean
  )
  field :baz, types.Boolean do resolve -> (o, a, c) { object_args[:bar] } end
end
```

I realize this is a contrived example that makes no sense, but you can presumably see the utility of being able to use a single argument to the object to inform the resolution of a number of different fields within that object.

**Comment by rmosolgo** [comment]
Hi! I think I get what you're going for: sometimes, you want to treat the _same object_ two different ways, depending on the context it's accessed from. 

In the example above, where would `object_args[:bar]` come _from_? How would you provide the value?

This doesn't exist now, the only option is to express the context via `obj` itself, for example:

- Add an accessor to `obj` called `graphql_context`, and assign it when the object is fetched. Then check the value later on to see how to treat the object 
- Wrap `obj` in a proxy which serves as a clue to treat `obj` in a special way.

**Comment by matthewowen** [comment]
Yeah, I was being kinda deliberately vague about where object_args[:bar] comes from :). Thanks for responding: will have a further think.

**Comment by cipater** [comment]
Presumably there's a `field :foo, FooType` somewhere... Unless I'm missing something, wouldn't that become:

```
field :foo, FooType do
  argument(:bar, types.Boolean)
  resolver(FooResolver.new)
end

# foo_resolver.rb
class FooResolver
end
```

**Comment by rmosolgo** [comment]
This kind of usage will be possible after #1037, when each object in the response will be backed by a `GraphQL::Object` instance, so please keep an eye on that PR!
