### ISSUE TITLE
Create a travis build that doesn't install Rails to make sure that any PR that introduce a dependency on Rails/active_support will break

### ISSUE THREAD

**Issue by esjee** [rmosolgo/graphql-ruby#841]
Creating this issue as a response to https://github.com/rmosolgo/graphql-ruby/issues/839

Rails is added as a test dependency, and there are several tests that rely on it being installed. Unfortunately, that also means that any accidental dependencies will easily go unnoticed. In order to resolve this, let's create a travis build that specifically does *not* install Rails to make sure that such mistakes are caught in the future. It will be necessary to avoid running tests that depend on Rails being installed on this specific build.

**Comment by rmosolgo** [comment]
This would be a huge win!
