### ISSUE TITLE
integrate gem built in func to graphql query

### ISSUE THREAD

**Issue by bondanherumurti** [rmosolgo/graphql-ruby#847]
Hey guys, probably this place is not the best idea to ask, but i still haven't got any answered from SO, hope this q did not violate any rules

i'm currently working on an ecommerce project, and start to implement graphql ruby with my solidus, now i'm about to build on faceted search using solidus searchkick

there is a custom function provided by solidus_searchkick

```
searcher = build_searcher(params.merge(fields: fields))
@products = searcher.retrieve_products   
```

my idea was to pass the params to graphql query and perform the search while return the products list

```
query facetQuery($params: String){
  viewer {
    facetProduct(params: $params){ ... }
  }
}
```

However if i put

```
connection :facetProduct, Types::ProductType.connection_type do
    resolve -> (obj, args, context) {
      searcher = build_searcher(params)
      searcher.retrieve_products
    }
end
```

i got a problem build_search is not defined, is there a way to integrate this function directly to graphql, currently i solved this problem over api, via httparty which is not very elegant solution

graph version

graphql (1.6.6)

Thank you

references https://stackoverflow.com/questions/44642934/graphql-ruby-integrate-with-solidus-searchkick

**Comment by Willianvdv** [comment]
Hey @bondanherumurti, sorry for the long wait! From the provided info, it looks like an error that's related to your setup. Since this already a week old, did you fix this already? If not, I'm happy to help you with this issue.

**Comment by bondanherumurti** [comment]
No i havent found any solution yet.. probably thinking to roll back to rest

**Comment by rmosolgo** [comment]
Sorry you didn't find something yet! The key is to find where `build_searcher` is defined, then make that method available to you in your resolve function. I hope you find something that works!
