### ISSUE TITLE
Resolve field on Root Query

### ISSUE THREAD

**Issue by timscott** [rmosolgo/graphql-ruby#848]
I think I should be able to do this:

```ruby
Queries::Root = GraphQL::ObjectType.define do
  name 'RootQuery'
  description 'The query root of this schema'
  # other fields
  field :foo, -> {Types::Foo}
end
```

But I get error

> #<NoMethodError: undefined method `foo' for nil:NilClass>

This workaround does the trick:

```ruby
field :foo, -> {Types::Foo} do
  resolve -> (_obj, _args, _context) {OpenStruct.new}
end
```

I guess I understand that I cannot resolve of field from the root because it has no object, but maybe it should to avoid this kind of silly code? Or maybe there's some better idiomatic way to handle this?

**Comment by rmosolgo** [comment]
You _can_ provide a root object using [`root_value`](http://graphql-ruby.org/queries/executing_queries.html#root-value): 

```ruby
Types::Query = GraphQL::ObjectType.define do
  name 'Query'
  field :foo, types.String
end

# ... 
root_val = OpenStruct.new(foo: "value for foo") 
MySchema.execute("{ foo }", root_value: root_val) 
# => { "data" => { "foo" => "value for foo" } } 
```

A real use case for this might be to pass `current_user` or `current_organization` as `root_value:`, then derive all fields from that starting point. 

Does that work for you?

**Comment by timscott** [comment]
I don't think that would work. `Types::Foo` is a `GraphQL::ObjectType` which has fields, each of which resolves from the query.

Actually, I think my "workaround" is probably the correct way to do it. Thanks!
