### ISSUE TITLE
25th of August - Amsterdam GraphQL Ruby hack day

### ISSUE THREAD

**Issue by Willianvdv** [rmosolgo/graphql-ruby#854]
Note: this invite is a work in progress. However, the date is **set and won't be changed.**

Hello peeps, 

It's going to happen, our first GraphQL hack day! The idea is to have a day where you can meet other GraphQLiasts, ask questions, improve the gem or just have a fun time.

Our hack location will be in Amsterdam. Don't worry if you're not in this time zone, we'll make this hack day remote friendly by having a dedicated Google Hangout and hack until even our friends from San Fransisco can join!

We've already started compiling a list of [project ideas](https://github.com/emilebosch/graphql-hackathon-ams/issues/1#issuecomment-316307447). Feel free to add more if you know a cool project.

**Date**: 25 Aug 2017
**Time**: (CEST) 09:00 - TBD
**Hangout Url**: TBA
**Location**: Codaisseur - [Rhijnspoorplein 28 (Sarphati Plaza @ Weesperplein), Amsterdam
](https://www.google.com/maps?f=q&hl=en&q=Rhijnspoorplein+28+(Sarphati+Plaza+@+Weesperplein),+Amsterdam,+nl)
Please RSVP [here](https://www.meetup.com/Amsterdam-rb/events/241877303/) if you're joining us in AMS so we know how many lunch+pizza+drinks we've to buy.

Hopefully, we'll see you in Amsterdam or on our hack day hang out!

Thanks,

@emilebosch 
@esjee 
@wvdv

---

**Code of conduct**

This should be a fun event for everyone! 

[HELP WANTED!] I'd like to reuse a code of conduct and have some entity that can handle complaints. I'll check if this is possible.

**Comment by rmosolgo** [comment]
Very cool! I just booked my ticket for a little trip to NL :D 


Can we add a page to `graphql-ruby.org` for this event, and perhaps a banner to notify visitors (once) about it? 

Also, when the page is up, I'd like to email the graphql-ruby newsletter with a link to that page. How does that sound?

**Comment by emilebosch** [comment]
That sounds awesome, Im @ HackerOne office tomo to get all these things done. Even though we’re not selling tickets, i need to put a limit on the number of ppl. because we have only so many spots. The amount i know exactly tomorrow. I’ll ping you tomo when u can put it up :) W

Keep rocking!

**Comment by skorfmann** [comment]
Cool idea, count me in 👍

**Comment by Willianvdv** [comment]
@skorfmann cool! Will you join us in Amsterdam or hangouts?

**Comment by skorfmann** [comment]
> @skorfmann cool! Will you join us in Amsterdam or hangouts?

I'll join you in Amsterdam (gonna fly in to AMS for that day)

**Comment by emilebosch** [comment]
@skorfmann awesome!! I see that you work at XING! Care to talk about that a littke? Just a short talk? Would love to know how you all implement it over there!

**Comment by skorfmann** [comment]
> @skorfmann awesome!! I see that you work at XING! Care to talk about that a little? Just a short talk? Would love to know how you all implement it over there!

FYI: Our GraphQL Ruby implementation is pre-production and won't really make it into production. It's gonna be replaced by Sangria. Nevertheless, I'd still be more than happy to talk about it and our experience so far 😄

**Comment by emilebosch** [comment]
I’m cool with that! sounds awesome what do you think @wilian? @esjee

**Comment by emilebosch** [comment]
Bam its live! 🙌  https://www.meetup.com/Amsterdam-rb/events/241877303/ I'll pimp it up a little soon!

**Comment by bdubaut** [comment]
I am interested to prepare something for the [GraphQL Themed Talks & Drinks!](https://www.meetup.com/Amsterdam-rb/events/241877366/) event right after the hack day, we have been using GraphQL in production for about 6-8 months, made plenty of mistakes and found ways to correct along the way, it could be interesting to some if me and some of my colleagues were to share our experience with GraphQL as a concept and graphql-ruby per say.

**Comment by emilebosch** [comment]
Hey @bdubaut would love to have a small chat with you! I see you're in amsterdam too. Please call /chat with me on +31611433101 :)

**Comment by esjee** [comment]
It's done!

Should this issue be closed?
