### ISSUE TITLE
Is this gem compatible with Relay Modern on the front?

### ISSUE THREAD

**Issue by igorpreston** [rmosolgo/graphql-ruby#856]
Hey, I am using developing a new React app with Relay Modern and I have Rails RESTful API on the backend. I am considering to use this gem to provide `/graphql` endpoint, however it seems to me that it is only compatible with Relay Classic. Because there were some breaking changes to the Relay API. Am I wrong?

Thanks!

**Comment by rmosolgo** [comment]
I think this gem will support either version of Relay. As far as I know, Relay's GraphQL requirements are the same between Relay Classic and Relay Modern. That is, the _JavaScript_ APIs are very different between Classic and Modern, but I think the same GraphQL server works for both. 

So, it should work! If you give it a try and have a problem, please open an issue. It's my goal to support all versions of Relay.
