### ISSUE TITLE
GraphQL::Relay::Mutation.define broken

### ISSUE THREAD

**Issue by asafigan** [rmosolgo/graphql-ruby#859]
version: 1.6.6

```
Types::MutationType = GraphQL::ObjectType.define do
  name "Mutation"

  field :createImage, field: GraphQL::Relay::Mutation.define do
    name "CreateImage"
    description "Create a image"

    input_field :fileRef, !types.String

    return_field :imageEdge, Types::ImageType.edge_type

    resolve -> (inputs, ctx) {
      file_ref = inputs[:file_ref]

      file = ctx[:files][file_ref]

      image = Image.create(file: file)

      {image: image}
    }
  end.field
end
```

I get this error:
```
GraphQL::Define::NoDefinitionError (GraphQL::Field can't define 'input_field'):
app/graphql/types/mutation_type.rb:9:in `block (2 levels) in <top (required)>'
app/graphql/api_schema.rb:1:in `<top (required)>'
app/controllers/graphql_controller.rb:10:in `execute'
```

I could be misusing the API. But all I did was follow the documentation.

**Comment by rmosolgo** [comment]
I think the block is being associated with the `field` method instead of `Mutation.define`. 

What if you move `GraphQL::Relay::Mutation.define do ... end` into its own file , and assign it to a constant?

or, wrap parens around: 

```ruby
 field(:createImage, # ...
 end.field)
```

That would force the block to be associated with `.define`

**Comment by asafigan** [comment]
The reason that I didn't make the mutation a constant is because when I did it wouldn't show errors. The constant would just be undefined, and I would get a undefined constant error.

**Comment by asafigan** [comment]
```
module ImageMutations
  Create = GraphQL::Relay::Mutation.define do
    name "CreateImage"
    description "Create a image"

    input_field :fileRef, !types.String

    return_field :image, Types::ImageType

    resolve -> (inputs, ctx) {
      file_ref = inputs[:file_ref]

      file = ctx[:files][file_ref]

      image = Image.create(file: file)

      {image: image}
    }
  end
end

Types::MutationType = GraphQL::ObjectType.define do
  name "Mutation"

  # TODO: Add Mutations as fields
  field :createImage, ImageMutations::Create.field

  field :testField, types.String do
    description "An example field added by the generator"
    resolve ->(obj, args, ctx) {
      "Hello World!"
    }
  end
end
```

This fixes it somehow.

**Comment by asafigan** [comment]
But if I move the `ImageMutations` module out of the file. I get a Undefined Constant error. What should I do?

**Comment by asafigan** [comment]
Got it working. I had to define it as `Mutations::ImageMutations` or else it wouldn't load. Can anyone tell me why? Both `Mutations::Image` and `ImageMutations` does work.

**Comment by asafigan** [comment]
Also I have to call my image type `Types::ImageType` or it won't load either.

**Comment by asafigan** [comment]
This really confuses me. Shouldn't I be able to name the constants whatever I won't and rails will load it for me?

**Comment by rmosolgo** [comment]
No, you can't name them whatever you want. The namespace & constant name must match the filepath.
