### ISSUE TITLE
Issues with schema validation

### ISSUE THREAD

**Issue by lucas-aragno** [rmosolgo/graphql-ruby#866]
I'm getting

```
21:44:51 web.1     | /Users/laragno/.rvm/gems/ruby-2.3.3/gems/graphql-0.19.4/lib/graphql/schema/validation.rb:147:in `block (3 levels) in <module:Rules>': uninitialized constant GraphQL::Relay::GlobalIdResolve (NameError)
21:44:51 web.1     | Did you mean?  GraphQL::Relay::GlobalIdField
```

this is my current gem version

```
Lucass-MacBook-Pro:todo-sinatra laragno$ cat Gemfile.lock | grep relay
    graphql-relay (0.12.0)
  graphql-relay
```

any ideas?

**Comment by lucas-aragno** [comment]
Update, seems like that error happens when i do:

```ruby
ApplicationSchema = GraphQL::Schema.define(
  query: QueryType,
  mutation: MutationType
)
```

If I use `new` instead of define works fine i.e:

```ruby
ApplicationSchema = GraphQL::Schema.new(
  query: QueryType,
  mutation: MutationType
)
```

but that's deprecated, right?

**Comment by rmosolgo** [comment]
I see you're using 

> graphql-0.19.4

Please update, the latest version is 1.6.6 !

**Comment by lucas-aragno** [comment]
oh I see, but i'm using [graphql-relay](https://rubygems.org/gems/graphql-relay/versions/0.12.0) as well which depends on 0.17 😞

**Comment by rmosolgo** [comment]
GraphQL::Relay was merged into this project [last summer](https://github.com/rmosolgo/graphql-ruby/pull/195), so you will find all of that code here now, for example: 

https://github.com/rmosolgo/graphql-ruby/tree/master/lib/graphql/relay

So, you should update `graphql` and stop using `graphql-ruby`!

**Comment by lucas-aragno** [comment]
WOW! Seems like I've been out of the game for a while 😬. Updated and everything works beautifully   
Thanks for the help and thanks for the awesome work! 

Closing this issue now 😄
