### ISSUE TITLE
Default enum values for arguments

### ISSUE THREAD

**Issue by khelll** [rmosolgo/graphql-ruby#868]
I have:

```ruby
RegionCodeType = GraphQL::EnumType.define do
  name "RegionCodeType"
  description "Possible region codes for a discover group"
  value("US", "USA")
  value("CA", "Canada")
end
```

and a field:

```ruby
argument :region, RegionCodeType, "Filter groups by region"
```

I'm trying to add a default enum value as the following:

```ruby
argument :region, RegionCodeType, "Filter groups by region", default_value: "CA"
```
And that triggers the following schema error:

```Argument 'region' on Field 'test' has an invalid value. Expected type 'RegionCodeType'.```

Also tried:

```ruby
argument :region, RegionCodeType, "Filter groups by region", default_value: types["RegionCodeType"].values["CA"]
```

and got:

```
NoMethodError (undefined method `to_list_type' for "RegionCodeType":String):
```

**Comment by khelll** [comment]
And also, is there a way to default to some enum value in case the supplied argument value doesn't match the provided values? Right now this will raise an exception.

**Comment by rmosolgo** [comment]
Try 

```ruby 
argument :region, RegionCodeType, "Filter groups by region", default_value: "Canada"
```
? 

(using the _Ruby_ value as the default_value, not the GraphQL value)

**Comment by rmosolgo** [comment]
Please let me know if that doesn't work for you!

**Comment by matisoffn** [comment]
I'm experiencing the same issue using the Ruby value. Here's my argument definition.

```ruby
argument :sort, Sort, "Sort for the search results", default_value: 1, required: false
```

What's the proper way to accomplish a default value using an enum?
