### ISSUE TITLE
Prepare proc fails to run for input type argument when putting the input type into the query variables

### ISSUE THREAD

**Issue by mengledowl** [rmosolgo/graphql-ruby#869]
I've got a mutation that allows the client to update the currently signed in user's preferences. The mutation looks like this:

```
field :updateUserPreferences, Types::PreferenceType do
  description 'Update the currently logged in user\'s preferences'

  argument :preferences, Inputs::PreferenceInput

  resolve Resolvers::UpdatePreferencesResolver.new
end
```

PreferenceInput:

```
Inputs::PreferenceInput = GraphQL::InputObjectType.define do
  name 'PreferenceInputType'
  description 'Properties for preferences on a user'

  argument :locationId, types.ID, as: :location_id, prepare: ->(location_id, ctx) {
    puts 'prepare' # <-- this is what never ends up getting run
  }
end
```

The following query executes without a hitch, and will run the `prepare`:

```
mutation {
  updateUserPreferences(preferences: { locationId: "175" }) {
    location {
      id
      name
    }
    errors
    successful
  }
}
```

When putting the preferences into a query variable however, the `prepare` never executes and my code blows up (because the processing isn't getting done in `prepare`):

```
mutation SelectLocation($preferences: PreferenceInputType!) {
  updateUserPreferences(preferences: $preferences) {
    location {
      name
      id
    }
    errors
  }
}

# query variables

{
  "preferences": { "locationId": "175" }
}
```

Interestingly enough, the following query will execute correctly and run the `prepare` proc too:

```
mutation SelectLocation($locationId: ID!) {
  updateUserPreferences(preferences: { locationId: $locationId }) {
    location {
      name
      id
    }
    errors
  }
}

# query variables

{
  "locationId": "175"
}
```

It's only when passing in the whole input type from the query variables that it doesn't execute properly.

This is on Rails 5.1.3, Ruby 2.4, with graphql-ruby 1.6.6.

**Comment by rmosolgo** [comment]
It looks like this was fixed in https://github.com/rmosolgo/graphql-ruby/pull/849, but the fix _wasn't_ on Rubygems yet! I pushed another fix in d22d3968 to confirm. 

I just released 1.6.7 with the fix, could you try again, and re-open this issue if you still see the problem?

**Comment by mengledowl** [comment]
@rmosolgo that seems to have fixed it! Thanks for looking into this!

**Comment by rmosolgo** [comment]
Glad to hear it!
