### ISSUE TITLE
Making field property accessible after definition

### ISSUE THREAD

**Issue by kliuless** [rmosolgo/graphql-ruby#87]
When defining a field, you can specify a property name, which gets called on the backing object during resolve:
```ruby
field :createdBy, types.String, property: :created_by
```
However, it seems like the property isn't accessible on the `GraphQL::Field` object; it's wrapped inside the resolver lambda in `GraphQL::DefinitionHelpers::DefinedByConfig::DefinitionConfig`:
```ruby
property && field.resolve = -> (t,a,c) { t.public_send(property)}
```
Is there interest in storing this to an instance variable and exposing a getter?

My use case is to access the mappings in a mutation which needs to do a reverse mapping, to set attributes on an ActiveRecord model. E.g. the mutation receives a `createdBy` argument and has to call `record.created_by = input_value`. If there's a better way to do this, let me know.

**Comment by rmosolgo** [comment]
> Is there interest in storing this to an instance variable and exposing a getter?

:+1: that'd be great!  Maybe you could update the default resolve proc to check for a property? (or maybe that's a waste of time at runtime?)

**Comment by kliuless** [comment]
At first I didn't want to have the proc do the check, but then `property` would make more sense as a attr_reader only (since the original property would be hardwired to the proc). But that complicates other things, like when `DefinitionConfig#to_instance` using `public_send` to set the attributes on the `Field`.

So I'm going to have the proc do the check. I don't think performance would be affected much, especially on ruby 2.x.

**Comment by kliuless** [comment]
Hmm, after making the changes, I realized I could've re-created the resolver proc when property is reassigned, instead of checking inside the proc. Not sure it's worth the effort to change it though.
