### ISSUE TITLE
Guide: Getting Started

### ISSUE THREAD

**Issue by gregclar** [rmosolgo/graphql-ruby#874]
Hi @rmosolgo 

Just starting a Rails 5 api app today using graphql-ruby - appreciate your work.  Running graphql 1.6.6.

I was working through the examples at http://graphql-ruby.org/getting_started and I used the install command:

> rails g graphql:install

After that I was able to query the testField.

But when I tried to define a NameType along the lines of the PostType example I kept getting 

> uninitialized constant NameType

errors. 

I eventually found I had to change `type NameType` to `type Types::NameType` in my field declaration in query_type.rb, and I also had to change

 > NameType = 

to 

> Types::NameType =

 in my name_type.rb file.

My query_type.rb now has:

```
Types::QueryType = GraphQL::ObjectType.define do
  name "Query"
  # Add root-level fields here.
  # They will be entry points for queries on your schema.
  field :name do
    type Types::NameType
    argument :id, !types.ID
    resolve -> (obj, args, ctx) {
      Name.find(args["id"])
    }
  end
end
```

and my name_type.rb file has:

```
Types::NameType = GraphQL::ObjectType.define do
  name "name"
  field :id, types.ID
  field :simple_name, types.String
end
```
This now works.

My (get) URL:` http://localhost:4004/graphql?query={name(id:91755){simple_name}}`
successfully produces:

```
{
"data":
{
"name":
{
"simple_name":
"Angophora costata"
}
}
}
```

**Comment by rmosolgo** [comment]
Hey, thanks for reporting this issue! 

Those two parts of the getting started guide were written months apart. They weren't meant to work together, but since they're one-after-the-other, it looks like they should! 

Those examples should be updated to so that they _work_ (like your changes above) or updated so it's clear they aren't supposed to be equivalent.

**Comment by rmosolgo** [comment]
The "getting started" page has been redone, so I'll close this as no longer relevant. Feel free to open a fresh issue for doc trouble!

**Comment by gregclar** [comment]
Thanks @rmosolgo.
