### ISSUE TITLE
How can I add a count field?

### ISSUE THREAD

**Issue by hegwin** [rmosolgo/graphql-ruby#880]
I'm developing an API for the front-end to query a list of resources, let's say, classrooms, for example.
There is a requirement that we need to show the total number (count) of classrooms that match the user's filter.

Our current response body is like:

```json
{
  "data": {
    "classroomList": [
      {
        "id": 48
      },
      {
        "id": 49
      }
    ]
}
```

How can I structure the responding JSON? Where can I put it? Or do I need a separate API for this?

**Comment by rmosolgo** [comment]
you can add an integer field called `classroomCount`, for example:

```
field :classroomCount, !types.Int do 
 resolve ->(obj, args, ctx) {
    Classroom.count 
  } 
end 
```

Does that work for you?

**Comment by hegwin** [comment]
Hi @rmosolgo 

Do you mean I put the count in every record? I'm not sure...Can I have something like:

```json
{
  "data": {
    "count": 23,
    "classroomList": [
      {
        "id": 48,
        "location": "...",
        "available_time_slots": []
      },
      {
        "id": 49,
        "location":  "...",
        "available_time_slots": []
      }
    ]
}
```

**Comment by rmosolgo** [comment]
Yes, you can have something like that! Add to your root `Query` type: 

```ruby 
field :count, !types.Int, "Total number of classrooms in the system" do 
  resolve -> (obj, args, ctx) { Classroom.count } 
end 
```

that will support a query like the one you posted above!

**Comment by hegwin** [comment]
@rmosolgo  That's awesome! Thank you!
