### ISSUE TITLE
Sequel::Error Limits must be greater than or equal to 1

### ISSUE THREAD

**Issue by jpserra** [rmosolgo/graphql-ruby#887]
Using the following query, if I get the `cursor` from the first `user` and use it as before argument, I get a `500 "#<Sequel::Error: Limits must be greater than or equal to 1>"`.
```graphql
{
  account(id: 1) {
    users {
      edges {
        cursor
      }
    }
    beforeUser: users(before: "MQ==") { # cursor of the first user
      edges { node { __typename } }
    }
  }
}
```
```
{
  "status": 500,
  "error": "Internal Server Error",
  "exception": "#<Sequel::Error: Limits must be greater than or equal to 1>",
  "traces": {
    "Application Trace": [
     ...
    ],
    "Framework Trace": [
      {
        "id": 0,
        "trace": "sequel (4.48.0) lib/sequel/dataset/query.rb:653:in `limit'"
      },
      {
        "id": 1,
        "trace": "graphql (1.6.6) lib/graphql/relay/relation_connection.rb:129:in `sliced_nodes'"
      },
      {
        "id": 2,
        "trace": "graphql (1.6.6) lib/graphql/relay/relation_connection.rb:56:in `paged_nodes'"
      },
...
```

Looking at the code, 

```ruby
## graphql-ruby/lib/graphql/relay/relation_connection.rb

111       # Apply cursors to edges¬
112       def sliced_nodes¬
113         return @sliced_nodes if defined? @sliced_nodes¬
114 ¬
115         @sliced_nodes = nodes¬
116 ¬
117         if after¬
118           offset = (relation_offset(@sliced_nodes) || 0) + offset_from_cursor(after)¬
119           @sliced_nodes = @sliced_nodes.offset(offset) if after¬
120         end¬
121 ¬
122         if before && after¬
123           if offset_from_cursor(after) < offset_from_cursor(before)¬
124             @sliced_nodes = @sliced_nodes.limit(offset_from_cursor(before) - offset_from_cursor(after) - 1)¬
125           else¬
126             @sliced_nodes = @sliced_nodes.limit(0)¬
127           end¬
128         elsif before¬
129           binding.pry¬
130           @sliced_nodes = @sliced_nodes.limit(offset_from_cursor(before) - 1)¬
131         end¬
132 ¬
133         @sliced_nodes¬
134       end¬
```

in line `130` `@sliced_nodes` is a dataset and we're calling `.limit(0)` on it since `offset_from_cursor(before) - 1 = 0`

Here's a simple example:
```ruby
[11] () <GraphQL::Relay::RelationConnection>: 0> @sliced_nodes
=> #<Sequel::Postgres::Dataset: "<<<Super secret dataset>>>">
[12] () <GraphQL::Relay::RelationConnection>: 0> offset_from_cursor(before) - 1
=> 0

[13] () <GraphQL::Relay::RelationConnection>: 0> @sliced_nodes.limit(offset_from_cursor(before) - 1)
Sequel::Error: Limits must be greater than or equal to 1
```

**Comment by jpserra** [comment]
I'm happy to work on a fix for this, let me know what you think about it!

**Comment by jpserra** [comment]
Now that I think about it, and looking at how ActiveRecord deals with this situation (`limit(0)` just returns an empty set), It might be something that Sequel should support too

**Comment by rmosolgo** [comment]
A fix here would be great! It would be great to include a test case for this too, so we don't break compatibility in the future 😬

**Comment by jpserra** [comment]
Cool I'll look into it then! But before I do, I'd like to hear your thoughts about the best approach for this. 

What is happening is the following: 
```ruby
## lib/sequel/dataset/query.rb

 632     def limit(l, o = (no_offset = true; nil))¬
 633       return from_self.limit(l, o) if @opts[:sql]¬
 634 ¬
 635       if l.is_a?(Range)¬
 636         no_offset = false¬
 637         o = l.first¬
 638         l = l.last - l.first + (l.exclude_end? ? 0 : 1)¬
 639       end¬
 640       l = l.to_i if l.is_a?(String) && !l.is_a?(LiteralString)¬
 641       if l.is_a?(Integer)¬
>642         raise(Error, 'Limits must be greater than or equal to 1') unless l >= 1¬
 643       end¬
 644 ¬
 645       ds = clone(:limit=>l)¬
 646       ds = ds.offset(o) unless no_offset¬
 647       ds¬
 648     end¬
```

Line `642` it's raising this error. This behaviour diverges from the one in `ActiveRecord` that allows for `limit = 0`

I'm still gonna see what is Jeremy's idea on this and if it should be changed in sequel itself. In the meantime, there's 2 things we can do to solve this in `graphql-ruby`:

 1 - Either rescue the exception that sequel is raising and somehow return an empty `Sequel::Dataset`
  - Brings the advantage of knowing already that it's a `Sequel::Dataset` that needs to be returned upon rescue

 2 - Avoid querying the database since `limit 0` will always yield an empty set
  - Avoids a database query
  - Needs some extra logic to see if it should return an `ActiveRecord::Relation` or a `Sequel::Dataset` 

3 - Rescue the exception and raise one that clearly explains the issue
 - Brings inconsistent behaviour between `ActiveRecord` and `Sequel`

Which one would you consider the best approach?

**Comment by rmosolgo** [comment]
In my opinion, option 2 above would be best! It adds some complexity to the implementation, as you noted, but it Just Works :tm: from the user perspective, which is great. 

Option 1 also Just Works, but personally I'm not a fan of using try-catch to implement logic. For a reader, it can be hard to determine _why_ the error is being raised and _where_ the error gets raised from. So if we can avoid it and use local, sequentially-executing code, that would be nice!

**Comment by rmosolgo** [comment]
To clarify, _any_ implementation that: 

- Adds a test for `limit(0)` + Sequel
- Returns an empty list instead of crashing 

gets a :+1: from me :)

**Comment by jpserra** [comment]
I also started this thread here: https://groups.google.com/forum/#!topic/sequel-talk/wd0pwZpPMxA
