### ISSUE TITLE
RFC: Missing InputValue node in parser

### ISSUE THREAD

**Issue by cjoudrey** [rmosolgo/graphql-ruby#891]
Currently, `InputValue` get turned into Ruby literals when parsed.

For example if we parse this GraphQL query:

```graphql
{
  field(argument: "value")
}
```

The `ArgumentNode` is:

```
#<GraphQL::Language::Nodes::Argument:0x007f8f8430bef0
  @line=3,
  @col=9,
  @filename=nil,
  @name="argument",
  @value="value">
```

The problem with this is we lose the `line` and `col` for the `InputValue` node `"value"` which is useful for validation rules.

In the reference implementation, they solve this by having an `InputValue` node and thus the `ArgumentNode` is:

```js
export type ArgumentNode = {
  kind: 'Argument';
  loc?: Location;
  name: NameNode;
  value: ValueNode;
};
```

I'd be willing to help add `ValueNode` support to the parser, but if we want to do it cleanly, it will be a breaking change for anyone relying on `GraphQL::Language::Nodes` as `Argument#value` (for example) would become a `ValueNode` instead of a Ruby literal.

Alternatively, we could leave the current `value` as a Ruby literal and add `value_node` which would be the `ValueNode`. While this is backwards compatible, I feel it might not be consistent with the rest of the parser.

@rmosolgo thoughts?

**Comment by rmosolgo** [comment]
It would be great to get position info for literal values! I think your suggestion of adding `#value_node` is great. Like you said, it's not consistent, but being non-breaking is a huge win. 

Alternatively, if you _wanted_ to explore a similar change in graphql-libgraphqlparser-ruby, we could merge them together and bump their gemspecs as needed.

**Comment by cjoudrey** [comment]
> Alternatively, if you _wanted_ to explore a similar change in graphql-libgraphqlparser-ruby, we could merge them together and bump their gemspecs as needed.

Just to confirm what you mean, you're asking if I could do the same change in `graphql-libgraphqlparser-ruby` so that we can ship both at the same time, correct?

It's not one or the other since, we'd still want this in the Ruby implementation.

**Comment by rmosolgo** [comment]
Sorry for being vague -- what I meant was: 

- Adding value_node is :+1: 
- If you want to make the breaking change on `InputValue#value` to return a `ValueNode` instead of a `String | Integer | Float | Boolean | nil`, it's ok with me _if_ we make the corresponding change to graphql-libgraphqlparser-ruby 

I think it's a reasonable breaking change with a straightforward upgrade path, I just  don't want to leave users of that library out in the cold. 

Heck, upgrade-wise you could even monkeypatch it if you really can't fix it now: 

```ruby 
alias :new_value :value 
def value 
  new_value.value 
end 
```

**Comment by rmosolgo** [comment]
This would definitely be nice, but I don't have plans to work on it now (and neither does anybody else, seems like), so I'll close it.
