### ISSUE TITLE
Conditionally allowing a field

### ISSUE THREAD

**Issue by jnfeinstein** [rmosolgo/graphql-ruby#893]
I am wondering if it is possible to add a proc on a field or type that specifies when it should be visible and query-able.  Specifically I am trying to build a single GraphQL API that can be used for internal and external queries.  The internal queries would be allowed to access fields that the external one cannot access.  This is similar to authorization but primarily based on context, and the two could be used together.  The syntax I'm imagining is:
```
context = {
  internal: cookies.signed[:is_most_definitely_my_app].true?
}

# Only admins from an internal application can access this field
field :internal_field do
  type types.String
  authorize :admins
  if ->(ctx) { ctx[:internal] }
end

# This field is visible to anyone not using an internal application
field :external_field do
  type types.String
  unless ->(ctx) { ctx[:internal] }
end
```
The result would be that `internal_field` would be visible and query-able from my app, and `external_field` would be visible and query-able by others.

I think this is possible using a whitelist/blacklist, but like the `authorize` helper I think it is much cleaner to include the logic on the field definition.  Is this possible?

**Comment by rmosolgo** [comment]
As you mentioned, [schema filtering](http://graphql-ruby.org/schema/limiting_visibility.html) supports this. You can [extend the DSL](http://graphql-ruby.org/schema/extending_the_dsl.html) to support inline logic. (This is what graphql-pro does for the [authorization framework](http://graphql-ruby.org/pro/authorization#visibility-authorization).)

**Comment by jnfeinstein** [comment]
Perfect.  Is there a way to always apply a filter to a schema rather than specifying it on the call to execute?  I.e.
```
MySchema = GraphQL::Schema.define do
  authorization(:cancan)
end
```
This schema will always be run with authorization, I'd like mine to do the same with show/hide (if/unless since those are reserved terms in the context of a definition).

**Comment by rmosolgo** [comment]
Good question, yes, filters can also be added by query instrumentation using `Query#merge_filters`: 

https://github.com/rmosolgo/graphql-ruby/blob/4ae161488d08682f940a852b8e79904c5ab428bf/spec/graphql/schema/warden_spec.rb#L106-L125

**Comment by jnfeinstein** [comment]
This works well, thank you.  Great work on the API for this API.
