### ISSUE TITLE
Polymorphic types

### ISSUE THREAD

**Issue by jimmybaker** [rmosolgo/graphql-ruby#894]
I have a model called Note

```
class Note < ActiveRecord::Base
  belongs_to :notable, polymorphic: true
end
```

When defining the graphql object to support this, I'm not sure what to put as the notable field since it could be a number of different types. What should I do here?

**Comment by jimmybaker** [comment]
Nevermind. I was able to solve using UnionTypes.

**Comment by sasharevzin** [comment]
@jimmybaker would you share your solution?

**Comment by jimmybaker** [comment]
@sasharevzin - I did it like this: https://github.com/rmosolgo/graphql-ruby/blob/master/guides/type_definitions/unions.md
