### ISSUE TITLE
Feature: allow interfaces to have interfaces

### ISSUE THREAD

**Issue by thefliik** [rmosolgo/graphql-ruby#897]
It seems very likely that this idea has already been discussed, but since I can't find anything:
The ability for interfaces to define default fields is awesome. It would be nice to have the ability to include interface A in interface B, so that any objects implementing interface B also implement interface A. 
(ps: this gem is awesome!!!)

**Comment by rmosolgo** [comment]
Hi, thanks for the suggestion! Glad to hear you're enjoying the gem. 

Personally, I'm not too interested in adding more interface inheritance. Although it's very convenient, I find that it's hard to keep track of which fields are implemented by which files. 

That said, I'm trying out a new schema definition api ( #871 ) which uses Ruby classes to implement GraphQL object types and fields. In that approach, you could use Ruby modules to inherit code however you like :) 

So, if someone else wants to try adding this feature, I would be happy to consider it. But for my part, I'm going to focus on a few other things for now! If anyone wants to continue the discussion, feel free to add your opinion here.

**Comment by thefliik** [comment]
#871 is a much better solution to this problem! Go with that. That's very cool. And I must reiterate, I super appreciate all the time you've put into this.
