### ISSUE TITLE
Connections generating unnecessary COUNT query

### ISSUE THREAD

**Issue by ddgromit** [rmosolgo/graphql-ruby#899]
For connection queries that request both `edges` and `hasNextPage`, a COUNT query is run even if the number of edges returned is less than the requested limit.

In queries like this for example, if less than 1000 users are returned, then hasNextPage should always be false:
```
{
  query {
    users(first: 1000) {
      edges {
        ...
      }
      pageInfo {
        hasNextPage
      }
    }
  }
}
```

It looks like optimization was added in [February](https://github.com/rmosolgo/graphql-ruby/commit/03464e02e38f9950ae33a29481242f8199d8e347) but taken out in [May](https://github.com/rmosolgo/graphql-ruby/commit/838b403e1c146ed9b491b93fee1e696aade93828), presumably because it doesn't work when both `first` and `last` are set.  Could this functionality be returned to `RelationConnection#sliced_nodes_count` in the scenario where only `first` is set?

**Comment by rmosolgo** [comment]
Thanks for tracking this down! I'm sad to hear it was removed, I guess I overlooked it in review 😬 

Getting it back in the works would be great, do you want to take a crack at it? 

One way or another, I'll try to add something to the test suite to watch the _actual_ database queries run by the connections.

**Comment by ddgromit** [comment]
Sure, I'll take a shot at it.
