### ISSUE TITLE
RFC: Should calling `connection_type` on an interface return an interface?

### ISSUE THREAD

**Issue by theorygeek** [rmosolgo/graphql-ruby#902]
Suppose that you have an interface:
```ruby
MyInterfaceType = GraphQL::InterfaceType.define do
  name "MyInterface"
  # some fields
end
```

And then you try to get a connection type for it:
```ruby
MyInterfaceType.connection_type
```

Would it be more natural to get an _interface_ type returned to you, instead of an _object_ type? And this would probably have to carry down: the type of the `edges` fields would also have to be an interface.

This boat has probably long sailed away, but I figured I'd bring it up as a discussion point. You could always add an option, or maybe we just say, "You should build it manually."

**Comment by rmosolgo** [comment]
Interesting idea! I looked through the GitHub schema and it looks like we have a couple of places where we make connections from unions or interfaces, for example, search results returns a connection of SearchResultItemUnion. 

Can you help me understand why getting an Interface instead of an Object is helpful? Or what's the case where that's the desired behavior?

**Comment by theorygeek** [comment]
Here's our use case, hopefully it makes sense. We have several places in our app where the user can import a spreadsheet of data. In order to help the user identify problems, we have a structure on our graph that looks like this (simplified):

```graphql
interface Spreadsheet {
  tabs: [SpreadsheetTab!]
}

interface SpreadsheetTab {
  rows(first: Int, last: Int, before: String, after: String): SpreadsheetRowConnection
}

interface SpreadsheetRowConnection {
  edges: [SpreadsheetRowEdge]
  pageInfo: PageInfo!
}
```

Simple: Spreadsheet has Tabs, each Tab has Rows, and the rows are exposed as a connection. As you can see, these are interfaces, because we are building a generic set of components that can display the results on screen in a nice grid view, with cell highlighting, etc.

However, we often have auxiliary data based on how we've interpreted information in each row, so we have a set of concrete types:
```graphql
type PayrollHourImport implements Node, Spreadsheet {
  # Info related to this _kind_ of spreadsheet, but not spreadsheets generally:
  company: Company!

  # Implementation of the `tabs` field from the interface:
  tabs: [PayrollHourImportTab!]!
} 

type PayrollHourImportTab implements Node, SpreadsheetTab {
  # In this particular type of spreadsheet, each tab is expected to match up to a particular object:
  payrollSchedule: PayrollSchedule

  # Implementation of the `rows` field:
  rows(first: Int, after: String, last: Int, before: String): PayrollHourImportRowConnection
}

type PayrollHourImportRowConnection implements SpreadsheetRowConnection {
  edges: [PayrollHourtImportRow]
  pageInfo: PageInfo!
}
```

So in this case you can see that we have essentially duplicated the structure, once as a set of interfaces, and another as a set of object types. The concrete object types generally add more information about how each part of the spreadsheet was interpreted.

Having said all of this, I myself am not entirely convinced that `connection_type` on an interface should return another interface. But for what it's worth, that's the use case: a hierarchy of interfaces and corresponding concrete types, where some of them are connections.

**Comment by rmosolgo** [comment]
Wow, that's really interesting! So, in your case, not only are the _nodes_ of varying types, but the edges are too. (Is that right, is `SpreadsheetRowEdge` also an abstract type?)

**Comment by theorygeek** [comment]
Yes, that is right. Mostly because the concrete types always reference concrete ones, and vice versa...
```graphql
# Edges...
interface SpreadsheetRowEdge {
  cursor: String!
  node: SpreadsheetRow
}

type PayrollHourtImportRow implements SpreadsheetRowEdge {
  cursor: String!
  node: PayrollHourImportRow
}

# Rows...
interface SpreadsheetRow {
  cells: [SpreadsheetCell!]!
  problems: [SpreadsheetProblem!]!
}

type PayrollHourImportRow implements SpreadsheetRow {
  cells: [PayrollHourImportColumn!]!
  employee: Employee
  problems: [PayrollHourImportError!]!
}

# Cells...
interface SpreadsheetCell {
  index: Int!
  problems: [SpreadsheetProblem!]!
  row: SpreadsheetRow!
  value: String
}

type PayrollHourImportColumn implements SpreadsheetCell {
  index: Int!
  problems: [PayrollHourImportError!]!
  row: PayrollHourImportRow!
  value: String
}
```

**Comment by theorygeek** [comment]
EDIT: Sorry, I just realized that I had a type called `PayrollHourtImportRow` and `PayrollHourImportRow`. The one called `PayrollHourtImportRow` (has a "t" after the word "hour") should have been `PayrollHourImportRowEdge`. (insert face-palm)

I think I fixed all the references in my previous comments.

**Comment by theorygeek** [comment]
I think this is the nail in the coffin for my suggestion, from the [Relay Cursor Connections spec](https://facebook.github.io/relay/graphql/connections.htm#sec-Connection-Types):
> Connection types must be an “Object” as defined in the “Type System” section of the GraphQL Specification.

The Relay modern compiler crashes if you attempt to query a connection that is an interface. ☹️
