### ISSUE TITLE
RFC: Input Object Types v2

### ISSUE THREAD

**Issue by theorygeek** [rmosolgo/graphql-ruby#903]
I'm not really sure the best title for this, but here's what I'm after. I'm trying really hard to have this in my schema:
```ruby
DateRangeInputType = GraphQL::InputObjectType.define do
  name "DateRangeInput"

  input_field :min, !DateType
  input_field :max, !DateType
end
```

I have a similar `DateRangeType` that is an ordinary object type, so that there's a nice harmony between the input object types and normal object types. But what would really make this spectacular is if my code received an instance of `Range` instead of a `Query::Arguments`.

I first tried to do this little monkey-hack:
```ruby
DateRangeInputType.define_singleton_method(:coerce_non_null_input) do |value, ctx|  
  args = super(value, ctx)
  args[:min]..args[:max]
end
```

I think that this hack would work when the value is provided as a variable. But when the value is provided as a literal in the query, it turns out that [`Query::LiteralInput` has its own coercion code](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/query/literal_input.rb#L42) which duplicates some of the [logic in `InputObjectType`](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/input_object_type.rb#L85).

Then I start thinking long and hard about whether I want to monkey-patch `LiteralInput` too, so I figured I'd just raise the question here. I can see a couple of ways of getting at this behavior, but they all require code changes.

#### Option 1 - Overriding input object coercion
This is essentially what I was aiming to do. To accommodate this well, we'd probably add some sort of a `prepare` API onto `InputObjectType`, very similar to how you can specify that option on arguments.

The next step would be to refactor both of those places in code I mentioned above, so that they respect the `prepare` option. Going this route with my example above, it would look like:
```ruby
DateRangeInputType = GraphQL::InputObjectType.define do
  name "DateRangeInput"

  input_field :min, !DateType
  input_field :max, !DateType

  # Your application code will receive the result of this proc, instead of a
  # Query::Arguments object.
  prepare -> (args, ctx) { args[:min]..args[:max] }
end
```

#### Option 2 - Adding a prepare option to the individual fields on an `InputObjectType`
The other place where this kind of work could live is inside of the `prepare` option that we already have today on field arguments. To make this really nice, we would want to extend it so that you could get this behavior when an input object is embedded inside another input object.

In this world, the usage would look a little more complicated, because the work would live on the field that is using the input type, instead of on the input type itself:
```ruby
# On a field
field :someField, SomeType do
  argument :range, DateRangeInputType, prepare: -> (args, ctx) { args[:min]..args[:max] }
end

# Same thing on a nested input object
GraphQL::InputObjectType.define do
  argument :range, DateRangeInputType, prepare: -> (args, ctx) { args[:min]..args[:max] }
end
```

Naturally, it gets pretty cumbersome to put these `prepare` options in every place where the type is consumed. So I think the next thing you'd want is to expand instrumentation so that, in addition to being able to instrument `:field`'s, you could also instrument `:input_field`'s. You could then systematically wire up this prepare behavior across the schema.

It seems like Option 1 would be more desirable. The use case for the `prepare` option on an argument seems closely related to the behavior of the field where it's being used - stuff like specifying dynamic default values for a field. Whereas here, it's really more related to how the input provided by the user is interpreted, regardless of where it's used.

What do you guys think? Figured I'd open it up for discussion before opening a PR, but I'd be glad to do a PR for this if it seems useful.

**Comment by rmosolgo** [comment]
Thanks for the writeup, agreed that Option 1 looks good! It makes sense to me that you'd want to replace the generic `Arguments` instance with some "real" value in a reliable way.

**Comment by psparrow** [comment]
Is this still in the works?

**Comment by rmosolgo** [comment]
I think this is covered by `GraphQL::Schema::InputObject` in `1.8`: 

https://github.com/rmosolgo/graphql-ruby/blob/38871decd8790fa14f0760799489354926c6f405/guides/schema/class_based_api.md#input-object-classes

If you see a missing use case, please reopen this issue or leave a comment!

**Comment by theorygeek** [comment]
I think that 1.8 lets you get an instance of a class that you own now, but how could you get `Range` instead of your `InputObject` subclass?

I think that the `prepare` option can only be applied to _argument_ definitions, but it'd be nice to apply it to _input object_ definitions. Something like:

```ruby
class Types::DateRangeInput < Types::InputObject
  argument :min, Types::DateInput, required: true
  argument :max, Types::DateInput, required: true

  # If you define this method, GraphQL will call it and pass its result into your field resolvers.
  def prepare
    min..max
  end
end
```

I think the framework code would change to something like:
```ruby
# Example from GraphQL::Schema::InputObject. There are a couple of other places in the codebase
# that look basically the same as this:
@arguments = self.class.arguments_class.new(values, context: context, defaults_used: defaults_used)

# Imagine adding this line:
@arguments = @arguments.prepare if @arguments.respond_to?(:prepare)
```

**Comment by Lasvad** [comment]
@theorygeek Hey there, did you ever figure out a way to return the proper class instead of the InputClass?  

I'm passing an entire object through as an argument in my mutation. I've created the Input Object that defines all the arguments for that object but when I end up in the resolver method of the mutation, It would be ideal to already have the proper class instead of the  input object class.

```
mutation{ createTransaction(
   id:"123", 
   job:{
       //entire job here 
   }
```

```
class Inputs::JobInput < Types::BaseInputObject
  argument :id, ID, "id", required: true
  argument :name, String, "name of job", required: false
  argument :domain, String, "domain of job",required: false
```

```
// resolve of mutation
def resolve(id:, job:, ... )
   //job here is "#<Inputs::JobInput:0x00007fbc49d38058>" but would be nice if it was already a Job class

```
