### ISSUE TITLE
Bug tracker integration

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#909]
I think it would be great to add some integrations for common bug trackers (eg Sentry, Bugsnag, Airbrake) which improve the metadata for runtime errors. 

At least, we could add: 

- query string 
- variables 
- ~~context~~ Can we count on the application adding enough context (eg `current_user`)? 

For usage, it could be a simple as: 

```
require "graphql/bugs/bugsnag" 
# or 
require "graphql/bugs/sentry"
```

which imports the code for adding metadata to the right system.

**Comment by mull** [comment]
Has someone attempted something like this already? I'm finding myself getting bug reports from my frontend guys without me having noticed it. Looking specifically at Sentry

**Comment by rmosolgo** [comment]
No, it wasn't picked up during the hack day, so it's waiting for someone to take a try at it :)

**Comment by rmosolgo** [comment]
One of my teammates at GitHub just handled this for our internal bug tracker and it worked really nicely, basically he made a field instrumentation that worked like this: 

```ruby 
def call(obj, args, ctx) 
  @inner_resolve.call(obj, args, ctx)
rescue 
  BugTracker.add_context(graphql_backtrace: ctx.backtrace.inspect)
end 
```

That way, whenever something went wrong, we had the metadata in the bug report. I think something similar could be implemented for the various third-party bug trackers, too.
