### ISSUE TITLE
Build a demo app

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#911]
A few demo apps exist already: 

- https://github.com/rmosolgo/graphql-ruby-demo
- https://github.com/GraphQLAcademy/swapi-graphql-ruby
- https://github.com/gauravtiwari/relay-rails-blog

But many of them are not up-to-date. There are several demos which would be valuable: 

- Rails + Relay Modern: how to use these two together? 
- Rails + Apollo Client: how to use these two together? 
- Rails demo with decent features: for example, an example app with 10+ types and some mutations.

(Are there other demos which would be valuable?)

**Comment by emilebosch** [comment]
We also have this:

https://www.howtographql.com/graphql-ruby/0-introduction/

**Comment by jjoos** [comment]
> Rails + Relay Modern: how to use these two together?
I'm going to try to write this as part of the hack day!

**Comment by emilebosch** [comment]
@jjoos  how is this going?

**Comment by jjoos** [comment]
Had limited time the last couple of days, will reserve some time tomorrow to finish it up!

**Comment by benjaminbarbe** [comment]
https://github.com/MatthieuSegret/graphql-rails-blog

**Comment by tb** [comment]
I have created [northwind-graphql-ruby](https://github.com/tb/northwind-graphql-ruby) for [`How To GraphQL`](https://www.eventbrite.com/e/haxorz-unconference-80-tickets-38492810031#tickets) workshops I have next week. It includes DB seed for Northwind-like db schema, see [erd.pdf](https://github.com/tb/northwind-graphql-ruby/blob/master/erd.pdf)). 

I want people to be able to related the sample code with documentation, yet be productive.
I went with a of [functions](https://github.com/tb/northwind-graphql-ruby/tree/master/app/graphql/functions), also included validation errors and Server-side REST wrapper example.

Here is the workshops initial schema:

Queries

    Types::QueryType = GraphQL::ObjectType.define do
      name "Query"

      field :supplier, function: Functions::FindById.new(Supplier) do
        type Types::SupplierType
      end

      field :allSuppliers, function: Functions::FindAll.new(Supplier) do
        type types[Types::SupplierType]
      end

      field :currencyRates, function: Functions::CurrencyRates.new
    end

Mutations

    Types::MutationType = GraphQL::ObjectType.define do
      name "Mutation"

      field :createSupplier, function: Functions::Create.new(Supplier) do
        type Types::SupplierType
        argument :supplier, !Types::SupplierInputType
      end

      field :updateSupplier, function: Functions::Update.new(Supplier) do
        type Types::SupplierType
        argument :supplier, !Types::SupplierInputType
      end

      field :deleteSupplier, function: Functions::Delete.new(Supplier) do
        type Types::SupplierType
      end
    end

**Comment by eshaiju** [comment]
My sample application based on blog posts http://tech.eshaiju.in/blog/categories/graphql/
https://github.com/eshaiju/graphql-ruby-sample

**Comment by rmosolgo** [comment]
Thanks for sharing your links! I don't have plans to work on this further so I'm closing the issue.
