### ISSUE TITLE
Website improvements

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#912]
It's no secret that I need all the help I can get in this department!

- Improve style / layout?
- Improve search 
  - Better results? 
  - Dedicated, linkable search results page 
  - Could replace handrolled search index with a free hosted plan? (Algolia?)
- Other improvements?

**Comment by emilebosch** [comment]
Im just going to add some inspiration from other sites for the designers.

- http://absinthe-graphql.org
- http://graphene-python.org
- http://graphql.org
- https://www.howtographql.com

Maybe add some logos of companies running graphql, github shoppify, IFTT etc. 

- https://www.shopify.com
- https://ifttt.com
- https://github.com

**Comment by rmosolgo** [comment]
It's ok with me to add company logos, but should we check with those companies before doing so? Or is it ok to post them, since we know it from our research? 🕵️

**Comment by emilebosch** [comment]
We should most definitely ask them beforehand!  But until we put it public, we can use some pseudo logos to make the designs with.

**Comment by cjoudrey** [comment]
> Im just going to add some inspiration from other sites for the designers.

Let's not forget [Sangria](http://sangria-graphql.org/). 😁 I especially like all the examples in the documentation section.

**Comment by rmosolgo** [comment]
It's fine with me to change the website in some way, but i'm going to close this issue as stale.
