### ISSUE TITLE
Invalid (?) enum values permitted

### ISSUE THREAD

**Issue by mull** [rmosolgo/graphql-ruby#913]
We had an invalid enum value slip by in code review which looked something like

```
value('Sick day', nil, value: 'sick_day')
```

Neither graphql-ruby nor Relay Modern complained about it. GraphiQL however rejected it immediately with the following error message:

```
Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "Child Sick" does not.
```

The [docs seem to be vague about it](http://facebook.github.io/graphql/#sec-Enum-Value) but but they [do hint at it](http://facebook.github.io/graphql/#sec-Enums)

The reference JS I _think_ (I'm not familiar with the code) has assertions as well:
- https://github.com/graphql/graphql-js/blob/7ddd8dd44cb7f8a3a9f7a760d5ab76ac91802931/src/utilities/isValidLiteralValue.js
- https://github.com/graphql/graphql-js/blob/7ddd8dd44cb7f8a3a9f7a760d5ab76ac91802931/src/utilities/assertValidName.js

**Comment by rmosolgo** [comment]
Yes, we should totally validate these values during schema build! Thanks for reporting this issue!

**Comment by rmosolgo** [comment]
Here's the `EnumValue` class: 

https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/enum_type.rb#L135-L141

I think we should add a `#name=(new_name)` method which validates the assigned value. If it's invalid, we can raise an error.

**Comment by esjee** [comment]
I'll try fixing this!

**Comment by esjee** [comment]
Hey @mull ! I tried to fix this, let me know if this works for you!

**Comment by mull** [comment]
@esjee thanks! According to the specs this is exactly what would've "saved" us :) Cheers!
