### ISSUE TITLE
[QUESTION] Is there a way to parse objects like the results?

### ISSUE THREAD

**Issue by Jose4gg** [rmosolgo/graphql-ruby#925]
If I have a simple object: { id: 132, name: "Something" }, How can I return a { id: "RELAY_NODE_UUID", name: "Something" }?

**Comment by Willianvdv** [comment]
You have to implement Relay's node identification on your types, [here](http://graphql-ruby.org/relay/object_identification.html) are the docs on how to do this.

Good luck!
