### ISSUE TITLE
Model validations seem to be ignored when doing mutations

### ISSUE THREAD

**Issue by terenceponce** [rmosolgo/graphql-ruby#927]
I'm just getting started on using `graphql-ruby`. Everything seems good so far, but I noticed that my model validations don't seem to be running when creating an object through mutation. Here's the code that I'm working with:

```ruby
# app/models/account.rb
class Account < ApplicationRecord
  enum status: %i[active closed]

  validates :name, :description, presence: true
  validate :ensure_type_is_fulfilled

  def type_name
    self.class.to_s.gsub('Accounts::', '')
  end

  private

  def ensure_type_is_fulfilled
    return true if valid_account_types.include?(type)

    type_passed = type.titleize.sub(' ', '')

    if %w[Cash Checking CreditCard Savings].include?(type_passed)
      self.type = "Accounts::#{type_passed}"
    else
      errors.add(:type, 'must be a valid type.')
    end
  end

  def valid_account_types
    [
      'Accounts::Cash',
      'Accounts::Checking',
      'Accounts::CreditCard',
      'Accounts::Generic',
      'Accounts::Savings'
    ]
  end
end

# app/models/accounts/cash.rb
module Accounts
  class Cash < Account
  end
end

# app/models/accounts/checking.rb
module Accounts
  class Checking < Account
  end
end

# app/models/accounts/credit_card.rb
module Accounts
  class CreditCard < Account
  end
end
```

As you can see, I have an STI model (`Account`) that has various types under it. I also have a validation that makes sure that the `type` is valid.

Here's my mutation class:

```ruby
# app/graphql/types/mutation_type.rb
Types::MutationType = GraphQL::ObjectType.define do
  name "Mutation"

  field :addAccount, Types::AccountType do
    description 'Adds an Account'

    argument :input, Mutations::AccountInputType
    resolve ->(t, args, c) {
      Account.create(args[:input].to_h)
    }
  end
end
```

Here's my GraphQL query:

```graphql
mutation {
  addAccount(input: {name: "Secret Stash", description: "Whatever", type: "Cash"}) {
    name
    description
    status
    type
    id
  }
}
```

And I get this error when executing the query:

```
ActiveRecord::SubclassNotFound (The single-table inheritance mechanism failed to locate the subclass: 'Cash'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite Account.inheritance_column to use another column for that information.):
  
app/graphql/types/mutation_type.rb:9:in `block (3 levels) in <top (required)>'
app/controllers/graphql_controller.rb:13:in `execute'
```

My problem is that when I try to do a mutation, it looks like it's bypassing the validations and going straight to saving. Of course, this means that `ActiveRecord` will raise an error since the `type` field hasn't been changed by my validation method.

Am I missing something here? Where did I go wrong?

**Comment by cipater** [comment]
This is unrelated to graphql-ruby. According to [this](https://github.com/rails/rails/blob/633e9745f8eafb0d1d5523ec761fdee420bcbc91/activerecord/lib/active_record/inheritance.rb#L50), you can't instantiate an AR object with an invalid type attribute as it will immediately try to initialize an instance of the specified subclass (`Cash` in your case)

Try this in the console: `Account.new(type: 'Cash')` ... you should receive the same `SubclassNotFound` exception.

You need to validate the type attribute prior to instantiating Account, or, if you want to keep the validation as-is, you'll have to instantiate Account without any attributes first:

```ruby
resolve ->(t, args, c) {
  account = Account.new
  account.update(args[:input].to_h)
}
```

**Comment by terenceponce** [comment]
Woops. That was a rookie mistake on my part. Thanks for clearing that up for me.
