### ISSUE TITLE
Using an interface from another file and making changes causes NameError (uninitialized constant...):

### ISSUE THREAD

**Issue by AndyKriger** [rmosolgo/graphql-ruby#929]
I am trying to use an interface that is in a different file from the type using it. 

Queries work when the server is started as long as I make no changes to any of the GraphQL-related files. As soon as I do, the next query in GraphiQL will spin for a while and then the server logs will show a ```NameError (uninitialized constant Types::MyInterface)```. Even if the change is just a comment, I'll see this error. It doesn't matter if the change is in the schema file, the type files, or the interface file. 

Once the error shows up, the server must be restarted before it will work again. If I put the interface in the same file as the type, I don't have this problem. When there's no interface at all, I can make changes till the cows come home without an error.

I think the following code samples are a minimal set that shows the problem without introducing extraneous complexity.

```ruby
# my_type.rb
require './app/graphql/types/myinterface_type'
# i've also tried require_relative 'myinterface_type'

Types::MyType = GraphQL::ObjectType.define do
  name 'MyType'
  interfaces [Types::MyInterface]
  field :tf, types.String do
    resolve -> (_,_,_) { 'foo' }
  end
end
```

```ruby
# myinterface_type.rb
Types::MyInterface = GraphQL::InterfaceType.define do
  name 'MyInterface'
  field :if, types.String do
    resolve ->(_,_,_) { 'bar' }
  end
end
```

```ruby
# query_type.rb
Types::QueryType = GraphQL::ObjectType.define do
  name "Query"

  field :mine do
    type Types::MyType
    resolve ->(_,_,_) { Hash.new }
  end
end
```

```ruby
# my_schema.rb
MySchema = GraphQL::Schema.define do
  query(Types::QueryType)

  # because we are using an interface to represent metadata, a resolve_type method is required by graphql-ruby
  resolve_type ->(_, _, _) do
    # however, it never seems to be invoked since we're not using interfaces to distinguish implementing types
  end
end
```

**Comment by rmosolgo** [comment]
Sorry to hear it 😖 

there are some other known issues with Rails autoloading (https://github.com/rmosolgo/graphql-ruby/issues/651), the only solution I can think of is to redo the schema definition from scratch to use classes, as Rails expects. 

So, I'm starting some experiments here and in GitHub to find another way!

**Comment by AndyKriger** [comment]
I'm only at the start of this schema so getting it setup correctly now is easy. Is there something in the docs that shows what you mean by "redo the schema definition from scratch to use classes"?

**Comment by rmosolgo** [comment]
Yes, that's what I mean. The API doesn't exist yet 😖

**Comment by lightwave** [comment]
I want to add that as soon as I define an interface (in the same file), I'd get a LoadError.

```
LoadError (Unable to autoload constant Types::MutationType, expected root_dir/app/graphql/types/mutation_type.rb to define it):
```

```ruby
AddressInterface = GraphQL::InterfaceType.define do
  name "AddressInterface"
  field :address1, types.String
  field :address2, types.String
  field :city, types.String
  field :province, types.String
  field :postalCode, types.String, property: :postal_code
end

Types::ContactType = GraphQL::ObjectType.define do
  name "Contact"

  interfaces [AddressInterface]

  field :id, !types.ID
  field :name, !types.String
  field :phone, types.String
  field :fax, types.String
  field :email, types.String
end

```

**Comment by rmosolgo** [comment]
> redo the schema definition from scratch to use classes, as Rails expects

This is "done", please reopen this if someone else finds this issue in a class-based schema!

**Comment by EAdeveloper** [comment]
NameError (uninitialized constant Types::AuthProviderEmailInput):derEmailInput):
