### ISSUE TITLE
Relay connection support for Mongoid

### ISSUE THREAD

**Issue by BranLiang** [rmosolgo/graphql-ruby#938]
Self applied a simple connection for mongoid. It would be really nice to see support from the community and integrate relay connection support for mongoid.
```ruby
# /initializer/mongo_relay.rb
GraphQL::Relay::BaseConnection.register_connection_implementation(Mongoid::Relations::Targets::Enumerable, Connections::MongoConnection)

```
```ruby
class Connections::MongoConnection < GraphQL::Relay::BaseConnection
  # derive a cursor from `item`
  def cursor_from_node(item)
    encode(item.id.to_str)
  end

  private

  # apply `#first` & `#last` to limit results
  def paged_nodes
    return @paged_nodes if defined? @paged_nodes
    # binding.pry
    @paged_nodes = sliced_nodes
    @paged_nodes = if first
                     @paged_nodes.limit(first)
                   elsif last
                     @paged_nodes.desc(:id).limit(last)
                   else
                     @paged_nodes.limit(10)
                   end
  end

  # apply cursor, order, filters, etc
  # to get a subset of matching objects
  def sliced_nodes
    return @sliced_nodes if defined? @sliced_nodes

    @sliced_nodes = nodes
    @sliced_nodes = @sliced_nodes.where(:id.gt => decode(after)) if after
    @sliced_nodes = @sliced_nodes.where(:id.lt => decode(before)) if before
  end
end
```

**Comment by rmosolgo** [comment]
Hi! Thanks for sharing the code. I'm sure many people will find it very useful!

How about this: if you (or someone else) can add Mongoid to the projects, including tests, I'll maintain it 😊

**Comment by BranLiang** [comment]
@rmosolgo I will see what I can do and hope someone could help me with that😊

**Comment by dorthwein** [comment]
Is there clarity or a check list on what needs to be implemented with this to make it efficient with Mongoid?  If there was clarity on what needed to be implemented we maybe able to help some.

**Comment by dblock** [comment]
Looks like support in https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/relay/mongo_relation_connection.rb works well for Mongoid::Criteria and relations in Mongoid work no different than a criteria. This seems to work for me (mongoid 7):

```ruby
GraphQL::Relay::BaseConnection.register_connection_implementation(
  Mongoid::Association::Referenced::HasMany::Targets::Enumerable, GraphQL::Relay::MongoRelationConnection
)
```

For mongoid 6 it should be the same.

```ruby
GraphQL::Relay::BaseConnection.register_connection_implementation(Mongoid::Relations::Targets::Enumerable, GraphQL::Relay::MongoRelationConnection)
```

I think the above can be committed to graphql-ruby with tests and some mongoid version checks. Anything I am missing? I can give it a shot.

https://github.com/33-minutes/33-minutes-server/commit/f0bd7df9dd0f4311344557dce4e673e28c84f1d1 includes code and tests.

**Comment by rmosolgo** [comment]
:+1: Definitely happy to support it as long as we can run the right tests!

**Comment by rmosolgo** [comment]
Feel free to add support for relations, I'll close this since we now have basic mongoid support.

**Comment by dblock** [comment]
Implemented in https://github.com/rmosolgo/graphql-ruby/pull/1754.
