### ISSUE TITLE
The error handling documentation (http://graphql-ruby.org/queries/error_handling) is not accessible from guides page (http://graphql-ruby.org/guides)

### ISSUE THREAD

**Issue by cebartling** [rmosolgo/graphql-ruby#943]
Minor nit about linking the error handling page (http://graphql-ruby.org/queries/error_handling) into the guides table of contents page (http://graphql-ruby.org/guides). I had to do a Google search to find the error handling page.

**Comment by Willianvdv** [comment]
I think this recently got fixed in #930

**Comment by cebartling** [comment]
@Willianvdv Sure looks like it! Closing this issue. Thanks for bringing this to my attention.

**Comment by rmosolgo** [comment]
Oops, at first I thought I just had to update the website, but then I saw the `section:` should be `Queries`, so I updated it in 70f0ffd9ae1215f669f226bd3982f44b9599f1c1 and repushed it!

**Comment by cebartling** [comment]
@rmosolgo and @Willianvdv Now it's showing up! Thanks for the quick turnaround on this.
