### ISSUE TITLE
(Idea) Append value of connection max_page_size to connection description

### ISSUE THREAD

**Issue by khamusa** [rmosolgo/graphql-ruby#950]
I often find myself manually writing the max page size for connections on the **description** of the connection itself, in oder to document the actual limit for the developers consuming the API. It's not that much of a job if we just use the default config (in that case we can just document once that every connection has a limited page size), but it becomes repetitive and error prone once we start customizing the page size for different fields.

So my suggestion is to automatically append the information of the used/applied max_page_size to the description of the connection fields.

I guess I could try working on this if you think it is an useful contribution

**Comment by Willianvdv** [comment]
```ruby
MySchema = GraphQL::Schema.define do
  default_max_page_size 100
end
```
Is this the setting you're looking for?

**Comment by khamusa** [comment]
@Willianvdv I guess I was quite tired when I wrote the contents of this issue. I just edited it trying to be clear. The idea is to inform the used page size on connection fields by using the description text of the field automatically.

**Comment by rmosolgo** [comment]
I think an approach like this will work. When building the schema, identify the fields with a max page size, and if it's present, add it to the description. 

What do you think, want to give it a try?

```ruby 
module MaxPageSizeDocumenter 
  def self.instrument(type, field)
    if field.connection_max_page_size 
      new_description = field.description + " (max page size: #{field.connection_max_page_size})"
      field.redefine(description: new_description)
    else 
      field 
    end 
  end 
end 


MySchema = GraphQL::Schema.define do 
  # ...
  instrument(:field, MaxPageSizeDocumenter) 
end 
```

**Comment by rmosolgo** [comment]
I hope you found something that works for you!
