### ISSUE TITLE
Re-stringify a GraphQL::Query 

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#952]
Sometimes you have a really complicated query with lots of fragments and variables, but you want to debug it in graphiql. 

It would be nice to get a "simplified" query somehow, where: 

- fragments are flattened 
- variable values are added as defaults to the query string 

That way, you could copy-paste into graphiql and poke around to debug.

**Comment by xuorig** [comment]
working on this!

**Comment by Willianvdv** [comment]
It would also be extremely useful to add this query to traces we send to monitoring systems. We use NewRelic, and currently, it's too hard to figure out what the exact query was executed for a given transaction. Adding an actual query makes reproducing a transaction a walk in the park. I'm not sure how to deal with mutations and inlined variable values, these values contain private data we don't want to send to 3rd parties. 

If metadata of the query execution could be included when generating the query, something like [sangria-slowlog ](https://github.com/sangria-graphql/sangria-slowlog) can be built. 
```graphql
# [Execution Metrics] duration: 12362ms, validation: 0ms, reducers: 0ms
#
# $id = "1000"
query Test($id: String!) {
  # [Query] count: 1, time: 2ms
  #
  # $id = "1000"
  human(id: $id) {
    # [Human] count: 1, time: 0ms
    name

    # [Human] count: 1, time: 11916ms
    appearsIn

    # [Human] count: 1, time: 358ms
    friends {
      # [Droid] count: 2, min: 0ms, max: 0ms, mean: 0ms, p75: 0ms, p95: 0ms, p99: 0ms
      # [Human] count: 2, min: 0ms, max: 0ms, mean: 0ms, p75: 0ms, p95: 0ms, p99: 0ms
      name
    }
  }
}
```
@xuorig if you need help building this, please let us know!

**Comment by rmosolgo** [comment]
That's a cool idea too 😎

**Comment by rmosolgo** [comment]
With class-based printers, you can now make custom printers for this.
