### ISSUE TITLE
Implement real hasNextPage/hasPreviousPage values on an opt-in basis

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#955]
We should allow people to break Relay spec and get `hasNextPage` or `hasPrevPage` values regardless of which direction they're paginating. 

The spec's behavior is often reported as a bug, see #656 for example. 

In GitHub, we've done this for our custom connections but we need it for the built-in ones too.

**Comment by eapache** [comment]
It's not breaking the spec anymore: https://github.com/facebook/relay/pull/2079 got merged.

**Comment by rmosolgo** [comment]
:clap: :clap: !!

**Comment by volkanunsal** [comment]
I noticed today that `hasPreviousPage` returns false on the final page in 1.6.7. Is this behavior related to this issue or the one referenced above? I can create another issue for it, if not.

**Comment by rmosolgo** [comment]
Sounds like a different bug, please do open an issue!

**Comment by rmosolgo** [comment]
Implemented in #960
