### ISSUE TITLE
Navigation: hasPreviousPage returns false on the final page, and perhaps startCursor is incorrect?

### ISSUE THREAD

**Issue by volkanunsal** [rmosolgo/graphql-ruby#958]
I noticed today that `hasPreviousPage` returns false on the final page in 1.6.7. 

To replicate, create a connection and navigate it using the `after` property. The `pageInfo.hasPreviousPage` indicates the correct result until the final page, where it returns false.

Another possibly related issue is when you are on the final page, if you set the `after` property to null and set the `before` property to `startCursor` from `pageInfo`, the server sends the first page. 

```js
updateCursor({ before: startCursor, after: null });
```

Expected behavior is the server would send the previous page.

UPDATE: This doesn't happen only on the last page. I confirmed that using the values `before: something` and `after: null` on any page to go back to the previous page always returns the first page from the server.

Example query:

```graphql
query getResources(
  $q: String
  $before: String
  $after: String
  $theGeom: String
) {
  me {
    developments(
      first: 20
      q: $q
      before: $before
      after: $after
      theGeom: $theGeom
    ) {
      edges {
        cursor
        node {
          id
          name
        }
      }
      pageInfo {
        startCursor
        endCursor
        hasNextPage
        hasPreviousPage
      }
    }
  }
}
```

**Comment by bessey** [comment]
Its not a bug, its in the Relay spec, but 1.7 [introduced a way to override it](https://github.com/rmosolgo/graphql-ruby/blob/master/CHANGELOG.md#new-features-2) to behave how a normal person might expect

**Comment by rmosolgo** [comment]
Yep, thanks @bessey. Here's the corresponding change to the Relay spec: https://github.com/facebook/relay/pull/2079

Previously, it was _required_ to return `false` in this case. Now, it's permitted to return either one. So you can use the flag linked above to return `true` in this case instead.
