### ISSUE TITLE
graphql-ruby-client needs to ability to expose `__typename` on persisted queries

### ISSUE THREAD

**Issue by kevinjalbert** [rmosolgo/graphql-ruby#961]
I encountered this using `graphql-ruby-client` version 1.0.2.

When using the `sync` command the client ends up saving the GraphQL queries as expected. The main problem is that in my specific React application I'm using [react-apollo](https://github.com/apollographql/react-apollo) with the [`addTypename` option](http://dev.apollodata.com/core/apollo-client-api.html#ApolloClient.constructor) enabled in the `ApolloClient`. This means that I can write my queries without any `__typename` and they get added automatically. The `__typename` is needed for Apollo to cache entities correctly.

Seems like the `graphql-ruby-client` needs an option to automatically add the `__typename` fields before sending the queries to be persisted. On the JS side I saw that this exists for [apollographql/persistgraphql](https://github.com/apollographql/persistgraphql#build-tool-semantics). I imagine that we could implement a similar interface on the CLI?

In my digging it seems like we'd have to add the fields somewhere [here](https://github.com/rmosolgo/graphql-ruby-client/blob/d05fb3bcd849ad76566f3f004698b7a4042b24f3/sync/prepareProject.js#L42-L61)? The AST visitor could probably follow some similar implementation as to how it's done in [`apollo-client`](https://github.com/apollographql/apollo-client/blob/fec6457746b1cb63c759f128349e66499328ae43/src/queries/queryTransform.ts#L22-L56)?

**Comment by rmosolgo** [comment]
:+1: Totally agree that we should add an `--add-typename` option to the `sync` task. Yep, I think we could add logic to that visitor in `prepareProject` to also add typename to selection sets. 

Are you interested in taking a crack at it? If so, go for it, otherwise, I'll take look this evening or tomorrow morning :)

**Comment by kevinjalbert** [comment]
I am interested in giving it a shot! Might not get it done as fast as you though ;)

I'm not in rush currently for this, so I could try and implement it over the next few days? I might reach out to you for some help if I get stuck (here or slack).

**Comment by rmosolgo** [comment]
:+1: that sounds great, feel free to hit me up here or there!

**Comment by rmosolgo** [comment]
BTW, I just finished merging `graphql-ruby-client` into this projects, so please make your changes here! https://github.com/rmosolgo/graphql-ruby-client is a dead end now 😬
