### ISSUE TITLE
Error with fallback authorization + introspection

### ISSUE THREAD

**Issue by medlefsen** [rmosolgo/graphql-ruby#966]
In the pro gem if fallback authorization is used, then any queries that includes the 'inputFields' field on the Type introspection type fail. Here is an isolated example: [graphql-issue.zip](https://github.com/rmosolgo/graphql-ruby/files/1315559/graphql-issue.zip).

The issue seems to be that `GraphQL::Pro::Access::Instrumentation::AuthorizedResolve::AllowedList#each` assumes that the value will never be nil, but `GraphQL::Introspection::InputFieldsField` returns nil if the type kind doesn't have input fields. I'm not sure which should be thought of as the bug.

Locally we've monkey patched `AllowedList#each` to just return if the list is nil. That fixes it although it does still result in the nil being turned into an empty array.

**Comment by rmosolgo** [comment]
Thanks for the details and the reproducing case! I'm glad to hear that you found a workaround for the time being. 

I'll take a close look later today and follow up here.

**Comment by rmosolgo** [comment]
Thanks again for your debugging, I released 1.5.7 with a fix. I've made it return `nil` when the input is `nil`, this seems in keeping with the [`__Type.inputFields` specification](https://facebook.github.io/graphql/#sec-Schema-Introspection)  and normal nullable list type behavior. 

Please let me know if you have any more trouble with this!

**Comment by medlefsen** [comment]
Thanks!
