### ISSUE TITLE
[HELP] How to create business logic validations.

### ISSUE THREAD

**Issue by raphaelcuba** [rmosolgo/graphql-ruby#970]
First of all, sorry if isn't the right place to put this question.

I'm using right now graphql (1.6.7) in my rails project and I need to put some business logic validations in my mutations.

Have some kind of best practices to resolve this cases? The doc isn't help me to clarify how I can resolve this point common in most applications.

First I'm thinking to create a type to use in all mutations response and using this technic.

I've tried to use this way below, but i will lost the possibility to define my custom response structure.

```ruby
  field :createCourse, Types::CourseType do
    description 'Creates a new course'

    argument :title, !types.String, prepare: ->(title, ctx) {
      # Forcing it. Maybe can be here my business logic validations.
      GraphQL::ExecutionError.new("Title empty")
    }

    resolve ->(obj, args, ctx) {
      # Forcing it. Maybe can be here my business logic validations.
      GraphQL::ExecutionError.new("Testing it")

      course = Course.create(title: args['title'])
      course
    }
  end
```

```json
# Response
{
  "data": {
    "createCourse": null
  },
  "errors": [
    {
      "message": "Title empty",
      "locations": [
        {
          "line": 2,
          "column": 16
        }
      ],
      "path": [
        "createCourse"
      ]
    }
  ]
}
```

An idea of what i'm thinking to returns to my clients if any data is wrong:
```json
{
  "data": {
    "createCourse": null
  },
  "errors": [
    {
      "attribute": "title",
      "messages": ["Title empty", "Title too short."]
    }
    // other validations...
  ]
}
```

Thanks!

**Comment by Willianvdv** [comment]
Hello @raphaelcuba! Did you manage to solve this problem? Or do you still need some help?

**Comment by raphaelcuba** [comment]
Hi, @Willianvdv, I still need help with this problem. Can you help me?

**Comment by roupen** [comment]
I am looking for a good solution to handle something similar. In my case my desired return structure on errors is something like this:

```
{
  "data": nil,
  "errors": [
    {
      "type": "validation",
      "message": "Validation failed",
      "fields": {
        "email": "is not unique",
        "password": "must be at least 8 characters"
      }
    }
  ]
}
```

In an ideal world I would think to be able to make a subclass to ExecutionError where I can pass in things like "type" and "fields" and then be able to specify an error rendering method to graphql. This method would be responsible for assembling the error structure which would then be pushed onto the "errors" array in the response.

**Comment by AlexanderMint** [comment]
My desired return structure on errors:

```
{
  "data": nil,
  "errors": [
    {
      code: 20001,
      message: "Text",
      type: "validation",
      fields: [:firstName, :lastName],
      info: "http://example.com/docs/errors/20001"
    },
    {
      code: 20002,
      message: "Text 2",
      info: "http://example.com/docs/errors/20002"
    }
  ]
}

```

**Comment by roupen** [comment]
In case anyone finds this useful, I ended up accomplishing this with relatively little code. I just subclassed ExecutionError and added the attrs I needed. Then I overrode the to_h class. In my custom resolver, I throw the new type of error whenever my validation fails. It's not extensively tested but seems to work for me so far. Here's the new class:

```
module GraphQL
  class DetailedExecutionError < ExecutionError
    attr_accessor :type, :fields

    def initialize(message, ast_node: nil, type: nil, fields: nil)
      self.type = type
      self.fields = fields
      super(message, ast_node: ast_node)
    end

    def to_h
      if type
        {
          type: type,
          message: message,
          fields: fields
        }
      else
        super
      end
    end
  end
end
```

**Comment by raphaelcuba** [comment]
@roupen to me your solution is perfect! I was thinking something similar to that. I'll try to use your approach with custom exceptions. In principle, we can close this issue.

Thanks so much!
