### ISSUE TITLE
Any style guide for contributions?

### ISSUE THREAD

**Issue by aviscasillas** [rmosolgo/graphql-ruby#98]
Hi there!

I was wondering if you were following some style guide for coding, or kind of best practices.
What do you think about boost styling based on the [bbatsov/ruby-style-guide](https://github.com/bbatsov/ruby-style-guide)?

Thanks!

**Comment by rmosolgo** [comment]
Sorry, not yet! I was thinking I should do this. I'll to add a `.rubocop.yml` soon. In the mean time, as long as the test coverage is good, we're free to change code pretty freely :)

**Comment by aviscasillas** [comment]
Well, I've just started playing with the code to see how is it made, and I think that by the way I could take advantage of that to make some styling refactors. IMHO even you are not forcing it, If you have the idea in mind, I think that would not be bad to make some refactors to have as more code in the style as better  :blush: 

Just as an example, we could move thinks like this:
```ruby
module GraphQL::DefinitionHelpers::DefinedByConfig
  # some code here
end
```
to this:
```ruby
module GraphQL
  module DefinitionHelpers
    module DefinedByConfig
      # some code here
    end
  end
end
```

This way we could also remove empty/redundant definitions like that: https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/definition_helpers.rb#L1-L4

What do you think?

**Comment by rmosolgo** [comment]
Yes, that particular fix would be great! When I started this project, I was using `autoload` :grimacing: Those are left-over from the old way.

**Comment by aviscasillas** [comment]
:+1: I will do it then! :wink:
