### ISSUE TITLE
Extended Field DSL is not available within Function

### ISSUE THREAD

**Issue by RabidFire** [rmosolgo/graphql-ruby#980]
As written [in the docs](http://www.rubydoc.info/gems/graphql/1.7.2/GraphQL/Function), a `GraphQL::Function` is a _reusable container for field logic_. However, extended Field DSL (specified using `GraphQL::Field.accepts_definitions(...)`) is not available within Functions.

### Example

```ruby
# Extend the Field DSL to accept :custom_metadata_key
GraphQL::Field.accepts_definitions(
  custom_metadata_key: GraphQL::Define.assign_metadata_key(:custom_metadata_key)
)
```

```ruby
# This works
field :myField do
  custom_metadata_key 'test'
end
```

```ruby
# This does not work
class MyFunction < GraphQL::Function
  custom_metadata_key: 'test'
end

field :myField, function: MyFunction.new
```

The problem is that `GraphQL::Function` is quite different from `GraphQL::Field`, `GraphQL::ObjectType`, etc, in that they are not _defined_ (and therefore does not include the `GraphQL::Define::InstanceDefinable` module) and are instead subclassed.

### Proposed Solutions

1. (Workaround) Define a class method within the Function.
2. Hook into `Field.accepts_definitions` to automatically `define_singleton_method` on `GraphQL::Function`.
3. (Ideal) Wait for https://github.com/rmosolgo/graphql-ruby/issues/820 - perhaps we won't need Functions if we can simply inherit from `GraphQL::Field` to define reusable fields.

**Comment by rmosolgo** [comment]
Function is out, Resolver is in, and Resolver should have all the API elements of normal class-based schema definition.
