### ISSUE TITLE
Custom error messages for scalar's input coercion

### ISSUE THREAD

**Issue by swalkinshaw** [rmosolgo/graphql-ruby#981]
Currently there's no way to specify a custom error message from a scalar type's `coerce_input` method and have it returned in the response.

The closest you can get is using `ctx.add_error` but it only appends to the existing default ones.

Use case: we want to provide better feedback for invalid Global IDs. The default is:

```json
    {
      "message": "Argument 'id' on InputObject 'FooInput' has an invalid value. Expected type 'ID!'.",
      "locations": [
        {
          "line": 2,
          "column": 26
        }
      ],
      "fields": [
        "mutation",
        "fooDelete",
        "input",
        "id"
      ]
    }
```

Ideally we could return or raise an `ExecutionError`. Is there a reason why this isn't possible? Or just not implemented yet?

cc @eapache

**Comment by rmosolgo** [comment]
Sounds like we just haven't needed it, sounds like a nice improvement to me!

**Comment by swalkinshaw** [comment]
🤔  since this is part of static validation, and how the error is added, it doesn't seem like raising an `ExecutionError` is really possible without a lot of changes.

My naive first thought is scalar's accepting a specific definition like `invalid_literal_error_message`?

Otherwise we could add a `rescue` around the call to `valid_literal?` and assume that its purpose is for an error message.

**Comment by eapache** [comment]
Would it make sense to do kind of like we have internally: create a specific `GraphQL::CoercionError` exception that scalars can raise and then rescue that in `ArgumentLiteralsAreCompatible`? That would avoid accidentally rescuing away real bugs but would still be an easy way to provide custom messages.

**Comment by swalkinshaw** [comment]
That's probably a better improvement over just raising `ExecutionError`. Also a better name semantically. `ExecutionError` seems like it should be raised during the execute phase?

**Comment by swalkinshaw** [comment]
Created https://github.com/rmosolgo/graphql-ruby/pull/988 to implement the solution of raising + rescuing.
