### ISSUE TITLE
Resolver not wrapping attribute

### ISSUE THREAD

**Issue by camertron** [rmosolgo/graphql-ruby#983]
Hey @rmosolgo! First of all, thanks for a fantastic gem! I have what I think might be a bug, but I'm not completely sure. I'm working with these two types (note that `day_x_experience` is a field on another type called `CurrentUser`):

```ruby
GameRecommendationsType = GraphQL::ObjectType.define do
  name 'GameRecommendationsType'
  # ... a bunch of other fields
  field :games, !types[!GameType]  # defined elsewhere
end

DayXExperienceType = GraphQL::ObjectType.define do
  name 'DayXExperienceType'
  # ... a bunch of other fields ...
  field :game_recommendations, !GameRecommendationsType do
    resolve GameRecommendationsResolver
  end
end
```

Here are the resolvers:

```ruby
class DayXExperienceResolver
  def game_recommendations
    { games: Game.where(...), ... }
  end
end

class GameRecommendationsResolver
  def games
    object[:games]
  end
end
```

I'm then trying to run a query similar to this:

```graphql
query {
  current_user {
    game_recommendations {
      games {
        # ... a bunch of fields
      }
    }
  }
}
```

What appears to happen is that the `GameRecommendationsResolver` gets instantiated with an instance of `DayXExperienceResolver` instead of the hash from `DayXExperienceResolver#game_recommendations` I'm expecting. As a result, Ruby raises a `NoMethodError`. I have to do this in order to get things to work:

```ruby
DayXExperienceType = GraphQL::ObjectType.define do
  name 'DayXExperienceType'
  field :game_recommendations, !GameRecommendationsType do
    resolve -> (obj, args, ctx) do
      GameRecommendationsResolver.new(
        obj.public_send(ctx.field.name), args, ctx
      )
    end
  end
end
```

Is this expected behavior? I was expecting graphql-ruby to call the `game_recommendations` method on `DayXExperienceResolver` and wrap it in an instance of `GameRecommendationsResolver`.

graphql-ruby version: 1.5.10 (we're in the process of upgrading)

**Comment by rmosolgo** [comment]
> expecting graphql-ruby to call the `game_recommendations` method 

Resolvers are functions, so only the `.call(obj, args, ctx)` method is called by graphql-ruby. (This is duck-typing a Proc.) 

Here's a way you could adapt the example above: 

```ruby 
GameRecommendationsType = GraphQL::ObjectType.define do
  name 'GameRecommendationsType'
  # ... a bunch of other fields
  field :games, !types[!GameType] , resolve: GameRecommendationsResolver
end

DayXExperienceType = GraphQL::ObjectType.define do
  name 'DayXExperienceType'
  # ... a bunch of other fields ...
  field :game_recommendations, !GameRecommendationsType do
    resolve GameRecommendationsResolver
  end
end


class DayXExperienceResolver
  def self.call(obj, args, ctx)
    { games: Game.where(...), ... }
  end
end

class GameRecommendationsResolver
  def self.call(object, args, ctx)
    object[:games]
  end
end
```

If you don't find a good solution, feel free to reopen this issue with the specific error message and stack trace that you get!

**Comment by camertron** [comment]
Awesome, thanks @rmosolgo!
