### ISSUE TITLE
How can I restrict visibility of a field to the owner of a resource?

### ISSUE THREAD

**Issue by Mihail-K** [rmosolgo/graphql-ruby#995]
How would I go about restricting certain fields based on whether a user owns a particular resource?
For example, users shouldn't be able to see each other's emails fields, however they should have access to their own email field.

In essence, I'd like to be able to do something like this:
```ruby
type 'User'

field :email do
  visible -> (context) { context[:current_user] == this_object }
end
```

I've not found a good way to do this, mostly because resolution happens after filtering, which means that even if I add a filter (and extend the DSL to add the `visible` attribute), I don't have the object to compare with.

**Comment by Mihail-K** [comment]
After yet more messing around, I've found a way to do it by messing with `resolve`.
However, it feels like a bit of a hack to me:

```ruby
resolve lambda { |obj, args, ctx|
  resolved = User.find(args['id'])
  current_user = ctx[:current_user]
  exec_context = Struct.new(:context, :current_user, :object).new(ctx, current_user, resolved)
  ctx.irep_node.typed_children.each_value do |children|
    children.delete_if do |_, child|
      child.definition.metadata[:visible] && !exec_context.instance_exec(&child.definition.metadata[:visible])
    end
  end
  resolved
}
```

I suppose I can extract this logic elsewhere, but I'm not sure modifying the query like this is good practice.

**Comment by Mihail-K** [comment]
I think I've found a was that doesn't seem too bad.
I'll leave it here for others to review, and potentially use in the future.

```ruby
module FieldVisibilityInstrumentation
  def self.instrument(_, field)
    return field unless field.metadata[:visible]
    old_resolve_proc = field.resolve_proc
    new_resolve_proc = lambda do |object, args, ctx|
      current_user = ctx[:current_user]
      exec_context = Struct.new(:context, :current_user, :object).new(ctx, current_user, object)
      exec_context.instance_exec(&field.metadata[:visible]) ? old_resolve_proc.call(object, args, ctx) : ctx.skip
    end

    field.redefine do
      resolve(new_resolve_proc)
    end
  end
end
```

**Comment by rmosolgo** [comment]
That looks good! I thing https://github.com/exAspArk/graphql-guard works roughly the same way.
