### ISSUE TITLE
add option to make autogenerated mutation field return type to be non null

### ISSUE THREAD

**Issue by gniquil** [rmosolgo/graphql-ruby#998]
Are there any issues with making the return type of a generated relay mutation field non-null (or at least provide an option to do this)? Currently in my front end code, I alway have to check whether the mutation itself is null, regardless whether the mutation is successful or not. 

To give you a bit of context, I am using apollo-codegen to automatically introspect the schema, and with it I can generate typescript definitions for my front end queries. However, the queries generated types, are always wrapped in something like this `addUserMutation | null`. This is somewhat annoying as it forces null checks for all my mutations, even though there is no reason that this is null (or please correct me if I am wrong). I can imagine when mutation fails, the types of the returned fields of the generated mutation type should be nullable, but not the mutation field itself.

**Comment by rmosolgo** [comment]
Hi! that's a nice suggestion. I don't have the bandwidth right now to do it myself, but a PR for that behavior would be very welcome. 

Here's where mutations generate the field for `Mutation` type: 

https://github.com/rmosolgo/graphql-ruby/blob/758782cf1a9346cff3f6feb0552f216618860872/lib/graphql/relay/mutation.rb#L132-L144

You can see how the `type` is populated by `mutation.return_type`.  So, you here's that method: 

https://github.com/rmosolgo/graphql-ruby/blob/758782cf1a9346cff3f6feb0552f216618860872/lib/graphql/relay/mutation.rb#L150-L165

Perhaps you could modify that method to call `.to_non_null_type` on the return value when a certain flag is set. 

I could imagine either or both of: 

- A global setting for the default (currently `false`), like `GraphQL::Relay::Mutation.non_null_return_types = true` 
- A local setting to override the default, like `Mutation.define { ... non_null_return_type true }`

If someone wants to give it a try, I'm happy to help out along the way!

**Comment by rmosolgo** [comment]
This is possible since #1406 in class-based mutations
